### ISSUE TITLE
Smartphone optimized interface

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#10]
Currently the interface is optimized for tablets. As this app may also be used on smartphones with other size constraints on GUI elements there is the need to design a tweaked user interface adapted to smaller screens.

This is a meta-issue to coordinate this effort.

The following screenshot shows a problem on small screens for the identify window.

![screenshot_2015-03-31-14-15-20](https://cloud.githubusercontent.com/assets/588407/6920193/57d8f220-d7bd-11e4-9278-3ac2a16efe54.png)

Proposal:
Disable the "follow current" button and use screen space 50/50 for map identify results.

**Comment by CATERBN** [comment]
I agree with this proposal. I got some problems on my smartphone after identifying feature and navigate between selected features. At this point i have only sected features no other elements. Going back withe the navigation buttons i came to a 0/0 and get au blank screen. I need to use the smartphone back button that bring me to the original view of the projetc, losing the position and zoom i did in the map before selection.

**Comment by andrerjesus** [comment]
On my S6 I can't even see the information tab... 
I totally agree with a adaptive interface

**Comment by m-kuhn** [comment]
@andrerjesus long press a feature to open the information tab.

**Comment by andrerjesus** [comment]
Oh, I feel.. dumb =]
Thank you!

But be able to rotate de screen really would bump the user experience

**Comment by rduivenvoorde** [comment]
Another example:

![screenshot_2015-12-04-12-41-59](https://cloud.githubusercontent.com/assets/731673/11589133/4700d602-9a86-11e5-9f31-754ae2f83077.png)

QField on a OnePlus One. 

As you can see the icons seem very small?
In the Information Tab, maybe the < and > button could be hidden when just one features is selected?
Or maybe could be put on the bottom? (and hidden when just one is selected?)
Agree on hiding the gps button. Maybe also the edit button? IF you want to edit: longtouch on a field could trigger that? Or ask if you want to start editing?
