### ISSUE TITLE
Unprecise selection

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#100]
When selecting a line feature, sometimes lines which are not closeby are selected as well.

QField version 0.9.1
Shapefile

**Comment by aleperlier** [comment]
Je relève un problème concernant l'affichage des thèmes de cartes:
lors du choix du thème du premier thème, rien ne se passe.
Si l'on resélectionne un thème (car rien ne s'est passé) il affiche le thème sélectionné précédemment.
En clair, il y a un décalage entre le thème affiché et le thème demandé avec le thème choisi précédemment.
