### ISSUE TITLE
No list of layers visible and fixed rounding issue persists on Samsung Galaxy tab A Android 6.0.1

### ISSUE THREAD

**Issue by etiennethomassen** [opengisch/QField#102]
The layer list on the left does not show any of the layers in the project (tried several) on my Samsung Galaxy Tab A with Android 6. The rounding issue in #60 returns on this device. On Fairphone 2 with Android 5.1 everything works fine (can see layer names and rounding is ok)

### Reproduction Steps:

1. Open project and layer menu

### Expected behavior:

Visible layer list and rounded labels

**QField version:** 0.8.8 on Samsung Galaxy Tab
**QField version:** 0.9.1 on Fairphone (no issues, just noticed the difference)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Don't know (just got tablet)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by etiennethomassen** [comment]
Just read previous issue again. Rounding issue is not expected to work in v 0.8.8, But the layer name issue remains.

Can I update to 0.9?

**Comment by m-kuhn** [comment]
You can join the beta team by visiting the following URL: https://play.google.com/apps/testing/ch.opengis.qfield

**Comment by etiennethomassen** [comment]
The layer issue is also solved by upgrading

Thanks!
