### ISSUE TITLE
Conditional Visibility causes field and value-Map scramble

### ISSUE THREAD

**Issue by Detritalgeo** [opengisch/QField#1020]
I have created a field data collection form structure in QGIS that makes use of Conditional visibility.

The form is designed to characterize rock samples in the field but when a sample is to be recorded for only quality checks it needs no technical data as it it simply a reference material. In this case it is assigned a sample number and which specific reference material is used and that is all.. all other tabs in the form are hidden.

I used an integer field called 'QAQC_YesNo' as a check-box to activate this transformation and everything looks good in QGIS desktop, when I check to box the 'Site Information' group is hidden from view.

![image](https://user-images.githubusercontent.com/49292273/81873185-0b5f8680-9530-11ea-853b-40ced6327085.png)

and with checkbox activated:

![image](https://user-images.githubusercontent.com/49292273/81873211-19150c00-9530-11ea-8602-cebbba86aa20.png)

In QFIELD, the form presents itself just at the QGIS desktop version:
![image](https://user-images.githubusercontent.com/49292273/81873408-917bcd00-9530-11ea-9813-6a302af57dea.png)

... and works as intended when the check-box is activated:
![image](https://user-images.githubusercontent.com/49292273/81873494-bcfeb780-9530-11ea-8bc9-bf13a6431e32.png)

. . . the BUG presents itself when I de-activate the check-box, it seems to scramble the fields (in the site information group for example, it has replaced the 'Station #' field with Sample #', 'Sampler 1' with 'Occurrence' and 'Sampler 2' with 'Prefix' which all occur at the top of the form. 

![image](https://user-images.githubusercontent.com/49292273/81873701-2383d580-9531-11ea-9be2-9a498a473832.png)

___________________________________________
**QField version:** 1.5.3 - 010503992

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [?]

**Comment by VxTedxV** [comment]
related to #399, isn't it ?

**Comment by Detritalgeo** [comment]
Yes, I think you are correct. It looks like a similar circumstance. 

In the short-term this can be mitigated by closing or canceling the form if a conditional visibility is deactivated in the current form view. The deactivation of the conditional visibility is when the artifacts are introduced when trying to restore the form groups and tabs.

**Comment by nirvn** [comment]
@Detritalgeo , this has been fixed in upcoming QField 1.9.
