### ISSUE TITLE
Merging Geometry

### ISSUE THREAD

**Issue by LucasKolendo** [opengisch/QField#1022]
Qfield offers splitting geometry (line, polygon faetures) what is a great thing, but not provides merging geometry. In field working with app, when we are editing geometry for example deviding polygons into smaller parts, many times we need to merge some devided earlier parts, what in my opinion could be a great step forward. 

### Expected behavior:

Possiblility to merge geometry (line, polygon) in edit session in Qfield with user defined attribute transfer option (User can choose an object for attribute transfer)

### Observed behavior:

Possiblility to merge geometry (line, polygon) in edit session in Qfield with user defined attribute transfer option (User can choose an object for attribute transfer)

**Comment by suricactus** [comment]
This feature has been implemented https://github.com/opengisch/QField/pull/1144
