### ISSUE TITLE
Qfield doesn't show numeric keypad

### ISSUE THREAD

**Issue by soester** [opengisch/QField#1026]
Qfield shows full keyboard, also for numeric fields (integer and double)

### Reproduction Steps:

Enter a value in a field with integer or double type.

### Expected behavior:

Qfield should show a nice numeric keypad with '.' and '-'

### Observed behavior:

Instead Qfield shows full QWERTY keyboard with small numbers to type

**QField version:** 1.5.3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes, i guess so]
* Problem happens with all files and projects, not only some files or projects: [Yes]
 - Offline-Projects from Postgres, created with Qfield-Sync, stored in geopackage

Would be great to get the nice numeric keypad back!

**Comment by soester** [comment]
not as severe as https://github.com/opengisch/QField/issues/197 in the old days...

**Comment by signedav** [comment]
Hi @soester

I cannot reproduce. What is the behavior you have in the demo projects (e.g. Advanced Bee Farming) on the Apiary - Yearly Harvest (kg)?

**Comment by soester** [comment]
Hi @signedav 
I checked with the demo projects: there it works.
The difference in configuration is the widget chosen in QGIS:
- Demo project: Range
- Our project: Text edit

So now the keyboard is now chosen by widget type and not by field type?
Worked in our project before. Therefore the issue.

Should all numeric fields be configured as Range to get a numeric keypad?
If so the documentation (https://qfield.org/docs/project-management/vector-layers.html#field-widget) should be adapded accordingly.

**Comment by signedav** [comment]
Okay thanks I have to check that.

**Comment by signedav** [comment]
@soester 

For your information: We introduced the range widget with it's capabilities to use slides and numeric input etc. and since we have there all this possibilities, it's handled there. So we usually don't use the text edit widget for numeric values anymore. But I agree, that this is a restriction. So we have to decide if we accept the restriction (write documentation) or bring it back, to be backward compatible.

**Comment by soester** [comment]
@signedav 
Ok, thanks for the information. We will have to rebuild our template projects soon anyway. So we will use the range widget there. But i think it is not only about backward compatibility. It is also a good thing to restrict users to enter letters into numeric fields.

**Comment by soester** [comment]
thanks for the quick response!
