### ISSUE TITLE
Relation 1-n Postgis

### ISSUE THREAD

**Issue by Benb73** [opengisch/QField#1028]
Hello
I cannot maintain a 1-N relation behavior between two Postgis tables under Qfield

### Reproduction Steps:

1. A punctual geometric table and a non-geometric table. 1-N relationship between the two with foreign key and primary key (serial) well configured under postgis, the relationship is well configured under QGIS. incrementaiton new object and update works under QGIS
2. Project preparation for QFIEL with QFIELSync
3. My postgis serial primary key does not work and no longer increments. There is an FID field created by QfieldSync which takes over. So my 1-n relationship no longer works when creating a new object.

### Expected behavior:

I would like to be able to create a new observation (1-n) on a new object created on Qfield. 
the same behavior as in the bee_project.qgs in the demo_projet folder

### Observed behavior:

Unable to create a new observation on a created object (error message indicating that it is impossible to retrieve the parent's ID)

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version: 1.5.3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

Thank you

**Comment by Benb73** [comment]
I advanced on the problem.
I understood that we could not "copy" postgis layers without connection. We are forced to configure in "offline edition" mode.

For that you have to make a Spatialite base

**Comment by signedav** [comment]
Thanks @Benb73 So this is no issue about the relations anymore?

**Comment by Benb73** [comment]
Yes. but My problem is that the "offline edition" mode of QFIELDSync breaks existing relationships and QFIELDSync does not offer the "copy" option for postgis tables. I have to go through an intermediate SpatiaLite base to have the "copy" option. 
In addition, with this option I do not take advantage of synchronization from Qfield when returning from the field.

**Comment by signedav** [comment]
Okay, so we keep this open. Still it's more a QFieldSync issue then I guess.

**Comment by fmensio** [comment]
I've a similar issue.
I created a custom attributes form where for some fields of a point layer I use a table with code and description to decode in input mode (for users on the field) the value stored in the point layer using the description cointained in the table. I've used the Value Relation with a filter expression where I put the value of a field that is associated (in the table) to the codes and description. (ex "field_to_dec" = 'lithology' or "field_to_dec"='Slope_class')
Both are Postgis tables.

When I create (with qfield sync plugin) the project, with online data (both, points and decode table) the relation is maintained. But when I edit a field, all the descriptions contained in the decodification table appear (and not only those related to that field), and this for all fields that need a decode.
In Qgis it works fine.

Instead, when I create the project with both data offline, I lose the relation, as the issue described before in the thread.

**Comment by fmensio** [comment]
The issue Value relation for offline layers and table is solved with last release of Qfildsync.
Howewer the filter expression in Value Relation still not working in Qfield.


> I've a similar issue.
> I created a custom attributes form where for some fields of a point layer I use a table with code and description to decode in input mode (for users on the field) the value stored in the point layer using the description cointained in the table. I've used the Value Relation with a filter expression where I put the value of a field that is associated (in the table) to the codes and description. (ex "field_to_dec" = 'lithology' or "field_to_dec"='Slope_class')
> Both are Postgis tables.
> 
> When I create (with qfield sync plugin) the project, with online data (both, points and decode table) the relation is maintained. But when I edit a field, all the descriptions contained in the decodification table appear (and not only those related to that field), and this for all fields that need a decode.
> In Qgis it works fine.
> 
> Instead, when I create the project with both data offline, I lose the relation, as the issue described before in the thread.

**Comment by signedav** [comment]
Hi @fmensio 

The Filter Expression is not yet implemented in QField. It's reported as an enhancement here #724

I close this issue. Feel free to reopen if there is anything left to have it open.

**Comment by fmensio** [comment]
Ok. Thanks. I opened the same problem on the qfieldsync repository. maybe
you need to close that too.
Is there any way around the problem until its resolved?

Thanks
