### ISSUE TITLE
Model works with a scratch layer. Input vector layer generated with data source manager or 'create points layer from table' does not work.

### ISSUE THREAD

**Issue by ejdkeys** [opengisch/QField#1044]
![error](https://user-images.githubusercontent.com/64247664/83601845-fe203f80-a5a3-11ea-9d6d-03af9b79712f.JPG)
[Short description of problem here]
I created a model to generate alerts or violations when a point falls outside/inside of a polygon or buffer. The input vector layer is a point file (I've tried geopackage, shape, scratch) generated within the workspace or outside the workspace. The model only works when points were generated manually using the add point feature. The model does not work when the points are created using the data source manager or the 'create points from table' tool... even when the points are in the exact same place. Its driving me mad.
### Reproduction Steps:

1. Create model, verify it works with test data points (generated within model using the 'add point feature'
2. export scratch to geopackage. run model. Works
3. Tried to use pre-existing geopackage point file to run model (same locations/same projection) does not work.

### Expected behavior:

Model to create output
![model](https://user-images.githubusercontent.com/64247664/83600538-61f53900-a5a1-11ea-80f1-99bb9abf8493.JPG)

### Observed behavior:

Only works with points generated by the 'add point feature'. It works if I save the generated scratch to a geopackage or shape file. I generate these points by enable snapping, and add point features on top of the point geopackage I created using the data source manager (or bringing in a csv/'create points layer from table'.

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]
3.12 

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
Model requires 3.12 for new features
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
Model works with a locally generated point, but not a previously generated point.
* Problem happens with all files and projects, not only some files or projects: [Yes/No]
No

**Comment by VxTedxV** [comment]
I don't think it's related to QField. Don't you make a mistake... wrong hub ?

**Comment by ejdkeys** [comment]
> I don't think it's related to QField. Don't you make a mistake... wrong hub ?

oops. Thanks mate!
