### ISSUE TITLE
Sub meter scalebar

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/QField#1046]
[Short description of problem here]

### Reproduction Steps:

When zooming in the scalebar is set to 0m. It would be nice to have smaller steps than 1m (example: 50cm, 25cm, 10cm.. or so)

maybe related to: https://github.com/opengisch/QField/issues/273

### Expected behavior:

Scalebar is scaling in sub-meter range

### Observed behavior:

Scalebar stops at 1m and jumps to 0m afterwards

### Screenshots and GIFs

![Screenshot_20200604-124714_QField](https://user-images.githubusercontent.com/23494522/83755307-a9e19200-a66d-11ea-932f-fa6a10d1bebb.jpg)
![Screenshot_20200604-124723_QField](https://user-images.githubusercontent.com/23494522/83755318-afd77300-a66d-11ea-8b01-99516fdcdc7c.jpg)

**QField version:** 1.5.3 (010503991)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: ?
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by MichaelEFlip** [comment]
This would be a very fine enhancement to work with RTK GNSS for precise positioning.

**Comment by EulenspiegelTill** [comment]
Am I supposed to close this issue? It works fine with @suricactus adjustments, thanks!
