### ISSUE TITLE
Interface stay blocked on 1 tab in multi-tab forms

### ISSUE THREAD

**Issue by vlebert** [opengisch/QField#1054]
Hi guys

I have an anoying issue on multi-tab forms :
In a form with tabs, the interface can stay blocked on 1 tab in certain conditions

### Reproduction Steps:

Make a multi-tab form
Open the form
Switch to 1 tab
Slide the edition windows down (but not totally) like to close the window, BY TOUCHING INSIDE THE WINDOW (and not on  the top title), then slide it up again
Click on an other tab : the tab doesn't switch

To unblock : switch tab by sliding left or right instead of clicking tab title

There may be other conditions when this bug happen

### Screenshots and GIFs

I'll post a video if the description is unclear

**QField version:** 
1.5.3 010503992
But this bug is older !

**Comment by m-kuhn** [comment]
Thanks for the report.

Sounds like an issue with the focus.

**Comment by nirvn** [comment]
Focus, or z-index.

**Comment by nirvn** [comment]
@vlebert , still an issue?

**Comment by vlebert** [comment]
I think it still occurs. But I stick to version 1.9.6 (for filesystem access). So can't say on the latest version

**Comment by nirvn** [comment]
@vlebert , here's a small "secret": you can enjoy full storage access and run latest version by selecting the "all access" variant in the list of APKs here (https://github.com/opengisch/QField/commit/cbb0000c0350859c94d0614a6caf4c148b3faa98#commitcomment-88755450).

It'll start appearing in the release pages starting with QField 2.5.

Could you try with these?

**Comment by vlebert** [comment]
Hi

I couldn't reproduce the bug on last version (it was quite random but still).
I could compare 1.9.6 with last version which surely handles better tabs (especially on projects with conditionnal visibility on tabs).

So I guess this issue can be closed.

A question on "all access" version : I couldn't find it on release page. I took it from last commit but do you plan to add it to release page ?
I am quite glad with this process as it also prevent auto-update of the APK on our tablet fleet 

cheers

**Comment by vlebert** [comment]
Hi 

Just a message to say that the bug occured today on my phone with last version.
Couldn't make a video but I think it has something to do with conditional visibility in tabs and containers

**Comment by nirvn** [comment]
@vlebert , keep alert and try to find a way to replicate.

**Comment by vlebert** [comment]
My mistake I have it on video but I was using 1.9.6.
Couldn't reproduce with 2.X. It is very random though
