### ISSUE TITLE
Map themes are reversed between QGIS and QField

### ISSUE THREAD

**Issue by gnerred** [opengisch/QField#106]
Working with version 0.9.2 on Galaxy tab.

I create two map themes in QGIS : "Cadastre" and "Ortho". The only difference between the themes is that in second one the ortho is checked. When I send the project to the tablet, themes are reversed. I have to select theme "Cadastre" to see the ortho, and vice versa.

**Comment by saemiw** [comment]
I can confirm this. for version 0.9.5. If you only have 2 presets its not a problem. One could even trick the bug. But when you have more presets it becomes difficult.

**Comment by saemiw** [comment]
Cool this would be very helpful to use for our fieldwork. Could you be so nice and pack this into a release (0.9.6)? I am uncertain how to do it myself.

**Comment by saemiw** [comment]
I it still reversed in version 0.9.6 that is available on playstore now: 

Here are some printscreens how it looks on QGIS:
present "rodent only"
![rodent only qgis](https://cloud.githubusercontent.com/assets/20398621/23449747/25545ca4-fe58-11e6-8fce-d65b10dcb6f1.JPG)
preset "all but rodent"
![all but rodent](https://cloud.githubusercontent.com/assets/20398621/23449746/25540b46-fe58-11e6-85a9-1b90b7cba1a1.JPG)

and on QField (it is reversed):
![screenshot_2017-03-01-08-18-31](https://cloud.githubusercontent.com/assets/20398621/23449748/2554f15a-fe58-11e6-873a-bb3e98d3d322.png)
![screenshot_2017-03-01-08-18-25](https://cloud.githubusercontent.com/assets/20398621/23449745/25527a06-fe58-11e6-83f9-4ac0e8c177b3.png)

**Comment by saemiw** [comment]
Here is the QGIS-project if you want to have a try yourself:

[mapthemereversed.zip](https://github.com/opengisch/QField/files/809927/mapthemereversed.zip)

**Comment by zakigates** [comment]
The behavior that I have is I can't see my layers when I activate 2 presets.

**Comment by zakigates** [comment]
an other weird behavior observed, when you create a preset, qfield doesn't show the layers which have a categorized style, only those with simple symbol are shown.

**Comment by saemiw** [comment]
I noticed once something similar. If I remember correctly this only is the case when you load layers that are empty (no data) but have a categorized style to qfield. If you have one feature in that layer the styling at the time of transfer the styling works well. (but this is not really related to this issue, which has been fixed).

**Comment by zakigates** [comment]
No I did a small test with two layers which contains data and I noticed that the layers disappear if they come from postgis other wise if they are geopackage or shp they work well.
