### ISSUE TITLE
The relational values widget does not work with strings keys

### ISSUE THREAD

**Issue by Roman2nc** [opengisch/QField#1060]
The relational values widget does not work on qfield if the relationship uses strings .

column id is of type varchar (guid)

Qfield version : 1.5.3 - piz palu

(work on qgis 3.10)

**Comment by m-kuhn** [comment]
Thank you @Roman2nc 

Are you able to provide test data?

**Comment by Roman2nc** [comment]
Excuse me, there's no bug. The problem came from the conversion between qgis2 and qgis3.
qgis 3 does an incomplete conversion, you have to go in the widget configuration and save.

qgis2
`<edittype widgetv2type="ValueRelation" name="typeSignalisation">
          <widgetv2config OrderByValue="1" AllowNull="0" FilterExpression="" UseCompleter="0" fieldEditable="1" Key="id" constraint="" Layer="bird_type_signalisation0000" Value="instanceLabel" labelOnTop="0" constraintDescription="" AllowMulti="0" notNull="0"/>
        </edittype>`

qgis 3 (auto-conversion)
`  <editWidget type="ValueRelation">
    <config>
      <Option type="Map">
        <Option value="0" name="AllowMulti" type="QString"/>
        <Option value="0" name="AllowNull" type="QString"/>
        <Option value="" name="FilterExpression" type="QString"/>
        <Option value="id" name="Key" type="QString"/>
        <Option value="bird_type_signalisation0000" name="Layer" type="QString"/>
        <Option value="1" name="OrderByValue" type="QString"/>
        <Option value="0" name="UseCompleter" type="QString"/>
        <Option value="instanceLabel" name="Value" type="QString"/>
      </Option>
    </config>
  </editWidget>`


qgis3 after save widget
`  <editWidget type="ValueRelation">
    <config>
      <Option type="Map">
        <Option value="false" name="AllowMulti" type="bool"/>
        <Option value="false" name="AllowNull" type="bool"/>
        <Option value="" name="FilterExpression" type="QString"/>
        <Option value="id" name="Key" type="QString"/>
        <Option value="bird_type_signalisation0000" name="Layer" type="QString"/>
        <Option value="Type de signalisation" name="LayerName" type="QString"/>
        <Option value="spatialite" name="LayerProviderName" type="QString"/>
        <Option value="dbname='export-sv.db' table=&quot;bird_type_signalisation&quot; sql=" name="LayerSource" type="QString"/>
        <Option value="1" name="NofColumns" type="int"/>
        <Option value="true" name="OrderByValue" type="bool"/>
        <Option value="false" name="UseCompleter" type="bool"/>
        <Option value="instanceLabel" name="Value" type="QString"/>
      </Option>
    </config>
  </editWidget>`
