### ISSUE TITLE
Lock features and geometry

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#1065]
It would be nice to be able to lock the geometries of a layer.

Use case:

A field worker should visit a number of known assets. For each visited asset, he should be able to adjust some attributes ("validated", "needs replacement", "repaired", "out of order", you name it).

The field worker should not be able to:

 - add new features
 - delete existing features
 - adjust the geometries

This behavior needs to be configurable on a per-layer basis in the project.

**Comment by m-kuhn** [comment]
I think we have a misunderstanding here.
You are completely right that in browse mode this is possible. But it's possible to switch to digitize mode on the field any time and that's where the possible source of errors is located. This new functionality handles this cleanly and does not disturb any existing operation, because it's opt-in and needs to be activated in the project configuration. If it's not activated, everything stays as before.

What do you think about the icon though. Should that

a) be shown for read only layers only
b) be shown for read only layers and geometry locked layers
c) be shown for read only layers and a different one for geometry locked layers

and also

1) always be shown
2) only be shown when the screen is wide enough

**Comment by VxTedxV** [comment]
OK I understand.
Waiting for how it will be activated : if it's a feature related to QField (and I think it is), think about not configuring it through QFieldSync, it would be better in QField (to all the users who don't use QFieldSync) or best in QGis (because that's where we configure all the project).

**Comment by m-kuhn** [comment]
Have a look here https://github.com/opengisch/qfieldsync/pull/157
It's seamlessly integrated with QGIS, but through QFieldSync.
I agree it would be nice to add support to QGIS itself, but the extra effort to also implement the functionality (and not only the configuration option) in QGIS was unfortunately out of scope for the current project. Having it would be very exciting.
