### ISSUE TITLE
GPS to wrong location - EPSG: 7855

### ISSUE THREAD

**Issue by ARBkey** [opengisch/QField#1072]
QFIELD: 1.5.3
QGIS: 3.12
Tested both using qfield sync and without

The GPS marker is not showing true location within QField while within GDA2020 Zone 55 (EPSG: 7855).

The GPS shows location as close to west africa when I am actually within Melbourne, Australia.

I am happy to support implementation of this datum with GPS location support ASAP.
 
![Screenshot_20200620-121917_QField](https://user-images.githubusercontent.com/64572560/85189255-ad714c00-b2f0-11ea-89bc-95b4c8fb9c79.jpg)

**Comment by VxTedxV** [comment]
Probably same issue as #604

**Comment by nirvn** [comment]
@m-kuhn , investing in upgrading GDAL/PROJ to their next-gen versions might well resolve this issue.
