### ISSUE TITLE
WFS_T is not being viewed in Qfield

### ISSUE THREAD

**Issue by denilsonjesus** [opengisch/QField#1074]
I'm using Qfield 1.5.3 and Qgis 3.12 for online editing using WFS-T. The problem I'm encountering is that in Qgis WFS works and is viewed and edited normally, regardless of the zoom level or scale. When I bring that same QGZ to Qfield, the layer does not appear at all zoom levels. If I include a new polygon, it is drawn, but the neighboring polygons are not. What could be happening?

**Comment by nirvn** [comment]
@denilsonjesus , is this still an issue with the latest QField 2.0 beta? There has been a fair amount of improvements in both QField and the underlying libraries used which has likely fixed your situation.

**Comment by denilsonjesus** [comment]
No.

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by nirvn** [comment]
@denilsonjesus , great news! Happy mapping with QField!
