### ISSUE TITLE
Picture orientation issue

### ISSUE THREAD

**Issue by vlebert** [opengisch/QField#1075]
Is it possible that the orientation of picture taken by Qfield are not properly interpreted in QGIS?
Outside QGIS it seems OK

Inside QGIS :
![image](https://user-images.githubusercontent.com/49779177/85293544-cc611100-b49d-11ea-8845-a3aa03c00720.png)

Outside Qgis : 
![image](https://user-images.githubusercontent.com/49779177/85293599-df73e100-b49d-11ea-9289-92d482abea76.png)

I don't really know if it is a Qgis or Qfield isue. It's annoying because pictures appear the same in print layout in QGIS.

I seems to be like this for picts taken since v 1.04 till now

**Comment by vlebert** [comment]
I precise I am using "webview" in Qgis as pictures as stored beside a public URL

**Comment by m-kuhn** [comment]
This is the corresponding upstream QGIS issue: https://github.com/qgis/QGIS/issues/34868
It looks like a tricky one to resolve there, but probably doable.
An alternative approach would be to apply the rotation in qfieldsync.

**Comment by vlebert** [comment]
Hi thanks for the link.

Any idea how can I set a test on length/width ratio to apply a rotation on landscape pictures?

I tried the <img> trick but it didn't work :

![image](https://user-images.githubusercontent.com/49779177/85376723-64133d80-b538-11ea-8b91-c93af5b26378.png)

**Comment by m-kuhn** [comment]
Please raise support requests through a support channel

**Comment by m-kuhn** [comment]
This seems to be evolving into a support question. We'd love to help you, but this will need to go through a [support channel](https://qfield.org/docs/en/development/index.html#support). This issue tracker is dedicated to improving the QField app.
