### ISSUE TITLE
Relation-Reference Widget: Values not saved

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#108]
You can well select the values from another table as defined by the relation-reference-widget. The values are however not saved to the table. Also if you modify the record it won't save the entry.

### Reproduction Steps:

1. digitize a feature and enter a value in a field that is defined by the relation-reference widget
2. select that point to see its attributes
3. in my case the attribute is named "observer". It is not saved and cannot be modified.

### Expected behavior:

Save the chosen selection (save chosen "observer" - see video)

### Observed behavior:

my field "observer" is not saved (see video)

### Video showing the behaviour of QField
https://youtu.be/vckV_gQsUag

### Setting in QGIS Desktop Project
![relationreference](https://cloud.githubusercontent.com/assets/20398621/23201848/b4f64908-f8db-11e6-9aca-53ccf25598d8.JPG)
![proj-properties](https://cloud.githubusercontent.com/assets/20398621/23201847/b4f52622-f8db-11e6-8abf-00746e9de4dc.JPG)

**QField version:** [0.9.3]
**QGIS Desktop version:** [2.18.3]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [didn't check but expect so]
* I used geopackes

**Comment by saemiw** [comment]
If I add a "observer" is not NULL constraint to that field I am (correctly) not able to save the field. This is an indication that the value reference widget really doesn't write a value into that field (despite the visual appearance).

**Comment by saemiw** [comment]
update:

First of all it seems important that the fieldname in the referencing and referenced table are identical. When I changed this the widget works and the values are written to the table.

Secondly I notice that the display of the values is slow. In the following video I 
1) start QField select point 5. Notice how the observer-field is emtpy. 
2) select another point, point 4. Here the value for observer is displayed correctly.
3)  Now I go back to point 5 and - surprise - the observer entry is now also visible.

https://youtu.be/hPsJiU3guPc

It seems to me that QField takes some time to get the value? Is that possible? Any explanations for this behaviour?

**Comment by m-kuhn** [comment]
The issue with different field names is solved in https://github.com/opengisch/QField/releases/tag/release-0.9.4

**Comment by m-kuhn** [comment]
Issue with usage in identification view addressed in
https://github.com/opengisch/QField/releases/tag/release-0.9.5
