### ISSUE TITLE
QRCode scan feature

### ISSUE THREAD

**Issue by atabaraud** [opengisch/QField#1085]
The idea is to implement the possibility of scanning a QRCODE to fill a field in a form with the raw value of the QRCODE

**Comment by Kabouik** [comment]
That would be super useful, I agree.

**Comment by miili** [comment]
The library should also support scanning of barcodes.

**Comment by marteinnm** [comment]
Has there been any development on this issue?

**Comment by miili** [comment]
Is there an update, can one help with the implementation of this feature?

**Comment by miili** [comment]
Some QML QRCode  // barcode resources:
https://scythe-studio.com/en/blog/how-to-scan-barcodes-in-qt-qml-application%22%20
https://www.dynamsoft.com/codepool/qt-qml-qr-code-scanner.html

This seems to be rather low hanging and can be integrated into `src/qml/editorwidgets/TextEdit.qml`.
How could this attribute _allowing QR scanning_ be communicated from the Attribute Form to QField's TextEdit?

**Comment by nirvn** [comment]
@miili , @marteinnm , @Kabouik , @atabaraud , this has been fully implemented in this PR (https://github.com/opengisch/QField/pull/3142). Feel free to test the APKs in there and report on your experience.

**Comment by Kabouik** [comment]
That's great news! For the record, I still can't see that option (no three-dot menu in the Beekeper field in the example projectcddc) despite having subscribed to the unstable branch on the store, and reinstalled Qfield. The about page says I'm using master-dev (dc1f4a) which seems to be the latest commit, but I see that PR #1085 is now open again?

**Comment by Kabouik** [comment]
Actually I assumed it was merged when you posted, but I was probably wrong. I'll wait and try later when the PR is merged.
