### ISSUE TITLE
Form in tracking doesn’t remember last value

### ISSUE THREAD

**Issue by alsper78** [opengisch/QField#1086]
In tracking of lines I tried to check the box to remember values in the attribute form, but when I track the next line the form is empty.
When I insert features in the normal way (not with tracking) the remembering of attributes works good.
(QField version: 1.5.3)

**Comment by signedav** [comment]
You are right. I think it was never supported. It would be nice to have it. And if not, then at least there shouldn't be the check boxes.

**Comment by nirvn** [comment]
@alsper78 , I suspect this has been addressed, could you confirm? A few versions ago, some work was done for QField to have static cache of remembered value across several feature forms.

**Comment by alsper78** [comment]
> @alsper78 , I suspect this has been addressed, could you confirm? A few versions ago, some work was done for QField to have static cache of remembered value across several feature forms.

Yes, I tested and now it works. Thank you

**Comment by nirvn** [comment]
@alsper78 , fantastic. Happy field mapping!
