### ISSUE TITLE
"Not null" checkbox under constraints not working

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#109]
In the Edit Widget Properties (QField Desktop) there is a section called "constraints". In this section there is a checkbox called "Not null". This checkbox does not work. There is a workaround available (fieldname is not null) but it is tedious work if you have lots of values. Something to improve?

### Screenshots and GIFs
In the picture the top setting does not work (bug explained here) - and the bottom setting is the "work around"
![prasentation1](https://cloud.githubusercontent.com/assets/20398621/23215081/640ca880-f911-11e6-80ba-108ccd3e3a8b.jpg)

**QField version:** [0.9.5]
**QGIS version:** [2.18.3]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [don't know]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [checked with 2 projects]

**Comment by m-kuhn** [comment]
It's a known issue and would be a nice improvement.

**Comment by m-kuhn** [comment]
@signedav is this fixed?

**Comment by signedav** [comment]
Yes 😊 Forgot about this issue. Fixed with #906
