### ISSUE TITLE
Measurements "length" with "ellipsoidal" or "Cartesian" representation.

### ISSUE THREAD

**Issue by RAFALCO** [opengisch/QField#1090]
QFIELD always seems to calculate the length in "Cartesian". In the case of lengths in a project in "ellipsoids" (for example wgs84 / EPSG: 3857) this leads to false lengths.
Do you have the same problem?

QField version:*1.5.3
Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects in ellipsoidal, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
This is correct, currently QField always calculates lengths as cartesian distances.

**Comment by signedav** [comment]
Are the distances wrong? If so, then we should maybe deactivate the measure-tool on ellipsoids until we can make this enhancement becoming true.

**Comment by nirvn** [comment]
@RAFALCO , I believe this is fixed in latest QField, could you confirm?
