### ISSUE TITLE
Show numeric digitizing information while drawing

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#110]
Obligatory screen cast

![digitizing](https://cloud.githubusercontent.com/assets/588407/23225175/4624b16c-f931-11e6-8c09-016b7ef9468a.gif)

@gnerred Some early development prototype. Is this what you envisioned?
(numbers are from a different CRS and likely wrong anyway)

**Comment by gnerred** [comment]
Very nice thanks :-) ! I didn't know that you were already developping polygon digitizing ;-) ...

**Comment by m-kuhn** [comment]
Oh... polygons are available since september (0.8.0) 😉

https://github.com/opengisch/QField/releases/tag/release-0.8.0

**Comment by gnerred** [comment]
Fine :O)

**Comment by m-kuhn** [comment]
Finally.

The logic to format and convert between different units is now shared with QGIS https://github.com/qgis/QGIS/pull/4213 

The following animation highlights the way it works

![digitizingnumbers](https://cloud.githubusercontent.com/assets/588407/23620817/9cde8b34-0298-11e7-8f3b-52fb6ebc9a58.gif)

**Comment by gnerred** [comment]
Great thanks :) !
