### ISSUE TITLE
Hiding legend nodes

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#1109]
Since QField 1.6.0, the tip given [here in the documentation](https://qfield.org/docs/project-management/allow-hiding-legend-nodes.html) to hide some layers seems not to work anymore

**Comment by m-kuhn** [comment]
@nirvn any idea why https://github.com/opengisch/QField/blob/master/src/core/layertreemodel.cpp#L636-L644 is no longer taken into account?

**Comment by nirvn** [comment]
Yep I do. Can be addressed without too much of an headache.
