### ISSUE TITLE
GPS tracks ?

### ISSUE THREAD

**Issue by MadoB** [opengisch/QField#111]
Hi,
I use the last Qfield version and find it very useful. Just a question : is it possible to make gps tracks automatically with Qfield ? With Qgis i know i can. 

Thank you for your answer and have a great day.

**Comment by m-kuhn** [comment]
It's not yet possible but a very interesting functionality.

The plan we have in mind so far is to add a tracking functionality that
will add new points or vertexes on lines and polygons automatically
(when in tracking mode).

This can be based on either a fixed interval in time (e.g. every 5
seconds) or a minimum distance to the previous point (e.g. every 5 meters).

This is not yet a finalized plan and not yet funded.

**Comment by m-kuhn** [comment]
Further requirements:

* Start tracking on long click on the edit button
* Fill in features with default values and remembered fields (point layers, like setting suppressFeatureForm to true)
* show an indicator about ongoing trackings in the layer tree

**Comment by MadoB** [comment]
Hi,
Is this tool work on the new version of Qfield ?
Thank you have a great day.

**Comment by m-kuhn** [comment]
Still looking for sponsors.

**Comment by geoRom** [comment]
Can you get us an idea of the cost of developpement?

**Comment by EmilyNGH** [comment]
I'm also interested in development cost and time frames. It's a feature that would be hugely useful

**Comment by KirstenReilly** [comment]
Has this functionality got any further? We would also be interested in development costs and time frames.

**Comment by georgecorea** [comment]
It's been a few more months now and just wondering if this extremely useful feature has been implemented?

**Comment by m-kuhn** [comment]
Not yet. Anyone interested in this feature, please contact us by mail to get a quote

**Comment by m-kuhn** [comment]
@signedav is this implemented?

**Comment by signedav** [comment]
Will be in the upcoming release 1.5 :tada:

**Comment by signedav** [comment]
See #855
