### ISSUE TITLE
lisibility of legend structure lost

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#1110]
Groups and sub-groups not well rendered in legend :

![path4522](https://user-images.githubusercontent.com/30288828/86518402-28c71780-be32-11ea-9028-f41a53b53207.png)

I know we loose collapsible nodes but is it possible to keep legend structure in some other way like indents ?

**QField version:** 1.6.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
Thanks for the suggestions.
We've scheduled some updates regarding this later this month.
