### ISSUE TITLE
Show hidden layers group

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#1111]
If a group of layers was hidden by default on the map, we were able to force show it. Since QField 1.6.0, hidden layers groups are shown in legend (greyed out) but long press on it doesn't show the "show/hide" option anymore so it will always remain hidden on the map, even if we try to force show layers contained in it ("show option" stays unchecked).

**Comment by nirvn** [comment]
Thanks for reporting this, I'll look into this.
