### ISSUE TITLE
Picture preview disappeared 

### ISSUE THREAD

**Issue by nicolasmcfadden** [opengisch/QField#1112]
The picture previews have disappeared in recent development versions and the latest 1.6 version

### Reproduction Steps:

1. Take picture
2. Open attribute table 
3. No preview anymore 

### Expected behavior:

Picture preview

### Observed behavior:

No preview, just working hyperlink

### 
[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] Yes
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No] Yes

**Comment by VxTedxV** [comment]
I tried but works for me.
Android 9, QField 1.6.0

**Comment by m-kuhn** [comment]
The external resource widget will need to be configured with a viewer. QField configuration was aligned to the QGIS Configuration.

**Comment by nicolasmcfadden** [comment]
Hello the project is configured for previews. 
I use Android 10

Here is an attribute form of the project opened with QField 1.5.3 
[
![WhatsApp Image 2020-07-07 at 11 20 39 (1)](https://user-images.githubusercontent.com/27243743/86758324-145a6900-c044-11ea-8ef4-e8ce8b846cb5.jpeg)](url)

Here is the same attribute opened with QField 1.6
[
![WhatsApp Image 2020-07-07 at 11 20 39](https://user-images.githubusercontent.com/27243743/86758458-2cca8380-c044-11ea-91e1-518b29cb2a68.jpeg)
](url)

This difference has appeared since the interface changes in the dev versions pushed out since 1.5.3.

**Comment by m-kuhn** [comment]
Are you able to see it in the apiary layer in the demo project?

**Comment by nicolasmcfadden** [comment]
Yes it does actually! Very strange...

**Comment by m-kuhn** [comment]
This seems to be a support question / project configuration question then. I'll close this since the app is working as expected.
Feel free to use one of the [support channels](https://qfield.org/docs/development/index.html#support) instead.
Thank you

**Comment by nicolasmcfadden** [comment]
I have figured it out on my projects... the preview disappears when i activate "Use a hyperlink for document path" and comes back when i deactivate it.
However, up to Qfield 1.5.3, this didn't happen

**Comment by nicolasmcfadden** [comment]
@m-kuhn might be worth reopening after my last find?

**Comment by m-kuhn** [comment]
@nicolasmcfadden up to QField 1.5.3 QField did not support "use a hyperlink for document path".
If activated a hyperlink will be used instead of a preview. It seems to me this is respecting the configuration and the main thing that is missing is an adjusted documentation. Is this what you have on your mind?
