### ISSUE TITLE
delay between recording features

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#1113]
Can't record a feature after just deleting one

### Reproduction Steps:

1. Create a feature
2. Save it
2. Delete it
3. Create a new feature
4. Can't be saved. Must abort and wait few more seconds to be able to create and save a new one

### Expected behavior:

Save any feature created

### Observed behavior:

On a .shp layer.
After deleting a feature, message "successfully deleted feature x" is shown, the feature disappear from the map as expected. Creating a new one show attribute table but when saving, message "unable to save changes" appears while attribute table menu disappear. Must push back button.  A second try works.

### Screenshots and GIFs

Weird that QField confirms deletion of the feature but the log says other thing :
![Screenshot_20200705-111946_QField](https://user-images.githubusercontent.com/30288828/86529833-38874000-beb4-11ea-992b-5a975bf7f38c.jpg)

**QField version:** 1.6.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [?]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [?]

**Comment by m-kuhn** [comment]
@VxTedxV can you test #1116 ?

**Comment by VxTedxV** [comment]
> @VxTedxV can you test #1116 ?

Can't save any feature with this one.
![20200705_233835](https://user-images.githubusercontent.com/30288828/86542772-f3e1c000-bf18-11ea-89d4-490953204dcd.jpg)

**Comment by VxTedxV** [comment]
May it comes from my project & layers stored outside of the QField beta folder ?

**Comment by suricactus** [comment]
Could you please upload the project and it's layers? I cannot reproduce on a few different random projects.
