### ISSUE TITLE
QField 1.6 crashes on Android 8

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#1114]
`07-05 12:45:22.774 23064 23082 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "inflateValidate" referenced by "/data/app/ch.opengis.qfield_dev-hVUvItJuDGvn4T4Hfkg9wA==/lib/arm64/libpng16.so"...`

**Comment by florida63** [comment]
It also crashes on Android 7.1.2

**Comment by m-kuhn** [comment]
@florida63 
Can you test the apk (probably arm64-v8a) on https://github.com/opengisch/QField/pull/1115#issuecomment-653892490
Thank you

**Comment by florida63** [comment]
@m-kuhn 

arm64-v8a works but not the armv7.

I went back to version 1.5.3 for my work.

Otherwise great application. To use it on a daily basis in the environmental field, it has really moved in the right direction.

Thank you for the team's work.

Sorry for my English

**Comment by m-kuhn** [comment]
armv7 works fine here, no problems observed.
we will need a logcat extract from a crash to continue
