### ISSUE TITLE
OGR Data Source is Invalid ()

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#112]
After opening the project shows the icon http://i.imgur.com/DsRTPuU.jpg. After opening writes "OGR Data Source is Invalid ()" http://i.imgur.com/d0xit9c.png
With the 0.9.2 version of this type of error does not exist.
I've tried on a variety of devices and a variety of projects. From 0.9.3 version always show this error.
project example https://drive.google.com/file/d/0B6234JBD50yCLWJVUjMxQU1yWTA/view?usp=sharing

**Comment by m-kuhn** [comment]
This was an upstream problem in QGIS and has been resolved recently.
The next release will include this change.
