### ISSUE TITLE
sapping doesn't work anymore with Qfield 1.6

### ISSUE THREAD

**Issue by soester** [opengisch/QField#1120]
Since Qfield 1.6 snapping is not working anymore..
There are some rare cases where snapping events occur (unpredictable). But usualy there are no snapping events at all.
Tested on different projects with point and line layers, where snapping worked very well before 1.6 (Android 9, armV7 apk).

I will try to gather more context.
@m-kuhn do you have any idea?

**Comment by soester** [comment]
all the red squares in this screencast should be snappable... only one feature actually does trigger a snapping event, but a strange one...
 
![20200707_180307](https://user-images.githubusercontent.com/28543978/86809717-746d0180-c07c-11ea-9754-0f05cb108055.gif)

**Comment by soester** [comment]
Project to test:
[live_qfield_users_survey_themes_snappingresults_.qgs.qgz.zip](https://github.com/opengisch/QField/files/4889130/live_qfield_users_survey_themes_snappingresults_.qgs.qgz.zip)
-> Select theme 'simple' and zoom out so you can see whole europe. When paning around it sometimes snaps, but mostly not.

**Comment by signedav** [comment]
Hi @soester 
Thanks for reporting. I can reproduce. I'll have a look on it.
