### ISSUE TITLE
Bug in the CRS conversion

### ISSUE THREAD

**Issue by armsilva** [opengisch/QField#1122]
Hello,

In my QGIS project I created two columns to give me the coordinates of latitudes and longitudes in degree, minute, second, for which I used the expression "to_dms (x (transform ($ geometry, 'EPSG: 3763', 'EPSG: 4937 ')),' x ', 1,' suffix ') ", since the project is in projected coordinates SRC 3763 (I replace x with y in the expression for latitude).
On the PC it works perfectly and automatically returns the correct coordinates, but on the tablet, through QField it presents "stupid" results, with longitudes like 50º. When I repeat the creation of the same point, then it is able to appear 30º and then 40º ...
I think Qfield must have a bug in the SRC conversion.

**Comment by m-kuhn** [comment]
Thanks for reporting.
Can you add the QField version you are using and a test project?

**Comment by armsilva** [comment]
Hello!

I'm using QField "1.5.3 - Piz Palu".

You can see the problem in the fields "long" and "lat". The CRS i am using are portuguese CRS's. In QGIS everything is allright. However, in QField it´s not.
[test.zip](https://github.com/opengisch/QField/files/4884525/test.zip)

Thanks,

**Comment by m-kuhn** [comment]
Can you try with the latest release (https://download.opengis.ch/qfield/ci-builds/qfield-dev--6b6d11cef77e81cee160a327ecc036c33ca3bd50-arm64_v8a.apk)? It likely has fixed the problem.

**Comment by armsilva** [comment]
Hi m-kuhn,

I have now installed this version and the problem is solved. Everything is already working perfectly.
Thank you!

**Comment by m-kuhn** [comment]
@armsilva 
Credits go to @arbkey who sponsored this fix. If you want to show your appreciation, send a mail to https://arbkey.com/ :-)

**Comment by mygiano** [comment]
i have kinda same problem, in QGIS the layer shown perfect, in Qfield also working as QGIS, until recently not show anything and list no feature. Layer name "Polaruang_Sitaro.gpkg"
[Uploading KRK-KKPR_cloud.zip…]()
