### ISSUE TITLE
Picture naming only works on "defaulted" values when creating a feature

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#1127]
[Short description of problem here]

### Reproduction Steps:

1. In QGIS, set a layer "Trashbins" with an "ID" column ( default expression value: "$id") and an attachment - column for the picture name/path
2. Second layer "Bus stops": column "name", no default value and one attachment column for pics

3. In Qfield Sync set photo naming expression: for trashbins layer: 'Trashbins/'||"ID"||'.jpg'  for Bus stops: 'Busstops'||"Name"||'.jpg'

### Expected behavior:

For layer trashbins: after creating a new feature, filling in some details and then taking a picture from within QField (with Opencamera app), a picture in the folder "Trashbins", named after the automatically assigned ID should be created - this works as expected

Same should work for the busstops - a picture in the busstop folder should appear, named after the the value manually written into to "name" field while creating the feature. This does not work, it just creates a picture named after the "default" QField picture naming pattern in the folder "DCIM"

Workaround so far: Creating the feature (and filling in the name), then hitting the save feature button in QField. Selecting the feature again, switching to edit the feature and then click a picture creates a picture after the desired pattern.

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

QGIS 3.14
QField 1.5.3
QFieldSync 3.2.0

**Comment by meyerlor** [comment]
issue is still a thing on the -dev version (downloaded via Google Play Store) of QField

**Comment by signedav** [comment]
You fill in the name before taking the photo, right? Hm... I'll have a look...

**Comment by KanalRotzen** [comment]
is there a better solution already? i also use the not so friendly workaround

_"Workaround so far: Creating the feature (and filling in the name), then hitting the save feature button in QField. Selecting the feature again, switching to edit the feature and then click a picture creates a picture after the desired pattern."_

**Comment by CATER-COM** [comment]
Hello,

Maybe, it could be possible to make available the function currentvalue() in the expression design window as this function as it's made especially for this purpose,  accessing field value before saving feature.

**Comment by suricactus** [comment]
Hello, @CATER-COM . The naming part has been moved to a new place in "QField" tab in the layer properties dialog.
![image](https://user-images.githubusercontent.com/2820439/121172304-37972500-c860-11eb-9ce7-3d25e4da7b57.png)

**Comment by CATER-COM** [comment]
Thanks very much for the tips @suricactus . Unfortunately this change don't give access to the current_value() variable to access form values before saving. Maybe for the next release ;-)

**Comment by suricactus** [comment]
Feel free to file a new feature request at https://github.com/opengisch/qfieldsync/issues .

**Comment by CATER-COM** [comment]
Yes this is what i did, but it work only if you add picture to an existing feature. If you create a feature, until it is not saved, the patern don't see it. It's the same in QGIS and the variable current_value() is designed in this purpose.

**Comment by meyerlor** [comment]
have you activated in the settings of QField "Fast Editing Mode" ? This might solve your issue, as the feature is saved as soon it has a valid geometry

**Comment by CATER-COM** [comment]
Hi @meyerlor i've just tried and it's a good workaround. Thanks for all.
But I think it's just workaround as in this mode QField seem to save feature after each field change and it slow down the UI, for exemple drop down list display not smooth as in the normal mode. So at the end implementing the QGIS current_value() fonction would be probably better.
