### ISSUE TITLE
editing geometry of point layer asks for vertex edit

### ISSUE THREAD

**Issue by ARBkey** [opengisch/QField#1139]
Qfield dev version 12.7.2020

When editing the geometry of a point (gpkg in my case) layer the software enters vertex edit mode.  After clicking bottom right icon again a couple of times vertex editing will be exited and  editing of the actual point geometry will be allowed. Skipping straight to point geometry edit in this case seems sensible . 

![Screenshot_20200712-092144_QField Dev](https://user-images.githubusercontent.com/64572560/87235626-5824e800-c421-11ea-887f-a0636b404750.jpg)

**Comment by signedav** [comment]
I can reproduce that. It was better behaving on 1.5.3.

**Comment by nirvn** [comment]
@ARBkey , in the forthcoming QField 2.0, a new move feature functionality has been added which makes moving points much, much easier than going through the vertex editor tool. Closing this.
