### ISSUE TITLE
Double appearance of newly added values (Relation Reference)

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#114]
Adding new values from within the referencing table to the referenced table works fine - BUT the newly added value appears twice (at the beginning and at the very end) in the drop down list. This disappears with the entering of the next value. Not very problematique but also not beautiful ;D.

## Video showing the problem
https://youtu.be/91ONiKk7Y8Y

## the project (withou the map layer pk25_ganzeSchweiz)
[add new name.zip](https://github.com/opengisch/QField/files/813799/add.new.name.zip)

**QField version:** [0.9.6]

**Comment by signedav** [comment]
This is not the case in later versions. Otherwise feel free to reopen. Thanks.

**Comment by signedav** [comment]
![WhatsApp Image 2019-11-19 at 08 41 55](https://user-images.githubusercontent.com/28384354/69126822-5a5cbf80-0aa9-11ea-8131-f9fdcb0801cb.jpeg)
