### ISSUE TITLE
Bad display of relation widget

### ISSUE THREAD

**Issue by Emic37** [opengisch/QField#1145]
@nirvn 

There is a small issue in the display of the relation widget. 

As you can see on the screenshot,  this problem doesn't appear when there is only one child entity. The problem appears when there is two or more child entities. 

![Screenshot_20200719-184420_QField](https://user-images.githubusercontent.com/2921424/87880303-f7814680-c9f0-11ea-9d5a-4c509756a71c.jpg)

**QField version:** 1.6.0 and previous versions

**Comment by nirvn** [comment]
By bad display you mean items' borders are overlapping with each other?

**Comment by Emic37** [comment]
@nirvn thanks for reply. yes, that's it.

**Comment by nirvn** [comment]
@Emic37 , there's been a fair amount of improvements in this area, are things better?

**Comment by nirvn** [comment]
This has been fixed in latest QField 2.0 beta.
