### ISSUE TITLE
Legend indentation and size

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#115]
A picture says more than 1000 words

![image](https://cloud.githubusercontent.com/assets/588407/23756598/7ab42868-04e4-11e7-8d64-964fd2a120b5.png)

**Comment by signedav** [comment]
Is the issue that the symbols are missing?

**Comment by signedav** [comment]
Hi @m-kuhn 
You don't have to write 1000 words, but at least around 30? :smiley:
