### ISSUE TITLE
QField crashes with value relation lists from wfs

### ISSUE THREAD

**Issue by monodo** [opengisch/QField#1157]
QField crashes when relational value list defined in project

### Reproduction Steps:

1. Add a spatial WFS layer A in a new project
2. Add a second non-spatial B layer 
3. Define a relational value
4. Try to select a feature...
### Expected behavior:

[Describe expected behavior here]

If not supported, do not freeze but output a message saying it's not supported

### Observed behavior:

Freezes QField

### Screenshots and GIFs

None

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.5.3 010503992 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes] 
* Problem can be reliably reproduced, doesn't happen randomly: YES
* Problem happens with all files and projects, not only some files or projects: [Yes/No] Don't know

**Comment by m-kuhn** [comment]
Can you try this with 1.6.1 and if it still crashes add a project that shows this behavior?

**Comment by monodo** [comment]
On 1.7.6 problem is still there, any plan to fix ?

**Comment by m-kuhn** [comment]
Are you able to provide a sample project?

**Comment by monodo** [comment]
Sent by mail

**Comment by nirvn** [comment]
This has been fixed for forthcoming QField 1.9.
