### ISSUE TITLE
Photo Naming

### ISSUE THREAD

**Issue by sgraham3** [opengisch/QField#1158]
Qgis 3.14
QField Sync 3.1.10

Name in attribute table and photo its self don't match

'DCIM/test-pics_'||now()||'.jpg'

test-pics_2020-07-23T102237.897.jpg       in DCIM dir
test-pics_2020-07-23T10:22:37.897.jpg     in attribute table

Iam not sure if its a setting on the phone that can be changed or something else coning on.

**Comment by m-kuhn** [comment]
Have a look at https://github.com/opengisch/qfieldsync/issues/163

**Comment by signedav** [comment]
It seems that the photo is stored with the name accepted by the storage (with removed signs). What should be done?
- Store the (wrongly edited) path from the photo in the attribute, so everything works, but with a slight different name than defined
- Write an error when the name the photo has been stored with differs from the one evaluated from the definition

I think anyway we could improve the behavior...

**Comment by nirvn** [comment]
Sure does look like an OS issue handling ':' characters in file names. Closing as @m-kuhn provided a link to a better filename expression a while back and the user has gone radio silent.
