### ISSUE TITLE
Input Lat/Long or UTM coordinates to create point or vertex

### ISSUE THREAD

**Issue by gispro168** [opengisch/QField#1163]
It would be very useful to be able to input Lat/Long or UTM coordinates to create point or vertex because this is needed for many use cases.

**Comment by nirvn** [comment]
With the newly pushed go to coordinate feature, it's possible to use that to move the cursor to a precise position. It can be used while digitizing, e.g.:
![Peek 2020-08-01 18-27](https://user-images.githubusercontent.com/1728657/89100853-cc511b00-d424-11ea-9a1c-ccbee792f5b8.gif)

**Comment by nirvn** [comment]
@gispro168 , have you tried the goto coordinate feature yet? Is that satisfying your needs?

**Comment by suricactus** [comment]
I am closing this due to lack of feedback. If needed, we can file a new issue. Thanks nirvn for this feature!
