### ISSUE TITLE
Average GPS positioning

### ISSUE THREAD

**Issue by gispro168** [opengisch/QField#1164]
To be able to set time interval for average GPS position would be very useful to ensure location precision.

**Comment by m-kuhn** [comment]
Great request !

**Comment by Benwaa74** [comment]
Another vote for this functionality. This would be a very useful option.

**Comment by shuttercat** [comment]
+1 for this enhancement request - It would make my data collection under tree canopies go much better

**Comment by m-kuhn** [comment]
This functionality has been implemented and is available since https://github.com/opengisch/QField/releases/tag/v2.2.0

See the documentation https://docs.qfield.org/how-to/gnss/#averaged-positioning-functionality
