### ISSUE TITLE
Multipage form display issue

### ISSUE THREAD

**Issue by MMR100** [opengisch/QField#117]
When adding a new point, the form with several pages (i.e. several containers) has a display issue. 
On the attached picture, you can see both current page ("building information")  and previous page ("population") of the form. 

### Screenshots and GIFs

![screenshot_20170314-190558](https://cloud.githubusercontent.com/assets/26409106/23901123/4653d76c-08ea-11e7-933f-449dab16666e.png)

**QField version:** [0.9.9]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes (previously, my forms were covering the whole screen, now it remains on the right side only)]

Thanks to all the developers and long life to QFIELD !

**Comment by m-kuhn** [comment]
Thanks for the report.

Until it's fixed, you can revert to the previous (full screen) behavior in the settings.
