### ISSUE TITLE
App crashes on Motorola E4 Plus

### ISSUE THREAD

**Issue by geoteacher** [opengisch/QField#1172]
Qfield is crashing when panning or zooming before map is entirely loaded.

### Reproduction Steps:

1. Open project
2. Pan/zoom or both
3. Pan/zoom again before map canvas is completely loaded.

### Expected behavior:

Map starts the drawing process over/reloads

### Observed behavior:

App crashes

**QField version:** 1.5.3
## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by nirvn** [comment]
@geoteacher , can you try the latest version (1.6.1; available in the google play store if you activate the beta channel), you crash might already be fixed.

**Comment by geoteacher** [comment]
1.6.0 crashes while opening on my phone

**Comment by geoteacher** [comment]
1.6.1 I meant

**Comment by nirvn** [comment]
@geoteacher , can you try if the armv7 APK here (https://github.com/opengisch/QField/pull/1161#issuecomment-663825326) fixes the crash on opening?

**Comment by geoteacher** [comment]
Still crashes on opening

**Comment by nirvn** [comment]
Are you able to produce a catlog of the crash?

**Comment by grdaveygrd** [comment]
I seem to have the same problem with a Samsung Galaxy Tab S2 - Android 7.  Versions 1.6.0 and 1.6.1 crash immediately on loading. I have to go back to version 1.5.3 to have something usable.

**Comment by VxTedxV** [comment]
@grdaveygrd I think your issue is more related to #1125

**Comment by violetlatch** [comment]
Same problem on Samsung Galaxy Active Android 5.1.1. Just “Unfortunately QField has stopped” message

**Comment by suricactus** [comment]
Is this still an issue?
