### ISSUE TITLE
Unable to close attribute form

### ISSUE THREAD

**Issue by geo0000-9** [opengisch/QField#1173]
QField v1.6.0 ~1.6.1

In the attribute form, after long-pressing and deleting the feature to be deleted, the attribute form cannot be closed by tapping the device back button or the map.

**Comment by m-kuhn** [comment]
CC @nirvn

**Comment by nirvn** [comment]
Looking into it. QML focus issue.

**Comment by nirvn** [comment]
One question: "long pressing and deleting feature" is on master only, are you using that? If not, I might be misunderstanding your description, a steps to reproduce list would be useful.

**Comment by gio999-com** [comment]
I am using the master. I tried using it again, but when I press the back button on my device, the toast asking if I want to close the app appears in priority.
Procedure.
1. Place one point feature
2. Tap to display the attribute field
3. Press and hold to delete
As the attribute form is still displayed, I try to close it by pressing the back button, but I can't close it.

However, there were some patterns that I was able to close by pressing the back button.

**Comment by m-kuhn** [comment]
Can you try with the apk from https://github.com/opengisch/QField/pull/1175#issuecomment-665590288 (arm64-v8a)?

**Comment by geo0000-9** [comment]
When I tried, the attribute form closed correctly.
Thanks. I look forward to the official release.

**Comment by m-kuhn** [comment]
@geo0000-9 does this also affect versions 1.6.0 and 1.6.1 or just master?

**Comment by geo0000-9** [comment]
I tried it on the master and it worked fine. It's fine.
