### ISSUE TITLE
Rendering speed of raster images considerably slower with Qfield 1.6.1

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#1178]
Since I updated from QField 1.5.3 to 1.6.1 i observed that the rendering speed of my orthofotos is significantly slower than it was before.
I have an orthofoto with a spatial resolution of 20cm. At 1:500 scale with QField 1.5.3 it took approx. 4-5secs to load when i moved the canvas. This time has almost doubled with Qfield 1.6.1

**Comment by m-kuhn** [comment]
What format are your images in?
Do they have pyramids?
Is there any reprojection going on?

**Comment by meyerlor** [comment]
Format: GPKG - Byte - Eight bit unsigned integer
createt with gdal_translate from TIFFS with:
gdal_translate.exe --config OGR_SQLITE_SYNCHRONOUS OFF -co  APPEND_SUBDATASET=YES -co TILE_FORMAT=PNG_JPEG -co RASTER_TABLE=Orthophoto -co ZOOM_LEVEL_STRATEGY=AUTO -a_srs EPSG:25832 -of GPKG  inputfile.vrt output.gpkg

gdaladdo.exe --config OGR_SQLITE_SYNCHRONOUS OFF -r AVERAGE output.gpkg 2 4 8 16 32 64 128 256

Pyramids: yes
![grafik](https://user-images.githubusercontent.com/15894401/88921873-8a32a880-d26f-11ea-89bd-d7a2d0f34953.png)

no reprojection (source reference system is epsg:25832 as is the project crs)

**Comment by m-kuhn** [comment]
This is almost certainly related to the updates of gdal and/or qgis. Not sure where to start looking exactly.
How does webp compare to that?

**Comment by meyerlor** [comment]
i changed the line of my script to:
gdal_translate.exe --config OGR_SQLITE_SYNCHRONOUS OFF -co APPEND_SUBDATASET=YES -co TILE_FORMAT=WEBP -co RASTER_TABLE=Orthophoto -co ZOOM_LEVEL_STRATEGY=AUTO -a_srs EPSG:25832 -of GPKG inputfile.vrt output.gpkg

so the Tiffs are stored as webp inside the geopackage but it does not make a difference. changing the map canvas still needs ~ 10sec to load the image (when deactivating the orthofoto through layer control panel, rendering speed is fast again (~1-2sec)

**Comment by m-kuhn** [comment]
I am a bit at loss what could be the reason for that.
Are you completely sure you tested exactly the same project without any changes?

**Comment by meyerlor** [comment]
yes, i opened exactly the same project with two different versions of QField (first with 1.5.3 and then updating it with the .apk from the current release. I can send the project via a cloud link if you want (~2GB)

**Comment by m-kuhn** [comment]
Did you also notice a slowdown going from qgis 3.8 to 3.10 around last december? I'm still thinking that it's very likely related to a gdal/proj/qgis update.

If you want to move this forward and have us look into it in more detail, please contact us by mail.

**Comment by meyerlor** [comment]
no, i could not observe a slowdown, i QGIS it is rendering almost instantly. I will send you an email!

**Comment by VxTedxV** [comment]
I notice a slow down too. I made some tests on the exact same project :
- opening the project : **0'20"** on v1.5.0, **1'13"** on v1.6.2
- some zooming/paning, almost 0'02" each version at different scales, with rasters shown with scale dependancy
- paning on orthophoto at same scale to compare : **0'02"** on v1.5.0, **0'04"** on v1.6.2

**Comment by nirvn** [comment]
@VxTedxV , if you want to help the project out, you can reduce this to a _single_ raster compare the time it takes to open that single raster project. It'd help out to understand whether the regression is raster-only (and if so, format specific or all formats) vs. vector and raster.

**Comment by VxTedxV** [comment]
I will do this as soon as I can (in few days I think).

**Comment by meyerlor** [comment]
I took some "benchmarks" to compare the different versions. This are my results:

QField 1.5.3  
Tiff, without Pyramids.....GPKG, without Pyramids.......GPKG with Pyramids
opening          <1sec ...................................8sec .............................................. 8sec
zooming          ~1sec....................................2-3sec............................................3-5sec
paning             ~1sec.......................................2-3sec............................................2-3sec

QField 1.6.2  
opening            1-2sec....................................10sec............................................9sec
zooming            1-2sec....................................5sec............................................6sec
paning                2sec........................................5sec............................................5sec

I loaded one orthofoto with a spatial resolution of 20cm pixel size and an extend of 1km*1km.
Original Tiff size: 73MB

Interesting side note: GPKG with pyramids has a tendency to be slower than without pyramids

**Comment by m-kuhn** [comment]
@VxTedxV / @meyerlor could you test with #1211 ?
