### ISSUE TITLE
Checkboxes remain checked between different entries of the same form

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#118]
When using checkboxes in QField there is a wrong (and dangerous) behaviour. If upon the first entry you check e specific checkbox, it will also appear checked when entering the second entry (without using the "remember value functionality"). The value in the second entry of that specific checkbox will however be NULL and not the value representing the checked state. So in the UI QField suggests that a checkbox is checked but in the data this checked state is not saved. This is pretty bad, because it is difficult to notice that you are not saving any data. 

**QField version:** [0.9.6 and 0.9.9]

**Comment by m-kuhn** [comment]
Thanks for the report, this sound serious.
I'll have a look towards the end of the week

**Comment by saemiw** [comment]
Thanks. that would be great. Let me know if you need more information.

**Comment by saemiw** [comment]
I can confirm the bugfix. Everything works fine with 0.9.10. Thanks for the super-fast fixing!

**Comment by saemiw** [comment]
Sorry, I have to come back to this bug. It doesn't seem to be completely solved:

When you check a box on QField and save the edit. Then open that same point by tipping with your finger on the point. The checkbox appears "unchecked" in the form, even though the data it is correctly stored as checked. (we tried with QField v 0.9.10)

Another thing: When you check a checkbox and use the functionality "remember value for next entry" (i.e. the checkbox at the end of the line in the entry form). The checkbox will not appear as checked in the next entry (even though you told QField to remember the checked value).

**Comment by saemiw** [comment]
This bug report should be reopened. There are 2 possibly related issues remaining:

- If you check a checkbox and look at the point in the identify window the checkbox does not appear checked, even though it is in the data
- You check a checkbox and also check the "remember last value" checkbox. During the next entry you expect the checkbox to be active because you chose the "remember last value" option. In fact the checkbox is not active and a "not checked" is written into the data.

The video below shows the behaviour and the picture shows the associated attribute table:
https://youtu.be/gFGuB6Woscg
![checkbox bug](https://user-images.githubusercontent.com/20398621/31997774-7870b252-b98d-11e7-8e6b-a9449016c328.PNG)

QField version: [0.10.1]

**Comment by gaby-h** [comment]
I tested this issue and can confirm the bugfix. Thank you!
