### ISSUE TITLE
Editing function is available and shows errors for vectortiles layer

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField#1180]
I just tried my vectortiles for QField. I created the following two layers.
- WASAC RWSS - our vectortiles layer
- Streets - added by Maptiler plugin. It consists of MapTiler Planet and background layer

![Screen Shot 2020-07-31 at 20 04 42](https://user-images.githubusercontent.com/2639701/89029426-65226080-d369-11ea-9c16-930b9061d767.png)

When I select `background` layer, a button for topology editing function appeared. And I can start to edit. I will be error when I tried to save. It says `unable to save`.

![Screen Shot 2020-07-31 at 20 05 05](https://user-images.githubusercontent.com/2639701/89029700-f2fe4b80-d369-11ea-8434-7ce8b2f85541.png)

When I double-click background layer, it also shows `Start tracking`. I don't know what's happening.

![Screen Shot 2020-07-31 at 20 10 47](https://user-images.githubusercontent.com/2639701/89029826-30fb6f80-d36a-11ea-8d45-e3b0d32c93a8.png)

Let me attach my QGIS project here. You can try
[rwss_vt_map.zip](https://github.com/opengisch/QField/files/5006714/rwss_vt_map.zip)

I think QField might consider some of vectortiles layer as editable layer??

**QField version:** 
Version 1.6.1

**Comment by JinIgarashi** [comment]
I forgot to write how it should be. I think editing functions should not be available for vectortiles layer.

**Comment by m-kuhn** [comment]
Hi,

I just had a look at the project. The background layer is not loaded because the data is not there. It's a geojson "vector" layer. Use QFieldSync to prepare the data and copy it along.

The only "vectortiles" layer is the MapTilerPlanet layer which cannot be selected and also not edited.

What we should improve is that invalid vector data sets can not be edited. On the vectortiles front everything looks good as far as I could see now.

**Comment by JinIgarashi** [comment]
I also just confirmed `background` layer is just `geojson` layer which is provided by MapTiler plugin. And it became invalid vector layer because there is no MapTiler plugin. I think this is the issue of MapTiler plugin... They should include background layer within their vectortiles, I think.

But it is also better to implement your idea `that invalid vector data sets can not be edited`. This error might happen for all of invalid vector layers on QField.

By the way, when I tried `Package for QField`, there was the below error...
`AttributeError: 'NoneType' object has no attribute 'dataSourceUri'`, this `NoneType` means vectortiles? I am not sure...
```py
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'dataSourceUri' 
Traceback (most recent call last):
  File "/Users/jin_igarashi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/package_dialog.py", line 118, in package_project
    offline_convertor.convert()
  File "/Users/jin_igarashi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/offline_converter.py", line 129, in convert
    if layer_source.action == SyncAction.OFFLINE:
  File "/Users/jin_igarashi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/layer.py", line 95, in action
    return self.default_action
  File "/Users/jin_igarashi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/layer.py", line 111, in default_action
    if self.is_file:
  File "/Users/jin_igarashi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/layer.py", line 129, in is_file
    elif os.path.isfile(QgsDataSourceUri(self.layer.dataProvider().dataSourceUri()).database()):
AttributeError: 'NoneType' object has no attribute 'dataSourceUri'


Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.14.1-Pi Pi, de08d6b71d 

Python Path:
/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python
/Users/jin_igarashi/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jin_igarashi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Users/jin_igarashi/Library/Python/3.7/lib/python/site-packages
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.14.app/Contents/Resources/python
/Users/jin_igarashi/Library/Application Support/QGIS/QGIS3/profiles/default/python
/private/var/folders/xl/b10m05611b99ky2f1hd6s7zw0000gn/T/tmp6hd9e68v
```

**Comment by m-kuhn** [comment]
Looks like the qfieldsync plugin really has a problem with vector layers
