### ISSUE TITLE
Point feature deletions.

### ISSUE THREAD

**Issue by RAFALCO** [opengisch/QField#1189]
With qfield 1.6.1 it seems impossible to remove, 2 or more, point entities.
For the first entity it works.
For the following ones this indicates that this is impossible.
To be able to delete another, you must modify it, then delete it.
Do you have the same problem?

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
Can you be more precise about the "indicates that this is impossible". Is there an error message?

**Comment by RAFALCO** [comment]
the message is: "failure to delete entity"

**Comment by RAFALCO** [comment]
there is also:
Provider errors: OGR error deleting feature (nomber)

**Comment by nirvn** [comment]
@RAFALCO , feature deletion has been revamped in upcoming QField 1.7. You can test it by installing the proper APK for your smartphone here: https://github.com/opengisch/QField/commit/391b7dcb8bcc07fb20e7889cd136d2360cdc05b6#commitcomment-41162721 (if you're phone is recent enough, go for arm64_v8a).

The upgraded way to delete feature(s) is via touching and holding your finger over a feature in the list to activate multi selection mode. Select one or more features, then hit the delete button (relocated to the navigation bar above the list).

If you want to test that is working fine for you, it'd be great.

**Comment by chakasasacha** [comment]
Hi ! I have exactly the same problem since yesterday ! The solution you proposed is running well ?
Have a nice day! :)

**Comment by m-kuhn** [comment]
Fixed in 1.6.4
