### ISSUE TITLE
Changelog on Startup and in About Dialog

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1192]
On the 1.0 Matterhorn release we created a nice changelog on startup with an announcement of our crowdfunding. 
![changelog](https://user-images.githubusercontent.com/233663/65707981-e1834d80-e08d-11e9-8eb8-ae228b44f2e6.jpg)
We still have the code #624 - just disabled.

It would be nice to have a changelog back.

### Where should the changelog appear? 
I suggest it should pop up on the first start after upgrading and accessible over the About in the Menu. Here we maybe can think about a redesign of the About dialog as well.

### How should it look like?
I think @suricactus already checked out the possibility to get the changelog directly from the GitHub Release page. This would be nice, with all the images etc. Open is, what should be displayed when there is no internet connection (what is not that often the case I think, since the user opens mostly the app right after upgrading it).

### What about the crowdfunding announcement?
I suggest not to have any announcements but keep open the possibility to place it there if we would have another nice crowdfunding like QField Love.

Thanks for inputs.

**Comment by suricactus** [comment]
This is using `StyledText` and python's `markdown` module to convert to simple HTML. In Qt5.15 markdown is natively supported.

However, there is no way to control the image width in both cases in sensible way, so whoever is creating the releases notes on GitHub should keep in mind not to exceed some sensible maximum, according to device width.

The changelog is automatically generated from the GitHub API and includes all the current minor versions (e.g. 1.6.x or 2.2.x)

![Peek 2020-08-19 23-12](https://user-images.githubusercontent.com/2820439/90685333-4e896e00-e272-11ea-8ee7-6271311e05fc.gif)

**Comment by signedav** [comment]
Looks great @suricactus Thanks.
In the start screen mentioned above, would it be in the container where already is a change log or would look different?

**Comment by suricactus** [comment]
It is literally the same popup on the startscreen. It does not popup for the same patch release anymore once you press  "That's cool". Once there is a change in the version number, it shows once again. 

It means I cleaned up a bit the popup code, but I believe once there is a new campaign, we can reintegrate what is missing.

Now the only missing thing for me is a link "Previous releases" that opens the https://github.com/opengisch/QField/releases page.

**Comment by m-kuhn** [comment]
@suricactus is this fixed?

**Comment by suricactus** [comment]
It is, closing.
