### ISSUE TITLE
Default value is not updated in QField

### ISSUE THREAD

**Issue by Fertuesta25** [opengisch/QField#1193]
Default value is not updated in QField

In QGIS:
![image](https://user-images.githubusercontent.com/59838508/89224241-bf0b6c00-d59d-11ea-8111-2d77d014039d.png)
The DAP is updated based on the CAP without any problem.

In Qfield:
![image](https://user-images.githubusercontent.com/59838508/89224803-bc5d4680-d59e-11ea-8fc7-365b06dd0a26.png)
DAP is not updated based on CAP.

In this link I attach the project https://drive.google.com/drive/folders/1xcc1hQjjqRBhzxEUZY9RSPJnAvEipMnN?usp=sharing

Additional information:
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by ARBkey** [comment]
Hi @Fertuesta25 , I'm currently seeking crowd funding partners to see this feature implemented. Feel free to get in contact if you would like to contribute.

**Comment by Fertuesta25** [comment]
I would like to contribute exclusively for this functionality. Could you tell me how to do it?

**Comment by m-kuhn** [comment]
@ARBkey @Fertuesta25 I hope you got in touch directly. If you need help to setup a contact, please write to info@opengis.ch

**Comment by Fertuesta25** [comment]
@m-kuhn Thank you, already send a message to info@opengis.ch.
