### ISSUE TITLE
Unable to measure the specified ellipsoid

### ISSUE THREAD

**Issue by geo0000-9** [opengisch/QField#1194]
QField master

I opened the properties of the QGIS project file and specified the ellipsoid I wanted to measure in the measurement section.
I was able to measure it correctly in QGIS, but it was not reflected in the QField measurement tool.
I've seen this phenomenon in versions prior to the master.

**Comment by VxTedxV** [comment]
Maybe related to #1090 ?

**Comment by geo0000-9** [comment]
That's right. It's the same as this.
