### ISSUE TITLE
Bad rendering of legend with SVG

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#1196]
Symbols contening SVG are well rendered on the map but not in legend. Works well in QGIS, not in QField

Create a legend based on rules. Rule 1 contain SVG in symbology, rule 2 none.

### Expected behavior:

As in QGIS, SVG are rendered in legend as in the map

### Observed behavior:

SVG symbols are well rendered in the map. In the legend, rule 1 is rendered as rule 2, without SVG.

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/30288828/89290146-b2981980-d658-11ea-961e-a69c74916102.png)
![20200804_134803](https://user-images.githubusercontent.com/30288828/89290691-8630cd00-d659-11ea-81e8-92c4b64c3855.jpg)

**QField version:** 1.6.2

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: **NO** (since a very looong time but a bit more annoying since legend is entirely deployed in v1.6)
* Problem can be reliably reproduced, doesn't happen randomly: yes
* Problem happens with all files and projects, not only some files or projects: yes

**Comment by nirvn** [comment]
@VxTedxV , that'll happen for as long as you do not provide your rules a proper label :)

**Comment by VxTedxV** [comment]
That's it ! Thanks :)
