### ISSUE TITLE
self built v1.5.3 apk crashes on start

### ISSUE THREAD

**Issue by geo0000-9** [opengisch/QField#1198]
I want to output the v1.5.3 apk file.
I got the QFieldSDK image with tag 20200421 based on sdk.conf and ran it and the apk file could be output.
However, the application crashes immediately after installing and running.
The following are the steps I performed.

1.docker pull opengisch/qfield-sdk:20200421
2.git clone https://github.com/opengisch/QField.git
3.cd QField
4.git checkout v1.5.3
5.git submodule init
6.git submodule update
7.TAG=20200421　
8.export APP_VERSION="v1.5.3"
9.docker run -v $(pwd):/usr/src/qfield -e APP_VERSION=$APP_VERSION opengisch/qfield-sdk:$TAG /usr/src/qfield/scripts/docker-build. sh --rm

Is this a bad QField SDK to use?
If so, I would like to know the QField SDK for the build.
Or is it a bad execution procedure?

**Comment by m-kuhn** [comment]
Your best bet when the app crashes is to have a look at adb logcat.

**Comment by geo0000-9** [comment]
Do the SDKs and build procedures match?

**Comment by geo0000-9** [comment]
[logcat.txt](https://github.com/opengisch/QField/files/5033257/logcat.txt)

Here's a text file of the results of the run. I'm attaching the results since the crash.
I'd appreciate it if you could tell me which parts of the file are incomplete.
(I haven't changed any of the sources.)

**Comment by m-kuhn** [comment]
The log is no that verbose unfortunately.

Two comments on the commands you printed above:

 - The `ARCH` definition is missing
 - There is an extra `10.` in the `APP_VERSION` definition

**Comment by geo0000-9** [comment]
10. is a typo. Sorry.
How do I define what should be in the ARCH?

**Comment by m-kuhn** [comment]
>        What should I define for ARCH?

One of https://github.com/opengisch/QField/blob/master/.travis.yml#L54-L70
Depending on the device you are using

**Comment by jlgranda** [comment]
Hi everybody, I try to build APK from local changes on QField source code. I get 

docker: unauthorized: authentication required.

Any advice?

**Comment by jlgranda** [comment]
Hi @m-kuhn, any idea https://github.com/jlgranda/QField/runs/1052841994#step:4:293

**Comment by jlgranda** [comment]
Hi everybody, the problem no is QField code, the instruction get code, get docker and run works. In my fork I add quazip for support  zip files into QField. This lib is the problem. Any idea for no use quazip?

**Comment by jlgranda** [comment]
>     1. is a typo. Sorry.
>        What should I define for ARCH?
in docker_build.sh
# Set default values if missing --> values to try armv7 x86 arm64_v8a
[[ -z ${ARCH} ]] && ARCH=armv7

**Comment by m-kuhn** [comment]
Is this still an issue?
