### ISSUE TITLE
Slow map to the Scrolling

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#120]
Slow map to the Scrolling. There was a long think. On the desktop versions of everything quickly. Maybe there are plans to make faster qfield? For example, geopaparazzi (mbtiles) or AvenzeMap (Geospatial PDF) works without blockages. This is important when you work in the field.

**Comment by m-kuhn** [comment]
QField supports mbtiles, geopackage (not sure about pdfs). It's up to you to configure a project accordingly. QFieldSync offers the possibility to generate a geopackage for you.

The difference is, that an image will only be painted to the screen once the rendering finishes. In QGIS it's done after a fixed interval. Both approaches have their up- and downsides, depending on the datasource.

In the most recent version you can switch the rendering approach to a fixed interval in the settings.
