### ISSUE TITLE
several QField versions on one device

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#1200]
As it's possible to install Qfield and Qfield betas on one device, is it possible to install two final versions of QField on the same device ?
Why ? As a pioneer/coach for my team, I would like to keep a stable version of QField to demonstrate AND test last versions with enhancements and make easier comparisons on performance between two versions for example.
I know that one of the tricky parts is the location of datas stored (read and write, on external SDcard)...

**Comment by signedav** [comment]
There is the last master build available as "QField - Unstable" on the playstore.

To get older builds you can browse https://download.opengis.ch/qfield/ci-builds

Is that what you need?

**Comment by VxTedxV** [comment]
no : I know where to find it but I would like to install at least two master versions on one device, and preferably sharing the same read&write folder in order to be able to use the same projects (with all their heavy data) on different QField versions (for example an old stable one for everyday use and the most recent one for testing before deploying on other devices).

**Comment by m-kuhn** [comment]
Android allows to install one version of a package. A package is defined by its name. (see https://github.com/opengisch/QField/blob/master/android/AndroidManifest.xml#L2 --> `ch.opengis.qfield`). For pull requests and master we change this name to be able to install it in parallel. As far as I understand, this is therefore not possible.

Apparently, there are tools out there to change this name for an existing package, using your favorite search engine will point you to a couple of different approaches to achieve that.

**Comment by VxTedxV** [comment]
Thanks for the answer.
Ok so it's possible outside of QField. But it doesn't allow to use only one read/write folder for two versions.
Even if it would be a big change, is it thinkable to make a folder outside Qfield writable, **selected when installing a version**, instead of the one configured by default ?

**Comment by m-kuhn** [comment]
Are you referring to access restrictions on external storage here?

**Comment by VxTedxV** [comment]
yes

**Comment by VxTedxV** [comment]
With a folder writable outside of Qfield folder on external storage, unstalling would prevent deleting datas. Switching between versions would be easier. Selecting a preferred folder would allow to share writable data between several Qfield versions.

**Comment by m-kuhn** [comment]
If you use internal storage, that will work already.

On external storage there is the possibility to gain read/write access for any folder through native android functionality. However, it is unclear how this maps to "file based access" that the qgis/gdal backend uses, it seems that this is an abstracted file interaction through some android functionality. If this is the case, it would be possible to a) create temporary copies of all files in a folder and copy them back later on through the android api or b) remap gdal file access functions to these android internals, but that would require a thorough research about feasibility first.

**Comment by VxTedxV** [comment]
I don't think so. For example, in QField beta, when I open a project stored in QField master folder, I can't save/modify datas.

**Comment by VxTedxV** [comment]
I don't think so. For example, in QField beta, when I open a project stored in QField master folder, I can't save/modify datas.

**Comment by m-kuhn** [comment]
Correct, so to be clear

> If you use internal storage, that will work already.

This is reflecting on the status quo. Use a location in the internal storage which is not application specific.

> 
> On external storage there is the possibility to gain read/write access for any folder through native android functionality. However, it is unclear how this maps to "file based access" that the qgis/gdal backend uses, it seems that this is an abstracted file interaction through some android functionality. If this is the case, it would be possible to a) create temporary copies of all files in a folder and copy them back later on through the android api or b) remap gdal file access functions to these android internals, but that would require a thorough research about feasibility first.

This is a consideration on possibilities to improve the situation as a response to 

>  Even if it would be a big change, is it thinkable to make a folder outside Qfield writable, selected when installing a version, instead of the one configured by default ?

**Comment by VxTedxV** [comment]
OK. I understand there is no way to configure inside the app, a path to external storage outside QField folder in write mode.
Sadly, internal storage :
- could have a very limited capacity (not compatible with large set of data) ;
- is not the most practical way to install large set of data on multiple devices.
