### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by lucienicolier** [opengisch/QField#1204]
In the version 1.6.2 of QField, I can't use search. When you enter something the result appeared and disappeared as soon.

### Reproduction Steps:

1. Enter something you want to search
2. Enter

### Expected behavior:

To be able to select the result

### Screenshots and GIFs

![qfield_issue](https://user-images.githubusercontent.com/50236352/90043926-2081b800-dccd-11ea-9d1c-49c8f935fcaf.gif)

**QField version:** 1.6.2 (code:v1.6.2)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: I don't know
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by geomondego** [comment]
@lucienicolier I have tried with the demo project and everything is working like expected. Have you tried with other project?

![Peek 2020-08-13 15-59](https://user-images.githubusercontent.com/4389239/90150945-18358580-dd7e-11ea-961d-25488c6e7331.gif)

**Comment by signedav** [comment]
Hi @geomondego and thanks for testing.

I experienced the same. It's only when the predictive text is activated.
But this is fixed here #1208 - So we can close this issue.
