### ISSUE TITLE
Clicking the cross in the search bar closes the bar instead of clearing the text

### ISSUE THREAD

**Issue by 3nids** [opengisch/QField#1205]
Clicking the cross in the search bar closes the bar instead of clearing the text
I am expecting that I need to click outside of the bar / results to close it.

**Comment by nirvn** [comment]
@3nids , that's fixed these days. First click clears, second click closes (when empty text widget)

**Comment by 3nids** [comment]
it looks like I have the last Qfield unstable version available (but I cannot see the commit version in the about dialog)

**Comment by 3nids** [comment]
another issue, it looks like the display view is not resized anymore to its content length: 

![image](https://user-images.githubusercontent.com/127259/90101217-95d9a100-dd3e-11ea-9ff6-ec857467c503.png)

**Comment by nirvn** [comment]
Hm, that's 1.6.x right? Master has a totally different looks.
