### ISSUE TITLE
Checkbox status unchecked not honored in related table

### ISSUE THREAD

**Issue by ivankautter** [opengisch/QField#121]
Unchecked checkbox state is not inserted into new record in standalone table that participates in relation with a shapefile. Multiple records in table relate to single feature in shapefile.

### Reproduction Steps:

1. Specify a checkbox widget for integer field in related table. Checked state = 1. Unchecked state = 0.
2. Add record to standalone table by hitting + control by relation widget in form for related shapefile.
3. Input data on autogenerated form for standalone table record. Leave a checkbox widget unchecked (e.g. untouched).
4. Tap save button on form. Tap save button for related shapefile record.
5. Open QGIS map file in QGIS for Android. Confirm new records with untouched unchecked state read NULL in attribute table, not the value specified for unchecked state (in this case, 0).  Checked state will be inserted properly as are other data values.
6. Repeated steps in QGIS for Android. Confirm that unchecked state is honored. Unchecked state is properly inserted into the record.

### Expected behavior:

Unchecked state value should be inserted into field for new record.

### Observed behavior:

NULL is inserted into field for new record with unchecked state rather than specified unchecked state value

**QField version:** 0.9.10

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes (answering yes here, but all files is a rather broad criterion, not possible to test)

**Comment by signedav** [comment]
Could be related to this #139

**Comment by signedav** [comment]
Hi @ivankautter 
Can you test that with the latest [beta version](https://github.com/opengisch/QField/releases/download/v1.3.0/qfield-v1.3.0-armv7.apk)? I guess it might be fixed meanwhile. Thanks.

**Comment by signedav** [comment]
Since I did not received a feedback I close this issue.
Feel free to reopen it, if it's still pending. Thanks :+1:
