### ISSUE TITLE
How to use QField with offline PostGIS-database and 1:m tables the right way?

### ISSUE THREAD

**Issue by geomoes** [opengisch/QField#1210]
Hi,
we are using QField for field survey in the forest.
We are using 3 PostGIS-tables, one parent and two child tables. The relations are set in QGIS and the primary key fields are of data type serial. As long, as we work online in QGIS everything works fine, and we can add new parent and child data.
To make it work in QField we had to add an expression maximum( "gid" ) + 1 in the gid field of the parent-table as described in the [post from RobiFag](https://github.com/opengisch/QField/issues/1159). Without this hint, we were unable to add child-datasets because of the missing gid (to which their foreign keys point). Now it works in QField, but we run regulary in troubles with duplicate keys when we try to sync the data back to the PostgreSQL-database, that is updated also by other persons.

So we wonder, what would be the right way to work in a multiuser scenario using tables with 1:m relations so that it would be possible to sync data back to the database using QFieldSync so that PostgreSQL could care about the correct keys? 
It seems to us, that the hint with the maximum("gid") + 1 is working only in a one man scenario, since this function mimics the sequence of the PostgreSQL-database and as we saw, the risk of running into problems with duplicate keys is given.

**Comment by m-kuhn** [comment]
Hi, this is a support question.

You will find some information in the documentation: https://qfield.org/docs/prepare/add-1-n-pictures.html
Otherwise, please refer to one of the support channels. https://qfield.org/docs/support/index.html
