### ISSUE TITLE
Multiline Text type attribute is not displayed in QFIELD

### ISSUE THREAD

**Issue by ponceta** [opengisch/QField#1212]
When dealing with a postgres text type attribute, editing works but the content is not shown when interrogating a text type feature.

### Reproduction Steps:

1. Set a project with a postgreSQL text type attribute
2. Set the attribute as multiline edit widget in QGIS
3. Go offline with QFIELD SYNC

### Expected behavior:

Content of the attribute is shown in the edit form and in the viewer form

### Observed behavior:

Content is present but not shown.

### Screenshots and GIFs

![image](https://user-images.githubusercontent.com/8614223/90251015-59409f00-de3d-11ea-8ade-1f82de6a0576.png)

[projet_edition.zip](https://github.com/opengisch/QField/files/5074621/projet_edition.zip)

**QField version:** 1.6.2

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: N/A
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes (I suppose)

**Comment by m-kuhn** [comment]
Thanks for reporting, should be fixed soon

**Comment by ponceta** [comment]
Thanks for the fix!
