### ISSUE TITLE
Phone camera attribute is not displayed in QFIELD

### ISSUE THREAD

**Issue by Maxi-92** [opengisch/QField#1213]
Hi everyone! I'm new using the QField app for Android. I found a problem while I was using it. 
Since last update (to version 1.6.2.) the option for taking photos with phone camera crashes. There is no chance to press camera icon/button and that function now is off.

### Reproduction Steps:

1. Set the shapefiles and .qgs proyect in the app
2. After showed it, in a editing mode takes photos pressing some icon of camera
3. Save it, and see the pictures I took now on my personal computer or mobile device

### Expected behavior:

See the button or icon of camera

### Observed behavior:

Button does not appear and app starting to work slower

### Screenshots and GIFs

Here are some pictures of the problem I found.

Before update the app:
![a1](https://user-images.githubusercontent.com/69681907/90269113-791c9680-de2e-11ea-88e4-5b74e7895155.jpg)

After update the app:
![a0](https://user-images.githubusercontent.com/69681907/90269123-7cb01d80-de2e-11ea-9ff8-44c1a13b602f.jpg)

**QField version: 1.6.2. 

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
When I was using the 1.5.3. version, that was working fine and without crashes. After the last one (1.6.2.), changed it, and the button dissapear. **I did not change anything about my proyect or personal shapefiles.**

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
It happens everytime now with this version.

* Problem happens with all files and projects, not only some files or projects: [Yes]
I have other proyects and tested in others mobile phones and found the same problem.

Thanks for your time, and I hope understand me !!

**Comment by lcortesz** [comment]
Hi, I'm having the same issue since the update to version 1.62. I am not being able to take picture since camera option had dissapeared

**Comment by VxTedxV** [comment]
No issue for me.
QField 1.6.2, Android 9, Samsung Galaxy XCover4 (armv7)

**Comment by m-kuhn** [comment]
What's the configuration for "use a hyperlink" on this attachment field?

![image](https://user-images.githubusercontent.com/588407/90315098-f4f30d80-df18-11ea-8a2b-2f24e2b33368.png)

**Comment by Maxi-92** [comment]
Hi Matthias ! Thanks for your answer,

I have that configuration with a check mark (✓). Should be without it ?

**Comment by m-kuhn** [comment]
Yes.
Up to 1.5, this checkbox was ignored. Now it is used to show a hyperlink instead of a photo widget, see https://github.com/opengisch/QField/pull/1076 .

**Comment by Maxi-92** [comment]
Nice !

I tried  with that change and is working again ...

Thanks for the reply !

**Comment by m-kuhn** [comment]
Glad it helped.
If you could rate the app, help with [the documentation of this issue](https://github.com/opengisch/QField-docs/issues/70), translate, sponsor or just talk about it, that will be appreciated :-)

**Comment by suricactus** [comment]
@m-kuhn What do you think about showing something like "No value" in case of empty values in readonly mode? Looking at the screenshot, it looks a bit "broken". However, what is "no value" - empty string, NULL values, or both (or `undefined` in qml :) )? I would suggest both, as the users may not diffferentiate between the two in most of the cases.

**Comment by m-kuhn** [comment]
@suricactus Showing "NULL" or similar would be good. But would that help to notice the required configuration change?

**Comment by suricactus** [comment]
Not directly, but the looks will probably change the issue reporting from:

> Since last update [...] phone camera crashes.

To "not working as expected" or "showing NULL instead of the photo". Now when there is no value, it looks like the field is broken and failed to render. And it will be easier for support and to explain in the docs  too I guess:

> If you see _"NULL value"_ in the attachment field instead of your photo, most probably you need to change the field setting to... 

Since there is already the icon for "no photo" there will be clear distinctio between the two.
