### ISSUE TITLE
Spreadsheet data-file gets corrupted since QField 1.6.x

### ISSUE THREAD

**Issue by bastooo** [opengisch/QField#1218]
Hello,

I'm using QField for my thesis and experienced a bug, since I updated to the last versions. I didn't had any problems until 1.5.3 and since 1.6.0 my data-file (.ods) is getting corrupted. Well QField itself can still open and modify it, but I can't open it any longer in LibreOffice (version 6.5.4). It seems like it corrupts something in the header and I guess the source of the problem might be a newer version of a library QField is using.

I use a custom formular-layout directly at the table and I have a reference to an other shape-file, but I guess this can't be the source of the problem, cause it works like a charm until QField 1.5.3.

My current workaround is, that I deinstalled the app and returned to use the version 1.5.3 of QField.

Thats the error I get from LibreOffice after trying to open the ods data-file.
![grafik](https://user-images.githubusercontent.com/69763546/90339470-3f47bd80-dff1-11ea-9771-06dc1183cd6b.png)

**Comment by m-kuhn** [comment]
If you edit the same file from within QGIS, can you still open it from LibreOffice?

**Comment by bastooo** [comment]
Yes there is no problem, but I'm on the LTR version 3.10.8-A Coruña.

**Comment by m-kuhn** [comment]
ods writing happens through gdal, qfield 1.6.3 comes with gdal 1.3.0. Can you check in your QGIS version which gdal version there is?

**Comment by bastooo** [comment]
My QGIS-LTR installation on Linux Mint is on GDAL 3.0.4.

**Comment by m-kuhn** [comment]
It would be great to get someone else verify this behavior.

**Comment by nirvn** [comment]
I assume that this is a GDAL issue that's been fixed in version 3.2: https://github.com/OSGeo/gdal/blob/master/gdal/NEWS#L512

@m-kuhn , this might be a good reason to update to GDAL 3.2

**Comment by m-kuhn** [comment]
:+1: the release is out for 2 weeks, let's go for it

**Comment by nirvn** [comment]
Brilliant.

**Comment by bastooo** [comment]
I would love to test it, unfortunately I saw that the last release of yesterday doesn't offer any apk-assets as it used to be in the former releases. I don't use any google-services and the app isn't offered in the F-Droid store, so I cannot test right now.

Is it your intention to purposely stop offering the apks here on Github?

**Comment by nirvn** [comment]
@bastooo , the fix will make its way into QField 1.8 (ETA end of year). You can test with the following set of APKs: 

https://github.com/opengisch/QField/pull/1400#issuecomment-723370079

**Comment by bastooo** [comment]
Alright, thought it got already merged. So I'll just wait.. :)

**Comment by m-kuhn** [comment]
Is this stiall an issue?

**Comment by bastooo** [comment]
I tested it with the current version and now I'm able to open my data-file (.ods) again. So the bug is fixed. 

Thank you very much!
