### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#1230]
Apparently there is a crash when clicking the back button to exit the app. This only happens sometimes and only on Android 9 and 10 devices.

We could not reproduce it and only have the reference from submitted crash reports from users.

The following is an upstream issue report:

https://bugreports.qt.io/browse/QTBUG-85449?focusedCommentId=523367&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-523367

**Comment by nirvn** [comment]
@m-kuhn , can we close this one? I haven't seen this myself nor s it popping up on sentry these days.
