### ISSUE TITLE
Expanded state of the legend

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1234]
Until 1.6 you have been able to expand/collapse legend items like groups or layers with categorized styles.

Since it has been used rarely, accidentally and has been stuffing the GUI, the dynamic expanding / collapse functionality has been removed.

Now it's always expanded, what is not nice, since there are very long legends in some projects.

There are two possibilities:
1. Bring the old status back
2. Use the state of the stored project. If you want to switch between collapsed / expanded states, then use Map Themes

**Comment by signedav** [comment]
Where @nirvn suggested the second possibility and I support it, since it keeps the nice look of the new legend and still manages all the use cases (but I have to admit, that there are maybe use cases I don't know). 

Do you agree @m-kuhn ?

**Comment by nirvn** [comment]
(carrying on some of the stuff Dave and I discussed on hive)

Regarding possibility 1, IMHO, the effort of coding a dynamic collapsing/expanding behavior for the listview is likely not worth the effort (both in terms of initial coding and the burden of maintenance).

If we want to address that (other than saying to users/clients to adjust to the new behavior :wink:), I'd go for 2.

**Comment by signedav** [comment]
Maybe @mbernasocchi or @3nids have an opinion as well.

**Comment by m-kuhn** [comment]
1 would be a pretty complete tree view implementation?
2 is collapsed state stored in themes? and if it's possible to do it this way, isn't it similarly easy to implement 1?

**Comment by monticola2** [comment]
Is there a way to collapse the value list of a paletted/unique value raster? That really stretches out the legend.
I cannot comment on methodology but from a user perspective I would appreciate bringing back the option to collapse or extend the legend items very much. One less thing to think about when preparing projects and possibly being restricted later.

**Comment by signedav** [comment]
Thanks for your input @monticola2 

> 2 is collapsed state stored in themes? and if it's possible to do it this way, isn't it similarly easy to implement 1?
@m-kuhn as far as I understood @nirvn it's much easier.

But independent from that: Do we want to have collapsible legend items back or do we prefer anyway another solution to keep the legend tree clean from rarely used options?

**Comment by signedav** [comment]
And to your question @m-kuhn Yes, collapsed state is stored in themes...

**Comment by m-kuhn** [comment]
I think collapsible makes sense:

- The legend also has a purpose as "layer selector" this functionality can be impacted by an overcrowded legend (scrolling just to find your other layer)
- Users will often know the legend by heart, they are experts in their domain, using this on a daily bases, in this case, the symbology legend is "stating the obvious"
- We could also show the legend in the layer properties, so users could go check it out on demand

**Comment by signedav** [comment]
Sorry, my question was: Do we want to have the **option** to collapse/expand of the items while using QField, or would it be an improvement when we don't have it anymore (because of a slimmer GUI), but we take the configuration from QGIS (if expanded on Map Theme, then expand it etc.)?

I like the idea of taking it from the QGIS project, but I'm not sure about the use cases.

Btw. I like @m-kuhn s idea to have it in the layer properties. So what about: Taking the collapse state from Map Theme, but having the option to see the children in the layer properties?

**Comment by m-kuhn** [comment]
I still could very well imagine an option to show or hide the legend in the layer properties (doesn't need to be integrated like in a tree view as before). It's too easy to forget preparing the legend exactly how you like it on project preparation (see statement of @monticola2 above).

**Comment by EulenspiegelTill** [comment]
My feedback: 

@signedav proposal sound good

> * The legend items are expanded/collapsed according to how it's configured in the QGIS Project / MapTheme
> * User can go to the layer properties and overdrive it by selecting expand / collapse (On reopening project / resetting map theme it's not overdriven anymore)

what we use quite regularly is having basic information (pipelines, WMS-Layers, AV, etc) packed in a group and not visible. This information ist sometimes needed, then we uncolapsed and make the wanted layer visible. It would be nice to have only the layers expanded and visible which are needed regularly. And on the other hand to have the layer information accesible from colapsed ones.

Thanks for your efforts.

**Comment by RobinRots** [comment]
Hi,

I agree with @EulenspiegelTill . For bigger projects with many layers arranged in different groups (some of them collapsed) it's definitely a step back to have the entire legend expanded. So I'd also go for @signedav 's proposal.

**Comment by BoswachterMarc** [comment]
As a user of QField, I have for example lot's of dates of plantations/natural regeneration in the forest. And it goes back to 1850... If not collapsed in one way or the other, that view is not workable. Adding the option in the layer menu could be a solution...
Keep up the good work 😉
![Screenshot_20200901-072814](https://user-images.githubusercontent.com/57868975/91798709-cae26080-ec25-11ea-8e69-f9e0d71af67e.jpg)
![Screenshot_20200901-073340](https://user-images.githubusercontent.com/57868975/91798727-d59cf580-ec25-11ea-855f-c4e1e9fdebbe.jpg)

**Comment by BoswachterMarc** [comment]
A enhancement could be an option tot choose in a layer 'show all/show none'. That way I could ask QField to show only all plantations from 2018 (by clicking 'show none' and then activating just the 2018 feature). 
This is something I can't foresee and add to a theme ..)

**Comment by m-kuhn** [comment]
@nirvn could you describe the plan you have?

@BoswachterMarc @monticola2 @VxTedxV @EulenspiegelTill @RobinRots would you be supportive of a crowdfunding to get this done?

**Comment by nirvn** [comment]
OK, the plan would be two-fold.

First part, have the legend widget read and respect collapsed state. It'd result in:
a/ upon loading a project, have the legend widget match the collapsed / expanded state of the layer tree as saved in the project file 
b/ upon changing a map theme, match the collapsed / expanded state of the layer tree as defined in the map theme.

Second part would be to add a UX _within_ QField to expand / collapse legend items. I'm thinking of two ways to do that:
1/ add a "collapse/expand" in the layer/group properties pop up overlay
2/ possibly have the collapsed state toggle upon double clicking on a legend item (this needs further thinking as currently the double click allows for stylus devices to open the layer properties pop up, which it can't do with a long press ATM)

**Comment by RobinRots** [comment]
> @BoswachterMarc @monticola2 @VxTedxV @EulenspiegelTill @RobinRots would you be supportive of a crowdfunding to get this done?

Hi,
As much as I would love to support further development for this issue, I'm afraid I'm already stretching my small NGO's budget by supporting for the development of completer functionality for the relation widgets (https://github.com/opengisch/QField/issues/724#issue-527908861), which for now is a bigger issue for us. I do hope you'll find some other's to back this one though.

**Comment by hrdrckx** [comment]
We have quite a few users of qfield in our team and this new 'default' expanded format of the layer list makes it unusable for everyone (as with @BoswachterMarc post).
We definitely vote 
a) make layer legends collapsed by default (ie how it was previously)

**Comment by signedav** [comment]
I like the proposal 1 to have it in the layer settings.
I suggest a checkbox 
- [ ] Collapse Legend Item
like we have it for "Show on map canvas"

![Screenshot_20200914-115657_QField](https://user-images.githubusercontent.com/28384354/93072353-8d4bf180-f681-11ea-933e-eee14c05f37e.jpg)

**Comment by hrdrckx** [comment]
> We have quite a few users of qfield in our team and this new 'default' expanded format of the layer list makes it unusable for everyone (as with @BoswachterMarc post).
> We definitely vote
> a) make layer legends collapsed by default (ie how it was previously)

Further to above I would now categorise this issue as a major bug.
I've just been in the field with my team (~10 people) and we are all lovers of qfield.  However when all those devices automatically upgraded to the newest version of qfield the app has become unusable for many of the them. 

I do not understand why it now by default shows such pointless information as:
- every possible colour in the raster 
- every possible layer styling and label in a vector layer 
and then requiring expecting users to scroll through all these thousands of line items in order just to find a layer a user wants to show on screen (in our case can take up to 1-3mins each time on the qfield project we are using which has quite a few layers) 

We all love Qfield but this is completely unsustainable.
Surely we're not the only ones having this problem?

**Comment by m-kuhn** [comment]
Hi all,

We appreciate all the feedback and good ideas in here. We are aware that this is a regression compared to earlier versions and would very much like to fix this. I will add some background about why this was done and what it means for the development team of QField.

As you may be aware QField uses QGIS under the hood and QGIS uses Qt under the hood. Qt is currently used in version 5. Qt 5 is not that young any more and has a lot of functionality which is no longer supported by Qt and deprecated. The old legend was based on a deprecated module, the tree view. Using it had some implications:

 - It was not very well supporting HiDPI. This affected not only the legend but the whole app. We had to carry around a lot of extra code to make things look nice (otherwise e.g. there would have been super small icons on buttons). And even this way we still had some visible effects
 - Deprecated modules will disappear with the soon-to-come Qt 6

This change was needed to make:

 - the rest of the app look better
 - be prepared for the future
 - the code more maintainable
 - keep on delivering the high quality app you are used to

Earlier in this issue we asked for support for this implementation. We don't do advertisement. We don't collect your data. We love you and now we need you :heart: :slightly_smiling_face:. Therefore we would like to raise the awareness that to keep QField at the quality we and you expect requires a lot of maintenance work. It is of utmost importance that users who rely on QField support the development.

We have come to the conclusion that this is high priority and will therefore fix this soon.
This is possible thanks to all the people and organisations who care for QField and bought [a support contract with the sustainability initiative](https://www.opengis.ch/qgis-support/) or committed to a [recurring sponsorship](https://github.com/sponsors/opengisch).

**Comment by m-kuhn** [comment]
QField 1.7.1 ships a new legend implementation including collapsing functionality:

https://github.com/opengisch/QField/releases/tag/v1.7.1

**Comment by EulenspiegelTill** [comment]
> QField 1.7.1 ships a new legend implementation including collapsing functionality:
> 
> https://github.com/opengisch/QField/releases/tag/v1.7.1

Works pretty nice, also in combination with predefined map themes. Keep them additional layer collapsed and only expend them if you need the legend. Till is happy, thanks!  🙂

**Comment by nirvn** [comment]
@EulenspiegelTill , glad you noticed the map theme support here, IMHO very useful indeed (and something the previous legend we've replaced couldn't do).

Enjoy QField'ing! :)
