### ISSUE TITLE
Save project in QField

### ISSUE THREAD

**Issue by gispro168** [opengisch/QField#1248]
It is important that QField save current map view and current setting in the project such as layer visibility so that we can continue to work from what left behind.

**Comment by nirvn** [comment]
@gispro168 , QField 1.9 will remember last map extent as well as selected map theme when you re-open a project.

**Comment by nirvn** [comment]
The remaining enhancement requested here is implemented in https://github.com/opengisch/QField/pull/3237

**Comment by nirvn** [comment]
Implemented.
