### ISSUE TITLE
Expression controlled visibility

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#125]
When using drag'n'drop designer to build up a form QGIS Desktop also offers tabs and group containers whose visibility can be controlled by expressions. This somehow works also on QField but as soon as there is more than one container the expressions defining the visibility are somehow mixed up.

### How it works perfectly fine on QGIS 2.18.6

This video quickly shows how the form should work (mainly second part of the video):
https://youtu.be/K7Bca1u_b1k

### How QField fails
This video shows the same project fails to behave the same way on QField. The project is set offline by QFieldSync but the same behaviour is also observed for "online" project (directly copy'n'pasting of QGIS-Project and data to QField):
https://youtu.be/ZedWQGd-VTI

**QField version:** [0.9.10]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [I am not sure, but I never noticed it on previous versions]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes, we noticed it already with another project

Here you find the data and project in Case you want to check out the settings in detail.
[steinschmaetzer.zip](https://github.com/opengisch/QField/files/925176/steinschmaetzer.zip)

**Comment by saemiw** [comment]
maybe related? https://github.com/opengisch/QField/issues/134

**Comment by signedav** [comment]
Fixed in Version 0.10.5 (in Playstore for Beta-Testers or [here](https://github.com/opengisch/QField/releases/tag/release-0.10.8_5))
