### ISSUE TITLE
Empty Attribute Form in tracking

### ISSUE THREAD

**Issue by alsper78** [opengisch/QField#1255]
Since version 1.6.0 the Attribute Form appears empty when using tracking. 
(Attribute Form has no problem when adding feature in the normal edit mode.)

### Reproduction Steps:

1. Create a layer of lines with attributes.
2. Load the project on Android device and open the project in QField.
3. Long press on the linear layer in the legend, start tracking and choose the Tracker Settings.

### Expected behavior:

After the tracker settings QField shows the Attribute Form with the field widget where you can insert the values.

### Observed behavior:

After the tracker settings the Attribute Form appears but it’s empty. 

**QField version:** 1.6.4 and -dev installed from play store
**Mobile OS:** MIUI Global 11.0.5 (based on Android 10)
**QGIS Version**: 3.10.8
**PC OS:** Windows 10 

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes, version 1.5 had no problem.
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by VxTedxV** [comment]
I can confirm the attribute appears blank (no fields). The track is recorded. It's still possible to edit attributes after stopping tracking.

QField 1.6.3 Android 9
![Screenshot_20200824-191022_QField](https://user-images.githubusercontent.com/30288828/91075769-dab6df00-e63e-11ea-9598-8ee1fd6c6ee0.jpg)

**Comment by signedav** [comment]
Thanks for reporting. I can reproduce on some projects. Not on all of them (e.g. when testing on Fields layer of demo projects it works). 

With the attached project the bug can be reproduced.

I haven't investigated more yet.

**Comment by signedav** [comment]
Didn't found the issue yet but for information: the tracking.qml is not yet using `EmbeddedFeatureForm` what the other similar parts of the code use (like the relation editor or the fill ring tool).

**Comment by signedav** [comment]
Should be working with master. Feel free to reopen if there are still issues.
