### ISSUE TITLE
Multi edit - extra click to edit attributes

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#1256]
In the new multi edit form, it takes an extra click on "skip this value" to change a value. I think directly being able to change this value without a click and adjust this to "change this value" upon changing the attribute would make it more intuitive.

**Comment by signedav** [comment]
+1

Currently the widget is disabled, when the attribute is "skipped" for the edit. On clicking the label below the widget you can enable it to edit. With your proposal it should be enabled by click on the widget as well, right? So this would be the only change needed.

Beside that, I would leave it like it is.

**Comment by nirvn** [comment]
Seems like a logical and worthy UX to implement.

**Comment by nirvn** [comment]
Implemented
