### ISSUE TITLE
Synchronizing data from QField to original SpatiaLite database

### ISSUE THREAD

**Issue by michiel00** [opengisch/QField#1259]
I'm trying to get started with QField. I created a SpatiaLite database with several SpatiaLite layers in my QGIS project. Exporting that project with QFieldSync is super easy, as is (offline) editing the data in QFIELD on my tablet. When I import and synchronize the data back to my QGIS project all the data is there and everything seems fine. However, the source path of the SpatiaLite layers has changed:

Original path: C:\Users\...\Documents\Demo.sqlite
Path after synchronization: C:\Users\...\QField\import\demo2\Demo.sqlite

So, the QGISproject gets synchronized, but not the original data. Instead a new file with the same name but in a different location is created.

My questions are:
Is this supposed to happen?
If yes, what is a smooth way to make sure the original data gets updated as well?
If no, what should I do differently?

![image](https://user-images.githubusercontent.com/70256299/91269864-143f3580-e778-11ea-998f-f168e8a193fe.png)
original database

![image](https://user-images.githubusercontent.com/70256299/91270022-4b154b80-e778-11ea-8f05-f1d7dff1373c.png)
new database

**QField version:** ["1.6.4" (code: v1.6.4)]

**Comment by michiel00** [comment]
Changed from SpatiaLite to GeoPackage and the problem is solved.

**Comment by nirvn** [comment]
You shouldn't have to do this though :)
