### ISSUE TITLE
Default values for integer with text edit widget

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#126]
I have a field that is defined as an integer. When I use the standard text edit widget to define a default value of 0 QGIS will use this entry for the form generation. QField on the otherhand will not show any default value unless I enter '0' into the default value field on QGIS-Desktop. Its not a very bad issue but it's somehow inexpected because  QGIS doesn't give any hints that one should type '0'. Maybe it is possible to change the behaviour so QField behaves like QGIS?

This setting will work perfectly on QGIS-Desktop (2.18.6) but not on QField (default value is not written to form):
![qgis0](https://cloud.githubusercontent.com/assets/20398621/25084301/1b8f6bc2-235c-11e7-9ccb-716e69463d0e.JPG)

This setting is working perfectly on both QGIS Desktop and QField 0.9.10 (using text edit widget):
![qfield0](https://cloud.githubusercontent.com/assets/20398621/25084305/1d5481ea-235c-11e7-9877-001c30a8ecf7.JPG)

**Comment by signedav** [comment]
I think  this is related to that #139 ?

**Comment by saemiw** [comment]
Yes, I think so.

**Comment by signedav** [comment]
Pretty sure this is fixed. I can see the 0 :slightly_smiling_face: 
Feel free to reopen if the problem still exists @saemiw Thanks.

**Comment by saemiw** [comment]
I can only confirm the fix! @

- [ ]
