### ISSUE TITLE
Do not try to open projects that cause a crash on load

### ISSUE THREAD

**Issue by Marwe** [opengisch/QField#127]
I have a crash at starting qfield (error layer cannot be loaded can be seen shortly before, with an empty list of layers).
This leads to an unusable qfield, since qfield keeps crashing before anything could be done (e.g. change project file).

### Reproduction Steps:

1. Open Qfield, select a project that does not load properly
2. see crash 
3. start qfield
4. goto 2.

### Expected behavior:

QField could ask to open the previous project, or start cleanly without project.

### Observed behavior:

No input can be done to prevent a crash at startup from happening.

### Screenshots and GIFs

**QField version:** 29900 2.99

## Additional information:

I could reinstall the app as a workaround for now.

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No] 
    * other projects, even complex ones were loaded successfully

**Comment by Marwe** [comment]
Currently I can reproduce the crash on Desktop qgis, too (v2.18), so there may be something wrong with the project file...

**Comment by m-kuhn** [comment]
It seems this is a bug in QGIS in this case.
Please [report an issue](https://www.qgis.org/en/site/getinvolved/development/bugreporting.html) for QGIS itself. As a hint already now: make sure you provide a complete qgis project with data or it will be impossible to solve.

**Comment by m-kuhn** [comment]
Oh, I guess your idea was that QField shouldn't be trying to automatically reopen a project that is crashing it.
Reopening the issue for this...

**Comment by Marwe** [comment]
Yes, the automatic "open last project" feature gets you stuck in the crash-restart-crash cycle.
You have to uninstall QField to "reset" this config.

**Comment by m-kuhn** [comment]
for reference, the configuration can also be cleared in app -> info -> storage -> clear data.

**Comment by nirvn** [comment]
We don't auto re open these days.
