### ISSUE TITLE
QField crashes when loading XYZ tiles

### ISSUE THREAD

**Issue by geo-lichen** [opengisch/QField#1273]
I had a working project on Qfield that could no longer load XYZ tiles with one of the last updates and therefore crashed. 
On the Screenshot is the message log of my project.
I used the following CRS EPSG: 4326, EPSG: 31468 (locale data) and EPSG: 3857 for Google Satellite/OpenStreetMap.
I located the error in the XYZ tiles. I tested the following URL
Google Satellite
https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z} 
https://mt1.google.com/vt/lyrs=s&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D
OSM 
https://tile.openstreetmap.org/{z}/{x}/{y}.png
https://tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png
https://a.tile.openstreetmap.org/${z}/${x}/${y}.png 
ESRI
https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}

Test:
* New project with point layer and XYZ-Tile(Google Satellite), both on EPSG 3857. As soon as the theme is opened in QField with Google Satellite it crashes.  ("Error message": Qfield stopped - close app - give feedback).
* Only XYZ tile is loaded into QFiled -> crashes

Are there other URLs running?
Are the XYZ tiles no longer supported?

reference
_Originally posted by @m-kuhn in https://github.com/opengisch/QField/issues/1219#issuecomment-675036643_

**QField version 1.6.4:**  
## Additional information:
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]
![Screenshot_20200829-125446_QField](https://user-images.githubusercontent.com/69799875/91635302-a143f200-e9f7-11ea-9f5f-8723587be194.jpg)

**Comment by m-kuhn** [comment]
Can you check if the crash also happens if you change the project to EPSG:4326 and remove the local data?
To confirm if it's the XYZ tiles or the projection causing the issue.

**Comment by geo-lichen** [comment]
I have tried it. EPSG: 4326 works with and without local data, but not with xyz-tiles.
Here is an example map with project coordinate system EPSG: 4326, a point layer (EPSG: 4326) and Google Satellite (EPSG: 3857). It works without Google Satellite. QField breaks down when Google Satellite is activated (via map theme). Unfortunately no concrete error message. The same is with OSM and ESRI on EPSG: 3857.
Transformation the CRS from Google Satellite into EPSG: 4326 does not work :-)
![3-1bilder](https://user-images.githubusercontent.com/69799875/91988951-34e72c80-ed30-11ea-984d-d49914fe53d4.png)

**Comment by m-kuhn** [comment]
Can you download an armv7 version and try with that as well?

**Comment by geo-lichen** [comment]
I tried the last armv7 file from https://github.com/opengisch/QField/pull/1236 (from 15 days ago). The beta is running, but also breaks with XYZ-tiles.
Where can I generally find the beta version? Sorry, I'm generally a relative beginner. I tried from the following address
https://github.com/opengisch/QField/releases/tag/v1.7.0 -> qfield-v1.7.0-armv7.apk <- but is crashed after the installation.
Are the older versions still available somewhere?

**Comment by VxTedxV** [comment]
> Are the older versions still available somewhere?

[https://github.com/opengisch/QField/releases](https://github.com/opengisch/QField/releases)

**Comment by geo-lichen** [comment]
Thanks. I can install the 1.6.(4-0) version, but I can't start it.
And starting with version 1.5.3 the XYZ-tiles work again. *happy* 
![funktioniert](https://user-images.githubusercontent.com/69799875/92303466-6997f580-ef75-11ea-9869-93dea584a8b7.jpg)
