### ISSUE TITLE
Support opening GeoPDF as project in QField

### ISSUE THREAD

**Issue by nirvn** [opengisch/QField#1276]
A great enhancement would be for QField to support opening of GeoPDF (and have a file association set up). Upon opening a GeoPDF via QField, a project would be setup with the following layers:
- a 'basemap' raster layer of the PDF
- any additional vector layers from point/line/polygon features
- those additional vector layers would be searchable via the search bar

**Comment by signedav** [comment]
Here is another one regarding this #994
