### ISSUE TITLE
Point attributes stop showing at feature creation after few created points. 

### ISSUE THREAD

**Issue by topive** [opengisch/QField#1279]
Creating many point features in a project, after a while the attribute table stops displaying at feature creation and I have to swipe up to make it show or it doesn't display at all and I have to restart QField. Has something to do with image fields (memory issue?).

### Reproduction Steps:

1. Have a point feature layer with quite a few fields (in my case 3 image fields, 4 checkbox fields, 6 value map fields, 1 text field)
2. Create many point features with at least one image taken every time.

### Expected behavior:

The attributes at feature creation should show every time.

### Observed behavior:

After few point features created with images taken the attribute table should stop showing. Swiping up makes the table visible at start but after couple more point features it stops showing altogether and QField has to be restarted. 

### Screenshots and GIFs

https://gfycat.com/inexperiencedblaringgrackle
This is me continuously wiping the screen upwards until the attributes show.

QField version: 1.7.0

Android version: 9

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
I cannot reproduce. Can you provide us the project?

**Comment by topive** [comment]
Here's the project https://drive.google.com/file/d/1dTv6x2SCNeeOfKV2Pae_bJqXpqKuPOZc/view?usp=sharing

**Comment by signedav** [comment]
I still had no success, sorry. I collected random points and lines with your project but the form stayed stable.
Keep us up to date when you find out more. Thanks.

**Comment by topive** [comment]
Thank you for your effort. I'll keep troubleshooting.

**Comment by nirvn** [comment]
@topive , using QField's latest version, 1.8.3, is your issue fixed?

**Comment by topive** [comment]
We haven't had the opportunity to test it recently, but we have a larger project coming along next month, which requires using Qfield. I'll keep you updated.

**Comment by nirvn** [comment]
@topive , no news good news? :)
