### ISSUE TITLE
QField converts 'Point' features into 'PointZ' when editing geometry and into 'Point25D' features when adding new

### ISSUE THREAD

**Issue by alansaviolobo** [opengisch/QField#1281]
Given that a layer containing 'Point' geometry is exported into a qfield project. 
During field work, 
- points may be shifted on the map to reflect true location (geometry update)
- new points may be added to fill in missing data (new feature)

Incase of geometry update, points are stored as **PointZ** i.e. including elevation.
Incase of new features, points appear to be stored as **Point25D**.

The net result is that when syncing back to QGIS, the sync fails with the message:
**ERROR: XX feature(s) not added - geometry type is not compatible with the current layer.**
and no updates are copied over.

### Reproduction Steps:

1.Export a layer containing point geometries.
2. update the location of any point on qfield
3. add a new point on qfield
4. sync back to the original layer in QGIS

### Expected behavior:

The updated point and the new point should be synced back to the original layer.

### Observed behavior:

The changes are not synced. Note that if only attributes are updated, then the sync works fine.
Note the screenshot of the geometry updates table in data.gpkg. The earlier entries are Point because I have manually edited them. The later points are the result of the qfield behaviour.
![updates](https://user-images.githubusercontent.com/1202289/92195109-d33ad580-ee89-11ea-9860-1fb9e7668a7f.png)

**QField version:** 
QGIS | 3.14.1-Pi
QField | 1.7.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Not sure]

**Comment by m-kuhn** [comment]
In QField we try to store as much information as possible. If the layer is 3D and we have 3D we store 3D.

This moves the problem to the synchronization process which should either create a 2D layer if the source layer is 2D. Or silently drop the Z coordinate during synchronization. The second approach strongly depends on the provider.

In short, there are a multitude of solutions available, I don't think there is one directly inside QField but we'll be able to find one. How would you like to proceed?

**Comment by alansaviolobo** [comment]
I am inclined to agree with you. the app should capture and store as much as possible.
its better to have more than less.
The synchronizing process should have a type casting.

I have found around 3 issues current which are related to type casting when synchronizing back:
The first is around updated geometries.
The second is around new geometries created
The third was when you blank out an attr of type integer results in a malformed sql query.

All the issues result in an aborted synchronization.

**Comment by m-kuhn** [comment]
Can you open issues in the qfieldsync repository for these including a bit of context information (foremost backend provider)

**Comment by alansaviolobo** [comment]
Can i transfer this issue to that repo instead?

**Comment by m-kuhn** [comment]
If you meant to open an identical one, yes. There is no "transfer" button.

**Comment by alansaviolobo** [comment]
🙄
Ok ill copy paste...
