### ISSUE TITLE
I don't take foto

### ISSUE THREAD

**Issue by Simon38** [opengisch/QField#1284]
I can't take photos with the last version of Qfield (1.7.0 - edit by @signedav), oppennig an old project who ran with the old versions of Qfield.

![Screenshot_20200907-222157_QField](https://user-images.githubusercontent.com/33135720/92415450-33b36680-f159-11ea-9e2b-38190992b82b.jpg)

Thanks!

**Comment by signedav** [comment]
Is this only happening on an old project? Can you provide us this project?

**Comment by Simon38** [comment]
> Is this only happening on an old project? Can you provide us this project?

In a new project, I have de same problem. I think the problem is due to changes in the latest version, because I have not made any changes to the way I take pictures.

**Comment by suricactus** [comment]
Can you confirm that the project is setup properly and "use hyperlink for document path (read-only)" on the attachment field is not checked? Find more https://github.com/opengisch/QField/issues/1213 .

![image](https://user-images.githubusercontent.com/2820439/92492588-28654700-f1fc-11ea-8098-393d83b8c844.png)

**Comment by Simon38** [comment]
You were right suricatus, I had checked the field "use hyperlink for document path (read-only)", sorry and thank you very much for solving the problem. A greeting!
![Screenshot_20200909-180134_QField](https://user-images.githubusercontent.com/33135720/92624397-bf4b0580-f2c7-11ea-8974-1295f1519bba.jpg)
