### ISSUE TITLE
Unexpected appearance of HTML Widgets

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1287]
### Reproduction Steps:

1. Open attribute form apiary (screenshot 1) > widget appears (unexpected)
2. Go to tap "Issues" (screenshot 2) > widget disappears (expected)
3. Go to tab "Help" (screenshot 3) > widget appears (expected)
4. Go to tap "General" (screenshot 4) > widget disappears (expected)
5. Open another apiary point (screenshot 5) > widget appears (unexpected)
6. Open new project (screenshot 6) > widget still appears (unexpected)

| screenshot 1 | screenshot 2 | screenshot 3 | screenshot 4 | screenshot 5 | screenshot 6 | 
|----------|----------|----------|----------|----------|----------|
| ![Screenshot_20200911-065523_QField Beta 1277](https://user-images.githubusercontent.com/28384354/92864379-58c80380-f3fd-11ea-89d1-3795858ce35c.jpg) | ![Screenshot_20200911-065542_QField Beta 1277](https://user-images.githubusercontent.com/28384354/92864390-5c5b8a80-f3fd-11ea-826d-5b38d76d96ac.jpg) | ![Screenshot_20200911-065533_QField Beta 1277](https://user-images.githubusercontent.com/28384354/92864397-5e254e00-f3fd-11ea-9473-0aebf25f325b.jpg) | ![Screenshot_20200911-065555_QField Beta 1277](https://user-images.githubusercontent.com/28384354/92864422-65e4f280-f3fd-11ea-948b-4c433e692877.jpg) | ![Screenshot_20200911-065603_QField Beta 1277](https://user-images.githubusercontent.com/28384354/92864438-6aa9a680-f3fd-11ea-99ca-1ee8cc4491cc.jpg) | ![Screenshot_20200911-065611_QField Beta 1277](https://user-images.githubusercontent.com/28384354/92864446-6c736a00-f3fd-11ea-9ca6-b983e99e6be6.jpg) |

**QField version:** 
Screenshots of a later PR version
Tested as well on 1.7.0 (10700992) 
(as on master, I guess)

**Project to reproduce**
Here the project I tested with:
[htmltrouble.zip](https://github.com/opengisch/QField/files/5206003/htmltrouble.zip)
(don't blame me for the bad HTML code - I botched it quickly for the demo :-) )

**Comment by signedav** [comment]
As you can see it's not the label that persists but only the `WebView` item.

**Comment by jhonalex06** [comment]
I tested the project in my **moto g5 plus**.
**QField Version:** 1.7.0 - R (Release).

The first time that I tried to collect data, I crashed with the same issue as the first image.

I reopen the app and the issue appears again in the first Field.

I attach the image, If is necessary to test other versions, tell me, please.

![image](https://user-images.githubusercontent.com/27906888/93287954-69330200-f7a0-11ea-8013-87ac88694c3b.png)

**Comment by nirvn** [comment]
I'll look into this one.
