### ISSUE TITLE
Not remember the last opened directory

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#129]
Not remember the last opened directory. 
When fovaritus chosen to include in the directory does not store the next session.
Is it possible to change the default folder?
Every time I have to search the directory to select another project.

Default:
<img src="http://i.imgur.com/M8ZtunH.png" >

Directory does not store the next session:
<img src="http://i.imgur.com/1xjpXuA.png" >

**Comment by signedav** [comment]
In case #232 can be done, this won't be an issue anymore.

**Comment by giedrioks26** [comment]
solved #250
