### ISSUE TITLE
Handling WMS / WFS

### ISSUE THREAD

**Issue by CATERBN** [opengisch/QField#13]
If the project done on QGIS Desktop use WMS or WFS layers. It could be great if they wher showing also in QField. But QField need a place to set the WMS or WFS parameters like name, URL, ID and password. If QField don't use private/specific flux, it could be great to use OSM or Google map and so on like QGis OpenLayers plugin do (https://plugins.qgis.org/plugins/openlayers_plugin/) .

**Comment by m-kuhn** [comment]
Couldn't the WxS services be just taken from the project without additional configuration on the device itself?
To keep the interface simple we try to keep as many configuration options as possible on the desktop.

**Comment by m-kuhn** [comment]
Fixed with 0.4.1

**Comment by boesiii** [comment]
I have a WMS on my desktop QGIS 2.12 but this layer does not show up on Qfield 0.4.3

The url for the wms layer is below:

http://data1.commons.psu.edu/arcgis/services/pasda/AlleghenyCountyImagery2013/MapServer/WMSServer?

**Comment by boesiii** [comment]
I am using Android 5.1.1

**Comment by boesiii** [comment]
on a Samsung Galaxy Tab E
