### ISSUE TITLE
Dpi scaling issue on windows.

### ISSUE THREAD

**Issue by OlivierLDff** [opengisch/QField#1308]
When using a 4K screen and a 1080p screen on windows, the windows bar doesn't scale well on most application.

### Reproduction Steps:

* Download app from CI.
* Open the app on windows with a 4K screen as primary display and 1080p display as second screen.

### Expected behavior:

The windows bar should the same size as any other windows bar.

### Observed behavior:

The windows bar is too big

### Screenshots and GIFs

![image](https://user-images.githubusercontent.com/17255804/93475782-508a2f80-f8f9-11ea-97ea-64f5094cd3eb.png)

## Additional information:

The problem can easily big fix by adding :
```c++
#if _WIN32_WINNT >= 0x0600
#include <winuser.h>
#endif

// ...

#if _WIN32_WINNT >= 0x0600
::SetProcessDPIAware();
#endif
```

The code snippet should be called **BEFORE** `QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);`

I can do a PR if you want.

**Comment by m-kuhn** [comment]
Thanks a lot, were you able to verify this fix?
I.e. are you able to compile a recent version for windows?

Pull requests are appreciated.

**Comment by OlivierLDff** [comment]
No I didn't compile it myself but it is a recurrent bug of qt applications this is always how I fix it.
If someone that can compile can test this would be nice.

**Comment by m-kuhn** [comment]
Good to know :+1: a pull request would be appreciated. Windows builds are currently on hold, but we hope to revive them soon.

**Comment by nirvn** [comment]
@OlivierLDff , your offer to open a PR would be most welcome, especially now that we have Windows builds up and running again.

**Comment by OlivierLDff** [comment]
I won't have time to look into this in the upcoming week. But as I said, it's just a one line to add somewhere.
You can just add this file to your build system:

`HighDpiFix.cpp` : 
```cpp
#include <QtGui/QGuiApplication>
#ifdef Q_OS_WIN
#    include <Windows.h>
#endif

namespace {

// Fix dpi at application startup
class HighDpiFix
{
    HighDpiFix()
    {
#ifdef Q_OS_WIN
#    if _WIN32_WINNT >= 0x0600
        ::SetProcessDPIAware();
#    endif
#endif // Q_OS_WIN

#if QT_VERSION_MAJOR < 6 // AA_EnableHighDpiScaling is enabled by default on qt6
        QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif
    }
    static HighDpiFix singleton;
};

HighDpiFix HighDpiFix::singleton;

}
```

Code from : https://github.com/OlivierLDff/Qaterial/blob/master/src/Qaterial/Details/HighDpiFix.cpp
