### ISSUE TITLE
Z coord is ignored

### ISSUE THREAD

**Issue by pcav** [opengisch/QField#131]
High res external GPS have precise Z, but this seem to be ignored by QField.

**Comment by m-kuhn** [comment]
Please clarify the meaning of "ignored".
Can you fill in at least the paragraphs "expected results", "observed results" and "qfield version" of the issue template?
Thanks

**Comment by pcav** [comment]
### Reproduction Steps:

1. connect and external, high precision GPS
2. get position from GPS

### Expected behavior:

Digitized data have Z coordinates, as taken from GPS unit

### Observed behavior:

Digitized data have Z coordinates stripped

**QField version:** 0.9.10

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
Now I understand, it's not about precise Z coordinates. It's about Z in general.

**Comment by pcav** [comment]
Yes, sorry I was unclear. Usual precision of Z with consumer level GPS is so low that is rarely useful, but when you are using high precision one, the loss of data is more of a waste.

**Comment by m-kuhn** [comment]
True.
Out of curiosity, do you know about support for ellipsoid/geoid correction of altitude values in QGIS?

**Comment by pcav** [comment]
Not really.

**Comment by m-kuhn** [comment]
Resolved in 0.10.0

**Comment by pcav** [comment]
Thank Matthias.
