### ISSUE TITLE
Feature list wrong after delete

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1314]
Feature list seems to be not correctly updated after delete on multi selection.
The deleting itself works fine.

### Reproduction Steps scenario 1 with simple bee farming:
1. Select two features on layer Apiary
2. Long press on Marco Bernasocchi (random selection) - delete it 
3. Feature List is empty (instead of expected Elizabeth Blackburn)

| 1 |  2 |  3 |
|----------|----------|----------|
| ![Screenshot_20200918-103115_QField](https://user-images.githubusercontent.com/28384354/93576645-6819f480-f99b-11ea-8f19-f79182d98a76.jpg) | ![Screenshot_20200918-103121_QField](https://user-images.githubusercontent.com/28384354/93576649-68b28b00-f99b-11ea-8274-276a4ef0024e.jpg) | ![Screenshot_20200918-103128_QField](https://user-images.githubusercontent.com/28384354/93576652-694b2180-f99b-11ea-8e81-cfebcb2a3048.jpg) |

### Reproduction Steps scenario 2 with simple bee farming:
1. Select features on layer Apiary and Fields
2. Long presso n Al Idrisi - delete it 
3. David Signer is not visible (but an empty entry is on its place)

| 1 |  2 |  3 |
|----------|----------|----------|
|![Screenshot_20200918-103204_QField](https://user-images.githubusercontent.com/28384354/93576653-694b2180-f99b-11ea-8453-4b412a7b4b35.jpg)|![Screenshot_20200918-103213_QField](https://user-images.githubusercontent.com/28384354/93576656-69e3b800-f99b-11ea-8bd6-35ef91513f4f.jpg)|![Screenshot_20200918-103220_QField](https://user-images.githubusercontent.com/28384354/93576657-69e3b800-f99b-11ea-8d1a-802097b53f7c.jpg)|

**QField version:** 
1.7.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Not sure]

**Comment by signedav** [comment]
Do you have an idea about that @nirvn ?

**Comment by nirvn** [comment]
I suspect I do, let me check if the listview has a transition attached to it.

**Comment by nirvn** [comment]
@signedav , can you confirm that the PR I just opened (https://github.com/opengisch/QField/pull/1316) fixes your issue when APKs are available?

**Comment by signedav** [comment]
I will. If back port bot fails (what I believe) can you do it manually to release-1_7 branch? Thanks a lot.

**Comment by nirvn** [comment]
Sure.
