### ISSUE TITLE
Readonly fields are editable

### ISSUE THREAD

**Issue by pcav** [opengisch/QField#132]
Readonly fields, as set in QGIS>Fields, are editable in QField. This is unexpected for the user and data admin.

**Comment by signedav** [comment]
That's integrated meanwhile.

"name" is not editable:

![WhatsApp Image 2019-11-18 at 16 00 59](https://user-images.githubusercontent.com/28384354/69063371-ae6d9280-0a1c-11ea-9312-3e1658565e3b.jpeg)
