### ISSUE TITLE
Hiding layers in layer overview with "Invisible Layers and Groups"-plugin does not work anymore

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#1322]
With the new version 1.71, hidden layers as configured in QGIS with the plugin  "Invisible Layers and Groups" are shown in QField when expanding a group.

### Expected behavior:

Layers show/hide only in the overview when configured to do so in QGIS

Not a major issue but i thought might be worth to report it! Keep up the great work!

**Comment by nirvn** [comment]
@meyerlor , can you share a project file (no need to attach the datasets). I'm surprised it'd be the case as the layers hidden by the Invisible Layers and Groups plugin are never actually added to the legend widget.

**Comment by meyerlor** [comment]
@nirvn sure, here it is the QGIS project!
[Bergatreute.zip](https://github.com/opengisch/QField/files/5254729/Bergatreute.zip)

**Comment by VxTedxV** [comment]
I don't encounter this issue on my projects with this QField version.

**Comment by m-kuhn** [comment]
CC @gacarrillor

**Comment by nirvn** [comment]
I've looked into this project file now, on my machine the hidden layers are not showing in the layer tree. @meyerlor , try  again using the latest version. Thanks.
