### ISSUE TITLE
Filter expression not working in value relation widget when re-editing attributes

### ISSUE THREAD

**Issue by BeBrian** [opengisch/QField#1323]
Dear all,
when re-editing attributes of a point with value relation fields and filter expressions, the filter do not work anymore. In the initial edit the filter works just fine (QField is even faster for filtering long lists than QGIS).  
Greetings and many thanks for your great work by the way

### Reproduction Steps:

1. In QField add a point to a feature which has value relations and filter expressions in its attribute form. Fill out attributes and save.
2. Edit point again. 

### Expected behavior:

When re-editing ("correcting") attributes filter expression work like they do when creating the point. 

### Observed behavior:

Filter expressions do not work when re-editing

**QField version:**
QField-dev 21.09.2020

**Comment by suricactus** [comment]
Hey @BeBrian , thanks for reporting this issue! Can you please try the APK on #1324 and confirm that you no longer experience the reported bug?

**Comment by BeBrian** [comment]
Hey @suricactus,
now it works as expected.
Thanks and all the best
