### ISSUE TITLE
Mandatory fields working in QGIS, but not in QField

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QField#1326]
A perfectly working project in QGIS does not work as expected in QField when it comes to mandatory fields. In QGIS when all required fields are fulfilled, the OK-button is clickable (stays grey until every required field is OK). I use QFieldSync to transfer the project from PC to tablet.

### Expected behavior:
Be able to accept a new point when all required fields are in place.

### Observed behavior:
In QField on the tablet, however, "Add feature on ..." stays "red" (not possible to accept the registration) even though all required fields are entered i.e. no red fields are shown, everything is "green". I can't figure out why.

### Screenshots
The attribute form in QGIS
![pointregistration_ok_in_qgis](https://user-images.githubusercontent.com/10632163/94284498-c114fa00-ff52-11ea-9066-071d5571e468.png)

The same form as it appears in QField
![Screenshot_20200925-162421_QField](https://user-images.githubusercontent.com/10632163/94284531-d1c57000-ff52-11ea-90c4-34abafe178af.jpg)
![Screenshot_20200925-162447_QField](https://user-images.githubusercontent.com/10632163/94284556-d5f18d80-ff52-11ea-97b0-86cd4695cadd.jpg)
![Screenshot_20200925-162501_QField](https://user-images.githubusercontent.com/10632163/94284567-d8ec7e00-ff52-11ea-8298-0275447070c4.jpg)
![Screenshot_20200925-162522_QField](https://user-images.githubusercontent.com/10632163/94284572-dab64180-ff52-11ea-93a2-9a73ceb5cbe7.jpg)

Several expressions are included in many of the fields in the form. See the qml-file for the point-layer in the attached zip-file for the point-layer: [hjorteskade_p.zip](https://github.com/opengisch/QField/files/5283614/hjorteskade_p.zip)

I'm using QGIS ver. 3.14.15-Pi (Windows 10), QFieldSync 3.3.0 and QField 1.7.1 (downloaded and installed qfield-v1.7.1-arm64_v8a.apk September 25 2020) on Samsung Galaxy Tab S4.

## Additional information:
* Problem started happening recently, didn't happen in an older version of QField: Did not succeed in older versions either
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: So far I only have this project with these requirements (expressions)

**Comment by signedav** [comment]
Thanks for reporting.

I haven't analyzed your project yet, but just a quick question: Do you use layernames in the constraints?

**Comment by 9ls1** [comment]
Thanks for responding, and for your patience.
No, I only use layer names in Default value for the fields "Lokalid", "kommnr", "treslag", "bonitet", "hkl", "areal", "antpflater" (they all use the Aggregate-function). In the constraints, only fields area included in the expressions.

**Comment by nirvn** [comment]
@9ls1 ,  providing the QML alone won't be sufficient here. If you could provide a sample of your point dataset, that way we can apply the QML to the dataset with the appropriate fields and test it. Thanks.

**Comment by 9ls1** [comment]
@nirvn Thanks for taking a closer look into the matter. After unzipping the file it should work as intended. The project file and shapefiles are in one folder, while the two tables are in another folder.
[ex4qfield.zip](https://github.com/opengisch/QField/files/5511573/ex4qfield.zip)

**Comment by nirvn** [comment]
@9ls1 , thanks, with your help the issue was found and fixed (look out for 1.7 .7 or 1.8.0 for the fix). 

BTW, I noticed that the two value relations in your form didn't have the proper layer ID (linking to the two delimited text CSV layers). I'm not sure if that as to do with you saving a smaller project sample to share here, or something else. In any case, if you notice the value relation attributes in the form are broken, just open the layer properties of the point layer in QGIS, click OK, then save the project again, it should assign the proper IDs (at least it did here :) ).

Thanks again for sharing the project.

**Comment by nirvn** [comment]
@9ls1 , oh and BTW, you'll probably enjoy the fixed attribute form header height (in upcoming 1.8.0):
![image](https://user-images.githubusercontent.com/1728657/98622229-97196a80-233b-11eb-825c-f55a359022a1.png)
_See for e.g. the section that starts with 'Skaderegistreringer...'_

**Comment by 9ls1** [comment]
@nirvn This is wonderful news, thanks! Looking forward to version 1.8.0.
In my original project the two value relations in the form have proper layer ID. I believed I checked this in my example project, hm. Anyway, sorry for the inconvenience.
And thanks again for your great effort. it's really appreciated.
