### ISSUE TITLE
QField crashing at 'What's New'

### ISSUE THREAD

**Issue by Pachuquero** [opengisch/QField#1327]
QField crashing at 'What's New' after fresh install

### Reproduction Steps:

1. Launch results in crash

### Expected behavior:

...

### Observed behavior:

...

### Screenshots and GIFs

![photo_2020-09-26-25%](https://user-images.githubusercontent.com/5184994/94351511-9ee4b000-0016-11eb-983d-d283b64199a8.jpg)

**QField version:**  

qfield-v1.7.1-arm64_v8a.apk on a Galaxy S7, Android 8.0.0, Samsung Experience 9.0

**Comment by signedav** [comment]
So you can see the "What's New" popup and without any interaction it crashes? Or does it crash on closing the dialog?

Would it be possible to provide us a logcat of the crash?

**Comment by Pachuquero** [comment]
@singedav

I've tried some three versions with the latest downloaded from GitHub. At least today when I first try to start the app then it cycles through two initial screens, the latter being to rate the app. However, instantly after it ends up with the capture I've sent earlier. 

If I didn't do the logcat properly or you, for some reason, need another do let me know.

[logcat_10-08-2020_10-09-31.txt](https://github.com/opengisch/QField/files/5349291/logcat_10-08-2020_10-09-31.txt)

**Comment by signedav** [comment]
I cannot see anything in the logfile concerning the crash. 

How do you produce it? 

If using adb try to enter:
```
adb logcat -s QField > logcat_10_09.txt
```

**Comment by signedav** [comment]
Btw. you closed this issue on purpose @Pachuquero ?

**Comment by Pachuquero** [comment]
I wasn't aware that it was closed and surely didn't do it - at least on purpose. 

>How do you produce it?

After installation I click the icon for the app and it crashes. Doesn't seem to like my phone model and / or Android version (as already mentioned, I tried with some earlier versions and had the same issue ending with the capture shown above).

I've also installed the app in a Samsung Galaxy Tab S3 (Android 9, One UI 1.1) where the app successfully launches. However, the app doesn't show the tools for registering data and also shows an unknown layer instead of the base map I defined.

I don't have a logcat for that device (yet)....

![photo_2020-10-10_14-52-16-50%](https://user-images.githubusercontent.com/5184994/95664835-96a56e00-0b08-11eb-9ac7-eeae1f01e702.jpg)

![photo_2020-10-10_14-52-26-50%](https://user-images.githubusercontent.com/5184994/95664848-af158880-0b08-11eb-996e-dabe52b86a50.jpg)

**Comment by VxTedxV** [comment]
> However, the app doesn't show the tools for registering data

You must activate the "write mode" first by toggling the pencil icon you can see on your first screen capture

**Comment by VxTedxV** [comment]
> However, the app doesn't show the tools for registering data

You must activate the "write mode" first by toggling the pencil icon you can see on your first screen capture, and select a vector layer to edit (your project doesn't seem to have one).

**Comment by signedav** [comment]
You need only to make a logcat for the crash. As @VxTedxV mentioned, it seems the project is not configured in a proper way on the device, where QField runs without problem. Are you successful with the demo projects?

Regarding the crash on the other specific Galaxy S7. Do you have more details about the type?

> (as already mentioned, I tried with some earlier versions and had the same issue ending with the capture shown above).

Just to know. You tested with older releases like 1.6.4. or 1.5.3 as well?

**Comment by gertjan55** [comment]
I do have the same problem  with mobile SM-A320FL, android 8.00, last month worked fine, but after last week updated apps, the qfield app crashes after start, Rate Qfield windows appear and the crashes or Window whats new. With other apparatus SM-T830, android 10 this does not happen.

**Comment by suricactus** [comment]
@gertjan55  @Pachuquero can you please try whether the apks here are causing your app to crash?
https://github.com/opengisch/QField/actions/runs/322558850

**Comment by gertjan55** [comment]
Hi,
Im not a programmer, a field user, so i'm not sure what to do with this info

**Comment by signedav** [comment]
Hi @gertjan55 
To get the 64bit APK download this https://github.com/opengisch/QField/suites/1383959717/artifacts/22797804 and copy it to your device (or click this link from your device and download it directly). It should ask you then to install it.

**Comment by gertjan55** [comment]
Hi,
I tried this but it answers:
We couldn’t find any repositories matching '22797804'

**Comment by signedav** [comment]
Oh, maybe you have no access.
Try to download here:
https://www.swisstransfer.com/d/d97030cd-3777-4dfe-88d1-144f5feab7f2

**Comment by gertjan55** [comment]
Hi,After download i get the message " there is no app to open this file" what to do?Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: signedav <notifications@github.com> Datum: 23-10-20  11:48  (GMT+01:00) Aan: opengisch/QField <QField@noreply.github.com> Cc: gertjan55 <gertjan.speckmann@gmail.com>, Mention <mention@noreply.github.com> Onderwerp: Re: [opengisch/QField] QField crashing at 'What's New' (#1327) 
Oh, maybe you have no access.
Try to download here:
https://www.swisstransfer.com/d/d97030cd-3777-4dfe-88d1-144f5feab7f2

**Comment by gertjan55** [comment]
After download and install: message appear: app not installed

**Comment by gertjan55** [comment]
I tried several ways, but so far not succefullVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: signedav <notifications@github.com> Datum: 23-10-20  11:48  (GMT+01:00) Aan: opengisch/QField <QField@noreply.github.com> Cc: gertjan55 <gertjan.speckmann@gmail.com>, Mention <mention@noreply.github.com> Onderwerp: Re: [opengisch/QField] QField crashing at 'What's New' (#1327) 
Oh, maybe you have no access.
Try to download here:
https://www.swisstransfer.com/d/d97030cd-3777-4dfe-88d1-144f5feab7f2

**Comment by signedav** [comment]
You are testing with the 64bit S7 or with the other device?

**Comment by gertjan55** [comment]
Hi,
It's SM-A320 FL (2017) , so yes that's 64 bit S7

**Comment by gertjan55** [comment]
I tried sdk-x86_64, sdk-x86, sdk-armv7, sdk-arm64_v8a, from these only
sdk-armv7 does install but does not recognise  project from sd-card and
crashes when opening a project from the internal storage

**Comment by signedav** [comment]
Hi @inthewoodz and @Axel-tec

Since it seems you have the same problem, would it be possible to test this package https://www.swisstransfer.com/d/d97030cd-3777-4dfe-88d1-144f5feab7f2 (64 bit devices) ?

**Comment by gertjan55** [comment]
Hi,It does not install, for some reasonVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: signedav <notifications@github.com> Datum: 26-10-20  07:10  (GMT+01:00) Aan: opengisch/QField <QField@noreply.github.com> Cc: gertjan55 <gertjan.speckmann@gmail.com>, Mention <mention@noreply.github.com> Onderwerp: Re: [opengisch/QField] QField crashing at 'What's New' (#1327) 
Hi @inthewoodz and @Axel-tec
Since it seems you have the same problem, would it be possible to test this package https://www.swisstransfer.com/d/d97030cd-3777-4dfe-88d1-144f5feab7f2 (64 bit devices) ?

**Comment by inthewoodz** [comment]
This version installs for me (you have to change your settings to allow it).  

It works!  I can open the demo project, as well as a project I created previously.

**Comment by gertjan55** [comment]
Hi,
For me, It starts to install, but a few seconds later the message :no
install, so it does allow but does not complete

**Comment by suricactus** [comment]
@inthewoodz can you also try with the APKs available at https://github.com/opengisch/QField/pull/1370#issuecomment-716441331 ? Thank you for helping us resolving this issue.

**Comment by gitgeo-bg** [comment]
To confirm that the last version available @ GooglePlay store is crashing as reported ( crashes at What's New" popup) . My experience is from yesterday. The device is Samsung Galaxy A5, runing Android v 8.0. The version from this [link](https://www.swisstransfer.com/d/d97030cd-3777-4dfe-88d1-144f5feab7f2) work perfectly.
Congrats to the developers, great software!

**Comment by signedav** [comment]
Thanks @gitgeo-bg - can you please test the APK here as well? https://github.com/opengisch/QField/pull/1370#issuecomment-716441331 Thanks a lot.

**Comment by gertjan55** [comment]
Download is ok, but does not install, at first starts installing but does not complete and messaga no installVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: signedav <notifications@github.com> Datum: 29-10-20  08:16  (GMT+01:00) Aan: opengisch/QField <QField@noreply.github.com> Cc: gertjan55 <gertjan.speckmann@gmail.com>, Mention <mention@noreply.github.com> Onderwerp: Re: [opengisch/QField] QField crashing at 'What's New' (#1327) 
Thanks @gitgeo-bg - can you please test the APK here as well? #1370 (comment) Thanks a lot.

**Comment by gitgeo-bg** [comment]
Hi, arm64_v8a.apk /QField Beta 1370 works fine, no crashes

**Comment by signedav** [comment]
Thanks @gitgeo-bg - if you could test this as well, it would be awesome https://github.com/opengisch/QField/pull/1372#issuecomment-717200817

**Comment by gitgeo-bg** [comment]
Installed and tested on Galaxy A5. Works.

**Comment by gertjan55** [comment]
Hi,
i tried
armv7, x86, arm64_v8a and x86_64
armv7 does install, does not recognise sd card and crashes when opening
project, the others do not install

**Comment by suricactus** [comment]
SM-A320FL

**Comment by gertjan55** [comment]
Hi,
I changed apparatus to  Samsung A51 and playstore app Qfield works well,
does not recognise external sd card,
thanks for the efforts taken

**Comment by signedav** [comment]
I think we can close that since this integration #1375
Feel free to reopen if there are still problems.
