### ISSUE TITLE
Value relation widget NULL value saved as 0

### ISSUE THREAD

**Issue by samueldurante** [opengisch/QField#1337]
Hi,
I'm encountering a bug with NULL values in value relation widget.
Qfield seems to save the integer value 0 instead of NULL value when typing on "NULL" in value relation widget dropdown.
Back into QGIS this problem breaks the foreign key constraint.
This problem doesn't appear if I don't touch the dropdown and save the new entity with an empty value.

Thanks for helping, and also for all enhancements commited on value relation widget since few month !!

### Reproduction Steps:

1. Create a simple gpkg with two layers : parent and children. Layer children should have a field "parent_fid" (integer64)
2. Create a relation referencing fid field of parent layer from the parent_fid field of children layer.
3. Add a value relation widget which allows NULL values
4. On Qfield, try to add or edit an entity in children layer and leave the parent_fid field set to an empty value (entity A)
5. On Qfield, try to add or edit an entity in children layer and set the parent_fid field to "NULL" (entity B)
6. Back on Qgis, check values of parent_fid field.

### Expected behavior:
Entity A and B should have a NULL value in parent_fid field.

### Observed behavior:
Entity A has the expected NULL value.
Entity B has the problematic value 0 instead of NULL.

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/54809024/95190228-44461380-07cf-11eb-944a-0f353fabeea1.png)

**QField version:** Qfield dev 6d157d3 (3/10/20). Same pb with current stable version 1.5.3 (010503991)

## Additional information:
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
Can you test this @samueldurante https://github.com/opengisch/QField/pull/1338#issuecomment-705486911

**Comment by nicpitsch** [comment]
This bug seems to be back again. QField Version 1.7.6.
