### ISSUE TITLE
Duplicate information in form field

### ISSUE THREAD

**Issue by vazlalo** [opengisch/QField#1339]
Hi good day. I have a problem with Qfield, the project I am working on is a kind of compass, I take the coordinate and with them I can obtain the direction angle, when I create the first line the obtained angle is zero, and when I create a second line Parallel to the first line in the angle field, the angle of the first one appears and when I create a third line the correct angle appears and so with each of the lines that are created, this type of "error" had already happened to me before with other protectos and in Qgis the data is correct when creating a line.

### Reproduction Steps:

1. I create a line
2. The form opens and the missing field (nombre) is filled y verifico que los campo que este llenos
3. Save space object

### Expected behavior:

That the angle (angulo) field is not zero or other data of a spatial object already created previously

### Observed behavior:

If a line is created for the first time, the angle (angulo) field has a zero and if a second line is created it takes the data from the previous one until the third line created takes the correct data

### Screenshots and GIFs

In this first image the project was opened, when the first line is created the angle field appears to be zero
![Screenshot_20201009-110220](https://user-images.githubusercontent.com/54996080/95609856-06dac380-0a25-11eb-853e-dccb90aa0a54.png)

in the second image the angle (angulo) field takes the information from the first line (image 1)
![Screenshot_20201009-110255](https://user-images.githubusercontent.com/54996080/95610654-448c1c00-0a26-11eb-8030-528519f788c0.png)

In this third image you can see the angle field, your data is correct (verify the data in qgis and on a web)
![Screenshot_20201009-110507](https://user-images.githubusercontent.com/54996080/95611837-0132ad00-0a28-11eb-8573-d266a4e9e9f2.png)

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 
1.6.4(code:v1.6.4)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
-Yes, it had already happened to me in other projects, when I configured the distance between two points or when the fields placed numerical data they were repeated in the new spatial objects

* Problem can be reliably reproduced, doesn't happen randomly: [No]
no, because I have already worked on other projects and nothing happens and only for when I use numerical data

* Problem happens with all files and projects, not only some files or projects: [No]
no, in some

**Comment by nirvn** [comment]
You should revisit this issue with APKs on QField master. Several bad regressions were fixed this week that could have fixed this.
