### ISSUE TITLE
QField crashes when using container "Control visibility by expression"

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#134]
QField crashes when using drag-and-drop forms designer, Configure container -> "Control visibility by expression". When it is not selected then no crashes.

<img src="http://i.imgur.com/jBo3u8T.png" >

This problem occurred QGIS 2.18.9. The older works well. Project example attached:
https://drive.google.com/file/d/0B6234JBD50yCd0ZZZW5nYTJtTkU/view?usp=sharing

Using Qfield 0.9.10
Sony xperia tablet z, Android 5.1.1
PC os Debian 9.0, QGIS 2.18.9

**Comment by signedav** [comment]
Do you know if this is solved with fix for that #125 @giedrioks26 ?

**Comment by giedrioks26** [comment]
Yes, it works perfectly now! Thanks!

**Comment by giedrioks26** [comment]
Sory, problem persist

**Comment by giedrioks26** [comment]
The problem occurs when there are less than 4 fields. When I add an extra field, not crashes. I upload a file with a good and bad layer.
[crash.zip](https://github.com/opengisch/QField/files/1850875/crash.zip)

1. Crash
[ekranvaizdis_2018-03-27_10-27-07](https://user-images.githubusercontent.com/6436791/37953327-46a1cfd6-31ab-11e8-9b55-f701c4d61c44.png)

2. No crash when add "ola" extra field
[ekranvaizdis_2018-03-27_10-29-41](https://user-images.githubusercontent.com/6436791/37953422-83ac94ce-31ab-11e8-8285-4cf5544f6f5e.png)

**Comment by giedrioks26** [comment]
yes, with 1.0.0 no crash
