### ISSUE TITLE
Version in Changelog Title

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1341]
When the changelog appears for version 1.7.3 it looks like this:
![WhatsApp Image 2020-10-12 at 08 07 10 (1)](https://user-images.githubusercontent.com/28384354/95711093-5c4fe400-0c62-11eb-8d7b-128db09611dc.jpeg)

Because it displays the changelog listing all major changes (in 1.7.0) and the patch version follows.

Still it can be confusing, when the user downloads version 1.7.3 and then the first thing she sees is "1.7.0".

Maybe we can change the title to "What's new on QField 1.7.3 Rockies" and have the following release titles slightly smaller.

@suricactus What do you think?

**Comment by suricactus** [comment]
What we have discussed with @m-kuhn is that the major release is the most important and should be on the top. I do agree it is a bit confusing that after minor update, we see the same initial screen. We can make it like:

> # What's new in QField 1.7.x series
> Check the new cool features up to 1.7.3 Rockies release:
> ## QField 1.7.0
> ...
> ## QField 1.7.1
> ...
> ## QField 1.7.2
> ...
> ## QField 1.7.3
> ...

**Comment by signedav** [comment]
I agree on having the notes of 1.7.0 on top as well. 

+1 for your proposal.

Or maybe just "What's new in QField 1.7"?

**Comment by suricactus** [comment]
Unfortunately, there is no reliable way to get the version number on the beta channel without changing the green title after successful fetch from the github API. So the only changing thing will be the release name in bold. 

![image](https://user-images.githubusercontent.com/2820439/95744547-26c7ec80-0c9c-11eb-907f-b9d1c0a575e7.png)

**Comment by signedav** [comment]
It's fine for me.
