### ISSUE TITLE
Qfields often dont start-> error “QField angehalten/QField stopped” any idea?

### ISSUE THREAD

**Issue by Axel-tec** [opengisch/QField#1346]
I run Qfield on Android Samsung S7 with one small project. Sometimes it runs ok but actually I cant open the programm. When I try it several times I get the message "QField bleibt ständig stehen/QField stops permanently" after QField "QField angehalten/QField stopped". I used the Version from the GoogleAppstore 1.6.4 and also after deinstallation I tried the APK version 1.7.3 (qfield-v1.7.3-armv7.apk)? No improvement.

Does anyone have the same error pattern?

**Comment by Axel-tec** [comment]
I try an older version qfield-v1.4.0-armv7.apk - and it works ...

**Comment by signedav** [comment]
It seems you are using a 32-bit device. If yes, then see the explanation here: https://github.com/opengisch/QField/issues/1328#issuecomment-705401603
Since it crashes with 1.7.3 as well, it might be something with the labels. Do you have labels enabled? Then see #1329

**Comment by Axel-tec** [comment]
Hi Signedav - short update - since yesterday also dhe v1.4.0. version chrashes/stopps while opening ... . I think i have no lables enabled but i`ll take a look and report. i also try the device thing 32 vs 64-bit. Thanks a lot!!!

**Comment by Axel-tec** [comment]
Now i try this version: qfield-v1.7.3-arm64_v8a.apk

**Comment by Axel-tec** [comment]
This Version dont run/open only for a short time. First display "news in this version" than qfield stops with the screen "QField angehalten when i try to open it for more times the error message is "QField bleibt ständig stehen" "App schließen" ...

**Comment by Axel-tec** [comment]
Running now stable with version qfield-v1.5.0-arm64_v8a.apk. I try higher versions in the next day`s. My Samsung S7 uses a 64 bit device.

**Comment by signedav** [comment]
Related to #1327
