### ISSUE TITLE
QField does not yet support the autocomplete option in the value relation widget

### ISSUE THREAD

**Issue by Fertuesta25** [opengisch/QField#1347]
QField does not yet support the autocomplete option in the value relation widget

### Expected behavior:

When entering the first letter or word of a value in the form, you should perform a search for added values using the value relation widget.

### Observed behavior:

The search for values is not activated.

### Screenshots and GIFs

I attach screenshots and project.
[https://drive.google.com/file/d/1xgupTt2xUKb3INQxAUa3jyXBXbwp_VGX/view?usp=sharing](url)
[https://drive.google.com/file/d/10LoR5kz-rGLYwefO64-uQmGfKF0oS4XC/view?usp=sharing](url)

Project
https://drive.google.com/file/d/1gruqS6go2jlZpV8WZ_-7Ztao9rZU5p68/view?usp=sharing

**QField version:** [QField version 1.7.3]

## Additional information:

**Comment by signedav** [comment]
This is not (yet) supported. See #724

I close this because of duplicate. Hope it's okay for you.
