### ISSUE TITLE
QGIS and QField Problem - Qfield Sync plugin won’t “Package for Qfield”

### ISSUE THREAD

**Issue by mikejensen28** [opengisch/QField#1348]
I am using either QGIS 3.14 or 3.10, and plugin Qfield Sync 3.2.2

I am having a problem where the Qfield Sync plugin won’t “Package for Qfield”.

This option is greyed out on the menu!

The option worked perfectly ok recently and I was able to package ok, but it has stopped working.

Mike Jensen
mike.jensen@codc.govt.nz
-------------------------------------------------
### Reproduction Steps:

1. [First Step]
### Expected behavior:

The menu option "Package for Qfield" is selectable, is not greyed out.

### Observed behavior:
[Describe observed behavior here]

The menu option "Package for Qfield" is not selectable,  it is greyed out.

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 

QGIS 3.14 or 3.10, and plugin Qfield Sync 3.2.2

**The operating system is:
  Edition: Windows 10 Enterprise
  Version: 1909
  OS Build: 18363.1016

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
Yes
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
Yes

**Comment by signedav** [comment]
Could it be possible that you are already working on an offline project?
If not, could you close this issue and open another one on the QFieldSync Issue List here: https://github.com/opengisch/qfieldsync/issues

Thanks.
