### ISSUE TITLE
Directly using the positioning coordinate for digitizing does not add point to the POINT layer

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#135]
When I use directly using the positioning coordinate for digitizing, and put a dot, fill in the form and press Save, point not addet. When I do not use it, everything works fine. Also using it with polygon and linestring everything works fine. Problem with add POINT. 

QField 0.10.0
Android 5.1.1
Sony Xperia tablet Z1

**Comment by m-kuhn** [comment]
Can you inspect the dataset on a desktop and check if the point is not added, added without geometry or added with wrong coordinates (and in the last case, which coordinates).

**Comment by giedrioks26** [comment]
I checked. With qgis not showing a point, but data in the attribute table remains. When zoom to feature, it writes: "Zoom to feature id failed: Feature has no geometry.":
<img src="http://i.imgur.com/JoWytq8.png" >

Sqlite show an empty geometry field:
<img src="http://i.imgur.com/XhLuZov.png" >

I tried to edit with the shp layer. Works fine. Not add point and multipoint with sqlite layers.

**Comment by m-kuhn** [comment]
> I tried to edit with the shp layer. Works fine. Not add point and multipoint with sqlite layers.

Do I understand this correctly:

* The point is added in qfield with a shapefile
* it's not added in qfield with sqlit
  * is sqlite spatialite? or geopackage? or plain sqlite something?

**Comment by giedrioks26** [comment]
> Do I understand this correctly:

>The point is added in qfield with a shapefile
>it's not added in qfield with sqlit

Yes correctly understood

> is sqlite spatialite? or geopackage? or plain sqlite something?

This is a simple sqlite database (not_add_point.sqlite)
[https://drive.google.com/file/d/0B6234JBD50yCci1rZ1NucEszTE0/view?usp=sharing](url)

**Comment by m-kuhn** [comment]
That's a spatialite file with 2D coordinates.
Apparently there's a problem when QField tries to write a 3D coordinate to this file. Apparently QGIS or GDAL silently removes the Z coordinate for shapefiles and handles spatialite differently.

**Comment by giedrioks26** [comment]
I changed the sqlite point layer to the 3d dimension. The problem is the same. Not add point.

<img src="http://i.imgur.com/3lNiEbt.png" >

**Comment by m-kuhn** [comment]
Can you check your file in the python console of QGIS. Select it in the layer tree first and then run this script:

```
layer = iface.activeLayer()
layer.startEditing()
f = layer.getFeatures().next()
f.setGeometry(QgsGeometry(QgsPointV2(QgsWKBTypes.PointZ, 1, 2, 3)))
layer.updateFeature(f)
layer.commitChanges()
f = layer.getFeatures().next()
print(f.geometry().exportToWkt())
```

With your demodata from above this gives me

shp:

```
Point (1 2)
```

sqlite

```
AttributeError: 'NoneType' object has no attribute 'exportToWkt'
```

**Comment by m-kuhn** [comment]
To be on the save side: delete all features in the file first and then add one single point with the add point tool and save the file.

**Comment by giedrioks26** [comment]
Yes, it gives me the same

shp:

`Point (1 2)`

sqlite

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'exportToWkt'`

**Comment by giedrioks26** [comment]
gpkg

`PointZ (1 2 3)`

**Comment by m-kuhn** [comment]
So it seems to be an isolated spatialite problem. For now, better just avoid it as workaround. In the long term, the Z coordinate should silently be dropped for such datasets.

Sidenote: please don't just call it "sqlite", that's a generic database format (spatialite and geopackage are both sqlite based formats).
