### ISSUE TITLE
Multi Window Mode

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1359]
Just an idea.

With Android 10 / SDK 29 it would be possible to have Multi Window Mode and Picture in Picture as well.

**Comment by nirvn** [comment]
@signedav , I've got good news for you:

![Screenshot_20210308-151609_QField Beta 1748](https://user-images.githubusercontent.com/1728657/110293530-44b63500-8021-11eb-883d-e6ee81d8ec4b.jpg)

**Comment by signedav** [comment]
Yay 🥳
