### ISSUE TITLE
Editing existing data (Show open form button)

### ISSUE THREAD

**Issue by jhonalex06** [opengisch/QField#1360]
QField currently does not support the Relation Reference’s “Show open form button” setting, which would be handy to edit existing data and thus, improve the data capture process on the field.

For instance, we tried to visualize the information inside of a table **Predio**, which has a relation with **Terreno**. However, we have no option in the QField form to open the form of a referenced (**Predio**) feature.

### Reproduction Steps:

1. (QGIS) Right-click on layer **Terreno** and select **Properties**.
2. (QGIS) Go to attributes form and select the field **Predio**.
3. (QGIS) Select **Show open form button** inside the **Widget Type**.
4. (QGIS-QField) Save the project and open it in QField.
5. (QField) Click on any **Terreno** and edit the information.
6. (QField) Try to visualize the **Predio** form through the relation.

### Expected behavior:

When **Show open form button** is selected, we expect that we can visualize the attributes of the referenced feature in the QField form.

### Observed behavior:

When **Show open form button** is selected, we cannot visualize the form of the referenced feature in the QField form.

### Screenshots and GIFs

Configuration in QGIS

![config_in_qgis](https://user-images.githubusercontent.com/27906888/96273109-95ef5a80-0f94-11eb-9732-be8b40d2f230.png)

QField’ behavior

![behavior_in_qfield](https://user-images.githubusercontent.com/27906888/96273121-9be53b80-0f94-11eb-95fc-9589c08b3c4f.png)

**QField version:** “1.7.1” (code: v1.7.1).

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
This has been fixed and will be part of QField's next major release.
