### ISSUE TITLE
Extremely long project loading time

### ISSUE THREAD

**Issue by freedom-studio** [opengisch/QField#1363]
I have pretty large qgs file (7 MB) generated by QField plugin in QGis. The file is large, because I am using multiple styles and themes in the project and I have about 50 layers.

In previous versions project loading time was about 10 seconds on my phone. But since 1.7 version loading time is over two minutes!!

### Reproduction Steps:

1. Select a large .ggs file to be open (~7 MB)

### Expected behavior:

It should load in no more than 20 s.

### Observed behavior:

Loading time is several minutes.

**QField version:** 1.7.3 (code v1.7.3)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No

**Comment by nirvn** [comment]
If you *only* copy the project file without the datasets on your device, does the project takes minutes to load? If so, if you can, attach the project file here.

If the project loads fast without datasets, you'll have a bit of work to do to narrow down the source of the slow down you're reporting. One by one, copy each dataset back onto the device, until you hit the one(s) that cause the slowdown.

**Comment by freedom-studio** [comment]
The project file alone also loads in two minutes. I have attached my zipped project file (withot layers).
[GeoportalTatry.zip](https://github.com/opengisch/QField/files/5403086/GeoportalTatry.zip)

**Comment by nirvn** [comment]
@freedom-studio , can you try the APK here to see if the speed regression is fixed: https://github.com/opengisch/QField/pull/1364#issuecomment-712556457 -- thanks

**Comment by freedom-studio** [comment]
In my case version 1364 is much faster than 1.7, but still slower than e.g. v1.5.

MY PROJECT LOADING TIMES
v1.5.3 - 9.5 s
v1364 - 15.5 s

**Comment by nirvn** [comment]
Much faster is good, still slower than 1.5 is both worth looking into some more.

That said, glad your back to manageable project load speed :)

**Comment by monticola2** [comment]
I have also experienced very slow loading of a project with a lot of data (~2GB). The project file size is only 5MB though.
With v1.5.3 the project loads in about 15s. With later versions (latest I checked is v1.7.6) the project takes about 3-4min to load, working then is a lot less responsive/laggy and the app usually crashes once I try to change the theme to one involving large databases. Also, one hillshade layer in this project is viewed rather strangely, unlike in v1.5.3 and QGIS (all versions from 3.10 to 3.16).
Other, smaller projects were fine though. Has there been any difference in handling/loading large datasets after v1.5?
Sorry, not a helpful bug report from me, I'll try to narrow down the source of the problem by myself once I find time for it.

**Comment by nirvn** [comment]
@monticola2 , can you zip and share your 5mb project file here?

**Comment by monticola2** [comment]
@nirvn : Sure:
[project.zip](https://github.com/opengisch/QField/files/5540393/project.zip)
Same project saved as .qgs and .qgz

**Comment by nirvn** [comment]
@monticola2 , thanks. The regression causing the feeeze has been identified. Unfortunately the problem lies within Qt itself. There might be ways to mitigate the issue. More soon.

**Comment by nirvn** [comment]
@monticola2 , when you have a minute, please test the APKs that will appear in PR #1425 , I believe this will fix the 3-4min freeze ( :fearful: ) you've been experiencing.
