### ISSUE TITLE
QFIELD don't enable camera function

### ISSUE THREAD

**Issue by JCCabreraMX** [opengisch/QField#1367]
QFIELD don't enable camera function on my project

### Reproduction Steps:

1. I create an attribute for as "Attachment" for "Photo" field. Next, I save and package my project for QFIELD
2. Load my project in my tablet. Next, I open my project in QFIELD
3. In QFIELD, choose my layer and enable digitize mode, choose the "Photo" field and then, camera function isn't enabled... AND I DON'T KNOW WHY??

### Expected behavior:

In previous versions, I did the same steps and everything worked fine, the camera function was enabled without problems. But with the new update, the camera function does not work as I am doing. I don't know if anything else needs to be done now.

**Comment by suricactus** [comment]
Can you please verify that you have your project configured properly, as described in https://github.com/opengisch/QField/issues/1213#issuecomment-674408619 .
