### ISSUE TITLE
Troubles loading wms layers from ICV (Institut Cartogràfic Valencià)

### ISSUE THREAD

**Issue by Simon38** [opengisch/QField#1368]
I have troubles loading wms orthophoto layers from the ICV (Institut Cartogràfic Valencià).

http://www.icv.gva.es/auto/aplicaciones/icv_geocat/#/results/ortofotos

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs
![Problem_WMS](https://user-images.githubusercontent.com/33135720/97002023-a9bd3280-1539-11eb-9d4c-2c20dd11558f.jpg)

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by vazlalo** [comment]
hello, the maps cannot be loaded as it requires a connection to the server where the maps are stored, what you can do is create a georeferenced image

**Comment by Simon38** [comment]
> hello, the maps cannot be loaded as it requires a connection to the server where the maps are stored, what you can do is create a georeferenced image
I loaded other maps from other wms servers, and I didn't have troubles. For example this: 
http://carto.icv.gva.es/arcgis/services/tm_agricultura/sigpac/MapServer/WmsServer
http://www.ign.es/wms-inspire/pnoa-ma
http://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx

**Comment by Simon38** [comment]
> hello, the maps cannot be loaded as it requires a connection to the server where the maps are stored, what you can do is create a georeferenced image
