### ISSUE TITLE
QField will not launch after last update

### ISSUE THREAD

**Issue by inthewoodz** [opengisch/QField#1369]
Since the most recent update, Q field will no longer launch. The new "what's new" screen opens and then the app closes / crashes before there's a chance to do anything.

### Reproduction Steps:

1. Attempt to launch app
2. It crashes / closes
3. Many additional attempts, as well as a few attempts to uninstall and reinstall the app

### Expected behavior:

In the past the app worked well on my phone, and I was able to look at maps, collect points, collect photos, etc 

### Observed behavior:

See above

### Screenshots and GIFs

**QField version:** Version available on 10/24/2020

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: YES
* Problem can be reliably reproduced, doesn't happen randomly: YES
* Problem happens with all files and projects, not only some files or projects: YES

Android v. 8.0.0

**Comment by signedav** [comment]
Related to #1327

**Comment by signedav** [comment]
I think we can close that since this integration #1375
Feel free to reopen if there are still problems.
