### ISSUE TITLE
Can't save record when adding point features

### ISSUE THREAD

**Issue by marcp1999** [opengisch/QField#1371]
Today while adding point data to a point layer containing about 600 entries I was regularly having problems saving the record. It is stored in a spatialite db with a number of other layers. The layer is in the same CRS as the project, and has an autogenerated id field (OGC_FID) and 11 other text and numeric fields, none of which are required.
 
Upon hitting the save button I would get a message "Cant save record". When I viewed the log file I saw a series of errors that related to 'geometry or SRID'. I would love to include the error messages for you but can't find a log file  to include. It's not clear to me where it is supposed to be, and now that I've restarted it there is no record of it in the log file dialog.

The next record might be ok or it might not. After successfully entering a couple of good ones I went back to the previous unsuccesful point and was still unable to do it. Generally speaking I create points when I am upon them, but I also tried creating a point just with the mouse.

On one occasion I was able to "force" it to accept a point by entering a large value into the OGC_FID field. When I tried this again it didn't work.

I am running QField 1.7.3 on a Samsung Galaxy Tab. The project and layers in question have all been in use for months.

**Comment by suricactus** [comment]
Thank you for reporting this issue. Is it possible to share the failing project, since I was not able to reproduce.
