### ISSUE TITLE
Boolean field return empty value on insert

### ISSUE THREAD

**Issue by audelorAd** [opengisch/QField#1373]
I've a layer store in a PostGres DB with one field is boolean type. Using QField I try to update this boolean field by checking checkboxes. When I'm back on my computer and I try to synchronize data with QField plugin I always have an issue with boolean field, QGIS try to update in PostGres with an empty value :

>  CRITICAL    Couche cellule : Erreur PostGIS lors de la modification d'attribut : ERREUR: syntaxe en entrée invalide pour le type booléen : « »
>              LINE 1: ... SET "enseigne"='GALERIES',"nationale"='' WHERE "...

### Reproduction Steps:

1. Create a table with a column as boolean type TRUE/FALSE in a PostGres DB
2. Load this table in QGIS and check boolean column configration as :  ![2020-10-28_14h17_26](https://user-images.githubusercontent.com/63049494/97440873-562b5a00-1928-11eb-80c3-08ff7756bbe3.png)
3. Create QFIELD package with QFIELD plugin in QGIS
4. Use it on smartphone and update features
5. Go back on QGIS for synchronisation, and see error 

### Expected behavior:

Update boolean columns with a TRUE or FALSE value

### Observed behavior:

Feature is updating with an empty value for boolean column

### Screenshots and GIFs

**QField App version: 1.7.3** 
**QGIS version: 3.10.11** 
**QField Plugin version: 3.3.1** 
**PostGres DB version: 9.1.14** 

## Additional information:

* I don't have this problem when I update features directly with QGIS

**Comment by suricactus** [comment]
I didn't manage to reproduce the problem with QGIS 3.14 and boolean field. Can you share the subset of the project that fails and try on 3.14.

**Comment by audelorAd** [comment]
I've try on QGIS 3.14 and it's working fine. Can I hope a correction on next minor release of QGIS 3.10 ?

**Comment by nirvn** [comment]
This issue was upstream and fixed in the latest supported release, closing.
