### ISSUE TITLE
Qfield blocks when I add a second entity

### ISSUE THREAD

**Issue by frgis** [opengisch/QField#1379]
Hi,

with the map attached, when I add an entity the first time the form is slow to display but it works. When I want to add a second entity qfield is blocked (see attachment).

### Reproduction Steps:

1. add an entity, the form is open, I can validate
2. add a second point, Qfield blocks

### Screenshots and GIFs

![Screenshot_20201101_101449_ch opengis qfield](https://user-images.githubusercontent.com/56657014/97799397-53817b00-1c2e-11eb-9b76-c4cb2b3b226b.jpg)
[QFIELD_REPERAGE_sans_fdp.zip](https://github.com/opengisch/QField/files/5470490/QFIELD_REPERAGE_sans_fdp.zip)

Problem in version : QField version:1.7.5, 1.7.0. > no problem 1.6.4

Thanks

**Comment by nirvn** [comment]
@frgis , can you try to see if the freeze still occurs with a 'master' build (APKs here: https://github.com/opengisch/QField/pull/1376#issuecomment-719872616)

**Comment by nirvn** [comment]
Asking as I've tried to reproduce this freeze with the APK above and couldn't.

**Comment by frgis** [comment]
I always reproduce the problem with armv8_x64.

My smartphone : Huawei p20pro

**Comment by frgis** [comment]
do I need to send the log of my phone (android 10)?

**Comment by nirvn** [comment]
Tu as essayé l APK attaché au lien que j ai partager plus tot aujourdhui et QField gele toujours?

**Comment by frgis** [comment]
Oui celui-ci:

![image](https://user-images.githubusercontent.com/56657014/97806359-9148c880-1c5b-11eb-8fef-05ecf9201637.png)

ça bloque toujours.
Avec la 1.6.4 pas de souci particulier mais à partir de la version 1.7.0 (j'ai essayé sur la 1.7.0 et sur la 1.7.5 et celle qui est publiée sur le playstore également).

J'ajoute une première entité, déjà cela met quelques secondes à afficher le formulaire alors que d'habitude il n'y a aucune latence. J'ajoute la première entité en remplissant le formulaire, ça c'est bon. A partir de là, dés que je souhaite créer un deuxième point, j'appuis sur le bouton d'ajout et puis il ne se passe rien pendant environ sept ou huit secondes puis j'ai ce message.

Si je fais "attendre" il finit par ré-ouvrir le même message au bout de quelques secondes. Je suis obligé de quitter qfield et de redémarrer.
J'ai construit la carte avec QGIS 3.10.

**Comment by nirvn** [comment]
@frgis , peux tu essayer cette nouvelle serie d'APK: https://github.com/opengisch/QField/pull/1390#issuecomment-722965630 et nous rapporter si la latence de quelques secondes est tjrs la ou non, et si ca freeze la deuxieme fois. 

Merci.

**Comment by frgis** [comment]
ok, je regarde ce soir ou dans le weekend, merci.

**Comment by frgis** [comment]
ça fonctionne mais attention uniquement sur la plus récente.
Bravo :-) !

Il y a juste un petit souci mais je n'ai pas réussi à trouver pour le reproduire systématiquement, deux fois j'ai du fermer l'application parce que qu'en j'ajoutais une entité (après en avoir ajouté 2 ou 3) le premier onglet (sur les 8 onglets) ne s'affichait pas (je veux dire son contenu ; et impossible à saisir dans cet onglet, le nom de l'onglet était là mais il n'y avait pas de contenu, les autres onglets étaient fonctionnels quant à eux). 
Mais comme je dis je n'ai pas réussi à le reproduire de façon systématique c'est arrivé deux fois.
Si tu vois quelque chose là-dessus au cas ou sinon j'essaierai de chercher le comportement qui déclenche l'anomalie.

merci en tout cas !

**Comment by frgis** [comment]
ok in 1.7.6

Thanks
