### ISSUE TITLE
Some translations are not reflected in v1.7.5

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField#1381]
Hi @m-kuhn 

I conducted translation to Japanese language, and some functions on the latest version of QField are not reflected yet.

Could you check them?

### Screenshots and GIFs

First screen is English.

![image](https://user-images.githubusercontent.com/2639701/97977642-ddd50500-1e0f-11eb-855f-3e44d1f37e19.png)

Layer switching menu is still English

![image](https://user-images.githubusercontent.com/2639701/97977726-fba26a00-1e0f-11eb-9f10-7689ea0ddc8f.png)

General tab of setting

![image](https://user-images.githubusercontent.com/2639701/97977804-15dc4800-1e10-11eb-9441-b59276a0bc47.png)

Variables tab of setting (add a new variable)

![image](https://user-images.githubusercontent.com/2639701/97977846-2260a080-1e10-11eb-8c7b-0f5ad3823b84.png)

When we change the mode, the message appeared are still English.

- you are now in browse mode
- you are now in digitize mode
- you are now in measure mode

<img width="496" alt="image" src="https://user-images.githubusercontent.com/2639701/97977978-52a83f00-1e10-11eb-8b01-278618c1c099.png">

## QField version: 1.7.5

![image](https://user-images.githubusercontent.com/2639701/97977610-d281d980-1e0f-11eb-9911-ddfd8034de3f.png)

**Comment by xBcai** [comment]
你的不错了，中文版的设置里全是英文，界面也是，只有很少部分是中文。1.6.0是全汉化了，其他版本（包括最新版）绝大多数是英文。

**Comment by m-kuhn** [comment]
Also affects Turkish https://twitter.com/orucberkay/status/1324083323493384192

**Comment by xBcai** [comment]
非常感谢，希望能修复这几国语言的翻译问题（包括中文版），对于一般人来说操作非母语的APP确实困难。

**Comment by suricactus** [comment]
@JinIgarashi  @xBcai could you please try the apks and confirm the translations are present?
https://github.com/opengisch/QField/pull/1388#issuecomment-723103680

**Comment by berkayoruc** [comment]
> @JinIgarashi  @xBcai @berkayoruc could you please try the apks from this comment https://github.com/opengisch/QField/pull/1388#issuecomment-723103680 and confirm the translations are present?
> 

![Screenshot_20201106-175302_QField Beta 1388.jpg](https://user-images.githubusercontent.com/22800134/98380065-22071600-2059-11eb-88cb-c768072194de.jpg) Some words are still in English.

**Comment by berkayoruc** [comment]
@m-kuhn [This version](https://github.com/opengisch/QField/pull/1388#issuecomment-723103680) is working very well in Turkish. I accidentally tried the [previous version](https://github.com/opengisch/QField/pull/1388#issuecomment-723091330).

**Comment by xBcai** [comment]
非常感谢，1388和1398终于可以看到中文了。还有个问题，部分机型文字显示不太清楚，看着比较累眼睛。
![Uploading IMG_20201107_062026.jpg…]()
![Uploading IMG_20201107_061959.jpg…]()

**Comment by JinIgarashi** [comment]
@suricactus @m-kuhn Thank you for fixing this issue quickly. I have confirmed all the translations are now reflected! It will help Japanese users a lot!
