### ISSUE TITLE
Problème saisie de formulaire texte et lenteur anormale de l'application

### ISSUE THREAD

**Issue by JULIENROC** [opengisch/QField#1382]
Problèmes avec la saisie de texte dans le formulaire :
- Impossible de créer un espace entre les mots que je saisis depuis la dernière mise à jour.
- la saisie intuitive sur une suite de mots me remplace le mot précédent à la place de l'ajouter.

Passer de la saisie d'un champ à l'autre prend anormalement beaucoup de temps et fais régulièrement planter l'application.

Est-ce un problème de paramétrage? ou de compatibilité du logiciel (Je travaille avec une Samsung Galaxy Tab S4 SMT830) ?

En attendant une réponse, je suis repassé sur la version antérieure avec laquelle je n'avais pas ces soucis.

**Comment by m-kuhn** [comment]
Is this still an issue?
