### ISSUE TITLE
webview initial before qgsapplication

### ISSUE THREAD

**Issue by sajadblog** [opengisch/QField#1384]
hi
there is a problem at main.cpp file when you at line 105 initialize QtWebView like this
QtWebView::initialize();
and the next line instantiate QgsApplication.

according to [Qt Document](https://doc.qt.io/qt-5/qtwebview.html#initialize), we must create QtWebView after QApplication creation.

and finally when executing the QField application show this error :

"QtWebEngine::initialize() must be called after the construction of the application object."

**Comment by m-kuhn** [comment]
CC @nirvn

**Comment by nirvn** [comment]
If I remember well, the Qt documentation disagrees with reality. Let me check.

**Comment by nirvn** [comment]
Right, so when you move the QtWebView::intialize() _after_ the QgsApplication app( argc, argv, true ) line, the following error is thrown in the console:

`QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.`

**Comment by suricactus** [comment]
I have encountered this problem when I started working on QField. As far as I remember, bumping the qt version 5.13+ solved the issue.

**Comment by m-kuhn** [comment]
@sajadblog  what's your Qt version?

**Comment by sajadblog** [comment]
5.12.8 
and
5.15.0

**Comment by sajadblog** [comment]
> @sajadblog what's your Qt version?

both 5.12.8 and 5.15.0 has a problem with this issue,
do not have this error ?!!! :O

**Comment by m-kuhn** [comment]
I implemented the proposed change and moved the webview initialisation to after creating the QApplication. The test was done on Qt 5.14.2 and the following warning was shown on startup:

> QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.

Quote from [a recent update of the QtWebView documentation](https://doc.qt.io/qt-5/qtwebview-index.html#prerequisites)

> To make the Qt WebView module function correctly across all platforms, it's necessary to call QtWebView::initialize() before creating the QGuiApplication instance and before window's QPlatformOpenGLContext is created.

For reference, there's also a discussion on the following bug report https://bugreports.qt.io/browse/QTBUG-80912

**Comment by sajadblog** [comment]
thanks.
