### ISSUE TITLE
Automatically increment ID of newly created feature fails

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#1387]
After setting up QGIS 3.16 via widget to auto-increment the ID, QField does not do it - in Qgis it is working as desired

### Reproduction Steps:

1. Setting up QGIS 3.16: Int column Mast_Nr, with following expression: IF ( "Mast_Nr"  is NULL,maximum( "Mast_Nr" ) + 1,  "Mast_Nr" )

2. Using QField Sync to create the project for QField (the layer is set to "offline editing"

3. Create a new feature in Qfield

### Expected behavior:

If a new feature is created, automatically set a new, unique ID

### Observed behavior:

In Qfield 1.7.3 it does not fill any number into the Mast_Nr field

### Screenshots and GIFs
![grafik](https://user-images.githubusercontent.com/15894401/98256640-19421180-1f7f-11eb-9e35-6db5c50c4fae.png)

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:
Usually, setting up the ID of a new feature would only need the expression $ID

This does unfortunately not work since QGIS 3.14, i reported this regression bug already ( https://github.com/qgis/QGIS/issues/37656  ). Maybe those bugs are somewhat related?

Switching to fast edit mode did not change the problem within QField

I'm using Geopackage

**Comment by meyerlor** [comment]
i researched a little more - as soon as i quit Qfield (with double tapping the "back" arrow to shut it down "gracefuly" ) and starting it again, the next item i place is incremented by one. following items are not incremented again, until i close QField. i assume this has something to do with the wal.gpkg etc? as soon these files in the project folder disapear, incrementing works for one step

**Comment by suricactus** [comment]
I would like to have a look, can you please share the project you are using?

**Comment by meyerlor** [comment]
ok, this is getting stranger. i started QGIS with a fresh profile and created a test project with one .shp and one .gpkg layer. both had two columns, "id" (expression: $id) and "ID_workaround"(expression: IF("ID_workaround" is NULL, maximum("ID_workaround")+1,"ID_workaround") )

for both layers in QGIS: none of the fields are incremented. As soon as i manually fill in a "1" into "ID_workaround", qgis increments all following items i add.

in Qfield (gpkg): ID is not incremented. ID_workaround is incremented ONCE when i manually put in a number to the first item i create - then i have to close QField, wait until the *.gpkg-shm and *gpkg-wal disapear from the Tablets' file system. Starting Qfield once again and adding one more item increments the "ID_workaround" once again. shutting down qfield is required again to continue incrementing

for the shp things are now a bit different: the ID field is actually incremented and filled with the correct ID but the ID_workaround field is not incremented, no matter what i manually fill in there to start the process.

Here my test project:
[Zählbug.zip](https://github.com/opengisch/QField/files/5551912/Zahlbug.zip)

**Comment by meyerlor** [comment]
with the new release (1.7.7) the ID_workaround works - when it got initialized (creating the first feature needs a user to fill manually in a number) but that is the same behaviour like in QGIS.
