### ISSUE TITLE
Value '0' is handled as 'NULL'

### ISSUE THREAD

**Issue by soester** [opengisch/QField#139]
Value '0' is handled as 'NULL'

### Reproduction Steps:

1. Create a numeric Field (default value 'NULL' or no default value)
2. insert value '0'
3. Qfield saves value as 'NULL'

### Expected behavior:

It is expected that qfield saves the enterd value '0' in to the field.

### Observed behavior:

Instead of '0' Qfield leaves the field blank (NULL)

**QField version:** 0.10

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: ?
* Problem can be reliably reproduced, doesn't happen randomly: Yes (on postgis and geopackage datasources)
* Problem happens with all files and projects, not only some files or projects: Yes (on postgis and geopackage datasources)

**Comment by signedav** [comment]
Could be solved already. But not sure.

**Comment by soester** [comment]
@signedav
0.10.11 has still the same issue.. but i'm not sure if it was fixed once..
Is this a big thing to fix/fund?

**Comment by signedav** [comment]
I will check that.

**Comment by fahrwegdienste** [comment]
I also encountered this problem and it is a very major problem for us. Happens in QField 0.10.11 and 0.10.9 (I did not check every release). Tested on 2 devices: Galaxy Tab A with Android 7.1.1 and Galaxy Tab Active with Android 5.1.1.

![image](https://user-images.githubusercontent.com/33343856/38352893-f4d31aa0-38b4-11e8-8a90-f2067a55bec1.png)

![image](https://user-images.githubusercontent.com/33343856/38352940-2896f0be-38b5-11e8-9e77-a9a2977add74.png)

Is it related to the field length which is obvisously 0??? Does QField relate on the field length or on the field type? This issue popped up before. It was not possible to create integer fields in QGIS with a field length (QGIS switched an entered field length automatically to 0).

**Comment by soester** [comment]
currently (0.10.12) values are recorded, but not displayed in qfield:
qfield:
![screenshot_2018-04-13-11-36-59](https://user-images.githubusercontent.com/28543978/38732493-9678aaae-3f1e-11e8-80b4-425caebe8682.png)

qgis:
<img width="361" alt="bildschirmfoto 2018-04-13 um 10 55 13" src="https://user-images.githubusercontent.com/28543978/38732518-b460076a-3f1e-11e8-8d70-2e1ca9decaaa.png">

**Comment by signedav** [comment]
Thanks @soester That's what I can reproduce.
If in QGIS 0 -> displayed in QField empty
If in QGIS NULL -> displayed in QField empty
If entered 0 in QField -> 0 in QGIS like expected...

Correct?

**Comment by soester** [comment]
Yes, @signedav that's correct.
QField just doesn't display '0', no matter where the data is enterd.
