### ISSUE TITLE
Shows bad coordinates

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#140]
When I use GPS, I get another place. Even though the day before, everything worked great. Now showing error:
<img src="http://i.imgur.com/CP2BGmb.png" >

Is it possible to solve it?

QField 0.10.0 and 0.10.1
Sony xperia tablet z 4, android 7

**Comment by m-kuhn** [comment]
Seems to be quite consistent in any Android 7 device, definitely something to look into.

The same was already reported in #124 , so I will close this ticket as duplicate.
