### ISSUE TITLE
No .APK at new release (1.7.6)

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#1407]
There seems to be only the source code at the new release without the ready-to-install apk. Will it only be published through the play store?

Same with QfieldSync, there is only the sourcecode ready to download but not the compiled .zip

**Comment by suricactus** [comment]
Thanks for reporting. The apks comming later today.

**Comment by suricactus** [comment]
@meyerlor the APKs are now packages, find them on https://github.com/opengisch/QField/releases/tag/v1.7.6

**Comment by meyerlor** [comment]
same as with last release, no apk to download! :)
