### ISSUE TITLE
Cannot draw lines or polygons

### ISSUE THREAD

**Issue by HoudGIS** [opengisch/QField#141]
Hi,

I cannot draw lines or polygons when switching to Editing Mode.

I exported a simple QGIS project that contains a point, line and polygon layers using Qfield Sync extension. When opening the same project in Qfield i can see my data that i already drawed in QGIS, but when i try to digitize new feature, I only have the points layer in the select list, also i cannot see the pencil button described in the documentation.

I am using an Hp slate tablet with android 4.2.2.
The Qgis project get its layers from a PostreSQL database 9.2.

Best

**Comment by m-kuhn** [comment]
Which version of QField are you using?

**Comment by signedav** [comment]
Strange behavior. Is this still an issue with the latest QField release @HoudGIS 
Thank you.
