### ISSUE TITLE
Image taken within qfield app causes DCIM folder to get corrupt

### ISSUE THREAD

**Issue by vincentvd1** [opengisch/QField#1417]
Have a qfield project with several shape files as layers. One of the fields is set to be an attachment so that I can take images when adding a point. Taking the image works fine nd everything is stored but when I load connect my phone to the computer to transfer the project back I notice that the project's DCIM folder is corrupt ( see image).

### Reproduction Steps:

1. Create a qfield project where the layers are shapefiles (I know atleast point layers have the issue). Set one of the attributes to attachment so that you can take images 
2. Store the Qfield project on your SD card in the qfield documents folder
3. Launch the project in the qfield app 
4. Create a new point feature and for the attachment attribute, take an image and save the new point (I used my native camera app). The bug also occurs when you abort taking an image and store the new point without an image.
5. Save and close the project
6. Connect you phone to the computer and navigate to the folder where the Qfield project is stored

### Observed behavior:
Notice that the DCIM map is now displayed as a file without extention. In my case it is also a few kb large so there is no image stored in it. The image is stored in my local camera folder so the capturing wend fine.

### Screenshots and GIFs

![Screenshot of windows file explorer](https://i.imgur.com/fEPikGi.png)

You can download the Qfield project I am using here: https://1drv.ms/u/s!ArU0pkDFsIFekZEUkZc2vd2aovi1Ng?e=SM76mZ

Qfield version 1.7.5 (couldn't find the built number on the about screen)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [**Yes**/No]
* Problem can be reliably reproduced, doesn't happen randomly: [**Yes**/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No] Well, the project worked before. I only transfered all the layers to shape instead of spatial lite. But even when I abort taking an image, the bug still occurs so maybe the folder is not created properly.

**Comment by jarvojta** [comment]
Happens to me only when storing the project to SD card. DCIM is OK in projects operated in internal memory. It also helps to move the already corrupted project from SD to internal memory. Then it is readable and transferable to PC.

**Comment by WebMaster50** [comment]
Is there any road to a fix for this issue?

**Comment by suricactus** [comment]
Since QField 2.0+ has totally new file handling, can you check whether this issue is still existing in the latest versions?

**Comment by nirvn** [comment]
@vincentvd1 , if you haven't done so yet, please read this storage documentation for Android (https://docs.qfield.org/get-started/storage/), it'll hopefully help you in this new paradigm we live in :)
