### ISSUE TITLE
 "Use completer" support with Value Relation

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#1419]
We keep geobotanical descriptions in nature research works. We have a list of about a thousand plants that we use to record data in the field.
Unfortunately, it is very inconvenient to use a drop list because it is very long and in practice it takes a long time.
For this, it would be convenient to use Value Relation with Use completer. This feature works with QGIS. But QField is not supported?
With "Use completer", entering a letter or syllable in a field automatically filters the list. So no need to search a long list.
I think it would be convenient to use in a variety of fields (bird research, botany, forestry or anywhere else where there is a large drop list).
Does anyone else lack such functionality on QField?

![copleter](https://user-images.githubusercontent.com/6436791/99195873-29cd6580-2791-11eb-863d-12f71b8d67db.png)

**Comment by signedav** [comment]
Thanks @giedrioks26 There are other enhancement requests open #724 #264 and a (as you know) a PR #1374 in the pipeline.

**Comment by m-kuhn** [comment]
@suricactus is this fixed?
