### ISSUE TITLE
POSTGIS serial fields

### ISSUE THREAD

**Issue by ocelot73** [opengisch/QField#1422]
In a postgis point Vector layer, packed with "no action" for qfield, i have problems dealing with two serial fields (one primary key and one not). When I'm inserting a new point in qgis these two fields show respectively "nextval(etcetc::reglass)" that are autonumbered in sequenze, so with qgis everything Is ok.
Inserting a new point with qfield these two fields appear empty and when trying to save qfield doesn't add new point saying those fields can't be null.
I could bypass this setting inside qgis widget a default value on update "maximum(aid)+1" but there could be problems with sequenze numbering since survey on fields Is made by more people in parallel.
How can I mantain autonumbering in sequence and manage to add new points with qfield?
See attached screenshot where the upper field sould write value in Ia serial primary Key column in a postgis db and the other Is just serial)
I'm using qgis 3.10 LTR and qfield 1.7.5

![qfield](https://user-images.githubusercontent.com/59670568/99488137-07417500-2968-11eb-802b-9ca6436fa201.jpg)

**Comment by ocelot73** [comment]
Apart from primary Key fields that are correctly dealt with, the problem is qfield does not real well with postgres default nextval() default value. It seems at commit It doesn't write integer numbers that should be calculated by default,while It tries to write as string 'nexval(sequence::reglass)' and since column Is integer type, the result Is a Null value.

**Comment by monodo** [comment]
As a workaround, you can use `uuid `field in DB as `pkey `and `uuid ` generator field in QGIS widget.

**Comment by ocelot73** [comment]
I could but not for my purpose, since in the second serial column (not primary key) i could store several same ids to track related changes during time so the field has not to contain ubique values. My aim Is to collect points on field progressively numbered in sequence that i could suspend, in case of need, manually inserting another id already stored in db. The problem is qfield doesn't write nextval() values when saving new points.
