### ISSUE TITLE
DCIM folder not seen in Windows after QField sync

### ISSUE THREAD

**Issue by grantboxer** [opengisch/QField#1426]
When I use QField sync the DCIM folder is not seen as a folder. I am not sure whether this is an Android problem or a Windows problem. If I zip the DCIM folder and then copy and unzip it works fine.

**QField version:** QField dev version - Unstable (Early Access) 4th Nov 2020

**Comment by m-kuhn** [comment]
@grantboxer we have had something like this in the past, see https://github.com/opengisch/QField/issues/400

Does the folder appear after a restart of the device?
