### ISSUE TITLE
Data lost from External SD card when uninstall qfield!

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#143]
Data lost from External SD card (/Android/data/ch.opengis.qfield/files) when uninstall qfield. Lost my all vectors layers and photos :-( 

QField version 0.9.10, 0.10.0, 0.10.1
Android 5.1.1

**Comment by m-kuhn** [comment]
I am really sorry for your data!

There is not much we can do here I guess. QField doesn't delete the data actively, I suppose it's Android that does. Do you have a good idea what could be done?

**Comment by giedrioks26** [comment]
Is it possible to leave the ch.opengis.qfield directory if it is not empty when you uninstall QField? Is it possible only with Android?
Uninstalling may or may not be required, but there is a high risk if you sometimes need to go back to an older version of QField.

I now resolved the problem through sync tools (FolderSync and Syncthing). FolderSync allows you to synchronize data between ch.opengis.qfield and com.nutomic.syncthingandroid in an external SD card. Syncthing has the ability to store deleted data for a specified time.
It's work around, but it's not easy for an ordinary user to do this.

**Comment by m-kuhn** [comment]
I totally agree that this is not optimal.
Seems like it's not possible to change this behavior according to this:
https://stackoverflow.com/a/15988690

What we could do is:

- mention this in the documentation (next to the recommendation to use this folder)
- improve QField so it is also able to work with other folders on external sd cards

**Comment by m-kuhn** [comment]
@giedrioks26 can you add a warning on this page here: https://github.com/opengisch/QField-docs/edit/master/en/project-management/android-data-structure.rst

That would be a great first step

**Comment by signedav** [comment]
Since it's not in our power to fix here something, we can close this issue @m-kuhn ? Or how should we proceed on that?

**Comment by giedrioks26** [comment]
Same problem on the internal card. If data is stored on /Android/data/ch.opengis.qfield/files, removing QField, data is lost. It's not safe to put data into /Android/data/ch.opengis.qfield/files the internal and external SD card!

**Comment by m-kuhn** [comment]
What we could do is to migrate this to a new issue that will allow opening (with write access) files from any location. I am confident that Android allows that with some API that requests the user to give an app write permissions for a folder. This way we could move away from this specific folder. What do you think?

**Comment by giedrioks26** [comment]
Ok That's what we have now:
1. On an external card, we can only store data here / Android / data / ch.opengis.qfield, but there is the risk of losing data when uninstalling Qfield. We can also avoid this by connecting an external card with an internal card - "Format as internel".
2. In the internal tab, we can also store data in any folder on the defaul path (but not at /Android/data/ch.opengis.qfield). Data is safe. But the risk of losing is when added to the internal card folder - /Android/data/ch.opengis.qfield. After removing qfield, remove and folder. This happens both external and internal.
So far, we need to know that we do not have to put data into this folder.

Is it right?

**Comment by m-kuhn** [comment]
From what I understand from your tests, yes.

People only save data into `/Android/data/ch.opengis.qfield` because they are told to in the docs. If we can remove this restriction (because we can work with arbitrary locations also on external cards) people will no longer be encouraged to save their files into this location.

**Comment by signedav** [comment]
I'm confused. What is the reason to store the project in `/Android/data/ch.opengis.qfield`?
