### ISSUE TITLE
Photo Geolocation is not working.

### ISSUE THREAD

**Issue by SirSocks** [opengisch/QField#1438]
Issue....
Photo geolocation recently stopped working. The geolocation is no longer being stored within the photos exif data. This feature use to work but recently stopped.

My Settings.... 
I have Open Camera installed with geolocation turned on.
I have "Use native Camera" turned on.
Within my phones privacy settings I have Qfield and Open Camera set to "Allow location data Access at anytime". 

Question...
Is anyone else experiencing this issue?

Note, I'm using the latest version of Qfield 1.7.6

**Comment by SirSocks** [comment]
I have found the cause of the issue. My mobile OS performed an update which added more features to the camera. This update is  limiting access to third party apps that want to access the camera. In my mobile settings, I changed the default camera to Open Camera. This forces Open Camera to launch when a third party app wants to access the camera. 📷

**Comment by suricactus** [comment]
Thanks for updating us. Could you please share your device and OS version in case anyone else faces a similar issue?

**Comment by SirSocks** [comment]
Phone: Huawei P20
OS Version: 10.0.0.172

**Comment by suricactus** [comment]
Thanks!
