### ISSUE TITLE
issue with snapping in qfield

### ISSUE THREAD

**Issue by zakigates** [opengisch/QField#144]
I have a problem with qfield about the snapping. When I configure it in qgis and when I export my package to qfield I realize that the snapping is lost. I import my project once again from qfield to  qgis so that I  can check if it exists, and truly the snapping that I configured in qgis in the begening disappeared. I'm realy stack at this level, cannot move on, and this problem is gonna drive me insane. Please help me find a solution out.

**Comment by soester** [comment]
https://github.com/opengisch/qfieldsync/issues/89
#361

**Comment by signedav** [comment]
Do you use Advanced Configuration in Snapping @zakigates ?

**Comment by soester** [comment]
@zakigates @signedav  should work now:
opengisch/qfieldsync#89

**Comment by signedav** [comment]
Thanks @soester . I close this.
