### ISSUE TITLE
QGIS 32-bit support on Windows and Qfield

### ISSUE THREAD

**Issue by frgis** [opengisch/QField#1444]
Hello,

On this URL (https://blog.qgis.org/2020/10/15/phasing-out-32-bit-support-in-qgis/), it is written that the 32 bit version of QGIS will soon be discontinued.

What is the impact on Qfield for 32 bit devices under Android (i think installer arm 7)?

**Comment by frgis** [comment]
thank you

**Comment by m-kuhn** [comment]
No impact at all expected so far, we will continue to offer 32 bit versions in the foreseeable future.
