### ISSUE TITLE
Layer-defect in QGis after layer-editing in QField

### ISSUE THREAD

**Issue by blattfisch** [opengisch/QField#145]
Layer-defect in QGis after layer-editing in QField

### Reproduction Steps:

1. Create a portable project in QGis with several shapefiles for fieldmapping
2. Transfer and open the project on a mobil device 
3. Ad some objects to the shapefiles during fieldmapping in QField
4. Import the project on a desktop and start the project (.qqs) with QGis
5. All with QField edited layes are defect an cannot be opened
6. A manual link to the shapefiles doesnt fix the problem

### Expected behavior:

After an Re-Import of the project on the desktop the whole project should  appear in QGis with all the edited objects an layers.

### Observed behavior:

I work since March 2017 on the same QField project without any big problems. The re-import of the project on the Desktop to QGis always went fine. But since yesterday I am not able to load in QField edited layers in QGis. Changing to older versions of QGis and QField doesn`t fix the problem. 
So I created severel new projects with different shapefiles, basemaps and coordinates. All project combinations show the same error. After that I tried to install the project on a different mobile device also without success.

### Screenshots and GIFs

![error](https://user-images.githubusercontent.com/30669642/28895675-9f5d1c52-77d9-11e7-92be-59e7cc591642.JPG)

**QField version:**
The error appears with QField 0.8.8, QField 0.9.10 and QField 0.10.1.
I am not able to say if the problem starts with v 0.10.1.
But I recognized the error the first time after the latest update.
The Installation of older versions doesnt fix the problem
I also changend my QGIS Version from 2.18 to 2.14 without success.

**Mobile devices:**
Samsung Galaxy Tab S3 with Android 7.0
Samsung Galaxy S7 edge with Android 7.0
Is it the Android system?

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
Is your project portable? http://www.qfield.org/docs/project-management/portable-project.html

**Comment by signedav** [comment]
What is the status on that issue? @blattfisch Is your project portable? Could you probably provide a project where this happens?

**Comment by 3nids** [comment]
closing due to lack of feedback
