### ISSUE TITLE
Adding features on CSV layers shows an error, but the feature is saved

### ISSUE THREAD

**Issue by suricactus** [opengisch/QField#1459]
1. Create a project with a CSV layer with the OGR provider.
2. Select the layer on the legend and enter editing mode.
3. Try to add a new feature.
4. Shows "Unable to save feature" toast, breaks the form and logs.
5. However, the feature is saved.

Test project:
[qfield_csv.zip](https://github.com/opengisch/QField/files/5650898/qfield_csv.zip)

| form | logs |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/2820439/101318149-84c21c00-3868-11eb-89ce-3ef57f7b5239.png) | ![image](https://user-images.githubusercontent.com/2820439/101318241-aae7bc00-3868-11eb-85e1-812ca09bb8b8.png) |

```
src/core/qgsmessagelog.cpp:29 : (logMessage) [12483ms] 2020-12-07T08:44:58 QField[2] Layer "countries ogr" has been commited but the newly created feature -2 could not be fetched
Nes message  "QField"  :  "Layer \"countries ogr\" has been commited but the newly created feature -2 could not be fetched"
src/core/qgsmessagelog.cpp:29 : (logMessage) [61113ms] 2020-12-07T08:45:59 QField[1] Cannot update feature
Nes message  "QField"  :  "Cannot update feature"
src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] 2020-12-07T08:45:59 QField[1] Feature -2 could not be fetched after commit
Nes message  "QField"  :  "Feature -2 could not be fetched after commit"```

**Comment by nirvn** [comment]
This likely a  GDAL error, this is a problem in QGIS too. The CSV driver returns a garbage feature ID when creating a feature.

**Comment by nirvn** [comment]
Closing as issue is upstream.

**Comment by suricactus** [comment]
Not so sure whether we should close it without explicit warning for such scenario in the docs or even better - directly in the UI.

**Comment by nirvn** [comment]
I think we should open an upstream issue in gdal (or QGIS but my preliminary look into it last month indicated the former) with python code to demonstrate the problem.

**Comment by suricactus** [comment]
@m-kuhn do you think it makes sense to add a note here https://qfield.org/docs/data-formats/index.html , so at least we have RTFM reference?

**Comment by suricactus** [comment]
Follow the GDAL issue here: https://github.com/OSGeo/gdal/issues/3552
