### ISSUE TITLE
QField does not respect whether the layer data source has editing capabilities

### ISSUE THREAD

**Issue by suricactus** [opengisch/QField#1460]
Add a delimited text layer and see the world burning.

**Comment by signedav** [comment]
Can make a note if the issues are concerning the current master or a released version?

**Comment by suricactus** [comment]
In theory - all QField versions. However, this is obvious since current master, because you can list the features from a textdelimited layer now. Probably textdelimited layer with lat/long fields will fail in current releases too. 

I have prepared a fix to expose this info from QGIS side, will be fixed soon. I will take care of this bug.

**Comment by suricactus** [comment]
Fix on the way https://github.com/qgis/QGIS/pull/40695
