### ISSUE TITLE
"fid"-attribute field automaticaly generated. Qfield forces me to fill in a specific number.

### ISSUE THREAD

**Issue by bsturm** [opengisch/QField#1480]
[Short description of problem here]

During the packaging procedure a new attribute field "fid" is automatically generated.
When in editing mode, Qfield forces me to insert a unique Number into this field, eg. 1, then 11, then 111...

When I don't add a number to this field, it says "Bedingung ungültig".

Deleting and reinstalling Qfield didn't change anything.

### Reproduction Steps:

1. Create new Project
Create layer for offline use, without fid-field.

2. Package for Qfield
3. Copy to Tablet, Open Project, Switch to Editing Mode
4. Add new Point
5. "fid" field exists, input is forced.

### Expected behavior:

The layers should be as i created them, without additional fields added. I should not be forced to enter anything.

### Observed behavior:

see above.

### Screenshots and GIFs

![Screenshot_20201215-154926_QField 1](https://user-images.githubusercontent.com/58474997/102232095-006a3b80-3eef-11eb-9277-ea637bf68443.jpg)

**QField version:** 
1.7.7

## Additional information:

* Problem didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

QfieldSync: 3.4.0
QGIS : 3.10.12 LTR

**Comment by m-kuhn** [comment]
Thanks for reporting this.
Are you able to share a project (qgs file + data.gpkg) where you experience this behavior (the qfield / offline project, you can also delete all the data in it if it is critical)

**Comment by bsturm** [comment]
Thanks for your answer.

I now noticed that the behavior is occurring in all my projects, even those that I have been working with for a longer time now.
Only exception: demo projects.

I am sharing the most recent where I noticed first. No relevant data in it. 

[fid_error.zip](https://github.com/opengisch/QField/files/5714559/fid_error.zip)

**Comment by signedav** [comment]
What I can reproduce: 
On auto generated forms and on drag-n-drop forms including the fid field I have the behavior like described by @bsturm. On creating a drag-n-drop form without the fid included, everything works fine. 

@bsturm you decribed:
> Create layer for offline use, without fid-field.

You mean you don't have the fid-field in the form of the online project but in the offline project it appears?

**Comment by signedav** [comment]
The behavior is like this:
- When creating a layer in a Geopackage an fid-field is generated (Geopackage-Side)
- This fid-field is displayed in the form (QGIS-Side)
- QFieldSync does not change anything on the fields. When the fid-field is visible in QGIS it's in QField as well.

Now the misbehavior in QField: The fid field has a constraint on it. You are forced to fill it up.
This has not been the situation always. Before you have been able to leave the field empty and the id has been auto-generated on save.

**Comment by bsturm** [comment]
> 
> 
> What I can reproduce:
> On auto generated forms and on drag-n-drop forms including the fid field I have the behavior like described by @bsturm. On creating a drag-n-drop form without the fid included, everything works fine.
> 
> @bsturm you decribed:
> 
> > Create layer for offline use, without fid-field.
> 
> You mean you don't have the fid-field in the form of the online project but in the offline project it appears?

Exactly.

**Comment by bsturm** [comment]
> 
> 
> The behavior is like this:
> 
>     * When creating a layer in a Geopackage an fid-field is generated (Geopackage-Side)
> 
>     * This fid-field is visible in the auto generated form (QGIS-Side)
> 
>     * QFieldSync does not change anything on this fields. When the fid-field is visible in QGIS it's in QField as well.
> 
> 
> Now the misbehavior in QField: The fid field has a constraint on it. You are forced to fill it up.
> This is introduced in 1.7.6. Before you have been able to leave the field empty and the id has been auto-generated on save.

I don't have the fid field in QGIS before going through the packaging process.
Afterwards i have.

tbh I am not sure, if the fid field was visible before, I have never paid attention.

**Comment by signedav** [comment]
I understand now. Your original source is not a Geopackage source. Fair enough.
Yes, then an fid field is created in fact. By the Geopackage.

We have two issues:
- QField is considering a constraint it shouldn't (I think this is introduced here, but not  sure: ea787cbb7210fa0adea5a85d7ab5aeaaac6b1a80)
- QFieldSync (Offline Editing) is not setting the fid field to invisible - that's not a bug, but might make sense...

**Comment by bsturm** [comment]
Ah, ok, sorry, I should have mentioned. My original source is a Project with various shape-files.

**Comment by bsturm** [comment]
I don

**Comment by suricactus** [comment]
> QFieldSync (Offline Editing) is not setting the fid field to invisible - that's not a bug, but might make sense...
@signedav this is on my todo list, when exporting the project it does not make sense to suddenly to see a `fid` field out of nowhere. If it was already existing in the original datasource, then ok.
What I was wondering whether this is a newly introduced issue or it has always been like this. @bsturm did you start experiencing this new `fid` field recently, or it has always been like this? 
Workaround for this is to open the exported project and edith the `fid` field visibility there.

**Comment by bsturm** [comment]
> What I was wondering whether this is a newly introduced issue or it has always been like this. @bsturm did you start experiencing this new `fid` field recently, or it has always been like this?

I just checked with a device that hasn't updated QField, there is a fid-field as well. So it is safe to say, that it has been like this for a longer time.

**Comment by signedav** [comment]
That the fid is visible (created by Offline Editing) is for sure something we have for a while (or even all the time).

But the issue is:
On 1.7.5 the fid field did not forced a constraint:

![WhatsApp Image 2020-12-18 at 13 08 06](https://user-images.githubusercontent.com/28384354/102613348-99d55f80-4132-11eb-9533-4e7300dee6f1.jpeg)

But since 1.7.6 it does:
![WhatsApp Image 2020-12-18 at 13 08 06 (1)](https://user-images.githubusercontent.com/28384354/102613347-993cc900-4132-11eb-95f6-ba54b4a84473.jpeg)
It's the same project. I compared the releases. There has been done something regarding constraints on invisible fields that should not have an impact. And we updated QGIS. Any ideas @m-kuhn @suricactus ?

**Comment by m-kuhn** [comment]
I have compiled 1.7.7 locally with an older qgis version. The problem does NOT appear, so it seems to be qgis related (and not qfield related)

**Comment by signedav** [comment]
Ah perfect. So it's pretty sure because of QGIS later 30.10.2020.

**Comment by bsturm** [comment]
I first exported from QGIS LTR 3.10.10 - Problem did appear.
Afterwards I updatet to LTR 3.10.12 - Problem did appear.

Problem must be qfield-related, because it appears on my older projects as well. These haven't left the tablet for a couple of months now, because i don't re-import projects for synchronization, i copy the data i need directly from data.gpkg

**Comment by signedav** [comment]
Sorry @bsturm we might got a little too low level here. We talk about the problem in the QGIS version QField uses in the backend.

**Comment by bsturm** [comment]
Ah, ok, sorry then. Thanks for explaining!

**Comment by m-kuhn** [comment]
@bsturm can you test the package from https://github.com/opengisch/QField/pull/1490 , this should fix your problem. We might release an express edition as christmas gift.

**Comment by bsturm** [comment]
Tried it on my Phone and yes, Problem is fixed. Fid-field is without constrain now!
thanks a lot!

Well who doesn't love Christmas gifts..? :)

18.12.2020 16:26:46 Matthias Kuhn <notifications@github.com>:

**Comment by jhemmi** [comment]
Fixed for me too with 1.7.8, thanks Matthias
