### ISSUE TITLE
Errors logged when closing the relation editor

### ISSUE THREAD

**Issue by suricactus** [opengisch/QField#1488]
To reproduce:
1) open the advanced bee demo
2) open the attribute form of any apiary feature
3) try to add a new review. The pop-up appears.
4) Just press the back button
5) Check the log panel

![Screenshot_2020-12-18-10-00-28-41_86d84e99d573f9b57760f7f1cc34e976.jpg](https://user-images.githubusercontent.com/2820439/102589985-887f5980-4118-11eb-91f6-c6b62692e3ea.jpg)

**Comment by suricactus** [comment]
Not sure if the same cause, but after a while the relation editor no longer responds to clicking the + button by popping up the form and becomes unusable.

**Comment by signedav** [comment]
Are those related #1494 ?

**Comment by suricactus** [comment]
The problem is no longer present with the current master. Not sure what fixed it, I would guess https://github.com/opengisch/QField/pull/1490 . Closing for now.
