### ISSUE TITLE
NMEA Improvements

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1492]
Some notes what can be improved regarding the NMEA receiver implementation.

### NMEA (Positioning) Settings: 
- Look: Make understandable buttons
- Feedback: there should be a feedback if a device is currently connected or not - this could be displayed in main screen better as well
- Where should be the setting? We kind of have two positioning settings. Should it be in the GPS Button initiated setting? Or should everything be here in the setting?

### NMEA (Positioning) Backend:
- When loosing connection (e.g. because the reach got too far away) QField should try to reconnect

**Comment by signedav** [comment]
@nirvn Maybe you can consider these inputs when you work on it.

**Comment by nirvn** [comment]
@signedav , absolutely, very useful.

**Comment by gispro168** [comment]
It is very nice to see this feature finally available. 

I found issue with the height/altitude reported in QField which was different from what my GNSS reported. See the screenshots below:

![image](https://user-images.githubusercontent.com/68795459/103114656-17005780-4692-11eb-9263-12f59fd5f829.png)

**Comment by nirvn** [comment]
@gispro168 , សួស្តីបង! I'm assuming you can read this on the basis of your location in Chhbar Ampov :wink:

We're going to do some NMEA bung hunting in the coming days, your report is useful. Have a nice day.

**Comment by gispro168** [comment]
សួស្តី Mathieu ខ្ញុំអាចអានបានតើបង 😉 ហើយយើងក៏ធ្លាប់ជួបគ្នាម្តងពីរដែរ។ សូមអរគុណក្រុមការងារ QField ដែលបានខិតខំបង្កើត និង Add Features អោយ QField which is a very useful useful app. 

I also found issue that QField could not start in my TC20 Controller: https://www.tersus-gnss.com/product/tc20-controller ចង់អោយបងជួយតែស រក bugs ដែលនាំអោយវាមិនដំណើរការ QField. បងអាចជួបានទេ?

**Comment by nirvn** [comment]
@gispro168 , that device might run on an Android version that's too old to support. The website indicates Android 6, is that the case?

**Comment by nirvn** [comment]
@gispro168 , looking at documentation on the internet, the REACH device does broadcast a different altitude via NMEA than it does via its web administration interface or its ReachView app. There, it does some geodesic / ellipsoid adjustment whereas NMEA value is 'raw'. That's as far as Internet search got me.

Looking at the NMEA strings sent by the device confirms it. For example, when the REACH web interface reported an altitude of ~25 meters, its NMEA strings sent were reporting ~38 meters:
```
"$GNGGA,115216.00,1131.3008020,N,10455.7024174,E,1,08,0.0,**38.693,M**,-13.262,M,0.0,*47"
"$GPGSA,A,3,07,09,17,30,,,,,,,,,0.0,0.0,0.0*39"
"$GBGSA,A,3,09,16,21,26,,,,,,,,,0.0,0.0,0.0*29"
"$GPGSV,1,1,04,07,49,340,35,09,43,232,40,17,15,233,39,30,19,326,37*7D"
"$GBGSV,1,1,04,09,60,222,38,16,44,184,35,21,11,232,36,26,24,331,35*65"
"$GNVTG,,T,,M,0.02,N,0.03,K,A*3C"
"$GNGST,115216.00,0.540,,,,2.165,8.086,7.739*6A"
"$GNZDA,115216.00,02,01,2021,00,00*7A"
"$GNRMC,115217.00,A,1131.3008054,N,10455.7023772,E,0.02,,020121,,,A*54"
```

The good news is, you can use the antenna height settings to adjust the NMEA value to match that you've come to expect from ReachView. E.g.:
![Peek 2021-01-02 18-49](https://user-images.githubusercontent.com/1728657/103456801-1fa8fb80-4d2c-11eb-984f-9bb7cb76ff40.gif)

**Comment by nirvn** [comment]
I think this can be closed for now. Individual improvements can be filed later.
