### ISSUE TITLE
Cannot create child features on demo project

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1494]
Cannot create child features in the relation reference of Apiary "Consumation" on the Advanced Bee Farming project opened at the Welcome Screen - while the project loaded from the master into the normal storage and opened over file selector, works fine.

![WhatsApp Image 2020-12-18 at 16 28 42](https://user-images.githubusercontent.com/28384354/102631756-6acce700-414e-11eb-9947-e34ef949a6ff.jpeg)

Could this be related to #1491?

**Comment by nirvn** [comment]
That's been fixed thanks to @m-kuhn .
