### ISSUE TITLE
Build instruction needs clarification

### ISSUE THREAD

**Issue by hieu-van** [opengisch/QField#1498]
Hello there,

I'm currently interested in tweaking some parts of QField so as to make it suitable for our production work. However, IMHO, most of the build instructions provided by you guys are either too summarized or leading to nowhere. For example, what to do after editing config.pri? Build OSGeo4A and then what??

Sorry if this sounds like a rant but it would be really great if you can make the instructions clearer so more people will be able to build and use QField effectively. :wink:

Regards.

**Comment by m-kuhn** [comment]
Yeah, they are terribly outdated!

The best place to start right now would be in https://github.com/opengisch/QField/blob/master/.github/workflows/continuous_integration.yml#L73
Updates to the readme will be very welcome!

Normally you don't need to touch osgeo4a. Avoid if possible ;)

**Comment by hieu-van** [comment]
I see. Is there a non-Docker way? For example, can I directly import QField's source in Qt Creator and start develop?

**Comment by m-kuhn** [comment]
For a desktop version (linux) for development

```sh
git cloud git@github.com:opengisch/QField.git
git submodule update && git submodule init --recursive
```

Now either open the CMakeLists.txt in QtCreator
or use the following lines on bash

```sh
mkdir build
cd build
ccmake -GNinja ../QField # adjust paths for QGIS libs, make sure you have a very recent version of QGIS (build master locally or install nightly)
ninja
```

**Comment by suricactus** [comment]
You can also pass `QGIS_PREFIX_PATH` if you use a standard QGIS build:
```
ccmake -GNinja -DQGIS_PREFIX_PATH=/home/user/Applications/qgis/qgis-master ../QField
```
Where `/home/user/Applications/qgis/qgis-master` is the QGIS installation directory.
```
$ ls /home/user/Applications/qgis/qgis-master
bin  include  lib  man  share
```

**Comment by hieu-van** [comment]
Thanks guys. What is the `OSGEO4A_STAGE_DIR` for? It's making CMake throw errors.

Also, it is reporting that tessellate doesn't contain a CMakeLists.txt file.

**Comment by m-kuhn** [comment]
Osgeo4a staging dir is where the sys prefix for the crosscompiled libs
Tesselate needs git submodules init


git submodule update --init --recursive

**Comment by m-kuhn** [comment]
I opened a pull request to improve the readme. Your review and suggestions will be appreciated.

**Comment by hieu-van** [comment]
> Osgeo4a staging dir is where the sys prefix for the crosscompiled libs

How can I get those libraries? :confused: I'm building on KDE neon 5.19 (Ubuntu 18.04), so most of the libs are installed using apt.

> Didyou follow #1498 (comment) ?

Of course I followed them, but there are probably some culprits in your instructions too…

> Your review and suggestions will be appreciated.

I definitely will help rewrite the build instruction once I finish this.

**Comment by m-kuhn** [comment]
Let's skip the whole osgeo4a part for now. It complicates considerably.

I'd compile with qtcreator for local desktop builds to develop and debug.
I'd use the docker to create an apk.

Instructions should be much simplified in  https://github.com/opengisch/QField/pull/1530

**Comment by hieu-van** [comment]
> Let's skip the whole osgeo4a part for now. It complicates considerably.

I know, I want to skip it too, but looks like CMake won't let me do it:

![VirtualBox_KDE neon_26_12_2020_16_08_09](https://user-images.githubusercontent.com/45692885/103148658-b86fd200-4794-11eb-9d50-cd88d1e0aa18.png)

> I'd use the docker to create an apk.

I know but Docker is mostly used to automate the build process, which unfortunately doesn't apply in my case.

**Comment by m-kuhn** [comment]
For simplicity of life do one of the following two:

 - switch qtcreator build kit to desktop, then qtcreator won't ask for osgeo4a
 - use docker to build for android

That'how most people work

If you want to increase complexity download the sdk from the [osgeo4a releases](https://github.com/opengisch/OSGeo4A/releases/tag/20201214) . That's undocumented so far so be prepared for some obstacles to overcome.

**Comment by hieu-van** [comment]
Yay, I succeeded to build for desktop. Sorry that I forgot to note that I was going to build for Android, not desktop. Can I build for Android without Docker?

**Comment by m-kuhn** [comment]
Cool. 
Yes it's possible. But it's not documented.
