### ISSUE TITLE
QField issue with child table filtered lookup fields.

### ISSUE THREAD

**Issue by djackan** [opengisch/QField#1499]
My project is *offline* and has a parent table and 2 child tables. One child table has a lookup field (Species) that is filtered based on the value chosen in another lookup field (Genus). In QField there are no values present/available to choose from in either field in the child table. Normal lookup fields in the child table operate as expected. The forms and fields work within QGIS. When I open the offline project packaged for qfield within QGIS everything works as expected. 

### Reproduction Steps:

1. Create a project using a PostGIS database
2. The database should have 1 parent table and one or two child tables
3. A child table needs to have one lookup field whose values are filtered based on a choice in another lookup field.
4. Package the project for QField and open it in QField and begin data entry, specifically looking at the child table and the filtered lookup fields.

### Expected behavior:

I should be able to choose a salamander genus and then in the species field it would restrict my species to those only found in that genus.

### Observed behavior:

In QField when I get to the child table and the lookup fields that involve the filtering are blank.

### Screenshots and GIFs

My packaged offline QField project: https://1drv.ms/u/s!AqjJo2iAo7jNgjT6lmDI0NW2z-Va?e=vwigcE

![The filtered fields are blank when using QField](https://user-images.githubusercontent.com/47269665/102725729-e95c8c80-42e6-11eb-88de-2ea918749805.png)

**QField version:** 
QField 1.7.8  In the about there is no build number.

## Additional information:

Using QGIS 3.16.1 code revision | b381a90dca
with QFiedSync 3.4.0

* Problem started happening recently, didn't happen in an older version of QField: [No]
-When tested on an older project where the filter fields are in the parent table the fields work as expected.
I just tested on an older project with the child table and the issue is present.

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

* Problem happens with all files and projects, not only some files or projects: [No]

**Comment by signedav** [comment]
Hi @djackan I cannot download your project but I can assume that you have layerids or layernames in the filter expression.
If so, then these get broken in the offline project: Layerids are unique and change in an offline project, layernames receive the suffix " (offline)" - The second thing is fixed in QGIS > 3.16.1 and QFieldSync 3.4.0. Please check it out :-)

**Comment by djackan** [comment]
@signedav I changed the formatting you should be able to download the project now.

**Comment by signedav** [comment]
Okay, then the layer name is not the reason. It needs some more research.
Maybe you can use meanwhile the relation reference widget instead @djackan ?

**Comment by djackan** [comment]
@signedav Thanks for pointing out the relations reference widget. I will see if I can understand how to use it. I am using QGIS 3.16.1 code revision b381a90dca with QFiedSync 3.4.0. I updated my report to reflect this. Below are the images of my _value relations_ widget settings, though like I said it works in QGIS.

![organism_genusid](https://user-images.githubusercontent.com/47269665/102785347-d50ea300-436b-11eb-82f2-6cb59c50a364.jpg)

![organism_speciesid](https://user-images.githubusercontent.com/47269665/102785355-d8099380-436b-11eb-9144-a931cc33f7db.jpg)

**Comment by djackan** [comment]
One thing to note it appears that if the filtered field using the value relations widget is in the parent table it works, but if it is in a child table it does not. For my use case I can have one observation point with multiple organisms found each needing a record for that observation, thus the child table. Keep in mind though the parent-child table arrangement works in QGIS.

**Comment by djackan** [comment]
With the most recent update (2068da v1.8.1) this bug no longer occurs.
