### ISSUE TITLE
QField master freezes when launching (on linux)

### ISSUE THREAD

**Issue by nirvn** [opengisch/QField#1500]
@signedav , since the merging of the NMEA/bluetooth PR, I can't successfully launch QField on my workstation.

The app freezes in the BluetoothReceiver constructor, here:
![image](https://user-images.githubusercontent.com/1728657/102766826-4e7cb480-43b1-11eb-902a-456493351f28.png)

Note: I'm on Qt 5.14.2.

**Comment by signedav** [comment]
Possible that it's because of the Qt Version since I'm using 5.15 but still I don't know what I'm using, that is not yet supported by Qt 5.14 (at least not in C++). But when it can compile, then it should not have unsupported stuff there. :thinking:

**Comment by m-kuhn** [comment]
Something in here maybe https://code.woboq.org/qt5/qtconnectivity/src/bluetooth/qbluetoothlocaldevice_bluez.cpp.html ?
Do you have a bluetooth service on your system that you could start?

**Comment by nirvn** [comment]
On my laptop, QField runs fine. Both my workstation and laptop run on Ubuntu 20.20 with Qt 5.14, however my workstation has _no_ bluetooth hardware. It's likely we'll need to have the code deal with bluetooth-less environments.

**Comment by signedav** [comment]
Hm. I think you are right. Thanks for checking that.

**Comment by m-kuhn** [comment]
@signedav do you have an idea how to do that? I had a look and didn't find any possibility. It seems that simply creating a `new QBluetoothLocalDevice()` will freeze, can we detect bluetooth availability even earlier?

**Comment by signedav** [comment]
I didn't checked it out deeply.

But it doesn't need a QBluetoothLocalDevice for all the QBluetooth activities. So if other objects do not freeze but return a false `isValid()` or similar we might go for that. But I guess they freeze as well.

Another sollution might be - at least for Android devices - to use plattform utilities and check for `BluetoothAdapter.getDefaultAdapter()`...

**Comment by m-kuhn** [comment]
@nirvn partially fixed?

**Comment by nirvn** [comment]
I realized that it unfroze after a minute or two. Then in subsequent runs, freeze is gone. I think we can close this for now (I closed the PR earlier today).

**Comment by m-kuhn** [comment]
Interesting... Maybe a dbus timeout ...

**Comment by nirvn** [comment]
Felt like it.
