### ISSUE TITLE
Unhandy behavior of double field

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1502]
When having a range / text edit widget with double number it reacts weird with the seperator.
![double_field_qfield](https://user-images.githubusercontent.com/28384354/102768878-20cc4700-4382-11eb-9200-7ad94caa0426.gif)

When inserting the number slowly, so it accepts the point (no underline), then it works.
Otherwise it puts the point to the end.
**QField version:** 1.7.8 and Master

## Additional information:
* Problem started happening recently, didn't happen in an older version of QField: I think it's here since 1.7 (at least) but I didn't validated
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by suricactus** [comment]
Also here https://github.com/opengisch/QField/issues/1440

**Comment by signedav** [comment]
Ah sorry, I think I motivated this user to open an issue and I didn't noticed he actually does. Closing this an putting the video to the other issue.
