### ISSUE TITLE
form carrying over invalid value from previous feature when not required

### ISSUE THREAD

**Issue by ARBkey** [opengisch/QField#1507]
Some of the the values from previously entered feature are placed in the next feautes form fielsd without the carry over box checked. 
These values are not considered as entries by the field and the field remains red and invalid (The field is set up to not accept NULL entries)

### Expected behavior:

Field should be blank for entry with a new value

### Observed behavior:

Within feature entry form

**QField version:** 1.8

## Additional information:

Problem just began occurring in 1.8

**Comment by m-kuhn** [comment]
Which values does this concern? Any attribute type or widget configuration in particular?
A demo project would be a great help.

**Comment by ARBkey** [comment]
@m-kuhn integer fields seem to be the only affected. The fields are set to a default value of NULL with a condition that the fields must not be NULL to validate. When the first feature of a session is added the field is NULL as planned. When the second feature is added the  values are carried over from the previous form instead of being NULL as planned. Interestingly, these values also do not validate the field.
See the attached screen shot from when I add the second feature.
![Screenshot_20210104-163241](https://user-images.githubusercontent.com/64572560/103504220-e3e87000-4eaa-11eb-9d85-aee40109d41d.png)

I will send a demo project to your email

**Comment by she-weeds** [comment]
I have encountered the same issue and so far have only noticed this with integer datatypes with a Range widget (editable, dial, or slider), regardless of whether an expression or NOT NULL constraint is applied, and regardless of whether 'Allow NULL values' is selected. This is using a project set up in QGIS 3.16.1 and I think I have seen this in previous versions of QField myself.

This behaviour does not occur when using Text Edit widget on integer datatypes (which forces the keyboard to be numeric only, so similar UI to Range with editable UI) - @ARBkey you may find this an useful stopgap.

However it isn't a complete workaround, as there are some features only available on the Range widget (slider UI, step number). Presumably in future releases when a +/- button is added this would only be available with Range and not text edit...

See attached demo project with bare basics - the same file (integers.shp) with two separate forms, one where dbh_int uses the Range widget, and another where dbh_int uses the Text Edit widget. You will notice that after digitising the first feature with the Range widget, the next one will retain the dbh_int value from the previous feature. And if you enable a NOT NULL constraint, the retained value doesn't satisfy the constraint.
[Integer test.zip](https://github.com/opengisch/QField/files/5763197/Integer.test.zip)

**Comment by nirvn** [comment]
@ARBkey , thanks for reporting, it'll be fixed in upcoming 1.8.4.
