### ISSUE TITLE
Allow single finger zoom

### ISSUE THREAD

**Issue by nyalldawson** [opengisch/QField#1509]
It would be great if qfield supported the Google maps style single finger zoom gesture, where a double tap and hold causes up/down movements to zoom in or out of the map.

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by m-kuhn** [comment]
See also https://github.com/opengisch/QField/issues/96

**Comment by suricactus** [comment]
Fixed by https://github.com/opengisch/QField/pull/1546
