### ISSUE TITLE
White pixel row shows at top of application

### ISSUE THREAD

**Issue by nyalldawson** [opengisch/QField#1511]
One for @nirvn 😉

There's a single pixel row of white always shown at the top of qfield. It's most noticeable in the settings screen, as shown below, but it's actually present on all screens

![Screenshot_20201224-063322](https://user-images.githubusercontent.com/1829991/103035006-fa8cee00-45b1-11eb-8b8c-36d23cb90053.png)

**Comment by nirvn** [comment]
@suricactus , was your experiment in setting the main window background successful here? Can't remember.

**Comment by suricactus** [comment]
Nope, neither margins nor bgcolor.

**Comment by nirvn** [comment]
Ok, I think we can unfortunately close this one on the rational that it's an upstream bug.
