### ISSUE TITLE
Print to PDF opens confusing menu

### ISSUE THREAD

**Issue by nyalldawson** [opengisch/QField#1514]
Selecting the "print to PDF" option results in a little floating menu opening in a different part of the screen, with no explanation of what the menu/choice is asking the user for.

It would probably be cleaner and more user friendly to open a pop-up dialog with a descriptive label "Select the template to use for the PDF" and a combo box to select the desired layout.

**Comment by nirvn** [comment]
@nyalldawson , is the newly-added disabled menu item to provide a bit of info is sufficient in your view:
![image](https://user-images.githubusercontent.com/1728657/103130844-f3a8cd00-46d0-11eb-8001-af22d03a485c.png)

**Comment by nirvn** [comment]
Let's close this, I think the recent changes have resolved the issue here.
