### ISSUE TITLE
Consider splitting the settings menu

### ISSUE THREAD

**Issue by nyalldawson** [opengisch/QField#1515]
Currently opening the settings menu shows a mix of "file" type operations (open project), settings options (settings/about/log) and project interaction tools (measure, export pdf).

It might be cleaner to separate this into two buttons, one containing project related operations and the other with the settings related options.

Alternatively I'd suggest rearranging the actions so that the less-frequently-used settings ones appear below the project interaction actions.

**Comment by nirvn** [comment]
We've dealt with this.
