### ISSUE TITLE
Compilation error for android, app version 1.8.0

### ISSUE THREAD

**Issue by daydreamer54** [opengisch/QField#1521]
Compilation error for android, app version 1.8.0

OS information : Ubuntu 18.04
docker --version : Docker version 19.03.6, build 369ce74a3c
docker-compose --version : docker-compose version 1.27.4, build 40524192

I followed these commands to get android apk:
```

sudo apt-get update
sudo apt-get install docker.io
git clone https://github.com/opengisch/QField.git
TAG=20201214
cd QField
git submodule init
git submodule update
sudo docker run -e APP_VERSION=1.8.0 -v $(pwd):/usr/src/qfield docker.io/opengisch/qfield-sdk:$TAG /usr/src/qfield/scripts/docker-build.sh --rm --verbose
```

```
The error : FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /usr/src/qfield/build-docker/android-build/AndroidManifest.xml:3:3-117:17: AAPT: error: attribute android:requestLegacyExternalStorage not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.

See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 4m 57s
20 actionable tasks: 20 executed
Building the android package failed!
  -- For more information, run this command with --verbose.

```  
 
 This is the first time i'm trying to compile the application to android. I've searched the errors above and tried to add permissions in AndroidManifest.xml file but still getting the same error every time. Anyone can help me?

**Comment by m-kuhn** [comment]
Please try

```
sudo docker run -e ANDROID_NDK_PLATFORM=android-29 -e APP_VERSION=1.8.0 -v $(pwd):/usr/src/qfield docker.io/opengisch/qfield-sdk:$TAG /usr/src/qfield/scripts/docker-build.sh --rm --verbose
```

**Comment by daydreamer54** [comment]
Thank you for your feedback, i was about to comment that how i fixed my issue. When i clone the project in AndroidManifest.xml file this tag was added in <application> tag as default => android:requestLegacyExternalStorage="true"  but at the time i was getting this error  =>   /usr/src/qfield/build-docker/android-build/AndroidManifest.xml:3:3-117:17: AAPT: error: attribute android:requestLegacyExternalStorage not found.

I removed this line from application tag => android:requestLegacyExternalStorage="true" then compile it with this command => 

sudo docker run -e APP_VERSION=1.8.0 -v $(pwd):/usr/src/qfield docker.io/opengisch/qfield-sdk:$TAG /usr/src/qfield/scripts/docker-build.sh --rm --verbose
