### ISSUE TITLE
Search: when a point is selected the map is zoomed incorrectly when the point layer's CRS differs from project CRS.

### ISSUE THREAD

**Issue by stevenmizuno** [opengisch/QField#1542]
With the example project CRS in EPSG:32632, when a point is selected from Search, if the layer has EPSG:4326 as its CRS and the map needs to be zoomed to show the point, the map is zoomed/panned to something like the point's x,y values taken in map coordinates without transformation. The map scale is appropriate for the point selected.
Selecting the point a second time causes the map to be panned to the point's location as transformed to the map CRS as expected.

And if the active layer is 3D, when the cursor is moved over a vertex that is on a visible layer with EPSG:4326 as its CRS the cursor disappears and the location information is approximately the vertex location (in the layer CRS) taken as map CRS.

The key is that the layer CRS is different from the map CRS, not specifically EPSG:32632 / EPSG:4326 as in the example provided. You could change the example project CRS to EPSG:3857 and see the issue with any of the layers in the example database.

Noticed this with QField 1.6.4; I haven't used any earlier version. It is still a problem with 1.8.0.

Initial select P01 
![Screenshot_20201228-092648_QField](https://user-images.githubusercontent.com/14251800/103225488-eb939c00-4921-11eb-87e0-9be9df43eeb3.png)

2nd time selecting P01 
![Screenshot_20201228-092708_QField](https://user-images.githubusercontent.com/14251800/103225541-07973d80-4922-11eb-9adb-c88fad37d4ed.png)

Active layer is 3d
![Screenshot_20201228-092734_QField](https://user-images.githubusercontent.com/14251800/103225618-3e6d5380-4922-11eb-8a57-cafde2f2a943.png)

### Reproduction Steps:
QField Settings:

- Show scale bar: ON
- Fixed scale navigation: OFF
- Show digitizing information: ON

These settings are so the map is zoomed as necessary and to show more information.

Set Digitize mode for cursor/location indication.

Example project and data: [test-QField-search-zoom.zip](https://github.com/opengisch/QField/files/5747670/test-QField-search-zoom.zip)

The project to demonstrate: test-QField-Search-Zoom.qgs

- project CRS: EPSG:32632
- layers from a GeoPackage database
- has themes: all, no 3D, no polygons, no 4326, no 32632

GeoPackage database: test_qfield.gpkg

- Has point, linestring, polygon tables in 32632, 4326; also 3d 4326, 3d 32632.
- The linestring layers are used for zooming to a small enough scale such that the map is zoomed to display a point.
- Feature names: P... for points, L... for linestrings, Py... for polygons
- Some features in the tables have the same coordinates, transformed as necessary, to show that the layers are properly transformed.
- Other features are only on particular layers. There is at least one feature on each layer that is not duplicated to other layers.
- Created using SpatiaLite 5.0

QField renders the map with the various different layers' CRS OK -- corresponding points, lines overlay as expected.

### Test procedure
Run test for each of: 32632, 32632 3D, 4326, 4326 3D layers as active; it doesn't matter if the active layer is point, line or polygon.

Select points from 4326 and 32632 layers. 

Move map when indicated so vertexes from 4326 or 32632 layers are under the cursor.

The overlaid features might be confusing as a vertex under the cursor is picked up from the first visible layer that has a vertex at the cursor location.
overlaid features: P 01... and P 02... and L 01... and L 02... along with polygons Py 01...

Steps for each test:

1. set a layer active (don't do this first time after starting QField, load project)
2. zoom to layer: lines_32632 (same as map CRS) -- this is so a zoom action has to occur when selecting a point
3. Search for 'p 0' or more specific, as 'p 01', for example
4. choose a point from the list
5. observe map: scale bar, cursor, cursor location indication (x:, y:), is the selected point shown?
6. in Search select the same point as in step 4.
7. observe map as in step 5.
8. move the map slightly -- what does location indication show?  the cursor?
9. move the map so a vertex is under the cursor -- what does location indication show?  the cursor?
---- end test procedure ----

### Summary of test results:

Search / Select point zooms map to the point's location when the point selected is on a layer in EPSG:32632. 

If the point selected is on a layer in EPSG:4326 the zoom goes to a location that appears to be the long/lat value (very approximately) taken as x/y in the map CRS. 
Selecting the point a second time pans the map to the point's location.

If a 3D layer is active and the map is moved such that a vertex that is on a layer in EPSG:4326 is under the cursor, the cursor disappears and the indication appears to be the long/lat value taken as x/y in the map CRS.

**Comment by nirvn** [comment]
@stevenmizuno , is it still an issue with the latest QField 2.0 beta? If so, could you try to provide a screencast of the issue? I've tried (and failed)  to duplicate this issue in the past, more information is needed if it's still a problem.
