### ISSUE TITLE
Selection issues with point features

### ISSUE THREAD

**Issue by tethysgeco** [opengisch/QField#156]
Hello, first of all we wanted to let you know how much we appreciate the lots of benefits Qfield delivers compared to other field data survey collection systems, despite some issues that are being constantly addressed in this thread. So really thank you for the great work!

Right now we are heavily testing Qgis & Qfield capabilities for field work, and therefore in the following weeks we can inform you on some of the main issues we have noticed.

To begin with, we wanted to inform you there is a very simple but quite useful command that doesn’t work properly: the selection on point data.

We are using Qgis v. 2.18.7 and Qfield v. 0.10.0 and we observed that selections attained by pressing point features (in Qfield):

>directly on screen or
>through attributes selection in the right area (where tabular data is shown) 

aren’t highlighted in the map, as it correctly occurs with polyline features. 
When you press a line or scroll in the attributes table the different selected lines, the chosen feature in the map rightly changes colour in association with the shown record, so that you can easily associate data to a specific location. 
For point features, instead, it is impossible to understand which record in the attribute table is associated to the specific points shown in the map, as no highlighting occurs.
We believe this is a very useful information when you operate in field; we didn’t try yet with polygon features, so we don't know if it works fine or not.

To solve the issue we tried to modify options in Qgis under Settings - Options menu (highlight color, buffer, minimun length) before uploading the project to Qfield, but it looks like these settings aren't being properly transmitted to Qfield or, maybe, we just didn't get it right and this is not the point to sort things out.

Did you also notice this issue or do you have any suggestions to solve this problem?

Thank you very much and Best Regards

The Tethys GIS-team

**Comment by m-kuhn** [comment]
Great to hear you enjoy the app and the QGIS ecosystem.

Yes, we are aware of the issue. The selection is actually there but 1 pixel in size only which was an acceptable (while certainly not optimal) behavior back in the days of lower resolution screens.

We are not aware of anything you could do, except for pushing a fix for this issue forward.
