### ISSUE TITLE
Log the last position when tracking

### ISSUE THREAD

**Issue by AgroGPS** [opengisch/QField#1564]
QFiled should log the last/current position when tracking is stopped. Right now when tracking is stopped the current position is not logged. So, for example, if the condition of the tracking is set to 1000m and tracking is stopped after 800m from last vertex, 800m of the track is lost :( And in the case where there is request to go to target and the last portion of the track is lost there is not evidence that You have been on target :(

**Comment by nirvn** [comment]
@AgroGPS , your issue/enhancement has been taken care of in this PR (https://github.com/opengisch/QField/pull/3247). Feel free to test and provide feedback. Thanks for taking the time to report this implementation gap.
