### ISSUE TITLE
Displayed rows when attribute table is open

### ISSUE THREAD

**Issue by AgroGPS** [opengisch/QField#1567]
When editing the feature in the terrain, I always edit 10th attribute. On some previous version it worked as follow - on first edited feature, it had to be scroll down the attribute table to edit 10th attribute but on next edited feature the attribute table opened right at position of 10th row (at position as it was whenthe table on previous feature was closed). But at current version of QField the attribute table always opens from 1st row. So, at every edited feature there is need to scroll down the table to edit 10th row/attribute :(

**Comment by nirvn** [comment]
@AgroGPS , I don't think this will be fixed, I assume a mob of users would shop up demanding for a newly opened feature form to start at its top :wink: 

One suggestion that would improve your workflow: customize your feature form by using a drag and drop designed form in QGIS:

https://user-images.githubusercontent.com/1728657/135708772-c79d2241-4d3d-448c-95f4-9afce781744d.mp4

You can drag your most-often used attribute(s) to sit at the top of your form. Instant gratification :) 

Happy field mapping!
