### ISSUE TITLE
Hardware back button

### ISSUE THREAD

**Issue by AgroGPS** [opengisch/QField#1568]
I think QField totally ignore hardware/Android back button. From smartphone usage - when I something don't want and want to go back, I press back button. And in QField it doesn't works like that. For example - from table of selected features I choose the feature to edit and I change some attribute. But then I found out that it's not that feature that I want edit. I want to go back to the table of selected features and select another feature. So, I press hardware back button. Sorry, I can't exactly remember where I get, but then I edit another feature. But when I then check the first selected/edited feature, the changed values are there :O Nevertheless I don't confirm the editions on that feature!

**Comment by signedav** [comment]
Hi @AgroGPS Yes, this is a behavior is in internal discussion. I think the thought was, that the back key is not a cancel key. When you go to e.g. a setting in Android, you change something and you go back, it's set as well. There is no Confirm-Button. But I agree on you that this behavior is confusing. I think we will change that in future. Cancel the changes with back key, or at least let a message pop up, asking you what should be done: commit or discard changes...

**Comment by AgroGPS** [comment]
Oh. I didn't know about that behaviour of hardware back button on Android. OK, then it will be hard, because it can be used anywhere within QField :( For example - when tracking is started, condition chosen and on attribute window the back button is pressed, the tracking starts :(

**Comment by signedav** [comment]
Yes. But I think most users use the buttons. I think we could change the behavior in future.

**Comment by nirvn** [comment]
Fixed/implemented.
