### ISSUE TITLE
Strange behaviour when tracking without any condition

### ISSUE THREAD

**Issue by AgroGPS** [opengisch/QField#1569]
When the tracking is started without any condition for vertex distance (due to forgotten or misalignment as condition for distance and pipe (as OK) are close to each other) the tracking don't start - OK. There is not tracking icon on the layer - OK. But when then the tracking is started (again) - there is an message that tracking was stopped :(

**Comment by signedav** [comment]
Can you test with the latest beta release 1.8.1? Thanks a lot.

**Comment by AgroGPS** [comment]
I tested. Now it works as follow - when tracking is started without any distance condition, the tracking starts normally :( - there is tracking icon on layer and line is draw on map canvas. But at the end, when tracking is stopped, any line is saved.

I suggest that QField should not allow you to go further when You don't choose any distance condition ;)
