### ISSUE TITLE
Cannot add new features on latest version

### ISSUE THREAD

**Issue by AgroGPS** [opengisch/QField#1570]
Why the process of adding new feature is in reverse order as on desktop? On desktop You first make an geometry and then add attribute values. Maybe for terrain work is (for someone) better the reverse order. I have no problem with current behaviour, but on the latest version the QField started to check if the attribute value can be null or not. And I got problem :( I use layers from geopackage. I track my path in terrain as line feature without any attribute. But in case of geopackage, the layer need to have at least ID (not null) attribute. I have set it to autoincrement. But in current version of QField when the tracking is started You have to add values for not null attributes otherwise QField don't allow You to go further. I don't know ID of last feature, I don't care of it and I can't remember it as I make 60-100 paths pre day.

**Comment by signedav** [comment]
Can you test with the latest beta release 1.8.1? Thanks a lot.

**Comment by AgroGPS** [comment]
Now it's works :) Perfect. Thank You very much.
