### ISSUE TITLE
Polygons cretaed with version 1.8.0 are not visible

### ISSUE THREAD

**Issue by IvanPusica** [opengisch/QField#1575]
Polygons created with version **1.8.0** are not visible because **only one coordinate** is written in geometry field. Screenshot with wkt interpretation of geometry is attached.

### Reproduction Steps:

1. Create geopackage with spatial table of polygon type. Create some polygons in QGIS.
2. Upload project with QSync to mobile device. Polygons created in QGIS are visible in QField.
3. Create new polygons in QField, they will be created but it will not be visible. Check geometry in QGIS.

### Expected behavior:

Polygon is visible.

### Observed behavior:

Polygon is not visible.

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/54592371/103687090-02746700-4f90-11eb-8d2a-e3986ec259cc.png)

****QField version: 1.8.0**

**Comment by nirvn** [comment]
@IvanPusica , can you provide a test dataset? I can't reproduce here.

**Comment by IvanPusica** [comment]
@nirvn , i have attached .zip with test data. 
[TestData.zip](https://github.com/opengisch/QField/files/5897587/TestData.zip)

**Comment by nirvn** [comment]
@IvanPusica , I can't replicate the issue with your test data -- can you give the latest QField release (1.8.2) a try?

**Comment by IvanPusica** [comment]
@nirvn release (1.8.2) "Selma" works fine. Polygons are valid and visible.
