### ISSUE TITLE
Keyboard popup in dropdown form is obstructive in short lists

### ISSUE THREAD

**Issue by soester** [opengisch/QField#1579]
When opening a dropdown with a short list the popup of the keyboard hides most of the list.

### Reproduction Steps:

1. Add a value relation list with eg. 7 items or similar to a form,
2. Open the form in qfield
3. Enter the list 
4. 'Cursor' jumps to search field and keyboard pops up

### Expected behavior:
Would be nice if items of short lists could be selected directly, without removing the keyboard.

https://user-images.githubusercontent.com/28543978/103797873-4f684400-5049-11eb-8f6f-73b8c1dc1aaf.mov

**QField version:** 1.8.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]

**Comment by soester** [comment]
By the way:
The search functionality is a very nice feature : )!

**Comment by signedav** [comment]
Thanks @soester That's a good point, but I don't mark it as a bug, since I think this is made like this on purpose.

@suricactus Any thoughts on that? I guess it's this behavior vs. no keyboard pops up and the user needs to click into "Search..."
The implementation might be just setting the focus differently.

**Comment by suricactus** [comment]
There is a workaround this:
If you don't set auto complete in QGIS, you will get just a regular dropdown. It has native support on the platform and looks not bad at all.

A "fix" for this would also be skipping the focus of the search field if `popup.scrollHeight > popup.height`. I believe for long list focusing the search field by default is a must.

**Comment by soester** [comment]
@signedav + @suricactus, thanks for the replies...

> There is a workaround this:
> If you don't set auto complete in QGIS, you will get just a regular dropdown. It has native support on the platform and looks not bad at all.
Is this a global QGIS option or something i can adapt for each field in the form editor? I didn't find any option in the value relation widget.

> 
> A "fix" for this would also be skipping the focus of the search field if `popup.scrollHeight > popup.height`. I believe for long list focusing the search field by default is a must.
This would be a good fix. But, if i know the values in the list, i think i'am much faster without having to type anything.
Maybe it would be also possible to skip focus if there are less than 10? items in the list?

**Comment by soester** [comment]
There is another thing:
Values wich are hidden by the keyboard cannot be selected if the keyboard is not hidden with the back button.
If you scroll up items from behind the keyboard, they cannot be selected.
Hard to describe, but:

https://user-images.githubusercontent.com/28543978/105845643-67ddd580-5fdb-11eb-89a5-9736f0516a42.mov

**Comment by suricactus** [comment]
Hey, @soester thanks for elaborating the issue. Can you please try #1699 and comment whether it fixes the issue for you?

**Comment by soester** [comment]
@suricactus 
no, sorry 1699 doesn't fix https://github.com/opengisch/QField/issues/1579#issuecomment-767514279 for me
allthought the hide when scroll feature is nice!

**Comment by suricactus** [comment]
> Hard to describe, but:
I do agree, I misunderstood the issue.
@soester can you confirm https://github.com/opengisch/QField/pull/1702/ is the fix you were looking for.

**Comment by soester** [comment]
@suricactus 
was now able to test and can confirm the fix. Many thanks!
