### ISSUE TITLE
label displayed for selected features

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#158]
When identifying a feature in QField, each one is nammed by default with the first attribute field (or is it the "ID" nammed one ?). I thought I could manage it in QGis, using the display menu (in layer properties) where it is possible to choose which attribute to show with cursor.
It seems I succeed with one layer but not with another one. Does QField manages things this way ?
A clue about this behavior ? Is it possible to manage selected features label displayed ? If yes, how to proceed ?

QGis 2.18.4
QField 0.10.1

**Comment by m-kuhn** [comment]
It's all in the documentation. http://www.qfield.org/docs/project-management/vector-layers.html#display-expression

**Comment by VxTedxV** [comment]
Shame on me, sorry for bothering and thank you !
