### ISSUE TITLE
Sylus pen issues 1.8.1

### ISSUE THREAD

**Issue by violetlatch** [opengisch/QField#1581]
[Stylus pen on Samsung Galaxy tab Active 2 not functioning. Cannot open project, menus, settings etc. with stylus pen]

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version [1.8.1]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
Is this a regression from 1.8.0?

**Comment by violetlatch** [comment]
> Is this a regression from 1.8.0?

Yes, seems to be. Stylus pen works for digitizing but not for any of the menus or buttons etc.

**Comment by nirvn** [comment]
@violetlatch , and it used to work before right?

**Comment by violetlatch** [comment]
> @violetlatch , and it used to work before right?



> @violetlatch , and it used to work before right?

Yes, works fine on 1.7.8

**Comment by nirvn** [comment]
@violetlatch , can you check whether it worked in 1.8.0 so we can be sure which version regressed?

**Comment by violetlatch** [comment]
> @violetlatch , can you check whether it worked in 1.8.0 so we can be sure which version regressed?

Not working on 1.8.0 either. Something to do with size of stylus pen, menus etc. work if I use my finger.

**Comment by nirvn** [comment]
It might have to do with 1.8.0 having moved to Qt 5.15.

**Comment by m-kuhn** [comment]
@nirvn I have created a qfield-sdk with 5.14.2 to check (https://github.com/opengisch/OSGeo4A/actions/runs/469698669)

**Comment by violetlatch** [comment]
Working again, many thanks
