### ISSUE TITLE
Extracting z information from a point layer

### ISSUE THREAD

**Issue by zakigates** [opengisch/QField#159]
I am using qfield and I am wondering if there is a way to get the elevation information from gps and display it in a field that I would create in qgis just like x and y coordinates.

**Comment by zakigates** [comment]
waiting for your aswers

**Comment by m-kuhn** [comment]
Yes, it is. Just set `z($geometry)` as default value for this field.
It would be great if you could add this information to the documentation!

**Comment by zakigates** [comment]
This is not working because in qfield they don't give the z value, just x and y.

**Comment by m-kuhn** [comment]
> This is not working

that could be true for you

> because in qfield they don't give the z value, just x and y.

that's wrong

**Comment by zakigates** [comment]
I did z ($geometry) but when I added a new feature point qfield did not
return the z value in the reserved field. I got just x and y.

**Comment by m-kuhn** [comment]
Did you link the crosshair to the positioning sensor?

**Comment by zakigates** [comment]
Yes i did it but still no result. When I add a point via the crosshair this
one is not added I don't know why and no information about the z

**Comment by zakigates** [comment]
here is a screen shot frm qfield
as you see I'm using tge screenhair but nothing displayed in the z field
this the configuration of the z field on qgis
[image: Images intégrées 1]

2017-10-16 11:23 GMT+02:00 zakaria mouqcit <zakaria.mouqcit@gmail.com>:

**Comment by m-kuhn** [comment]
I guess you need to use the github interface, the image does not show up unfortunately.

**Comment by zakigates** [comment]
here is a screen shot from qfield
as you see I'm using the crosshair but nothing displayed in the z field
![screenshot_2017-10-16-15-51-51 1](https://user-images.githubusercontent.com/30039918/31619054-f250ec0a-b293-11e7-881a-4b97c2d0dfbf.png)
and this is how I set my z field on qgis 
![cppp](https://user-images.githubusercontent.com/30039918/31619238-35a10a44-b294-11e7-877f-8aaf4fc7ee94.PNG)

**Comment by m-kuhn** [comment]
Can you turn on the GPS information display (long click on the blue GPS icon) and make a screenshot?

**Comment by zakigates** [comment]
![screenshot_2017-10-16-16-20-15 1](https://user-images.githubusercontent.com/30039918/31620027-6e0f754e-b296-11e7-8465-4d05ec621b6d.png)
This is it

**Comment by m-kuhn** [comment]
Looks like your positioning device doesn't expose any altitude information.
Do you have this information available in any other app?

**Comment by zakigates** [comment]
I succeeded to get the z value in qfield Thanks so much for your precious help. but I still have a problem when I try to synchronize with qgis I get this python error 

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 30: ordinal not in range(128) 
I seriously don't understand it. If you have any idea about it source tell me I would be very thakfull

**Comment by m-kuhn** [comment]
Good to hear that your issues could be sorted out.

It would be very handy for the general public if you could write down the missing information in the documentation. Thanks!

**Comment by geomoes** [comment]
after trying to get it work I figured out, that I can use the following function to get the altitude when digitizing points with an external GPS device. Just create a altitude field (e.g. altitude, real) and add as default value the following function to get the altitude of points:
z(@position_coordinate).

**Comment by m-kuhn** [comment]
Issue opened https://github.com/opengisch/QField-docs/issues/76

Would be great if someone could add this information to the docs !
