### ISSUE TITLE
F-Droid or independant APK distribution

### ISSUE THREAD

**Issue by vpicavet** [opengisch/QField#16]
It would be great to be able to install QField without requiring a Google Play account.
This could be done either by : 
* providing a single APK file to download and install
* use the F-Droid infrastructure

**Comment by m-kuhn** [comment]
@vpicavet

F-Droid would be nice but a short look at https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md reveals that they build the apps based on recipes and I'm not quite sure they have the build tool chain to build Qt apps and all the dependencies on their infrastructure. Would need some previous investigation.

Offering the .apk for manual downloading should be fine I think. @mbernasocchi

**Comment by vpicavet** [comment]
Thanks for investigating.
If f-droid could be nice, an APK is fine with me

**Comment by mbernasocchi** [comment]
we do have an apk online, at http://www.opengis.ch/download/qfield/apk/
I'll update the installation page

**Comment by vpicavet** [comment]
Thanks !
Here is for 0.4.1 : 
![qr code qfield](http://chart.apis.google.com/chart?chs=200x200&cht=qr&chld=|1&chl=http%3A%2F%2Fwww.opengis.ch%2Fdownload%2Fqfield%2Fapk%2Fqfield-0.4.1_armeabi-v7a.apk)

**Comment by mbernasocchi** [comment]
:)

**Comment by mbernasocchi** [comment]
I had a chat with the f-droid guys, there is no way to upload an apk on their infrastructure. And I'm honestly not too keen on trying getting QField to build on their machines. but we could setup our own f-droid repo. see https://f-droid.org/manual/fdroid.html#Simple-Binary-Repository

**Comment by Matthias84** [comment]
Can anybody confirm, if the APK works on CM, BlackberryOS, or SFOS?

**Comment by mbernasocchi** [comment]
I develop on CM 12.1.
android is the platform we target. no idea about blackberry OS. what is SFOS?

**Comment by m-kuhn** [comment]
Installed from the playstore it works on CM, the .apk has the same payload as the one distributed via playstore.
I would not see any reason why it should not work.

**Comment by mbernasocchi** [comment]
@m-kuhn just told me, sailfish OS :)

**Comment by m-kuhn** [comment]
apk hosting moved to github.

https://github.com/opengisch/QField/releases/

**Comment by s-m-e** [comment]
Bump ... Any likelihood that this app gets distributed via f-droid?

**Comment by mbernasocchi** [comment]
not really for the moment since we already offer Playstore and all signed apks directly from github (as stated above) and adding F-droid would require time resources that we currently don't have.
If it is critical to you please get in touch with us.

**Comment by opk12** [comment]
Discussion 2706 `Android QField availability on F-Droid` has recent updates on this (for those coming here from Google)
