### ISSUE TITLE
Synchronization 

### ISSUE THREAD

**Issue by zakigates** [opengisch/QField#160]
I have a serious issue with synchronizing qfield and qgis. I'm working with .qgs project that I export  to qfield via qfieldSync , then I added  a new feature and every thing  works perfectly even when I synchronize with qgis I see my new feature, but when I want to edit the feature  that I created (change the value of a field) in qfield the synchronization with qgis doesn't seem to be working, it preserves the old values. If you have any idea about what is happening tell me please.

**Comment by m-kuhn** [comment]
You could check the offline spatialite file. There is a table that logs all the performed actions (add, delete, update). So first thing to check would be if everything in there looks ok.
Something I could imagine is that there are no stable feature ids on the database (e.g. using string as primary key).

After all, it very much depends on the particular data source and system setup, while the offline editing functionality of QGIS tries to do things as generic as possible there are still a couple of things that can go wrong.

**Comment by gisengineer** [comment]
for what type of data source can Synchronization be applied ?
I used shapefile and spatial oracle and for both the Synchronization was not working

**Comment by m-kuhn** [comment]
In theory to all of them.
This functionality is based on QGIS offline editing functionality (which has a core plugin). It's possible to likely that the problem is there.

**Comment by saemiw** [comment]
@ gisengeineer: We used it with geopackage and it worked perfectly.

**Comment by gisengineer** [comment]
its seems that I missed step or something went wrong I did as in this link  https://docs.qgis.org/2.2/en/docs/user_manual/plugins/plugins_offline_editing.html
I tried shapefile, spatial oracle and SpatiaLite and for all it is not working so is there any thing to do more than mentioned in the user manual

**Comment by m-kuhn** [comment]
There have been a couple of fixes in recent QGIS 2.18.x patch releases, make sure you use the very latest version.

**Comment by gisengineer** [comment]
when try to save edits on mobile device using qgis experimental,  I have this warning"offline editing plugin:could not open the spatialite logging database" although the editing is saved on the mobile version

**Comment by m-kuhn** [comment]
> when try to save edits on mobile device using qgis experimental

Does this concern qgis on Android or qfield?

**Comment by gisengineer** [comment]
it is for  qgis experimental on Android not qfield

**Comment by zakigates** [comment]
An other strange behavior when I put some layers on no action and I let the one that i want to update on offline editing it works , but when i have all my layers on offline editing and I update an specific one, no updates are applied.

**Comment by agatacc** [comment]
Dear colleagues, 
I’m working on qfield (version 0.10.13 - Kesch) and qgis (version 2.18.7) through the plugin qfield sync. I packed my qgis project, where there’s one postgis layer (object to edit) and a ortho base map (google map Tile server). When I pack the qgis project, the postgis layer is changed into data.sqlite and the base map to a basemap.gpkg. 
The field work consists on editing and adding information on pre-existent features (exploring mode) and in some cases digitizing new features on field (digitize mode). 
The problem I have is when I try to synchronize qfield to qgis. Firstly, it synchronize perfectly and I can view the changes done in the field, but when I try to save the editing changes I get this error: 
Error de PostGIS al cambiar atributos: ERROR: prepared statement "updatefeature" already exists.

I supposed it’s something related to my postgis - database, but I’ve been looking for this kind of error on internet but I didn’t find any useful information. 

Do you  know how I can resolve it?

**Comment by germain83** [comment]
I have exactly the same problem with qgis 3.6

**Comment by Asmaa2499** [comment]
how can i I export to qfield via qfieldSync

**Comment by signedav** [comment]
Hi there

@gisengineer If you still have an issue with QGIS on Android, please open an issue here: https://github.com/qgis/QGIS-Android

@agatacc possibly something with the primary keys? Can you deliver the SQL statement of your table?

@zakigates Is your problem still persisting on the latest QField Beta Release? https://github.com/opengisch/QField/releases/tag/v1.3.0

@Asmaa2499 Maybe this part of documentation can help you https://qfield.org/docs/qfieldsync/

**Comment by qnmai** [comment]
Hello, I have the same issue on QGIS 3.8, QField 1.1.0, and Android 5.1.1.
Erreur 42P05: l'instruction préparée "updatefeature" existe déjà.

I've attached the project causing the issue.
[0_SDAEP_TevaIUta_TAB.zip](https://github.com/opengisch/QField/files/4206252/0_SDAEP_TevaIUta_TAB.zip)

**Comment by strathmannm** [comment]
Hello,
did you try it with saving your qgis project (Project/Save) after setting the layer to "offline editing" (Plugins/QFieldSync/Configure Current Project/)  but before exporting the project to qfield (Plugins/QFieldSync/Package for QField/)
This step seemed to solve the problem for us.
Kind regards
