### ISSUE TITLE
Altitude incorrect when using NMEA in combination with vertical grid shift 

### ISSUE THREAD

**Issue by soester** [opengisch/QField#1601]
### We tested QField NMEA with the following Setup:
REACH RS2 / Reachview via Browser
siwpos ntrip mount point: MSM-LV95-LN02
**QField version:** 1.8.1.
chgeo04_htrans.gtx

### Observed behavior:
Somehow the transformation from NMEA via grid-shift file doesn't work correct.
There seems to be kind of pseudo-geoid correction of the NMEA string.
Grid shift calculation seems to be different.

#### Reference Point (GNSS Measurement, STONEX with Penmap Software, NTRIP Correction):
Z Ellipsoid of Reference: **496.31**
Z LN02 of Reference: **448.83**

Calculated grid shift: - 47.48 m

#### Value reported in Reach View
Z Ellipsoid REACH View: 498.45
Corrected by Antenna Height (2.134m): **496.32** 

#### Values reported in QField with different options
Altitude QField (Antenna height +2.134, Skip alt. corr -> Yes, Vert. grid shift -> Yes): 400.63
Altitude QField (Antenna height +2.134, Skip alt. corr -> Yes, Vert. grid shift -> No): 448.03
Calculated grid shift: -47.40 m

Altitude QField (Antenna height +0, Skip alt. corr -> Yes, Vert. grid shift -> No): 450.17
Altitude QField (Antenna height +0, Skip alt. corr -> Yes, Vert. grid shift -> Yes): 402.77
Calculated grid shift: -47.40 m

### Screencast
https://user-images.githubusercontent.com/28543978/104454702-8dfc8200-55a6-11eb-85da-f2b34b626b28.mov

Switching on and off the 'Skip altitude correction' didn't have any effect on the altitude in reported in Qfield.

### Expected behavior:

Altitude QField (Antenna height +2.134, Skip alt. corr -> Yes, Vert. grid shift -> Yes) = 448.83 m

**Comment by soester** [comment]
cc @m-kuhn @EulenspiegelTill

**Comment by nirvn** [comment]
This could well be because we use the ortho elevation/Z value from the NMEA signal whereas your reachview's Z reference is ellipsoidal.

**Comment by soester** [comment]
@nirvn shouldnt the 'Skip altitude correction' switch disable this?
Maybe it would be a 'fix' to use the ellipsoid elevation/Z value from the NMEA signal when 'Skip altitude correction' is switched on?

**Comment by nirvn** [comment]
Which value is "corrected"? The ortho Z or ellipsoidal Z value?

**Comment by m-kuhn** [comment]
So far we only get ortho Z in QField. Ellipsoidal Z (generic wgs84 ellipsoid) is on its way but needs a newer QGIS version first.

However, for @soester I think we want the "raw" ortho height with chgeo04_htrans.gtx correctin

**Comment by nirvn** [comment]
By the looks of his numbers, it feels like he's expecting the grid correction (-47.4) to be subtracted from the ellipsoid Z, no? That's the only way he'd get to stated expected value of 448.83.

**Comment by soester** [comment]
yes @nirvn
i think chgeo04_htrans.gtx contains the difference between wgs84 ellipsoid and swiss geoid LHN95.

The differece of 8cm between the two grid shifts could be the HTRANS difference of LHN95-LN02 (https://s.geo.admin.ch/8e27765a3c).
@EulenspiegelTill and me just realized swipos services MSM-LV95-LN02 and MSM-LV95-LHN25 deliver different values. Maybee we need to use the MSM-LV95-LHN25 service.
Unfortunately this is hard to test for us as the difference is 0 in our region.

**Comment by nirvn** [comment]
So I'm left to wonder whether the raw Z REACH is ellipsoidal and a geoid adjustment is applied when sending the ortho Z within the NMEA signal.

**Comment by m-kuhn** [comment]
For reference, this is what Emlid says

> ReachView provides ellipsoidal height. However, according to the NMEA standard, the GGA message should contain an orthometric one (in the 9th field). Along with the orthometric height, GGA transfers geoid-ellipsoid separation (in the 11th field) which can be used to restore the ellipsoidal height you see in ReachView:

**Comment by m-kuhn** [comment]
So far QField only knows the 9th field (11th field inbound soon)

**Comment by soester** [comment]
thanks @m-kuhn i think we are on the right track!

**Comment by m-kuhn** [comment]
> By the looks of his numbers, it feels like he's expecting the grid correction (-47.4) to be subtracted from the ellipsoid Z, no?

I agree. I wonder if the gtx is in the wrong direction or our calculation.

**Comment by lucienicolier** [comment]
I think what should be used is a combination of fields 9 and 11.

**Comment by Benwaa74** [comment]
> For reference, this is what Emlid says
> 
> > ReachView provides ellipsoidal height. However, according to the NMEA standard, the GGA message should contain an orthometric one (in the 9th field). Along with the orthometric height, GGA transfers geoid-ellipsoid separation (in the 11th field) which can be used to restore the ellipsoidal height you see in ReachView:
> 
> So far QField only knows the 9th field (11th field inbound soon)

I am experiencing the exact same issue here in Australia.

m-kuhn (and lucienicolier), it appears that if QField used both fields 9 and 11 of the GGA message, then this will (should) produce the correct orthometric heights in QField. At the moment I am only able to record ellipsoidal heights.

Any idea when this option will be available in QField?

**Comment by nirvn** [comment]
@Benwaa74 , it's all a bit confusing, but for the record, ATM QField _is_ serving orthometric heights when connected to an external bluetooth device (i.e. the 9th field).

Improved elevation coming soon, likely a new beta release in the coming days.

**Comment by Benwaa74** [comment]
Hi nirvn, thank you for the information. I did think this was/should be the case (I'm using version 1.7.8). I'm using an Emlid Reach RS2 antenna and receiving a correction via CORS network, then passing this to QField via Lefebure NTRIP Client app. Lefebure reports the correct orthometric height but QField only reports (and records) the ellipsoidal height. Has this been sorted in the latest version 1.8 beta release?

**Comment by nirvn** [comment]
@Benwaa74 , oh, you're _not_ connected to your Reach antenna directly in QField, that's a different scenario. I guess the good news for you is you can simply grap the latest 1.8 beta and you will get ortho height off the box :) note that we're about to release a new version that will have external (bluetooth) device return the ellipsoidal height by default, but you'll be able to fetch the ortho value of the device by setting the vertical grid shift combo box to "external device".

**Comment by Benwaa74** [comment]
@nirvn , fantastic news! That sounds like the perfect scenario for us. Thank you so much. I'll download the beta now and give it a go. Many thanks!

**Comment by Benwaa74** [comment]
@nirvn , happy to report it works great! There was no option in the vertical grid shift combo box (other than 'none'), but it appears to be giving me the correct ortho height now anyway. Will test it against a previously coordinated control mark, but looks like it's working fine. There is an ellipsoidal separation of around -42.5 metres where I tested it. So, _measured elevation - 42.5_ to give corrected ortho height of (AHD)11.9 metres) Many thanks again, great work! :)

**Comment by nirvn** [comment]
@soester , @Benwaa74 , could you guys test out the APKs here: https://github.com/opengisch/QField/pull/1625 . The PR is a follow up to your feedback and comments, keep those coming :)

**Comment by nirvn** [comment]
Fixed.

**Comment by soester** [comment]
I was able to test QField 1.8.2 yesterday. With the same setup as in the original issue report.
REACH RS2, EPSG:2056 LV95-LN02, Swipos NTRIP, Htrans-Gridshift file. 
Difference in altitude compared to another GNSS-Reciever: 5cm resp. 2cm on a second point :thumbsup: :smile:
Thanks to all! This is a milestone for QField!

**Comment by nirvn** [comment]
@soester , thanks for letting us know, this ends the week on a great note :)

**Comment by Benwaa74** [comment]
Tested 1.8.2 against known state control mark a few days ago. Result was within 2cm vertical of published coordinates! (1cm horizontal). This was using a Reach RS2, a geoid file (AusGeoid09) for vertical shift, no ortho correction set and antenna height of 0.134 (RS2 phase centre offset to base of antenna, so placed the antenna directly on top of mark, no pole used). NTRIP correction from SmartnetAus - nearest base almost 20km away! Very impressed with this result. Well done folks!

**Comment by gdt** [comment]
I know this is closed, but I wanted to point out about NMEA and height:
 * receiver calculate in ellipsoidal coordinates.   With RTK that's going to be the CRS of the reference network
 * GPS receivers have a built-in geoid correction, usually of abysmal quality (F9P geoid is 4m off from EGM2008 around me)
 * NMEA's elevation field is in orthometric height, obtained by the receiver from HAE and the receivers' geoid model
 * The best way i know is to back out the receiver's geoid model from receiver's orthometric height to recover the HAE
 * Then one has to assign it a CRS and convert to the desired datum of orthometric height.  For me that's NAD83(2011) epoch 2010.0 and NAVD88, and that's obviously a national/regional alignment thing, vs WGS84/ITRF and WGS84 Orthometric Height as realized by EGM2008.   I'm not aware of any other global orthometric height datums.
