### ISSUE TITLE
UI freezes whe a project contains a lot of PostGIS layers

### ISSUE THREAD

**Issue by suricactus** [opengisch/QField#1605]
Open a project with let's say 10 PostGIS layers. The screen freezes with the project pushed and nothing happens for half a minute. Then suddently you see the white canvas. Not sure how it was in the past, but I am pretty sure the white map canvas was visible while the layers are being loaded.

**Comment by nirvn** [comment]
Pre welcome screen, a blank canvas was shown. I have some plans on working around the issue here next week.

Long term, we'd need to have QGIS load projects off the main thread, which is a large undertaking.

**Comment by nirvn** [comment]
@suricactus , can we close this issue now?

**Comment by suricactus** [comment]
Thanks, works like a charm!
