### ISSUE TITLE
position horizontal accuracy is also set when not using the current GPS Position digitizing

### ISSUE THREAD

**Issue by LindaOPENGIS** [opengisch/QField#1607]
position horizontal accuracy is also set when not using the current GPS Position. Would be nice if it would be possible to know if we use the GPS Position for digitizing or if we're setting the position manually.

### Reproduction Steps:

1. add field with default value `@position_horizontal_accuracy`
2. digitize new feature in qfield with point manually set
3. accuracy value is the actual position of the tablet

### Expected behavior:

- when Feature manually set  ->  `@position_horizontal_accuracy` and all other `@position*` -> Output:  NULL
- @position_source_name  -> add  "manual position setting" / "manual" or whatever..
- new additional expression variables `@sensor_horizontal_accuracy` -> describes accuracy of GPS Sensor (that's what   `@position_horizontal_accuracy` does until now)

**Comment by m-kuhn** [comment]
Nice, I like the `@sensor_` prefix :+1:

**Comment by LindaOPENGIS** [comment]
juhui
