### ISSUE TITLE
Minimise text popups delaying further action when editing geometry

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#1611]
This is more a suggestion than a bug.

When editing point locations in the field the 'Vertex Tool' text popup at the bottom of the screen appears twice for about 3 seconds - first when you click the green '...' button in geometry editing mode, then the check mark when confirming the new vertex geometry.

Also, when you change the coordinate cursor to lock on to your position or disable it there is a text popup at the bottom of the screen that stays on for about 3 seconds as well. 

These text popups are informative and useful but the problem I can't seem to be able do anything else while they're on the screen - you can try pressing a button but it won't do a thing.

For example when editing a simple point geometry I have to wait up to 3 seconds for the 'Vertex Tool' popup to start fading out before I can even move the point to its new location. Then another 3 seconds before I can confirm the new geometry. And if I'm switching between GPS-derived and manual locations there's an extra 3 seconds for that popup too.

The time starts to add up in the field over 1000s of points especially for rapid assessments and where GPS locations can suddenly jump around so you need to save the new geometry as quickly as possible.

Is there any way to allow the user to be able to perform actions/tap on buttons while the text popup is on the screen, or another way of modifying point geometries that is faster? (It seems a bit counter intuitive to require so many steps simply to move a non-multi point geometry - would be nice if when you select edit geometry it immediately lets you move the point).

Alternatively is this possibly an issue with the device specs? This is on a fairly basic model (Galaxy Tab A 2018) and I notice it takes longer on projects with lots of features on the active layer.

**Comment by nirvn** [comment]
@she-weeds , try these APKs (https://github.com/opengisch/QField/pull/1760#issuecomment-792627111) and let us know if the improvement satisfies you.

**Comment by she-weeds** [comment]
Thanks for this @nirvn - I've only done limited testing as I'm using a different device atm, but it definitely seems to be a lot faster - I seem to be able to move onto the next task even while the toast message is visible (now I know what it's called...) and the ability to dismiss it with a tap is beneficial on slower devices. I still feel the number of steps required to move a single point geometry is a bit excessive (tap on feature, open form, tap on edit geometry, tap on edit vertex, move, tap on green tick), but that would be another issue that I think is being partly addressed already. 

Really grateful for the response to little suggestions like this (y)
