### ISSUE TITLE
Selection of a polygon doesn't display holes 

### ISSUE THREAD

**Issue by lindacamathias** [opengisch/QField#1614]
The selection (yellow line) of a polygon with an isle inside (donut) shows only the outer line. 
This can be confusing especially when there is another polygon inside the ring.

### Reproduction Steps:

1. digitize a polygonA
2. select polygonA
3. create a new polygonB (insle) inside PolygonA with fill ring tool (with the option create a new polygon)
4. select polygonA 

### Expected behavior:

Selection (yellow) considers line and fill of the new cutted ring. the inner line should be drawn in yellow too. the isle shouldn't be drawn yellow.

### Observed behavior: 

Selection (yellow) only shows the outer line of the polygone. The isle (no poygon area) is filled with yellow.

**Comment by geomondego** [comment]
This also happens, when using the Fill Ring tool and having a new polygon created. When selecting the biggest polygon, will show all the area. Tested in master-dev (225f71)

![Screenshot_20210204-080338](https://user-images.githubusercontent.com/4389239/106862953-c1bb5b00-66bf-11eb-876d-f9aabea06ae5.png)
