### ISSUE TITLE
Missing version numbers in GooglePlayStore

### ISSUE THREAD

**Issue by Thunichgud** [opengisch/QField#1615]
When you upload a new version to the GooglePlayStore you don't fill in the new version number. The new version number is neccessary for the download of the APK-file using the Raccoon APK-downloader. It don't recognises the new version as new version when the version number is missed. So I often don't get the new version by Raccoon.

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by nirvn** [comment]
@m-kuhn , @suricactus , that was fixed last week right?

**Comment by suricactus** [comment]
Have not tested with :raccoon: , but all the meta is already in place and should be fixed.

**Comment by Thunichgud** [comment]
With version 1.8.4 it did work, but with version 1.9.0 qfield again isn't updated by raccoon. Raccoon needs the correct version number in the belonging field in the GooglePlayStore to recognize that there is a new version.

**Comment by Thunichgud** [comment]
I just saw that the version 1.9.0 isn't yet published in the GooglePlayStore. That seems to be the reason why raccoon didn't recognized the new version.
