### ISSUE TITLE
GPKG relative path

### ISSUE THREAD

**Issue by 1900g** [opengisch/QField#162]
qfield does not assume the relative directory for geopakage.
when charged creates an error and says the layers can not be loaded. I checked the project and it is configured correctly. the problem lies in the individual raster content in the geopakage.

**Comment by m-kuhn** [comment]
This always worked for me.
Can you upload a sample dataset somewhere?

**Comment by 1900g** [comment]
after many attempts I solved the problem by adding more geopakages with each one a single tiff image. so it works! creates errors if you upload only one geopakage containing more tiff images.
thank you!
ps. a very useful job. I hope you will continue to develop it!

**Comment by m-kuhn** [comment]
Glad you found a solution

**Comment by VxTedxV** [comment]
Don't know if it's the same issue but same symptom from QGis 3 project. Thanks to @m-kuhn who found another answer [elsewhere](http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Relative-path-for-GeoPackage-Rasterlite-rasters-does-not-work-td5372354.html) by a simple drag&drop to solve this issue :) Able to use geopackaged .jp2 rasters in QField now :)

**Comment by m-kuhn** [comment]
How is such a VRT file produced?
