### ISSUE TITLE
NULL values in numeric fields are saved as 0

### ISSUE THREAD

**Issue by soester** [opengisch/QField#1624]
NULL values in numeric fields are saved as 0

### Reproduction Steps:

Any Numeric field (double or integer)
Text edit widget

### Expected behavior:
If no value is entered the field should be null.

### Observed behavior:

Null is displayed as 0

### Screenshots and GIFs

https://user-images.githubusercontent.com/28543978/105872125-548e3280-5ffa-11eb-8d6a-238cf5ef8277.mov

**QField version:** [1.8.1)], acctually beta 1623

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes] no problem with 1.7.8

**Comment by suricactus** [comment]
Hey! Well described issue, thanks. Can yo please provide a sample project, I didn't manage to reproduce?

**Comment by soester** [comment]
@suricactus 
can i send you a sample project by private mail?
would be glad not to share it publicly.

**Comment by suricactus** [comment]
Sure, ivan at opengis.ch

**Comment by soester** [comment]
as @suricactus wrote by mail, i can also not reproduce with QField 1.8.2
@nirvn is it possible that this is introduced by https://github.com/opengisch/QField/pull/1623 ?

**Comment by soester** [comment]
This bug still persist in QField 1.9.0

**Comment by soester** [comment]
@m-kuhn would be great if you could have a look at this.
we would fund fixing it!

**Comment by m-kuhn** [comment]
Thanks for the reminder @soester , a reason for a 1.9.3 release!

**Comment by soester** [comment]
Thanks for the fix. Works now as expected :)

**Comment by nirvn** [comment]
@soester , thanks for the confirmation.
