### ISSUE TITLE
Working with WFS layers

### ISSUE THREAD

**Issue by gnerred** [opengisch/QField#163]
When working with WFS layers, QGIS and QField do not refresh data from server when navigating. For QGIS, simply clicking on the refresh button allows to refresh layer from server. Wouldn't it be usefull to integrate a refresh button in QField ? Or a way to refresh the map without closing and reopening the project ?

**Comment by monodo** [comment]
Seems related to https://github.com/opengisch/QField/issues/665

**Comment by m-kuhn** [comment]
Would it work for you to put this button directly onto the (WFS) layer properties page to keep the main interface clean?

**Comment by monodo** [comment]
Yes
