### ISSUE TITLE
Date entered via Date-Widget sometimes not shown

### ISSUE THREAD

**Issue by bsturm** [opengisch/QField#1630]
### Reproduction Steps:

**QGIS**:
I have got a project with 2 Point Layers, A.shp, B.shp
Each Layer contains a Date-Field (defined as date - Type Qdate, Type-Name Date, Lenght 10)

They are are both marked for offline use, i used them for a year now.

**Qfield**:

Add Point to Layer A
Date field days: ___-__-__
Open Date Widget / set today's Date
Chosen Date appears in Date-Field

Add Point to Layer B
Date field already says: (Kein Datum / No Date)
Open Date Widget / set today's Date
Date field still says: (Kein Datum / No Date)

**-> When importing back to QGIS, Dates in both layers are shown correctly**.

### Expected behavior:

Date should be shown correctly

### Observed behavior:

sometimes date is shown and sometimes not.
if i tap a recently added point where that issue occured within Qfield, date is also not shown, but back in QGIS, that date is visible.

If the field is corrupt it already says "(Kein Datum)" before opening the widget.
If field is  not corrupt it shows ____-___-___ before opening the widget.

### Screenshots and GIFs

I can add, if necessary

**QField version:** 

QGIS 3.10.12-A Coruña
QField 1.7.8
## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
 - I have observed this behavior before.
* Problem can be reliably reproduced, doesn't happen randomly: [No]
 - It happens on different Projects, seemingly wthout reason. I am posting this because it occurred to a colleague as well.
 -
* Problem happens with all files and projects, not only some files or projects: [No]
 - Only in some. Colleagues Project was freshly created, the project I am describing wit A and B is over a year old. A quick test project I created right now worked perfectly. I created different shapefiles for offline use, additionially added file B.shp, which doesn't work properly in another project. In this one it does.
 
What am I missing?

**Comment by nirvn** [comment]
@bsturm , can you share a test project that shows this issue?

**Comment by nirvn** [comment]
@bsturm , if you can, can you try the APKs in PR #1642 and confirm your issue is gone? Thanks.

**Comment by bsturm** [comment]
Sorry, had no time yet. Is it still needed?
