### ISSUE TITLE
Database locked error when editing geopackage

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#164]
When editing different layers from the same geopackage, after some edits the edit session cannot be continued and a message "database locked" appears.

**Comment by saemiw** [comment]
Does this happen systematically?

**Comment by m-kuhn** [comment]
should already be solved with the next release

**Comment by saemiw** [comment]
fucking excellent!!!

**Comment by m-kuhn** [comment]
Done with [QField 0.10.2](https://github.com/opengisch/QField/releases/tag/release-0.10.2).
Any feedback appreciated.
