### ISSUE TITLE
@position_ information not recorded in QField 1.8.1

### ISSUE THREAD

**Issue by Benwaa74** [opengisch/QField#1640]
Trying to record position information in the data using the @position_coordinate variable in QField 1.8.1. 

This appears to be the same issue as @stevenmizuno experienced with a recently closed issue. I made a [comment today on that issue](https://github.com/opengisch/QField/issues/1580#issuecomment-770152954) but have opened this one as that issue had been closed - not sure if that's the correct thing to do (apologies if not)? 

**Reproduction Steps:**
I am using a Samsung Galaxy Tab A and connecting to a Emlid Reach RS2 antenna via Bluetooth (using corrected NMEA). The connection is fine and I receive a nice accurate position (connecting to a CORS network for corrections). However, I need to be able to record the x, y and z positions of newly digitised points and I cannot get this to work. I have tried with both the internal device and the reach device but still no luck.

Default Expression Used:
'src name: ' || coalesce(@position_source_name,'?') || ' time of fix: ' || coalesce(@position_timestamp,'?') || ' position: ' || coalesce(@position_coordinate,'?') || ' Ground speed: ' || coalesce(@position_ground_speed,'?') || ' V spd: ' || coalesce(@position_vertical_speed,'?') || ' direction: ' || coalesce(@position_direction,'?') || ' mag var: ' || coalesce(@position_magnetic_variation,'') || ' num used sats: ' || coalesce(@position_number_of_used_satelites,'?') || ' used sats: ' || coalesce(@position_used_satelites,'?') || ' fix stat: '|| coalesce(@position_fixstatus_description,'?') || ' qual: ' || coalesce(@position_quality_description,'?') || ' fix mode: ' || coalesce(@position_fix_mode,'?') || ' h v p -dop: ' ||coalesce(@hdop,'?') || ' ' || coalesce(@position_vdop,'?') || ' ' || coalesce(@position_pdop,'?') || ' h v -acc: ' || coalesce(@position_horizontal_accuracy,'?') || ' ' || coalesce(@position_vertical_accuracy,'?') || ' x-position: ' || coalesce(x(@position_coordinate),'?') || ' y-position: ' || coalesce(y(@position_coordinate),'?') || ' z-position: ' || coalesce(z(@position_coordinate),'?')

Result:
src name: ? time of fix: ? position: ? Ground speed: ? V spd: ? direction: ? mag var: ? num used sats: ? used sats: ? fix stat: ? qual: ? fix mode: ? h v p -dop: ? ? ? h v -acc: ? ? x-position: ? y-position: ? z-position: ?

I have tried with and without the 'coalesce' function and also individually eg, x(@position_coordinate). But I get nothing in the form (only Null or ?). Maybe I'm doing something wrong?

**Expected behavior:**
Should record @position_ information in field, particularly x, y and z positions.

**Observed behavior:**
Field value remains NULL or ?

QField version: 1.8.1 - from Google Play Beta

**Additional information:**
Problem started happening recently, didn't happen in an older version of QField: No (have never been able to reliably get this to work in QField in older versions or this version)
Problem can be reliably reproduced, doesn't happen randomly: Yes
Problem happens with all files and projects, not only some files or projects: Yes

If you need more information, please let me know. Happy to supply what I can.

Regards,

Ben

**Comment by Benwaa74** [comment]
I can get the positions to record if I use the expression: "x($geometry)" or "y($geometry)" or "z($geometry)" [without the quotes of course] but this returns an error in the Message Logs which says:

"_Default value expression for Control_Checks:Easting has evaluation error. Cannot convert to geometry_".

It still records the correct value in the field but not convinced it's the correct way to achieve this and as far as I understand the documentation, using @position_coordinate should work.

**Comment by Benwaa74** [comment]
### **UPDATE:**
Have just tested the latest beta release (version 1.8.2) and **it is working!!** :)
One query though... 
Is it possible to show/record the coordinates in the CRS of the current project? For example, my project's CRS is 28356 and I would like to record the coordinates in UTM format rather than Lat/Lon. I can achieve this using x($geometry), y($geometry), z($geometry), but should the @position_coordinate be able to produce this format or is it purely the 'raw' lat/lon values that it produces?
Incidentally, I cannot get any values from the equivalent @gnss_position variable, e.g., x(@gnss_position) returns nothing. Not an issue for me at this stage, just thought I'd mention it.

**Comment by m-kuhn** [comment]
Glad it's working with 1.8.2!

Regarding the gnss variables, is it only this one that's not working or all of them?
To get the local CRS, you can use the `transform` function

**Comment by Benwaa74** [comment]
@m-kuhn , Ok thanks for the tip regarding the `transform` function. Just tested this:

`x(transform(@position_coordinate, 'EPSG:4326', @project_crs ))`

It worked perfectly!

As far as the gnss variables go, I only tested @gnss_coordinate, e.g., x(@gnss_coordinate). _My apologies, I wrote this incorrectly in my previous post as x(@gnss_position), but my testing did use x(@gnss_coordinate)._

**Comment by m-kuhn** [comment]
Nice, nice !

Could you add this as an example to the list here: https://qfield.org/docs/prepare/attributes-form.html#id1 ?

**Comment by Benwaa74** [comment]
@m-kuhn Done!

**Comment by m-kuhn** [comment]
Thanks a lot, it's pending a review now.
Next time make sure you click through until you opened a "pull request", so we don't miss it .

**Comment by Benwaa74** [comment]
Will do. Sorry, that's the first time I've ever edited anything on GitHub :) Wasn't sure how far to go

**Comment by m-kuhn** [comment]
No worries,it looks very good what you did

**Comment by Benwaa74** [comment]
Thanks!

**Comment by m-kuhn** [comment]
Shall we close this issue? I think it's almost all fixed. The gnss one would be better off in a new one.

**Comment by Benwaa74** [comment]
Yes, for sure. Go for it

**Comment by amgiss** [comment]
This is broken again in 1.9.0. Project working with @position_horizontal_accuracy as field value does not work after installing 1.9.0 but does when reinstalling 1.8.4.

**Comment by EulenspiegelTill** [comment]
@m-kuhn This should be reopened. All of the @position_ and @gnss_ variables are not working in the actual version 1.9.1.
Last version running is 1.8.4 as @amgiss mentioned on top.

**Comment by signedav** [comment]
@m-kuhn Could it be something with check if the position is locked?

**Comment by stevenmizuno** [comment]
None of the @gnss_ and @position_ variables are working on master, either, as of #1806; haven't tested earlier versions.

**Comment by stevenmizuno** [comment]
Further testing using the APK available at #1608 -- both sets of variables do return values when cursor is the locked to GNSS. 

If the cursor is not locked to GNSS then for the @position_ variables only @position_source_name returns a value: 'manual' and the @gnss_ variables return values, as expected.

**Comment by m-kuhn** [comment]
We'd like to sort this out soon.

@stevenmizuno @EulenspiegelTill can you confirm:
- after #1608 everything worked as expected (`@position_` variables were only set when locked to cursor / `@gnss_` variables always)
- this no longer works as of #1806 or master

so it was introduced recently, but after #1608 

Thanks !

**Comment by stevenmizuno** [comment]
@m-kuhn I have been sort of doing a binary search of pull requests for where this broke.
Using internal gnss with the cursor locked to gnss for the testing, unless otherwise indicated.
Results in the order I tested:
#1773 master -- testing failure of @position_ vars -- not working
#1680 not working
#1638 not
#1629 not
#1618 @position_ has values, but not @gnss_ ; however, with cursor NOT locked gets @position_ variables with the gnss values!

Then I noticed in Git that 1623 was committed before 1618, so now we have
#1623 @position_, @gnss_ are working
To be precise, with the cursor locked to gnss, both @gnss_ and @position_ variables have values from the gnss.
If the cursor is not locked, then @position_source_name has a value of 'manual'; others don't have values. And @gnss_ variables have values as would be expected.

**Comment by nirvn** [comment]
@Benwaa74  , @stevenmizuno , I believe this issue has been addressed in PR #1819 . If it's possible, could you test against the APKs provided in the PR's comments section? Thanks.

**Comment by EulenspiegelTill** [comment]
@nirvn The @position_ variables tested with my sample gcp-project i have with me in the field are working in PR #1819. the @gnss_ i will try to test in on the way home.

**Comment by nirvn** [comment]
@EulenspiegelTill , keep the good news coming :)

**Comment by stevenmizuno** [comment]
@nirvn On a quick test I find both @position_ and @gnss_ variable do have gnss values when cursor is locked.
When cursor is unlocked the @position_source_name has 'manual' with the rest of the @position_ variables null, and the @gnss_ variables have the gnss values.

**Comment by nirvn** [comment]
@stevenmizuno , good, that's working as intented then (see code logic here https://github.com/opengisch/QField/blob/master/src/core/expressioncontextutils.cpp#L30).

Does this satisfies you?

**Comment by stevenmizuno** [comment]
@nirvn Yes. Thanks
