### ISSUE TITLE
Expose Antenna Height from Settings with a expression variable

### ISSUE THREAD

**Issue by Benwaa74** [opengisch/QField#1644]
### A small enhancement
Would be good to be able to record the antenna height that is set under the _Antenna height compensation_ option. 

The antenna height (pole height) is often used by surveyors both for QA purposes and/or further post processing. It is also critical in determining the corrected (reduced level) of surveyed points. Recording the antenna height can be done manually in a form field, but if the operator changes the pole height during a field survey (which can sometimes happen frequently) it is necessary to change it not only in the settings but also in the form field. 

To be able to access a variable to read the value stored in the settings would be a great help as it would mean only having to change it in the one place. For example, a variable called @antenna_height (or similar) could be used as the Default value in a field which would read the value stored in the settings.

### Reproduction Steps:

1. Set Antenna height value under the _Antenna height compensation_ option in settings
2. Digitise a point
3. Read the value into a form field from settings using the variable _@antenna_height_.

**QField version:** 1.8.2

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Please ask if you need any further information/clarification.

Thanks

Ben

**Comment by soester** [comment]
that would be a very welcome addition!

**Comment by Benwaa74** [comment]
It's been a while since I have used QField, but I notice on the recent version that this has been added. Well done team :)

I have not had a chance to test it but if anyone else has and are happy with it I'm happy to close this issue.

Thanks,

Ben

**Comment by nirvn** [comment]
@Benwaa74 , thanks for the feedback. I hope you'll get the chance to use QField sooner than later again :-)

**Comment by SIG-NCA** [comment]
Hello,
Even if it's now possible to precise the antenna height value in the parameters, which variable is used for it ? I would like to store it in a field of my layer.
Thanks
Vincent
