### ISSUE TITLE
Selection of a multipart polygon only displays one part of it

### ISSUE THREAD

**Issue by lindacamathias** [opengisch/QField#1649]
Selection of multipart polygons only display one part of the selected multipart polygon

### Reproduction Steps:

1. create multipart polygon (easily done in topological editing mode to avoid overlaps)
2. tap to select the multipart polygon (it may be necessary to zoom out to hit it)

### Expected behavior:
all parts of the multipart polygon are selected (yellow line and fill)

### Observed behavior:

only one part of the multipart polygon is displayed in yellow color

### Screenshots and GIFs

**QField version:**1.8.2

**Comment by nirvn** [comment]
@lindacamathias , this is fixed on master:
![image](https://user-images.githubusercontent.com/1728657/143765768-694e1201-d035-46db-87e1-4a74ce3a773f.png)

Likely a benefit from having moved to QgTessallac. :partying_face:
