### ISSUE TITLE
Missing tracking

### ISSUE THREAD

**Issue by geomondego** [opengisch/QField#1656]
The option for tracking is missing in master-dev (225f71)

**Comment by signedav** [comment]
I did not experienced that. Are you you have the localisation activated? Otherwise maybe you have to provide us your project then I can test with it...

**Comment by geomondego** [comment]
> I did not experienced that. Are you you have the localisation activated? Otherwise maybe you have to provide us your project then I can test with it...

That was probably it. I was helping a guy by messaging and experimenting with three versions. It's operational. Sorry for the noise. You can close
