### ISSUE TITLE
Value relation show wrong values

### ISSUE THREAD

**Issue by geomondego** [opengisch/QField#1657]
I have a layer with two fields configured with the Value Relation widget for alphanumeric tables.
The first field should show the value A, B or C and then the second field would use the function current_value to see the value chosen in the first and show only the corresponding values. 

The relationship is working, but instead of showing the correct values, it is using the value of the corresponding tables' FID attribute 

### Expected behavior:
Working well in 1.8.2
![1 8 2](https://user-images.githubusercontent.com/4389239/106864832-49a26480-66c2-11eb-807e-c72b7f02b412.png)

### Observed behavior:
On master-dev (225f71)
![master](https://user-images.githubusercontent.com/4389239/106864905-60e15200-66c2-11eb-9535-580aa08e6237.png)

**Comment by nirvn** [comment]
@geomondego , if you can provide a test project, that'd be helpful.

**Comment by geomondego** [comment]
@nirvn the problem has however been resolved. I'm sorry for not closing the issue.
