### ISSUE TITLE
UUID Generator Widget

### ISSUE THREAD

**Issue by lucienicolier** [opengisch/QField#1661]
### Reproduction Steps:

1. Create a QGIS project with the widget type "Uuid Generator"
2. Open it on QField
3. Add a feature

### Expected behavior:

Uuid should be fill in by itself

### Observed behavior:

The Uuid is not fill in by itself.

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/50236352/107037809-e694f880-67bb-11eb-9672-bf2692cbf0d0.png)

![image](https://user-images.githubusercontent.com/50236352/107038097-50ad9d80-67bc-11eb-8338-f97435c57fce.png)

**QField version:** 1.8.2 (0e99ab v1.8.2)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No]

**Comment by she-weeds** [comment]
Could you not use the uuid() function as the default value and disable editing in a text edit widget?

**Comment by signedav** [comment]
You are totally right @she-weeds 

But since it exists in QGIS and needs no default value / expression knowhow it would be nice to have it in QField as well.

**Comment by nirvn** [comment]
Implemented :partying_face:
