### ISSUE TITLE
Attribute table

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#167]
Add a button for each layer to open the attribute table.
For each entry, there are also feature actions available that allow to jump to a feature when the action is triggered.

**Comment by signedav** [comment]
@m-kuhn can you precise this issue?
And how is the priority for that?

**Comment by m-kuhn** [comment]
It's about being able to see all features in an attribute table. It's a very interesting feature but no top priority for now.

**Comment by 3nids** [comment]
Would you list all attributes or only the `displayText` and a button to open feature form?

**Comment by m-kuhn** [comment]
It's mainly to inspect (short) value lists -> all attributes.

**Comment by saemiw** [comment]
Could also be interesting for tables with no geometry. This tables cannot be accessed currently...

**Comment by Isaacson33** [comment]
I realise my use might not be common, but this would be a very advantageous feature for the reason @saemiw gave. Currently non-geographic datatables can't be seen and yet are a significant part of some Qgis projects.

**Comment by suricactus** [comment]
Should we close this now? https://github.com/opengisch/QField/pull/1461
