### ISSUE TITLE
Remember last attribute value checkbox doesn't work

### ISSUE THREAD

**Issue by balogh89** [opengisch/QField#1673]
Hi,
Although I checked the box, it has no effect on the next feature, fields are empty/default. Integer are displayed but will be NULL after the feature is stored. It was working properly on version 1.7.8, but since it doesn't work not only in my projects, but in the demo projects too. Last checked on 1.8.3 (87c51d).

**Comment by she-weeds** [comment]
I have the same issue as well on the same version. It last worked fine in 1.8.2.

**Comment by geomondego** [comment]
Also in dev version (1e60bd)

**Comment by nirvn** [comment]
Confirmed.
