### ISSUE TITLE
Qfield has stopped

### ISSUE THREAD

**Issue by MacGilllycuddyReeks** [opengisch/QField#1676]
Hi there, 
When I try to open qfield it comes up with a message saying 'what's new in qfield' and then crashes. I then get a message saying qfield has stopped. I have tried uninstalling and reinstalling it but that does not work. Does anyone know how I can fix this? Simple steps would be great as I am not experienced in programming etc. 

Thanks
Mary

 [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by suricactus** [comment]
Hi, Mary. Could you please share the QField version you are using? The easiest way to check it is directly from Google Play. Please make sure you are using the latest QField version available. It would be nice if you share details on your device (e.g. Samsung A42) and Android version.

**Comment by MacGilllycuddyReeks** [comment]
Hi Ivan,

The phone I am using is Samsung Galaxy A6 (32 gig) and I am not sure which version of qfield. It is the version currently available in the playstore. It has 4.5star beside it. I ws not sur i f that was a rating or a version.

Thanks,
Mary
________________________________

**Comment by signedav** [comment]
@MacGilllycuddyReeks 
Does it only happen on first start or does it happen everytime you start it?
And if it happens everytime, do you see always the "Whats new..." screen?

**Comment by MacGilllycuddyReeks** [comment]
Hi yes,

I opened it out in the field the other day and it came started doing an automatic update without me selecting anything as soon as I opened it. Then it came up with the message 'what's new in qfield' and then a message to say 'qfield has stopped'. It does this every time I open it so I have no opportunity to try and open any files etc. I have since installed and reinstalled qfield but the same issue keeps arising.

Thanks

________________________________

**Comment by MacGilllycuddyReeks** [comment]
Hi Ivan,

I have sorted the issue. It was actually to do with my phone and not qfield. I asked my phone to do a manual update and now it has let me access qfield again. It must not have been updating properly.

Thanks very much for your help.
All the best,
Mary

________________________________

**Comment by signedav** [comment]
Hi Mary

Just to know, have you seen the "Whats new on QField..." Screen now or did it run without displaying this screen?

**Comment by MacGilllycuddyReeks** [comment]
HI Ivan,

It opened the screen and displayed it this time. Thanks

________________________________

**Comment by signedav** [comment]
One last question.Can you go over the menu to "About QField" and tell me what version you have (top line)?

**Comment by MacGilllycuddyReeks** [comment]
HI there,

It is version 1.8.3.

Thanks,
Mary

________________________________

**Comment by signedav** [comment]
Okay thanks.

So let's close this issue.

Enjoy QField 🙂
