### ISSUE TITLE
Move points

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#168]
A new tool should be introduced that allows to move point geometries.

The feature will first be identified (clicking on it). On the feature form, a new button to "edit geometry" will be available. This will switch the display to "edit geometry mode" in which the geometry point can be moved around, just like when digitizing a new point.

**Comment by gnerred** [comment]
+1 ! Yes it will be great

**Comment by soester** [comment]
+1!

**Comment by mbernasocchi** [comment]
@3nids, @signedav please coordinate on who is taking the lead on this

**Comment by 3nids** [comment]
implemented

**Comment by vfonsecaz** [comment]
Is this available on the mobile version?

**Comment by 3nids** [comment]
Yes

**Comment by vfonsecaz** [comment]
It seems on some mobiles we have to activate the option 
**"Show Attributes Form in Full Screen"**
or else the Edit geometry button won't show.

Thanks

**Comment by mbernasocchi** [comment]
Can you give details on android version and device. Ans idealli a screen record to show the behaviour

**Comment by vfonsecaz** [comment]
Here you go

https://www.youtube.com/watch?v=ua8NHHEJGW8&feature=youtu.be

![screenshot_20190220-140445](https://user-images.githubusercontent.com/9846715/53098632-fd34dd00-351b-11e9-954d-cef09897d1ad.png)

**Comment by mbernasocchi** [comment]
Great thanks.
@3nids can you have a look?
