### ISSUE TITLE
"format_number" expression not supported in attribute fields

### ISSUE THREAD

**Issue by MTrim** [opengisch/QField#1685]
"format_number" not supported in attribute fields

### Reproduction Steps:

1. I created fields for collecting date like GPS coordinates or distances to other points
2. I use the "format_number" expression in the default value field (attribute form)
3. For example: to automatically store the GPS coordinates with 3 decimals

format_number($x,3)

### Expected behavior:

Numbers should be stored in the configured attribute field.

### Observed behavior:

When measuring a point in qfield (GPS or digitizing does not make a difference), the correct values are shown in the attribute fields. After storing the point, the fields are filled with '0'
In QGIS Desktop everything worsk. In QField it works without the 'format_number' expression

### Screenshots and GIFs

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 1.8.1 (2068da)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes
[Vermessung.zip](https://github.com/opengisch/QField/files/5968170/Vermessung.zip)
]

**Comment by nirvn** [comment]
@MTrim , can you attach a screencast of your issue? Is the device you are running QField on using the same locale/language as your desktop? Is it English?

**Comment by MTrim** [comment]
Thanks for the tip. Qfield and QGIS are both in German. Maybe it has to do with the local settings. I will try it.

**Comment by nirvn** [comment]
@MTrim , how did it go? :)

**Comment by nirvn** [comment]
No news good news, closing this issue. @MTrim , please re-open if it's still an issue with the latest QField 2.0 beta.
