### ISSUE TITLE
Apply default values on update

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#169]
Default values can be used to generate a value when creating new features already (`now()`, `$length`, ...).
A new function should be introduced that allow to recalculate values when a feature is edited/modified. This will happen when the geometry is modified as well as when an attribute is modified.
A new checkbox is introduced in the QGIS configuration interface for default values that defines if a default value is only updated on create or also on update.

**Comment by fahrwegdienste** [comment]
Test with  nightly built  QGIS 3, 2.99.0.2 and QField 0.10.4:
summary from my email:
Ich habe in QGIS allerdings ein Anzeigeproblem. Ich wähle z.B. den Timestamp aus und klicke auch das Feld an "Vorgabewert bei Aktualisierung anwenden". Danach "Apply", "OK" und das ganze noch im Projekt abspeichern. Schaue ich erneut in die Layereigenschaften zu diesem Feld, ist der Haken nicht mehr gesetzt. 
Ich vermute, es ist ein Anzeigeproblem, da ich mit dieser Projektdatei es vorher getestet hatte und die Funktionalität an sich funktionierte. 

![image](https://user-images.githubusercontent.com/33343856/36025955-463d6a26-0d95-11e8-92ac-e5a12a41c90f.png)

**Comment by m-kuhn** [comment]
As far as I can see, that was reported and should be fixed in recent QGIS versions, but since I'm not in office I could never verify.

https://issues.qgis.org/issues/17712
https://github.com/qgis/QGIS/commit/fe2292c59a5fb7c65399aaf8903e33dbe9ab41d4

**Comment by signedav** [comment]
I cannot reproduce the problem with the current QGIS code - means I can approve the statement of @m-kuhn and I belief it's fixed...
