### ISSUE TITLE
QField Sync: Exporting layer in "offline editing" results in python error

### ISSUE THREAD

**Issue by MartinMap** [opengisch/QField#1694]
Exporting layer in "offline editing" results in python-error

### Reproduction Steps:

1. create a new project
3. add new GPKG-Layer (any kind)
4. set layer to offline editing via QField Sync
5. export to a local folder

### Expected behavior:

The export should be done without any failure

### Observed behavior:

QGIS python error pops up:
```
File "/home/map/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/offline_converter.py", line 342, in on_offline_editing_next_layer
msg = self.trUtf8('Packaging layer {layer_name}…').format(layer_name=self.__offline_layers[layer_index - 1].name())
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
```

### Screenshots and GIFs

![Selection_040](https://user-images.githubusercontent.com/6401482/107958970-0b9b1f80-6fa3-11eb-95cf-7c5bd4f7bb07.png)

**QField version:** QField 1.8.4 / QField Sync 3.4.1
**QGIS version:** 3.16.3
**OS version:** Mint 20.1

![Selection_041](https://user-images.githubusercontent.com/6401482/107959982-5b2e1b00-6fa4-11eb-8430-60ac7a980f9c.png)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [don't know]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by suricactus** [comment]
@MartinMap can you try the latest (non-experimental) release of QFieldSync and confirm the issue is gone now?
