### ISSUE TITLE
Feature request: geocoding & address search (Finland)

### ISSUE THREAD

**Issue by tjukanovt** [opengisch/QField#1695]
As a user I would like to be able to search for addresses with QField by using a third party API. Currently [the search works with layers](https://qfield.org/docs/et/old-doc/development/index.html), but not with external API's. In Finland there is an open geocoding API that could be used for this purpose: https://digitransit.fi/en/developers/apis/2-geocoding-api/

Addresses could be searched with [address lookup](https://digitransit.fi/en/developers/apis/2-geocoding-api/address-lookup/). The API has a rate limit of 10 requests per second which should very well be sufficient to cover the needs of Finnish QField users 😊. We have also done [a QGIS plugin that uses this API](https://github.com/GispoCoding/QGISDigitransitGeocoding) if that would be helpful in any way in the implementation.

Geocoding has already been mentioned as one of the identified development topics[ in the docs. ](https://qfield.org/docs/et/old-doc/development/index.html) and a discussion about adding this functionality has been already started with @m-kuhn 

One open question is that how this could be activated for only users in Finland. Also as the API is pretty generic and based on [Pelias](https://github.com/pelias/documentation), I would hope implementing this could benefit also other locations. I am open for discussion regarding this implementation.

**Comment by MMR100** [comment]
In case the enhancement is produced, it would be great to have the same thing possible to French address. 
Currently there are two QGIS plugins available: French locator filter  and Gban. The first one adding address information in the QGIS search bar

**Comment by m-kuhn** [comment]
We are working on the Finnish integration. I am not aware of ongoing projects for other locations at the moment (even though it would be very nice).
