### ISSUE TITLE
now() storing date without time

### ISSUE THREAD

**Issue by vlebert** [opengisch/QField#1696]
Hi,

Is it possible that the "now()" function was broken in recent updates.

When editing (the field is pre-filled with now() function), I see the full date with time. But when the data is saved, it is saved whithout the hour detail (only the date)

I didn't have this behaviour previously (and the problem is only with qfield, but not with Qgis using the same project)

I wonder if it may be due to the QGIS "type idendifié" which says date (and sometimes says datetime on other projects)
![image](https://user-images.githubusercontent.com/49779177/108491874-be6dc500-72a4-11eb-987f-bea9a37ab1e8.png)

I don't know exactly which version changed the behaviour. I am now running the last version. I use spatialite database.

Maybe the esiest way to describe is to upload the .qgs project?

**Comment by lomptorne** [comment]
Hey, 
There is an option in the forms editor of Qgis to select the date format, have you tried to make the change directly there ? (screen caputre related with one of my project. 

![help](https://user-images.githubusercontent.com/61391570/108520608-2cc57e00-72cb-11eb-8f69-bbc7a9eb49b4.png)

**Comment by vlebert** [comment]
Hi

yes I tried Date & Heure, and Date& Heure ISO

I am a bit lost because is seems I have 2 project, one working as expected and the other storing only the date.

The form settings are the same, the only difference I see is in on "Type identifié" shown in my screenshot

**Comment by vlebert** [comment]
Hi,

I think I identified the problem

If the field is declared "date" in sqlite CREATE TABLE, then Qfield won't store datetime values in it (though Qgis will be able to do it)

To work properly, the field must be created as datetime or text, and my problem is fixed in Qgis.

I guess this behaviour must be improved nevertheless 
- To align Qfield behaviour with Qgis
- Because in the end date or datetime are the same type in sqlite (text)
https://www.sqlite.org/datatype3.html

Valérian

**Comment by nirvn** [comment]
@vlebert , I'd argue QGIS is in need of aligning its behavior to that of QField here :)

**Comment by m-kuhn** [comment]
The QField behavior seems correct to me.
Other applications should expect a date field to contain a date and not a datetime. Even if it's technically feasible to put a datetime in there --it's technically also possible to put a string `"I am not a date"` in there, which I guess we all agree is non-sensical.

I would vote to close this as upstream (QGIS) issue.

**Comment by nirvn** [comment]
I'm pretty sure this has been addressed in QGIS, thanks to @nyalldawson . Closing.
