### ISSUE TITLE
Delete Feature is not available

### ISSUE THREAD

**Issue by ismailsunni** [opengisch/QField#1704]
I can't find the delete button  like explained on this page: https://qfield.org/docs/fieldwork/digitize.html#delete-features

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

There is a button to delete a feature

### Observed behavior:

No delete button found

### Screenshots and GIFs

![WhatsApp Image 2021-02-22 at 10 30 54](https://user-images.githubusercontent.com/1421861/108689327-3c2a0e80-74f9-11eb-9629-9d11f9ab08a2.jpeg)
![1](https://user-images.githubusercontent.com/1421861/108689424-55cb5600-74f9-11eb-83da-9d11641993db.jpeg)

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:**
1.8.4 7b5255 v1.8.4

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Not sure, first time seeing this
* Problem can be reliably reproduced, doesn't happen randomly: No
* Problem happens with all files and projects, not only some files or projects: Tested on one project only, so far

**Comment by signedav** [comment]
Long press on the feature in the list will do it.

**Comment by signedav** [comment]
We know that it's not that nice, when the user has to "find this out". We are thinking about give the user some hints (e.g. on first time use there could be a popup).

**Comment by signedav** [comment]
It's described like this in the documentation:
> To delete a feature, identify it first by a short tap on it. Then select it with a long press in the identification list, select further features to delete if you want and click the trash button to confirm the deletion.

But the screen cast seems to be obsolete.

**Comment by ismailsunni** [comment]
ah yes, my bad, I didn't realise there is more text under the screenshot. It works!

Thanks @signedav
