### ISSUE TITLE
Make "delete feature" accessible from the feature form

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#1714]
Currently features have to be deleted through a long press on the identify list.

The title bar should be cleaned up and possibly a ⋮menu be added with advanced functionality.

**Comment by suricactus** [comment]
I see the prev/next feature buttons to be transformed into left/right swipe? Adding the delete button back would make https://github.com/opengisch/QField/issues/696 relevant again. I am +1.

**Comment by nirvn** [comment]
I'm not sure we can use swipe since we need left / right swipes to move across feature form's tabs.

**Comment by nirvn** [comment]
@m-kuhn , implemented in #1731

**Comment by m-kuhn** [comment]
Thanks !

**Comment by m-kuhn** [comment]
If you add a `Fixes #1714` in a commit message or the pull request there, this will be linked and closed automatically ;-)
