### ISSUE TITLE
Does QField not support kmz format data

### ISSUE THREAD

**Issue by xBcai** [opengisch/QField#1715]
Does QField not support kmz format data? But there is a kmz file in the open dialog.

https://user-images.githubusercontent.com/66826351/109303446-c6fe6680-7875-11eb-8f91-ef5f21dc4610.mp4

**Comment by nirvn** [comment]
@xBcai , well spotted, the gdal kml driver doesn't support KMZ. I'll adjust accordingly.

**Comment by nirvn** [comment]
@xBcai , lucky you, QField will support KMZ opening after all :smile:

**Comment by xBcai** [comment]
I found that KMZ files are more than KML files, which is much more convenient. Thank you!
