### ISSUE TITLE
Multiple choice attributes

### ISSUE THREAD

**Issue by maxmentha** [opengisch/QField#172]
It seems like there exists no option to make multiple-choice attributes when digitizing vector data

### Expected behavior:

With multiple choice attributes, the user would be able to select among predefined options the text/value to be used for a certain field of a newly created feature.

### Observed behavior:

This feature does not seem to exist yet

### Screenshots and GIFs

-

**QField version:** 0.10.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by signedav** [comment]
This is implemented here #600
