### ISSUE TITLE
Improve the log window

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#1723]
Interesting suggestions from #259

- ~any chance to add a timestamp?~
- any chance to add a 'clear' button?

Added from my side:

- Make it accessible from the main menu or settings page

**Comment by nirvn** [comment]
@m-kuhn , there is a timestamp these days no?

![image](https://user-images.githubusercontent.com/1728657/109413223-d816b700-79de-11eb-8531-c9ab9c602fc6.png)

A clear button is a good idea.

**Comment by m-kuhn** [comment]
Thanks for the feedback, I deleted that one.

**Comment by nirvn** [comment]
@m-kuhn , a green ( clear button ) below the listview would fit in quite nicely (there's a similar UI in the qfield cloud project list panel).

**Comment by m-kuhn** [comment]
Do you have ideas where to put a "show log" button, so it's still accessible once it's been closed?

**Comment by nirvn** [comment]
@m-kuhn , the dashboard gear menu button seems to be the logical location for it. It's not really crowded at the moment either so that's not a worry.
