### ISSUE TITLE
Lag in position reporting with TDC600

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#1724]
With the TDC600 (and its clone the MM60) there is a lag of several seconds (reports in the range of 1 to 2 minutes) before the position is being visualized and registered in QField.
The same devices do not show this lag with other apps.
This behavior has been reported exclusively with these specific devices.

The reasons for this behavior are unclear at the time of writing. It might be QField, the device, Qt or other reasons.

**Comment by Thibtib51** [comment]
Hi thanks m-khun.
I have a little explanation from Trimble.
"Google Maps is able to get the position from WiFi (for example) in MM60. This is no longer the case with Mobile Mapper Field on MM60. Indeed, in the code of Mobile Mapper Field they decides to make the application working only with the GPS system in spite of High Accuracy mode is enable. VThis has been done to avoid too many inconvenient jumps in the position between different position providers. QField probably behaves like Google Maps".
Hope this information be clear to understand.
Thank you QField community if you can help : )

**Comment by m-kuhn** [comment]
Thank you for this information.

Can you be more precise about the difference between "mobile mapper field" and "google maps". Does one of these two apps also show this lag/delay?

**Comment by Thibtib51** [comment]
The same trouble (lag/delay) is observed with Google Map in MM60(TDC600) like QField. With the Trimble application Mobile Mapper Field the lag/delay doesn't exit the localisation is fine.

**Comment by m-kuhn** [comment]
I assume mobile mapper has an internal direct connection to the GNSS (NMEA?).
Similar to [the GNSS functionality that what was integrated recently in QField](https://www.opengis.ch/2021/02/24/powerful-and-gentle-qfield-1-8-selma-sneaked-in/#gnss_receivers). QField so far only supports bluetooth connections.

**Comment by Thibtib51** [comment]
Yes but it use another program called SPace from Trimble, this program provide a fictive position to android. If a use an external GNSS connected to SPace and the position is given fictively to android I haven't lag/delay with QField
-- 
Thibaut de MTe

**Comment by burreledge** [comment]
Hello. I also have a trimble tdc600 on which I tried to work with qfield, on a simple android phone no problem, but with the TDC 600 the program works very slowly recording the location and movement. I was advised to use a topoXpress program, which is not so convenient but works correctly and responds instantly.

**Comment by Thibtib51** [comment]
Hello, dix you fond the same trouble with Google Maps on your TDC600 ?
To add information, if you show the GPS information the V precision is ND and H prevision is OK.
-- 
Thibaut de MTe

**Comment by m-kuhn** [comment]
> He resuelto el problema calibrando la brújula (apicación e-compass). De esta manera se actualiza la posición bastante más rápido.

There has been a report that calibrating the compass helps to improve the situation.

**Comment by Thibtib51** [comment]
Thanks, I try it too but still in trouble
-- 
Thibaut de MTe

**Comment by burreledge** [comment]
> 
> Hello, dix you fond the same trouble with Google Maps on your TDC600 ? To add information, if you show the GPS information the V precision is ND and H prevision is OK. -- Thibaut de MTe Le 2 mars 2021 09:41:58 GMT+01:00, burreledge <notifications@github.com> a écrit :
> […](#)

Google maps on the trimble TDC600 work inadequately, very slowly. I've found that when you run Waze (car navigation system) in the background (parallel), both google maps and Qfield start working correctly.

**Comment by Thibtib51** [comment]
Exactly the Waze can help about this trouble.
I don't know the exact proverb in English : it's a bandage not a solution
-- 
Thibaut de MTe

**Comment by burreledge** [comment]
![Screenshot_20210303-092230](https://user-images.githubusercontent.com/79902405/109835625-0c42df80-7c4c-11eb-8b8f-171fcd774f03.jpg)
![Screenshot_20210303-105435](https://user-images.githubusercontent.com/79902405/109835632-0d740c80-7c4c-11eb-94ff-7c8a31bd670c.jpg)

I took screenshots today, I hadn't noticed that Qfield on the trimble TDC600 doesn't show V accuracy. Maybe useful for solving accuracy problems, I'm not a programmer, just a user.

**Comment by Thibtib51** [comment]
Same things from my side.
Whatever the position settings in Android parameters (High precision or GPS only).
Like in another comment QField use Position API from Android and force the High Accuracy precision. Trimble application use only GPS to avoid different sources of location to avoid lag/delay and imprecision in position.
-- 
Thibaut de MTe

**Comment by nirvn** [comment]
@Thibtib51 , @m-kuhn , is this still an issue? We've gone through a big positioning framework revamp, I feel like this might have improved dramatically since then.

**Comment by Thibtib51** [comment]
Hi @m-kuhn,
I quit my job and I don't have an tdc600 (it will be difficult to find another) can you try at your side ?
Hi @nirvn if I don't have answer I will try at my side.

**Comment by m-kuhn** [comment]
I had it for testing only for a short time, I can no longer test.
Should we close this and if someone else has a device we can reopen?

**Comment by nirvn** [comment]
Yeah, let's do that.

**Comment by Thibtib51** [comment]
Ok, I will try to get an TDC600 and I will try it.
I come back with my conclusion

**Comment by m-kuhn** [comment]
> Ok, I will try to get an TDC600 and I will try it. I come back with my conclusion

That'd be great!

**Comment by Thibtib51** [comment]
Hi all !
I try the lasted version with TDC600 and you're right @nirvn this version was improve and it's work with this Trimble data-collector !
You can let this issue closed.
