### ISSUE TITLE
Double values can be entered in integer fields

### ISSUE THREAD

**Issue by maxmentha** [opengisch/QField#173]
When the user creates a new feature and fills the attribute table, he can enter data that does not have the correct format without being warned about it, and without the app to prevent this from happening. For example, if a field is defined as a double real number, but with a scale of 0, the user can still enter numbers with decimals when digitizing. However, they will be saved with the scale that was defined at the creation of the field. This leads to a loss of information that goes unnoticed at the moment of the digitalization.

### Reproduction Steps:

1. create a shapefile with a real/double field with scale 0
2. enter data with decimals
3. the data gets lost...

### Expected behavior:

warning or impossibility to save invalid data

### Observed behavior:

data gets saved with defined scale, without any warning

### Screenshots and GIFs

**QField version:** 0.10.1
## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: ?
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by saemiw** [comment]
I can confirm this. It happend during some field work of us where we entered double values into an accidentally as integer define field. All the decimal information was lost. It would of course be nice if QField could somehow show a warning when this is the case.

**Comment by m-kuhn** [comment]
> When the user creates a new feature and fills the attribute table, he can enter data that does not have the correct format without being warned about it, and without the app to prevent this from happening. For example ...

Is it only the double/integer issue or are there other ones as well?

**Comment by saemiw** [comment]
I'll have list of potential bugs that I will check hopefully mid-october. I will then also check if this issue is relevant for other data types. For the moment I am only aware of the above mentioned.

**Comment by saemiw** [comment]
There are some other issues (date for example does not save integer, decimal values). This is probably not so problematic. BUT it would of course be nice to have a warning for all the fields if the entry doesn't correspond to the datatype defined.
