### ISSUE TITLE
Special characters symbols not properly displayed in value lists

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/QField#1740]
The special characters (such as &) are not properly displayed in Value Relation Widget for WFS layers

### Reproduction Steps:

1. [First Step] Create a table of Companies (id, name) (Values = [OpenGIS, Meylan & CIE]) 
2. [Second Step] Reference this table in a Value Relation Widget to display the Company name
3. [Other Steps...] Make this table and the parent table a WFS layer for QGIS Server

### Expected behavior:
You should see in the companies' pull-down menu the 2 values [OpenGIS, Meylan & CIE]
Note : this problem does not occur with a geopackage, but it occurs with a WFS layer

### Observed behavior:

Instead of Meylan & CIE, the pull-down menu displays the value < ! [CDATA[Meylan_CIE]]>

### Screenshots and GIFs

**QField version:** 1.8.4

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Unknown]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@jpdupuy , is this a problem with QField only or also a problem in QGIS?

**Comment by jpdupuy** [comment]
Hello, 

This also occurs in QGIS Desktop 3.10
![image](https://user-images.githubusercontent.com/72449015/116079222-d47a7600-a697-11eb-8137-963292e2c2eb.png)

**Comment by nirvn** [comment]
@jpdupuy , OK, this is therefore a problem upstream. You should a/ download the latest QGIS version (3.20) and verify that the problem is still present there. If so, please file a report against QGIS' issues tracker.
