### ISSUE TITLE
Issue with updating layers coming from a postgresql database on qfield

### ISSUE THREAD

**Issue by zakigates** [opengisch/QField#176]
We encounter a serious problem with QField, we're working with a postgreSQL database that we related to a QGIS project. We export the project via qfieldsync then we open it in QField, after that  we create  new features from different layers and we update  others. Yet when we synchronize with QGIS we recognize that the  created features have been added, but the updates are not applied to all layers, except to the one which is first on the alphabetical order. we are  stuck at this level. We don't want to be imposed to work with each layer separately. 

1. Open the QGIS project related with database 
2. export with qfieldsync.
3. copy the project folder to the device.
4. open qfield and navigate to my project.
5. create new features.
6. update existing ones.
7. quit qfield.
8. copy the project from the device with the sqlite file.
9. past it on my computer.
10. synchronize in qgis

### Expected behavior:
Find your new features and the see your updates

### Observed behavior:

the New features are being created but there is no update.

**Comment by saemiw** [comment]
I can unfortunately confirm this pretty serious issue when using qfieldsync in combinations with geopackages. It happens both when you use geopackages that contain one layer each and also if you use 1 geopackage containing several layers. In my eyes this is a very serious issue that needs urgent fixing, because it is not obvious/easy to notice to users that this is not working properly.

**Comment by saemiw** [comment]
We still have the offline projects is there a way to see where updates happened (for ex. with spatialite-gui)?

**Comment by m-kuhn** [comment]
Attribute changes are tracked in "log_feature_updates", new features into "log_added_features", feedback about its content (and sample data to reproduce) will be appreciated.

**Comment by saemiw** [comment]
Some more details from our tests:
Updates on the second, third,... layer are not synchronised by qfield sync (for the first layer everything works as expected). But this only happens to already existing features. If you create a new feature, save it and then afterwards edit an attribute -> these updates are synchronised correctly. However if you update an attribute of a feature that was digitized in a earlier field session (befor setting the project offline) updates on attribute values are lost. So if a feature is newly created and updated in the same field-digitizing-session everything works well. It is only a problem if you update attributes of older features (from previous field sessions).

You can check this out with this simple dummy project:
[Updates_lost.zip](https://github.com/opengisch/QField/files/1484497/Updates_lost.zip)

**Comment by m-kuhn** [comment]
Looks like a bug in offline editing, present in QGIS 2.18 and master. It has probably been there forever. Upstream issue report https://issues.qgis.org/issues/17647. Investigating...

**Comment by m-kuhn** [comment]
Pull requests for 3.99 https://github.com/qgis/QGIS/pull/5814 and 2.18.15 https://github.com/qgis/QGIS/pull/5815 pending.

**Comment by m-kuhn** [comment]
@saemiw @zakigates can you test with the current 2.18 nightly and report back if it's fixed? Thanks.

**Comment by saemiw** [comment]
I fail to install QField Sync using 2.18.14-23 (nightly). Any advice?
![unbenannt](https://user-images.githubusercontent.com/20398621/33718996-a902e4fa-db5f-11e7-8f67-6451c0628220.PNG)

**Comment by m-kuhn** [comment]
Seems to be a qgis2compat issue again...
https://github.com/opengisch/qfieldsync/issues/43

**Comment by zakigates** [comment]
It's a pyqt issue. Uninstall and reinstall it and it would be fixed.

**Comment by zakigates** [comment]
Could you please send me the link to download 2.18 nightly

**Comment by m-kuhn** [comment]
Use osgeo4w (qgis-rel-dev)
Or download 2.18.15

**Comment by saemiw** [comment]
Yes I can confirm that the bug has disappeared with 2.18.15 (I tested with geopackage only). Excellent!!!

**Comment by zakigates** [comment]
@saemiw  dev or released version, could you confirm it to me.

**Comment by saemiw** [comment]
I tested with the released version (2.18.15).
