### ISSUE TITLE
Crashing upon opening

### ISSUE THREAD

**Issue by adrigen123** [opengisch/QField#1763]
Upon installing onto galaxy s5 android 6.0.1 the app crashes every time. Dialogue is unfortunately qfiled has stopped. I have 

1. Reported this via reporting option.
2. Reinstalled app same result.
3. Removed SD card same result
4. Tried install on another more recent android phone and had no prob. 

is there an upper limit to compatability with the OS?

**Comment by m-kuhn** [comment]
Can you try with older versions to see if it worked with one of them?
