### ISSUE TITLE
Symbols are displayed incorrect and in the wrong color

### ISSUE THREAD

**Issue by gemmos** [opengisch/QField#1766]
I have a layer with several different Symbols for various categories (10 to be exact).
Half of the layers are green, the other half is using the same symbols, but in red.

When imported to QField, the existing symbols on the map are displayed correctly, but the symbols in the layer description are all shown in the same color (all green).

When adding a new datapoint, the color is displayed correctly. This problem seems to affect only the layer description.

I tested the project on two different devices: Samsung Galaxy Tab Active (SM-T365, Android 5.1.1) and Samsung S10+ (Android 10). Both devices show the aforementioned problem.

QField Version 1.8.4

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No]

**Comment by nirvn** [comment]
@gemmos , can you attach a screenshot of the problematic legend? Off the top of my end, this could happen if you have named your layer categories with the exact same name/label.
