### ISSUE TITLE
Remember "Remember checkboxes" when switching between layers

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#177]
The "remember checkboxes" make data entry faster/easier by remembering values that are used over and over. Our this years field work has shown that people often have to switch between different tables (so: digitize a tree in the table trees and then digitize a bird in the table birds). When you check a "remember checkbox" this checked state is lost as soon as you start digitizing on another layer. It would be nice if the "remember checkbox" state would be remembered until QField is closed and not until the next layer is edited.

**QField version:** [0.10.1]

## Additional information:

* The data are saved in geopackages
* The project is set up on QGIS 2.18.13

**Comment by soester** [comment]
We have the same issue when working on offline Sqlite-DB. As we often use the remember checkboxes to retain values for site specific parameters (around 5 values) this can get quite annoying. Specially in combination with issue #138.

**Comment by signedav** [comment]
@saemiw I'm not sure about the status anymore. Remember that something has been done about.
Is this still an issue?

**Comment by saemiw** [comment]
@signedav No this is not fixed yet. It is however not really a bug and hence not a very urgent issue (nor did we pay for it to be fixed) . 

When in the digitizing mode the remembered value for table 1 (for example "apple tree") is still lost as soon as you switch to another layer/table2.  The loss happens as soon as you select another layer in the layer tree (you don't need to actually enter a value for layer/table2).

**Comment by signedav** [comment]
Okay. Thanks @saemiw

**Comment by xyago** [comment]
We wanted to ask how can we sponsored this development

**Comment by m-kuhn** [comment]
@xyago please contact us by mail at info@opengis.ch so we can send you an offer. We quickly estimated this roughly a day of work.

**Comment by xyago** [comment]
@m-kuhn ok I'll write you an email.
