### ISSUE TITLE
Qfield crashes when accessing layer features list

### ISSUE THREAD

**Issue by Vb1983** [opengisch/QField#1776]
Hi, 
I am currently working on a project where I collect data points and whole area information. So far things worked well, although in the polygon layer labels were not shown correctly. I could access the layers features list and edit the polygon shapes. Now I can only sometimes draw a new polygon, and when I try to access its features, qfield is terminated. 
The point layer and accessing the features works fine. How do I fix this?
Thank you for any ideas!

### Expected behavior:

I expect to access the polygon features list, select a polygon and be able to modify its shape or attributes ( details)

### Observed behavior:

First I could not change the attributes (name or information details) but could change the shape,
Now qfield is terminated when trying to access the features list.

**QField version:** 1.8.4 (7b5255 v1.8.4)

## Additional information:

I have only used this version of qfield
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [first project]

**Comment by nirvn** [comment]
@Vb1983 , more information is needed here. What dataset format are you using to digitize the polygon? How do you digitize your polygon? 

Ideally, try to attach a project with a sample dataset and steps to reproduce. Without that, devs are left completely in the dark.

As for wrong labels, if you're referring to the map being drawn, that's most likely a problem with the way you've set up your project.
