### ISSUE TITLE
Qfield crashes randomly

### ISSUE THREAD

**Issue by Oisin-JK** [opengisch/QField#1779]
Qfield 1.8.4, on Samsung Galaxy Tab S4, Androip 10. Project prepared in QGIS 3.14

My project is file based, shp files. It contains various non-editable layers (a topographical survey) and three editable layers  - a point, line, and polygon layer. It also has a copy of each of the editable layers with a geometry generator applied.

This has worked fine since July 2020. Recently (last two months) it has started crashing unexpectedly, with no warning and no error. Re-starting Qfield usually works, but I am unable to determine the cause. 

Sometimes the crash occurs immediately at start-up. Other times when zomming in. I've also noted crashes occurring when trying to edit or delete a feature. But none of it is reliably reproducible.

### Reproduction Steps:
Unable to reproduce reliably

### Expected behavior:
Either not to crash, or if a crash does occur, to provide an error message or log.

### Observed behavior:
No error message occurs. When I reopen, I open the log, but it is empty. I cannot see how to turn on error logging. 

### Screenshots and GIFs
None

**QField version:** 7b5255 v1.8.4

**Comment by m-kuhn** [comment]
Do you have the possibility to create an adb log of when the crash happens? (will need debugging tools installed on a computer and the device attached by cable)

**Comment by Oisin-JK** [comment]
I can certainly try.
Where do i get the tools from.

⁣Get BlueMail for Android ​

**Comment by m-kuhn** [comment]
A command line tool can be obtained here:
https://developer.android.com/studio/releases/platform-tools
Otherwise it comes with Android Studio

**Comment by Oisin-JK** [comment]
I'll look into it and let you kniw if its in my capability.

⁣Get BlueMail for Android ​
