### ISSUE TITLE
Large forms take too long to load

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#178]
Large forms (91 attributes) take a long time to load if one uses widgets like value maps. Without widgets the attribute table loads much faster. Is there a possiblity to enhance the performance of the form generation?

In the attached example a table with 91 attributes of which 22 use value maps takes >1min to load. Without the value maps the same table takes about 2 secs to load (which is comparable to the behaviour on QGIS Desktop). See attached data to reproduce on your own device
[Large forms take too long to load.zip](https://github.com/opengisch/QField/files/1410996/Large.forms.take.too.long.to.load.zip)

### Reproduction Steps:

This video documents the time it takes for the situation with value maps:
https://www.youtube.com/watch?v=zaojktWHN-w&feature=youtu.be 

**QField version:** [0.10.1]

## Additional information:

* We work with geopackages
* Project was set up with QGIS 2.18.13
* Tablets used: Samsung Galaxy Tab Active

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [didn't test but expect so]

**Comment by saemiw** [comment]
Associated to this problem: When you have impatient users that continue clicking on the screen while qfield builds up the form QField can crash. So: Fast clicking that make QField crash (which is understandable but not very nice ;D).

**Comment by saemiw** [comment]
@m-kuhn: In the first post on this issue report I already posted (inside zip) two offline qgs-projects (and data) that illustrate the problem. 

If you need non-offline projects, try with the attached project below (currently not using the value-map widget). If you use value maps (choos any random values) instead of the text widget you'll be able to create the problem. Is that sufficient for you or do you need more?
[Large forms take too long to load (non-offline project).zip](https://github.com/opengisch/QField/files/1453603/Large.forms.take.too.long.to.load.non-offline.project.zip)

**Comment by saemiw** [comment]
@m-kuhn I made a reminder to me that I should provide you with data for testing this issue. Upon reading the issue it seems that I also provided some data. Let me know if you need more/other projects as soon as you start working on this. I am happy/willing to support you with problem data in case you need more ;D: For now I leave it as it is.

**Comment by m-kuhn** [comment]
Thanks @saemiw I might get back to you in January in case of open questions

**Comment by signedav** [comment]
Maybe it's because of the more powerful devices or this is fixed meanwhile. It takes not long to load the project (mit value maps).
If it persists, please reopen it @saemiw 
Thanks

**Comment by saemiw** [comment]
@signedav just to avoid unnecessary testing effort. Have you tried with project provided on the 8th of November 2017....It was only a problem when you have a lot of value maps (say 80 fields with valuemaps).

**Comment by signedav** [comment]
Yes I tested with your project as well.

**Comment by saemiw** [comment]
pleasently surprised I can also confirm this (tested with QField 1.3.0)
