### ISSUE TITLE
QField Display Glitch - ghosting of text

### ISSUE THREAD

**Issue by Oisin-JK** [opengisch/QField#1780]
Qfield 1.8.4, on Samsung Galaxy Tab S4, Androip 10. Project prepared in QGIS 3.14

My project is file based, shp files. It contains various non-editable layers (a topographical survey) and three editable layers - a point, line, and polygon layer. It also has a copy of each of the editable layers with a geometry generator applied.

Sometimes when editing an existing feature, the text in a text box widget appears to be ghosted, i.e. duplicated and slightly offset, making it appear blurry. If you then try to edit the text, deleting text removes 'one layer of the ghosted text' leaving the other. When you enter new text, this is superimposed over the old text, making it very difficult to see text changes. On save, edits are correctly saved.

### Reproduction Steps:
Cannot identify steps to reliably recreate issue. Seems to occur after after a period of use.

### Expected behavior:
No ghosting of text

### Observed behavior:
As described above

### Screenshots and GIFs
![Uploading GifMaker_20210317162352231.gif…]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Don't know]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: [Yes, albeit all are similar projects created from the same template]

**Comment by nirvn** [comment]
Fixed in 1.9.
