### ISSUE TITLE
Crash on print when having no map

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#1782]
When having a print layout with a map item inside it works.
When having a print layout with only a label inside it crashes.

I'll provide more information.

It's 1.9.

**Comment by nirvn** [comment]
@signedav , let me check a sec.

**Comment by signedav** [comment]
found it

**Comment by nirvn** [comment]
@signedav , PR open :wink:

**Comment by signedav** [comment]
Ah, you're just too fast :rocket: 
![image](https://user-images.githubusercontent.com/28384354/111594834-d5340880-87cb-11eb-9680-f30132fa59bd.png)

**Comment by signedav** [comment]
Thanks a lot.
