### ISSUE TITLE
Bugs QFIELD

### ISSUE THREAD

**Issue by mmantran** [opengisch/QField#1784]
Bonjour,
J'utilise QFIELD depuis plusieurs années.
Plusieurs bugs sont constatés dans la dernière version : 
 - Dans le formulaire, il est impossible de mettre des espaces dans le texte.
 - La prise de photo est longue et plante régulièrement l'application
 - la création d'objet est long et plante aussi l'application
 - l'ajout de la géolocalisation des photos ralenti considérablement la prise de photo, plante régulièrement et, pour mon usage, ne m'est pas utile
La version précédente n'avait pas tous ces bugs.
Vous avez corrigé l'échelle graphique qui indiquait en degré et non en mètres dans la version précédente.
Je suis en pleine enquête de terrain et ces bugs ralentissent considérablement mon enquête.
Géomatiquement

**Comment by nirvn** [comment]
@mmantran , suggestions:
1/ ouvres un ticket par bug
2/ donnes des instructions (et si possible des projets et datasets) pour reproduire chaque bug qui tu aura ouvert individuellement
3/ sois le plus precis possible, car en ce moment ta description est bcp trop generique; par exemple, la "derniere" version (j imagine 1.8.4?) n a rien changé point de vue camera, donc on a aucune idee de ce que tu utilises, et de ta version precedente

Pour ce qui est de la camera, tu peux essayer de changer l option native camera (l enlever si c est presentement actif, ou vise versa).
