### ISSUE TITLE
Moving point feature opens reshape tool

### ISSUE THREAD

**Issue by monticola2** [opengisch/QField#1785]
If I want to move a saved point feature to another location, the reshape tools opens and the point cannot be moved. Instead you can create a polygon with the reshape tool.

### Reproduction Steps:

1. Create point feature
2. Select it and click edit geometry
3. 3. try moving the point

### Expected behavior:

You can move the selected point with the crosshair and save it at another location.

### Observed behavior:

The reshape tool opens, you cannot move the point and if you click on "+" a polygon gets created.

### Screenshots and GIFs

https://user-images.githubusercontent.com/64013745/111799796-a1d8a300-88cb-11eb-93d9-d2f5b0820ae2.mp4

**QField version: 1.9.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes, tested with geopackages and shapefiles in at least three different projects; (projects were created with "the dud" QGIS 3.18.0 on Windows but that shouldn't matter, should it?)

**Comment by signedav** [comment]
I cannot reproduce it e.g. with the bee farming demo project on layer "apiary"? Do you?

**Comment by signedav** [comment]
Otherwise can you provide us a dataset to test with?

**Comment by monticola2** [comment]
Happened with "apiary", too. Works now after a simple reinstall though. Sorry!
