### ISSUE TITLE
Relation Reference Widget is not able to select same entry twice in a row

### ISSUE THREAD

**Issue by lp-dj** [opengisch/QField#1788]
If I try to select the same item in a Relation Reference Widget as i did for the last feature the Value stays NULL.

### Reproduction Steps:

1. Create feature in a layer with at least one Relation Reference Widget in its attribute form.
2. Select entry from Relation Reference Widget.
3. Save feature.
4. Create new feature in same layer as in Step 1).
5. Select same entry from same Relation Reference Widget as in Step 2).

### Expected behavior:

Apply the value for the corresponding attribute.

### Observed behavior:

The value stays Null.

### Screenshots and GIFs

https://user-images.githubusercontent.com/80956612/111783601-a9438080-88ba-11eb-9d7b-ffac197e1077.mp4

**QField version:** 1.8.4 (77b5255)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Unsure; Similar behavior in the Relation Reference widget has been present in QField for at least a year now: It is not possible to scroll far down the list and select an entry there. Are you aware of that? Fortunately, thanks to the long-awaited autocomplete, you are now at least able to narrow down the list! Thanks a lot for your great work!  :)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes, e.g. same behavior is reproducable with the "Advanced Bee Farming" demo-project of QField.
* Sometimes remembering the last attribute values suddenly doesn't work anymore. I have the suspicion that this could also have to do with this bug?
* QGis-Version: 3.16.4
* Mobile-OS: LineageOS 10 / Android 10
* Desktop-OS: Fedora 33

**Comment by bsturm** [comment]
I am experiencing the same issue with Qfield 1.9.0., exactly as lp-dj described it.

**Comment by suricactus** [comment]
Confirmed and reproducable. I will take care of it probably next week.

**Comment by amgiss** [comment]
This is still happening as lp-dj described in the latest 1.9.5 build.

**Comment by soester** [comment]
I can confirm this behaviour as well.
Setup:
Offline Projects created via qfieldsync form QGIS-Porject with value relations defined via Postgres-Layers (Qfield 1.9.5). 

# Observed behavior:
Values in the dropdown list, which are allready 'marked green' cannot be selected. This is the case, when i want to select the same value again for the next digitized feature.

**Comment by nirvn** [comment]
Fix incoming.

**Comment by nirvn** [comment]
@soester , @amgiss , @lp-dj @bsturm , please try the APKs in PR #1893 and confirm this issue has been fixed there. I've also spent a fair amount of timing tweaking the widget padding / spacing / etc. so you should notice a visual improvement and a nice alignment between the widget and the "remember value" checkbox.

**Comment by soester** [comment]
@nirvn 
much better, thanks for the fix!

**Comment by lp-dj** [comment]
Thanks a lot, works great!

**Comment by amgiss** [comment]
That fix seems to be working well. Thanks!

**Comment by nirvn** [comment]
@lp-dj , @amgiss , beautiful! :) thanks to all for confirming
