### ISSUE TITLE
QField crashes when I tried to created a geometry from a alphanumeric form that start editing from geometry form

### ISSUE THREAD

**Issue by jhonalex06** [opengisch/QField#1789]
When I tried to create a new **terreno** or a new **direccion** started from **terreno historico** and passing through the **predio**, the application is not able to create the latter geometry.

### Reproduction Steps:

1. Select **Terreno historico** in the interface.
2. Activate edit option.
3. Select the option green (Open form). This will display a **predio** form
4. Try to create a new **direccion** in **Listado de direcciones**
5. If you can create a new **dirección**, go to tab **3- Terreno**
6. Try to create a new **Terreno** in **Listado de terrenos del predio**

### Expected behavior:

When I start editing from geometry form and go to alphanumeric form, I expect that I could create a new geometry from this form.

### Observed behavior:

When I start editing from geometry form and go to alphanumeric form, I can't create a new geometry from this form.

### Screenshots and GIFs

Direccion

https://user-images.githubusercontent.com/27906888/111802539-1ac00680-889c-11eb-915d-4c8ca45c8476.mp4

Terreno

https://user-images.githubusercontent.com/27906888/111802558-21e71480-889c-11eb-8c59-fc563d56967d.mp4

**QGIS Project**: [project.zip](https://github.com/opengisch/QField/files/6172267/project.zip)

**adb logcat**: https://gist.github.com/jhonalex06/477856de3c359f578546e88c2f5b0467

In the logcat file, I tried to create a new **direccion** and the application showed me a loading icon and I reloaded the application, then when I tried to create a new **terreno**, the application stopped.

**QField version:** "1.9.0" (d8766c)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@jhonalex06 , I've been trying - and failing - to replicate the freeze or the crash here.

**Comment by nirvn** [comment]
@jhonalex06 , try those APKs, the crash might be gone: https://github.com/opengisch/QField/pull/1792#issuecomment-803824508

**Comment by jhonalex06** [comment]
@nirnv, Thanks for your attention, I was tested these days, different versions of QField, like #1792, and the release 1.9.1, 1.9.2, and 1.9.3, and in all of them the error happened. 

When I tried in the emulator on QT Creator, the error didn’t happen, but today I discovered that the error happens in the cellphone, when I use in portrait mode, if I put it in a landscape, the error doesn't happen 

In this video, I show you this behavior: 

https://user-images.githubusercontent.com/27906888/114583968-c6643880-9c47-11eb-96bb-fb99327a74f8.mp4

**Comment by nirvn** [comment]
@jhonalex06 , are you able to get crash trace via adb logcat? I just tried on my phone in both landscape and portrait and still can't get it to crash.

**Comment by jhonalex06** [comment]
Yes @nirvn, here is the adb logcat: https://gist.github.com/jhonalex06/477856de3c359f578546e88c2f5b0467, but today I will generate other for you.

**Comment by nirvn** [comment]
@jhonalex06 , no luck on the latest logcat didn't capture the crash itself. Still unable to replicate crash :thinking:

**Comment by nirvn** [comment]
@jhonalex06 , are you still able to replicate the crash in the latest version of QField (2.2.2)?

**Comment by jhonalex06** [comment]
Hello @nirvn, I am not currently working with SwissTierras Colombia, but I will be happy to test it and let you know the result.

Thank you for your reply
