### ISSUE TITLE
Save GPS accuracy

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#179]
Not an issue but a useful improvement:

It is possible to get the elevation from GPS by using the expression z($geometry). Is it also possible to extract within QField the GPS-accuracy the moment a point is digitized?

Matthias Kuhns reply (on the mailing list):
> Unfortunately this is not yet implemented.
> 
> I see two different approaches on how to get this information from the sensor to the data
> 
> - Expose it as a variable (@positioning_accuracy) to the attribute form. The attribute form will need to be configured, so this information is saved to a feature (via default values). 
> 
> - Save this information to the m value of vertices. For this to work, the dataset has to be a format that supports m values. It could then also be extracted with m($geometry).
> 
> The approach with m values has the approach that it works perfectly fine for line geometries as well. An accuracy value can be saved for each vertex. The approach with @variables on the other hand is on geometry level and not on vertex level. Therefore, this would need to save this information into an array for lines. So if a vertex is deleted on such a line later on, the information is corrupted easily. On the other hand, it has the advantage that several values can be saved like other data coming from positioning sensors (like speed) or from external sensors. Whereas with m values there is only space for one single value per vertex.
Personally, I tend towards the variable/attribute  approach.

We would at the moment mainly use this functionality for point data. Hence the variable/attribute approach would be perfectly fine. If someone has a strong preference for the m values please let us know. Otherwise will probably soon as opengisch to implement the variable/attribute approach.

**Comment by signedav** [comment]
That's done [here](https://github.com/opengisch/QField/commit/efde26a5d98801eccd11684a7f6487414c177870)

You can use @position_horizontal_accuracy as the default value.

**Comment by 3nids** [comment]
would it make sense to name these variables as `qfield_ position_horizontal_accuracy`?

**Comment by AndreaMainz** [comment]
> seems to work fine (with 0.10.11)! thanks

It works only with digitizing new points? ora also polygons?
and only when digitizing new features? when on edit an attribute it is not recorded?
very nice features!
