### ISSUE TITLE
START TRACKING

### ISSUE THREAD

**Issue by pacoogrove** [opengisch/QField#1791]
Hello; in the last update of the application, have you not included **START TRACKING**? I think it was a very good complement to the application; traking the route !! I miss her... ;( 

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField 1.9.0** 

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: No
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
I cannot reproduce. Do you have the localisation activated? Can you test on the demo project "Advanced bee farming" on layer "Fields"?

**Comment by pacoogrove** [comment]
![start_tracking](https://user-images.githubusercontent.com/9004868/111870235-cc863280-8983-11eb-8598-f4ac7b7487ab.png)


> I cannot reproduce. Do you have the localization (GPS) activated? Can you test on the demo project "Advanced bee farming" on layer "Fields"?
-------------------------------------------------

After activating the tracking of Advanced bee farming, the tracking was perfectly activated in my application.
![WhatsApp Image 2021-03-20 at 22 09 09 (3)](https://user-images.githubusercontent.com/9004868/111886071-c61ba900-89cb-11eb-9278-7bff607451a7.jpeg)
![WhatsApp Image 2021-03-20 at 22 09 09 (2)](https://user-images.githubusercontent.com/9004868/111886072-c6b43f80-89cb-11eb-855b-378d298e8885.jpeg)
![toma datos en playas](https://user-images.githubusercontent.com/9004868/111886075-ca47c680-89cb-11eb-8782-0370086912af.jpeg)



Attached screenshots ...

Thanks a lot!!
