### ISSUE TITLE
MultiLine Form Field - Double Text

### ISSUE THREAD

**Issue by sonicnkt** [opengisch/QField#1796]
Using Multiline Form Fields produces double or shadow like text. (See Screenshot below).
Those "background" characters are the previous value so if you have set default values those will be shown in the background or if you have changed the form data switch to another form tab and return. 

Only happens with multiline Text Input, Single line works flawlessly.

This only a display bug, correct values are stored in the layer.

### Reproduction Steps:

1. Create Multiline Input Form with Default Text set
2. Create Feature in QField

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/5454622/111980972-527eb680-8b07-11eb-8ec7-15871175fbd5.png)

**QField version:** 1.8.4 (7b5255)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes (not sure when)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
Fixed in 1.9 (currently in beta stage, should be out soon)

**Comment by sonicnkt** [comment]
Ah ok sorry, searched fro closed issue but didnt find anything! 
Thanks for the quick reply!

**Comment by nirvn** [comment]
No worries, you did good, I don't think it was reported before. We're just too quick at fixing regressions ;-P
