### ISSUE TITLE
Not support mbtiles?

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#18]
qfield not support mbtiles raster layer. crashes when uploaded the project with mbtiles raster layer.  Sony xperia tablet z1, Android 4.3

**Comment by m-kuhn** [comment]
Probably related to #23

**Comment by m-kuhn** [comment]
Can you check again with a recent build? This may have been improved by recent build tools/gdal updates.

**Comment by giedrioks26** [comment]
so, now open the project with mbtiles
