### ISSUE TITLE
Adjustable image size in form

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#180]
On some devices taking images works well. We used images to relocate birds nest that were found during a previous visit. Unfortunately the size of the images shown in the QField form is rather small. It would be cool to either always use the maximum screen width (if the option "integrated document viewer" is checked in the External Resource widget) or have thepossiblity to modify the prefered image width (also through the settings of the external resource widget). At the moment these settings have no effect on the image size on QField.

**Comment by m-kuhn** [comment]
I was considering a "fullscreen on click", would that work?

**Comment by saemiw** [comment]
yes that would be perfect

**Comment by signedav** [comment]
Is the stored image-size with the new camera feature sufficient?

**Comment by saemiw** [comment]
the "fullscreen on click" functionality is not implemented yet, maybe something for the crowd-funding campaing (if you get the money...)

**Comment by nirvn** [comment]
I think that's implemented now. Image will take full available width and clicking on image opens full screen app
