### ISSUE TITLE
Three finger screenshot breaks clickable elements

### ISSUE THREAD

**Issue by suricactus** [opengisch/QField#1803]
Does not always happen (50% of the time), but when it does, it requires QField restart. The same goes not only for the map canvas, but buttons too. Swipe, scroll and other gestures other than tap seem to work.

Someone mentioned this for the new relation widget too. 

https://user-images.githubusercontent.com/2820439/112143855-20418780-8be1-11eb-894d-0e2c60961764.mp4

Android 10
ColorOS 7.1

**Comment by nirvn** [comment]
@suricactus , still an issue with QField 3.2? If not, let's praise Qt6 and close this ;)

**Comment by mohsenD98** [comment]
Tested on Xiaomi Poco X5: No issue occurred.

**Comment by suricactus** [comment]
I changed my phone since then, last time I checked it was still an issue.

**Comment by nirvn** [comment]
Let's close for now and reopen if we find a phone that reproduces this.
