### ISSUE TITLE
External GNSS accuracy indicator/requirement

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/QField#1804]
When connecting with a external gnss reciever, the accuracy indicator is a handy thing to use.

Question: on with variable is it based on? horizontal, vertical or 3D?

The accuracy requirement, when activated in the settings->positioning is sometimes working, giving the expected restriction. Sometimes I'm able to collect point even if I'm above my accuracy set (but not knowing on which variable based).

### Reproduction Steps:

1.connect an external receiver
2.set accuracy and enable accuracy requirement
3.collect point with bad gnss accuracy (ex. >0.02m)

### Expected behavior:

not possible to collect a point

### Observed behavior:

sometimes possible and sometimes not, quite random and not realy reproduceable.

**QField version:** 1.9.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: ?
* Problem can be reliably reproduced, doesn't happen randomly: No
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@EulenspiegelTill , I believe this issue has been addressed in PR #1819 . If it's possible, could you test against the APKs provided in the PR's comments section? Thanks.

**Comment by EulenspiegelTill** [comment]
@nirvn did tested it now with the apk in PR #1819, it is working fine!  
It is based on the horizontal accuracy am I right? `positionSource.positionInfo.hacc` 
I did tested it field with a old gnss-receiver: smooth pairing and it was running on spot! 🙌

**Comment by nirvn** [comment]
@EulenspiegelTill , fantastic news! Thanks for the quick feedback.

**Comment by nirvn** [comment]
@EulenspiegelTill , sorry, to answer your question how what we use as accuracy variable, your deduction is correct. At the moment, we rely solely on the device's horizontal accuracy value.
