### ISSUE TITLE
A string does not appear in transifex

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField#1805]
@m-kuhn 
I found a string in QField which is not translated to Japanese language.

https://github.com/opengisch/QField/blob/66c89757671e7b669aae4e28d0de5f8ded899f43/src/core/locatormodelsuperbridge.cpp#L192-L198

This string `Returns a point from a pair of X and Y coordinates typed in the search bar` does not appear in transifex. 

My QField version is `1.9.1`.

The below is the screenshot of QField.
![image](https://user-images.githubusercontent.com/2639701/112785845-ec0e1100-908f-11eb-95bd-76acbb8ced81.png)

The following figure is when I tried to search the string in transifex, the result was empty.
![image](https://user-images.githubusercontent.com/2639701/112785946-22e42700-9090-11eb-8ed3-bdf9287e8320.png)

**Comment by nirvn** [comment]
@JinIgarashi , good catch, fix submitted. Thanks for your dedication keep QField's Japanese translation up-to-date! :)
