### ISSUE TITLE
Access/edit project variables in settings

### ISSUE THREAD

**Issue by 3nids** [opengisch/QField#1814]
it would be quite useful to access and edit the project variables in the settings.
To play with default values for attributes for instance.

**Comment by nirvn** [comment]
That'd be interesting, and relatively easy (I'm thinking a combobox over the variable list to switch between system and project). 

Since we deal with projects as read-only entities, you don't see those as being permanent changes?

**Comment by 3nids** [comment]
I think that the changes should be saved yes.
We could maybe create an overwriting hack using QSettings?

**Comment by nirvn** [comment]
We would have to indeed.

**Comment by mussels** [comment]
I raised this in a different discussion #4374 only for someone to kindly pointing me in this direction... but this is now more than 2 years old. Has this proposed enhancement been retired? This is something I regularly use on QGIS desktop and would be really useful on qfield... default values and all that. It's easy to access the setting in qfield and used this for day to day data collection work. Setting global variable achieves similar results but not right as I could simply bake the proj vars right into the project instead. Thanks

**Comment by nirvn** [comment]
Implemented in https://github.com/opengisch/QField/pull/5593
