### ISSUE TITLE
Qfield treating Point25D as PointZ

### ISSUE THREAD

**Issue by kwaabs** [opengisch/QField#1815]
Qfield is treating Point25D as PointZ geometries and this is causing errors during synchronization.

I undertook the following steps.
1. Loaded Point25D geometries and packaged them for Qfield as offline editing
2. Loaded project into Qfield (Android file transfer)
3. New data is added to offline Qfield and also some edits are made on tablet
4. Data is file transferred back to PC
5. Error has to do with dimensioning

What is wrong?

**Comment by m-kuhn** [comment]
This seems to be a QGIS issue.
Can you try the same directly inside QGIS with the "offline editing plugin"?
