### ISSUE TITLE
QField external resources should support adding non-image resources

### ISSUE THREAD

**Issue by Ahmad-Fuad** [opengisch/QField#1816]
Can't open documents on QField after configuring hyperlink attachment widget on QGIS. It works well on QGIS but not on QField.

### Reproduction Steps:

1. Prepare QGIS project with attachment widget enabled in layer form (hyperlink option checked)
2. Load and open packaged project on device
3. Edit the layer

### Expected behavior:

The option “hyperlink” on the attachment widget will disable the camera functionality and enable a hyperlink to open a document (pdf, doc, …)

### Observed behavior:

Camera functionality still there and no way to browse documents

**QField version:** 1.8.4 (7b5255 v1.8.4)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
This should be working actually since https://github.com/opengisch/QField/pull/1029

**Comment by nirvn** [comment]
@Ahmad-Fuad , you filed both a likely issue and a feature request here.

If you have setup a project with an attachment widget that links to an existing file on your mobile device and the hyperlink was missing, #1838 should fix this situation.

As for QField's attachment widget supporting non-image inputs, that's an interesting feature request :)

**Comment by nirvn** [comment]
@Ahmad-Fuad , you'll be happy to know this has been implemented as of QField 3.2. Happy field mapping!
