### ISSUE TITLE
Remember value no longer works

### ISSUE THREAD

**Issue by monticola2** [opengisch/QField#1823]
Remembering values in feature creation does no longer work with v1.9.2

### Reproduction Steps:

1. Create feature e.g. with field "number" and attribute "3"
2. Check "remember value" box
3. Create another feature and check the "number" field

### Expected behavior:

New feature shows the same value (in this example "3") as the feature before.

### Observed behavior:

Field "number" freestyles. Anything from empty, 0 to the same value is possible but absolutely unpredictable.
(I only tested with integer fields.)

**QField version:** v1.9.2

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes, I went back to 1.8.4 and have no problems. I think it didn't happen in 1.9.0 und 1.9.1 but I am not sure. Reinstalling 1.9.2 didn't help.
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by monticola2** [comment]
Works again, thanks for the quick response!

**Comment by nirvn** [comment]
@monticola2 , thanks to you for being an active beta participants and help out keeping track of regressions.
