### ISSUE TITLE
Copy features

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#1825]
I would like to copy a selection of features and then be able to move them and change attributes.

On the "feature selection panel"
1. add a new button to copy selected features
2. show selected features as temporary rubberband / features (multiple geometries)
3. allow moving these temporary features to a new location
4. allow cancelling or confirming the operation
5. if confirmed, keep the selection of the new features to be able to modify them with multi edit (or delete or ...)

**Comment by lp-dj** [comment]
Oh, that sounds great. Can I join in? ;)

What I would also find great would be the possibility to just copy the attributes from one existing feature to another.

1. add a new button to "copy attributes" of a selected feature (should only appear if exactly one feature is selected)
2. from now on the button to "paste attribute" appears next to it (this button is also visible if multiple features are selected at the same time, to apply the copied attributes to all selected features)
3. the crowning glory would be, if the copying also works cascaded including possible existing relations and ...
4. ... there would be the possibility to mark/ exclude attributes to be copied. Maybe by a checkbox similar to the one you already use to mark attribute entries for the next feature.

**Comment by m-kuhn** [comment]
@lp-dj I have moved this suggestion to a new issue, while they are similar, I think they can both be treated individually. This one is likely to be sponsored by someone soon, so it would be a pity to loose your ideas if we close this when implemented.

**Comment by lp-dj** [comment]
@m-kuhn You're right, thanks for moving!

Will keep that in mind next time.

**Comment by nirvn** [comment]
We now have both feature duplication (+ move) and attribute copy/pasting. Closing.
