### ISSUE TITLE
Support for time

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#183]
QField can use now() to save a time stamp at the time of digitalisation. Sometimes it would however by nice to record a time that is not the current time (time where sampling break starts, time when camera trap took a picture,...). QField currently doesn't support a setting like this. It would be nice if time could be modified but needs to stay in a predefined format (e.g. mm:mm:ss).
![time](https://user-images.githubusercontent.com/20398621/31994186-15ed9170-b980-11e7-890a-95b53bb17301.jpg)

**Comment by saemiw** [comment]
I have the impression that this was solved with https://github.com/opengisch/QField/pull/421. Can you check @3nids and close if you agree?

**Comment by 3nids** [comment]
yep, thanks
