### ISSUE TITLE
Attribute table updates upon sync from Qfield

### ISSUE THREAD

**Issue by danesadog** [opengisch/QField#1842]
Attribute fields in .shp files, that are setup to have default values or are virtual fields, experience a complete reset in their value once they are synced with the main project. 

For example, I have a "Create_Date" field which is intended to record the date an object or point was created; I accomplish this through a default value expression: If("Create_Date" is NULL, now(), "Create_Date"). Its not very robust, but it does work in the QGIS environment perfectly fine. But when I sync data from the field the "Create_Date" field is replaced by the current date, not the date that the data was created; this date will then perpetually stay with that object through any more syncs with Qfield, the objects attributes are only affected in the first synchronization.

I also have a "Creator" field which uses the same logic,  If("Creator" is NULL, Qfield_user, "Creator"), where "Qfield_user" is a variable I created in each of my field tablets and my pc that assigns them a name. When I sync the data, all new objects created in the field have their creator changed to my pc.

I understand that this isn't a bug, and it doesn't call for a specific improvement, but I'm just wondering if there is a way this could be made possible or worked around.

**Comment by nirvn** [comment]
@danesadog , without a sample project and dataset, it's unlikely this will be looked at.

**Comment by nirvn** [comment]
(Shot in the dark: this is likely an upstream limitation as when synchronizing from an offline layer, features are re-created, and default values re-evaluated)
