### ISSUE TITLE
Feature request: get attribute values from first snapped point

### ISSUE THREAD

**Issue by mittakainen** [opengisch/QField#1845]
Feature request: 
It would be nice to have an option to get attribute values from first snapped point automatically prefilled in form and if necessary you could also modify them. If snapped to feature in another layer, then just show e.g last used values.

**Comment by m-kuhn** [comment]
This should already be possible using appropriate geometry overlay or snapping default values.

**Comment by m-kuhn** [comment]
If this does not suit your needs, please feel free to leave another comment here.
