### ISSUE TITLE
UX issues with relation editor with more than 5 children

### ISSUE THREAD

**Issue by 3nids** [opengisch/QField#1850]
There are some design issues with the relation editor when the relation has more than 5 children:

* the view is clipped to 5 items: this is not obvious that the view can be scrolled. clipping it to 4.5 or 5.5 would solve the issue. Or showing a scrollbar?
* the children are not ordered. Could we respect the order used in desktop app?
* when you add a new child, it is placed at the end of the list, making it difficult to see, would be better placed on top

**Comment by nirvn** [comment]
All points above have been fixed.
