### ISSUE TITLE
Raster Layer  diplay is long

### ISSUE THREAD

**Issue by Crapaud04** [opengisch/QField#1859]
QGIS  3.16.5 - QField Sync 3.4.2 - Qfield 1.8.4 (7b5255v1.8.4) and 1.9.3 (5457e7 v1.9.3) - Tablette Huawei CMR-W09 Android 9

I have a Qgis project with different rasters (mbtile, vrt jpeg2000).
The project opens without major problem in 15 to 20s.
My probleme is after each movement of the map it takes on average 5s(in 1.8.4) or 10s (in 1.9.3) for it to be displayed. 

### Reproduction Steps:

1. Open Prject
2. Slide map
3. Wait 5s in 1.8.4 and 10 or 15 s 1.9.3
4. rasters layers diplay

### Expected behavior:

the raster display time is long

### Observed behavior:

The base map is white.

### Screenshots and GIFs

My project open raters layer of 2go in mdtile and vrt tile of 3 go in jpeg2000.

**QField version:  1.8.4 (7b5255v1.8.4) and 1.9.3 (5457e7 v1.9.3) 

https://user-images.githubusercontent.com/37582771/115512210-02b81a00-a282-11eb-8d05-0b26445022d7.mp4

https://user-images.githubusercontent.com/37582771/115512218-06e43780-a282-11eb-9cbf-a5079b740b96.mp4

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes and no, in the old version 5s and new 10-15s 
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@Crapaud04 , you can try the following APKs: https://github.com/opengisch/QField/pull/1905#issuecomment-841805399 -- a few library updates might have brought more speed. Let us know :)

**Comment by Crapaud04** [comment]
To follow up on the ticket, the new version is more stable with rasters the transition between zoom levels is smoother without white transition.
But with a VRT the loading is always 5 seconds.

On the other hand, I managed to get around the problem by using the Geopackage raster format with pyramid from qgis and this made everything much faster.

**Comment by nirvn** [comment]
@Crapaud04 , missed that reply. I'm glad you report QField is stabler and that you've found a raster dataset format that behaves better on phones. It's indeed the case that formats aren't all equally friendly to mobile devices :) 

OpenGIS.ch published a blog post a while back looking at the performance of a couple of formats: https://www.opengis.ch/2020/06/09/offline-wms-benchmarking-raster-formats-for-qfield/ -- that might be of help to you too.
