### ISSUE TITLE
sample qgis project

### ISSUE THREAD

**Issue by jaakla** [opengisch/QField#186]
To get quick idea what the app/qfield general can do it would be nice to have a generic sample QGIS project in working form, with a basemap layer and some data and one basic survey form. Current "get started" is quite difficult, I have used QGIS for years but never created forms for example and there is no detailed doc or video how to do that properly.

**Comment by jbostoen** [comment]
Just a basic project wouldn't really help, would it? 

I started playing with QField two weeks ago. The form creating was new to me to, but it was actually quite easy. A short tutorial could be nice, or more references on how to start with that. But once you know where to look, it's easy.

**Comment by geomondego** [comment]
Try to follow this slides http://opengisch.github.io/talks/qfield-workshop/#0 and explore the different options

**Comment by mbernasocchi** [comment]
@m-kuhn what do you think about this one? and adding a button on the welcome screen o open a demo mproject?

**Comment by m-kuhn** [comment]
sounds like a good idea to me.
does someone have a nice project that could be used for this?

**Comment by mbernasocchi** [comment]
just bear in mind that the data should be freely shareable

**Comment by signedav** [comment]
This is done.
