### ISSUE TITLE
Crash after: Opening of individual vector/raster datasets

### ISSUE THREAD

**Issue by gitgeo-bg** [opengisch/QField#1864]
[Short description of problem here]
QField version 1.9.3 (5457e7 v. 1.9.3)
Crashes on 1/ Open local file; 2/ Open recent Projects
Device Galaxy A5 (2017); checked again after device restart

### Reproduction Steps:

1. [First Step]
Open the application 
2. [Second Step]
Open local file (kml, shp, geojson)
3. [Other Steps...]
Open existing project

### Observed behavior:

program crashes with notice: "Qfield has stopped."

**QField version:

1.9.3 (5457e7 v. 1.9.3)
## Additional information:
The problem started after today update.
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
Can you attach a sample dataset here and expand on your steps to reproduce? Are you saying it crashes opening a project after opening a dataset in the same session?

**Comment by gitgeo-bg** [comment]
On Thu, 22 Apr 2021 07:28:11 -0700
Mathieu Pellerin ***@***.***> wrote:

> Can you attach a sample dataset here and expand on your steps to
> reproduce? 

that is the link to the files I tried to open, and app crashes:
https://we.tl/t-Pc7e1Px4TI

Steps: onen the app, then choosing Open local file, below "Welcome back
to QField". After this app crashes.

Also crashes when opening some previously used projects.


>Are you saying it crashes opening a project after opening
> a dataset in the same session?

I have to check this again.

Thanks for great app!

Cheers,
Ianko

**Comment by gitgeo-bg** [comment]
here are also some screen recording, that documents the crashes:
https://we.tl/t-xYogDW0mEl

greetings,

Ianko

-- 
--
*Ianko Gerdjikov*
*Dept. Geology and Paleontology*
*=============================*
Faculty of Geology and Geography
Sofia University "St. Kliment Ohridski"
15 Tzar Osvoboditel Blvd.
1504 Sofia, Bulgaria
phone: +359 2 9308 331 / 359 877 612679
e-mail: ***@***.***
skype: ian_ko

**Comment by nirvn** [comment]
@gitgeo-bg , thanks, the video is useful. Could you share the riverbank shapefile that crashed twice? Thanks

**Comment by gitgeo-bg** [comment]
Hi,

> Could you share the riverbank shapefile that crashed twice? Thanks
>
>
> The file is attached. I opened in QGIS, it was fine with projection etc.,
so probably no errors with that file.

cheers,

Ianko
-- 
--
*Ianko Gerdjikov*
*Dept. Geology and Paleontology*
*=============================*
Faculty of Geology and Geography
Sofia University "St. Kliment Ohridski"
15 Tzar Osvoboditel Blvd.
1504 Sofia, Bulgaria
phone: +359 2 9308 331 / 359 877 612679
e-mail: ***@***.***
skype: ian_ko

**Comment by nirvn** [comment]
@gitgeo-bg , sorry, I'm currently behind a very bad connection, the 134mb archive would take me ~1 hour to download. If possible, could you attach that single geojson file? 

Thanks.

**Comment by nirvn** [comment]
Also, if you are able to get a logcat of the crash, that'd help a lot. So far I've been unable to replicate the crash with more than a dozen datasets at hand.

**Comment by suricactus** [comment]
Hey, @nirvn these are the kml files only. Didn't manage to reproduce the crash with the desktop build.

[qfield_1864_dataset_crash.zip](https://github.com/opengisch/QField/files/6371878/qfield_1864_dataset_crash.zip)

**Comment by gitgeo-bg** [comment]
>
>
> Also, if you are able to get a logcat of the crash, that'd help a lot. So
> far I've been unable to replicate the crash with more than a dozen datasets
> at hand.
>
>
> logcat is here <https://we.tl/t-HZNyfLgESF>. (7 Mb) Hope this help. Still
having the same situation with the App, after last update.
cheers,

**Comment by nirvn** [comment]
Oh, I think I know what's happening. Did you ever report or witness crashes when QField had a changelog popup showing up?

By looking at the stacktrace I'm pretty sure the crash has to do with the app crashing whenever its trying to connect to an HTTPS server. In your case, it'd be the fetching of OSM tiles.

If your game, try this: save a blank project in QGIS, name it basemap.qgs (or basemap.qgz depending on your default), copy that into your phone's root /QField/ directory. What it'll do is QField will use that as basemap instead of OSM. It shouldn't crash then.
