### ISSUE TITLE
Support Android file sharing API beyond direct file lnk

### ISSUE THREAD

**Issue by xBcai** [opengisch/QField#1865]
https://user-images.githubusercontent.com/66826351/115817897-42236980-a42e-11eb-89a6-9cea8ceabe0d.mp4

**Comment by xBcai** [comment]
This problem exists in other apps opening files, I don’t know if it’s an example.

**Comment by nirvn** [comment]
It's indeed the case that not all apps well permit direct opening from their app to QField directly without saving on the device first.

That said, if you save that kml file onto your device (say in the download folder) and you then open it using QField's open local fille button, can you confirm that things work ok? It could be an issue with utf8 filenames.

**Comment by xBcai** [comment]
The same problem occurs when saving to the phone. It can be opened normally from the file manager, and cannot be opened after saving from the app to the device. I am not sure what is going on.

**Comment by nirvn** [comment]
Can you attach this KML sample here?

**Comment by xBcai** [comment]
https://user-images.githubusercontent.com/66826351/115977798-cfd99300-a5ad-11eb-8186-8c6f3f528e6f.mp4

**Comment by xBcai** [comment]
[河东村.kml.zip](https://github.com/opengisch/QField/files/6371098/kml.zip)

**Comment by nirvn** [comment]
@xBcai , in the second video, it's not working because you're not opening the file you saved in Download/WeChat, you used the recent project that links to the wrong "internal" wechat path. Use the [ open local file ] button and find the kml in Download/WeChat.

**Comment by nirvn** [comment]
![Screenshot_20210425-091544_QField](https://user-images.githubusercontent.comp/1728657/115978017-0069fe80-a5a7-11eb-83b6-3ace852ef4c8.jpg)

Works on my phone if I open it using QField's open file button or Amaze file browser.

**Comment by xBcai** [comment]
This is the case, both qfield and file manager can be opened, but other apps can't call it directly.

**Comment by nirvn** [comment]
@xBcai , good. That's a limitation at the moment. We need to implement handling of Android's file sharing, which relies on copying datasets onto a temporary directory. I've been inclined not to go down that path so far as people might not realize editing such a file would not be saved back when closing QField.

In any case, this could be transformed into a feature request: Support Android's file sharing API :)

**Comment by xBcai** [comment]
On the mobile side, editing is relatively small, mainly for viewing files, hoping to increase this function.

**Comment by xBcai** [comment]
I wonder if this function can be added in the next version? Waiting......

**Comment by nirvn** [comment]
@xBcai , this isn't actively pursued at this moment. It's a good candidate for a crowd funded campaign, or private funding :)
