### ISSUE TITLE
Issue when launching the export on qfield 

### ISSUE THREAD

**Issue by zakigates** [opengisch/QField#187]
Please I have a problem here. Every time I lanch  the export for QField,  I have this message in the log panel : 

`2017-11-03T13:45:48	1	Erreur lors de l’exécution de la requête : SELECT styleQML FROM layer_styles WHERE f_table_catalog='C:/Users/AlexSige/Desktop/packages/Export/171029_DataCollection - Export Alex/data.sqlite' AND f_table_schema='' AND f_table_name='meter20171017151052282' AND f_geometry_column='Geometry' ORDER BY CASE WHEN useAsDefault THEN 1 ELSE 2 END,update_time DESC LIMIT 1`

As I understood this error is in relation with the layer_styles table that I already have in my database. 
It doesn't bother the work but I want to get ride of it. 
If you know how tell me please. 
Cordially

**Comment by m-kuhn** [comment]
This concerns QFieldSync, right?

In any case, that's a QGIS issue, nothing related to QField at all. And I think I recently killed this message for QGIS 3, so in the mid-term this should be solved.

**Comment by zakigates** [comment]
I'm running on 2.18.13 and the latest version of qgis is 2.18.14

**Comment by m-kuhn** [comment]
Please report this upstream on the qgis issue tracker.
