### ISSUE TITLE
@snapping_results or variable problem

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/QField#1871]
@snapping_results or dealing with variables seem not to be running anymore.

I used the expression below to get feature infos of existing points. From Version 1.9.0 on it is not working anymore. Are there changes made relating to @snapping_result or dealing with variables.

```
with_variable(
  'first_snapped_point',
  array_first( @snapping_results ),
  attribute(
    get_feature_by_id(
      map_get( @first_snapped_point, 'layer' ),
      map_get( @first_snapped_point, 'feature_id' )
    ),
    'id_messtelle_objekt'
  )
)
```
### Reproduction Steps:

1. @snappingresult in placed in attribute form - default value
2. should pass information of an existing point to a new one

### Expected behavior:

get the @snapping_result

### Observed behavior:

not getting the @snapping_result

**QField version:**  1.9.0-1.9.3
## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes, last running 1.8.4
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by soester** [comment]
Many thanks for the quick fix and release! 🚀
