### ISSUE TITLE
PostGIS Sync Error with SDE

### ISSUE THREAD

**Issue by cnmassery** [opengisch/QField#1872]
A project was configured using two layers from a PostGIS database (sde schema) for offline use. When the project is then synced back the following error occurs: 

 Layer Survey Metadata : PostGIS error while adding features: ERROR: column "shape" is of type geometry but expression is of type st_geometry
             LINE 1: ...erage","survey_type","gdb_geomattr_data") VALUES (st_geomfro...
              ^
             HINT: You will need to rewrite or cast the expression.

**QField version:** 1.9.3

## Additional information:

This is the first time I have tried syncing data from out PostGIS database. It is created to work in a ESRI environment as well, so it uses PG_Geometry, not sure if that is the cause of this problem or not.

**Comment by nyalldawson** [comment]
Can you even edit data in qgis itself from an sde schema? I don't believe this is supported at all.

**Comment by cnmassery** [comment]
Nyall,

I believe you are correct, I was not aware of this as I typically just use QGIS for analysis and quick maps (no data editing). Thank you for clarifying and making it aware that this is not a bug with QField. I will close this issue and research possible solutions to creating a hybrid database that works with ESRI and QGIS. Thanks again!
