### ISSUE TITLE
Allow controlling layer visibility individually

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#188]
Right now, layer visibility can only be controlled by map themes.

Add a new option to activate / deactivate a layer instantly without having a predefined map theme available.

**Comment by saemiw** [comment]
related with this issue no? https://github.com/opengisch/QField/issues/59

**Comment by m-kuhn** [comment]
Correct, this one is just more specific

**Comment by gnerred** [comment]
+1

**Comment by saemiw** [comment]
This seems to work fine - thanks. It makes QField faster when not all points have to be rendered.
