### ISSUE TITLE
QField allow to add only a few new features in clayer with constraints

### ISSUE THREAD

**Issue by kluuboo** [opengisch/QField#1884]
QField does not allow to add more than 3-4 features to working layer with constraints: i have to end the editing mode, change to different layer, change back to  working layer and then start of editing: it allows me again to add 1-3 features, then i have to end editing/layer switching/start editing to be able to add 1-3 features, and so on.

Constraints are not simple "not null", but a bit more elaborated (if this attribute is this, then constraint is active;;; if another attributte is that then you dont have to enter values, etc..) I can upload QField project (this is my first github post, so im not sure if i have to put it here right now).

IMPORTANT: The layer does not act like that if there are no constraints, i cant identify which one is acting weird (there is about 10 constraints and default value calculations)...

Tested with geopackages and shapefiles.

**QField version:** 1.9.5 (5f66b7 v1.9.5)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Dont know (first use of layer with coinstraints)]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@kluuboo , please do upload your project, it'll help us replicate and investigate the issue.

**Comment by kluuboo** [comment]
Here is the zip of project and i added the screenshot of adding the new feature after i added 2-3 features - that is the problem - im not able to add any data.

The workflow in general is:
1. Select the required feature in "stromy_geopackage.gpkg" and enable editing of particular feature OR  or enable layer editing and add feature
2. fid is not important (shp version even dont have fid attribute and does the same)
3. chose value for "mazat" (mazat= erase - just attribute value, not the physical deleting!).
 if mazat = "ano" (yes), no other data are necessary - no mattere how many features i add - if i chose mazat = 'ano', i can add any amount (it will also hide the other attributes in form)
 if mazat = "nie" (no), i must fill other attributes values  (it will also show the other attributes in form). After adding 2-4 new features it does not show any attributes so im not able to set "mazat"  and thus im not able to see and fill attributes so dhe constraints prevent me from saving the newly added feature.

I thought there is problem in my constraints, but they are working properly - they fill the default data, hide/show attributes or trigger the constraints in given scenarios. They just seem to affect the app after those first 2-3 new features...

**NOTE:** The datasets are reduced (layer stromy_geopackage.gpkg has originally >16k features, hotove_stromy_poloha.gpkg >7k features, layer ulohy.gpkg is about 20 features, layers zilina.shp and zavodie.shp have >100 features each) - no matter the initial count or if the attributes of stromy_geopackage.gpkg are partially filled for some features, still the same.

Thanks for your help in advance, i appreciate it ;)


[__MAZAT__.zip](https://github.com/opengisch/QField/files/6439090/__MAZAT__.zip)

**Comment by nirvn** [comment]
@kluuboo , please give the APKs from PR #1888 a try to confirm your issue is gone. Thanks for the report and test project, way to go.

**Comment by kluuboo** [comment]
It worked, you are awesome!!! Thanks a lot!!!
