### ISSUE TITLE
Main window not visible on windows

### ISSUE THREAD

**Issue by ntrip6** [opengisch/QField#1885]
What are the steps for installing the Windows build?

Currently running 64 bit Windows 10 (Build 20H2)
1. Downloaded Qfield latest dev build from
[(https://nightly.link/opengisch/QField/workflows/windows/master/QField-dev-Release.zip)]

2. Unzipped C:\Program Files\QField-dev-Release\bin\

3. Ran C:\Program Files\QField-dev-Release\bin\qfield.exe

Result is only a text window that reads:
        - 'VirtualXPath'        [XML Path Language - XPath]
        - 'VirtualXPath'        [XML Path Language - XPath]
qrc:/qml/qgismobileapp.qml:1144:9: Unable to assign [undefined] to GnssPositionInformation
qrc:/qml/OverlayFeatureFormDrawer.qml:80:13: Unable to assign [undefined] to GnssPositionInformation
qrc:/qml/qgismobileapp.qml:2259:5: Unable to assign [undefined] to GnssPositionInformation

**Comment by m-kuhn** [comment]
The installation steps are correct.
We once had a similar issue and solved it by deleting the stored window position from the windows registry. @mbernasocchi or @lindacamathias do you remember the registry key of this?

**Comment by emarmolejo** [comment]
I made the same instalation as R ntrip6 in a tablet Currently running 64 bit Windows 10 

the result messaje is text window:
- 'VirtualXPath' [XML Path Language - XPath]
- 'VirtualXPath' [XML Path Language - XPath]
qrc:/qml/qgismobileapp.qml:1144:9: Unable to assign [undefined] to GnssPositionInformation
qrc:/qml/OverlayFeatureFormDrawer.qml:80:13: Unable to assign [undefined] to GnssPositionInformation
qrc:/qml/qgismobileapp.qml:2259:5: Unable to assign [undefined] to GnssPositionInformation

Do you have any solution for this?

**Comment by m-kuhn** [comment]
![image (3)](https://user-images.githubusercontent.com/588407/135812899-788c200e-6926-4a2d-ac03-32ed2e8f8c86.png)

Workaround: open `regedit` go to `HKEY_CURRENT_USER/SOFTWARE/OPENGIS.ch/QField`, delete x, y and width

**Comment by m-kuhn** [comment]
@lucienicolier is it possible that you normally do have an external screen attached and this time you did not?
The `x` value looks very large, we could possibly sanitize this value.

**Comment by lucienicolier** [comment]
@m-kuhn Yes I do normally have 2 externals screens
