### ISSUE TITLE
Crosshair missing in 0.10.2

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#190]
With the update to 0.10.2 the crosshair (used to choose the exact position of a vertex to be digitized) disappeared. I can digitize a point but I simply don't see what coordinates im digitizing because of the missing crosshair.

The crosshair is visible on 0.10.1

**Comment by gnerred** [comment]
I confirm...

**Comment by saemiw** [comment]
we checked on 2 tablest (same model) and 2 different qgs-projects

**Comment by m-kuhn** [comment]
will have a look soon!

**Comment by m-kuhn** [comment]
Is this still an issue?
