### ISSUE TITLE
Project optimization for QField

### ISSUE THREAD

**Issue by arkanoid87** [opengisch/QField#1901]
While trying to reduce memory usage and improve speed in qfield for a specific qgis project, I've found no specific hints on how qfield prefers the input data.
I'm following general rules that would be valid for every qgis project, but a developer view on this might be beneficial as I've no clue if qfield rendering works as the qgis one and I've found no benchmarks and no obvious benefits during initial experiments.

Some examples:

- What is the preferred/faster vector data container?
- How is vector data loaded?
- How to correctly handle large amount of vector data?
- What is the preferred/faster raster data container? This page partially gives an answer https://qfield.org/docs/data-formats/index.html:
```
gdal_translate --config OGR_SQLITE_SYNCHRONOUS OFF -co  APPEND_SUBDATASET=YES -co TILE_FORMAT=WEBP -a_srs EPSG:21781 -of GPKG raster.tif raster.gpkg
gdaladdo --config OGR_SQLITE_SYNCHRONOUS OFF -r AVERAGE raster.gpkg 2 4 8 16 32 64 128 256
```
- Is WEBP encoding the way to go?
- Will more pyramids be beneficial on on ram consumption on device?
- Is tiling beneficial and is WEBP the most optimized tiling option available?

I infer that GPKG may be the best data format for both raster and vector layers, but what about GPKG itself:
- should I use one GPKG per layer?
- should I use different GPKGs for different geographical regions?
- should I split raster and vector data in different GPKGs?
- should I merge all data into a single large GPKG?

I'm just looking for general considerations, thanks.

**Comment by signedav** [comment]
Hi @arkanoid87 our college @lucienicolier made once some interesting research https://www.opengis.ch/2020/06/09/offline-wms-benchmarking-raster-formats-for-qfield/ It might be interesting for you.

**Comment by signedav** [comment]
@arkanoid87 feel free to reopen if there are more questions.

**Comment by arkanoid87** [comment]
Failed to respond, but I used the linked information to optimize my project. Thanks!
