### ISSUE TITLE
Multiple columns in a group

### ISSUE THREAD

**Issue by MMR100** [opengisch/QField#191]
Splitting a form into various tabs is well working but It would also be interesting to split in columns each group in a container (as we can do in QGIS)

Here is a screenshot in QGIS
![capture qgis](https://user-images.githubusercontent.com/26409106/32605011-278f1728-c57e-11e7-96c8-ec48ed348eac.JPG)

Here is a screenshot in QFIELD with only one column

![capture qfield](https://user-images.githubusercontent.com/26409106/32605013-280b8650-c57e-11e7-8d2e-dbb6d46e9d7f.png)

**Comment by MMR100** [comment]
Hello Matthias, I am absolutely not a programmer but when I look to the changes done to the code it seems to be more related to the previous issue #190 rather than this one. Sorry in advance if my reaction is not appropriate.

**Comment by m-kuhn** [comment]
I think having multi column layouts is a valid feature request and would be really nice to have one day, we just need someone to step up to implement or fund this.

#190 was about a bug introduced in the latest version of QField with the crosshair on the map canvas, so I think it's totally ok to keep this open.

**Comment by jfbourdon** [comment]
I'm also looking foward to the possibility of using multiple columns in a group. Can I have any hints on where and what to look for in the code? Depending of the scope of modifications needed, the organization for which I work may be able to sponsor this or do the implementation in-house... maybe...
