### ISSUE TITLE
Vector layer symbology categorized by field value is not correctly displayed in layer panel

### ISSUE THREAD

**Issue by lindacamathias** [opengisch/QField#1913]
Vector layer symbology categorized by field value of an integer field is not correctly displayed in the layer panel. In QField all the categories show the symbol of the first category instead of their own symbols.  In map canvas it's displayed correctly. 

### Reproduction Steps:

1.. create a vector layer (e.g. point)
2.  add an integer field (in example called: "whh")
3. symbology -> categorized: symbol: a simple point symbol with color, value: field "whh" (see screenshot)
4. add categories (1, 2, ..) as shown in screenshot and use a color ramp (or random colors) to create different symbols for each category
(5. create some random features and add a category number in field "whh")

### Expected behavior:

Symbology in QField it's shown according to the symbols in QGIS

### Observed behavior:

Symbol of the first value is taken for all values (see screenshot) in layers panel
(works properly in map canvas)

screenshot QGIS:
![image](https://user-images.githubusercontent.com/77726342/118510198-0465e800-b731-11eb-8bf5-b6e9db022ec6.png)

screenshot QFIELD:
![image](https://user-images.githubusercontent.com/77726342/118510890-ae457480-b731-11eb-8401-c8695d6664a1.png)

**QField version:** master-dev (cae251)

**Comment by nirvn** [comment]
Cause: absence of unique labels for your items.

Known limitation. Would be worth addressing.

**Comment by mathewpetro** [comment]
Hi lindacamathias, I have the same problem, I have defined my layer style in qgis 3.18.3 with categorized option and tested it with qfield Release v1.9.5. Everything works fine except the symbology has changed to other styles which I didn't define through the qgis, I tried even to embed the layer style into the Geopackage but did not work out, see the attachments
Thanks

![qgis](https://user-images.githubusercontent.com/10742374/119768104-bdaa8780-bec0-11eb-8c0d-9dcda82a3377.png)
![qfield](https://user-images.githubusercontent.com/10742374/119768114-c26f3b80-bec0-11eb-854f-e5dfa5232050.jpg)

**Comment by nirvn** [comment]
@mathewpetro , those are font markers right? You'll need to copy the font(s) ttf files on your mobile device for those to work properly. In the QField/fonts directory.

**Comment by mathewpetro** [comment]
@nirvn Thank you for your reply, Yes!, they are font markers, where do I find this ttf and otf in qgis , I tried to search from the qgis I found one file in 'C:\OSGeo\apps\Qt5\qml\QtQuick\Dialogs\qml' and multiple files from 'C:\OSGeo\apps\Python37\lib\site-packages\matplotlib\mpl-data\fonts\ttf'(particularly ttf), I copied everything to QField/fonts but didn't, any help will be appreciated!

**Comment by nirvn** [comment]
Those fonts would be in your windows fonts folder.

**Comment by mathewpetro** [comment]
@nirvn!, Thank you very much, it has worked though, I have to copy the entire folder from the windows, I couldn't figure out what exactly containing my font markers. and the folder has 264 files, which will make my device misbehave. I would wish to copy only the font that containing what I need. Thank you in advance.

**Comment by mathewpetro** [comment]
@nirvn Thank you very much, It has worked much appreciation!
Thanks

**Comment by nirvn** [comment]
@mathewpetro , happy to hear it's working. Happy field mapping! :)
