### ISSUE TITLE
Offline editing python error

### ISSUE THREAD

**Issue by Pierwul** [opengisch/QField#1922]
Hi, I can not use offline editing anymore for a project. 
This problem also happen in other version of QGIS.
I don't have this problem with other files and project.
I'm on QGIS 3.14.7

I have already tried to delete the "interet" column and to delete the "interet" layer but i still have trouble with python.

I have no python errors if i put the qfield settings on "copy" instead of "offline editing".

Here are the screens of the python errors

![erreur1](https://user-images.githubusercontent.com/73639483/119375123-b6199180-bcba-11eb-801e-a688a17bbd57.PNG)
![erreur2](https://user-images.githubusercontent.com/73639483/119375129-b9ad1880-bcba-11eb-9fff-153fbd9d8408.PNG)

**Comment by signedav** [comment]
At least the second one should be fixed with the next QFieldSync Release, right @suricactus ?

**Comment by suricactus** [comment]
Yes. I think I can fix the first one too.

**Comment by Pierwul** [comment]
Thanks for the quick answer ! Nice to hear that it should be fixed in the next QFieldSync :) 
Do you know if i can do something to make these problem disappears ? My project worked for a long time but now i can not create it on offline editing.

**Comment by suricactus** [comment]
@Pierwul can you try the latest (non-experimental) release of QFieldSync and confirm the issue is gone now?
