### ISSUE TITLE
Moving point features opens vertex tool

### ISSUE THREAD

**Issue by monticola2** [opengisch/QField#1923]
Moving an existing point feature most often (not always) opens the vertex tool and requires a few seemingly unnecessary clicks.

### Reproduction Steps:

1. Create a feature in a point layer.
2. Select the feature and click edit geometry.
3. Try moving the point to a new location.

### Expected behavior:

Moving the canvas moves the feature to a new location. Then simply click the toggle in the lower right corner to save. It actually works like this from time to time with no clear pattern.

### Observed behavior:

Most of the time, moving the canvas moves the crosshair only and the vertex tool opens. You then have to click on the "..." toggle in the lower right corner which then switches to the vertex option. Then you can move the point when moving the canvas. But to save it to the new location, you have to click on the toggle on emore time to get the option to check the save tick (see video).  So, it works but it is a but cumbersome.

### Screenshots and GIFs

https://user-images.githubusercontent.com/64013745/119400646-c0e41e80-bcda-11eb-90bf-aec6f2ef79db.mp4

**QField version: v1.9.5

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Not sure about v1.8.x, happened in all v1.9.
* Problem can be reliably reproduced, doesn't happen randomly: Well, no. Sometimes it works, most of the time not.
* Problem happens with all files and projects, not only some files or projects: Yes.

**Comment by nirvn** [comment]
@monticola2 , a move feature functionality has been implemented for the upcoming QField 2.0. You can test it by download the latest APKs in this PR (https://github.com/opengisch/QField/pull/2146) or wait for it to appear in the next round of betas on google play store.
