### ISSUE TITLE
$id no longer works

### ISSUE THREAD

**Issue by monticola2** [opengisch/QField#1924]
$id no longer works. Not much more to say...

**QField version: 1.9.5

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: I think since 1.9
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Thank you for opening this issue. Can you add more details, where `$id` isn't working and if possible share a project file?

**Comment by monticola2** [comment]
Here's a simple project with a shapefile:
[QField_id_test.zip](https://github.com/opengisch/QField/files/6538505/QField_id_test.zip)

id is always "0". I have also experienced this with geopackage.
Actually, I just tested this in QGIS 3.18.3  and it didn't work there either; all values are 0. So this might be a QGIS issue? (Or user error..., am I doing something wrong?)

**Comment by m-kuhn** [comment]
Can you add a short description where in the project `$id` is used.

**Comment by meyerlor** [comment]
maybe this is related to your problem (and helps to solve it?): https://github.com/qgis/QGIS/issues/37656

**Comment by monticola2** [comment]
Sorry @m-kuhn for being so unspecific. $id is the default value for all fields.

Thanks @meyerlor! I will try the suggested approach.

Anyway, I am closing this issue as it is not QField related.
