### ISSUE TITLE
Generating new uuid's (primary keys) while importing from QField breaks (1:n relation) to child features

### ISSUE THREAD

**Issue by geomoes** [opengisch/QField#1927]
We have a QGIS project with a parent and two child layers (1:n relation) all stored in PostGIS. The parent primary key is a uuid (no default value). Both child layers have as foreign key an uuid field. Foreign key constraints are set properly in PostGIS.  In QGIS relations are set and the parent uuid has an uuid() function in the attribute field set as default. 

In QGIS we can digitize new parent polygons, add multiple childs and save everything back to the database.
When using the project in QField we are able to digitize new polygons and add child layers. When trying to sync back to QGIS only the parent polygons are imported and we run in the following error:

`insert or update on table "parents" violates foreign key constraint "child1_fk" 
DETAIL: Key (uuid)=(24fdfc80-2f1e-44fb-8dd8-d492901c37de) is not present in table "parents".`   

This behavior is correct.  When I look in the attribute table of the parent layer, all the uuid's are new ones. 
So non of the children can be imported since they all keep the old uuid's from QField.

We followed the example in '[add a series of pictures to a feature](https://qfield.org/docs/prepare/add-1-n-pictures.html)'  but keep struggling with this problem. Did we miss something?

QGIS 3.16.7
QField 1.9.5 (5f66b7v1.9.5)

**Comment by geomoes** [comment]
We did a few more tests and we unchecked the "apply default on update" on the attribute configuration of the UUID field of the parent layer. Now at least one of the child layers is synced to PostGIS. For the second child layer we still get the same error. We don't see a difference in the configuration of the second layer, so we cannot understand the different behavoir.  

We checked the data.gpkg from QField and there all the UUID's match, means the generated parents UUID's are the same as the related children UUIDs. After synchronisation of the QField data.gpkg to QGIS the correct UUIDs are stored in the PostGIS database. Only the second child layer cannot be imported. So it seems that this is an issue of the order how the data is synced to the database. When QFieldSync tries to import a child layer before the parent layer exists, the import fails. It seems that this could be the source of the problem. So it looks like beeing a bug in QFieldSync.

**Comment by m-kuhn** [comment]
See also https://github.com/opengisch/qfieldsync/issues/249

**Comment by suricactus** [comment]
Check if QGIS 3.22 fixes it for you https://github.com/qgis/QGIS/pull/44636

**Comment by turtlemap** [comment]
> Check if QGIS 3.22 fixes it for you [qgis/QGIS#44636](https://github.com/qgis/QGIS/pull/44636)
I just experienced the same issue in Qgis LTR 3.22.8 / QFIELD 2.8.4
As @geomoes commented on May 28, 2021, a wrong insert order violate foreign key
