### ISSUE TITLE
"No feature at this position" not working properly

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#193]
When identifying a feature (by tipping on the map) qfield 0.10.3. shows a message "no feature at this position" even if there are features at the position (shown by the identify window).
![screenshot_2017-11-16-10-40-54](https://user-images.githubusercontent.com/20398621/32884716-885ae7a2-cabb-11e7-9647-173ef92020d3.png)

**Comment by signedav** [comment]
I think this is not the case anymore.
If it is, feel free to reopen @saemiw
