### ISSUE TITLE
Error - 'Could Not Save changes Rolling Back'

### ISSUE THREAD

**Issue by mattpitts74** [opengisch/QField#195]
I have been testing the latest version of QField on a onePlus 3T running Android 7.1.1

I have used the Qfield Sync plugin to package up my project with consists of a geopackage raster basemap and a geopackage point dataset. 

I copied these over to the phone and loaded the QGIS project and started to test digitising, which appeared to work correctly. 

I noticed the small bell in the top right corner of the screen which when I click on it gives the following error 

'Could Not Save changes Rolling back' 
Commit Errors
Error 1 Features Not Added - Gemetry Type is not compatible with the Cur/ The rest of the error is cut off by the screen

But this error only seems to occur when I am trying to create a point at the actual GPS location!!

**Comment by m-kuhn** [comment]
Can you check the type of the layer (in QGIS), is it point or multipoint or something else?

**Comment by mattpitts74** [comment]
It's a point dataset

**Comment by m-kuhn** [comment]
Note to self: Might be an issue with PointZ vs. Point in this case

**Comment by mattpitts74** [comment]
I'm out in the field testing right now, it's working perfectly with polygon and line layers so far. 

What do suggest I do about point layers then?

**Comment by m-kuhn** [comment]
If you have the possibility to create some different layers to test with (i.e. if you have a QGIS at hand), one with Z value coordinates (PointZ), and a flat one with (Point), that would be a good feedback.

**Comment by mattpitts74** [comment]
I've just finished and heading back to the office to check results, I'll do some more testing and let you know. Where should I log feature requests?

**Comment by m-kuhn** [comment]
Just open new issues in this repository, and contact us by email if you'd like us to work on them.

**Comment by m-kuhn** [comment]
Fixed in https://github.com/opengisch/QField/pull/246
