### ISSUE TITLE
Impossible to check with a small screen. (Start monitoring)

### ISSUE THREAD

**Issue by RAFALCO** [opengisch/QField#1958]
With a small screen (5" samsung sm g390f) it is not possible to check or uncheck "digitize vertex only when both conditions are met" in tracking parameters ". the text is off screen
there is no problem on a larger screen. (8" tab activ 3)

default on qfield 1.9.5 and 1.9.6
Problem happens with all files and projects.
Problem can be reliably reproduced: Yes
doesn't happen randomly: Yes

**Comment by suricactus** [comment]
Thanks for reporting the issue. Adding a screenshot would be very nice.
