### ISSUE TITLE
show feature count of layer when "show feature count" in qgis is enabled

### ISSUE THREAD

**Issue by lindacamathias** [opengisch/QField#1961]
show feature count of layer when "show feature count" in qgis is enabled

### Expected behavior:
show feature count on layer when it's enabled in qgis. 
screenshot qgis: 
![image](https://user-images.githubusercontent.com/77726342/120837151-a9bcf080-c566-11eb-8a75-feadb8d8e392.png)

### Observed behavior:

feature count per category is shown but total feature count of layer is missing 
screenshot qfield:
![image](https://user-images.githubusercontent.com/77726342/120837496-0d471e00-c567-11eb-8e20-3e21916108cc.png)

**QField version:** master-dev

**Comment by nirvn** [comment]
Fixed, woupidou.
