### ISSUE TITLE
Categorized Renderer layer crash QField

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#199]
I'm trying to expand the layer with Categorized Renderer style layer properties, QField crashes.
QField 0.10.4
Android 7.0, 5.0
Device: Blackview BV6000s, sony xperia tablet z1

previous qfield version (0.10.1) works fine

**Comment by m-kuhn** [comment]
What is e "expand"?

**Comment by giedrioks26** [comment]
> What is e "expand"?

that's it drop down categorized layer
On QGIS called "expand"
![ekranvaizdis_2017-12-25_10-39-05](https://user-images.githubusercontent.com/6436791/34336552-bc442088-e960-11e7-8e1c-87fa62f7790c.png)

**Comment by m-kuhn** [comment]
Can you extend a minimal sample project? E.g. the one here (no need to include rastras)

**Comment by giedrioks26** [comment]
[categorized.zip](https://github.com/opengisch/QField/files/1585813/categorized.zip)

**Comment by giedrioks26** [comment]
In QField double touch on layer

**Comment by gaby-h** [comment]
version 0.9.10, displayind categorized symbols also works, no crash

**Comment by giedrioks26** [comment]
I think this is related to the new feature in version 0.10.4 - "Change layer visibility on the fly"

**Comment by signedav** [comment]
Fixed in Version 0.10.5 (in Playstore for Beta-Testers or [here](https://github.com/opengisch/QField/releases/tag/release-0.10.8_5))

**Comment by giedrioks26** [comment]
works perfectly. Thank you!
