### ISSUE TITLE
Window does not fit the information about the coordinates

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#20]
Half of the coordinates is not visible. Displays the coordinates (WGS84), but should be EPSG: 3346 (Lithuania TM).
![screenshot_2015-12-05-21-27-17](https://cloud.githubusercontent.com/assets/6436791/11609774/b0a3f31a-9b98-11e5-831e-cd0104cda469.png)

Sony xperia tablet z 1, Android 4.3

**Comment by gnerred** [comment]
Same problem on Samsung Galaxy Note 2014 edition 10.1 (SM-P605)
