### ISSUE TITLE
QField does not edit the sqlite layer

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#200]
When you load a sqlite layer with the "Add Vector Layer" on QGIS into a project, QField does not edit that layer. Writes: 'Could not Save Rolling Back'.
When the layer is loaded with the "Add Spatielite Layer", everything works fine.
We are looking for this problem for two days :)

exemple project:
[bad_layer.zip](https://github.com/opengisch/QField/files/1588994/bad_layer.zip)

**Comment by suricactus** [comment]
Is this stil the case? Seems that current master is no longer suffering from this problem.
