### ISSUE TITLE
gnss_used_satellites is not available

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#2007]
1. connect an external antenna and set it up using bluetooth
2. create a project with a default value of `array_to_string(@gnss_used_satellites)` for a string field
3. collect points
4. information is missing

QField 2.0, Beta 1

**Comment by geckeau** [comment]
I get the following error
_Default value expression for digitizing_logs:gnss_used_satellites has evaluation error: Cannot convert" to array_

**Comment by geckeau** [comment]
@nirvn @m-kuhn Any chance that this will get fixed before next week?

**Comment by m-kuhn** [comment]
As far as I can see, this needs some in depth investigation with a device to see if the device doesn't deliver the data, if qgis doesn't extract the data or if qfield doesn't properly handle the data. There are no immediate plans to work on this.

**Comment by nirvn** [comment]
Implemented during the positioning framework revamp.
