### ISSUE TITLE
Can't edit text fields since latest upgrade to version 2.0.1

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#2015]
Since the latest update,  I can't add text in (or edit) text fields (multiline?) in the field (in my case, the fields 'Memo' and 'ToDo' > see printscreens).
In the QGis project or in the Input app, there is no problem...
Any other users with the same problem?

QField version: "2.O.1" (f3b43f v2.0.1)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [I think so]
* Problem happens with all files and projects, not only some files or projects: It happens in the two mobile projects I have and in different layers.

![Schermafdruk_2021-06-17_20-11-57](https://user-images.githubusercontent.com/57868975/122451585-a08d4400-cfa8-11eb-9ac0-6434056ed590.png)
![Screenshot_20210617-175658](https://user-images.githubusercontent.com/57868975/122436310-0245b200-cf99-11eb-866d-d27018f8bc15.jpg)
![Screenshot_20210617-175902](https://user-images.githubusercontent.com/57868975/122436308-01ad1b80-cf99-11eb-9935-3013bddaabc8.jpg)
![Screenshot_20210617-180711](https://user-images.githubusercontent.com/57868975/122436304-01148500-cf99-11eb-854e-0d4f3451b4ee.jpg)

**Comment by Patoow** [comment]
I've the same problem.  Impossible to enter text in field.  I've trying with a external Keyboard but the problem seems that The field can't be change.  This problem apeart with dthe version : "2.0.1(f3b43f v2.0.1)

**Comment by BoswachterMarc** [comment]
I just reproduced the problem by setting up two text fields in a small project. One text field with length '0', and one with length '100'. In both ways I can't add anything in those fields!

![afbeelding](https://user-images.githubusercontent.com/57868975/122546730-8a769680-d02f-11eb-96ac-5a56922e9ff9.png)

**Comment by nirvn** [comment]
The regression has been fixed already, a new beta should be out soon, stay tuned.

**Comment by Isaacson33** [comment]
> The regression has been fixed already, a new beta should be out soon, stay tuned.

Any idea what sort of timescale 'soon' might be? I've got a couple of surveys lined up and it would be great to know if I need to shift all my survey tools to another platform (temporarily, of course!) or if I can just postpone them.

**Comment by nirvn** [comment]
@Isaacson33 , the latest non-beta version (1.9.6) isn't impacted by this regression. Feel free to revert to that until the next 2.0 beta is out.

**Comment by Isaacson33** [comment]
> the latest non-beta version (1.9.6) isn't impacted by this regression. Feel free to revert to that until the next 2.0 beta is out.

Thanks. I couldn't work out how to _stop_ being a beta tester so the only version Google Play will offer me is 2.0.1, but I downloaded the latest unstable instead (with the fix) and it seem stable enough to do what I need over the next few days, so that will do for now, unless I can get hold of 1.9.6 in the meantime.

**Comment by m-kuhn** [comment]
@nirvn is this fixed?

**Comment by nirvn** [comment]
Correct

**Comment by BoswachterMarc** [comment]
Hy, I see there is a new update 2.0.2 but I didn't get it automatically  although I am a beta user 🤔
![Screenshot_20210627-105728](https://user-images.githubusercontent.com/57868975/123538902-41ad9480-d737-11eb-8c75-042562ca5f28.jpg)
