### ISSUE TITLE
Credential Popup

### ISSUE THREAD

**Issue by ngulesanlar** [opengisch/QField#202]
Can we use login popup for secured WFS layers in Qfield?

**Comment by m-kuhn** [comment]
Not yet, but it would be a great feature to implement!

**Comment by ngulesanlar** [comment]
Yes it would be great. 
I'm trying to use something like this:
"http://username:password@mydn.com/geoserver/......."
and store this user name and password in the qgs project, but qfield throws 
"Layer extend reported by the server is not correct. You may need to zoom again..."
I must use wms layers with username/password security.
Is there any way to do this?
Thanks.

**Comment by m-kuhn** [comment]
It [should be possible according to this gis.se answer](https://gis.stackexchange.com/a/135956/9839), but nothing that I could comment on.

A form to ask for login credentials will be a (desirable) new feature.

**Comment by faibistes** [comment]
Not only that, we should be able to enter db credentials for db-based layers

**Comment by signedav** [comment]
Implemented here #608
