### ISSUE TITLE
Two anomalies

### ISSUE THREAD

**Issue by xBcai** [opengisch/QField#2027]
The latest version of qfield (2.0.2) displays the update interface every time it is opened (if the update interface cannot display the updated content), and "invalid map settings" is displayed in the information log no matter what file is opened.

**Comment by xBcai** [comment]
![IMG_20210626_132922](https://user-images.githubusercontent.com/66826351/123503013-d1ddd200-d682-11eb-9088-43a4dcbdedaa.jpg)

**Comment by nirvn** [comment]
@xBcai , can you try to further explain this part:

> displays the update interface every time it is opened (if the update interface cannot display the updated content)

I can't understand what you are hinting at here. A photo / screencast is most welcome :) 

As for the (harmless but irritating) invalid map settings message, it's been taken care of.
