### ISSUE TITLE
Relational value in form is not working 

### ISSUE THREAD

**Issue by geogeek11** [opengisch/QField#203]
in the promotional video of QField it seems that this feature is working or it was working, i've tested using these steps:
*Create qgis project with relational value.
*Export project using QField Sync, when i opened with qgis the result project relational value did not work, so i corrected the problem by ressiting relational value,.
*Copy the project folder to the smartphone, then open using QField.
*Select digitize mode, add new feature, relational value did not work in QField.

Any kind of help is welcome, any QField version where this feature is working or any kind of hack.

I'm using QField (0.10.4)

offline Qgis project is attached 
 [t5.zip](https://github.com/opengisch/QField/files/1608887/t5.zip)

**Comment by ngulesanlar** [comment]
I did the same mistake at first:)
Here is the link for the supported form objects.
http://www.qfield.org/docs/project-management/vector-layers.html#forms-and-fields
 You can use "map value"
it works fine for me.

**Comment by m-kuhn** [comment]
...or realation reference

**Comment by signedav** [comment]
The value relation widget is implemented #600
