### ISSUE TITLE
Checkbox "show on map" unchecked on QField

### ISSUE THREAD

**Issue by lucienicolier** [opengisch/QField#2030]
I did an export by QFieldSync of a project. When I open it in QGIS everything is checked and visible but when I open it in QField the "vue signal" "show on map" is unchecked

### Reproduction Steps:

1. Open the project in the zip file
2. Check the layer "Vue signal (symbologie)

### Expected behavior:

The checkbox "show on map" of layer "Vue signal (symbologie)" should be checked

### Observed behavior:

The checkbox "show on map" of layer "Vue signal (symbologie)" is unchecked

### Screenshots and GIFs

[signalo_export.zip](https://github.com/opengisch/QField/files/6742109/signalo_export.zip)

**QField version:** "master-dev" (107e26

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by signedav** [comment]
Quick test on pc run of e8de88b86250abcd2537dc942259ac571e612b52 (two weeks old master) leaded to the expected (correct) behavior. Do you have the same error in "older" QField versions (like eg. 2.0.1 Beta 2)?

Can you reproduce that with any other project @lucienicolier ?

**Comment by lucienicolier** [comment]
@signedav 
I tested in QField 2.0.2 (1ff4cf v2.0.2) and I get the same issue. 

No, I couldn't reproduce that with another project.

**Comment by nirvn** [comment]
@lucienicolier , I can't replicate over here. That is, when opening the attached project in QGIS, the vue signal layer visibility is also toggled off, so both QGIS and QField behave the same here. If I toggle visibility on in QGIS, and save the project, that layer is also visible when subsequently opening the saved project in QField.
