### ISSUE TITLE
Expose processing algorithms

### ISSUE THREAD

**Issue by nyalldawson** [opengisch/QField#2031]
I'm sure I'm not the only one who'd love to buffer, offset, and run other spatial analysis tasks on my mobile 😁

This could be a killer feature -- I digitise a line (say a river bank), then buffer it out by a certain distance to obtain the mandated offset trigger area for the waterbody.... Then proceed to survey the area inside the result! Mmmm tasty....

**Comment by m-kuhn** [comment]
Thanks for raising this. It has been sitting in the back of my head for a long time.

I can see a couple of ways how this could be integrated, is it one of these approaches or yet another workflow you are thinking of?

 - Completely flexible, you can run and parametrize any algorithm. Whenever you added a new river line and run the "buffer" alg a new layer is created (opens the question, how much configuration of this new layer do we need to be able to do from within qfield)
 - Preconfigure (feature based) algs to upsert waterbodies when riverline is added / changed / (removed)
 - Preconfigure (feature based) algs to be run manually from a feature (identify river line -> hamburger menu -> "buffer")

**Comment by nyalldawson** [comment]
@m-kuhn 
> Completely flexible, you can run and parametrize any algorithm. Whenever you added a new river line and run the "buffer" alg a new layer is created (opens the question, how much configuration of this new layer do we need to be able to do from within qfield)

This is what I had in mind. Basically I trigger the tool from some menu, pick the input layer from layers in the project, and then the resultant layer gets saved as a gpkg alongside the project and automatically added to it. (Although now I say that, I realise that there's complications even with that... as a polygon layer would need to be added below lines, etc). 

> Preconfigure (feature based) algs to upsert waterbodies when riverline is added / changed / (removed)

Do you mean like a type of "virtual layer" which responds automatically to changes in the source layer? If so, it's an interesting idea! I guess with this you'd have to preconfigure the "virtual processing layer" on the desktop in advance? 
 
> Preconfigure (feature based) algs to be run manually from a feature (identify river line -> hamburger menu -> "buffer")

Also an interesting idea, but probably the trickiest of the 3 to implement from a UI perspective.

My initial thoughts were purely to (1), as it would give a huge amount of flexibility for conducting analysis in the field. I mean, as a spatial geek I'd love it if I could directly perform these kinds of operations on my mobile, so when someone asks "how much of my backyard is covered by this easement?" I can give them the correct answer immediately :laughing: 

(...and I'm sure that either yourself or @mbernasocchi has asked themselves sometime in the past if the bike ride your mid-way through follows a simple-features topologically valid path, or if their ride has been subject to self intersects :wink: )

**Comment by m-kuhn** [comment]
> @m-kuhn
> 
> > Completely flexible, you can run and parametrize any algorithm. Whenever you added a new river line and run the "buffer" alg a new layer is created (opens the question, how much configuration of this new layer do we need to be able to do from within qfield)
> 
> This is what I had in mind. Basically I trigger the tool from some menu, pick the input layer from layers in the project, and then the resultant layer gets saved as a gpkg alongside the project and automatically added to it. (Although now I say that, I realise that there's complications even with that... as a polygon layer would need to be added below lines, etc).

If this, it could be integrated into the locator bar (which we ordinarily call "search"). And then all the questions about data management and organisation will need to be tackled.

> 
> > Preconfigure (feature based) algs to upsert waterbodies when riverline is added / changed / (removed)
> 
> Do you mean like a type of "virtual layer" which responds automatically to changes in the source layer? If so, it's an interesting idea! I guess with this you'd have to preconfigure the "virtual processing layer" on the desktop in advance?

Exactly.

> 
> > Preconfigure (feature based) algs to be run manually from a feature (identify river line -> hamburger menu -> "buffer")
> 
> Also an interesting idea, but probably the trickiest of the 3 to implement from a UI perspective.
> 
> My initial thoughts were purely to (1), as it would give a huge amount of flexibility for conducting analysis in the field. I mean, as a spatial geek I'd love it if I could directly perform these kinds of operations on my mobile, so when someone asks "how much of my backyard is covered by this easement?" I can give them the correct answer immediately 

... and/or we implement the qml / html widgets in forms and your spatial geek of confidence can preconfigure this and your backyard experts can show nice a nice pie chart to someone that visualizes the backyard.
... plus we definitely need a dashboard that does the same on project level (not feature level) to show a progress bar of how many street lamps you have checked already and how many you still have to go.

> 
> (...and I'm sure that either yourself or @mbernasocchi has asked themselves sometime in the past if the bike ride your mid-way through follows a simple-features topologically valid path, or if their ride has been subject to self intersects  )

Tunnels or jumps, this analysis needs to be performed 3d

**Comment by nirvn** [comment]
@nyalldawson , guess what sir, it's been implemented :partying_face:
