### ISSUE TITLE
stylus issue

### ISSUE THREAD

**Issue by lucienicolier** [opengisch/QField#2037]
I am having an issue when using a stylus to select from a list. I am using a Samsung Active 3 tablet with S pen. When I tap the pen to make a selection from a list it will close the create feature interface if I click a selection listed over the map area. If I make a selection in the lower portion of the screen it works fine.

PS: message from a website contact

### Reproduction Steps:

1. use pen
2. open a list
3. choose a value covering the map

### Expected behavior:
The value chosen should be selected. 

### Observed behavior:

The edition is exit without saved.

### Screenshots and GIFs

https://user-images.githubusercontent.com/50236352/124773113-ecdefa80-df3c-11eb-92c2-df2c1beb2465.MOV

**Comment by lp-dj** [comment]
I have the suspicion that behind this bug could possibly be the same cause as in the problem described in #2079, don't you think?

**Comment by nirvn** [comment]
@lucienicolier , is this using QField 2.0 beta or on 1.9.x? I feel I've fixed a similar issue during the 2.0 development cycle.

**Comment by lucienicolier** [comment]
@nirvn it's a message from a website contact, I don't know which version he was using, but if you fixed it I suppose it was 1.9.x.

**Comment by nirvn** [comment]
K. I think it's been addressed

**Comment by nirvn** [comment]
Let's re open if it's still an issue in 2.0.
