### ISSUE TITLE
GNSS not working on windows

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#2038]
I made the same instalation as ntrip6 in a tablet Currently running 64 bit Windows 10 

the result messaje is text window:
- 'VirtualXPath' [XML Path Language - XPath]
- 'VirtualXPath' [XML Path Language - XPath]
qrc:/qml/qgismobileapp.qml:1144:9: Unable to assign [undefined] to GnssPositionInformation
qrc:/qml/OverlayFeatureFormDrawer.qml:80:13: Unable to assign [undefined] to GnssPositionInformation
qrc:/qml/qgismobileapp.qml:2259:5: Unable to assign [undefined] to GnssPositionInformation

Install .NET SDK 5.0.300 (x64) on tablet and If the QField application works correctly on windows but the GPS does not work

_Originally posted by @emarmolejo in https://github.com/opengisch/QField/issues/1885#issuecomment-868803015_

**Comment by m-kuhn** [comment]
Internal GNSS is non functional on windows currently, this needs development.

**Comment by jonnyforestGIS** [comment]
Hi all, 
@m-kuhn I had some time to do some tests using the internal GPS chipset in a Getac T800 tablet with the last build and I don't know if this is related or is reported (try to avoid a potential duplicate issue) but is giving the following output log:

```
serialnmea: No known GPS device found. Specify the COM port via QT_NMEA_SERIAL_PORT.
<Unknown File>: Can't assign to existing role 'isVisible' of different type [Number -> Bool]
<Unknown File>: Can't assign to existing role 'isVisible' of different type [Number -> Bool]
qrc:/qml/qgismobileapp.qml:471:7: Unable to assign [undefined] to bool
qrc:/qml/DigitizingToolbar.qml:75:5: Unable to assign [undefined] to GnssPositionInformation
qrc:/qml/qgismobileapp.qml:1183:9: Unable to assign [undefined] to GnssPositionInformation
qrc:/qml/FeatureListForm.qml:499: TypeError: Cannot read property 'crs' of null
qrc:/qml/OverlayFeatureFormDrawer.qml:81:13: Unable to assign [undefined] to GnssPositionInformation
qrc:/qml/qgismobileapp.qml:2396:5: Unable to assign [undefined] to GnssPositionInformation
Could not add position handler (Operation aborted)

```

By default, the COM Port is 2 but I can change it in the control panel.

I install a normal QGIS Desktop in the tablet to check if the problem is from Windows 10 and using QGIS Desktop, the tablet can find the port and can connect to internal GPS.

Regards

**Comment by mariusd2022** [comment]
Qfield has no GNSS position on Trimble T100 tablet, Windows OS.
QGIS freeze after connect GNSS internal port of same tablet and has no position even if GPS is connected.

**Comment by legnad** [comment]
Dell Latitude 7220 Rugged (Windows 10) over here with u-blox M8 GNSS-Module (working in u-center and in QGIS on COM Port 10). However no selection is possible in QField. The drop down shows "internal Antenna" only even after hitting "scan". No positional data is given.

QField 2.0.14 on Windows.

**Comment by nirvn** [comment]
@legnad , QField version 2.6.1 has gained a serial port receiver for external GNSS devices, this should unlock positioning for you (and many , many others :) )

**Comment by legnad** [comment]
@nirvn this is great news! Looking forward to give feedback around end of January.

**Comment by jonnyforestGIS** [comment]
> Hi all, @m-kuhn I had some time to do some tests using the internal GPS chipset in a Getac T800 tablet with the last build and I don't know if this is related or is reported (try to avoid a potential duplicate issue) but is giving the following output log:
> 
> ```
> serialnmea: No known GPS device found. Specify the COM port via QT_NMEA_SERIAL_PORT.
> <Unknown File>: Can't assign to existing role 'isVisible' of different type [Number -> Bool]
> <Unknown File>: Can't assign to existing role 'isVisible' of different type [Number -> Bool]
> qrc:/qml/qgismobileapp.qml:471:7: Unable to assign [undefined] to bool
> qrc:/qml/DigitizingToolbar.qml:75:5: Unable to assign [undefined] to GnssPositionInformation
> qrc:/qml/qgismobileapp.qml:1183:9: Unable to assign [undefined] to GnssPositionInformation
> qrc:/qml/FeatureListForm.qml:499: TypeError: Cannot read property 'crs' of null
> qrc:/qml/OverlayFeatureFormDrawer.qml:81:13: Unable to assign [undefined] to GnssPositionInformation
> qrc:/qml/qgismobileapp.qml:2396:5: Unable to assign [undefined] to GnssPositionInformation
> Could not add position handler (Operation aborted)
> ```
> 
> By default, the COM Port is 2 but I can change it in the control panel.
> 
> I install a normal QGIS Desktop in the tablet to check if the problem is from Windows 10 and using QGIS Desktop, the tablet can find the port and can connect to internal GPS.
> 
> Regards

@nirvn For this sub-topic of this issue I can say that is possible to use the internal GPS in the Windows Tablet. Is fixed (thank you guys).

I have an external GNSS device and will try to test as well and give feedback.

**Comment by nirvn** [comment]
@jonnyforestGIS , that's great, thanks for letting us know.

**Comment by emarmolejo** [comment]
Install QField version 2.6.1 on MINNO tablet with Windows 10, set the positioning device: (u-blox Virtual COM Port COM1) and YES IT WORKED.

As soon as I have the test on a Getac T800 tablet, I'll let you know

THANK YOU
INEGI

Instale QField version 2.6.1 en tableta MINNO con Windows 10, configure el dispositivo de posicionamiento: (u-blox Virtual COM Port COM1) y SI FUNCIONO (ver imagen).
![GPS_Tableta_MINNO_win10](https://user-images.githubusercontent.com/36648285/213798957-1b59a24a-8c9d-44c5-bda2-527b18037781.PNG)

En cuanto tenga la prueba en una tableta Getac T800 le comento

GRACIAS
INEGI

**Comment by m-kuhn** [comment]
Gracias por compartir
