### ISSUE TITLE
Show picture direct in QField

### ISSUE THREAD

**Issue by bru500** [opengisch/QField#2041]
QField would rock even more, if it could show pictures direct in QField insted of a link to the photo.
For a quick check and to get an overview, every click less is worth a lot.

### Reproduction Steps:
1. Click on an element with a photo
2. I see only the link to the photo and need to click on it to see it.

### Expected behavior:
1. Click on an element with a photo
2. directly see the picture in QFIELD, with other attributes above or below.

### Screenshots and GIFs
![Screenshot_20210712-175623_QField](https://user-images.githubusercontent.com/40229231/125319721-4da27480-e33b-11eb-90b9-dbb63092f5a0.png)

**QField version:** 
1.9.6 and others.

**Comment by suricactus** [comment]
Can you please verify the project has been configured properly as described in the comment here https://github.com/opengisch/QField/issues/1213#issuecomment-674408619 .

**Comment by bru500** [comment]
The foto in the project above has been configured with "Use a hyperlink for document path", which is different as in comment  #1213.

But if I configure as described in this comment, the foto is not displayed at all.
New configuration:
![grafik](https://user-images.githubusercontent.com/40229231/125766079-1582921f-cdc9-4133-8955-4f34e9a483ee.png)

Result in QFIELD (Foto is not displayed):
![Screenshot_20210715-113629_QField](https://user-images.githubusercontent.com/40229231/125766263-9ae2a851-f4ad-4017-a305-6cfab5f2b4ff.png)

**Comment by VxTedxV** [comment]
Check the length of your field in QGis : maybe the path is too long to be stored and return a broken link to show the image ?

**Comment by bru500** [comment]
As I found out this functionality is already available, thanks to the valuable Bee Farming Demo. Sorry for posting this. This issue can be closed. In my project, pictures where not saved, the length of the path was not the problem. After setting up the project new from scratch, now it works. I can not say, what the problem was. Thanks for the feedback.
