### ISSUE TITLE
No more use of the Open Camera app and therefore less image metadata since Android 11 update

### ISSUE THREAD

**Issue by lp-dj** [opengisch/QField#2042]
A few weeks ago, my Samsung Galaxy Tab Pro received an update to Android 11 (Kernel 4.9.227) and One UI 3.1. Since then, when adding a photo in QFIELD (v1.9.6), the Open Camera app is no longer started as usual and desired, but the Android Builtin Camera app.

I know this was a bad design decision by Google (perhaps for understandable reasons, but in my opinion poorly implemented) and not by opengisch
(for e.g. see here: https://www.theverge.com/2020/8/20/21376391/google-android-11-third-party-camera-picker-intents).

But maybe I'm lucky and someone has already found a solution for the problem?

Why is this a problem at all? On the one hand, I like the Open Camera app much better because of the higher configurability and image quality (maybe this is somewhat subjective and I could get along with the default app when i have to). More importantly, the default camera app in Android 11 stores much less metadata about the image, for example, not the viewing direction which I often find quite helpful.

Is there a way that to take a new picture the Open Camera app is launched again? Or is there at least the possibility to save the viewing direction in a separate attribute field during the capture? I can't find a suitable variable here: https://qfield.org/docs/prepare/gnss.html

Best thanks and many greetings

**Comment by m-kuhn** [comment]
That really is a pity.
At the moment it seems such pictures need to be taken through the camera app itself and then added on QField via the gallery image picker.

It looks like there's one door left open, it involves hard coding the camera provider into QField. 
 https://commonsware.com/blog/2020/08/16/action-image-capture-android-r.html .

Having the compass available as a variable would be great, it's not currently possible (see also https://github.com/opengisch/QField/issues/1882 and here https://github.com/opengisch/QField/issues/492)

**Comment by lp-dj** [comment]
Thank you very much for your feedback, @m-kuhn .

Do you think the remaining option by hard coding the camera provider into QField is a long term prospect or do you have indications that this may not exist for long either?

Otherwise, this sounds like a good possibility for a compromise to me: wouldn't it be relatively easy (Attention: Estimate of a non-involved layman :D ) to set up the already existing camera setting option (native vs. default camera) as a dropdown list with the following choices: native, default, OpenCamera?

**Comment by m-kuhn** [comment]
> Do you think the remaining option by hard coding the camera provider into QField is a long term prospect or do you have indications that this may not exist for long either?

I not know what other plans there are on Google side.
 
> Otherwise, this sounds like a good possibility for a compromise to me: wouldn't it be relatively easy (Attention: Estimate of a non-involved layman :D ) to set up the already existing camera setting option (native vs. default camera) as a dropdown list with the following choices: native, default, OpenCamera?

That sounds like a good UI proposal.
There probably needs to be a condition to only show the open camera option for Android > 11 and usually things that involve interfacing with the Android system take a bit longer and some extra testing rounds. But it doesn't sound overly complicated.

**Comment by lp-dj** [comment]
> I not know what other plans there are on Google side.

Yeah, sure... to a certain extent, we are exposed to Google's actions and any assessment on our part remains speculative.

> Having the compass available as a variable would be great, it's not currently possible (see also #1882 and here #492)

To be able to access the compass via variable would of course be the more universal solution, which is also probably independent of the OS version, I guess? But that again seems like a bigger deal, judging by the age of this feature request.

> That sounds like a good UI proposal.
There probably needs to be a condition to only show the open camera option for Android > 11 and usually things that involve interfacing with the Android system take a bit longer and some extra testing rounds. But it doesn't sound overly complicated.

So if you get around to expanding the camera settings, feel free to let me know if I can help (presumably my help would be limited to the extra testing rounds you mentioned :-\ ).

**Comment by m-kuhn** [comment]
> > I not know what other plans there are on Google side.
> 
> Yeah, sure... to a certain extent, we are exposed to Google's actions and any assessment on our part remains speculative.

Very much so, yes

> 
> > Having the compass available as a variable would be great, it's not currently possible (see also #1882 and here #492)
> 
> To be able to access the compass via variable would of course be the more universal solution, which is also probably independent of the OS version, I guess? But that again seems like a bigger deal, judging by the age of this feature request.

That would be a very nice functionality, but would also not reflect the state of the picture itself and needs an extra action from the user.
It's not necessarily a big job to do. But it still needs someone to do it.

> 
> > That sounds like a good UI proposal.
> > There probably needs to be a condition to only show the open camera option for Android > 11 and usually things that involve interfacing with the Android system take a bit longer and some extra testing rounds. But it doesn't sound overly complicated.
> 
> So if you get around to expanding the camera settings, feel free to let me know if I can help (presumably my help would be limited to the extra testing rounds you mentioned :-\ ).

Thanks for the offer. Testing is always very welcome :+1:

**Comment by ARBkey** [comment]
+1 for hard coding open camera . for android 11 or higher. I recently purchased a Samsung Galaxy s20 FE and am having problems with the stock camera crashing qfield (as reported in a few other issue reports). Open Camera was my preferred work around, however this is no longer viable with android 11. I would be willing to contribute to the development of this feature.

**Comment by nirvn** [comment]
@lp-dj , since Android won't allow us the camera freedoms of the past and our non native camera adds a bunch of metadata now, should we close this?

**Comment by lp-dj** [comment]
@nirvn I think we can close this issue, thanks for the feedback!

Two comments in this context:

1) The reference to the OpenCamera app still appears in the QField settings. This should probably also be removed? There is also a typo in the German translation here. It should be "Standardkamera" or "Standard-Kamera". A period is also missing at the end of the sentence. :wink:

![grafik](https://github.com/opengisch/QField/assets/80956612/c8f120f1-6cec-4684-afe4-c45e12013ab7)


2) I have just taken three test photos with the BuiltIn camera and looked at the metadata. Looks good so far, with the exception that the following metadata was written to one of the three images (the other two look ok):
`
GPSImgDirection - 21396.216485`

I would have assumed that these are degrees from 0-360, with the zero point in the north? Am I wrong here or how should the 21396 be interpreted as a direction indicator?

Or do you think it's a bug and we should create a new issue for it?

(For info: the QField version used was 3.2.2 - Congo 72be17)

**Comment by nirvn** [comment]
@lp-dj , nice, let's close it. For the documentation, it'd be great if you could open a pull request in the documentation repository with needed changes.

As for direction, looks like a bug to me. Please open if you have steps to replicate. Thanks :)

**Comment by m-kuhn** [comment]
@lp-dj also note that the translation is done by volunteers on transifex, see https://github.com/opengisch/QField?tab=readme-ov-file#contribute

**Comment by lp-dj** [comment]
@nirvn @m-kuhn Good to know, thanks for the hint/reminder regarding documentation and translation. I will try to familiarize myself with transifex soon and contribute my part ;)

As for the EXIF metadata: I'll try to recognize a pattern and create a new issue if I discover reproducible steps. First hypothesis: Since it only affects the first photo after I turned on the GPS, maybe the positioning was not yet fully "initialized" and somehow returned wrong values!?

**Comment by notgernot** [comment]
For everyone that is able to root your device there is actually an Option to make OpenCamera to the "default camera" again. I testeted it on a dive With Lineage21/Android14 adn it works perfect....Now OpenCamera Opens as default Camera App in Qfield again also is also the default Camera systemwide.

```
I copied privapp_whitelist_net.sourceforge.opencamera in /root/system/system_ext/etc/permissions/ (chmod 644, root/root)

I created /root/system/system_ext/priv-app/OpenCamera and copied the apk of the app, net.sourceforge.opencamera.apk

restart the phone (and you'll find OpenCamera installed)
```

from 

https://sourceforge.net/p/opencamera/discussion/qa/thread/f77dc7d7a8/
