### ISSUE TITLE
dead screen after tapping on a photo

### ISSUE THREAD

**Issue by lindacamathias** [opengisch/QField#2059]
Clicking on a photo in QField (trying if it can be enlarged) results in a persistent black screen (master dev) or white screen (v 2.0.2). i didn't found another way than close and reopen QField to turn back to the normal map canvas view.

### Reproduction Steps:

1. take a project with photos (attachment widget) -> from QFieldCloud: simple bee farming demo
2. go to a feature with a photo in a photo widget  (some features in apiary have photos ) 
   or take a photo
3. tap on the photo 

### Expected behavior:

photo is enlarged or  at least nothing happens 

### Observed behavior:

persistent black screen (master-dev, white screen in v. 2.0.2.) the androids return button doesn't effect anything at all

https://user-images.githubusercontent.com/77726342/127043179-706ed862-e29c-4b11-b1b7-557821ecdc18.mp4

message in master-dev after waiting a few minutes: 
![Screenshot_20210726-194246_QField_Dev 1](https://user-images.githubusercontent.com/77726342/127043237-caa69221-96b4-41d9-a699-d4547fefef98.jpg)

**QField version:** tried with v. 2.0.2  and master-dev 9981f1

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by lindacamathias** [comment]
I was using a strange default app for viewing pictures. 
After i reset all app defaults and set the default for viewing pictures to the Photo Viewer it's fine

**Comment by suricactus** [comment]
What is the name of the "strange default app", just to keep it as a reference in the future.

**Comment by lindacamathias** [comment]
i don't know which one was set but i have a suspect ;-) . these were the proposed apps for photo preview in QField on my android :
![Screenshot_20210804-222505_Android_System 1](https://user-images.githubusercontent.com/77726342/128250246-1c6b2765-fecc-4860-bff5-c32a4328b781.jpg)
We found out that QField is in that list because the app wants to tell Android that it can handle .jpg (GeoJPEG) Files (and other Geo* Files) what is correct basically. But obviously it just makes no sense to choose the app for previewing pictures. I didn't choose a particular app for the photo preview. So maybe the android made the choice without asking me, just picking one of the apps randomly (?).
