### ISSUE TITLE
WMS Layer still not working with QFIELD 0.10.4

### ISSUE THREAD

**Issue by IvoPlanoetscher** [opengisch/QField#206]
Hello everyone,
QFIELD is a great app that I really enjoy using, but the still existing problem with rendering the WMS layer is a very strong limitation!  
Also in this new version (0.10.4) the well-known problem of non-visualizable WMS layers was not solved.  
For example, in my QGIS project, I have the following WMS server: http://geoportal.dgu.hr/wms?request=getcapabilities  
With QGIS (version 2.18.15) its layers can be easily visualized, but then absolutely not with the same QGIS project on QFIELD.

To easily replicate the error, I enclose a ZIP file with a test QGIS project and the associated data.
[Data_for_QFILD-Issue206.zip](https://github.com/opengisch/QField/files/1625818/Data_for_QFILD-Issue206.zip)

I kindly ask you to solve this problem as soon as possible and definitely.
Thanks in advance

**QField version:** 0.10.4

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: NO
* Problem can be reliably reproduced, doesn't happen randomly: YES
* Problem happens with all files and projects, not only some files or projects: YES

**Comment by signedav** [comment]
Closing because of duplicate. I keep #267 open.
