### ISSUE TITLE
Enhancement proposal : Set tracking parameters 

### ISSUE THREAD

**Issue by karinelsg** [opengisch/QField#2060]
Hello,

I am currently testing a QField project to collect field data for cycling paths.
To do so, I need to record a GPS track each time I want to add a new entity, when there is a change in a defined characteristic.

Currently, I need to re-enter tracking parameters each time I stop a track and record a new one.
I don't know if there would be a way to set the tracking parameters either in the QGIS project or directly in QField parameters, to assure all users use the same parameters for a same purpose and gain precious time when several tracks need to be recorded on a fieldwork day.

Thanks a lot for your answer,

**Comment by nirvn** [comment]
This has been implemented and will be available in the next QField 2.0 beta.
