### ISSUE TITLE
Show checkbox again for Boolean fields

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#2062]
Since the most recent versions of QField, Boolean fields do not show a real checkbox anymore but show the text "True" or "False". Changing the setting in QGIS from Attribute Form -> Checkbox -> Display Settings to "Stored value"  shows then a switch in QField - but not a real checkbox. Ist that intended? I would not mind the switch, but it shows also not under the field name but on the very right side, so the readability is not that great:

![grafik](https://user-images.githubusercontent.com/15894401/127505486-ec792880-7bbf-4e48-8773-4b5348f457d5.png)

Using QGIS 3.16.9 and Qfield 2.0.3 Beta (on PC)

**Comment by nirvn** [comment]
What are the stored values representing unchecked/checked in your dataset?

There's a problem here, and that's the missing left aligned string (which is either true or false by default, or stored values when configured as such).

**Comment by suricactus** [comment]
@nirvn can we show the default true/false combo when what is going to be shown is an empty string?

**Comment by nirvn** [comment]
@suricactus , yeah, but I'm still curious as to what the stored values are here in case something else is wrong.

In any case, yes, we should detect empty values.

**Comment by meyerlor** [comment]
@nirvn  it is a boolean field in a geopackage table. the widget configuration looks like: 
![grafik](https://user-images.githubusercontent.com/15894401/127812219-f5e800cd-be20-4616-97b4-4091be6df94f.png)
