### ISSUE TITLE
Shapefile windows-1252 encoding problematic on Android leading to wrong field name

### ISSUE THREAD

**Issue by Rutjat** [opengisch/QField#2067]
### Description

QField doesn´t show all the fields in form, if the Drag and Drop Designer is used to create it. 

Especially two fields: "Määrä" and "Kasviryhmä" which are both whole number type fields (same as other fields on this layer that are whole number).
Only difference I have noticed (to the other fields which do show up) is that both of these features are those that define the symbology of the layer (I use rule-based symbology). 
They do show up in QField form if I use Autogenerated form.

## Steps
1. Created the field (Type: Whole number (integer 64 bit))
2. Go to Attributes Form and choose the Drag and Drop Designer
3. Draging & Droping (with container creating)
4. " Ok" and Saving the file & packaging it for QField
5. Copying the files to my QField device and opening project

### Screenshots and GIFs
These screenshots illustrate the problem with feature "Määrä". Forms shown first in Qgis then QField:

![form](https://user-images.githubusercontent.com/88327378/127871199-f6ec0724-6a1a-4e18-9d77-331c04f03be9.JPG)
![form_QField (2)](https://user-images.githubusercontent.com/88327378/127872901-62622f1e-da27-499a-af7b-a0d615cbf6ab.jpg)

**QField version: 1.9.6 (d5dd01 v11.9.6)**

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Haven´t used older version

**Comment by nirvn** [comment]
@Rutjat , can you share this dataset (or a sample of it) here as well as the layer setting (in qml format)?

**Comment by Rutjat** [comment]
[project_sample.zip](https://github.com/opengisch/QField/files/6918421/project_sample.zip)

**Comment by nirvn** [comment]
@Rutjat , I can see the "Maara" field here on latest QField 2.0 beta:
![image](https://user-images.githubusercontent.com/1728657/127947767-1e991ec4-0bf3-4798-abde-9c3f873dbc69.png)

Can you try QField 2.0 beta 4 and confirm that your field shows up too?

**Comment by Rutjat** [comment]
I tried and still not showing those fields.
![Screenshot_20210803-091006_QField](https://user-images.githubusercontent.com/88327378/127967499-b593f565-b692-4609-adc0-bda985413d68.jpg)

**Comment by nirvn** [comment]
OK, I can confirm this is the case with the APK offered on Google Play. Investigating.

**Comment by nirvn** [comment]
@Rutjat , as I suspected above, the problem as to do with the detection of the shapefile encoding (which on QGIS desktop is set to windows-1252). 

For the time being, a workaround this issue is to convert your dataset to a geopackage.

**Comment by nirvn** [comment]
@Rutjat , if you want to keep using the shapefile, merely renaming the field names to avoid special characters is likely not enough (because you'll end up with the same decoding error for the actual data attached to each feature). You can (should, actually) save your windows-1252 encoded shapefile as a utf-8 encoded shapefile. You can do that within QGIS.

**Comment by m-kuhn** [comment]
We should possibly just check this (encoding is utf-8) in qfieldsync and offer advice. It will help to make geo a more modern place anyway :-)
