### ISSUE TITLE
Symbols not shown in QField (renderer types)

### ISSUE THREAD

**Issue by Rutjat** [opengisch/QField#2068]
### Short description 
I have a shapefile layer ("istutukset") I use Rule-based symbology (size & color) to visualize the features. All works great on Qgis, but on Qfield nothing is shown unless the layer is activated (even then only highlighted points do show up, without any styling).

With an older version of the project I used  Graduated styling depending on one field ("Määrä" =amount defining the size of the symbol) and it worked on QField. I tried saving the style and Loading it to my up-to-date version of the project but it still doesn´t  work in QField. I tried changing the style in the old project and then loading the "working" style back and now it doesn´t work even in the old project version.

### Expected behavior:
You create field, create the symbol style and save and package project for QField. You open QField and it should look like it did on Qgis, because QField supports all style setting.

### Observed behavior:
As you create field, create the symbol style and save & package project for QField everything still looks ok.
You open the project in QField, no error messages appear, but no symbols from layer "istutukset" is shown.

### Screenshots and GIFs
Project sample and symbols now:

![example1](https://user-images.githubusercontent.com/88327378/127903308-95d1001e-a9ad-458f-af82-2936303236a9.JPG)
![working_symbology_field](https://user-images.githubusercontent.com/88327378/127903371-f26b5d8b-ca3d-45a9-bb00-f06dc28cc3d6.JPG)

Screenshots from Qfield. How it looks as you open the project(sample) and how it looks as you open the feature list:

![Screenshot_20210802-204231_QField](https://user-images.githubusercontent.com/88327378/127903410-23ca0e56-b510-4aa2-b698-e162624041bd.jpg)
![Screenshot_20210802-204252_QField](https://user-images.githubusercontent.com/88327378/127903420-8f159dcf-88df-42d3-bf96-ce8448cc8e85.jpg)

Sample from old version of project and symbol style that worked:

![working_symbology_symbol](https://user-images.githubusercontent.com/88327378/127903394-d2ac4fdf-3d42-4ea9-88d4-471f98095ce6.JPG)

**QField version:1.9.6 (d5dd01 v1.9.6)** 

## Additional information:
Attached files contain sample of the project dataset and qml file with symbols style that did work on QField.
[sample_project.zip](https://github.com/opengisch/QField/files/6918803/sample_project.zip)

* Problem started happening recently, didn't happen in an older version of QField: [Haven´t used older version of QField]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes & No] started randomly, haven´t worked since
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
Are you cable exporting your project via qfieldsync? If so, it's likely your shapefile gets converted to gpkg and the field names (containing "exotic" characters) are modified. 

If you do export to cable, can you open that exported project in QGIS itself and a/ check if the rendering works, and b/ check the field names.

**Comment by nirvn** [comment]
@Rutjat , BTW, that point layer has a min/max scale visibility turned on. You have to zoom into the canvas a fair amount to see the points show up. They also show up in QField 2.0 beta:
![image](https://user-images.githubusercontent.com/1728657/127948414-aecf1a6b-7835-4930-8f2b-c15319186bbf.png)

**Comment by Rutjat** [comment]
The visibility, or the version wasn´t clearly the problem, but the "exotic" characters in the field names. I changed the exotic characters and both problems were solved. Weird in a way, since it did work earlier despite the characters. But thank for your help and pointing me back to those oddities.

**Comment by nirvn** [comment]
@Rutjat , that's correct. Both this and the form issue you reported are due to the shapefile field name not decoding properly on Android platform. I had suggested you to move to a geopackage format, but indeed just renaming the field name so that only A to Z and 0 to 9 characters are used will work too :)

**Comment by nirvn** [comment]
Let's close this issue and keep the other one alive.
