### ISSUE TITLE
Re-Use attribute value checkbox missing

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#2072]
In QField version 1.9.6 the checkbox behind an attribute is missing - is there another way to re-use a previously entered attribute value?

**Comment by signedav** [comment]
I cannot reproduce that. Can you provide us some screenshots and more details about the steps to reproduce?

**Comment by meyerlor** [comment]
sorry, my bad - the checkbox is there after creating a new feature. i thought it would also be there when simply editing an existing one!
