### ISSUE TITLE
Crashes when using the autocompletion

### ISSUE THREAD

**Issue by lp-dj** [opengisch/QField#2090]
I am trying to use autocompletion to select entries from a larger reference list (range 15.000 - 20.000 entries). This results in both reliably reproducible crashes and seemingly random crashes.

### Reproduction Steps:

1. Create an attribute form in which you can use autocomplete to select entries in a larger reference list for selection (strictly speaking, i have observed the problem so far only with the one reference list you can also find below in the mre. i don't have a second comparably structured list).
2. Tap the desired entry as soon as it appears in the list of entries filtered according to your input string.

### Expected behavior:

The tapped entry is selected and assigned to the corresponding attribute of the current feature.

### Observed behavior:

At the beginning of a QField session, filtering and selection usually works as expected. However, two limitations can be observed that prevent productive use of the function.

1) There are very specific search strings when using QField in combination with the used reference list can be crashed reliably, although the filtering of the entries always works very smoothly. But as soon as you try to select a filtered entry in these cases QField crashes.

2) Often but not reliably reproducible, QField (in combination with the large reference list used) gets into a situation where any interaction with autocomplete causes it to crash.

### Assumptions:

Regarding 1) I assume that the reliable reproducible cases have something to do with the size of the list of filtered entries. Above a certain number of entries, it crashes. Look at my example in the video below. I type "t s r" to filter for "Taraxacum sect. Ruderalia" to filter. Filtering works great as can be seen, but tapping the entry is followed by the inevitable crash. If I type something longer instead of "t s r" to further narrow down the results list, I am eventually allowed to select the desired entry.

Regarding 2) I see a trend here that the longer the QField session lasts, the higher the probability of a crash. Once it crashes, often no restart of the app helps and it crashes with every input attempt. The only thing that helps temporarily is restarting the entire system.

Another factor that I feel increases the likelihood of a crash is the speed at which I type or try to select a filtered entry after typing.

Bottom line: Both together makes me suspect that it might have something to do with memory management or similar (The system's working memory does not seem to be the problem, since there is usually still around 1 GB free)? All the single elements of the function on their own works, but presumably I'm pushing the system to its current limits with the size of the reference list? What is the largest reference list you guys have used so far without any problems? Is there such a thing as "official" specifications of QField's performance limits?

### mre

[mre_autocompletion_crash.zip](https://github.com/opengisch/QField/files/7001295/mre_autocompletion_crash.zip)

### Screenrecording

https://user-images.githubusercontent.com/80956612/129756769-bd069b05-d92a-49dc-a43a-ec6d5fbc38b5.mp4

### adb-log 

Here is also an adb log. Please let me know if and how I can create it more helpful, it's my first one ;) Is it better for you to have the verbose log? 

[adb_log_autocomplete_crash.txt](https://github.com/opengisch/QField/files/7001299/adb_log_autocomplete_crash.txt)

**QField version:** 1.9.6 (d5dd01)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Don't know.
* Problem can be reliably reproduced, doesn't happen randomly: Yes, see above.
* Problem happens with all files and projects, not only some files or projects: Presumably with all reference lists above a certain size?

**Comment by suricactus** [comment]
Hey, I just wanted to say this is one of the most awesome, descriptive and clear bug reports I have ever seen! You have a text description, screen recording, example project and even adb log! Thanks a lot! I will have a look.

**Comment by lp-dj** [comment]
Haha, thank you @suricactus  ;)

On the one hand for the compliment (have practiced the last few days ;) ), and on the other hand especially for taking a look and the great app in general (<3 to all @opengis.ch).

**Comment by she-weeds** [comment]
I can confirm this happens to me as well since I think 1.8.4 - similar issues where crashes are generally more likely (a) the longer a project remains open and (b) the longer the list of potential candidates. But I had not thought to put in a bug report and certainly it wouldn't have been as thorough as this one! Thanks on behalf of everyone else quietly using this app.

**Comment by nirvn** [comment]
@lp-dj , when you have a minute, please test the APK build here (https://github.com/opengisch/QField/pull/2091#issuecomment-900894770), I'm pretty sure it fixes this crash.

I second @suricactus 's comment here, fantastic reporting on your part. Your test project was invaluable.

**Comment by lp-dj** [comment]
@nirvn Hey, sounds great!

With such fast reactions to report bugs can even be fun ;)

Thank you very much!

"Unfortunately" I'm just in the long weekend and have left my work equipment in the office. On my personal smartphone, the installation of the APK build always fails.

Looking forward to trying it out right at the beginning of next week on my working tablet. I'll be in touch!

**Comment by lp-dj** [comment]
@nirvn Running a little late here. But for the sake of completeness, I happily confirm that I can no longer reproduce the bug in the current QField Dev version from the Playstore :) Great, thanks a lot!
