### ISSUE TITLE
Initial screen needs line-wrapping of text

### ISSUE THREAD

**Issue by esigra** [opengisch/QField#210]
A certain screen is only shown with a new install of QField 0.10.4 - Kesch. It has some text that goes beyond the edge of the display. There is no line wrapping nor scrolling, so the text is not readable:
![qfield_initial_screen_landscape](https://user-images.githubusercontent.com/12582697/35013965-531d166c-fb0f-11e7-89ab-a9533c2583ad.png)
![qfield_initial_screen_portrait](https://user-images.githubusercontent.com/12582697/35013973-5974b0ce-fb0f-11e7-8d10-538389f2afaa.png)

**Comment by signedav** [comment]
Solved.
