### ISSUE TITLE
Strange behavior of back button when using nested forms

### ISSUE THREAD

**Issue by blacktesta** [opengisch/QField#2106]
Back button closing all opened forms when using it second time instead of closing only last form.
### Reproduction Steps:

1. Create a  project with 3 layers: A, B, C. "A" layer is parent for "B" layer and "B" layer is parent for "C" layer
2. Create some features:
layer A: parent_1
layer B:  child_1
layer C:  grandchild_1, grandchild_2
3. Open in qfield grandchild_1 form from parent1 form. Press back button.
4. Reopen grandchild_1 form. Press back button.

### Expected behavior:

After first pressing back button in grandchild_1 form Qfield returns to child_1 form. After reopening granchild_1 form and pressing back button Qfield returns to child_1 form

### Observed behavior:

After first pressing back button in grandchild_1 form Qfield returns to child_1 form. After reopening granchild_1 form and pressing back button Qfield returns to map with some UI elements became unclickable.

### Screenshots and GIFs

https://user-images.githubusercontent.com/74047515/131219483-845fff17-eb3f-46d0-9069-6035ef20204a.mp4

Sample project: 
[data_base.zip](https://github.com/opengisch/QField/files/7070759/data_base.zip)

**QField version:** 2.0.4 (448e67 v2.0.4)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No (I don't remember which version I started using qfield from, but this problem was in all the versions I used, including dev and beta)
* Problem can be reliably reproduced, doesn't happen randomly:Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
Reproducable on device (haven't tested on computer). It's *not* concerning 1.9 releases. It's introduced with version 2.

**Comment by nirvn** [comment]
@blacktesta , your issue has been fixed in https://github.com/opengisch/QField/pull/2182 -- if you can, please try the APK in that PR, your confirmation would be appreciated.

**Comment by nirvn** [comment]
@blacktesta , BTW, I love your use of a single geopackage with both layers and a QGIS project embedded into it. :)

**Comment by blacktesta** [comment]
> @blacktesta , your issue has been fixed in https://github.com/opengisch/QField/pull/2182 -- if you can, please try the APK in that PR, your confirmation would be appreciated.

Awesome news! The main bug is gone! But there is another little one. In edit mode pressing back button several times to close several nested forms doesn't close the main parent form, showing message about closing app instead. See the video.
https://user-images.githubusercontent.com/74047515/135711482-9247e6ae-ae95-4ee4-a5f1-f736a997d088.mp4

**Comment by nirvn** [comment]
@blacktesta , OK, fixed that regression, APKs soon here (https://github.com/opengisch/QField/pull/2185)
