### ISSUE TITLE
About screen should be rearranged when rotated to portrait

### ISSUE THREAD

**Issue by esigra** [opengisch/QField#211]
The content of the about screen is not fully visible when the display is in portrait mode:
![qfield_about_screen_portrait](https://user-images.githubusercontent.com/12582697/35014321-77765374-fb10-11e7-934c-cb6afe3a75a7.png)Neither can it be scrolled. The 3 bottom items that are placed in a row should be rearranged so that they are placed below each other when the display is rotated to portrait mode.

**Comment by signedav** [comment]
Solved.
