### ISSUE TITLE
Live default with pictures

### ISSUE THREAD

**Issue by lucienicolier** [opengisch/QField#2114]
I was testing live default with pictures, and I expected to get my pictures changing in live, but it does change only when I save it.

### Reproduction Steps:

1. Make a picture widget depending on a field with rang widget
2. change the field with rang widget value

### Expected behavior:

I expected to get my pictures changing in live

### Screenshots and GIFs

![live_change](https://user-images.githubusercontent.com/50236352/131643483-c0f1a101-7dfa-44fa-9345-4c065ae08e32.gif)

**QField version:** 2.0.3 (e60e7e v2.0.3)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by lucienicolier** [comment]
I can't attach the project but if you need one let me know.

**Comment by signedav** [comment]
@nirvn Should this work because of this implementation around here https://github.com/opengisch/QField/pull/2047/files#r672202516? 
Or would this more be an enhancement?

**Comment by nirvn** [comment]
@signedav , it should work already, I'd consider a bug.

@lucienicolier , if you can drop a test project in this issue, that'd help me looking into it during the next bug fixing session :)

**Comment by nirvn** [comment]
Working fine :smile: 
![Peek 2021-09-02 10-00](https://user-images.githubusercontent.com/1728657/131774814-31e223c0-c0f8-43eb-a2f7-5cde9f9bbe83.gif)

Closing, following up with Lucie on chat.
