### ISSUE TITLE
Photos not displayed in QField

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/QField#2118]
I have installed the latest QField Dev version. The photo is not displayed on the form once the picture is captured.

### Reproduction Steps:

1. Enter the Edit mode for any object having an Image widget, select the camera icon
2. Take the photo, and save the photo
3. The photo is not displayed on the form

### Expected behavior:

The photo should be displayed on the form

### Observed behavior:

No pictures get displayed on the form

### Screenshots and GIFs

![Screenshot_QField_EtatArbre_Photo_20210902-084236](https://user-images.githubusercontent.com/72449015/131817095-ce26753e-058c-497c-bccf-6ca4d9ec9bf4.png)

**QField version:** =c69cb

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] No
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No] not tested

**Comment by nirvn** [comment]
Can you test whether you can take photos using the advanced bees demo project? It's working for me.

**Comment by jpdupuy** [comment]
Hello, it is working fine for me using the advanced bees demo project.
I have prepared my project with QGIS 3.20. 
Can you tell me if a made a mistake in the widget parameters or would in come from the QFieldCloud project conversion?
![image](https://user-images.githubusercontent.com/72449015/131840647-49046370-885c-425b-9215-5b046317d130.png)
![image](https://user-images.githubusercontent.com/72449015/131840950-5c8a91b4-3bd7-4e6d-bd53-73fb22a1c4cb.png)

**Comment by VxTedxV** [comment]
Choisir "relatif au chemin du projet"
-> https://qfield.org/docs/fr/prepare/attributes-form.html#attachment-photo-settings
