### ISSUE TITLE
Photo not pushed from QField to QFieldCloud

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/QField#2119]
Although the attribute value of the photo has been pushed to QfieldCloud, the photo has not been pushed to QFieldCloud

### Reproduction Steps:

1. Enter the Edit mode for any object having an Image widget, select the camera icon
2. Take the photo, and save the photo
3. Select the menu, then the cloud icon, then push the changes
4. select the https://app.qfield.cloud/a/jpdupuy/ARB_DMS/files to check if the photos have been pushed to the Cloud
5. select the https://app.qfield.cloud/a/jpdupuy/ARB_DMS/changes to check if the changes have been applied to postgis

### Expected behavior:

The new photos should be visible in the file list

### Observed behavior:

The photos have not been pushed to the cloud, although the attribute value have been changed in the postgis DB

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/72449015/131819681-cf26b98a-b479-461c-9431-f8a4c59a2a81.png)

![image](https://user-images.githubusercontent.com/72449015/131819926-d492a1ea-cb13-44e8-a896-c4455a1aae36.png)

**QField version:** 0c69cb

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] Yes
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No] not tested

**Comment by nirvn** [comment]
@jpdupuy , I've re-tested photo/attachment upload over the last week, working as expected. Your issue is likely a problematic configuration for your photo attachment widget. Free free to attach your project here.

**Comment by mia-uapmq** [comment]
I have the same issue. Some pictures are uploaded but others arn't.
