### ISSUE TITLE
Photo : automatic download from QFieldCloud to your server (suggestion)

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/QField#2120]
Once the pictures have been pushed from QField to QFieldCloud, the administrator need to connect to https://app.qfield.cloud/a/<user name>/<project name>/files in order to download the files to the client server.

### Reproduction Steps:

1. Take and save a picture with QField
2. Push the changes to QFieldCloud
3. Logon to https://app.qfield.cloud/a/<user name>/<project name>/file and download the new photos to your server

### Expected behavior:

The file should be automatically resized from Qfield to QfieldCloud in order to speed up the transfer (avoid to change this parameter for each smartphone or tablet -> prefer Qfield parameter option)
The file shoule be automatically download to the client server, to avoid the administrator to do it manually, and make the photos immediatly avaliable to QGIS Desktop.

### Observed behavior:

Large file size (depends on the camera settings smartphone/tablet side)
The administrator has to connect to QFieldCloud and download the files in the proper directory
The QGIS end user do not see any result before the administrator has downloaded the pictures ( not synchronized with the postgis attribute values).
If another QfFeld user wants to view the pictures taken by another QField user/smartphone, it is unclear if the synchronization from QFieldCloud will make the pictures available to its device.
It might be clever to use a dedicated file server in the cloud to store the images so that it can be accessed directly by QField and QGIS Desktop without having to download the files from an application to another.

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 0c69cb

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] No
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No] Yes

**Comment by nirvn** [comment]
@jpdupuy , you can automatically download those photos/attachment into your QGIS desktop environment using the qfieldsync plugin's cloud synchronization. It's available in the latest beta via the qfieldsync toolbar or within the cloud projects dialog. 

If that's broken to you, please file an issue in the qfieldsync repository (https://github.com/opengisch/qfieldsync/). Thanks.
