### ISSUE TITLE
Measure tools not available, crash after selecting.

### ISSUE THREAD

**Issue by edelsau-coder** [opengisch/QField#2135]
Hi there,

when I load/use a "WMS Layer" into Qfield, everything works in view mode.
As soon as I want to switch to tool mode, the application crashes.
Is there a size limit on the wms layer that leads to the crash?

Samsung S20 +, Android 11

Thanks!

**Comment by edelsau-coder** [comment]
attached used layer.

https://drive.google.com/file/d/1aLZlTZ7-dcHxuO4CgmWw1jnaHFEjRst4/view?usp=drivesdk

**Comment by nirvn** [comment]
@edelsau-coder , thanks for reporting this, the hand has been fixed in this PR (https://github.com/opengisch/QField/pull/2183).
