### ISSUE TITLE
Force user to log in (enhancement request) or to disconnect

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/QField#2140]
When QField get installed on a shared device (on a tablet used by several staff members for different projects) the first person who logs in can access the projects is has been authorized to. 
If a second staff member uses this device, he is not asked to log on launching QField Dev. He can therefor edit-view data he is not authorized to access.
It is not obvious for a user to know how to disconnect (the icon in the upper right corner needs to be replaced by a text)

### Expected behavior:

Force user to enter connection details every time QField Dev get launched
Simplify the way you disconnect

### Observed behavior:

Anyone can edit-view data on QField if the previous user did not disconnect properly (using a shared device)
Once the project map is displayed, you need to 
- open the menu, 
- click on parameters, 
- select open a project, 
- select QFieldCloud projects, 
- click on QFieldCloud icon, 
- click on Disconnect. (a long way to disconnect :-(

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 2ba69d

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] No
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No] Yes

**Comment by m-kuhn** [comment]
The easiest approach to deal with this would be using different user accounts (https://support.google.com/nexus/answer/2865483?hl=en), just like on a desktop computer. From a security / isolation perspective this would make most sense and doesn't require any changes to QField.

What could be done on QField side is a new check box "remember me" on the login screen, the question for this would be when the session ends (When the user exits QField? After x hours of no interaction? After a reboot of the device?)
