### ISSUE TITLE
Editing demo projects in iOS testing version

### ISSUE THREAD

**Issue by geomondego** [opengisch/QField#2147]
When i try to add new features to the layers from the Advanced Bee Farming Demo project, I get the message **Unable to save chages**. 
If i only change attributes, everything goes as expected.

Picture1 - Message
![IMG_0510](https://user-images.githubusercontent.com/4389239/134948192-7cb8f6bb-f9cc-4eac-a936-65a52891a360.PNG)

Picture 2 - Log message
![IMG_0511](https://user-images.githubusercontent.com/4389239/134948236-2c0eeba3-f54e-41dd-b5d6-0be2b4c88017.PNG)

Regards,
Nelson

**Comment by m-kuhn** [comment]
This should be fixed by https://github.com/opengisch/QField/pull/3117
@geomondego would you have a device to test this?

**Comment by geomondego** [comment]
@m-kuhn Working with last iOS version (20202990)

**Comment by m-kuhn** [comment]
@geomondego I don't think sample projects are enabled there, are they?

**Comment by geomondego** [comment]
@m-kuhn I have a shared folder in my laptop with syncthing

**Comment by m-kuhn** [comment]
@geomondego that's excellent for everyday work. I'm trying to fix editing of sample projects and am currently looking for someone to test this. If you are able to help here, I can put your device onto the internal ios tester list.

**Comment by geomondego** [comment]
@m-kuhn ok, sure. What you need?

**Comment by m-kuhn** [comment]
Can you send me the UDID of your device? (feel free to do by mail because it's potentially sensitive information).

**Comment by geomondego** [comment]
Done. Regards

**Comment by m-kuhn** [comment]
Can you try to iInstall the package from https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3117-65a95434c1b7c336b62d770cea5e07ec5ac1161b.html

It will ask you to uninstall the app before. This will cause losing all settings. Please make sure you don't put anything important at risk.
