### ISSUE TITLE
Download QFieldCloud Project in iOS test version

### ISSUE THREAD

**Issue by geomondego** [opengisch/QField#2148]
When i try to download a QFieldCloud Project,  i get the message **Project failed to download.**

Picture 1 - Message
![IMG_0512](https://user-images.githubusercontent.com/4389239/134948927-40bf8fa0-e016-4ea2-969e-d154a4cd405e.PNG)

Picture 2 - Log message
![IMG_0513](https://user-images.githubusercontent.com/4389239/134948975-b1c0e7cf-4281-43a3-a239-f7bde9925531.PNG)

Regards,
Nelson

**Comment by 3nids** [comment]
This should have been fixed in build  19343070

**Comment by geomondego** [comment]
@3nids It is working
