### ISSUE TITLE
Most of strings are not translated to Japanese language in the latest iOS version

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField#2149]
Most of strings are not translated to Japanese language in the latest iOS test flight version.

In Transifex, I have already translated all strings of app to Japanese language.

### Screenshots and GIFs

Here, I put some screenshots which are not reflected to Japanese language. I found most of strings are not still in English.

![image](https://user-images.githubusercontent.com/2639701/135040903-dca88bd3-ff40-4c8a-b24e-03b0fd8dff2e.png)

![image](https://user-images.githubusercontent.com/2639701/135040980-6d8d355b-840a-42e3-8f8c-603096ed94dd.png)

![image](https://user-images.githubusercontent.com/2639701/135041066-92ce74b8-909f-4896-af15-e9bcbe944446.png)

![image](https://user-images.githubusercontent.com/2639701/135041098-8215865c-bf05-4df8-a739-5ddfc5469a51.png)

![image](https://user-images.githubusercontent.com/2639701/135041135-b68875f0-abdd-4093-826b-abf00086b2d6.png)

![image](https://user-images.githubusercontent.com/2639701/135041186-3ba41020-d366-48e6-a510-2c8d2d51356e.png)

![image](https://user-images.githubusercontent.com/2639701/135041259-dd741ae6-60e0-4de5-805c-9b4c3a1ab462.png)

![image](https://user-images.githubusercontent.com/2639701/135041313-76329c8b-ff76-457d-9d4a-a678f7c07038.png)

![image](https://user-images.githubusercontent.com/2639701/135041349-eaee4bd0-8b93-4689-9cce-b5b9a686ac66.png)

![image](https://user-images.githubusercontent.com/2639701/135041397-a3db0787-3784-447c-9502-54da68d7cd58.png)

![image](https://user-images.githubusercontent.com/2639701/135041441-34d43ab7-d8ac-426f-b4e5-97206c2f07a5.png)

![image](https://user-images.githubusercontent.com/2639701/135041514-ce8de9a6-f461-41c6-9c8d-79ad82eb3977.png)

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

iOS Test Flight - master-dev (2c073d)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by 3nids** [comment]
This should be fixed in build 19400000.

**Comment by JinIgarashi** [comment]
@m-kuhn I saw now all translations are reflected correctly!! Thank you!!
