### ISSUE TITLE
Calendar widget

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#215]
In QGis (2.18.16), whether calendar option is checked or not in Date/Time widget, it pops up in QField (0.10.4) when clicking on the field.

### Expected behavior:

Calendar pops up if checked in date/time option in QGis ; doesn't pop up if not checked

## Additional information:

Maybe related to answer given in issue #9 (which would be nice to solve too ;) )

Thanks to all the team : you make great work !

**Comment by saemiw** [comment]
I can confirm that this is also/still the case with QGIS 3.2 and QField 0.11.6

**Comment by 3nids** [comment]
fixed
