### ISSUE TITLE
Update target API level to 30

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#2174]
![image](https://user-images.githubusercontent.com/28384354/135617871-aea70be7-0441-40d0-b2cf-f8d5f3489e14.png)

See https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by nirvn** [comment]
I suspect the greatest pain here will be changing the way we handle storage and file access.

**Comment by nirvn** [comment]
@signedav , as far as I understand from reading the part below, that flag would be ignored:

Scoped storage enforcement
Apps that run on Android 11 but target Android 10 (API level 29) can still request the requestLegacyExternalStorage attribute. This flag allows apps to temporarily opt out of the changes associated with scoped storage, such as granting access to different directories and different types of media files. After you update your app to target Android 11, the system ignores the requestLegacyExternalStorage flag.

**Comment by m-kuhn** [comment]
@nirvn shall we close this?

**Comment by nirvn** [comment]
Yep agreed.
