### ISSUE TITLE
Advanced Checkbox widget can lead to confusions

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#2176]
The "new" checkboxes are very nice, still the information can lead to confusions. Maybe it's not something that is actually true or false but instead the answer is "yes" or "no". With using strings, you could provide that when you actually store in the data "yes" or "no" but mostly you want to have your bools stored as bools. Anyway, if the question is, if a beehive is infected the answer is not "true" or "false" (well it is for us who can imagine how data is stored, but not for field workers). While you can assume how it's used when it's English, then it looks quite abstract when there is written in German "Wahr/Falsch".

![Screenshot_20211001-145822_QField](https://user-images.githubusercontent.com/28384354/135623897-67e26163-f704-49ec-a90e-de3064d803c4.jpg)

How could we handle that? Remove this information would be a pity. Having it configurable would be another (maybe rarely used) setting. Any ideas?

**Comment by signedav** [comment]
Btw. having the check-slider right next to the remember value box, could be misinterpreted as well. Having a quick look at the screenshot above could lead to the expression, that only one of the values is checked.

**Comment by nirvn** [comment]
Reminder: the old widget only showed a labeless rectangle outline, "sometimes with an x in it, sometimes not" ;) so I think using words to represent value here increased understanding for most.

On whether we should default to True/False, Yes/No, On/Off, etc., I think that's an interesting question to look at.

I'd be fine switching to Yes/No by default if you think it suits the context better. We could risk making an internal poll to see what most ppl prefer.

As long as we don't revert to a labeless rectangle outline ;)

**Comment by nirvn** [comment]
@signedav , on the remember values checkbox, IMHO it's a separate issue. It's one remaining part of the feature form UI/UX we need to rethink and improve. Contextless, labeless checkboxes are not good. I've met multiple QField users (from GIS novice to experts) who had no idea what those checkboxes were doing even after using QField for months. They just saw those at eating space.

**Comment by signedav** [comment]
I completely agree on having the androidoid (love this word) check-slider. We definitely should keep that.

But considering the labels I'm not sure. I like them to have this metainformation. But in QGIS we don't have any labels. 
![qgis_checkboxes](https://user-images.githubusercontent.com/28384354/135627402-c57a6dd7-f36c-412a-8814-befef4d4103f.png)
Not saying that's better, but it's at least what a user expects.

**Comment by signedav** [comment]
And yes, just replacing them by "yes"/"no" would lead to confusion in other context again. Coolest would be to have a setting here.

**Comment by nirvn** [comment]
For QGIS, the checkbox itself is placed right next to the label, we can't do that in QField. 

I'd been keen to add those extra default labels to QGIS too :) it's especially bad when you use those in the attribute table, with again just a rectangle.

**Comment by signedav** [comment]
Just seen that in the attribute table it uses the plain text.
![image](https://user-images.githubusercontent.com/28384354/135628284-a6edeb51-6f41-4b4c-8535-27aeeb2c5040.png)

**Comment by nirvn** [comment]
In the attribute table, what happens when you try to edit that field? I think it goes to a labeless checkbox.

**Comment by signedav** [comment]
If this would be implemented in QGIS once, don't you think it should be configurable then? 1. a representing text and 2. a setting if the label should be visible or not. And if so, then I think it should behave the same in QField?

**Comment by signedav** [comment]
I think you agree not to have a QField config consider that without having the same in QGIS. So I would either remove the label or keep it fix. But if we keep it, then what could we have to avoid the true/false confusion? 
- making the label less strong (maybe green or gray)?
- using other words (but I don't have a good idea for it)?
- ...

**Comment by nirvn** [comment]
On the basis of a firm belief from my part that we've improved things (for what it's worth :wink:), my two cents here is let's see how the users react when we release 2.0 final with this change in. I feel we might be overthinking it here. A textual representation of a boolean value (true/false) I think ends up being friendlier in this form environment than a visual metaphor ([_] vs [x]).

**Comment by signedav** [comment]
I agree that it's an improvement for most situations but sometimes it becomes very confusing. For a technical guy it's clear. Whatever the question was on a boolean you have true/fals and it's represented with checked/unchecked. But a non-technical guy takes the textoutput more serious. In German true is "wahr" and false is "falsch" (what is the  same word for "wrong").
In english it's hard to find a good example, let's try it anyway:
"Asset contains false statements?"
- [ ] false
Concentrated person in the office gets it.  Fieldworker fighting alligators in the swamp might be confused 🙃

**Comment by nirvn** [comment]
@signedav , can we close this or is this still an issue after using it for years? :)
