### ISSUE TITLE
Rethink Remember Checkboxes

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#2177]
![Screenshot_20211001-145822_QField](https://user-images.githubusercontent.com/28384354/135627739-012aa194-662e-4f26-9e4c-98bf52e8259d.jpg)

Quote myself:
> Btw. having the check-slider right next to the remember value box, could be misinterpreted as well. Having a quick look at the screenshot above could lead to the expression, that only one of the values is checked.

Quote @nirvn:
> on the remember values checkbox, IMHO it's a separate issue. It's one remaining part of the feature form UI/UX we need to rethink and improve. Contextless, labeless checkboxes are not good. I've met multiple QField users (from GIS novice to experts) who had no idea what those checkboxes were doing even after using QField for months. They just saw those at eating space.

**Comment by m-kuhn** [comment]
See also #2285

**Comment by nirvn** [comment]
Checkboxes gone in favor of clearer icons.

**Comment by suricactus** [comment]
I think we should not forget the general direction that will make it less weird with so many icons next to your widget: having a hamburger menu/long press of on the field, that shows this option. The improvements done in https://github.com/opengisch/QField/pull/5109 are still letting to suboptimal UI with a random icon next to your field.

**Comment by nirvn** [comment]
@suricactus , there's still https://github.com/opengisch/QField/issues/4084 open, fear not ;)
