### ISSUE TITLE
Look into replacing legacy java

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField#219]
we should have a look at https://github.com/opengisch/QField/blob/master/android/src/ch/opengis/qfield/QFieldActivity.java

and see if it is still needed or if there is a better (and probably cleaner) way to do it now see: https://github.com/lutraconsulting/qgis-quick-demo-app/blob/master/android/src/org/qgis/quick/MyActivity.java

**Comment by nirvn** [comment]
Done.
