### ISSUE TITLE
Feature request: Button interface for value map widgets

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#2193]
I've tried to see if this has been brought up at all for qfield or qgis and haven't really found anything, so apologies if it's a repeat.

Is it feasible/possible for there to be a button UI (similar to Option Row in ROAM) for simple list widgets like Value Map in QField? 

For rapid assessments with short lists, we find that being able to select a value with a button (all options immediately visible, one press) is much faster than selecting a value from a dropdown list (requires two separate presses, not all options immediately visible).

Of course the mobile interface adds extra limitations in terms of space, but I think there is merit in having buttons for short lists (3-5 values).

I understand QField's forms are based off QGIS widget/form settings; is it fair to assume that requesting buttons in QField will require upstream amendments in QGIS? What would be the best channels through which to get this implemented?

**Comment by m-kuhn** [comment]
That would be a great enhancement, I think it could be triggered via a new "radio button" option that would also be available for qgis.

**Comment by she-weeds** [comment]
It's definitely been puzzling - radio buttons are one of the most basic form UIs out there but QGIS has been limited to boolean checkboxes and dropdown lists this whole time. If there's a project or group out there working on buttons I'd love to support them personally. Surely it can't be too complicated to implement, compared to the tremendous overhaul of annotations done in the most recent release.

**Comment by m-kuhn** [comment]
If the demand for this is high enough I'm sure someone will contact developers and ask for a quote. If this is such a basic functionality it cannot be too complicated to find a sponsor for that.

**Comment by lp-dj** [comment]
> Certainly the use of the Value/Description setup of the Value Map widget would be useful to create abbreviations for use as button text.
> 
> I would think though once you get into scrolling territory you almost might as well use the existing drop down list UI with search function? One of the reasons I would be grateful to see button UI implemented is because several colleagues want to avoid scrolling as much as possible - it can be finicky on smaller screens or in rapid assessments.

Yes you are right @she-weeds. Personally, I would agree that you can just as well use the drop-down list with search function before you provide a new scrollable widget.

However, I also know colleagues who would like to avoid typing at least as much as scrolling ;)

Hence my idea with the categories as a compromise to allow targeted scrolling and thus shorten the process of scrolling a bit.

But I'm also undecided what I would prefer myself. I think it's a tradeoff between ease of use and greater functionality in some situations.

Probably the radio buttons suggested by @m-kuhn would fit better into the operating concept of QField.

**Comment by jpnunn** [comment]
Hi I guess this is still not possible?  This would be really useful for the ornithology team who have to quickly guess every 15 sec the height of bird (tricky I imagine!). Having 3-6 horizontal radiobuttons for each height band of the bird (and a duplicate field for each 15 second estimate) would really help the process and also allow them to visualize the height of the bird a better than drop down list as they scroll down the page.

**Comment by she-weeds** [comment]
Apologies for resurrecting an old thread, but I noticed the amazing new release 3.3.0 includes this feature: "The feature form’s value map widget gained a toggle buttons interface for faster data entry" per PR #5269 .

It looks like this request might be finally closed after 3 years (🎉), which is a fantastic job by the devs as buttons will dramatically improve data entry and elevate QField even further.

Can someone advise how to enable this in QField, though? I'm using QGIS 3.34.7 with QFieldSync 4.9.1 on Windows 10/11, and QField 3.3.1 on Android 13. 

I'm guessing the project has to be configured in QFieldSync but it looks like that feature is [yet to be released](https://github.com/opengisch/qfieldsync/pull/584).

**Comment by lp-dj** [comment]
Wow, great news! Thanks to @nirvn and team for the implementation. And thanks for the notification @she-weeds. 

[QField Sync v4.10.00](https://github.com/opengisch/qfieldsync/releases/tag/v4.10.0) is the key to success ;)

![Bildschirmfoto vom 2024-06-13 14-07-37](https://github.com/opengisch/QField/assets/80956612/bae22885-dd9f-4527-9bbb-41398633c892)

Working well so far! Two feedbacks after first short test:

- When displaying existing objects, the attributes of the ValueMap are not displayed in the new button interface as soon as the current attribute values are equal to the default values.
- Less dramatic: The delay when switching between different values in the button interface is a bit too long for my taste (at least on my Fairphone4). Is it possible to speed this up?

**Comment by nirvn** [comment]
@lp-dj , could you provide test projects or screencaat of those two issues? It's not entirely clear from your description. 

Thanks for stress testing the feature :)

**Comment by lp-dj** [comment]
@nirvn Sure, here's a quick recording:

[screen_recording_bug_button_interface_dv.webm](https://github.com/opengisch/QField/assets/80956612/8d2beba9-2500-4978-ab51-151ae9787f3f)

What can be seen:

I add an feature in the layer "Vogelbeobachtungen". The two attributes "Stadium/Geschlecht" & "Verhalten" are displayed with the new button interface. The default values for the two attributes are "Männlich" & "singend".

When creating a new feature, the default values are also displayed correctly (highlighted in green). However, when I save the feature with the default values and then open it again, I can no longer see which values are saved for "Stadium/Geschlecht" & "Verhalten" (the green background is missing) as soon as/as long as the attribute values are set to the corresponding default value.

If I set values other than the default values, the display works as expected even after reopening the attribute form.

I show this in the video by repeatedly changing, saving and reopening the feature with different values.

**Comment by mohsenD98** [comment]
Hi @lp-dj, thanks for the tests you've run so far! We've created a pull request to address the issue you're experiencing. To help confirm whether the fix is effective, could you please download the APK from [Here](https://github.com/opengisch/QField/pull/5330#issuecomment-2168248144) and test if the issue is still present? Your feedback is greatly appreciated.

**Comment by lp-dj** [comment]
@mohsenD98 Tested and approved. :wink:

Looks good! Many thanks for the quick response!

**Comment by nirvn** [comment]
This has been implemented, happy field mapping!
