### ISSUE TITLE
iOS Photo rotated 90

### ISSUE THREAD

**Issue by kevkev770** [opengisch/QField#2194]
When  take pictures with the iOS camera, the pictures are rotated by 90° in the viewer. I assume it's because Mac and other systems use different values for alignment.

### Reproduction Steps:

1. Take picture in edit mode
2. safe and have a look attributes in info view – image is rotated

### Expected behavior:

image shown as taken

### Observed behavior:

image is turned.

### Screenshots and GIFs

<img width="375" alt="image" src="https://user-images.githubusercontent.com/34672534/135871949-e5542e71-ef3a-4815-b002-061f2220e71d.png">

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** iOS "master-dev" (4174dc)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by uapmq** [comment]
Hi.
I cannot help you in anyway but I am wondering how do you manage to add a picture with the ios camera? For my project it releases the same error as in issue #2819.

Did you make some specific configuration for the picture taken by the IOS camera on the ipad to be saved/visible in Qfield ?

It would be wonderful if you could help me with this, thanks in advance.

**Comment by uapmq** [comment]
Hi, I figured it out. Deactivation of the native camera (in Qfield settings) for IOS allow Qfield to take a picture. For those who would have the same issue!

**Comment by nirvn** [comment]
@kevkev770 , is it still an issue with QField 3.3.10?
