### ISSUE TITLE
some error appear when i run  project.please tell me how to fix it.

### ISSUE THREAD

**Issue by P8CM** [opengisch/QField#22]
In file included from ../../QField/src/appinterface.h:26:0,
                 from ../../QField/src/appinterface.cpp:18:
../../QField/src/feature.h:21:24: fatal error: qgsfeature.h: No such file or directory
 #include <qgsfeature.h>
                        ^
make[1]: Leaving directory `/home/tq/QField/qfield/build-QField-Android_for_armeabi_v7a_GCC_4_8_Qt_5_5_1_d856d8-Debug/src'
compilation terminated.
make[1]: *** [appinterface.o] Error 1
make: *** [sub-src-make_first-ordered] Error 2
14:53:31: 进程"/usr/bin/make"退出，退出代码 2 。
Error while building/deploying project QField (kit: Android for armeabi-v7a (GCC 4.8, Qt 5.5.1))
When executing step "Make"
14:53:31: Elapsed time: 00:01.

**Comment by m-kuhn** [comment]
You will have to cross-compile a variety of dependencies first. It's easiest by using https://github.com/opengisch/OSGeo4A . There is unfortunately not much documentation about it.

Or you can install the apk from playstore instead.
