### ISSUE TITLE
Font Styling

### ISSUE THREAD

**Issue by lrmodesgh** [opengisch/QField#2214]
[Font styling is not reflected in Qfield]

### Reproduction Steps:

1. Added unicode compatible font in different languages for layers in QGIS
2. QGIS canvas reflects correctly
3. All other styling like size, color, buffer ... etc.. gets updated in Qfield, except the font added to the project

### Expected behavior:

I could not see the font required, which means the localization effort is consistently ruined for the end surveying user.

### Screenshots and GIFs

![Screenshot](https://files.reconstruct.how/s/xP9gbr5kxt5gBPs)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:**  master-dev : 729b80, as well as in Qfield : 1.9.6

## Additional information:

* Copying the styles is very important when it comes to typography from a design perspective. This adds more UX and helps people like me to support Qfield and Qgis to humanities scholars and activists in ground to a great extent.

**Comment by nirvn** [comment]
@lrmodesgh , QField already supports loading extra fonts. Place additional fonts (ttf or otf files) you want to use in your mobile device's /QField/fonts directory. QField will also load font files that are present in the same directory as the project file being read on your mobile device.

**Comment by lrmodesgh** [comment]
yay... .thanks a lot @nirvn i guessed but didnt tried it, and instead like a dumb, i just spent the night just looking at how to add extra fonts in android. 
he he.... 

Its straight forward for me. But for someone, who just uses QGIS and Qfield, it might feel like an additional little task. Even if its subjective, it will be of great help that deployment stage can accomplish that...

However, i am happy that i can look at my local names in neat unicode font tomorrow. 

Thanks @nirvn
