### ISSUE TITLE
A confirmation dialog box before quiting the app

### ISSUE THREAD

**Issue by ad-sige** [opengisch/QField#222]
One clic too many and you are out !
Takes time to reload the project.
(Improvment)

### Reproduction Steps:

1. Click on return button (to hide the right panel for exemple)
2. Re-clic because it's slow to hide
3. You are out ! But you did not want.s

### Expected behavior:

A pop-up shows befor quiting the app confirming if you want to quit or not.

### Observed behavior:

One clic too many and you are out !

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** Current

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
Fixed in 355c32ae25b9d338c8599805dc01a094754f268f
