### ISSUE TITLE
Text color too light

### ISSUE THREAD

**Issue by lucienicolier** [opengisch/QField#2227]
In Chinese the text color is really light, it is practically not possible to read.

### Expected behavior:

Text color darker

### Observed behavior:

In Chinese the text color is really light, it is practically not possible to read.

### Screenshots and GIFs

![Setteing interface 2](https://user-images.githubusercontent.com/50236352/137448743-790747b6-e5bb-4e59-afb1-742476c0bc55.jpg)

**QField version:** qfield-android-v2.0.8-arm64_v8a.apk

**Comment by nirvn** [comment]
@lucienicolier , is that a complaint from a user or you proactively testing things out? The 'problem' there is the font being used (provided by the OS) which evidentially isn't great. Not sure there's much we can do (I know phones in the region of the world I live in have better default fonts :) )

**Comment by nirvn** [comment]
I'm going to close this issue as the problem either is with the OS and/or Qt and font rendering, which is out of our control.
