### ISSUE TITLE
GPS horizontal and vertical accuracy not filled on update

### ISSUE THREAD

**Issue by rfazimut** [opengisch/QField#2236]
We stored horizontal and vertical accuracy retrieved from a GPS by setting default value on 2 fields using these variables:

@position_horizontal_accuracy
@position_vertical_accuracy

So they get updated, we checked the "Apply default value on update" on those field.  So, the accuray field should alwats get populated from the GPS when the feature is created or when the feature is moved at a new position.

The accuracy fields gets populated correctly when the feature is created.  When we update the feature, wether its the position or simply an attribute, the accuray fields are set back to Null.  Basically, we lose the accuracy value that we got when we created the feature the first time,

Our only alternative is to delete the feature and create a new one from scratch.

### Reproduction Steps:

1. Create a offline project for QField by using default value @position_horizontal_accuracy or
@position_vertical_accuracy and by setting "Apply default value on update" for some fields.
1. Export the projet using QfieldSync
2. Copy the projet to a mobile connected to a GPS.
2. On the mobile start QField.
3. Open the offline project.
4. Create a new feature using the GPS position. 
5. Verify that the accuracy is set correctly in the fields.
6. Select the feature created in 5.
7.  Update the position using the GPS.
8. Verify that the accuracy is set correctly in the field. -->  the values are null 

### Expected behavior:

After step 8, accuracy values should be updated when the feature set to a new position based on the GPS @position_horizontal_accuracy and @position_vertical_accuracy variables.

After step 8, accuracy values are reset to null which suggest GPS @position_horizontal_accuracy and @position_vertical_accuracy variables are not populated from the GPS during update.

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

GPS models tried:
•	https://eos-gnss.com/products/hardware/arrow-200
•	https://eos-gnss.com/products/hardware/arrow-gold

**QField version:** 1.9.6 

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]  Yes
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]  Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]  Yes

**Comment by nirvn** [comment]
This isn't a bug. When checking the apply default value on update, you're telling QField to re generate a value for those fields whenever you edit a feature. In this case, you're not digitizing anymore so there isn't any gps values to work without so result is null.

Uncheck that option. You'll end up with desired outcone.
