### ISSUE TITLE
Forced to quit in about dialog

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#224]
Must quit after going to "about" dialog

### Reproduction Steps:

1. Go to "about" dialog
2. click on "back" button

### Expected behavior:

Return in QField interface

### Observed behavior:

Show message telling to press twice the back button to quit. Forced to do that and quit the app.

**QField version:** 0.10.8_5

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by saemiw** [comment]
I agree that this is still confusing on how one should close the "about" panel depending on where you clicked last. But there has been work on it and the current warning message is at least a good information that an additonal click will close qfield (and not the "about" panel)

**Comment by signedav** [comment]
I think, this is solved with this implementation #266
