### ISSUE TITLE
Legend not responding when digitizing not finished inthe previous project

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#2252]
### Reproduction Steps:

1. Add vertex of polygon - don't finish digitizing
2. Open another project 

### Expected behavior:
On opening new project the old digitizing gets discarded.

### Observed behavior:
Cannot select layers in the new project. Legend not enabled.

**QField version:** 1.10.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files rojects, not only some files or projects: Yes

**Comment by mohsenD98** [comment]
this issue is resolved by [**this**](https://github.com/opengisch/QField/pull/5310).
