### ISSUE TITLE
Internal storage not available on iOS

### ISSUE THREAD

**Issue by tgdbepe4** [opengisch/QField#2253]
The APP is starting but clicking on local or cloud files bottom shows no reaction

**Comment by m-kuhn** [comment]
We couldn't reproduce this issue here. Is anyone able to confirm that? Do you have a reason to assume it's related to this specific ios version?

**Comment by tgdbepe4** [comment]
I have now IOS 15.2 but still the same observation. A click on "Open local file" shows no reaction.

**Comment by m-kuhn** [comment]
Interesting. Did you try with a different device too?
If yes, which iOS version and is it the same behavior?

**Comment by tgdbepe4** [comment]
No only on my iPhone 12 with IOS 15.2 but it was still the case with 15.1. The bottom "QFieldClod projects is working. I have made a registration but I don't know if I am now registered or not. If then I haven't found a way to reset my password.

**Comment by m-kuhn** [comment]
Interesting, we'll have a look at that.

You can reset your passowrd here https://app.qfield.cloud/accounts/password/reset/
If it doesn't work, please send me a notice with your email address and I'll be happy to enable an account for you.

**Comment by tgdbepe4** [comment]
Hallo Matthias
Scheint so, als dass ich keinen Account hätte, ***@***.***

Gruss 

Peter

Von meinem iPhone gesendet

**Comment by m-kuhn** [comment]
Hi Peter, can you send me a mail, the address didn't get through on github.

**Comment by 3nids** [comment]
There is an open issue on Qt to provide this functionality https://bugreports.qt.io/browse/QTBUG-67522

**Comment by m-kuhn** [comment]
Would it be possible to show the "randomly assigned home directory" in the about screen?

**Comment by m-kuhn** [comment]
A user could copy his files there if I understood this correctly?

**Comment by nirvn** [comment]
Implemented.
