### ISSUE TITLE
spatialite layers loaded through ogr broken on 1.10

### ISSUE THREAD

**Issue by vlebert** [opengisch/QField#2260]
Hi Qfield Team

Some projects based on spatialite layers shows errors on 1.10.

I tested a step back to 1.9.6 which solved the issue. Qfield Unstable is also OK

### Reproduction Steps:

I can share a project if needed.

### Screenshots and GIFs

![IMG_4978](https://user-images.githubusercontent.com/49779177/140031463-bff0294b-b154-481a-91d7-d1bed7194139.JPG)

![image](https://user-images.githubusercontent.com/49779177/140031478-2c923895-21f1-493d-844a-89e902e903ad.png)

**QField version:** 1.10

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by nirvn** [comment]
I'm 90% sure un installing QField and reinstalling 1.10 from scratch (vs update) will fix the issue here, it has to do with duplicate provider libraries from different versions.

**Comment by vlebert** [comment]
I tested on a tablet, uninstalling and reinstalling Qfield seems to solve the issue

I will confirm with more feedback from other users having the issue.

Thanks

**Comment by vlebert** [comment]
I do have a second confirmation that reinstalling can fix the issue

**Comment by nirvn** [comment]
Thanks for confirming the way out of this. Let's keep the issue open to look into root cause

**Comment by vlebert** [comment]
Hi,

I think ther is another issue related to this change : Qfield seems not able to load Spatialite Spatial Views:

Tested with 1.10 and Unstable, same issue: 

![image](https://user-images.githubusercontent.com/49779177/140302670-efd61b28-3034-4332-8fa9-eaa8fb410fd1.png)

**Comment by nirvn** [comment]
@vlebert , can you share a test project that showcases this issue?

**Comment by vlebert** [comment]
Here is a light version of the project
[example_bug.zip](https://github.com/opengisch/QField/files/7474712/example_bug.zip)

**Comment by nirvn** [comment]
Have you tried the project with? QGIS 3.22? Is it also broken on desktop

**Comment by vlebert** [comment]
No, I am on 3.16.

**Comment by nirvn** [comment]
Could you try with 3.22 and see if it's broken there? I have a feeling this might be an upstream QGIS regression. If so, it'd be good to report that there so it can be addressed before 3.22 becomes the new LTR.

**Comment by vlebert** [comment]
OK, but not sure to be able to test this before 2 weeks. I am on a laggy 4G connection and not able to download the installer right now.

**Comment by vlebert** [comment]
I did one more test : editing the project to load the layer through Spatialite connection (instead of QGIS explorer or drag & drop which is OGR provider I believe).

Loading with spatialite connection makes the layer unreadable in Qfield 1.10 (and readable in 1.9.6)

Opening the project this way gives a bit more logs on the error:
![image](https://user-images.githubusercontent.com/49779177/140319545-868f24d2-9ddd-4de5-913d-134280e02e20.png)
The spatialite provider seems unable to query ROWIDs

**Comment by nirvn** [comment]
Ok, those layers are ogr provider driven, so not linked to QGIS' own spatialite provider. 

That said, using the spatialite provider for these view based tables wouldn't work with QGIS' spatialite provider. That's fixed here:

https://github.com/qgis/QGIS/pull/45901

Is that why you were mixing spatialite and ogr providers to read spatialite datasets?

**Comment by vlebert** [comment]
I usualy use ogr provider (drag and drop is just quicker than adding a spatialite connection)

But I already experienced in the past different behaviours like one provider working only read-only with Qfield, that's why I took the habit to try both approach when facing a problem. 

So if I understand, the fix you're linking will fix in QGIS spatial views (based on ROWIDs) with QGIS spatialite provider.
This fix will follow in Qfield is that right?

Then, broken spatial views in Qfield through OGR provider remains to be fixed

**Comment by nirvn** [comment]
@vlebert , you are correct on all counts :) the OGR situation will need more investigation.

Btw, you have a great project setup going. What are you surveying?

**Comment by vlebert** [comment]
Survey operations over optical network (FTTH) roll out in rural areas (that's why we use spatialite for offline work).
Need to try Qfield cloud beta soon :)

**Comment by nirvn** [comment]
@vlebert , the last APKs in this PR (https://github.com/opengisch/QField/pull/2278) fixes the spatialite regression. It'd be great if you can confirm things are good on your end.

As for QFieldCloud, be warned: there's no coming back once you get a taste of it ;) make sure you've signed onto the waiting list to get as early an access as possible.

Thanks for the reporting and test project you provided.

BTW, you guys should consider writing a brief story on your use of QField, I'm sure your successful use of the tool would inspire many. Cheers.

**Comment by vlebert** [comment]
Thanks @nirvn , I'll check this next week.

I had a Qgis Cloud Beta invitation from @mbernasocchi in March but I didn't have the time to test it. I think it was still very rough and my tests are generaly on production project so I was a bit afraid to take the leap. But I will definitly try it in early 2022 if my invitation is still valid :)

We have a lot to say about Qfield. We were early adopters and have now around 20-25 tablets on the field daily. We are recently using it on survey in Ivory Coast where afternoon sun/heat is quite an issue for the tablets and we need to find a proper equipment...

We also developped some tricks to handle offline work and daliy syncronization. First with Seafile/Syncthing (thanks again to @mbernasocchi who gave me the tip for [Syncthing](https://syncthing.net/)).

We now host our Qfield projects on private Gitlab repos (gitlab allows up to 10go) and developped some termux scripts (with termux widget for UI) to handle synchro and picture resizing (each tablet have it's own branch and get updates from master). It's working but a bit too complicated to put in everybody's hand and I hope Qfield Cloud will simplify a lot our workflow.

Then we push the data on Postgis/Lizmap and/or on Airtable (for more interaction on the data).

I need to find the time write about all this :)

**Comment by nirvn** [comment]
@vlebert , I sure hope you and your team will write about this, sounds fantastic. As for QFieldCloud, things have progressed a lot since a few months ago. I'd consider it as being pretty close to a release candidate stage, it's been very stable in the last few weeks.

And back to the original sqlite issue, it appears the problem wouldn't be in gdal but rather with the view definition that isn't compatible with changes made in sqlite 3.36 (see this comment https://github.com/OSGeo/gdal/commit/7ca239e6fd54da817e0fc12eaf6c672cfd6efc79#commitcomment-59560368 ).

I think we'll likely revert back to 3.35.5 to give users more time to be aware of this sqlite syntax change. That said if you want your spatialite dataset to be future proof, might be worth tweaking it :)
