### ISSUE TITLE
1.10.0 release - no native camera issue

### ISSUE THREAD

**Issue by aliasatp** [opengisch/QField#2262]
Hi all, as  I mentioned in the title, after the upgrade to 1.10.0 release I relised that the no native camera option, even if I actived it in the setting panel, doesn't work or better it isn't possible to take a picture because only the "browse" icon appears.

### Reproduction Steps:

1. Activation of no native camera option (actually disable the use of native camera)
2. Try to take a picture
3. Only the icon "browser" in your device memory appears

**QField version:** 1.10.0 - ANDROID device

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]
![Screenshot_2021-11-03-17-47-31-704_ch opengis qfield](https://user-images.githubusercontent.com/62659943/140106253-f3d903b6-ac38-46ab-8a4f-b61e29bdefc2.jpg)

**Comment by nirvn** [comment]
Confirmed. Looking into it
