### ISSUE TITLE
Expression "attribute" doesn't work in new QField-Version

### ISSUE THREAD

**Issue by TSanderPGG** [opengisch/QField#2266]
We used the expression "attribute(get_feature('CSV-Table', 'speciesname', "speciesname"),'shortcut')" to get automatically the shortcut of a species name and vice versa. It worked perfectly with the old version of qfield. After the update to 1.10 the fields with this expression stay grey and one is not able to click into it nor write something into it.

### Reproduction Steps:

1. create a project with editable layer and an csv-table
2. refer in the attribute form to the csv-table with the expression from above
3. open project in qfield

### Expected behavior:

Writing the shortcut in one field and get the species name in to another automatically

### Observed behavior:

Field in QField is grey with no ability to click into it nor write something into it.

### Screenshots and GIFs

![Screenshot_20211105-091135_QField](https://user-images.githubusercontent.com/80879779/140481387-fb026a37-0f82-4a66-bf28-9c4a2139a4fd.jpg)

(don't mind the wrong form of the field "Artname", the screenshot was taken when I tried to identify the problem, normally this is also a text-editor field)

**QField version:** 1.10.0 (1da006 v1.10.0)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: As far as I observed it - yes

**Comment by nirvn** [comment]
@TSanderPGG , can you provide a test project?

In 1.10, if you have a field that has a default expression value and has the [x] apply value on update (I might misremember the label here), the field is considered read only as the value will always be expression derived.

**Comment by TSanderPGG** [comment]
Yes, I can. But I think with your answer my problem is already solved (and it's not really an issue, just unawareness). Without checking the update value box the field is no longer grey and luckily our expression seems to work also when the box is not checked!
Thank you for your reply!

[Test.zip](https://github.com/opengisch/QField/files/7481973/Test.zip)

**Comment by nirvn** [comment]
Can we close this issue then?

**Comment by TSanderPGG** [comment]
Yes, thank you!
