### ISSUE TITLE
Feedback: Preventing accidental closing of an attribute form

### ISSUE THREAD

**Issue by lp-dj** [opengisch/QField#2267]
When filling out an attribute form, it can happen that the attribute form is closed by accidentally tapping on the map. This happens regardless of whether the attribute form is already completely filled in and all hard constraints are met or not. If the latter is not yet the case, existing data entries are of course discarded again. This is especially annoying for more extensive entries like long texts.

It is unclear to me if the current behavior is a bug or intentional. Presumably it is deliberately implemented this way? However, I would suggest to keep the described behavior only if the "fast editing mode" is activated. By default, I would find it more user-friendly and "common" to ask if you want to discard the changes and close the attribute form in case an object cannot be saved due to unfulfilled constraints.

Alternatively, you could allow closing the attribute form only via the buttons (similar to the behavior with maximized attribute form), if the fast editing mode is not activated.

**Comment by dingausmwald** [comment]
Not completly the same behavior, but meeting the headline. Same happens when scrolling the attribute form down. On swiping down, applying the changes accidently happens. It's not clear why it sometimes scrolls and why sometimes swipes.

**Comment by Emmawilsonjncc** [comment]
Hi is there a solution to this issue?
