### ISSUE TITLE
Feedback: Labels of relations are not applied

### ISSUE THREAD

**Issue by lp-dj** [opengisch/QField#2268]
I find it a bit irritating that in QField instead of labels the names of relations for relation widgets are displayed in attribute form.

In QGIS the labels of relation widgets are treated the same way as the aliases of attribute widgets, which in my opinion would be the logical way for QField, too. Maybe the consideration of relation aliases in QField has simply been forgotten so far?

I can live with the current situation, only sometimes I find it a bit annoying when you try to design a nice attribute form for third parties and then labels appear there on which you have no direct influence anymore ;)

**Comment by nirvn** [comment]
@lp-dj , can you provide some screenshots here?

**Comment by nirvn** [comment]
@lp-dj , no need, this PR fixes the reported issue (https://github.com/opengisch/QField/pull/2321)
