### ISSUE TITLE
Feature request: Show feature list for categories

### ISSUE THREAD

**Issue by lp-dj** [opengisch/QField#2272]
Currently it is possible to show all features of a layer in a list by choosing a layer and then tap on "Show features list". I would like to see this also for a category created in the symbology. Currently you can click on a category, but the command is still executed on the entire layer.

**Comment by nirvn** [comment]
@lp-dj , give the APKs in this PR (https://github.com/opengisch/QField/pull/3261) a try.

**Comment by lp-dj** [comment]
Hi @nirvn, great, seems to work well!

Thanks for the implementation and that you have brought it to my attention!

My next idea would be to sort the feature list, e.g. by position or display name instead of fid.

If I understand it correctly, however, that should no longer be the content of this closed issue, right?

If you are interested, I have therefore formulated my idea on this in response to #1897 in a little more detail.
