### ISSUE TITLE
Theme-selector does not update its status automatically

### ISSUE THREAD

**Issue by lp-dj** [opengisch/QField#2277]
The map theme in the theme-selector* is not automatically updated according to the currently visible layers, etc.

\* Here I mean the dropdown list on the left under Map Theme. Please correct me if there is already another name for it ;)

### Reproduction Steps:

1. Select a predefined map theme.
2. Show an additional layer or hide a shown one (enable/disable "Show on map").
3. Choose again the same map theme as in step 1.

### Expected behavior:

I would expect a similar behavior as in QGIS:

In 2.: As soon as the displayed layers no longer correspond to the selected theme, this should also be deactivated in the theme-selector (I think the dropdown list is simply missing a "NULL" value for such cases?).
In 3.: As soon as I click again on the desired theme, it should also be activated again.

### Observed behavior:

In 2.: The theme-selector in QField, unlike its counterpart in QGIS, does not update itself on its own.
In 3.: Since the desired theme was still selected in the theme-selector by mistake, a new finger tap has no effect. So you have to switch to another theme first to be able to activate the theme selected in step 1 again.

### Screenshots and GIFs

Please let me know if my description was not understandable or clear enough, then I'll record an example video here.

**QField version:** 1.10.0 (1da006)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Was already so in version 1.9
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: As far as i can tell, yes

**Comment by nirvn** [comment]
@lp-dj , this PR (https://github.com/opengisch/QField/pull/2282) fixes the map theme combo box issue by insuring that whenever users manually toggle visibility of individual layers, QField sets the map theme to none. Thanks for the report.

**Comment by lp-dj** [comment]
You're welcome, @nirvn. Thank you for the lightning fix!
