### ISSUE TITLE
SVG symbols in the layers panel are too big and do not fit in the box provided 

### ISSUE THREAD

**Issue by Teodora18** [opengisch/QField#2286]
When using SVG symbols for vector symbology (points, marked lines and filled polygons) in QField for Android, the whole symbol do not fit in the provided box from the layers panel. It is too big and only parts of it are visible.

### Reproduction Steps:

1. Create a new project with a new vector layer (point layer, for example) in QGIS.
2. Add a new feature in the layer  and use any SVG symbol from the library for symbology.
3. Import your project in QField.
4. Open the layers panel and you will see how the symbol is cut.

### Expected behavior:

SVG symbology to fit in the box in the layers panel.

### Observed behavior:

SVG symbology is not fully visible.

### Screenshots and GIFs

Screenshot from the layers panel
![Screenshot from the layers panel](https://user-images.githubusercontent.com/72937659/140662239-42a106e6-b0a1-4ce5-b855-100934b959f7.jpg)

Screenshot from the canvas with the actual symbol
![Screenshot from the canvas with the actual symbol](https://user-images.githubusercontent.com/72937659/140662263-4c3927c2-fe66-4b0e-86a2-594bd79f953b.jpg)

[Project and layers used](https://github.com/opengisch/QField/files/7493113/qfield_svg_bug.zip)

**QField version:** 1.10.0 – Uluru on Android 11

## Additional information:
Resizing the symbol in QGIS do not change its size in QField. Trying with a different vector layer will lead to the same problem. 

* Problem started happening recently, didn't happen in an older version of QField: [Not sure]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by lp-dj** [comment]
I can confirm this issue and add that it has existed since at least version 1.4.
