### ISSUE TITLE
SVG symbols are not recognizable in the layers panel and on placing a new feature on windows

### ISSUE THREAD

**Issue by Teodora18** [opengisch/QField#2287]
When using SVG symbols for vector symbology (points, marked lines and filled polygons) in QField for Windows, the symbol is not recognizable. It is visualized as a question mark both on the map canvas and in the layers panel.

### Reproduction Steps:

1. Create a new project with a new vector layer (point layer, for example) in QGIS.
2. Add a new feature in the layer  and use any SVG symbol from the library for symbology.
3. Import your project in QField for Windows.
4. Open the layers panel and you will see a question mark instead of the SVG symbol.

### Expected behavior:

Seeing the SVG symbol visualized correctly.

### Observed behavior:

The SVG symbol is visualized as a question mark no matter what the real symbol is.

### Screenshot

Screenshot from the layers panel and the map canvas
![Screenshot from the layers panel and the map canvas](https://user-images.githubusercontent.com/72937659/140662774-d81464a5-8df6-4dd0-8be2-13195dfec485.png)

[Project and layer used](https://github.com/opengisch/QField/files/7493143/qfield_svg_bug_windows.zip)

**QField version:** 2.0.8 - beta 8 on Windows 10

## Additional information:
I suppose that once this bug is fixed, [this one](https://github.com/opengisch/QField/issues/2286) might happen.

* Problem started happening recently, didn't happen in an older version of QField: [Not sure]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by BoswachterMarc** [comment]
I had the same issue, but the solution is on our side ;-) Is the SVG symbol part of the project map? Otherwise copy it manually to that map on you're mobile. It works fine over here.

**Comment by geomondego** [comment]
I haven't tried it, but would **Embed File** be an option?

**Comment by Teodora18** [comment]
Thank you both for your recommendations. With **Embed File** it works. I have just tried it and the SVG symbols are no longer unrecognizable.

**Comment by nirvn** [comment]
@m-kuhn , I suspect the hard work you've been putting in updating builds might have had a positive impact here.

**Comment by nirvn** [comment]
@Teodora18 , this has been fixed in 2.4.X. Happy field mapping!

**Comment by Teodora18** [comment]
Thank you!
