### ISSUE TITLE
Blackout of the screen when working on the display/Zaciemnienie ekranu podczas pracy na wyświetlaczu.

### ISSUE THREAD

**Issue by Pawelt102** [opengisch/QField#2291]
Qfield version 1.10.0 unfortunately but had to uninstall.  I went back to version 1.9.6.  .  The reason is that version 1.10.0 during operation, after a while, the screen dims and therefore the visibility in the field is poor.  It is not possible to set continuous brightness because the application interferes with the brightness settings of the phone.  To brighten the screen, you need to click on the display, which changes the place on the map and then you have to return to the current location and so on each time.  This is annoying.  Please correct this error in the next update so that the screen does not go dark.  I have a samsung galaxy m51 model phone.  Regards to the Qfield crew!  Overall great app.  And one more thing, add a distance and area measurement to the application and when drawing a polygon to show the surface.

**Comment by nirvn** [comment]
@Pawelt102 , this is not an "error", it's a battery saving feature :) you can disable screen dimming in the settings panel.

**Comment by Pawelt102** [comment]
hello! :) the problem is that setting the brightness in the phone settings
does not help.  The application turns itself off after a certain moment.  I
struggled with this problem for hours and found no way.  I will put a
screenshot of the display, which even shows the interference of the QField
1.10.0 application.

pt., 12 lis 2021, 05:38 użytkownik Mathieu Pellerin <
***@***.***> napisał:

**Comment by nirvn** [comment]
@Pawelt102 , go to the QField's settings panel (not your phone's settings), and toggle off the dim brightness option.

**Comment by Pawelt102** [comment]
Why had I not noticed this before?  It's sorry, my mistake.  I close the topic.

**Comment by nirvn** [comment]
@Pawelt102 , no worries, user feedback is priceless. Glad you can go back to enjoying 1.10 :wink: . Do you think a longer timeout period (e.g. 60 sec instead of 20 sec) would be better or you simply don't want dimming at any time?

**Comment by Pawelt102** [comment]
While working, I use Qfield with the display turned on all the time.  It is the most convenient for me.  I have a phone strapped on my hand and I check and edit from time to time.

**Comment by Pawelt102** [comment]
I think 60 seconds would also be a good option

**Comment by suricactus** [comment]
@nirvn what if the setting is a slider instead of a boolean. 0 -> turn on forever, 10-60 - seconds until it turns dims?
