### ISSUE TITLE
Real-time collaboration feature

### ISSUE THREAD

**Issue by brylie** [opengisch/QField#230]
It would be cool for a team to be able to collaboratively create/edit entities in a geodatabase. E.g. the QField app could be connected to an online data source with other clients editing the data simultaneously. This would open up possibilities for team/group-based mapping efforts.

**Comment by biomap** [comment]
GeoGig for the win on this one https://github.com/locationtech/geogig

**Comment by m-kuhn** [comment]
Happy to be able to close this issue by pointing to https://qfield.cloud/
:tada:
