### ISSUE TITLE
No more picture botton

### ISSUE THREAD

**Issue by Growth64** [opengisch/QField#2306]
Hi,

Since the last update, the taking picture icon disapear from the formular. But it stills "browse from the gallery".
https://zupimages.net/up/21/46/3m06.jpg

**Comment by nirvn** [comment]
@growth64 , known regression. It'll be addressed in the next release. In the meantime, you can get the button by reverting the QField camera settings back to "native" if that works for you.

**Comment by Growth64** [comment]
Thanks it works, I didnt know this settings.
