### ISSUE TITLE
Swipe on a formular

### ISSUE THREAD

**Issue by Growth64** [opengisch/QField#2314]
It's not a problem but maybe a improvement to make.

When you are on editing and add a item, Qfield opens the formular. If you have a lot of attributs, you have to swipe down to display others attributs. Problem is that swipe down on the top of the forumar is also a shortcut for 'validate' the item.
It could be boring when you are outdoor.

**Comment by lp-dj** [comment]
If I may add:

To my feeling, horizontal swiping doesn't feel completely consistent yet.

With an open attribute form, you can currently swipe to the right and left on two levels:

- to the next or previous tab by swiping to the right or left in the lower area in the attribute form itself
- through the list of tabs above in the header of the attribute form

I've often caught myself wanting to swipe through the current selection list of features at the very top of the screen now, too. Here, however, you can only navigate through the list using the arrow buttons.

**Comment by nirvn** [comment]
This has been fixed in QField's latest version. Thanks for the report.
