### ISSUE TITLE
Qfield not recording point data while locked to gps location 

### ISSUE THREAD

**Issue by EmilyNGH** [opengisch/QField#233]
QField will not record point data when locked to gps location error message as follows

**OGR
Unbalanced call to leave UpdateMode() w.r.t. enterUpateMode()
Qfield
Could not save changes. Rolling Back 
Commit errors:
ERROR: 1 feature(s) not added - geometry type is not compatible with the current layer**

### Reproduction Steps:

1. Enable GPS
2. Lock cursor to location 
3. Select file to write to (shape)
4. Add point
5. Enter data in pop up window
6. Save point 
7. Error message above displays and will not save point   

Running on a Samsung Tab S2 8.0 Android 7.0 

If the cursor is not locked to location the point will record and save without issue 
Line and polygon files will save while locked to location
All files are in the same projection 
The point data is X and Y only (no z data)
The files are saved on the internal storage of tablet, not a SD card
I have been running Qfield on tablet for the last 5 months without issue and older project files that previously worked will no longer record point data

**QField version:** [0.10.4]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
It's probably related to this

> The point data is X and Y only (no z data)

we'll need to make sure to strip the Z part of the data before handing it internally from QField to QGIS (or make QGIS more tolerant in the data it accepts).

As an intermediate workaround, I'd propose to switch to a dataformat which supports Z.

**Comment by saemiw** [comment]
I can confirm the "issue" - we also have only x- and y-coordinates.

**Comment by m-kuhn** [comment]
Can you remind me, that happens with spatialite files, correct?

**Comment by saemiw** [comment]
Yes...its spatialite (data.sqlite - created by qfieldsync from geopackage). But for us at the moment no "urgent" issue.

**Comment by Domszi** [comment]
Hi, 
I have the same error, on xperia z1 compact, with android 5.1.1.
What can I do, what does it mean exactli:
>  I'd propose to switch to a dataformat which supports Z.

I`m waiting for your responds!
Thanks for your help,
Peter 

**QField version: [0.10.9]**
