### ISSUE TITLE
Option to set max number of lines shown for Widget Type Relation Editor

### ISSUE THREAD

**Issue by jfbourdon** [opengisch/QField#2333]
When using a Relation Editor type widget with a many to one relation, the maximum number of entries shown before scrolling become needed is of 4 (see image below). We would like to see this limit increased to 15 or 20.

![multiple_lines](https://user-images.githubusercontent.com/32580398/144277531-7320c9ab-1503-4fb6-bdeb-e5bef64a9930.png)

If it's a hardcoded limit, where should I look in the code to edit this value? I suppose it has more to do with the maximum heigh of box before it becomes scrollable than with the number of entries. We might then try finding a way to fund a feature request for having the ability to change this value per widget. Thanks for any hints.

**Comment by m-kuhn** [comment]
The height is defined in the widget, see here: https://github.com/opengisch/QField/blob/master/src/qml/editorwidgets/relationeditors/relation_editor.qml#L16
The tricky bit will be where to make it configurable.

**Comment by nirvn** [comment]
@jfbourdon , you'll be happy to know this is now a project configuration that you can tweak using qfieldsync. Closing as implemented. Cheers

**Comment by suricactus** [comment]
Documented here: https://docs.qfield.org/get-started/tutorials/get-started-qfs/#configuring-maximum-items-visibility-for-qfield
