### ISSUE TITLE
Add support for Flatgeobuff format

### ISSUE THREAD

**Issue by mpoza** [opengisch/QField#2341]
Format is getting more and more attention and I believe is quickly becoming mainstream. Performance is very good and file size is small enough. When opened in Qgis it also doesn’t modifiy its date and time like with gpkg which is good if you have real-time synchronisation active (Qnap, Dropbox, box etc.).

**Comment by nirvn** [comment]
@mpoza , QField already supports the format and will read such layers when opening a project file. PR #2350 adds individual flatgeobuff (i.e. *.fdb) dataset opening.
