### ISSUE TITLE
 After about 20 seconds, the screen suddenly goes dark.

### ISSUE THREAD

**Issue by queenmedley** [opengisch/QField#2342]
[Short description of problem here]
 After about 20 seconds, the screen suddenly goes dark.

### Reproduction Steps:
1. launchig app or open project.
2. do nothing just watching for a while.( over 20sec)

### Expected behavior:
According to the Android screen settings, in my case, the screen should not go dark for 5 minutes.

### Observed behavior:
After about 20 seconds, the screen suddenly goes dark.
It is not turn-off screen,, just 90% darken.
when touching the screen, screen get brighten  again.
And can't find option to control time
If I try to adjust the brightness in the brightness settings, this message appears.
"You cannot adjust the brightness because another app is using the brightness."

**QField version:** 
1.10.0 - Uluru 

## Additional information:
I tested it with galaxy note 9 and galaxy tab s7, both have same problems.

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
I have surffering since 1.10.0 - Uluru
 
* Problem can be reliably reproduced, doesn't happen randomly: [No]

* Problem happens with all files and projects, not only some files or projects: [yes]

**Comment by Ipickedausername** [comment]
Hello, 

Since the release of the new version of QFIELD (1.10.0), there is an option  in Settings, "Dim screen when idling" ("If enabled, the screen brightness will be dimnmed after 20 seconds of inactivity to preserve battery"). 

So you can disable this option to avoid this. 

Bye !
