### ISSUE TITLE
app often crashes and close particularly after pinch to zoom and click on the object in map

### ISSUE THREAD

**Issue by BGianni** [opengisch/QField#235]
I use it on tablet Android 7.1.1.

The error in a logcat is very generic:

F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 28381 (QtMainThread)

**Comment by m-kuhn** [comment]
Thanks for the feedback. Is there more context after this line in the logcat? Something like [here](https://github.com/opengisch/QField/issues/133#issuecomment-312561792)

**Comment by BGianni** [comment]
Complete logcat:
`03-09 09:06:48.660 642-3276/? D/GameManagerService: identifyGamePackage. ch.opengis.qfield
03-09 09:06:48.727 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 1
03-09 09:06:48.892 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 0
03-09 09:06:48.965 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 1
03-09 09:06:49.102 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 0
03-09 09:06:49.861 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 1
03-09 09:06:50.034 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 0
03-09 09:06:50.129 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 1
03-09 09:06:50.293 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 0
03-09 09:06:50.387 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 1
03-09 09:06:50.628 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 0
03-09 09:06:50.713 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 1
03-09 09:06:50.951 7802-7802/ch.opengis.qfield D/ViewRootImpl@61375c6[QtActivity]: ViewPostImeInputStage processPointer 0
03-09 09:06:51.058 7802-7826/ch.opengis.qfield A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7826 (QtThread)
                                                       
                                                       [ 03-09 09:06:51.061   236:  236 W/         ]
                                                       debuggerd: handling request: pid=7802 uid=10195 gid=10195 tid=7826
03-09 09:06:51.079 1759-1759/? E/audit: type=1400 audit(1520582811.069:521): avc:  denied  { search } for  pid=7932 comm="debuggerd" name="ch.opengis.qfield" dev="mmcblk0p28" ino=198251 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.1.1_0003 audit_filtered
03-09 09:06:51.082 1759-1759/? E/audit: type=1400 audit(1520582811.069:522): avc:  denied  { search } for  pid=7932 comm="debuggerd" name="ch.opengis.qfield" dev="mmcblk0p28" ino=198251 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.1.1_0003 audit_filtered
03-09 09:06:51.082 1759-1759/? E/audit: type=1400 audit(1520582811.069:523): avc:  denied  { search } for  pid=7932 comm="debuggerd" name="ch.opengis.qfield" dev="mmcblk0p28" ino=198251 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.1.1_0003 audit_filtered
03-09 09:06:51.083 1759-1759/? E/audit: type=1400 audit(1520582811.069:524): avc:  denied  { search } for  pid=7932 comm="debuggerd" name="ch.opengis.qfield" dev="mmcblk0p28" ino=198251 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.1.1_0003 audit_filtered
03-09 09:06:51.083 1759-1759/? E/audit: type=1400 audit(1520582811.069:525): avc:  denied  { search } for  pid=7932 comm="debuggerd" name="ch.opengis.qfield" dev="mmcblk0p28" ino=198251 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.1.1_0003 audit_filtered
03-09 09:06:51.083 1759-1759/? E/audit: type=1400 audit(1520582811.069:526): avc:  denied  { search } for  pid=7932 comm="debuggerd" name="ch.opengis.qfield" dev="mmcblk0p28" ino=198251 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.1.1_0003 audit_filtered
03-09 09:06:51.083 1759-1759/? E/audit: type=1400 audit(1520582811.069:527): avc:  denied  { search } for  pid=7932 comm="debuggerd" name="ch.opengis.qfield" dev="mmcblk0p28" ino=198251 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.1.1_0003 audit_filtered
03-09 09:06:51.083 1759-1759/? E/audit: type=1400 audit(1520582811.069:528): avc:  denied  { search } for  pid=7932 comm="debuggerd" name="ch.opengis.qfield" dev="mmcblk0p28" ino=198251 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.1.1_0003 audit_filtered
03-09 09:06:51.084 1759-1759/? E/audit: type=1400 audit(1520582811.069:529): avc:  denied  { search } for  pid=7932 comm="debuggerd" name="ch.opengis.qfield" dev="mmcblk0p28" ino=198251 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.1.1_0003 audit_filtered
03-09 09:06:51.183 7932-7932/? A/DEBUG: pid: 7802, tid: 7826, name: QtThread  >>> ch.opengis.qfield <<<
03-09 09:06:51.190 7932-7932/? A/DEBUG:     #03 pc 0001c7b3  /data/app/ch.opengis.qfield-1/lib/arm/libcrystax.so (abort+26)
03-09 09:06:52.970 642-7933/? W/ActivityManager:   Force finishing activity ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity
03-09 09:06:52.984 642-7933/? D/WindowManager: [VIRTUALSCREEN] setFocused() :: mFocusedApp = AppWindowToken{d1bebde token=Token{16e7f19 ActivityRecord{2ccbe60d0 u0 ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity t448}}}, newFocus = AppWindowToken{74c47b token=Token{1c9140a ActivityRecord{e90715fd0 u0 com.sec.android.app.launcher/.activities.LauncherActivity t444}}}
03-09 09:06:53.043 642-2004/? I/WindowManager: WIN DEATH: Window{609ffebd0 u0 SurfaceView - ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity}
03-09 09:06:53.043 277-304/? I/SurfaceFlinger: id=22 Removed SurfaceView - ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity (2/5)
03-09 09:06:53.046 277-7386/? I/SurfaceFlinger: id=23 Removed SurfaceView - ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity (1/4)
03-09 09:06:53.046 277-7386/? I/SurfaceFlinger: id=22 Removed SurfaceView - ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity (-2/4)
03-09 09:06:53.054 642-1995/? I/ActivityManager: Process ch.opengis.qfield (pid 7802) has died(214,765)
03-09 09:06:53.055 642-4011/? I/WindowManager: WIN DEATH: Window{9f072fad0 u0 ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity}
03-09 09:06:53.055 642-4011/? D/WindowManager: disposeInputChannel mInputChannel: 9f072fa ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity (server)
03-09 09:06:53.056 277-402/? I/SurfaceFlinger: id=21 Removed ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity (1/3)
03-09 09:06:53.058 277-1663/? I/SurfaceFlinger: id=21 Removed ch.opengis.qfield/org.qtproject.qt5.android.bindings.QtActivity (-2/3)
03-09 09:06:53.157 642-674/? D/WindowManager: openInputChannel mInputChannel: 74eebd7 Application Error: ch.opengis.qfield (server)
03-09 09:06:53.202 642-674/? V/WindowManager: Relayout Window{74eebd7d0 u0 Application Error: ch.opengis.qfield}: viewVisibility=0 req=512x172 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x110 fmt=-3 wanim=0x1030392 surfaceInsets=Rect(2, 2 - 2, 2) needsMenuKey=2 naviIconColor=0}
03-09 09:06:53.203 277-277/? I/SurfaceFlinger: id=25 createSurf (5x5),1 flag=4, Application Error: ch.opengis.qfield
03-09 09:06:53.451 642-674/? D/WindowManager: finishDrawingWindow: Window{74eebd7d0 u0 Application Error: ch.opengis.qfield} mDrawState=DRAW_PENDING
03-09 09:06:53.460 642-674/? D/WindowManager: finishDrawingWindow: Window{74eebd7d0 u0 Application Error: ch.opengis.qfield} mDrawState=HAS_DRAWN
03-09 09:06:53.517 277-277/? D/SurfaceFlinger:   Display[0] configurations (* current):
                                                   * 0: 768x1024, xdpi=131.804993, ydpi=132.028000, refresh=16666667
                                                 numHwLayers=5, flags=00000000
                                                   type   |  handle  | hint | flag | tr | blnd |   format    |     source crop (l,t,r,b)      |          frame         | name 
                                               -----------+----------+------+------+----+------+-------------+--------------------------------+------------------------+------
                                                      HWC | b64a3400 | 0002 | 0000 | 00 | 0100 | RGB_888     |  128.0,  171.0,  896.0, 1195.0 |    0,    0,  768, 1024 | com.android.systemui.ImageWallpaper
                                                      HWC | b64a3460 | 0002 | 0000 | 00 | 0105 | RGBA_8888   |   50.0,   65.0,  719.0,  958.0 |    0,    0,  768, 1024 | com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity
                                                     GLES | b64a3340 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  176.0,  516.0 |  292,  274,  454,  749 | Application Error: ch.opengis.qfield
                                                     GLES | b64a2e00 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,   24.0, 1024.0 |  7
03-09 09:06:53.530 277-277/? D/SurfaceFlinger:  455,  755 | Application Error: ch.opengis.qfield
                                                     GLES | b64a2c80 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,   24.0, 1024.0 |  744,    0,  768, 1024 | StatusBar
                                                FB TARGET | b64a26e0 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  768.0, 1024.0 |    0,    0,  768, 1024 | HWC_FRAMEBUFFER_TARGET
`

**Comment by m-kuhn** [comment]
The later one doesn't include the SIGSEGV line from your first response. Is it complete?

**Comment by signedav** [comment]
Hi @BGianni 
Do you have any news regarding these crashes? What version of QField you tested?

**Comment by BGianni** [comment]
I tested last version 0.10.9 .
I'm not able to solve this problem "Fatal signal 11" and "Fatal signal 6"
Android 7.1.1

**Comment by signedav** [comment]
I got similar errors on one device (not on another) with a checkout of the code I made on the start of the month. But not with the last official release 0.10.9

Some catlogs I stored are these:

Bei der Nodebo-Karte:

```

E/lights  (  968): write_int failed to open -1

E/lights  (  968): write_int failed to open -1

E/File    (31321): fail readDirectory() errno=2

E/com.samsung.app(29338): [AccuTab_Magagine]>>> UIMK:1250 [0:0] time : 12:22

E/Watchdog(  968): !@Sync 552 [03-07 11:22:12.360]

F/libc    (31321): Fatal signal 11 (SIGSEGV), code 2, fault addr 0xa11a5e54 in tid 31392 (QtThread)

E/        (  340): ro.product_ship = true

E/        (  340): ro.debug_level = 0x4f4c

E/audit   ( 1910): type=1701 msg=audit(1520421737.269:249): auid=4294967295 uid=10192 gid=10192 ses=4294967295 subj=u:r:untrusted_app:s0 pid=31392 comm="QtThread" reason="memory violation" sig=11

[...]

E/android.os.Debug(  968): ro.product_ship = true

E/android.os.Debug(  968): ro.debug_level = 0x4f4c

E/lowmemorykiller(  317): Error writing /proc/31321/oom_score_adj; errno=22

```

Beim HB_resti projekt ohne karte, wenn ins Menu:

```

E/PBSessionCacheImpl( 1731): sessionId[7614538860519518] not persisted.

E/samsungRecord(  350): miccalib file can't created. (/data/snd/miccalib.txt)

E/ACDB-LOADER(  350): Error: ACDB AudProc vol returned = -19

```

Im OSM Projekt:

```

E/Watchdog(  968): !@Sync 588 [03-07 11:40:12.432]

E/File    ( 3224): fail readDirectory() errno=2

E/Watchdog(  968): !@Sync 589 [03-07 11:40:42.434]

E/com.samsung.app(29338): [AccuTab_Magagine]>>> UIMK:1250 [0:0] time : 12:41

F/libc    ( 3224): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 3258 (QtMainThread)

E/        (  340): ro.product_ship = true

E/        (  340): ro.debug_level = 0x4f4c

E/audit   ( 1910): type=1701 msg=audit(1520422865.959:253): auid=4294967295 uid=10193 gid=10193 ses=4294967295 subj=u:r:untrusted_app:s0 pid=3258 comm="QtMainThread" reason="memory violation" sig=11

E/android.os.Debug(  968): ro.product_ship = true

E/android.os.Debug(  968): ro.debug_level = 0x4f4c

```

Vogelwarteprojekt beim schnellen Auszoomen ohne Map:

```

E/com.samsung.app(29338): [AccuTab_Magagine]>>> UIMK:1250 [0:0] time : 13:06

E/Watchdog(  968): !@Sync 640 [03-07 12:06:12.582]

F/libc    (11286): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 11341 (QtMainThread)

E/        (  340): ro.product_ship = true

E/        (  340): ro.debug_level = 0x4f4c

E/audit   ( 1910): type=1701 msg=audit(1520424375.759:254): auid=4294967295 uid=10195 gid=10195 ses=4294967295 subj=u:r:untrusted_app:s0 pid=11341 comm="QtMainThread" reason="memory violation" sig=11

E/android.os.Debug(  968): ro.product_ship = true

E/android.os.Debug(  968): ro.debug_level = 0x4f4c

```

I will do more investigation ASAP...

**Comment by m-kuhn** [comment]
Could you install the builds from this pull request (download the armv7 package),
https://github.com/opengisch/QField/pull/247#issuecomment-373998244

It's very likely that they resolved this issue.

**Comment by signedav** [comment]
First small test has been successful. I'll make more tests with locally created builds.

**Comment by signedav** [comment]
I think this is solved. Can you confirm @BGianni ?

**Comment by BGianni** [comment]
@signedav yes now work. Thank you
