### ISSUE TITLE
Possible issue with tabs in a form

### ISSUE THREAD

**Issue by gioman** [opengisch/QField#2361]
This is what I observed today:

I prepared with the D&D designer in QGIS a form with two tabs, so far so good also in QField.

Then I added a new field, and left it out of the tabs > in QField the tabs where completely ignored and everything was shown as if no D&D designer was used. Is this expected?

QField 2.0.8

**Comment by VxTedxV** [comment]
related to #2044 & #1025 ?

**Comment by gioman** [comment]
Yes, is the same as https://github.com/opengisch/QField/issues/1025 thanks for noticing.
