### ISSUE TITLE
Improve visibility of temporary tracking (line) when adding points manually

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#2362]
When manually adding a track line (adding point by point), it is difficult to see the line that was already tracked before ending the track/line. When adding the points to build the track line as one is walking along the track, it is very handy that each time when adding a point, the recent added point is highlighted for a moment. Each time - before ending the track - the temporary line is also extended/drawn but this line is nearly visible. It would be very handy for fieldworkers that this line would be more visible.

### Reproduction Steps: 

see screen recording
1/ Start adding a line in QField by manually adding points along the way
2/ Observe how the added points are highlighted and a temporary small line is build while adding those points
3/ The temporary line is nearly visible

### Expected behavior: 

while adding points manually, the highlighting of the added point is very good but the temporary line (before ending the track) should be more visible. When it is more visible, this is - aside from the highlighted points - a confirmation for the fieldworker that the line is drawn. Often this is not visible and the fieldworker is not sure if the last added point was registered.

### Observed behavior: 

the temporary line is nearly visible

### Screenshots and GIFs

https://drive.google.com/file/d/19n4f75FO3LQSCaw-BmWXEBgbSTOrQARW/view?usp=sharing

**QField version:** 2.0.8 (a44914 v2.0.8)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@BoswachterMarc , things should have improved by this PR (https://github.com/opengisch/QField/pull/2756), give it a try and let us know.
