### ISSUE TITLE
ability to turn off the whats new popup at startup

### ISSUE THREAD

**Issue by alansaviolobo** [opengisch/QField#2364]
Everytime you open qfield, the whats new popup shows up with no option to turn it on.
its ok if it shows up whenever the app has updated but it is annoying otherwise.

**Comment by suricactus** [comment]
> its ok if it shows up whenever the app has updated but it is annoying otherwise.

This is how it is intended to behave. Can you share the your QField version and device?

**Comment by alansaviolobo** [comment]
Qfield Version "2.0.8" (a44914 v2.0.8)

My device is Unihertz Titan ( https://www.unihertz.com/collections/smartphones/products/titan )

**Comment by suricactus** [comment]
Did you ever clicked the "ok" button in the bottom?

**Comment by alansaviolobo** [comment]
yes. that is the only way to get rid of the box.
now that you mentioned it, i tried clicking at the side and that also got
rid of the box.
but either ways, it shows up again on next startup.

Regards,
Alan Lobo

**Comment by suricactus** [comment]
Did you try to clear the app data and/or reinstall from scratch?

**Comment by alansaviolobo** [comment]
yes actually. I tried that when trying to resolve another issue.

**Comment by m-kuhn** [comment]
Does the app remember when you change your settings?

**Comment by alansaviolobo** [comment]
yes. it remembers the settings.

Regards,
Alan Lobo
