### ISSUE TITLE
pr2376 Custom font invalid

### ISSUE THREAD

**Issue by xBcai** [opengisch/QField#2377]
pr2376 Custom font invalid
![IMG_20220101_072400](https://user-images.githubusercontent.com/66826351/147840982-3b1e6fd5-102d-4896-a7f3-04ba79fa5248.jpg)

**Comment by nirvn** [comment]
@xBcai , these APKs should fix the regression:

https://github.com/opengisch/QField/pull/2376#issuecomment-1003497735

Feel free to comment in open PRs when you see regressions. And thanks for testing things out!

**Comment by xBcai** [comment]
Thanks. It's normal
