### ISSUE TITLE
Improving duplicate feature

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#2387]
Hello ! 

For now, when we duplicate a geometry, the new one is superimposed to the last one. 
I have some ideas to make it more usefull and easy to use. 

Show, after a long press on one entity (when one entity selected), a listing of action : 
- Delete
- Move the geometry
- **Duplicate at my position**
- **Duplicate to a new position** (then we can choose on the map where to put the new point)
- **Duplicate at the same position**

In the window where entities are listed, when an entity is "checked" (with the checkboxe on the left), giving the same options (and if possible, not via a drop-down list, but directly in the UI (banner on the top of the screen ?). 

And finaly, during duplication, allow the user to change the content of the fields and to check the "repeat checkbox" of theses fields.

I hope that I'm not doing a duplicate post ! 

What do you think about it ? 

Thanks for your attention.

**Comment by m-kuhn** [comment]
Hi, duplicated features stay selected after duplication, so they can be moved and their attributes mass edited.

I think that should respond to your requirements?

**Comment by Ipickedausername** [comment]
Hi, 

Thank you for your answer.
After you said this, I made few tests. 

Indeed, the entity is still selected, but it isn't working very well. For exemple, you need to uncheck / check the entity to allow the moving option (or else the option is grayed out). 
Also there is no option to duplicate at my position (then, when you move the map / zoom in / zoom out, the entity disapear out of the screen.

Anyway, thank you very much for this information, it was one of the most annoying issue I had on field word ! 

Bye !

**Comment by suricactus** [comment]
@Ipickedausername the selection problem was detected by me too and will be fixed soon.

**Comment by Ipickedausername** [comment]
Hello, 
Perfect then ! Thank you. 
I'll close this issue. 

Bye !

**Comment by Ipickedausername** [comment]
When modifying attributes of an entity, we cannot use repeat checkboxes, but I think it can be mentionned in another issue, because it doesn't only appear in duplicate feature.
