### ISSUE TITLE
Allow track on point geometry

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#2388]
Hello, 

We can record the movement of the GPS for polygons and lines. Could it be also allowed for points ? 

It would be particularly interesting when we want to save informations automatically calculated like coordinates, altitude, etc.

Thank you for your attention. 

Bye

**Comment by nirvn** [comment]
@Ipickedausername , your wish has been granted thanks to the QGIS usergroup Switzerland. Feel free to test the APKs in this PR (https://github.com/opengisch/QField/pull/3247) and provide feedback.

Closing this issue as duplicate of https://github.com/opengisch/QField/issues/1921 .
