### ISSUE TITLE
Functionality to pause/resume position tracking

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#2390]
Hello, 

Is it possible to allow the user to continu recording and modify the geometry, after stoping tracking. 

Something realy interesting would be to add options like : 
- Start tracking
- Pause tracking (then allow the user to modify the geometry by adding / deleting sommets)
- Resume tracking (tracking is resumed at the last sommet)
- Stop tracking

And to every geometry, allow the possibility to "Resume tracking", so the same entity can be modified in several steps if needed. 

I thank you for your attention, 

Have a good day !

**Comment by nirvn** [comment]
@Ipickedausername , implemented, hope you've been enjoying the functionality :)
