### ISSUE TITLE
Cannot open local projects in last iOS testing version

### ISSUE THREAD

**Issue by geomondego** [opengisch/QField#2391]
After update iOS testing version to 019520360, i can no longer open any of my local projects.
For any project, the message received is the same as shown in the image below. 

![IMG_0537](https://user-images.githubusercontent.com/4389239/148543454-7706c737-90a3-4023-b1ff-648f55b96636.PNG)

Regards,
Nelson

**Comment by m-kuhn** [comment]
Did this work before @geomondego ?

Possibly related to https://github.com/opengisch/QField/issues/2253

**Comment by geomondego** [comment]
> Did this work before @geomondego ?
> 
> Possibly related to #2253

@m-kuhn yes, it was working previously. I can still browse the local files 

![img1](https://user-images.githubusercontent.com/4389239/148675685-3903cb28-5efd-4e1f-9aea-e6d713844fd5.png)

**Comment by M-Rick** [comment]
I do have the same problem whatever the project I'm gonna try. It works perfectly with QField for Android or with Input
![IMG_1850](https://user-images.githubusercontent.com/2520948/154553088-d9b5739e-a840-489d-968c-a7238dac9d4e.PNG)
![IMG_1851](https://user-images.githubusercontent.com/2520948/154553099-23383816-0075-410b-a9d2-c9e946c70546.PNG)
![IMG_1859](https://user-images.githubusercontent.com/2520948/154553106-b7b41260-7d06-4866-b422-4cd48c778aeb.PNG)
.

**Comment by mbernasocchi** [comment]
We had some more happening in a course with a iPad Pro, IOS 15.3.1

**Comment by 3nids** [comment]
QFieloCloud is working.
Local files are indeed an issue.
Closing this one (duplicate) in favor of the original issue https://github.com/opengisch/QField/issues/2253
