### ISSUE TITLE
Enabling user/password prompt for postgresql layers

### ISSUE THREAD

**Issue by dukytony** [opengisch/QField#2392]
This is more of a feature request post.

1. open qfield project with online postgresql/postgis layers
2. A user/password prompt pops up before opening the project
3. Projects opens the designated layers with the right id user

I set up a multi user GIS using QGIS and postgresq/postgis online layers. The GIS is accessed with QGIS on desktops and Qfield on android tablets for fieldwork.

Each different user has a customized access to each layers via rls policies.

I would like for the users to be able to type their id and password at the opening of the project on qfield so that each user could use any tablets. Also this would save me a lot of time because I wouldnt have to preset the id/password in each qgis/qfield project everytime the project needs an update (forms, style, and so on).

Thanks a lot guys!

**Comment by TeoGoddet** [comment]
Hello, 
Would a PR going in this direction be accepted ?

**Comment by ZsanettMed** [comment]
Great news: the feature you requested is already in the pipeline for our upcoming release! Should you have any more suggestions, don't hesitate to contribute them on the [QField Idea Platform](https://ideas.qfield.org/).

Best,
Zsanett

**Comment by tonyduky** [comment]
That's great news indeed!
Please let me know when this feature is up and running so I can do a feedback on it!

Thanks a lot for all of your work guys!

**Comment by nirvn** [comment]
Implemented, will be available in QField >= 3.4. Happy field mapping!
