### ISSUE TITLE
Can't load Qfield for windows anymore

### ISSUE THREAD

**Issue by dukytony** [opengisch/QField#2393]
So I installed Qfield for windows a few months back then it stopped working for some reason.

I'm using win 10.

Here is a screenshot of the console : 

![image](https://user-images.githubusercontent.com/96209495/148678323-1c158c38-7076-4e68-a205-444f1f45ac65.png)

Thanks a lot for your help !

**Comment by m-kuhn** [comment]
How exactly is it not working?

Are you experiencing https://github.com/opengisch/QField/issues/1885 (see https://github.com/opengisch/QField/issues/1885#ref-issue-940013403 for a workaround)

**Comment by dukytony** [comment]
The console stays as on the screenshot and the qfield windows stays blank and I can't access it.

**Comment by m-kuhn** [comment]
>  the qfield windows stays blank and I can't access it.

can you add a screenshot of this? thanks

**Comment by dukytony** [comment]
https://youtu.be/ZPATiWyr-eg

**Comment by m-kuhn** [comment]
Did you try the workaround from https://github.com/opengisch/QField/issues/1885#ref-issue-940013403 ?

**Comment by dukytony** [comment]
Alleluiah!

i worked with deleting x y width registry entries

I had the feeling it had to do with multiple screen desktop.

Thanks a lot mathias!

**Comment by m-kuhn** [comment]
@dukytony are you able to reproduce this issue by attaching an external screen, starting qfield, closing qfield, removing the external screen, or similar?
Or even manipulating the values in the registry where you fixed them?

I have prepared a potential fix and it would be really nice if you could test this version so we know that this problem is gone.

**Comment by dukytony** [comment]
yeah i can try that. 

Not sure how to use the .apk though (not that of a geek yet)

**Comment by m-kuhn** [comment]
That's for android only.
Here is the windows build
https://github.com/opengisch/QField/suites/4937748438/artifacts/142953339

**Comment by dukytony** [comment]
yup, it seems like it's working on a 2 screen setup on win 10.
Could be interesting to try it on 3 or 4 screen setups still.

here is what i tested:

1. open qfield on main screen
2. move qfield windows on second screen
3. close qfield
4. unplug second screen
5. open qfield
6. it's opening on main screen
7. close qfield
8. plug in second screen
9. open qfield
10. it's still opening on main screen

**Comment by m-kuhn** [comment]
Excellent, thank you very much for taking the time to test.
