### ISSUE TITLE
2D points are generated on 3D layers

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#2399]
If a layer has z coordinates, it is filled from gnss data whenever available.
If a feature (point) are drawn manually on a PointZ layer, a Point without Z is generated instead.

This causes hickups in further processing in QGIS 

https://github.com/qgis/QGIS/issues/46808

Proposal: promote points to pointz and fill z with nan before saving.

**Comment by nirvn** [comment]
@m-kuhn , fixed many moons ago.
