### ISSUE TITLE
add screen rotation

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField#24]
dump android < 4.3 and set android:screenOrientation to
"fullUser" If the user has locked sensor-based rotation, this behaves the same as user, otherwise it behaves the same as fullSensor and allows any of the 4 possible screen orientations. Added in API level 18.

**Comment by m-kuhn** [comment]
Should we implement this?

Are there really users with Android < 4.3 which actually have working installations?

**Comment by mbernasocchi** [comment]
10% of our users are < 4.3

**Comment by m-kuhn** [comment]
10% of the installations. The actual users will be minus another few percent who only get a "too many open libraries" #6.

**Comment by mbernasocchi** [comment]
For reference this implies that we drop support for android < 4.3, which is ok.
