### ISSUE TITLE
Sometimes QField show `NaN m` in scalebar

### ISSUE THREAD

**Issue by suricactus** [opengisch/QField#2408]
Better hide the scalebar or show something better than `NaN`.

[qfield_0000_dependencies.zip](https://github.com/opengisch/QField/files/7876250/qfield_0000_dependencies.zip)

![image](https://user-images.githubusercontent.com/2820439/149644896-4c025d31-aefa-41e2-a5aa-77a85185e9bf.png)

**Comment by nirvn** [comment]
When does that happen?

**Comment by suricactus** [comment]
When I open the project, I have seen this in the past too. Cannot reliebly reproduce.

Just hiding the scalebar if NaN is calculated should be enough to fix all the cases.
