### ISSUE TITLE
Windows version: Bluetooth API requires Windows 10

### ISSUE THREAD

**Issue by ntrip6** [opengisch/QField#2415]
Installed on MS Surface 64bit running Windows 8.1 and app will not start.
![image](https://user-images.githubusercontent.com/480545/150015357-21adb786-ae0c-4588-97b9-9827267bc120.png)

Is it necessary to use a Bluetooth API that is Win10 only? Due to this requirement many useful field devices (older rugged devices) are excluded. QField otherwise has relatively low hardware requirements. 

Version: using the latest version from
https://nightly.link/opengisch/QField/workflows/vcpkg/master/QField-dev-x64-windows-Release.zip

**Comment by m-kuhn** [comment]
Thanks for reporting this, for context and a workaround by deactivating Bluetooth, refer to https://github.com/GIS4WRF/gis4wrf/issues/103

**Comment by ntrip6** [comment]
Thank you @m-kuhn. Given that many of the RTK GNSS units use Bluetooth connections so disabling all BT would be a less preferred solution. Interestingly QGIS doesn't have this issue on this Win8 tablet so if QField cannot support bluetooth on pre-Windows 10 hardware I guess I would just run QGIS itself.

**Comment by m-kuhn** [comment]
If the topic is RTK GNSS, then indeed deactivating is not an option and this is something where development is needed for Windows.

**Comment by dani1967** [comment]
> Thanks for reporting this, for context and a workaround by deactivating Bluetooth, refer to [GIS4WRF/gis4wrf#103](https://github.com/GIS4WRF/gis4wrf/issues/103)

The suggested solution

> I've "solve" this on my PC:
> 
> Go to c:\Python37\Lib\site-packages\PyQt5\Qt\bin\ (or where your python installed in) and rename
> 
> Qt5Bluetooth.dll to Qt5Bluetooth.dll1

 don't work for qfield., Qfield check Qt5Bluetooth.dll before start.

**Comment by nirvn** [comment]
@ntrip6 , I believe this should be fixed by now having moved to Qt6. Can you confirm?
