### ISSUE TITLE
[QField-DEV][GUI] Icon and description Duplication for storage

### ISSUE THREAD

**Issue by jonnyforestGIS** [opengisch/QField#2428]
Name for storage is equal and points to different directions.

### Reproduction Steps:

1. Open QField-DEV
2. Go to Local Storage
3. Same name and description:
   Internal Storage - points to internal storage
   **Qfield files diretory - points to internal storage
   Qfield files diretory - points to sd card**

### Expected behavior:

The third icon called as external storage ou sd card?

### Screenshots and GIFs

![photo_2022-01-21_11-41-02](https://user-images.githubusercontent.com/4480601/150521862-c0c76fb8-5ebd-4a5f-b821-1291553499e5.jpg)

**Equipment:** Huawei  MediaPAd T5 10.1' Model AGS2-W09 / EMUI 8.0.0 (Android 8.0.0)

**QField version:** [master-dev ea33e5)]

## Additional information:
* Using Portuguese (pt-pt) interface
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by jonnyforestGIS** [comment]
Thanks for quick feedback. Can we close this?

**Comment by nirvn** [comment]
Yep
