### ISSUE TITLE
Back button of feature list becomes previous feature button when last feature in list is reached

### ISSUE THREAD

**Issue by blacktesta** [opengisch/QField#2445]
Back button ("<-") of  feature list grabs previous feature button ("<") functionality when last feature in list is reached with next button (">") of a feature list.

### Reproduction Steps:

1. Select several features
2. Open attribute form for some feature
3. Tap next feature button until you reach last feature and tap next feature button again

### Expected behavior:

Qfield does nothing or goes back to the first feature.

### Observed behavior:

Qfield returns to feature list. When you tap back button ("<-") on top of list it works like previous feature button (watch in attached video)

### Screenshots and GIFs

https://user-images.githubusercontent.com/74047515/151766651-5067f1e8-26b9-4d5e-8adc-60b31fb443eb.mp4

**QField version:** 2.0.10 - Dev (268e5d)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: haven't tested
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@blacktesta , fixed by this PR (https://github.com/opengisch/QField/pull/2755), thanks for reporting.
