### ISSUE TITLE
Impossible to select last square pointer of polyline in vertex tool after node adding

### ISSUE THREAD

**Issue by blacktesta** [opengisch/QField#2447]
If i added new node to any polyline segment and then want to select last square pointer to add node at the end of line. I can't do this.

### Reproduction Steps:

1. Add new node to any segment of polyline 
2. Try to select last square pointer at the end of line with next (">") button

### Expected behavior:

Qfield selects last square pointer.

### Observed behavior:

Qfield can't select last square pointer because next button is inactive on penultimate square pointer (watch in video).

### Screenshots and GIFs

https://user-images.githubusercontent.com/74047515/151786489-d4834cd6-2e0a-4d4d-a08d-65348561cafd.mp4

**QField version:** 2.0.10 - Dev (268e5d)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: haven't tested
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by blacktesta** [comment]
While I was doing some testing of this bug a couple of times I caught another bug. Square and circle pointers of vertex tool didn't appear when using it fo the first time for polyline (watch in attached video at 00:14). But i can't replicate it for now.

https://user-images.githubusercontent.com/74047515/151788243-efa0f55e-5905-4f8e-a637-1d86cfcde64b.mp4

**Comment by blacktesta** [comment]
Fixed

**Comment by suricactus** [comment]
@blacktesta I just want to share I am super happy that you continuously test QField versions and close your tickets when you find them fixed! Highly appreciated!

**Comment by blacktesta** [comment]
@suricactus It's the least I can do. I'm glad if it's beneficial.
