### ISSUE TITLE
CRS Transform error 

### ISSUE THREAD

**Issue by giuenrico93** [opengisch/QField#2476]
Hi, 
I have a question about QGIS 3.16 and QFIELD 1.10.0. 
I have already created several projects then imported into QFIELD to collect data in the field, and then synchronize with the project on the computer.
I am having the following problem, which has never happened before: I have created a project, with 4 layers (all belonging to the same geopackage) and one of them is a point layer. I collected my points in the field using QFIELD and then synchronized everything with the project on the computer. I then made some changes on the computer, specifically I added a couple of fields to the point layer and added a couple of points. I then created a new project for QFIELD and uploaded it to the smartphone.
When I open it on smartphone with QFIELD it loads everything correctly except the point layer which loads with 0 points. If I try to open the attribute table it doesn't open and the attached log message appears.
What does it mean? I did not make any changes to the reference systems. The project is in epsg 4326 and the point layer in epsg 32632. 
On the pc everything works correctly, the only problems are using QFIELD 
Thanks!

### Screenshots and GIFs

![Screenshot_20220201-130952](https://user-images.githubusercontent.com/81111629/152123338-34eb83d6-42f2-4b8d-9525-47e6eef4017a.png)

**QField version:**  1.10.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: yes
* Problem can be reliably reproduced, doesn't happen randomly: no
* Problem happens with all files and projects, not only some files or projects: no

**Comment by nirvn** [comment]
@giuenrico93 , have you given QField 2.0 a try? Feel free to attach a test project here so we can do further testing.
