### ISSUE TITLE
Can't access any local files

### ISSUE THREAD

**Issue by Dubhain** [opengisch/QField#2480]
Since updating to 2.0.11 - beta I can no longer work with any files in local storage. Mysteriously, the changelog lists this as a 'Feature'  - "direct storage access is disabled for now", but I've not been able to find any information about why this functionality has been reduced nor what the cryptic "...for now" might mean.

Is there some discussion of this change someone could direct me to? Or, if simple, could anyone explain why it's happened and whether anything is planned to fix it.

Thanks

**Comment by geomondego** [comment]
@Dubhain Try to open like explained in the attached image

![IMG_20220204_114533](https://user-images.githubusercontent.com/4389239/152525020-da761df8-36d0-471f-bd31-4431ff1a9488.jpg)

**Comment by Dubhain** [comment]
> Try to open like explained in the attached image

Thanks. I'd got that far by trial and error. I'm not sure if some further step is required that I'm missing, but this just seems to copy a version of the project into Qfield's data folder.

**Comment by veroniqueC** [comment]
Hy,

I have the same problem. Should i understand that is no more possible to work on an external SD card?

**Comment by nirvn** [comment]
@veroniqueC , please read this blog post (https://www.opengis.ch/2022/03/05/qfield-users-sit-down-we-need-to-talk-about-storage-access-on-android%ef%bf%bc/), it'll explain the changes surrounding storage access on devices running Android >= 10.

The TLDR from the post: _Since November 2021, Google has enforced new storage access limitations for apps published on its Play store which prohibits direct storage access on Android 11 and above forcing QField to adapt and rely on importing projects and datasets to access those._

I highly recommend reading the whole thing, it's quite informative.
