### ISSUE TITLE
Qfield closes when opening on Samsung Galaxy Tab Active 2

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#2483]
Qfield bèta 2.0.8 and QField Dev both closes immediately on the above mentioned tablet type when opening the app (before opening a local or cloud project!).
The cloud project(s) were functioning and synchronizing before. The problem started yesterday 3 february.
I removed the QField app and reinstalled it but the problem persists (also with the latest 2.0.11 version). I sent some feedback with the app pop-up.

### GIF
https://drive.google.com/file/d/1UkjISmsqDqbn8Gg54wuVD84nnXtVYKkt/view?usp=sharing

**QField version:** 2.0.8 (a44914)
**Tablet** SM-T395, version Ine UI 1.1, Android 9

## Additional information:
The problem does not exists on a Samsung Galaxy Tab Active Pro SM-T545 version One UI 3.1 and Android 11.
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes (I tried it on 2 tablets)
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by xBcai** [comment]
qfield-v2.0.11-armv7 flash back when starting. Please check it if you have time. Thanks

**Comment by m-kuhn** [comment]
Related to https://github.com/OSGeo/PROJ/issues/2996

**Comment by mascarcelen** [comment]
Hola, soy Miguel Angel, yo también he descargado e instalado el 5/2/2022 en dos tablet Galaxy Tab A 2016 SM-T585 Android 8.1.0 Qfiel beta y Qfield Dev y nada mas arrancar se cierran con el mensaje "Qfiel se ha detenido".
Alguna solución ?
Nota: no soy informático.

**Comment by m-kuhn** [comment]
For the moment the only possibility is to download an older working release from https://github.com/opengisch/QField/releases (under Assets -> qfield-version-**armv7**.apk), it would be great if someone could find the latest working release and post a direct link here.

**Comment by BoswachterMarc** [comment]
> For the moment the only possibility is to download an older working release from https://github.com/opengisch/QField/releases (under Assets -> qfield-version-**armv7**.apk), it would be great if someone could find the latest working release and post a direct link here.

I will try to go back in time ;-).  I had 2.0.8 installed on those tablets (because of cloud support) so will start with for example 2.0.4

![image](https://user-images.githubusercontent.com/57868975/152642675-1bcb0773-6355-48c8-86e2-a3a0db3178f7.png)

**Comment by BoswachterMarc** [comment]
> For the moment the only possibility is to download an older working release from https://github.com/opengisch/QField/releases (under Assets -> qfield-version-**armv7**.apk), it would be great if someone could find the latest working release and post a direct link here.

I tried 2.0.4 and 2.0.7 bèta releases. **They both work (no crash on opening the app)**. They also allow me to open a local file. Cloud projects are not available for the moment, it looks like the server of QFieldCloud is down (cant't reach it with QField, nore with desktop).

**Comment by mascarcelen** [comment]
Muchas gracias. Como última ayuda, (no soy informático) el archivo que baje, debo guardarlo en la tablet ?

**Comment by m-kuhn** [comment]
> 

Sí, es un instalador android, se abre directamente en el tablet

**Comment by mascarcelen** [comment]
Muuuuuchas Gracias

**Comment by mascarcelen** [comment]
Os informo que ha funcionado perfectamente..........

**Comment by m-kuhn** [comment]
> funcionado perfectamente

I think this needs no translation :rocket:

**Comment by BoswachterMarc** [comment]
The QFieldCloud server is back online and I could also download the cloud project with the 2.0.7 bèta release! That's a good workaround :-)

**Comment by m-kuhn** [comment]
@BoswachterMarc 
Here's a completely random attempt to fix this, I don't have a possibility to check that locally
https://github.com/opengisch/QField/pull/2485#issuecomment-1030697052

**Comment by BoswachterMarc** [comment]
> @BoswachterMarc Here's a completely random attempt to fix this, I don't have a possibility to check that locally [#2485 (comment)](https://github.com/opengisch/QField/pull/2485#issuecomment-1030697052)

Thank you Matthias, I will try the latest QField bèta release and check if the issue is solved

**Comment by BoswachterMarc** [comment]
> @BoswachterMarc Here's a completely random attempt to fix this, I don't have a possibility to check that locally [#2485 (comment)](https://github.com/opengisch/QField/pull/2485#issuecomment-1030697052)

I upgraded the 2.0.7 QField version (latest working release) to the new 2.0.11 version, but still, the 2.0.11 crashes on opening...

**Comment by m-kuhn** [comment]
The attempts are in #2485 , no release yet. But I think the problem is not yet solved.

**Comment by nirvn** [comment]
@BoswachterMarc , have you had the time to try the APKs in the PR @m-kuhn linked too yet?

**Comment by BoswachterMarc** [comment]
> @BoswachterMarc , have you had the time to try the APKs in the PR @m-kuhn linked too yet?

I tried these :-) https://github.com/opengisch/QField/issues/2483#issuecomment-1030621450

**Comment by she-weeds** [comment]
Can anyone help test the latest release on a Galaxy Tab? I have some active projects going so am reluctant to jinx things. 

When I accidentally updated to 2.0.11 on a Samsung Galaxy Tab 10.5 running Android 10 via the beta channel on Google Play without having checked the latest issues on github, and of course it didn't work, trying to downgrade from it was a pain and ate up a couple of hours of my time...

I couldn't sideload any of the lower version apks from github - not even using adb without other things glitching - eventually I found out I had to unsubscribe from the beta channel on Google Play, as otherwise Android pretended as if 2.0.11 was still installed even when I tried removing all trace of it from the device. (We try to install and update via Google Play for the benefit of other less tech-savvy consultants)

**Comment by Smithsinarazz** [comment]
Thanks for this, that's really useful. I've had the same problem and switching to an earlier version seems to have worked.

**Comment by nirvn** [comment]
@she-weeds , by "not working" you mean it crashes?

**Comment by she-weeds** [comment]
> @she-weeds , by "not working" you mean it crashes?

Yes, the app would just force close. The same happened when I uninstalled and tried reinstalling by sideloading the apks from github (Android would still think it was 2.0.11?) When I tried force downgrading using adb -r -d it technically worked in that it was the correct version installed, but then every couple of seconds I would get a android.process.media has stopped error. Tried doing all the usual (clear cache and data in Google Play, Google Services Framework) but it would only go away if I uninstalled the app. 

Eventually I figured Google Play has it in its head that I should only be allowed to run 2.0.11 on this device if I'm in the beta program so it finally worked when I opted out, waited about 30 minutes for the changes to process, then installed 1.10.0. (My personal android phone is rooted and runs a much older ROM so I had no idea how things have changed, can't manually downgrade apks nowadays huh...)

**Comment by nirvn** [comment]
@she-weeds , could you try the APKs here (https://github.com/opengisch/QField/pull/2485) and tell us whether you still see the crash on app launch?

**Comment by nirvn** [comment]
@she-weeds , actually you can ignore this request, if 1.10 works for you, the problem has to be elsewhere.

**Comment by nirvn** [comment]
@she-weeds , please try these APKs: https://github.com/opengisch/QField/pull/2527#issuecomment-1043972638

**Comment by nirvn** [comment]
@she-weeds , @BoswachterMarc , can either of you test the latest set of APKs linked to in the comment above?

**Comment by BoswachterMarc** [comment]
> @she-weeds , @BoswachterMarc , can either of you test the latest set of APKs linked to in the comment above?

I will try in a week or so, I don't have the tablet at hand.

**Comment by stcz** [comment]
I have also some Samsung Galaxy Tab Active 2.
I tried the [Linked APK](https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2527-288a374b685c906cc3707fa15148ee2da617c3a7-arm-android.apk) unsuccessfully.
Beta 2.0.7 is the latest working, i also tried 2.0.13 and 2.0.12 unsuccessfully.

**Comment by stcz** [comment]
I tested some versions again:
2.0.7 -> Working 
2.0.8 -> Working
2.0.9 -> Working
2.0.10 -> Not Working
2.0.11 -> Not Working
2.0.12 -> Not Working
2.0.13 -> Not Working

**Comment by stcz** [comment]
2.0.14 still not working. 
Is there anything i can do to help to resolve the Issue?
[Here is a log file from startup](https://github.com/opengisch/QField/files/8410858/qfield.log).
Thanks for your help!

**Comment by pigreco** [comment]
I confirm, I have just installed 2.0.14 and after installation the program closes.

**Comment by notgernot** [comment]
Same here i use the SM-T395 with the latest update to Android 9
1.10.0 - is working
2.0.9 - is working with some small bugs
everything above 2.0.10 including 2.0.14 crashes imediately after the start

**Comment by nirvn** [comment]
Public service announcement to people who have reported crashes here: the APKs in this PR (https://github.com/opengisch/QField/pull/2773) should fix the crasher.

**Comment by nirvn** [comment]
@stcz , @notgernot , @BoswachterMarc , can one of you guys confirm the crash is gone when installing QField 2.1?

**Comment by m-kuhn** [comment]
Or @pigreco ...

**Comment by pigreco** [comment]
@m-kuhn @nirvn 
it works great!
you are fantastic!!!
![image](https://user-images.githubusercontent.com/7631137/164886854-6a78756a-e2e9-4290-8827-9e35dd9c2569.png)
