### ISSUE TITLE
Windows (Beta) x64 Installer Issues

### ISSUE THREAD

**Issue by amgiss** [opengisch/QField#2492]
Windows (Beta) x64 Installer Issues

### Reproduction Steps:

1. Start to Install QField 0.1.1-win64
2. Install required C++ Runtime
3. Reboot as requested

### Expected behavior:

QField Installer continue to install QField  when relaunched as C++ requirements were previously installed

### Observed behavior:

Installer launches C++ setup again with remove/repair option, dismissed C++ installer and QField setup completes.

The Start Menu shortcut is broken as the program installs into a "usr" directory inside the QField directory and this sub-directory is missing from the shortcut.

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes, previous installer was a zip
* Installed on Windows 10 x64

**Comment by m-kuhn** [comment]
Here is the test build
https://nightly.link/opengisch/QField/actions/runs/1818612717/QField-dev-x64-windows-Release.zip

**Comment by amgiss** [comment]
Thanks for the quick fix.

I have installed the test build.

The QField install completes when the MSVCRT installer is cancelled.

The start menu shortcut is still broken with a missing path separator. I'm getting this path in the shortcut - "C:\Program Files\QField\usrbin\qfield.exe"

**Comment by m-kuhn** [comment]
Thank you for the testing. Here is another one which hopefully should have the path fixed
https://nightly.link/opengisch/QField/actions/runs/1822036716/QField-dev-x64-windows-Release.zip

**Comment by amgiss** [comment]
Thanks for the updated build. The start menu shortcut now works.
