### ISSUE TITLE
value relation widget issues

### ISSUE THREAD

**Issue by zvaragabor** [opengisch/QField#2493]
Hey folks,

I've encountered an issue with value relation widget. Actually it is a multiple issue.
1. It won't remember the value I choose, it switches to an other value from the list right away. Even if I type the value in the box, or choose it from the search window. It seem so me that Qfield switches to the first value of that type from the csv table.
https://youtu.be/_xvaum9aA8M
2. If I manage to choose a value, it cannot be edited (like it could not recognize my finger touching it).
https://youtu.be/58rG7RntfWA
3. I cannot search in the search window, it won't give me suggestions (only if a filter expression criteria is met based on an other attribute)
https://youtu.be/dhsmXheH6GI

Just to clarify things a bit, I have a point shapefile, with two attributes (relevant in the issue).

1. A Value map widget, with 13 different values.

![kép](https://user-images.githubusercontent.com/99144850/152757894-7a31e126-0334-4203-9ff4-59ef99ab9dc7.png)

2. A Value Relation widget, where I have a csv, attribute structure shown in pic below.

![kép](https://user-images.githubusercontent.com/99144850/152750725-07c27c1f-d2c7-4869-aa63-85711bcd4ba9.png)

![kép](https://user-images.githubusercontent.com/99144850/152751359-06a7bf5a-1082-4b55-80a2-7977730aa9b5.png)

The goals, is to be able to filter the second attribute based on the value set in the first attribute. But If I do not set any value in the first attribute, the second attribute should let me search/choose from the whole list. The issues mentioned above are issues encountered during this process.

Sorry guys, I can't really explain the issues in detail, as english is not my native language, and it's a bit hard to make a reasonable sentence with these technical terms. :)

Everything's working fine in QGIS.

I've attached the project.

**QField version: "1.10.0" (1da006 v.1.10.0)

Problem can be reliably reproduced, doesn't happen randomly: [Yes]

[zvaragabor_Issue_project.zip](https://github.com/opengisch/QField/files/8011201/zvaragabor_Issue_project.zip)

**Comment by BoswachterMarc** [comment]
Just wondering... In your value relation for the Biotika, the key column is the field "ID". But I think the key is not really a key or ID because **it is not unique** (I see 4 times value 5, 18 times value 1, 4 times value 13...). In other words, perhaps it's the project which causes the problem?

By the way, I love the Salamandra salamandra ;-)

![afbeelding](https://user-images.githubusercontent.com/57868975/153275765-c10ceb6c-5f87-47c5-b3e0-78daf0796f77.png)

**Comment by BoswachterMarc** [comment]
> Just wondering... In your value relation for the Biotika, the key column is the field "ID". But I think the key is not really a key or ID because **it is not unique** (I see 4 times value 5, 18 times value 1, 4 times value 13...). In other words, perhaps it's the project which causes the problem? You should check if the values are really saved as you wish in QGis. I experienced once that I thought the information was saved correctly but it didn't (values were wrong in the attribute table).
> 
> By the way, I love the Salamandra salamandra ;-)
> 
> ![afbeelding](https://user-images.githubusercontent.com/57868975/153275765-c10ceb6c-5f87-47c5-b3e0-78daf0796f77.png)

See the following printscreens and this article: https://www.northrivergeographic.com/archives/qgis-3-2-drive-down-lists-aka-value-relation-widget

![image](https://user-images.githubusercontent.com/57868975/153279923-d94f98ac-395d-4f36-b26f-95fe4cfb1bc5.png)

![image](https://user-images.githubusercontent.com/57868975/153279295-871a36c3-24b7-4249-91c0-503c4c37465f.png)

![image](https://user-images.githubusercontent.com/57868975/153279445-88078e76-2764-4b7e-8a13-1eabec9b88d1.png)

**Comment by nirvn** [comment]
@zvaragabor , is this still an issue with QField 3.3.10?
