### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by ylatis** [opengisch/QField#25]
I had the first session with QField it is really great!.. I have a project in QGIS with Greek characters (UTF-8). When loaded to the QField the Greek characters are unreadable.
Any ideas what is wrong?.

**Comment by m-kuhn** [comment]
Would be great if you could share a sample dataset

**Comment by ylatis** [comment]
Thank Matthias for your response.

Problem solved. The loaded shapefile was converted to System character set  by mistake and not UTF-8.

Reloaded with greek character set and it is ok.

 

Thanks

 

 

Stelios Papageorgiou

SSM Computer Systems Ltd

P.O.Box 20314

2150, Nicosia

Cyprus

Tel + 357 22 44 82 44

Fax + 357 22 34 21 40
