### ISSUE TITLE
Qfield not opening external camera app on OnePlus 8 Pro Android 11

### ISSUE THREAD

**Issue by Firefly86** [opengisch/QField#2503]
Qfield master-dev (d7be25) does not open the external camera app on an OnePlus 8 Pro running Android 11. Project is working with Samsung Phones. Qfield 1.10.0 does open the external camera app using the same project on OnePlus 8 Pro. 

### Reproduction Steps:

1. Setup Pictures in QGis following https://qfield.org/docs/de/prepare/add-1-n-pictures.html
2. Transfer to Phone using Qfield Cloud.
3. Set to use native camera
4. Try to take a picture 

### Expected behavior:

Opening the native camera app.

### Observed behavior:

White screen 

### Screenshots and GIFs

![Screenshot_20220209-213306](https://user-images.githubusercontent.com/3370704/153287833-8bceae06-6018-418f-9bc8-bbc103fbf93f.jpg)

**QField version:** Qfield master-dev (d7be25)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Working with "old" Qfield 1.10.0
* Problem can be reliably reproduced, doesn't happen randomly: only on OnePlus 8 Pro Smartphone
* Problem happens with all files and projects, not only some files or projects: Happens with different project as well

**Comment by m-kuhn** [comment]
Could you download and try this app: https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-2486-b0a5fca01c35c977f0c92fe78305220c7466baed-arm64_v8a.apk ?

**Comment by m-kuhn** [comment]
Does the internal camera work?

**Comment by Firefly86** [comment]
In the downloaded version the camera is working correctly.
