### ISSUE TITLE
How to increase timeout download on Qfieldcloud Android apps?

### ISSUE THREAD

**Issue by lkino** [opengisch/QField#2505]
We have create new projet from windows Qgis application and then upload to Qfield cloud whithout any issue. But when we try to open the project on Android application, we have an error message ("download error. Exportation issue"). We have try to download form WIFI an from 4G connexion with the same. This project is haevy 700Mo, we don't have any problem with a light project (28Mo).

### Reproduction Steps:

1. Create project on Qgis
2. Connect to Qfield Sync
3. Upload project to cloud OK (700Mo)
4. Open project on Qfiel cloud Andoid app
5.  Try to download project: error

### Expected behavior:

Let the enought time to download the entire project maybe add task download bar

### Observed behavior:

After more or less 1 minute, error message: "download error. Exportation issue"

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by suricactus** [comment]
Hey @lkino , we have made quite some changes in this area since you posted your question. Do you still experience the problem?

**Comment by lkino** [comment]
@suricactus, Sorry, I thought I was already replied. We have tested and now it is working thanks! 
I have put some request to improve apps: 
- Could choose in a project witch layer we want download (not compulsory all)
- Have a progress download bar 
I addition,when we have seen some roles (like: ispector, admin, editor, reader....) to adjust right into the application but doesn't find any description of these roles. And, on each change line there is a box whitch one is disable... Is it for approuve or reject each change? That can be very interresting to have double check and to avoid to integrate error from field engineer?
Best regards ans thanks for this application!

**Comment by suricactus** [comment]
Glad it works fine!

> - Could choose in a project witch layer we want download (not compulsory all)

This is not planned for now. You can add it as an idea here https://github.com/opengisch/QField/discussions or contact us directly if you are interested in funding such feature.

> - I addition,when we have seen some roles (like: ispector, admin, editor, reader....) to adjust right into the application but doesn't find any description of these roles. And, on each change line there is a box whitch one is disable... Is it for approuve or reject each change? That can be very interresting to have double check and to avoid to integrate error from field engineer?
Best regards ans thanks for this application!

I see you have already opened a new discussion topic, I will answer there https://github.com/opengisch/QField/discussions/2626 .

So now I will close this issue and feel free to open a new one if you experience any problems.
