### ISSUE TITLE
Failed to build for arm64-android

### ISSUE THREAD

**Issue by lionkor** [opengisch/QField#2523]
I'm trying to build QField from source and get this error:

```
-- Package arm64-android-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/ninja install -v
    Working Directory: /home/lion/QField/vcpkg/base/buildtrees/fontconfig/arm64-android-dbg
    Error code: 1
    See logs for more information:
      /home/lion/QField/vcpkg/base/buildtrees/fontconfig/package-arm64-android-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:53 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:21 (vcpkg_install_meson)
  scripts/ports.cmake:142 (include)


Error: Building package fontconfig:arm64-android failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fontconfig
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[fontconfig]+Build+error
including:
  package: fontconfig[core]:arm64-android -> 2.13.94#5
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 68b5cb602 2022-01-16 (4 weeks ago)

Additionally, attach any relevant sections from the log files above.
-- Running vcpkg install - failed
CMake Error at vcpkg/base/scripts/buildsystems/vcpkg.cmake:831 (message):
  vcpkg install failed.  See logs for more information:
  /home/lion/QField/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:26 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
```

### System Info

- ArchLinux x86_64, kernel 5.16.9
- gcc/g++ 11.2.0
- CMake 3.22.2
- aqtinstall(aqt) v2.0.6 on Python 3.10.2 [CPython GCC 11.1.0]
- Android NDK version 21.3.6528147
- GNU Make 4.3

### Reproduction Steps:

1. Install cmake, aqtinstall, run `aqt install-qt linux android 5.14.2 -m qtcharts`, android NDK via QtCreator's SDK/NDK installer
2. Run `export ANDROID_NDK_HOME=/home/lion/Android/Sdk/ndk/21.3.6528147`
3. clone the QField repository *recursively* & cd into it
4. run CMake
```
cmake -S . \
      -B build \
      -D VCPKG_TARGET_TRIPLET=arm64-android
```
5. The error above pops up.

### Expected behavior:

It should configure the build correctly.

### Observed behavior:

It fails to build fontconfig. I've looked for this issue, could not find anything like it. The `Unix Makefiles` error is weird, too.

### What I need

It would be great if someone could look at this and let me know if I did anything fundamentally wrong, or if the buildsystem is broken, or what the issue is. I've been at this for a few days and am out of options.

### Logs & dumps

[package-arm64-android-dbg-out.log](https://github.com/opengisch/QField/files/8080395/package-arm64-android-dbg-out.log)
[vcpkg-manifest-install.log](https://github.com/opengisch/QField/files/8080401/vcpkg-manifest-install.log)
[cmake.log](https://github.com/opengisch/QField/files/8080411/cmake.log)
[vcpkg-bootstrap.log](https://github.com/opengisch/QField/files/8080413/vcpkg-bootstrap.log)
[aqtinstall.log](https://github.com/opengisch/QField/files/8080412/aqtinstall.log)

**Comment by Aqibiweb** [comment]
I have also same issue during Window configuration for Window build.

**Comment by lionkor** [comment]
I figured it out, I was building from master. Only the latest release tag works, in this case v1.10.0

**Comment by Aqibiweb** [comment]
Thanks for replying, I hope this will also work for me.
