### ISSUE TITLE
Retrieve username or password

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#2525]
I have a collaborator who forgot his password (or username). I can't find a way that he can ask for a new password (not in the app, not on the QFieldCloud website/dashboard).
Is is possible to enable such a possibility or do I need to delete the user on the QFieldCloud collaborators list and add him again (with the same e-mail)?

Thank you

**Comment by suricactus** [comment]
If I understand you correctly, you can already achieve the same:
![image](https://user-images.githubusercontent.com/2820439/154366959-329da2ab-284b-4908-9170-dad69be362d8.png)

> do I need to delete the user on the QFieldCloud collaborators list and add him again (with the same e-mail)?

This will not do much, you just remove an already registered user from your project. Their user account and email are still there.

**Comment by BoswachterMarc** [comment]
I probably overlooked the solution because for collaborators there is no
need to go the the QFieldcloud website/dashboard.

Thank you for pointing out. This wil do 👍

Best regards,
Marc


Op wo 16 feb. 2022 23:22 schreef Ivan Ivanov ***@***.***>:

**Comment by BoswachterMarc** [comment]
Having the option 'forgot password' in QField (link to the QFieldcloud
site/dashboard) could be a enhancement.

Regards,

Op do 17 feb. 2022 07:27 schreef Marc de Boswachter <
***@***.***>:

**Comment by suricactus** [comment]
> I probably overlooked the solution because for collaborators there is no need to go the the QFieldcloud website/dashboard.

I think there is one misconception that seems to being confusion. Your project collaborator or organization member are just regular QFieldCloud users - they can have their own projects and their own organizations just like you. The only difference is that they have limited access to your projects, e.g. they cannot delete or rename your project, depending on their role. This means you don't "control" their accounts in any way - passwords, avatars, their own projects - all of these is their own concern, you just let them use your own projects.

On the reset pwd on QField - I do agree, we will add the button before official release. Please consider the web UI the main interface to deal with QFieldCloud.

**Comment by BoswachterMarc** [comment]
I agree, this is my misconception! Thank you for pointing out.
