### ISSUE TITLE
No puedo subir y actualizar proyectos

### ISSUE THREAD

**Issue by mascarcelen** [opengisch/QField#2529]
No se que ha pasado, ni que he borrado pero estoy toda la tarde y no me funciona ni la creación de proyectos, actualización o carga a la nube. Quiero subir un proyecto a la nube y me da el siguiente error :
![3](https://user-images.githubusercontent.com/79381149/154865933-d13c36c0-c680-412e-b3df-e1e4b7607a55.png)
![2](https://user-images.githubusercontent.com/79381149/154865935-6a5494b9-3a03-4b1a-9a96-bb4c860e4268.png)
![1](https://user-images.githubusercontent.com/79381149/154865937-3e0c47aa-8fd1-41d3-a54b-3956621016a3.png)
![4](https://user-images.githubusercontent.com/79381149/154865993-0c762bab-c1a4-44e4-8821-9ecc421389de.png)

**Comment by mascarcelen** [comment]
Quiero crear desde el complemento QfiedlSync un nuevo proyecto y me da este error:
![5](https://user-images.githubusercontent.com/79381149/154866194-58613097-dc3c-492f-9575-1facd0e2af73.png)

Esto me agota ¡¡¡¡¡¡¡¡

**Comment by nirvn** [comment]
@mascarcelen , I believe this has been fixed in the latest release of the qfieldsync plugin , please re-open if it's not the case.

Also, help yourself, update to the latest 3.22 LTR :wink:
