### ISSUE TITLE
QField cloud sync no longer works

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#2537]
Since 2-3 days syncing no longer works on desktop  from cloud to desktop (I have the issue on a Windows 10 pc and a linux/ubuntu 20.04.3 LTR).
I work with QGIS 3.16 on windows and 3.22.3 on Ubuntu
The  issue exists with QFieldSync plugin i4.0.0-BETA17 and the latest release BETA19.
The error message says 'aborted'. When upgrading to the latest QFieldSync release I get an error for each layer saying "_The layer is not configured with neither cable, nor cloud action yet. Default action will be selected only for this time. Please select and save appropriate layer action in "Layer Properties -> QField"_. Strange, because before everything was working fine and nothing changed on the project settings.

![afbeelding](https://user-images.githubusercontent.com/57868975/155770181-b4bfabb6-e514-4612-bd04-a92103a13c3b.png)

![afbeelding](https://user-images.githubusercontent.com/57868975/155770295-7ddc75da-0e7b-48e0-88f7-22b804a5415c.png)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: YES
* Problem can be reliably reproduced, doesn't happen randomly: I assume
* Problem happens with all files and projects, not only some files or projects:YES (I tried two cloud projects)

**Comment by BoswachterMarc** [comment]
@suricactus I invited myself with  another e-mail. When I receive the invitation, I will try with that new account. Until now, syncing is not possible (the button 'next' is greyed out). I also checked all the (QField) layer properties, but I don't see any solutions over there...

![image](https://user-images.githubusercontent.com/57868975/156728966-f299ce62-af5a-4f49-bb85-10531de8fdaf.png)

**Comment by suricactus** [comment]
And you invited yourself to another account, because you cannot use it with your original one?

On the issue described in the first comment: Have you tried your original account and a new QGIS profile?

**Comment by BoswachterMarc** [comment]
@suricactus Sorry, we were talking about Qfieldcloud and I thought about a new profile at Qfieldcloud ;-)
1/ With a new QGis profile, I opened the project but then the synchronize button is greyed out.
2/ When opening the browser panel, I was able to synchronize the project (only the *.gpkg files were changed)
Is there a way I can 'restore' the greyed out sync button?

![Knipsel](https://user-images.githubusercontent.com/57868975/156890769-77f20e4f-af9e-4e04-acf6-b6c73ea122c1.PNG)

![Knipsel1](https://user-images.githubusercontent.com/57868975/156890780-568d45da-9727-4834-bb1e-4efaf8f6ee15.PNG)

![Knipsel2](https://user-images.githubusercontent.com/57868975/156890787-26d84dac-f249-4d44-8692-2eb4232aba92.PNG)

**Comment by suricactus** [comment]
@BoswachterMarc I have found the issue you were experiencing and should be [fixed](https://github.com/opengisch/qfieldsync/pull/394) in the upcoming BETA20. 

The problem with download aborted is affecting 3.16 only. I doubt that it is also present on 3.22.3 on Ubuntu, it might be another issue. If so, please open a new issue [here](https://github.com/opengisch/qfieldsync/issues) .
