### ISSUE TITLE
Settings not saved after exit

### ISSUE THREAD

**Issue by mrtwister3142** [opengisch/QField#254]
With 0.10.9-0.10.11 my settings (e.g. full-screen attribute table) are not saved after quitting QFIELD,

### Reproduction Steps:

1. Open a project
2. Settings -> check show attibute form in full screen
3. close settings, quit QFIELD.

### Expected behavior:

Settings are saved.

### Observed behavior:

Settings are not saved, and last used project is not remembered.

**QField version:** 0.10.9-0.10.11 on Samsung Galaxy A3 2016 and Android 7.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by VxTedxV** [comment]
Same kind of issue with 0.10.11 for me (but not 0.10.9 as I remember).
QField doesn't open the last project. It shows the starting page with the icon to open a project.
Updated from PlayStore.
Samsung Galaxy XCover4 Android 7.0

**Comment by mrtwister3142** [comment]
also on Samsung Galaxy Tab A with Android 7.0

**Comment by giedrioks26** [comment]
also on blackview BV6000s with Android 7.0

**Comment by giedrioks26** [comment]
same problem with Sony xperia tablet z1, 2, 3, Lenovo tablets, Samsung galaxy tab.
Android 5, 6, 7

**Comment by bartabbas** [comment]
Also on XCover3 under android6 Qfield 0.10.11
Updated from Playstore.

**Comment by fahrwegdienste** [comment]
also on Glalaxy Tab A, Android 7, QField 0.10.11

**Comment by m-kuhn** [comment]
Just a random thought, that this might be related https://github.com/opengisch/QField/issues/259#issuecomment-378885619

> Also starting to notice more and more QField- folders when choosing 'open project'.
