### ISSUE TITLE
Symbols on Linefeature, presentation different to QGIS

### ISSUE THREAD

**Issue by Amphibitus** [opengisch/QField#2543]
After the project export from QGIS to QFIELD, the representation in the map is different

### Reproduction Steps:

since QGIS 3.24

in QGIS:
![grafik](https://user-images.githubusercontent.com/7237786/156024335-238d02a2-7beb-424f-88f6-b264f74ee37d.png)

in QFIELD the arrow symbol is not placed in the center of the segment. There are many arrowsymbols.

![grafik](https://user-images.githubusercontent.com/7237786/156024375-3fb1e471-025d-4bda-960f-ee2e525074fe.png)

Deffenition is here:
![grafik](https://user-images.githubusercontent.com/7237786/156024593-0feed29a-34d9-4e6f-a3ad-51ef58311a19.png)

**Comment by nirvn** [comment]
@Amphibitus , that's because QGIS 3.24 had some backward incompatible changes to line markers. It'll look different with QField until it updates its QGIS library to 3.24.

**Comment by nirvn** [comment]
@Amphibitus , can you install a recent master build of QField (e.g. the APKs in this PR: https://github.com/opengisch/QField/pull/2754), we updated QGIS to 3.24 there, which means your symbology should match now.

**Comment by Amphibitus** [comment]
@nirvn Yes thanks, I tried the old version of LTR from QGIS and the error no longer occurs.
