### ISSUE TITLE
qfield sync plugin - 4.0.0-BETA18 and 19 ERROR CABLE PACKAGE

### ISSUE THREAD

**Issue by aliasatp** [opengisch/QField#2549]
Hi all,
after qfield sync plugin 4.0.0-BETA18 update, when I try to create the package for QFIELD I get the error as diplayed in the following image.
All the subdir are a problem for exporting process even if it isn't using BETA17 and 3.4.4 release.

### Reproduction Steps:

1. Update QFIELD PLUNG TO 4.0.0-BETA18/19
2. Set export for CABLE USE (offline setting, nothing changed)
3. POPUP as in the following pitcure

### Expected behavior:

no error as it was before update or if I use 3.4.4 release

### Observed behavior:

see pitcure

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 

## Additional information:
![qfield_plugin](https://user-images.githubusercontent.com/62659943/156206508-6f8f3553-690f-4779-995a-3da660878cd2.jpg)

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by suricactus** [comment]
Your issue have been addressed and will be fixed on QFieldSync BETA20 (https://github.com/opengisch/libqfieldsync/commit/41812ff567e5f7a5f4dc4b368b388a772e689f91). Thanks for reporting.
