### ISSUE TITLE
Absolute path saved when taking pictures

### ISSUE THREAD

**Issue by gnerred** [opengisch/QField#256]
With actual version 0.10.11, there is no more crash whn taking a picture, cool. 

But, the path written in the database is absolute (/storage/...), instead of relative (DCIM/...), even if relative paths are configured in project. This is really annoying, because project is no more compatible between mobile and desktop. Could it be fixed ? Thanks !

**Comment by gnerred** [comment]
Other problem with the pictures : on older versions, the filenames contained the timestamp, like 20170510_155256.jpg. Now the file is called IMG_00000001.jpg, and that is really annoying too... Could you please fix it too ? Thanks a lot !

**Comment by EulenspiegelTill** [comment]
The new camera function runs on all our tablets and phones. Thumbs up!! 
Using the photo name with timestamp again would be extremely helpful. Especially when several people work in the field at the same time and the data then ends up in a database.
merci!

**Comment by signedav** [comment]
Merged PR #258
