### ISSUE TITLE
Append "stage" to OSGEO4A_DIR path

### ISSUE THREAD

**Issue by elpaso** [opengisch/QField#257]
Not sure if this is a local issue but I had to append `/stage` to the `OSGEO4A_DIR` path in 
`config.pri`

The build was failing to find `qgsfield.h` and other QGIS headers.

This is what worked for me:

`OSGEO4A_DIR = /home/user/dev/Android/OSGeo4A/stage`

This is where my headers are:
`/home/user/dev/Android/OSGeo4A/stage/armeabi-v7a/include/qgis/qgsfield.h`
`/home/user/dev/Android/OSGeo4A/stage/x86/include/qgis/qgsfield.h`

You might want to add this information to the config template.

**Comment by signedav** [comment]
Thanks @elpaso

What do you think @m-kuhn ?

**Comment by m-kuhn** [comment]
OSGeo4A has changed a lot since then, I'd say we close it and if an issue surfaces again let's find a solution for it.
