### ISSUE TITLE
QField directory

### ISSUE THREAD

**Issue by bettellam** [opengisch/QField#2574]
Same software version as QField.
Phone with Android 10 I only have "QFiled app directory" ...
I can't set the folder that contains "Vertical grid shift .."
With other Android 8 phone I also have the "QField storage-wide directory" folder and everything works perfectly !!!
How can I do?
Thank you.
![Screenshot_20220309-163228](https://user-images.githubusercontent.com/23143342/157481578-b2b5f72b-544c-47c9-bc0b-ed276fc40deb.jpg)
![Screenshot_20220309-163919](https://user-images.githubusercontent.com/23143342/157481630-fc5bf77d-61d7-4799-828a-aec52b3ace5f.jpg)

**Comment by suricactus** [comment]
Hi @bettellam . Have you checked https://www.opengis.ch/2022/03/05/qfield-users-sit-down-we-need-to-talk-about-storage-access-on-android ? It explains some of the recent changes in file access.

**Comment by bettellam** [comment]
OK I had read these news that also concern other applications.
I imported my project, but QField does not show me the "Vertical Grid Shift" that I loaded into the folder:
/storage/emulated/0/Android/data/ch.opengis.qfiled_dev/files/QField/proj
Should I place them in some other folder?

**Comment by nirvn** [comment]
Confirmed, fix incoming today
