### ISSUE TITLE
Cable mode doesn't sync with qfield-dev (master-dev c8459c)

### ISSUE THREAD

**Issue by aliasatp** [opengisch/QField#2580]
Hi all,
I am testing qfield-dev (last update) and qfield sync plugin 4.0.0-BETA20.
It works well with CLOUD MODE SYNC but I realised that in CABLE MODE during "back sync (mobile to pc)" nothing happens.
In my mobile I tried to open with qfield "stable realese" the project modified with qfield-dev and I get the same behaviour as the PC, modifications don't appear.

### Reproduction Steps:

1. Create package to use in cable mode - move to mobile device my project
2. Open my project with qfield-dev and I modify my data
3. Sync back to PC but nothing updates

### Expected behavior:

Update data as in qfield-dev

### Observed behavior:

My project modified with qfield-dev even if I open it with qfield stable or doing the "sync bak to PC" doesn't have modification.
If I work with qfield stable version everything works as expected.
I think the issue is in qfield-dev (master-dev c8459c), probably.

### Screenshots and GIFs

2 screenshot of the same project opened in qfield-dev and qfield stable. I expected everythig should be as in first screeshot. The same thing I observe in PC after sync (qfield stable screeshot)

qfield-dev
![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)
![Screenshot_2022-03-10-11-09-16-727_ch opengis qfield_dev](https://user-images.githubusercontent.com/62659943/157642667-3478e11e-9dd7-4a9d-824d-34272b03b8e9.jpg)

qfield stable (and PC)
![Screenshot_2022-03-10-11-10-06-932_ch opengis qfield](https://user-images.githubusercontent.com/62659943/157642716-f787657a-a48f-406f-aa2f-0c3be9813ba9.jpg)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by aliasatp** [comment]
I realised right now that the qfield-DEV release as you have to import your "cable project", it must be exported to a folder to be used to sync bak to pc. Am I right?

**Comment by suricactus** [comment]
You need to copy the project and all it's files back on your PC and then sync with your master project.

If you still cannot sync, please reopen this issue.

Once you copy the files on your PC, you can make sure the changes are in place by opening the project copied from your device.
