### ISSUE TITLE
QField for Linux Crashes when Uploading a File

### ISSUE THREAD

**Issue by rodreras** [opengisch/QField#2583]
[Short description of problem here]
Hey, guys. 

I just downloaded the `qfield-v2.0.13-linux-x64.AppImage` file to test in my computer. I saw 2 things that might be fixed: 

1 - the 1st time I opened the app, its window was so small that I could barely see. I had to increase its width with my mouse. 

2 - When trying to open a local project, QField crashes.

### Reproduction Steps:

1. Open QField AppImage
2. Select `Open Local Project` 
3. QField Crashes

### Expected behavior:

Expected to open a folder with all my files

### Observed behavior:

QField Crashed.

### Screenshots and GIFs

![2022-03-10 17-21-35](https://user-images.githubusercontent.com/53950449/157748359-a82f3a37-9534-4cff-87dd-8506605d30c0.gif)

**QField version:** 2.0.13 DEV (53468a v.2.0.13) Pre release candidate 

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by m-kuhn** [comment]
Thank you for reporting.

Can you launch the app from a terminal and share the output?
Which linux distribution/version are you using?

**Comment by nirvn** [comment]
I've tried and failed to reproduce the crash on my machine (Ubuntu 22.04).

**Comment by rodreras** [comment]
I'm using PopOS! 21.10. 

Sorry, but how can I run it from my terminal?

**Comment by nirvn** [comment]
@rodreras , can you give the latest release a try and report back? Fetch it here: https://qfield.org/get_latest/?platform=linux

Thanks
