### ISSUE TITLE
integer field randomly strange behavior: +/- buttons

### ISSUE THREAD

**Issue by aliasatp** [opengisch/QField#2584]
Hi all,
I report the following strange behavior with "integer field" in qfield. Randomly my integer fields (with +/- buttons) start increse or decrease their value in a uncontrollable way. 
I tried to manage this issue setting these fields as "text" in qgis (in properties but the field remains integer in DB) so in qfield I haven't +/- buttons but only number can be insert. This solution seems to work, but it is a workaround

### Reproduction Steps:

1. qfield package with "integer fields" set as integer in qgis
2. quite rarely one of those fields starts to increse or decrease their value in a uncontrollable way
3. I stop it and everythig works well but it is tempory solution

### Expected behavior:

see above
### Observed behavior:

[Describe observed behavior here]

see above

**QField version:** stable and dev version, also in cloud mode

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by Ipickedausername** [comment]
Hello, 

I can reproduce this behavior when I push the "-" or "+" button while sliding the form to another tab.

I made a small video where you can see this bug is easily reproductible, but not everytime. 

https://user-images.githubusercontent.com/72577399/158089128-dd2a1ae6-fc78-4280-abe8-d17cfd059315.mp4

Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@aliasatp , these APKs should improve things (https://github.com/opengisch/QField/pull/2659). Let us know if you think the issue can be closed.

**Comment by Ipickedausername** [comment]
Hi, 

For information, I made a few tests, I never had this error. It is probably resolved ! 

Thank you !

**Comment by nirvn** [comment]
Woupidou
