### ISSUE TITLE
WFS issues: edits not saved? zoom issue?

### ISSUE THREAD

**Issue by jbostoen** [opengisch/QField#259]
Currently running a test on a local network. Sometimes when zooming, the features (WFS vector layer) disappear. Surprisingly, they reappear when I zoom out (=more features = more data?). 

Also, when tapping on an existing feature while digitizing, most of the time I get "no feature at this position" (when digitizing). Then the WFS points seem to disappear. One has to be lucky to be able to select the feature. Then, when editing a comment field and saving, there's no error but it never gets saved.

### Reproduction Steps:

Zoom issue:
1. Load project at default zoom
2. Zoom in , pan a bit, see for yourself. Sometimes the points disappear (I use a WMS below with the same points, those appear)
There are no contraints on zoom levels or anything.

Edits not saved:
1. Start editing an existing point in a WFS vector layer
2. Save
3. Check results on the server-side
Also, perhaps related to the issue above: often difficult to select points. QField claims there's no data, then suddenly the vector point layer disappears after this message.
( I verified using QGis Desktop 3.0.1, there changes were saved when using the WFS service )

### Expected behavior:
- Still show features (hydrants) after zooming, perhaps with small delay since data needs to be fetched

- Save edits

### Observed behavior:

In the log, I see from the start:
```
WFS
Cannot create temporary SpatiaLite Cache.
CRS
Could not open CRS database //profiles/default/qgis.db
Error(14): unable to open database file
```

Specifically for the editing:
```
QField
Could not save changes. Rolling back.
Commit errors: 
ERROR : 1 geometries not changed.
ERROR: 1 attribute value change(s) not applied.
WFS
Sending of transaction failed: Error transferring http://ip-address/cgi-bin/qgis_mapserv.fcgi.exe?VERSION=1.3.0&SERVICE=WFS - server replied: Bad Request
```

**QField version:** 0.10.11 - Kesch

## Additional information:
* Using a local WFS service - QGIS 3.0.1 .  Since it would show less features when zooming in, it shouldn't disappear, right?

**Comment by m-kuhn** [comment]
Did you replace `ip-adress` yourself?
Do you have anything meaningful in the server logs related to the bad request?

**Comment by jbostoen** [comment]
Yes, it was a valid IP-address (also tested with QGis Desktop if it was working correctly).

Nothing more than that was shown in the Log window

**Comment by m-kuhn** [comment]
> Nothing more than that was shown in the Log window

I'm basically looking at the last bit of the log window

> server replied: Bad Request

which looks like something is sent to the server and the server has trouble understanding it. So possibly there is more information on server side in the logs. If you have access to the server that would be a great thing to check.

**Comment by jbostoen** [comment]
I used this tutorial for the server - http://level2.si/2018/03/qgis-server-3-0-on-windows-10/ 

Should I be looking at QGis specific logs (any idea of the default locations/names); or should I intercept the WFS request?

**Comment by jbostoen** [comment]
I did a WireShark test. I can see the incoming request for new features perfectly.

```

<Transaction xmlns="http://www.opengis.net/wfs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml" version="1.0.0" xsi:schemaLocation="http://www.qgis.org/gml http://10.3.13.100/cgi-bin/qgis_mapserv.fcgi.exe?ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0&amp;SERVICE=WFS&amp;REQUEST=DescribeFeatureType&amp;VERSION=1.0.0&amp;TYPENAME=fieldtest_afsluiters" service="WFS"><Insert xmlns="http://www.opengis.net/wfs"><fieldtest_afsluiters xmlns="http://www.qgis.org/gml"><controle xmlns="http://www.qgis.org/gml">2018-04-05T08:36:11.919Z</controle><opmerking xmlns="http://www.qgis.org/gml">TEST</opmerking><geometry xmlns="http://www.qgis.org/gml"><gml:Point srsName="EPSG:31370"><gml:coordinates cs="," ts=" ">66334.34112529989215545,181932.3964880236890167</gml:coordinates></gml:Point></geometry></fieldtest_afsluiters></Insert></Transaction>

<WFS_TransactionResponse xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/wfs.xsd" xmlns="http://www.opengis.net/wfs" version="1.0.0" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <InsertResult>
  <ogc:FeatureId fid="fieldtest_afsluiters.1728"/>
 </InsertResult>
 <TransactionResult>
  <Status>
   <SUCCESS/>
  </Status>
 </TransactionResult>
</WFS_TransactionResponse>

```

When I attempt to edit this feature I just created, I don't see anything incoming on WhireShark when editing. QField reports "bad request".

I can easily replicate the zoom/pan issue as well here. More often, the vector points are invisible (especially at lower resolutions). This results in a "no feature at this position". Even when I wait until I see the point showing up, then go over it with the crosshair, then touch, I often get that message.

Could it the rendering and feature selection be a timeout-issue? I'm using a WMS provided by Flemish gov, also an internal one to test (on the same server)


About the log window:
- any chance to add a 'clear' button?
- any chance to add a timestamp?

Also starting to notice more and more QField-<random number> folders when choosing 'open project'.

**Comment by Asmaa2499** [comment]
can you more explain 
Zoom issue:

Load project at default zoom
Zoom in , pan a bit, see for yourself. Sometimes the points disappear (I use a WMS below with the same points, those appear)
There are no contraints on zoom levels or anything.

**Comment by nirvn** [comment]
Based on error messages in the issue description, closing as most likely fixed.
