### ISSUE TITLE
Losing connection when pushing changes hide the message "attachment(s) are currently being uploaded in the background"

### ISSUE THREAD

**Issue by MMR100** [opengisch/QField#2590]
I created 7 features in Qfield with photo attached. 
If I push changes, there is a message "7 attachment(s) are currently being uploaded in the background". 
If the internet connection is lost before all the attachments are uploaded, then when the connection comes back the message is not appearing again, and the button "push changes" is grey. 
I have to create a new feature to have "push change" in green again, and also the message "XX attachment(s) are currently being uploaded in the background".

I think the photos would have been uploaded anyway, but it would be nice if the user could see again the message "XX attachment(s) are currently being uploaded in the background" when the internet connection is back.

Here are the screenshots when pushing changes and when the connection is lost.
The first time, it happened because of server down, but I made several test by cutting intentionnally my wifi connexion and the same occured.

![Screenshot_2021-12-31-11-32-02-753_ch opengis qfield_dev](https://user-images.githubusercontent.com/26409106/147907675-5c969008-8e1c-4e73-8fe9-18eaa1327fa2.jpg)

![Screenshot_2021-12-31-11-39-25-189_ch opengis qfield_dev](https://user-images.githubusercontent.com/26409106/147907672-6c08fd1d-141e-4dee-b8e8-4bf0447a5fe0.jpg)

Qfield master-dev (c997bb)

**Comment by nirvn** [comment]
@MMR100 , is this still an issue?

**Comment by MMR100** [comment]
@nirvn the issue solved. I just tried now with Qfield 3.3.11
However, I feel the message "changes successfully pushed to Qfield Cloud" is appearing too fast and might mislead the user if the connection is lost before all the photos are reaching the cloud. 
It can happens typically when someone pushes a lot of changes after a big survey on field and switch off his data too early. (the only way to make sure all the photos are on cloud is to count the number of photo on QfieldCloud user page)

Would it be possible to inform the user that all his features are succesfully uploaded and that he can safely switch off his internet on mobile device ?

**Comment by nirvn** [comment]
@MMR100 , glad to hear this! If you enable QField's notification permission (ATM can only be dona via Android itself), you'll get a notification that will stick until attachment uploads are done. 

We'll have the permission requested in-app ASAP.
