### ISSUE TITLE
Issue when we try to download heavy project (700Mo) on Qfiel-dev app Android from Cloud

### ISSUE THREAD

**Issue by lkino** [opengisch/QField#2592]
We have create new projet from windows Qgis application and then upload to Qfield cloud whithout any issue. But when we try to open the project on Android application, we have an error message ("download error. Exportation issue"). We have try to download form WIFI an from 4G connexion with the same. This project is haevy 700Mo, we don't have any problem with a light project (28Mo).
Thanks

**Comment by lkino** [comment]
@suricactus Hello, Thanks for your feedback and fixed this issue ! 
We have tested now and it is working now !! (with a good Internet connexion).
I will propose in request section to improve the app environnement:
- Have the progress dowloading bar
- Once we select the project:
    * Open windows with all files 
    * Can select just files needed (as user can activate just layers needed.

**Comment by suricactus** [comment]
@lkino hey, thanks for the feedback. While nice additions, please keep the issues focused. If you want these features, you can either open a new feature requsts on github or contact us on info at OPENGIS.ch to speed up the process.
