### ISSUE TITLE
List not loaded when too many occurences 

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#2594]
Hello, 

I made 2 project for a comparison. 
The first one is composed with more less than 500 entities (points). 
The second one is composed with more than 1100 entities (points). 

In the first one, the list is charged. 
In the second one, nothing is charged. 

### Expected behavior:

I presume the list should be charged in any case ?  

### Observed behavior:

Here two video, the first one with the correct behavior, the second where you can see the list isn't loaded. 

https://user-images.githubusercontent.com/72577399/158217053-6de673f5-453e-49b1-b9a4-51d9093f7447.mp4

https://user-images.githubusercontent.com/72577399/158217034-fb792cb5-b644-41b1-a175-4b2266217173.mp4

### Screenshots and GIFs
QField version: [1.10.0 (1da006 v1.10/0)] and last version of QField Dev.

I'll try to send light files later.

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Thank you !

**Comment by Ipickedausername** [comment]
Hello, 

Here are 2 projects QGIS and 2 projects QFIELD to compare. 

To see the problem, in the list of feature of the layer "OPTIONS", open the only one feature. 
In the field "Compart", clic on the first list, and select "03 - Flora"
In the field "PT_Codes", a list is loaded (on the List_ok project) and no list loaded on the other project.

[List_ok.zip](https://github.com/opengisch/QField/files/8260772/List_ok.zip)
[List_not_ok.zip](https://github.com/opengisch/QField/files/8260773/List_not_ok.zip)
[QFIELD_Litst_ok.zip](https://github.com/opengisch/QField/files/8260774/QFIELD_Litst_ok.zip)
[QFIELD_Litst_not_ok.zip](https://github.com/opengisch/QField/files/8260771/QFIELD_Litst_not_ok.zip)

Bye !

**Comment by nirvn** [comment]
I can confirm the issue here, there's definitively something wrong going on. From what I can see, the feature gathering thread never finishes for some attributes when a large number of value relation widgets are in the form.

**Comment by nirvn** [comment]
@Ipickedausername , the APKs here (https://github.com/opengisch/QField/pull/2658) should fix your problem. Thanks for providing a test project, it helped narrow things down.
