### ISSUE TITLE
Right info form does not dissappear in "navigation" mode

### ISSUE THREAD

**Issue by fahrwegdienste** [opengisch/QField#260]
The right info form (when you click on a feature in the map) does not dissappear in "navigation" mode. I press the "back" button, but nothing happens. I need to kill the app and restart it again to work properly.
If I open a project and select the "digitizing" mode straight ahead and then click on the map, the right info form appears. It disappears when clicking on the "back" button. 

### Reproduction Steps:

1. open project and stay in "navigation" mode 
2. click on a feature on the map (to open info form on the right handside)
3. click the "back" button
--> Bug

### Expected behavior:

When clicking the "back" button the form should disappear and the feature should be deselected. No freeze is expected. 

### Observed behavior:

Works fine when:
1. open project and select "digitizing" mode 
2. click on a feature on the map (to open info form on the right handside)
3. click the "back" button

**QField version:** 0.10.11
tested with Galaxy Tab A, Android 7.1.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

## Important:
tested with Galaxy Tab Active and Adroid 5.1.1 WORKS AS EXPECTED!

**Comment by Isaacson33** [comment]
Same behaviour on my Xperia Z2 with Android 6.01. If you open the feature sidebar, then carry out any other action (change layer visibility, go into digitize mode etc.) then the back button no longer closes the sidebar. Especially problematic in digitize mode as the digitize button is hidden by the sidebar. Perhaps a button on the sidebar to close it, maybe where the 'zoom' square is (which no longer seems functional)?

**Comment by m-kuhn** [comment]
Is this fixed?

**Comment by willadam** [comment]
Also having the same issue with a samsung Tab S2 running Android 7 Nougat. Is this issue being looked at?

**Comment by m-kuhn** [comment]
The back button for making it disappear should work meanwhile, so I assume this is fixed. Are you still experiencing this issue? If yes, which version of QField?

**Comment by willadam** [comment]
Apologies, it is 0.10.13

**Comment by m-kuhn** [comment]
What's the effect of the back button?

**Comment by willadam** [comment]
If I have features selected it shrinks down to the 1/4 size, when nothing is selected it just remains blank with 0/0:
![screenshot_20180531-124520](https://user-images.githubusercontent.com/32360036/40780896-e6bb9e4e-64d1-11e8-9b32-220431481557.png)
![screenshot_20180531-124538](https://user-images.githubusercontent.com/32360036/40780897-e6d6806a-64d1-11e8-9b85-11ffc4e74fc0.png)

**Comment by m-kuhn** [comment]
Can you confirm you are clicking the back button (and not some GUI element)?

**Comment by willadam** [comment]
Doh! As a primarily iOS user I assumed that it was a GUI and not the physical back button! My apologies. I feel a bit stupid now! :-)

Thanks very much for you help!

**Comment by m-kuhn** [comment]
I think you are not the only one... Maybe we really need to implement another back/close button there on top
