### ISSUE TITLE
Sync problems with one project

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#2615]
Since a couple of weeks I experience the following problems with one project (not with another project)
1/ When syncing from computer (QGis 3.22.3 Bialowieza on Ubuntu 20.4.03 LTR) to cloud or vice versa I get a error message about layers that are not configured for cable or cloud action (this message didn't show up before). Nevertheless, I can hit the next button and start syncing the project back and forth. I checked the QField layer properties and in my opinion everything is set.
2/ When using QField, I can push changes to the cloud project but syncing with the cloud no longer works. The QField message log says: "downloading the project finished with an error: packaging job finished unsuccessfully". Other people working on my project are experiencing the same problem.
3/ When I delete the local file on a mobile device and I try to download the file from the cloud again, this is not possible (because of the packaging problem?).
4/ In the QFieldSync toolbar (plugin version 4.0.0), the cable button 'Package for QField' is greyed out/not active, the button 'synchronize from QField' is in color/active).

### Reproduction Steps:
I have no idea

**QField version:** [2.0.13 - Dev (53468a)]

## Additional information:
I sent the application log from QField a couple of times (from different mobile devices because they al have the QField sync problem).

* Problem started happening recently, it didn't happen before a couple of weeks. I should check if this problems also occurs in an older version of QField (I think I don't get the error message then).
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: [No, I don't have this issue with another cloud project]

![ksnip_20220318-170814](https://user-images.githubusercontent.com/57868975/159047513-7332d86d-9aba-48ee-84d1-39448614aef5.png)

![ksnip_20220318-170805](https://user-images.githubusercontent.com/57868975/159047549-fe118201-a8c7-4cfc-9b6b-44e9d77f9ba0.png)

![Screenshot_20220318-090202](https://user-images.githubusercontent.com/57868975/159047572-95f6a7cc-1db2-4608-ab86-c5bb8195dcee.jpg)

![Screenshot_20220318-090218](https://user-images.githubusercontent.com/57868975/159047578-75fcb60f-fe43-4bda-8a05-52eb56d7f99b.jpg)

![ksnip_20220318-181159](https://user-images.githubusercontent.com/57868975/159050790-ec837b12-d3d6-4bce-8fc8-387929ec9a7f.png)

**Comment by suricactus** [comment]
@BoswachterMarc there is a bug in QGIS that is preventing QFieldCloud to package the file for QField. If you try to package within QGIS using the "old way", you will get a crash. See https://github.com/qgis/QGIS/pull/47718 for more info.

As soon as this fix is available in the 3.24, the project on QFieldCloud will start working again.

**Comment by BoswachterMarc** [comment]
@suricactus Thank you for pointing out. But then I should experience this with all projects, no?

**Comment by suricactus** [comment]
Not exactly, as you can see in the QGIS PR, the cause is not 100% clear. If you have a project opened with the WMS provider (e.g. drag and drop mbtiles in QGIS) instead of using "open raster data" dialog, it is more likely to happen in your project.

**Comment by BoswachterMarc** [comment]
> Not exactly, as you can see in the QGIS PR, the cause is not 100% clear. If you have a project opened with the WMS provider (e.g. drag and drop mbtiles in QGIS) instead of using "open raster data" dialog, it is more likely to happen in your project.

@suricactus Is there any workaround? I do have several mbtiles in the project. Perhaps if I save them in another format (gpkg, geotif?), the project will run again?

**Comment by suricactus** [comment]
Try adding the mbtiles to your project using "open raster data" dialog. If the project still fails, try converting them to geotiff.

**Comment by BoswachterMarc** [comment]
> Try adding the mbtiles to your project using "open raster data" dialog. If the project still fails, try converting them to geotiff.

I copied the project and changed/saved all mbtiles as layers in one GPKG file. The new project is syncing smoothly now :-)

![afbeelding](https://user-images.githubusercontent.com/57868975/160703904-5c1e5d6a-88b3-4bab-bb76-de5f097bf8b0.png)

**Comment by suricactus** [comment]
More than happy to hear that!
