### ISSUE TITLE
Digitizing in Qfield

### ISSUE THREAD

**Issue by bakakno** [opengisch/QField#262]
Hi,
I am a new user to Qfield. I try to digitize points, lines and polygons on the application but I can't. I am using Samsung Galaxy J7+. I click on Mode < Digitize but then when I go to the map I can't draw lines, points or polygons.

Cheers.
Arnaud  
 
### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by m-kuhn** [comment]
Do you have any layers in your project and select one in the layers list?

**Comment by bakakno** [comment]
Yes I have 2 layers and I selected 1 layer.

I can delete the items but I can't create new features.

Regards.
Arnaud

**Comment by giedrioks26** [comment]
Maybe indentify window covers the editing button? @bakakno could you please add a screenshot here?

without indentify window
[screenshot_20180409-232213](https://user-images.githubusercontent.com/6436791/38521372-1fe9db38-3c4e-11e8-8d8a-9c93cc8428e3.png)

with indentify window
[screenshot_20180409-232251](https://user-images.githubusercontent.com/6436791/38521427-52505a0c-3c4e-11e8-90d6-0ef51b87d41e.png)

**Comment by giedrioks26** [comment]
Identify window appears when touch map with objects. Did not you click on the edit button?
In this case, press "back". If it does not work it is possible work around: 1. Touch the indentify window on the entry; 2. Touch back from the entry; 3. press back again. This will turn off the identify window.

1. [screenshot_20180317-115448](https://user-images.githubusercontent.com/6436791/37556080-6c45332c-29f9-11e8-9678-a61c9b3b3b9c.png)
2. [screenshot_20180317-120142](https://user-images.githubusercontent.com/6436791/37556083-733e01ea-29f9-11e8-85c5-69b6286842cb.png)
3. [screenshot_20180317-115507](https://user-images.githubusercontent.com/6436791/37556092-828396a6-29f9-11e8-95e2-b7ff7c2f94c3.png)

You also need to select layer

**Comment by bakakno** [comment]
Thanks for this information.

It all works now.

I know it is possible to export qgis project to Qfield but is it possible
to export the project modified in Qfield into Qgis software ?

Regards.
Arnaud
