### ISSUE TITLE
Feature request: autocomplete combobox

### ISSUE THREAD

**Issue by caiohamamura** [opengisch/QField#264]
When you have a Relation Reference or Value Map, you can only select the value from the list. But if you have hundreds of values to list it is almost impossible to find the value you want. It would be great to have the possibility to type the text with autocomplete support for selecting options from Relation Reference and Value Maps.

**Comment by she-weeds** [comment]
Wonder if there's been any progress on this. Autocomplete would make a massive difference for making this an usable app for environmental/biological use - it's currently very hard to use when you have 100s of species to manually scroll through. I really hope this can be implemented...

**Comment by VxTedxV** [comment]
👀

**Comment by rjwillson** [comment]
I was just looking at this feature request yesterday as it is one of my biggest needs as well

the autocomplete currently built into QGIS with the value relation widget only picks up the starting characters of the value

a more valuable implementation is what Nathan Woodrow has set up in his mobile Roam application. Roam’s version will auto-complete the character string anywhere in the value. This is very useful when you forget the common name of a species but remember the scientific name

**Comment by rjwillson** [comment]
![image](https://user-images.githubusercontent.com/11098144/56967342-026f6300-6b2f-11e9-897b-930b0d6e45ee.png)

**Comment by she-weeds** [comment]
Yes, we use ROAM on the windows tablets as well and that was my inspiration for asking. The ROAM implementation is ideal especially if you have 200 eucalypt species and just want to go straight into the species name. But at this stage I'd be happy with any kind of autocomplete/search functionality.

**Comment by 9ls1** [comment]
Any progress with autocomplete? Would be very convenient in stead of scrolling through 400 species...

**Comment by Lontsdriver** [comment]
Yes, i also think that this feature is more or less necessary to work with more than 50 Values in an attributfield.
That´s a big Point in enhancing QField a lot. It´ll make it usable in various Fields of gathering Data like mapping environmental things like Flora&Fauna and Stuff. I wonder why it isn´t implementet jet. In the MainProgramm of QGIS it´s possible to do so.
Hope someone will take on this task.  I think it´s probably not even a big Problem to make it happen =)

**Comment by FolkyHobbit** [comment]
If this will be implemented, for my use case it would be most useful if the autocomplete matches anywhere within the relations, not just from the start. I would use this to select species names from a long species list. With scientific species names the first part is shared with all other  species of the genus, so searching by the second part is often faster, and the same goes sometimes for common names as well.

**Comment by m-kuhn** [comment]
@suricactus is this fixed?

**Comment by Plant15** [comment]
> Yes, we use ROAM on the windows tablets as well and that was my inspiration for asking. The ROAM implementation is ideal especially if you have 200 eucalypt species and just want to go straight into the species name. But at this stage I'd be happy with any kind of autocomplete/search functionality.

I used this fonction with the Fulcrum app at my old job. That was very convenient. I hope that it will come soon for QGIS.

**Comment by m-kuhn** [comment]
This is implemented and working.

**Comment by Plant15** [comment]
I'm wondering : can I write for example "maculatum" and the field will match and show the "hima - Hieracium maculatum" relation in the list? I can't get it to work with this functionality. Should I write a code for this instead? 

Thank you for your help

**Comment by m-kuhn** [comment]
Yes, see here: https://github.com/opengisch/QField/pull/2086

Some documentation about this would be great

**Comment by Plant15** [comment]
Your are totally totally right. 

However, If the function could be added to QGIS primary attribute form and not just QField it would better fit my case as I use a windows tablet with full QGIS in the field
