### ISSUE TITLE
Closing the project/application using the app list instead of double pressing the back button leads to data.gpkg not finalized

### ISSUE THREAD

**Issue by arkanoid87** [opengisch/QField#2655]
If I close QField project using the app drawer instead of double tap on back button, wal and shm files are present in QField project folder (sqlite db not closed).

Not sure if this is a specific issue with my smartphone (Samsung)

### Reproduction Steps:

1. Open QField project
2. Add a feature on any layer to trigger write operation on data.gpkg
3. Close QField application opening the app list and swipe up (depends on Android OS, but this is how it's done generally) instead of double pressing the back button.

### Expected behavior:

data.gpkg is correctly finalized in project folder

### Observed behavior:

data.gpgk, data.gpkg-wal and data.gpkg-shm are present in project folder, where only data.gpkg should exist.

**QField version:** 1.10.0 (1da006) from Play Store

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by arkanoid87** [comment]
I might be wrong, but Isn't `onCleared` callback the way to go? I don't see it defined in https://github.com/opengisch/QField/blob/c8514fd0aa861f09813034ebffbc777b82ae26cd/platform/android/src/ch/opengis/qfield/QFieldActivity.java

https://developer.android.com/topic/libraries/architecture/viewmodel#lifecycle

Beware, I know zero about the internals of QField, just guessing

**Comment by arkanoid87** [comment]
AFAIK, `onPause()` is the only reliable way to early know the user is leaving: https://developer.android.com/guide/components/activities/activity-lifecycle#onpause

The only exception to this would be force killing the foreground app, that again AFAIK it was a thing only on some custom roms like Lineage.

I don't see `onPause` declared in any Android Activity

**Comment by arkanoid87** [comment]
I've verified the same behavior on smartphones and tablets of different brands. Closing the app via overview leaves the db open.

**Comment by nirvn** [comment]
@arkanoid87 , does this cause any data loss/corruption or it is merely inconvenient to have these sidecar files in your folder?

**Comment by arkanoid87** [comment]
As sqlite files are memory mapped, a non-closed db may end up being not flushed (depends on OS implementation details afaik).
Long story short, synching gpkg+sidecar may lead to loss or corruption.

Complete explanation at:
https://www.sqlite.org/howtocorrupt.html

**Comment by gdt** [comment]
Having watched the discussion about WAL on qgis, my impression is:
  - it's a bug to not close the db (and thus flush/rm journal) when the app is stopped via anything nicer than force close
  - the db should only be open in WAL mode if it is editable.  Generally, it's best not to cause a write to the filesystem if the app does not have  need to do a semantic write operation.   I( realize that with tracklogging it's always writeable, but one could and probably should set up tracklogging on a geopackage separate from one's feature geopackage, partially for this reason.)

**Comment by nirvn** [comment]
QField 2.1 has improved things on that front by upgrading gdal to 3.4.2, which only triggers the WAL mode when _editing_ a geopackage. That should help a lot.

**Comment by m-kuhn** [comment]
> @arkanoid87 , does this cause any data loss/corruption or it is merely inconvenient to have these sidecar files in your folder?

Did someone actually observe data loss?

QField regularly flushes the db to minimize the risk of data loss.
