### ISSUE TITLE
QField : virtual key does not show up when asked to enter login details

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/QField#2665]
The Virtual keyboard does not show up when user is asked to enter login details on Samsung Galaxy TAB Active PRO

### Reproduction Steps:

1. Launch QField
2. Open an existing QfieldCloud Project (already downloaded)
3. A window pops up to ask to enter login details
4. select the user or email field

### Expected behavior:

the virtual keyboard should popup

### Observed behavior:

nothing happens, 

### Screenshots and GIFs

**QField version:** master-dev c25e28

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: not tested

**Comment by joekbullard** [comment]
Can confirm this is also happening for me on Xiaomi Poco NFC on 2.0.14 dev

**Comment by nirvn** [comment]
@joekbullard , you can try APKs here, _might be_ fixed: https://github.com/opengisch/QField/pull/2687

**Comment by jpdupuy** [comment]
Hello,

It seems that the problem still occurs on QFIELD 2.0.14

**Comment by nirvn** [comment]
@jpdupuy , correct, the likely fix hasn't been in a public release yet. Can you try the APKs in the above-linked PR #2687 ? Thanks

**Comment by jpdupuy** [comment]
Fine, I have downloaded the APK, and the test was successful.  The virtual keyboard is back.. Taadaa
Thanks for the fix.
