### ISSUE TITLE
WMS layers only opening sporadically

### ISSUE THREAD

**Issue by Isaacson33** [opengisch/QField#267]
I've tried several types of project but can't seem to work out what the common thread is. WMS layers are currently not working at all, but I've definitely had a layer work in a previous project (same layer)

http://www.landis.org.uk/arcgis/services/UKSoilObservatory/Soilscapes_Cranfield/MapServer/WmsServer?

### Reproduction Steps:

1. Create a project with http://www.landis.org.uk/arcgis/services/UKSoilObservatory/Soilscapes_Cranfield/MapServer/WmsServer? as the only layer in Qgis (2.18)
2. Copy project to device (Xperia Z2 Android 6.01)
3. Open project in Qfield - layer is blank

### Expected behavior:

Layer shows. It definitely showed up on a previous project, but I don't have that one anymore (I'm testing Qfield out) so I can't work out why it opened there.

### Observed behavior:

Additional info - When loaded into a project with other layers, the 'Show on map canvas' tick box won't stay ticked, every time I select it and then return to the menu, it's unselected again.

### Screenshots and GIFs

It's just a blank screen

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 0.10.12

**Comment by signedav** [comment]
I can reproduce that on my device.

While it's fine on the development environment on the computer:

![image](https://user-images.githubusercontent.com/28384354/69060542-c7277980-0a17-11ea-84e7-508b54681ab9.png)

On the device the WMS map is not visible:
![WhatsApp Image 2019-11-18 at 15 27 31](https://user-images.githubusercontent.com/28384354/69061065-cb07cb80-0a18-11ea-981b-abbcceb926dc.jpeg)

**Comment by nirvn** [comment]
This is very outdated and most likely fixed, closing.
