### ISSUE TITLE
App crash when adding photo to new object

### ISSUE THREAD

**Issue by Repeato** [opengisch/QField#2675]
[Short description of problem here]

Using Redmi 9 with MIUI 12.0.2, used 28GB out of 64. Android verze 10 QP1A.190711.020

### Reproduction Steps:

1. [First Step] - create new object and save it
2. [Second Step] - add 1st. 2nd or 3rd photo, camera launches, make photo, accept photo
3. [Third Steps...] - in 50% cases camera continues open while it should disappear and allow adding next photo in app
4. [Fourth Steps...] - closing camera using left (X) button and app crashes to selecting project status
5. [Next Steps...] - re-openning project, last added/edited object is there but photo is missing

### Expected behavior:

[Describe expected behavior here] add picture and allow me saving object with pictures

### Observed behavior:

[Describe observed behavior here] app crashing

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.02.0 (10200993)] : 1.10.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] ?? I don't know. There were other crashes but this is most problematic one
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] almost 50% cases when adding photo to new object
* Problem happens with all files and projects, not only some files or projects: [Yes/No] didn't test with other projects

**Comment by aliasatp** [comment]
I suggest you to use "no native camera" by setting it in app menu

**Comment by Ipickedausername** [comment]
Hello, 

If you're using a field to name the picture (ex: 'Picture' || "field_1"), make sure that you don't have any unauthorized character (like "<, >, :, “, /, \, |, ?, *"), otherwise, the access path of the picture will not work (and maybe crash QFIELD). 

Check also on QFIELD sync if you're not using a wrong access path in "naming expression".

**Comment by nirvn** [comment]
@Repeato , could you please try the APKs here - https://github.com/opengisch/QField/pull/2744 - and tell us whether the crash continue to occur or not? Thanks

**Comment by Repeato** [comment]
> I suggest you to use "no native camera" by setting it in app menu

This was not helpful because I had to adding pictures from picture folder manually.

**Comment by Repeato** [comment]
> Hello,
> 
> If you're using a field to name the picture (ex: 'Picture' || "field_1"), make sure that you don't have any unauthorized character (like "<, >, :, “, /, , |, ?, *"), otherwise, the access path of the picture will not work (and maybe crash QFIELD).
> 
> Check also on QFIELD sync if you're not using a wrong access path in "naming expression".

I only used Czech alphabets "í,á,ř,é" and spaces in project name. I removed them but I could not test because new version 2.0.14 - Dev got uploaded automatically. I had only one occurence of app failure since then.
