### ISSUE TITLE
Seguimiento con el GPS

### ISSUE THREAD

**Issue by JUAN1936** [opengisch/QField#2679]
[Short description of problem here]

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]
Hola cuando realizo un seguimiento con una capa en qfield, tengo que tener la aplicacion abierta con la pantalla encendida, si apago la pantalla el seguimiento se hace errático, ya he configurado la app para que se mantenga activa. Tengo que observar que se resitúa continuamente para que no de errores en la situación gps. Esto da mucho gasto de batería, y además los riesgos de tocar la pantalla con las causas que pueda tener.
El trabajo que hacéis es excelente, todo mi trabajo en qfield da gusto de hacerlo

**Comment by m-kuhn** [comment]
Thank you for reporting.
This has already been reported at https://github.com/opengisch/QField/issues/1841, please add any additional information there.
