### ISSUE TITLE
Save/Cancel options

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#268]
With the Save and Canceling of **Settings** and after **editing features** there appeared some problems I don't know since when. Anyway I think we should think about it in general. Since we will have a solid focus-handling we could use sometimes the back-key instead of cancel.

Save and Cancel is used in the following situations:
- Settings
- Edit Feature
- Add Feature 

### Settings
![01_qfield_settings](https://user-images.githubusercontent.com/28384354/38996469-8f5e300a-43eb-11e8-8e4e-d1869ae0fcde.gif)
**Problem:**
It doesn't matter if I click Save or Cancel or back-key. It's saved anyway.
**Suggestion:**
Remove the option Save/Cancel and let it be saved always on closing (with back-key). IMHO the UX is, that it's saved then. Anyway I don't really know apps where we use Save/Close on settings...

### Edit Feature
![02_qfield_featureedit](https://user-images.githubusercontent.com/28384354/38996635-e6ece14a-43eb-11e8-8adf-53c2598085a8.gif)
**Problem:**
It doesn't matter if I click Save or Cancel or back-key. It's saved anyway.
**Suggestion:**
I see three sollutions:
1. Fix it. Then it will be saved on Save and not saved on Cancel or back-key.
2. Remove Cancel. Then we have Save for save and back-key for cancel (because I suppose that a user anyway never uses cancel but back-key instead)
3. Remove Cancel and Save. Then it will be always saved when closing (pressing back-key)

### Add Feature
![03_qfield_digitize](https://user-images.githubusercontent.com/28384354/38996789-39ebc4ec-43ec-11e8-9ea7-0c612d132c9a.gif)
**Problem:**
No problem. This works like expected.
**Suggestion:**
I would make it like the Edit Feature. Means if we remove any Save/Cancel option, I would remove it here as well.

What do you think @m-kuhn @3nids @mbernasocchi ?

I suppose it's a small thing to do that. And I propose to do it before 1.0.

**Comment by mbernasocchi** [comment]
specifically: https://stackoverflow.com/questions/4988224/how-to-handle-save-and-cancel-buttons-and-the-back-key/4989368#4989368

> I highly recommend you following the model used by the standard Android and apps, where editing always happens in place. That is, there is no "save" button -- the changes you are making are effectively being saved as they are being done.

**Comment by signedav** [comment]
Thanks @mbernasocchi Yes, that's my opinion as well. For **settings** it's everyone's I guess.
For the **edit feature** case, I tend to the similar handling. So suggestion 3. 
In the **add feature** case I'm not sure yet.

**Comment by m-kuhn** [comment]
In the add feature tool, a trashcan icon might be appropriate if the cancel button is removed for the others?
This would (at least look like) the action has already been performed.

**Comment by signedav** [comment]
Okay, so I will do what @m-kuhn proposed with the **trashcan** button. Like the feature is created after pressing the pencil button. Then the user can enter the attributes. In case of adding no attribute it's saved as empty feature (with default values).

In case of constraints, back-key should effect a message that the feature-configuration cannot be closed because the constraints are not fulfilled. So in case of add-feature you could use the **trashcan** if you just want to leave (and not save the feature). In case of edit-feature we need something to **cancel**. One possibility is to let the **cancel** icon stay or we add a **reset** icon instead of it, to reset the values to the status before edit them. So if you want to leave fast you press **reset** and back-key.

**Comment by signedav** [comment]
I see here a conceptional conflicts with #294 because there you rely on the save button at adding feature to "finalize".

So this approach needs to be changed. A solution I see:
On Settings -> solve as mentioned above. No buttons. It's saved always.
On Editing -> save on "save button", not saved on back \*.
On Adding -> save on "save button", not saved on back \*.

So the implementations would be only:
- Remove buttons on settings
- Remove cancel button on editing
- Remove cancel button on adding

Are there other ideas, how we could life without any "save" button (what would make the GUI lighter)?
Is there a risk that the user expects that it's saved on edit/add feature on back \*?

Opinions @mbernasocchi @m-kuhn @3nids ?

\* ("on back" means pressing back-key on device)

**Comment by 3nids** [comment]
I am not a huge fan of not saving on back as you mentioned you might expect it to be saved.
I would ask for confirmation when pressing back.
Otherwise, I would rather opt for "back" being the save action and have icons for cancel/reset (trash icon for adding feature and refresh icon for editing).
Why do you say it's not compatible with form as a drawer? Can't we switch this?

**Comment by 3nids** [comment]
I think this stash status is not available anymore since the rubbberband is reset when the drawer is closed.
Anyway, I think this doesn't go against the process you describe (bback => save/continue)
To me, the approach seems to be the most intuitive.

**Comment by m-kuhn** [comment]
No worries about the stash status, that was more a side-effect than by design.
I'll leave the other decision to the two of you.

**Comment by signedav** [comment]
Okay. Thanks @m-kuhn 
So I guess @3nids and me agrees. Only open thing is with the confirmation dialog, but I guess I can make a first version without and then we still can discuss...

**Comment by 3nids** [comment]
no need for confirmation dialog (I wanted one if back was canceling, no need if back is saving/continue)
good move!

**Comment by signedav** [comment]
Btw. what do you think about Switch buttons in
![switch2](https://user-images.githubusercontent.com/28384354/44031178-70b6f290-9f03-11e8-8fdd-fdecc661b466.gif)
 the settings.
Pro: looks more like android app - Contra: looks less like super basic nerd tool

**Comment by 3nids** [comment]
like it a lot! that makes the app much more polished!

**Comment by m-kuhn** [comment]
+1, like it

**Comment by mbernasocchi** [comment]
+1

**Comment by signedav** [comment]
Another thing in this relation. 

The icon + on adding a point, does in my opinion not parallel on the + icon on adding a polygon or a line. 
It should be the icon on adding a point like adding a line or a polygon - means the end of the digitizing and the start of entering the attibute-values.

Short:
I would like to replace *on point layers* this icon:

![selection_025](https://user-images.githubusercontent.com/28384354/44095460-2d3cc392-9fd9-11e8-97f4-aec74d684949.png)

with that one:
![selection_026](https://user-images.githubusercontent.com/28384354/44095462-30b82746-9fd9-11e8-8886-5cad2794d508.png)


What do you think?

**Comment by m-kuhn** [comment]
I agree there's something misleading currently. To me the floppy symbol looks like "save the current state". What's your opinion on using a yellow plus instead?

**Comment by signedav** [comment]
I agree on your input as well. I even thought about a yellow +. But then it would need a yellow plus to store the polygon as well if we want to be consequent. And then there would be two +. One green plus and one yellow plus. And that's not that nice...

**Comment by m-kuhn** [comment]
Why not leave the floppy for the polygons?

**Comment by signedav** [comment]
The function we are talking about is: "Keep this geometry (on points and polygons) and go now to the attribute form, where I can enter the values and then it's saved or I cancel it"
This is the same on polygons and on points and I prefer to have the same icon for that. Because it's nice with the floppy on polygons I proposed to change it on points to the floppy as well.
But I agree on your input, that the floppy symbol is "save the current state" - but this it is on polygons as well.

**Comment by m-kuhn** [comment]
One could argue that on polygon it's "go to the attribute dialog" and on point it's "add a point and go to the attribute dialog", especially after the latest changes by @3nids where the current point is not added on lines/polygons on save.
