### ISSUE TITLE
Qfield on iOS

### ISSUE THREAD

**Issue by katagen** [opengisch/QField#2681]
Qfield is no longer available on Testflight! How can I recover an iOS version? I need it for fieldwork?!?

**Comment by aleko205** [comment]
Hope it will be back soon, as a test or as a final version 🙏🏼

**Comment by mbernasocchi** [comment]
Hi,
unfortunalely Apple is taking very long to start reviewing QField. We've submitted 2.0.14 last week for review and we still in "waiting for review" status. We've also contacted support to no avail. we're really sorry but there is nothing we can do. 
as soon as Apple will aprove QField again it will be immediately available on testflight (qfield.org/get)

**Comment by mbernasocchi** [comment]
@katagen @aleko205, we just received the reviewers approval :)
you can now install QField again using testflight 🚀 
https://testflight.apple.com/join/TbG1kJVI
