### ISSUE TITLE
QField shows error when negative numeric value is entred

### ISSUE THREAD

**Issue by soester** [opengisch/QField#2695]
QField shows error when negative numeric value is entred:
`Value "-" NOT NULL could not be converted to a compatible value for field messung_c_prz_ch4(Real).`

### Reproduction Steps:

1. enter negative value to numeric field in attribute form
2. save
3. error log shows warning
4. data is correctly in feature

### Expected behavior:
This is somehow disturbing behavior. No error should be thrown.

**QField version:** 2.0.14
Android 11, Samsung Tab Active 3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No] Not in latest 1.x version
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by aliasatp** [comment]
I had the same issue, a workaround is to set the field in qgis as "text". The issue is in qfiled side

**Comment by nirvn** [comment]
Are you guys able to provide a tiny test project to show this issue?

**Comment by soester** [comment]
In this project you can enter numeric values in the num_* fields:
[Qfield_Generic.zip](https://github.com/opengisch/QField/files/8425122/Qfield_Generic.zip)

**Comment by nirvn** [comment]
@soester , the fields there are set to use the text edit widget, which I assume do not show the problem, am I correct? If so, can you send me a project that's set up to show the issue?

**Comment by nirvn** [comment]
@soester , you can ignore the follow up request, APKs here (https://github.com/opengisch/QField/pull/2705) should fix your issue. But in the future, make sure you send test projects set up in a way that actually demonstrate the issue raised :)

**Comment by soester** [comment]
@nirvn ok, changed to range.
but this didn't solve the issue.

It was fixed once...
https://github.com/opengisch/QField/issues/1026

New sample project:
[Qfield_Generic 2.zip](https://github.com/opengisch/QField/files/8425315/Qfield_Generic.2.zip)

**Comment by nirvn** [comment]
@soester , no worries -- if you can test the APKs (they are up now) and confirm the warning is gone, it'd be appreciated. Cheers.

**Comment by soester** [comment]
@nirvn issue is fixed in https://github.com/opengisch/QField/pull/2705
