### ISSUE TITLE
When Zoom to select point feature, then makes the map inactive

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#270]
When Zoom to select point object from the preview form, makes the map inactive. Touching the screen does not move.
1. Select point.
[screenshot_20180423-221747](https://user-images.githubusercontent.com/6436791/39150815-29d93630-474c-11e8-9571-c3d11a7b409a.png)

2. Zooming to object.
[screenshot_20180423-221756](https://user-images.githubusercontent.com/6436791/39150833-3966f240-474c-11e8-89d2-1794feac5e55.png)

3. Inactive map
[screenshot_20180423-221933](https://user-images.githubusercontent.com/6436791/39150861-468f43d2-474c-11e8-8e3d-74a345ddbbd1.png)

Work around from this:
1. select polygon or line
[screenshot_20180423-221947](https://user-images.githubusercontent.com/6436791/39150878-55d4756a-474c-11e8-8249-af78a1c6d71d.png)

2. Zooming to object
[screenshot_20180423-221955](https://user-images.githubusercontent.com/6436791/39150898-621b605e-474c-11e8-84da-3185365d0ca0.png)

3. Now the map is active
[screenshot_20180423-230417](https://user-images.githubusercontent.com/6436791/39150949-86bd017e-474c-11e8-9180-62d556d1d122.png)

Project demo: 
[null.zip](https://github.com/opengisch/QField/files/1939871/null.zip)

Device: Blackview BV6000s, Sony xperia tablet Z3, LENOVO Tab 3-710F, Samsung galaxy A, S
Android 5.1, 6.0, 7.0

**Comment by m-kuhn** [comment]
Did that start with the latest release?

**Comment by giedrioks26** [comment]
Same with 0.10.10 - 0.10.13

**Comment by giedrioks26** [comment]
I don't see this with the last version 1.0.  Now works well
