### ISSUE TITLE
Feature suggestion: Export DCIM folder

### ISSUE THREAD

**Issue by jfmoyen** [opengisch/QField#2718]
Greetings,

QField 2.x gives the "send to..." option on project files (which allows to move them out of QField private folder into some public space). It also allows (or at least will allow in 2.1, but I'm willing to take this as a baseline for this discussion !) to "zip and send" a whole project folder, which is great.

However, when dealing with many images (in the DCIM folder), it is not a very practical approach. In this situation you have to either (i) export all the photos one by one, which is time-consuming and error-prone, or (ii) zip the whole folder and export it to where you want it to be and unzip there. 

Option (ii) works for a one-shot export, but if you regularly export a project (perhaps at the end of every field day, "just in case" something happens to your device), you have to replace each time the previous DCIM file by the new one, effectively manually merging the folders, with (again) risks of errors and forgotten or duplicated images.

A much better solution would be to export the folder as it is - adding only the missing images to the DCIM folder. From a user perspective this would mean that the ... menu associated to a folder would include an option for "zip and send to...", and an extra one (the object of this suggestion) called perhaps "update target folder...". 

Well, I suspect there may be complexities around what is actually meant by "merging" folders (files with the same name, younger dates of modification, etc....). I'm rather convinced that there s some theory around it, anyway.

Thanks for your consideration !

**Comment by nirvn** [comment]
@jfmoyen , I believe this PR (https://github.com/opengisch/QField/pull/2733) mostly implements your suggestion. A new "export to folder..." action is now available to export a project's root folder (or any of its child folder) onto a user-provided location on your device. When exporting, the content is copied from the edit project content within the QField app's files directory to the destination folder/location.

If that fulfills your enhancement request, let us know, I'll close this issue then.
