### ISSUE TITLE
Simple Field Map/Geopackage showing Python error for Offline Editing

### ISSUE THREAD

**Issue by CCGSSurvey** [opengisch/QField#2730]
Note: I do not know how to code using Python (yet) but have made QField maps for over two years and followed the same steps without this error. 

I am creating a simplified field map with just three layers:
- point data geopackage with four fields
- polygon data geopackage with four fields
- MBtiles basemap
-
### Reproduction Steps:

1. followed all the normal steps for setting up the two geopackages, CRS are all the same, follows exactly how I have done this several times
2. turned off all other layers in my project map, set both the point and polygon tools to "offline editing" as I have done before
3. set MBtiles layer to copy
4. set "Create Base Map" to Single Layer→my MBTiles map layer (it is based on a jpeg of a Google Maps map)

### Expected behavior:

mobile map would generate for export to QField

### Observed behavior:

Received "An error has occurred while executing Python code" message: 

TypeError: decorated slot has no signature compatible with progressModeSet(QgsOfflineEditing::ProgressMode,long long) 
Traceback (most recent call last):
  File "C:\Users/kenho/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 116, in package_project
    offline_convertor = OfflineConverter(self.project, export_folder, self.iface.mapCanvas().extent(),
  File "C:\Users/kenho/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\offline_converter.py", line 77, in __init__
    offline_editing.progressModeSet.connect(self.on_offline_editing_max_changed)
TypeError: decorated slot has no signature compatible with progressModeSet(QgsOfflineEditing::ProgressMode,long long)

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.4-Białowieża Białowieża, ce8e65e9 

Python Path:
C:/PROGRA~1/QGIS 3.22.4/apps/qgis-ltr/./python
C:/Users/kenho/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/kenho/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS 3.22.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.4\bin\python39.zip
C:\PROGRA~1\QGIS 3.22.4\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.22.4\apps\Python39\lib
C:\Program Files\QGIS 3.22.4\bin
C:\PROGRA~1\QGIS 3.22.4\apps\Python39
C:\PROGRA~1\QGIS 3.22.4\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.22.4\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS 3.22.4\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.22.4\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.22.4\apps\Python39\lib\site-packages\Pythonwin
C:/Users/kenho/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\kenho\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:/Users/kenho/Documents/GIS DataBase

QGIS version
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
HCMGIS
20.12.22
qfieldsync
v3.4.1
quick_map_services
0.19.11.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

**Comment by suricactus** [comment]
Can you upgrade to the latest v4.0.0 QFieldSync version and confirm the issue still exists? If yes, please provide an example project, will ease fixing the problem a lot.

**Comment by CCGSSurvey** [comment]
> Can you upgrade to the latest v4.0.0 QFieldSync version and confirm the issue still exists? If yes, please provide an example project, will ease fixing the problem a lot.

Upgraded plugin and issue resolved--thanks!
