### ISSUE TITLE
Different behavior of "Apply default value on update" between QField and QGIS

### ISSUE THREAD

**Issue by stcz** [opengisch/QField#2747]
Using the checkbox "Apply default value on update" on a Attribute Form Fields defaults disables the possibility to edit in QField

### Reproduction Steps:

1. Create a easy project with a Attribute Form with two Fields (e.g. `parent` and `child`)
2. Add a default value for one field depending on another, e.G. 
```
CASE
WHEN "parent" = 1 THEN 1
WHEN "parent" = 2 THEN 2
ELSE NULL
END
```
3. Export the Project to QField

Here are two simple example projects to reproduce:
[QField.zip](https://github.com/opengisch/QField/files/8490429/QField.zip)
[QGIS.zip](https://github.com/opengisch/QField/files/8490430/QGIS.zip)

### Expected behavior:

1. I would expect that QGIS and QField behave the same way.

2. Second, I would expect that a "default" value is only a "default" value and still editable. 

3. (I'm unsure about the case, when editing the `child` value and update the `parent` value later. The current QGIS behavior and what i expected behavior is that the child will be overwritten again. In some use cases, it could be more comfortable if the manually edited value of `child` would remain. But this is another topic, what could be solved by 3 values for the attribute `applyOnUpdate`)

#### QGIS
- When editing the parent value in a form, the child object is updated as expected.
- I'm able to edit the child field.
- The child field is updated the parent field is edited again
![QGIS Behavior](https://user-images.githubusercontent.com/66465573/163426636-2c2fa765-a816-4fae-b1d5-b454248102ce.gif)

#### QField v2.0.9
- When editing the parent value in a form, the child object is updated as expected.
- I'm not able to edit the `child` field.
![QField Behavior](https://user-images.githubusercontent.com/66465573/163426613-b48a8f26-b111-460b-ad4c-025e846f2b3d.gif)

#### QField v2.0.14 (8f9aa8)
- When editing the parent value in a form, the child object is updated as expected.
- I'm able to edit the child field.
- The child field is updated when the parent field is edited again
![QField v2 0 14](https://user-images.githubusercontent.com/66465573/163435879-f2af5eaf-0208-4bb9-b029-2ea8dd5494c2.gif)

#### QField master-dev (d5ffbe)
- When editing the parent value in a form, the child object is updated as expected.
- I'm able to edit the child field.
- The child field is not updated when the parent field is edited again
![QField master-dev](https://user-images.githubusercontent.com/66465573/163437209-7bc137f4-b2e7-4c5e-9796-7c7fa53ecff4.gif)

## Additional information:
**QGIS version:** 3.24.1-Tisler (5709b82461)

* Problem started happening recently, didn't happen in an older version of QField: [The Problem seems to be Version dependent]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

The corresponding attribute in the default element is called "applyOnUpdate".

Thanks for your great work on QGIS and QField

**Comment by stcz** [comment]
I tested it with **QField Version:** master-dev (d5ffbe) on my phone and there it is working. I went into this because of #2483 :roll_eyes: I will update the Issue.

**Comment by nirvn** [comment]
@stcz , is this still an issue with QField 3.3.10?
