### ISSUE TITLE
QField <-> QGIS' reuse last entered value configuration

### ISSUE THREAD

**Issue by acebulsk** [opengisch/QField#2748]
After checking _Reuse last entered value_ under field attributes, when adding a new feature in QGIS it will autopopulate the new field entry box with the previously entered value. This same feature does not work on QField, tested on Linux, IOS, and android.

### Reproduction Steps:

1. Create a QGIS project and GeoPackage layer.
2. Add a table called _samples_ to the GeoPackage layer with a field named _number_
3. Check the box _Reuse last entered value_ in layer properties > field attributes > highlight numbers field.
4. Save project and open in QField
5. Add new feature and enter 1 in the _number_ field.
6. Add another feature and see that the field does not auto-populate. 

### Expected behavior:

The second feature should auto-populate with a number 1. 

### Screenshots and GIFs

This is the function checkbox:

![Screenshot from 2022-04-14 11-15-55](https://user-images.githubusercontent.com/45050185/163440896-ee43e5be-532e-4dda-b145-ac43ca2969e9.png)

Here is the function working properly in QGIS:
![output1](https://user-images.githubusercontent.com/45050185/163442586-512484f2-1776-465a-9b76-389607b4e8a8.gif)

Here is the function not working in QField:
![output2](https://user-images.githubusercontent.com/45050185/163442594-a571a2fd-1b54-45d5-8469-2ae4c559122b.gif)

**QField version:** 2.0.14
## Example Dataset:

[test2_cloud.zip](https://github.com/opengisch/QField/files/8491154/test2_cloud.zip)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@acebulsk , QGIS' [x] reuse last entered value configuration isn't handled by QField at this moment. However QField _can_ reuse last entered value, simply click on the checkbox at the right edge of a given field to tell QField to remember values across feature addition:
![image](https://user-images.githubusercontent.com/1728657/163555621-7f9e1b2d-9030-40ab-809f-8d64d365da82.png)

**Comment by acebulsk** [comment]
@nirvn okay thank you for the clarification! :+1:

**Comment by nirvn** [comment]
@acebulsk , this functionality has been implemented and will be available in QField 3.3. Cheers
