### ISSUE TITLE
QField folders in main directory 

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#276]
On `/data/data/ch.opengis.qfield/files` there are some folders I don't know what they are for. They seem to appear and stay on a crash of QField.
![whatsapp image 2018-04-24 at 18 17 43](https://user-images.githubusercontent.com/28384354/39200268-f8ffb5b6-47eb-11e8-8e2a-bbce1b2f5593.jpeg)

**Comment by VxTedxV** [comment]
I've got 25 folders like that ! I'm not able to find them in my phone to delete them. I can only see them in QField. Any idea to be able to delete them ?

**Comment by m-kuhn** [comment]
What's the content of the folders?

**Comment by VxTedxV** [comment]
Seems to be empty in QField (but can't verify it in the file browser of the phone)

**Comment by signedav** [comment]
I can't find this directories anymore. I close this issue.
Feel free to reopen @VxTedxV if the problem persists.
