### ISSUE TITLE
QFieldCloud Changes pending

### ISSUE THREAD

**Issue by enheduanna** [opengisch/QField#2764]
I collected data in the attribute table of several files offline and pushed the changes to the cloud. However, it keeps saying that changes have not yet been applied and whether or not I want to apply them. I hit "Yes apply pending changes" numerous times, also by selecting the files and and in "action" selected "apply changes". I get a message saying that the changes are being applied but the files remain in "pending" and the changes are not sync. I have done exactly the same for a number of files and it always worked perfectly. The changes made offline were pushed to the cloud and downloaded to a local folder on my pc. This problem only occurred today April 16h. I made changes to files in the same project on April 14th without any issue. 

Two possible issues - I am in Iraq where the internet connection is right now very slow and I have received once or twice the message that the connection has timed out. Is it possible that the server on your end is down? 

Thank you

**Comment by suricactus** [comment]
Hey, this the problem occured since two days and we are working on it. I will close this issue here and see the discussion here https://github.com/opengisch/qfieldcloud/issues/314 .
