### ISSUE TITLE
QField on Windows Mobile

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#277]
Would be awesome :sunglasses:

**Comment by jonnyforestGIS** [comment]
@signedav i think  windows mobile SO will replace by Windows Andromeda in 2019. Please read for more info. https://www.windowscentral.com/microsoft-andromeda-everything-we-know-so-far

About Qfield running in Windows devices particularly in Windows tablets, you can team up with https://github.com/DMS-Aus/Roam developed by @NathanW2 QGIS Developer as good way. 

Roam IntraMaps is similarly to Qfield but oriented to Windows tablet SO and QGIS based. But the project don't have enough activity and i think if you united forces to join the two projects this can result. 

I know they have different names but share the same love QGIS framework. I hope this can help united in some way to join efforts in both projects.

Regards
João Gaspar

**Comment by mbernasocchi** [comment]
we already did plenty of work on this, we are still looking for sponsors to help out finalise the work

**Comment by mbernasocchi** [comment]
Windows suport has landed some time ago already. closing this
