### ISSUE TITLE
Tiny font on date/time widget

### ISSUE THREAD

**Issue by marcp1999** [opengisch/QField#278]
I have a spatialite layer which includes a date field. I've created a form using the drag and drop method and assigned a Date/Time edit widget to that field, with or without the calendar popup. When I view or edit that layer in QField the date is unreadable due to a tiny font. Problem is not specific to spatialite. I've also reproduced it with a Shape layer.

Also, in edit mode, if I click on the picker it defaults to the current date, not the date in the existing field.

![2018-03-28 14 49 37](https://user-images.githubusercontent.com/38697502/39197391-916583e4-47a1-11e8-9cd8-211d2fe58e98.png)

**QField version:** [0.10.13]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No, I've observed this problem on  multiple versions]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes totally consistent]
* Problem happens with all files and projects, not only some files or projects: [Yes, I've reproduced the problem by creating a new spatialite layer in a new project with the same result.]

**Comment by gioman** [comment]
Confirmed on the latest beta

![screenshot_20181115-125145](https://user-images.githubusercontent.com/1951107/48575514-0d7c6100-e90a-11e8-9278-064c5c2ac9a1.png)

**Comment by m-kuhn** [comment]
Might be solved with https://github.com/opengisch/QField/pull/395
