### ISSUE TITLE
Project crashes after reboot

### ISSUE THREAD

**Issue by javiergasan** [opengisch/QField#2782]
The application crashes after a tablet  reboot

### Reproduction Steps:

1. Open the project located on the SD
2. reboot the tablet
3. open the app
4. Select the project again

### Expected behavior:

Open the project

### Observed behavior:

The custom project crashes, but the demo projects still working

If reinstall the app it works until the next reboot

**QField version:** 1.10.0 (1da006 v1.10.0)     
**Tablet  Galaxy tab S2
**Android 7.0
## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@javiergasan , please try against QField 2.1. It's available on Play store by activating beta tester, or by manually installing the APK here (https://github.com/opengisch/QField/releases/tag/v2.1.0). I believe that is fixed.

Make sure you read the storage handling documentation for QField >= 2.0 (https://docs.qfield.org/get-started/storage/), that'll be of help :)

**Comment by javiergasan** [comment]
After installing  version 2.0 It woks

**Comment by nirvn** [comment]
Great 👍
