### ISSUE TITLE
build arm64-Android error ./keystore.p12 (No such file or directory)

### ISSUE THREAD

**Issue by wzxflying** [opengisch/QField#2785]
-- Running vcpkg install - done
-- Building for git rev 8f9aa8af79a85a2eafc515bf7d3bfd516e2e71b9
/usr/src/qfield/platform/android/openssl
-- Searching for QGIS
-- Found QGIS: 3.22.3
-- Found QGIS core: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libqgis_core.a
-- Found QGIS analysis: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libqgis_analysis.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libauthmethod_basic_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libauthmethod_esritoken_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libauthmethod_identcert_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libauthmethod_oauth2_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libauthmethod_pkcs12_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libauthmethod_pkipaths_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_postgres_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_postgresraster_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_wms_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_delimitedtext_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_arcgisfeatureserver_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_arcgismapserver_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_spatialite_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_wfs_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_wcs_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libprovider_virtuallayer_a.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libpq.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libqgis_core.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libspatialite.a
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found suitable version "1.2.11", minimum required is "1") 
-- Reading /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/share/GeoTIFF/geotiff-config.cmake
-- GeoTIFF configuration, version 1.7.0
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found version "1.2.11") 
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found suitable version "1.2.11", minimum required is "1") 
--   include directory: ${GeoTIFF_INCLUDE_DIRS}
--   ${GeoTIFF_LIBRARIES} set to static library
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found version "1.2.11") 
-- Found OpenSSL: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libcrypto.a (found version "1.1.1m")  
-- Found LibXml2: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libxml2.a (found version "2.9.12") 
-- Found OpenSSL: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libcrypto.a (found suitable version "1.1.1m", minimum required is "1")  
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found suitable version "1.2.11", minimum required is "1") 
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found version "1.2.11") 
-- Found OpenSSL: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libcrypto.a (found version "1.1.1m")  
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libspatialindex.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libfreexl.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libqt5keychain.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libpoppler.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libfreetype.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libbrotlidec-static.a
--   Link qgis_core interface to /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libbrotlicommon-static.a
-- Found OpenSSL: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libcrypto.a (found suitable version "1.1.1m", minimum required is "1")  
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found suitable version "1.2.11", minimum required is "1") 
-- Reading /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/share/GeoTIFF/geotiff-config.cmake
-- GeoTIFF configuration, version 1.7.0
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found version "1.2.11") 
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found suitable version "1.2.11", minimum required is "1") 
--   include directory: ${GeoTIFF_INCLUDE_DIRS}
--   ${GeoTIFF_LIBRARIES} set to static library
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found version "1.2.11") 
-- Found OpenSSL: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libcrypto.a (found version "1.1.1m")  
-- Found OpenSSL: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libcrypto.a (found suitable version "1.1.1m", minimum required is "1")  
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found suitable version "1.2.11", minimum required is "1") 
-- Found ZLIB: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/lib/libz.a (found version "1.2.11") 
-- Found QCA: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libqca.a (2.3.4)
-- Found QtKeychain: /usr/src/qfield/build-arm64-android/vcpkg_installed/arm64-android/debug/lib/libqt5keychain.a
-- Found Sqlite3: /arm64-v8a/lib/libsqlite3.so
--    + Qt Installer Framework                NO 
--    + AppImage                              NO 
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/qfield/build-arm64-android
[1/8] Automatic MOC for target qfield_core
[2/6] Generating qrc_qml_qmlcache.cpp
[3/6] Automatic RCC for ../../translations.qrc
[4/6] Building CXX object src/app/CMakeFiles/qfield.dir/qrc_qml_qmlcache.cpp.o
[5/6] Building CXX object src/app/CMakeFiles/qfield.dir/qfield_autogen/UFLBSVMFMR/qrc_translations.cpp.o
[6/6] Linking CXX shared library android-build/libs/arm64-v8a/libqfield_arm64-v8a.so
[1/5] Automatic MOC for target qfield_core
[2/2] Running CPACK. Please wait...
CPack: Create package using STGZ
CPack: Install projects
CPack: - Install project: QField []
CPack: Create package
CPack: - package: /usr/src/qfield/build-arm64-android/QField-1.0.0-Android.sh generated.
CPack: Create package using TGZ
CPack: Install projects
CPack: - Install project: QField []
CPack: Create package
CPack: - package: /usr/src/qfield/build-arm64-android/QField-1.0.0-Android.tar.gz generated.
CPack: Create package using TZ
CPack: Install projects
CPack: - Install project: QField []
CPack: Create package
CPack: - package: /usr/src/qfield/build-arm64-android/QField-1.0.0-Android.tar.Z generated.
Failed to load signer "signer #1"
java.io.FileNotFoundException: ./keystore.p12 (No such file or directory)

**Comment by nirvn** [comment]
That's fixed on master, git checkout origin/master and rebuilt, should work fine.
