### ISSUE TITLE
Problem with (non-)display of polygons in Geopackage layers

### ISSUE THREAD

**Issue by AveryAndrews** [opengisch/QField#2800]
Polygons in geopackage layers don't display properly

### Reproduction Steps:

1. Create project with Geopackage layer with polygon geometry in QGis 3.24.1-Tisler on Win10,
    Make sure that no rendering options are checked
    Configure and export to QField 2.0.15-Dev on Android v9. 
3. Activate editing the  layer,
   make sure that 'show on map' is checked
   add a polygon, fill in an attribute such as Name
   hit the checkbox
   observe that the polygon disappears a moment after the editing form disappears
5. Activate 'show features' and see it reappear
6. Close 'show features' and see it disappear again

### Expected behavior:

It stays visible the whole time upon creation.  This is what happens with a shapefile layer rather than a Geopackage layer.

### Observed behavior:

It disappears except under certain circumstances, including, for a moment, when the project is reloaded.

### Relevant screenshots 
would show nothing, therefore not be useful

**QField version:** QField 2.0.15-Dev 0c5bde v2,0.15

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]
      (at least the multiple test project I set up to investigate it with)
      
 Playing with rendering options appears to have no effect.
 Also happened with projects created by QGis 2.22
 Also happened with QField 2.0.14-dev
 No such problem exists with Geopackage point layers; they work exactly as expected.
 Haven't tried any other geometries

**Comment by nirvn** [comment]
@AveryAndrews , to increase the chance of devs looking into this, please: a/ attach a test project that replicates your issue, and b/ try to record a screencast of the issue and attach it here too.

**Comment by AveryAndrews** [comment]
And today, things seem to work properly, on new projects created by both 2.22 and 2.24, so it will take some time to track down what the problem, presumably some kind of user error, is with the test projects where things don't work right.

**Comment by AveryAndrews** [comment]
Here is a sample project, created on 2.22, that shows the problem with the two layers with polygon geometry. Perhaps somebody can figure out is causing it.

[polytest.zip](https://github.com/opengisch/QField/files/8562301/polytest.zip)

**Comment by nirvn** [comment]
@AveryAndrews , move your polygon layers to sit _on top of your opaque basemap_, things will work.

**Comment by AveryAndrews** [comment]
Yes, thanks!  I should have thought of that.
