### ISSUE TITLE
QField cuts the variable names and values when they are too long

### ISSUE THREAD

**Issue by suricactus** [opengisch/QField#2809]
![image (10)](https://user-images.githubusercontent.com/2820439/165020481-1bd30f21-d4d9-4b21-9a15-8868f5601fae.png)

### Expected behavior:

In the best case we use a table which will automatically take the whole space available, not just fixed 35% of the width. When we run out of space, we should be able to flick horizontally.

**Comment by mohsenD98** [comment]
I think with this [**This PR**](https://github.com/opengisch/QField/pull/5352) issue is resolved.


[Screencast from 2024-07-08 18-26-57.webm](https://github.com/opengisch/QField/assets/36326627/3dd696f2-e18f-4005-8578-65840a180a0a)

@nirvn @suricactus

**Comment by nirvn** [comment]
Fixed, woupidou!
