### ISSUE TITLE
Value Relation Widget

### ISSUE THREAD

**Issue by BeaSavoie** [opengisch/QField#281]
In our QGIS project, we have some attributes whose are defined in layer properties with value relation. It's work well on Qgis but once the project started on Qfield the layer properties is automatically in text edit.
We saw in the setting application that the project should be linked to 3.0 Girona version of Qgis. We open on Qgis 3.0, there's no problem and the problem persists on Qfield.
We want to use value relation with a table without geometry to facilitate updates and the use in lots of projects. 
Have you a solution ? 
Thanks a lot.

**Comment by xyago** [comment]
Hello, i do that and works ok and it works with table with and without geometry
I do:
1) Create the relationes in QGIS project (Project(Properties/Relations).
2) Define the field with RELATION REFERENCE (not works with Value Relation).
3) Sincronize all tables with relations.

I wish this help you.

**Comment by ferenc-attila** [comment]
Hello,
The filters aren't work in the value relation widget for me, while they're ok in QGIS.

Is it a bug or a missing feature or I made something wrong?

Thanks!

**Comment by xyago** [comment]
It works with Relation Reference (previously you need to create the relations in Project/Project Properties) and works with Value Map. 

Value Relation is not implemented.

**Comment by redidisha** [comment]
I heave related one shape file data with csv data using database[sqlite]. this it works on qgis3.2 but when I open project on qfield, relation dont work...

**Comment by m-kuhn** [comment]
It would be one day of work to implement this. 3 days to also review the performance when many of them are used / bigger lists are used.
Meanwhile, the relation approach should work nicely (except for aforementioned performance degradation on heavy usage)

**Comment by Kjewitsch** [comment]
I have the same question here. It is not implemented already, isn't it?

**Comment by m-kuhn** [comment]
See https://github.com/opengisch/QField/issues/281#issuecomment-388039990 for the moment

**Comment by Kjewitsch** [comment]
Ok. But I want to use the function _current_value ()_ in the filter expression. This is not possible in relation references. Any help?

**Comment by signedav** [comment]
That's implemented here #600 meanwhile.
I close this. If there are issues with it, feel free to reopen a new one. Thanks.
