### ISSUE TITLE
unable to esport edited project to folder Qfield 2.0

### ISSUE THREAD

**Issue by RobiFag** [opengisch/QField#2815]
According to the new QField documentation, I should be able to export my edited project to a folder (https://docs.qfield.org/get-started/storage/#exporting-modified-projects-and-datasets) but in the dropdown action menu from Imported project I haven only two option, remove folder or add to favorite as shown in the image below

![Screenshot_20220426-133541](https://user-images.githubusercontent.com/25825472/165291700-47b793a7-4e07-4346-abd9-a6788144e319.jpg)

### Reproduction Steps:

1. Import project from Open Local File --> Import project from folder
2. edit the project
3. Export the edited project

### Expected behavior:

I should see the export to folder option from the dropdown menu

**QField version:** 2.0.14 - Dev (8f9aa8)

**Comment by nirvn** [comment]
@RobiFag , please update to 2.0.15, you'll find the export actions you are looking for there.

**Comment by RobiFag** [comment]
With the new version of Qfield I can see the export to folder option but when I use it any project folder is copied in the selected location. Maybe I miss something?
