### ISSUE TITLE
photo attachment error in ios

### ISSUE THREAD

**Issue by assawhan** [opengisch/QField#2817]
I get an error when I try to attach a photo on my iphone.
But in my android product there is no problem.
There is no problem taking pictures, but the preview does not activate.
Please let me know if you have a solution

ios ver : 15.4.1
qfiled ver : 2.1.0
QFieldSync ver : 4.0.0

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: [Yes]

![KakaoTalk_20220427_102208767](https://user-images.githubusercontent.com/104474092/165419744-a832037c-29fb-4ec7-b0f3-ca550597fed0.jpg)
![KakaoTalk_20220427_102208636](https://user-images.githubusercontent.com/104474092/165419742-33d6d0bc-9824-4762-835c-fbddd881cbe5.jpg)

**Comment by nirvn** [comment]
@assawhan , what is your expression for the photo attachment?

**Comment by assawhan** [comment]
> @assawhan , what is your expression for the photo attachment?

**Comment by suricactus** [comment]
Follows in #2819
