### ISSUE TITLE
What's new is shown every time

### ISSUE THREAD

**Issue by gdt** [opengisch/QField#2818]
QField 2.1.0: Every time the app is opened, it shows a (not very useful; just a github pointer) what's new screen.

### Reproduction Steps:

1. Tap QField icon on home screen and see "What's new in QField"
2. Tap backarrow.  Tap back button to get to home screen.
3. Tap QField in launcher again and see "What's new in QField".

### Expected behavior:

I expect the app to store that the what's new has been shown for a version and not show it again until the app is upgraded.

### Observed behavior:

The what's new screen is shown every time.

### Version

2.1.0, apk from github release

2.1.0-Bumblebee (3e5eac v2.1.0)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Happens with 2.0.14 also.
* Problem happens with all files and projects, not only some files or projects: Yes, happens without a project

**Comment by nirvn** [comment]
@gdt , I can't duplicate here. Whether I install QField 2.1 though the play store or through the APK on the release page, I get the same result: I see the changelog _once_ upon first launching the app. Subsequent launches are changelog-free.

There's likely something specific to your environment that triggers a corner scenario as the changelog souldn't just show a "not very useful github pointer" but a full changelog text.

Is your device connected to the internet?

**Comment by nirvn** [comment]
@gdt , the APKs here (https://github.com/opengisch/QField/pull/2821) should fix your issue

**Comment by gdt** [comment]
I see you have made a change, but I should have said:
  - OS is CalyxOS, Android 12L version
  - OS has firewall but QField is allowed, and QField has been fetching OSM and MassGIS TMS tiles just fine.

The release branch apk indeed does not show the issue.  Thanks for the quick fix.
