### ISSUE TITLE
photo attachment error in ios

### ISSUE THREAD

**Issue by assawhan** [opengisch/QField#2819]
The question was closed by mistake. I ask again

I get an error when I try to attach a photo on my iphone.
But in my android product there is no problem.
There is no problem taking pictures, but the preview does not activate.
Please let me know if you have a solution

ios ver : 15.4.1
qfiled ver : 2.1.0
QFieldSync ver : 4.0.0
photo attachment expression : 'DCIM/n/' || 'n-' || "번호" || '.jpg'

Problem started happening recently, didn't happen in an older version of QField: [No]
Problem can be reliably reproduced, doesn't happen randomly: [No]
Problem happens with all files and projects, not only some files or projects: [Yes]

![165419744-a832037c-29fb-4ec7-b0f3-ca550597fed0](https://user-images.githubusercontent.com/104474092/165652850-d916a714-1fa9-4651-b710-e4e7b02b1207.jpg)
![165419742-33d6d0bc-9824-4762-835c-fbddd881cbe5](https://user-images.githubusercontent.com/104474092/165652856-39088d54-bdb3-49ea-920b-2dea01687af7.jpg)
![3](https://user-images.githubusercontent.com/104474092/165652859-8e64824a-8978-4715-ad2a-59b690c6a472.jpg)
![4](https://user-images.githubusercontent.com/104474092/165652860-bbdcc493-7452-4ee0-bd1b-132210709dd5.jpg)

**Comment by nirvn** [comment]
@assawhan , can you get rid of the /n/ subfolder in your expression to see if that helps?

**Comment by assawhan** [comment]
> @assawhan , can you get rid of the /n/ subfolder in your expression to see if that helps?
![KakaoTalk_20220428_133120258](https://user-images.githubusercontent.com/104474092/165677035-18716ab6-864b-4671-89f9-279186c1d626.jpg)

I tried as you said, but it doesn't work.

**Comment by JUJUBAEDATE** [comment]
Hello. I'm a newbie at Qfield.
I have same problem too.
Did you solve this problem?
혹시 문제해결하셨나요? 저도 똑같은 문제가 발생하는데,
현장조사용 태블릿으로 아이패드를 쓰고싶은데 이게 발목을 잡네요... ㅠㅠ

**Comment by uapmq** [comment]
Hi, I figured it out. Deactivation of the native camera (in Qfield settings) for IOS allow Qfield to take a picture. For those who would have the same issue!

**Comment by m-kuhn** [comment]
Is this solved?
