### ISSUE TITLE
Does not open a form associated with a relationship type field

### ISSUE THREAD

**Issue by alexaardila** [opengisch/QField#2833]
### Describe the issue
When I select the eye icon, it does not open a form associated with a relationship type field

### Reproduction steps
please, check the video showing the error

### Expected behavior
When the eye icon is selected, it allows to consult and/or edit the form associated to the field

### Observed behavior
When I select the eye icon, it does not open a form associated with a relationship type field

### Screenshots and GIFs
please, check the video showing the error

### Mobile (please complete the following information)
 - Device: all cell phones
 - OS: all android
 - QField version: 2.0.15, 2.0.16

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: yes, in version 2.0.14 it worked

https://user-images.githubusercontent.com/95715923/165978251-b9a266a6-6259-4a85-b8dc-0a944cc21e75.mp4

**Comment by nirvn** [comment]
@alexaardila , these APKs (https://github.com/opengisch/QField/pull/2844#issuecomment-1114579125) should fix your issue.
