### ISSUE TITLE
Manual builds stable, official one is not

### ISSUE THREAD

**Issue by mefistotelis** [opengisch/QField#284]
The build on Google Play is unstable on Samsung Note 4.
It was unstable for the whole last year, but an update this year made it worse, impossible to use.

So I decided to build it and debug the issue. But - after building, it turned out that my APK is perfectly stable. No startup crashes, no hang-on-white-screen when changing orientation, no crashes on projects having more than 3 layers. Even restoring after sleep works. Now I have the QField I wanted.

Maybe the build system of official releases could be fixed somehow? Or divided into "more experimental" and "more stable" part?

Some details on building:

It took me ~2 days to setup build system on Windows using MSYS2 toolchain, without docker. This is mostly because I wanted to use MSYS2, and it turns out this toolchain has its own issues. (I also tried Ubuntu, but it was 32-bit system and it turns out Qt works there only up to v5.5 - waste of time).

Then it turned out the version of QGIS downloaded when building OSGeo4A is not really compatible with latest QField source, had to go back to "Release 0.10.7" and then revert commits "Introduce datum transformcontext" and "fix QgsDistanceArea::measureLine using QVector rather than QList".

After this, I was able to build the APK.

Some bad patches I used to build OSGeo4A with MSYS2 are attached.
(these are just dirty hacks, helpful only if you're trying to use MSYS2 too)

[OSGeo4A_build_for_msys_info.txt](https://github.com/opengisch/QField/files/1976458/OSGeo4A_build_for_msys_info.txt)
[OSGeo4A_build_for_msys_libgdal.patch.txt](https://github.com/opengisch/QField/files/1976460/OSGeo4A_build_for_msys_libgdal.patch.txt)
[OSGeo4A_build_for_msys_libzip.patch.txt](https://github.com/opengisch/QField/files/1976461/OSGeo4A_build_for_msys_libzip.patch.txt)
[OSGeo4A_build_for_msys_recipes_cmake.patch.txt](https://github.com/opengisch/QField/files/1976462/OSGeo4A_build_for_msys_recipes_cmake.patch.txt)

**Comment by mefistotelis** [comment]
Oh wait, I was wrong.

The manually built version is as unstable as the official build was. Looks like it is stable during first and second run (worked for ~20 minutes without issues), but when stopped and re-started two times - it is back to "usual" state. Now it is crashing every minute or two, and on every screen rotation.

**Comment by mefistotelis** [comment]
This issue is invalid. The source of instability is not in build system.

**Comment by m-kuhn** [comment]
Too bad, that really sounded interesting!
