### ISSUE TITLE
QField - Autonumeric

### ISSUE THREAD

**Issue by xyago** [opengisch/QField#285]
Is there any way to do a autonumeric field in QField?

**Comment by m-kuhn** [comment]
Using a SQLite based format like SpatiaLite or GeoPackage, that should be doable.
I think playing with default expressions would be an option as well.

**Comment by saemiw** [comment]
With this default you write an integer into a field named "id_creator". Is this of any help? 

CASE WHEN aggregate( @layer_name,'max',"id_creator") is NULL THEN '0'
	ELSE aggregate( @layer_name,'max',"id_creator")+1
END

**Comment by m-kuhn** [comment]
Nice idea, or shorter

```sql
COALESCE(aggregate(@layer_name,'max',"id_creator")+1, 0)
```

**Comment by xyago** [comment]
OK, this is great!!!

I have other question. I work with a posgresql postgis database. When i use qfieldSync, thats convert it in a SQLite database (yes?), so, could i use the SQLite format to calculate fields??

I need to substract two fields in the same layer, but also i need to do other complex calculations in fields of differents layers.

I don´t really know how work Qfield with that, beacause i try with python script, but don´t work.

Thank you!!!!

**Comment by m-kuhn** [comment]
> I have other question. I work with a posgresql postgis database. When i use qfieldSync, thats convert it in a SQLite database (yes?), so, could i use the SQLite format to calculate fields??

Correct.

There are also virtual fields and virtual layers in QGIS and QField available. And SQLite based functionality but no Python support in QField.

I would recommend to either go to [public channels like the mailing list or gis.stackexchange for such questions so the answers are more visible for others or get a support contract with a company](http://www.qfield.org/docs/development/index.html).
