### ISSUE TITLE
Could not open CRS database. Error (14): Unable to open database file.

### ISSUE THREAD

**Issue by Geol0gue** [opengisch/QField#286]
Upon opening a QField project packaged via the QField Sync plugin, an alert icon appears in the upper right corner of the screen. Tapping on the alert shows the following message:

CRS
Could not open CRS database//profiles/default/qgis.db
Error(14): unable to open database file

Upon exiting this and returning to the map canvas the notification disappears and data can be collected (seemingly) without any issues and imported into QGIS, via the QField Sync plugin.

This appears to be similar to the following closed issues (which I have also experienced).

https://github.com/opengisch/QField/issues/192
https://github.com/opengisch/QField/issues/84

I'm cautious about sending staff out to collect data when the issue doesn't seem entirely resolved.

### Reproduction Steps:
Set up project and confirm 'Save paths' is set to 'Relative'

![image](https://user-images.githubusercontent.com/39152831/39862712-72de0f5c-543c-11e8-92b1-20a9b660e9f6.png)

Confirm project CRS is set to British National Grid (EPSG 27700).

![image](https://user-images.githubusercontent.com/39152831/39863154-c420b454-543d-11e8-921c-5d8cb5884d7b.png)

Confirm CRS of each layer in the project (Test Point, Test Line, Test Polygon) is set to British National Grid (EPSG 27700).

![image](https://user-images.githubusercontent.com/39152831/39863203-e50c7248-543d-11e8-8c7b-f8ca9c6327c4.png)

![image](https://user-images.githubusercontent.com/39152831/39863211-eb2b0900-543d-11e8-8c62-f4d93d82691d.png)

![image](https://user-images.githubusercontent.com/39152831/39863222-f2a00d0c-543d-11e8-9b44-1796ce0a718c.png)

Package the project using QField Sync (copy all option used) and drop in the following location on device:

![image](https://user-images.githubusercontent.com/39152831/39863299-29f2f7a6-543e-11e8-8116-d61c1d02441b.png)

Open project in QField using the 'Open Project' dialogue:

![image](https://user-images.githubusercontent.com/39152831/39863506-c116e606-543e-11e8-8abe-33117872f1b7.png)

Full file path copied from the QField dialogue is as follows:

/data/data/ch.opengis.qfield/files/storage/Android/data/ch.opengis.qfield/files/Test Field Package

Project opens successfully, but with error notification in upper right hand corner:

![image](https://user-images.githubusercontent.com/39152831/39863576-f973fd40-543e-11e8-9c33-7bfe18fa74da.png)

Error notification as follows:

![image](https://user-images.githubusercontent.com/39152831/39863594-048af562-543f-11e8-863b-bc3ff81d48fa.png)

Exiting this results in disappearance of the error icon. Activating the GPS correctly places the cursor on the map canvas. This is an an improvement on the issue highlighted in #192 by saemiw on 20th Feb whereby activation of the GPS caused the cursor to centre on a location away from the basemap in white space.

Point, line and polygon data can be collected:

![image](https://user-images.githubusercontent.com/39152831/39863793-8fb05da8-543f-11e8-8bf6-e30f077ca91d.png)

Collected data can be imported to QGIS successfully using the QField Sync plugin and plots in the correct location.

### Expected behavior:

Project opens with no CRS warning

### Observed behavior:

Project opens with three line error warning as described above (as opposed to the multiple lines reported in #192). Upon exiting this, GPS cursor location and data collection appear to function correctly. Data can be imported into QGIS successfully.

**QField version:** 0.10.12 (although this behaviour has been observed as reported in #192 since 0.10.2)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No] - occurred as reported in #192 from v 0.10.2 onwards.

* Problem can be reliably reproduced, doesn't happen randomly: [Yes] - can be reproduced with multiple projects on different devices (Samsung Galaxy Tab Active 2, Android 7.1.1; OnePlus 5, Android 8.1.0, Samsung Galaxy Tab A, Android 7.0)

* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nicpitsch** [comment]
@mbernasocchi, with the latest QField version 0.11.0 this error rises now always (Log):

`Error(14) ...
Could not open CRS Database /data/user/0/ch.opengis.qfield/files/resources/srs.db`

I have tried with QGIS 3.3.0 dev. and also QGIS 2.x projects. From Android 6.0.1 to 8.0.0. It happens also with simpliest project containing only 1 shape, within internal memory and also on SD card.

Switch back to QField version 0.10.13, same QGIS project: no error.

**Comment by giedrioks26** [comment]
Problem persists on 0.11.2. "can't open database: ..." wrong GPS location

**Comment by nicpitsch** [comment]
The log says `Could not open CRS Database /data/user/0/ch.opengis.qfield/files/resources/srs.db`.  `/data/user` is not visible to me because root, but obviously QField doesn't find it there. And why does exist a _resources_ folder at `Internal Storage/Android/data/ch.opengis.qfield/files/resources/`?

**Comment by mixedbredie** [comment]
I have the same issue running the latest .apk (qfield-dev-release-0.11.2-armv7) on a Samsung Galaxy Tab 4 with Android 5.1.1
```could not open CRS database /data/data/ch.opengis.qfield/files/resources/srs.db```

The actual location of the CRS database is 
```Storage/Android/data/ch.opengis.qfield/files/share/resources/srs.db```

My QGIS project is using EPSG:27700 and pressing the GPS button zooms me in to 0,0 on the British National Grid rather than to the correct location around 350000, 750000.

**Comment by m-kuhn** [comment]
I think the issue should be fixed with #350 .
We will ship a new version soon, any feedback on this (nasty) issue is much appreciated on the download on the pull request page (#350) or after the release.
