### ISSUE TITLE
Unable to load layers in QField

### ISSUE THREAD

**Issue by gisisfun19** [opengisch/QField#2860]
have configured a QGIS Project file in QGIS 3.22 and used the QFieldSync version 3.4.4 to create a QField Package Project File to be imported into my tablet. However, I encountered this error upon loading the QGS file in QField.

Some of my colleagues also encountered this error. As a workaround, they closed their QGIS project and then repackaged again the project using QFieldSync. They transferred the file to their tablets and luckily the error was fixed and the following layers were able to be loaded.

I did the same workaround but still encountered this error. What could be the cause of this error? Are there any solutions or fixes for this aside from the one I mentioned?

Thanks!
![received_2610254435775161](https://user-images.githubusercontent.com/104948522/166842539-099f79ba-9a68-4d94-a9a0-2db99e1ce43b.jpeg)

**Comment by suricactus** [comment]
Note QFieldSync 3.x is no longer supported. What I see from the provided screenshot is that some files might be in a different directory that the `.qgs` project file itself, which is also not supported.

Would be nice if you provide a test project so it will be much easier to check your issue.
