### ISSUE TITLE
Relational value don't register

### ISSUE THREAD

**Issue by Ecochiro** [opengisch/QField#2862]
### Describe the issue
Relational value don't register on phone (last Qfield version : 2.0.16 artic fox), but it works on computer (Qgis 3.22 bialowezia)

### Reproduction steps
1. On QGIS : Join a attributes table base on a .shp file with the form
2. Choose the values relational to insert the attributes table base to get a multiple choice field
3. Charge on Qfield the project
4. On Qfield : Create a point and check some attributes, then save the point
5. Repeat the same action several times
6. When we control the created points, we see that the first created point has no registered attributes. However, the following points have well the attributes registered in the field.

### Expected behavior
Every point should show a field with the checked attributes.

### Observed behavior
Register of the checked attributes is irregular. Sometimes, if we go back on view points, the attributes are checked. This tool was however fonctionnal with oldest version of Qfield and Qgis.

### Screenshots and GIFs
The attribute table base :  [COMPORTEMENTS.csv](https://github.com/opengisch/QField/files/8630369/COMPORTEMENTS.csv)

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.22.0

### Mobile (please complete the following information)
 - Device: Samsung Galaxy A20e
 - OS: Android 11
 - QField version: 2.0.16 artic fox

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: No
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@Ecochiro , can you test against the latest available QField 2.2, there has been tons of fixes with relations that hopefully means your issue is gone.
