### ISSUE TITLE
Multiple choice questions duplicate values

### ISSUE THREAD

**Issue by gabgarcies** [opengisch/QField#2865]
Hi everyone,

I have a form in which some questions are multiple choice (question type: value relation). 
![image](https://user-images.githubusercontent.com/80522138/167125832-db4bb3e0-0dee-4fc8-b814-2ab83c284374.png)

I have no idea why some answers sync like this (some others, do not):
![image](https://user-images.githubusercontent.com/80522138/167125627-2ca6f174-aa37-4995-ab09-50badb0a93ac.png)

This behavior is quite annoying... any help will be appreciated.

Thank you,

Gabriel Garcies

**Comment by atsanna** [comment]
I have the same problem when I edit the record.
In my case, being able to edit the record is important.

Thanks

**Comment by baumsicht** [comment]
We have the same issue  (QField 2.1.2).

**Comment by nirvn** [comment]
@gabgarcies , you can test the APKs provided in this PR (https://github.com/opengisch/QField/pull/2971), your issue should be resolved.

**Comment by nirvn** [comment]
I'll assume no news is good news here :) Happy field mapping!
