### ISSUE TITLE
Remember last values: Forget the values when change the layer to digitalize

### ISSUE THREAD

**Issue by xyago** [opengisch/QField#287]
When  press remember last value in a feature of a layer, and chage the layer forget the value (and the option 'remenber last value').

This is an important issue. Many times you have to change layers when you digitize entities, and if the last values are not recorded, forces you to have to enter all the values in the layer again.

### Reproduction Steps:

1. Digitalized mode
2. Select layer A, select remenber values, cover the values and change to layer B digitalize other entitie.
3. When you try to digitalized other feature in layer A, values and remenber option are forgotten.

I think this is a very important issue.

Best regards

**Comment by m-kuhn** [comment]
This would be very nice indeed.
If it is important to you, please consider sponsoring its implementation.

**Comment by saemiw** [comment]
I think this is the same issue, yes? https://github.com/opengisch/QField/issues/177

**Comment by m-kuhn** [comment]
Correct :+1:

**Comment by xyago** [comment]
​Hello we want to know the cost of sponsoring this issue??​

Un saludo.

------------------------------

*Iago Bascoy Feito*
Tel. +34 689 568 898


​
servicios técnicos y de formación en ingeniería, arquitectura y diseño
    <https://www.facebook.com/imasgal>
<https://www.linkedin.com/company/imasgal-t-cnica-sl>

------------------------------

*imasgal técnica, S.L.*

*Av. das Américas. 83 entlo. B 27004 Lugo | Tel. 982 803 001
| www.imasgal.com <http://www.imasgal.com/>*

En cumplimiento de lo establecido en los artículos 5.5 y 30.2 de la Ley
Orgánica 15/1999 de 13 de diciembre, de Protección de Datos de Carácter
Personal (LOPD), le comunicamos que los datos utilizados  en este
e-mail han sido obtenidos de las fuentes accesibles al público establecidas
en el articulo 31 de la LOPD y/o a través de nuestra relación comercial.
Así mismo Imasgal Técnica, S.L., le informa que sus datos forman parte de
un fichero debidamente inscrito en el Registro General de Protección de
Datos, con finalidad la gestión de cliente. Usted podrá ejercer sus
derechos de acceso, cancelación y/o rectificación dirigiéndose a Avd. das
Américas 83 entlo. B, 27004, Lugo, ó entablando comunicación por correo
electrónico en la dirección remitente de este email. El contenido de este
correo electrónico y sus anexos son estrictamente confidenciales. En caso
que haya recibido este mensaje por error, agradecemos nos lo comunique
inmediatamente sin difundir, almacenar o copiar su contenido.

No imprima este email si no es imprescindible, el medio ambiente y nuestros
bosques agradecerán su colaboración ahorrando papel.

2018-05-16 8:49 GMT+02:00 Matthias Kuhn <notifications@github.com>:

**Comment by xyago** [comment]
We wanted to ask how we can sponsored this development.
