### ISSUE TITLE
Invalid relation message

### ISSUE THREAD

**Issue by SandraCardosoEDIA** [opengisch/QField#2880]
Good afternoon,

QField gives an error message - invalid relation in layers that have relations when the project opens. This is a new error (QField 2.1.2 version)! In some equipments (eg. Android 10, Honor View20) this message disapears but in other (eg. android 9, Samsung Tab Active 2) the project crashes. Can you help? 

### Mobile

 - OS: Android 9 and Android 10
 - QField version: 2.1.2 - Bumblebee (1c22b0 v2.1.2)

**Comment by suricactus** [comment]
It would help if you provide a minimal test project that reproduces the error.

**Comment by SandraCardosoEDIA** [comment]
{ Sol_int_0426 }

Hi,

Here is the project for testing.

Thank you


Sandra Cardoso
Técnico Superior | Dep. Informação Geográfica e Cartografia

www.edia.pt<https://www.edia.pt>
www.alqueva.com.pt<http://www.alqueva.com.pt>
Tel. +351 284315100

[https://www.edia.pt/images/rodape.jpg]<https://www.edia.pt/>

De: Ivan Ivanov ***@***.***>
Enviada: 11 de maio de 2022 09:47
Para: opengisch/QField ***@***.***>
Cc: Sandra Cardoso ***@***.***>; Author ***@***.***>
Assunto: Re: [opengisch/QField] Invalid relation message (Issue #2880)

ATENÇÃO: Este email foi originado de fora da organização. Não clique em links ou abra anexos, a menos que reconheça o remetente e saiba que o conteúdo é seguro.


It would help if you provide a minimal test project that reproduces the error.

-

**Comment by suricactus** [comment]
Hey, @SandraCardosoEDIA . I think you have to upload it via the GitHub interface, because direct reply via email does not preserve the attached files.

**Comment by SandraCardosoEDIA** [comment]
ok

Sandra Cardoso
Técnico Superior | Dep. Informação Geográfica e Cartografia

www.edia.pt<https://www.edia.pt>
www.alqueva.com.pt<http://www.alqueva.com.pt>
Tel. +351 284315100

[https://www.edia.pt/images/rodape.jpg]<https://www.edia.pt/>

De: Ivan Ivanov ***@***.***>
Enviada: 11 de maio de 2022 10:31
Para: opengisch/QField ***@***.***>
Cc: Sandra Cardoso ***@***.***>; Mention ***@***.***>
Assunto: Re: [opengisch/QField] Invalid relation message (Issue #2880)

ATENÇÃO: Este email foi originado de fora da organização. Não clique em links ou abra anexos, a menos que reconheça o remetente e saiba que o conteúdo é seguro.


Hey, @SandraCardosoEDIA<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSandraCardosoEDIA&data=05%7C01%7Cscardoso%40edia.pt%7Ca24605eb6f5c40b9f43508da3330fcfe%7Cc3397d2a94104eee9461f43b8efb86ba%7C0%7C0%7C637878582748035214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Uy6UW7HuK4aW%2F3OZHLapOQ1PMDkBsyGGazxHGKyzA1w%3D&reserved=0> . I think you have to upload it via the GitHub interface, because direct reply via email does not preserve the attached files.

-

**Comment by nirvn** [comment]
@SandraCardosoEDIA , regarding the invalid relation, you can see the same error messages when opening your test project in QGIS' console:
![image](https://user-images.githubusercontent.com/1728657/171768178-d1bc6d15-a1f3-4965-a21c-33076dd2bdc6.png)

You should fix those in QGIS first, then if your fixed relations still crash QField, send an updated project.

**Comment by SandraCardosoEDIA** [comment]
I've notest that his error only appears in the QGIS 3.14 version. In other versions, such as 3.16 and 3.22 this error does not appear. What could possibly happen?
Thank you for the answer.



Sandra Cardoso
Técnico Superior | Dep. Informação Geográfica e Cartografia

www.edia.pt<https://www.edia.pt>
www.alqueva.com.pt<http://www.alqueva.com.pt>
Tel. +351 284315100

[https://www.edia.pt/images/rodape.jpg]<https://www.edia.pt/>

De: Mathieu Pellerin ***@***.***>
Enviada: 3 de junho de 2022 02:16
Para: opengisch/QField ***@***.***>
Cc: Sandra Cardoso ***@***.***>; Mention ***@***.***>
Assunto: Re: [opengisch/QField] Invalid relation message (Issue #2880)

ATENÇÃO: Este email foi originado de fora da organização. Não clique em links ou abra anexos, a menos que reconheça o remetente e saiba que o conteúdo é seguro.


@SandraCardosoEDIA<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSandraCardosoEDIA&data=05%7C01%7Cscardoso%40edia.pt%7C0aabec7f93f94576a9d508da44fe8f08%7Cc3397d2a94104eee9461f43b8efb86ba%7C0%7C0%7C637898157362285743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K%2FoC6RRrypR7KReLlMkMKP2o782Vsj20rz7oWp6kgWc%3D&reserved=0> , regarding the invalid relation, you can see the same error messages when opening your test project in QGIS' console:
[image]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1728657%2F171768178-d1bc6d15-a1f3-4965-a21c-33076dd2bdc6.png&data=05%7C01%7Cscardoso%40edia.pt%7C0aabec7f93f94576a9d508da44fe8f08%7Cc3397d2a94104eee9461f43b8efb86ba%7C0%7C0%7C637898157362285743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l5WLgoj7UVnlM8BNFGqhS%2FLfGaIO%2Bg6wsACtq%2FWhgAU%3D&reserved=0>

You should fix those in QGIS first, then if your fixed relations still crash QField, send an updated project.

-
