### ISSUE TITLE
Relation widget cannot be opened

### ISSUE THREAD

**Issue by hissakai** [opengisch/QField#2890]
### Describe the issue
Relation widget data cannot be added/opened. "+" -sign for opening relation widget doesn't appear and child data cannot be added.

### Reproduction steps
1. Edit mode and add some data to form
2. Try to open child-form -> not possible ("+" -button missing)

### Expected behavior
Child data can be added 

### Desktop (please complete the following information)
 - OS:  Windows]
 - QGIS Version 3.22.0
 - QFieldSync Version 4.1.1

### Mobile (please complete the following information)
 - Device: SAmsung a42
 - OS: 11
 - QField version: 1c22b0 v2.1.2

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by hissakai** [comment]
[test_project.zip](https://github.com/opengisch/QField/files/8676136/test_project.zip)
With QField version e3af71 v2.0.12 this test project works fine. Child elements can be added to main table.

**Comment by suricactus** [comment]
If you enable the drag and drop designer, instead of autogenerated form, the widget appears properly with the ability to add new child features.

**Comment by hissakai** [comment]
> If you enable the drag and drop designer, instead of autogenerated form, the widget appears properly with the ability to add new child features.

Well, this solved my problem, thank you very much! :)
