### ISSUE TITLE
WMS Reprojection Issue

### ISSUE THREAD

**Issue by boesiii** [opengisch/QField#29]
I have a map using shapefiles in epsg 2272 with a WMS which gets reprojected.  When the WMS gets reprojected the image is clipped.  Sample data and screengrab attached.

![screenshot_2016-03-31-16-33-20](https://cloud.githubusercontent.com/assets/2079638/14190049/a4aacd28-f75e-11e5-8c35-58e558c22729.png)
[sample data.zip](https://github.com/opengisch/QField/files/198547/sample.data.zip)

**Comment by m-kuhn** [comment]
Can you check if this persists with QField 0.8
