### ISSUE TITLE
Attribute form new entry button is missing on the Qfield App

### ISSUE THREAD

**Issue by chadcottlezip** [opengisch/QField#2901]
![Expected Behaviour](https://user-images.githubusercontent.com/82982774/168454526-a4e3efcb-e8ee-4aa6-8dd9-a6ed46af4204.jpeg)
![Observed Behaviour](https://user-images.githubusercontent.com/82982774/168454527-3cff668a-d5cc-4f4b-8bb5-60f98e11c016.jpeg)
### Describe the issue
The button to add a new entry to the attribute form of a layer has disappeared and now just shows a blank white bar meaning you can no longer add new entries.

### Reproduction steps
1. Go to a point on the map
2. Click on the point/device
3. Select your point/device
4. Start an editing session on the point/device
5. Scroll down to the attribute form section
6. The new entry box with a black + is no longer there.

### Expected behavior
This new entry box with a black + on the right hand side is meant to be clicked on to add new information 

### Observed behavior
The button is no longer there to click on

### Mobile (please complete the following information)
 - Devices: Oneplus 8, Vivo Y11s, Samsung Galaxy S20FE, Samsung Galaxy A52s, Blackview 9700 Pro
 - OS: Android 9, 10, 11, 12
 - QField version: 2.1.2 - Bumblebee

### Additional information
* Problem started happening recently after app was updated to 2.2.1 Bumblebee, doesn't happen in older versions of QField.
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
This has been fixed with the latest release
