### ISSUE TITLE
WFS Issue

### ISSUE THREAD

**Issue by jeffmsig** [opengisch/QField#292]
Hello,
I have a project using geoserver wfs layer. I work fine but I have always this error message when I load the project:
Cannot Create temporary spatialite cache.

Could it be a problem like this : 
https://issues.qgis.org/issues/15062

**QField version:** [0.10.13]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by gnerred** [comment]
Hi,
I am facing the same problem, and I work a lot with WFS... This bug came from 0.10.10, it works well on 0.10.9 ! Hope this helps for fixing.
Thanks

**Comment by m-kuhn** [comment]
Could you provide us with a project for testing?

**Comment by gnerred** [comment]
Ok I've sent you a projet by email

**Comment by gnerred** [comment]
Hi,
Any idea about the resolution state of this issue ? 
Thanks

**Comment by signedav** [comment]
Sorry @gnerred It' still not solved. We are working on it.

**Comment by gnerred** [comment]
Ok thanks for feedback

**Comment by signedav** [comment]
Hi @gnerred Can you test it with one of the latest created APKs. 
Like the one from this #344 

[Download here](https://opengis.ch/download/qfield/ci-builds/qfield-dev-344-598b93dd95574e49001b375fdc21a95b3ab1f87e-armv7.apk)

**Comment by gnerred** [comment]
Hi,
I tested, but it freezes when loading...
![screenshot_2018-08-29-08-01-20](https://user-images.githubusercontent.com/1989467/44768691-64bc3200-ab62-11e8-9e44-f3cbb5c878cf.png)

**Comment by signedav** [comment]
Thanks for testing.

Can you provide me the project you are testing with? I think the last one has WFS layer not existing anymore.

@m-kuhn with what QGIS version are the latest QField builds created?

**Comment by gnerred** [comment]
Yes, could you please give me your email ?

**Comment by m-kuhn** [comment]
0.11.2 is based on master from last week

**Comment by signedav** [comment]
david at opengis dot ch @gnerred

**Comment by signedav** [comment]
Thanks for the project @gnerred 

With the download I linked and with the latest apk [here](https://github.com/opengisch/QField/releases/tag/release-0.11.2) I have the following behavior:
- With the project like you sent it to me: cannot open the layer, but no freeze (opening without the features)...
- With the project including user='test' password='test': can open it and see the polygons.
And I have the message "WFS Layer extent reported by the server is not correct. You may need to zoom again on layer while features are being downloaded"

So I cannot reproduce your exact behavior, sorry. 
Is it a freeze in fact or is it just an endless loading?
And can you test it with configured username/password in the project and tell me if you are able to open the project?

Thanks!

**Comment by gnerred** [comment]
Oh sorry, the endless loading is due to user / password not supplied... When I write user='test' password='test' in project, it runs OK ! So this issue is solved for me. But I would be great if QField could ask user for user/password when loading, as QGIS does. Is there a wishlist in wich you could integrate this functionnality ? Thanks a lot for work !

**Comment by signedav** [comment]
Opened an "Enhancement"-Issue #347 for the Login-Feature :-)
