### ISSUE TITLE
Path to project file in QField app does not match actual path to project file

### ISSUE THREAD

**Issue by AndeVandenberg** [opengisch/QField#293]
Apologies for wasting time if this is rudimentary.

Browsing for QGIS projects in the QField app seems to be problematic. The path to the project file through QField does not match the actual location that the project is saved and it seems to show incorrect directories that do not match the actual Android directory.

"data/data/ch.opengis.qfield/files/storage/Android/data/ch.opengis.qfield/files"

The project opens and everything seems to work perfectly, however.

This is happening on both Samsung Galaxy 8  (Android 8.0.0) and Samsung Tablet A (Android 7.0)

### Reproduction Steps:

1. Save QGIS project correctly on desktop (using QFieldSync)
2. Copy project to device to "Android\data\ch.opengis.qfield\files"
3. Open QField and 'Open Project'

### Screenshots and GIFs
![screenshot_20180622-180123](https://user-images.githubusercontent.com/40511773/41806051-85589d3c-766a-11e8-9034-2244a3932b80.jpg)

**QField version:** 0.10.13

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: This is the first version I've used.
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by AndeVandenberg** [comment]
Could this incorrect path be creating errors in the places that photos are saved QField? 

I have ran a couple tests and cannot find the captured photos anywhere on the Android device.

![screenshot_20180627-090125](https://user-images.githubusercontent.com/40511773/41996681-85ecc3f6-7a0a-11e8-80c8-567a0886d6d5.png)
![screenshot_20180627-090137](https://user-images.githubusercontent.com/40511773/41996683-8700d534-7a0a-11e8-8725-5ca5493cdf39.png)

**Comment by VxTedxV** [comment]
Photos are saved in the DCIM folder, in the .qgs project's folder.

**Comment by signedav** [comment]
Hi @AndeVandenberg On the newer releases of QField we have a much better file navigator to find your projects. Did you tried it out?

Feel free to close this issue, when you think it's solved.

Thanks.
