### ISSUE TITLE
Residual values in a new record of tables related to an entity

### ISSUE THREAD

**Issue by Fertuesta25** [opengisch/QField#2936]
### Describe the issue
Residual values in a new record of tables related to an ent

### Reproduction steps
1. Create a QGIS project with a table related to an entity
2. Create a field that stores integer data
3. Configure the form with the editable range control type for the created field
4. In QField start a record in the related table and then a second record
5. Use the +/- buttons to increment the values in the field

### Expected behavior
When adding a new record the form should be clean with no residual values from the previous record

### Observed behavior
There are residual values from the previous record in the form

### Screenshots and GIFs
Registro 1
![Registro 1](https://user-images.githubusercontent.com/59838508/170279745-0266c035-4a05-4c02-963c-7492786d05e0.jpeg)
Registro 2
![Registro 2](https://user-images.githubusercontent.com/59838508/170279796-c04661dc-5680-41ed-b6f3-e71d253785c3.jpeg)

[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows 10]
 - QGIS Version [e.g. 3.24.3]
 - QFieldSync Version [e.g.4.1.1]

### Mobile (please complete the following information)
 - Device: [e.g. moto g(50) 5G]
 - OS: [e.g. Android 11]
 - QField version: [2.1.4 - Bumblebee (496792 v2.1.4)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] - I don't know
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] - I don't know
* Problem happens with all files and projects, not only some files or projects: [Yes/No] - I don't know

[If the problem happened with QFieldCloud, please add your username (ftuestac) and project name (Calidad_Cosecha).]

**Comment by Ipickedausername** [comment]
Hi, 

I think this issue is the same as the one I presented in this post : 
[https://github.com/opengisch/QField/issues/2612](url)
