### ISSUE TITLE
Multiple values recorded but not well displayed

### ISSUE THREAD

**Issue by bsaglio2001** [opengisch/QField#2954]
### Describe the issue
Multiple values for a value relation field are recorded but not always correctly displayed

### Reproduction steps
1. Create a new feature
2. Select multiple values in the proper field
3. Save the new feature
4. Select this new feature and display its form - The previous values will probably not be displayed properly
5.  Try to select multiple features, and then switch from one form to another by clicking the left or right arrows - Sometimes the multiple values recorded are correctly displayed.

### Expected behavior
Always a proper display (checkboxes checked) of multiple values recorder !

### Observed behavior
Unstable display

### Screenshots and GIFs
![Screenshot_20220603-111729](https://user-images.githubusercontent.com/47885683/171827017-973e393a-5fd4-4a24-b0f1-631e18b35084.png)
![Screenshot_20220603-111744](https://user-images.githubusercontent.com/47885683/171827025-3c3e4d85-1fea-4dfb-b927-cf4feccb59ad.png)
![Screenshot_20220603-111755](https://user-images.githubusercontent.com/47885683/171827032-7b1b6dbd-808f-4312-ad93-d17154f4c937.png)
![Screenshot_20220603-111807](https://user-images.githubusercontent.com/47885683/171827035-29e0b2ea-0dea-4423-9c12-82794c7b5bd6.png)

attached QGIS files : basic configuration to reproduce the problem
[TEST_VALEURS_MULTIPLES.zip](https://github.com/opengisch/QField/files/8831146/TEST_VALEURS_MULTIPLES.zip)

### Desktop (please complete the following information)
 - OS: Windows 10 Professional
 - QGIS Version : 3.22 / 3.16 / 3.10
 - QFieldSync Version : not used

### Mobile (please complete the following information)

 - Device: Nokia 7 plus
 - OS: Android 10
 - QField version: 2.1.4 - Bumblebee (496792 v2.1.4)

### Additional information
* This bug seems to be linked to this other issue ; https://github.com/opengisch/QField/issues/2865

**Comment by larslund** [comment]
Also applies to Value Relation Fields with "Allow multiple" activated:
https://github.com/opengisch/QField/discussions/2888

**Comment by nirvn** [comment]
@bsaglio2001 , you can test the APKs provided in this PR (https://github.com/opengisch/QField/pull/2971), your issue should be resolved.
