### ISSUE TITLE
QField crash after printing atlas to pdf

### ISSUE THREAD

**Issue by lindauju** [opengisch/QField#2962]
### Describe the issue
QField is crashing after printing Atlas features to PDF

### Reproduction steps
1. Show feature list
2. Toggle feature selection
3. Check a feature
4. Click on Print Atlas Feature to PDF
5. QField is crashing

### Expected behavior
Print a PDF, in  a older Version of Qfield the Atlas Print was ok.

### Observed behavior
Qfield is crashing

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.16.11
 - QFieldSync Version 4.1.0

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab A
 - OS: Android 11
 - QField version: 2.1.4 (496792)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by nirvn** [comment]
@lindauju , can you attach a test project here? Trying atlas printing in the simple bees demo works ok here.

**Comment by lindauju** [comment]
@nirvn i have tested the atlas printing with the bees demo. This is working.

In my project the atlas printing is crashing qfield. I have attached a simplifed version of my project. I start the atlas printing with the feature list of rapport. There is one Rapport in the sample project
[test_Github.zip](https://github.com/opengisch/QField/files/8909642/test_Github.zip)
.

**Comment by nirvn** [comment]
@lindauju , excellent I can get it to crash

**Comment by nirvn** [comment]
Crash occurs in QGIS, issue lies upstream.

**Comment by nirvn** [comment]
Fixed upstream, will be part of QField 2.2.

@lindauju , thanks for your reporting efforts.
