### ISSUE TITLE
QFieldCloud synchronisation from App to Cloud does not work

### ISSUE THREAD

**Issue by JonnyFri** [opengisch/QField#2966]
### Describe the issue
Changes made in the QFIELD App result in an error in the changes menu.
QFIELD dosent give out a error message.
I can push the results onto the cloud, but there i cant approve it because it fails.

### Expected behavior
[Normally you should approve the change to implement it into your project]

### Observed behavior
[QFIELD CLOUD says error in the change menu.
Every job gets the status failed]

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.24.2]
 - QFieldSync Version [e.g.4.1.1]

### Mobile (please complete the following information)
 - Device: [Samsung Galaxy Tab]
 - OS: [e.g. Android 11]
 - QField version: [2.1.4]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

[jonnyfr, [QFIELD_2022_04-29_qfield]
![image](https://user-images.githubusercontent.com/96238971/172827438-df5eca96-88b6-4784-98ba-10c27273861b.png)

**Comment by m-kuhn** [comment]
Is this still an issue?
