### ISSUE TITLE
QField not responding on upgreaded tablet

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#297]
Customer wrote:

> Samsung Galaxy Tab 3 (GT-P5200), i installed QField when tablet was running a stock ROM (android 4.1) and QField crashed at startup. 
> Now i installed a custom ROM (LineageOs 14.1) (android 7.1) and QField starts but shows an empty screen. 
> 
> I'm using latest QField version available on Play Store [...] the release date is april 23, 2018.
> 
> I'm using succesfully QField on an smartpgone (OnePlus One) running LineageOs 15.1 (android 8.1).
> I'm trying to use (unsuccesfully) the same release of QField on a tablet (Samsung Galaxy Tab 3 10.1 GT-P5200).
> The differences between smartphone and tablet hardware are:
> - SOC (ARM vs. x86)
> - screen size (5.5” vs. 10.1”)
> - available RAM (3GB vs. 1GB). However, QField "run" on 168MB RAM on tablet.
> 
> Syntoms on tablet are:
> - unresponsive screen;
> - missing menu text.
> 
> Every other app runs fine on tablet.

[2018-07-09_16.24 (1).zip](https://github.com/opengisch/QField/files/2180198/2018-07-09_16.24.1.zip)

**Comment by m-kuhn** [comment]
Did you download the x86 release and manually install it? I think there's still an issue with distribution of x86 binaries through play store.

**Comment by niubii** [comment]
Hi,
I'm the "customer" from the first message.
I've definitively solved, thank you for support.

What I've done:
- restored a stock Android 4.4.2 ROM (*)
- removed the QField App coming from Google Play
- installed the .apk from https://github.com/opengisch/QField/releases/download/release-0.10.13/qfield-release-0.10.13-x86.apk
- Et voilà :-) QField is now running on Samsung Galaxy Tab 3.0 3G (GT-P5200).

Not yet tested in every function, but at least it don't crashes.
Again, thank you for support.

Francesco

(*) I also tried to manually install the apk in the Android 7.1 custom ROM (LineageOS 14.1 unofficial), but it crashes as in the official Google Play app.

**Comment by m-kuhn** [comment]
Thanks for the feedback, glad it helped.

> (*) I also tried to manually install the apk in the Android 7.1 custom ROM (LineageOS 14.1 unofficial), but it crashes as in the official Google Play app.

That's surprising, we're running (the arm version) happily on latest LineageOS here).
