### ISSUE TITLE
Do not see .qgs

### ISSUE THREAD

**Issue by Nekkinisiwan** [opengisch/QField#298]
Hi everybody,

I am a new user of Qfield. My issue is that I can not see the project copied from my desktop

Here are the Steps I followed :

1. I first installed the latest version of Qfield on my tablet (Samsung Galaxy S3) version 0.10.13 - Kesch
2. I exported my project from desktop with qfieldsync. I am using Qgis 2.14.3 Essen
3. I then copied the project on the tablet at the following path : /Android/data/ch.opengis.qfield/files

The problem is that when I want to open my project from Qfield, I don't see the folder I copied from desktop. i tried to move it to another path and same thing.

I am really disappointed that I am stuck in the very first step. the basis of opening a project !
is anybody faced this before or have any clue fro me.

thx in advance

**Comment by m-kuhn** [comment]
No worries, this is still the hardest step (unfortunately!)
Can you copy the files to the root folder of your tablet and then on the tablet navigate to `/sdcard` and check if it's there?

**Comment by Nekkinisiwan** [comment]
Hi,

I have no SDCard installed on the tablet

**Comment by signedav** [comment]
Even with no SDCard you should have a folder called `/sdcard`. Actually it's the internal storage space.
I know it's really confusing. AFAIK an external storage (real SDCard) would be called like `/sdcard-ext`.

**Comment by Nekkinisiwan** [comment]
Hi everybody,

You were right, the project was in /SDCard.
I was a little bit tired to not see that.

Thank you for your help
