### ISSUE TITLE
Hidden (SVG-)folders / SVG's are not shown

### ISSUE THREAD

**Issue by koenigherford** [opengisch/QField#299]
Custom SVG's are not recognized

### Reproduction Steps:

1. Fresh install of QFIELD from PlayStore (on Samsung Galaxy Tab A6 with Android 7.0 (with system-update from today after the problems described below)) 
(It seems there is no Samsung "Secure Folder"-App on the device. Samsung Knox-App can not be deactivated) (-> #282))
2. Lauch QField/Open Project

### Expected behavior:

File-structure of mobile device in qfield-menu is in the same structure as on other android-apps (on android I used GhostCommander or ES FileExplorer which shows hidden files/foldes too ) and windows-explorer (I changed the settings to display hidden system-files and hidden files and folders)
Custom SVG's can be copied to a auto-created, custom SVG-folder.

### Observed behavior:

File-structure of mobile device is not shown in qfield-menu in the same structure as on other android apps (and windows-explorer)
The auto-created SVG-folder for custom SVG's does not exist for file explorer apps outside qfield (There is a additional "share"-folder-level in qfield (with the subfolders resources/svg/share)). Several files of the data\ch.opengis.qfield-folder are inaccesible without root-access. This will destroy the device warranty.
 

### Screenshots and GIFs
As not shown in FileExplorer-Apps/WindowsExplorer I created a new folder "ch.opengis.qfield\files\share\svg" and copied custom svg-files into this folder but the svg's are not recognized in the qfield map (only displayed with "?")
Using the QFieldFile-Browser "my" svg-folder is in a second "share"-folder (a level deeper than in other FileBrowser-Apps): "ch.opengis.qfield\files\share\share\svg". The auto-created-svg-folder is on the level "ch.opengis.qfield\files\share\svg" - which can not be reached by other file-browser-apps.

As there are 2 svg-folders (autocreated and manually created) the problem becomes probably more clear with the custom-project data-folder: In QFIELD-FileBrowser it has the path 
[...] data\ch.opengis.qfield\files\share\SHARE\mobiles_gris_Juli_2018_qgis3_2 

![grafik](https://user-images.githubusercontent.com/28433436/42569617-6673dc6e-8511-11e8-81d1-00ad01006f83.png)

In Windows-Explorer or the other AndroidFileExplorerApps on the the device the path is shown without the second "share"-folder level - it's just 
[...]data\ch.opengis.qfield\files\share\mobiles_gris_Juli_2018_qgis3_2

![grafik](https://user-images.githubusercontent.com/28433436/42569968-9624e312-8512-11e8-9f13-aa7561446ce8.png)

(Although the path differs between the two apps the project runs (just without the custom-svg's). )

I think, the wrong/unreachabele/differing storarge of custom svg-data is the reason for the issue. 
Do you have an idea how to solve the issue/access the auto-created svg-folder ? I think it's related to #282, but there is no "Secure Folder-App" on my device which can be deactivated. The "Knox App" can not be deactivated.
**QField version:** 0.10.13

**Comment by VxTedxV** [comment]
Read comments in #130 
Try to reinstall QField but not with PlayStore...

**Comment by koenigherford** [comment]
Yes, did this approach yesterday too - but did not mention it. Made a fresh download from github today deinstalled the PlayStore-version and installed the Github-version of 0.10.13 on my device.. Same result:

![grafik](https://user-images.githubusercontent.com/28433436/42614626-fe96c444-85a6-11e8-8ea4-e15e8bb13795.png)

#130 is from me too. We had a device where after some trys everything worked well - but I do not know how.

**Comment by VxTedxV** [comment]
I tested and I have the same thing but look at the Qfield path which a bit different with data/data/
When you go backward in the Qfield path, you can notice it's not the same folders as in the phone...
But I don't find how to access these folders from the android file explorer...
Related to #276

**Comment by koenigherford** [comment]
Is it a possibility 
1) to store the default-(and custom)-svg folder outside the android/data/data-folder
or
2) to add a settings-interface to set a additional user-defined-svg-path. This will reduce the risk of data- loss / additonal installation efforts of custom svg-data after a version-update

Something like
![grafik](https://user-images.githubusercontent.com/28433436/42623635-a72fa0aa-85c3-11e8-86fb-64cc1ab0d58b.png)
in QGIS

**Comment by VxTedxV** [comment]
Before :
- QField 0.10.13
- project with custom SVG : custom SVG were well shown

After (Playstore update) : 
- QField 0.11.0
- same project : custom SVG are shown with "?"
- no path shown in "about" menu...

**Comment by grdaveygrd** [comment]
The situation (Issue 332) on my Samsung Galaxy Tablet S2, Android 7.0 and 0.11.0 - I couldn't open a project through QField (couldn't find the path) but have installed Total Commander which does allow me to open a project. Once a project is open, I can then open another one through QField. With all layers in the correct CRS, I get multiple Can't open database:... messages whenever I do anything such as scroll around - even if there are not svg characters in any of the tables.. Svg files are not found in any workspace that has tables with them, although they can be seen in the QField browser for opening files. But the path shown is quite different to where I copied them, and can see them with Total Commander. There is no Secured Folder app on this tablet. It would be really nice to have this sorted out as I bought the new tablet for a job I will be doing in a few weeks. 

On my Galaxy Tab A 2016, Android 5.1.1 and Qfield 0.10.13 things work fine, svg characters show up, although in About - QField Shared Items Folder, there is no path shown - same as on the other tablet. I did try 0.10.13 on the Tab S, with no success.

**Comment by m-kuhn** [comment]
We are really sorry for the inconvenience. We are working on this issue with high priority.

**Comment by VxTedxV** [comment]
After a fresh install of QField 0.11.4 from .apk, my custom SVG from my usual project show again.

**Comment by grdaveygrd** [comment]
I've installed 0.11.4 from Github, but in "About" the QField Version is shown as 0.11.2 and there is nothing listed under "QField Settings folder:" or "QField Shared items folder:"

My svg files are still not showing. However I can now open a QField project from within QField.

**Comment by grdaveygrd** [comment]
Update - the above is for my Galaxy S2 with Android 7.0. I've also installed Qfield 0.11.4 on my Galaxy Tab A 2016 with Android 5.1.1. On the latter svg symbols are showing, they are in the same folder (share/svg) as the S2.  The "QField Settings folder:" and the "QField Shared items folder:" have the correct paths shown on the Tab A.

**Comment by koenigherford** [comment]
Deinstalled QField 0.10.x
Installed QField 0.11.4 (on Samsung Galaxy Tab A6 with Android 7.0)
Result:
Warning is shown first time opening with following text
"CRS
Could not open CRS database / data/user/0/ch.opengis.qfield/files/share/resources/srs.db
Error(14): unable to open database file
Can't open database: unable to open database file
Can't open database: unable to open database file
..."
->
Checked the files with a FileExplorer app and QField:
Result:
Folder"/ data/user/0/ch.opengis.qfield/files/share/" is empty. No "resources" or "svg" or other subfolders extracted during install.

**Comment by koenigherford** [comment]
Tanks a lot for for solving the issue with 0.10.11. - The only new problem (-on qgis- 3.4.1.-side) is that -according to 
https://issues.qgis.org/issues/20276 and
https://github.com/opengisch/qfieldsync/issues/94
 the whole (former postgis-data) symbology is lost because the symbology-steering values are shifted to the next field. 
(As a workaround i renamed the fieldnames - which is not good a good approach if you try to syncronize the data later). So I hope the qgis bug will be fixed soon to.

**Comment by m-kuhn** [comment]
Thanks for the feedback @koenigherford 
Can we close this issue?

**Comment by koenigherford** [comment]
yes

Mit freundlichen Grüßen

Ralf König
Abteilung Stadtplanung, Grünflächen und Geodaten
[cid:image001.jpg@01D47C01.563F7D80]<http://www.herford.de/>
Tel.: +49 5221 189 617
Fax: +49 5221 189 691
eMail: Ralf.Koenig@Herford.de<mailto:Ralf.Koenig@Herford.de>

Hansestadt Herford
Auf der Freiheit 21
32052 Herford
http://www.herford.de

Bitte denken Sie an Ihre Verantwortung gegenüber der Umwelt, bevor Sie die E-Mail ausdrucken.

[cid:image002.gif@01D47C01.563F7D80]
Von: Matthias Kuhn [mailto:notifications@github.com]
Gesendet: Mittwoch, 14. November 2018 10:04
An: opengisch/QField
Cc: König, Ralf (Hansestadt Herford); Mention
Betreff: Re: [opengisch/QField] Hidden (SVG-)folders / SVG's are not shown (#299)


Thanks for the feedback @koenigherford<https://github.com/koenigherford>
Can we close this issue?
