### ISSUE TITLE
Version mismatch : About vs. PlayStore information

### ISSUE THREAD

**Issue by ceeu01** [opengisch/QField#30]
updated to from v. 0.5.2 to 0.5.6 on play store but realized that 0.5.5 (instead of 0.5.6) was installed. 0.5.5 seems to be very unstable since i cannot open projects worked on 0.5.2

using android 5.1.1

**Comment by m-kuhn** [comment]
Confirmed that the version in the about dialog is currently wrong. Will fix with next release.

For the other issue, please open a new report and include details about what exactly happens.

**Comment by m-kuhn** [comment]
Fixed in 0.6.0
