### ISSUE TITLE
Error postgis trying to save edits after synchronization

### ISSUE THREAD

**Issue by agatacc** [opengisch/QField#300]
Dear colleagues, 

I'm working in qfield and qgis and the plugin qfieldsync. I have the trouble after synchronize the data from qfield to qgis, when I want to save edits, I get an error and I can not add the new data to postgis layer. 

Steps:

1. I packed my qgis project, where there’s one postgis layer (object to edit) and a ortho base map (google map Tile server). I export it to qfield.
2. When I pack the qgis project, the postgis layer is changed into data.sqlite and the base map to a basemap.gpkg. 
3.The field work consists on editing and adding information on pre-existent features (exploring mode) and in some cases digitizing new features on field. Any problem with qfield field work.
4.The problem I have is when I try to synchronize qfield to qgis. Firstly, it synchronize perfectly and I can view the changes done in the field, but when I try to save the editing changes I get this error: 

_**Error de PostGIS al cambiar atributos: ERROR: prepared  statement "updatefeature" already exists.**_

I would expect that I could save to the postgis layer of the qgis project the new or modified data done during the work by qfield.

The versions are qfield (version 0.10.13 - Kesch) and qgis (version 2.18.7).

I got the same problem with other projects but it's the same dbase because all my data is in one dbase. 

![image](https://user-images.githubusercontent.com/41004320/42689413-79067e82-86a0-11e8-9bb8-5bc9f7cc0eb2.png)

]

**Comment by m-kuhn** [comment]
This is an issue within the offline editing functionality (or the postgres provider) of qgis itself. I can see that you are running QGIS 2.18.7, which is quite old. Can you try again with QGIS 3.2 (or the latest 2.18 version)?

**Comment by agatacc** [comment]
Hi, I tried what you said. I downloaded the qgis 2.18.21 version (ltr) and I got exactly the same error. Then I downloades the qgis 3.2 but, the plugin qfieldsync doesn't work with this latest version. 
When you say, postgres provider, do you want mean that maybe it could be pgAdmin? I'm working with PgAdmin 4. 

Thakfully

**Comment by m-kuhn** [comment]
For QGIS 3 you need to manually install the plugin using the "install from zip" in the plugin manager and download the zip from [releases](https://github.com/opengisch/qfieldsync/releases/tag/3.0.0).

The problem *sounds* like it's in the part of QGIS that makes the connection between QGIS and the postgres database. Most likely not in QFieldSync and certainly not in pgAdmin.

If the data is not sensitive, could you upload the `data.sqlite` file (and a backup of the postgres database) here?

**Comment by signedav** [comment]
Hi @agatacc 
What is the status here? Is it still happening on later QGIS versions?

**Comment by agatacc** [comment]
Hi signedav, 
To be honest, I don't remember how to solved it, I think I didn't solve the syncronisation with the postgis database and at the end I worked with shapefiles......but I'm not sure.....

**Comment by signedav** [comment]
Okay thanks. I'm pretty sure it works with newer QGIS versions.
I close this issue. Feel free to reopen if you have the problem again. Thanks.
