### ISSUE TITLE
Embedded Layers still reference remote layer in the packaged QField Project

### ISSUE THREAD

**Issue by legnad** [opengisch/QField#3004]
### Describe the issue
I have a QGIS project which contains multiple embedded layers from a different project file. There are PostGIS, WMS, TIF among them. The PostGIS layers only work when setting them to "Offline editing". "Directly access data source" and "Copy" are not working, which applies to the embedded TIF and WMS layers too.

### Reproduction steps
1. Embed (e.g. PostGIS or WMS) Layer
2. within QField Cloud Sync set it to "Directly access data source"
3. export package with QField Sync
4. import to QField

### Expected behavior
Load and show features/rasters/layers.

### Observed behavior
Layer ist either missing completely (in list) or showing nothing (no raster/feature) on the canvas at all. Log messages indicate a reference to the other project file from which the layers are embedded from: `Error zip file does not exist: '<<relative path to _remote_ qgis project>>.qgz'`

### Screenshots and GIFs
-

### Desktop (please complete the following information)
 - OS: Windows 10 Pro 1909
 - QGIS Version 3.22.6
 - QFieldSync Version 4.1.1

### Mobile (please complete the following information)
 - Device: Dell Latitude 7220 Rugged Extreme Tablet
 - OS: Windows 10 Pro 21H2
 - QField version: 2.0.14

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Unknown
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@legnad , is this still an issue with the latest QFieldSync / QField versions?
