### ISSUE TITLE
Qfield creates extra objects on different layers

### ISSUE THREAD

**Issue by jfmoyen** [opengisch/QField#3005]
Apologize for not supplying a MRE right away - I'm in the field so it is a bit difficult to be comprehensive and to run proper tests. In the hope that maybe somebody has a clue, I'll try to describe the issue, and when back home latter I'll run some serious tests if this is not enough.

I have a project with several point layers  - localities, photos and samples. 
Photos, you would have guessed, contains photos taken from the device, using the camera widget. The photos are then stored in the DCIM folder.

The other two are just plain point layers.

Whenever I create a point on any of the three, I also get a point created on layer photo. Whether this layer is visible or not is irrelevant. The extra points are created without any attachment. So, 
- create a point on samples -> one sample AND one point on photo
- create a point on localities -> one locality AND one photo
- create a point on photo -> TWO points on photo, one with the attachment (assuming I took a picture of course) and one without.

As you can guess this is a rather annoying behaviour. It happened already on another project (with a similar structure) a month ago or so, but it disappeared when I restarted Qfield ... This time it is rather persistent.

Any hint (with this admittedly limited info, again further tests will have to wait until I'm back, or a rainy day perhaps...) ?

**Comment by jfmoyen** [comment]
PS- I tried to re-upload the project to the tablet, no luck. And whenever I open the project it always opens innavigation mode with the purple line pointing to wherever - if this may be of any help or related in anyway !

**Comment by jfmoyen** [comment]
[MassifCentral.zip](https://github.com/opengisch/QField/files/8969367/MassifCentral.zip)

That project, attached. I did not attach the basemape (from geopackage MCF_geo50k and tiff FRANCL2E), so QGIS will complain, but these are static layers, I don"t think they affect the issue.

**Comment by jfmoyen** [comment]
Reproduced today on Qfield windows (latest version) with the minimal project as uploaded last week (ie the qgs and the gpkg).

**Comment by itsakifa** [comment]
Hi @jfmoyen 

This is very much likely because you've set your Photos layer as the digitizing log layer in your QGIS project properties

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/4679915/220122931-8bd5e0df-6fcb-405b-bd29-5d9a6b96ff0e.png">

See here what the digitizing log layer is meant to be for : https://docs.qfield.org/how-to/gnss/?h=digitizing+log#vertex-log

Can you confirm that if you don't choose any point layer as digitizing log layer, you don't have the problem of double created points?

**Comment by jfmoyen** [comment]
@itsakifa That was it ! Thanks a lot ! Well spotted... I've been pulling my hair since last year...
