### ISSUE TITLE
"Renforced constraints" in qfield

### ISSUE THREAD

**Issue by RAFALCO** [opengisch/QField#301]
With "renforced constraints" in QGIS 3.2 it's possible to prohibit registration of an entity if a field is not filled.
With qfield the empty field is red but the registration is possible.
is it possible to really prohibit the validation of a entity in qfield if a field is empty?
Thanks a lot.

**Comment by m-kuhn** [comment]
No. So far this is not possible.

But it should not be too complicated to add support for this.

**Comment by saemiw** [comment]
I confirm this and add a comment:

There is a work around if you type in your constraint as a expression. An example with a attribute called "species": 

This does not work (is not taken over):
![grafik](https://user-images.githubusercontent.com/20398621/54590329-29af1c80-4a28-11e9-962c-e3ad356b1a81.png)

This works perfectly:
![grafik](https://user-images.githubusercontent.com/20398621/54590367-3e8bb000-4a28-11e9-9e24-7ec2907253c0.png)

**Comment by signedav** [comment]
This is implemented since 1.5
