### ISSUE TITLE
Self-compiled Windows executable doesn´t find proj.dll

### ISSUE THREAD

**Issue by cplasan** [opengisch/QField#3018]
Hello,
I'm trying to create a  QField executable, but after I run builds commands describe it in development guide, I had no errors, I executed generated QField.exe and I got a Windows modal message saying that proj.dll is not found.

![image](https://user-images.githubusercontent.com/108342205/176177214-b1a7fe32-3573-420f-bc16-f0362613bc0c.png)

What am I doing wrong?

Offtopic: Any advice to set up a development enviroment for a programmer with no idea of Qt / C++?

**Comment by m-kuhn** [comment]
Can you try `cmake --build build --config Release` instead?

**Comment by cplasan** [comment]
Thanks for your answer @m-kuhn
I have re-built project and run the command suggested, but now QField window shows a error message before close automatically:

![image](https://user-images.githubusercontent.com/108342205/177570696-55b8aba4-2ea9-4826-9342-9d8a976790e2.png)

It seems that now can't find declarative_positioning.dll :(

**Comment by m-kuhn** [comment]
You should be able to find this file somewhere in vcpkg_installed.. copy it yo the right location.
The build system is currently switched from dynamic to static, with no more dlls but it's not completely ready yet.
