### ISSUE TITLE
Print Composer

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#302]
Customer said:
> Can the QFiled support, QGIS multiple print compositions which are listed in Composer Manager? 
We need support for printing a warrant on the field.

![image003](https://user-images.githubusercontent.com/28384354/43058272-079f9932-8e47-11e8-8c6e-b5c9b9beb354.png)

**Comment by VxTedxV** [comment]
Interesting but even if I'm not a programmer, it seems complex (and probably expensive) as QField is not designed to be used as a composer.
Since you need a printer, it appears it would be easier if you take a computer on the field with QGis, don't you think ?

**Comment by signedav** [comment]
Thanks. Until now  it's just an input/idea of a customer. Comments like yours are very helpful and important for the evaluation of it.

As I understood it, it's not about using QField as composer (edit the layout on QField), but having the composed layouts in the project on QField. To have a possibility to print from there (with the current QField data).

**Comment by m-kuhn** [comment]
If it's only about *printing* and not about *layouting*, that seems like a fair request on first sight.

Question:

 * Is atlas printing (including selection of a feature to print) a requirement?

Technical precondition (to check on our end):

 * Does Qt for Android support printing?

**Comment by nimcnaan** [comment]
I think this request is reasonable and even required. We would appreciate any support for this kind of feature, with or without support of "Feature Selection".

**Comment by m-kuhn** [comment]
@signedav can this be closed?

**Comment by m-kuhn** [comment]
@nimcnaan if you would like to test this feature, please go to https://github.com/opengisch/QField/releases and download the latest release.
We will start rolling it out to devices soon, but feedback from testing will be appreciated anytime.
