### ISSUE TITLE
Field expression bug

### ISSUE THREAD

**Issue by olegzhelezn** [opengisch/QField#3020]
### Discussed in https://github.com/opengisch/QField/discussions/3019

<div type='discussions-op-text'>

<sup>Originally posted by **olegzhelezn** June 28, 2022</sup>
Greetings to the QField community! 

Writing here to report a potential bug and ask for advice.

I have a vector layer with some of the fields regulated by default expressions. Specifically, there is a set of points which need to be regularly updated, and i am trying to do it in such a way that the original point preserves the information about all updates.
For this, I have created two types of fields (=> columns in the attribute table):
- an original field with the current value
- a field that accumulates the values of the original field throughout the time.

For example:

I have a field called **_ch_date_** (checkup date), which is being transformed into a string and summarised in the **_ch_dates_** field, which has a default value of:
**_"ch_dates" +';' +  to_string( "ch_date")_**

This works perfectly in QGIS, with ch_dates containing all checkup dates in the form of delimited string.
However, in QField the cumulative data field gets updated twice, once when writing the attribute, and then second time when saving the updated feature. If the attribute is rewritten before saving the feature, than the date is added again, and again, and again... 

This is not very comfy, but it works in some way, though.
But when it comes to the same expression with string data, e.g.:
**_"ch_values" +';' +  "ch_value"_**
it does not work in QField whatsoever...

Could this be addressed in the future releases?
Or maybe, someone might recommend a way to solve this in an alternative way? E.g. creating nested tables somehow?...</div>

**Comment by nirvn** [comment]
@olegzhelezn , can you attach a small test project to show your issue?
