### ISSUE TITLE
Edit and add new points to a saved polyline

### ISSUE THREAD

**Issue by Naturtecnica** [opengisch/QField#303]
I'd like to add new points to a saved polyline, how can I do?
How can I active editing mode to polyline layer and to point layer in the same time?

**QField version:** 0.10.13

**Comment by m-kuhn** [comment]
This is not yet possible but on the roadmap for soon.
Keep an eye on this existing issue: https://github.com/opengisch/QField/issues/105

**Comment by Naturtecnica** [comment]
Thanx Matthias, hope to get this skill very soon.
QField's a great field app... with this skill it will be the best!
