### ISSUE TITLE
error creating feature...database disk image is malformed

### ISSUE THREAD

**Issue by Eisenbarth** [opengisch/QField#3034]
**### Describe the issue**
We're using predefined .gpkg files (individual attribute form) for collecting bird data with QField.
When editing a point layer and trying to create a feature, the point is not created and an error message is shown. 

"Commit errors: ERROR: 1 feature(s) not added. Provider errors: OGR error creating feature -2: failed to execute insert: database disk image is malformed"  

**### Reproduction steps**
1. Open QField.
2. Open a project.
3. Activate the edit mode of a point layer.
4. Try creating a point feature.

**### Expected behavior**
The point feature is created and visible in the map.

**### Observed behavior**
The point is not created neither in the feature list nor in the map as a visible point.

Complete error message:
"Commit errors: ERROR: 1 feature(s) not added. Provider errors: OGR error creating feature -3: failed to execute insert: database disk image is malformed
QField    Änderungen konnten nicht gespeichert werden, Rollback.
OGR      Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()
QField    Layer "BvK_T6" kann nicht mit dem neu erzeugten Feature -2 gespeichert werden. Grund: ERROR: 1 feature(s) not added.     
              Provider errors: OGR error creating feature -2: failed to execute insert : database disk image is malformed"

With every new attempt to create a feature, the error comes up again with an altered feature number (e.g. -2 -> -3).

**###What has been done so far to solve the issue**
- Tried to shut down the tablet (complete off, no restart) and turned it on again.
- Tried to reopen the project.
- Tried to reopen the app.

**### Desktop** 
 - OS: Windows 10
 - QGIS Version 3.22
 - QFieldSync Version -> not using sync

**### Mobile** 
 - Device: Samsung Galaxy Active Tab 2
 - OS: Android 9
 - QField version: Bumblebee 2.14

**### Additional information**
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: No, happened first time.
* Problem happens with all files and projects, not only some files or projects: not tested (Update soon)

**Comment by nirvn** [comment]
Please provide a test project

**Comment by Eisenbarth** [comment]
Due to holidays, there has been no way to provide a test project. I assume an invalid project upon creation, since other projects on the same device are working fine.
If it happens again, I will provide a project and try to reopen this issue.
