### ISSUE TITLE
App crash when on open the project or moving the layer (IOS)

### ISSUE THREAD

**Issue by aleko205** [opengisch/QField#3035]
Hi,
We have an application crash problem on every project in QField on IOS. We tested it on two different IOS (ios 15.5, QField 2.1.4).
The application works fine without the project (navigation in menu, settings, etc), but after opening any project (or during the open application), the application crashes when I try to zoom or move the layer.
The same project works fine on Android's QField.
Here is a log file from my IOS - [https://drive.google.com/file/d/17b74qyhxeYtO8HsrfKjhQgGHPEmncPfA/view?usp=sharing](https://drive.google.com/file/d/17b74qyhxeYtO8HsrfKjhQgGHPEmncPfA/view?usp=sharing)
What may be the reason for crashes on IOS? Does someone have the same problem?

**Comment by nirvn** [comment]
@aleko205 , a large number of improvements are being worked on for iOS, expect a much better experience in the next release.
