### ISSUE TITLE
Allow customization of CRS used to display coordinates in map canvas popup menu

### ISSUE THREAD

**Issue by olegzhelezn** [opengisch/QField#3044]
When creating a bookmark or generally doing a lookup in QField, a popup appears with coordinates and options to create a bookmark or set as destination. The coordinates are shown in the project CS. 
However, from my experience, projects are usually prepared using projected CS, such as various UTM WGS84 zones. So, the coordinates seen there are not very useful when it comes to orientation and interoperability between different devices. 

**So, I would like to suggest to implement a button in the Settings which would allow selection between project CS and decimal degrees in the lookup.**

![image](https://user-images.githubusercontent.com/39202056/177104943-a025d13a-1c65-4bb0-b995-44a553a1d750.png)

**Comment by nirvn** [comment]
@olegzhelezn , QField 2.2 is the answer to your request :) 

QField now respects this QGIS project setting:
![image](https://user-images.githubusercontent.com/1728657/179337898-acbb4379-6a72-41ae-b361-8e66ad587a60.png)

If you set it to geographic, you'll get WGS84 coordinates in the map canvas popup.

**Comment by olegzhelezn** [comment]
Very nice, many thanks!!
