### ISSUE TITLE
Path to QField export-folder not clickable

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QField#3047]
### Describe the issue
When for example exporting map canvas as an image, you may click on the link appearing in the message bar when the export is finished and the destination folder will be opened in File manager in Windows.
After exporting a project with QField Sync, apparently a link is displayed in the message bar, but when clicking on this link, nothing happens.

I may be wrong, but didn't this use to work in previous versions of QField Sync and/or QGIS?

### Reproduction steps
1. Export your QGIS-project with QField Sync.
2. Click on the link displayed in the Message bar when the project creation is finished.

### Expected behavior
When clicking on the link the destination folder should be opened in File manager.

### Observed behavior
Nothing happens when clicking on the link (besides the message bar being closed).

### Screenshots
Link works and File Manager opens:
![link_works_with_export](https://user-images.githubusercontent.com/10632163/177137977-95e3a956-01c7-47f3-b3d8-a34f6b46c664.png)
![filemanager_opens](https://user-images.githubusercontent.com/10632163/177138004-c33bfd2d-cf0b-48a7-9fad-5289a3463ef2.png)

Link doesn't work and no File Manager opens:
![nothing_happens](https://user-images.githubusercontent.com/10632163/177138025-e4c4bf99-5156-409b-bb38-f19daa0febe8.png)

### Desktop
 - OS: Windows 10
 - QGIS Version 3.26
 - QField Sync Version 4.1.1

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@9ls1 , thanks for reporting, a fix will be in qfieldsync's next version.
