### ISSUE TITLE
0700 permissions error during applying the changes

### ISSUE THREAD

**Issue by aleko205** [opengisch/QField#3060]
Hi,
Hope this is the right place to post a problem regarding the qfield.cloud.
During applying the changes on [qfield.cloud](https://qfield.cloud) I have a permanent error with this message:
```
> Apply Deltas
INFO:QGIS_STDERR:Starting QGIS app version 32402 (exported)...
WARNING:QGIS_STDERR:QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/0', please create it with 0700 permissions.
```
I have tested a few projects, and they all have the same problem.
Is it a bug? or how can I solve it?

**Comment by suricactus** [comment]
It is a warning that is not crucial to QFieldCloud operations. It will disappear in very near future.

**Comment by aleko205** [comment]
Thank you for your answer @suricactus.
It's fine, but I asked because I thought it would be connected to my problem in my projects where it is impossible to apply changes that are pushed from the qfield app.
Please see screenshot - [https://prnt.sc/CG8VIg48gyjY](https://prnt.sc/CG8VIg48gyjY)
How can I identify why I have such errors? It does not matter if I add, move or delete the feature; I always get this error after pushing the changes from the qfield :/ 

I appreciate your help!

**Comment by suricactus** [comment]
Seems you are using a shapefile. Please switch to GeoPackage or:

> If you use experimental data sources without a primary key field (e.g. Shapefiles, GeoJSON etc), you must have a lowercase `fid` field that will be used as a primary key that uniquely identifies each feature.

**Comment by aleko205** [comment]
@suricactus, oh, my bad! It was without a primary key field!
You saved my time.
Thanks a lot.
