### ISSUE TITLE
Unable to push data after network error

### ISSUE THREAD

**Issue by ign1s-fatuus** [opengisch/QField#3070]
### Describe the issue
When attempting to push changes to Qfield Cloud from my phone I will often get a network error (both using a wireless network and cel data). When this happens no data is pushed to the cloud and I am given a message that there is no new data to push. One is not given another chance to push the data as it thinks everything has synced. 

### Reproduction steps
1. Add or edit data
2. Press push changes button
  2a. In event of network error no data will be pushed
3. App will say all data is up to date even though no data was pushed to the cloud 
### Expected behavior
data collected/edited via the Qfield should be pushed correctly to the cloud. In the event of an error, one should be given multiple chances to push the data.

### Observed behavior
data is not pushed in the event of an error and the app does not give further chances to push said data.

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Arch Linux
 - QGIS Version 3.36.0
 - QFieldSync Version 4.1.1

### Mobile (please complete the following information)
 - Device: Galaxy S20
 - OS: Andriod 12
 - QField version: 2.2.0

**Comment by RTcarlos** [comment]
My application is not updating, I register the information in the field, but when I open it in QGis I do not receive the information. I see that in QField Cloud it is receiving, but not updating. keeps asking to apply the seedlings, but he doesn't accept. Can someone help me ?

**Comment by m-kuhn** [comment]
Is this still an issue?
