### ISSUE TITLE
Enhancement - add expression variable to record Orientation

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3072]
Hello, 

When I'm geotagging information using a point layer, I'm saving the information about GPS orientation, using this expression: 
`@position_direction`

If I'm moving, the GPS will save the direction of the phone (the expression is quite right), but it will not save the orientation. 
In the situation where I'm in a moving vehicle and try to save the orientation of a photo, the photo is always oriented toward the direction of the vehicle. 

Is there a way to save the orientation, like on the picture below ? 

![direction_orientation](https://user-images.githubusercontent.com/72577399/178996863-b7a750f0-4790-4a01-bb12-705f8de34b20.jpg)

### Desktop (please complete the following information)
 - OS: [eWindows 10]
 - QGIS Version [3.26.0]
 - QFieldSync Version [4.1.1]

### Mobile (please complete the following information)
 - Device: [Samsung Galaxy S9]
 - OS: [Android 11]
 - QField version: [master-dev (7e3543)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Thank you

**Comment by m-kuhn** [comment]
In short, this is a request for adding a `@position_orientation` variable?

**Comment by Ipickedausername** [comment]
Hello, 

If nothing similar exists to record the orientation, this is a request for adding a @position_orientation variable.

**Comment by nirvn** [comment]
This is implemented since QField 3.1 (i.e. https://github.com/opengisch/QField/blob/master/src/core/utils/expressioncontextutils.cpp#L64).
