### ISSUE TITLE
Error - Canvas never follow location

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3073]
Hello, 

Unless I'm mistaken, when I click on the button location : 

![location](https://user-images.githubusercontent.com/72577399/178998055-df1ad60a-fe9b-4554-a70c-5798b1e9c299.jpg)

QField displays this message: "Canvas follows location"

But the canvas never follows the location. 

### Expected behavior
I suppose the GPS should stay in the middle of the map while the map is moving around the GPS location. 

### Observed behavior
The GPS can be outside the canvas ; we can move outside the view on the phone. 

Desktop (please complete the following information)

    OS: [eWindows 10]
    QGIS Version [3.26.0]
    QFieldSync Version [4.1.1]

Mobile (please complete the following information)

    Device: [Samsung Galaxy S9]
    OS: [Android 11]
    QField version: [master-dev (7e3543)]

Additional information

    Problem started happening recently, didn't happen in an older version of QField: [No]
    Problem can be reliably reproduced, doesn't happen randomly: [Yes]
    Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@Ipickedausername , if your positioning button does not have a blue background, it means you are out of canvas-follow-position mode. To activate it, press on the positioning button, which will turn blue. If you move the canvas manually, that'll switch the mode off.

E.g.:
![Peek 2022-07-16 10-31](https://user-images.githubusercontent.com/1728657/179337561-3b3e7877-7684-4acc-a5ff-20fd4bb75f29.gif)

**Comment by Ipickedausername** [comment]
Hi, 

Thank you for the information.

I was alway moving the canvas during the tests, I didn't understand the canvas was stoping following the gps at this moment (which is logical...).

I close this issue !
