### ISSUE TITLE
cannot enter a "space" in QText field

### ISSUE THREAD

**Issue by herrsei123** [opengisch/QField#3099]
### Describe the issue
On my project, when i want to add a new point to my shape i have a column named "name" QString and masked in form-editor as default textfield with default settings. When i type, i can't enter any space letter directly. when i set the cursor manually, it is possible.

### Reproduction steps
1. go in edit mode
2. select layer "falter"
3. add a new point
4. fill in the column "name" and press space. it doesn't work on my device.

### Expected behavior
i can enter a space letter

### Observed behavior
space letter is ignored when pressed

### Screenshots and GIFs
the project is attached.

[project_sample.zip](https://github.com/opengisch/QField/files/9170002/project_sample.zip)

### Mobile (please complete the following information)
 - Device: Samsung S7
 - OS: Android Lineage 17.1 without google but with MicroG
 - QField version: 2.2.0

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: YES
* Problem happens with all files and projects, not only some files or projects: NO. It doesn't happen, when i use the textfield "beekeeper" in the sample app. But it happens on different layers an column names in the same project.

**Comment by nirvn** [comment]
@herrsei123 , this sounds like a virtual keyboard problem possibly out of our control. Have you tried a different virtual keyboard (e.g., if you are using the Samsung keyboard, try Google's Gboard keyboard).

**Comment by herrsei123** [comment]
Hey and thank your for your answer. I'm currently a lot in the "field", so hardly time for being on time on computer :-)
For the bug i descriped, changing the keyboard (tried different ones) did not bring any changes to the problem. Could it be related, that i'm not using any Google Play Services on my phone?
I did a workaround and use another device (with Lineage 14.1 and Google Play Services) which also "solved" another problem which i descriped in another thread. In autumn i will update to another LineageOS version.
