### ISSUE TITLE
values in attribute tables from predefined lists

### ISSUE THREAD

**Issue by ceeu01** [opengisch/QField#31]
created point layer with three 4 attributes. Values of two attributes can be chosen from predefined lists (Wertabbildung). One of type INTEGER, one of type TEXT. Values of the other two attributes must be entered manually (cannot be selected from predefined lists). 

When digitizing data values entered manually are saved without problem. Default values from predefined lists will not be saved but must be manipulated before they can be saved.

See example in file attached
[AttrTable.docx](https://github.com/opengisch/QField/files/211358/AttrTable.docx)

**Comment by m-kuhn** [comment]
To be sure: When a new attribute is digitized, attributes with a Value Map (German: Wertabbildung)  widget need to be modified. If left in default state they are saved as empty/NULL value. Correct?

**Comment by ceeu01** [comment]
Yes, that is correct

Von: Matthias Kuhn [mailto:notifications@github.com]
Gesendet: Montag, 11. April 2016 17:04
An: opengisch/QField
Cc: Homberger Benjamin
Betreff: Re: [opengisch/QField] values in attribute tables from predefined lists (#31)


To be sure: When a new attribute is digitized, attributes with a Value Map (German: Wertabbildung) widget need to be modified. If left in default state they are saved as empty/NULL value. Correct?
