### ISSUE TITLE
android application is shut down / restarts when switching apps

### ISSUE THREAD

**Issue by herrsei123** [opengisch/QField#3100]
### Describe the issue
qfield restarts when mobile is idle for some time and when i was using another app inbetween.

### Reproduction steps
1. using the application
2. using another application than qfield
3. deactivate display
4. reactivate display
5. unlock screen
6. switching to qfield
7. qfield restarts. i have to select the project again. i have to go in edit mode again. i have to select layer again.

### Expected behavior
the state of qfield is preserved and i can work continousely.

### Observed behavior
qfield restarts from beginning. i deakticated the power settings so that it is allowed to work in background, but it doesnt change anything.

### Screenshots and GIFs
not possible

### Mobile (please complete the following information)
 - Device: Samsung S7
 - OS: Android Lineage 17.1 without google but with MicroG
 - QField version: 2.2.0

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: UNSURE
* Problem can be reliably reproduced, doesn't happen randomly: YES
* Problem happens with all files and projects, not only some files or projects: YES

----
otherwise: great project! very happy to see whats evolving out of it!

**Comment by nirvn** [comment]
@herrsei123 , looking at your phone brand (S7 released in 2016), my educated guess is that your device is running out of memory, leading Android to forcefully close background apps. That's something that is unfortunately out of our control, and I can't see a way around it other than upgrading your device to a newer model with more memory (which is the last thing you probably want to hear :) ).

There are ways that this OS-forced restart could be less painful. E.g., QField could remember its view / edit state across sessions, and possibly remember the last selected layer for a given project. Then you'd be left with only re-opening the project, but everything else would be restored as you left it prior to locking your phone.

**Comment by VxTedxV** [comment]
Same problem here and I think @nirvn is right because my phone is full.
Also, the longer the phone stays in deactivated screen state the more it occurs.
Model : Samsung Galaxy XCover4 16Go (>15Go filled), Android 9

**Comment by nirvn** [comment]
Closing as this is not an issue on our end but rather a limitation of the OS/hardware.
