### ISSUE TITLE
Cmake cannot find toolchain file

### ISSUE THREAD

**Issue by KianL1** [opengisch/QField#3116]
### Describe the issue
I'm playing around with the QField open source and I'm having trouble trying to actually build, compile and then package.
Its taken my a couple of days to get all of the tools I need correctly installed within visual studio.

When I open any file within the source I get this message:

``
C++ IntelliSense information may be out of date, generate the CMake cache to refresh
``
then when I generate the CMake cache, I get this error:

```
Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:130 (message):
  Could not find toolchain file:
  C:/Users/KianLeggett/Documents/Creoplan-QFIELD/QField-master/vcpkg/base/scripts/buildsystems/vcpkg.cmake		C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake
```

I've not seen this posted before, and I'm really not sure where to go from here. Have I not installed something properly or do I need to hardcode the file path of the toolchain file

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/109590778/181018780-d1b9c0c3-6107-4adf-a01b-bc54c1299eae.png)
![image](https://user-images.githubusercontent.com/109590778/181018825-b0e8b112-25d5-4dd5-b450-d2148a6714f9.png)

### Desktop
 - OS: Windows
 - QGIS Version 3.22
 - QFieldSync Version latest

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by m-kuhn** [comment]
I don't normally use visual studio for development, so I cannot talk from a lot of experience.
Some hints though:

 - Make sure you get git submodules `git submodule update --init --recursive`, that will very likely solve the toolchain problem
 - The cmake command comes from https://github.com/opengisch/QField/blob/master/.github/workflows/desktop.yml, pay attention to `-DVCPKG_TARGET_TRIPLET=x64-windows-static` and `-DCMAKE_MSVC_RUNTIME_LIBRARY` and `-DPKG_CONFIG_EXECUTABLE`.
 - Windows support is experimental, it will probably need some investment to get it up and running properly

**Comment by m-kuhn** [comment]
@KianL1 did the above suggestions help to solve the problem?

**Comment by KianL1** [comment]
first solution worked yes thankyou
