### ISSUE TITLE
QField slowed when using the option "Fast editing mode"

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3126]
Hello, 

For your information, QField is slowed when we use the option : "Fast editing mode". 
I had a hard time working on my project, my phone is still quite good and fast.

In my situation, I'm not using this option, but maybe there is something wrong ? 

Without the option:
https://user-images.githubusercontent.com/72577399/181278978-3c3e9fdc-5e5d-4aaf-b2e4-a2977a38c4d7.mp4

With the option: 
https://user-images.githubusercontent.com/72577399/181279058-23730e91-d268-4bbb-b5b7-3bcca90f4b19.mp4

Mobile
    Device: [Samsung Galaxy S9]
    OS: [Android 11]
    QField version: [master-dev (c77752)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No] (same situation on QField 2.2.1)
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

Thank you

**Comment by nirvn** [comment]
This is to be expected when using complex attribute forms. "Fast editing mode" is misleading and should probably be renamed "Constant saving mode" :) When enabled, every time an attribute value is edited, the whole feature is saved and the attribute form refreshed. The more complex the attribute form, the longer it takes to do that refresh.

**Comment by Ipickedausername** [comment]
Thank you for the information. 

Nothing wrong here. I close the issue.
