### ISSUE TITLE
Issue checkboxes contents not well displayed / crash the application

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3127]
Hello, 

Since one of the last updates, I noticed an issue with the checkboxes we use to select entities in the feature list. 

When several entities are selected, some errors occurs, or bad display. 
- After the action, "moving", the entities aren't visually ticked anymore, but they are. 
- After the action delete, if 2 entities are selected, only one is deleted. No more actions are proposed in the (except toggle feature selection) ; which means Qfield consider nothing is selected (the remaining entity is still existing and still ticked) 
- Duplicate crash the application

It was working well before one of the lasts updates. 

Here is a video of the error with the action "moving". 

https://user-images.githubusercontent.com/72577399/181289049-6afe1d58-c1e5-49b9-99c8-0ab193617c9c.mp4

Desktop

OS: [Windows 10] 
QGIS Version [3.26.0]
QFieldSync Version [4.1.1]

Mobile

Device: [Samsung Galaxy S9]
OS: [Android 11]
QField version: [master-dev (c77752)]

Additional information

    Problem started happening recently, didn't happen in an older version of QField: [Yes]
    Problem can be reliably reproduced, doesn't happen randomly: [Yes]
    Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@Ipickedausername , I cannot replicate locally. You might need to provide a test project or at least a test dataset which can replicate this issue.
