### ISSUE TITLE
OGR error: Coordinates with non-finite values are not allowed on QGIS after on edited geometries (+ display error on QField)

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3128]
Hello, 

On QField, when after adding a polygon geometry, if the geometry is modified, when saving, a part of it isn't displayed (video after). 

The geometry still exist (we can see the shape when selecting it), it is just partially visible. To make it appear totally, the whole geometry has to be changed (every vertex). 

But the worse part is on QGIS. When this geometry is synchronized, it's not possible to work with it. Every modification or copy-paste brings this error : Coordinates with non-finite values are not allowed on QGIS

![error_OGR](https://user-images.githubusercontent.com/72577399/181424894-d467faef-ba71-4b4e-ae28-9aed88eb72f4.jpg)

When we check on the vertex editor, there is no coordinate error. 
![vertex_editor](https://user-images.githubusercontent.com/72577399/181425087-c4aea2bb-d1ba-4f7c-a30c-adb63e82a4e1.jpg)

### Expected behavior
This error isn't recent, I saw it in many previous versions. 

https://user-images.githubusercontent.com/72577399/181425126-800c65d3-38da-4da5-92a5-33ee69dc9021.mp4

Desktop
OS: [Windows 10]
QGIS Version [3.26.0]
QFieldSync Version [4.1.1]

Mobile

Device: [Samsung Galaxy S9]
OS: [Android 11]
QField version: [master-dev (c77752)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Thank you

**Comment by m-kuhn** [comment]
Related to https://github.com/qgis/QGIS/pull/47034

**Comment by Ipickedausername** [comment]
Is this issue related to the Z dimension ?
I'll change the geometry and check the differences. 

Thanks
