### ISSUE TITLE
Check default values when adding a new entity when fields are repeated

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3132]
Hello, 

The checkbox which is used to repeat fields when adding entities is very useful !
But, in the situation where the repeated field is used to calculate another one, it doesn't work. 

Would it be possible to allow QField to check the constraints before repeating the value in the field ? 

In my case, if I repeat "COMPART", the field ID is supposed to be updated (it integrates the information present in the field "COMPART"). And when I repeat the value in "Code_esp", I'm expecting the field "Exact number" to update (but it remains NULL). 

Here is a video, I hope it is clear.
https://user-images.githubusercontent.com/72577399/181574336-e4ad7c52-ea7a-4652-81d5-cfafd86310c4.mp4

### Expected behavior
Repeat execute automatically the update expression on the fields which depends on the repeated one. 

Desktop
OS: [Windows 10]
QGIS Version [3.26.0]
QFieldSync Version [4.1.1]

Mobile
Device: [Samsung Galaxy S9]
OS: [Android 11]
QField version: [master-dev (c77752)]

Additional information

Problem started happening recently, didn't happen in an older version of QField: [Yes]
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
Problem happens with all files and projects, not only some files or projects: [Yes]

Thank you

**Comment by nirvn** [comment]
@Ipickedausername , is this fixed in recent QField versions?

**Comment by Ipickedausername** [comment]
I’ve adjusted the way my project operates to prevent these kinds of issues. While I can't be certain, I haven't encountered similar problems recently. I close this issue!
