### ISSUE TITLE
URL not displaying correctly in last version (Display as html code and not as clickable link)

### ISSUE THREAD

**Issue by Kinad** [opengisch/QField#3135]
Hello

I recently update my QField app from play store, and in the last version, seems there is a different behaviour interpreting url/hyperlinks text.

In my project, I have two QEdit field in my forms, wich are not editable, where i put two different url (a GMaps Link and a Waze link). I just write for example : _http://www._ ,with no html formatting in this field.
In the previous version, the fields where clickable, perfect behaviour. 
But in the new version, QField displays the html code (as you can see in attachments) and not the clickable link .

Is it normal ?

Could you fix it in the next update ?

Thank a lot to all devs for all your work !!! 

Desktop
OS: [Windows 10]
QGIS Version [3.22.9]
QFieldSync Version [4.1.1]

Mobile
Device: [Samsung Galaxy A10]
OS: [Android 9]
QField version: [2.2.1 Capybara (137bc3 v2.2.1)]
Same on all devices i tested (Android 9 -10)

Additional information

Problem started happening recently, didn't happen in an older version of QField: [Yes]
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
Problem happens with all files and projects, not only some files or projects: [Yes]
![Screenshot_20220729-114711](https://user-images.githubusercontent.com/17593677/181736346-6d01fa35-163c-4f07-a09f-f5c17cc7ef1e.jpg)

**Comment by nirvn** [comment]
@Kinad , can you attach a sample project, or if not possibly at least a screenshot of one broken hyperlink's attribute configuration panel in QGIS?

**Comment by nirvn** [comment]
@Kinad , actually it'll likely not be needed -- the APKs here will likely fix your issue: https://github.com/opengisch/QField/pull/3137
