### ISSUE TITLE
Error when trying to build from docker image

### ISSUE THREAD

**Issue by KianL1** [opengisch/QField#3141]
### Describe the issue
I've been trying to make a custom build from a forked source which has no changes just yet via docker image but I'm encountering an error. My linux terminal cannot find build.sh even though its in the directory. Any other guidance on building would be really appreciated as I'm working in the dark here aha. tyty

### Reproduction steps
1. Open docker desktop, create new dev environment from source
2. Start Dev Environment
3. Open Container in VSCode
4. Open Ubuntu
5. sudo su
6. log into docker
7. pull the image
8. clone git branch 
9. change directory
10. submodule init + update
11. "triplet=arm-android ./scripts/build
### Expected behavior

build to start

### Observed behavior

"bash: .scripts/build.sh: No such file or directory"

### Pictures

![image](https://user-images.githubusercontent.com/109590778/181779736-2f7090de-7c99-412e-be65-733432f1648f.png)

### Desktop (please complete the following information)
 - OS: Windows 11

**Comment by m-kuhn** [comment]
Is selinux turned on?

**Comment by KianL1** [comment]
No, forgot to close this issue. Fixed via restarting my linux machine
