### ISSUE TITLE
Qfield 2.2.2. on IOS Hyperlinks not working anymore

### ISSUE THREAD

**Issue by PeterDrexel** [opengisch/QField#3153]
QField 2.2.2 - 81e273 (IOS): Hyperlinks in Attributes are not shown as Links anymore and are not working (see Screenshot). 
The same Project works fine when I use build 2.2.0 (from Testflight).

![qfield_link_not_working](https://user-images.githubusercontent.com/40065134/182108782-e498aa72-7338-4826-b93a-1aa219b31019.JPG)

iPhone SE2020 (and also on my 2018 Ipad)
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by nirvn** [comment]
@PeterDrexel , fixed, a new 2.2.3 should be released in the coming days.
