### ISSUE TITLE
Freeze and dropdown list transparent

### ISSUE THREAD

**Issue by Growth64** [opengisch/QField#3168]
Hi,

Qfield 2.2.3
Samsung Galaxy Tab Active 2 (Android 9)
QGIS 3.16.7

I updated my qfield and now I have a lot of freezing when I create item. I make dropdown lists and some time it is transparent or do not appear at all. Editing an existant item  could freaze (most of the time).
Editing an item could freeze and same.

Same project works well on my phone: Samsung Galaxy A8 (Qfiled 2.2.0)

**Comment by aghiraldi** [comment]
These problems also appear on my device : 
 - Samsung Galaxy Tab Active 2 (Android 9)

... but not on these devices :
- Fairphone 3 (Android 11)
- Samsung Galaxy Tab Active 3 (Android 12)

**Comment by nirvn** [comment]
Providing a test projet would help a lot here, I personally can't reproduce.

**Comment by aghiraldi** [comment]
[project_freeze_bug.zip](https://github.com/opengisch/QField/files/9289165/project_freeze_bug.zip)

To reproduce the bug:
1) Open the project in the attached zip file in Qfield
2) Click on a station (pink square)
3) Open the form of the entity
4) Start the attribute edition mode
5) Add a child (+)
6) Click on the drop-down list => the form freezes or the list appears transparent

**Comment by Growth64** [comment]
screenshot
<a href="https://ibb.co/8D3Hpbp"><img src="https://i.ibb.co/8D3Hpbp/20220809-120422.jpg" alt="20220809-120422" border="0"></a>

**Comment by nirvn** [comment]
@aghiraldi , the num_catalogue drop down list?

**Comment by nirvn** [comment]
@aghiraldi , also, which version of QField are you running?

**Comment by aghiraldi** [comment]
@aghiraldi , the num_catalogue drop down list? 
- The list 'num_catalogue', when it "works", looks transparents (both backgroupd and texts) => After you cliqu to drop-down, if you click someware on the screen, it picks an element of the list.
- On the list 'mode_identification', the background is transparent but y ca see the texts by superposition.

@aghiraldi , also, which version of QField are you running? Qfield v2.2.3

**Comment by Growth64** [comment]
It works well on my Qfiled 2.2.0 (on phone Samsung Galaxy A8)

**Comment by Growth64** [comment]
I'm on Qfield 2.2.1 and it doesnt freeze anymore but dropdown could be transparent again.

**Comment by aghiraldi** [comment]
New test with Qfield version 2.3.2 :

The project with large dropdown list uploaded above shows that the problem still affects the "old" Samsung Tab Active 2 (Android 9).

On my more recent tested devices (Fairephone 3 with Android 11 and Samsung Galaxy Tab Active 3 with Android 12) the project works fine.

**Comment by aghiraldi** [comment]
The problem persists with Qfield version 2.3.4

**Comment by nirvn** [comment]
The freeze issue here has been fixed. As for the other issue - transparent menu background - let's consolidate things in the following issue https://github.com/opengisch/QField/issues/3309.
