### ISSUE TITLE
Qfield Cloud problem

### ISSUE THREAD

**Issue by uapmq** [opengisch/QField#3171]
### Describe the issue
I can connect to the cloud (with multiples account, doing the same thing) but the projets doesn't appear (even after refreshing) and this error message appears on QGIS:

![image](https://user-images.githubusercontent.com/106489233/183118277-06a41333-cdd2-40f2-924b-f0326da8b709.png)

![image](https://user-images.githubusercontent.com/106489233/183118384-bfc0969d-7992-412a-bc4f-ab4c66228a03.png)

### Reproduction steps
1. Open 'QGIS'
2. Click on 'Qfield project list' (the blue cloud)
3. Connect to an account with already available projects
4. Projects don't show and the error message appears after refreshing.

### Expected behavior
The projects to show normally.

### Observed behavior
The projects don't show.

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version [e.g. 3.24.0-Tisler
 - QFieldSync Version 4.1.1

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]
User name: PatrouilleBleue/mia-uapmq
projects example: stlaurent_ce/Ahuntsic-Cartierville

**Comment by RobertM2323** [comment]
I am having this issue as well...hopefully we can get a fix soon.

**Comment by SavannahEB** [comment]
Also having this issue at my company in field... shame we were going to pilot this with our exploration field work this year starting tomorrow.

**Comment by suricactus** [comment]
Is this still the case?

**Comment by uapmq** [comment]
For me, everything is fine now!

**Comment by pallaviprakashjha20** [comment]
Sign in failed: [QT-3] Host app.qfield.cloud not found 
 
I am getting this message everytime i try log in. My username and password is correct. please help
