### ISSUE TITLE
Error uploading changes

### ISSUE THREAD

**Issue by Fertuesta25** [opengisch/QField#3172]
### Describe the issue
When trying to upload changes, a server error 500 internal server error appears.

### Reproduction steps
1. [Go to '...']
2. [Click on '...']
3. [Scroll down to '...']

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.26.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - OS: [e.g. Android 11]
 - QField version: 2.2.3 - Coordinated Capybara [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by SavannahEB** [comment]
I believe this is the same issue as #3171 , experiencing the same error when I attempt to sync projects as well.

**Comment by suricactus** [comment]
@SavannahEB is this still the case? Username and project name would be really helpful.

**Comment by SavannahEB** [comment]
Hi @suricactus, yes: 
username: savannah or jarod-kobold
project: Kobold_Metals / CSB_Prospection_2022
Happening on: android galaxy tab A8 tablet

**Comment by m-kuhn** [comment]
Is this still an issue?
