### ISSUE TITLE
Points collected on Qfield and sync to cloud disappear

### ISSUE THREAD

**Issue by Alekssssanderr** [opengisch/QField#3175]
### Describe the issue
Points collected on Qfield and sync to cloud disappear in Qfield but on QGIS this changes are visible and saved

### Reproduction steps
1. Open project in Qfield with point layer
2. Collect some points
3. Sync project

### Expected behavior
Changes pushed to cloud still visible on map on Qfield

### Observed behavior
Changes pushed to cloud disappear on Qfield but on QGIS they are visible

### Screenshots and GIFs
(https://user-images.githubusercontent.com/110682360/183287830-c678ae89-8d27-4a53-b237-d2e08c4d55f9.png)

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.22.9
 - QFieldSync Version 4.1.1

### Mobile (please complete the following information)
 - Device: Realme 7
 - OS: Android 11
 - QField version: 2.2.1 137bc33

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects Yes

user: Alekssssander
project ex.: Piotr_Hladyszewski_082022

**Comment by suricactus** [comment]
Hey, @Alekssssanderr . I have checked a project with slightly different name (Piotr_Hladyszewski_072022) and there are two point created that seem to be available in your project. Can you try again adding a few more features?

**Comment by robinjonesuk** [comment]
I think I've previously had the same problem. I think that a newly pushed record got corrupted (although not affecting qgis) and prevented the layer from displaying. 
Filtering out all the recently pushed records displayed the points again (old records). Gradually including the new records eventually brought the problem back, identifying the suspect record.

Filtering out just the suspect record and syncing qfield resulted in the other points being displayed. 
When I duplicated the record and deleted the original then all the points displayed too.

I have no idea why qgis showed the layer perfectly and qfield had this problem.
