### ISSUE TITLE
QFieldCloud - process QGIS project file : Connection to database failed timeout expired

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/QField#3176]
### Describe the issue
The QGIS project file could not be loaded successfully. 

### Reproduction steps
1. Create a new QFieldCloud project (using QFieldSync) from an existing QGS project file
2. Define the SECRETS for the new project on app.qfield.cloud (service_name, database name, database user and password, database host, port). Note : I used the same parameters that I used for some previous project files.
3. Check the job status on app.qfield.cloud (I takes 10 minutes before I get project status=failed)
![image](https://user-images.githubusercontent.com/72449015/183383814-5800319e-0107-4061-a15c-3819681dce6f.png)

 I get the following job error 
Download Project Directory
INFO:root:Downloading file "projects/3e6770f4-b869-428a-8c39-e6b8c9c90ec6/files/arb_qfcloud_xxx.qgs", size: 553015 bytes, md5sum: "b5968972f0841c7885cc6a9c75c3be7d" 
Project Validity Check
INFO:root:Check QGIS project file validity...
Opening Check
INFO:root:Open QGIS project file...
INFO:QGIS_STDERR:Starting QGIS app version 32402 (exported)...
WARNING:QGIS_STDERR:QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/0', please create it with 0700 permissions.
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
WARNING:QGIS_MSGLOG:Connection to database failed
timeout expired
Timeout error! The job failed to finish within 600 seconds!

### Expected behavior
project file loaded succesfully

### Observed behavior
process QGIS project file : job status=failed (see above log)

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.22.4
 - QFieldSync Version 4.1.1

### Mobile (please complete the following information)
 - Device: Galaxy Tab Pro
 - OS:  Android 11
 - QField version: 2.2.3 (772d14)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] No
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No] Yes

[If the problem happened with QFieldCloud, please add your username and project name.]
username = morges_admin, project name=EspacesVerts_XXX

**Comment by suricactus** [comment]
@jpdupuy it seems there is no problem on the QFieldCloud side. 

However, having your job timeout is a symptom of wrong port configuration. In that case, QGIS will retry to connect indefinitely.

Something that you can make sure of is that you delete the current pgservice configuration and recreate it from scratch with double checking you input.

**Comment by jpdupuy** [comment]
Thank you, I missed one digit for the port number. It now works fine
