### ISSUE TITLE
Only select visible features in categorized or rule-based layers

### ISSUE THREAD

**Issue by monticola2** [opengisch/QField#3182]
### Describe the issue

I have a layer with categorized symbology, in my case on the column "species". If I deactivate the view of all but one species in the layer tree and try to select one point in the map, all the invisible points in the background close to the visible one get selected too. This is especially cumbersome if there are many invisible features because it's hard to find the one you actually wanted to select in the selection list.
Also, this is a case where QGIS and QField differ. In QGIS (3.26) standard behaviour is that you can only select (or identify) visible features in a categorized layer.

### Reproduction steps
1. Create a layer with categorized symbology with points of different categories lying close together
2. Hide all categories except one
3. Select a visible point

### Expected behavior
Only the visible point(s) of this layer get selected and show up in the selection view

### Observed behavior
All invisible points of other categories of this layer are selected and shown in the selection overview, too.

### Screenshots and GIFs

https://user-images.githubusercontent.com/64013745/183858296-4e94f6a0-3900-435b-906e-64197240a82e.mp4

Only "B" was activated in the layer tree, the other species are supposed to be invisible and I'd prefer them to be not selectable then.

### Desktop (please complete the following information)
 - OS: Windows 8.1
 - QGIS Version 3.26
 - QFieldSync Version 4.1.1

### Mobile (please complete the following information)
 - Device: Xiaomi Mi 10 Lite 5G
 - OS: Android 11
 - QField version: 2.2.3 (772d14)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No (?)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
This felt more like a bug to me than an enhancement :) 

@monticola2 , good news, this shortcoming has been fixed, you can try the APKs here (https://github.com/opengisch/QField/pull/3262) and give us some feedback. Happy field mapping!
