### ISSUE TITLE
my projects disappeared from Qfield cloud  

### ISSUE THREAD

**Issue by juwizeye** [opengisch/QField#3183]
### Describe the issue
I have been using Qfield and Qfield cloud for a while now. unfortunatly,  today I noticed that some of my projects are no longer  present in Qfield cloud. I don't understand because i didn't delete them. is there any limited number of projects that can be in Qfield cloud.
my username is joyeuse
I lost all my recents projets.

**Comment by suricactus** [comment]
Please follow the updates on this thread. TL;DR Your projects are safe and will appear again shortly.

**Comment by juwizeye** [comment]
ok cool. thanks!
