### ISSUE TITLE
Some default values are not calculated

### ISSUE THREAD

**Issue by koenigherford** [opengisch/QField#3187]
I you digitize a line in line-layer "Haupt..." in attached sample-project in QGIS some default values are calculated based on a underlying polygon-layer "alle..." (see example). 
(The spatial query is done only once and the value is stored in field "polygon_info". This data is used in other fields to calculate default values (to save time of spatial queries) for example by the code `to_int(coalesce(array_get( string_to_array(
"polygon_info" ,',') ,0),0))`

If you open the offline-project in QGIS, the calculation of these values works well, but in QField the values are not calculated.

![grafik](https://user-images.githubusercontent.com/28433436/172799396-76e55329-50a1-43e7-aed7-8d2183e3285f.png)

[offl_test.zip](https://github.com/opengisch/qfieldsync/files/8868500/offl_test.zip)

**Comment by nirvn** [comment]
@koenigherford , are things working under QField 3.2.0? Tons of work done with regards to default value since the time you filed this.

**Comment by koenigherford** [comment]
@nirvn, thanks for reminding me of that. The topic was out of my focus because you solved it in between. I forgot to close the issue. Excuse me.
