### ISSUE TITLE
Edited date is visible on all other objects

### ISSUE THREAD

**Issue by geoplanteam** [opengisch/QField#319]
Dear all

Once a date field has been edited, it will be displayed on all other objects, even if the date for these objects is not saved.
It sounds a bit confusing, but I'll try to explain it below.

### Reproduction Steps:

I have a tree layer with a felling-date attribute. By editing this attribute, for example tree number 100 has now felling-date 2018-08-14, the same date is shown for all other trees as well.

Only by closeing and reopening the application, the felling-date for the other trees is reset to their initial state again.

### Expected behavior:

The modification of the date of one attribute mustn't be displayed for all the other objects as well.

### Observed behavior:

The felling-date wasn't set for all trees, just for tree number 100. Therefore it must be a display problem I guess.

**QField version:** [0.10.13]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]
I tried several projects and different data sources (shape, gepackage, sqlite).

Regards and thanks
Christoph

**Comment by m-kuhn** [comment]
> The felling-date wasn't set for all trees, just for tree number 100. Therefore it must be a display problem I guess.

Does that mean, the felling-date for all other trees is still NULL?
Is it the same, if the felling-date for another tree is also set (to a different date), is also the wrong date shown?

**Comment by geoplanteam** [comment]
What I mean is, that there is noch global update of the felling-date for all trees. In the database (geopackage) the update is correctly on tree number 100. All the other trees still have their felling-date as before.
But when ich select other trees after updateing the felling-date of tree 100, QField displays always the recently set felling-date of tree 100. Even the felling-date in the database is an other.
I can set other felling-dates without a problem. But I always get displayed the last set felling-date.

Only after closeing and reopening the project, the correct felling-dates are shown again.

I reproduced this behavior with a simple point-layer and some attributes.

Hope that helps.
Christoph

**Comment by m-kuhn** [comment]
Thanks for the comprehensive description :+1:

**Comment by saemiw** [comment]
This might be related to what is explained here https://github.com/opengisch/QField/issues/369?

**Comment by geoplanteam** [comment]
Dear all

Thanks for all your work and the release 1 :-)

This issue #319 was resolved (rc3 I think), but now I have it again.
Issue #369, which is very similar, is solved.

I try to explain the difference:
The issue #369 problem is related with newly digitized objects. A date set for the first object was kept for the second, but only displayed and not saved to the database => see the short film with the issue.
This issue is solved.

The issue #319 is a display problem of the date. The date of an iterrogated object is displayed on every other object, when the date-attribute of this object is null. If the date-attribute is not null, the correcte date is displayed. But now this date is displayed on every other object with a null value fot the date-attribute.

Regards Christoph

**Comment by geoplanteam** [comment]
I found a workaround
The problem is due to the datatype. Choose QDateTime instead of QDate and you won't have this problem.

Regards Christoph
