### ISSUE TITLE
QField Sync list of projects empty & server error 500

### ISSUE THREAD

**Issue by abosman-idds** [opengisch/QField#3195]
### Describe the issue
When logging into QField sync, the list of projects is completely empty. The account I am logging in with is the owner and the sole contributor. I am using the beta version of the community edition. An empty test project doesn't show up in the list after creation
Furthermore, when trying to login to the web version, I just get a server error (500) after entering the password. 

### Reproduction steps
1. Go to Qfield Sync
2. Login with account and password
-----------------------------------------
1. Go to https://app.qfield.cloud
2. Login with same password as entered in the steps above

### Expected behavior
To see a list of the projects created by this account.

### Observed behavior
The list of project is empty and the webversion returns a server error (500)

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.26.1
 - QField Version 2.2.3.

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

###Username 
IDDSExplosieven

**Comment by suricactus** [comment]
Are you sure you still experience this error as of today?

**Comment by suricactus** [comment]
Thanks, will investigate right now.

**Comment by suricactus** [comment]
Ah, I just realized you login somehow with your organization username, but not your personal userename. Being allowed to do so is a bug, that will be addressed very soon and will show a proper error message.

What you should actually do is to login with your presonal username (b*****k).

**Comment by abosman-idds** [comment]
Gotcha, that was it. Thanks for the assistance!
