### ISSUE TITLE
sdcard - points not saved

### ISSUE THREAD

**Issue by vowasemp** [opengisch/QField#32]
If the project and spatiallite db is on sdcard of smartphone, the points disappear after closing and ropening the project. There is no error message that points cannot be saved. The project/database on memory of smartphone is working fine

**Comment by m-kuhn** [comment]
The same setup works here. Error reporting in the app certainly could need some love. Something we have experienced problems with in the past was if no autoincrementing primary key was present in the spatialite file.

**Comment by vowasemp** [comment]
I did add an autoincrement key field to the spatiallitedb-layer. But its is the same behaviour, points are lost after closing/opening the project on sdcard

**Comment by m-kuhn** [comment]
Can you attach the project and the database here (or send it to us by mail if it is not public)

**Comment by m-kuhn** [comment]
Too bad we do not have an sdcard slot in our test device.

**Comment by vowasemp** [comment]
OK, its not an urgent problem, we don't need project on sdcard for the moment, I can put project/data to device storage

**Comment by m-kuhn** [comment]
Note to self, probably only requires this permission:

http://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE

**Comment by mbernasocchi** [comment]
building to test

**Comment by mbernasocchi** [comment]
as of 0.6.6 from playstore writing to external sd fails silently

**Comment by mbernasocchi** [comment]
the same project on internal sd works as expected. My own builds crash when writing anywhere, I guess that is something else

**Comment by m-kuhn** [comment]
> The WRITE_EXTERNAL_STORAGE permission must only grant write access to the primary external storage on a device. Apps must not be allowed to write to secondary external storage devices, except in their package-specific directories as allowed by synthesized permissions. Restricting writes in this way ensures the system can clean up files when applications are uninstalled.

https://metactrl.com/docs/sdcard-on-kitkat/

IIUC, all works needs to be done in `/Android/data/ch.opengis.qfield/files`

With Android 5 we get this extra intent [ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT_TREE)

* http://www.androidcentral.com/lollipop-brings-changes-way-your-sd-card-works-kind-youll

**Comment by mbernasocchi** [comment]
haha, I was going to post the same comment after noticing how ES file browser does things.

**Comment by mbernasocchi** [comment]
Confirmed that putting projects and data on the external SD card in

`/Android/data/ch.opengis.qfield/files`

Works on my galaxy s7 edge android 6

**Comment by mbernasocchi** [comment]
so _currently_ QField supports reading data from any location on an an SD card but writing only works in the /Android/data/ch.opengis.qfield/files folder of the SDCard. No writing is possible yet in other folders (unless possibly if the device is rooted).

**Comment by m-kuhn** [comment]
Thanks @mbernasocchi 

I think we should (in the following order)

 1. document this
 2. add a warning when this happens
 3. offer to "unlock" the location with `ACTION_OPEN_DOCUMENT_TREE` in the warning

**Comment by ludodo** [comment]
Thank's for the redirection and the answer.
I moved my "SIG" directories data and project into /[sdcard2]/Android/data/ch.opengis.qfiel/files
No more warning when editing... 
Attribut modification are well saved but when editing new geometries, they don't appear, with no log in qfield.

**Comment by m-kuhn** [comment]
Does the layer's CRS match the project CRS?

**Comment by m-kuhn** [comment]
Yes, I just documented the status in #58 
We should fix that but meanwhile just keep your digitizing layers in the project CRS.

**Comment by m-kuhn** [comment]
Interesting information https://bugreports.qt.io/browse/QTBUG-50759

**Comment by signedav** [comment]
What is the status here @m-kuhn?
