### ISSUE TITLE
Program fail on start up

### ISSUE THREAD

**Issue by Redos09** [opengisch/QField#323]
I am a user of QGIS and Qfield on my google pixel 2L device for geological mapping data as a geologist, I must say that this program is fantastic. Unfortunately I am encountering problems with Qfield today. The program is failing to open continuously. I recently updated the operating system on my phone to Android 9 (Pie) over the weekend. Is there a chance Qfield is not operational on this platform? Any suggestions for fixing would be appreciated?

Thank you

Tom

**QField version:** [0.10.13 - Kesch]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No]

**Comment by m-kuhn** [comment]
Yes, there was a report for problems with Android 9 compatibility before (https://github.com/opengisch/QField/issues/291)

Someone with an Android 9 device needs to have a look at what's going on. First thing to check would be the logcat.

We are available to work on that, contact us by mail if you need a quote.
