### ISSUE TITLE
QField app closed suddenly

### ISSUE THREAD

**Issue by lucienicolier** [opengisch/QField#3248]
### Describe the issue
My team and I are running QField on Android’s electronic tablets and we have a big issue. Indeed, it’s seems like our tablets have a compatibility’s problem with the app, so when we use them on the field, entering the data in the forms, the app closed suddenly for “no reason”. This is happening after one hour an a half, and sometimes before that. When we want to opened the app again, it is now extremely slow and we cannot used it anymore for the day…

### Reproduction steps
Using the app on the field 

### Expected behavior
It should not close and work fluency 

### Observed behavior
It closed for no reason

### Mobile (please complete the following information)
 - Device: electronic tablets
 - OS: Android 10
 - QField version: 2.2.3

**Comment by Ipickedausername** [comment]
Hello,

Unless the incompatibility problem with is established, you'll probably have to provide a test project.

Is "electronic tablets" a brand ? / model ?

**Comment by nirvn** [comment]
@lucienicolier , any update on this? I noticed the version reported was 2.2.3, which is relatively old (we've had a bunch of underlying library updates as well as tons of QField fixes). Could you try on latest 2.4.4?
