### ISSUE TITLE
SDLmain.vcxproj missing

### ISSUE THREAD

**Issue by Bandit253** [opengisch/QField#3259]
### Describe the issue
Unable to clone repo in Visual Studio 2022

e:\DEV\QField\vcpkg\base\ports\sdl1\SDLmain\SDLmain.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'e:\DEV\QField\vcpkg\base\ports\sdl1\SDLmain\SDLmain.vcxproj'.

### Reproduction steps
I opened Visual Studio 2022 and cloned the repository, then there was a heap of working then this error.

### Expected behavior
I would expect the this to be a project tree populated
![image](https://user-images.githubusercontent.com/9003261/187051737-e487a6ad-6dc9-46b9-9940-d94e3044fdc5.png)

### Observed behavior
`x:\DEV\QField\vcpkg\base\ports\sdl1\SDLmain\SDLmain.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'x:\DEV\QField\vcpkg\base\ports\sdl1\SDLmain\SDLmain.vcxproj'.`

### Desktop (please complete the following information)
 - OS: Win 11
 - QGIS Version 3.26.1
 - QFieldSync Version - master repo

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: N/A

**Comment by m-kuhn** [comment]
Please follow the instructions in https://github.com/opengisch/QField/blob/master/doc/dev.md
