### ISSUE TITLE
Invisible button for Topological Editing can provoke geometry corruption

### ISSUE THREAD

**Issue by lp-dj** [opengisch/QField#3266]
### Describe the issue
I'm not sure if the concern described below should be considered an issue or feature request. Please decide for yourself ;)

When editing the geometry of a point, the button for topological editing is not visible. However, if the button was last active on another layer, then moving a snapped point's geometry may unintentionally change the geometries of other layers.

### Reproduction steps
1. Edit a polygon with Topological Editing enabled.
2. Leave topological editing enabled and create a point snapped to an editable layer in a point layer.
3. Move the point created in step 2.

### Expected behavior
Yes, what did I expect... As you can see in the video below, the polygon layer is also changed according to the activated topological editing. I've had this happen to me a few times unintentionally in the field.

I think the point is on the one hand that the button for topological editing is no longer displayed when a point layer is selected. On the other hand, you may not be aware of whether you are still in topological editing from another layer.

Therefore I would suggest 2-3 things here:

1.: The button for topological editing should also be visible in point layers.
2.: It might be worth thinking about whether the status of Topological Editing is switched and saved separately per layer?
3.: Also, it might be helpful to include a warning and confirmation prompt if geometry editing in one layer would also change geometry in another layer?

### Observed behavior
The layer at which the point was snapped is also changed. Even the "Avoid Overlap" set in QGIS is ignored.

### Screenshots and GIFs
[example_video.webm](https://user-images.githubusercontent.com/80956612/187229701-86725f10-d9d4-42f4-85c7-eb13e53d16fe.webm)

[mwe.zip](https://github.com/opengisch/QField/files/9445546/mwe.zip)

### Desktop (please complete the following information)
 - OS: Debian 11
 - QGIS Version 3.22.9

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab Active Pro
 - OS: Android 11
 - QField version: 2.2.3 (772d14)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@lp-dj , fixed, send your thanks to @suricactus :smiley_cat:
