### ISSUE TITLE
Some pictures are missing on QFieldCloud

### ISSUE THREAD

**Issue by juwizeye** [opengisch/QField#3272]
### Describe the issue
I have been using Qfield and QfieldCloud for a while now, but recently , I have some problems with pushing pictures on QField Cloud. the problem is that i  see the picture path in QGIS but there is no corresponding picture in DCIM folder.  I taught before that there was a problem with my configuration but now it think that it is not the reason why. 

### Reproduction steps
1.  I make the configuration for picture in QGIS 
i have tried this configuration:
![image](https://user-images.githubusercontent.com/96420889/187400332-d4a6d6bc-8f7a-4e17-be47-dba5059f4f9f.png)
and this one:
![image](https://user-images.githubusercontent.com/96420889/187400787-e32df6c2-ec4b-42c3-a110-37a2a09a1749.png)
for both , some pictures are missing. 
3. After i push the projet on Qfield via QFieldCloud, after I take pictures and then i push my changes on QfieldCloud. 

### Desktop 
I am using :
 - window 10
 - QGIS 3.22.1
 - QFieldSync 4.0.0

### Mobile 
 - Xiaomi mi 9
 - Android 11
 - QField 2.2.3

**Comment by miili** [comment]
Can confirm this behaviour. Here happening with configured maximum image size.

**Comment by strrings** [comment]
I can also confirm that we're having the same issues as outlined here: [https://github.com/opengisch/QField/discussions/3328]
The sync process to QField Cloud doesn't always send all the photos and we have to manually extract them from our device.

**Comment by nirvn** [comment]
@juwizeye , @miili , @strrings , QField 3.3.10 has received a number of fixes with regards to photo synchronization with QFieldCloud. In addition, it is now possible to manually send individual images to the cloud in case of upload failure. The action is available in the project folder panel through the 3-dot menu of images.

Let us know if 3.3.10 works for you.
