### ISSUE TITLE
Project Export fails to make online layers for QField Cloud projects

### ISSUE THREAD

**Issue by thymaro** [opengisch/QField#3278]
### Describe the issue
When packaging a QGIS project containting a PostGIS layer in a remote DB, the layer is exported to GPKG in the QField Cloud project. The layer configurations are set to "prefer online" in the QField plugin settings tab in the layer properties.
The GPKG in the QField Cloud project is set to "offline editing" instead.

### DB access
host: `postgresql-beq.alwaysdata.net`
database: `beq_testdb_usutf8`
table: `test_table_01`
usr: `beq_testuser`
input: `let-me-in-1234`

### Reproduction steps
1. Create new QGIS project
2. Add a PostGIS table as layer
3. Configure the layers to be "directly access data source" 
4. Export as QField Cloud project
    1. It opens in the QGIS browser
    2. Double-click the supposed PostGIS layer, the info says it's a GPKG
    3. Check the file on disk exists --> sure enough, it's a GeoPackage file.

### Expected behavior
The QField Cloud Project should access the PostGIS database and make edits to the table directly.

### Observed behavior
cf. above

### Additional files
[testproject_01.zip](https://github.com/opengisch/QField/files/9461519/testproject_01.zip)
[testproject_01_cloud.zip](https://github.com/opengisch/QField/files/9461517/testproject_01_cloud.zip)

### Desktop (please complete the following information)
 - OS: Win10
 - QGIS Version 3.22.10-Białowieża
 - QFieldSync Version v4.1.1

### Mobile (please complete the following information)
 - Device: Galaxy Tap S6, SM-T865
 - OS: Android 11
 - QField version: v2.2.3 Coordinated Capybara (772d14)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: don't know, as I didn't use it like this with older versions.
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes, tried several diffeent files and projects and DBs and users.

### QFieldCloud
username: thymaro
project name: testproject_01

**Comment by luisjorge** [comment]
Hi,

Same happens to me. 

Is this problem solved?

Thanks!

**Comment by thymaro** [comment]
Nope. If you want to edit database layers, you will need to make a cable export project. Your PG connection will need a PG service config file and the info therein will need to be stored in your QField Cloud secrets.

I am not using QField Cloud projects with PostGIS layers anymore. Instead, I use QField projects with database connections, but the edit function in QField is really tedious, as it always takes a long time for each keystroke to be translated to an input. So, basically, I only record point coordinates in QField and use something called a “pen” to write on “paper” to record the feature attributes.

Here are some links to get you started with QField × Cloud Projects × PostGIS:

https://docs.qfield.org/how-to/pg-service/#postgresql-service
https://docs.qfield.org/reference/qfieldcloud/secrets/
https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/opening_data.html#pg-service-file

**Comment by m-kuhn** [comment]
It looks like this issue has been solved, so I am closing this.
Please reopen if this is still an issue.
