### ISSUE TITLE
QField crashes when trying to display or interact with a PostGIS layer

### ISSUE THREAD

**Issue by thymaro** [opengisch/QField#3279]
### Related Issue
https://github.com/opengisch/QField/issues/3278#issue-1357279981

### Describe the issue
Text from the related issue for reference, since these steps are pertinent to this issue as well:

> When packaging a QGIS project containting a PostGIS layer in a remote DB, the layer is exported to GPKG in the QField Cloud project. The layer configurations are set to "prefer online" in the QField plugin settings tab in the layer properties.
> The GPKG in the QField Cloud project is set to "offline editing" instead.

After that, I open the local QField Cloud project "testproject_01 (QFieldCloud)" and add the same PostGIS layer as before. The project now has two identical layers "test_table_01", but one is a GPKG and one is a PostGIS layer. In QGIS, both show up as expected and can be edited and everything seems normal.

### DB access
host: `postgresql-beq.alwaysdata.net`
database: `beq_testdb_usutf8`
table: `test_table_01`
usr: `beq_testuser`
input: `let-me-in-1234`

### Reproduction steps

> 1. Create new QGIS project
> 2. Add a PostGIS table as layer
> 3. Configure the layers to be "directly access data source" 
> 4. Export as QField Cloud project
>     1. It opens in the QGIS browser
>     2. Double-click the supposed PostGIS layer, the info says it's a GPKG
>     3. Check the file on disk exists --> sure enough, it's a GeoPackage file.

5. Add PostGIS table as layer in QGIS project "testproject_01 (QFieldCloud)"
6. sync to QField Cloud and wait for the server to process the project
7. Open QField on mobile device, go to cloud projects and download "testproject_01"
8. Open the layer tree and double-tap or long-press the PostGIS layer

### Expected behavior
- The layer should be visible on the map, as it was configured to be visible on the canvas when saving the project in QGIS. 
- The layer dialog should open with possibilities to view the layer on the map and the layer should be editable, accessing the data source directly

### Observed behavior
- _(A single-tap on the layer doesn't select it. Instead, the text background color, that usually is displayed when selecting a layer, just flashes up and away instantly. No crash at this moment.)_
- _The layer in the layer tree shows no symbol before the layer name._
- The app crashes and closes instantly with no message, the PostGIS layer is not editable or viewable in QField for Android.

### Additional files
[testproject_01.zip](https://github.com/opengisch/QField/files/9461519/testproject_01.zip)
[testproject_01_cloud.zip](https://github.com/opengisch/QField/files/9461517/testproject_01_cloud.zip)

### Desktop (please complete the following information)
 - OS: Win10
 - QGIS Version 3.22.10-Białowieża
 - QFieldSync Version v4.1.1

### Mobile (please complete the following information)
 - Device: Galaxy Tap S6, SM-T865
 - OS: Android 11
 - QField version: v2.2.3 Coordinated Capybara (772d14)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: don't know, as I didn't use it like this with older versions.
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes, tried several diffeent files and projects and DBs and users.

### QFieldCloud
username: thymaro
project name: testproject_01

**Comment by suricactus** [comment]
Just a quick question. When you created your QFieldCloud project, did you use the first or the second option from the radio buttons selection? The second one is dumping your data into a GeoPackage anyaway, no matter how you set it up.
![image](https://user-images.githubusercontent.com/2820439/187780710-3a545647-f3b2-41d7-b482-c318597449f2.png)

**Comment by thymaro** [comment]
The first one, creating a new QFC project from the currently open project.

**Comment by suricactus** [comment]
Note the description under the first option "[...] datasets will be copied into an export directory that will act as your local mirror. Vector datasets will be converted to geopackage format [...]". I am pretty sure if you use the second option you will have better success making QFieldCloud connecting to your database, rather than QFieldSync dumping the contents of it. :)

**Comment by thymaro** [comment]
### First try

No luck. I tried creating a fresh empty project on the cloud, specifying a local directory. The cloud sync mask showed a red dot and said there was no file, neither online nor offline. Sure, I thought, that makes sense, as it just told me it would be empty. So I moved some files over and synced, upon which it uploaded the project files. Cool. I downloaded the files to the mobile device through QField, opened the layer tree, double-tapped the PostGIS layer and the app crashed. (same as before)

These files were a pre-existing qfield cloud project. I figured something in the configuration would prevent the project from accessing postgis layers.

### Second try
1. create a fresh QFC project, which is entirely empty
2. create a fresh QGIS project (not qfield or cloud or anything else fancy), two layers, a WMTS and a PostGIS layer
3. move the project file to the empty folder
4. sync to QFC and wait for the project to be processed on the server
5. download to mobile
6. try to interact with the PostGIS layer
7. crash as before

What is the right way to do this if not any of these ways work? I am out of ideas at this point.

**Comment by thymaro** [comment]
I don't see the option to reopen this issue, sorry. Ah, I just read on stackexchange

> you cannot re-open your own issues if a repo collaborator closed them

I would like to kindly ask to reopen, then   😅

**Comment by ewoutdegraaff** [comment]
After repeating all the above steps, I still have the same problems. The corresponding layer does exist in the app, but no objects are drawn on the canvas. When opening an object list from the layer list, the QField app crashes. 
It does not depend on the platform used as I tested it on Android, iOS and Windows. So the problem seems to be in QField Cloud.

**Comment by suricactus** [comment]
Have you tried to transfer your original project from QGIS to QField and test there?

**Comment by ewoutdegraaff** [comment]
I have tested both methods + 1 described above:

- First create a project and then send it to QField Cloud;
- Create project from the QField Sync plugin (v4.2.0);
- And also create a project from QField Cloud.

QGIS does give an error in the log when saving the project:

2022-09-06T13:25:53 WARNING Traceback (most recent call last):
              File "C:\Users/{user}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\layers_config_widget.py", line 93, in
              lambda msg: self._on_message_bus_messaged(msg)
              File "C:\Users/{user}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\layers_config_widget.py", line 274, in _on_message_bus_messaged
              layer_source.read_layer()
              File "C:\Users/{user}/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\layer.py", line 101, in read_layer
              self._action = self.layer.customProperty("QFieldSync/action")
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

Could this be the cause of the problem?

**Comment by suricactus** [comment]
Good catch, can you share your QFIeldSync version?

On the testing, can we add a 4th way of testing:

1. go to your directory where the `.qgs` project is stored.
2. zip it to `project.zip`
3. send it to your QField device (via email, telegram etc)
4. import your `project.zip` in QField
5. share if QField still crashes.

**Comment by ewoutdegraaff** [comment]
Also tried QFieldSync v4.0.0-BETA20 wit similar results

**Comment by suricactus** [comment]
Ok, crash fixed here: https://github.com/opengisch/QField/pull/3304

I have just looked into the project from the initial message and there is a configuration error.

QField supports two ways of connecting to a postgis database:

1) Storing all credentials within the `.qgs` project file.
2) Storing all credentials in an external `pg_service.conf` file. (https://docs.qfield.org/how-to/pg-service/)

I have configured the QGIS project to use `pg_service.conf` file, add the pg_service secret on QFieldCloud and all works as expected now.

![Peek 2022-09-06 17-47](https://user-images.githubusercontent.com/2820439/188665914-97f25f7f-4f5f-4773-b203-4f89e186e538.gif)

Please reopen only if you are using one of the above described ways of connecting to PostGIS layers.
