### ISSUE TITLE
The copy text, paste text and scan code tab is not displayed

### ISSUE THREAD

**Issue by Fertuesta25** [opengisch/QField#3282]
### Describe the issue
The copy text, paste text, and scan code tab is not displayed on a record tab when dealing with a relationship.

### Reproduction steps
1. Create a project that has a relationship
2. Add a relationship record in QField
3. The copy text, paste text and scan code tab is displayed below the tab

### Expected behavior
The copy text, paste text and scan code tab should be displayed above the registration tab in a relationship

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]
As shown in a relationship record tab
![WhatsApp Image 2022-09-01 at 11 55 46 PM](https://user-images.githubusercontent.com/59838508/188062779-d5411bb1-22f7-4c6a-a3df-077c54f9e4a1.jpeg)

How it looks when the tab is not a relationship
![WhatsApp Image 2022-09-01 at 11 56 18 PM](https://user-images.githubusercontent.com/59838508/188062965-7cb30897-f860-40d0-9222-ca73dc111f59.jpeg)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows 10 Pro]
 - QGIS Version [e.g. 3.26.2]
 - QFieldSync Version [e.g.4.2.0]

### Mobile (please complete the following information)
 - Device: [e.g. Moto g(50) 5G]
 - OS: [e.g. Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.3.0 (472043)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@Fertuesta25 , this has been fixed, you can test APKs here (https://github.com/opengisch/QField/pull/3419)

**Comment by Fertuesta25** [comment]
Thank you very much @nirvn, it works perfectly.
