### ISSUE TITLE
Font size on windows

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#3289]
It would be nice if the font size in the QField for windows user interface is similar to the default font size of the operating system.

Currently the font size of the QField user interface is somewhat large.
![image](https://user-images.githubusercontent.com/59838508/188280511-f23be4ad-ef37-42e0-a16c-254b2c284ea3.png)

_Originally posted by @Fertuesta25 in https://github.com/opengisch/QField/issues/3121#issuecomment-1236163153_

**Comment by nirvn** [comment]
@m-kuhn , fixed.
