### ISSUE TITLE
Samsung S-Pen not working with QField 0.5.5 Elbrus

### ISSUE THREAD

**Issue by rwjdennis** [opengisch/QField#33]
I'm running QField on two Samsung Galaxy Tab A tablets. One (call it Tab1) has version 0.5.2 - Elbrus and the other (call it Tab2) is 0.5.5 - Elbrus. The stylus that comes with the tablet - the S-Pen - has some integration with the software of the tablet. The stylus has full functionality with QField (and other apps) on Tab1, but no functionality with QField on Tab2. The stylus works with all other apps on Tab2.

This is mainly a concern in colder weather when you can't take gloves off for very long. Non-proprietary styli still work with QField and Tab2, so that is a workaround. They are not as precise, though.

**Comment by m-kuhn** [comment]
Confirmed in a test with a Galaxy Note 8.0.

But no idea why just right now, will need some more investigation.

**Comment by rwjdennis** [comment]
This continues to be an issue for version 0.8.8 - Hiendertelltihoren. Neither of our tablets have S-Pen functionality with QField.

We're going to be doing some pretty intensive field hours during the next four weeks and having S-Pen functionality would help keep our hands warm. :)

Any updates on the progress towards fixing this bug? Can I provide any pertinent system information/logs that could help?

**Comment by m-kuhn** [comment]
If I remember correctly I could reproduce this with a Galaxy Note 8.0.

Some things to consider

 * How does zooming work (given that there's no pinch possibility with the stylus)?
 * Would digitizing be done with the stylus instead (I think there's a button to control pan vs. digitizing)?

We didn't have the time to look into this yet. If you would like to raise its position in our todo list, please contact us by mail :)

**Comment by rwjdennis** [comment]
Thanks, Matthias.

You are correct.

To your points:
- zooming with the stylus was executed using a double-tap. I don't know by how much each double-tap increased the scale.
- digitizing worked the same as it does with fingers. Select Mode>Digitize, then pan with the stylus to place the reticle where the new feature should be, and start editing by tapping the button in the lower right corner whenever you want.

I'll email you, then. :)

Thanks!

**Comment by signedav** [comment]
@m-kuhn Is this a pending thing anymore? Or is it fixed? 
I did not have any issues with the pens, but I have no possibility to test with old tablets.

**Comment by m-kuhn** [comment]
Stylus support could be improved with a dedicated "stylus digitizing mode" which is different to the working mode with finger. I.e. moving the crosshair when the stylus is close to the display, pretty much like a mouse.

**Comment by m-kuhn** [comment]
Stylus support has been much improved recently.
Is this still an issue?

**Comment by rwjdennis** [comment]
This is no longer an issue.
