### ISSUE TITLE
Windows silent installation blocked by Microsoft Visual C++ Redistributable

### ISSUE THREAD

**Issue by slefrancois** [opengisch/QField#3308]
### Describe the issue
When installing QField 2.0.14 on Windows silently, the installation is interrupted by the Microsoft Visual C++ Redistributable installer requiring user input. This blocks automated deployment.

### Reproduction steps
1. Run silent install: `qfield-v2.0.14-windows-x64.exe /S`

### Expected behavior
QField should install silently without user input.

### Observed behavior
A window pops up asking to modify the installation for Microsoft Visual C++ 2015-2019 Redistributable (x64) 14.29.30139, blocking silent installation until the user chooses to repair or ignore the VC++ installer. By closing the VC++ installer, installation of QField finishes silently.

A possible solution would be to pass the silent install arguments down to the VC++ sub-installer.

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/18192425/188918803-30f2d24f-987b-41c5-8a3a-4f262375f9b0.png)

### Desktop (please complete the following information)
 - OS: Windows 10 21H2
 - QField 2.0.14

### Additional information
* Problem can be reliably reproduced, doesn't happen randomly: probably depends on whether another version of Microsoft Visual C++ 2015-2019 Redistributable (x64) is already installed on the system.

**Comment by slefrancois** [comment]
I have tried uninstalling the existing Microsoft Visual C++ 2015-2019 Redistributable (x64) 14.29.30139. A similar problem then occurs where the VC++ installer pops up to perform a fresh install of the redistributable.

Installing the vcredist_x64.exe provided with the QField installer reproduces the original modify VC++ install problem.

It appears that in any case, the QField installer is blocked by a VC++ popup.

**Comment by nirvn** [comment]
@slefrancois , please try the latest version:

https://github.com/opengisch/QField/releases/tag/v2.3.2

Look for the windows installer towards the bottom of that page.

**Comment by slefrancois** [comment]
Silent Windows install with /S on v2.3.2 works, thanks.
