### ISSUE TITLE
[Android] Menu backdrops are transparent

### ISSUE THREAD

**Issue by ImpulseDeer** [opengisch/QField#3309]
### Describe the issue
The top left menu and the gear menu are  transparent which makes them unreadable.

### Reproduction steps
1. Click top left menu button
2. Click gear menu in the top row of menu options
Random if it happens on first or within 10 times from startup.

### Expected behavior
Expecting a white fill behind the menu to make it readable.

### Observed behavior
Background fill is transparent.

### Screenshots and GIFs
![Screenshot_20220908-150100](https://user-images.githubusercontent.com/111496869/189129679-b09619e4-8392-44eb-bd4d-6e9c2f592e3e.jpg)
![Screenshot_20220908-151931](https://user-images.githubusercontent.com/111496869/189132513-27e75490-7833-4908-aa7a-fa1457620058.jpg)

### Desktop
Not a problem on
Windows 10
2.0.14

### Mobile
 - Device: Galaxy Tab Active2, SM-T395
 - OS: Android 9
 - QFIELD Version 2.2.3 and 2.3.2

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [New user]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes, always per session but not on first open]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by ImpulseDeer** [comment]
Does not happen on my phone:
Device: Xiaomi 11T
OS: Android 12 SP1A.210812.016

**Comment by BoswachterMarc** [comment]
I am preparing the same tablet (Galaxy Tab Active2, SM-T395) for someone and experiencing the same problem.
The project is made in QGIS 3.26.3 and running on the latest QField beta release 2.4.2 Ecstatic Elk (b6fa99 v2.4.2).
Other devices  (Samsung Tab Active Pro SM-T545 or smartphone Galaxy A52) do not have that problem.

![image](https://user-images.githubusercontent.com/57868975/196052308-3d101a54-7a6c-48c0-aed4-c9169cf6e9dd.png)

**Comment by aghiraldi** [comment]
The problem appears with several faces in the forms: 
 - the background of the drop-down list is sometimes transparent
 - sometimes the text is also invisible (if you click on the window, a choice from the invisible menu can be selected)
 - sometimes, nothing happens and the display remains blocked for a few seconds.

Qfield version: 2.4.5
Project: any project
Device: Samsung Galaxy Tab Active2, SM-T395
OS: Android 9

Qfield has become unusable on Samsung Galaxy Tab Active2 tablets : ( 

Maybe we need to review the minimum requirements?

Translated with www.DeepL.com/Translator (free version)

**Comment by nirvn** [comment]
@aghiraldi , @BoswachterMarc , @ImpulseDeer , can one of you provide a sample project that features a broken feature form combobox? 

Also, if you guys could give QField 2.5 a try, I can't think of anything _directly_ related to this that changed but we did touch on styling handling a bit.

**Comment by nirvn** [comment]
@aghiraldi , @BoswachterMarc , @ImpulseDeer , in 15 min, there should be APKs for you guys to try out: https://github.com/opengisch/QField/pull/3593

Could you report back as to whether the feature form combo boxes still have transparent background (sometimes, all the times) or whether you always see a red background.

**Comment by nirvn** [comment]
Oh, one more thing: if you guys can go back in time and find which was the last "good" QField version that did not have this bug, that'd be helpful. You can install APKs from the release page one version at a time and try (https://github.com/opengisch/QField/releases/). Good hunting.

**Comment by nirvn** [comment]
@BoswachterMarc , @aghiraldi , @ImpulseDeer , gentle ping. It'd be great if you guys could try the APK in the above-mentioned PR #3593 and report back :)

**Comment by BoswachterMarc** [comment]
I did check with the latest QField release (Fancy Flamingo 13f23d v2.5.6) and the problem is still there. A certain moment, aside from the know issue of transparant backdrop menu, the app froze and turned into a black screen.
But I will go back in time and see if there is a earlier release without that problem.
By the way, the app (and project) works well on a Galaxy Tab Active Pro SM-T545 with Android version 11.

**Comment by BoswachterMarc** [comment]
I tried the PR https://github.com/opengisch/QField/pull/3593 but the APK doesn't install. I think it should be a ARM release, not a ARM64  (Droid info says CPU ARMv7-A and Kernel armv8l for the SM-T395)

![afbeelding](https://user-images.githubusercontent.com/57868975/205698077-08e8985b-c7b9-405e-abdc-ceb8c6ed9baf.png)

**Comment by nirvn** [comment]
@BoswachterMarc , you can expand the other architectures section, you'll find arm in there.

**Comment by nirvn** [comment]
@BoswachterMarc , direct link: https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield-dev-3593-7069ebf0f86f11bc4d67035a6dcab0cd2fd8b0fe-arm-android.apk

**Comment by BoswachterMarc** [comment]
Ok, I tried

- QField old version Uluru1da006 v1.10.0 and it works (no transparent dropdown sidemenu). This version works more fluent on the SM-T395
- QField version #3593 bèta does not work!. The project is loaded but the dropdown under the 3 stripes is not shown (I mean no dropdown at all). The menu with settings, read/write, cloud, is also absent!
In this bèta version, the project files is stored in 'ch.opengis.qfield_beta', not in 'ch.opengis.qfield' (the path to 'imported projects' is not available in ch.opengis.qfield)

**Comment by nirvn** [comment]
@BoswachterMarc , when you say 1.10 works, are you implying that all 2.x versions are problematic? 2.0 also has the menu problem?

**Comment by BoswachterMarc** [comment]
> @BoswachterMarc , when you say 1.10 works, are you implying that all 2.x versions are problematic? 2.0 also has the menu problem?

I will check thoroughly the 2.x versions one of these days

**Comment by BoswachterMarc** [comment]
@nirvn

- The Arctic Fox release 2.0.14 (arm Android) crashes (before opening a project) when opening on the Galaxy Tab Active2, SM-T395
- The coordinated capybara 2.2.0 opens a project but works slow and freezes when asking for the side menu.
- The Bumblebee version 3e5eac v2.1.0 doesn't crash but has the same issue (transparent backdrops, not at first but after doing some manipulations)

In other words, as you said, it looks like all 2.x versions are problematic.

**Comment by nirvn** [comment]
Very useful thanks

**Comment by nirvn** [comment]
@BoswachterMarc , thanks for this dissection. Looking at the changes between 2.0.14 and 2.1, I've identified two commits that have possibly caused the combobox background issue. Could you try APKs from two PRs that revert those commits?

First APK to try, I've reverted an android theme change: https://github.com/opengisch/QField/pull/3750

Second APK to try, I've reverted surface antialiasing change: https://github.com/opengisch/QField/pull/3751

Crossing fingers, we're getting closer :)

**Comment by nirvn** [comment]
@BoswachterMarc , great news! :)

Could you test the APKs from PR #3751 again please? I applied one more tweak and I would like to make sure comboboxes are still OK on your device. Thanks

**Comment by nosmos** [comment]
Hi, I can confirm: the last PR #3751  has solved the transparency issue on my SM-T395 device. Thanks.
