### ISSUE TITLE
Unable to open dataset from project folder

### ISSUE THREAD

**Issue by ImpulseDeer** [opengisch/QField#3312]
### Describe the issue
I have a project consisting of multiple geotiff layers as its dataset. Its possible to open these layers by going out to the "Go to Home Screen" but not directly from within the "Open Project Folder".

### Reproduction steps

This works:
1. Click top left menu
2. Click gear menu
3. Click "Go to Home Screen"
4. Click "Open local file"
5. Click "Imported projects"
6. Click on the project in question
7. Click on the wanted dataset link
8. The data will now be selected and shown on the map

This does not work
1. Click top left menu
2. Click gear menu
3. Click "Open Project Folder"
4. Failure point: The dataset doesn't not have a valid link and are not clickable.

### Expected behavior
It to be possible to select the data both of these ways, especially the broken one since it requires half as many clicks!
(I would be happy if it was possible to change viewed layer with even fewer clicks than that!!)

The "Remove dataset" menu option is also missing when entering this folder from "Open Project Folder"

### Observed behavior
Links in the Project Folder seems to be broken and thus unclickable.

### Screenshots and GIFs
Selecting file after import works but not from the "Open Project Folder" path
https://user-images.githubusercontent.com/111496869/189150541-78226f1f-e825-4827-b05f-0e99b0efb309.mp4

Selecting files by first going to the "Home Screen" works
https://user-images.githubusercontent.com/111496869/189150695-92efa00e-388b-40c2-abd5-88330b0867af.mp4

### Desktop (please complete the following information)
 - OS: Windows
 - QField Version: 2.0.14 dev
 
 Does not happen here because the defintion of a project is different and one can only open one dataset (file) at a time and not import a full folder.

### Mobile (please complete the following information)
Device: Galaxy Tab Active2, SM-T395
OS: Android 9
QFIELD Version 2.2.3 and 2.3.2

AND

Device: Xiaomi 11T
OS: Android 12 SP1A.210812.016
QFIELD Version 2.2.3

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Unknown, new user]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes, always]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@ImpulseDeer  , FYI, this is on purpose to avoid people mistakenly opening an individual dataset when viewing project files. IMHO, we should only open datasets/projects from the welcome screen. If you are OK with this UX decision, let's close the issue?
