### ISSUE TITLE
Photo Attachment: Automatic Downscale of Picture

### ISSUE THREAD

**Issue by miili** [opengisch/QField#3314]
### Describe the issue
Modern phones have high resolution and generate 10+ MB per photo. This cloaks the pipeline and increases the project size.

### Expected behavior
Setting for automatic down scaling of photos to standard resolution.

### Observed behavior
[A clear and concise description of what actually happened.]

**Comment by suricactus** [comment]
This is already available in QFieldSync settings.

**Comment by nirvn** [comment]
@miili , this is implemented and can be activated in the project properties' QField panel:
![image](https://user-images.githubusercontent.com/1728657/189518254-560507e0-e3c9-4895-822f-01beaccc799c.png)
