### ISSUE TITLE
Empty mail after using Compress folder to option

### ISSUE THREAD

**Issue by geomondego** [opengisch/QField#3323]
Hello @opengis-ch Team,

In version 2.3.2 (07ed27) after i try to use the **Compress folder to** option, the mail is empty.

![Screenshot from 2022-09-10 14-52-40](https://user-images.githubusercontent.com/4389239/189486494-89f69eff-0780-4f11-81c2-2a3766f933e3.png)

**Comment by nirvn** [comment]
@geomondego , I've tried with what will become 2.3.3 (no code change on that front), and was successful in attaching:
![Screenshot_20220910_210549](https://user-images.githubusercontent.com/1728657/189487062-50153def-93a1-477a-b2ca-923f120e1de2.jpg)

If there's an issue with QField, it seems not to be for all folders. Can you provide steps to reproduce?

**Comment by geomondego** [comment]
@nirvn I'm with an old device with Android 8.1.

The steps are the same that with Android 12, that works just fin.:
   - Open local file, then Imported Projects

**Comment by nirvn** [comment]
@geomondego , alright that narrows things down a bit. Could you attach a screencast of a failed send compressed folder to mail on your android 8 device? 

Are you able to send compressed folders using other apps (eg whatsapp) on that Android 8 device?

**Comment by geomondego** [comment]
@nirvn after update to version 2.3.3 everything works. We can close this issue?

**Comment by nirvn** [comment]
@geomondego , we sure can. Thanks for confirming the regression is gone.
