### ISSUE TITLE
statusbar overlaps the menu

### ISSUE THREAD

**Issue by antoniusz** [opengisch/QField#3332]
### Describe the issue
Starting with version 2.3.0, the statusbar overlaps the menu and buttons, partially covering them.
When touched, in an unpredictable way, sometimes the statusbar, other times the menu/buttons react.

### Screenshots and GIFs
![Screenshot_20220912-160221](https://user-images.githubusercontent.com/10415477/189665598-714ef68d-b900-4578-8806-dcb95bfe9e08.png)

### Desktop (please complete the following information)
 - OS: Debian Bullseye
 - QGIS Version 3.26.3
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: Spectra Geospatial MobileMapper50
 - OS: Android 6.0.1
 - QField version: 2.3.3

**Comment by nirvn** [comment]
@antoniusz , could you try the APKs here and let me know if your issue is fixed: https://github.com/opengisch/QField/pull/3336 -- thanks.

**Comment by antoniusz** [comment]
Yes, solved it.
