### ISSUE TITLE
Menu button and menu green header not showing

### ISSUE THREAD

**Issue by hernanfuria** [opengisch/QField#3333]
### Describe the issue
While opening a (demo or personal) project (for example the 'Simple Bee Farming Demo'), the menu button (the black circle with the 3 horizontal lines) is not appearing. The only way of accessing the layer menu is by sliding the finger on the left side of the screen towards the center. When i do this, i can see the layers, but te green top part of the menu is missing.

### Reproduction steps
1. Open QField app
2. Open a project

### Screenshots and GIFs
I attach pictures of the screen because couldn't take screenshots on the device
![issue qfield1](https://user-images.githubusercontent.com/105759780/189736646-0b10e467-8b5e-4fba-9c14-e6e15e0422d0.jpeg)
![issue qfield2](https://user-images.githubusercontent.com/105759780/189736649-56a4dd8f-0ee0-4670-8850-f34336a0fcce.jpeg)

### Expected behavior
These are some screenshots of the app working properly on another device (Mobile: Motorola Moto g6, Android 9)
![issue qfield1 expected behavior](https://user-images.githubusercontent.com/105759780/189738490-08c7b2e3-0d69-40b3-a178-45d5ee343716.jpeg)
![issue qfield2 expected behavior](https://user-images.githubusercontent.com/105759780/189738500-022eb017-6825-4bdb-a9e0-286faac1644a.jpeg)

### Mobile
 - Device: tablet Alcatel 8067
 - OS: Android 8.1.0
 - QField version: 2.3.2 Diversified Dugong

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@hernanfuria , I'll look into this ASAP.

**Comment by nirvn** [comment]
@hernanfuria  , could you try the APKs here and let me know if your issue is fixed: https://github.com/opengisch/QField/pull/3336 -- thanks.

**Comment by nirvn** [comment]
@hernanfuria , are you in a position to verify the above-linked APKs fixed the issue for you?

**Comment by amgiss** [comment]
I had the same issue on an older Samsung tablet and can confirm that the beta #3336 does not fix the missing top green bar or circular menu not appearing on my device.

**Comment by nirvn** [comment]
@amgiss , thanks. Could you attach a screenshot?

**Comment by nirvn** [comment]
(@amgiss , details on your phone model, android version, etc would be helpful too)

**Comment by amgiss** [comment]
Samsung Galaxy Tab A (2017) running Android 7.1.1.

I can't get the beta to run, it keeps crashing before I can open a project.

Screenshot of the problem running QField 2.3.3.

![QField 2 3 3](https://user-images.githubusercontent.com/80868027/190392259-755f2ba9-e516-4a51-a0bc-19f4478fa33d.jpg)

**Comment by nirvn** [comment]
@amgiss , try the APKs here: https://github.com/opengisch/QField/pull/3340

Are you using the arm v7 or arm64 v8 APKs?

**Comment by amgiss** [comment]
I installed qfield-dev-3340-b22d92dcbe55f001cb608149cafc48d59eaa1560-arm-android.apk and that seems to have fixed the issue for me.

Thanks very much.

**Comment by nirvn** [comment]
@amgiss , screenshot possible? :)

**Comment by amgiss** [comment]
Screenshot from PR3340.
![QField PR3340](https://user-images.githubusercontent.com/80868027/190846166-6fe5d4e6-0c97-426d-b1be-d88d6cf5128e.jpg)

**Comment by amgiss** [comment]
The black circular menu is visible again and I don't need to swipe to get the panel open.

**Comment by nirvn** [comment]
@amgiss , big thanks. We will publish a new version on the play store as soon as possible, stay tuned :) thanks for your help.

**Comment by hernanfuria** [comment]
Just got the device back from the field work. Now it's running the most recent version (2.3.5 i think) and i can confirm that the menu and search buttons are back and working properly.
Thank you very much!
