### ISSUE TITLE
White screen while trying to open local file

### ISSUE THREAD

**Issue by hernanfuria** [opengisch/QField#3334]
### Describe the issue
While pressing 'Open local file' at the home screen the UI is not showing properly, instead a white screen appears, which is not touch responsive.

### Reproduction steps
1. Open QField app
2. Press 'Open local file'

### Expected behavior
The UI should appear to let me select the project i want to open.

### Observed behavior
Only a white screen appears.

### Mobile (please complete the following information)
 - Device: tablet Alcatel 8067
 - OS: Android 8.1.0
 - QField version: 2.3.2 Diversified Dugong (07ed27 v2.3.2)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by nirvn** [comment]
@hernanfuria , thanks for reporting this. Are you in a position to send a screencast of you launching the app and trying to open the local files panel?

If you are in a position to provide a logcat file that'd be good too.

**Comment by nirvn** [comment]
@hernanfuria , is this fixed in QField 2.3.4?

**Comment by hernanfuria** [comment]
Hi, i had to install an older version (Coordinated Capybara) on that device and now it's being used for field work. When i get it back i'll check it out.
Sorry for the late reply.

**Comment by nirvn** [comment]
@hernanfuria , gnetle ping, back in office yet? :)
