### ISSUE TITLE
Impossible to open new project

### ISSUE THREAD

**Issue by Emic37** [opengisch/QField#334]
As I met some errors with new release 0.11.0, I made a clean install of QField : wipe data of the application, uninstall and reinstall QField 0.11.0.
Now it's impossible to open a portable project : the explorer doesn't display anything.  

### Screenshots and GIFs

Screenshot of the errors encountered before clean install. I define Qfield seemed work despite these errors : 
![Screenshot of the errors encountered before clean install. I define Qfield seemed work despite these errors](https://zupimages.net/up/18/34/trix.jpg)

And the empty explorer : 
![And the empty explorer](https://zupimages.net/up/18/34/9pdq.jpg)

**QField version:** [0.11.0]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nicpitsch** [comment]
I made the same experience, which i commented here https://github.com/opengisch/QField/issues/286#issuecomment-416040435.

**Comment by giedrioks26** [comment]
I have the same problem with 0.11.0. Also shows the wrong GPS position. XYZ tiles do not work. Different QGIS projects (2.18.23, 3.2.2). Android 5-7. Tested on different devices - Samsung, Lenovo, Blackview.

**Comment by signedav** [comment]
Thanks for reporting. I can confirm that and we will check ASAP.

The empty file dialog issue is not on the compiled master but only on the released version @m-kuhn

**Comment by m-kuhn** [comment]
Our special operations team is right now working on a complete replacement of this dialog with a new and future proof system. Stay tuned!

**Comment by Emic37** [comment]
Thank to you all for your answers. I switched back to 0.10.13 and I'm waiting for the new file dialog system. ;)

**Comment by m-kuhn** [comment]
There is a new emergency fix available on https://github.com/opengisch/QField/releases/tag/release-0.11.1 and playstore (might take some time to be rolled out), we are happy to get any feedback on this!

**Comment by giedrioks26** [comment]
I'm working fine. but I do not see the difference from 0.10.13 (scalebar always shows mm, no print layouts etc. ). So must it be?

**Comment by m-kuhn** [comment]
Yes, It offers only parts of the updates so far unfortunately, we're working on getting all up and running again still. It was mostly meant to get everyone up and running again.

**Comment by nicpitsch** [comment]
I can confirm that this issue is resolved with QField latest version 0.11.1.

**Comment by m-kuhn** [comment]
@giedrioks26 @nicpitsch can you also check the download here?

https://github.com/opengisch/QField/pull/340#issuecomment-416519091

It should come with all the new features

**Comment by giedrioks26** [comment]
I checked apk. the problem persists. "can not open database: ..." wrong GPS location

**Comment by m-kuhn** [comment]
Let's focus on the new problems introduced with 0.11, opening projects, that works?
The cannot open database problem is not new I think https://github.com/opengisch/QField/issues/286

**Comment by giedrioks26** [comment]
If we focus only on innovation, it's all great. XYZ tiles are not working, but I think it's affecting "can't open database: ..."

**Comment by iqnaul** [comment]
> If we focus only on innovation, it's all great. XYZ tiles are not working, but I think it's affecting "can't open database: ..."

hi, I'm also experience an issue that XYZ Tiles is still not working on the latest version of QFIELD
