### ISSUE TITLE
Search: Feature select zooms to 0.0 E / 0.0 N

### ISSUE THREAD

**Issue by miili** [opengisch/QField#3351]
### Describe the issue
Selecting a searched feature pans and zooms to 0.0 E / 0.0 N.

### Reproduction steps
1. Search a feature
2. Select the found feature

### Expected behavior
Zoom to feature.

### Observed behavior
Map jumps to 0/0 in WGS84 coord system.

### Mobile (please complete the following information)
 - OS: Android 11
 - QField version: 2.3.3

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Dunno
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Only some projects.

Project `Eifel-Large-N / Eifel_LargeN-Deployment`

**Comment by nirvn** [comment]
@miili , can you share a sample project over here? Or, alternatively, assuming you've referred to a cloud hosted project at the end of your description, add my account (mathieu@opengis.ch) as a collaborator.

**Comment by mbernasocchi** [comment]
@miili can you try the apk mentioned in #3465 and see if your issue is fixed?
