### ISSUE TITLE
Cannot use GPS with CRS

### ISSUE THREAD

**Issue by Palatkik** [opengisch/QField#336]
I cannot use GPS with CRS = what am I doing wrong? I am new to the app so apologies if the answer is obvious to others except me?

### Reproduction Steps:

1. Create two different projects in QGIS 3.2 using CRS WGS84 UTM47N.
2. Package for Qfield using the QGIS 3.2 QGISFieldSync plugin.
3. Copy the packaged folder to the HUAWEI Mate 9\Internal storage\Android\data\ch.opengis.qfield\files\share folder using Win10 file exlorer. Note if I copy to any other folder, I cannot find the files to open with Qfield app folder browser. Why?
4. Open the qgs file from the share folder on Android with Qfield and project seems to display OK.
5. Enable GPS with Show Position information on. The GPS displays coordinates in decimal degrees and seems to plot the real time position on screen using a decimal degree value on the projected UTM sytem, i.e thousands of meters in error?   

### Expected behavior:

I expected the Qfield app to plot GPS in corrected CRS system coordinates? 

**QField version:** [0.11.0]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes - only started using QField recently - no experience of older versions] 
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by giedrioks26** [comment]
I have the same problem.
I think it's about this #334. Currently being repaired. Try the older version (0.10.13) so far https://github.com/opengisch/QField/releases/tag/release-0.10.13

**Comment by giedrioks26** [comment]
#286

**Comment by Palatkik** [comment]
Thanks giedrioks26 - that solved the problem for me.

**Comment by VxTedxV** [comment]
I think this issue can be closed : problem solved for me with QField 0.11.4.
