### ISSUE TITLE
How do you use @position_used_satellites ?

### ISSUE THREAD

**Issue by bettellam** [opengisch/QField#3360]
How do you use @position_used_satellites ???
The QField Documentation:
https://docs.qfield.org/how-to/gnss/
says to use: array_count (@position_used_satellites),
but using this function:
- I don't get values;
- this error is reported in the log messages:
"**Default value expression for MY_Point_GNSS: used_satellites has parser error: array_count function is called with wrong number of arguments. Expected 2 but got 1**"
It would seem that we need to add Arguments / Attributes / ???, but I can't find any descriptions about it.
array_count (@position_used_satellites, Arguments / Attributes,)

[array_count] does not exist in QGis functions, certainly it is managed internally by QField, 
**it is possible to have indications / suggestions ....
or is it an error: @position_used_satellites == Nan ???**
Thank you
Mauro B

PS
Looking at the code for a while, I realized that @position_used_satellites is passed
QList <int> QgsGpsInformation :: satPrn (IDs of satellites used)
which brings no more information:
@position_number_of_used_satellites == array_count (@position_used_satellites)

It would be much more useful to have: **satellites in View**, replacing with:
QList <QgsSatelliteInfo> QgsGpsInformation :: satellitesInView

PS - PS
 ... is it conceivable to have a SkyPlot Satellites in QField?
![SkyPlot](https://user-images.githubusercontent.com/23143342/191558653-fce3868f-fdae-4b98-b507-e6414f9f9433.jpg)

**Comment by bettellam** [comment]
I have updated the QGIS version - 3.24.3-Tisler
There is the function: array_count.
I close this issue.
If anyone gives me suggestions, they are well accepted.
Thank you

**Comment by antoniusz** [comment]
After struggling for a while, with help of ChatGPT :-), i managed to populate the string type field "usedSatellites" using `@position_used_satellites` variable. 

The default value expression:
`array_to_string(array_foreach(@position_used_satellites, to_string(@element)), ', ')`

**Comment by bettellam** [comment]
@antoniusz  VERY GOOD Thank you!!!
I just tested it and it works perfectly.
![image](https://github.com/opengisch/QField/assets/23143342/850beb15-db60-4688-90ca-8ce20789cd05)

With this result I will reopen the question!
@nirvn , @m-kuhn , @nyalldawson 
Currently **@position_used_satellites** is passed:
`QList QgsGpsInformation :: satPrn `(ID of satellites used)

It would be much more useful to have:
`QList QgsGpsInformation :: satellitesInView`
this could allow me to have a lot of further information:
- skyplot satellites;
- count number of satellites for each constellation;
- satellite in use/not in use;
- signal quality:
- etc.

Thank you

**Comment by m-kuhn** [comment]
@antoniusz great to hear that chatGPT is able to write QGIS expressions 👍 

@bettellam should we open a new issue as an enhancement / feature request to add a variable `@position_satellites_in_view` instead?

**Comment by bettellam** [comment]
Ciao @m-kuhn 
The current setting of **@position_used_satellites**:
`QList QgsGpsInformation :: satPrn` (ID of satellites used)
doesn't add anything more than **@position_number_of_used_satellites**.
Knowing the satellite ID is useless for a normal user.
Only an expert user of GNSS/NMEA signals will be able to figure out which constellation it belongs to.

Personally I wouldn't create a new variable,
**in @position_used_satellites there will be all the visible satellites**:
`QList QgsGpsInformation :: satellitesInView`
will be a: array of arrays:
{ {azimuth, elevation, id, inUse, satType, signal}, {azimuth, elevation, id, inUse, satType, signal}, etc..... }
I was thinking about this:
https://api.qgis.org/api/classQgsSatelliteInfo.html

With these values the user will be free to create the appropriate commands to extract the data of all the satellites received.
We will have to work with the **ARRAY_ xxx** commands of Qgis,
but I think good results can be achieved...

**Comment by m-kuhn** [comment]
Shall we concentrate on the other issue then and close this?

I am in favor of stable interfaces. i.e. no change to the semantic of existing variables.

**Comment by bettellam** [comment]
@m-kuhn  ok fine, you're right! I'm closing this one

**Comment by bettellam** [comment]
@antoniusz  your solution is now in the QField documentation.   
https://docs.qfield.org/how-to/gnss/#:~:text=QField%20can%20make%20use%20of,%2C%20TCP%2C%20or%20UDP%20connection.
