### ISSUE TITLE
@position_horizontal_accuracy and @position_vertical_accuracy not working on feature geometry UPDATE

### ISSUE THREAD

**Issue by Inogeo** [opengisch/QField#3380]
### Describe the issue

During **feature geometry update**, fields with default value set to `@position_horizontal_accuracy` and `@position_vertical_accuracy` are updated with empty values. In my *.qgs project, the property **"Apply default on update" is active** inside the Form Widget Editor.

### Reproduction steps

1. Create a *.qgz project with a point vector layer
2. Add 2 real fields
3. Set the default value to  `@position_horizontal_accuracy` and `@position_vertical_accuracy` inside the form widget editor
4. Check up the checkboxes "Apply default on update" inside the form widget editor
5. Open the *.ggz project on Qfield
6. Switch to editing mode
7. Create a point and save entity
8. Check the properties : **vertical / horizontal accuracy values are well recorded and saved**
9. Select the point
10. Update the point geometry
11. Check the properties : **vertical / horizontal accuracy values are now empty**

### Expected behavior

Value of fields with default value set to `@position_horizontal_accuracy` and `@position_vertical_accuracy` should be updated by the latest value reported by the device after each update saved for feature's geometry

### Observed behavior

During **feature geometry update**, fields with default value set to `@position_horizontal_accuracy` and `@position_vertical_accuracy` are updated with empty values. In my *.qgs project, the property **"Apply default on update" is active** inside the Form Widget Editor.

### Screenshots and GIFs

QGIS project creation (click on the picture to get video):

[![QGIS project](https://user-images.githubusercontent.com/16825471/192288104-e92f58a0-5630-4a1f-ad73-45f1eff3e2c8.png)](https://user-images.githubusercontent.com/16825471/192284345-dd57296a-2339-45ac-be2c-6c53bd335a1f.mp4)

QFIELD use case  (click on the picture to get video):

[![QField use case](https://user-images.githubusercontent.com/16825471/192288355-2793e4fe-35b0-4d54-8b8e-afab68b69f46.png)](https://user-images.githubusercontent.com/16825471/192289693-9600f39c-d973-4d12-be6f-6a0556001ad3.mp4)

QGIS Project for testing:
[qfieldtest.zip](https://github.com/opengisch/QField/files/9646750/qfieldtest.zip)

### Desktop (please complete the following information)

 - OS: Windows 10
 - QGIS Version **3.22.3**
 - QFieldSync not used

### Mobile (please complete the following information)
 - Device: Galaxy Tab S3 (SM-T825)
 - OS: Android 9
 - QField version: 2.3.4

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: We don't know
* Problem can be reliably reproduced, doesn't happen randomly: **YES**
* Problem happens with all files and projects, not only some files or projects: Two different projects were used to used, even the simplest on has the bug.

**Comment by Inogeo** [comment]
@bettellam I just tried with another device:
- Device: Samsung Galaxy A50
- OS: Android 11
- QField version: 2.3.4
- internal GNSS

Did you tried an update on the feature's geometry (check red circled button on the picture below) ?
![image](https://user-images.githubusercontent.com/16825471/192512603-69dbbd49-1a56-4f40-a016-d5b526e62639.png)

**Comment by bettellam** [comment]
@Inogeo Ok, your observation is correct!
The "Edit Vertex" tool does not update the @position_xxxx fields used in data table!
In fact, another "Edit Attributes" tool has been provided.

Actually I could have a Points Feature Class, where the point is positioned in an approximate way (Aqueduct network nodes) and with a GNSS survey I would like to update the correct position, consequently you also need to update the @position_xxxx variables (GNSS status / quality values) used in data table!

I agree to your update request!

**Comment by Inogeo** [comment]
Yes, in the case of a survey that aims to acquire better GPS positioning on existing entities we need this feature to be operational.

**Comment by nirvn** [comment]
@Inogeo , this issue has been fixed. Could you test APKs provided in this PR (https://github.com/opengisch/QField/pull/3495) and confirm all works as you'd expect? Thanks

**Comment by bettellam** [comment]
Ciao @nirvn , I'm sorry but for the tests I ran, it doesn't work!
(commit: 6d5dbcb33e01514dfae54f36c36b018680ba6ea6)
I used the vertex (point) edit tool
After "Stop editing":
Fields containing standard QGis functions are OK, they are updated to new values!
Fields containing @GNSS_xxx or @POSITION_xxx are NULL!

**Comment by nirvn** [comment]
@bettellam , I think you're using the wrong APKd. Install the right one provided in the above-linked PR.

**Comment by nirvn** [comment]
@bettellam , happy to hear this, thanks for testing.

**Comment by Inogeo** [comment]
After testing we confirm that the feature is well operational too.
