### ISSUE TITLE
GPS position not recognizing southern hemisphere (Y coordinate with '-')

### ISSUE THREAD

**Issue by SvenFish** [opengisch/QField#3386]
### Describe the issue
Qfield 2.3.4 is not recognizing the '-' (minus sign) in my phone's GPS coordinates.
So, my Samsung Galaxy S10 is sending it X: 145.35..., Y:-37.8... (correctly shown at the bottom of the QField screen) and QField is showing my location as just off the coast of Japan which would equate to X: 145.35..., Y: 37.8... (no '-' sign in front of Y coord) while I'm actually near Melbourne, Australia.
All other GPS enabled apps on my phone show correct location.

### Reproduction steps
1. Make sure you are in the southern hemisphere
2. Open a project with OpenStreetMaps as the base
3. Enable GPS - is the location correct?

### Expected behavior
GPS shows position in southern hemisphere

### Observed behavior
GPS shows position in northern hemisphere

### Screenshots and GIFs
N/A

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - Device: Samsung Galaxy S10
 - OS: Android 12
 - QField version: 2.3.4 - Diversified Dugong (65044c V2.3.4)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@SvenFish , :eyes: does it happen with the simple bees sample project?

**Comment by SvenFish** [comment]
It did happen with the bee project so then I tried deleting and reinstalling the app and it now shows the correct location. Strange!

**Comment by nirvn** [comment]
@SvenFish , odd, but glad things are not upside down for you anymore ;) shall we close this issue for now?

**Comment by SvenFish** [comment]
Yes, case closed - thanks for the help!
