### ISSUE TITLE
SVG error after update & slow layer panel loading

### ISSUE THREAD

**Issue by olegzhelezn** [opengisch/QField#3387]
### Describe the issue
After update to the latest version, SVG markers (the ones available in QGIS, not custom) are gone, replaced by question marks. I know embedding works as temporary troubleshooting, but these are default QGIS SVGs, and they used to work fine in past versions of QField.
Also, the layer panel is opening very slowly: it takes ~2 seconds between tapping on it and opening. 

![image](https://user-images.githubusercontent.com/39202056/193156962-bf04cea8-6ba8-4c25-8211-9ee557f28d2d.png)

### Mobile (please complete the following information)
 - Device: Redmi Note 10
 - OS: Android 11
 - QField version: 2.3.4 65044c

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by VxTedxV** [comment]
https://qfield.org/docs/prepare/custom-svg.html

**Comment by nirvn** [comment]
@olegzhelezn , can you try the APK here: https://github.com/opengisch/QField/pull/3368#issuecomment-1257123897

I suspect the SVG regression is fixed.

As for slow layer label opening, please provide a test project. Cheers
