### ISSUE TITLE
QR function access

### ISSUE THREAD

**Issue by berniefritsch** [opengisch/QField#3415]
### Describe the issue
Menu for opening QR code function is in the back

### Reproduction steps
Form is designed with using 'Visibility controlled by expression`- function in QGIS

### Expected behavior
Menu after clicking the three dots should appear in the front to be able to use the QR code scanner and return to form afterwards

### Observed behavior
Menu is in the back, form closed in order to get access to the QR Reader

### Screenshots and GIFs
![ScreenshotQR](https://user-images.githubusercontent.com/4800959/194284976-634b68a4-1922-436c-8467-5eb6f4e7c956.jpg)

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version [e.g. 3.20.0]
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab Active Pro SM-T545
 - OS: Android 11
 - QField version: 2.3.2 (07ed27)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Looking at the screenshot, this seems to be happening when editing objects on a relation (child), is this correct?

**Comment by berniefritsch** [comment]
Yes, this is the case of a editing objects on a relation (child). The QRCode function is inside a vector layer (child) related to a geometryless table (parent) and it does not work properly, as shown in the screenshot. However, this does not happen if the function runs through the parent table and not through the child layer. The function is supposed to work through the layer, anyway. Thanks in advance for your suggestions.

**Comment by berniefritsch** [comment]
Sorry to bother you once more - I just updated to QField 2.4 - here the problem still exists. So I need to keep using the apk-version from #3419 for some time?

**Comment by nirvn** [comment]
@berniefritsch , did you post a comment earlier today? Github seems to have completely removed it, I only have an email trace of it.

**Comment by berniefritsch** [comment]
Yes, I posted a comment and deleted it myself. I thought I had updated QField via Playstore and the error still exists, but apparently I did not update QField (2.4 is not in the playstore yet?) and was working in the old version. I now installed the latest 2.4 apk from github and everything is fine.

**Comment by nirvn** [comment]
@berniefritsch , I was hoping you'd reply along those lines :) we have started rolling out the new version to users gradually. By the end of the weekend, it should be available to all users.
