### ISSUE TITLE
password shows in clear text even when hiding

### ISSUE THREAD

**Issue by thymaro** [opengisch/QField#3417]
### Describe the issue
On the login screen of q field the user password is shown in full or in part when showing the password with the button to the right of the password input field.

### Reproduction steps
1. Open QField without having logged in
2. Go to the login screen
3. Input username then input password
4. Tab on the eye icon to show the password
5. Tap on the eye icon again to hide the password

### Expected behavior
The password should be hidden after tapping the eye icon to hide the password.

### Observed behavior
When there is white space in the password the last part of the password is shown in plain text instead of dot symbols. This seems to be linked to the autocorrect function of the mobile device, as it only happens when a keyboard app is active and the cursor focus is at the end of a word. 

### Screenshots and GIFs
https://youtube.com/shorts/crUx8NUIT38?feature=share

### Mobile (please complete the following information)
 - Device: Cat S62 Pro
 - OS: Android 11
 - QField version: db8560 v2.3.5

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: not sure
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: NA

**Comment by nirvn** [comment]
@thymaro , could you try the APKs in PR #3420 , I am (somewhat :wink:) confident it'll improve the situation for you.

**Comment by thymaro** [comment]
The newest release has this issue gone.
