### ISSUE TITLE
QFieldCloud packaging bug

### ISSUE THREAD

**Issue by JUAN1936** [opengisch/QField#3424]
### Describe the issue
After time working without problems and with a large volume of data. I suppose something has happened with the Geopackage data package. That I am unable to load the project on the smartphone.
The project is successfully uploaded to the server, but then: packaging error unable to download the project.
I have managed to upload it through the cable but not in the cloud. I'm a bit desperate.
I would like you to analyze the package for me, to see if you see the error.

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS 3.22.8
 - QFieldSync Version [4.2.0]

### Mobile (please complete the following information)
 - Device: [Samsung S20FE]
 - OS: [ Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.3.5 The last
 
Project:
 Juan63  Catastro_con_estilos

**Comment by suricactus** [comment]
Hey, @JUAN1936 . It seem you are not aware of the existance of Jobs page in your QFieldCloud project. There you can see additional information what is going on with your project. In your case I see the job is timing out, which means it failed to finish within 1 minute. Now the timeout is increased to 10 minutes and all should be good.
