### ISSUE TITLE
Lose data during entering new object and tap on map

### ISSUE THREAD

**Issue by nicpitsch** [opengisch/QField#343]
During digitizing a new object you might lose data when you tab on the map (instead within the form). This behavour is new with the latest version 0.11.x.

### Reproduction Steps:

1. Enter digitizing mode.
2. Start entering data on the form.
3. Tap on the map (instead of within the form) -> the form gets closed and the new entered data is lost.

### Expected behavior:

Same as with older versions, where nothing happens. Besides this particular case, the more consistent behavour concerning closing the form, which was introduced with 0.11.1, is welcome.

### Observed behavior:

This only happens as long as you didn't save the new object. After that, when you open again the form for editing, there is the expected behavour.

### Screenshots and GIFs

**QField version:** 0.11.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by giedrioks26** [comment]
Do you have the correct GPS location on the device?

**Comment by nicpitsch** [comment]
With QField 0.11.2 i get now a message `Changes saved` when i tap on the map. In fact the object is saved now, the issue is resolved. I'm sure this was different with version 0.11.1, isn't it?

**Comment by m-kuhn** [comment]
Thanks for the feedback.
Yes, 0.11.1 was an emergency release lacking many of the new features in 0.11.0 and 0.11.2.
