### ISSUE TITLE
QField 2.4.0/2.4.1 fails to install on iPad

### ISSUE THREAD

**Issue by rabeneth** [opengisch/QField#3437]
Hello,

we have been using QField for Android for years for our field work (almost all employees have android devices) and it is nicely integrated in our workflow. 
Our new managing director however favors Apple products and now my task is to implement it on an iPad and iPhone.
The experience I have with Apple devices so far comes from my research since an iPad device was bought a few weeks ago.
Now that QField for iOS is out of beta I wanted to try that, since the time limited beta is not suited for our needs.

### Describe the issue
Installation of non-beta iOS QField 2.4.0 (also 2.4.1) on Ipad (using iTunes) fails with error message "integrity could not be verified".

### Reproduction steps
1. Connect iPad with iTunes (running on Windows 10) via USB-C
2. Drag and drop  **qfield-v2.4.1-arm64-ios-12.0.ipa** or  **qfield-v2.4.0-arm64-ios-12.0.ipa**  file over "Device" section in iTunes

### Expected behavior
After dropping *.ipa file on "Device" section in iTunes QField should install successfully.

### Observed behavior
After dropping *.ipa file on "Device" section in iTunes:
1. iTunes copies file to device and starts installation
2. Installation process is visible on iPad Display
3. Installation fails with error message "integrity could not be verified"

### Screenshots and GIFs
![IMG_0017](https://user-images.githubusercontent.com/115541608/195295607-d55dc672-0c34-4d6c-9836-901e943309e9.PNG)

### Desktop
 - OS: Windows 10
 - iTunes: 12.12.5.8
 - QGIS Version 3.22.4

### Mobile
 - Device: iPad 9 MK4E3FD-A
 - OS: iPadOS 15.7
 - QField version: 2.4.0/2.4.1

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: First installation outside of Testflight
* Unrelated issue: I was able to install QField beta from Testflight but i can not figure out how to get my local project in a file location QField can see (Project Home Screen has no +-Button; QFieldCloud currently not integrated in our workflow).
* Problem can be reliably reproduced, doesn't happen randomly: Yes (Only 1 device available for testing)
* Problem persists after logging in with AppleID in iTunes: Yes
* QField does not show up in the AppStore
* Experience with Apple products: Basically zero
* I am not sure if the chosen install method is recommended for this app but other methods of installing apps that are not on the AppStore seem to use sketchy third-party software with key features locked behind paywalls or require Jailbreak

**Comment by nirvn** [comment]
@rabeneth , question: are you able to install it via the app store?

**Comment by rabeneth** [comment]
> @rabeneth , question: are you able to install it via the app store?

I was under the impression that this is what happens through itunes. QField does not show up in app store search. Within the app store there are no tools to install anything that does not show up in the app store. Nothing happens when the ipa-file is opened on the iPad and there are no install options anywhere.

from appmaster.io:
How to Install an IPA File on an iOS Mobile App?

iTunes application is used to install IPA files on iOS devices _using the app store_.

-  First, you need to plug your iOS device (iPad/iPhone) into your laptop.
-  Second, go to iTunes and locate your iOS device in the section Devices of the program's side menu.
-  Drag your Open IPAss into the iTunes device list.

**Comment by mbernasocchi** [comment]
just go to https://qfield.org/get and you'll be redirected to the appstore.

as for the search, i guess we're not well indexed yet. if you search qfield for qgis you find it
