### ISSUE TITLE
[Enhancement] Option to enable/disable selection on layers

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3444]
Hello,

Do you think we could have an option for each layer, with a tick, to enable or disable the possibility to select features on the map. 

In this way, we could keep displaying information on the map, without opening everything each time we try to open a specific feature. 

It could look like this: 

![Example](https://user-images.githubusercontent.com/72577399/195635281-507c8e84-4bc4-447a-afde-a59cc67cd01a.jpg)

What do you think ?

**Comment by m-kuhn** [comment]
Could that be set in the configuration on qgis side (layer properties) already?

**Comment by Ipickedausername** [comment]
I don't know if it is possible. 
And, it would result in less liberty for the user. 

The idea is to keep important information on the map without opening the feature list anytime we clic on the map. 
If I use a grid, a layer with administrative localities, study area, etc. I need to keep it displayed, sometime I could open a feature to check information, but most of the time I would prefer not to open the feature list of these layers when I clic on another editing layer.

It can improve the efficacy and speed of the app by opening the right features without loading useless features (for example, in my situation, the grid can take "time" to open (we talk about 1 sec) every time I open a point layer). 

I'll also try to find a better approach to work with my layers. Maybe I'll find something more practical.

**Comment by timbo-barnes** [comment]
I agree this would be a useful enhancement for the reasons mentioned above: Often you want to have layers in your project as reference but without the need to select them- Having all features selected/highlighted makes the UI more cluttered and confusing when, for example, your project is only concerned with one or two editable layers but needs multiple other layers as reference.

**Comment by nirvn** [comment]
This is something that can be configured already in QGIS in the project properties dialog:

![image](https://github.com/user-attachments/assets/6ce1609e-46fd-4d56-b755-0cfe9761b395)

Unless someone here thinks this should be something we can toggle in QField itself (I'm not sure how I'd respond to that ;-P), should we close the issue?

**Comment by Ipickedausername** [comment]
I wasn’t aware that this functionality worked this way. In my work, this should be sufficient, as I can't foresee a situation where I would need to change the selectable/unselectable status of a layer from QField.

But maybe it would be practical for someone else?

**Comment by nirvn** [comment]
@Ipickedausername , I will close this then. Unless someone explicitly needs that level of on-the-fly toggling and can justify it, I think what we have now is what I feel is the right approach.
