### ISSUE TITLE
QField 0.11.1 update

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#345]
Trying to update from 0.11.0 to 0.11.1 on my Android 7.0 phone but : 
- from Playstore -> download OK but error -504 on installing
- from apk armv7 -> "App not installed. Package seems corrupted."
I've seen 0.11.2 but no apk available (and not on Playstore).

Did I miss something ?

**Comment by giedrioks26** [comment]
Sometimes it happens to me too. You should uninstall the program (not upgrade) and reinstall the new apk or from the playstore again. It's work around. Of course, your settings are left out.

**Comment by m-kuhn** [comment]
The error sounds pretty much like [this one here](https://android.stackexchange.com/questions/35062/error-504-when-downloading-apps-from-play-store) which is out of our responsibility.
0.11.2 took a moment longer in testing than usual but it's uploaded now.

**Comment by VxTedxV** [comment]
Thanks for your help I will try to reinstall later, as I must save my datas first (tried 0.11.2 with same issue).
