### ISSUE TITLE
 I can't print to pdf

### ISSUE THREAD

**Issue by JUAN1936** [opengisch/QField#3471]
### Describe the issue
Since the last update, I can't print to pdf
### Reproduction steps
1. [Go to '...']
2. [Click on '...']
3. [Scroll down to '...']

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows 10]
 - QGIS Version [ 3.26]
 - QFieldSync Version [last ]

### Mobile (please complete the following information)
 - Device: [ - Device: [samsung S20FE]]
 - OS: [ Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.04.1 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@JUAN1936 , thanks for reporting this, a regression did slip into the latest QField 2.4. A fix is inbound, it would be great if you could confirm the APKs in this PR (https://github.com/opengisch/QField/pull/3472) fixed printing for you.

**Comment by JUAN1936** [comment]
Ok in that apk, printing without problem, thanks for everything.
