### ISSUE TITLE
Qfield freeze / crash when adding relation 

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3473]
Hello, 

The app Qfield freeze or crash when I try to add information in a relation layer. 

I add 2 video to visualize it: 
Freeze:
https://user-images.githubusercontent.com/72577399/196347953-270a2ca9-7050-4291-a090-4f45bc60cf55.mp4

Crash:
https://user-images.githubusercontent.com/72577399/196347932-e40ea2e3-1d36-4e3a-a3ac-54d6f77a8bc0.mp4

And also a test project: 

[test_simpl.zip](https://github.com/opengisch/QField/files/9806899/test_simpl.zip)

Thank you.

### Desktop (please complete the following information)
 - OS: [Windows 10]
 - QGIS Version [ 3.26.0]
 - QFieldSync Version [e.g.4.2.0]

### Mobile (please complete the following information)
 - Device: [Samsung galaxy S9]
 - OS: [e.g. Android 11]
 - QField version: 
 [master-dev 16c92a]
[Qfield 2.4.1 (5d2ac1)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by nirvn** [comment]
@Ipickedausername , confirmed; the problem has to do with attributes' default value expressions referring to each other, creating a never-ending loop of updates.

**Comment by nirvn** [comment]
@Ipickedausername , a set of APKs will be available in ~15 minutes here (https://github.com/opengisch/QField/pull/3475), they should fix your issue. Let us know.

**Comment by nirvn** [comment]
@Ipickedausername , BTW, thanks for attaching the test project, I suspect without it the issue would not have been addressed for the foreseeable future. 

Good issue reports produce speedy fixes :wink:

**Comment by nirvn** [comment]
@Ipickedausername , you had a few issues raised in this one PR -- the crasher is gone, but the freeze isn't.

**Comment by nirvn** [comment]
The freeze happens when QField waits for and never is able to acquire an OGR connection:
![image](https://user-images.githubusercontent.com/1728657/196378390-4d815f56-069e-42ad-9482-323812873aa1.png)

**Comment by Ipickedausername** [comment]
Hello, 

Indeed, there are no more crashes.
I tried to disable [legend] feature count for all layers, and indeed no more freezes (I liked this option, but I can do without...). 

You were mentioning loop in default values. I can't find any loop. 
Is this related to the use of joined layers ?

I close the issue because it is working well with the APK. 

Thank you!
