### ISSUE TITLE
Enhancement proposal: Support communication/reading data-fields from NFC-device

### ISSUE THREAD

**Issue by koenigherford** [opengisch/QField#3476]
Lots of mobile devices are able to communicate with NFC-devices (sticker, buttons, coins....) When checking ((similar) point) objects in the field (e.g. maintenance and cleaning of bee-boxes, nesting boxes, waste bins, ...), NFC devices can ensure that the beekeper / staff was directly on site and collects data of the correct object. 

It will be great if QField may provide the reading of NFC devices and joining a nfc-data-field with a key-field in the nest box or waste-bin-GIS-dataset. In this case the user will be able to open the input form of the correct feature in QField. The beekeper, the staff ... can  now collect any data (control date, maintanence-result ... ) manually or automatically with higher precision and maybe by forced to be on site .

**Comment by m-kuhn** [comment]
Could this be solved with https://github.com/opengisch/QField/issues/2435 in combination with another app?

**Comment by koenigherford** [comment]
I think a combination with #2435 can useful, but as a non-software-specialist I have no idea how to persuade QField and another app to talk together and establish a useful workflow (click scan NFC in QField/or other app, auto-open the form of a layer in QField which is combined with NFC-reading in QField-settings). 

Are there any QField interfaces for 3rd-party app, which will allow such a workflow ? (I've never read about them)

**Comment by m-kuhn** [comment]
#2435 would allow QField to talk to other apps, but as you say the exact workflow would first need to be evaluated.
An implementation without #2435 would also be feasible.

**Comment by koenigherford** [comment]
closed with https://github.com/opengisch/QField/pull/4539
