### ISSUE TITLE
Value Relation Widget cannot write to Int Field

### ISSUE THREAD

**Issue by amgiss** [opengisch/QField#3483]
### Describe the issue
Using a filtered value relation widget to select and write values to an int field fails.

### Reproduction steps
1. Value Relation widget configured with unique string field as key and integer field as value.
2. Selecting a key field value to filter the input options fails when the target field is an int. Testing done with GPKG only.
3. Selecting a key field value to filter the input options succeeds when the target is a string field. Tested with GPKG only.

### Expected behavior
The widget will input a int to an int field.

### Observed behavior
The value relation widget will write a text string to a text string field or int to a text string field but not an int to an int field.

The project and widget works as expected in QGIS but not in QField on Android or Windows

Qfield returns an error - Value "From Key Field" NOT NULL could not be converted to a compatible value for Col_Int(Integer)

QField value relation widget populates a target int field with a greyed value that disappears whenever another field is changed. A target text field populated with the widget is black and remains selected when any other form field is changed.

Test project attached.

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.26-3
 - QFieldSync Version N/A

### Mobile (please complete the following information)
 - Device: Samsung S22 Ultra
 - OS: Android 12
 - QField version: 2.2.4 db90b00

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Unsure
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes
* Problem happens with QField for Windows the same as on Android
[Value Relation.zip](https://github.com/opengisch/QField/files/9836794/Value.Relation.zip)

**Comment by amgiss** [comment]
This issue is caused by a configuration error. Sorry, and please close this issue.

**Comment by nirvn** [comment]
@amgiss , thanks for taking the time to let us know. Happy field mapping!
