### ISSUE TITLE
Support for external receiver via NMEA over TCP 

### ISSUE THREAD

**Issue by pyrog** [opengisch/QField#3484]
### Feature request
Some GNSS receivers could send a NMEA stream over TCP (port 1958 by default).
The receiver could be a client of your app (QField is the TCP server)…
or the server (QField is the client).

#### Softwares
- [Vespucci](https://vespucci.io/help/en/GPS%20sources/) an OpenStreetMap editor

#### GNSS receivers
- [Sparkfun RTK devices](https://github.com/sparkfun/SparkFun_RTK_Firmware/pull/309)
- [Emlid Reach M2](https://docs.emlid.com/reach/reachview-3/settings-overview/#position-streaming)

**Comment by m-kuhn** [comment]
@pyrog as you noticed, this is likely closed by #3770, could you verify if this works as expected with 2.6?

**Comment by nirvn** [comment]
We've got good feedback from users who have tested the feature, it's officially implemented and working :partying_face: .
