### ISSUE TITLE
Move Feature: Update derived GNSS attributes

### ISSUE THREAD

**Issue by miili** [opengisch/QField#3485]
### Describe the issue
Special fields, e.g. `@gnss/position_horizontal_accuracy` are set when **new** features are created.
When an existing feature is moved using the phone's position the attributes are not set.

### Reproduction steps
1. Move an existing point feature to the current position

### Expected behavior
The feature's specia `@position_` attributes are set.

### Observed behavior
The attributes are `NULL`

### Mobile (please complete the following information)
 - OS: Android 11
 - QField version: 2.4.3

**Comment by nirvn** [comment]
@miili , this should be fixed in the next QField point release. You can test APKs here (https://github.com/opengisch/QField/pull/3495) and give some feedback as to whether it now works properly.
