### ISSUE TITLE
Freehand scanning doesn't work for me

### ISSUE THREAD

**Issue by JUAN1936** [opengisch/QField#3486]
Because it may be that freehand digitization with an optical pen does not work on my device, which I may be doing wrong.
### Reproduction steps
1. [Go to '...']
2. [Click on '...']
3. [Scroll down to '...']

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows 10]
 - QGIS Version [e.g. 3.26.0]
 - QFieldSync Version [e.g.the last version]

### Mobile (please complete the following information)
 - Device: [e.g. Samsung S20 FE]
 - OS: [e.g. Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.4.4 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by m-kuhn** [comment]
Thank you for opening this issue. This has been reported in https://github.com/opengisch/QField/issues/3054 already. Thanks for adding any additional information there.
