### ISSUE TITLE
Add AppStream Metadata file for Linux

### ISSUE THREAD

**Issue by darkdragon-001** [opengisch/QField#3492]
### Describe the issue
In order for package managers to gain more meta info (screenshots, bug tracker, donation URL, ...), applications should provide an [AppStream Metadata file](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html).

### Reproduction steps
No template in https://github.com/opengisch/QField/tree/master/platform/linux

### Expected behavior
Application should provide AppStream Metadata file for Linux.

### Observed behavior
No AppStream Metadata file provided for Linux.

### Desktop (please complete the following information)
 - OS: Linux
 - QGIS Version
 - QFieldSync Version

### Mobile (please complete the following information)
 - Device:
 - OS:
 - QField version:

**Comment by m-kuhn** [comment]
Could you open a PR with a draft?
I'll be happy to review.

**Comment by darkdragon-001** [comment]
It differs a bit based on the package format you are distributing your app as. For AppImage, you can find the docs [here](https://docs.appimage.org/packaging-guide/optional/appstream.html).

**Comment by m-kuhn** [comment]
The part where I'd be happy to get someone experienced involved is the installation routine.
I have filled the generator:

```
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
	<id>qfield</id>
	<metadata_license>GPL-2.0</metadata_license>
	<project_license>GPL-2.0+</project_license>
	<name>QField</name>
	<summary>A simplified touch optimized interface for QGIS</summary>
	<description>
		<p>QField focuses on efficiently getting GIS fieldwork done and exchanging data between the field and the office in a comfortable and user friendly way.

Built on top of the popular QGIS open source project, QField lets users consume fully configured projects in the field allowing for customized feature forms, map themes, print layouts, and more, bringing the power of QGIS at your fingertips.
</p>
	</description>
	<launchable type="desktop-id">qfield.desktop</launchable>
	<url type="homepage">https://qfield.org/</url>
	<screenshots>
		<screenshot type="default">
			<image>https://qfield.org/images/title_tablet.png</image>
		</screenshot>
	</screenshots>
	<provides>
		<id>qfield.desktop</id>
	</provides>
</component>
```

**Comment by darkdragon-001** [comment]
One suggestion: `<id>` is usually the reverse DNS name (e.g. `org.qfield.QField`). The file name should be `<id>.metainfo.xml`.

You CMake structure looks quite complex.

So the target for linux needs to [`install()`](https://cmake.org/cmake/help/latest/command/install.html#files) the AppStream file to `${CMAKE_INSTALL_DATADIR}`.

Something like:
```cmake
include(GNUInstallDirs)
install(FILES /path/to/metainfo.xml
        DESTINATION ${CMAKE_INSTALL_DATADIR}/metainfo/qfield.metainfo.xml)
```

**Comment by darkdragon-001** [comment]
I created a PR as suggestion but didn't test it. You should check that the built AppImage contains `usr/share/metainfo/qfield.metainfo.xml`.
