### ISSUE TITLE
Default values using other fields in expressions inconsistent behavior

### ISSUE THREAD

**Issue by GCouet** [opengisch/QField#3509]
### Main issue
Using expressions referencing other fields in the project, default values are inconsistently filled. All do work within QGIS.

- a string field concatenating geometry X and Y only when a second boolean field is set to true, else is set to NULL. (does not work)
- a datetime field set to now() with the same boolean field condition as the previous. (does not work)
- another string field concatenating gnss_coordinate when a second boolean field is set to true. (does not work)
- another datetime field with the same conditions but referencing the second boolean field (this one sometimes works, it is the last field in the form, may be relevant).

Live update is inconsistent. Depending on the order in which the fields are filled, sometimes the expression succeeds during entity edition for the second datetime field (the last field in the form).

Even if live update doesn't work, when saving the entity, the last datetime field will always have been filled. Not the other three.

This happens on projects packaged through QFieldSync, QGIS projects opened directly in QField, and QFieldCloud projects. Tested on two different devices.

### Reproduction steps
1. Set a layer with conditional expressions using a boolean field true/false state ( if() function ) for default value
2. Send project to QField via any means (direct, QFieldSync, QFieldCloud)
3. Add entity and tick boolean checkboxes. String and datetime fields do not live update, some are filled on saving entity.

### Expected behavior
Either for all default values to work if supported or for all to fail if not.

### Observed behavior
Only certain fields work, and live update is inconsistent. One of two same type fields with the exact same expression writes default value on saving. Not the other.

### Desktop
 - OS: Windows 10
 - QGIS 3.26.3
 - QFieldSync 4.2.0

### Mobile
 - Device 1: Motorola G7 Play
   - OS: Android 10
   - QField 2.4.4 (db90b0)
 - Device 2: Samsung Galaxy Tab A
   - OS: Android 7
   - QField 2.4.4 (db90b0)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Unknown
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes
* QFieldCloud project _Echantillonnage_ can be checked under user: **gabrielc** 

[Test_data.zip](https://github.com/opengisch/QField/files/9869960/Test_data.zip)

**Comment by nirvn** [comment]
@GCouet , bonjour -- I think you'll get the desired behavior by insuring that the [x] apply default value on update is checked:

![image](https://user-images.githubusercontent.com/1728657/198057624-cfd55ece-01a2-40c9-95bc-918a50fdc2de.png)

Without that check the default values are deliberately only computed _once_ (upon feature creation, which in QField is when you hit the :white_check_mark:  icon of a newly created point's form.

**Comment by GCouet** [comment]
> I think you'll get the desired behavior by insuring that the [x] apply default value on update is checked

@nirvn Unfortunately, this means if any other field is ever updated, all default values will be overwritten, which is what I was trying to avoid. I am still puzzled on why it worked for one field and not the others (all had the _Apply default value on update checkbox_ disabled).

> Without that check the default values are deliberately only computed once

In QGIS this is true although the warning message isn't really correct in that even when unchecked, the expressions work (as shown in the gif). The intended behavior in my case is to have a timestamp of the moment and location where the boolean fields were changed to TRUE.
![form_use](https://user-images.githubusercontent.com/52578322/198071711-81d761e6-8b78-4051-bd6b-64efa33e7f86.gif)

**Comment by nirvn** [comment]
@GCouet , give robots roughly 15 minutes to cook a set of APKs in this PR (https://github.com/opengisch/QField/pull/3510) and give this a try. I think it'll fix the behavior discrepancy you have highlighted here.

**Comment by GCouet** [comment]
@nirvn This PR brings the behavior inline with QGIS. Perfect!

Merci pour le super travail!

**Comment by GCouet** [comment]
@nirvn I'm a tech at Université de Sherbrooke. It's a research project called LakePulse. Lakes are studied all across Canada to build a health profile for each one. Unfortunately it seems the online web map portal is offline right now. The project has been going on for several years but I'm trying to convert the group to digital note-taking.
Their protocol is pretty strict and detailed, and in order to limit the amount of different layers and entities to deal with, I'm attempting to have one single form/entity that can deal with an entire lake. That's the reason for all those conditional default values.

**Comment by nirvn** [comment]
@GCouet , sounds fascinating. Keep us updated on your progress, sounds like it'd make for a fantastic QField usage case study! :)

**Comment by nirvn** [comment]
@GCouet , greetings, hope this finds you well. Due to regressions linked to the commit that fixed this issue, we are about to revert the QField behavior to what it was before this issue was addressed.

While doing some testing, I noticed that latest QGIS 3.30 behaves like QField used to on this front. Have you noticed the same thing?
