### ISSUE TITLE
Multiline for TextEdit widget

### ISSUE THREAD

**Issue by Emic37** [opengisch/QField#351]
I choosed TextEdit widget with 'multiline' option for some of fields in my layers. All works perfectly with Qgis Desktop but with QField, these fields are displayed with only one line. It's not practical to use these free expression fields with only one edit line.

### Reproduction Steps:

1. Set a field with TextEdit widget and tick 'multilines' option. 
2. Export your project 
3. Open with QField

### Expected behavior:

QField displays the multilines text edit fields with a few text edit lines. Ideally, user should be able to set in the parameters the number of lines to display. But the default could be around 5 lines.

### Observed behavior: 

QField displays the multilines text edit fields as a simple text edit field, with only one edit line.

### Screenshots and GIFs
[One multilines text edit field normally displayed in Qgis desktop](https://nsa39.casimages.com/img/2018/08/30/1808300300198427.jpg)

[...and the same field displayed in QField](https://nsa39.casimages.com/img/2018/08/30/180830030019180000.jpg)

**QField version:** [0.11.1]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
Do you have the return button avialable? IIRC it should grow as you add new lines.

**Comment by Emic37** [comment]
No, it doesn't. You will able to view [another exemple](https://nsa39.casimages.com/img/2018/08/30/180830045151345283.jpg) with more text and the keyboard opened. All lines of text are displayed on only one and the return button of keybord doesn't display.

**Comment by m-kuhn** [comment]
I thought that was already done, sorry.
Any work on edit widgets is considered a feature request on QField side. We will be happy to accept contributions to improve the situation here.

**Comment by m-kuhn** [comment]
Estimated time is half a day / 500 €.

**Comment by m-kuhn** [comment]
#368 looks like it's already there

**Comment by nicpitsch** [comment]
@m-kuhn issue #351 here concerns the same Field widget as #368, but that's the only common. #351 is only relevant if keyboard doesn't have a _return_ button, which seems to me like a rare constellation.

**Comment by m-kuhn** [comment]
Do you work with a physical keyboard?

**Comment by nicpitsch** [comment]
No only the default virtual keybord, using a smartphone and different tablets. I hit the return button and the _Text Edit, Multiline_ field gets a new line.
![screenshot_20180918-075645](https://user-images.githubusercontent.com/1652835/45667337-11158680-bb19-11e8-8fe3-decad5d20c97.jpg)

**Comment by m-kuhn** [comment]
Thanks.

Let's see if @Emic37 can come up with more test results and insights. Might be also a virtual keyboard issue like https://github.com/opengisch/QField/issues/289 .

**Comment by Emic37** [comment]
I only use a Samsung Galaxy S7 with the Gboard keyboard. 
I tried with default samsung keyboard but I encountered the same problem and filled multiline fields on my computer are always displayed with only one line.
So, I tried swiftkey keyboard. Return button is displayed but it allows to validate entry and not to create a new line.

**Comment by Emic37** [comment]
@m-kuhn Any news about this bug ?

**Comment by m-kuhn** [comment]
What QGIS Version are you using?

**Comment by Emic37** [comment]
I used new Qgis `3.4` version. Now I use the last Qgis LTR version `3.4.5` but my project has been created with previous Qgis LTR version `2.18`.

**Comment by m-kuhn** [comment]
Can you open the project in QGIS 3.4, check that the configuration is correct and save the project and try again the newly saved project in QGIS?

**Comment by Emic37** [comment]
I checked the configuration but no problem. Qgis displays a multiline field. 
So I tried to disable multiline, save my project, open again this newly project, enable again multiline and save again project. It's working ! 

But now I encountered the same bug which @nicpitsch describe [here](https://github.com/opengisch/QField/issues/368).
