### ISSUE TITLE
For some reason this text string does not allow to save the translation in transifex

### ISSUE THREAD

**Issue by Fertuesta25** [opengisch/QField#3513]
The text string "%n device(s) found" cannot be translated in transifex.

**Comment by nirvn** [comment]
@Fertuesta25 , which language(s)? I'm looking at s few random languages, e.g. French, and can see the string translated.

**Comment by Fertuesta25** [comment]
@nirvn It is from the Spanish language

**Comment by nirvn** [comment]
@Fertuesta25 , what I'm seeing here is this:
![image](https://user-images.githubusercontent.com/1728657/198889531-2939184a-da39-4e35-a140-44c063a62b38.png)

Two identical English strings, one translated into Spanish while the other isn't. Can you elaborate on the problem / why it won't let you translate?
