### ISSUE TITLE
Lock option seems to not work properly

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3534]
Hello, 

I just tried the option "lock screen" which was mentionned in the last pulled request. 

In my situation, I can still zoom/unzoom with the movement using two fingers, which then allow me to select features. The features cannot be open.
The window display a list of features but it act like I'm still on the map canvas. 

Then when I go back to the map canvas using "<" button, the unlock option disapeared. 

Here a video:

**Comment by nirvn** [comment]
@Ipickedausername , thanks for testing this out -- APKs in this PR (https://github.com/opengisch/QField/pull/3536) should fix your issue.
