### ISSUE TITLE
Not save new variables on QField from 0.11.X  version 

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#354]
Entering a new variable on qfield does not work. When a program restarts, the variable does not remain in the list of variables. This is evident with all versions of 0.11.x.
With 0.10.13 it works great.

Work around:
1. Fresh install 0.10.13 (before removing Qfield from device)
2. Open QField.
2. Enter a new variable.
3. Save.
4. Quit the program.
5. Update qfield 0.11.4 from Google plystore or from here https://github.com/opengisch/QField/releases/download/release-0.11.4/qfield-release-0.11.4-armv7.apk

Only in this case, the new variable remains in the newer version of 0.11.x, but does not allow it to be edited. Fixed, the old variable still remains.

I add a sample project 
[null.zip](https://github.com/opengisch/QField/files/2343223/null.zip)
The variable "nickname" must enter the value in the "name" field.

Tested with various devices (Samsung, Lenovo, Blackview, Sony) and on different Android (5.x, 6, 7.1)

**Comment by m-kuhn** [comment]
@signedav is this related to the new widget?

**Comment by signedav** [comment]
I'll have to check that...

**Comment by signedav** [comment]
My bad. Should be fixed with #355.
