### ISSUE TITLE
iOS 16.1 update makes application quit as soon as it opens.

### ISSUE THREAD

**Issue by CSTEZCAN** [opengisch/QField#3545]
### Describe the issue
I believe version check issue causing application to quit on iOS 16.1 - iPhone SE 2022.
I have recently updated my old iPhone 7 from iOS 14 to 15.7.1 and it didn't break anything. Both devices are connected to same iCloud account.
Maybe isolated issue but I also deleted QGIS folder from my phone as well as apple cloud - nothing changed.

### Reproduction steps
1. [Go to 'update your iOS to 16.1']
2. [Click on 'QFIELD']
3. [You can't scroll on anything 'it quits']

### Expected behavior
[app to behave normally]

### Observed behavior
[application will quit as soon as it launches, Q logo appears and crashes.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]
Behaviour on 7 2016 iOS 15.7.1
![7](https://user-images.githubusercontent.com/33690601/198899843-9a874711-33e6-45f9-9a2c-69ecd1f3de64.gif)

Behaviour on SE 2022 iOS 16.1
![se](https://user-images.githubusercontent.com/33690601/198899848-7ff50098-b097-42f9-b074-c5f7acec7766.gif)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Mobile (please complete the following information)
 - Device: [iPhone SE 2022]
 - OS: [iOS 16.1]
 - QField version: [screen flashes fast, can't reach that section]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
Likely this crash on sentry: https://sentry.io/organizations/opengisch/issues/3502297057/?project=6119013&query=is%3Aunresolved&referrer=issue-stream&sort=user&statsPeriod=14d -- it's the top one crash affecting QField users across all platforms in the last 24 hours.

**Comment by nirvn** [comment]
@CSTEZCAN , we released QField 2.4.5 on the app store with a fix to this crasher. Thanks for the report.
