### ISSUE TITLE
Option to disable +/- buttons in range widget

### ISSUE THREAD

**Issue by soester** [opengisch/QField#3556]
### Describe the issue
While scrolling through forms with lots of range widgets with lots of +/- buttons these buttons are often accidentally pressed.
Actually, this process is currently the main source of error in our field data collection.

I think https://github.com/opengisch/QField/pull/3537 would already greatly reduce the impact of this problem.

Usually we will enter values between 0 and 100 or 0 and 10' 000 into these range-widget fields. If one doesn't enter the values 0 or 1 it is always more efficient to use the number pad to enter a value:
to enter the value 4 
- you have to tap 4 times '+'  OR
- tap on the form-field and the number '4' (only two taps). 

For these cases the +/- buttons really have no value and it should be possible to deactivate them.

### Reproduction steps
1. Have a form with lets say 10 fields with range widgets.
2. Scroll down to enter a value in field n 8.
3. accidentally press one of the 20 +/- buttons.

https://user-images.githubusercontent.com/28543978/199477520-e5242fdb-c350-4b3e-95cc-db6234ee19a8.mp4

### Expected behavior
Add an option to (globally) deactivate +/- buttons in forms in Qfield itself or while setting up a form/project in QGIS. 

### Mobile (please complete the following information)
 - Device: Fairphone 3 and Samsung TAB Active 3
 - OS: Android 
 - QField version: From 1.1  to https://github.com/opengisch/QField/pull/3510 tested

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Since +/- buttons are introduced (1.0?)
* Problem can be reliably reproduced, doesn't happen randomly: [Yes] probably happens more often if you have thicker fingers
* Problem happens with all files and projects, not only some files or projects: [Yes] probably happens more often if you have thicker fingers

**Comment by nirvn** [comment]
@soester , you can try APKs here, I think things should be OK: https://github.com/opengisch/QField/pull/3558

**Comment by soester** [comment]
@nirvn thanks for the very quick fix! Tested and works much better!

**Comment by nirvn** [comment]
@soester , great.
