### ISSUE TITLE
Having a scrollbar in forms and feature lists

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3557]
Hello,
To complement the proposition here: 

https://github.com/opengisch/QField/issues/3556#issue-1432980397

May we imagine having a scrollbar on the right edge of the screen?

This scrollbar could be used for the forms longer than the size of the screen and also in the feature list. 

To go further, in the feature lists, some options like "search", "A-Z classification", "go to the top" or "go to the end" could also be very useful. 

Thank you!

**Comment by nirvn** [comment]
@Ipickedausername , a scroll bar is not visible when you scroll the feature form (check APKs here: https://github.com/opengisch/QField/pull/3558)
