### ISSUE TITLE
problem with the constraints.  enhancement

### ISSUE THREAD

**Issue by RAFALCO** [opengisch/QField#358]
some constraints, not all, are misinterpreted in qfield. even by rewriting them in another way.
in qgis 3.2.2 they work.
See attached file.
[CONSTRAINT ERROR.pdf](https://github.com/opengisch/QField/files/2357616/CONSTRAINT.ERROR.pdf)

### Expected behavior:

the same reaction in qfield as in qgis 3.2.2

**QField version:** [0.11.5]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes/No] it depends on the constraint.

**Comment by m-kuhn** [comment]
This looks like a complicated case, can you contact our support at info at opengis dot ch.

**Comment by signedav** [comment]
Hi there
Is there any update on that? Can we close it?

**Comment by signedav** [comment]
Since I did not received a feedback I close this issue.
Feel free to reopen it, if it's still pending. Thanks :+1:
