### ISSUE TITLE
Add no sleep button

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField#36]

**Comment by m-kuhn** [comment]
What is the reason for this?

Our principle is [KISS](https://en.wikipedia.org/wiki/KISS_principle) so we should be careful with adding new buttons. Better to properly state the problem first and find an appropriate solution.

**Comment by sem-geologist** [comment]
in android there is this 'Stay Alive!' app which allows to do exactly that.

**Comment by m-kuhn** [comment]
I agree, this should be delegated to the operating system / external tools.
Unless we find some other parameters to bind the "keep awake" to (tracking and regularly capture coordinates might require this in the future)
