### ISSUE TITLE
Bug with dates and default values

### ISSUE THREAD

**Issue by gnerred** [opengisch/QField#360]
When defining a field as date, QField automatically sets a default value after having entered a first value in the date field. Reproduced on last vers 0.11.6 and also on old versions 0.10. To reproduce : 

1°/ Open attached project on QField 
2°/ Create a new feature and enter a "date_mesure" -> checkbox beside field is automatically checked, but we do not want it 
3°/ Save the feature
4°/ Create a second new feature -> "date_mesure" already contains a date, but we do not want it (field is not defined in QGIS as "not null") and it is not possible to set the "date_mesure" to null

This issue is really annoying when dealing with dates in a production environnement...

[test.zip](https://github.com/opengisch/QField/files/2370238/test.zip)

**Comment by m-kuhn** [comment]
Might be the same issue as solved with this approach:

https://github.com/opengisch/QField/blob/master/src/qml/editorwidgets/CheckBox.qml#L23-L26

**Comment by saemiw** [comment]
Might be the same issue as described here https://github.com/opengisch/QField/issues/369. @gnerred are you sure the date is actually saved into the file when you haven't chosen it manually (i.e. when it was chosen automatically).

**Comment by gnerred** [comment]
@saemiw you are write, the date is only shown in the interface, but not saved in database. Sorry for that, I thought it was saved without controlling it.
