### ISSUE TITLE
iOS cannot create a DCIM Folder when "use native camera" option is enabled

### ISSUE THREAD

**Issue by Meykaefer** [opengisch/QField#3602]
Thank you for the great work! I am thrilled that QField made it to iOS, and I started to use it during its Beta testing phase with Testflight. I discovered this "bug"? back then and assumed it was connected to a sandbox environment imposed by the Testflight app. But now, with its official release on iOS and the ability to transfer projects via cable, I started to give it some extensive testing.

### Describe the issue
When importing a new project with a photo layer and no DCIM folder while the "use native camera" option is enabled, QField cannot save the photo to the project and will display an empty photo attachment widget. But if the "use native camera" option is disabled, it will take a photo, save and display it in the photo widget. Furthermore, after taking a photo with the "use native camera" disabled and enabling it again, photos can be taken, saved and displayed in the photo widget with the "use native camera" option without complications.

### Reproduction steps
1. Create a new project containing a photo layer without a DCIM folder. Upload it to an iOS device and try to take a photo while the "use native camera" option is enabled. No photo will be attached/ saved and displayed.
2. Now go to settings, disable the "use native camera" option, retake a photo and save the photo (feature can be saved or discarded).
3. Go back into the settings, enable the "use native camera" option, and take photos. Photos will save and display normally.

### Expected behavior
The expected behaviour is to take, save and view photos with an enabled "use native camera" option and an automatic DCIM folder creation if missing.

### Observed behavior
No DCIM folder or path is created with the "use native camera" option enabled. Disabling it, taking and saving photos with the minimal in-app camera script will create the DCIM folder and paths and allow the native camera to use it afterwards.

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.28
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: iPhone XR, iPad 10.2
 - OS: 15.7
 - QField version: 2.4.5 

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@Meykaefer , @she-weeds , it'll be fixed in the next point release. Thanks for reporting.
