### ISSUE TITLE
Can't load jpg datasets on iOS

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#3611]
### Describe the issue
Georeferenced rasters with a world file (e.g. .jpg with .jgw) fail to load in the project. 
GeoTIFFs are not affected.

### Reproduction steps
1. Open a project that has a raster with a world file.
2. Error message appears showing that rasters failed to load

### Expected behavior
Rasters should load

### Observed behavior
Rasters do not load

### Screenshots and GIFs
Example of error message
![Screenshot 2022-11-10 at 9 18 00 am](https://user-images.githubusercontent.com/41975056/200957343-1717218e-3f5e-4073-9512-9bcf84e148ee.png)

Files are clearly in the folder
![Screenshot 2022-11-10 at 9 18 38 am](https://user-images.githubusercontent.com/41975056/200957353-0be42a5d-cd17-40b6-acf3-c1389e440335.png)

### Mobile (please complete the following information)
 - Device: iPhone 8
 - OS: iOS 15.7.1
 - QField version: 2.4.5 57ac82 , 2.5.2 e58dc2

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes - rasters that loaded fine in 2.4.4 no longer do
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes on iOS - I have tried multiple projects, renaming the layer/raster/folder. No problem on Android with QField ver 2.5.0

I know a .dmg has been released for 2.5.0 via github but the latest version still available on the app store is 2.4.5

**Comment by nirvn** [comment]
@she-weeds , how did you copy those files onto your device? Are they located in QField's documents folder? If you could attach a screen cast it'd be helpful.

**Comment by she-weeds** [comment]
I used iTunes' File Sharing function with a data cable to transfer the entire project folder over into the QField root folder (so same level as Imported Datasets and Imported Projects).

Sorry it might take me a bit of time to get a screen cast as I'd have to remove some other folders with identifying information, but if you need one I'll organise one later.

It worked fine in 2.4.4 using the same method, although I think I upgraded my iOS by one point release since i last tried that (Have not upgraded to 16 yet).

**Comment by nirvn** [comment]
@she-weeds , very odd; are you using custom projection grids by any chance? That's really the only thing that changed between 2.4.4 and 2.4.5 on iOS.

Also, 2.5.1 will be rolling out on iOS over the next 7 days, you should keep an eye on that.

P.S., could you attach this project here or send a link to me privately at mathieu@opengis.ch ? Thanks.

**Comment by she-weeds** [comment]
@nirvn Nothing fancy at all - it's a mix of EPSG 28355 and 7855 but I had the same issue with a separate project that was only 28355. Attached is a sample very basic project with just a shapefile and aerial, still had the same error

[iOS Test aerial project.zip](https://github.com/opengisch/QField/files/9977107/iOS.Test.aerial.project.zip)

**Comment by nirvn** [comment]
@she-weeds , can you try and open the individual jpg? I.e., when you click on the open local dataset button, instead of picking the project file, go in /_data/ and pick a jpg.

**Comment by she-weeds** [comment]
I get no error message but there is nothing loaded either on the screen or the layers list. The scalebar at the bottom says 'Unknown'.

Compared to a GeoTIFF where it loads properly in relation to my current location and has the correct scalebar at the bottom, and appears in the layers list as well.

**Comment by she-weeds** [comment]
Just as an update, still having the same issue in 2.5.2

**Comment by nirvn** [comment]
@she-weeds , I'll try to get my hands on an iOS device to do some testing later this week. It's odd QField reads the .qgs file as well as the images but somehow would not be able to access the sidecar world files. As Yoda would say: mysterious this issue is.

**Comment by she-weeds** [comment]
@nirvn Thanks so much. I have updated to iOS 16 on the iPhone 8 and still the same issue, also tried on an older iPad and same.

I have also run into an issue with raster .gpkg (e.g. the kind generated by the Base Layers function in QFieldSync) incompletely loading on iOS but I will raise that as a separate issue when I have time later, I'm just mentioning it now in case there is some esoteric gdal link or something...

**Comment by she-weeds** [comment]
Still having the same issue on 2.5.5 unfortunately.

**Comment by she-weeds** [comment]
Still having the same issue in 2.6.0 - sorry to be a pest, just hoping this issue does get looked at eventually.

**Comment by nirvn** [comment]
@she-weeds , did some more looking into this issue. I could replicate the missing layer in your test project, thanks.

Turns out what I'm seeing here is a failure to open _JPG_ rasters. A PNG raster with a PNW world file works perfectly fine for me. Can you confirm on your end that you are witnessing the same thing?

**Comment by she-weeds** [comment]
@nirvn thank you so much for investigating and apologies for the late reply - can confirm that png/pgw works on the latest release (2.6.3 aaa93d), .jpg/.jgw still doesn't. I tried renaming the .jgw to .wld, raster still loaded in the correct location in QGIS but got the same error message as above in QField.

.png/.pgw is a great backup for now so that is a good find but would be great to figure out how to get .jpg to work (and mbtiles as mentioned in the linked issue). Thank you.

**Comment by she-weeds** [comment]
Hi team, sorry to sound like that Bernie Sanders meme. Love the new features in the latest 2.7 release but unfortunately have tested that jpg rasters are still an issue on iOS devices.

**Comment by nirvn** [comment]
@she-weeds , yeah, that's still in the known issue bag unfortunately.

May I ask you to check whether the sample bees project shipped with QField has photos showing up in the feature form of apiary points? Proof of life through screenshot most appreciated.

**Comment by she-weeds** [comment]
Thanks @nirvn for confirming it's still on the list! 

Yes, the photos show up in the feature form for apiary points. But jpgs in the feature form haven't been an issue ever since I started testing QField on iOS, fwiw (aside from the small DCIM folder bug). It's jpgs as a layer that won't load...

Short video:

https://user-images.githubusercontent.com/41975056/225239068-d57f3c7f-9966-4662-aef7-47070a6c0b9e.MP4

**Comment by lp-dj** [comment]
May I join the game? :-P

I wish I had discovered this thread here earlier. Spent a few hours over the last few months getting my projects up and running on iOS as well. Finally I also came to the conclusion that it must be the JPEG format.

I would like to add two additions to this thread:

1) The problem still exists in QField 2.7.2.
2) As a somewhat more memory-saving variant than png, I can also recommend WEBP as a format that runs on all platforms.* 

*Unfortunately, the [COGs described here](https://docs.qfield.org/reference/data-format/#use-cog-cloud-optimized-geotiff) do not work for me on iOS with either JPEG or WEBP compression. But in a geopackage - apart from a few manageable problems with the transparency channel - it works very well. I prefer geopackages anyway because of the more compact data storage with multiple layers.

**Comment by she-weeds** [comment]
Just chiming in again to say it's still unresolved as of 2.8.1 ...

**Comment by she-weeds** [comment]
Looking forward to testing this out when it's rolled into the next release! (Have tested 2.8.2 but it's not in that yet). How exciting - thank you all so much, devs, for tackling this thorny issue.

**Comment by she-weeds** [comment]
(also not ready in 2.8.3 for anyone following along...)

**Comment by nirvn** [comment]
@she-weeds , that's correct, it'll be fixed in QField's next big version, coming soon.

**Comment by she-weeds** [comment]
Hey @nirvn, congrats on the big release of QField 3! I'm eager to test this out on my iOS device but I can't get AltStore to work in order to sideload the .ipa file, any idea when it might be available on the App Store? It still shows only 2.8.3. I figure it takes a while to get approved
