### ISSUE TITLE
WMS-Layer Error on Android 7.1.1

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/QField#362]
WMS-Layer Error on Android 7.1.1
Maybe relatet to Issue #206 

### Reproduction Steps:

1. WMS-Layer from geodienste.ch in offline Project
2. Opening Project
3. Error

### Expected behavior:

Displaying the WMS Layer.
Which is happening on our old Tablets (Samsung Tab Active 1, Android 4.4).

### Observed behavior:

SSL-Error on our new Tablet (Samsung Tab Active 2, Android 7.1.1) with the same project file.

Log:
**WMS**
Download of capabilities failded: Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten.

**QField version:** [0.11.6 - Lucendro]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes, on other Android 7 devices ]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
Ist das bei der neusten Version gelöst?

**Comment by soester** [comment]
seems to work with Qfield 1.0.3

**Comment by m-kuhn** [comment]
thanks for the feedback
