### ISSUE TITLE
Build qfield for android using docker

### ISSUE THREAD

**Issue by luckystar360** [opengisch/QField#3621]
![image](https://user-images.githubusercontent.com/57883393/201460984-8188f6fa-242e-40f9-9eb2-914ae044780b.png)

Hi, I'm a newbie.
Currently, I'm building qfiled for Android using docker, but I'm getting an error message. Can you tell me what to do next.
Thank you.

**Comment by m-kuhn** [comment]
This looks like a problem with windows paths inside docker.
The easiest way is likely to run this in a wsl.

**Comment by luckystar360** [comment]
hi @m-kuhn,
Thank you very much, I have solved it.
