### ISSUE TITLE
Huge performance issue since last update

### ISSUE THREAD

**Issue by OBVYamaska** [opengisch/QField#3628]
### Describe the issue
Quite simply, my ongoing projects all became extremely slow two days ago. I tried various things (like flushing everything and lightening my project), before realizing a patch came through recently. I reinstalled 2.4.5, and everything started to act normally again.

More details: the issue is mainly seen when I open a Relation (a sub-form), and echos to every sub-forms from there.
Things end up opening, but usually take about 1-5min, while on 2.4.5, it is instantaneous.

I found a way to prevent my apps to auto-update, but I would rather use the latest QField version :) Happy to help pinpoint the issue in any way I can, although I don't know where to start?

P.S: The issue happens in all of my project who have a relation (sub-form).

### Mobile (please complete the following information)
 - Device: Samsung Galaxy A52, reproduced on a brand new A53
 - OS: Android 12
 - QField version: 2.5.1, didn't test where the bug started, although it is not present on 2.4.5

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by Ipickedausername** [comment]
Hello, 

I tried two projects with relations on the two versions and I didn't have any slowing issue. You will probably have to share a test project to make it easier for the developers to find the issue.

**Comment by nirvn** [comment]
@OBVYamaska , please try the APK in this PR (https://github.com/opengisch/QField/pull/3629), I am hopeful it'll improve things.

**Comment by OBVYamaska** [comment]
> @OBVYamaska , please try the APK in this PR (#3629), I am hopeful it'll improve things.

Yep, that did it :)
Awesome fast work, thanks!
