### ISSUE TITLE
Crosshair position upon change of tablet orientation

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#364]
If you are in digitizing mode and switch the way you hold the tablet from landscape to portrait (or vice versa) the crosshair jumps around in a way that is not usefull. It does neither stay at the current position (expected behaviour) nor does it centre in the middle of the screen.

**QField version:** [0.11.6]

## Additional information:
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by signedav** [comment]
Yes. I can confirm that. It's still an issue on the current version.

**Comment by nirvn** [comment]
Fixed a long time ago, not sure why I didn't close this issue then.
