### ISSUE TITLE
Layer panel lag

### ISSUE THREAD

**Issue by olegzhelezn** [opengisch/QField#3640]
### Describe the issue
Since QField 2.3.4 (possibly earlier), the layer panel is opening for an extended time lag (>1 second). Additionally, there is a similar problem with some long lists in the attributes. The behavior is observed on Redmi Note 10, but has not been observed on a diffrernt Android device (only one additional device checked).

### Screenshots and GIFs
List in the attributes:
![list](https://user-images.githubusercontent.com/39202056/202024199-8fa2ed4f-a075-49ae-a3be-639e6b5cfa31.gif)
Layers:
![layers](https://user-images.githubusercontent.com/39202056/202024424-542822aa-25c5-425e-89fc-2eb13cfceefc.gif)

### Mobile (please complete the following information)
 - Device: Redmi Note 10
 - OS: Android 11
 - QField version: 2.5.1 (b906ac)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@olegzhelezn , could you share your project file here please? Without it, it's near impossible to debug your situation.

For more comments:
- Please try against QField 2.5.4 (released ~48 hours ago)
- Does the 1sec lag to open the side drawer also occurs with the sample bees farming project?

**Comment by olegzhelezn** [comment]
@nirvn, the same happens after an update to the latest version, **the lag occurs in the bees farming project as well**. I am attaching a sample project where the attribute list takes time to load.
[Lag_check.zip](https://github.com/opengisch/QField/files/10077913/Lag_check.zip)

**Comment by nirvn** [comment]
@olegzhelezn , hm, I can't replicate the lag here:


https://user-images.githubusercontent.com/1728657/203668949-d85a6a8b-9f6e-4c38-b8b0-8b8b9015c0b7.mp4


Are you able to create a logcat of your device running QField?

**Comment by olegzhelezn** [comment]
@nirvn, indeed...
Here is the log:
[logcat_11-24-2022_02-17-35.txt](https://github.com/opengisch/QField/files/10080101/logcat_11-24-2022_02-17-35.txt)

**Comment by olegzhelezn** [comment]
The issue seems to be fixed in the latest release!
