### ISSUE TITLE
multiline text field visually corrupted when feature is open for editing

### ISSUE THREAD

**Issue by AveryAndrews** [opengisch/QField#3643]
### Describe the issue
multiline text field visually corrupted when feature is open for editing

### Reproduction steps
1. Click on an editable feature on the map in my little QField project; multiline tex field looks good.
2. Tap on the A-with-a-pen-as-superscript, and becomes corrupted with bold, badly superposed text
3. Hit the checkmark on the left to accept changes, and it looks good again

### Expected behavior
Does not get visually corrupted

### Observed behavior
display of multiline is corrupted when editing enabled

### Screenshots and GIFs
one screenshot for normal state, another for corrupted

### Mobile Device:
   Pixel 6 Pro; Android 13

### Desktop (please complete the following information)
 - OS: W10
 - QGIS Version: 3.26,2
 - QFieldSync Version: 4.2.0
![corrupted](https://user-images.githubusercontent.com/70241033/202065586-0eefc4fd-b19c-4ddd-87d5-0ba7bbee4a48.png)
![normal](https://user-images.githubusercontent.com/70241033/202065599-afd4033b-a8b2-4db3-8d5e-d1dbb08761ea.png)

**Comment by nirvn** [comment]
@AveryAndrews , thanks for the reporting -- a fix is available in this PR (https://github.com/opengisch/QField/pull/3644), feel invited to test the APK in there and report back. It'll be fixed in the next QField point release.

Thanks for reporting this issue; happy field mapping!
