### ISSUE TITLE
Cannot discover bluetooth devices on 2.5

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#3647]
### Describe the issue

When scanning for bluetooth devices, an error appears

> Scanning failed: Classic discovery cannot be started

![90e2560a-9830-4c57-8cce-d758146be846](https://user-images.githubusercontent.com/588407/202189865-72ddb948-abb0-4da8-b9cc-f955377d7636.jpg)

affected device:
galaxy s21 ultra android 12

works fine on 2.4.5

contact @mbernasocchi for more details

**Comment by mbernasocchi** [comment]
fixed by #3648

**Comment by Marwe** [comment]
The fix was needed and works for Samsung Galaxy Tab Active3 devices here.
Currently Android 12 and Kernel 4.9.191-24871673.
System Upgrade just came in (2022-11-01), patch still working fine.
Thank you for the quick fix!
