### ISSUE TITLE
.qgz-Format not supported yet

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#365]
QGIS-Projects saved with QGIS 3.2 in the format .qgz are not supported by QField yet. Upon opening such a file Qfield crashes.

### Reproduction Steps:

1. copy a qgz-File and the data to the table
2. find it in the file system and open
3. crash

**QField version:** [Enter 0.11.6]

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by m-kuhn** [comment]
I think https://github.com/opengisch/QField/pull/250 should solve this, if you have the possibility to test, that would be great.

**Comment by signedav** [comment]
I think this is solved. Otherwise feel free to reopen @saemiw

**Comment by saemiw** [comment]
@signedav I tested with _qfield-v1.2.0-armv7-Android5.apk_ and _qfield-v1.2.0-armv7.apk_. On the later it works perfectly. On the Android7 it is not working. QField returns the following Error: 
`QgsZipUtils: Error opening zip archive '...path to qgz file' `

I did not check with later releases. For us it's not critical as we just use the .qgs-Format.

**Comment by signedav** [comment]
Thanks for reporting. Would be great if you could test on the Android 7 device with the 1.3. version as well just to be sure. (I don't have an Android 7 currently)

**Comment by saemiw** [comment]
shit...sorry, I wrote it wrong...on Android7 it works. 

> On the Android**7** it is not working 

should be 

> On the Android**5** it is not working

**Comment by m-kuhn** [comment]
@saemiw the Android5 build was based on an old osgeo4a codebase up to 1 month ago. Which version did you test? We have good reasons to assume it's fixed with release 1.2 (or 1.3).

**Comment by saemiw** [comment]
I tested with v1.2.0...I'll check with 1.3

**Comment by saemiw** [comment]
@signedav and @m-kuhn I lack a apk for 1.3.0 and Android5. Is there one or do I oversee it? For 1.2.0 I tested with android 5.1.1 and its not working with qgz... (I tried on two different devices).

**Comment by m-kuhn** [comment]
@saemiw can you just take the "standard" apk, there is no longer an Android 5 apk (which is also the reason why the bug should be fixed ;) )

**Comment by saemiw** [comment]
you were right, qgz works with 1.3.0 on Android5. This issue deserved to remain closed! Thanks guys.
