### ISSUE TITLE
Camera crashes when when rotating from portrait to landscape

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#366]
I have a field that stores picture paths taken with the "Attachment"-Widget. Everything works fine, but when I turn the tablet from portrait to landscape (only in this order!) while the camera widget is open, I am thrown out of the camera widget. 

I used QGIS 3.2 to set up the project.

### Reproduction Steps:
here a crappy video showing the behaviour
https://youtu.be/aqmSZ9BWNbk

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Comment by signedav** [comment]
I cannot reproduce this. Is this still happening?
Thanks for your feedback.

**Comment by signedav** [comment]
Since I did not received a feedback I close this issue.
Feel free to reopen it, if it's still pending. Thanks :+1:
