### ISSUE TITLE
HTMLWidget: hrefs are not rendered // Adding `geo:` Links

### ISSUE THREAD

**Issue by miili** [opengisch/QField#3661]
### Describe the issue
Sometimes people need turn-by-turn navigation to a feature. A simple solution can be `geo:` URIs, kicking the user to Google Maps/AppleMaps/OSMAnd or whatever.

How can this be archived?

I tried using a HTML widget:

```html
<script>
document.write(Number(expression.evaluate("$y")).toFixed(5) + " N ");
document.write(Number(expression.evaluate("$x")).toFixed(5) + " E ");
document.write(
  "<a href='geo:"
  + expression.evaluate("$y") + "," + expression.evaluate("$x")
  + ";pname=" +expression.evaluate("fid")
  + "'>Navigate</a>");
</script>
```

But it does not render. What am I doing wrong?

### Expected behavior
Rendered HTML with `a` element.

### Observed behavior
Empty widget. Nothing is rendered

### Mobile (please complete the following information)
 - Device: Pixel
 - OS: Android 11
 - QField version: 2.5.2

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: dont know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

See `Eifel-LargeN/Maintance`

**Comment by nirvn** [comment]
@miili ,the APK in this PR (https://github.com/opengisch/QField/pull/3662) should fix the issue for you. Thanks for reporting, happy field mapping!

**Comment by miili** [comment]
Excellent, thank you! @nirvn Can you share the code the QML? I would like to add it to the docs as an example.

**Comment by miili** [comment]
> Excellent, thank you! @nirvn Can you share the code the QML? I would like to add it to the docs as an example.

Got it!

**Comment by nirvn** [comment]
@miili , glad you got it, make sure to send your thanks to @zzzef :)
