### ISSUE TITLE
Problem in selecting photos

### ISSUE THREAD

**Issue by AveryAndrews** [opengisch/QField#3663]
### Describe the issue
I can't find any way to select a photo and have it appear in a feature which superficially appears to be set up properly

### Reproduction steps
1. Open feature for editing (screenshot "Step 1")
2. Click on photo selection from file icon
3. Select desired photo by long press (screenshot "Step 3-4")
4. Hit 'select' in upper right hand corner of screen
5. App returns to feature screen without adding the photo (screenshot same as Step 1)

### Expected behavior
At step 5, I would expect to see the photo on the feature screen (I have sometimes seen this)

### Observed behavior
No change to feature screen

### Screenshots and GIFs

![Step_1 1](https://user-images.githubusercontent.com/70241033/202833757-328d8229-0178-4ece-a70a-c42f812ecbf5.png)
![Step_3-4 1](https://user-images.githubusercontent.com/70241033/202833771-95e722fd-e0bf-4a33-842f-542f7efc20c6.png)

### Desktop (please complete the following information)
 - OS: W10
 - QGIS 3.26.3
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: Pixel 6 pro
 - OS: Android 13
 - QField version: 2.4.3 (2fe880 v2.5.3)
 
### Additional information
I have sometimes noticed this problem with earlier versions of the project, not sure what the difference was between times when photo addition worked, and when it didn't

I don't know whether this problem is a bug (interface action not working), a result of misconfiguration by myself, out of date documentation (of which there is a lot, for QGIS), or my own inability to correctly read up to date documentation.

**Comment by nirvn** [comment]
@AveryAndrews , can you try with the bees sample demo and tell us whether it works there?

**Comment by AveryAndrews** [comment]
Well, embarassingly for me, that solved the problem .. there was no image viewer selected in mine.
