### ISSUE TITLE
How to build setup file in windows platform

### ISSUE THREAD

**Issue by luckystar360** [opengisch/QField#3672]
Hi all,
I was a newbie. I have successfully built the version for Android.
Now, I am building for windows platform. But I don't know how to export the setup file. Can you help me?

Thank you advanced.

**Comment by m-kuhn** [comment]
All that's available can be seen in https://github.com/opengisch/QField/blob/master/.github/workflows/windows.yml

**Comment by luckystar360** [comment]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/57883393/203827950-2b72e467-a8d4-403a-9791-f67491128865.png">
Can you help me how to fix this error?
Thank you,
