### ISSUE TITLE
Not possible to search within WFS-Service Layer

### ISSUE THREAD

**Issue by Spacedatists** [opengisch/QField#3674]
Hello,
How do I make my WFS-Service searchable? I have two layers in my project. A WFS-Service and a vector layer "adresses" inside a gpkg.
I set both "searchable" via the project properties, but QFIELD is returning only information from the adress-layer when I do sthe search. Am I missing something?

![grafik](https://user-images.githubusercontent.com/82571263/203278326-071e53a3-81ae-4cd6-84a3-16edcebf78e0.png)

Using
QGIS 3.22.10
QFIELDSync 4.2.0
QFIELD 2.5.4
Samsung Galaxy S8
Android 9

**Comment by nirvn** [comment]
I did a quick test here and could successfully search within a WFS layer. 

Feel free to include a test project here so devs can replicate. Also make sure searching in your layer actually works in QGIS.
