### ISSUE TITLE
Tiny font for Multiline Text Edit Widget Type

### ISSUE THREAD

**Issue by nicpitsch** [opengisch/QField#368]
The font size for the Widget Type _Text Edit, Multiline_ is tiny and much smaller than the other Widget Types.

### Reproduction Steps:

1. Open the Attributes Form.
2. Set the Widget Type for a String Field to _Text Edit, Multiline_.
3. Add some text to that field and look at it within QField.

### Expected behavior:

Same font size as for the _Text Edit_ Widget Type (without _Multiline_ checked).

### Observed behavior:

Look at the entry description.

### Screenshots and GIFs
![screenshot_20180918-055924](https://user-images.githubusercontent.com/1652835/45664365-baee1680-bb0b-11e8-84e1-9ff3302dd69f.jpg)

![2018-09-18_06-15-06](https://user-images.githubusercontent.com/1652835/45664103-71e99280-bb0a-11e8-8a4c-2ac6514007d2.jpg)

**QField version:** 0.11.6

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

Naive suggestion: could this issue be solved within _src/qml/editorwidgets/TextEdit.qml_ by adding a `font.pointSize: 14` to the TextArea property at line 53? (Unfortunately I was not able to set up a build environment with Docker or OSGeo4A to try it myself).

**Comment by m-kuhn** [comment]
It's probably a bit more complex unfortunately, many of these widgets need to be corrected for exactly this kind of hidpi issue
