### ISSUE TITLE
Hidden fields QFIELD 2.5.4

### ISSUE THREAD

**Issue by CACG1022** [opengisch/QField#3683]
Hello, I want to report the following bug. What happens is that I have hidden fields that are dependent on other fields and those in turn have fields that are required to be filled. When I go to fill out the form, it doesn't let me save because I have to fill out these fields that are hidden. In previous versions this error did not occur because if the field was hidden it did not ask me to fill in the field. The version I'm using is QFIELD 2.5.4

**Comment by nirvn** [comment]
Could you attach a sample project please?

**Comment by nirvn** [comment]
@CACG1022 , please try the APK in this PR (https://github.com/opengisch/QField/pull/3686), your issue should be fixed.
