### ISSUE TITLE
QField project loads forever when featrue count is enabled

### ISSUE THREAD

**Issue by bladnor** [opengisch/QField#3702]
### Describe the issue
We have a QGIS project with approx. 160 layers. The data backend is a postgis database. When we try to open this project in QFiled the project loading never comes to an end when feature count is enabled.
When feature count is disabled all works as expected.

### Reproduction steps
Compare QField project loading time with enabled and disabled feature cont.

### Expected behavior
The QField project loading should be successfull even with enabled feature count with layer number >160

### Observed behavior
When we try to open this project in QFiled the project loading never comes to an end when feature count is enabled.

### Desktop (please complete the following information)
 - OS: Linux
 - QGIS Version  3.22.0

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab active 3
 - OS: Android all
 - QField version: all versions

**Comment by she-weeds** [comment]
Out of curiosity are any of your layers VIEWs or filtered layers?

**Comment by bladnor** [comment]
No, only db tables no filtered layers.

**Comment by nirvn** [comment]
@bladnor , are things better these days with QField 3.2.0?

**Comment by nirvn** [comment]
@bladnor , PSA on feature count: use it only when really needed, sparsely, and not on large and/or remote datasets. It comes at a high cost in any case
