### ISSUE TITLE
Rotated photos when maximum size is set

### ISSUE THREAD

**Issue by aliasatp** [opengisch/QField#3704]
### Describe the issue
Hi all, when I set decrease in size in qfield sync plugin, my photos are 90° rotated after shot.

### Reproduction steps
1. set 800px width as maximum size
2. take a pitcture
3. saved 90° rotated

### Expected behavior
As in previous (=<2.3) release I expect only resize not rotation

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: window 11
 - QGIS Version 3.28.1
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: Redmi 11
 - OS: Android 11
 - QField version: 2.5.4

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@aliasatp , thanks for the report, this PR fixes your issue (https://github.com/opengisch/QField/pull/3817). Expect it to come to a released version very soon.
