### ISSUE TITLE
Entry of time only (without date)

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#371]
I'd like to only save time into a geopackage. As geopackage only knows date/time format I chose a text as the field type in order to only save time (and not also date). Then I define the attribute form the following way: 
![zeittext](https://user-images.githubusercontent.com/20398621/45941393-42d99200-bfde-11e8-9fb8-d613996b7e4c.PNG)

On QGIS 3.2 I the data entry is presented like this.
![zeittextqgis](https://user-images.githubusercontent.com/20398621/45941395-453bec00-bfde-11e8-8337-32a74ae61da4.PNG)

On QField I am shown an calendar widget upon data entry, which is of course useless for storing time. I would expect something like this as well:
![zeittextqgis](https://user-images.githubusercontent.com/20398621/45941395-453bec00-bfde-11e8-8337-32a74ae61da4.PNG)

**QField version:** [0.11.6]
**QQGIS version:** [3.2]

## Additional information:
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by giedrioks26** [comment]
I have the same problem. I found it unnecessary when it became possible to make a "Default value". This is how I make the date, time and other recordings that are recorded in real time. For example:
` format_date(  now() ,'yyyy-MM-dd')` -> 2018-09-24
` now()` -> 2018-09-24T11:48:50
` format_date(  now() ,'HH:mm')` -> 11:48

Need to enter the last time on your mobile device? Data is collected in real time. Do you have any other cases?

![ekranvaizdis_2018-09-24_11-44-34](https://user-images.githubusercontent.com/6436791/45943550-74a72480-bfef-11e8-8206-fbb655ee0f0d.png)

**Comment by giedrioks26** [comment]
In such cases, I use a column with a number. It's called "days before" or "hours before." The trigger automatically calculates (adds to the date or time) and enters the time value.
Of course this is just my appendix to work around. Maybe it will be useful.
I have been monitoring birds for many years. It's fun to meet here doing the same :)
