### ISSUE TITLE
Qfield 2.5 Fancy Flamingo does not work with Bluetooth NMEA GPS

### ISSUE THREAD

**Issue by fan32111** [opengisch/QField#3710]
Qfield 2.5.x does not work anymore with Bluetooth NMEA GPS
I downgraded to version 2.4.5 and everthing works fine again.

1. Upgrade to Version 2.5.x
2. Connect to NMEA GPS with Bluetooth
3. GPS connects
4. getting not location information

 - Device: Android 12 Galaxy Tab A7 SM-T505 and other Android devices
 - OS: Android 12
 - QField version: 2.5.x

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@fan32111 , there was a known issue with 2.5 and Bluetooth on Android >= 12 which was fixed in 2.5.3. It involves QField requesting an additional permission when you launch the app (it's a requirement from Android). Did you grant that permission? It's called 'nearby devices permission', you can check in your settings, I'm pretty sure it's merely the permission not switched on.

**Comment by fan32111** [comment]
I reinstalled Qfield 2.5.5 and granted all requested permissions, even 'nearby devices permission' (in German: Geräte in der Nähe - Zulassen) 

no success - GPS connects, but I get no location information ..

**Comment by nirvn** [comment]
@fan32111 , OK, then could you include more details on your external GNSS model, as well as possibly a screencast of you enabling the Bluetooth device, going back to the main map and enable positioning information panel? Thanks

**Comment by fan32111** [comment]
Receiver:Device Model:  A60 ProSerial No.:  XXXXXXXXXX Hardware Version:  V1.1BOOT Version:  1.09Firmware Version:  0.22.201118AOS Version:  1.10MCU Version:  4.19Sensor Version:  2.15Battery Power:  84%Power Source:  batteryData Memory:  Internal Storage Total 6.05 GB;  Free 6.02 GB
![nmea](https://user-images.githubusercontent.com/119491519/204774059-35dd60e3-b0ac-4d21-81e2-877e7270a599.jpg)
![1-Screenshot_20221130-113050](https://user-images.githubusercontent.com/119491519/204774304-d2bb1e64-844e-4dc8-a33c-f44b8addd9f3.jpg)
![2-Screenshot_20221130-113121_Settings](https://user-images.githubusercontent.com/119491519/204774310-6b4ca7ba-3385-4c89-99c2-66e0d403f5c3.jpg)
![3-Screenshot_20221130-113134](https://user-images.githubusercontent.com/119491519/204774312-9891bbb2-0683-42e0-bd8f-36175c165346.jpg)
![4-Screenshot_20221130-113451](https://user-images.githubusercontent.com/119491519/204774316-7dd9bdce-59e6-44c2-b0f0-d12f2e3cab02.jpg)

**Comment by nirvn** [comment]
@fan32111 , also, if at all possible, try to give it a try in QGIS 3.28 itself to see if it works there.

**Comment by nirvn** [comment]
@fan32111 , if your desktop computer has a Bluetooth connection, you can try to connect the GNSS device in QGIS via the GPS panel (https://docs.qgis.org/3.22/en/docs/user_manual/working_with_gps/live_GPS_tracking.html).

**Comment by fan32111** [comment]
I downloaded and installed lastest QGIS 3.28.1 on my private laptop (Windows 10). I am able to connect to GNNS device over bluetooth and get location information every second.

By the way - on tablet I have intalled SWMAPS too, and it works fine.

**Comment by fan32111** [comment]
@bettellam
Thank you - now it works - I get position information

**Comment by nirvn** [comment]
@fan32111 , can we close this issue?

**Comment by nirvn** [comment]
FYI QField 2.6 now consumes NMEA without RMC sentence. There indeed was a regression.
