### ISSUE TITLE
2D Objects are created on 3D Layer

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#3714]
### Describe the issue
When a new vertex is created by manually placing it, it is created as a 2D point.
Even if it is placed on a 3D layer.

QField should promote all vertices to 3D (on creation or on save) whenever they are placed on a 3D layer and replace missing values with `NaN`

**Comment by suricactus** [comment]
BTW, there are situations when QField creates geometries in 3d with `NaN` in the third dimension. Source: QFieldCloud had to deal with a bug due to `NaN` values.
