### ISSUE TITLE
Qfield connection problem with external GPS 

### ISSUE THREAD

**Issue by GianlucaAgr** [opengisch/QField#3722]
Hello I wanted to report that for about 3 weeks, when I try to connect my Emlid Reach RS2 external GPS to Qfield with Bluetooth, I get the following error: Positioning error: Unable to find the UUID of the service on the remote host.

Qfield v2.5.6 13f23d is installed on a XIAOMI Redmi Note 10 Pro with Android 12

**Comment by GianlucaAgr** [comment]
> Related #3710 ?

I don't think

**Comment by nirvn** [comment]
@GianlucaAgr , can you give this arm64 APK a try: https://github.com/opengisch/QField/pull/3784#issuecomment-1368376513 , I'm moderately confident it will fix your issue.

You'll notice the device setup / management UI has change quite a lot. Should be straight forward enough though (click on the [ add ] button, scan for your device, et voila).

**Comment by nirvn** [comment]
@GianlucaAgr , QField 2.6 is out and includes a possible fix for your issue. I'm flagging this PR as in need of feedback, hope we'll hear from you soon :)
