### ISSUE TITLE
Problem with uploading photos in DCIM folder created by QField

### ISSUE THREAD

**Issue by AveryAndrews** [opengisch/QField#3736]
### Describe the issue
If a QField project starts with no DCIM folder, but creates one due to user taking a picture, other apps (Autosync & Cx File Explorer) can't access its contents

### Reproduction steps
1. Create a project with the capacity to take pictures but no DCIM folder
2. Export it to QField
3. Take a picture
4. Try to look at the contents of the DCIM folder with Cx File Explorer (after of course getting permission to look at the contents of ch.opengis.qfield), and find that you can't (or try to set up an Autosync upload to cloud, but that is more complex)
5. Delete the DCIM folder and create a new one with Cx File
6. Take another picture
7.  Find that viewing and Autosync upload now works.

### Expected behavior
Contents of folders created by QField ought to be accessible by other apps

### Observed behavior
they aren't

### Desktop (please complete the following information)
 - OS: W10
 - QGIS Version: 3.26.3
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: Pixel 6 Pro
 - OS:  Android 13
 - QField version: 2.5.6 13f23d v2.5.6

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Not as far as I know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: All the ones I've tried (several)

**Comment by nirvn** [comment]
@AveryAndrews , please try the APKs here: https://github.com/opengisch/QField/pull/3818 , it should fix your issue.
