### ISSUE TITLE
Auto-push changes on QFieldCloud + options 

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#3737]
Hello, 

I think it could be useful to have the possibility to set auto-push in the options. 

With the possibility to specify: 
- Every "x" change(s) (1 to x)
- Every "x" minutes (10 to x) 

It could prevent the loss of data when the device is lost / broken. 

Thank you

**Comment by suricactus** [comment]
Just to clarify, this feature request is in the context of QFieldCloud? Please adapt the title accordingly.
