### ISSUE TITLE
XYZ Tiles with referer stopped working

### ISSUE THREAD

**Issue by balogh89** [opengisch/QField#3742]
### Describe the issue
XYZ Tiles with referer stopped working on Qfield. 

### Reproduction steps
1. Create XYZ Tiles connection with referer in QGIS, 
2. Add the layer to the project, it's displayed properly on QGIS.
3. Cable export project (layer configuration set to directly access datasource)

### Expected behavior
XYZ Tiles Layer should be seen on Qfield. (Layers without referer are working propely with this method.)   

### Observed behavior
Layer shows nothing. 

### Desktop
 - OS: Win10
 - QGIS Version 3.22.4
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: Realme 8
 - OS: Android 12
 - QField version: 2.5.6 (13f23d)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes, I don't know exactly which was the latest working version, but versions before 2.0 were surely OK.     
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@balogh89 , can you attach a test project here (or send directly to me at mathieu@opengis.ch)?

**Comment by nirvn** [comment]
@balogh89 , I've tried your project on QGIS 3.28 and I can't get it to work either, this doesn't appear to be a QField issue. The referer URL looks a bit suspicious to me (repeating the {x}. {y}, {z} parameters for e.g.).

I would advise you to test against QGIS 3.28, and if you feel there is an bug there, open an issue upstream.
