### ISSUE TITLE
Failed to upload packaged project

### ISSUE THREAD

**Issue by JUAN1936** [opengisch/QField#3756]
### Describe the issue
Since you fixed the DNS issue, all the processes are being carried out properly, but in the end the project does not package for me.
I have redone the project, I have uploaded a new project, but it keeps doing the same thing to me.
What can be wrong?

### Reproduction steps
1. [Go to '...']
2. [Click on '...']
3. [Scroll down to '...']

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows 10 ]
 - QGIS Version [e.g. 3.28.0]
 - QFieldSync Version [the last version ]

### Mobile (please complete the following information)
 - Device: [e.g. samsung s20 FE]
 - OS: [e.g. Android 13]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example the last version

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by JUAN1936** [comment]
Upload packaged project
06:38:01.895 root INFO List of local files for project "5f91b04d-77b8-4ded-b3ee-74837162ef08":
Name Size MD5 Checksum
-------------------------------------------------- -- --------- --------------------------------
Plot_with_species_cloud_qfield.qgs 10387923 dea9a40938df9bd83c786f7d7db2c993
Plot_with_species_cloud_qfield_attachments.zip 2110 602f404aa1288dc82e857f34e92eebe6
data.gpkg 292671488 f4d4ef6823f625a26c75bdcd5012f0be
06:38:01.896 root INFO Loading file "data.gpkg"...
Delicate

**Comment by suricactus** [comment]
@JUAN1936 your project is using way too much resources (memory > 1GB) and it got killed. I have slightly increased the limit now. Can you try again now, and confirm that your project works now?

**Comment by JUAN1936** [comment]
Ok

**Comment by JUAN1936** [comment]
Now working correctly, thanks for everything Suricato
