### ISSUE TITLE
"Picture expression eval error" on startup

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#377]
> I get an error on my project loading : "Picture expression eval error" written two times upper left on a white screen. If I touch, the map appears...

I could reproduce the issue once. On a second load of the project it did not appear anymore. Does it appear every time on you @gnerred ? Could you deliver screenshots then?

[test_photo.zip](https://github.com/opengisch/QField/files/2446668/test_photo.zip)

**Comment by gnerred** [comment]
Once too

**Comment by signedav** [comment]
Hi @gnerred 
What is the status here? Did it happen on newer versions?
Feel free to close this issue if not.

**Comment by gnerred** [comment]
You can close for the moment, I have no possibility to test now with the last version

**Comment by OBVYamaska** [comment]
Did you find what could cause this?
I have this issue lately and don't know where to start to debug it, as the project worked fine last week...

**Comment by nirvn** [comment]
@OBVYamaska , watching linked to either a symbology raster fill / marker or a layout's picture item. It's the reflection of a path pointing to a non existing image.

**Comment by OBVYamaska** [comment]
@nirvn , is there a way to get more details on the layer generating the problem?

**Comment by nirvn** [comment]
@OBVYamaska , actually, just checked, the _only_ way to trigger this error is via a layout picture/image item.

**Comment by OBVYamaska** [comment]
@nirvn , is there a way to go around that?
I have a layout which includes images whose link are dynamic (the report loops over every feature of a layer, and they do not always have the same number of pictures linked). This doesn't seem to be a problem when I export the report, but it trows multiple errors and it seems to be a problem on the QField project. Is there a way to prevent the layout to get to the QField project? They are of no use there...  Thanks!

**Comment by nirvn** [comment]
@OBVYamaska , the warning will be gone in QField 2.7.

**Comment by VxTedxV** [comment]
Same issue here.
QGis relative I think because the errors appear as warning in general messages even if it seems not issuing atlas preview nor atlas PDF printing...
QGis 3.26.0 / QField 2.8.1 (5333ee)
