### ISSUE TITLE
Photos resized through the maximum image size settings lose their metadata

### ISSUE THREAD

**Issue by mboutry** [opengisch/QField#3779]
### Describe the issue
I'm taking photos with Qfield on the field and i'm using XnView on my desktop computer to add the _FileCreateDate_ (in french "Prise de vue") as a watermark on them. Qfield used to record exif datas of photos taken within the app until one of the newer versions. The _FileCreateDate_ field is now empty, wether the photo is taken with the native camera app of the phone or the app built-in camera.

If the photo is taken outside the app (with the native camera of the phone), the _FileCreateDate_ is recorded.

### Reproduction steps
1. Take a photo with Qfield 
2. Transfer it to your computer desktop
3. Check the details of the file to see the exif datas

### Expected behavior
The _FileCreateDate_ field should be filled with the date and time when the photo was taken

### Observed behavior
The _FileCreateDate_ is empty

### Screenshots and GIFs

![TestA](https://user-images.githubusercontent.com/81357265/210063049-86538361-4029-458c-bb6e-5698629f1feb.png)

### Desktop (please complete the following information)
 - OS: Windows 10 Enterprise
 - QGIS Version 3.22
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: Crosscall Action X5
 - OS: Android 11
 - QField version: 2.537 build 428951

 - Device: Pixel 6A
 - OS: Android 13
 - QField version: 2.537 build 428951

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@mboutry , a couple of follow up questions:

1/ are you using the 'maximum image size' setting in your project? If so, that'd strip away the metadata

2/ if not, could you identify which QField version appears to have regressed on that front? You can find older QField releases on this page (https://github.com/opengisch/QField/releases).

**Comment by mboutry** [comment]
I'm actually using the 'maximum image size' setting, so the problem probably occured for the first time with the Qfield release introducing this new option.
Is there a way to use this setting AND keep the metadatas ?

**Comment by nirvn** [comment]
@mboutry , ah, that explains it :) ATM, resized images do indeed "forget" all of their metadata. I'll adapt the title of this issue.

**Comment by nirvn** [comment]
@mboutry , this will be fixed in 2.7. thanks for reporting this issue.
