### ISSUE TITLE
GPS broken by recent update(s) on Android

### ISSUE THREAD

**Issue by drpeter2000** [opengisch/QField#379]
With version 0.11.8 the position sensor does not work at all.  OK on 0.11.6

### Reproduction Steps:

1. Update to 0.11.8 (don't know about 0.11.7) either from Play Store or github
2. Open a project that works under 0.11.6
3. Click Blue crosshairs widget to center map at current location

Map should pan to current location and mark it with a dot

Instead nothing happens except msg: Activating position sensor.
Opening show coordinates widget shows lat=lon=0.0000

Same behavior on Android 8.1.0 (Nexus 6p) and Android 6.0.1 (Nexus 7 2013 Wifi).

Reinstalling 0.11.6 from github restores functionality. Not tested with 0.11.7

* Problem started happening recently, didn't happen in an older version of QField:  YES
* Problem can be reliably reproduced, doesn't happen randomly: YES
* Problem happens with all files and projects, not only some files or projects: YES

**Comment by 3nids** [comment]
confirmed, fix coming
