### ISSUE TITLE
Direction of compass cone not correct on iOS

### ISSUE THREAD

**Issue by geowatti** [opengisch/QField#3810]
I’m using an iPhone 12 with the latest version 16.2. I store fotos on on sight visits from different directions in a point layer. 
I need the direction in which I took a photo. But the cone which marks the direction is never correct, it always points out eastwards. 

As a result I always get wrong directions if I use @position_direction as value in my attribute table.

In other map apps the direction is correct.

I used two other IPhones, one with iOS 16.1 one with iOS 16.2, the problem was the same.

### Desktop (please complete the following information)
 - OS: [Windows]
 - QGIS Version [3.28.0]

### Mobile (please complete the following information)
 - Device: [iPhone 12 mini, IPhone SE 2020]
 - OS: [iOS 16.1 & 16.2]
 - QField version: [2.6.0]

**Comment by Ipickedausername** [comment]
I may say something useless, but are you sure that you get wrong "Directions" which is different as "Orientation". 

Direction gives you the last information saved about your direction. If you walk north and then take picture west, it will point your photo to the north. 

Currently, Qfield cannot save the orientation of the phone, I already asked for such enhancement, but we'll have to fund it.

**Comment by geowatti** [comment]
This is right. You have to be careful that your orientation while setting a point suits to your foto.
But I clearly can see it on the direction of the view cone, which is not rotating 360 degree when I turn around, that something is wrong here.
Btw you can store the direction of your view if you add @position_direction as fixed variable to an attribute in your foto layer. 
Now I use a different mapping app, it works here. But I like the layout in QField and would be happy to use it.

**Comment by nirvn** [comment]
@geowatti , could you provide a screencast of your problem? I've been unable to replicate what is being described here.
