### ISSUE TITLE
Windows - Folder - Vertical grid shift in use

### ISSUE THREAD

**Issue by bettellam** [opengisch/QField#3830]
Hello, I was testing the Windows QField 2.6.2 version.
Great job!!!
I'm having trouble finding the right location (folder) where to upload the files : **Vertical grid shift in use:**
With Android no problem:
`<drive>:/Android/data/ch.opengis.qfield/files/QField/proj`

My installation root for windows is:
`C:\Program Files\QField\`

`C:\Users\XXXXXX\AppData\Roaming\OPENGIS.ch\QField`

Can you give me some hints on how to proceed?
Thank you
Ciao

**Comment by nirvn** [comment]
@bettellam , they should be placed in your user document's QField\proj subdirectory.

I've just opened a PR that will have QField auto create those directories in the future (https://github.com/opengisch/QField/pull/3833). It should help people. That and better documentation :)
