### ISSUE TITLE
Relations - Referencing field won't show in form on QField

### ISSUE THREAD

**Issue by MatparMcWolfie** [opengisch/QField#3857]
### Describe the issue
When adding a new feature to a child layer through a relation editor widget in a form, the field containing the referenced field won't appear on QField.

### Reproduction steps
1. Create a QGIS project with a point layer and a table;
2. Set up a relation between layers (Point layer as parent, "ID as referenced and table layer as child , "PARENT_ID" as referencing field);
3. Set up forms as seen in attached folder and test to make sure form is functional;
5. Export to mobile device using QFieldsync (cloud or cable) or by copying project file to device;
6. Open project in QField;
7. Digitize a point in POINT layer and create child feature in table;
8. Notice missing field in form on QField.

### Expected behavior
Field "PARENT_ID" (Referencing field) visible in form, although non-editable (per form settings).

### Observed behavior
Field "PARENT_ID" is not visible. 

### Screenshots and GIFs
Here is the form tested on QGIS with referencing field (PARENT_ID) visible:

![New Project (2)](https://user-images.githubusercontent.com/98125070/215580473-bab7b361-be3c-4424-9c75-8779e0ca4f35.gif)

Referencing field not visible when filling form on QField:

![Untitled (1)](https://user-images.githubusercontent.com/98125070/215580523-87edf603-d9fd-4268-a07d-125a4b6cd463.gif)

Also, I should notice that when I access child layer form directly (without going throug parent form and relation), the referencing field is shown: 

![New Project (3)](https://user-images.githubusercontent.com/98125070/215581725-6f4ca6fe-d3c9-45d6-be5c-99037358dd9a.gif)

Project used to demonstrate issue: 
[qgis_test_project.zip](https://github.com/opengisch/QField/files/10539449/qgis_test_project.zip)

### Desktop
 - OS: Windows 10
- QGIS Version : 3.28.2
- QFieldSync Version V4.2.0

### Mobile (please complete the following information)
 - Device: Multiple, currently testing on Ulefone Power Armor 14 Pro
 - OS: Android 12
 - QField version: 2.6.2 - Geeki Gecko (fc58dd v2.6.2)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: YES
* Problem can be reliably reproduced, doesn't happen randomly: YES
* Problem happens with all files and projects, not only some files or projects: YES

**Comment by nirvn** [comment]
@MatparMcWolfie , this isn't really a bug per say as the behavior was deliberate on QField's part. That said, I think you raise a good point on discrepancy between QGIS vs. QField. This PR (https://github.com/opengisch/QField/pull/3876) now disables the attribute instead of hiding it. You can give the APKs a try in 10 minutes or so.

**Comment by MatparMcWolfie** [comment]
That's great, thanks @nirvn. This will be particularly useful when testing forms before a field survey as it allows to confirm the relation is working properly (which is testable on desktop but a double check never hurts)
