### ISSUE TITLE
Zoom and pan on a picture

### ISSUE THREAD

**Issue by SygPi** [opengisch/QField#386]
Some time the picture preview in the form is too small to see some details even when the form is in fullscreen.

### Expected behavior:

It could be great to zoom on the picture.
 Or could be also open in external app (for example Android gallery).

**QField version:** [0.11.9]

**Comment by nirvn** [comment]
This has been addressed, clicking on a photo in the feature form opens it in an external viewer. The picture widget has also been revamped in QField 2.0 and offers a slightly larger view of the photo by default.
