### ISSUE TITLE
App freezes after deleting point

### ISSUE THREAD

**Issue by philstel** [opengisch/QField#3871]
### Issue description
After deleting a point in QField, sometimes the QField app freezes and the only way to recover is to force close the app, delete the project and start from scratch.
Reloading the project results in a white screen, see screenshots attached.
Deleting the shape resolves the problem.

We could reproduce this with various projects of our own, but are still not sure if this is a general problem or just something with our setup.

### Reproduction steps
1. Set a point on the map
2. Delete the point afterwards
3. App becomes unresponsive 

Also, see screenrecording:

https://user-images.githubusercontent.com/1367500/216005800-84344add-f8d1-4ac8-95f6-aeeb51dbd1c5.mp4

### Expected behavior
QField should not crash when deleting points.

### Desktop
 - OS: Windows
 - QGIS Version: 3.28.0
 - QFieldSync Version: none

### Mobile
 - Device: Fairphone 4
 - OS: Android 11
 - QField version: 2.6.2 Geeky Gecko (fc58dd v2.4.2)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Not sure
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No, most probably not, but we could reproduce it with different projects.

**Comment by m-kuhn** [comment]
Are you able to share a sample project?

**Comment by philstel** [comment]
Hey @m-kuhn,

yipp, see here:
[GithubTest.zip](https://github.com/opengisch/QField/files/10570368/GithubTest.zip)

**Comment by nirvn** [comment]
@philstel , thanks for the test project, it made fixing this issue super easy. Test APKs will appear here (https://github.com/opengisch/QField/pull/3874), and you can expect a QField 2.6.3 within the coming days.

The issue wasn't actually with the feature deletion itself but rather the zoom to layer extent triggered when you hit the ( show features list ) button. For 1-point layers, QField would just go broke.
