### ISSUE TITLE
Suggestion - Digitizing points taping on screen

### ISSUE THREAD

**Issue by filippo-ferrario** [opengisch/QField#388]
It could be really useful to be able to digitize points by tapping on the screen with the finger or with a pen. this is handy in particular if you have to deal with 1000s of point features.

see here https://gis.stackexchange.com/questions/302359/android-app-to-help-digitizing-point-layers-on-a-tablet/302370?noredirect=1#comment487096_302370

**Comment by nirvn** [comment]
@filippo-ferrario , pen tapping has been implemented, enjoy! :tada:

**Comment by pgathogo** [comment]
@nirvn, how do I enable the tapping feature?
