### ISSUE TITLE
Username changes while WMS Login

### ISSUE THREAD

**Issue by krz-gisteam** [opengisch/QField#3888]
We have a WMS layer protected with username and password in a QField project.
When logging in, the first character of the username moves to the end when the focus changes to the password field. After editing the username again, it remains correct.

Example:
-> username: b982webgis
-> set focus on passwordfield
-> username 982webgisb
-> renaming username to b982webgis

**Comment by nirvn** [comment]
@krz-gisteam , this PR (https://github.com/opengisch/QField/pull/3889) should fix your virtual keyboard issue. You can try APKs in 10 minutes or so.
