### ISSUE TITLE
Open layer properties with double click on windows

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/QField#3910]
### Describe the issue
Trying to double click to switch layer visibility does not work on Windows 10 Professionnel

### Reproduction steps
1. Download and install the QFIELD 2.6.3 Geeky Gecko for windows on Windows 10 Professional
2. Download a QFieldCloud project or open a local project file
3. Open the project
4. Open the navigation panel, and try to double click on any layer

### Expected behavior
A pop-up should propose to set up the layer visibility

### Observed behavior
pop-up does not show up

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10 Professional
 - QGIS Version 3.22.4
 - QFieldSync Version 4.3.1

### Mobile (please complete the following information)
 - Device: Desktop DELL
 - OS: Windows 10 Professionnel
 - QField version: 2.6.3 Geeky Gecko

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by m-kuhn** [comment]
Did you try a long click instead of a double click?

**Comment by jpdupuy** [comment]
No I did not know this way was the right way to proceed. I have seen this suggestion in the documentation
It works fine this way. 
Many thanks, you can close this ticket.

**Comment by m-kuhn** [comment]
Would a right lick menu make it more discoverable (on desktop) cc @nirvn

**Comment by nirvn** [comment]
@m-kuhn , good idea, it costs nothing too.

**Comment by nirvn** [comment]
Right click implemented.
