### ISSUE TITLE
New File Browser 0.11.10: Qfield cannot open Project from external SD Storage

### ISSUE THREAD

**Issue by soester** [opengisch/QField#392]
Projects on external SD Storage can be browsed in the **realy nice new File Browser**.
After opening we get an error:
QFIELD
File /storage/0000-0000/Android/data/ch.opengis.qfield/projectfolder/porject.qgs does not exitst

### Expected behavior:

on older versions this was not a problem (same directory)

**QField version:** 0.11.10

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]
* Android 5.1.1 on Samsung Galaxy Tab Active

**Comment by m-kuhn** [comment]
CC @marioba

**Comment by marioba** [comment]
Thanks @soester for reporting this problem. This is related to #390 

Could you also tell me what is the correct path of the qgs file you are trying to open? You can see it from "My Files" by selecting the file -> and then "details".

**Comment by soester** [comment]
the path would be:
/storage/extSdCard/Android/data/ch.opengis.qfield/projectfolder/porject.qgs
(this would also be the path i would select using the old filemanager)
