### ISSUE TITLE
QField (Windows 2.6.3) altitude correction not working with Swiss correction file

### ISSUE THREAD

**Issue by MH-Mueller** [opengisch/QField#3929]
The altitude correction within QField is not working using the Swiss correction file "ch_swisstopo_chgeo2004_ETRS89_LHN95.tif" (https://cdn.proj.org/ch_swisstopo_chgeo2004_ETRS89_LHN95.tif, unfortunately I cannot upload the tif-file I used (upload not supported)).

We use an external "GNSS-receiver" coupled via Bluetooth to QField. Positioning ist working fine for 2D-data (i.e. "x-y-positioning" is correct), but altitude correction is not working. The file is located in the folder "C:\Users\XXXXXXX\Documents\QField\proj" and it shows up in the drop down list for altitude correction files. However, even after activating the file, altitude is not corrected.

 - OS PC: Windows
 - QGIS Version: 3.22.16
 - QFieldSync Version: 4.3.1

 - field device: Leica CS35 tablet (Panasonic)
 - OS field device: Windows
 - QField version: 2.6.3 (aaa9ed)

Thanks for any advice

Matthias

**Comment by nirvn** [comment]
@MH-Mueller , have you tried the .tif file on Android? Is it working there?

**Comment by MH-Mueller** [comment]
@nirvn, no, I have not tried it, because our field device does run on Windows and we cannot change the field device.

_________________________________
Dr. Matthias H. Müller
MSc in Environmental Geosciences, Univ. Basel

Kiefer & Studer AG
Geotechniker SIA/USIC
Bruggstrasse 12a
CH-4153 Reinach BL

Zentrale            +41 (0)61 716 93 00
Fax                      +41 (0)61 716 93 01
Direkt                 +41 (0)61 716 93 17
Mobil                  +41 (0)79 429 94 66
E-Mail                ***@***.******@***.***>
web                     www.kiefer-studer.ch<http://www.kiefer-studer.ch/>
_______________________________

Von: Mathieu Pellerin ***@***.***>
Gesendet: Montag, 20. Februar 2023 14:29
An: opengisch/QField ***@***.***>
Cc: Matthias Müller ***@***.***>; Mention ***@***.***>
Betreff: Re: [opengisch/QField] QField (Windows 2.6.3) altitude correction not working with Swiss correction file (Issue #3929)


@MH-Mueller<https://github.com/MH-Mueller> , have you tried the .tif file on Android? Is it working there?

**Comment by nirvn** [comment]
@MH-Mueller , no worries. Is the tif you are linking to in your description (hosted on cdn.proj.org) the one used on your windows machine?

**Comment by nirvn** [comment]
@MH-Mueller , faking a moving position over Switzerland and using the cdn.proj.org hosted tif, I can see the altitude being rectified over here, e.g.:

![image](https://user-images.githubusercontent.com/1728657/220132511-c2782231-3107-4d91-a396-fdd2da87358d.png)

My fake position has an altitude of 0 meter, which means a -48 altitude confirms the grid is being taken into account.

Could you provide a sample project showing this issue? It could be a project CRS <-> grid CRS issue here.

**Comment by MH-Mueller** [comment]
@nirvn, attached you will find my sample project. It only contains a WMS layer und the CRS is LV95 (EPSG:2056). Following your hint, I also re-projected the “ch_swisstopo_chgeo2004_ETRS89_LHN95.tif”-file from https://cdn.proj.org/ to LV95 (EPSG:2056), but with no success.



_________________________________
Dr. Matthias H. Müller
MSc in Environmental Geosciences, Univ. Basel

Kiefer & Studer AG
Geotechniker SIA/USIC
Bruggstrasse 12a
CH-4153 Reinach BL

Zentrale            +41 (0)61 716 93 00
Fax                      +41 (0)61 716 93 01
Direkt                 +41 (0)61 716 93 17
Mobil                  +41 (0)79 429 94 66
E-Mail                ***@***.******@***.***>
web                     www.kiefer-studer.ch<http://www.kiefer-studer.ch/>
_______________________________

Von: Mathieu Pellerin ***@***.***>
Gesendet: Montag, 20. Februar 2023 15:25
An: opengisch/QField ***@***.***>
Cc: Matthias Müller ***@***.***>; Mention ***@***.***>
Betreff: Re: [opengisch/QField] QField (Windows 2.6.3) altitude correction not working with Swiss correction file (Issue #3929)


@MH-Mueller<https://github.com/MH-Mueller> , faking a moving position over Switzerland and using the cdn.proj.org hosted tif, I can see the altitude being rectified over here, e.g.:

[image]<https://user-images.githubusercontent.com/1728657/220132511-c2782231-3107-4d91-a396-fdd2da87358d.png>

My fake position has an altitude of 0 meter, which means a -48 altitude confirms the grid is being taken into account.

Could you provide a sample project showing this issue? It could be a project CRS <-> grid CRS issue here.

**Comment by nirvn** [comment]
@MH-Mueller , alright, I can see the elevation is adjusted with this test project too:

![image](https://user-images.githubusercontent.com/1728657/220353262-ba67f94e-a9a0-4a90-8108-72ae4aee2583.png)

I'll try to get my hands on a windows laptop and give it one more try.

**Comment by nirvn** [comment]
@MH-Mueller , could you give this windows build a try: https://github.com/opengisch/QField/suites/11135630661/artifacts/567916093

While I haven't had the opportunity to get my hands on a windows machine yet, the build tries to use native windows path separator when linking to the vertical grid with proj, which might fix the issue being reported here.

**Comment by MH-Mueller** [comment]
@nirvn, thanks for the windows build. I installed it tried the grid shift file, but still, the file is not used. Everyrhing works fine, despite the altitude correction. When starting QField, a second window opened, where the following error message showed up: "Pipeline: Bad step definition: proj=vgridshift (File not found or invalid) proj_create: Error 1029 (File not found or invalid)". Maybe this helps. The grid shift file is shown in the drop down list and can be selected, so it can be found. This suggests that it is invalid...?

**Comment by nirvn** [comment]
@MH-Mueller , interesting. I've been able to find a windows device to test things and it worked here:
![PXL_20230223_121016356](https://user-images.githubusercontent.com/1728657/220907439-4310b062-50b3-4894-9d21-1fbe4a164867.jpg)

Could you give me the full path to your grid file (ie c:\Users\....tif ? I'm thinking maybe your path contains a special character.

**Comment by MH-Mueller** [comment]
The path is: C:/Users/Leica Support/Documents/QField/proj/.....tif.  Nothing really special, but maybe the space is the problem?

**Comment by nirvn** [comment]
@MH-Mueller , ha yeah, the space could well be the issue here. Do you have an easy way to test that?

**Comment by nirvn** [comment]
@MH-Mueller , here's a new test build to try:

https://github.com/opengisch/QField/suites/11159967671/artifacts/569746510

It adds quotes to handle spaces in paths.

**Comment by nirvn** [comment]
@MH-Mueller , any luck confirming the test build fixes your issue?

**Comment by MH-Mueller** [comment]
@nirvn<https://github.com/nirvn>, thanks for the new test build. I was not able to test it yet; hopefully today. I will let you know.

**Comment by nirvn** [comment]
@MH-Mueller , fantastic.

**Comment by MH-Mueller** [comment]
@nirvn, I finally could test the new test build, and the altitude correction works! Thanks for your effort!
