### ISSUE TITLE
Point features are synced with QFieldCloud but some do not show up on the map in QGis

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#3930]
### Describe the issue
Synchronising from QField to QGis over QFieldcloud works fine but when syncing a series of points, one or some points in that series go wrong. It seems that the points are available in the attribute table but that they are not shown on the map. When selecting - I guess - those features, QGis says: "Cannot zoom to selected object(s). No range could be determined".

### Reproduction steps
1. Register a series of points in QField
2. Sync back to QGis
3. Check the number of points that are visible on the screen

### Expected behavior
When syncing, all features need to be visible on the map

### Observed behavior
I noticed this in some occasions, a series of point were synced but that one or more were missing. For the moment, I observed this in only one project, I will test others.

### Screenshots and GIFs

Screenshot from QField
![image](https://user-images.githubusercontent.com/57868975/220190239-74779c4e-570f-412e-a8a2-d5dbde4bb9a7.png)

Screenshot from QGis
![image](https://user-images.githubusercontent.com/57868975/220191213-c21c53d3-ced9-42c4-b36b-909c0b4f06d7.png)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Ubuntu 20.04.5 LTS
 - QGIS Version 3.26.3-Buenos Aires
 - QFieldSync Version 4.2.0

### Mobile (please complete the following information)
 - Device: Galaxy A52
 - OS: Android 13
 - QField version: 2.6.3 - Geeky Gecko (aaa9ed v2.6.3)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: YES
* Problem can be reliably reproduced, doesn't happen randomly: I need to try the reproduction steps with another project
* Problem happens with all files and projects, not only some files or projects: don't know yet

If the problem happened with QFieldCloud, please add your username and project name
boswachter_marc - project "ANB/Walden_v5a"

**Comment by suricactus** [comment]
Hey, @BoswachterMarc thanks for the report. There is a known incompatibility between QField 2.6+ and QFieldCloud for layers containing Z and/or M dimension.  Quick workaround - downgrade to QField 2.5 .

See https://github.com/opengisch/qfieldcloud/issues/496 .

**Comment by BoswachterMarc** [comment]
My first reaction was 'ok', this is a good workaround (for a individual or small team). But for 10 people in a organization this is somehow cumbersome. They all need to uninstall QField, install a apk, disable automatic updating en download again the project from the cloud. Is there no other workaround or a update in the near feature?

**Comment by suricactus** [comment]
@BoswachterMarc yes, the update is coming in the next few weeks. You can follow the progress of fix here https://github.com/opengisch/qfieldcloud/pull/523 . Once it gets merged, it is 1 week away from being deployed.

Sorry for the inconvenience.
