### ISSUE TITLE
Spatialite layers editable only if added using the QGIS browser

### ISSUE THREAD

**Issue by gioman** [opengisch/QField#394]
I'm almost 100% sure (from several tests today) that a SL layer is editable in QField only if it was added using the QGIS Browser. If added by other means then saving edits in QField does not work. Log messages: "could not save changes, rolling back" and "feature could no be added".

**Comment by m-kuhn** [comment]
Quick thoughts

 * when using the browser layers are added as spatialite layers
 * when using drag and drop or other means layers are (probably) added as ogr layers

**Comment by giedrioks26** [comment]
a similar problem like here #200

**Comment by montarob** [comment]
Hi guys,
Just an information please.
I would like to edit some spatialite tables without geometry inside my qfield project but it doesn't let me to do that.
By any chance do you know if it is possible to do that in qfield?
Many thanks.
Rob

**Comment by giedrioks26** [comment]
@montarob now its pasible with QField 1.0.0

**Comment by Dubhain** [comment]
> I'm almost 100% sure (from several tests today) that a SL layer is editable in QField only if it was added using the QGIS Browser. If added by other means then saving edits in QField does not work. Log messages: "could not save changes, rolling back" and "feature could no be added".

I'm also having a similar problem with _node_ editing, I don't know if it's related. Polygons on spatialite only seem to save node edits when they are polygon type (as in single polygon), not when they are multi-polygon. But to test this out, I also added the same spatialite layer three times to a test project, once by double-clicking from within DB Manager, once by selecting from Sqlites within Source Manager, and once by selecting the files itself from Source Manager (just by browsing). Oddly it was only the third option which would accept node edits, which seems to corroborate what you're saying. Only a simple browse for the layer works, actually connecting the database (which I always took to be the 'proper' way of doing it) doesn't seem to work.

**Comment by suricactus** [comment]
Is this still the case?

**Comment by m-kuhn** [comment]
@nirvn your recent `path` fix on qgis?
