### ISSUE TITLE
Error on QFieldcloud when pushing changes

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#3950]
### Describe the issue
When pushing changes from mobile to the cloud, Qfield says changes were pushed. On QFieldCloud they are not accepted (status 'Error'). When trying to re-apply, it still gives an error.
I think this is because of the transition from bèta to organization?
Both collaboraters and owner/admin are affected.

![image](https://user-images.githubusercontent.com/57868975/220600224-0d967863-79e0-4813-ad3f-4c685c1dc573.png)

The project is ANB/Walden_v5a. Admin is boswachter_marc.

Thanks for checking.

**Comment by suricactus** [comment]
@BoswachterMarc thanks for reporting. We got in touch with you by email about the configuration we did with your account.

**Comment by BoswachterMarc** [comment]
@suricactus I just tried again, the problem is solved. Thank you!
