### ISSUE TITLE
Only some layers syncing

### ISSUE THREAD

**Issue by ShanaDDW** [opengisch/QField#3952]
### Describe the issue
I just starting using Qfield after using QGIS for several years. 
Qfield project set up was very simple - basemap, two polygon layers and three points layers for collecting data. 
I have lost all the data collected on one polygon layer and one points layers because these two layers have not pushed any changes. 

Only discovered the problem after using the app in the field for three days using push changes. When I synchronised the app today back in the office, the data from the faulty layers disappeared from my phone.

I can see that the layers with problem have not pushed any changes for the last three days. The layers without problems have a version for each day in the field. (see screenshot below from Qfield sync showing versions of a layer without problems and a layer with the problem)

Can I conclude that the data is lost forever? 

### Reproduction steps
1. 'Push changes' at the end of each field day for three days.
2. Synchronise project on day four.
3. Two layers used to collect data now have no features. 

### Expected behavior
All layers to have feature data.

### Observed behavior
Two layers now have no features, which previously had features collected.

### Screenshots and GIFs
![image](https://user-images.githubusercontent.com/126123642/220791905-aaf0430c-99c8-4ff2-a2a2-5dfac1c8e4b5.png)

### Desktop (please complete the following information)
 - OS: Windows 10 Business
 - QGIS Version 3.28.1-Firenze
 - QFieldSync Version v4.3.1

### Mobile (please complete the following information)
 - Device: iPhone12
 - OS: iOS 16.1.2
 - QField version: 937970 v2.5.5

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: N/A new user
* Problem can be reliably reproduced, doesn't happen randomly: Not sure
* Problem happens with all files and projects, not only some files or projects: Only some layers within a project

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by suricactus** [comment]
Are you able to see the changes in the Web UI? Got to the Project -> Changes and there is a list of everything that QField is aware of. Also please share your QFieldCloud username and project, so we can look on our end too.

**Comment by ShanaDDW** [comment]
The situation is the same on the Web UI. Notepoly layer has the four versions but Note (point) layer only has one. 
Username is shanaddw. The project is the one with QfieldCloud at the end of the file name. 

With thanks

**Comment by ShanaDDW** [comment]
Hi guys, I think I've worked out the problem. I think I've been caught up in the switch from beta to subscription service. 

The project I uploaded included a contours layer for reference. Unfortunately, it looks like the complete extent of the layer uploaded, not just the project area extent. So my QFieldCloud project has a layer that is 1.9 GB in size. It means I can't do anything with the project as I'm over the data limit. I can't even pay for a subscription to unlock the project because the data limit is 1 GB.

Is there a way I can delete this one layer/file off Qfieldcloud so I can unlock the rest of the project? I see now there is a list of errors that need to be resolved but I can't resolve them while I'm over the storage limit.

Many thanks.

![image](https://user-images.githubusercontent.com/126123642/222341591-dc3eb31f-4e8c-4f74-af18-8ccb0f5187f4.png)

**Comment by suricactus** [comment]
Yes, you can delete using QFieldSync.

**Comment by Luke-Steer** [comment]
Is the recorded information still showing in QField on your tablet? If so you may be able to connect your tablet to a pc with a wire, locate the updated project and copy it to your pc. 

Best of luck. 

Luke

**Comment by ShanaDDW** [comment]
@Luke-Steer Thanks for your comment, unfortunately, the data disappeared off the device so no chance of retrieving it.
I've had the opportunity to re-collect the data. To be safe, I used the manual import/export local project method. I'm the only person collecting data on the project so don't really need the functionality of the cloud based service.
