### ISSUE TITLE
[Bug] Add Google Map as base map

### ISSUE THREAD

**Issue by jonnyforestGIS** [opengisch/QField#398]
Add Google Hybrid as Base map

### Reproduction Steps:

1. Create project with QGIS 3.4.1 and use Google as basemap (set local crs in project)
2. Turn on mobile network or wifi connection.
3. Open in Qfield and turn on GPS

### OS QGIS
Windows 10 64-bits
Windows 7 64-bits

### Equipment's and Android SO

- Caterpillar S41 Android (7.0.0)
- Samsung S7 Android (8.0.0)
- Wiko Pulp Android (5.1) - Note: This for know the only one that have the correct behavior.
- Huawei P8 Lite Android (8.0.0)

### Expected behavior:

Load the google map in location

### Observed behavior:

blank map

### Screenshots and GIFs

Don't have for know.

Project QGIS
[project.zip](https://github.com/opengisch/QField/files/2630692/project.zip)

**QField version:** 0.11.11 Lucendro

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Not sure
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Not sure

**Comment by mmarius2** [comment]
I have encountered same problem in Android 8.1 (Xiaomi mi 8) but there is no problem on Android 6.0.1.
I attached logcatfile excerpt. Warnings appear only in Android 8.1 when I activate Google Hybrid layer.
[logcat.txt](https://github.com/opengisch/QField/files/2635804/logcat.txt)

**Comment by m-kuhn** [comment]
Can you verify with this build
https://github.com/opengisch/QField/pull/389#issuecomment-438332293

**Comment by jonnyforestGIS** [comment]
@m-kuhn i'm downloading the apk and i will give feedback.

**Comment by mmarius2** [comment]
@m-kuhn, apk from given link, works perfect. Layer Google hibrid  loads ok in this case.

**Comment by jonnyforestGIS** [comment]
@m-kuhn i download both versions and when i try to install both give me an error:
"Error analyzing the package." and abort the installation.
Tested in Huwaei P8 Lite and Samsung S7 Galaxy with Android 8.0.0.


The step is download the files from the link
x86 - size: 41,4 mb
armv7 - size: 33,8 mb

Copy and paste to folder Downloads in Android device
Run with the Android installer packages.

Any idea what i'm doing wrong?

**Comment by m-kuhn** [comment]
> @m-kuhn i download both versions and when i try to install both give me an error:
"Error analyzing the package." and abort the installation.
Tested in Huwaei P8 Lite and Samsung S7 Galaxy with Android 8.0.0.

Can you download on the device and launch the installation from there? (armv7 is the one you want)

**Comment by jonnyforestGIS** [comment]
@m-kuhn is working :)
