### ISSUE TITLE
Wrong tab content when a tab is hidden because of conditional visibility

### ISSUE THREAD

**Issue by jonnyforestGIS** [opengisch/QField#399]
The forms are made in QGIS but in the Qfield fields go to the wrong tabs

### Reproduction Steps:

1. Create forms in QGIS with option drag n drop in layer proprieties.
2. Copy to Android Equipment.
3. Open Qfield try to digitize some polygon.
4. The fields start to appear in the wrong tabs.

### **OS QGIS**

Windows 10 64-bits
Windows 7 64-bits

### **Equipment's and Android SO**

- Caterpillar S41 Android (7.0.0)
- Samsung S7 Android (8.0.0)
- Wiko Pulp Android (5.1)
- Huawei P8 Lite Android (8.0.0)

### Expected behavior:
The fields in the correct tabs.

### Observed behavior:

Fields in the wrong tabs. The last fields tab are in previous tab and so one. **Update Note: After remove constraint in one of the fields the tabs have the correct behavior.**

### Screenshots and GIFs

Screenshots: 
[QFIELD report.pdf](https://github.com/opengisch/QField/files/2609336/QFIELD.report.pdf)

Project see attach in #398  

**QField version:** 0.11.11 Lucendro

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Not Sure
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No

**Comment by signedav** [comment]
Maybe related to this #574

**Comment by suricactus** [comment]
Seems this is no longer an issue with the given example project? @jonnyforestGIS can you confirm

**Comment by jonnyforestGIS** [comment]
Hi guys, sorry this can be close. 👌
