### ISSUE TITLE
DCIM folder with photos don't appear in Qfield Project

### ISSUE THREAD

**Issue by jonnyforestGIS** [opengisch/QField#400]
The DCIM folder don't appear in the android Gallery or Windows Explor after fill the form with a photo.

### Reproduction Steps:

1. Copy project to Android phone in the folder Documents.
2. Open Qfield and Open Project.
3. Open Qfield try to digitize some polygon.
4. Take a Photo.
5. Open the Gallery and try to find the DCIM folder.
6. Connect the cable to computer and try to open in Windows Explorer the project folder and don't appear the DCIM folder. 

### **OS QGIS**

Windows 10 64-bits
Windows 7 64-bits

### **Equipment's and Android SO**

- Caterpillar S41 Android (7.0.0)
- Samsung S7 Android (8.0.0) Note: Only that have the correct behavior but only when check the checkbox in the right of the photo and disconnect the cable of the computer.

- Wiko Pulp Android (5.1)
- Huawei P8 Lite Android (8.0.0)

### Expected behavior:
Open the Windows Explorer and go to the Android Phone and see the folder of DCIM inside of the Qfield project folder.

### Observed behavior:

Only visible on the Android Folder Manager. Don't appear in the Android Gallery and Windows Explorer.

### Screenshots and GIFs

Screenshots: 
Don't have for now.

Project see attach in #398 . 

**QField version:** 0.11.11 Lucendro

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Not Sure
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No

**Comment by m-kuhn** [comment]
Interesting that no one else has experienced this.
Is it any better if you create the DCIM folder on the tablet from Windows Explorer before leaving the office for data collection?

**Comment by jonnyforestGIS** [comment]
@m-kuhn thanks for rising this. I think this issue is already fix. I will close for now. If this behavior appears again i give some feedback.
Regards,
João

**Comment by xenelsta** [comment]
Hi, I have the same problem with Qfield!

When I want to download the photos from Qfield to my computer, the DCIM folder does not appear in Windows Explorer... However it is right there on my tablet (Sony Xperia).

I have tried to creat a DCIM folder beforhand on the tablet.... In this case when I want to download the photos the DCIM folder in Windows Explorer is empty (however not empty on my tablet). 

How did you manage to fix this problem? Any ideas?

Kind regards,
Xenia

**Comment by CBrownBuc** [comment]
I'm experiencing the same problem! DCIM folder exists on my phone ( SONY Xperia) but isn't visible in windows explorer.
Would be interested in any solutions.

Thanks
Chris

**Comment by m-kuhn** [comment]
It's very well possible that this is fixed with enabling the native camera which will be implemented if the ongoing [crowdfunding campaign](https://opengis.ch/projects/qfield-love/) is successful.
If it's still an issue after that, we can look at it within the subsequent bugfixing sprint.

**Comment by m-kuhn** [comment]
Can you try the current 1.4.1 release with native camera and check if this is fixed?
Thank you.

**Comment by SumoJoe66** [comment]
Help! I have the same problem here. I tried with both native and QFIELD camera, but I still can't find the DCIM folder with the pictures I took...

FYI, here are the steps I followed:  
1. I installed QFIELD on my mobile phone (LG G5) on March 31 2020.
2. Created a QGIS project in which I added a single shapefile (point) with 1 field for photo.
3. Exported QGIS project to QFIELD.
4. Opened the project in QFIELD
5. Digitized 1 feature point and took a photo with native camera (I can see the picture in the form and the file path DCIM\JPEG20200331_53536727.JPG) 
6. Digitized 1 feature point and took a photo with QFIELD camera (I can see the picture in the form and the file path DCIM\JPEG20200331_5686980.JPG) 
7. Imported the QFIELD folder on my laptop and synchronized in QGIS (I can see the 2 new feature points with DCIM folder path)
8. DCIM folder can't be found in the imported folder.

**Comment by signedav** [comment]
@SumoJoe66 This is related to QFieldSync and will be implemented in the next relesse. See https://github.com/opengisch/qfieldsync/pull/142

**Comment by m-kuhn** [comment]
Can someone affected by this issue check if https://android.stackexchange.com/questions/165818/some-folders-and-files-not-showing-up-on-pc-when-connected-via-usb applies here?

**Comment by m-kuhn** [comment]
> I don't have permission to use a cloud app for this project.
> Apparently, the problem origin is is caused by MTP protocol. It is necessary to use MediaScannerConnection for rescan files.
> [Folder added on Android is not visible via USB](https://stackoverflow.com/questions/13507789/folder-added-on-android-is-not-visible-via-usb)

From https://github.com/opengisch/qfieldsync/issues/146#issuecomment-665090976 (CC @RealSniperKing)

**Comment by m-kuhn** [comment]
Can affected people test the updated apk at https://github.com/opengisch/QField/pull/1174#issuecomment-665568128 (arm64_v8a in doubt)? Thank you!

**Comment by RealSniperKing** [comment]
I tested apk [arm64_v8a.apk](https://download.opengis.ch/qfield/ci-builds/qfield-dev-1174-cbeb97ebc486212a19c88ee3e55a4e314b3ef014-arm64_v8a.apk). No change : the pictures always aren't visible on usb

**Comment by m-kuhn** [comment]
Thanks for testing. To be sure, you have activated "native camera" in the settings?

**Comment by RealSniperKing** [comment]
No I had done the test without native camera, but I just activated it and result is same.

**Comment by RealSniperKing** [comment]
My skill with android studio is low, but I writed this code and it works !! :D

```
        File root_folder = Environment.getExternalStorageDirectory();
        String root_path = root_folder.toString();

        String rc_conf_path = root_path + "/QGIS";

        dataBase_path = rc_conf_path;

        File dataBase_folder = new File(dataBase_path);

        if (dataBase_folder.exists()) {
            File[] list_files_in_DataBase = dataBase_folder.listFiles();

            if (list_files_in_DataBase != null) {
                for (File child : list_files_in_DataBase) {
                    if (child.isDirectory() == true) {

                        String root_dcim = child + "/DCIM";
                        File DCIM_folder = new File(root_dcim);

                        if (DCIM_folder.exists()) {
                            File[] pictures = DCIM_folder.listFiles();

                            for (File picture_t : pictures) {
                                picture_t.setExecutable(true);
                                picture_t.setReadable(true);
                                picture_t.setWritable(true);

                                MediaScannerConnection.scanFile(this, new String[]{picture_t.toString()}, null, null);
                            }
                        }
                    }
                }
            }
        }
```

**Comment by m-kuhn** [comment]
Thanks for that! :tada: 
I have adjusted the code with these inputs, could you test the latest apk as well?

**Comment by Darcman0** [comment]
Got the issue but I go to the project folder in my Qfield app on my iphone?
Then I see a folder named "DCIM" where all the picture that i take was. I hit the option bottom of each picture and hit upload. right after it on my QfieldSync in my PC, i tried to sync back the change. Finally i get my picture back and in the DCIM folder. But it's annoying to make it manually for each picture taken in the field.
