### ISSUE TITLE
"Qfield closed because this app has a bug, Try updating this app after its developer provides a fix for this issue"

### ISSUE THREAD

**Issue by mushchan00** [opengisch/QField#4012]
I have experiencing issues with Qfield. Every time I went to click on the map to survey it would freeze and close the app down. An error message was coming up every time saying “**Qfield closed because this app has a bug, Try updating this app after its developer provides a fix for this issue**”, but I already have the latest version which is 2.6.3. (On a side note, area has a poor connection)

I went to area with a good connection and re-installed 2.6.3, but issue still occurring. I have then installed the old version of Qfield(2.6.2) and worked fine when testing (clicking, editing and adding new items on Qfield). But when I got back to site(area with poor connection) the same issue occurred before started again. 

I wiped the tablets memory, deleted and re-installed both version of Qfield (2.6.3 and 2.6.2) but this issue is still occurring. Please help to fix the issue.

 - Device: Samsung Galaxy s6 lite
 - OS: One UI 5
 - QField version: [2.6.3 - Geeky Gecko](https://github.com/opengisch/QField/releases/tag/v2.6.3)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No, problem occured in recent and old version]

**Comment by m-kuhn** [comment]
With which project is this happening?
Can you reproduce it with the simple bees demo project?
