### ISSUE TITLE
Links video from Chat help center seems to be wrong

### ISSUE THREAD

**Issue by GlaDal** [opengisch/QField#4017]
You can have a look on the image below : 
![image](https://user-images.githubusercontent.com/7015197/223795682-e6d9f6a1-3987-4589-a48f-b392abcd308c.png)

**Comment by GlaDal** [comment]
In this image, it's wrote 'Please share your suggestions for improvement'. Just a feedback but if I don't find an answer to my question in the chatbot, I would want to ask my question to the Qfield team (espacially if you have a pro plan paid). I'm not sure that's the right place to share a suggestion for improvement. Just a feedback ! :-) Thanks

**Comment by mbernasocchi** [comment]
thanks @GlaDal,
normally if the bot cannot answer you it will suggest opening a ticket. how did you get to that window?

Thanks a lot also for the information regarding the video links. We'll look into it.

I'll close this issue and will track it internally since it is not really a QField issue.
