### ISSUE TITLE
OGR error creating feature: Coordinates with non finite values are not allowed

### ISSUE THREAD

**Issue by Dartazen** [opengisch/QField#4035]
### Describe the issue
When I try to add points on some layers on QField, it doesn't work. I didn't have this problem before and the layers haven't been touched since their last use at the end of 2022. It only occurs for some layers, others can be edited without problems, but I tried to find the source of the problem without success. The layer has no geometry problems, and even if I delete all the existing points, the bug recurs. I tried to remove all points, remove the joint, reintegrate the layer, change the layer SCR... None of this works. All layers are in the same editable folder. I have no problem in my desktop on QGIS. I think this bug appeared with the last updates of QField.

### Expected behavior
Edit points layer in QField.

### Observed behavior
"Unable to save changes" message. ERROR: 1 feature(s) not added. Providers errors: OGR error creating feature -3: Coordinates with non-finite values are not allowed.

### Desktop
 - QGIS version: 3.22.0

### Mobile
 - Device: Galaxy A20e
 - OS: Android 11
 - QField version: 2.7.0 (6ca507)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No

Thank you in advance

**Comment by nirvn** [comment]
@Dartazen , could you share one dataset that is now broken in 2.7?

**Comment by nirvn** [comment]
Actually, just confirmed now. Geopackage datasets work but shapefile is busted (since 2.6).

**Comment by nirvn** [comment]
@Dartazen , in 10 minutes or so, APKs will be available in this PR (https://github.com/opengisch/QField/pull/4036) which should fix your issue. Confirmation would be most welcome.

**Comment by Dartazen** [comment]
@nirvn This APKs fix it! Thank you a lot! Do you plan to integrate this patch soon?

**Comment by nirvn** [comment]
@Dartazen , we are planning to roll out a 2.7.1 ASAP, expect an update on the play store within 48 hours.

**Comment by Dartazen** [comment]
Thanks for being quick :)
