### ISSUE TITLE
Location error when moving feature on a rotated canvas

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#4038]
Hello, 

When we move a feature, if the orientation of the map have been changed (top screen not pointing the north), the point will not be located in the correct location. 

As you can see on the video, the feature moves weirdly. Also, sometimes the movement is ok (it doesn't look unusual), but the feature location is auromatically modified right before I save the changes.

https://user-images.githubusercontent.com/72577399/224970632-17842288-bc4c-4408-bb0d-7c00e862edde.mp4

This problem doesn't happen if the orientation point the north. 

Same issue wirh polygons and lines. 

I see 2 solutions: 
- automatically reorient the map to the north before moving
- calculate the correct location according to the map orientation. 

Thank you.

 - QGIS Version [3.28]
 - QFieldSync Version [4.0.1]
 - 
 - Device: [Samsung Galaxy 9]
 - OS: [e.g. Android 11]
 - QField version: [master-dev 19e8b8]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
Confirmed.
