### ISSUE TITLE
Update the language file for minor point release versions

### ISSUE THREAD

**Issue by XuBaocai** [opengisch/QField#4041]
I hope you can update the language file every time you update QField. Thank you! Now every major version is updated, so other languages cannot be updated in time.

**Comment by nirvn** [comment]
@XuBaocai , you mean between 2.7.0 and 2.7.1 or generally? It *should* definitively update across major releases like 2.6 -> 2.7, was there a problem there?

**Comment by XuBaocai** [comment]
Now only the translated language files are read when the large version is updated (such as 2.6.3 ->2.7.0). If new functions are added to 2.7.1, the translated files cannot be updated

**Comment by nirvn** [comment]
@XuBaocai , I've re-opened this as an enhancement request. ATM, our automated translation update system doesn't handle minor point releases. We could try and improve this in the future. 

You sir are one of the fastest QField translator out there, thanks for the efforts you're bringing to this community :)
