### ISSUE TITLE
Import via Dropbox URL places .zip file in 'Imported datasets' not 'Imported projects'

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#4044]
### Describe the issue
When using the new Import from URL function, when downloading a .zip file from Dropbox (even if the .qgs file is in the root location)  QField puts the file in the 'Imported datasets' folder and it doesn't seem to be possible to open it as a project.

### Reproduction steps
1. Open Import from URL dialog box
2. Paste in URL from 'Sample data' below to test 
3. Resulting zip file is put in 'Imported datasets'

### Expected behavior
.zip file with .qgs file in root location should be put in 'Imported projects' and be able to be opened as a project.

### Observed behavior
FIle is opened as a dataset and shows no data.

If app is newly opened and you go straight into the import dialog box and open the imported zip, the screen is blank and there are no layers. 

If a project was opened previously then you navigate back to the home screen and try to open the imported zip from the URL (which is in imported datasets), it loads the structure of the previous project (themes, layer groups) but no actual layers or data.

### Sample data

Project with subfolders: [iOS Test aerial project.zip](https://www.dropbox.com/s/2ylgpzy3su85b0z/iOS%20Test%20aerial%20project.zip?dl=0)

Project with no subfolders (flat folder structure):  [iOS Test aerial project Flat.zip](https://www.dropbox.com/s/tjtmao9g0k2agvr/iOS%20Test%20aerial%20project%20Flat.zip?dl=0)

(Same results if you remove the ?dl=0 part at the end)

So far I have not been able to import anything meaningful from uploads onto WeTransfer, Google Drive or OneDrive as the URL doesn't end in .zip

### Mobile (please complete the following information)
 - Device: iPhone 8 
 - OS: iOS 16.1.1
 - QField version: 2.7.1 2de281

(I have also tested this on an old Android phone with same results but not on a more contemporary Android tablet)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes - function not available in previous versions
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@she-weeds , have you tried dropbox with the URL parameter `dl=0` changed to `dl=1`? It works for me here with the test URLs you provided above.

What happens here is that without the `dl=1`, your telling QField to download the web page previewing the ZIP, not the ZIP itself. it's not only going to go into the imported datasets folder, it'll be an invalid ZIP :)

**Comment by nirvn** [comment]
Just to be clear: you need a URL that links *directly* to the compressed project, not a web preview. That'd also be the case for wechat, etc.

**Comment by she-weeds** [comment]
Aha. Thank you so much - yes it works perfectly now. I didn't realise that was the parameter required to change it to a direct download. The default link given by Dropbox when you share the file has the `dl=0` suffix and I don't think Dropbox have made it clear where to get the immediate zip download link (when I open the web preview I can't right click on the 'Download' button to get a link). 

Could I request including this in the documentation since I suspect the average person will run into the same issue as well.

Will have to figure out what the direct links are for Google Drive and OneDrive, if any. I know nothing about how the actual download links are generated but I did find this while futilely inspecting the source functions for the 'Download' button on OneDrive...

![oh no](https://user-images.githubusercontent.com/41975056/225284581-4c861224-ec71-4612-b69e-e83d783f8f31.JPG)

**Comment by TomKenda** [comment]
With my Iphone and my Android phone, I had the same problem than the one described by @she-weeds here above. When I used the tricks of `dl=1` (for dropbox) or `?download=1` for OneDrive, it worked on my android, but I still have a problem with my Iphone : 
When I copy the link in the import url box, the green horizontal bar start loading, like if the app was downloanding the project, but then, when the green bar is almost full, the application suddenly shut down and the project does not appear in the imported dataset or anywhere else.

I tryed to update my iOS, re-strat my Iphone and to re-install the QField app but it does not solve the problem.

**Mobile** 
Device: iPhone 8
OS: iOS 16.2
QField version: 3.0.5

Do you have any idea of what could cause this ?

**Comment by BoswachterMarc** [comment]
I had a simular problem for a iOs phone and a direct link on Google Drive. The following article was of great help ;-)

https://www.howtogeek.com/747810/how-to-make-a-direct-download-link-for-google-drive-files/
