### ISSUE TITLE
invalid relation

### ISSUE THREAD

**Issue by TNogatz** [opengisch/QField#4049]
### Describe the issue
I'd like to record polygons (biotopes) and take photos of the biotopes. For the photos I created a point layer to save the location I made the photo from. Now I created a relation between the polygon and the point layer - so the ID of the polygon is automatically copied to the points.
In QGIS this works fine.
I've copied the project to the QField Imported Projects folder by cable without any settings in QFieldSync (see attached project).
When I make a point belonging to a polygon > QField shows a message "Ungültige Beziehung" (see attached screenshots).

Viele Grüße an Matthias von Thomas von der FOSSGIS-Tagung

### Screenshots and GIFs
Beispielprojekt: [Test_Beziehungen.zip](https://github.com/opengisch/QField/files/10990787/Test_Beziehungen.zip)

Polygon object no. 3 with related point object "Becken" in QField:
![Screenshot_20230316_131454_ch opengis qfield](https://user-images.githubusercontent.com/26670955/225619790-f1e2e86b-4d8a-4452-b55c-efe5834dd625.jpg)

Tap on "3 - Becken" shows the formular for point object "Becken":
![Screenshot_20230316_131447_ch opengis qfield](https://user-images.githubusercontent.com/26670955/225620180-2d546f2f-bd37-49c1-8e97-ab248e00b14c.jpg)

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.28.4
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - Device: Huawei Mate 9
 - OS: Android 9
 - QField version: 2.7.1

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Thank you for sharing the demo project.

A first inspection shows, that in the .qgs project file, there is no relation configured for the relation reference widget:

```
        <field name="FID_Polygon" configurationFlags="None">
          <editWidget type="RelationReference">
            <config>
              <Option/>
            </config>
          </editWidget>
        </field>
```

Normally in here it should say which relation should be represented by this widget. It seems QGIS has some fallback logic and that's why it works there.
Could you also share the original project (before running it through qfieldsync)?

**Comment by TNogatz** [comment]
Thank you very much for your analysis! Unfortunately I overwrote the original project file. But you've found the problem: I didn't configure the relation reference widget for FID_Polygon! I never did so before because projects worked well without this setting in QGIS. 
Now I've configured the reference widget properly and the project works well under QField. Here's the new project file:
[test_beziehungen.zip](https://github.com/opengisch/QField/files/11009511/test_beziehungen.zip)

So thank you very much for your help! I think we can close this issue. Nothing is wrong with QField - it was my fault. 
Best wishes, Thomas

**Comment by m-kuhn** [comment]
Thank you for providing the necessary information for reproduction (not configuring anything in QGIS).
I have adjusted the behavior of QField to match the behavior of QGIS, as that's what users expect. A fixed version will be out soon.
