### ISSUE TITLE
Suggestion - adding a compass

### ISSUE THREAD

**Issue by ptaconet** [opengisch/QField#406]
It could be interesting to have a compass that shows the direction where the mobile device is pointing to, on the red dot that shows the location, as it is implemented in Google Maps for instance

**Comment by rjwillson** [comment]
this feature would be very valuable to have as long as it uses the device's built in compass sensor when the device has one (most phones and some tablets) 

as it is now I always have to switch to a different GPS app to see what direction I am facing and then switch back to QField

**Comment by m-kuhn** [comment]
Sounds like a very good proposal and not very complicated to do.
If you need an offer for this, please contact us by mail.

**Comment by rjwillson** [comment]
great thanks, I am going to do this in the new year

**Comment by FilipjFry** [comment]
What would actually be awesome, would be to couple the compass with the gyro so that we can take structural measures directly with the tablet. That would be an amazing feature for geologists.

Fry

**Comment by nirvn** [comment]
PR #757 implements this feature request.
