### ISSUE TITLE
Node Tool editing line not well visible

### ISSUE THREAD

**Issue by domi4484** [opengisch/QField#4063]
The red digitizing line is quite thin and difficult to see depending on the background.
When working outside in sun light it can become almost invisible.

![Screenshot_20230323_080949](https://user-images.githubusercontent.com/9881900/227131160-3bff6822-d05a-44b1-801a-cf0d76e555d7.jpg)

**Comment by nirvn** [comment]
This has been massively improved, definitively fixed.
