### ISSUE TITLE
Qfield Cloud Crashes after dwg file import

### ISSUE THREAD

**Issue by tlaslett** [opengisch/QField#4068]
### Describe the issue
[I have imported a series of cad files into a project. Most of the dwg files imported work. One dwg file I had to convert from the latest AutoCAD 2022 version to an older version (2013) as QfieldCloud did not work with the newer file. "Drawing Import Failed (Unsupported Version. Cannot Read AutoCAD 2018/2019/2020 documents)". Once I imported the new file it can be seen no problem on QGIS, an issue arises when I sync with Qfield Cloud. It all transfers and loads correctly but when I go to touch the screen, the ios app crashes. ]

### Reproduction steps
1. [Sync Project via QfieldCloud plugin and create a new project by converting current open project]
2. [Sync with iOS app]
3. [App loads correctly and can be seen correctly on screen]
4. [When the screen is touched and try to scroll or move the map, the app crashes and closes].

### Expected behavior
[Load the dwg files onto Qfield and display as it does on QGIS without crashing.]

### Observed behavior
[App crashes.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

### Desktop (please complete the following information)
 - OS: [Windows]
 - QGIS Version [3.30.0]

### Mobile (please complete the following information)
 - Device: [iPhone 13
 - QField version: [2.7.1 2de281]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

[If the problem happened with QFieldCloud, please add your username and project name.]
[Qfield Login: tlaslett]
[Project File "[Nelligen_FINAL]"

**Comment by nirvn** [comment]
@tlaslett , is this still an issue using latest QField 3.3.10?
