### ISSUE TITLE
Problème Qfield Qgies

### ISSUE THREAD

**Issue by Matdu11** [opengisch/QField#4083]
Bonjour,

Depuis peu j'ai un problème sur Qfield. Quand je travaille sur le terrain et que je prends des photos, les photos ne suivent pas le chemin que j'ai indiqué dans Qgis mais suivent un autre chemin en créant un nouveau dossier files. De plus les photos se nomment toutes QFieldCamera et il m'est impossible de les ouvrir sur l'ordinateur car toutes les photos prisent se créaient sans aucune extension. Pouvez-vous m'indiquer d'où provient le problème?
![Capture d’écran 2023-03-28 083843](https://user-images.githubusercontent.com/129149867/228149673-efdb319e-0f3b-4d6d-ba17-25e48ac1bb58.jpg)

Merci d'avance de votre retour

Cordialement

**Comment by nirvn** [comment]
@Matdu11 , you'll need to give us a few details here. Please show us the expression you have used while setting up your project via qfieldsync plugin, and provide a test project if you can.

**Comment by nirvn** [comment]
@Matdu11 , your photo naming issue should be fixed by these APKs: https://github.com/opengisch/QField/pull/4212
