### ISSUE TITLE
map_get() function not working

### ISSUE THREAD

**Issue by Oli22** [opengisch/QField#4086]
### Describe the issue
I have a geojson dataset containing json values as an attribute.
elevation: `referenceDatum: 1, unit: 0, value: 1`
For displaying the elevation value I use the expression `map_get("elevation", 'value')`.
This works on the QGIS desktop version, but not on QField

### Reproduction steps
1. Add this vector dataset: https://storage.googleapis.com/29f98e10-a489-4c82-ae5e-489dbcd4912f/de_apt.geojson
2. Add a label with the following text: `map_get("elevation", 'value')`
3. See the label displayed on desktop but not on mobile, neither via cable nor cloud sync

### Expected behavior
Label should display as in desktop version of QGIS

### Observed behavior
Label does not display at all

### Additional information
This is not only limited to the use of `map_get()` in labels, but also for the use of the funtion inside of filters etc.

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.30.0
 - QFieldSync Version 4.4.9

### Mobile (please complete the following information)
 - Device: Samsung Galaxy S10E
 - OS: Android 12
 - QField version: 2.7.2 (86617e)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: -
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@Oli22 , please make sure that your layer is set to "copy" for cable exports and "directly access data source" in the cloud section of your project settings' QField panel:

![image](https://user-images.githubusercontent.com/1728657/230714764-f85e397a-3bcd-4f9e-916a-746d49a6efed.png)
