### ISSUE TITLE
WMS Map error from geoportal.gov.pl

### ISSUE THREAD

**Issue by Grynius** [opengisch/QField#4088]
Hello, 
I cant make WMS maps working from geoportal.gov.pl

When I import layer to qgis from
https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution
in QGis everytnig works fine but after exporting by qfield plugin to QField
I get error in QField

Provider is not valid

![IMG_1961](https://user-images.githubusercontent.com/129232528/228389143-a6b5719c-28d8-4242-9ee4-43739a984e55.PNG)

### Desktop 

 - OS: WINDOWS
 - QGIS Version 3.28.4
 - QFieldSync Version 4.4.9

### Mobile 
 - Device: iPhoneXS
 - OS: 16.3
 - QField version: 2.7.2

I didnt manage to make it work at all

**Comment by nirvn** [comment]
@Grynius , is this still a problem with latest QField 3.2.0?
