### ISSUE TITLE
Overwriting pictures on QField for Windows does not work

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#4089]
You still could overwrite the picture with a new one. Anyway, I think you want to **_set your picture field to empty again_** (having no picture on this feature), right? I think this option would make sense indeed.

_Originally posted by @signedav in https://github.com/opengisch/QField/issues/2029#issuecomment-870277077_
   
Overwriting pictures does not seem to work in Qfield 2.7.1 on Windows - if there is a picture already existing, Qfield creates a DCIM folder within the project folder an saves to newly taken picture as "IMG_00000001".

Windows 11, x64

**Comment by nirvn** [comment]
There is no way to overwrite a preexisting picture, this is by design. When adding a new (or replacing a pre-existing) image attachment, the image will be copied and named according to the expression string setup in the vector layer's qfield panel (available when the qfieldsync plugin is installed).

**Comment by meyerlor** [comment]
sorry to gravedig, but i'm running again in this problem and your answer is not exactly clear to me. 

I have set up via Qfield Sync the attachment form perfectly right (when there is no pre-existing picture and i select a random pic from my harddrive it is getting copied into the "Foto_Points" folder and gets the right name as well).
In case there is a pre-existing picture, the pic does not get replaced by the newly selected. Is this wanted behaviour?

**Comment by nirvn** [comment]
@meyerlor , it doesn't get replaced as in the new image isn't shown or as in the old image file stays in the director but the new file image is properly displayed?

**Comment by meyerlor** [comment]
none of those - the new file is nowhere placed on the windows file system (in the set up folder by QField Sync) nor is it displayed in Qfield itself

**Comment by nirvn** [comment]
Can you provide a screencast as well as a test project that replicates this issue?

**Comment by meyerlor** [comment]
Screencast + screenshots of the QGIS (QField Sync) settings: 
[Upload.zip](https://github.com/opengisch/QField/files/12161820/Upload.zip)

Can i send you the project/data via mail? It's customers data so i can not share it here!
