### ISSUE TITLE
Constraints are not recocnized using multiple selections/json fields

### ISSUE THREAD

**Issue by koenigherford** [opengisch/QField#4097]
### Describe the issue
If you define a constraint based on a "multiple-selection" / josn-array-field everything works as expected in QGIS:
![grafik](https://user-images.githubusercontent.com/28433436/228740025-7f69a077-7c80-48ba-be6b-9195c7e21aba.png)

but in QFIELD the constraints are not recognized:
![grafik](https://user-images.githubusercontent.com/28433436/228740646-5c62261d-1f46-4ff9-a1a1-5007f1710b44.png)

### Reproduction steps
1) Create a project with a layer which contains a field "data" of json-field-type
2) create a value relation in the data-field-settings to another value-table-layer
3) select "Allow multiple selections"
4) add a constraint "case when  array_contains(  "data" ,'violating entry 1') then 0 else 1 end"

### Expected behavior
When a constraint-violating-entry is selected in selection-list the constraint shall raise a warning of contraint-violation.
When no constraint-violating-entry is selected the constraint shall accept selections in list.

### Observed behavior
Behavior is observed as expected in QGIS but in QFIELD coinstraint-violation-warnings are raised all times

### Screenshots and GIFs
see above

### Desktop (please complete the following information)
 - OS: [Windows]
 - QGIS Version [3.30.0]
 - QFieldSync Version [4.4.9.]

### Mobile (please complete the following information)
 - Device: [IPad10, Galaxy A10]
 - OS: [IOS, Android 11]
 - QField version: [2,7,2 86617ev2.7.2)

Test-project (QFIELD):
[test_json_constraints_.zip](https://github.com/opengisch/QField/files/11108274/test_json_constraints_.zip)

**Comment by nirvn** [comment]
@koenigherford , the constraint expression in the ZIP in there also doesn't work in QGIS.

Your "data" field is a string type, not an array; you can use this expression:  `"data" is null or strpos( "data",'"violating entry 1"') = 0`

**Comment by koenigherford** [comment]
@nirvn 
Do not know, how this happend in the test-project form above. Excuse me.

Attached a new project with json-data-type again.
![grafik](https://user-images.githubusercontent.com/28433436/231079688-ccbbc444-32ca-4fb7-a83e-bba9a1958074.png)

Different behaviour between QGIS / QFIELD in the last example of the sceenshots. (All results of constraint-checks are resulting with "0" in QFIELD although "1" is expected in last example)
Constraint is defined as `case when array_contains( "json_data" ,'violating entry 1') then 0 else 1 end`

Issue shall be reproducable now with newly attached project.
[test_json_constraints_2.zip](https://github.com/opengisch/QField/files/11197482/test_json_constraints_2.zip)

![grafik](https://user-images.githubusercontent.com/28433436/231073156-36e6fcf8-e594-4653-a2af-3c8437800f59.png)

IPAD 10th gen. IOS 16.4.1.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code revision | f186b8efe0e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
qfieldsync | v4.1.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
[f186b8efe0e](https://github.com/qgis/QGIS/commit/f186b8efe0e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




Active Python plugins
qfieldsync
v4.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

**Comment by koenigherford** [comment]
made project-export above on a different pc with accidentally old qfieldsync-version. But same behaviour too after update to
qfieldsync | v4.4.9:

[test4.zip](https://github.com/opengisch/QField/files/11197953/test4.zip)

**Comment by koenigherford** [comment]
@nirvn 
maybe its another issue, but now i narrowed down why there was a "string-data-type" in my first demo-export project (and constraints are not working there):

If you have a QGIS-project with a json-field-type and launch qfieldsync-tool - settings -cable export and 
1) select "copy" a json-data-type will be preserved in the export-project
2) select "offline-editing" the field-data-type wil be changed to "string"

The conversion of data-types during export-process will not be expected by the user and there will be traps in forgetting to adjust some expressions from "json"/"array"-based-expression to "string"-based-expression

![grafik](https://user-images.githubusercontent.com/28433436/231128313-e2618520-407e-4448-9247-1326d5262446.png)

Result of "copy-export"
![grafik](https://user-images.githubusercontent.com/28433436/231131415-250e8b87-3b1b-47b6-818c-15b116fb0c1f.png)

Result of "offline-editing"-export
![grafik](https://user-images.githubusercontent.com/28433436/231132268-0eb0e1d9-3492-4ed4-af3c-6f02fdd448aa.png)

Nevertheless the issue of not working constraints is remainig in the export-project with "json"-datatype on mobile devices (after "copy"-selection).
