### ISSUE TITLE
With photos widget, default path with expression no longer work with 2.7

### ISSUE THREAD

**Issue by zzzef** [opengisch/QField#4098]
Hello, 

With photos widget, default path with expression no longer work with 2.7 (ok with 2.6 for example). 

Example joined for test. 
[issue_dcim_expr.zip](https://github.com/opengisch/QField/files/11111576/issue_dcim_expr.zip)

Expression example with attribute "ph1" (alias "photo_expr") : 
'DPH' || format_date(now(),'yyyy') || '/PHO' || format_date(now(),'yyyyMMdd_hhmmsszzz') || '.jpg'
For this example I have simplified the expression. In reality I'm using an expression that calculates the folder name and the file name from data.  

Before, a folder was created and the file was named correctly by the expression. All in relative path. Now the files are named JPEG_20230330113828118.JPG in the DCIM folder. So impossible to organise the photos. 

Env : 

    QGIS 3.22.16 on Windows

    OS: Android 10 on Mi Mix 2s

    QField version: 2.7.2

**Comment by EricM71** [comment]
Hello !

Sorry no solution here but I have the same issue with QGIS 3.20, QFIELD 2.7.3 and Android 13

**Comment by nirvn** [comment]
@EricM71 , you are not putting your expression in the right place. I.e., the default path setting is _not_ where you put the expression.

You need to install the qfieldsync plugin, which will add a new QField panel in your vector layer properties:
![image](https://user-images.githubusercontent.com/1728657/230714397-bd7d8514-615d-435f-a5c9-c2a7a9686449.png)

In that new panel, you find your field name in the attachment naming table widget, add your expression there.

Cheers.
