### ISSUE TITLE
Enhancement suggestion: Duplicate child feature

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#4099]
At the moment, it is possible to duplicate mappable features after selecting them on the map and then long-press the feature in the feature-list. It would be nice to have this option as well for non-mappable features.

Reason: To use QField for revisiting sites more efficiently it would boost productivity alot when it would not be necesary to fill all the unchanged observations again

**Comment by Ipickedausername** [comment]
Hi, 

In which situation do you need to have several child with the same information, assoaciated to the same parent ? 

To make it maybe more interesting, it could be useful to be able to duplicate parent + child to another location, and only updating the id (to differentiate it from other parent).

**Comment by nirvn** [comment]
@meyerlor , duplicating features now duplicate children of relationships set in composition mode.

**Comment by meyerlor** [comment]
@nirvn this is very helpful already, thanks for implementing this!
Unfortunately, thats not exactly what I suggested in the first post: In my use case not the parent + child should duplicated but only the child of a parent. 
Example: Trees need to be observed on a yearly basis. On the first visit, a funghi was found as well as some dead wood. Both will be entered in the observation. Next year, this funghi and dead wood will still be there - so to save time, it would be easiest to just duplicate the first observation, put the right date/time and add new observable things etc.
