### ISSUE TITLE
Problème d'affichage apres enregistrement des modifications

### ISSUE THREAD

**Issue by pierre-gil** [opengisch/QField#41]
Mode: Parcourir
Geometrie selectionnée: point
Type de couche: Shape

J'appui sur les points (même géolocalisation) - apparition du menu à gauche - j'appui sur le crayon - je modifie un menu déroulant - j'enregistre - je passe au point suivant - si je reviens sur le point précédent je ne retrouve pas les informations saisies - pour les retrouver je dois fermer le menu de gauche puis le ré ouvrir.

Merci

**Comment by m-kuhn** [comment]
Quelle version?

Est-ce que tu peux verifier demain avec la nouvelle version 0.6.1?

**Comment by pierre-gil** [comment]
Bonjour,

Vérification effectuée. Version 0.6.1. Toujours le même problème.
Yablette Samsung galaxy Tab Active

Bonne journée

Le mer. 29 juin 2016 à 22:16, Matthias Kuhn <notifications@github.com> a
écrit :
