### ISSUE TITLE
Android devices no longer autoloading Qfield files

### ISSUE THREAD

**Issue by toddb88** [opengisch/QField#4116]
### Describe the issue

We are running Sales Force Field Service (FSL) and QField on multiple android devices.

All are running the latest app versions of FSL and QField. There is a combination of devices from CT8 and CT8-2 rugged tablets to Samsung galaxy tablets.

The Android versions are therefore 8.1 to 10 and 11 the latest for their hardware We have turned off MFA security in Salesforce. In the past 2 weeks, the majority of the 20 devices no longer will autoload our usual QField zip files from the FSL/Saleforce app. I have spoken to SF and they advise no change their side.

Whilst we can open the file from Outlook and download to a directory and then open the files successfully, the ease of use for our field technician to open the QField file from the FSL/SF app makes it much easier.

The Current Process

The QField files are stored in SF and show up in FSL app
The field technician clicks on the QField file in FSL and Android asks which app to open the files. We select the QField app.
The system then loads the QField app and goes through its normal file loading process.
The system then displays the navigation screen, but only with our location point but no points/data brought in.
Their is an error log which relates to the project file saying the files don't exist (see below)
This has only started to occur in the last 2 weeks.
It seems to be file directory is the root cause of our issues, but I cannot work out why and how to change this across 20 devices.
The error is:

project files "/storage/emulated/0/android/data/ch.opengis.qfield/files/imported database/(our file name added here).zip" does not exist

What would have caused this change?

### Reproduction steps
1. [Go to '...']
2. [Click on '...']
3. [Scroll down to '...']

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - OS: [e.g. Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by m-kuhn** [comment]
This seems to be very specific to the combination with SF and the specific workflow.
I am not aware of any generic explanation for that.
You could try to download older versions and see if that helps.
