### ISSUE TITLE
GNSS on Windows 11 working only with "Maps" application opened

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#4119]
I installed Windows QField 2.7.1 on a Surface 7+ with internal GPS reciever. It is running on Winodws 11. 

QField only gets a location fix (and continuos updates of the location) while having the "maps" application opened. This is OK for now as a workaround, but the dataplan gets depleted quite fast that way :)  As reading through the thread https://github.com/opengisch/QField/issues/2038#top GNSS on Windows should generally work, but everyone seems to be using Windows 10 - so this might be a Windows 11 only issue?

**Comment by nirvn** [comment]
@meyerlor , is it still an issue with QField 3.2? The update to Qt6 gives me hope you'll see this working properly now.
