### ISSUE TITLE
QField document provider spinner

### ISSUE THREAD

**Issue by 3nids** [opengisch/QField#414]
show a spinner when the provider is scanning the directories.

note: are the documents shown whenever found, or does it wait for the whole process to finish?

**Comment by 3nids** [comment]
@marioba any chance to have this this week for a release?

**Comment by marioba** [comment]
I'll try. I can not guarantee it because I'm super full of work this week...

**Comment by marioba** [comment]
I close because with the new implementation of the file selector it is no longer needed.
