### ISSUE TITLE
[Enhancement] Alphabetical sorting of the features list

### ISSUE THREAD

**Issue by TNogatz** [opengisch/QField#4145]
### Description of the problem
If you are heading to the features list, the entries are displayed in the order in which they were created: 

![01_Objektliste_Aufruf](https://user-images.githubusercontent.com/26670955/230843202-8de24194-a331-4eaf-9f84-ac94f7853b3e.png)

![02_Objektliste_Anzeige](https://user-images.githubusercontent.com/26670955/230844514-1f1d5182-5222-4605-8c5c-0ff782247f09.png)

It would be useful, especially with long lists, to have the entries in alphabetical order. But there is currently no way to change the order. 

In QGIS the features list is in alphabetical order by default and the order can be defined:
![03_QGIS_Objektliste](https://user-images.githubusercontent.com/26670955/230846068-3345cf88-f9f3-4b22-a5db-0bd66ff12c25.png)

### Feature request
It would be great to have the possibility to show the features list sorted alphabetically in QField as well.

**Comment by nirvn** [comment]
@TNogatz , the following PR implements this enhancement: https://github.com/opengisch/QField/pull/4192

**Comment by TNogatz** [comment]
Have just tested the APK - works well! Thank you very much!

**Comment by nirvn** [comment]
Implemented.
