### ISSUE TITLE
Warn when opening a 2.18 project?

### ISSUE THREAD

**Issue by 3nids** [opengisch/QField#415]
Some have been reporting bad results with the search (long respond time, probably due to huge number of layers). As layers are all searchable by default, this seems well possible.
But you can configure searchable only in QGIS 3.4+

I would propose to display a message in QField when opening a project of 2.18, something like: you might encounter issues or sub-optimal results.

Even maybe for <3.4 ?

Opinions?

**Comment by m-kuhn** [comment]
While it's *possible* to configure the search with 3.4, it's still on by default, so the same happens if no configuration is done. Correct?
In this case, I am not sure a warning about the project version is the right criteria for a warning.

**Comment by 3nids** [comment]
agreed

**Comment by saemiw** [comment]
What about a warning "All your layers are searchable - be aware that this can slow down the searching process" (or similar) that appears only when all layers are searchable? Just an idea - I am open for more sophisticated solutions...;D
