### ISSUE TITLE
Get Started Page is missing copy folder location

### ISSUE THREAD

**Issue by arc12** [opengisch/QField#4157]
This page:
https://docs.qfield.org/get-started/tutorials/get-started-qfs/
does not provide the location to which the package folder should be copied to for Android users.
This would be very helpful for people getting started!
I suggest locations for both "internal" and SD storage should be provided.

**Comment by nirvn** [comment]
Closing this, filed a relevant issue in the QField-docs repository (https://github.com/opengisch/QField-docs/issues/347)

@arc12 , we'd most welcome a pull request on the QField-docs repository with relevant additions.
