### ISSUE TITLE
Feature already existing in supposed empty new project. 

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#4168]
Hello, 

When I create a new project, I synchronize it and I paste the folder in my phone. All the layers are empty, except one. 

When I open it on QField, through : /storage/emulated/0

I can find some layers already filled with "test" data.  Those are testing features that I've added during my tests. They don't appear in my project on QGIS. 

Even weirder, when I create a new project, with another name, to compare, and I import it on my phone. The first layer is empty, as expected, but a second one has other test features ! 
I tried a third time, and another layer... 

Do you know what can cause this issue ? 

I add QGIS and Qfield test projects, if you want to give a look. But I think it comes from my phone.
Before testing on my phone, I made sure the other projects are deleted, so I only have one project at a time to make the tests. 
It looks like my phone remembers some data. 

[ProjectQGIS.zip](https://github.com/opengisch/QField/files/11224297/ProjectQGIS.zip)
[Uploading ProjectQfield.zip…]()

**Comment by Malvineous** [comment]
When you open a project, you need to import it from a folder into QField.

Are you importing your project, or are you writing the files over the top of QField's data files?  If you are overwriting QField's files this might be the problem.  Try copying the files to a normal location (e.g. 'Downloads' folder) then using QField to import the project, and choose yes you want to overwrite the existing project with the same name.

This is what I do and I have never noticed anything left behind from old projects.

**Comment by Ipickedausername** [comment]
Hi, indeed, I try to overwrite, because when I'm importing the files, there is an error. 
I will open an issue related to this error and close this discussion because the problem is probably somewhere else. 

Thank you for your reply !
