### ISSUE TITLE
[Enhancement] Make it faster to show/hide layers

### ISSUE THREAD

**Issue by Malvineous** [opengisch/QField#4173]
Currently, in order to show/hide a layer, you have to open the layer list, press and hold for a few seconds on the layer, then tick a box to show or hide it, then press on the map to close the layer list.

This process is very slow if you want to quickly show or hide a layer, for example to hide one with labels that are obscuring your view, but then show it again to remind yourself what the labels said.

I would like to request a quicker way of showing and hiding layers.

One suggestion that might be quick to implement is to allow a layer to be double-tapped to toggle its visibility.  Currently double-tapping a layer does nothing (it only expands or shrinks a double-tapped group) so this might be a good way to put an otherwise unused action to good use.

**Comment by felixpekarek** [comment]
I would also love to see that function. Our field workers are happy with the application but we often need to turn on or turn off some layers (especially when working with imagery). It just takes too much time for them, to change the visibility of the layers. Double tapping the layer to change the visibility would be great!

**Comment by suricactus** [comment]
Note you can use "map themes" as in the sample bee project to have a dropdown with preconfigured visible layers.

**Comment by hensjl** [comment]
A quicker way to show and hide layers is a must, but why not a tick box in front of layers name like in QGIS ?

**Comment by larslund** [comment]
There is a limit somewhere in how much detail-management via QField makes sense. In my opinion the implementation of change order possibilty and an opacity-slider would be an overkill, adding complexity to the UI for functions which may not be needed by most users and distracting to some.

The quickest way to turn on/off layers would be a double tap.

**Comment by jfdarveau** [comment]
I believe this is a must too! In my opinion, just a little "eye" icon to the right of the layer in the left pane would do the trick and look good. I would also like to add that an easier way to explode/implode layers would be very useful too. It could only be by tapping the arrow left of the layer. Since both features are currently accessible by long pressing the layer, I thought it was worth mentioning this too.

**Comment by nirvn** [comment]
This has been implemented, enjoy! :)

**Comment by Malvineous** [comment]
The feature works really well!  Thanks for implementing it!
