### ISSUE TITLE
Unable to remove default projects from "recent projects" screen

### ISSUE THREAD

**Issue by Malvineous** [opengisch/QField#4174]
### Describe the issue
When I launch QField, or return to the Home screen, there are three default projects listed - "Bee Farming Sample Project", "Wastewater Management Sample Project" and "Live QField Users Survey".

I want to remove these on a family member's device, so that they do not press them by accident and then get confused about why they cannot see my project.

When I long-press on these a menu appears with the option "Remove from Recent Projects" however when I select this nothing happens, the projects remain visible.

### Reproduction steps
1. Go to the Home screen
2. Press and hold on one of the default projects, e.g. "Bee Farming Sample Project"
3. Select "Remove from Recent Projects"
4. Observe the project cannot be removed

### Expected behavior
The project should be removed from the list.

### Observed behavior
The project remained visible, and was not removed from the list.

### Mobile (please complete the following information)
 - Device: Pixel
 - OS: Android
 - QField version: 2.7.4

### Additional information
* It would be useful to display the QField version number on the Home screen, so you can see it without having to open a project first!

**Comment by nirvn** [comment]
@Malvineous , the APKs here (https://github.com/opengisch/QField/pull/4176) should fix the reported issue.

**Comment by nirvn** [comment]
@Malvineous , also, a new feature that will make its way to 2.8 might be of interest to you: https://github.com/opengisch/QField/pull/4175

**Comment by Malvineous** [comment]
That worked perfectly!  The build lets me remove the sample projects and they don't come back.  Thanks for such a quick fix!

The other one (reload last project) looks like it will be very useful too.  I hope it will appear in the next release!
