### ISSUE TITLE
Inside dcim folder didn't create jpg attach but a new "files" folder is create inside the smartphone

### ISSUE THREAD

**Issue by cristianocastaldi** [opengisch/QField#4178]
### Describe the issue
I use qfield 2.7.4 and qgis (both 3.18 and 3.30 on w10). For a week now, the photo attachments in the project's DCIM folder have not saved them, but it creates a "files" folder where it creates a file "20230416125525765_QFieldCamera20230416_1455257636045758982092301" and I don't understand why. I did n times the attribute form but nothing. The only message that has appeared to me once is the one attached, I don't know if it could be due to this

### Reproduction steps
1. i take a photo on smartphone with qfield
2. A new folder is created inside project folder on smartphone with "files" name
3. For each photo a new file as this is created: "20230416125525765_QFieldCamera20230416_1455257636045758982092301" 

### Expected behavior
I would like a file to be created for each photo in the DCIM folder

### Observed behavior
Attach the screenshot of pyton error

### Desktop (please complete the following information)
 - OS: [ Windows]
 - QGIS Version [e.g. 3.18. and 3.30]
 - QFieldSync Version [e.g. 2.7.4]

### Mobile (please complete the following information)
 - Device: [e.g. samsung galaxy A71 or A53]
 - OS: [e.g. Android 13]
 - QField version: [2.7.4]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

![errore pyton](https://user-images.githubusercontent.com/130918806/232324184-6c37eed1-4129-4449-ab8a-0955fd7275c6.jpg)

**Comment by nirvn** [comment]
@cristianocastaldi , your photo naming issue should be fixed by these APKs: https://github.com/opengisch/QField/pull/4212
