### ISSUE TITLE
Feature is captured (saved) even when digitizing is cancelled

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QField#4179]
### Describe the issue
When all mandatory fields are completed, but the regretting and hitting the garbage bin to cancel the recording, the feature is still being saved.

### Reproduction steps
Download and unpack the zip-file and transfer it to QField and start digitize a point (the layer named "arter"). As long as not all mandatory attributes, I may cancel the recording (no point is saved). But when all demands are fulfilled (the frame turning green), the point is saved even though I choose to click the rubbish bin and confirm the cancelling. See images below.
[humleregistrering.zip](https://github.com/opengisch/QField/files/11243177/humleregistrering.zip)

### Expected behavior
I was expecting no feature would be saved.

### Observed behavior
The feature is saved even when cancelling.
In QGIS:
Cancelling is respected, i.e. the point is not recorded. However, if Blomster, Humler and/or Sommerfugler (Value relation widgets) is entered and then cancelling, the records are not deleted in their corresponding layers blomstereg, humlereg and sommerfuglreg. But, we're using QField, so it's most important for us that the cancelling works in QField. If not possible to fix, the solution will be to delete the point after is mistakenly has been saved.

### Screenshots and GIFs
Put the arter-layer in digitize mode
<img src="https://user-images.githubusercontent.com/10632163/232330219-b8cc228e-73f2-45cd-ab14-7a1a8dab1ef0.jpg" width="500"/>

#### 1 Cancelling when all in order (green frame)
Recording a point intersecting with line segment no. 14
<img src="https://user-images.githubusercontent.com/10632163/232330233-5e26894e-ff73-4ace-b9f9-75dce8c77726.jpg" width="500"/>
Entering all required fields
<img src="https://user-images.githubusercontent.com/10632163/232330255-ce6f206c-e72b-4673-834b-40b73d70eea6.jpg" width="500"/>
Regretting and hitting the garbage bin and confirming dismissing
<img src="https://user-images.githubusercontent.com/10632163/232330307-ec558853-e04b-4adf-8f59-f57600070501.jpg" width="500"/>
Nevertheless, the point is recorded?!?
<img src="https://user-images.githubusercontent.com/10632163/232330346-54a568cd-6b5b-4228-9876-709f6f0354f9.jpg" width="500"/>

#### 2 Cancelling when something is still missing (red frame)
Recording a point intersecting with line segment no. 13 and NOT filling out all required fields and hitting the garbage bin
<img src="https://user-images.githubusercontent.com/10632163/232330363-47f1d4bb-dc2c-4aae-a092-bedc694f4a94.jpg" width="500"/>
Confirming the cancelling
<img src="https://user-images.githubusercontent.com/10632163/232330382-c0796d16-b99d-4494-b820-674b50a1e047.jpg" width="500"/>
No point is being recorded (saved)
<img src="https://user-images.githubusercontent.com/10632163/232334065-ce760293-c18c-4fcf-9905-fd3d28ea5793.jpg" width="500"/>

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.30
 - QFieldSync Version 4.4.9

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab S4
 - OS: [e.g. Android 10
 - QField version: 2.7.4 (836225)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Don't know

The issue occurs both when retrieving the project on the tablet from QFieldCloud or from QField Sync with cable.

**Comment by nirvn** [comment]
@9ls1 , do you have fast editing mode enabled by any chance?

**Comment by 9ls1** [comment]
No, I don't - fast editing mode is turned off.
(Sorry for not mentioning this, but I was actually not aware of this option in the Settings - now I am.)

**Comment by nirvn** [comment]
@9ls1 , OK; I've not been able to replicate this (e.g. with the sample bees farming demo). Could you attach a project with which you can replicate this issue?

**Comment by 9ls1** [comment]
@nirvn Just tested the project on another tablet: Samsung Galaxy Tab Active 3 with **Android 13**. Here everything is working as expected. Whenever I choose to cancel the recording (regardless if species are chosen), no point is captured and saved. 😊 
On the older tablet with Android 10, points are captured when cancelling after a specie is chosen.
Strange or just due to differences in Android version?
