### ISSUE TITLE
Not able to import project anymore. "The following layers could not be loaded, [...]"

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#4180]
Hello, 

When I try to import a project from a folder located in my phone (using the green [+] button), I receive an error on every layer.
I got this error before when I started creating this project, and one day it disappeared. 

I have made some change on the project and now, the error is back. I have no idea on what is causing it, and the message log isn't giving much information. It just looks like it is related to the location of the layers. 

Here is a screenshot of the message log:

![image_viber_2023-04-17_05-45-48-861](https://user-images.githubusercontent.com/72577399/232344809-4689d973-d63b-4ee7-b393-6d7daa4c660d.jpg)

And my project:

[ProjectQfield.zip](https://github.com/opengisch/QField/files/11244734/ProjectQfield.zip)]
[ProjectQGIS.zip](https://github.com/opengisch/QField/files/11244731/ProjectQGIS.zip)

Thank you. 

QGIS Version [3.28]
QFieldSync Version [4.0.1]

Device: [Samsung Galaxy 9]
OS: [e.g. Android 11]
QField version: [master-dev (6f9d5f)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@Ipickedausername , looking at your screenshot, the layers path is outside the root directory of your .qgs project, you should insure that all of your dataset are sitting alongside the .qgs project file or in sub-directories relative to the project file.

**Comment by Ipickedausername** [comment]
Thank you for the answer. 
I tried exporting the project on the desktop, and now it works. 

I recently changed the way I organize my projects and I stopped exporting the desktop. Well now it is working!
