### ISSUE TITLE
Remote layers not loading in android version

### ISSUE THREAD

**Issue by Oli22** [opengisch/QField#4185]
### Describe the issue
A vector .geojson layer is not loading via vsicurl on the android app, the windows app works just fine

### Reproduction steps
1. Add [this vector layer](https://storage.googleapis.com/29f98e10-a489-4c82-ae5e-489dbcd4912f/de_apt.geojson) as directly accessed layer via https
2. Set QField to directly access data source in QField project properties
3. See it working with the windows app but not on android

### Expected behavior
Should work same on all platforms

### Observed behavior
Only works in windows version.
Android version shows below given error

### Screenshots and GIFs
![QField_Error-2](https://user-images.githubusercontent.com/18697989/232594383-7bdd81fb-ea8f-49b8-8ba7-4cdaa72c2cbd.jpeg)

Error within project messages
![QField_Error-1](https://user-images.githubusercontent.com/18697989/232594381-e0abc7f0-b18d-4dd0-9bbb-201a994f5680.jpeg)

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.30.1
 - QFieldSync Version 4.4.9

### Mobile (please complete the following information)
 - Device: Samsung Galaxy S10E
 - OS: Android 12
 - QField version: 2.7.4 (836225)

 - OS: Windows 10
 - QField version: 2.7.4 (836225)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Unknown
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by Oli22** [comment]
Additional testing on my side revealed that IOS is also working as expected with QField 2.7.4 (836225)

**Comment by nirvn** [comment]
Fixed.
