### ISSUE TITLE
Qfield crashes when loading project from qfieldcloud

### ISSUE THREAD

**Issue by antoniusz** [opengisch/QField#4195]
Hi,

Qfield crashes when loading any project from qfieldcloud. All versions, since 2.7.2, are affected.
The device is a Spectra Precision MobileMapper 50 with android version 6.0.1.

If i synchronize the project via cable, there is no crash, it opens nicely.
Another device running android 11 doesn't have the problem.

When it crashes, the system offers to send an error report, which I did, several times, but I don't know where it goes.

**Comment by nirvn** [comment]
Confirmed by sentry (reference: https://opengisch.sentry.io/issues/4037513524/?project=6119013&query=is%3Aunresolved+device.family%3AMobileMapper50_4G&referrer=issue-stream&statsPeriod=14d&stream_index=0)

**Comment by nirvn** [comment]
Fixed.

**Comment by antoniusz** [comment]
yes, solved it. Thank you!
