### ISSUE TITLE
Fatal error on Asus zenfone 5

### ISSUE THREAD

**Issue by ngocducgis** [opengisch/QField#42]
Hi, i've just install QField to my Asus zenfone 5 but it just crashed. Error: "Your application encountered a fatal error and cannot continue". Please check this, thank you! :)

**Comment by m-kuhn** [comment]
Which Android Version?
At what point did it crash?

**Comment by ngocducgis** [comment]
Sorry I'm using Android 5.0, It crashed when I first run app

**Comment by m-kuhn** [comment]
Can you send us a report with the "Unfortunately QField has stopped" dialog.

Or use this https://github.com/opengisch/OSGeo4A/wiki/Debugging

**Comment by m-kuhn** [comment]
Probably fixed with 0.8.7

If it persists, please open a new issue and provide additional information to reproduce.
