### ISSUE TITLE
Cannot save pictures as child features of another layer in QField 2.7

### ISSUE THREAD

**Issue by DCTN54** [opengisch/QField#4213]
### Describe the issue
Since last update (QField 2.7) I cannot save pictures as child features of another layer from a form in QField.

### Reproduction steps
1. Create one "points" layer (shapefile) and one "pictures" layer (dbf file)
2. Create a relation 1 to n between them on id field (associating several pictures to one point feature)
3. Create the attributes form in the "pictures" dbf layer properties like in screenshot 1 below
4. Create the attributes form in the "points" layer properties (drag and drop designer) and call your point-to-pictures reference like in screenshot 2 below
5. Copy your QGis project to Qfield and try to add a feature to "points" layer, and then attach pictures to that feature through the form

### Expected behavior
  Before last update, the list of pictures taken for each point were visible in "points" layer's attributes form, both in QField and QGis (after importing QGis project back into computer).

### Observed behavior
   Now the pictures don't appear in the "points" layer's  attributes form anymore, altough the pictures are correctly stored in my pictures folder, and their path and attributes are correctly recorded in the "pictures" dbf file.
This problem is obviously related to QField and not QGis becaus points created in QGis show their attached pictures as they should.

### Screenshots and GIFs
  
Screenshot 1

![image](https://user-images.githubusercontent.com/128024911/233623631-ce6ff0ac-b43c-485e-8c31-4b155b7fbd92.png)

Screenshot 2

![image](https://user-images.githubusercontent.com/128024911/233624333-4cc54831-37ca-46d9-b7ba-c70de48f6890.png)

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.22.6

### Mobile (please complete the following information)
 - Device: Samsung Galaxy TabActive 2 and 4 (both show the same behaviour)
 - OS: Android 9
 - QField version 2.7.3 (c42fb5) and 2.7.4 (836225)
 - .

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@DCTN54 , can you attach a simple test project to replicate the issue here?

**Comment by DCTN54** [comment]
[test.zip](https://github.com/opengisch/QField/files/11295450/test.zip)

**Comment by nirvn** [comment]
@DCTN54 , the problem lies in your project settings. You have enabled [x] apply default value on update for the "id" attribute of your RELEVE_PHOTO_PT layer, which means that every time you save you save/edit your layer, the "id" value changes, which is bad considering you are using that as your join value :scream: :wink: 

Simply uncheck that setting and you'll get your list working again:
![image](https://user-images.githubusercontent.com/1728657/233637546-c8c88538-1794-44c2-a986-0eba3e0f5cbd.png)

**Comment by DCTN54** [comment]
Of course^^
Thanks a lot
