### ISSUE TITLE
Font missing for Linux AppImage

### ISSUE THREAD

**Issue by kannes** [opengisch/QField#4225]
### Describe the issue
The font is a thin monospace font, probably not as intended.

### Reproduction steps
1. Download https://qfield.org/get_latest/?platform=linux (qfield-v2.7.5-linux-x64.AppImage)
2. Run the AppImage
3. Look at the fonts

### Expected behavior
~~Font should be as beautiful as the project itself.~~ Font should be as beautiful as in the Windows version.

### Observed behavior
Font looks thin and monospaced.

Terminal shows error about fontconfig:

```
...
Proj path:  "/tmp/.mount_qfieldsWAJ1R/usr/share/proj"
Fontconfig error: Cannot load default config file: No such file: (null)
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
...
```

I guess it is using some bad fallback.

### Screenshots and GIFs
AppImage:
![grafik](https://user-images.githubusercontent.com/7661092/233953616-616745df-8478-4af1-9010-7df7488caf82.png)

Windows version via Wine:
![grafik](https://user-images.githubusercontent.com/7661092/233954093-3e2affa0-a40e-4414-b927-484265ca6e8d.png)

### Desktop (please complete the following information)
 - OS: Ubuntu 22.04.2 LTS
 - qfield-v2.7.5-linux-x64.AppImage

**Comment by m-kuhn** [comment]
Fixed by https://github.com/opengisch/QField/pull/4228 ?

**Comment by kannes** [comment]
Probably! Can't be arsed to compile ;)

**Comment by m-kuhn** [comment]
Normally the action should build that for you but something seems to be borken ... Let's see if that latest commit fixes things.

**Comment by kannes** [comment]
Looks good, thank you!

**Comment by kannes** [comment]
Screenshot from the same system as before:
![grafik](https://github.com/opengisch/QField/assets/7661092/369da16d-be25-4efa-a844-b165742f38cc)

:heavy_check_mark:
