### ISSUE TITLE
Labels in Background Map (osm) too Small to Read

### ISSUE THREAD

**Issue by hensjl** [opengisch/QField#4249]
One year later the problem remain unchanged. 

Same with Samsung Galaxy A70 and with qfield-v2.7.6-linux-x64.AppImage

### Discussed in https://github.com/opengisch/QField/discussions/3043

<div type='discussions-op-text'>

<sup>Originally posted by **sledbird** July  4, 2022</sup>
Hi Everyone, 

I've noticed that there seems to be a an issue between the screen resolution and the zoom level of the tiles that are delivered in the background map. All of the labels of street names, cities, etc. are not legible at wider zoom levels. Only by zooming in to the last 2-3 levels of the background map are the labels visible. This works sometimes when trying to identify a street name, but becomes quite difficult when trying to look at a city name for example. I've been using this app for over a year on the same phone and it seems to be something that appeared only more recently, like 3-4 months ago, but I'm not certain of the timing.

Attached are four screen shots using the Simple Bee Farming Demo included in the app and the online OSM background layer. Interestingly, the information is delivered to the phone, because you can actually read the labels when you zoom into the screenshot image, just not on the phone itself. I.e. trying to zoom in on the phone calls different zoom levels of the background map. 

I've tried using different screen and font sizes in the system settings of the phone, but no luck. I am using a Google Pixel 4a on an Android 12 phone.

Anyone else have this problem and found a solution?
![Screenshot_20220704-074736](https://user-images.githubusercontent.com/71427498/177091371-486a622c-3d5f-431b-a3ed-3127a421b469.png)
![Screenshot_20220704-073419](https://user-images.githubusercontent.com/71427498/177091392-a9b5f833-c557-426b-adb5-9efdac6ceaa8.png)
![Screenshot_20220704-073434](https://user-images.githubusercontent.com/71427498/177091402-1455b56c-492e-4a6c-a5d1-3f7e046d123c.png)
![Screenshot_20220704-073511](https://user-images.githubusercontent.com/71427498/177091407-4d97cbf3-8b61-4874-a616-f4d6bb3ca44a.png)
</div>

**Comment by nirvn** [comment]
@hensjl , QField doesn't ship with the pair of "simple" and "advanced" bees sample projects,if you still see that, I advise you to update ASAP :)

For your own projects, make sure the added OSM basemap has its DPI explicitly stated (look at the tile resolution combobox below):
![image](https://user-images.githubusercontent.com/1728657/235611705-1fcb946c-fb2f-4a60-81e7-2b7728dc9cdd.png)

For individual datasets opened in QField, I've just opened a fix that'll insure the default OSM basemap works for highdpi.

**Comment by hensjl** [comment]
Thank you @nirvn for this very quick answer.

Tile Resolutions are limited to:
Standard (256x256 / 96 DPI)
High (512x512 / 192 DPI)

The result is good on my computer (with qfield-v2.7.6-linux-x64.AppImage too, sorry)

My phone screen has 420 DPI.

I don't know what way you are going to use for the fix you just opened but, I think that adding a magnifier factor (same as QGIS) in setting should do the job. Maybe you can set the default value to 200% for android application.

Keep on the good work, Thank you.
