### ISSUE TITLE
Default map theme

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#427]
In QGis I save my project with a choosen map theme. When opening the project, it shows this map theme. In QField, it shows the first map theme of the list.

### Expected behavior:

Open the project in QField with the same map theme as QGis

### Observed behavior:

QField open the first map theme of the list instead of the choosen map theme last shown in QGis before saving the project.

**QField version:** 0.11.11

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Not tried

**Comment by 3nids** [comment]
fixed in #459 and coming in 1.0 RC3
