### ISSUE TITLE
Geopackages still open when closing QField project

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/QField#4278]
### Describe the issue
When closing the project after some fieldwork, the geopackage remains open (.wal files..). And the project is therefore not syncable with Qfieldsync. The problem happens not with every project we run, the simple one are closing properly, but the little advanced ones are not closing. Closing the app takes more than 10s and it looks like somekind of runtime error..

when reopening the project and closing it directly again the geopackage is closed properly.

### Reproduction steps
1. Close Project
2. Check the Folder
3. geopackage is not closed

### Desktop (please complete the following information)
 - OS: MAC OS
 - QGIS Version 3.28
 - QFieldSync Version 4.4.9
### Mobile (please complete the following information)
 - Device: Samsung Tab active 2&3
 - OS: Android 9 &12
 - QField version: 5f7236 v2.7.5

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No

**Comment by nirvn** [comment]
@EulenspiegelTill , would it be possible to share the advanced projects with which you are able to replicate the issue here? You can send over to mathieu@opengis.ch .

**Comment by EulenspiegelTill** [comment]
@nirvn it's the one you allready had from us.

**Comment by nirvn** [comment]
@EulenspiegelTill , do you mind resending? I've expunged that project after we fixed the previous issues

**Comment by EulenspiegelTill** [comment]
@nirvn the provided #4326 seems to resolve the problem fine. gpkg is closed properly. Thanks!

**Comment by nirvn** [comment]
@EulenspiegelTill , perfect, we'll release 2.8.2 ASAP.
