### ISSUE TITLE
Expanded groups of layers with map themes

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#428]
QGis 3 allows controlling expanded view of groups of layers with map themes. Each map theme rules the behaviour of these groups.
Not a priority but could be useful in QField especially for projects containing lots of groups of layers.

**Comment by 3nids** [comment]
This is not possible at the moment since we don't have a proper tree view for the legend.
Qt has not implemented it yet, see upstream ticket https://bugreports.qt.io/browse/QTBUG-61630

This will not be fixed in a short term.

**Comment by signedav** [comment]
For information, the tree view issue on QT:
https://bugreports.qt.io/browse/QTBUG-61630

**Comment by nirvn** [comment]
Here's why all the energy on the new legend was worth it: we were able to fix things like that. 🥳
