### ISSUE TITLE
QField check boxes already checked

### ISSUE THREAD

**Issue by LordDuck71** [opengisch/QField#4287]
### Describe the issue
I encounter a huge problem with check box widgets (Boolean True False) in QField since the last update. 
When I add a new feature in QField it automatically marks those boxes as "checked" that were checked in the previous feature. Funny thing though is that the value (True or False) that appears in the attribute table is not the one showed by the check box.
For example:
First feature: I add a Bird (Point Feature) and I check the box "Singing" (here everything is fine, in attribute table the attribute "singing" is showed as 'TRUE')
Second feature: I add a second Bird. The "Singing" box is already checked but in attribute table it shows 'ZERO'.

 If I uncheck and check it again it takes over the value.

So I think it's maybe a graphical issue. The Check box is shown as checked but in fact isn't. 

### Reproduction steps
1. in QGIS create a formular with check boxes. For example: a point feature Layer "Birds" and add Boolean Fields with "TRUE/FALSE"Check Boxes (for example "Singing", "foraging" ...)
2. Export it to a QField Project
3. [Load it on your device (Tablet, Smartphone)
4. Set the first Point and check at least on box.
5. Set a second Point (here you the previously checked Field should be shown as checked but the value is 'Zero'

### Expected behavior
Normally the previously checked boxes shouldn't be shown as checked in the new generated feature. 

### Screenshots and GIFs
It looks like this:
![Screenshot_20230512-130027~2](https://github.com/opengisch/QField/assets/133647104/7181ce90-dfa8-4e76-be9c-c84054ed38b3)
but it should look like this:
![Screenshot_20230512-130118~2](https://github.com/opengisch/QField/assets/133647104/5a4641f9-f42d-430c-a9b9-22469fff5082)

### Desktop (please complete the following information)
 - OS: Windows 
 - QGIS Version 3.28
 - QFieldSync Version 4.4.9

### Mobile (please complete the following information)
 - Device: Fairphone 3/Samsung Galaxy Tab Active Pro
 - OS: Android 11
 - QField version: 2.7.6 - Heroic Hedgehog 3313e4

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@LordDuck71 , thanks for reporting this issue; it's a long standing regression which had gone unnoticed. 

This PR (https://github.com/opengisch/QField/pull/4291) fixes your issue. It'd be great if you could test the APKs in the PR and confirm you have working checkboxes :).

**Comment by LordDuck71** [comment]
@nirvn , Thank you so much! It works!

**Comment by nirvn** [comment]
@LordDuck71 , fantastic. Happy field mapping!
