### ISSUE TITLE
Problem with line digitizing

### ISSUE THREAD

**Issue by gnerred** [opengisch/QField#43]
When I try to digitize a polyline, the polyline is not saved in the database, and no shown on map. I can draw the points and fill the form, but when I click on save button, nothing is saved. 

Device : Galaxy Note 2014 Edition with Android 5
BD : Spatialite

**Comment by m-kuhn** [comment]
Confirmed here with your sample data.

It works when running QField on the computer with your dataset.
And it works on the device with other line based datasets in the past. This points to a data provider problem.

**Comment by gnerred** [comment]
Okay it work if the line layer is created with Layer > Create layer > New Spatialite layer. It doesn't work if QSpatialite is used
