### ISSUE TITLE
GPS information partially covered by search button

### ISSUE THREAD

**Issue by pigreco** [opengisch/QField#431]
GPS information and search capabilities are superimposed and reading is not easy

![image](https://user-images.githubusercontent.com/7631137/50822801-dc7d4300-1332-11e9-8d4c-80b900c43643.png)

thanks and happy new year

**Comment by geomondego** [comment]
Guys, in fact a bit inconvenient. Maybe search as a on/off button or change the position?

**Comment by 3nids** [comment]
This should have been solved by #438

**Comment by geomondego** [comment]
@3nids Nice Job. Works fine :+1:

**Comment by pigreco** [comment]
@3nids thank you so much
