### ISSUE TITLE
Destination reappears each time the application is opened

### ISSUE THREAD

**Issue by Dartazen** [opengisch/QField#4314]
### Describe the issue
Even if I clear the destination, it reappears each time the application is opened.

### Expected behavior
Delete the destination so it doesn't reappear each time you open the app

### Mobile (please complete the following information)
 - Device: Galaxy A20e
 - OS: Android 11
 - QField version: 2.8.0 (333387)

**Comment by nirvn** [comment]
@Dartazen , this has been fixed as of QField 3.2.0.
