### ISSUE TITLE
Android USB GPS not connecting - permissions

### ISSUE THREAD

**Issue by erik3dg** [opengisch/QField#4329]
### Describe the issue
When attempting to use an external GPS via USB-Serial connection, the serial device is detected but QField won't connect to it because it has "insufficient permissions".

### Reproduction steps
1. Go to 'Settings - Positioning'
2. Add Device - Serial port (NMEA)
3. Tap 'Connect to USB gps'
4. Connection error is now displayed & permission to use device is not asked for

### Expected behavior
QFIeld should ask for permission to use the USB device and then read in the external GPS NMEA position information

### Mobile (please complete the following information)
 - Device: Samsung S21
 - OS: Android 13
 - QField version: 2.8.1

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by m-kuhn** [comment]
Serial Port was mainly added for Windows, it was never tested with USB on Android. It seems a specific dialog prompting for permissions needs to be implemented. Work in this area is very welcome.

**Comment by bettellam** [comment]
@erik3dg , @m-kuhn 
Hi...
It can be solved using the TCPUART app on android, which takes care of sending the USB_UART NMEA messages to a TCP port (in my case default: 10.1.10.1:8080)
In QField connection type choose: TCP (NMEA) with same port indicated by TCPUART
Buon lavoro...
Ciao :-)

![Screenshot_20230702-154411_TCPUART](https://github.com/opengisch/QField/assets/23143342/ccc5d9c0-982b-441d-a10e-b1549809d4ea)

![Screenshot_20230702-154621](https://github.com/opengisch/QField/assets/23143342/311f16c4-c788-4d52-8c50-6cd0cb623fc8)

![Screenshot_20230702-154545](https://github.com/opengisch/QField/assets/23143342/7a7ba3a7-9e62-4fbe-97dd-b1add19419b8)
![Screenshot_20230702-154527_TCPUART](https://github.com/opengisch/QField/assets/23143342/b377291c-2990-4cd2-bb80-d75dc4b4ad9a)

**Comment by ruocalgis** [comment]
This worked for me when I tried it. However, when I went to check my horizontal and vertical precision positioning variables (via both @gnss_* and @postion_*), they return NULL values. @bettellam - Have you encountered this issue before?

**Comment by bettellam** [comment]
@ruocalgis I generally use the bluetooth connection with my GNSS receiver.  
The "Postion Error Statistics" values ​​are taken from the NMEA $GPGST message, 
check if they are enabled in your receiver!
https://receiverhelp.trimble.com/alloy-gnss/en-us/NMEA-0183messages_GST.html
Ciao

**Comment by NickSchub** [comment]
Hello,

i have some problems to find the right IP and Port to connect my gps device via TCPUART. Can anybody help me, where I can find them?

I'm using the external ppm 10xx device. In this case, your IP adress doesnt work...

**Comment by bettellam** [comment]
@NickSchub it is TCP<>UART application which generate the IP address, 
... user can only change the port.
In the image below:
- in red IP of the mobile device;
- in green the IP generated by the TCP<>UART application. This is the address you will then need to use with Qfield!

Ciao

![20230820_092730](https://github.com/opengisch/QField/assets/23143342/53ae8e65-d466-4729-8654-33257556bc8f)

**Comment by NickSchub** [comment]
There is only one IP shown in my app. 
![20230821_054000](https://github.com/opengisch/QField/assets/127605405/70a814c6-377f-4fa7-a9bc-94538b6e7bb7)

**Comment by bettellam** [comment]
@NickSchub  From "developer options" **enable USB Debugging**!!!
Let me know if it works!
Ciao

**Comment by NickSchub** [comment]
It works. Thank you REALLY much!

**Comment by ruocalgis** [comment]
@bettellam, I am having issues with this on 2 separate Samsung devices:

1. Samsung Galaxy S21 FE phone - in this case I get an error "ERR: USB_NO_DEVICE_CONNECTED" even though I have USB debugging activated.
2. Samsung Galaxy Tab A - only lists 1 IP address under the TCP menu. USB debugging also activated.

Any ideas on what could cause these issues?

Thanks!
