### ISSUE TITLE
"Help, photos from the DCIM folder are not synchronizing in QField."

### ISSUE THREAD

**Issue by CACG1022** [opengisch/QField#4341]
Hi, currently I'm working on a census project where we collect a lot of photos. We have gathered over 2000 photos so far, but the photos are not showing up in QFieldCloud. Only 342 photos appear, and the rest are missing. We have tried synchronizing from the mobile several times to see if they would upload, but they didn't. And now, several photos that were taken on the phone are no longer there. It seems that when we pressed the sync button, they were directly deleted from the phone. I'm really disappointed with this tool. We have tried different methods, like exporting the DCIM folder from QField, but the application crashes because there are too many photos. We even tried using a USB connection, but we couldn't find the DCIM folder using the Windows file explorer. I've posted several requests on this forum, but honestly, there hasn't been a concrete solution.

**Comment by CACG1022** [comment]
![IMG_20230604_195051](https://github.com/opengisch/QField/assets/118937011/bbdd4da1-2395-4d9b-90e9-63a1842f743e)

This is a screenshot from the QField application showing that the photo is not displayed. 🤦🏻‍♂️ Help

**Comment by m-kuhn** [comment]
Thank you for reaching out.
Please contact support via the chat bot on the qfield.cloud application, the question mark at the bottom right.
Please specify the project and user in question as well as the delta id and time of incident if you have these.
Thank you.

**Comment by CACG1022** [comment]
Hello everyone, I want to ask if anyone has found a solution to this problem? I have been experiencing this issue for a few years now. Some photos never arrive, and sometimes photos get deleted on the device they were taken on. I need an urgent solution, I would greatly appreciate it if anyone knows how to resolve this issue. I also use the paid version, but they do not provide a definitive solution.
