### ISSUE TITLE
Problems creating new project.

### ISSUE THREAD

**Issue by mediosapoyoconservacion** [opengisch/QField#4343]
### Describe the issue
[A clear and concise description of what the problem is.]

### Reproduction steps
When trying to create a new project from the web page, it gives me a 500 error and won't let me create it. If I try to log in from Qgis, it gives me a message that the subscription is not active.

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
![image](https://github.com/opengisch/QField/assets/126456315/385a559e-3dcb-4870-b17c-38a4717a173a)
![image](https://github.com/opengisch/QField/assets/126456315/8fae3104-2fe0-4f7e-ad21-42c990fd5e52)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: windows 10
 - QGIS Version 3.22.1-Białowieża
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - OS: [e.g. Android 11]
 - QField version: Versión instalada	4.5.0

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: yes
* Problem can be reliably reproduced, doesn't happen randomly:  yes
* Problem happens with all files and projects, not only some files or projects: no

[If the problem happened with QFieldCloud, please add your username and project name.] mediosapoyoconservacion (Proyect "Eventos Temporales", unable to create project

**Comment by ZsanettMed** [comment]
Hi, 
Thank you for reaching out.
Please contact support via the chat bot on the qfield.cloud application, the question mark at the bottom right.
Please specify the project and user in question.
Thank you.
