### ISSUE TITLE
Qfield Build

### ISSUE THREAD

**Issue by SI-Lab** [opengisch/QField#4347]
### Describe the issue
Hello Team,
I am compiling Qfield 2.7.6 using Cmake. On reaching qgis:x64-windows dependency file, I got these errors
CMake Warning at scripts/cmake/vcpkg_configure_cmake.cmake:380 (message):
The following variables are not used in CMakeLists.txt:
PYRCC_PROGRAM
PYTHON_LIBRARY
PYUIC_PROGRAM
QSCINTILLA_LIBRARY

How do I solve this error? Thank you..]

### Reproduction steps
1. Start cmake 3.2.6
2. Load source file 2.7.6
3. Compiling till qgis:x64 file then crash

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
The following variables are not used in CMakeLists.txt:
PYRCC_PROGRAM
PYTHON_LIBRARY
PYUIC_PROGRAM
QSCINTILLA_LIBRARY

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 11
 - QGIS Qfield 2.7.6
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - OS: [e.g. Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by SI-Lab** [comment]
> Supported steps to compile for windows are here. Did you follow these?
> 
> https://github.com/opengisch/QField/blob/master/doc/dev.md#windows

Thank you for the reply.

Yes I followed the listed steps for windows

**Comment by m-kuhn** [comment]
The abovementioned output in observed behavior are warnings. Do you have an error message?

**Comment by m-kuhn** [comment]
Actually it looks like you are building for x64-windows whereas the docs mention x64-windows-static, or am I missing something here?

**Comment by SI-Lab** [comment]
Below are the 5 errors

D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\src\fce5ac5a83-3289c70339.clean\src\core\qgstessellator.cpp(25,10): fatal error C1083: Cannot open include file: 'poly2tri.h': No such file or directory [D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\x64-windows-rel\src\core\qgis_core.vcxproj]
         D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\src\fce5ac5a83-3289c70339.clean\src\core\mesh\qgsmesheditor.cpp(26,10): fatal error C1083: Cannot open include file: 'poly2tri.h': No such file or directory [D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\x64-windows-rel\src\core\qgis_core.vcxproj]
         D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\src\fce5ac5a83-3289c70339.clean\src\core\mesh\qgstopologicalmesh.cpp(23,10): fatal error C1083: Cannot open include file: 'poly2tri.h': No such file or directory [D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\x64-windows-rel\src\core\qgis_core.vcxproj]
         D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\src\fce5ac5a83-3289c70339.clean\src\core\mesh\qgsmeshadvancedediting.cpp(20,10): fatal error C1083: Cannot open include file: 'poly2tri.h': No such file or directory [D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\x64-windows-rel\src\core\qgis_core.vcxproj]
         D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\src\fce5ac5a83-3289c70339.clean\src\core\mesh\qgsmeshforcebypolylines.cpp(20,10): fatal error C1083: Cannot open include file: 'poly2tri.h': No such file or directory [D:\Build\Qfield8\_deps\vcpkg-src\buildtrees\qgis\x64-windows-rel\src\core\qgis_core.vcxproj]

    33 Warning(s)
    5 Error(s)

Time Elapsed 00:44:36.50

**Comment by SI-Lab** [comment]
> Cannot open include file: 'poly2tri.h': No such file or directory

![Qfield error](https://github.com/opengisch/QField/assets/114161464/5752c902-fecd-46d7-88da-1e1cea479f05)

**Comment by m-kuhn** [comment]
It seems you are building for `x64-windows` whereas the instructions mention `x64-windows-static`, am I missing something?

**Comment by SI-Lab** [comment]
Oooh

Kindly, where do I change  from x64-windows to x64-windows-static?

Thank you.

**Comment by m-kuhn** [comment]
If you follow the steps in the windows section on https://github.com/opengisch/QField/blob/master/doc/dev.md it should be static

**Comment by SI-Lab** [comment]
> If you follow the steps in the windows section on https://github.com/opengisch/QField/blob/master/doc/dev.md it should be static

Even after declaring VCPKG_TARGET_TRIPLET=x64-windows-static on windows environment, I still get the same error.

**Comment by m-kuhn** [comment]
The best information you will get is probably in the log file that is mentioned in your screenshot https://github.com/opengisch/QField/issues/4347#issuecomment-1580687277

**Comment by m-kuhn** [comment]
I never work with VS and just build on the console.

It's almost certainly related to the following line from the dev doc

```
CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded\$<\$<CONFIG:Debug>:Debug>

```

Do you have any suggestions to improve the windows build doc?

**Comment by SI-Lab** [comment]
> I never work with VS and just build on the console.
> 
> It's almost certainly related to the following line from the dev doc
> 
> ```
> CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded\$<\$<CONFIG:Debug>:Debug>
> ```
> 
> Do you have any suggestions to improve the windows build doc?

I realize that i will end up with .exe for windows while what i need is .apk. Started all over again for Android(Android Sdk/Qt/Cmake).
After doing all the required setups,Cmake give libpg dependency error.How do i solve it on windows platform? Thank you.
![libpq](https://github.com/opengisch/QField/assets/114161464/103af17f-4775-4390-bc0c-5dc74205e3eb)

**Comment by m-kuhn** [comment]
> Do you have any suggestions to improve the windows build doc?

Please let me kindly re-raise this question. This is a community where everyone helps each other and your feedback is valuable!

**Comment by SI-Lab** [comment]
> > Do you have any suggestions to improve the windows build doc?
> 
> Please let me kindly re-raise this question. This is a community where everyone helps each other and your feedback is valuable!

I followed https://github.com/microsoft/vcpkg/issues/30327 

It worked.

**Comment by m-kuhn** [comment]
Good!
Is there something useful we should add to the windows build instructions in doc/dev?

**Comment by nirvn** [comment]
Closing this now. @SI-Lab , if what made it work for you is relevant to others, please consider adding details in the windows build instruction documentation (https://github.com/opengisch/QField/blob/master/doc/dev.md).
