### ISSUE TITLE
Search functionality does not highlight point type layer element

### ISSUE THREAD

**Issue by carlosjacintogithub** [opengisch/QField#435]
Search functionality does not highlight point type layer element.

Performing a search on a specific feature of a point type layer, **only** centers the element on the equipment screen.

![screenshot_20190109-165518](https://user-images.githubusercontent.com/46531969/50914876-788c7480-142f-11e9-9846-d5bad95fe42b.png)

On the other hand, when the research occur in a  row-type layer, qfield, besides centering the element on the equipment screen, **increases the scale allowing an approximation to it** and **highlights the element** with the color of selection (defined in the workspace project: General Settings).

![screenshot_20190109-161142](https://user-images.githubusercontent.com/46531969/50913087-817b4700-142b-11e9-9b2a-15dd09f8a604.png)

It would be convenient if the layer of the type of point would have the same potentialities in the level of its research..

Best

Carlos

**Comment by ElvisDahnert** [comment]
Another failure I noticed:
If the user performs a second search for a point other than the first, this second point will not be highlighted. The highlight of the first point is only undone if you perform one search per line.

**Comment by 3nids** [comment]
indeed, I could reproduce.
fix will follow.
