### ISSUE TITLE
More search providers

### ISSUE THREAD

**Issue by BigJ1980** [opengisch/QField#4356]
How can I search for street address with the tile google map layers in Qfield?
I can search the other layers in Qfield but not the google map layer… how to I fix this?

In QGIS there is no checkbox in "Searchable" column for map layers but all other layer that are files.
Have I done something wrong, or use a different URL to include this feature with XYZ tile, or don't use XYZ tile and if so what do I use?

The layers that I can search are Geopackage files, the map layers are in the project linked to the following so no files in project folder:
"https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}"

New to QGIS but getting there :)

Any help appreciated, thanks.

![tiles](https://github.com/opengisch/QField/assets/131635418/a92d687f-0208-4237-b43a-736066bfef38)
![non-searchable](https://github.com/opengisch/QField/assets/131635418/98afb86b-9327-4636-8672-962ea72eb299)
![direct data access](https://github.com/opengisch/QField/assets/131635418/8081b408-3bf3-41ec-b8ab-d0784df3c1a5)

**Comment by m-kuhn** [comment]
QGIS (and QField) can search natively in vector layers where we have information associated with individual features.

Google maps is a raster layer -- an image -- which doesn't know about the features (objects like streets etc) on it.

This could be done by using a separate search API ([google maps offer](https://developers.google.com/maps) such an api, [nominatim](https://nominatim.org/release-docs/latest/api/Search/) is another one)

Currently a [search provider for Finland is integrated](https://github.com/opengisch/QField/pull/1739), more could be done but would need development.

**Comment by BigJ1980** [comment]
Thank you m-Kuhn, I am looking into your helpful links. 
I appreciate the help... should i have posted this question here in "Issues" or in "Discussions" or elsewhere?
