### ISSUE TITLE
Cascading value relations

### ISSUE THREAD

**Issue by cocro** [opengisch/QField#436]
Hi!

We're tried to use the type 'relational value' to have cascading dropdowns (we've 2 dropdowns : a choice in the first one filter the second), it works on QGIS with the extension QField, but we discovered that is not supported on QField app. 

So what should we do to achieve our goal ? 

The type 'value map' seem not allow to make cascading dropdown and at this moment I've no idea to how to do that.

![test_formulaire](https://user-images.githubusercontent.com/46560615/50963640-8ee90d80-14cd-11e9-8b98-8a4ac34c070a.jpg)

Thank you for your help!

**Comment by m-kuhn** [comment]
Cascading dropdowns are currently not supported by QField. Non cascading value lists can be done with relations / relation reference widget.

**Comment by cocro** [comment]
Thank you for that answer
Do you think you will develop this tool which facilitates seizures nested in the field?
if so, how soon?

**Comment by m-kuhn** [comment]
Nothing scheduled yet, but we will be happy to send you an offer for that.

**Comment by cocro** [comment]
Why not ? 
No idea of the cost for this development that would certainly make many services during collection and productivity gains post-processing in office
It could be a basis of discussion with my boss

**Comment by schoeller** [comment]
@m-kuhn : I have generated a QfieldSync from a naked QGEP install. When trying to edit the layer ```vw_qgep_wastewater_structure``` I see a dropdown menu for attributes ```ws_type```, but not for ```ma_function```. Am I correct that this is related to #436?

**Comment by m-kuhn** [comment]
Sorry, @cocro I totally forgot about this. Can you send a mail to info@opengis.ch if you are still interested.

@schoeller I guess that is correct, but I would expect other issues too for the full export. Could you also contact me to setup a call and discuss the details?

**Comment by nischmi1** [comment]
+1 for this enhancement from our side. Will send a mail to info@opengis.ch about it.

**Comment by manumanul** [comment]
Has this issue been solved by now?
