### ISSUE TITLE
Bug affecting how html-widgets is displayed in Qfield

### ISSUE THREAD

**Issue by kelprmy** [opengisch/QField#4366]
I recently built a field-form using the Qfield plugin in QGIS. It includes a html-widget (html-element in the Norwegian version) with some important instructions. It worked perfectly before the last Qfield-update. But after the update, when I open the project on my phone (Android) or tablet (iPad), only the name of the html-widget is displayed. The widget still shows when I register new features using QGIS on my laptop, though.

**Comment by nirvn** [comment]
@kelprmy , share a test project please.

**Comment by Benwaa74** [comment]
> I recently built a field-form using the Qfield plugin in QGIS. It includes a html-widget (html-element in the Norwegian version) with some important instructions. It worked perfectly before the last Qfield-update. But after the update, when I open the project on my phone (Android) or tablet (iPad), only the name of the html-widget is displayed. The widget still shows when I register new features using QGIS on my laptop, though. 
> 
> 

Did you resolve this issue? I'm finding the same thing with both the html widget and text widget on latest version on iOS...

**Comment by Benwaa74** [comment]
This is still not fixed in latest iOS version 3.0.5

**Comment by m-kuhn** [comment]
@Benwaa74 are you able to share a test project?

**Comment by nirvn** [comment]
I think I've fixed the lingering issue in this PR:

https://github.com/opengisch/QField/pull/4734
