### ISSUE TITLE
"Error when taking a photo with QField 2.8.2."

### ISSUE THREAD

**Issue by CACG1022** [opengisch/QField#4369]
Hello, currently I have a project in which several photos are taken through the QField form, and we have been experiencing many issues. Firstly, there is a problem with the synchronization of the photos in QField, where only some of them are uploaded and not all. Secondly, there is an error that occurs when taking a photo where QField closes unexpectedly. We have tried with both the native camera activated and deactivated. This error occurs randomly, and we have not been able to determine the cause. It has happened on different devices such as Xiaomi and Samsung with 4GB of RAM.
I really appreciate the help of someone who can help me I need an urgent solution

**Comment by RatInTheField** [comment]
Sounds like my issue #4429??

**Comment by Geodanagrimensura** [comment]
Estou com o mesmo problema

**Comment by nirvn** [comment]
@CACG1022 , work has been don to improve this situation; are you still seeing this in QField 3.2.0?
