### ISSUE TITLE
In QField 1.0. some features do not work in portrait mode.

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#437]
1. can't select a layer. inactive. 
2. does not work gps location button.
3. inactive touch screen, I can't push the map.

When you rotate in landscape mode, everything works fine. But in practic the phone works better in portrait mode.

the problem starts with version 1.0

OS: Android 8.0
device: Black View BV9000 pro

project 
[null.zip](https://github.com/opengisch/QField/files/2749938/null.zip)

![screenshot_20190111-130053](https://user-images.githubusercontent.com/6436791/51039639-4eb58800-15be-11e9-8699-1dc22efeb761.png)
![screenshot_20190111-130103](https://user-images.githubusercontent.com/6436791/51039640-4eb58800-15be-11e9-9652-e698a6d18031.png)

**Comment by nicolasmcfadden** [comment]
Hello,
I have the same problem. In general it seems that only the lower third of my screen is selectable on the main map interface and on the layer interface.

**Comment by m-kuhn** [comment]
Can you check in the app information that GPS permissions are enabled?

**Comment by giedrioks26** [comment]
Yes, GPS enabled. In landscape mode it work

**Comment by 3nids** [comment]
this has been fixed by #422

**Comment by 3nids** [comment]
and a801c11af8efb0bb484a384a1d9b19cc8ece540c

**Comment by 3nids** [comment]
please try packages from https://github.com/opengisch/QField/commit/a801c11af8efb0bb484a384a1d9b19cc8ece540c#commitcomment-31964308

**Comment by giedrioks26** [comment]
Partly the problem is solved. But the search box hides behind the grill. Only in portrait mode. In landscape mode everything is fine.

Portrait mode:
![screenshot_20190116-214038](https://user-images.githubusercontent.com/6436791/51274818-d5140480-19d8-11e9-875c-d012519740d9.png)

Landscape mode:
![screenshot_20190116-214055](https://user-images.githubusercontent.com/6436791/51274820-d5ac9b00-19d8-11e9-9a85-f6c6d3350319.png)

**Comment by 3nids** [comment]
thanks for testing, fix coming asap!

**Comment by 3nids** [comment]
should be fixed in #439

**Comment by giedrioks26** [comment]
Great! Solvet. Thanks @3nids!

**Comment by giedrioks26** [comment]
@nicolasmcfadden you solved?

**Comment by 3nids** [comment]
closing, feel free to comment if any issue remains
