### ISSUE TITLE
Troubles with changing the checkbox-status

### ISSUE THREAD

**Issue by trutti6440** [opengisch/QField#4380]
Since two weeks we have troubles with the status of a checkbox in our qfield-form to collect data. The checkbox-status can't be changed from True (active) to False (deactive). If the default value is False (deactive) we can change it to True (active), but the other way around (from True to False) doesn't work.

Mobile
 - Device: Samsung Tablet Active (two different versions)
 - OS: Android 11
 - QField version: 2.8.2 - Insightful Indri and 2.8.1 - Insightful Indri

Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@trutti6440 , I've tried it here and can't replicate; could you share your attribute configuration, i.e. this:
![image](https://github.com/opengisch/QField/assets/1728657/7b05aaad-4d22-4d2b-8c91-23d14e5998e3)

**Comment by trutti6440** [comment]
@nirvn; we used the same settings as shown in the figure before the problems occured:
![image](https://github.com/opengisch/QField/assets/137033756/51e26dc6-5e70-4c31-ad6c-136a92dff76e)

**Comment by trutti6440** [comment]
@nirvn; yes :)
![image](https://github.com/opengisch/QField/assets/137033756/d51f131c-fcf7-4718-91c5-594ec0e1a4d4)

**Comment by trutti6440** [comment]
@nirvn, i've just tried the qfield version 2.7.6 Heroic Hedgehog. With the same *.qgs-file the checkbox works perfectly fine.

Maybe this helps to figure out the problem :)
