### ISSUE TITLE
Show visible features doesn't work

### ISSUE THREAD

**Issue by GammaGames** [opengisch/QField#4404]
### Describe the issue
Opening the layer inspector has an option for "Show feature list" with an extra option of "Show visible features..."
![image](https://github.com/opengisch/QField/assets/7832163/f71ad2da-b49f-4a39-95e5-89d9cb3bdbcd)

This doesn't do anything. Clicking the "Show feature list" shows all features as expected, but the other option closes the panel and does nothing else

### Reproduction steps
1. Move the camera so only a handful of features are in the window
2. Right click the layer
3. Click the "Show feature list" dropdown and select "Show visible features..."
4. Nothing

### Expected behavior
It should open a panel with only the visible features

### Observed behavior
It does nothing

### Mobile (please complete the following information)
 - Device: iPad Air 3
 - OS: ios 16.5
 - QField version: 256868 v2.8.3

**Comment by m-kuhn** [comment]
This works for me.
Can you test this with one of the sample projects and share a dataset/screenshots?

**Comment by GammaGames** [comment]
Hmm, it does seem to work fine in the example projects. No idea why it's not working in ours, I don't see anything in the logs either.

**Comment by Ipickedausername** [comment]
Hello, 

I made the test with my current projet, on the last version of qfield master-dev (f69a04).

I have the same error: 

https://github.com/opengisch/QField/assets/72577399/884a7fb2-0edf-4ad3-b985-1948e2a7f1a8


On this video, you can also see at the end that I cannot scroll down in the list. This is another issue I guess.

**Comment by Ipickedausername** [comment]
I created a test project, but I don't have this error on the new one...

**Comment by nirvn** [comment]
@GammaGames , your issue is most likely fixed, you can install an APK here (https://github.com/opengisch/QField/pull/4437) and confirm if you have a minute.

Thanks for reporting.

**Comment by Ipickedausername** [comment]
I tested it, the visible features can be listed, but I could'n move the map properly.. only zoom/unzoom. 
To move the map I had to hold it with 2 fingers (the same way we do to change the orientation of the map).

**Comment by nirvn** [comment]
@Ipickedausername , the map move issue is likely you having double tapped on the canvas on Android. Known issue. Avoid these for now

**Comment by GammaGames** [comment]
Just downloaded the new release and tested, can confirm it's working now 🎉 Thanks so much!
