### ISSUE TITLE
Qfield incomplete synchronization

### ISSUE THREAD

**Issue by cocro** [opengisch/QField#441]
Hi,

I work on qfield (version 1.0 of 7/1/19) and qgis 3.4.3) via the plugin qfield sync. I have packaged my project qgis, where there are two layers shape (object to modify or create - offline project) and an OSM base map. When I package the qgis project, the shape layer is transformed into data.gpkg and the base map into basemap.gpkg.
The field work consists of editing and adding information in the shape.1 (fill in the existing form (exploration mode)) and in some cases add points in the shape.2 (scan mode). I sync every two days.
It is noted in the documentation that "every change made in the packaged project during the job is saved in a log file and that, during the synchronization-return, this file will be restarted and all the changes applied to the database as well. principal. "

Day 1: Synchronization go, departure for a day of collection
Day 2: Back office and the timing is perfect ; I can see the changes made on the ground. Whether modifications or additions.
Day 3: I delete points on the tablet, j.1 collection error and I keep my updates updated
Day 4: I synchronize and ... all j.2 points remain on the PC layer.

Is this the normal operation of the application?
If so, I would only make the changes on my PC
If not, how can I solve my problem? because now I have to find all the points removed from the tablet
Does this concern qgis or qfield ? or cache machin ?

Cordially
Corinne

**Comment by signedav** [comment]
I close this because it's reported still in #447 and apparently solved anyway.
Thanks.
