### ISSUE TITLE
Cannot move entities anymore

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#4414]
Hello, 

Since the previous updates on the master-dev version (I don't really know which one), moving features is not possible anymore. 

https://github.com/opengisch/QField/assets/72577399/b8125031-50c3-468b-bde9-760ab4eeaad5

I think this video describe it well. 
You can also see that the project is very slow (I noticed Qfield is progressively becoming slower and slower). Before, I could have 1.5k points with a lot more complex symbology. Now, with 50 points it looks already like on the video (but this is another problem that I want to test before). 

It is working with Qfield 2.8.3

Thank you for your attention. 

 - OS: [Windows 10]
 - QGIS Version [3.26.0]
 - QFieldSync Version [4.5.0]
 
 - Device: [Samsung galaxy S9]
 - QField version: [master-dev f69a04]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@Ipickedausername , can't replicate. Feel free to attach a sample project that replicates this issue.

**Comment by Ipickedausername** [comment]
Hello, 

Here is a project test, I can reproduce the issue on this project.


https://github.com/opengisch/QField/assets/72577399/930f90af-7c88-4732-82a5-3a90f744d35f


[test_move_qfield.zip](https://github.com/opengisch/QField/files/11946823/test_move_qfield.zip)

**Comment by nirvn** [comment]
@Ipickedausername , thanks, regression fixed, should emerge in a master build soon.
