### ISSUE TITLE
QFieldCloud Downloading error

### ISSUE THREAD

**Issue by Oisin-JK** [opengisch/QField#4418]
### Discussed in https://github.com/opengisch/QField/discussions/4409

<div type='discussions-op-text'>

<sup>Originally posted by **Oisin-JK** June 30, 2023</sup>
I have a community plan account with QFieldCloud. I have one project, and have not exceeded the 100MB limit. I cannot access the project from my android device. I sign in correctly to the same account I created the project with, i.e. no collaborators. I get the following error: 

> "Permission denied because the useraccount's plan is insufficient."

But I do not belive the account is insufficient. No collaborators, under 100MB, no other projects using up account space. File based project.

Can anyone help?</div>

**Comment by SeqLaz** [comment]
We appreciate you bringing this issue to our attention. Your report will greatly assist us in addressing and resolving the problem.

Please be assured that our dedicated team of developers is actively working on fixing this issue.

If you have any additional questions or concerns, please don't hesitate to reach out to us. You can do so by clicking on the question mark in the right corner of the QFieldCloud platform. Our support team is always ready to assist you.

Best regards.

**Comment by Oisin-JK** [comment]
Hi. I did raise a ticket. There seems to be no way of seeing that ticket after it has been submitted to check on progress etc. I now have no evidence a ticket was even successfully posted.

**Comment by sanojLeOne** [comment]
I have the same Problem on iOS except for having one collaborator.
