### ISSUE TITLE
List of entities - Can't scroll down anymore

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#4421]
Hello,

On the last version of Qfield dev, we cannot scroll in the list of entities. It is working on qfield 2.8.3

I don't think we need a test project since this can be reproduced on the Bee farming project.

https://github.com/opengisch/QField/assets/72577399/372f9ad5-56dd-4273-8f70-74b4218a00f7

### Desktop (please complete the following information)
 - OS: [Windows 1p]
 - QGIS Version [ 3.26.0]
 - QFieldSync Version [4.5.0]

### Mobile (please complete the following information)
 - Device: [samsung s9]
 - OS: [e.g. Android 8]
 - QField version : qfield-dev 7f2bd4

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Thank you.

**Comment by nirvn** [comment]
@Ipickedausername , regression fixed. You can confirm by installing a test APK from the PR here: https://github.com/opengisch/QField/pull/4426 -- thanks for the report.

**Comment by Ipickedausername** [comment]
Thank you, it is working.
