### ISSUE TITLE
Geotagging photos in Qfield

### ISSUE THREAD

**Issue by RatInTheField** [opengisch/QField#4429]
### Describe the issue
[A clear and concise description of what the problem is.]
On certain mobile devices I am unable to capture geolocation data when capturing a photo to a field on a layer. The image is saved, but the LatLong data is not.
I am using OpenCamera app with Qfield on Lenovo 8505X.
All apps have been updated to latest versions.

Uses on its own, OpenCamera saves location data correctly in EXIF, but when a photo is taken in Qfield using the OpenCamera app (set as default camera app), location data is not saved to the image files' EXIF data.

On other hardware that does not require OpenCamera to save location data,  Qfield correctly saves location to EXIF.

### Reproduction steps

1)  in Qfield, select layer, create new feature, navigate to photo field, add photo.
2)  in Qfield, select layer, open existing feature, navigate to photo field, add photo.

### Expected behavior
[A clear and concise description of what you expected to happen.]
Photo is captured, saved to folder, image is displayed in photo field with the location icon active. Location data is saved to image file

### Observed behavior
[A clear and concise description of what actually happened.]
Photo is captured, saved to folder, image is displayed in photo field with location icon greyed out and crossed out. Location data is NOT saved to image file.

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - Lenovo 8505X
 - OS: [e.g. Android 11]
 - Android 10
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]
 - 2.8.3 insightful Indri 256868 v2.8.3

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Yes. Problem only noticed recently. Last known to work on device c12 months ago.
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]
* Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by RatInTheField** [comment]
Resetting the default camera app to OpenCamera  in the tablet and in Qfield seems to have corrected the issue. I removed default app settings in Android Settings, then re-set them when the system and Qfield requested. Image is captured and Location icon is active.

**Comment by nirvn** [comment]
@RatInTheField , happier to hear you got things under control. Happy field mapping!
