### ISSUE TITLE
Can't delete selected entities

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#4430]
Hello, 

As for the move entity action, the delete entity is not working when this one is selected. 

There are two ways of deleting : 
- opening the entity > tap on the 3 dots > delete entity : This is working
- opening the list of entities > select one (tick) > delete the selected entity : This one is not working

Here is a video of the behavior: 

https://github.com/opengisch/QField/assets/72577399/930cf45d-01aa-41c0-a5bd-4bbf88d385c0

A test project with 2 layers (but you can check on Bee Farming also):

[test_move_qfield.zip](https://github.com/opengisch/QField/files/11973427/test_move_qfield.zip)

Desktop (please complete the following information)

    OS: [Windows 10]
    QGIS Version [ 3.26.0]
    QFieldSync Version [4.5.0]

Mobile (please complete the following information)

    Device: [samsung s9]
    OS: [e.g. Android 8]
    QField version : qfield-dev 7f2bd4

Additional information

    Problem started happening recently, didn't happen in an older version of QField: [Yes]
    Problem can be reliably reproduced, doesn't happen randomly: [Yes]
    Problem happens with all files and projects, not only some files or projects: [Yes]

Thank you

**Comment by nirvn** [comment]
@Ipickedausername , thanks for the report, fixed here: https://github.com/opengisch/QField/pull/4431
