### ISSUE TITLE
Multiple records in one field

### ISSUE THREAD

**Issue by FilipjFry** [opengisch/QField#446]
Hi, Is there a way to enter multiple records in one same field ?

For example, I use Qfield to describe Rocks on the field, I would like to be able to enter several minerals in the same column from a list of value, (Example, Qz ; Fp; Bt), what would be great would be to be able to add a mineral name with a percentage, e.g. Qz5 ; Fp3; Bt4, do that require to have several mineral columns in my acquisition layer or is ther a way to append all the minerals in the same column ?

Thanks,

Fry

**Comment by 3nids** [comment]
there is no such functionality at the moment.
We could port the behavior of QGIS' value relation widget allowing multiple choice.
Please get in touch with us, if you are interested in such feature.

**Comment by FilipjFry** [comment]
That would be great, I have seen QGis value relation widget that allows multiple choice, but I am unable to link it with a list of value. I am obviously more a geologist than a programmer !
I will get in touch with you, Thanks.

**Comment by FilipjFry** [comment]
Definetily ready to fund that one if anyone is able to do so.

Fry.

**Comment by jarvojta** [comment]
Not very user-friendly but working workaround is to make two different tables. One main (e.g. locality description) and subordinate one (e.g. minerals found) with 1:N relationship. The relationship between the tables must be established using some ID, so you have to somehow transfer the ID from main table to the subordinate one which can be done using "aggregate" function: aggregate('Main table', 'max', "ID") as a default value in some field in Main table. This takes the largest (i.e. last) ID from the main table and establish 1:N relationship. Of course, the ID in main table must be set to auto-increment ( if( maximum("ID")  IS NULL, 1, maximum("ID")+1)). When in the field you have first to fill the form for Main table, then save the record and add a new record to subordinate table (first mineral) and you can add as many new minerals as you want. The obvious disadvantage is that when you want edit the Main table again, you must reopen it. The second disadvantage is that when you want to add minerals for some locality that was not the last recorded you have to edit the inherited ID.
Subform functionality would be definitely useful.

**Comment by KirstenReilly** [comment]
Has this functionality got any further? We would also be interested in development costs and time frames.

**Comment by signedav** [comment]
Hi there 

As @jarvojta already proposed the best solution would be to have a child-table. The "other" side of the mentioned Relation Reference Widget is meanwhile implemented as well and well described here: https://qfield.org/docs/project-management/vector-layers.html#relation-widget
In the QFields demo-project you can check it out as well in the layer apiary under consumption.

Please give us feedback if this is what you need. Thanks.

**Comment by signedav** [comment]
Hi @KirstenReilly 
Can we close this issue? Or is there something else needed?
Thanks
