### ISSUE TITLE
New feature not added/saved when digitising 

### ISSUE THREAD

**Issue by KirstenReilly** [opengisch/QField#448]
The newly digitised feature (point, line or polygon) isn't always added/saved once the save button is clicked. A message comes up saying it has been saved but it doesn't display.

This has occurred with points, lines and polygons, and usually happens at the start of a session (within the first 15mins).

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/39792722/51547899-14ba7080-1e5f-11e9-876d-6c4e57034b0b.gif)

![screenshot_20190122-135809_qfield](https://user-images.githubusercontent.com/39792722/51547233-c789cf00-1e5d-11e9-8225-3f070d378511.jpg)

**QField version:** Release Candidate 1
Using on Samsung Galaxy Tab S3

**Comment by geomondego** [comment]
Do you have any a constraint for IDs? The error show that you have a field with Unique constraint

**Comment by 3nids** [comment]
I think this is a bug related to the date widget.
see coming fix in #421 and issue #9

a fix will come asap

**Comment by KirstenReilly** [comment]
Hi @geomondego there are no constraints applied for the IDs.

@3nids ok thanks, I'll try it again when the fix has been rolled out

**Comment by KirstenReilly** [comment]
hi @3nids I upgraded the app to Release Candidate 2 and now it crashes on opening every time, is there a fix/work around for this?

**Comment by nicolasmcfadden** [comment]
> 
> 
> hi @3nids I upgraded the app to Release Candidate 2 and now it crashes on opening every time, is there a fix/work around for this?

I have the same problem on Sony Xperia, Android 7.1.1

**Comment by 3nids** [comment]
Release Candidate 3 is on its way, sorry for the trouble.

**Comment by signedav** [comment]
Hi @KirstenReilly 
Is this solved with the latest QField version?

**Comment by KirstenReilly** [comment]
@signedav Yeah everything seems to be working as expected now. Thanks

**Comment by signedav** [comment]
Great @KirstenReilly 
Thanks for the feedback.
