### ISSUE TITLE
QField Photo functionality - Filename and incrementation.

### ISSUE THREAD

**Issue by FilipjFry** [opengisch/QField#449]
Hi as requested I open a new thread for my suggestion,

The question is in the title, Is there a feature that allows one to name the picture files from a station ID (or whatever field you want) ?

I guess I would have to edit those lines ?

var timestamp = (new Date()).toISOString().replace(/[^0-9]/g, "")
var filename = timestamp+'.jpg';

Also, is there a way to take several pictures on one station, if so how would one do to increment filenames with ID_Station+1 ?

Thanks,

Fry

**Comment by m-kuhn** [comment]
Hi,

there is currently no functionality for any other naming than the date.
It's also a question, if this needs to be done on the field already or can be managed later on as part of the synchronization job.

Concerning multiple pictures, at the moment your only choice is to add more than one attribute. having a dynamic amount of pictures (a gallery) is a candidate for a crowdfunding if there is interest.

**Comment by FilipjFry** [comment]
Renamed directly on the field  by incrementing from station ID would be ideal, For the moment my best option would be to treat my photos by another app maybe, I don't really like the compromise of adding multiple attributes.

How does crowdfunding works ? I might be interested in resolving this issue and the previous «Multiple records in one field» issue.

Thanks, Fry.

**Comment by magana71** [comment]
Already have the solution?

**Comment by m-kuhn** [comment]
No, there are still some open questions regarding the concept, mainly:

- when adding a new feature and directly taking a photo for it, how can it be guaranteed that the id is already present
- how exactly is the image name format configured
- for the *multiple images per station* things become even a bit more complex, so we better deal with this separately

It's mostly the id presence guarantee that would be easier to resolve in post-processing compared to when taking the picture.

**Comment by m-kuhn** [comment]
@signedav is this implemented?

**Comment by signedav** [comment]
QField side yes, QFieldSync as well but not yet released.

**Comment by qnmai** [comment]
@signedav @m-kuhn is this related to the functionality mentioned in this link (under the section 'Configure the name of images'):
https://github.com/opengisch/QField/releases/tag/v1.6.0

Should this be available using QField 1.6.2 and QFieldSync 3.2.2? I can't seem to find it...

**Comment by signedav** [comment]
Hi there
The photo naming possibility in QFieldSync is supported from QGIS 3.14

Not sure if we could make it for earlier releases as well.

**Comment by signedav** [comment]
I think this is solved :-)

**Comment by KanalRotzen** [comment]
is this problem solved too? I have to save the object first. Otherwise the path is incorrect :-/ 

_*when adding a new feature and directly taking a photo for it, how can it be guaranteed that the id is already present_
