### ISSUE TITLE
QfieldCloud - geopackage don't appear on Qfield but seems fine on Qgis

### ISSUE THREAD

**Issue by MorganPNF** [opengisch/QField#4499]
After synchronizing a project with change on Qfield, a geopackage data (only one point layer) doesn't appear anymore on QfieldCloud !
No problem on dashboard on https://app.qfield.cloud and I can retrieve data with the new change on it and use it in Qgis, but the geopackage don't appear anymore on Qfield.

I don't understand why this occurs, we use one project with 5 collaborators, but we were previously on the same account with the same issue.

The only way to fix it that I found was to convert the geopackage on shapefile, and then to convert it on geopackage again...
The "bugged" geopackage can't be displayed any more in Qfield Cloud with another project

When this bug appears, raster data is then not displaying too in QfieldCloud

 - OS: Windows
 - QGIS Version 3.22
 - QFieldSync Version 4.5

 - Device: Samsung A50
 - OS: Android 11
 - QField version: 2.8.4 - Insightful Indri (1c5f41 v2.8.4)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: I don't know, I use only when layer for editing.

[If the problem happened with QFieldCloud, please add your username and project name.]
username pn_forets, project name Miradors_RI_V7

**Comment by SeqLaz** [comment]
Thank you for bringing this to our attention. To expedite the assistance process, may I kindly request that you contact our support team directly for further guidance? You can easily reach them by clicking on the question mark icon located in the top-right corner of the QFieldCloud platform.
