### ISSUE TITLE
The windows installer of Qfield v2.8.5 is considered as a threat by Avast.

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#4506]
The windows installer of Qfield v2.8.5 is considered as a threat by Avast. Is it a real threat or just an illusion because of the type of installer used?
![QField installer threat](https://github.com/opengisch/QField/assets/55922863/f860e4dd-2cb4-4a9e-8eb3-8814ea5b6ffd)

_Originally posted by @sigmoe in https://github.com/opengisch/QField/issues/4349#issuecomment-1674396321_

**Comment by m-kuhn** [comment]
The windows installer is built from the same source code as the other packages (android, ios, macos, linux) where the store operators (google, apple, etc) are not complaining about security. There is no trojan horse inside.

If you want, the full code is in this repository and open to a review.

@sigmoe Does Avast give any information *why* it thinks this installer is a threat?

**Comment by sigmoe** [comment]
Ok, Avast just gives the information of the screenshot.
So I'll trust you and force the installation.

**Comment by m-kuhn** [comment]
If you could open a ticket with avast, so they can recommend how to improve the situation, that would be much appreciated.

**Comment by sigmoe** [comment]
Yes, I've declared the file as a false positive to Avast, and they said the file will be analysed in detail to see if there's a real threat.
I'll keep you in touch of Avast return.

**Comment by sigmoe** [comment]
Meanwhile I'll work with the version 2.8.1 (I didn't have problem of installation).
