### ISSUE TITLE
Problem of CRS on QField Windows

### ISSUE THREAD

**Issue by sigmoe** [opengisch/QField#4507]
### Describe the issue
The OSM layer is not displayed with the correct coordinates on QField Windows.

### Reproduction steps
1. Create a new project in EPSG:2154, with a vector layer in EPSG:2154 and the OpenStreetMap layer (EPSG:3857)
2. Open the project in QField: the OSM layer is not dispalyed with the correct coordinates (vector layer and OSM layer are not at the same place)

### Screenshots and GIFs
![project on QGIS](https://github.com/opengisch/QField/assets/55922863/57d450bf-ffb4-4f13-a686-9a78b1b26cc5)
![project on QField](https://github.com/opengisch/QField/assets/55922863/eef03ab8-145f-4330-b1e4-a8d173a48e68)
![zoom on osm same view](https://github.com/opengisch/QField/assets/55922863/dfd35b94-6bf9-4284-9116-9a492f1269ea)

Fisrt screenshot: the project on QGIS
Second screenshot: the project on QField (we don't see OSM where the trees are)
Third screen: if I zoom to the place in the OSM layer, we can see that the coordinates are wrong. We should have 1051310,6842122 instead of 253539,909786

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.28.7
 - QFieldSync Version 4.5.0

### Mobile (please complete the following information)
 - OS: Windows 10
 - OS: [e.g. Android 11]
 - QField version: 2.8.1 - 5333ee v2.8.1

### Additional information
This problem doesn't appear on QField Android.

The example project is attached.
[test_lyrs.zip](https://github.com/opengisch/QField/files/12320396/test_lyrs.zip)

**Comment by nirvn** [comment]
@sigmoe , have you tried QField 3.0(.2) yet? Let's confirm whether it remains an issue or has been fixed in the new version

**Comment by sigmoe** [comment]
@nirvn : 
I've totally uninstalled QField, deleted manually the directory C:\Program Files\QField, and installed QField 3.0.2.
Still the same problem with QField 3.0.2.
