### ISSUE TITLE
Text missplaced in multiline fields with constraint

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#4510]
Hello,

When a multiline field is set with a constraint, the text written in this multiline field will appear in the area of the constraint text. 

This doesn't create any issue to save the information, it is simply missplaced. 

The expected behavior would be to have the text displayed in it appropriate field.

![Screenshot_20230812-121624](https://github.com/opengisch/QField/assets/72577399/f9ea2ad6-1d47-41cf-b2d1-81d0fbd3151b)
![Screenshot_20230812-121618](https://github.com/opengisch/QField/assets/72577399/1ccb4a77-6db3-4575-ae15-1ab5ad15dd70)
![Screenshot_20230812-121614](https://github.com/opengisch/QField/assets/72577399/6d9906d7-07a7-4dce-9501-b5a506f1e797)

### Desktop (please complete the following information)
 - OS: [e.g. Windows 10]
 - QGIS Version [ 3.26.0]
 - QFieldSync Version [.4.a.0]

### Mobile (please complete the following information)
 - Device: [samsung Galaxy 9]
 - OS: [e.g. Android 8]
 - QField version: qgield master-dev af01c8

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Thanks !

**Comment by nirvn** [comment]
@Ipickedausername , thanks for reporting, fixed by this PR (https://github.com/opengisch/QField/pull/4536).
