### ISSUE TITLE
Weird behavior with the (+) button

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#4511]
Hello, 

When we put 2 fingers on the screen, sometimes, the green (+) button disapear. 
Usually, it reappears as soon as we remove one finger from the screen. 

But sometimes, it doesn't.. 
To resolve this issue, I zoom/unzoom until the green button reappears 

Here a video that shows this behavior.

https://github.com/opengisch/QField/assets/72577399/d590a0a9-cc46-4ccd-a7cd-3bd0d883f49f

### Desktop (please complete the following information)
 - OS: [e.g. Windows 10]
 - QGIS Version [ 3.26.0]
 - QFieldSync Version [.4.a.0]

### Mobile (please complete the following information)
 - Device: [samsung Galaxy 9]
 - OS: [e.g. Android 8]
 - QField version: qgield master-dev af01c8

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Thanks !

**Comment by nirvn** [comment]
@Ipickedausername , is it still an issue for you using QField 3.2.0? I'm pretty sure we fixed this a while back.

**Comment by Ipickedausername** [comment]
Hi, 

This issue is fixed indeed. I close it.
