### ISSUE TITLE
Always open child form in the first container

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#4512]
Hello, 

When a child feature is added, the displayed container is always the last one that was open. 
If there is 4 containers and you save the feature while you were on the third one, then when you add a second  child it will open on the third container. 

I suppose it should always show the first container (I didn't check what happen if the third container visibility depends on a value from the first container, which one is missing when we add a child). 

Here is a video that shows this behavior:

https://github.com/opengisch/QField/assets/72577399/16d67513-8ab7-42d2-a0ea-61de438346af

### Desktop (please complete the following information)
 - OS: [e.g. Windows 10]
 - QGIS Version [ 3.26.0]
 - QFieldSync Version [.4.a.0]

### Mobile (please complete the following information)
 - Device: [samsung Galaxy 9]
 - OS: [e.g. Android 8]
 - QField version: qgield master-dev af01c8
 
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Thank you !

**Comment by she-weeds** [comment]
Just FYI your post shows only a thumbnail jpg, not a video.

**Comment by Ipickedausername** [comment]
Post edited. Thank you :)

**Comment by nirvn** [comment]
@Ipickedausername , could you attach a small test project for this? Thanks

**Comment by suricactus** [comment]
@Ipickedausername thanks for backreferencing! Should be fixed by #5436.

**Comment by suricactus** [comment]
Ah, if I prematurely closed the issue, please reopen, sorry for the noise.
