### ISSUE TITLE
QfieldCloud rejected project creation :API error

### ISSUE THREAD

**Issue by Bvpraagh** [opengisch/QField#4513]
### I have been tying to upload a project to Qfield Cloud for over a day. It keeps getting rejected on the basis of an API error.
I am doing nothing different to what I normally do.

Create Project in QGIS using template. 
save template in new project folder with new name
points in a geopackage
convert currently open project to cloud project
attempt to upoad to cloud
error  message and cloud rejected
 

### Expected behavior
Upload to cloud immediately
### Observed behavior
project rejected

### Screenshots and GIFs
![image](https://github.com/opengisch/QField/assets/104828477/e452be7c-c536-430d-8685-340c5e0eecdc)

[

**Comment by SeqLaz** [comment]
We appreciate you bringing this issue to our attention. Your report will greatly assist us in addressing and resolving the problem.

For more quick assistance with this matter, we recommend reaching out to our dedicated support team. You can easily do so by clicking on the question mark located in the bottom right corner of the QFieldCloud platform. Our support team is always ready to provide you with the necessary help and guidance, please don't hesitate to reach out.

Best regards.

**Comment by SeqLaz** [comment]
As a recommendation could you try the following workflow: 

1. Create a new empty project in QFieldCloud.
2. Synchronize this project on your computer using QField Sync. Select an empty folder for this synchronization.
3. After the synchronization, paste the project that you have been working on into this folder.
4. And re-synchronize to upload the files to QFieldCloud.

A similar workflow is detailed in our documentation, accessible through the following link: https://docs.qfield.org/get-started/tutorials/get-started-qfc/#create-a-project-in-an-organization

**Comment by SeqLaz** [comment]
We appreciate your feedback.

Could you kindly reach out to our support team through the ticket system, providing the specific details of the project that is generating the error? The more details you can offer regarding the issue, the better our team can assist.

We apologize for any inconvenience caused and are dedicated to resolving this matter promptly.

Best regards.
