### ISSUE TITLE
new shape file stuck in "read only" state - qfield cloud

### ISSUE THREAD

**Issue by ewaca** [opengisch/QField#4519]
### Describe the issue
New shape file stuck in read only state

### Reproduction steps
create new projet
import several existing shapefile
Create a new shape file
sync data on qfield cloud
load qfield project on qfield app
all exisiting shapefile are editable, only the new shape file is in read only state

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: window 11 22h2
 - QGIS Version : LTR 3.28.9-Firenze
 - QFieldSync Version v4.5.0

### Mobile (please complete the following information)
 - Device: corss call core x4
 - OS: Android 10
 - QField version: 2.8.5

### Additional information
I have tried to put all layers in read only value on qgis, all layers are in read only on qfield, then uncheck read only on qgis, sync, all layers are editable expect the created shapefile 

Qfield cloud projet  name : Anneville
qfield cloud account : ewaca.

i will try to load project with usb cable.

**Comment by ewaca** [comment]
I copied the project folder to the phone. From the phone, I opened a local folder, and the layer that was in "read only" state is editable now.
The problem seems to come from conversion step when exporting to qfield cloud.

**Comment by SeqLaz** [comment]
To effectively address this concern, I highly recommend transitioning your data source from the shapefile format (.shp) to GeoPackage format (.gpkg). GeoPackage is the official data source format supported by both QField and QFieldCloud, offering numerous benefits such as enhanced performance, improved compatibility, and fewer limitations.

Additionally, the lock functionality within QFieldCloud is linked to the absence of a proper configured "fid" field within the layer. This field is essential for facilitating proper synchronization updates that are pushed from QField.

If you require further clarification or have additional questions, please don't hesitate to reach out to us. You can do so by clicking on the question mark located in the right corner of the QFieldCloud platform. Our support team is dedicated to providing assistance whenever you need it.

Best regards.
