### ISSUE TITLE
QField Cloud not downloading data collected in field onto computer- local files deleted

### ISSUE THREAD

**Issue by hcg0509** [opengisch/QField#4527]
I have used this same project before, and now I am having issues with getting data from the cloud onto my machine.

I am helping someone (not me) with doing this, so the initial mistake I think was this:

1. Data were collected in the field on tablet.
2. Data were successfully pushed from tablet to cloud. I can see the data and the changes to the geopackage in the QField Cloud account online. I have downloaded the most recent version of the geopackage from the qfield cloud website and the new data collected in the field is present in the cloud.
3. When the person went to pull data from the cloud onto their machine, they chose "prefer cloud". For some reason when this happened, instead of replacing the local file with the cloud file, it deleted the local file. (the person did not know this was happening).
4. Now when going to sync, the geopackage does not show up at all. Cannot be pushed to the cloud or pulled down to the computer.
Why did this happen in the first place? I have never had an issue after the field trying to download data and the local files being deleted. How can I "restore" the local file?

Here is what I see regarding the issues above (picture).

The red points are data collected from the first sampling session.

### Expected behavior
When the person went to pull data from the cloud onto their machine, they chose "prefer cloud". Replace the local file with the cloud file

### Observed behavior
When the person went to pull data from the cloud onto their machine, they chose "prefer cloud". For some reason when this happened, instead of replacing the local file with the cloud file, it deleted the local file. (the person did not know this was happening).

Now when going to sync, the geopackage does not show up at all. Cannot be pushed to the cloud or pulled down to the computer.
Why did this happen in the first place? I have never had an issue after the field trying to download data and the local files being deleted. How can I "restore" the local file?

### Screenshots and GIFs
![image](https://github.com/opengisch/QField/assets/142808354/e667ce03-2d75-430f-b744-bd183bcb7c33)

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.3.0
 - QFieldSync Version 4.2.0

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Unclear
* Problem happens with all files and projects, not only some files or projects: Yes

[jstoller; marys_rive_subbasin_hybridization_sampling]

**Comment by SeqLaz** [comment]
We appreciate you bringing this issue to our attention. Your report will greatly assist us in addressing and resolving the problem.

For more quick assistance with this matter, we recommend reaching out to our dedicated support team. You can easily do so by clicking on the question mark located in the bottom right corner of the QFieldCloud platform. Our support team is always ready to provide you with the necessary help and guidance, please don't hesitate to reach out.

Best regards.
