### ISSUE TITLE
High data consumption by QField 

### ISSUE THREAD

**Issue by chleeb** [opengisch/QField#4554]
Hi,

we have observed very high data consumption by QField lately, which is very problematic because we have incurred high costs as a result.

In one case, the data consumption was about 60 GB within a few days, in another case it was 9.38 GB within of three days.

We are using the QFieldCloud for data storage, so the data traffic might be linked to the synchronisation with the cloud. However, the data storage of of QFieldCloud is 4 GB, whereby usually <3 GB are used and the projects that had been synchronised have only some MB. In the case where 9.38 GB were consumbed two projects with abolut 20 MB were downloaded. Both maps have WMS-background maps, but they are usually only consume some MB (we are working with projects of this kind since month).

For the moment we decided to work offline, but this can't be the solution for the future. 

Any idea what is going on?

Basic information:
* Device: Samsung Galaxy Tab Pro LTE SM-T545
* Android version: 11
* QField version: Qfield 2.8.3-insightful Indri (256868 v2.8.3)
* QFieldCloud organisation: bfw_waldbio
* QFieldCloud user name: fmeyer (but also others)
* QFieldCloud project: e.g. id256, id795
* Problem started happening recently, didn't happen in an older version of QField: yes (last months)
* Problem can be reliably reproduced, doesn't happen randomly: no
* Problem happens with all files and projects, not only some files or projects: different projects, but don't know if with all.

Screenshot showing the data consumption:

![MicrosoftTeams-image (47)](https://github.com/opengisch/QField/assets/89195127/726fd9f6-e97c-49f2-af3b-e99cafe74bac)

Best,
Christoph

**Comment by SeqLaz** [comment]
Hello,

When you synchronize the entire QField project, as a security measure, backup copies of the layers are generated. These backups are stored both locally on your device and in the QFieldCloud platform. In QFieldCloud, you have the option to specify the number of versions you would like to retain. You can adjust this setting within the project's configuration section.

If you have any additional questions or concerns, please don't hesitate to reach out to us. You can do so by clicking on the question mark in the right corner of the QFieldCloud platform. Our support team is always ready to assist you.

Best regards.
