### ISSUE TITLE
Unable to find server/permission denied

### ISSUE THREAD

**Issue by Cotnap** [opengisch/QField#4555]
Using iphone 12 & Mac pro on Ventura 13.4.1 I have lost all access to QFieldCloud. 

Everything seemed to be working ok up to yesterday when I needed to load a new project.

Initially attempted to load an offline project to device which didn't work. Copying project to Imported Projects.
Then tried to load using cloud but was required to log in unsuccessfully with message saying Server couldn't be found or URL incorrect.
Tried to add app.qfield.cloud as server without any success.
Reloaded app and now get QF/permission_denied.
QFieldcloud appears to be working okay on laptop.
I was supposed to be pitching this to a potential user in 3 hours!!!!
User name is Dight
On community plan and only used 60% of storage

**Comment by SeqLaz** [comment]
Hello,

The functionality to directly import projects and datasets is available on Android. 

Regarding when it comes to selecting a server, it's often best to leave this field empty. By doing so, QField will attempt to connect to the default server. For more detailed instructions, please refer to the following documentation:

https://docs.qfield.org/get-started/tutorials/get-started-qfc/#change-the-default-qfieldcloud-server-in-qfield-and-qfield-sync

If you have any additional questions or concerns, please don't hesitate to reach out to us. You can do so by clicking on the question mark in the right corner of the QFieldCloud platform. Our support team is always ready to assist you.

Best regards.
