### ISSUE TITLE
Qfield cloud not pushing ongoing tracking from mobile phone

### ISSUE THREAD

**Issue by GuyGeneau** [opengisch/QField#4578]
### Reproduction steps
1. [Open a tracking on a layer and take some positionning]
2. [Open the cloud option and push the modification of the user']
3. [Open the QGIScloud  project to see that the tracking is not there ]
4. Try to resend it from the mobile.

### Expected behavior
[Pause the tracking to send the informations taken so far or stop the tracking to start a new one after the push.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
- OS: [Windows] Windows 10 Professionnel
- QGIS Version 3.28
- QFieldSync Version 4.4.9

### Mobile (please complete the following information)
- Device: Galaxy A50
- OS: Android 11
- QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]
2.8.5 insightful indri (cd8dd5 v2.8.5)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Just noticed so probably No]
Allo Guy : Habituellement il fermait le tracé, et l’envoyait de chez lui. Alors difficile de dire si ça aurait pu le faire avant ou si c’est un nouveau problème. 
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

[If the problem happened with QFieldCloud, please add your username and project name.]
Username : Arie_comptePERSO
Project name: Qfield_leger_20230518-C

**Comment by nirvn** [comment]
This has been resolved.
