### ISSUE TITLE
Connect to Garmin GLO iPad

### ISSUE THREAD

**Issue by jescott2** [opengisch/QField#4582]
### Describe the issue
Garmin GLO is a popular external GPS receiver but connects via Bluetooth which Qfield does not support for iPad.

### Reproduction steps
1. [Go to '...']
2. [Click on '...']
3. [Scroll down to '...']

### Expected behavior
Is connection to external receiver via Bluetooth in the plans for Qfield on the iPad

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.32.2
 - QFieldSync Version 2.83

### Mobile (please complete the following information)
 - Device: iPad (gen 8) WiFi & Cell
 - OS: iOS 16.6
 - QField version: 2.8.3 256868

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@jescott2 , I'm closing this as the lack of direct Bluetooth connection support on iOS is an upstream limitation that is out of our control (and isn't likely to be fixed/implemented any time soon). Usually iOS users rely on the GNSS vendor app to stream NMEA sentences via TCP, which QField supports. Hopefully it's an option for you.

**Comment by jescott2** [comment]
I found a 3rd party app for a different receiver which is working, okay. Thanks.

**Comment by nirvn** [comment]
@jescott2 , do you mind sharing the name? It might help others looking for connecting their gnss devices to QField:)

**Comment by jescott2** [comment]
Receiver: DUAL Electronics https://www.dualav.com/product/gps-solutions/gps/xgps150a-universal-gps-receiver/
Helper App: https://apps.apple.com/us/app/nmea-gps/id590868529
The only info lacking seems to be the error estimate.
