### ISSUE TITLE
QField photos stored as a File instead on jpg

### ISSUE THREAD

**Issue by Jessie42** [opengisch/QField#4583]
### Describe the issue
Photos are sometimes stored as 'File' in a folder called 'files' instead of as a jpg in the 'DCIM' folder. A single project can have a combination of photos stored in the DCIM folder and in the file folder. Photos stored in the 'files' folder need to be converted before they can be opened as a jpg

### Reproduction steps
1. In 'Attributes Form' the photo field is set as an attachment and the path is stored as 'Relative to Project Path' 
2. It only happens in some projects and not others. Both projects have the same set up
3. Take photos in QField 
4. Export the project back onto the computer and there is 2 folders 'DCIM' and 'files'

### Expected behavior
I would expect all photos to be stored as jpg in the 'DCIM' folder

### Observed behavior
[A clear and concise description of what actually happened.]
Photos are stored in the DCIM folder and in a folder called 'files'. These files need to be converted before they can be opened as a jpg.

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.
![image](https://github.com/opengisch/QField/assets/25470785/24b3d610-a951-44e7-afea-04eb890aaaf2)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS:  Windows
 - QGIS Version  3.32.2
 - QFieldSync Version [4.6.0]

### Mobile (please complete the following information)
 - Device: Oppo A54s
 - OS: Android 13
 - QField version: 2.8.7 - Insightful Indri (4d464e v2.8.7)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: No - but happening more frequently
* Problem happens with all files and projects, not only some files or projects: Yes

I have uninstalled and reinstalled the app and cleared caches with the problem still occurring.

**Comment by VxTedxV** [comment]
Native camera in QField settings ?
May your device able to take photos in RAW format ? (with or without additional app)

**Comment by nirvn** [comment]
@Jessie42 , you can customize the location of your photos via the vector layer properties dialog's QField tab:

![image](https://github.com/opengisch/QField/assets/1728657/6f6ad626-6af3-4881-b53b-d93d77e5e166)

**Comment by Jessie42** [comment]
Hi @nirvn, 
I have customised my photos and they still get added as 'file' into the 'File' folder.
@VxTedxV this problem still happens in RAW format

![image](https://github.com/opengisch/QField/assets/25470785/b608f678-6aec-443e-87a6-7991e9b53e91)
![image](https://github.com/opengisch/QField/assets/25470785/112f00a1-66e9-4edd-ab04-bb87a88bbe27)

**Comment by nirvn** [comment]
@Jessie42 , are you able to share a reduced version of your project that replicates the issue?

**Comment by Jessie42** [comment]
@nirvn here is a reduced version of the project 
[QField Photo Test.zip](https://github.com/opengisch/QField/files/12710277/QField.Photo.Test.zip)

**Comment by nirvn** [comment]
@Jessie42 , OK, the problem is with your expression: `'DCIM/' || "label" || '_' || format_date(now(),'yyMMdd_hhmmss') || '.jpg'`. If you have not entered a value for the "label" field yet, that will be null and will result in a null/empty evaluated expression value. In that case, QField will fallback to default values. Since your integrated document viewer type combobox is set to 'No Content', QField considers the attachment as a generic file.

You have two options:
1/ improve your expression by handling a null "label" value, e.g.: `'DCIM/' || coalesce("label",'') || '_' || format_date(now(),'yyMMdd_hhmmss') || '.jpg'`
2/ set the integrated document viewer type combobox to image

Cheers.
