### ISSUE TITLE
Tracking Issue

### ISSUE THREAD

**Issue by shapley** [opengisch/QField#4598]
### Discussed in https://github.com/opengisch/QField/discussions/4576

<div type='discussions-op-text'>

<sup>Originally posted by **shapley** September 14, 2023</sup>
Hi,

A small group of three people went out to try 3 Android 10 or above devices (3 x samsung galaxy's plus one galaxy tablet) and an iOS device and tested them all with 'Tracking' enabled. We found that 2 Android devices were able to plot points every 30 seconds (default settings on all devices were checked to ensure they were the same) whereas the iOS, SG Tablet, and two Android devices would only plot the first track point then the gps arrow 'seeks' in a continuous line but doesn't plot any further points. 

At first I thought it was the QField settings in each device but they were all identical. Has anyone had this issue? I think it is possible there is a setting somewhere to rectify this problem but don't know where to start looking. Any hints to check?</div>

**Comment by nirvn** [comment]
@shapley , we've applied a bunch of improvements to the tracking code in upcoming QField 3.0; could you try the APKs here (https://github.com/opengisch/QField/pull/4590) to check whether your issue has been fixed?

**Comment by shapley** [comment]
The problem seems to have gone with the version 3.0.2
