### ISSUE TITLE
Cannot Digitize/Double fields

### ISSUE THREAD

**Issue by nsm91** [opengisch/QField#46]
I cannot digitize in the QField mobile app at all any longer since installing the second most recent update maybe a week ago. Also, when choosing which field to digitize it shows me two entries for each, one with Capital letters (as they appear in the .sqlite database) and one with lower letters as the layers appear in QGIS layers panel. Neither allow me to create a point that is visible.

**Comment by m-kuhn** [comment]
Which version?

**Comment by nsm91** [comment]
0.6.2 is what I am currently using, I don't recall what the other was but I imagine 0.6 or 0.6.1 because the patch in between was small ~27mb. Attached are the files I'm working with
[Trees.zip](https://github.com/opengisch/QField/files/348392/Trees.zip)

**Comment by m-kuhn** [comment]
There seems to be something strange with your project file:

Running the following code in the QGIS python console:

```
>>> QgsMapLayerRegistry.instance().mapLayers()
{u'Streets20160628104823397': <qgis._core.QgsVectorLayer object at 0x7f06ec4292b0>, 
u'pavement20160629124820131': <qgis._core.QgsVectorLayer object at 0x7f06ec429f28>, 
u'trees20160624142713955': <qgis._core.QgsVectorLayer object at 0x7f06ec43b0e8>, 
u'parcels20160624142724703': <qgis._core.QgsVectorLayer object at 0x7f06ec429180>, 
u'streets20160624142716858': <qgis._core.QgsVectorLayer object at 0x7f06ec43b050>, 
u'Trees20160701130900833': <qgis._core.QgsVectorLayer object at 0x7f06ec429218>}
>>> len(QgsMapLayerRegistry.instance().mapLayers())
6
```

I'd start a new project and re-import the existing symbology. This seems to be an upstream QGIS issue that there are map layers which do not appear in the legend.

If you still have troubles after starting with a new project, please reopen this issue (or start a new one).
