### ISSUE TITLE
QField 1.0.0-rc1 not working with Samsung galaxy S4

### ISSUE THREAD

**Issue by anotheruserhere** [opengisch/QField#461]
QField 1.0.0-rc1 on Samsung Galaxy S4 (running Android 4.4.2) doesn't work for me.

When I open QField the app crash straight away.

I have uninstalled QField 1.0.0-rc1, installed Lucendro (0.11.11) instead and everything works fine.

**Comment by giedrioks26** [comment]
same with QField 1.0.0-rc2 on Blackview BW9000 pro (android 8.0). Crash when opening.

**Comment by m-kuhn** [comment]
@giedrioks26 does https://download.opengis.ch/qfield/ci-builds/qfield-dev--234e69e3f76473de32c03507338419be878df3d6-armv7.apk work for you?

**Comment by m-kuhn** [comment]
@anotheruserhere that's probably a duplicate of https://github.com/opengisch/QField/issues/434

**Comment by anotheruserhere** [comment]
@m-kuhn yes more than likely.

**Comment by mbernasocchi** [comment]
@giedrioks26 we just pushed RC3 to the playstore beta channel, can you try? cheers

**Comment by giedrioks26** [comment]
@m-kuhn yes, it work :)
@mbernasocchi in playstore I see only rc1 (although recently it was rc2). From here https://github.com/opengisch/QField/releases/download/v1.0.0-rc3/qfield-v1.0.0-rc3-armv7.apk work fine

**Comment by giedrioks26** [comment]
@mbernasocchi I get rc3 version from playstore. Works fine. No crashed at startup.  I don't know how to work with andrioid 4.4. We are no longer using it. No chance to try.

**Comment by mbernasocchi** [comment]
Ok thanks. Maybe somebody else stumbles to this issue and will report :)
