### ISSUE TITLE
Opening Google Maps URL

### ISSUE THREAD

**Issue by EmmanueleMereu** [opengisch/QField#4615]
### Describe the issue
Google Maps URLS does not work as expected: clicking on link opens Maps app however, it is shown the last viewed location, not the one requested by URL. 

### Reproduction steps
1. On a string type field with enough characters paste this URL:
[https://www.google.com/maps/search/?api=1&query=47.5951518%2C-122.3316393&query_place_id=ChIJKxjxuaNqkFQR3CK6O1HNNqY](url)
2. Save changes and click on it.
3. Maps app gets launched but it shows the same screen as last time it was closed.

### Expected behavior
As shown on developers page, [https://developers.google.com/maps/documentation/urls/get-started?hl=en](url), it should result in a markplace on CenturyLink Field.
Link works perfectly when I export the attribute table and open it from Excel.

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.28
 - QFieldSync Version 4.6.0

### Mobile (please complete the following information)
 - Device: Samsung S10e
 - OS: Android 12
 - QField version: 2.8.7

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes, but can't tell which version last worked
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by MarcoVavassori90** [comment]
I have the same problem

**Comment by nirvn** [comment]
@EmmanueleMereu , if you could share a geopackage file with a couple of sample URLs, that'd be helpful.

The likelihood of this being QField-specific vs. the way Google Maps' Android app handles suspension/resuming is 50/50 IMHO :wink:

**Comment by EmmanueleMereu** [comment]
> @EmmanueleMereu , if you could share a geopackage file with a couple of sample URLs, that'd be helpful.
> 
> The likelihood of this being QField-specific vs. the way Google Maps' Android app handles suspension/resuming is 50/50 IMHO 😉

Certainly, here is a geopackage file. 
There are two fields: the first one contains the link constructed using a field calculator expression based on the point's coordinates in the EPSG:4326 reference system, while the second one is simply a copy-paste from the developers page. 

Thank you for your interest.

[GOOGLE_MAPS_URL.zip](https://github.com/opengisch/QField/files/12844848/GOOGLE_MAPS_URL.zip)

**Comment by nirvn** [comment]
@EmmanueleMereu , thanks, your sample dataset helped me figure out what was wrong here. Fix in this APK: https://github.com/opengisch/QField/pull/4616

**Comment by EmmanueleMereu** [comment]
Mano thanks for resolving this issue, your help is greatly appreciated.
