### ISSUE TITLE
Antenna height is neglected

### ISSUE THREAD

**Issue by DrThomasK** [opengisch/QField#4618]
### Describe the issue
The height correction does not change anything. If I enter an antenna height of 1,4 m the shown and recorded value is still the same as with no correction at all.

### Reproduction steps
(German Version)
1. activate QField Einstellungen–>Höhenkompensation der Antenne (Config–>Height compensation for antenna)
2. enter Height as 1,4 m
3. back to Working screen

### Expected behavior
shown height should be reduced by 1,4 m
recorded height should be reduced by 1,4 m

### Observed behavior
height does not change, shown and recorded values identical and unchanged with respect to disabled height compensation

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: 
 - QGIS Version 
 - QFieldSync Version 

### Mobile (please complete the following information)
 - Device: iPad
 - OS: iPadOS 16.6.1.
 - QField version: 2.8.3
  
### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@DrThomasK , this should be fixed in QField 3.0, which will be released by the end of the month.
