### ISSUE TITLE
Attaching image automatically rotates 90° when setting picture maximum size in QField project preferences

### ISSUE THREAD

**Issue by StevenSteeno** [opengisch/QField#4620]
### Describe the issue
On the latest QField version when adding images in the attachment widget with the image document viewer and having the maximum image size set automatically rotates the image on android mobile devices using both native as none native camera.

### Expected behavior
the resized image should retain the orginal rotation

### Observed behavior
On android devices, attached images using the device camera automatically rotates the photo 90°

### Desktop (please complete the following information)
 - OS: Windows 10 and 11
 - QGIS Version 3.32.3
 - QFieldSync Version 4.6.0

### Mobile (please complete the following information)
 - Device: samsung galaxy tab or galaxy S23 (both presented the problem)
 - OS: Android one ui 5.1
 - QField version: 2.8.7

**Comment by nirvn** [comment]
@StevenSteeno , I believe we've just fixed this. Can you try the APK here: https://github.com/opengisch/QField/pull/4696
