### ISSUE TITLE
Relation Reference Editor cannot delete child records

### ISSUE THREAD

**Issue by amgiss** [opengisch/QField#4631]
### Describe the issue
After updating to version 3 the relation reference editor no longer allows deleting child records from a parent.

### Reproduction steps
1. Select parent object with related child records
2. Click edit to enable the relation reference controls
3. Editing existing records or adding new child records appears to work, but the delete trash can icon no longer deletes existing child records

### Expected behavior
Deleting child records would happen as per previous versions

### Observed behavior
The delete icon appears to do nothing in both the WIndows and Android versions tested.

### Desktop (please complete the following information)
 - OS: Windows 10 x64
 - QField version: 3.0.0 (fb70fb v3.0.0)

### Mobile (please complete the following information)
 - Device: Android Tablet
 - OS: Android 7
 - QField version: 3.0.0 fb70fb v3.0.0)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Don't know

**Comment by nirvn** [comment]
@amgiss , I'm not able to replicate locally, could you share steps to reproduce and a sample project?

**Comment by nirvn** [comment]
@amgiss , thanks for reporting this regression, it'll be fixed in the next point release.
