### ISSUE TITLE
Virtual field and QML Widget together cause crash

### ISSUE THREAD

**Issue by nicpitsch** [opengisch/QField#4636]
### Describe the issue

This combination in edit form crashes QField:

- Create a virtual text field (I named it *vrt_Field1*) containing a string expression like `'test'`. Add it to the Attributes Form and set it's Widget Type to *Text Edit, Multiline, HTML*.
- Add a QML Widget to the Attributes Form and set it's content to `expression.evaluate("\"text1\"")`. Where *text1* is an field of the layer *point1*

The *point1* layer was created in a *test1.gpkg* using `create table point1 (fid integer primary key autoincrement not null, geom POINT(2056) not null, text1 text);`.

### Reproduction steps

Steps to reproduce the issue:
1. Either create a project based on the issue description or download [this zip](https://cloud.pitsch-ing.ch/s/ZZCQMBFLB2kzBA8) and open it with QField.
2. Tipp to the point feature, open the form.
3. Close the form and tipp again the point feature, open the form. => QField crashes, that is the QField App closes.

### Expected behavior

The crash should not happen.

### Observed behavior

As QField closes without a message I didn't observe anything which could explain the problem.

### Screenshots and GIFs

Relevant QGIS project settings to reproduce the constellation which causes the issue.

Virtual Field definition and usage:

![grafik](https://github.com/opengisch/QField/assets/1652835/33f237e8-3908-4684-a04a-ec2b908fe84d)

QML Widget settings:

![grafik](https://github.com/opengisch/QField/assets/1652835/2ad3f415-cb19-46c3-ab33-2dbee6e9e2a0)

### Issue solving

Either remove the QML Widget or uncheck the virtual field properties *Multiline* and *HTML*!

### Discussion

This issue is reproducible by setting up a very primitive QGIS respectively QField project. In real world I have two large projects which have the combination of that properties. This issue is a show stopper for the users.

### Desktop (please complete the following information)

 - OS: Windows
 - QGIS Version 3.32.3
 - QFieldSync Version: not involved

### Mobile (please complete the following information)

 - Device: Pixel 6 and (other) tablets.
 - OS: Android 13, tablets: Android 8.
 - QField version: 3.0.0

### Additional information

* Problem started happening recently, **didn't happen in an older versions** of QField: Yes.
* Problem can be reliably reproduced, doesn't happen randomly: Yes.
* Problem happens with all files and projects, not only some files or projects: Yes, using the specific setting.

**Comment by nirvn** [comment]
@nicpitsch , thanks for the report. The issue has been fixed, and APKs will be available in this pull request for you to test and confirm the crasher is gone: https://github.com/opengisch/QField/pull/4638

**Comment by nicpitsch** [comment]
I can confirm that #4644 resolves this issue. Thanks a lot @nirvn.
