### ISSUE TITLE
Features not able to be selected (seemingly random)

### ISSUE THREAD

**Issue by falcon5nz** [opengisch/QField#4641]
### Describe the issue
I cannot select certain point features from a layer, but can select other features. I could select everything on V2.8.7, upgraded to V3.0.0 and couldn't select them, same behaviour with 3.0.1. I have rolled back to V2.8.7 and can select all features. The behaviour seems limited to one layer. I can open the features via the attribute table.

(PS I am new to GitHub so hope I have done this all correctly)

### Reproduction steps
1. [Go to '...']
2. [Click on '...']
3. [Scroll down to '...']

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.28.2-Firenze
 - QFieldSync Version 4.6.0

### Mobile (please complete the following information)
 - Device: Samsung S23+ SM-S916B/DS
 - OS: Android 13
 - QField version: Issue occurs on 3.0.1 - Amazonia (ccf18a v3.0.1) and works fine on 2.8.7 Insightful Indri (4d464e v2.8.7)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField:Yes
* Problem can be reliably reproduced, doesn't happen randomly: Sort of. The features I cannot select are consistently unselectable, but seemingly random. I.e. If I can't select it, I can't select it regardless of what I try, but I can't predict which features I will not be able to select.
* Problem happens with all files and projects, not only some files or projects: No

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@falcon5nz , a test project or a screencast would help replicate this issue. Are you using a stylus?

**Comment by nirvn** [comment]
@falcon5nz , give the APKs in this PR (https://github.com/opengisch/QField/pull/4652) a try, it might have fixed what you felt like random failures.

**Comment by nirvn** [comment]
@falcon5nz , gentle ping, are you able to provide some feedback?
