### ISSUE TITLE
DATE WIDGET IN QFIELD 3.0 STAY ON LOCKED ON SPECIFIQUE DATE

### ISSUE THREAD

**Issue by Sekou225** [opengisch/QField#4650]
### Describe the issue
When a field in a layer is typed as date data type and configured to show the date widget while edition, the widget appears but stay locked on a specifique date, whitout any possibility to change it. 

### Reproduction steps
1. Open your project
2. Click on a feature and start editing its attributes
3. Locate the date field (that zou configured first on QGIS)
4. Click on the date widget (or directly try to fill the date field)
5. The date widget will appear, showing JANUARY 2020
6. If zou try to move to an other month or year, you will see that it don't work

### Expected behavior
The widget should give ability to move forward and backward in the calendar.

### Observed behavior
The calendar stay locked on JANUARY 2020

### Screenshots and GIFs
![image](https://github.com/opengisch/QField/assets/91322749/19676dfe-c6b5-4590-8eaf-041a5b41e688)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10 Enterprise 22H2
 - QGIS Version 3.30.0-'s-Hertogenbosch
 - QFieldSync Version 3.0.0 Amazonia
 - Device: Dell Latitude 5531

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by BoswachterMarc** [comment]
Same issue here 👍

**Comment by BoswachterMarc** [comment]
https://github.com/opengisch/QField/assets/57868975/b7923988-1ce5-4c45-849e-e460e0f0c201

**Comment by Sekou225** [comment]
The last QGIS use a lower version of QT than Qfield. It may be the source of this problems, and many others. I'm not developper, it's just hypothesis, i can be wrong.

**Comment by nirvn** [comment]
@Sekou225 , @BoswachterMarc , fix in this PR: https://github.com/opengisch/QField/pull/4651

**Comment by BoswachterMarc** [comment]
@nirvn Yes, the calender is 'dynamic' again/fixed with apk #4651
