### ISSUE TITLE
Use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by danieldegroot2** [opengisch/QField#4656]
I would like to suggest using the now preferred https://tile.openstreetmap.org URL instead of the [current one](https://github.com/search?q=repo%3Aopengisch%2FQField+.tile.openstreetmap.org&type=code), see

https://github.com/openstreetmap/operations/issues/737

And, try to [update other repositories](https://github.com/search?q=org%3Aopengisch+.tile.openstreetmap.org&type=code) too, please.

**Comment by nirvn** [comment]
@danieldegroot2 , well spotted, thanks for filing an issue. It'll be fixed today and deployed just in time for QField 3.0's public release.

**Comment by danieldegroot2** [comment]
It seems [other repositories](https://github.com/search?q=org%3Aopengisch+.tile.openstreetmap.org&type=code) are still outdated.

cc @nirvn Could you let others in your organization know, please?
(assuming these repositories are still maintained.)
