### ISSUE TITLE
Geometry editing: Ring tool not working in v 3.0.2

### ISSUE THREAD

**Issue by stm21** [opengisch/QField#4663]
I'm working in a local QField project on a android tablet (Android 11). 
I want to digitize different polygons (shapefiles). 

In version 2.8.5 I could edit the geometry of a polygon with the "Ring Tool"
Since I installed the latest version od QField 3.0.2 it doesn't work anymore although it shows up in the lower right.
I assume I can select the tool, as the sign in the upper left changes to the correct one to finish editing. But when changing to the "Ring Tool" there appears no text in the lower middle like with the other tools. And I can't draw any ring.
All the other four tools I can select and use.

![Screenshot_20231019-140233 1](https://github.com/opengisch/QField/assets/148454528/90e4c8b7-efe3-49d7-91e3-4f1f6e41c8ae)

**Comment by nirvn** [comment]
@stm21 , thanks for reporting this regression, it's fixed. APKs here: https://github.com/opengisch/QField/pull/4664
