### ISSUE TITLE
QField 3.0.2 open empty projects

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#4669]
### Describe the issue
Since last update (QField 3.0.2), my projects can't be opened. When I select one to be opened, no layer is shown. It's blank. At first opening since last update, the scale shows a very high number (like zoomed on a world size instead of the last tiny zone the project was centered on) and if I open twice the same project it saves the previous zoom level but stays blank. GPS works. I can see all the menus/buttons but layers list is blank and mapscreen too. Happened to any project. All these projects used to open correctly before.
Projects SCR = EPSG:2154
May projects created with old QGis version (but updated with last ones after) be the reason why ?
I can't provide files for now.

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version : 3.32
 - QFieldSync Version : not used to upload my projects

### Mobile (please complete the following information)
 - Device: Samsung Galaxy A13
 - OS: Android 13
 - QField version: 3.0.2 (dfa8a6)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@VxTedxV , that sounds dramatic. Have you tried to uninstall QField then reinstall it to see if the issue has to do with it having been updated from a previous version?

Is there anything that shows in the message logs that could help us?

Since we've not seen this in the multiplicity of tests we have gone through, we'll likely need a sample project to replicate the situation. If you can't share in this public space, you can always send one privately to my email address (mathieu@opengis.ch).

**Comment by nirvn** [comment]
@VxTedxV , one last thing: is the sample bees project working on your device?

**Comment by ztgis** [comment]
I confirm this issue. The bee project is NOT affected. I transfer my project in a ZIP via URL on my IPhone. The project opens blank without error messages or warnings. The layer list and also the log are empty.

**Comment by nirvn** [comment]
@ztgis , please provide a sample project

**Comment by ztgis** [comment]
I will try to create a minimum project without sensible data.

**Comment by nirvn** [comment]
@ztgis , much appreciated

**Comment by nirvn** [comment]
@ztgis , if you can share screencasts too, that could help. On my end, I've not been able to replicate this situation.

**Comment by ztgis** [comment]
I think, the issue is triggered by custom fonts.

**Comment by ztgis** [comment]
Sample projects:

- Bad project with symbology containing custom font: http://www.sgroe.at/vkn/qfield3-empty.zip
- Good project with symbology without font marker: http://www.sgroe.at/vkn/qfield3-ok.zip

**Comment by nirvn** [comment]
@ztgis , super useful, I can replicate on my phone now.

**Comment by shapley** [comment]
I have the same issue when upgraded to 3.0.2 Amazonia (dfa8a6) on Android 10 on a Samsung Galaxy S9 ( (SM-G960F). I've uninstalled and re-installed (from the Aurora Store) but the issue remains. Haven't found a solution yet. Was working up until 3.0.0

**Comment by nirvn** [comment]
@shapley , if you can share a sample project to replicate your issue it'd be super helpful. The more projects we have the better.

**Comment by draken76** [comment]
I have the same issue. Old projects works normally, but new are empty.
Uninstalled QFIELD and intalled 2.8 and it worked. But after upgrade to 3.03 stopped working.
That was on Samsung Galaxy Note 10

On Huawei P30 3.03 works almost normally (just strange fonts, but I can see layers)

**Comment by nirvn** [comment]
@draken76 , please share a sample project to replicate your issue.

**Comment by nirvn** [comment]
@ztgis , so, part of the problem is that QGIS is allowing for project files to contain invalid XML characters (via the font marker symbol layer). The first 32 characters should not be allowed to be picked:

![image](https://github.com/opengisch/QField/assets/1728657/be82924f-a8a9-40ce-9abe-056bef2e291e)

Any of these options would break the project file itself when opening it with a XML-compliant reader. And while Qt5 was tolerating those, Qt6 is stricter and now fails to load such XML documents. 

If you could file an issue upstream as a QGIS issue, that'd be useful.

**Comment by nirvn** [comment]
@VxTedxV , @ztgis , @draken76 , @shapley , APKs are available in this PR (https://github.com/qgis/QGIS/issues/55037) which should fix your project load issue. Feedback much appreciated.

If the project load still fails (i.e. blank canvas with no layers), QField will now append an error message in its message log, that should help us allow dissect this further if need be.

**Comment by nirvn** [comment]
@VxTedxV , @ztgis , @draken76 , @shapley , oups, pasted the wrong link. This is the correct one: https://github.com/opengisch/QField/pull/4684

**Comment by ztgis** [comment]
@nirvn : I can read my "bad" project that I have posted here. Thank you very much for your investigation and the fix.

**Comment by nirvn** [comment]
@ztgis , we wouldn't have a fix if it was not for your sample project, thanks for the efforts you have been in this too.

**Comment by ztgis** [comment]
@nirvn : Are the first 32 characters invalid in every font? Or is this a Qt6 issue/feature?

**Comment by nirvn** [comment]
@ztgis , they are invalid irrespective of the font, it has to do with characters that are not permitted within XML documents, which is the format QGIS uses.

**Comment by VxTedxV** [comment]
Sorry, coming after the battle, but I can confirm it works again with QField 3.0.4.
Thanks everybody ! 🙂

**Comment by shapley** [comment]
Can confirm the same issue affects QField 3.1.4 on Android (e/OS 1.8) on the Fairphone 4. Sorry cannot send you the project files. Will forward a screenshot shortly...
