### ISSUE TITLE
Qgis/Qfield sync issue - blank layer missing_dataprovider

### ISSUE THREAD

**Issue by jluthman** [opengisch/QField#4686]
### Describe the issue
I have several layers in QGIS 3.22.10.  Everything is just fine in QGIS.  I package and send it to qfield and QGIS has no errors.  Most of the layers are from an ArcGIS REST server.  They load just fine in QGIS.  There are also two QMS layers (Google Maps, Google Satellite).

Qfield.cloud has error:

Warning! Your QGIS project may not work as expected on QField.
Layer "" has an error with code "missing_dataprovider": Check the last "process_projectfile" logs for more info and reupload the project files with the required changes.

This happens when I add the 'Address' layer.  I can fix the problem by removing this layer.  I really really want this layer on Qfield though :)  This layer has the same data source as 11 other layers that have no problems.  

I'm using 43.83% (43.8 MB/100.0 MB) of total storage quota.

On Qfield the layer shows up in the list on the left, but when enabling gives error:
This layer is invalid.  This might be due to a network issue, a missing file or a misconfiguration of the project.

On the Qfield.cloud website I see the file 'Address.gpkg' and I can download it.

### Reproduction steps
For what its worth, this layer did work until a couple of weeks ago.  I don't know what could have changed.

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[A clear and concise description of what actually happened.]

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.22.10
 - QFieldSync Version 4.6.0 (latest in repo 10/24/2023)

### Mobile (please complete the following information)
 - Device: Google Pixel 7
 - OS: Android 14 (UP1a.231005.007)
 - QField version: 2.8.7 & 3.0.3

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]
jluthman/home was many attempts and then I did a new one, below, to see if that would fix it
currently running on jluthman/new

**Comment by SeqLaz** [comment]
Hello  @jluthman

In the Community plan, external connections such as layers from PostGIS or WFS or WCF services cannot be directly utilized. However, you do have the option to make use of XYZ Tiles services.

For more quick assistance with this matter, we recommend reaching out to our dedicated support team. You can easily do so by clicking on the question mark located in the bottom right corner of the QFieldCloud platform. Our support team is always ready to provide you with the necessary help and guidance, please don't hesitate to reach out.

Best regards.

**Comment by jluthman** [comment]
11 of the layers use that connection.  They work just fine.  The Address layer does not work now.  It worked previously (last week).

Why would this be an issue now but not last week?  I wanted to add a different layer, SpliceClosure, which was the only one missing last week.
