### ISSUE TITLE
HTML Widget in attributes form not showing

### ISSUE THREAD

**Issue by baumsicht** [opengisch/QField#4691]
### Describe the issue
Data of HTML Widget in attributes form not showing anymore (worked in QField 2)

### Reproduction steps
1. Generate a HTML Widget in attributes form in QGIS (for example `Baumnummer <script>document.write(expression.evaluate(" \"baumnummer\" || ', ' ||\"baumart\""));</script><br>`)
2. Open project in QField

### Expected behavior
Showing inserted data via widget.

### Observed behavior
Nothing is showed.

### Screenshots and GIFs
QField 2
![Screenshot_QField2](https://github.com/opengisch/QField/assets/54360394/02bee090-9b7c-456d-a427-315b3e9a7178)

QField 3
![Screenshot_QField3](https://github.com/opengisch/QField/assets/54360394/c1573bb4-06df-480b-9853-3f30e6a4c9d5)

### Desktop
 - OS: Windows
 - QGIS Version 3.28.10

### Mobile (please complete the following information)
 - Device: Blackview BV9900
 - OS: Android 9
 - QField version: 3.0.4 f928e3

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes (not in QField 2)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@baumsicht , could you share a sample project please? Thanks

**Comment by baumsicht** [comment]
@nirvn  Thanks for your reply, sample data attached (Object 1234 has data).
[baumkataster_demo.zip](https://github.com/opengisch/QField/files/13185371/baumkataster_demo.zip)

**Comment by nirvn** [comment]
@baumsicht , can you try the APK here: https://github.com/opengisch/QField/pull/4694#issuecomment-1782368548

Thanks

**Comment by baumsicht** [comment]
@nirvn It works, thank you!

**Comment by nirvn** [comment]
@baumsicht , great, thanks for reporting the regression. How's 3.0 for you otherwise? Enjoying the new features?
