### ISSUE TITLE
Feature Not Saved after edit it ( Last Update )

### ISSUE THREAD

**Issue by abdullamuthana** [opengisch/QField#4693]
### Describe the issue
if there is any feature on the map then i want to edit the feature after that the edit i have done not save

### Observed behavior
When i try to edit any feature on the map it said Changes Saved but it's not saved 

### Screenshots and GIFs
Already Added

[Please also attach additional files if a 
![Error Message](https://github.com/opengisch/QField/assets/63540100/dfc7da26-c0d1-42b7-a6a3-b0304c6b18cc)
specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
Qfield Last Update

### Mobile (please complete the following information)
 - Device: [iPhone13 pro max]
 - OS: [Android 11]
 - QField version: 3.0.4 - Amazonia

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes All

**Comment by nirvn** [comment]
@abdullamuthana , can you share a sample project? I'm unable to replicate with the sample bees project shipped with QField.

**Comment by abdullamuthana** [comment]
[test.zip](https://github.com/opengisch/QField/files/13184945/test.zip)
Sure you can use this one and try to edit something in PO layer 

> @abdullamuthana , can you share a sample project? I'm unable to replicate with the sample bees project shipped with QField.

**Comment by nirvn** [comment]
@abdullamuthana , thanks this is helpful.

Turns out that the problem has to do with your geopackage structure. For some reason, your feature ID column in your layers are name-less, i.e.:

![image](https://github.com/opengisch/QField/assets/1728657/cd32d196-e577-4b62-8b7d-fe9e610865ce)

This results in QGIS/gdal not being able to add the feature ID column when sorting features. In QField 3.0, we now sort feature lists, which means in your case that editing sorted features results in a missing ID needed to save the edits.

My suggestion is to simply edit your geopackage and name the fid columns "fid" (you can do that easily using the open source sqlite browser application) That fixes the situation.

You could also file an issue upstream in QGIS, but in this case I think name-less columns is the problem, not QGIS :)

**Comment by abdullamuthana** [comment]
> @abdullamuthana , thanks this is helpful.
> 
> Turns out that the problem has to do with your geopackage structure. For some reason, your feature ID column in your layers are name-less, i.e.:
> 
> ![image](https://user-images.githubusercontent.com/1728657/278545800-cd32d196-e577-4b62-8b7d-fe9e610865ce.png)
> 
> This results in QGIS/gdal not being able to add the feature ID column when sorting features. In QField 3.0, we now sort feature lists, which means in your case that editing sorted features results in a missing ID needed to save the edits.
> 
> My suggestion is to simply edit your geopackage and name the fid columns "fid" (you can do that easily using the open source sqlite browser application) That fixes the situation.
> 
> You could also file an issue upstream in QGIS, but in this case I think name-less columns is the problem, not QGIS :)

You mean the issue happen because the id column is NULL ?

**Comment by nirvn** [comment]
@abdullamuthana , no, I mean the issue is happening because your fid index column has an empty name (i.e. the `"" INTEGER NOT NULL` line).

**Comment by abdullamuthana** [comment]
but why the same project file was working without any problem before the update ?

**Comment by abdullamuthana** [comment]
I got ur idea you mean this is because the first column show as - which mean no name 
<img width="263" alt="image" src="https://github.com/opengisch/QField/assets/63540100/1820352b-d705-453f-93ff-ea5fef85e974">

**Comment by nirvn** [comment]
@abdullamuthana , prior to QField 3.0, we were not sorting feature lists (eg the list you get when identifying features through tapping on the screen). 

Your malformed geopackage leads to the loss of feature ID when sorting features. It is replicable in QGIS too. I'm surprised the geopackage worked at all considering the empty attribute name used for the indexed ID.

**Comment by nirvn** [comment]
@abdullamuthana , exactly 💯

**Comment by abdullamuthana** [comment]
Ok let me try to do name for it

**Comment by abdullamuthana** [comment]
Why i can't do a name for it inside DB Manager of Qgis ? 
<img width="530" alt="image" src="https://github.com/opengisch/QField/assets/63540100/b89b56e1-3210-428f-8027-d42b97de0146">

**Comment by nirvn** [comment]
@abdullamuthana , empty column names have got to break quite a few assumptions in QGIS. 

I was able to rename the column using SQLite Browser.

**Comment by abdullamuthana** [comment]
I have downloaded DB Browser SQLite would you please guide me ?
<img width="524" alt="image" src="https://github.com/opengisch/QField/assets/63540100/a3950640-8885-44a2-8224-134094f518d2">

**Comment by abdullamuthana** [comment]
nvr mind i have figure out 
<img width="340" alt="image" src="https://github.com/opengisch/QField/assets/63540100/c549df44-b446-4d82-81db-c173aead0ac4">

**Comment by abdullamuthana** [comment]
The Issue has been fixed after creating a name for it 
Many Thanks

**Comment by nirvn** [comment]
@abdullamuthana , great, thanks for confirming. Happy field mapping!
