### ISSUE TITLE
No line While Drawing

### ISSUE THREAD

**Issue by abdullamuthana** [opengisch/QField#4700]
### Describe the issue
When I try to add a new line there is nothing to show this issue occurred for me when updated to the last update i tried to download the previous versions and there was no issue

### Expected behavior
Don't Know

### Observed behavior
When I try to add a new line there is nothing to show this issue occurred for me when updated to the last update 

### Screenshots and GIFs
Before Update : You can see  the line with the crosshair
<img width="196" alt="Before Update" src="https://github.com/opengisch/QField/assets/63540100/d307c302-1ca7-4140-b144-e5780b3406f7">
After Update You can see the line not with the crosshair it is at the button left
<img width="212" alt="After Update" src="https://github.com/opengisch/QField/assets/63540100/bf7e2541-8386-40dc-83a6-1ca6956069c9">

### Desktop (please complete the following information)
 - QFieldSync Version [Last Version]

### Mobile (please complete the following information)
 - Device: [e.g. iPhone13 pro max]
 - OS: [e.g. Android 11]
 - QField version: 3.0.4 - Amazonia 

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly:Yes
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

Sample of the project file
[test.zip](https://github.com/opengisch/QField/files/13195793/test.zip)

this issue happens for lines only

**Comment by nirvn** [comment]
@abdullamuthana , any chance you could do a screencast of what you're seeing?

I've tried digitizing lines using your project and for me the line does stick to / follow the crosshair:

https://github.com/opengisch/QField/assets/1728657/907829d3-a061-403f-bd10-62695d4f50a4

**Comment by nirvn** [comment]
@abdullamuthana , oh and could you try the measuring tool to see if the line suffers from the safe offsetting? Thanks

**Comment by abdullamuthana** [comment]
Same issue also with measure tool

**Comment by nirvn** [comment]
@abdullamuthana are you on an iphone?

**Comment by abdullamuthana** [comment]
Yes and also tried it on the android same issue

**Comment by nirvn** [comment]
@abdullamuthana , got it. Issue appears with rotated canvas. Thanks for helping confirm the problem.

**Comment by abdullamuthana** [comment]
You are welcome, anything can do it by my side ?

**Comment by nirvn** [comment]
@abdullamuthana , can you try the APK in this pull request (https://github.com/opengisch/QField/pull/4701), I believe the issue is resolved there.

**Comment by abdullamuthana** [comment]
> @abdullamuthana , can you try the APK in this pull request (#4701), I believe the issue is resolved there.

I'll Test and bring back with feedback
