### ISSUE TITLE
Calendar popup doesn't show current month and year

### ISSUE THREAD

**Issue by L10ns** [opengisch/QField#4720]
When you open a calendar popup in mobile phone, it shows the January of 2020 instead the current month and year.
There was not this problem with older version of QField.

 - Device: Samsung
 - OS: Android
 - QField version: 3.0.5 Amazonia

**Comment by nirvn** [comment]
@L10ns , thanks for reporting this regression, it has been fixed in this PR (https://github.com/opengisch/QField/pull/4721). You can test the APK in there or wait a few days for a new public version to emerge :)
