### ISSUE TITLE
WMS layer not loaded in QField but works fine in QGIS

### ISSUE THREAD

**Issue by Dutch5972** [opengisch/QField#4723]
Hi,
Since a year I am using a WMS backround map in QField. For using this map I have a subscribtion with its developer. Till recently it worked fine on both QGIS and QField (Samsung Android). But suddenly it stopped working in QField although it is still working in QGIS. The provider mentioned no other customers reported any problems with using this background map.
I reïnstalled the latest QGIS version (Lima), the latest Qfield sync plug-in and the newest version of QField. The 'Save path' setting in project properties is set in 'relative'.
In QField in the layerinfo it says that the layer is invalid, which might be due to a network problem, an unknown file or wrong configuration of the project. But the project settings have not changed and on QGIS the WMS layer is working properly. Other standard WMS background maps and aerial photos are working fine though.

Does anyone know how to tackle this issue? Thanks in advance!

**Comment by nirvn** [comment]
@Dutch5972 , can you try the APKs in there: https://github.com/opengisch/QField/pull/4719 ?

**Comment by Dutch5972** [comment]
Hi,

 

Thank you for your message and comments!

It seems there is a bug in the newest release of QField that was installed on my android phone  and tablet due to automatic updates (QField 3.0.5. Amazonia). After uninstalling that version and after reinstalling an older version (QField 2.8.7 Insight Indri), the WMS background map is working properly again. It seems there is some kind of bug in the transfer of the authentication when copying the QField project to the phone/tablet as it works properly on the PC. WMS layers that do not require authentication (like open source aerial photos and OpenStreetMap etc.) don’t show this issue and can be opened in QField on the device.

 

I informed Opengisch on this and they will address this bug when developing new releases of QField. I hope it will be fixed soon in order to keep on using the newest releases of QField. In the meantime its better to temporarily work with an slightly older release (make sure to switch off the automatic updates!).

 

With kind regards,

 

 

Aernout Theunissen

 

 

 

Van: Peteris Martinsons ***@***.***> 
Verzonden: donderdag 2 november 2023 16:47
Aan: opengisch/QField ***@***.***>
CC: Dutch5972 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [opengisch/QField] WMS layer not loaded in QField but works fine in QGIS (Issue #4723)

 

The same problem for me. Several WMS layers worked until around two weeks ago; maybe a week earlier.
Information that can be used for testing:

1.	Create a QCloud project with OpenStreetMap as a background layer. This works in QGIS and QField.
2.	In QGIS, download and modify the project, adding several WMS layers from the address http://lvmgeoserver.lvm.lv/geoserver/ows. This is a public WMS server that provides geospatial data about Latvia - ortophoto layers, cadastral data, etc.
3.	Add also OpenStreetMap to project as a WMS layer from the same server.
4.	Save, upload to QCloud and download to QField.
5.	See that WMS layers do not work, OpenStreetMap from lvmgeoserver.lvm.lv does not work. See attached image with QField screenshot with message logs. In QGIS, all layers show up on map without errors.

Tested with the build mentioned in prevoius comment under the link #4719 <https://github.com/opengisch/QField/pull/4719> . Does not work also; the only difference is that in one of the projects cadastral layers showed up. For others, the same problem.

Hypothesis, why this effect could be: maybe this is somehow connected with the layer parameters "Ignore axis orientation" and "Invert axis orientation". When changed in QGIS, these parameters do not change in .qgs file. In July, I had to tweak these params for the layers to show up in QField.

 <https://user-images.githubusercontent.com/10693914/280046535-1323c7af-9d6d-417e-9f5a-1d3da0817ee4.png>

**Comment by nirvn** [comment]
@pmartinsons , use https:// instead of http:// , that'll avoid a redirect, which I think might be causing the problem.

**Comment by nirvn** [comment]
Reason why that'd fail under QField 3 due to an upstream change in Qt 6 with regards to handling of redirects. When QGIS upgrades to Qt 6, the same situation will arise. Better update your WMS URL :)

**Comment by pmartinsons** [comment]
@nirvn Yes, changing http to https helped. Thanks!
