### ISSUE TITLE
@position_averaged_count - Value counting error (+1)

### ISSUE THREAD

**Issue by bettellam** [opengisch/QField#4738]
`@position_averaged_count` - Value counting error (+1)
Hi Development Team, request for simple update
**Qfield Positioning Setting**:
Minimun number of positions collected = **5**

![Screenshot 2023-11-08 100009_P](https://github.com/opengisch/QField/assets/23143342/850f89b9-5a96-43f5-9930-b7fbeb2e7209)

Value obtained from `@position_averaged_count` in my GNSS data table:
@position_averaged_count = **4**

![Screenshot 2023-11-08 101023_P](https://github.com/opengisch/QField/assets/23143342/57e9bfb5-718a-476d-b21d-492e30da3341)

Ciao

**Comment by nirvn** [comment]
@bettellam , this has been fixed and will be part of QField 3.2.1. Thanks for the report, and happy field mapping!
