### ISSUE TITLE
Replicable crash on QField RC3

### ISSUE THREAD

**Issue by gioman** [opengisch/QField#474]
I found a way to crash consistently QField RC3. Can provide sample project if necessary.

### Reproduction Steps:

1. open a project with two layers from the same GPKG datasource (possibly affected other datasources, not tested), one point, one polygon
2. (optional step) enable editing for polygons, add a feature, save --> OK
3. enable editing for the point layer
4. opsss... I wanted to edit the polygons --> enable editing for polygons
5. add a polygon, save --> crash

**Comment by geomondego** [comment]
I confirm this behavior with shapefiles

**Comment by 3nids** [comment]
is your project prepared with QFieldSync or it is used as is from QGIS?

**Comment by gioman** [comment]
> is your project prepared with QFieldSync or it is used as is from QGIS?

@3nids QFieldSync not used.

**Comment by geomondego** [comment]
@3nids i have used QFieldSync

**Comment by 3nids** [comment]
@gioman would be nice to test your project as I am unable to reproduce.

**Comment by saemiw** [comment]
> @gioman would be nice to test your project as I am unable to reproduce.

@3nids: Meaning with my project you can't reproduce the crash? Damn I was able to do so with two people on two separate devices... I can offer videos, device type specification or teamviewer session to help understand the problem better?

**Comment by gioman** [comment]
@3nids screencast attached. Will send the project and data privately.

[20190220_103213.zip](https://github.com/opengisch/QField/files/2884201/20190220_103213.zip)

**Comment by signedav** [comment]
I can reproduce it with the tablet and on computer with Giovannis project. There is after some layer switching a "Segmentation Fault" crash on random (seems so) places but always after this `clear()` of the  `QStandardItemModel` we call here: https://github.com/opengisch/QField/blob/master/src/core/attributeformmodelbase.cpp#L116

The scenario is like:
```
<no layer selected - maps in the end>
- click on layer two (Geral)
- click on layer one (Outros_registos)
- click on layer two
- click on layer one -> crash
```
or
```
<no layer selected - maps in the end>
- click on layer one (Outros_registos)
- click on layer two (Geral)
- click on layer one
- click on layer two
- click on layer one -> crash
```
seems to crash after second clear() of two...
or 
```
<no layer selected - maps in the end>
- click on layer five (Conc_Frec_CI)
- click on layer two (Outros_registos)
- click on layer five
- click on layer two
- click on layer five -> crash
```
But I can endlessly switch between fife and one!
But when I then change to layer four (Coop...) it crashes after the second clear of five...
*So it's the second clear of something.*

@3nids Any idea? I can make further investigations, but probably you have an input?
@gioman Did you have this issue on older versions of QField as well or only with RC1?

**Comment by gioman** [comment]
>  @gioman Did you have this issue on older versions of QField as well or only with RC1?

@signedav this report is about having observed this replicable crash on RC3. Anyway if my memory does not tricks me I would say that this also occurred on previous releases (but it wasn't until RC3 that I understand exactly how to replicate).
