### ISSUE TITLE
Search features by toolbar  - zoom at layer?

### ISSUE THREAD

**Issue by robibrazze** [opengisch/QField#4748]
Hi everyone,
i use qgis desktop v. 3.28.4 and the last versione of qfield.
I have imported a layer tipe linestring and when a search features by value "name" and click on the name 
found the map is center by the geometry but the level on the zoom is not so good, (the layer founded is not at the max extension on the screen) and geometry flashes red only for a few seconds.
I espected that the zoom at layer work as when i click "zoom by element", (see image below)
Am I doing some settings wrong? 
thank a lot
![image](https://github.com/opengisch/QField/assets/28442671/2baddf19-9404-48b0-9cda-f09fd70c804f)

**Comment by nirvn** [comment]
@robibrazze , this PR should fix the extent issue you are raising here: https://github.com/opengisch/QField/pull/4749

**Comment by robibrazze** [comment]
@nirvn , i read the PR [#4749 ](https://github.com/opengisch/QField/pull/4749l) but I know the functions described and these do not resolve the zoom level when selecting a feature after searching for it.
Maybe I'm missing something but if I search, (either whit option all layer or active layer) and then click on the result, the zoom I get on the map is not at the maximum extent of the geometry. 
I notice this event with linestring geometries and not as point geometries where the zoom level allows the geometry to be well defined.
thanks a lot
