### ISSUE TITLE
Unable to pan if the project contains geometryless tables 

### ISSUE THREAD

**Issue by jhonalex06** [opengisch/QField#475]
### Reproduction Steps:

1. Create a project with geometryless table 
2. Open the project in QField 
3. Try to pan the map

### Expected behavior:

Map panned 

### Observed behavior:

Map does not move 

### Screenshots and GIFs

![Demo video](http://downloads.tuxfamily.org/tuxgis/tmp/ai/IMG_5146.MOV)

In the second 10 of the video, we load project with geometryless tables. you can download the project from: [Issue.zip](https://github.com/opengisch/QField/files/2852564/Issue.zip)
 
**QField version:**  1.0.0-rc3

**Comment by 3nids** [comment]
There is something wrong in your project. Opening it in QGIS leads to the same issue (unable to pan).
I used "zoom to layer" on the raster layer, saved the project and reopen it in QField and it works.

Do you want us to look at the issue upstream (in QGIS core)?

**Comment by jhonalex06** [comment]
yes, you have reason, i had this issue but when i configure the project of the right way, this issue disappear 

Thanks for your attention. @3nids
