### ISSUE TITLE
Error pushing changes - qfieldcloud server down?

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#4752]
### Describe the issue
Pushing changes gives a error.
Syncing not working neither.
Server down but QField cloud seems alive and kicking? https://status.qfield.org/

### Mobile (please complete the following information)
 - Device: Galaxy A52
 - OS: Android 11
 - QField version: 3.0.6 d36352

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [No - pushing works in another (community) project]
* I tried pushing a change from the same project from another device and that didn't give a error (both devices are on the same network/wifi)?!
* A colleague of mine was able to push changes and sync the project

[If the problem happened with QFieldCloud, please add your username and project name.]
- Username Boswachter_Marc
- Project Walden v6a

![Screenshot_20231111_225702](https://github.com/opengisch/QField/assets/57868975/491c8d14-c96c-40e5-a321-ac3656f1bbd7)
![Screenshot_20231111_225739_Ecosia](https://github.com/opengisch/QField/assets/57868975/e6d1d134-8614-4e6c-8aee-211e5ec6a4df)
![Screenshot_20231111_230444](https://github.com/opengisch/QField/assets/57868975/b173b298-3f8c-43d6-9ffb-66ceff36f052)

**Comment by BoswachterMarc** [comment]
The problem persisted on one of my devices while other collaborators were able to push and sync the same project. I undid the local changes and then tried to sync. To my surprise this worked. Then I made one change and tried to push it. That also worked... The 16 changes that could not be pushed previously were mainly additions to a non-spatial, related child layer. I will check if I can replicate...

**Comment by suricactus** [comment]
Thanks for narrowing this down! I am also having a look in the logs and will share info later this week.

**Comment by BoswachterMarc** [comment]
I can't reproduce the error. I added non-spatial information in a child layer and pushed them; some one by one, others all together. It worked smoothly...

**Comment by suricactus** [comment]
Seems like a temporary glitch. I will close this for now and feel free to reopen if it happens again.
