### ISSUE TITLE
Snap function does not work with online layer

### ISSUE THREAD

**Issue by Ragnavig** [opengisch/QField#4766]
Hi, I am trying to use QField on my iPad.

When I use an offline project, I can snap new features to other geometries with the snap tool (magnet button).
But when I use the function in an "online" project (postgresql), I cannot use the snap function. The function can be switched on and off, but it does not work, it does not snap to a geometry. 

Have I done something wrong?

**Comment by nirvn** [comment]
@Ragnavig , without a sample project it'll be hard to look into this issue. Can you provide one for us?
