### ISSUE TITLE
Latest QField version crashes regularly when taking pictures

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#4767]
### Describe the issue
QField crashes after taking a couple of pictures (photos) or when using the QR Code scanner

### Reproduction steps
1. create a picture
2. repeat a couple of times
3. :boom: 

### Expected behavior
No crash

### Observed behavior
Crash

### Mobile (please complete the following information)
 - OS: Android
 - QField version: 3.0.6

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
Duplicate of https://github.com/opengisch/QField/issues/4704
Looks like the fix is arriving end of November (or as a workaround, it's possible to download the apk from https://github.com/opengisch/QField/releases/tag/v2.8.7 .

**Comment by gioman** [comment]
> (or as a workaround, it's possible to download the apk from https://github.com/opengisch/QField/releases/tag/v2.8.7

@m-kuhn the workaround is then to downgrade to qfield version from august?

**Comment by m-kuhn** [comment]
Yes, we need to wait for a qt upgrade...

**Comment by gioman** [comment]
thanks!
