### ISSUE TITLE
@cloud_username and @cloud_useremail do not return value

### ISSUE THREAD

**Issue by pmartinsons** [opengisch/QField#4773]
### Describe the issue
There is a QField attribute edit form created in QGIS.
Form has a text field that is intended to be filled with the qcloud user name or alternatively, email.
Expression to fill the default value in the text field is '@cloud_username' (without quotes).
When form is opened for editing in QField, the field is empty, because it returns NULL.
Tested with the latest QField from Google play and with beta version 4719.
I am logged in to QField cloud (Pro account) while using the Qfield and also while developing the project in QGis on Windows machine.
Similar result if the text field default value expression is "cloud_username" (with double qoutes). Then it returns empty string (see the field setup in attachment).

### Reproduction steps
1. In QField on Android, try to open a form with a default value in text field described in previous point.
2. See that the field is not populated with the default value.

### Expected behavior
Both expressions (@cloud_username and @cloud_useremail) should return the intended variables 

### Observed behavior
Both expressions (@cloud_username and @cloud_useremail)  do not return anything.

### Screenshots and GIFs
![image_2023-11-16_212358274](https://github.com/opengisch/QField/assets/10693914/baeb56a4-29e2-457d-9e55-a34a926445a4)

### Desktop (please complete the following information)
Used to develop the project
 - OS: Windows 11
 - QGIS Version 3.30.2
 - QFieldSync Version 4.6.0

### Mobile (please complete the following information)
 - Device: Galaxy XCover 5
 - OS: Android 13
 - QField version: 3.0.6-Amazonia (d36352 v3.0.6) Qt 6.5.3

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes (not tested on older projects)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes/maybe, not tested in other projects

username baltukokaqcloud, project name (https://app.qfield.cloud/a/BaltuKoks/Apsekosana/)

**Comment by m-kuhn** [comment]
Thank you for raising this.

It is a (known) limitation that QGIS doesn't show these variables at configuration time. This is confusing and it would be nice to improve the situation here. We might do so when we have some free time.

On QField side on the other hand, the expression should work nonetheless as soon as you are logged in. If you are experiencing a problem there, could you share an affected project?

**Comment by pmartinsons** [comment]
Yes, I can share. Should I send *.qgs file or do something else?

**Comment by suricactus** [comment]
Can you please share your QField version? If not latest, can you try with the latest 3.1.6?

**Comment by geogeek11** [comment]
May be it was related to the Qfield version, I works well on the last up to date version of Qfield.

**Comment by suricactus** [comment]
@pmartinsons Can you also confirm the variables work in the latest QField version (3.1.6 or newer)?
