### ISSUE TITLE
Problem in About dialog box : paths are not visible

### ISSUE THREAD

**Issue by geostonemarten** [opengisch/QField#479]
need to be reopeen same problem on 1.0.0 rc3 on french version. I don't no if it is affected by translation

version is truncated;

I have this in my about box:

_Version de Qfield : 1.0.0-rc3 - M...
Dossier des paramètres de QField :
Dossier des éléments partagés de QField_

I send a request for transiflex translation because I see some spelling error. It is possible to update documentation in addition because it's 0.10 in website or we are on 1.0 on play store ?

_Originally posted by @geostonemarten in https://github.com/opengisch/QField/issues/272#issuecomment-464738580_

**Comment by signedav** [comment]
Close it because of duplication.
