### ISSUE TITLE
Error pushing changes - qfieldcloud server down? #4752

### ISSUE THREAD

**Issue by BoswachterMarc** [opengisch/QField#4796]
See #4752 

### Reproduction steps
1. Open a spatial layer (polygon?)
2. Open a referenced non spatial child layer
3. Open a text field in a existing child layer
4. Change the text in this field and save
5. Try to push the change
6. I got a error pushing the change(s)

See screen recording (changing text field 'Test2' to 'Test2a')

https://github.com/opengisch/QField/assets/57868975/731b249b-d4bb-45bb-a15e-b6eabfac7235

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - Device: Samsung A52
 - OS: Android 13
 - QField version:  3.0.7 - Amazonia - 35e3ee
 - 
### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: Don't know yet

Boswachter_Marc
walden_v6a

**Comment by nirvn** [comment]
@BoswachterMarc , every time I see screenshots / videos of your project, I can't help but notice how nice the symbology is ;) 

Has the connection returned?

**Comment by BoswachterMarc** [comment]
Thans you @nirvn ;-)
The connection returns when I delete that specific change. I other words, when I add child feature, there is no problem, when I change the content of a (text) field, I got the connection error. It could be handy to have - before pushing - a overview of the local changes one made...

**Comment by nirvn** [comment]
@BoswachterMarc , can you click on the error message area, it should expand and give us a longer error string.

**Comment by BoswachterMarc** [comment]
I was able to reproduce but had to add a child feature AND change the content of a text field of a existing child feature. 
![Screenshot_20231125_102456](https://github.com/opengisch/QField/assets/57868975/0f18b488-66cd-4ecf-a267-654d9d6db61d)
![Screenshot_20231125_102521](https://github.com/opengisch/QField/assets/57868975/26520255-0067-4c79-8415-54a326ea614a)

**Comment by nirvn** [comment]
@BoswachterMarc , is it still an issue on the latest QField 3.2? There's been a fair amount of development both on the QField app as well as the QFieldCloud server side of things.

**Comment by BoswachterMarc** [comment]
@nirvn I am afraid the problem is still there 

https://github.com/opengisch/QField/assets/57868975/6f5334a1-f05c-4de1-a85f-e2cd676c2195

**Comment by BoswachterMarc** [comment]
And this is the log

![Screenshot_20240323_091247](https://github.com/opengisch/QField/assets/57868975/501da091-7729-44f9-aad0-bdd4ec9f3928)

**Comment by BoswachterMarc** [comment]
@nirvn I am afraid the problem is still there


https://github.com/opengisch/QField/assets/57868975/a09b0d23-9fa1-4a9f-a01a-d5588973a9a2

![Screenshot_20240323_114751](https://github.com/opengisch/QField/assets/57868975/da321c05-36b2-49fd-8ea0-dc6430040478)

**Comment by nirvn** [comment]
@BoswachterMarc , what is your cloud user name?

**Comment by suricactus** [comment]
I am on it, fix is coming with the next QField and QFieldCloud versions.

**Comment by nirvn** [comment]
@suricactus , nice! I was literally about to open the admin side of things to look into this some more. :pray:

**Comment by BoswachterMarc** [comment]
Thanks guys, you all do a great job!

**Comment by suricactus** [comment]
@BoswachterMarc can you please try this PR if it fixed the issue for you? https://github.com/opengisch/QField/pull/5139

**Comment by BoswachterMarc** [comment]
Just tried it (installed the PR and downloaded the same cloud project)
1/ when I add a new feature, I can not see it on the map. There is no symbol so I can not select it and change the child value.
2/ when I add a feature not related to the child form, the symbol is drawn.
3/ when I change a existing feature the symbol remains and I can push the change without error.
See the screen recordings

https://github.com/opengisch/QField/assets/57868975/d9cb2e5a-0137-4078-99ac-a3d91cbc558f


https://github.com/opengisch/QField/assets/57868975/8f7076c8-de1c-496f-8093-75a390e9d17a


https://github.com/opengisch/QField/assets/57868975/65e15811-88f3-4dd1-96f7-6bbba1af4e16

**Comment by BoswachterMarc** [comment]
@suricactus I did exactly the same as in https://github.com/opengisch/QField/issues/4796#issuecomment-2016448088

I used the same cloud project (didn't change anything) so - for now - I disagree.

**Comment by BoswachterMarc** [comment]
@suricactus here with the exact same attribute values selected in the 3.2.0 release... No problem with the symbol.

https://github.com/opengisch/QField/assets/57868975/1085c10e-3303-45a3-a0b5-aadb237cc78f

**Comment by suricactus** [comment]
> @suricactus here with the exact same attribute values selected in the 3.2.0 release... No problem with the symbol.

Interesting, I am still quite sure this is another regression prior to the PR that you are testing, note there were a lot more other changes betwee 3.2.0 and the version your tested.

Just a very quick way to confirm the feature is actually created, but not visualized in two independent ways:

1) when you create the "invisible" feature, the QFieldCloud counter icon should increment by 1 (if you don't create the child feature).
2) create the feature in a remote/zoomed area without any other features from this layer visible. After successfull save, go to layer popup and select "Show visible features list". The the list should show your invisible feature.

![image](https://github.com/opengisch/QField/assets/2820439/0fc2743d-7776-4ef9-bdad-68f169a58888)

---

@nirvn super nice we got this regression in early stage, now we need to find exactly where it comes from.

**Comment by nirvn** [comment]
@BoswachterMarc , the "invisible symbology" issue is fixed by this PR: https://github.com/opengisch/QField/pull/5141 -- you can try an APK in the PR to confirm.

The regression did occur in 3.2.0 :) maybe you did not spot it as you might have had 'fast editing' mode turned on. In any case, thanks for making us aware of that one.

**Comment by BoswachterMarc** [comment]
Everything works! Pushing the changes in the child layer and symbology.

**Comment by suricactus** [comment]
@BoswachterMarc expect this in 3.2.2 in the next weeks, not in the immediate 3.2.1 released today.

**Comment by BoswachterMarc** [comment]
@suricactus I noticed ;-) In the meantime, I will use the PR you shared with me. Thanks for all the effort.

**Comment by nirvn** [comment]
@BoswachterMarc , if you don't mind me asking, what are the uses you have for QField. You've clearly got a complex project here, makes me curious.

**Comment by BoswachterMarc** [comment]
> @BoswachterMarc , if you don't mind me asking, what are the uses you have for QField. You've clearly got a complex project here, makes me curious.

We manage forests and nature reserves in a multifunctional and sustainable/climate-smart way. The wood we produce is FSC certified. But apart from that, we love dead wood, monumental and old trees, plantations and natural regeneration in various forms. And of course, we cherish the plants and animals that live there. That's it in a nutshell ;-)

**Comment by nirvn** [comment]
@BoswachterMarc , thanks for sharing that paragraph, it's always quite inspirational to hear the many uses people have for QField out there.

Also, QField 3.2.2 was released within 24 hours of 3.2.1, with the cloud fix you were in need of, you can therefore hop back onto the official release builds. Happy field mapping!

**Comment by FjInvestigador** [comment]
Hello, i have this problem, i use an iphone xs, the version of QField is 3.3.6 - Darién (78a4fe v3.3.6) Qt 6.6.3
![image](https://github.com/opengisch/QField/assets/175027369/70105674-6961-4c5e-b0fd-291ad3802aed)

**Comment by suricactus** [comment]
Please consider opening a support ticket on the ticketing platform at https://support.qfield.cloud/portal/en/home .
