### ISSUE TITLE
Qfield pictures going into Files folder

### ISSUE THREAD

**Issue by connorjfns** [opengisch/QField#4800]
### Describe the issue
Qfield pictures now going into a folder called "Files". It's also losing the .jpg or .png extension.

### Reproduction steps
1. Take a picture on Qfield
2. Connect mobile device to a laptop/PC and use File explorer to go to Tablet folder location. For us, it's This PC\TB85Plus\Internal shared storage\Android\data\ch.opengis.qfield\files\Imported Projects\
3. Open project, then go to Files folder.

### Expected behavior
The pictures used to go into the folder "DCIM" and they had the .jpg extension

### Observed behavior
Not sure what to put as already mentioned

### Screenshots and GIFs
![Picture1](https://github.com/opengisch/QField/assets/151828546/f29347a4-3dea-4644-812e-20eeafa877e6)
![image (1)](https://github.com/opengisch/QField/assets/151828546/1f85d709-7874-4285-ab00-3810d03712a2)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10/11

### Mobile (please complete the following information)
 - Device: Unitech TB85
 - OS: Android 8
 - QField version: 3.0.7
### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

Can I make a request that these pictures go back into the DCIM folder and retain the .jpg extension please?

**Comment by nirvn** [comment]
@connorjfns , that sounds like a project setting issue to me, can you share the expression you've set for the photo attachment's path in the vector layer properties dialog, i.e. this:

![image](https://github.com/opengisch/QField/assets/1728657/6a12e530-3b5f-4937-9e06-2f9ba7cdb316)

**Comment by connorjfns** [comment]
@nirvn So, by default I use the expression below (the part after DCIM varies based on layer)
'DCIM/chambers-and-notes_' || format_date(now(),'yyyyMMddhhmmsszzz') || '_{filename}'  || '.jpg'
 
 
But sometimes the QGIS changes the formula above to the default one (PSB). This happenes when the project is opened with the older QGIS version and sometimes it happens like randomly for reason I can`t detect. 
'files/objects_' || format_date(now(),'yyyyMMddhhmmsszzz') || '_{filename}'

My observation though is that this seems to change with the qfield version without any changes on our end to the project settings. For example, if we did a project in Qfield version 2.6.2, the pictures would go into DCIM. If we worked on the same project from any version from 2.8.0 onwards, the pictures would go into Files.

**Comment by connorjfns** [comment]
Hi, we are using QGIS version 3.22.11
On our Tablets, we are using latest version of Qfield 3.0.7

I have uploaded 2 files. One is when we worked on it using qfield version 2.6.2. the other is the same project, but on qfield version 3.0.7

In the correct work folder, the pictures are stored in the folder DCIM with the .jpg extension. In the faulty folder, the pictures are stored in the Files folder with no extension.

[Correct-work.zip](https://github.com/opengisch/QField/files/13544948/Correct-work.zip)
[Faulty-work.zip](https://github.com/opengisch/QField/files/13544949/Faulty-work.zip)

**Comment by gioman** [comment]
Seen also here on several different devices.

**Comment by nirvn** [comment]
@connorjfns , looking at the faulty-work.zip project, I can see one configuration issue. You should set your attachment viewer type to image, that provides the hint for QField to through images in DCIM by default:

![image](https://github.com/opengisch/QField/assets/1728657/1d39aa74-d2f7-4d3c-9f59-f002ff906799)

In your case, you'll also need to tweaked the preexisting attachment expressions here:

![image](https://github.com/opengisch/QField/assets/1728657/286f4ac8-aec5-4e5e-937b-0f58556ed2e7)

**Comment by nirvn** [comment]
@connorjfns , is this still an issue?
