### ISSUE TITLE
vcpgk build error for Android: qtbase[egl] is only supported on '!uwp',

### ISSUE THREAD

**Issue by maciek252** [opengisch/QField#4817]
I'm on freshly installed linux 22.04.3 LTS (jammy). I've installed the Android Studio with the NDK, and the apt and aqtinstall dependencies listed in the dev docs. However, the build fails with:

-- Running vcpkg install
qtbase[egl] is only supported on '!uwp', which does not match arm64-android. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build qtbase anyway, rerun vcpkg with `--allow-unsupported`.
-- Running vcpkg install - failed

1. Clone the QField repo and install the dependencies
2. set up the NDK path:
export ANDROID_NDK_HOME=/home/maciek/Android/Sdk/ndk/26.1.10909125/
3. execute 
cmake -S QField       -B buildQF       -D VCPKG_TARGET_TRIPLET=arm64-android

I've tried both master and v3.0.7 QField branches.

**Comment by m-kuhn** [comment]
You will need to provide `SYSTEM_QT=ON` as well and probably even other variables (see https://github.com/opengisch/QField/blob/v3.0.7/.github/workflows/android.yml#L118-L144 for reference, not all of them are required)
The "build locally" workflow has not been tested in depth, the [docs/scripts for building with a docker image](https://github.com/opengisch/QField/blob/master/doc/dev.md#using-a-docker-image) are in much better shape. If you go down the road of building locally a pull request for the [building locally section of the documentation](https://github.com/opengisch/QField/blob/master/doc/dev.md#building-locally) would be much appreciated.

**Comment by maciek252** [comment]
Thank you very much for your answer. After adding -D SYSTEM_QT=ON I've made some progress (12/95). The build has crashed at:

-- Configuring arm64-android-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/bash -c "V=1 ././configure --host=aarch64-linux-android \"--without-icu\" \"--with-lz4\" \"--without-nls\" \"--with-openssl\" \"--without-python\" \"--without-readline\" \"--without-xml\" \"--without-xslt\" \"--with-zlib\" \"--without-zstd\" \"ac_cv_header_langinfo_h=no\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/home/maciek/dev/buildQF/vcpkg_installed/arm64-android\" \"--bindir=\\${prefix}/tools/libpq/bin\" \"--sbindir=\\${prefix}/tools/libpq/sbin\" \"--libdir=\\${prefix}/lib\" \"--mandir=\\${prefix}/share/libpq\" \"--docdir=\\${prefix}/share/libpq\" \"--datarootdir=\\${prefix}/share/libpq\""
    Working Directory: /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/libpq/arm64-android-rel
    Error code: 77
    See logs for more information:
      /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/libpq/config-arm64-android-rel-config.log
      /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/libpq/config-arm64-android-rel-out.log
      /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/libpq/config-arm64-android-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:838 (vcpkg_execute_required_process)
  ports/libpq/portfile.cmake:115 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)


error: building libpq:arm64-android failed with: BUILD_FAILED
Elapsed time to handle libpq:arm64-android: 22 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libpq
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libpq]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fmaciek%2Fdev%2FbuildQF%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

I need to familiarize myself with the process, which variables can be missing here?

**Comment by m-kuhn** [comment]
Information can be found in these files:

> See logs for more information:
> /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/libpq/config-arm64-android-rel-config.log
> /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/libpq/config-arm64-android-rel-out.log
> /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/libpq/config-arm64-android-rel-err.log

**Comment by maciek252** [comment]
I've downloaded and set up the NDK 23, and the progress was much better. I was hoping it would finally build fine :) However, there was an error at 75/100:

Installing 75/100 qca-qt6:arm64-android...
Building qca-qt6:arm64-android...
-- [OVERLAY] Loading triplet configuration from: /home/maciek/dev/QField/vcpkg/triplets/arm64-android.cmake
-- Installing port from location: /home/maciek/dev/QField/vcpkg/overlay/qca-qt6
-- Downloading https://github.com/KDE/qca/archive/v2.3.6.tar.gz -> KDE-qca-v2.3.6.tar.gz...
-- Extracting source /home/maciek/dev/buildQF/_deps/vcpkg-src/downloads/KDE-qca-v2.3.6.tar.gz
-- Applying patch 0001-fix-path-for-vcpkg.patch
-- Applying patch 0002-fix-build-error.patch
-- Applying patch 0003-Define-NOMINMAX-for-botan-plugin-with-MSVC.patch
-- Applying patch ios.patch
-- Applying patch connect_fix.patch
-- Using source at /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/src/v2.3.6-1540531191.clean
-- Importing certstore
-- Importing certstore done
-- Configuring arm64-android
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/maciek/dev/buildQF/_deps/vcpkg-src/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/arm64-android-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/config-arm64-android-rel-CMakeCache.txt.log
      /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/config-arm64-android-out.log

Call Stack (most recent call first):
  /home/maciek/dev/buildQF/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  /home/maciek/dev/QField/vcpkg/overlay/qca-qt6/portfile.cmake:58 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


error: building qca-qt6:arm64-android failed with: BUILD_FAILED
Elapsed time to handle qca-qt6:arm64-android: 2.3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qca-qt6
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qca-qt6]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fmaciek%2Fdev%2FbuildQF%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed
CMake Error at /home/maciek/dev/buildQF/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /home/maciek/dev/buildQF/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:32 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

/home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/config-arm64-android-out.log:

(...)

Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:19 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Found Doxygen: /bin/doxygen (found version "1.9.1") found components: doxygen dot 
-- Building Qt 6 version
CMake Error at /home/maciek/dev/buildQF/vcpkg_installed/arm64-android/share/qt6/vcpkg-cmake-wrapper.cmake:132 (_find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /home/maciek/dev/buildQF/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:813 (include)
  CMakeLists.txt:54 (find_package)


-- Configuring incomplete, errors occurred!
ninja: build stopped: subcommand failed.

I'm learning about vcpkg. How to diagnose those errors? I've checked other log files but they are repeating the stuff I've posted.

**Comment by m-kuhn** [comment]
Good to hear there is progress
It's likely something from these three lines: 

https://github.com/opengisch/QField/blob/ade2fc6/.github/workflows/android.yml#L131-L133

**Comment by maciek252** [comment]
So does it mean that Qt 6 has to be provided and is not downloaded by the toolchain? Which Qt version should be used?

**Comment by maciek252** [comment]
So I've downloaded Qt 6.5.3, set the dir path:

export Qt6_DIR=/home/maciek/Qt/6.5.3/

and run the build with the command:

cmake -S QField -B buildQF -D VCPKG_TARGET_TRIPLET=arm64-android -D SYSTEM_QT=ON -D Qt6_DIR=/home/maciek/Qt/6.6.1 -D CMAKE_PREFIX_PATH=${Qt6_DIR} -D QT_HOST_PATH=/home/runner/work/QField/Qt/6.6.1/gcc_64                 -D QT_HOST_PATH_CMAKE_DIR:PATH=/home/maciek/work/QField/Qt/6.6.1/gcc_64 

And I'm getting:

Installing 1/29 qca-qt6:arm64-android...
Building qca-qt6:arm64-android...
-- [OVERLAY] Loading triplet configuration from: /home/maciek/dev/QField/vcpkg/triplets/arm64-android.cmake
-- Installing port from location: /home/maciek/dev/QField/vcpkg/overlay/qca-qt6
-- Using cached KDE-qca-v2.3.6.tar.gz.
-- Cleaning sources at /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/src/v2.3.6-1540531191.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/maciek/dev/buildQF/_deps/vcpkg-src/downloads/KDE-qca-v2.3.6.tar.gz
-- Applying patch 0001-fix-path-for-vcpkg.patch
-- Applying patch 0002-fix-build-error.patch
-- Applying patch 0003-Define-NOMINMAX-for-botan-plugin-with-MSVC.patch
-- Applying patch ios.patch
-- Applying patch connect_fix.patch
-- Using source at /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/src/v2.3.6-1540531191.clean
-- Importing certstore
-- Importing certstore done
-- Configuring arm64-android
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/maciek/dev/buildQF/_deps/vcpkg-src/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/arm64-android-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/config-arm64-android-rel-CMakeCache.txt.log
      /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/config-arm64-android-out.log

Call Stack (most recent call first):
  /home/maciek/dev/buildQF/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  /home/maciek/dev/QField/vcpkg/overlay/qca-qt6/portfile.cmake:58 (vcpkg_cmake_configure)
  scripts/ports.cmake:170 (include)


error: building qca-qt6:arm64-android failed with: BUILD_FAILED
Elapsed time to handle qca-qt6:arm64-android: 787 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qca-qt6
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qca-qt6]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fmaciek%2Fdev%2FbuildQF%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed
CMake Error at /home/maciek/dev/buildQF/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /home/maciek/dev/buildQF/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:32 (project)

--------------------------------------------------------------------------------------
in /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/config-arm64-android-out.log


- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:19 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Found Doxygen: /bin/doxygen (found version "1.9.1") found components: doxygen dot 
-- Building Qt 6 version
CMake Error at /home/maciek/dev/buildQF/vcpkg_installed/arm64-android/share/qt6/vcpkg-cmake-wrapper.cmake:132 (_find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /home/maciek/dev/buildQF/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:813 (include)
  CMakeLists.txt:54 (find_package)


-- Configuring incomplete, errors occurred!
ninja: build stopped: subcommand failed.
--------------------------------------------------------------------------------------

Is something wroing with setting up the Qt6_DIR variable?

**Comment by m-kuhn** [comment]
> ```
> export Qt6_DIR=/home/maciek/Qt/6.5.3/
> 
> and run the build with the command:
> 
> cmake -S QField -B buildQF -D VCPKG_TARGET_TRIPLET=arm64-android -D SYSTEM_QT=ON -D Qt6_DIR=/home/maciek/Qt/6.6.1 -D CMAKE_PREFIX_PATH=${Qt6_DIR} -D QT_HOST_PATH=/home/runner/work/QField/Qt/6.6.1/gcc_64 -D QT_HOST_PATH_CMAKE_DIR:PATH=/home/maciek/work/QField/Qt/6.6.1/gcc_64
> ```

I see a mix between 6.6.1 and 6.5.3 and I see some paths `/home/runner` which are used on the CI system and should be adopted to your system.

**Comment by maciek252** [comment]
I've prepared a script:


export ANDROID_NDK_HOME=/home/maciek/Downloads/android-ndk-r23c/
export Qt6_DIR=/home/maciek/Qt/6.5.3/

cmake -S QField -B buildQF -D VCPKG_TARGET_TRIPLET=arm64-android -D SYSTEM_QT=ON -D Qt6_DIR=/home/maciek/Qt/6.5.3 -D CMAKE_PREFIX_PATH=/home/maciek/Qt/6.5.3/ -D QT_HOST_PATH=/home/maciek/Qt/6.5.3/gcc_64 -D QT_HOST_PATH_CMAKE_DIR:PATH=/home/maciek/Qt/6.5.3/gcc_64

(maybe I could use the env. variables and not repeat the same string)

However, I still get the same error:

Installing 1/26 qca-qt6:arm64-android...
Building qca-qt6:arm64-android...
-- [OVERLAY] Loading triplet configuration from: /home/maciek/dev/QField/vcpkg/triplets/arm64-android.cmake
-- Installing port from location: /home/maciek/dev/QField/vcpkg/overlay/qca-qt6
-- Using cached KDE-qca-v2.3.6.tar.gz.
-- Cleaning sources at /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/src/v2.3.6-1540531191.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/maciek/dev/buildQF/_deps/vcpkg-src/downloads/KDE-qca-v2.3.6.tar.gz
-- Applying patch 0001-fix-path-for-vcpkg.patch
-- Applying patch 0002-fix-build-error.patch
-- Applying patch 0003-Define-NOMINMAX-for-botan-plugin-with-MSVC.patch
-- Applying patch ios.patch
-- Applying patch connect_fix.patch
-- Using source at /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/src/v2.3.6-1540531191.clean
-- Importing certstore
-- Importing certstore done
-- Configuring arm64-android
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/maciek/dev/buildQF/_deps/vcpkg-src/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/arm64-android-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/config-arm64-android-rel-CMakeCache.txt.log
      /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/config-arm64-android-out.log

Call Stack (most recent call first):
  /home/maciek/dev/buildQF/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  /home/maciek/dev/QField/vcpkg/overlay/qca-qt6/portfile.cmake:58 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


error: building qca-qt6:arm64-android failed with: BUILD_FAILED
Elapsed time to handle qca-qt6:arm64-android: 1.3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qca-qt6
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qca-qt6]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fmaciek%2Fdev%2FbuildQF%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed
CMake Error at /home/maciek/dev/buildQF/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /home/maciek/dev/buildQF/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:32 (project)

--------------------------------------------------------------------------------------------------------------------------
 /home/maciek/dev/buildQF/_deps/vcpkg-src/buildtrees/qca-qt6/config-arm64-android-out.log

-- Found Doxygen: /bin/doxygen (found version "1.9.1") found components: doxygen dot 
-- Building Qt 6 version
CMake Error at /home/maciek/dev/buildQF/vcpkg_installed/arm64-android/share/qt6/vcpkg-cmake-wrapper.cmake:132 (_find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /home/maciek/dev/buildQF/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:813 (include)
  CMakeLists.txt:54 (find_package)


-- Configuring incomplete, errors occurred!
ninja: build stopped: subcommand failed.
------------------------------------------------------------
So it says that the Qt6_DIR should be set to the folder containing one of the Qt6Config.cmake files. Is this correct? To which one exactly?

/home/maciek/Qt/6.5.3/android_x86_64/lib/cmake/Qt6/Qt6Config.cmake
/home/maciek/Qt/6.5.3/gcc_64/lib/cmake/Qt6/Qt6Config.cmake
/home/maciek/Qt/6.5.3/wasm_singlethread/lib/cmake/Qt6/Qt6Config.cmake
/home/maciek/Qt/6.5.3/android_armv7/lib/cmake/Qt6/Qt6Config.cmake
/home/maciek/Qt/6.5.3/android_arm64_v8a/lib/cmake/Qt6/Qt6Config.cmake
/home/maciek/Qt/6.5.3/android_x86/lib/cmake/Qt6/Qt6Config.cmake
/home/maciek/Qt/6.5.3/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake

How is Qt6_Dir set in the docker setup? (it is not set in the yaml file you've pointed at)

**Comment by m-kuhn** [comment]
> How is Qt6_Dir set in the docker setup? (it is not set in the yaml file you've pointed at)

In the github workflow it is set by the [install-qt-action](https://github.com/jurplel/install-qt-action)

You can see it e.g. here: https://github.com/opengisch/QField/actions/runs/7061368009/job/19222851502#step:11:63

![Screenshot 2023-12-06 at 06 47 55](https://github.com/opengisch/QField/assets/588407/f7f67751-9759-48b0-b52a-4cb3a0df8d57)

**Comment by m-kuhn** [comment]
It looks like you have been able to compile all dependencies and it fails at the final step to configure the QField cmake project.
I don't think I ever had to specify anything special for Qt6Gui, I assume it is either a leftover from earlier tries (i.e. it might be solved by deleting the build dir and trying again) or by playing around with the Qt6 dir things. Sorry it's been a while since I set this up last time, I only ever test on linux and use the docker script `./scripts/build.sh` to build for linux.

You could also try this:

https://github.com/opengisch/QField/blob/cb6f9e5982a6607e948aa3bc44ac05b0dbe210cc/scripts/build-vcpkg.sh#L22-L24

I don't think this is about missing ubuntu packages (it's trying to compile for Android, so it will need the android opengl libs which come either from the ndk or from Qt itself).

**Comment by maciek252** [comment]
I have switched on the debugging and I've got:

  Qt6Gui could not be found because dependency GLESv2 could not be found.
  
  What does it mean? Is this dependency to be provided by the Qt? Vcpkg? NDK? I need to familiarize myself with the build system as it is very complex. Also, what's the point of this GLES? In the file 
  
  there is a comment:
  
    # GLESv3 needed by barcode reader's use of OpenGL functions

(but are there versions v2 and v3 in use? Maybe it is possible to disable the barcode reader?)

Many thanks for your help, I don't want to bother you but I hope that this discussion will be interesting for people interested in compiling the stuff. Also, maybe building locally is not so important if the docker build works fine? What's the advantage? As I can see, the docker image is not recreated every time:

docker image ls
qfield_and_dev   latest    dde924cd97ad   5 days ago     6.02GB


But probably local build will be faster and also incremental, will it?

**Comment by m-kuhn** [comment]
> What does it mean? Is this dependency to be provided by the Qt? Vcpkg? NDK?

I really think ndk. Maybe Qt.


> Also, what's the point of this GLES? In the file src/core/CMakeLists.txt

That's a red herring. For what I can see the complaint here is from QtGui, not QField directly. Disabling barcode will not help.



> Many thanks for your help, I don't want to bother you but I hope that this discussion will be interesting for people interested in compiling the stuff.

Absolutely, a working local build will have advantages. Mostly debugging with an IDE will be much better possible.



> But probably local build will be faster and also incremental, will it?

I don't expect big advantages here, everything is cached in a mounted volume.

Your findings and insights are appreciated, our current documentation is really weak with respect to this!

**Comment by m-kuhn** [comment]
We've just had similar issues, where system packages were picked up instead of ndk ones and ended up uninstalling these to solve the issue: https://github.com/opengisch/QField/pull/4835/files#diff-b46b6cdc887427355980140454172d7b5ff3dd1f68523667bdd4947358d927d8R124

**Comment by m-kuhn** [comment]
Is this still a problem @maciek252 ?

**Comment by maciek252** [comment]
I realized that I need to know more about the details of cmake and vcpkg, and I'm going through the course about cmake on udemy, which covers also vcpkg. I'll go back into this when I'll have more understanding of the internal working.
