### ISSUE TITLE
Qfield 3.xx (windows desktop) don't show feautures label in correct fonts as defined in QGis project

### ISSUE THREAD

**Issue by Sekou225** [opengisch/QField#4827]
QField 3.xxx shows feature label in a different font than the one difined in the project throught QGIS.

### Reproduction steps
1. Create a project in QGIS
2. Add layer vector with features (entity) and attributs inside
3. Add (show) feature label with Arial font (or other), size and other settings of your will 
( in my case it is : font = MS Shell Dlg 2 / style = Bold / size = 9 / buffer = 0.5 millimeters....)
4. Save your project and uplod it to QfieldCloud / or create a package for Qfield
5. Open your project with Qfield

### Expected behavior
The labels shoud appears as the same as set in your Qgis project.

### Observed behavior
Labels appears in different font with different parameters.

### Screenshots and GIFs
As it set and appears  in Qgis
![image](https://github.com/opengisch/QField/assets/91322749/5c8b806e-7a9d-4ea1-97f6-0f91a6dcd513)

As it appears in Qfield 2.8.3
![image](https://github.com/opengisch/QField/assets/91322749/a37c5e35-a86d-40c6-968b-c92fde18edd7)

As it appears in Qfield 3.0.7
![image](https://github.com/opengisch/QField/assets/91322749/f4a13d18-9bc8-461e-b45d-ed5eb682fe92)

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.32
 - QFieldSync Version 4.6.1

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: YES
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

rtgeologist / Drilling_tracking_new_project

**Comment by nirvn** [comment]
@Sekou225 , nice map!

That's likely a Qt5 vs Qt6 handling inconsistency. Am I right to think that the font family is correct but that the font weight (one's bold, another is extra thin) is the issue?

Could you take a screenshot of your label format UI in QGIS?

**Comment by Sekou225** [comment]
![image](https://github.com/opengisch/QField/assets/91322749/45c01e4c-6eb8-45cd-aa8f-71709ab60b58)

**Comment by nirvn** [comment]
@Sekou225 , sorry for being imprecise, I meant this section:

![image](https://github.com/opengisch/QField/assets/1728657/47df80d9-02e6-4d91-80da-0d02ccdd461c)

**Comment by Sekou225** [comment]
Its already shared on the first printscreen of issue's description

**Comment by Sekou225** [comment]
@nirvn Yes i have try "TW Cent condensed" font by it still changing it to another i cant identify exactely

**Comment by nirvn** [comment]
@Sekou225 , is there any chance you could send me a test project?

**Comment by Sekou225** [comment]
[for_github.zip](https://github.com/opengisch/QField/files/13558289/for_github.zip)
Here is it

**Comment by nirvn** [comment]
@Sekou225 , what is '72 Black' ? I.e., this is what I get when I open your project in QGIS:

![image](https://github.com/opengisch/QField/assets/1728657/992b511d-0e40-4384-b828-0afe6fdd7c99)

**Comment by Sekou225** [comment]
@nirvn It's a font. Seems it's not a default QGis font. The problem could come from there.

**Comment by nirvn** [comment]
@Sekou225 , right so looking into this, I think the problem has to do with an old version of QGIS. When I look at your project (saved with QGIS 3.30), I see the following font information in the .qgs file:

`<text-style namedStyle="Regular" ... fontFamily="72 Black">`

That doesn't load in QGIS 3.34 on my machine either, and is wrong as the font name is 72, not 72 black, the latter is the style. However, after installing the font and **saving with QGIS 3.34**, I see the following definition in the .qgs project file: 

`<text-style ... fontFamily="72" ... namedStyle="Black" ...>`

Which subsequently loads fine. 

So, my advise to you is to update to QGIS 3.34.1, re-configure the font in your QGIS project, save that, and use it in QField, I suspect it'll fix your issue.
