### ISSUE TITLE
The cancel buton when editing feauture attributs (windows QFIELD 3.0.7)

### ISSUE THREAD

**Issue by Sekou225** [opengisch/QField#4828]
### Describe the issue
In an openned project in Qfield 3.0.7, when you select a feature and try to edit its attributs, the button for cancel changes, habitually in top left of the attributs panel don't appear.

### Reproduction steps
1. Open your project with vector editable layer
2. Select a feature by simple clic on it
3.  In the panel that appears, clic on the edit button
4. the editable field will change to grey background
5. Add or change informations in a field
6. Now try to cancel your editions.
7. There is no option to cancel attributs changes you made 

### Expected behavior
when the attribut edition button is hit, THE CANCELLATION BUTTON WHOULD APPEAR AT THE TOP LEFT OF THE ATTRIBUT'S PANEL

### Observed behavior
THERE IS NO OPTION TO CANCEL EDITION MADED
### Screenshots and GIFs
**As it appears in Qfield 2.8.3** / THE WAY IT SHOULD BE

![image](https://github.com/opengisch/QField/assets/91322749/bf0c9b93-5fd6-494f-a236-84e3c0a11075)

**As it appears in Qfield 3.0.7**  / THE WAY IT IS

![image](https://github.com/opengisch/QField/assets/91322749/1db85796-6442-4b1e-872a-08d8ccd6890d)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.30
 - QFieldSync Version 4.6.1

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@Sekou225 , that's a setting, not a bug :) you must have accidentally turned on fast editing in the settings:

![Screenshot_20231205-073639](https://github.com/opengisch/QField/assets/1728657/9f547e81-e7a5-4e2d-b32d-77c3eb581fc1)

When that is switched on, every single edit made is immediately saved, hence why the cancel button is hidden. You should turn that off and see QField behave like you'd expect.

Cheers.

**Comment by Sekou225** [comment]
@nirvn Thank at lot. It was exactely that.
