### ISSUE TITLE
Open projet from Qfield dont detect projet if external SD card is mount

### ISSUE THREAD

**Issue by geostonemarten** [opengisch/QField#483]
I have create a folder in my internal memory "QFIELD" and have create a sub foder that contain my project. If SD card is mounted there is no project detected on QField space (blue Qfield link un

### Reproduction Steps (with sd card external mounted)
1. add project in internal memory /QFIELD/myprojet/myproject.qgs
2. find a project to open it
3. nothing here

### Expected behavior:
I see my folder and project QGS contained

### Observed behavior:
if external sd card is dismount: I see my folder and project QGS contained
else (sd cart mount) : 15s after touch "QFied" there is a message "impossible to load content"

### Screenshots and GIFs

Menu with sd card mounted
![menu with sdcard](https://user-images.githubusercontent.com/5580128/53095101-379e7a00-351c-11e9-960c-4e4c1a3e372c.png)

Normal result and result when sd card is dismounted
![normal result case ](https://user-images.githubusercontent.com/5580128/53095231-8f3ce580-351c-11e9-96ef-c68d9e884f28.png)

Menu after eject card
![02 : sd card dismounted
](https://user-images.githubusercontent.com/5580128/53094832-87307600-351b-11e9-9de2-057c45317ed0.png)

No result if card is mounted
![menu without sdcard](https://user-images.githubusercontent.com/5580128/53094667-15582c80-351b-11e9-9158-91a5c528bc50.png)

**QField version:** 1.0.0-rc3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Not tested
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by geostonemarten** [comment]
I see also a problem when i change folder from QField link folder.

It don't proposed subfolder when I go to parent folder...

**Comment by marioba** [comment]
Thanks @geostonemarten for the report.
The file selection part was problematic and was completely rewritten recently. It will be part of the next release of QField. If you want you can already test it by installing the apk found [here](https://github.com/opengisch/QField/pull/476#issuecomment-463287849).

**Comment by geostonemarten** [comment]
> Thanks @geostonemarten for the report.
> The file selection part was problematic and was completely rewritten recently. It will be part of the next release of QField. If you want you can already test it by installing the apk found [here](https://github.com/opengisch/QField/pull/476#issuecomment-463287849).

arm7 or x86?

**Comment by marioba** [comment]
Depends on your device's processor.
Probably arm7...

**Comment by marioba** [comment]
I'm closing this issue because the file selector is completely different now. If there are still problems, you can proceed with a new issue.
