### ISSUE TITLE
log is blank

### ISSUE THREAD

**Issue by geostonemarten** [opengisch/QField#485]
Log is blank sceen

**QField version:** 1.0.0-rc3

**Comment by m-kuhn** [comment]
The log only shows errors, maybe there is none?

**Comment by geostonemarten** [comment]
> The log only shows errors, maybe there is none?

Humm. I Report 3 applications problems... I think log need contains part of problems but there is nothing... The level of log is not a parameters. 

There is a system path for trace log? 

there is no document on internal memory
check ./Android/data/ch.opengis.qfield/files/
.qgis2 > nothing No Qgis 3 ???
Alarms > nothing
Documents > Nothing
Movies > Nothing
Music > Nothing
Notifications > Nothing
Picures > Nothing
Podcasts > Nothing
share > Nothing

**Comment by m-kuhn** [comment]
Do you have a .qgs project file placed on your device?

**Comment by geostonemarten** [comment]
> Do you have a .qgs project file placed on your device?

yes there is multple project.

One in ./Download/
One in ./QFIELD/myproject/

**Comment by m-kuhn** [comment]
And you can open them? (I don't see those listed in the empty paths above)

**Comment by geostonemarten** [comment]
> And you can open them? (I don't see those listed in the empty paths above)

Yes the twice is open automatically because this is the last work project. the first is an old project just download and unzip for test.

**Comment by m-kuhn** [comment]
Sorry, I really have trouble to follow exactly what your problems are if you can open your project.

**Comment by geostonemarten** [comment]
There is no log and this is the problem.
I have 10 crash app in 2 days so this is my problem! log is blank in the proposed menu and I can't find the corresponding file.
Problem to find project https://github.com/opengisch/QField/issues/483
Problem on layer changed https://github.com/opengisch/QField/issues/484

So I think log should contain information about that

**Comment by m-kuhn** [comment]
Unfortunately this class of errors does not write anything to the log, the log is mostly there for messages that come from qgis (e.g. problems with data providers).

* For crashes like #484, it's too late to write a log, for these it's best to open an issue as you have done and send a crash report to the play store as suggested after the crash. What you can do is to get a logcat and attach it to the issue report, that will help a lot but requires to setup some tools on a computer too.

* For #483, there might be a log entry in the future but it's up to @marioba to tell us how to best proceed there.
