### ISSUE TITLE
Expression constraint depending on another field is NOT re-evaluated when dependent field has changed

### ISSUE THREAD

**Issue by marcantoinedupre** [opengisch/QField#4855]
### Describe the issue

It seems that a field's expression-based constraint depending on another field's value is not re-evaluated smoothly when the other field's value has changed. Though it works in QGIS.

For instance with the following project : my layer has a `type` field with 2 possible values, "foo" and "bar", and a `foo_subtype` field. I want to make `foo_subtype` mandatory but only when the `type` field has the "foo" value. I use the following expression constraint on `foo_subtype`:

```
NOT (type IS 'foo' AND foo_subtype IS NOT NULL)
```

(btw my use case is that the `subtype` field would be in another form tab with conditional visibility. And since I would have several of those tabs I cannot just use the NOT NULL constraint. Otherwise the user would be blocked in validating the form because of invisible tabs).

In QGIS this works like I expect: depending on the `type` value the `foo_subtype` field immediatly toggle between mandatory and not mandatory.

In QField this does not work, it looks like the validity of the constraints on a field are evaluated only when the value of that field changes but not when other values change.

### Reproduction steps
1. Add a new entity to `test` layer
2. On the form select the "foo" value for the `type` field

### Expected behavior

The form presentation should change to indicate an invalid value and the text "Expression constraint" in red color should appear below the field `foo_subtype`.

### Observed behavior

Nothing happens (unless you change `foo_subtype` value to "A" or "B" and then to NULL).

### Screenshots and GIFs

![qfield_expression_constraint_issue](https://github.com/opengisch/QField/assets/15977920/159faa8f-cc0c-4d0f-90f3-5b544a58470d)

demo project : [dependent_constraint.zip](https://github.com/opengisch/QField/files/13686158/dependent_constraint.zip)

The zip file contains:

- dependent_constraint.qgs
- dependent_constraint.gpkg

### Desktop (please complete the following information)
 - OS: Linux Ubuntu 22.04
 - QGIS Version 3.34.1
 - QFieldSync Version [e.g.4.0.0]
 - QField version: 3.0.7

### Mobile (please complete the following information)
 - OS: Android 7
 - QField version: 3.1.3 (14a225)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: not tested
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by zhuwq75** [comment]
Yes, I also met the same issue since version 2.8.8, but it is ok for version 2.8.7. Hope this problem can be solved soon!

**Comment by nirvn** [comment]
@marcantoinedupre , this is a fantastic issue report, made it really easy to dissect and fix. Keep those coming :)

The fix is in this PR (https://github.com/opengisch/QField/pull/4935), it'll be in the next QField point release.

**Comment by nirvn** [comment]
@marcantoinedupre , you can confirm the issue has been fixed by running this linux dev build: https://github.com/opengisch/QField/actions/runs/7509804616?pr=4935

**Comment by marcantoinedupre** [comment]
I can confirm it is fixed, thanks! :pray: 

I am glad the details I provided were useful. :)
