### ISSUE TITLE
Editing features with stylus

### ISSUE THREAD

**Issue by Paul-Losse** [opengisch/QField#4869]
### Describe the issue
When editing a polygon with a stylus (Samsung S pen), the first edit works as expected. However when trying subsequent edits only the previously used tool is available. The full suite of editing tool is then not available.

### Reproduction steps
1. select a polygon using the stylus
2. Select feature using stylus in attribute form
3. Select edit geometry button in attribute form
4. Select editing tool on main map canvas 

### Expected behavior
On each editing occasion using a stylus, each geometry editing tool should be available and not just the previously used tool

### Observed behavior
On the first edit using the stylus, all editing tools are available and editing works as expected. Subsequent edits using a stylus do not work as expected, only the last used tool is available.  This problem can only be cleared by using a finger to select the editing tool. This problem occurs on both a Samsung Tab Active 3 and Samsung Galaxy Tab S3 and using both geopackages and shapefiles. The problem has only occurred since upgrading to QField version 3.1.3. 

### Screenshots and GIFs
![Screenshot_20231219_094806-1](https://github.com/opengisch/QField/assets/77330795/de899827-89fb-4f92-832a-08ce756d4201)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.34.1
 - QFieldSync Version 4.6.3

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab Active 3
 - OS: Android 13
 - QField version: 3.1.3 - Borneo (14a225 v3.1.3)
![Screenshot_20231219_094806](https://github.com/opengisch/QField/assets/77330795/75893b66-6f76-47d1-a3b7-b49777660733)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by Paul-Losse** [comment]
https://github.com/opengisch/QField/assets/77330795/83c3a718-c44f-443a-8e0b-1f6ba3f7393d

**Comment by nirvn** [comment]
@Paul-Losse , useful video, will look into it.

**Comment by nirvn** [comment]
@Paul-Losse , I believe the APK in this pull request (https://github.com/opengisch/QField/pull/4877) fixes your issue. Thanks for reporting this.

**Comment by Paul-Losse** [comment]
Thanks very much for this. Will the fix be implemented via playstore update?

Otherwise, how do I update using the APK (apologies, I'm not a techie!)

Best regards

Paul
