### ISSUE TITLE
QField 1.0.0 rc3 crash on startup in Huawei Mediapad t3 7

### ISSUE THREAD

**Issue by eduardosoltig** [opengisch/QField#488]
Hi

I just installed the version M... (1.0.0 Release Candidate 3) after installing and open the app QField just crash on starup, cant use the app.

QField version: 1.0.0 Release Candidate 3
Android version: 7.0
Device: Huawei Mediapad t3 7
Emui: 5.1

1. [First Step]: download Release Candidate 3 qfield-v1.0.0-rc3-armv7.apk
2. [Second Step] install QField 1.0.0 Release Candidate 3
3. [Other Steps...] Open QField

Crash on starup

**QField version:** 1.0.0 Release Candidate 3

## Additional information:
Lucendro 0.11.90 Legacy release for Android 4.4 works perfectly without problems

* Problem started happening recently, didn't happen in an older version of QField: Yes

* Problem can be reliably reproduced, doesn't happen randomly: Yes on +12 Huawei Mediapad t3 7 devices that I have
* Problem happens with all files and projects, not only some files or projects: cant tell its in startup

I hope I can help if you need more info Im here to assit
Thanks for the atention

**Comment by 3nids** [comment]
Could you please try the APK here and report if this is still failing
https://github.com/opengisch/QField/commit/5b1a942a1fff3bac23c96f98d1a781141d4c2bb2#commitcomment-32578312
thanks.

**Comment by eduardosoltig** [comment]
Hi Denis

I tested the apk in 

https://github.com/opengisch/QField/commit/5b1a942a1fff3bac23c96f98d1a781141d4c2bb2#commitcomment-32578312

and appears to work as intended!

thanks.

Im going to test de (1.0.0 Release Candidate 5) to see if also works

**Comment by 3nids** [comment]
glad to read this 👍
