### ISSUE TITLE
QField Android Build Locally on Windows

### ISSUE THREAD

**Issue by ajithandro** [opengisch/QField#4895]
### Issue Description  
I need to Clone and set up/Build the QField Android  Application in Windows Locally. Please Verify the Below Steps I have tried and  Suggest me the Correct Procedure to build Android app locally in windows.

[https://github.com/opengisch/QField/blob/master/doc/dev.md](https://github.com/opengisch/QField/blob/master/doc/dev.md)
Based do the above Development Document tried with docker and local setup like mentioned below

### Docker
1. Installed Docker on  Windows
2. Cloned the Source from Repo
3. `triplet=arm64-android ./scripts/build.sh`

### Issue Raised with Docker
```
$ triplet=arm64-android ./scripts/build.sh
[+] Building 7.4s (12/16)                                                                                                                                              docker:default 
 => [internal] load .dockerignore                                                                                                                                                0.2s 
 => => transferring context: 2B                                                                                                                                                  0.1s 
 => [internal] load build definition from Dockerfile                                                                                                                             0.1s 
 => => transferring dockerfile: 1.99kB                                                                                                                                           0.1s 
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                                  4.7s 
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                    0.0s 
 => [ 1/11] FROM docker.io/library/ubuntu:22.04@sha256:6042500cf4b44023ea1894effe7890666b0c5c7871ed83a97c36c76ae560bb9b                                                          0.0s 
 => [internal] load build context                                                                                                                                                0.2s 
 => => transferring context: 673B                                                                                                                                                0.1s 
 => CACHED [ 2/11] RUN dpkg --add-architecture i386 && apt-get update -yqq && apt-get install -y   curl   expect   git   make   libc6:i386   libgcc1:i386   libncurses5:i386     0.0s 
 => CACHED [ 3/11] RUN groupadd android && useradd -d /opt/android-sdk-linux -g android -u 1000 android                                                                          0.0s 
 => CACHED [ 4/11] COPY tools /opt/tools                                                                                                                                         0.0s 
 => CACHED [ 5/11] COPY licenses /opt/licenses                                                                                                                                   0.0s 
 => CACHED [ 6/11] WORKDIR /opt/android-sdk-linux                                                                                                                                0.0s 
 => ERROR [ 7/11] RUN /opt/tools/entrypoint.sh built-in                                                                                                                          1.7s 
------
 > [ 7/11] RUN /opt/tools/entrypoint.sh built-in:
1.543 /bin/sh: 1: /opt/tools/entrypoint.sh: not found
------
Dockerfile:65
--------------------
  63 |     WORKDIR /opt/android-sdk-linux
  64 |
  65 | >>> RUN /opt/tools/entrypoint.sh built-in
  66 |
  67 |     RUN yes | /opt/android-sdk-linux/cmdline-tools/latest/bin/sdkmanager --licenses && /opt/android-sdk-linux/cmdline-tools/latest/bin/sdkmanager "ndk;${NDK_VERSION}"
--------------------
ERROR: failed to solve: process "/bin/sh -c /opt/tools/entrypoint.sh built-in" did not complete successfully: exit code: 127

View build details: docker-desktop://dashboard/build/default/default/0zbro3pojmxzjookep03lv6vy
```

### Docker Screenshots 
![image](https://github.com/opengisch/QField/assets/57447752/65f391c9-704a-44c1-9e98-c08b30d1983b)

### Development Document Steps
![image](https://github.com/opengisch/QField/assets/57447752/ca55b453-0811-4875-a22a-f6d64135e870)

### Local Setup Steps
1. Installed CMake 
2. Latest Android NDK Downloaded From the Source - [https://developer.android.com/ndk/downloads]. (https://developer.android.com/ndk/downloads) - Don't Know Where this needs to be Configured.
3. To Install QT Installed Pip Via Python from the Source [https://[bootstrap.pypa.io/get-pip.py](https://bootstrap.pypa.io/get-pip.py).
4. `aqt install-qt linux android 6.5.0 android_arm64_v8a -m qt5compat qtcharts qtpositioning qtserialport qtconnectivity qtmultimedia qtwebview qtsensors  --autodesktop`- Getting 'aqt' is not recognized as an internal or external command
5. Updated the NDK Path in Docker File - `export ANDROID_NDK_HOME=[path to your android ndk]`.
6. `cmake -S QField -B build -D VCPKG_TARGET_TRIPLET=arm64-android` - Getting Following Error

### Issue Raised with Local Setup
```
$ cmake -S D:/Projects/QField -B D:/Projects/QField/build -D VCPKG_TARGET_TRIPLET=arm64-android -D SYSTEM_QT=ON
CMake Warning (dev) at cmake/Platform.cmake:24 (set):
  implicitly converting 'INT' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:24 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Platform.cmake:25 (set):
  implicitly converting 'INT' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:24 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Platform.cmake:26 (set):
  implicitly converting 'INT' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:24 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Building for Android --
-- Updating vcpkg
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
-- Building with vcpkg libraries version
CMake Error at build/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:209 (include):
  include could not find requested file:

    C:\Program Files\android-ndk-r26b-windows\android-ndk-r26b/build/cmake/android.toolchain.cmake
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:170 (include)
  CMakeLists.txt:32 (project)


-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet arm64-android...
error: while detecting compiler information:
The log file content at "D:\Projects\QField\build\detect_compiler\stdout-arm64-android.log" is:
-- Configuring arm64-android
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/Projects/QField/build/_deps/vcpkg-src/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: D:/Projects/QField/build/detect_compiler/arm64-android-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Projects\QField\build\detect_compiler\config-arm64-android-rel-CMakeCache.txt.log
      D:\Projects\QField\build\detect_compiler\config-arm64-android-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:170 (include)


error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
-- Running vcpkg install - failed
CMake Error at build/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  D:\Projects\QField\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:170 (include)
  CMakeLists.txt:32 (project)


-- Configuring incomplete, errors occurred!
```

### Local Build Failure Screenshots 
![image](https://github.com/opengisch/QField/assets/57447752/2e72613d-f365-4da2-b355-c4959f205aad)

Thanks

**Comment by m-kuhn** [comment]
Hi, thanks for getting in touch.

We don't have any experience in building for android on windows, we only ever did that on Linux.

1. I would assume the docker build should work quite similar. It looks as if the docker build context was not properly added.
In your first snippet you can see ` => CACHED [ 4/11] COPY tools /opt/tools   ` which is supposed to copy in tools, whereas these tools are later not found `1.543 /bin/sh: 1: /opt/tools/entrypoint.sh: not found`.
It would be good to start looking into why these tools are not copied.
2. For "local setup" it will probably require a good amount of time to dive into the build process and fine tune everything, as nobody (to my knowledge) has done this before. In the last screenshot, you can see some "logs for more information" which will be the best starting point if you want to start looking into this.
3. You might also consider to test things using WSL2. I admit that I don't know the level of docker integration of that either.

The "easiest" approach is probably to build on a linux machine instead.

**Comment by m-kuhn** [comment]
Please let us know how it goes

**Comment by m-kuhn** [comment]
Just use the command documented in https://github.com/opengisch/QField/blob/master/doc/dev.md#using-a-docker-image

It's by far the most reliable and stable approach

**Comment by ajithandro** [comment]
Do you have any idea on this @m-kuhn 
Package: boost-vcpkg-helpers:arm64-android@1.83.0

**Host Environment**

- Host: x64-linux
- Compiler: Clang 14.0.6
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: f1c6efee2 2023-12-24 (10 days ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /usr/src/qfield/build-arm64-android/_deps/vcpkg-src/vcpkg-bundle.json
[DEBUG] Failed to open: /usr/src/qfield/build-arm64-android/_deps/vcpkg-src/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] Detected /.dockerenv file
[DEBUG] 1000: execute_process(curl --fail -L https://raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt --create-dirs --output /usr/src/qfield/build-arm64-android/_deps/vcpkg-src/downloads/boost_LICENSE_1_0.txt.28614.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 35 after    92304 us
error: Failed to download from mirror set
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt: curl failed to download with exit code 35
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to raw.githubusercontent.com:443 

[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(1048): 
[DEBUG] Time in subprocesses: 92304us
[DEBUG] Time in parsing JSON: 8us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 284us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 93.7 ms (93010us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/boost-vcpkg-helpers/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:170 (include)

Based on the Above Error Response, the Following URL failed to Download the License  due Proxy or something
https://[raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt](https://raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt)

But It's Accessible in Browser  
![image](https://github.com/opengisch/QField/assets/57447752/9aeb2c66-b9c6-4e68-b8a4-ad22e705f4c0)

**Comment by m-kuhn** [comment]
This looks like a local connectivity problem:

```
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to raw.githubusercontent.com:443 
```

Can you just try again?

**Comment by ajithandro** [comment]
@m-kuhn  I have fixed the issue and Successfully Took one development build of application, later just tried to change app name and  app logo and tried the same I'm getting the following issue from VCPK.
Please see the issue created on VCPKG if you get chance 
[https://github.com/microsoft/vcpkg/issues/36071](https://github.com/microsoft/vcpkg/issues/36071)

and I'm trying with the Second approach with the Cmake
export ANDROID_NDK_HOME=[path to your android ndk]
cmake -S QField \
      -B build \
      -D VCPKG_TARGET_TRIPLET=arm64-android
I'm not aware where I need to config the NDK path , downloaded the ndk from the following source [https://developer.android.com/ndk/downloads](https://developer.android.com/ndk/downloads) , can you pls let me know if you know about this?

**Comment by m-kuhn** [comment]
> export ANDROID_NDK_HOME=[path to your android ndk]

Is that not sufficient?

**Comment by ajithandro** [comment]
I understood, I have Downloaded the NDK and Configured it in a docker file like, tried with the complete path too , is this need to mention somewhere too?
![image](https://github.com/opengisch/QField/assets/57447752/ebc970f3-ed7a-421d-a41d-385c13124787)

**Comment by m-kuhn** [comment]
I am confused which approach you are following:

- local build, you need to download the ndk and sdk, but no dockerfile involved
- dockerized build, we ship a dockerfile that does all that setup and a script (`scripts/build.sh`) that does everything for you

**Comment by ajithandro** [comment]
### Docker
Docker approach which you said worked for me  last week, Now I just Changed the logo alone and tried to build with the `scripts/build.sh`, getting an issue 
![image](https://github.com/opengisch/QField/assets/57447752/d71b112d-1803-430b-98da-fdb680ba7aa0)

### Cmake
So I just tried the Cmake approach to build the app locally, with the command steps mentioned in document , 
In the this Approch I have Downloaded the NDK   is this need any configurations or just place the downloaded NDK into Project Folder is enough for this that's my Query @m-kuhn

**Comment by m-kuhn** [comment]
Please read the logs which are mentioned in the error. Please also give clear instructions what you did and post text, not screenshots. Please also try with latest master with no modifications.

One thing you could also try is

```
sudo setenforce 0
```

To make sure selinux is not in your way.

**Comment by ajithandro** [comment]
okay

**Comment by skylning** [comment]
> Do you have any idea on this @m-kuhn Package: boost-vcpkg-helpers:arm64-android@1.83.0
> 
> **Host Environment**
> 
> * Host: x64-linux
> * Compiler: Clang 14.0.6
> * vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
>   vcpkg-scripts version: f1c6efee2 2023-12-24 (10 days ago)
> 
> **To Reproduce**
> 
> `vcpkg install ` **Failure logs**
> 
> ```
> -- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
> [DEBUG] To include the environment variables in debug output, pass --debug-env
> [DEBUG] Trying to load bundleconfig from /usr/src/qfield/build-arm64-android/_deps/vcpkg-src/vcpkg-bundle.json
> [DEBUG] Failed to open: /usr/src/qfield/build-arm64-android/_deps/vcpkg-src/vcpkg-bundle.json
> [DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
> [DEBUG] Metrics enabled.
> [DEBUG] Feature flag 'binarycaching' unset
> [DEBUG] Feature flag 'compilertracking' unset
> [DEBUG] Feature flag 'registries' unset
> [DEBUG] Feature flag 'versions' unset
> [DEBUG] Feature flag 'dependencygraph' unset
> [DEBUG] Detected /.dockerenv file
> [DEBUG] 1000: execute_process(curl --fail -L https://raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt --create-dirs --output /usr/src/qfield/build-arm64-android/_deps/vcpkg-src/downloads/boost_LICENSE_1_0.txt.28614.part)
> [DEBUG] 1000: cmd_execute_and_stream_data() returned 35 after    92304 us
> error: Failed to download from mirror set
> error: https://raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt: curl failed to download with exit code 35
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
> curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to raw.githubusercontent.com:443 
> 
> [DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(1048): 
> [DEBUG] Time in subprocesses: 92304us
> [DEBUG] Time in parsing JSON: 8us
> [DEBUG] Time in JSON reader: 0us
> [DEBUG] Time in filesystem: 284us
> [DEBUG] Time in loading ports: 0us
> [DEBUG] Exiting after 93.7 ms (93010us)
> 
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
>       
>       Failed to download file with error: 1
>       If you are using a proxy, please check your proxy setting. Possible causes are:
>       
>       1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
>          to `https://address:port`. This is not correct, because `https://` prefix
>          claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
>          , etc..) is an HTTP proxy. Try setting `http://address:port` to both
>          HTTP_PROXY and HTTPS_PROXY instead.
>       
>       2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
>          set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
>          The value set by your proxy might be wrong, or have same `https://` prefix issue.
>       
>       3. Your proxy's remote server is out of service.
>       
>       If you've tried directly download the link, and believe this is not a temporary
>       download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
>       to report this upstream download server failure.
>       
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
>   ports/boost-vcpkg-helpers/portfile.cmake:4 (vcpkg_download_distfile)
>   scripts/ports.cmake:170 (include)
> 
> Based on the Above Error Response, the Following URL failed to Download the License  due Proxy or something
> https://[raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt](https://raw.githubusercontent.com/boostorg/boost/boost-1.83.0/LICENSE_1_0.txt)
> ```
> 
> But It's Accessible in Browser ![image](https://private-user-images.githubusercontent.com/57447752/293919122-69cdb757-37d8-4f93-bf9b-1eb6c6d5ad3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzI2MzMsIm5iZiI6MTcwNDg3MjMzMywicGF0aCI6Ii81NzQ0Nzc1Mi8yOTM5MTkxMjItNjljZGI3NTctMzdkOC00ZjkzLWJmOWItMWViNmM2ZDVhZDNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA3Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlOWRlZTZmM2M5NzVmNDY0YTExY2Q5NTgzM2M5ZTM1ZDI4NDJlZTU5NDNkNDU5ZTAwZmJkNTc3OTIxMzliYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FPrUhAAPb3LzbDioyfhIgjGzES6kZVcX9Fcs8PD7dQU)

change you subnet mask

**Comment by ajithandro** [comment]
@m-kuhn @skylning I have Done a Local Setup and Got the Android to debug version of the Build APK file with the docker procedure,
can you please let me know the process of Production(Release Version) Of APK File ?

**Comment by m-kuhn** [comment]
You will somehow need to bundle it (from within the docker)

https://github.com/opengisch/QField/blob/master/.github/workflows/android.yml#L174

This is not something that has been tested or documented, but should normally work

**Comment by ajithandro** [comment]
Yes @m-kuhn i have seen this CMD , I hope in this release folder .aab file or .apk will generated once build sucessful right?
`${{ env.CMAKE_BUILD_DIR }}/src/app/android-build/build/outputs/apk/release`

But in my case i have only debug folder alone release folder not exists

**Comment by m-kuhn** [comment]
superseded by https://github.com/opengisch/QField/issues/4962
