### ISSUE TITLE
viewing changes in Qfield.Cloud website broken in recent versions of Chrome browser

### ISSUE THREAD

**Issue by w0pr** [opengisch/QField#4897]
### Discussed in https://github.com/opengisch/QField/discussions/4896

Opening popup to view changes for a prticular changes ID (circled in red in screenshot below)  stopped working in recent Chrome browser versions.

![image](https://github.com/opengisch/QField/assets/8257055/b88ffa55-51b5-4888-b4a7-842b2a3b3fc9)

It seems that since at least a few weeks ago, opening this popup does not work anymore in Chrome (tried with current version120.0.6099.130), since the relative URL (from "href" property) is missing its base.

![image](https://github.com/opengisch/QField/assets/8257055/2d213a4c-fd6d-4491-a308-f0d83d4eb1e9)

```
jquery.min.js:2 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at new Reviewer (qfc.0e04ee1f1fa0.js:860:21)
    at qfc.0e04ee1f1fa0.js:1381:22
    at HTMLDocument.<anonymous> (qfc.0e04ee1f1fa0.js:1453:5)
    at e (jquery.min.js:2:30038)
    at t (jquery.min.js:2:30340)
```

Firefox works, though.

**Comment by SeqLaz** [comment]
This is a known issue related to an update in the code base of Chromium browsers. To address this, we recommend using the Firefox browser to open those modals of changes. By the way, a fix for this issue will be released soon.
