### ISSUE TITLE
Include feet unit for altitude. Add simple stateout tool for engineering purposes

### ISSUE THREAD

**Issue by ConJaySten** [opengisch/QField#4899]
(For clarity, proposed enhancements are
shown in **red** on Figures 1 – 4, the actual
style should conform to existing UI
standards)

Include a pull down menu in ‘Positioning.’
Figure 1![1_300x800](https://github.com/opengisch/QField/assets/135619877/7f820123-58f0-4799-8c3b-ec77ebce788e)  

The pulldown menu allows for the selection of an
‘Altitude Units’ in either meters or
international feet. See Figure 1

Figure 2![2_360x800](https://github.com/opengisch/QField/assets/135619877/10cc4c08-ce15-437f-a7a8-05fadc2f2771)

The pull down menu shown in Figure 1
changes the displayed altitude value seen
in Figure 2 as “516.54 ft” The value
should be rounded to the nearest
hundredth.

Include "Stakeout Tool"  in settings:
Figure 3![3_360x800](https://github.com/opengisch/QField/assets/135619877/76073cc4-34da-4a46-9036-39887d8406b1)

In the settings menu, include a
new option for “Stakeout Tool.”
The purpose of the tool is to generate a
negative or positive number based on a
user inputted value seen in Figure 4.

Figure 4![4_360x800](https://github.com/opengisch/QField/assets/135619877/282fcf9e-c466-4302-ac6f-834f50b0c164)

The “Stakeout Tool” should have a user
defined “input value” shown in Figure 4
as “514.34”
Tapping the “input value” should open the
keyboard to input values.
This user inputted value should be
subtracted from the displayed “Altitude”
value to arrive at the Δ value
“-2.20” displayed near the digitizing
cursor as a live readout.
The Δ value should automatically change
if the user changes the input value.
The tool remains active until the user
closes the tool.

**Comment by nirvn** [comment]
@ConJaySten , regarding stakeout, have you checked the vertical stakeout meter in the precise positioning view that appears when you set a destination point?

**Comment by ConJaySten** [comment]
I didn't know about that feature.  That's way better than what I was asking for.  Thanks for the follow up.
