### ISSUE TITLE
Data modifications done on existing objects are not saved

### ISSUE THREAD

**Issue by gnerred** [opengisch/QField#49]
With version 0.7.1, it becames impossible to edit data of existing features : 

1°/ Long touch on a point (Spatialite point layer)
2°/ Touche on start edit button
3°/ Change some values in the form
4°/ Touch on save button
5°/ Close the form
6°/ Long touch on the same point -> data modifications are OK
7°/ Exit and start QField
8°/ Long touch on the same point -> data modifications are lost ! They have not been saved

**Comment by m-kuhn** [comment]
I am about to release a new beta version in the next hours which fixes some issues with the editing system and also introduces a message log which sometimes helps to debug problems.

**Comment by gnerred** [comment]
Cool :O)

**Comment by m-kuhn** [comment]
0.7.2 will contain these fixes, I'll be happy to get feedback.

**Comment by gnerred** [comment]
I will test today or tomorrow

**Comment by gnerred** [comment]
Issue fixed by 0.7.2, thanks !
