### ISSUE TITLE
changes are not saved in version 3.1.4 of qfield

### ISSUE THREAD

**Issue by CACG1022** [opengisch/QField#4909]
Hello, I have problems with version 3.1.4 of QField. It turns out that when I finish filling out all the mandatory fields in the form, the application doesn't allow me to save, even though all the mandatory fields are filled. In fact, in the attached image, you can see that the form changes to green, but I still get the message that the photo cannot be saved.

<img width="602" alt="ayudaqfield" src="https://github.com/opengisch/QField/assets/118937011/33352320-483f-4092-a7ce-af2899a4bbfb">

**Comment by m-kuhn** [comment]
Hello,

Could you add some additional information?

- a sample project
-  steps to reproduce
- operating system
- did it work with earlier versions

Thank you

**Comment by CACG1022** [comment]
Hello, if it works with previous versions, I am attaching the project so you can review it. It is currently working for me with version 3.0.7 amazon
[PRUEBAX1.zip](https://github.com/opengisch/QField/files/13829897/PRUEBAX1.zip)

**Comment by m-kuhn** [comment]
What operating system are you using?

**Comment by CACG1022** [comment]
I AM USING IT ON ANDROID 12 AND WINDOWS 10

**Comment by dziyad91** [comment]
I encounter a similar issue in this QField 3.1.6 version

**Comment by nirvn** [comment]
@CACG1022 , the problem has to do with default values that are incompatible with attribute field type. In upcoming QField 3.2, you'll find more helpful error messages in the message logs. This is what you'll see in QField 3.2:

```
Provider errors:
    Could not convert value for attribute "EXISTENCIA" to type Integer64
    Could not convert value for attribute "MAPPING" to type Integer64
```

Looking at your project, the default value for "EXISTENCIA" is a string value, which can't be transformed into Integer64. Same default value problem applies for "MAPPING".

Your solution here is to either change the field type from integer to string for "EXISTENCIA" and "MAPPING", or prepare default value expressions that output integers :)
