### ISSUE TITLE
Windows release binaries for 3.1.5 still install 3.1.4 (because they are identical)

### ISSUE THREAD

**Issue by w0pr** [opengisch/QField#4918]
### Describe the issue

See above.

### Reproduction steps

1. Download both:
https://github.com/opengisch/QField/releases/download/v3.1.4/qfield-v3.1.4-windows-x64.exe
https://github.com/opengisch/QField/releases/download/v3.1.5/qfield-v3.1.5-windows-x64.exe

2. Compare

3. Files are identical.

Freshly installed  "3.1.5" shows in "Programs and Feature" as 3.1.4:
![image](https://github.com/opengisch/QField/assets/8257055/5c0fd9b8-f587-451b-bc44-2e2d8e0b6bd2)

![image](https://github.com/opengisch/QField/assets/8257055/954f1e35-e336-4a3b-8230-cf3b8794320c)

**Comment by m-kuhn** [comment]
Correct, we are currently experiencing build problems. No changes were implemented for windows, so 3.1.4 was rereleased.
