### ISSUE TITLE
Apple pencil freezes certain QField functionalities

### ISSUE THREAD

**Issue by andreimirt** [opengisch/QField#4919]
### Describe the issue
After using Apple pencil, selecting a feature by hand doesn't work.

### Reproduction steps
1. Have a project open in QField
2. Pan the map using the Apple Pencil, or do any other action using the Apple pencil
3. Select a feature from the map using the Apple pencil
4. Select a feaure from the map using the hand

### Expected behavior
The feature intended to be selected should get selected and the form of the feature should pop up

### Observed behavior
The feature intended to be selected is not selected and the form of the feature does not pop up

### Desktop (Probably irelevant for this issue in my opinion)
 - OS: Windows 10
 - QGIS Version 3.28 LTR
 - QFieldSync Version 4.6.3

### Mobile
 - Device: iPad Pro (11-inch) (4th generation)
 - OS: [e.g. Android 11]
 - QField version: 3.0.5 - Amazonia (bfecdc v3.0.5) Qt 6.5.3

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

### User's understanding of the issue
* This is clearly an issue related to Apple Pencil interaction with Qt objects. Perhaps the issue is related to [this filled bug](https://bugreports.qt.io/browse/QTBUG-98936) on Qt issue tracker
* QField was probably not sufficiently tested with the Apple pencil.

### Workarounds
1. Once the issue is present (every time the Apple pencil is used in QField), the only solution is to restart QField and reopen the app.
2. To prevent the issue, Apple Pencil must not be used.

**Comment by m-kuhn** [comment]
Thank you for reporting, could you try with the latest QField version?

**Comment by NickSchub** [comment]
Same on Android. I'm working with The newest Version. It happend since Borneo came out.

**Comment by nirvn** [comment]
@NickSchub , do you have replicable steps for pencil freeze on Android?

**Comment by violetlatch** [comment]
Still having this issue with the latest Qfield (3.34.1) on Samsung Galaxy Tab Active3, Android 13. On using the stylus pen, the add waypoint dialogue comes up and then functionality freezes e.g. being able to select features with the pen.

**Comment by nirvn** [comment]
@violetlatch , could you provide a screencast here? Thanks

**Comment by violetlatch** [comment]
https://we.tl/t-KoXR4mfZuj

I’ve made a screen recording of what happens - it works fine if you don’t use the stylus pen, but when you do, the add waypoint menu appears unasked and then things freez.

**Comment by NickSchub** [comment]
Sorry for not responding. It seems to interact with the measurement tool. If the pencil is already freezed, I was able to use it again while deactivating/activating the measurement function.

**Comment by nirvn** [comment]
@NickSchub , can you share steps to reproduce this "frozen" interaction + measurement tool resurrection, and maybe also a video?
