### ISSUE TITLE
Map rotation with compass

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#492]
Hi there, I am new in using and promoting Qfield, but I have a first observation and request: please implement a map rotation mecanism/functionality, it will be very helpful to the orientation of users in the field.
Thanks!

https://github.com/opengisch/OSGeo4A/issues/40

**Comment by KirstenReilly** [comment]
Has this functionality got any further? We are interested the time frames for this

**Comment by 3nids** [comment]
There is no time frame as this feature is not currently sponsored. If you are interested to sponsor it, do not hesitate to contact us for an offer.

**Comment by Spacedatists** [comment]
This is still a thing for us. How do we get in touch?

**Comment by catalinmiraute** [comment]
Mail: ***@***.***
Phone: 0040721987501

**Comment by m-kuhn** [comment]
Best use the [contact form](https://www.opengis.ch/#contact) mentioned in https://qfield.org/docs/support/index.html#development-and-custom-apps

**Comment by nirvn** [comment]
Implemented.
