### ISSUE TITLE
Constraint argument is satisfied, but still can not save the qfield form

### ISSUE THREAD

**Issue by dziyad91** [opengisch/QField#4933]
### Describe the issue
I am using a qfield project. When filling in the form, the constraint is already satisfied (there is no more red dot indicator), but still can not save the form that is already filled. 
The problem does not happen in the previous QField version (3.0.7 Amazonia)

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.32.3
 - QFieldSync Version 4.6.0

### Mobile (please complete the following information)
 - Device: Xiaomi 12T
 - OS: Android 13
 - QField version: 3.1.6 (Borneo)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes (file with constraints argument)

**Comment by nirvn** [comment]
@dziyad91 , can you share a sample project to replicate this issue?

**Comment by dziyad91** [comment]
[Sample project.zip](https://github.com/opengisch/QField/files/13917324/Sample.project.zip)

Hi @nirvn, above is the sample project.

**Comment by nirvn** [comment]
@dziyad91 , it's a problem with your project; the following expression for your timestamp field produces a value that can't be parsed as datetime:
![image](https://github.com/opengisch/QField/assets/1728657/81385219-0ed1-4248-a4e7-c2ccd2a61987)

What were you trying to achieve here?  The first non-null value? If so, try coalesce(@position_timestamp, now()), that will work.

**Comment by dziyad91** [comment]
Hi @nirvn, I want to get the timestamp data but only if the position lock is active. I try your suggestion, but it is error, as shown below.

![error_1](https://github.com/opengisch/QField/assets/156417279/ab2a985b-8997-49b8-9c79-06b8b7867029)

or 

![error_2](https://github.com/opengisch/QField/assets/156417279/10e27df6-cef8-4216-b8e2-a9a7eb4731a2)

**Comment by 9ls1** [comment]
@dziyad91 I think you need to add coalesce in front of the start parenthese: **coalesce**(@position_timestamp, now()) to get the first non-null value as nirvn mentions in his comment.

**Comment by nirvn** [comment]
This isn't really a QField issue, and recent @m-kuhn 's improvement on the associated error message will help users figure out what's wrong with their project files.

**Comment by dziyad91** [comment]
Hi @nirvn @9ls1 , thanks. It works.

**Comment by dziyad91** [comment]
Hi @nirvn , could you check my project below? I have followed your previous suggestion but it seems there are other problems.
It works fine on the QField 3.0.7 Amazonia. But in QField 3.1.7, whenever I create a point data in "VGM form" layer, it always shows "Unable to save changes" although the constraints have already fulfilled.

[QField OPLS_example.zip](https://github.com/opengisch/QField/files/13934465/QField.OPLS_example.zip)
