### ISSUE TITLE
Image is randomly not renamed when taking Photo

### ISSUE THREAD

**Issue by soester** [opengisch/QField#494]
![bildschirmfoto 2019-02-28 um 16 19 12](https://user-images.githubusercontent.com/28543978/53577057-47017100-3b75-11e9-8947-999973f73e13.png)

Path in Form is stored as DCIM/20190228071817740.jpg Image is still named IMG_00000002.jpg

### Reproduction Steps:

1. Digitizing in field and take photos
2. Some Filenames get changed some not. Randomly not in a row. Qfield stores 'correct'/changed filepath in attribute form

### Expected behavior:
All Images should be renamed.

**QField version:** 11.11
Samsung TabActive Android 5.1.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
-> we weren not sure so far. today we could name the problem (We had one time when some Pictures were missing completely).
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: [Not sure]

**Comment by signedav** [comment]
Hi @soester 
Let me summarize:
You make a photo, the timestamp-like name is stored, but on your device you don't find this picture name. Instead you find the expected picture with another name. Right?

Do you use the system camera or the temporarily QField implementation?

**Comment by soester** [comment]
Hi @signedav 


> You make a photo, the timestamp-like name is stored, but on your device you don't find this picture name. Instead you find the expected picture with another name. Right?
Yes, that's correct

> Do you use the system camera or the temporarily QField implementation?
We used the Qfield implementation. The other doesn't work at all on our tablets.

This behavior didn't show up anymore recently, maybe it's fixed. I was never really sure why it happened.

**Comment by signedav** [comment]
Ok. I'll close it. Otherwise feel free to reopen.
