### ISSUE TITLE
QFieldCloud : What exactly happens when doing a full sync (instead of a push)

### ISSUE THREAD

**Issue by vlebert** [opengisch/QField#4942]
Hi

I have a setup as follows:

```
project.qgs
controle/data.sqlite       # database to be edited
ressources/fdp.sqlite    # readonly date such as baselayers. Could be spatialite or gpkg
```

I noticed that when doing a "full synd" on an android device, it could lead to updating the readonly files on the server even if this layer is set to readonly in QGIS project. I guess just opening the file changes the date of the file and QField considers it shoud be sent to the server.

I tried both `offline editing` and `direct access to datasource` (not sure of the english translation for those option) in the layer configuration (through qfieldsync plugin). **In both case it can lead to android client updating some layers I want to be readonly.** 

It does not add a feature, but it changes the file which is a mess because then my administrator have to decide what to do with those changes when syncing on its side. Moreover, it could lead to unnecessary bandwidth use for potential large files.

Finally, the "full sync" process often crashes my QField. I don't know if this is related or not.

Can you detail how android client behave when doing a full sync ? On desktop, we can choose a behaviour for each file during a sync but not on Android.

![digi-studio 2024-01-13 at 10 37 21](https://github.com/opengisch/QField/assets/49779177/06a67d3c-622d-476c-b0d7-d1d463f741cd)

![digi-studio 2024-01-13 at 10 41 27](https://github.com/opengisch/QField/assets/49779177/da0ffb05-a926-403a-b980-ab0bddd5df26)

**Comment by suricactus** [comment]
Hey @vlebert . Thanks for the question!

Let me try to explain what happens. Assuming you already did a few changes in QField:

1) QField shows loading...
2) the changes from QField are pushed to the cloud
3) the changes create a new apply job
4) the job gets picked and executed
5) all changes that succesfully modified your data are now incorporated in your datasource and are having status "applied". Those that failed to apply have status "not applied".
6) QField downloads a new copy of your project data with all changes that got successfully applied.
7) Once the download is ready, the QField project is reloaded.

Note that QField -> QFieldCloud communication is not with the full files, but just the changes.

The observed behaviour that some GPKG files are rewritten without being changed is currently known limitation that we are working on solution. Unfortunately, some implementation details on GPKG as file format prevents us from providing a providing a fast solution on this issue.

Will keep you posted about the advancements we are doing on this front. For now I will close this issue as it is more a question.

**Comment by vlebert** [comment]
Thanks for detail

Is it also true for spatialite layers ?
It is a bit of an issue: I often have heavy baselayer and the duplication of the file server-side take un-necessary ressources (especially as storage is a paying ressource).

Couldn't you not duplicate any file server-side if all depending layers are set to read-only in the project ?
