### ISSUE TITLE
The QField user interface language can not be changed with the system language

### ISSUE THREAD

**Issue by zhuwq75** [opengisch/QField#4953]
### Describe the issue
No matter how I change it in the settings menu (Settings--General--User Interface Language), the QField UI language always shows up in English, but the settings page itself shows the correct system language (Chinese).

### Reproduction steps
1. Settings--General--User Interface Language--system
2. Home menu: English; Context menu: English
3. Settings page: Chinese (system)

### Expected behavior
Because my phone has a Chinese version of Android operating system, I hope that both the main menu and the context menu will display Chinese when I set the UI language as system. 

### Observed behavior
Except the settings page itself shows the correct system language (Chinese), the UI language always shows up in English. 

### Screenshots and GIFs
![微信图片_20240115182451](https://github.com/opengisch/QField/assets/155275975/09a2e9b3-5d92-4ba8-a620-1df6abaab5c2)
![微信图片_20240115182513](https://github.com/opengisch/QField/assets/155275975/2af607ec-6729-4e7c-abf1-9ef9ffdf9c82)
![微信图片_20240115182506](https://github.com/opengisch/QField/assets/155275975/8a9edd99-1d7b-4944-be1a-097b1f713cbc)
![微信图片_20240115182502](https://github.com/opengisch/QField/assets/155275975/6414bc7c-8864-4640-a126-fde33e7b47b2)

### Mobile (please complete the following information)
 - Device: Xiaomi 13
 - OS: Android 11 (Xiaomi HyperOS)
 - QField version: qfield-v3.1.8-arm64-android.apk

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@zhuwq75 , what happens if you explicitly select Chinese in the list of languages (instead of system) and restart QField?

**Comment by zhuwq75** [comment]
> @zhuwq75 , what happens if you explicitly select Chinese in the list of languages (instead of system) and restart QField?

The same issue as I have reported above when I explicitly select Chinese in the list of languages (instead of system) and restart QField.

**Comment by nirvn** [comment]
@zhuwq75 , confirmed, thanks, investigating.

**Comment by nirvn** [comment]
@zhuwq75 , can you try the QField APK in this PR (https://github.com/opengisch/QField/pull/4955) to confirm the issue has been fixed? 

Big thanks for reporting this, we were completely unaware of this serious regression.

**Comment by zhuwq75** [comment]
@nirvn, Thank you. I have tried the QField APK in this PR (https://github.com/opengisch/QField/pull/4955). This issue is partly resolved, but there are still some menus show in Englilsh in the Home menu. 
![微信图片_20240115204547](https://github.com/opengisch/QField/assets/155275975/4e0eb8b9-8895-4ce4-a84b-3e8f392de239)

**Comment by zhuwq75** [comment]
@nirvn, Thank you. I have tried the QField APK in this PR (#4955). This issue is partly resolved, but there are still some menus show in Englilsh in the Home menu.






-----原始邮件-----
发件人:"Mathieu Pellerin" ***@***.***>
发送时间:2024-01-15 20:12:22 (星期一)
收件人: opengisch/QField ***@***.***>
抄送: zhuwq75 ***@***.***>, Mention ***@***.***>
主题: Re: [opengisch/QField] The QField user interface language can not be changed with the system language (Issue #4953)






@zhuwq75 , can you try the QField APK in this PR (#4955) to confirm the issue has been fixed?

Big thanks for reporting this, we were completely unaware of this serious regression.

**Comment by nirvn** [comment]
@zhuwq75 those will be fixed in QField 3.2, in the meantime we will have to live with that sightl inconvenience.

**Comment by nirvn** [comment]
@zhuwq75 , to share a bit more, this is how QField 3.2 menu looks like:

![Screenshot_20240115-205342](https://github.com/opengisch/QField/assets/1728657/139affa7-48a8-40e5-82b0-7cdf08009403)

As you can see several menu items have lost their labels and were relocated al into a top action bar. These strings being gone, they were not available to be backported to QField 3.1.
