### ISSUE TITLE
QField Android Build Custom Modification 

### ISSUE THREAD

**Issue by ajithandro** [opengisch/QField#4962]
### Done So far
Based on the Android Build documentation, followed the below Docker build procedure and Successfully got the Android Debug Version of the APK File
### Using a docker image

A simple script helps build everything by using a docker image.

```sh
triplet=arm64-android ./scripts/build.sh
```
### Need to Know
Can we change the following things, If Yes please share how and where we can change those things.
- APP_NAME 
- APP_LOGO
- APP_PACKAGE
- Production Build - This Docker CMD gives only the Debug Version of the Application 

### Clarifications
1. I can see this information **(app_name, app_logo, app_package, build_type)** in `build-vcpkg.sh` file, Are changes with this file enough, else we need to change somewhere?
2. Are there any Options there to provide this information in Docker CMD itself to Prepare the Application Build?

Thanks

**Comment by m-kuhn** [comment]
the best reference for this is the current release pipeline

https://github.com/opengisch/QField/blob/c9ead83/.github/workflows/android.yml#L174

any pull request to improve the documentation will be very welcome
