### ISSUE TITLE
Unable to Save Changes

### ISSUE THREAD

**Issue by abdullamuthana** [opengisch/QField#4976]
### Describe the issue
[I have multiple layers and some of these layers when I try to add a feature or even try to edit the feature that is already added it says " Unable to Save Changes".]

### Expected behavior
[A clear and concise description of what you expected to happen.]

### Observed behavior
[when I try to add a feature or even try to edit the feature that is already added it says " Unable to Save Changes".]

### Screenshots and GIFs
![Issues](https://github.com/opengisch/QField/assets/63540100/ada2f686-622a-4951-a4ee-eb27ea3dd416)

test file
[test.zip](https://github.com/opengisch/QField/files/14001061/test.zip)

### Desktop (please complete the following information)
 - QFieldSync Version [3.1.9]

### Mobile (please complete the following information)
 - OS: [e.g. Android 12 and Android 13]
 - QField version: [ 3.1.9 f2829b]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No]

There was no issue with the same file but suddenly this issue happened, and the same file worked fine with other Android OS, btw the same file also worked fine with IOS ( iPhone etc.. )

![photo_2024-01-21_12-37-00](https://github.com/opengisch/QField/assets/63540100/819bbb77-1cfe-4642-be15-87ca12f02eca)
![photo_2024-01-21_12-36-54](https://github.com/opengisch/QField/assets/63540100/cb79c5fa-bbbe-454d-897c-827c0a37c4c1)

**Comment by m-kuhn** [comment]
Can you click the message bubble on the top right and check if there is meaningful information?

**Comment by abdullamuthana** [comment]
> Can you click the message bubble on the top right and check if there is meaningful information?


https://github.com/opengisch/QField/assets/63540100/254f7188-cae0-47de-903e-43ad05b25407

this is what i got

**Comment by m-kuhn** [comment]
Have a look at the error message "Could not convert attribute "X" to type Real". It looks like it is trying to set a value for the field X that is not a (floating point) number, probably some text.

**Comment by abdullamuthana** [comment]
> Have a look at the error message "Could not convert attribute "X" to type Real". It looks like it is trying to set a value for the field X that is not a (floating point) number, probably some text.
> 
> This is a project configuration question, nothing that could be fixed in QField.

but same project file work with iPhone and some other android devices why ?

**Comment by m-kuhn** [comment]
Please check the fields with the name "X" and "Y" for the values, do they contain something that is convertible to a number?

**Comment by abdullamuthana** [comment]
Actually, it has a default expression from QGIS that counts the coordinate for X ( format_number($x,6) ) for Y ( format_number($y,6) ), and the type of X, Y fields are Decimal (double), i don't know why the issue occurred on some devices while there is a lot of other devices that use the same version of Qfield and the same project file don't have any issue, btw i still having the same issue till now and i did not figuar out the issue

**Comment by nirvn** [comment]
@abdullamuthana , it must have to do with device locale. Using format_number transform the number into a string with a decimal and thousand separator characters that might not be compatible with the double field attribute.

Replace format_number() with round(), it'll work everywhere.
