### ISSUE TITLE
Localised datasource basemap cannot be displayed

### ISSUE THREAD

**Issue by geogeek11** [opengisch/QField#4993]
I have created a project containing a basemap layer ( mbtile created using Qgis) storeded in a localized datasource path, then converted it to a new qfield cloud project.
I have also put the same basemap mbtile file in this path `<drive>:/Android/data/ch.opengis.qfield/files/QField/basemaps` as described in [docs](https://docs.qfield.org/how-to/outside-layers/?h=basemap)

But the basemap is not displayed in Qfield mobile app, an error is displayed in the logs saying `Caught a coordinate system exception while trying to transform a point. Unable to calculate line length.`

The Qgis project is using the projection EPSG:32630 the basemap mbtiles project is 3857 and cannot be reprojected to another projection, this mbtile was working well when using the cable transfer without using localized datasource when placing the basemap in the same folder as the project.

![WhatsApp Image 2024-01-29 at 13 42 37](https://github.com/opengisch/QField/assets/7670475/7741b4d0-bb15-43b4-8efd-a38cdabcdcc7)
![WhatsApp Image 2024-01-29 at 13 42 37(1)](https://github.com/opengisch/QField/assets/7670475/0d674a2c-ef0a-4caa-917f-127a5b8f0e30)

### Desktop (please complete the following information)
 - OS: Ubuntu 22.04
 - QGIS Version : 3.34.3
 - QFieldSync Version : v4.7.0

### Mobile (please complete the following information)
 - Device: Samsung A71
 - OS:Android 13
 - QField version: f2829b v3.1.9

### Additional information
* Problem can be reliably reproduced, doesn't happen randomly:  Yes
* Problem happens with all files and projects, not only some files or projects: Yes

Qfield Cloud local instance.

**Comment by nirvn** [comment]
@geogeek11 , while the error message might be linked to the underlying issue, I don't think it's directly related.

I notice your scale bar is broken too, unknown. Why is that? 

Can you take a screenshot of your sidebar legend to see the validity status of your layers?

**Comment by geogeek11** [comment]
@nirvn  Thank you for your swift response

this the Layers panel, I'm available for any information, I really appreciate your help.

![WhatsApp Image 2024-01-29 at 14 48 37](https://github.com/opengisch/QField/assets/7670475/d76199f3-5df7-49c3-99ad-fc92a49a33b0)

**Comment by nirvn** [comment]
@geogeek11 , the basemap layer is font satellite right? What happens if you long press that layer and click on the zoom to layer button?

Can you try to do a USB cable transfer of the project with the dataset not handled as a localized basemap?

I'm suspecting the issue might be projection related more than localized paths.

**Comment by geogeek11** [comment]
I have loaded the same mbtiles file with cable with no localized data source configuration and it works.

I have made a test with live OSM basemap just to check the extent when I click on zoom to extent, it zooms to the whole world extent

**Comment by geogeek11** [comment]
> @geogeek11 , you've tried USB cable, with QField 3.1.9, today ?

Yes, this morning, this is a screenshot of the basemap, I had the same error in the logs but only once, which may mean that the error is not really related directly.

![WhatsApp Image 2024-01-29 at 15 17 09](https://github.com/opengisch/QField/assets/7670475/ccdde625-782f-45f7-87b8-0d67a8ac7c41)

**Comment by nirvn** [comment]
@geogeek11 , what happens if you click on the "zoom to layer extent" by long pressing on the fond_satellite_1_15 localized basemap layer through the layer properties.

**Comment by geogeek11** [comment]
I get zoomed to the whole world extent

![Uploading WhatsApp Image 2024-01-29 at 15.23.58.jpeg…]()

**Comment by nirvn** [comment]
@geogeek11 , alright, well, I think the only way forward now is for you to share your cloud project with me (user email mathieu@opengis.ch) and send me the localized mbtiles (via email or Dropbox link). I'll have a look.

**Comment by radim-ek** [comment]
Same problem here. Can I send a project + base map too?

**Comment by nirvn** [comment]
Issue confirmed, thanks.

**Comment by geogeek11** [comment]
@nirvn Please is there any timeline when this issue will be fixed as there is no workaround to use basemaps with a qfc project.

**Comment by nirvn** [comment]
@geogeek11 , I'm not quite sure, the problem (partly) lies in upstream QGIS. 

There's a workaround though. Load your mbtile datasets via the gdal raster provider, through this UI:

![image](https://github.com/opengisch/QField/assets/1728657/6a4a8471-9d02-4cdd-9f25-e0f4d9ee06b3)

That properly handles mbtiles put in a localized path.

**Comment by nirvn** [comment]
Fix on the QGIS front is here: https://github.com/qgis/QGIS/pull/56296

**Comment by geogeek11** [comment]
> @geogeek11 , I'm not quite sure, the problem (partly) lies in upstream QGIS.
> 
> There's a workaround though. Load your mbtile datasets via the gdal raster provider, through this UI:
> 
> ![image](https://private-user-images.githubusercontent.com/1728657/303899422-6a4a8471-9d02-4cdd-9f25-e0f4d9ee06b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTgyNjgsIm5iZiI6MTcwNzgxNzk2OCwicGF0aCI6Ii8xNzI4NjU3LzMwMzg5OTQyMi02YTRhODQ3MS05ZDAyLTRjZGQtOWYyNS1lMGY0ZDllZTA2YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMDk1MjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjY2ZTJiYWI2YzMzYzU1YzllYzRhMmI2MTM1MGE2N2EwNTRlMzBmNDdhYTVjNzI1YzU1ZmRjMDk2YTg2MGEyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2Q7wwTq7OiWnfOjzxUa6wa1uJ_hmMCl4VR_RSfTKUjU)
> 
> That properly handles mbtiles put in a localized path.

I have tested this solution in qgis linux and qgis windows and it did not work, so should I wait for Qfield Cloud and Qgis, and qfieldsync next releases ?

**Comment by geogeek11** [comment]
This issue is not fixed , I have tested using the project that I have shared with @nirvn, but the same issue has remained.

I have tested using :
    OS: Ubuntu 22.04
    QGIS Version : 3.34.4 and 3.36.0
    QFieldSync Version : v4.7.1
   QfieldCloud Version : v0.25.0

**Comment by nirvn** [comment]
@geogeek11 , you'll have to wait until QField 3.2 is released (very soon) and QFieldCloud is updated (by end of next month). Fixes haven't reached production yet.
