### ISSUE TITLE
Data not saved if cursor does not go to another field

### ISSUE THREAD

**Issue by gnerred** [opengisch/QField#50]
When entering data on a new or existing object, the data of the last field edited is not saved if the cursor remains in it. To save it, the user has to tap into another field after having entered the data of the last field.

**Comment by m-kuhn** [comment]
After 2 hours of unsuccessfully trying to fix this problem yesterday, I just had the proper idea.

https://github.com/opengisch/QField/releases/tag/release-0.7.3

**Comment by gnerred** [comment]
Thanks a lot :O)
