### ISSUE TITLE
QField custom fonts

### ISSUE THREAD

**Issue by jancabaj** [opengisch/QField#5002]
Custom fonts are not displaying in QField.

I copied fonts from windows to my android device :/Android/data/ch.opengis.qfield/files/QField/fonts
I already tried to reinstall QField or delete cache.
I'm using latest QField app on android 13 (Motorola G54)
QGIS stable version 3.28.15 on win11

Currently I have two projects on QField cloud and I tried to create new one just with one new layer to try out but neither of them is displaying correct font.

I just found out that font is displaying correctly if I import project to device from ZIP.

**Comment by nirvn** [comment]
FYI, here's the problem: when QFieldCloud packages a given project, it will save the project to make it ready for field work. Since the server doesn't have the custom fonts, the saved project on the server reverts back to a font that's available on that system.

**Comment by nirvn** [comment]
This is an upstream issue with QGIS which should be addressed soon (https://github.com/qgis/QGIS/pull/59145)
