### ISSUE TITLE
qfield does not start local qfc project

### ISSUE THREAD

**Issue by Forstrevier** [opengisch/QField#5003]
qfield does not start a local qfc project. The qfc project was downloaded from the qfc server without errors. It is then displayed as "locally available". But when I tap on it, the project does not start, but the project is downloaded again and again only from the qfc-server.
Tested with qfc 0.24.0 and 0.23.2
Tested with qfield 3.1.9 - Borneo

**Comment by SeqLaz** [comment]
Could you try with new packager, you can find more information about this optimized packager at: https://docs.qfield.org/get-started/tutorials/get-started-qfc/#enhance-your-project-with-the-optimized-packager

Try synchronizing your project using this new functionality. To do so, please navigate to the Settings of your project and make the changes to the packager.

**Comment by Forstrevier** [comment]
No matter which packager I set, the error still occurs.

Is it possible to view a log file for Qfield on Android? The error message "failed to get latest package data" is not very informative.

**Comment by SeqLaz** [comment]
I recommend attempting to resolve the issue by reinstalling the QField application. This may help to address any underlying issues causing the problem.

**Comment by suricactus** [comment]
> No matter which packager I set, the error still occurs.
> 
> Is it possible to view a log file for Qfield on Android? The error message "failed to get latest package data" is not very informative.

You can check what is going on in the message log and also look at the applicaiton output during downloading. Do you experience the same problem on non-on-premise installation?
