### ISSUE TITLE
QField unresponsive after stylus editing

### ISSUE THREAD

**Issue by Paul-Losse** [opengisch/QField#5010]
### Describe the issue
After using the 'split' tool or 'fill ring' tool with a stylus QField then becomes unresponsive when tapping on the screen with a finger (cannot select feature) or panning the map with one finger 

### Reproduction steps
1. Create a project with a geopackage polygon layer and import to QField
2. Create a polygon
3. Split the polygon or create a ring using a stylus
4. Select a feature by tapping on the feature or move the map using a finger

### Expected behavior
Once editing is complete, it is then possible to move the map or select a feature using a single finger

### Observed behavior
After editing a polygon using a stylus, it is then not possible to select a feature by tapping on the screen using a finger or to pan the map using a single finger. Using two fingers works to pan the map. The stylus can still be used to pan the map and select features. Correct functionality can be restored (temporarily) by closing QField and then re-opening the project. Note that this is an intermittent problem. Often it is possible to do several edits before the problem re-occurs 

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.34.1
 - QFieldSync Version 4.7

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab Active 3
 - OS: Android 13
 - QField version: 3.1.9- Borneo (f2829b v3.1.9

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: No - intermittent but normally occurs after editing for a while 
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by bsaglio2001** [comment]
Hello,

I reproduce exactly the same odd behaviour on my tablet ; QFIELD 3.1.9 / QGIS PROJECT 3.28.15 / Tablet Galaxy Tab Active3 /Android 11 / One UI 3.1

Please note that ;
- Finger touch is still available on buttons (zoom +/-, layer panel, search bar...). It seems that finger touch is only blocked inside the map canvas.
- When editing again without stylus, the target icon is located at the last position of the stylus. With previous versions of QFIELD (at least 1.8 and 2.7) this target was automaticly moved to the center of the screen... Much more intuitive !

**Comment by Paul-Losse** [comment]
Yes, this is exactly the behaviour I'm experiencing with the same tablet. A solution would be very welcome!

**Comment by bsaglio2001** [comment]
The problem is still unsolved... And it seems that this other ticket refers to the same issue ;

https://github.com/opengisch/QField/issues/4919

**Comment by violetlatch** [comment]
I also reported this issue a while back. When using the stylus (Galaxy Tab Active 3) the bookmark dialogue comes up, after which I cannot select anything using the stylus. I can move the map around with the stylus but not select anything. I cannot move the map with my finger. This seems to have something to do with the size of the stylus - if you don’t use the stylus at all, then everything works as it should.

**Comment by nirvn** [comment]
@violetlatch , could you try to see if the APK in this PR (https://github.com/opengisch/QField/pull/5107) improves the situation?

**Comment by lp-dj** [comment]
@nirvn @violetlatch  I hope it's okay if I get myself involved.

I've been an enthusiastic QField user for many years. But from the beginning my biggest problem has been the unfortunately quite error-prone stylus usage. I would be happy if I could help here as a beta tester.

I have tested the APK, unfortunately it doesn't seem to solve all the problems yet.

Here is an adb_log of my attempt: 
[adb_log.txt](https://github.com/opengisch/QField/files/14695380/adb_log.txt)

(Samsung Galaxy Tab Active Pro, Android 11, One UI 3.1, Bee Farming Sample Project)

As you can probably see from the log, at first I had problems with the stylus being recognized as such (this hapstyluss more often). Once I was able to draw with the stylus, it worked very well. However, after that many interactions with the finger on the canvas no longer worked (selecting objects an so on, see comments above).

Please let me know if I can help with further information.

**Comment by ollieprudden** [comment]
@nirvn @violetlatch 
The APK seems to entirely sort the issue for me - (Samsung Tab S7, android 13, One UI 5.1.1)
I have the current Qfield release open at the same time the beta version you linked above.  
In the current Qfield release the stylus is pretty much not working at all from start-up, in the beta version the stylus and finger work completely as I would expect.
I'm afraid I'm not familiar with how to generate a adb_log but can look it up if that would be helpful.

**Comment by lp-dj** [comment]
So it's 2:1 here for "Problem solved" versus "Problem persists"?

Similarity of the leading side: Android 13 with One-UI 5.x?

Could my older Android version be the problem?

**Comment by ollieprudden** [comment]
The 3.20 update hasn't changed the issues for me.

**Comment by nirvn** [comment]
@lp-dj , @ollieprudden , can you try the APKs in this PR: https://github.com/opengisch/QField/pull/5135#issuecomment-2014966925 and report whether things are better?

**Comment by lp-dj** [comment]
@nirvn Now we are talking, works like a charm :heart_eyes:

Thank you for your quick response! When is the next official release including this update? Can hardly wait for it! ;)

**Comment by nirvn** [comment]
@lp-dj , happy to hear this -- can you try to "break" this QField build? Go wild, do measurements, digitizing, etc. and let me know if you spot any _regressions_. Thanks.

**Comment by ollieprudden** [comment]
Hi - that version does work for me, the same as the previous beta so no problems with finger or stylus entry.  It does seem to have reverted to another problem that I had before which is that the cursor returns to the centre of the screen and adds the final node there after any digitising / splitting is completed which means hat the object being digitised gets a 'spike' added to it with the last node on the screen centre, or objects being split get an extra split line from the last intended split line node to the centre.

**Comment by lp-dj** [comment]
@nirvn Good that you remained skeptical. And sorry that I was apparently too hasty.

I tested again in more detail for a while and tried to go wild, as you said ;)

In fact, after some time the following problems occurred again (sorry for the bad news):

- no more panning the map by finger, only zoom gestures work
- no selection of objects by finger possible, more rarely it does not work even by stylus or needs some attempts (and sometimes switching back and forth between navigation and digitizing mode)
- on the other hand, when using the attribute form, the operation via stylus failed from time to time (e.g. selecting an entry from a reference list, here it helped to cancel the input and restart it with a finger)
- I also had the situation that the canvas could no longer be operated with the stylus (no map movement, no setting of reference points). Here I had the feeling that the app was stuck in "finger mode" despite using the stylus. I could fix this by switching freehand mode on and off again (which, interestingly, was still available for selection)
- probably not specifically relevant for this issue (?), but generally irritating: Cutting a polygon is not possible as long as freehand mode is activated. You can then draw with the stylus. However, it then draws a polygon instead of a line and you cannot complete the process (green checkmark missing).

All in all, it is difficult to reproduce reliably, but the situations described above do occur regularly with intensive use. A reasonably practicable mode appears to be in the tested state: Operating the map canvas and digitizing the geometry exclusively by stylus; operating the attribute form by finger.

Please let me know if and how I can help!

**Comment by nirvn** [comment]
@ollieprudden , the APKs here should fix that issue you are talking about: https://github.com/opengisch/QField/pull/5138#issuecomment-2016478846

**Comment by ollieprudden** [comment]
@nirvn - unfortunately that hasn;t fixed it.

When I first opened the beta version it didn't re-centre the cursor to the middle but did still use the final position of the crosshair as a node when you end the digitising of a shape or perform a split - its very hard to avoid moving the cursor off the last added node without any movement   
 
After a couple of splits to test it I could no longer use finger input.

Now when I re-open the beta version, it always re-centres the crosshair and adds a node at the centre, which seems odd that I can;t get it to behave the way it did when I first installed the 5138 version - I've checked the version and that is the one I'm using.

**Comment by nirvn** [comment]
@ollieprudden , alright, well, the quest to figure out Qt's stylus handling continues :) if you can attach a video demonstrating what you see, it'd be useful.

**Comment by ollieprudden** [comment]
https://github.com/opengisch/QField/assets/162481377/8dc659e3-4374-4441-b475-b2ddd5d1a09b

digitising this object created a node at the cursor location (I didn;t click for a node here)

**Comment by ollieprudden** [comment]
https://github.com/opengisch/QField/assets/162481377/6401146b-27a2-4ad8-a322-ba3199dffee0

Second object (I re-positioned the screen so the cursor was close to the final node i intended to add) - splitting worked as anticipated - i.e. it only split between nodes that I had digitised and not adding a split line to the final cursor position

**Comment by Paul-Losse** [comment]
I tested this morning. It seems to be working perfectly for me now. I can switch between using finger and stylus without problem and after using the stylus the cursor now returns to the centre of the screen after one touch which it wasn't doing before. Many thanks, Paul

**Comment by nirvn** [comment]
@Paul-Losse , that's great news -- have you tried the new drawing-over-image functionalities offered by that PR too (as demo'ed by the screencast in the description)? :) thanks for taking the time to test and report.

**Comment by Paul-Losse** [comment]
I've just tried drawing over an existing photo but unfortunately it caused QField to freeze. The ability to add videos, record a video clip etc is excellent though

**Comment by nirvn** [comment]
@Paul-Losse , interestingly enough, the video (and audio) support has been there for a while, but the UI made it real hard to find as it required a specific attribute configuration. This new UI exposes everything no matter what.

Could you send me the photo that froze QField? I'm not seeing it locally when trying eg photos from the bees demo project.

**Comment by Paul-Losse** [comment]
I tried a few times. QField froze at this point, although it did work on a couple of attempts

**Comment by Paul-Losse** [comment]
Update: having tried a few more times, it often works, but takes a very long time to respond after tapping the tick

**Comment by nirvn** [comment]
@Paul-Losse , excellent feedback, I'm pretty sure I know what's happening then. Thanks

**Comment by lp-dj** [comment]
@nirvn Excellent build, significant improvement! Thanks a lot ;)

I'm a bit late (didn't have my tablet with stylus at hand yesterday to test the new build).

But I can confirm that the linked APK (PR5149) works pretty well, even on my old Android 11.

I've been digitizing, measuring, selecting, etc. for quite a while now. The most important things work really well, including the drawing-over-image functionalities (the only thing I've noticed here is that it takes a relatively long time to save the modified graphics).

Apart from that, I have noticed the following problems:
- there are sometimes situations where Qfield needs a moment to switch between stylus and finger

1. i.e. if I have previously worked with the stylus and then want to select a feature using my finger, this sometimes doesn't work straight away. A second/ third tap then helps quite reliably.
2. The other way around is sometimes more difficult. Sometimes Qfield no longer recognizes the stylus and behaves as if I were using a finger. In contrast to previous versions, however, I always manage to get back to stylus mode somehow by interacting with other UI elements or "wildly" swiping around on the map with the stylus.

- I consider the problems described so far to be relatively minor. It becomes more problematic when you try to change existing geometries with the stylus in combination with freehand mode. Some strange things happen there. But I think we would be leaving the focus of this issue, as QField remains responsive in the current build. We should open a separate one for that at some point.

**Comment by nirvn** [comment]
@Paul-Losse , can you try these updated APKs (https://github.com/opengisch/QField/pull/5149#issuecomment-2021965412) to see if the freeze is gone? Thanks.

**Comment by Paul-Losse** [comment]
@nirvn Much better but there is still a bit of a delay after tapping the tick - around 4-5 secs

**Comment by Paul-Losse** [comment]
When will this version be released? Thanks

**Comment by nirvn** [comment]
@Paul-Losse , expect 3.3 by end of this coming month of May

**Comment by Paul-Losse** [comment]
@nirvn That's great. The APK (PR5149) is working well for me and has solved all the stylus issues I was experiencing
