### ISSUE TITLE
Stakeout precise view - Not showing anymore the position of the receiver

### ISSUE THREAD

**Issue by Catalin75** [opengisch/QField#5021]
![203313452-12bb2420-3418-4aae-bc78-76cd4ddb791a](https://github.com/opengisch/QField/assets/134632643/6d7394e1-5e2a-488b-8210-2b1c7b84f72d)
With latest update (Borneo), the stakeout precise view does not show anymore the position of the receiever, (the blue dot in the image attached). This makes more difficult the stakeout of a feature, which now should be realised through distance and bearing only, without any visual help.

**Comment by nirvn** [comment]
@Catalin75 , could you attach a video capture of what you see on Borneo?

**Comment by Catalin75** [comment]
At this moment I cannot. Yesterday I noticed that, when trying to stakeout a point, the blue dot didn't appear at all, and when I got very close to the point to identify, the trigonometrical circle turned green entirely, for a short moment. Also, the documentation referring to the stakeout on qfield.com says that this is how stakeout should happen (no reference to the dot representing the receiver).

**Comment by nirvn** [comment]
@Catalin75 , just tried with QField 3.1.9  on Android, and I can see the point:

![image](https://github.com/opengisch/QField/assets/1728657/bc47d9b6-551c-4730-b9bb-47cf18138d1b)

Something specific to a project of yours might be at play. You'll need to provide a sample project and a video to facilitate looking into this. Thanks.

**Comment by Catalin75** [comment]
![Screenshot_2024-02-09-14-07-23-712](https://github.com/opengisch/QField/assets/134632643/47847468-e983-4d8b-9031-d38bec126326)
I think I figured out the cause of my problem. When using the tablet Lenovo M10 FHD plus for staking out a feature, I only get the green screen as in the picture attached, without the blue marker. I have to pinpoint that this tablet does not have a built-in compass (magnetometer sensor). Staking out the same point, from the same project,  with a different device, equipped with a magnetometer sensor, results in the appearence of the blue receiver marker (normal functionality).
Also, I have to tell you that using the previous version of Qfield (Amazonia), on the Lenovo tablet indicated, gives the normal functionality of precise stakeout view. 
Many thanks for your answers.

**Comment by nirvn** [comment]
@Catalin75 , that was exactly the kind of details that was needed. Fix incoming here: https://github.com/opengisch/QField/pull/5023

**Comment by nirvn** [comment]
@Catalin75 , if you have a minute, please confirm the regression has been fixed using this test APK: https://github.com/opengisch/QField/pull/5023#issuecomment-1936006677 -- thanks.

**Comment by Catalin75** [comment]
I am really sorry, but until Monday, 12.02.2024, when I will get back to work, I will not have acces to my tablet. 
Thank you very much for your support.

**Comment by nirvn** [comment]
@Catalin75 , no problem, you'll have something to look forward to going back to work ;)

Out of curiosity, what are the way(s) your company is using QField?

**Comment by Catalin75** [comment]
Good morning !
I have installed the test APK 5023 and is working perfectly. Thank you so much for your support.
About your question, I work in a local public administration unit and I use QGIS and Qfield, along with a RTK Rover/NTRIP subscription, for field measurements and identification of agricultural parcels, roads, real estate. I also create in QGIS different kind of maps and I use it as a .dwg/.dxf viewer.
Could you tell me the aproximate date of the next Qfield update ?
Best regards,
Catalin

**Comment by nirvn** [comment]
@Catalin75 , by end of February, the new version should be out.
