### ISSUE TITLE
Range widget only allows one digit

### ISSUE THREAD

**Issue by jguelat** [opengisch/QField#5036]
### Describe the issue
I'm using a points layer inside a GeoPackage. When I'm using the range widget to enter integer values as attributes, I can only enter one digit. The only solution to enter more digits consists of repeateadly clicking the "+" button to increase the value until a 2 digits number is reached. After that I can enter other digits manually. There is no problem if I use a text widget instead.

### Reproduction steps
1. Create a QField project with a point layer and one attribute (e.g. "id") as integer32 (I'm using QField Cloud).
2. Make sure the attribute will use the range widget (this should be the default).
3. Digitize a new point in QField and try to enter a 2 digits number using the keyboard. It doesn't work.
4. Repeateadly click on the "+" button until you reach "10", then you can add a third digit using the keyboard.

### Expected behavior
It should be possible to enter all values defined in the range widget configuration.

### Desktop (please complete the following information)
 - OS: Windows 10 Pro
 - QGIS 3.28.15 and 3.34.3
 - QFieldSync 4.7.1

### Mobile (please complete the following information)
 - Device: Galaxy Tab Active3
 - OS: Android 11
 - QField 3.1.9 (f2829b))

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: I don't remember having this problem before, but I don't know when this started to happen, sorry.
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

QField Cloud username: jguelat
QField Cloud project: testbug

**Comment by SeqLaz** [comment]
This is not a bug, a better approach is to use the Range > Slider, to reach your numbers quickly.
![QGIS](https://github.com/opengisch/QField/assets/77129293/03aae183-b0ea-488e-96bb-9d563b7f5c63)
![QField](https://github.com/opengisch/QField/assets/77129293/6ae6781a-2e40-47c7-a2d9-ec58d5215309)

**Comment by jguelat** [comment]
Hello!

Thanks for your help! I know the slider setting but it's not efficient if you need a precise number. I'm sorry to disagree with you but I do think it's a QField bug since I can't directly enter a number that is allowed in the widget settings. This is working properly in QGIS.

**Comment by jguelat** [comment]
This is indeed working! Thanks!

This is still quite strange though, since it is working properly in QGIS Desktop even if I don't edit the range.

**Comment by thymaro** [comment]
Thanks for the workaround!

I'd argue this issue is stale and lingering, instead of completed. If there's a possibility to add some kind of warning before packaging, like the potentially incompatible layers with bad encoding do, then that would be great.

**Comment by bsaglio2001** [comment]
Hi there !

I reproduce this bug, in a very intersting way, so let me share this project with you, hoping it could help to fix the problem.

**QGIS 3.34.13** / **QFIELD 3.5.2** / smartphone Motorola g13 **Androïd 14**

The attached project contains just 2 editable layers, both point shapefiles, with : 

- 2 integer attributes (**INT_10** / **INT_100**)
- 2 decimal attributes (**DEC_10_5** / **DEC_20_10**)

On the second layer (**TESTFORMnum02**) no attribute is configured with the range widget and everything works fine.
On the first layer (**TESTFORMnum01**) **INT_100** and **DEC_20_10** are configured with a range widget tool (the two others are still edited as text).

In that case (the first layer) there's a pb editing more than one digit at first for **INT_100**. No problem for the other numeric attributes with just text editing widget.

https://github.com/user-attachments/assets/2985a588-dedb-4926-942e-e778c5f08996

As @jguelat said, the bug only occurs in QFIELD, not in QGIS.

On additionnal remark, the maximum value for **INT_100** slider (ie 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368) was automaticly filled out by QGIS, as this attribute is an integer64. Of course it looks like non sense and the obvious reason why it's not working.

But I can't understand why it dosen't matter for DEC_20_10 (decimal) while it creates this strange bug for INT_100 (int64).

[PROJQF_test.zip](https://github.com/user-attachments/files/19293576/PROJQF_test.zip)

**Comment by SeqLaz** [comment]
> Hello,
> 
> Due to the field is integer 32bit, could you try by stablishing a reduce range?
> 
> ![QGIS](https://github.com/opengisch/QField/assets/77129293/f513e328-0a2a-42fe-8ce4-e5d2845bfeec)
> 
> ![QField](https://github.com/opengisch/QField/assets/77129293/fcd469fe-4e1d-4bc4-bbc3-185ee6d6cd1c) [ ![QField](https://github.com/opengisch/QField/assets/77129293/fcd469fe-4e1d-4bc4-bbc3-185ee6d6cd1c) ](https://private-user-images.githubusercontent.com/77129293/307304463-fcd469fe-4e1d-4bc4-bbc3-185ee6d6cd1c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIzMjAwMjEsIm5iZiI6MTc0MjMxOTcyMSwicGF0aCI6Ii83NzEyOTI5My8zMDczMDQ0NjMtZmNkNDY5ZmUtNGUxZC00YmM0LWJiYzMtMTg1ZWU2ZDZjZDFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzE4VDE3NDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxM2JhMzNkODhlYjQzNDU5NmE3NTJhMDljZTViNmYwM2ZlZTEwM2IxZjVkODEzNTA4OGQ2MTVmNDQ4YWM0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EvFsFS3f2oeEuniFG9XOWag8YPix_TuxYpDizapNkXM) [ ](https://private-user-images.githubusercontent.com/77129293/307304463-fcd469fe-4e1d-4bc4-bbc3-185ee6d6cd1c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIzMjAwMjEsIm5iZiI6MTc0MjMxOTcyMSwicGF0aCI6Ii83NzEyOTI5My8zMDczMDQ0NjMtZmNkNDY5ZmUtNGUxZC00YmM0LWJiYzMtMTg1ZWU2ZDZjZDFjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzE4VDE3NDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxM2JhMzNkODhlYjQzNDU5NmE3NTJhMDljZTViNmYwM2ZlZTEwM2IxZjVkODEzNTA4OGQ2MTVmNDQ4YWM0MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EvFsFS3f2oeEuniFG9XOWag8YPix_TuxYpDizapNkXM)

Hi @bsaglio2001, thanks for the attached project, in the test I did, with the suggestion up there, you should set a range on the maximum and minimum with fewer than 20 digits, which is more than enough to register values up to 99999999999999999999, and allows you to digitize more than 1 step value.

https://github.com/user-attachments/assets/61d6ba52-0338-4188-b999-77be395303fb
