### ISSUE TITLE
Permit making map rotation fixed

### ISSUE THREAD

**Issue by agseaton** [opengisch/QField#5049]
It's currently easy to rotate the map canvas by accident and this makes zooming in and out of the map frustrating.

Two suggestions:
- Allow fixing the map rotation, perhaps via some setting in the menu so as not to clutter the map window.
- Increase the threshold for rotating the canvas.

**Comment by SeqLaz** [comment]
In QField, there exists a feature that enables users to disable touch functionality on the screen, which can be activated as needed to prevent inadvertent inte
![Lock screen in QField](https://github.com/opengisch/QField/assets/77129293/0e62a840-3d02-43e7-882b-6cb77ea2fa85)
ractions

**Comment by agseaton** [comment]
Sure, that's a useful feature to know about, but it doesn't address the issue I'm raising.

To reiterate, the problem I'm referring to is that if the user is trying to zoom in and out of the map using two fingers, this can cause the map to rotate.

I just compared this with the behaviour in Google maps. In that case, the app appears to lock the rotation angle while the user is zooming, which may be another solution to this issue.

**Comment by SeqLaz** [comment]
This functionality may be consider submitting a request and contributing to its development by utilizing the QField Feature Requests platform available at [QField Feature Requests](https://qfield.canny.io/)

**Comment by agseaton** [comment]
Sure, feel free to list this issue there if that helps you track it. I just want to make sure you are aware there is a problem.

I would like to emphasise that, while this is in some sense a feature request, it is also basic functionality that is causing friction for users of this software.

**Comment by SeqLaz** [comment]
Hello @agseaton, I wanted to ensure that this idea is being considered for future implementation
