### ISSUE TITLE
Partial visualization of data with new QFIELD version (no problem in QGIS)

### ISSUE THREAD

**Issue by L10ns** [opengisch/QField#5056]
### Description
After installation of new version of Qfield, I show just some part of data (geopackage and shapefile files) on project of the device. Mostly of the data are missed. Otherwise I can see all data on Qgis (PC), without any problem.

### Reproduction steps
1. Open Qfield project on the device
2. Make data visible on the map
3. On the project, just some few data are visible.
4. Open attribute table of the data: it shows only the data are visible on the map

### Expected behavior
See, work, add and modify data (shapefiles and geopackage files) of the project.

### Observed behavior
See few data on project. See all data on Qgis (PC). The few data in Qfield can modify or add.

### Desktop
 - OS: Windows
 - QGIS Version 3.34.4 LTR
 - QFieldSync Version 4.7.1

### Mobile
 - OS: Android 13
 - QField version: 3.1.9 - Borneo (f2829b v3.1.9)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@L10ns , did you accidentally enable the clip by area of interest option in the project properties' QField panel while preparing your project in QGIS? Sounds like it.

**Comment by nirvn** [comment]
Fixed in the next version of qfieldsync to be released this week.

**Comment by L10ns** [comment]
> @L10ns , did you accidentally enable the clip by area of interest option in the project properties' QField panel while preparing your project in QGIS? Sounds like it.

Sorry nirvn for my late answer.
No, there isn't any option enabled. One day Qfield was able to read all my geopackage, the day later no.
I tried to erase all project and data on my device, created new one and save all data again.
Nothing change.
Last week, Qfield has shown all data as in the past, without any hidden data, but now it's worse: I can't see any data except some of them. In Qfield the attribute table of a geopackage called "Notes" is without any data. In QGIS, the same geopackage is filled by 60 points and data. If I copy the geopackage from QGIS to Qfield with QfieldSync, nothing change....
