### ISSUE TITLE
The web view/attachment widget is not working in QField.

### ISSUE THREAD

**Issue by gioman** [opengisch/QField#5057]
see also https://github.com/opengisch/QField/issues/1811#issuecomment-1956284385

### Describe the issue

The web view/attachment widget is not working in QField.

The configuration for the field/attribute is:

`attachment > web view`

and the field is filled with an URL that point to a photo in jpg format. The photo shows fine in a QGIS form, but does not show in QField.

### Screenshots and GIFs

![_20240226_110330](https://github.com/opengisch/QField/assets/1951107/a42f9af2-254f-4786-9262-4c0e85bdb87c)

![image](https://github.com/opengisch/QField/assets/1951107/8e79ffc3-0d88-46f1-a60d-a7849aa53cef)

### Desktop (please complete the following information)
 - OS: [e.g. Windows ] Windows 11, Ubuntu 22.04
 - QGIS Version 3.28.15
 - QFieldSync Version: not used
 - 
### Mobile (please complete the following information)
 - Device: all
 - OS: [e.g. Android 11]
 - QField version: 3.1.9

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: probably true since a while
* Problem can be reliably reproduced, doesn't happen randomly: yes
* Problem happens with all files and projects, not only some files or projects: yes

**Comment by bsaglio2001** [comment]
Hello,

I reproduce the same issue on different android tablets in my company (Galaxy Tab Active 3 - Android 12 / Galaxy Tab Active Pro - Android 11) with QFIELD 3.1.9.
The fact that surprises me the most is that the issue seems to appear only in specific old projects, initially configured with QGIS 3.10. 
When recreating a new project in QGIS 3.28.15 with exactly the same SHP layer and the same form parameters (attachment, path relative to project...) then it works !

**Comment by lp-dj** [comment]
I recently had a similar case. In my case it was the separator in the folder path. Do you use the forward slash "/" or the backslash "\"?

If I remember correctly, QGIS works with both variants (may depend on your OS!?), but QField only works with the forward slash "/", e.g. "DCIM/filename.extension".

**Comment by nirvn** [comment]
@gioman , I can't replicate this issue on my end, even when setting the attachment to web view (instead of image or none). If you have a small project you can send me, I'd be happy to look into this.

**Comment by gioman** [comment]
> @gioman , I can't replicate this issue on my end, even when setting the attachment to web view (instead of image or none). If you have a small project you can send me, I'd be happy to look into this.

@nirvn here you go

[teste.zip](https://github.com/opengisch/QField/files/14499363/teste.zip)

**Comment by nirvn** [comment]
@gioman , ah, you were referring to remotely hosted images on http(s) servers. I don't think this ever worked before right?

In any case, a fix for displaying those images ( i.e. read-only) support has been added here: https://github.com/opengisch/QField/pull/5078

**Comment by gioman** [comment]
> In any case, a fix for displaying those images ( i.e. read-only) support has been added here: #5078

@nirvn thanks! I think I commented in another ticket about the possibility to upload photos to a webdav endpoint... that would really be a big improvement considered the pain of having to manually upload/move the photos.

**Comment by nirvn** [comment]
@gioman , you are most welcome :) and yeah, webdav is an enhancement worth considering. Crossing fingers the community will step up with some support for it to happen :)

**Comment by gioman** [comment]
> Crossing fingers the community will step up with some support for it to happen :)

I that comment I expressed my interest in joining the effort.

**Comment by bsaglio2001** [comment]
Hello,

I've just elaborate new crash tests, and the result is a little bit weird, but interesting !

Please find attached two similar QGIS projects, referencing the same GPKG layers.

[TEST_BUG_PHOTO.zip](https://github.com/opengisch/QField/files/14508334/TEST_BUG_PHOTO.zip)

In the first one (**TEST_BUG**) I've kept the form as defined by my collegue (with many default values, some of them being uncorrect). Moreover, the QFIELD properties of the editable layer (Le_Vigeant_DecouverteCadavre) is supposed to title the pictures with explicite '.jpg' extension.
In this case, the picture attachment on Photo1/2/3 fields doesn't work on QFIELD 3.1.9.

In the second project (**TEST_NO_BUG**) I've reconfigured a new form, and I've specified '.{extension}' for naming pictures in QFIELD. In that cas, every thing works fine with QFIELD 3.1.9 !

Note that both projects work fine in QGIS Desktop.

My intuition is that QFIELD 3.1.9 is much more sensitive than before, and a slight error in the form configuration could create weird errors that QGIS ignores but QFIELD doesn't.


Hope it could help.

**Comment by gioman** [comment]
@nirvn feedback has been left, not stale.

**Comment by nirvn** [comment]
@gioman , good reminder :) can we close this PR as the issue filed by you here has been fixed, correct?

**Comment by gioman** [comment]
Ah yes, I also forgot about the PR :)
