### ISSUE TITLE
Add Exif.GPSInfo.GPSImgDirection to builtin camera

### ISSUE THREAD

**Issue by diegstroyer** [opengisch/QField#5059]
### Describe the issue
[A clear and concise description of what the problem is.]
I need to know GPS direction from phto taked with QFIELD, I used Exif.GPSInfo.GPSImgDirection, but not works into QFILED, into QGIS works. Another function works well in both, Exif.Image.Orientation, returns values 0 and 1 into two systems.

### Reproduction steps
1. Create a widget with exif(@project_folder + '/' + "path", 'Exif.GPSInfo.GPSImgDirection'), and check apply value on update. Linked into field "ORIENT"
2. create files for QFIELD and charge the project into
3. Take a photo and save it into the qfield's project form

### Expected behavior
When save the photo, "ORIENT" should take the GPS orientation into field "ORIENT"

### Observed behavior
If I pass the projecto to QGIS again, the orientation appears into field without troubles

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.28.13
 - QFieldSync Version 4.7.1

### Mobile (please complete the following information)
 - Device: Xiaomi 10 PRO
 - OS: 13
 - QField version: 3.1.9 (f2829b)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by Ipickedausername** [comment]
I think this is similar to this request : [https://github.com/opengisch/QField/issues/3072](url)

**Comment by m-kuhn** [comment]
Are you using the native camera or not? (See qfield settings)

**Comment by diegstroyer** [comment]
Nop, the native camera is disabled.

**Comment by m-kuhn** [comment]
Does it work if you switch to the native camera?

**Comment by diegstroyer** [comment]
Hi, same result, with additional icon with no GPS into picture image.

How I say before (1rst message), Exif.Image.Orientation works as I expected
(showing 1 or 0).

**Comment by m-kuhn** [comment]
Looks like this:

 - with native camera, the image exif information is removed (by Android)
 - with the builtin camera, the image exif information doesn't contain orientation / magnetometer which is related to the feature request https://github.com/opengisch/QField/issues/3072 (thanks @Ipickedausername)

**Comment by diegstroyer** [comment]
Maybe, but the built-in camera contains orientation, I check it with
exiftools and when I pass the project to qgis, ORIENT field is filled by
the correct values when updates the form.

Looks like the function is not recognised properly in qfield, I'm wrong?

**Comment by m-kuhn** [comment]
The builtin camera is implemented within QField, this allows QField to add exif information to images. This functionality does not yet add ``GPSImgDirection``, as QField is missing this information (see https://github.com/opengisch/QField/issues/3072).

**Comment by diegstroyer** [comment]
ok, looks like you say.

Thanks a lot.

**Comment by lp-dj** [comment]
Just for the record: This issue is also related to #2042.

And in @m-kuhn's opinion, we had already developed a "good UI proposal" that "doesn't sound overly complicated" ;)

But a @position_orientation variable as suggested in #3072 would of course be even more elegant and universal! 👍

**Comment by nirvn** [comment]
This is implemented by the non-native QField camera (see https://github.com/opengisch/QField/blob/master/src/core/utils/fileutils.cpp#L209-L213 where we tag an image with Exif.GPSInfo.GPSImgDirection).

Am I missing something here?

**Comment by m-kuhn** [comment]
Probably I was missing something. If that's in the very latest brand new release, probably noone tested with that yet.
Thanks for the correction 😀
