### ISSUE TITLE
Could not open files from OneDrive etc.

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#506]
One Drive is visible in file selector.
But it's not visible under QFieldProjects.
On opening over file selector it sais "File not found"

More infos will follow.

**Comment by marioba** [comment]
@signedav it's not possible to open project from providers like dropbox, google drive etc.
 
With the new file selector, you should see only files that you can correctly open.

**Comment by signedav** [comment]
Thanks @marioba - is the new file selector used for every device? I believe some participants of the workshop have installed the latest RC 3 and still the "standard file selector" where they could open projects from google drive that failed then...

**Comment by marioba** [comment]
The new file selector is in master but will be released in RC4...

**Comment by signedav** [comment]
It's because you get only an uri of the file on opening and cannot get the info from the other files (like GPKG). This is why QField currently needs absolute paths and is not able to handle projects on Google Drive. With the new file selector (published in RC4) will not allow to open these files.
