### ISSUE TITLE
Cursor does not centre

### ISSUE THREAD

**Issue by Paul-Losse** [opengisch/QField#5063]
### Describe the issue
After digitising with a stylus, the cursor does not return to the centre of the screen

### Reproduction steps
1. Open a project in QField
2. Toggle editing on
3. digitise a polygon using a stylus

### Expected behavior
After digitising, the cursor should return to the centre of the screen

### Observed behavior
After digitising, the cursor does not return to the centre of the screen

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.4.1
 - QFieldSync Version 4.7.1

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab Active 3
 - OS: Android 13
 - QField version: 3.1.9-Borneo (f2829b v3.1.9)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

https://github.com/opengisch/QField/assets/77330795/0a4f8819-357b-4e4d-ab69-61fc41105c8d

**Comment by nirvn** [comment]
@Paul-Losse , how are things in QField 3.3.10? Stylus has received some love in recent versions.

**Comment by Paul-Losse** [comment]
Hi Matthieu, 
It's working better than before and is fine, until you need to move the map (for example getting to the edge of the screen), then the stylus stops working. It restarts working after moving the cursor around manually a bit using finger. It would be great if this could be fixed. 

Best, Paul

**Comment by Paul-Losse** [comment]
In fact I notice that this issue is covered in issue 5296

**Comment by nirvn** [comment]
@Paul-Losse , let's close this issue then. Big thanks for the swift feedback :)
