### ISSUE TITLE
Relation Reference-Widget > Option "Show open form button" > shows two Buttons, one out of function(?)

### ISSUE THREAD

**Issue by lp-dj** [opengisch/QField#5067]
### Describe the issue
Recently, two buttons are displayed for the Relation Reference widget in QField as soon as the "Show open form button" option is activated in QGIS: An eye and a form icon. The eye no longer seems to have a function (or I haven't understood it yet).

### Reproduction steps
1. Configure a relation reference widget in QGIS.
2. Activate the option "Show open form button".
3. Open the project in QField and interact with the corresponding field.

### Expected behavior
Previously, after activating the "Show open form button" option, I remember that only an eye icon ![grafik](https://github.com/opengisch/QField/assets/80956612/6e7de28d-1c17-439b-b1bb-8d687dce9266) was displayed, which opened the attribute form of the related feature, right? That was perfectly fine.

### Observed behavior
Now it seems that the form icon ![grafik](https://github.com/opengisch/QField/assets/80956612/08518c09-2172-4a9e-9b69-b5c84b55c091) has been added and has taken over the function of the eye: To open the attribute form of the related feature. If you tap on the eye, nothing happens.

The form icon becomes an edit attribute icon ![grafik](https://github.com/opengisch/QField/assets/80956612/e7a8f3b3-2b2f-4b73-af8e-32ef588e5827) as soon as the edit mode is activated. The eye icon does not change here.

### Screenshots

**QGIS:**
![QGIS_RelationReference_ShowOpenFormButton](https://github.com/opengisch/QField/assets/80956612/d389e75e-d5b6-451d-96c6-437068bbf1b4)

**QField:**
![QField_issue_OpenButton](https://github.com/opengisch/QField/assets/80956612/be8d8dbc-aff3-4643-98f5-64b17444c37f)

### Desktop (please complete the following information)
 - OS: Windows 10 Pro 22H2
 - QGIS Version 3.34.4-Prizren

### Mobile (please complete the following information)
 - Device: various
 - OS: Android 11 upwards
 - QField version: 3.1.9 - Borneo (f2829b)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes, see your sample projects.

**Comment by nirvn** [comment]
@lp-dj , the eye moves the map canvas to focus on the related feature, while the feature form opens the related feature form.

**Comment by lp-dj** [comment]
Ah, ok! Thanks for the clarification @nirvn. I can understand the idea behind it and I like it!

But the function/behavior of the eye icon has changed since version 3.x, right? Was it previously a combined "Pan Map to and Show Form of Related Feature" function of the button that you have now split up or was it previously just the "Show Form" function?

Anyway, two suggestions for improvement to the current situation, if you don't mind:

1) Lack of context sensitivity or feedback to the user: I often use Relation References in context with geometry-less layers. I don't think I'm an exception, am I? In this case, the eye makes little sense. What do you think about displaying the eye only for layers/objects with geometry? Or at least show a short feedback such as "Related Feature has no geometry. Map panning not possible" or something similar.

2) Configuration: Another reason I didn't come across the (new?) eye function was because the option I have to activate for it in QGIS is called "Show open form button". I find it irritating when this check mark brings up a "Pan to Related/ Selected Feature". My suggestion here would be to make the eye independent of this option. Either the eye is always displayed on Related Features with geometry or a separate option is set up for it?

What do you think?

Many thanks and best regards

**Comment by nirvn** [comment]
@lp-dj , done here -> https://github.com/opengisch/QField/pull/5077 , good suggestions.
