### ISSUE TITLE
checkbox widget not represented in latest qfield

### ISSUE THREAD

**Issue by saeri-ims** [opengisch/QField#508]
I am setting a field in a table which should take a yes/no reply. I modify the widget in the attribute table form so that it shows a checkbox. Once i import the project into qfield the checkbox doesn't visualise. 

### Reproduction Steps:

1. create a geopackage layer and define, in its attribute table, a field "has_virus" as integer (length 2)
2. open the properties of the table and set the widget for the field "has_virus" as checkbox. At this point i define the representation of checked and unchecked status as 1 and 0
3. save the file, the project and export for qfield. No errors are issued so far

### Expected behavior:
Open the layer in qfield and find a check box for that specific has_virus field

### Observed behavior:

no checked box

### Screenshots and GIFs

![qfield_checkbox](https://user-images.githubusercontent.com/42073830/54071312-bad10700-4262-11e9-8e50-3b472dad03f3.png)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 1.0.0 rc3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: don't know
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by saeri-ims** [comment]
Added issue on visualising checkbox widget in qfield. Added screenshot for clarity

**Comment by signedav** [comment]
Hi there
Can you please update your QField and test again.
I think this should be fixed meanwhile. Thanks.

**Comment by signedav** [comment]
Since I did not received a feedback and I belief it's fixed meanwhile, I close this issue.
Feel free to reopen it, if it's still pending. Thanks :+1:
