### ISSUE TITLE
Accidently closing attribute form 

### ISSUE THREAD

**Issue by Emmawilsonjncc** [opengisch/QField#5084]
When swiping down on an attribute form in order to reach fields which are at the bottom of the form, you can sometimes close it by accident and lose your data. Is there a way to fix this?

I would like to be able to scroll down the attributes form without accidently closing the form.

Happens on iOS and Android.

**Comment by Ipickedausername** [comment]
I had the same issue. 
I finished enabling the option to display the form on the full screen. 

But indeed, I wondered several times why this action on the screen is triggering the saving (or deleting?) of the feature. 
In my opinion, we have a button to validate the form, this is actually good.

**Comment by Oisin-JK** [comment]
I agree, it is very sensitive and easy to cloise accidentally.

**Comment by Arkon74** [comment]
Sometimes it scrolls very abruptly, sometimes you accidentally close the form and sometimes nothing happens. I agree this is very annoying.

**Comment by nirvn** [comment]
@Emmawilsonjncc , @Ipickedausername , @Oisin-JK , @Arkon74 , thanks for reporting this issue. It somehow slipped through my radar until yesterday. Fear not though, it's been fixed! :wink: 

You can try the APKs here (they will appear ~10 minutes after I wrote this comment): https://github.com/opengisch/QField/pull/5368
