### ISSUE TITLE
Moving add-feature button

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/QField#509]
For field measurements with an external GNSS receiver there is sometimes only one hand free to operate the device/tablet. Furthermore, some of our field measurements are quite continuous. Here no values have to be changed, only Add & Save feature has to be used. It would be helpful to be able to move the Add-Feature button here. For example longpress, then move the button into the desired corner of the screen.

### Observed behavior:

Button is not movable.

**QField version:** 0.11.11 

## Additional information:
Would be an enhancement, not a bug.

**Comment by nirvn** [comment]
@EulenspiegelTill , is this still a valid enhancement? Things have radically changed since 0.11.11 :) 

By 3.3, we can now add points using the volume key

**Comment by EulenspiegelTill** [comment]
@nirvn No you can skip that, the vol button works well. Thanks!
