### ISSUE TITLE
wrong geotag at picture taked by the qfield camera

### ISSUE THREAD

**Issue by SergioCastillo75** [opengisch/QField#5093]
### Describe the issue
Setting up the project before the field job, at the moment to test the camera and taking some  pictures, the geotag always is setting the long coordinate as east (90°) but that should be the west (-90°) 

### Reproduction steps
1. take the picture with the qfield app because  the buid-in phone app not save the geotag even if is on, for information the phone's camera works fine and save the good location outside Qfield
2. send the project to qgis
3. identify the picture

### Expected behavior
the coordinates of reference should be west not east

### Observed behavior
the coordinates reference at the geotag is (east)

### Screenshots and GIFs
![Screenshot_20240314-112316_QField__01](https://github.com/opengisch/QField/assets/142488915/81a9b23d-4462-4a58-939e-56767ac75df1)
the coordinates lat and long at the field are correct 

![Capture du 2024-03-14 11-27-58](https://github.com/opengisch/QField/assets/142488915/519eb095-ac61-4e33-988d-30e6d6ec91aa)
![Capture du 2024-03-14 11-31-36](https://github.com/opengisch/QField/assets/142488915/b7b357bf-0f26-484e-b897-7b9a01324a5f)
The green spot is the location of the real location
The red is the location after the geotag from the picture taked by Qfield

### Desktop (please complete the following information)
 - OS: [Linux]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - Device: [OnePlus HD1911]
 - OS: [Android 14]
 - QField version: [3.2.0-Congo (b2ed1f v3.2.0) Qt6.6.2]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: N/a
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@SergioCastillo75 , thanks for reporting this, it'll be fixed in the next point release (test APKs will pop up in this PR - https://github.com/opengisch/QField/pull/5095 - in the next 10 minutes or so).

Now, trivia question: guess on which side of the prime meridian is the developer of this code living in? :wink:
