### ISSUE TITLE
AttributeError: 'LayerSource' object has no attribute 'tracking_session_active' 

### ISSUE THREAD

**Issue by bakkerss** [opengisch/QField#5096]
I installed version v4.9.0 of the plugin QField Sync today. During working on my project I got the following python error which seems to be realted to the qfield sync plugin. I can't reproduce the exact step that led to this error but I assume the error message would be sufficient information to find the error.

**AttributeError: 'LayerSource' object has no attribute 'tracking_session_active'** 

Traceback (most recent call last):
  File "C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\map_layer_config_widget.py", line 48, in createWidget
    return MapLayerConfigWidget(layer, canvas, parent)
  File "C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\map_layer_config_widget.py", line 152, in __init__
    self.layer_source.tracking_session_active
AttributeError: 'LayerSource' object has no attribute 'tracking_session_active'

Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.28.4-Firenze Firenze, fd0fb72ab3 

Python pad:
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass82\etc\python
C:\Users\SebastiaanBakker\OneDrive - Natuurlink\Documenten
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:\Users/SebastiaanBakker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:\Users\SebastiaanBakker\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:/Users/SebastiaanBakker/Natuurlink B.V/Natuurlink - Documenten/QGIS/Woonstichting Thuis

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - OS: [e.g. Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@bakkerss , could you try to completely remove the plugin than re-install it? That seems to be an out-of-sync plugin issue.

**Comment by nirvn** [comment]
Fixed
