### ISSUE TITLE
Problem with Qfield version3.2.0

### ISSUE THREAD

**Issue by mahmoodi-source** [opengisch/QField#5112]
I have configured the attribute form of my project value relation using a table with no geometry to create the multiple selection field, which is not working in QField version 3.2.0-congo, while it was working in the previous version 2.8.1-insightful perfectly.
 anyone knows what is the problem?

**Comment by nirvn** [comment]
@mahmoodi-source , please share a sample project that showcases this regresion.

**Comment by mahmoodi-source** [comment]
> @mahmoodi-source , please share a sample project that showcases this regresion.

Hi, in the old version of Qfield (2.8.1-insightful), in the attribute form, I had to run an expression ("Verk_ph" =current_value('Verkehrsplanung') for the multipal selection field to work.
So when the update version of Qfield was installed on my phone, I found out that there is no need for the above expression, and it works now when I remove the expression. 
Thanks you.
