### ISSUE TITLE
multiple selection on QField 3.2.0 not working

### ISSUE THREAD

**Issue by mahmoodi-source** [opengisch/QField#5125]
I have configured the attribute form of my project value relation using a table with no geometry to create the multiple selection field, which is not working in QField version 3.2.0-congo, while it was working in the previous version 2.8.1-insightful, perfectly. 
anyone knows what is the problem?

**Comment by suricactus** [comment]
Can you please try to identify which version was the first one experiencing the issue, by trying 3.0.0 and 3.1.0? You can find the versions and downloadables here: https://github.com/opengisch/QField/releaseshttps://github.com/opengisch/QField/releases

**Comment by mahmoodi-source** [comment]
I was using an expression attribute form configuration for the old version of Qfield 2.8.1-Insightful ( "Verk_ph" =current_value('Verkehrsplanung')) to be able to have multiple selections. It turns out that I did not need that expression for the newer version of Qfield (3.2.0-congo). When I removed that expression, it worked perfectly.

Thanks.
