### ISSUE TITLE
After while can't login "Network error"

### ISSUE THREAD

**Issue by EgidijusViko** [opengisch/QField#5130]
### Describe the issue
Problem appear when I connect to VPN. And try login to local it show "Address/api/network error" image added. From first expresion it looks like that some tokkens or what was cached, because after fully unistall application and install everything goes well again.

### Reproduction steps
1. Go on connect to profile. 
2. Download project.
3. Close app.
4. Wait ~30 minute or more.
5. Try again login 
6. And show network error

![image](https://github.com/opengisch/QField/assets/55689250/6d0f9a50-d390-4596-8b50-c79ee2fde4c2)

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - Device: Android 13 Xioami
 - OS: [e.g. Android 11]
 - QField version: 3.20

### Additional information
With older version it can't reproduce this problem but with 3.20 it started.

**Comment by suricactus** [comment]
What do you have in the qfield message log? Looks like you it's more your network connection from your qfield client than other.

**Comment by EgidijusViko** [comment]
It show ssl handshake is unseccfully. Local find can't be find it.

**Comment by EgidijusViko** [comment]
Also it can't be network failure if I reinstall app and everything goes well...

**Comment by EgidijusViko** [comment]
At least now trying it only can login but after that can't push changes and etc.

**Comment by suricactus** [comment]
QField does not keep constant connection to the server, and as you pointed out, uses token based authentication. You have this other level of abstraction as VPN and receive a network error. I have my suspicion these are interrelated. Please try without your VPN software and share your results. 

Also, rephrased message log does not help a lot. There might be additional details in it that bring additional value.

In any case, if you want an in-depth support with your specific issue that is not reproducible for us, please drop us an email at sales [at] qfield.org.

**Comment by EgidijusViko** [comment]
Tested also same problem when try verification with Wi-Fi with can reach qfieldcloud server. But same issue presist. 
Please make note. That if I downgrade app to lower version all problems disspear.

**Comment by suricactus** [comment]
Can you point us to the last version it used to work as you expect and the last one that does not work as you expect? You can test all versions of QField here: https://github.com/opengisch/QField/releases

**Comment by EgidijusViko** [comment]
Atlest at 3.19 version okey, no issue appear.

**Comment by suricactus** [comment]
> It show ssl handshake is unseccfully. Local find can't be find it.

When you experience this QFIeldCloud issue, can you please try to open the changelog and see if it works?

You can do that by going to the top-left menu, About QField, click arrow on Documentation button and select Changelog:
![image](https://github.com/opengisch/QField/assets/2820439/2fc69070-d2b8-49d7-9b53-43507d7e0aff)

**Comment by EgidijusViko** [comment]
[HTTP/0]
https://Hidden.lt/api/v1/deltas/6731fe33-ead6-4948-9cef-efc6cf63f810
/ Network Error.<br><br>SSL hello failed: Could not find locally found CA certificate

**Comment by suricactus** [comment]
What do you use for SSL authority of your secret server?

Can you please confirm this is a problem you also experience with app.qfield.cloud?

**Comment by gounux** [comment]
Hi, I'm facing the exact same issue here, using a custom QFieldCloud instance : `[HTTP/0] https://DOMAIN/api/v1/auth/token Network Error` in the login screen. With version 3.1.9 it is fine, the problem appears starting from version 3.2.

> Can you please confirm this is a problem you also experience with app.qfield.cloud?

The problem does not appear on app.qfield.cloud. It appears on some self-hosted instances (not all) even if all are configured the same

> What do you use for SSL authority of your secret server ?

SSL certificate self-signed, the certificates have been updated but the issue still appears

**Comment by EgidijusViko** [comment]
@suricactus Can reopen this ticket issue still presist. Maybe can said what kind of information be valueble for further investigation. Because at least same issue presist.

**Comment by EgidijusViko** [comment]
Issue still exist please look here more deeper.
