### ISSUE TITLE
Photo resize and JPEG compression rate

### ISSUE THREAD

**Issue by gounux** [opengisch/QField#5160]
# Camera photo resize and compression rate

**Current and suggested behavior**

Currently, QField saves and syncs "raw" photos taken by the camera or other photo app as well as photos selected in the gallery. It could be interesting and useful if QField could resize and change JPEG compression rate of taken photo right after taking it or selecting it from the gallery

**Why would the enhancement be useful to most users**

I think this feature could be interesting for reducing packages size as well as synchronization size and time with the cloud for projects with a lot of photos, thus facilitating the survey process and workflows with QFieldCloud. Especially when working with low network connectivity and bandwidth.

Usually the camera quality of smartphones or tablets used for GIS surveys is not for professional photographers, so most of the time we don't need the 4500x3500 pixel resolution (like it's the case on my low-to-mid range smartphone, taken photos are approximately 5MB in size and I guess it is too big). It is still possible to bypass this by using another camera app (like OpenCamera for instance) and then pick it from the gallery, but it makes the process longer and tiresome

**Screenshots, GIFs and mockups**

It could be two new lines in the QField app's settings :
- max photo size in pixels
- JPEG compression rate

Or even better : those 2 parameters could be set in the QGIS project and synchronized to QField with the QFieldSync / QFieldCloud packaging and synchronization ? :heart_eyes:

**QField Version:** 3.X
**OS and Version:** Android, iOS ?

**Comment by nirvn** [comment]
@gounux , photo size maximum setting is already implemented, check the documentation here: https://docs.qfield.org/how-to/pictures/#maximum-picture-size

As for JPEG compression, if you think it's that useful, feel free to reword the title/description to focus only on that.

**Comment by gounux** [comment]
@nirvn oh okay ! Thank you very much, indeed it helps a lot reducing the photo size and the sync time. Sorry for _not reading the documentation_
