### ISSUE TITLE
Ver. 3.2.2: Browse/Digitize mode-icons not visible on the menu?

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QField#5161]
### Describe the issue
In ver. 3.2.0 the icons are visible and may be clicked. In ver. 3.2.2 they don't appear?

### Reproduction steps
1. Loading the same project on two devices with these two different version installed
2. [Click on the hamburger menu and the two icons/buttons are only visible in 3.2.0.

### Expected behavior
The buttons should be visible in 3.2.2.

### Screenshots and GIFs
Samsung Galaxy Tab Active3, Android 13 (ver. 3.2.0, b2ed1f):
![image](https://github.com/opengisch/QField/assets/10632163/71c15791-9a52-4f71-98b3-1a0adbe91484)

Samsung Galaxy Tab Active4 Pro, Android 14 (QField ver. 3.2.2, 72be17):
![image](https://github.com/opengisch/QField/assets/10632163/7ddce50e-6301-479d-9187-6885b4544f6f)

### Desktop (please complete the following information)
 - OS: Windows 10 Enterprise
 - QGIS Version3.36.1
 - QFieldSync Version 4.9.1

### Mobile (please complete the following information)
 - Device: see above
 - OS: see above
 - QField version: see above

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: yes
* Problem can be reliably reproduced, doesn't happen randomly:
* Problem happens with all files and projects, not only some files or projects:

**Comment by nirvn** [comment]
@9ls1 , is that with a cloud project by any chance? If so the toggle will disappear if your QFieldCloud user role is read-only for a given protect.

**Comment by 9ls1** [comment]
@nirvn Ah, I C (said the blind man). We're testing self-hosted QFieldCloud and I'm slowly getting more familiar with the admin-webpage. I now added Project collaborators (with Editor role), and that did the trick regarding Digitize/Browse. Thanks!

**Comment by nirvn** [comment]
@9ls1 , great.
