### ISSUE TITLE
Opening secondary storage from file selector only opens the opengis.qfield folder

### ISSUE THREAD

**Issue by nicolasmcfadden** [opengisch/QField#518]
[Short description of problem here]

### Reproduction Steps:

1. Open QField
2. Go to Open Project
3. Select Secondary storage

### Expected behavior:

Get access to the entire SD card to look for projects.

### Observed behavior:

Only access to the "ch.opengis.qfield/files" folder and not the entire SD card.

However if I use the phone file browser to find the project file and I select the project file, QField opens it without any problems. If the project is opened this way, it will not later appear in the recent projects the next time

### Screenshots and GIFs

![image](https://user-images.githubusercontent.com/27243743/54357897-20acfc80-4670-11e9-81ca-639a8e839e12.png)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 1.0.0 Release Candidate 5

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] since file browser changes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by zersorger** [comment]
Having exactly the same problem, so I have to store my files on the internal storage to be able to use them.

**Comment by marioba** [comment]
Hi @nicolasmcfadden, 
this is the expected behavior of the file selector. The file selector only shows the application-specific directory (`/Android/data/ch.opengis.qfield/files`) on an external SD card, as it is the only directory for which the app has write access and for the moment we have decided to show only that directory.

**Comment by nicolasmcfadden** [comment]
@marioba thank you for the explanation. However people shoudl be aware that if QField is uninstalled and reinstalled, the projects in that folder will disappear.

**Comment by marioba** [comment]
@nicolasmcfadden thank you for raising that. 
The behavior is documented on the documentation
[here](https://www.qfield.org/docs/project-management/project-selection.html) and we are thinking about a way to show it clearly in the app.

**Comment by 3nids** [comment]
A message when we first open a project at this location?

**Comment by nicolasmcfadden** [comment]
@3nids that's not a bad idea... I'd read the documentation a long time ago and have been fiddling with QField for a long time so I don't go read the documentation anymore... But the other day I did lose my projects by trying new test apks. Wasn't a big deal in my case but could be a problem
