### ISSUE TITLE
Small memory-leak causes QField-crash (and loss of currently digitzed feature)

### ISSUE THREAD

**Issue by koenigherford** [opengisch/QField#5194]
### Describe the issue
When digitizing with a complex qgis/qfield-project (lots of fields, constraints, default values, and photo-attachements) sometimes QField crashes when adding a photo-attachment after pressing the "ok" button in the camera-mode.

This only happens after a lager bunch of collected features. But it happens sometimes a day collecting data. Once there was something like a "cache-overflow"-warning, but mostly the notice was as screenshot below.

After that it seems you have to start QField and the procect again and have to digitize the (lost) feature again -which will cause a new crash when adding a photo-attachement.

After that it seems you have to open the project again and manually close it by using "<" button. 

After starting QField and the project again and collecting the feature again (with same attributes and taking a picture as before)  everything will work for some hours again. So it seems not to be a reason inside the project configuration itself.

Sample-project-download-link (no cloud-project) can be provided outside this platform if you like

![grafik](https://github.com/opengisch/QField/assets/28433436/6bae782d-cce2-405d-a1de-468e47a1eb05)

### Desktop (please complete the following information)
 - OS:  Windows
 - QGIS Version [e.g. 3.36.0]
 - QFieldSync Version [4.9.1]

### Mobile (please complete the following information)
 - Device: [Galaxy Tab Active3]
 - OS: [Android 13, OneUI 5.1.1]
 - QField version: [3.2.2 - 72be17 v3.2.2 QT 6.6.2]

**Comment by koenigherford** [comment]
Yes...
![grafik](https://github.com/opengisch/QField/assets/28433436/bcd77e95-b682-4bdd-8564-b5cc4596977e)

**Comment by koenigherford** [comment]
Issue can be avoided by disabeling "use native camera" as described above

**Comment by m-kuhn** [comment]
Thanks for checking, I think we should switch the default then ...

@nirvn thoughts?

**Comment by m-kuhn** [comment]
> Yes... ![grafik](https://private-user-images.githubusercontent.com/28433436/324725936-bcd77e95-b682-4bdd-8564-b5cc4596977e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTEzNDIsIm5iZiI6MTcxNDY1MTA0MiwicGF0aCI6Ii8yODQzMzQzNi8zMjQ3MjU5MzYtYmNkNzdlOTUtYjY4Mi00YmRkLTg1NjQtYjVjYzQ1OTY5NzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDExNTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOWFkNTRmM2ZkNGIwZTQ0NjhkMDJmNTM2OTVlNWFkMzc0NTNkZjUzMGNmYWRiZWM1ZDg3MDEyMjI4ODlkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HfZg2_iUWPbXItetwwPsSFkX_yK5AgdRc3wLQ5viPpQ)

@SeqLaz IIRC you planned to adjust this documentation (and remove the reference to open camera) did you get to it?

**Comment by SeqLaz** [comment]
@m-kuhn I will add it to the documentation
