### ISSUE TITLE
Read only fields

### ISSUE THREAD

**Issue by nsm91** [opengisch/QField#52]
An attribute set as uneditable on QGIS is still editable in QField. However edit widgets do transfer as check boxes or value maps work in QField, so I think the issue is captive to toggling edit on or off.

**Comment by m-kuhn** [comment]
The fix will be more or less straightforward.
I'll see if I can integrate it in an upcoming project about which improves some aspects of forms (Funding almost there).

It's not a real replacement but in some cases setting the widget type "Hidden" will inherently also make it uneditable.
