### ISSUE TITLE
 URGENT how to add members to the organization payment plan

### ISSUE THREAD

**Issue by sabinananu** [opengisch/QField#5203]
### Describe the issue
In QFieldlCloud I am a Pro user and I currently have a Trial Organization plan with 4 active members (editors, who take the data in the field and upload it to the cloud) and a fifth member who is an administrator, manages the projects and downloads the data (me). In billing under Current Subscription it appears 0 members included. I have requested a storage increase and it already appears in Next subscription with 2 members included. I can't add more members in Billing. I need that when I increase the storage, I can add more members to the Organization plan and make the full payment for the members and the storage together. How can this be done?

### Reproduction steps
1. Go to 'Organization'
2. Click on 'Edit organization' and 'Billing'
3. Scroll down to 'Subscriptions'

### Expected behavior
Be able to add storage and members to Billing - Subscription

### Observed behavior
When you click Change and Next subscription, it only allows you to update storage, not add members

### Screenshots and GIFs
![Captura](https://github.com/opengisch/QField/assets/167850583/53b01315-72d1-484d-8a7d-655784e626ca)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: Windows 10 Pro
 - QGIS Version 3.22.11-Białowieża
 - QFieldSync Version 4.6.0

### Mobile (please complete the following information)
 - OS: [e.g. Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

QFieldCloud username: sabinaproma

**Comment by SeqLaz** [comment]
Hello,

Thank you for reaching out. Regarding the active members in an Organization, they are typically calculated automatically based on their activity within the Organization's projects. In a regular Organization plan, you have the flexibility to add or remove members as needed during each billing cycle.

If you have any specific questions or require further assistance, I recommend opening a ticket with our support department at sales@opengis.ch.
