### ISSUE TITLE
URGENT Problems when applying errors and conflicts

### ISSUE THREAD

**Issue by sabinananu** [opengisch/QField#5205]
### Describe the issue
At QFieldCloud I am a Pro user and I currently have an Organization plan with 5 active members. Yesterday the data was uploaded to the cloud and it was uploaded with errors and conflicts, I suspect it is due to lack of space. Today we have increased the storage and they have uploaded the data to the cloud again, but the errors persist. I have disabled the Overwrite Conflicts option to fix errors manually, but it doesn't work at all well. I try to "apply" the errors and conflicts, but not all of them are applied, some are applied, others are not, or I "apply" again and others are applied and the corrected ones are set to "error". I hit "reapply" and the problem persists.
If I activate the Overwrite conflicts option, the errors are not corrected or applied either.

I have also tried deleting the versions of recent files, leaving the version with empty layers, and uploading the data to the cloud again. But the data continues to be uploaded incorrectly.

When downloading that data to my computer, some layers have duplicate objects and I don't know why.

I need all the data to be uploaded correctly to the cloud and to be able to download it correctly to the computer. Can someone help me with this problem please?

### Reproduction steps
1. [Go to '...']
2. [Click on '...']
3. [Scroll down to '...']

### Expected behavior
I was hoping that by increasing the storage, the data would be uploaded to the cloud correctly, without errors or conflicts.

### Observed behavior
I have disabled the Overwrite Conflicts option to fix errors manually, but it doesn't work at all well. I try to "apply" the errors and conflicts, but not all of them are applied, some are applied, others are not, or I "apply" again and others are applied and the corrected ones are set to "error". I hit "reapply" and the problem persists.
If I activate the Overwrite conflicts option, the errors are not corrected or applied either.
I have also tried deleting the versions of recent files, leaving the version with empty layers, and uploading the data to the cloud again. But the data continues to be uploaded incorrectly.

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - OS: [e.g. Android 11]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (10200993)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

QFieldCloud username: sabinaproma

**Comment by SeqLaz** [comment]
You can retrieve your data from the mobile device by navigating to Settings > Open Project Folder > data.gpkg. Then, use the three dots on the right side and select "Send to..." to transfer your data to your computer. Paste the data into the original layers in the project and re-synchronize the project to QFieldCloud.

Additionally, could you hover over the information icon to see the type of issue you're encountering?
![Screenshot from 2024-04-23 10-07-37](https://github.com/opengisch/QField/assets/77129293/155eca0d-efa2-4ca7-a2b8-211ed3e4ef1e)

**Comment by sabinananu** [comment]
Thank you very much for your help. I suspect that in this way, after copying the data from data.gpkg to the original layers and synchronizing it again with qfieldcloud, the data can then be taken in the field and successfully uploaded to the cloud, without errors or conflicts. Is that so?

**Comment by SeqLaz** [comment]
> Thank you very much for your help. I suspect that in this way, after copying the data from data.gpkg to the original layers and synchronizing it again with qfieldcloud, the data can then be taken in the field and successfully uploaded to the cloud, without errors or conflicts. Is that so?

Yes, that is correct!

**Comment by sabinananu** [comment]
Can you help me with something else?
When I open the data.gkpg layers, the columns appear with numbers, although in Layer Properties > Fields they are still of type string. Is there a way to have data from data.gkpg layers downloaded with the original text instead of numbers?

**Comment by sabinananu** [comment]
I have figured out why columns that should have text have numbers in the data.gkpg layers. It's because in those layers, in Layer Properties > Attributes Form > Control Type > Value Map, the Value column has numbers and the Description column has the text.
It seems that the data is saved in the value column, not the description.
