### ISSUE TITLE
Is it possible to restore full access to files on Android?

### ISSUE THREAD

**Issue by eachuisge** [opengisch/QField#5225]
Not asking for a full step-by-step instruction, but before I embark on the idea I would really appreciate a heads up from anyone who's familiar with the code history.

I'm planning on forking the project and removing the annoying restriction on accessing my files in Android (just for my own personal use, I don't want to interfere with the developer's business model).

A simple "No, there's thousands of changes tied to file access", or "Yes, it's only a few lines" is all I'm after here (unless anyone _wants_ to give a full step-by-step instruction of course...)

I'm assuming this has either been attempted and proven impossible or has already been done somewhere.

**Comment by m-kuhn** [comment]
Hey, this is imposed by Android, or more precisely, Play Store.

You can read more about it here: https://www.opengis.ch/2022/03/05/qfield-users-sit-down-we-need-to-talk-about-storage-access-on-android%EF%BF%BC/

We even build "all access" binaries nowadays. They are downloadable from any action run (choose any recent one from https://github.com/opengisch/QField/actions/workflows/android.yml scroll all the way down to the artifacts and download the corresponding all_access apk). You will have to install them manually, this works fine for now but we've heard that this might change and future versions of Android might completely shut down this functionality.

**Comment by eachuisge** [comment]
> We even build "all access" binaries nowadays. They are downloadable from any action run (choose any recent one from https://github.com/opengisch/QField/actions/workflows/android.yml scroll all the way down to the artifacts and download the corresponding all_access apk). You will have to install them manually, this works fine for now but we've heard that this might change and future versions of Android might completely shut down this functionality.

Wow. Even easier than I thought. Thank you. There was me thinking I'd at least have to delete an "OFF" and replace it with an "ON" somewhere.

The day Android shut that functionality down is the day I finally get a linux phone.

> Hey, this is imposed by Android, or more precisely, Play Store.
> 
> You can read more about it here: https://www.opengis.ch/2022/03/05/qfield-users-sit-down-we-need-to-talk-about-storage-access-on-android%EF%BF%BC/

Bloody Google. I assumed it was a business decision (promote the cloud server), not that I have any objection to that, we've all got to earn a living somehow, but providing an all access version too is really cool. It might be worth promoting that, maybe do a release on F-Droid, if they'll allow it (I don't know what their rules are on that sort of thing).

**Comment by m-kuhn** [comment]
I'd love to see an F-Droid release, there's a discussion (with a link to an F-Droid issue) open.
https://github.com/opengisch/QField/discussions/2706

If someone wants to get their hands dirty on that I am available for technical support

**Comment by eachuisge** [comment]
Absolutely. I'll look into what's needed and see if it's within my skillset (or something I can pretend is in my skillset by frantically looking everything up on Stack Exchange!)
