### ISSUE TITLE
Cannot open srs database error message

### ISSUE THREAD

**Issue by ivankautter** [opengisch/QField#523]
[Short description of problem here]
Upon opening any QField project, logged error message reports "Can not open srs database (/data/user/0/ch.opengis.qfield/files/share/resources.srs.db): unable to open database file" many times.

### Reproduction Steps:

1. Open any project on Pixel 2 running Android Pie

### Expected behavior:

Opening without errors

### Observed behavior:

Error message as described above.

### Screenshots and GIFs

https://user-images.githubusercontent.com/17435854/54454379-9075c280-4716-11e9-936c-57e42726f404.png

**QField version:** [1.0.0-rc5]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by ivankautter** [comment]
Have also observed that error message returns on any refresh of the interface. Zoom in, error. Interact with nav drawer, error.

**Comment by m-kuhn** [comment]
Could you try the apk from pull request https://github.com/opengisch/QField/pull/526 ?

**Comment by veroniqueC** [comment]
I have the same issue (not on all materials), and the repertorie with srs is empty. All is OK when i desinstalled the old version and reinstalled RC5.

**Comment by m-kuhn** [comment]
@veroniqueC that sounds a lot like it could be resolved with #526 
I'm moving forward and merge this. If someone is still affected in the future, please reopen.

**Comment by ivankautter** [comment]
This appears to have fixed the issue.  Thanks for timely update. It saved my field day.

**Comment by m-kuhn** [comment]
Thanks for the feedback. This will help a lot for a stable 1.0
