### ISSUE TITLE
Chose where QField files are saved on the phone

### ISSUE THREAD

**Issue by Dartazen** [opengisch/QField#5231]
To follow up on this discussion : [Android Imported Project Location (add Android > media)](https://github.com/opengisch/QField/discussions/4526) - it would be really useful to add the user's choice of where files are stored.

Regards.

**Comment by m-kuhn** [comment]
This is prevented by Google PlayStore (for security reasons), so it's not something we could do.
Read more here https://github.com/opengisch/QField/issues/5225
