### ISSUE TITLE
2nd tracking restart from the 1st point of the 1st tracking 

### ISSUE THREAD

**Issue by GuyGeneau** [opengisch/QField#5234]
2nd tracking line restart from the 1st point of the 1st tracking line 

### Reproduction steps

1. Start tracking on a layer.
2. Start tracking on a second layer.
3. Stop tracking on one or both layers.
4. Restart tracking on one of the two layers:

When STARTING tracking, not using the RESUME function, the starting point of the tracking is attached to the FIRST point of the previous line.

### Expected behavior
start a new tracking line not attach to the previous one

### Observed behavior
when the use simultaneous tracking, the starting point of the tracking is attached to the FIRST point of the previous line for the others tracking strarted.

### Desktop (please complete the following information)
 - Windows 10
 - QGIS Version [e.g. 3.34.5]
 - QFieldSync Version [e.g.4.9.1]

### Mobile (please complete the following information)
 - Device: [Samsung and Blackview]
 - OS: [e.g. Android 11 and 12]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 2.0.0 (72be17)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [can provide the info]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
Confirmed.
