### ISSUE TITLE
QFieldCloud generating duplicates of basemaps every time changes are pushed

### ISSUE THREAD

**Issue by GiroDiGiiro** [opengisch/QField#5237]
Hello, as soon as a change is made or synchronized with QfieldCloud, the basemap is duplicated which significantly increases my account storage.
I tried to put the basemap in .tif or .gpkg and I have the same problem.
I saw that an issues had been opened here ( [QFieldCloud generating duplicates of basemaps every time changes are pushed](https://github.com/opengisch/qfieldcloud/issues/813#) ) but is closed due to inactivity, and the problem is still there.
If anyone knows of an alternative to avoid this problem, I'd love to hear from you.
I use the community version

**Comment by suricactus** [comment]
@GiroDiGiiro can you please let us know which username and project combination you are experiencing issues with?

**Comment by GiroDiGiiro** [comment]
Hi @suricactus , thanks for your quick reply.
username: victorgiraud
project: all in fact (I have one stored in the cloud currently 'test1')

**Comment by suricactus** [comment]
I never communicated this with you, but in the last QFC version you should no longer experience this problem.
