### ISSUE TITLE
Support for remote geojson

### ISSUE THREAD

**Issue by mecrider** [opengisch/QField#524]
I added a vector layer in QGIS using GeoJSON protocol and configured it to refresh every 300 seconds. I used QFieldSync to package it for QField. When I opened QField, I got: "Cannot open http...(GDAL/OGR not compiled with libcurl support, remote requests not supported.) This is on qfield-android_5_v1.0.0-rc5-armv7.apk.

**Comment by m-kuhn** [comment]
Interesting feature. Please contact us to get an offer.

**Comment by tbarthelet** [comment]
Hi, this would be a great feature instead of having to send shape files to mobile devices.
From what I understand, it seems this could be solved just by adding curl support.
Possible fix mentionned [here](https://github.com/JuliaGeo/GDALBuilder/pull/12) or [here](https://gis.stackexchange.com/questions/322017/missing-wfs-driver-in-gdal-installation).

**Comment by dlutsVMM** [comment]
Hi, we would also be interesseted in this functionality to be able to load GeoJSON's from a webservice in the QField app. Is there any update on the progress of this enhancement?

**Comment by m-kuhn** [comment]
I'm not aware of any ongoing work currently.

**Comment by dlutsVMM** [comment]
Thanks, Matthias so it is safe to assume you cannot access data from an API/webservice in QField unless the webservcies is a WMS/WFS or somebody develops the feature to allow http-requests to API's/webservices to access Geojsons, csv's, GML's, ...?

**Comment by m-kuhn** [comment]
That's my understanding too, qfield currently misses libcurl

**Comment by nirvn** [comment]
This would be a great enhancement to have in QField, and very much achievable provided some sponsors the work to add the missing libcurl in the OSGeo4A SDK.

**Comment by nirvn** [comment]
Today is the lucky day of all who commented here. QField 2.0 will support remote geojson (in fact, any remote dataset supported by OGR). This was a collateral benefit to work done by @m-kuhn to upgrade on build system. Send flowers and love to him.
