### ISSUE TITLE
"all access" APK not available anymore

### ISSUE THREAD

**Issue by vlebert** [opengisch/QField#5240]
Hi

I used to download the "all access" dev apk that allow user to open local project without importing it.

For a while now it is not available anymore on release page but could be found on commit page :

Example : https://github.com/opengisch/QField/commit/2de2814be25c97038efa1455218b2bad76eaae88

![image](https://github.com/opengisch/QField/assets/49779177/90d51075-6adc-4065-824c-0f3a3a034dab)

However, these links are now broken (example : https://sos-ch-dk-2.exo.io/qfieldapks/ci-builds/qfield_all_access-dev-release-2_6-aaa9ed3747add7a2659e3ed3111b48aeccc555d8-arm64-android.apk).

Could you add the "all  acces" apk to release page and/ok fix those broken links ?

Valérian

**Comment by m-kuhn** [comment]
We keep dev apk's only for 3 months, they are still made available for new builds.

**Comment by m-kuhn** [comment]
I don't think we ever released these packages. Can you point to a release, where this was still the case?

**Comment by vlebert** [comment]
Hmm I thought at the beginning they were available through release page but maybe I dreamt.

I think yesterday even recent builds were unavailable but the links are OK today. I keep in mind the 3 month availability so I'll do my own archives :)

**Comment by m-kuhn** [comment]
Well, we certainly did before google disabled this by default. Not sure we did ever after 🧐
Feel free to publish your archive here if you want.
