### ISSUE TITLE
Tabs are not following the selected container.

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#5242]
Hello,

The tabs are not adjusting with the selected container.

I believe that moving the containers to the right or left within the form should also shift the tabs accordingly.

Currently, when I move to the left to access the containers on the right, the tabs do not move, causing some tab aliases to be hidden.

While this is not a critical issue (no critical issues remain for me on the QField app), it affects the overall quality of the application.

https://github.com/opengisch/QField/assets/72577399/919a8495-09f2-4f02-86ea-07e877fd58ed

Thank you.

Desktop
OS: [Windows 10]
QGIS Version [3.36.1]
QFieldSync Version [4.9.1]

Mobile
Device: [Samsung Galaxy S9]
OS: [Android 11]
QField version: [master-dev (14a0be)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No sure]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by suricactus** [comment]
Thanks for the report. Providing a test project will drastically accelerate the speed the development team can identify your issue.

**Comment by Ipickedausername** [comment]
Hi, 

Here are two projects. One for QGIS and the other one for Qfield. 


https://github.com/opengisch/QField/assets/72577399/d1002817-aae8-43d6-9eed-fea511fb68a0

[test_tabs_Qfield.zip](https://github.com/opengisch/QField/files/15367072/test_tabs_Qfield.zip)
[test_tabs_QGIS.zip](https://github.com/opengisch/QField/files/15367071/test_tabs_QGIS.zip)

**Comment by SeqLaz** [comment]
I can confirm that Tabs are not moving accordingly to the current Tab.


https://github.com/opengisch/QField/assets/77129293/27199481-d12c-46c2-a623-17a621a21441
