### ISSUE TITLE
Tracking session is freezing the Qfield App

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#5253]
Hello, 

I have a configured layer with a tracking session enabled.

When I open the project, the form for the tracker layer opens and I cannot close it. The app seems to be frozen.
When I tap on the validate button, nothing happens, and I can't even quit the app by double-tapping the return arrow.

What's very curious is that I don't recall updating the app. It was working yesterday, but today it is not, even on the same project I used yesterday.

This error only occurs on the QField Dev version; it does not happen on the regular QField version.

https://github.com/opengisch/QField/assets/72577399/44073426-27aa-48a8-8350-b1d5f4fddbe0

Desktop
OS: [Windows 10]
QGIS Version [3.36.1]
QFieldSync Version [4.9.1]

Mobile
Device: [Samsung Galaxy S9]
OS: [Android 11]
QField version: [master-dev (14a0be)]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Here is a test project for QFIELD and one for QGIS

[test_track-layer_QGIS.zip](https://github.com/opengisch/QField/files/15367057/test_track-layer_QGIS.zip)
[Test_tracker.zip](https://github.com/opengisch/QField/files/15367058/Test_tracker.zip)

Thank you

**Comment by nirvn** [comment]
@Ipickedausername , thanks for the report and test project, made it super easy to fix.
