### ISSUE TITLE
Add a Signing Certificate for Future Releases

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [opengisch/QField#5265]
Title is self explanatory.  As this app is open source, it may attract android users who have degoogled devices and choose to download the app directly from github.  This is possible on android with [AppVerifier](https://github.com/soupslurpr/AppVerifier).  A signing certificate is used to verify the integrity of release downloads directly from github and would improve user confidence of the download.

Thank you for your consideration.

**Comment by m-kuhn** [comment]
The releases are signed already. What more os needed?

**Comment by shrimprugbysnowowl** [comment]
Thank you for the reply.
I believe you'd need to post the hash of the signing certificate, but ideally in multiple locations to reduce the possibility of tampering.

**Comment by m-kuhn** [comment]
Good idea, let's add it to the readme. This is in git, so not tampered with without noticing.
Can you create a pull request? You can gpg the commit. We will double check that it's correct before merging.
