### ISSUE TITLE
qfield crashes..

### ISSUE THREAD

**Issue by alpagutbeyi** [opengisch/QField#5271]
The file I exported for qfield from qgis 3.36.1 version opens without any problems..

project; It consists of multiple lines and polygons.

1-) by moving the map screen
2-) with scale movement
3-) with positioning button

qfield crashes..

iPhone 13, 17.4.1

**Comment by nirvn** [comment]
@alpagutbey , have you enabled QField anonymized crash reporting? What version of QField are you running?

We'd probably need a bit more for you, eg a sample project with steps to reproduce the crash.

**Comment by alpagutbey** [comment]
> @alpagutbey , have you enabled QField anonymized crash reporting? What version of QField are you running?
> 
> We'd probably need a bit more for you, eg a sample project with steps to reproduce the crash.

thank you for your response..
some layers in the qgis project are not configured to work for qfield.

**Comment by Ipickedausername** [comment]
Hi,

Most of projects use line or polygon layers, and we do not encounter crashes.

QField crashes are highly problematic for developers. They will take your issue seriously if you provide a test project and explain how to reproduce the crashes.
