### ISSUE TITLE
UI improvement on legends

### ISSUE THREAD

**Issue by Ipickedausername** [opengisch/QField#5276]
Hi, 

This proposition is related to the current work done by @mohsenD98  ([https://github.com/opengisch/QField/pull/5275](url))
#5275 

I've been thinking for a while that the left panel in the app could be improved by making all the options related to the layers available and clickable.

Something, more or less, like this:

![proposition](https://github.com/opengisch/QField/assets/72577399/33c93ab5-c172-423f-8e62-61c4c9507822)

What do you think?

I think the left panel could cover the whole screen to provide more space, as there's nothing else we can do when this panel is open.

However, this might make the interface too crowded? In my case, I would find such options very useful, especially being able to open the feature list, disable selection (not currently available), or hide/unhide layers with a simple tap.

Thank you.

**Comment by mohsenD98** [comment]
Hello, thank you very much for the great idea you shared. I'll definitely bring this up with my friends and we'll try to improve it over time. 
If you have any other ideas, please feel free to share them with us. 
Thank you!

**Comment by nirvn** [comment]
@Ipickedausername , this was partly implemented. As of upcoming QField 3.3, an eye icon will be displayed to quickly toggle layer visibility. The collapsed/expanded arrow will also be reactive to click (expanding/collapsing groups and map  layers).

**Comment by nirvn** [comment]
@Ipickedausername , if you feel the implementation satisfies you, please close this feature request. For the other elements, I think it's quite unlikely we'd go into this direction as we're still aiming at keeping the UI as light as possible.

**Comment by Ipickedausername** [comment]
Hi,

Alright, I understand your point. 
In my use case, I need to collect a lot of data in the field. The faster the app is, the more I can accomplish. 
Currently, the app runs as fast as possible on my device, which is already great! (a big thanks to the team, your app is already better than the others I tried / work with).

However, I think the ergonomics could still be improved a little.
For example, avoiding the necessity of long presses and removing all the swipe actions that are not practical for a field app. Adding quick access to actions, such as displaying options to duplicate, delete, or open a feature after selecting an entity, instead of immediately opening the feature, would also enhance usability.

I close this issue as suggested. 
Thanks !
