### ISSUE TITLE
Qfield widget external resource - link web  

### ISSUE THREAD

**Issue by giocoro** [opengisch/QField#528]
Hi,

it would be possible to  enable external resources (e.g photos) on Qfield ?

My idea was to have available online photos during the data collection.

Attached is an example of  what I would like to have.

 
![Widget_ex](https://user-images.githubusercontent.com/48674804/54523191-30c62400-496f-11e9-8506-d98c7d4b9521.jpg)

Thanks you for your help!"

**Comment by VxTedxV** [comment]
"External ressources" are currently available if they are local ressources.
I tried "external ressource" with web viewer property in Qgis (3.6), which works fine, but in QField it shows the broken image icon instead of the image shown from the web.

**Comment by nirvn** [comment]
@giocoro , QField now has read-only support for http(s) image attachments. Was that what you were looking for?
