### ISSUE TITLE
Implement interactive username/password entry for pgsql layers

### ISSUE THREAD

**Issue by gioman** [opengisch/QField#5285]
### Describe the issue
Given the fact that qfield do not support QGIS authentication profiles for direct PostgreSQL connections (correct me if I'm wrong), there is a use case for using projects that make use of a pg_service file with no credentials stored in it: 

make the users enter their own (DB) username and password when a project is open, this way the same project can be used on the **same** device by **different** people, each one will enter their own credential and this allows to recognize who did what, by storing the (DB) username in an audit/history table.

In Desktop QGIS this works fine: on project open QGIS asks the credential **once** and all the project layers are loaded pulling down the data from the remote server.

On QField the pg_service file works fine if it contains all the infos, included username and password.

If username and password are not stored in the pg_service file then not only it does not ask to enter the credential as QGIS Desktop does, but it behaves weirdly:

QField says that layers cannot be loaded and the log show the typical error message when a client can't load a PostgreSQL table/layer because there is no pg_hba.conf entry for that IP/user... with the user being a weird "u0_a264" that I have no idea where it comes from (absolutely no reference to that in the project and pg_service I'm using) and also the pg_hba.conf file on the endpoint is correctly defined to allow remote connections to that specific DB (also proved by the fact that if using the pg_service file with the username and password stored it all works fine).

Is there any workaround to this?

**Comment by gioman** [comment]
Maybe I'm overthinking it and it is just enough to use a project that pulls layers from a connection where username and password are were not saved in the connection properties. Is this case supported in QField? > will it asks (once) for the credential on project load?

**Comment by gioman** [comment]
> will it asks (once) for the credential on project load?

Answering myself > do not ask to enter the credential and log show same weird error as described before (on QGIS Desktop it asks for the credential and all works ok).

**Comment by m-kuhn** [comment]
Interactive user name/password entry for pg is not yet implemented

**Comment by gioman** [comment]
> Interactive user name/password entry for pg is not yet implemented

@m-kuhn can you quote that for me? Thanks!

**Comment by gioman** [comment]
> @m-kuhn can you quote that for me? Thanks!

@m-kuhn gentle ping.

**Comment by m-kuhn** [comment]
hi @gioman sorry for the delay
Good news, this feature is already comissioned and planned for the next release.

**Comment by gioman** [comment]
> hi @gioman sorry for the delay
> Good news, this feature is already comissioned and planned for the next release.

@m-kuhn no worries, that is a great news! Still waiting for some more details on the webdav thing, cheers!
