### ISSUE TITLE
Repeat Attribute Checkbox Not Shown in Forms

### ISSUE THREAD

**Issue by ivankautter** [opengisch/QField#530]
Upon digitizing a point feature with attribute form, checkbox to allow attributes to be repeated on subsequent feature creation does not appear.

### Reproduction Steps:

1. Digitize a feature with an attribute form on latest release candidate on Pixel 2 running Android 9

### Expected behavior:

Repeat attributes checkbox should appear.

### Observed behavior:

The checkbox does not appear irrespective of orientation mode (e.g. portrait or landscape). Error does not occur on device running Android 6.0.1

### Screenshots and GIFs

![Screenshot_20190319-085242](https://user-images.githubusercontent.com/17435854/54621793-94128d80-4a25-11e9-87e7-db588baaa09a.png)
![Screenshot_20190319-085257](https://user-images.githubusercontent.com/17435854/54621812-9bd23200-4a25-11e9-9374-02287a5f41c8.png)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 1.0.0.-rc5

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Fixed by #541
