### ISSUE TITLE
OSM tiles not showing in 3.30.0

### ISSUE THREAD

**Issue by qsavoye** [opengisch/QField#5304]
### Describe the issue
OSM tile layer or other XYZ layer can't be displayed on new qfield version 3.30.0 Window 64 

### Reproduction steps
1. Open a project (for instance bees sample project)
2. Check if OSM layer is displayed on legend

### Expected behavior
OSM tiles must be shown on map

### Observed behavior
OSM tiles not visible on map

### Screenshots and GIFs
![image](https://github.com/opengisch/QField/assets/88184311/56c6254c-2135-45f9-a0aa-e94d78d06a4e)
![image](https://github.com/opengisch/QField/assets/88184311/1cbd1e48-1ee9-46fc-8463-e71b1646517c)

### Desktop (please complete the following information)
 - OS: Windows 10 Family Edition
 - QGIS Version 3.36.3
 - QField version 3.30.0

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@qsavoye , could you test something for us: open the QField changelog popup (found in the About QField panel). Are you seeing a page of content or a blank page?

Here:

![image](https://github.com/opengisch/QField/assets/1728657/e0cca281-5890-4b52-89a3-4b72817164bc)

**Comment by qsavoye** [comment]
Its weird : i have a blank page whereas i have an internet connection because i can connect to my qfield cloud account on the app

**Comment by Iomys** [comment]
I have the same problem with the iOS app 3.3.0 - Darién (1272d1 v3.3.0), with Qt 6.6.3. 
App downloaded today on the App Store.

Changelog is not visible (like no internet access) and the WMS tiles requests does not work.

It is possible to connect to QField Cloud, but impossible to load a project.

**Comment by nirvn** [comment]
I can replicate this issue with the Linux release build of QField 3.3.0. I see these thrown:

```
qt.network.http2: stream 3 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 5 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 7 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 9 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 11 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 13 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 15 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 17 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 19 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 21 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 23 finished with error: "Server is unable to maintain the header compression context for the connection"
qt.network.http2: stream 1 finished with error: "Connection closed"
```

**Comment by nirvn** [comment]
FYI, we are testing a tentative patch for this regression.

**Comment by qsavoye** [comment]
> I can replicate this issue with the Linux release build of QField 3.3.0. I see these thrown:
> 
> ```
> qt.network.http2: stream 3 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 5 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 7 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 9 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 11 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 13 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 15 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 17 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 19 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 21 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 23 finished with error: "Server is unable to maintain the header compression context for the connection"
> qt.network.http2: stream 1 finished with error: "Connection closed"
> ```
> 
> (see https://github.com/qt/qtbase/blob/5b151ea2d23dc3834180d3ec6495ac5d99cae550/src/network/access/http2/http2protocol.cpp#L141-L144)

Same error when i looking my logs on windows OS
