### ISSUE TITLE
RedMi does not accept non-UTF characters

### ISSUE THREAD

**Issue by spono** [opengisch/QField#5324]
Hi,
I don't know if the reading of non-UTF characters is handled on a brand-wise or OS-wise level, but I'm writing here only to report that I found out that the same project (containing a non-UTF character in a layer's path) was correctly handled (i.e. switched on/off and modified) on an Oppo Find X3 but not on a RedMi note 10 pro, both using Android 12.
HTH!

Packed on Windows 10 and tested on QField 3.19, 3.2.2 and 3.3.0

**Comment by m-kuhn** [comment]
Thank you for reporting this issue.
In order to allow someone to investigate this, this will need a minimal sample project to reproduce this behavior.
