### ISSUE TITLE
 No more highlighs of selected features

### ISSUE THREAD

**Issue by ChristOffPro** [opengisch/QField#533]
[Short description of problem here]

 No more highlighs of selected features

### Observed behavior:
Using qgis projects edited with Qgis 2.18, then using QfieldSync

**QField version:** [Latest]

## Additional information:

* Problem started happening recently
* Problem can be reliably reproduced, doesn't happen randomly
* Problem happens with all files and projects, not only some files or projects

**Comment by m-kuhn** [comment]
Can you verify with QGIS 3? QGIS 2 is end of life.

**Comment by geoplanteam** [comment]
Hi all

I can confirm with QGIS 3.4.4 for point and line features (didn't test polygon).

Regards Christoph
