### ISSUE TITLE
Bug in editing attributus with stylus (introduced in latest version Darien 3.3.1)

### ISSUE THREAD

**Issue by elmonchas** [opengisch/QField#5342]
### Describe the issue
Since the update to version 3.3.1 (Darien) we encouter a bug when editing attribute data with the stylus.

The issue happens with value - relation fields. When you select an option using the stylus a popup will show up, asking if "you're sure to leave editing modus?". If you click yes, all changes will be ignored. If you cancel, you also loose the changes.

This means currently it is impossible to use the stylus for editing value-relation attribute data. 

![image](https://github.com/opengisch/QField/assets/158583631/2683d1e7-64bf-41e6-8846-265a90650400)
(Image of the message when trying to edit a value relation with stylus)

### Reproduction steps
1. make a layer with a value relation field
1. Open the object attribute form (with finger or stylus)
2. go to edit attributes
3. tap the value relation field, or magnifying glass icon with the stylus. Select one of the options. 
4. The error will occur and you can't fill in the field.

### Expected behavior
selecting a value relation with stylus should behave the same as using fingers. Note that there is a workaround for this bug to presse the value-relation field with your finger and select the value with your finger. 

### Mobile (please complete the following information)
 - Device: Samsung galaxy tab active 3
 - OS: android 13
 - QField version: Darien 3.3.1

**Comment by nirvn** [comment]
@elmonchas , the APKs in this PR should fix your issue: https://github.com/opengisch/QField/pull/5359 -- if you could test and report back, it'd be much appreciated.

**Comment by elmonchas** [comment]
thank you very much. I installed the new APK and some first tests were working good.
