### ISSUE TITLE
Toogle Button Interface

### ISSUE THREAD

**Issue by charles9469** [opengisch/QField#5344]
As the new version of QField allows value map to be displayed as buttons, I cannot see this new interface on my iOS 3.3 Qfield app.

How should I configure the layer proprieties on my computer ?

Regards, 
Charles

![image](https://github.com/opengisch/QField/assets/8075710/0d8f9cbc-304a-4d00-8810-2ede1f4e453b)

**Comment by she-weeds** [comment]
You need to set it up in QFieldSync on the desktop. Layer Properties > QField tab (all the way at the bottom)

**Comment by charles9469** [comment]
In Qfield Tab, is it the Relationship configuration ?

At first glance, i thought buttons were available for Value Map instead of Relation Reference...

**Comment by suricactus** [comment]
Proper documentation willl land very soon in QField docs. You can find a screenshot and all the details of the new configuration here https://github.com/opengisch/qfieldsync/pull/584
