### ISSUE TITLE
drop down menu in Qfield

### ISSUE THREAD

**Issue by recekibr** [opengisch/QField#535]
Good morning to all,
[Short description of problem here]
I cannot obtain multiple selection filed in Qfiled
### Reproduction Steps:

1. I create a Qgis project that can support multiple choiche in point edit ( example : tree.status, selection : [ good, bad, excellent ]
2. using the plugins I craete the project for Qfield ( but same problem if i move the project manually)
3. open in Qfield: everything is ok BUT the multiple choiche in the point editing/creation

### Expected behavior:

I expected to have the dropdown menu in the point editing/creation feature,
hacking on that, I only succeded to have the proposed values {good, bad, excellent} but when I edit, I cannot choose, and have to write manually

### Observed behavior:

I was expecting to have something like in the vimeo video at this page
www.northrivergeographic.com/archives/qfield-mobile-qgis-data-collection

### Screenshots and GIFs
**QField version:** [1.0.0-rc5-M (10000053)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] : don't know, I only used this version
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]: always happens
* Problem happens with all files and projects, not only some files or projects: [Yes]

##thanks in advance

**Comment by m-kuhn** [comment]
Hi, which widget did you configure for the field?

**Comment by signedav** [comment]
Hi @recekibr 
What is the status here? What widget did you configured? Could you provide us a project?
