### ISSUE TITLE
QField error during upload of geopackages: invalid_dataprovider

### ISSUE THREAD

**Issue by anheinra** [opengisch/QField#5350]
### Describe the issue
I get the error "Packaged layer 'layer_name' is not valid. Error code invalid_dataprovider, error message: File 'name_file' missing." Can someone help?
I already tried moving the files to the same file as the cloud project, as someone has suggested, but that didn't work. I am new to QField, so I would appreciate help!

### Screenshots and GIFs
<img width="446" alt="Bildschirm­foto 2024-06-18 um 16 34 15" src="https://github.com/opengisch/QField/assets/173172470/be427195-b0e1-4a52-a97f-166d86394ea8">

### Desktop (please complete the following information)
 - iOS Ventura 13.2.1
 - QGIS Version Prizren 3.32 longterm release

### Mobile (please complete the following information)
 - Device: Samsung tablet S7
 - OS: Android 12
 - QField version: 3.3.1 Darién
### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [No]

[anheinra, Kartierunterlagen_Wellritztal]

**Comment by SeqLaz** [comment]
Hi @anheinra , It seems like the GeoPackage location was saved or imported from the wrong path. To fix this, find the correct QFieldCloud project folder path. You can check the Properties of the project to locate the folder path, which is typically (../{user}/QField/{Project name}/). Once you find the correct folder, copy and paste the GeoPackage inside the folder, then import the layers into the QGIS project and synchronize any changes to the cloud.

**Comment by anheinra** [comment]
@SeqLaz Thanks for the quick answer! Unfortunately, the geopackages seem to have the correct folder path... The path seems correct in the cloud, however changes are not uploaded to my mobile device. When I open the cloud project, everything is in place.
However, I am unable to open the QGIS project, which includes the reference files for the cloud. I didn't have that problem yesterday. It appears blank in the starting screen and I can not open the qgz-file in the folder.
<img width="1298" alt="Bildschirm­foto 2024-06-20 um 11 03 53" src="https://github.com/opengisch/QField/assets/173172470/cdc3dd41-e33d-45bb-9820-3f16ae8bb3ab">

**Comment by SeqLaz** [comment]
> @SeqLaz Thanks for the quick answer! Unfortunately, the geopackages seem to have the correct folder path... The path seems correct in the cloud, however changes are not uploaded to my mobile device. When I open the cloud project, everything is in place. However, I am unable to open the QGIS project, which includes the reference files for the cloud. I didn't have that problem yesterday. It appears blank in the starting screen and I can not open the qgz-file in the folder. <img alt="Bildschirm­foto 2024-06-20 um 11 03 53" width="1298" src="https://private-user-images.githubusercontent.com/173172470/341347279-cdc3dd41-e33d-45bb-9820-3f16ae8bb3ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MjYxNDQsIm5iZiI6MTcxOTUyNTg0NCwicGF0aCI6Ii8xNzMxNzI0NzAvMzQxMzQ3Mjc5LWNkYzNkZDQxLWUzM2QtNDViYi05ODIwLTNmMTZhZThiYjNhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QyMjA0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmQ0OTY2ODY4YTEyOTg0NjIwM2FiOWFlZDBjNDExYmRhNmUwOTkwOGRhNmFlN2E0YWI0OGMzY2E3NDUyOTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TZ7_0isU_gH0k8wwl27JojVtmz9cSDS8G4ABapzUkYE">

@anheinra could you try the new packager? to improve synchronization across devices.

You can find more information about this optimized packager at: https://docs.qfield.org/get-started/tutorials/get-started-qfc/#enhance-your-project-with-the-optimized-packager

I kindly request you to try synchronizing your project using this new functionality. To do so, please navigate to the Settings of your project and make the changes to the packager.

**Comment by suricactus** [comment]
@anheinra actually your project stores absolute paths to your layers. Can you please force the layer files to be relative paths. I can see in the screenshot you have provided there are paths that are `/Desktop/Stadium Lab/`, which are absolute paths from your system. If you make sure all your project files are in the same directory and the qgs project stores them as relative paths, you will no longer experience this problem.

**Comment by sboillat** [comment]
I had the same error "invalid_dataprovider" with each one of my layers. This even though all .gpkg files are in the same folder as the project, and project properties are set to relative.
I found out that if I create a new project with another name, upload all my .gpkg and style files again and then upload to QFieldCould, it works. But if I close the project and re-open it, I get the error again.
