### ISSUE TITLE
Selecting a value in a form dropdown with Samsung S Pen in QField

### ISSUE THREAD

**Issue by bladnor** [opengisch/QField#5351]
### Describe the issue
When selecting a value from a dropdown with a samsung s pen does not work most of the time

### Reproduction steps
1. Create a dropdown in a from with approx. 50 to 80 values
2. Use a Samsung S Pen to select one

### Expected behavior
The value in the dropdown is choosen to fill the corresponding field with. The dropdown gets closed.

### Observed behavior
When taping with the S Pen on a value in the dropdown, nothing happens

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab Active 3 Enterprise
 - QField version: Darién 3.3.1

### Additional information
The workaround is to close the dropdown, reopen it again and use the finger to select the value.

**Comment by m-kuhn** [comment]
Thank you for reporting, is this the same as https://github.com/opengisch/QField/issues/5342 ?

**Comment by bladnor** [comment]
Yes, exactly.

**Comment by nirvn** [comment]
@bladnor , are you sure it is the same issue here? In #5342 , clicking on a dropdown value doesn't do "nothing", it triggers an editing cancellation dialog.

**Comment by bladnor** [comment]
Yes, it is the same. 'do notthing' was ment in the sense that it does not take over the value. Agree, not the best description. We had this pop up dialog as well.

**Comment by nirvn** [comment]
@bladnor , oh good. Can you try the APK here to see if it fixes your situation: 

https://github.com/opengisch/QField/pull/5359

**Comment by elmonchas** [comment]
i did some first test. The fix seemed to have solved the issue.
