### ISSUE TITLE
Snapping icon beside wrong layers/tables?

### ISSUE THREAD

**Issue by gioman** [opengisch/QField#5372]
I haven't used much snapping on QField, so forgive me if I'm getting something wrong.

I have a project that when opened on QField (3.3.2) show the snapping icon beside wrong layers (as also the icon is not fully visible on some of them)

![image](https://github.com/opengisch/QField/assets/1951107/d9f7b600-3f85-41a0-b878-447879213c3a)

![image](https://github.com/opengisch/QField/assets/1951107/246fbc20-d629-46e6-a274-fab9018dba50)

If the icon represent the layers where snapping is active then it should not be visible beside table with no geom. Also the (partial) icon shows besides layers where snapping is not active

![image](https://github.com/opengisch/QField/assets/1951107/633c5772-969e-48fb-9541-69412fdecff0)

PS On this specific device Blackview Active 8 Pro (maybe others, untested), some symbology class name is also truncated

![image](https://github.com/opengisch/QField/assets/1951107/fc965b2c-51f8-4d2e-99c3-3d4d93a3593b)

**Comment by gioman** [comment]
As seen also on other projects and devices

![image](https://github.com/opengisch/QField/assets/1951107/0200c09a-2995-45ec-8cf4-b74aa0671bf2)

**Comment by nirvn** [comment]
@gioman , thanks for the report. The issue with badges cut of has been fixed, can you try the APK in this PR to confirm: https://github.com/opengisch/QField/pull/5361 ?

As for geometryless tables showing snapping. Well, snap! Good catch :)

**Comment by nirvn** [comment]
@gioman , the remaining issue is addressed in this PR (https://github.com/opengisch/QField/pull/5377), feel invited to try the APK and report back.

BTW, I see you are making use of the weather plugin, that just made my day :)
