### ISSUE TITLE
Atlas print which includes table prints out NULL values

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#5373]
When i print an atlas with Qfield which has a table where some values are NULL, the table shows NULL as well (instead of just beeing empty. If i print the same atlas via QGIS, nothing is shown (as desired). Two screenshots for better understanding:

Print via QGIS:
![grafik](https://github.com/opengisch/QField/assets/15894401/9891627e-9f58-40d3-b779-b3443b3c8d66)

Print via QField:
![grafik](https://github.com/opengisch/QField/assets/15894401/3549a550-5bf9-406c-8fea-933974d7547a)

Is there a trick to supress the printing of `NULL`?

**Comment by m-kuhn** [comment]
Could you share a test project to reproduce this?

As a workaround, I guess you can probably do some tricks with `COALESCE` and virtual fields

`COALESCE("durchgefuehrt",'')`

**Comment by nirvn** [comment]
@meyerlor , to add to @m-kuhn relevant suggestion, I suspect what's happening here is that you have modified the following NULL representation setting in QGIS and set it to an empty string:

![image](https://github.com/opengisch/QField/assets/1728657/a95bc4b2-1ebc-4618-9424-dd4175a89669)

In QField, we represent NULL values by the default 'NULL' string. If I set the above-mentioned setting in QGIS to NULL, I get the same representation in QGIS as I do in QField:

![image](https://github.com/opengisch/QField/assets/1728657/578bfb9b-1934-431f-8ea6-e85fae13ff67)

I will close this issue as resolved. Happy field mapping!

**Comment by meyerlor** [comment]
alright, thanks - @nirvn you are right with my QGIS setting and @m-kuhn thanks for the nice workaround!
