### ISSUE TITLE
Issue: Drop-down Selection Automatically Resets to Default Value in QField Attribute Form search

### ISSUE THREAD

**Issue by vishnunv2696** [opengisch/QField#5374]
I am experiencing an issue with the attribute form search functionality in QField. When I search for data within a drop-down menu and make a selection, the value sometimes changes back to the default instead of retaining the selected value. This problem occurs intermittently – sometimes the selection works correctly, but most of the time it reverts to the default value. This behavior is affecting the reliability of data input in the field. 

https://github.com/opengisch/QField/assets/173331997/069aad78-4c24-47d0-8b10-4565286cd7e5

**Comment by nirvn** [comment]
@vishnunv2696 , can you share a test we can use to replicate this issue?

**Comment by vishnunv2696** [comment]
What kind of test you want ,Sorry I cant understand.

**Comment by nirvn** [comment]
@vishnunv2696 can you share the project you used to make the video above?

**Comment by nirvn** [comment]
@vishnunv2696 , your issue *might* have been fixed by a PR today, you can try the APKs here: https://github.com/opengisch/QField/pull/5399

Note that unless you provide a project, it's quite unlikely this will get resolved otherwise. Cheers.
