### ISSUE TITLE
Difficulté de mise à jour champ avec liste déroulante ou date

### ISSUE THREAD

**Issue by jefconseil** [opengisch/QField#5382]
Bonjour, j'ai un problème sur Qfield (dernière version).
J'utilise un projet QGIS avec Qfield sur le terrain. 
Il a bien fonctionné il y a deux semaines et maintenant, après avoir à nouveau transféré des données de la tablette au PC , puis rechargé le projet, les champs avec liste déroulante génèrent un message d'erreur.
Par exemplecsibje veux changer le nom de la rue ou un autre paramètre d'objet.
Voir image 1
![Screenshot_20240621_170557](https://github.com/opengisch/QField/assets/173481892/189ea0f0-5a17-4d91-9cc2-1c97a7414ead)
Image 2
![Screenshot_20240621_170526](https://github.com/opengisch/QField/assets/173481892/a4fe94e3-0fe3-4383-88c0-eb35e9059b0d)

### Desktop (please complete the following information)
 - OS:  Windows 11
 - QGIS Version 3.36.3 Maidenhead ​
 - QFieldSync Version ? 

### Mobile 
 - Device: Samsung Tabactiv pro 8"
 - OS: Android 12
 - QField version: 
![Screenshot_20240621_172619](https://github.com/opengisch/QField/assets/173481892/cd96e7f7-1013-445f-a690-ddffeb43d573)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [yes]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by nirvn** [comment]
@jefconseil , c est avec stylus? Si oui le problème a été identifié et corrigé. Une nouvelle version sortira d'ici lundi.

**Comment by suricactus** [comment]
@jefconseil can you please support your issue report in English? You can use machine translation to support you in this task. Thank you!

**Comment by jefconseil** [comment]
Stylus, c'est à dire le stylet de la tablette ? Oui

Le ven. 21 juin 2024 à 17:43, Mathieu Pellerin ***@***.***> a
écrit :

**Comment by jefconseil** [comment]
Le stylet de la tablette Samsung ? Oui

Le ven. 21 juin 2024 à 17:43, Mathieu Pellerin ***@***.***> a
écrit :

**Comment by nirvn** [comment]
@jefconseil , vous pouvez essayer l APK ici afin de confirmé que le problème est fixé https://github.com/opengisch/QField/pull/5380

**Comment by jefconseil** [comment]
Merci j'essaierai lundi et je vous donne le retour.
Cordialement
JF Fave

Le ven. 21 juin 2024 à 17:49, Mathieu Pellerin ***@***.***> a
écrit :

**Comment by jefconseil** [comment]
Merci, une personne a répondu en français.
Thanh you, but in had an answer in french language

Le ven. 21 juin 2024 à 17:44, Ivan Ivanov ***@***.***> a
écrit :

**Comment by jefconseil** [comment]
Bonjour,
Je vous confirme que le problème a été résolu. L'application fonctionne
parfaitement maintenant avec le stylet.
Meilleures salutations
Jean-François Fave

Le ven. 21 juin 2024 à 17:49, Mathieu Pellerin ***@***.***> a
écrit :
