### ISSUE TITLE
Qfield Pictures folder

### ISSUE THREAD

**Issue by denilsonjesus** [opengisch/QField#5383]
I noticed in several projects that Qfield is storing all the photos taken, in addition to saving it in the DCIM folder, it also saves it in the ...\Internal Storage\Android\data\ch.opengis.qfield\files\Pictures folder, It's normal that? It creates files, for example, QFieldCamera20240603_1431201597398156462030757JPG, without the JPG extension.

**Comment by denilsonjesus** [comment]
Has anyone observed this situation?

**Comment by gioman** [comment]
Are you using a recent release? I think I have seen it in the past, but not on recent releases.

**Comment by denilsonjesus** [comment]
I noticed it in the latest version, 3.2.2, but there were old and new photos which means the situation is old. I will remove the folder and see if the current version continues to occur.

**Comment by nirvn** [comment]
@denilsonjesus , fixed by this PR, you can check the APKs in ~10 minutes to confirm it is working as expected: https://github.com/opengisch/QField/pull/5398
