### ISSUE TITLE
Pictures not being pushed (or downloaded) in ver. 3.3.4?

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QField#5390]
### Describe the issue
Images captured with tablet in QField is not pushed (downloaded) when synchronizing with self-hosted QFieldCloud.

### Reproduction steps
1. Take an image
2. Push changes to the cloud
3. Synchronize (download) with QFieldSync in QGIS. Only the path is shown, no image. Worked fine with previous versions of QField.

### Expected behavior
The images should be downloaded as well. And should appear in the form (when using the Identify button).

### Observed behavior
 Only the file path and image filename is shown, no image.

### Screenshots and GIFs
![image](https://github.com/opengisch/QField/assets/10632163/c2061d98-8eb4-4f5f-a63f-d37c4240d909)

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.36.3
 - QFieldSync Version 4.10.0

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab Active4
 - OS: Android 14
 - QField version: 3.3.4 Darién bae0ff v3.3.4

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
We have tried to reproduce this, with an on prem installation but were not able to reproduce.

**Comment by 9ls1** [comment]
Thanks for looking into that. I'll have another try myself. However, the problem is still present for the fieldworkers pushing data from the field with their Android tablets. Stay tuned.

**Comment by 9ls1** [comment]
Update: Sometimes images appears as file paths and sometimes they appear as images (even with the same attachment-settings) on tablets and PC (after sync). I have not yet dug too deep into the reasons. The main point is that the images are downloaded from the cloud and into the project's cloud folder on the PC. I think you may move this to "Closed".
