### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by EgidijusViko** [opengisch/QField#5396]
Describe the issue
Problem appear when I connect to VPN. And try login to local it show "Address/api/network error" image added. From first expresion it looks like that some tokkens or what was cached, because after fully unistall application and install everything goes well again.

Reproduction steps

Go on connect to profile.
Download project.
Close app.
Wait ~30 minute or more.
Try again login
And show network error
image

Desktop (please complete the following information)
OS: [e.g. Windows]
QGIS Version [e.g. 3.22.0]
QFieldSync Version [e.g.4.0.0]
Mobile (please complete the following information)
Device: Android 13 Xioami
OS: [e.g. Android 11]
QField version: 3.20
Additional information
With older version it can't reproduce this problem but with 3.20 it started.

**Comment by nirvn** [comment]
@EgidijusViko , is this a problem against the official QFieldCloud instance (i.e. app.qfield.cloud)? This sounds a lot like a local network issue vs. an issue with QField.

**Comment by EgidijusViko** [comment]
Yes it local. But still think that with older version is working normally without any problems. But from 3.20 started. That can't be then network issue if it be all version be touch???

**Comment by nirvn** [comment]
OK, I see you've filed an issue on this here (https://github.com/opengisch/qfieldcloud/issues/956) -- I'm gonna close this one in favor of avoiding parallel discussions. Thanks.
