### ISSUE TITLE
Relationship’s children can not be created.

### ISSUE THREAD

**Issue by jhonalex06** [opengisch/QField#5445]
### Describe the issue

I created a project with some relations between the different tables, the project was working correctly in old versions of *QField (3.1.9)* but no now in *QField (3.3.6)*. When I try to create a new feature related to the table *predio*, QField throws an error that says *Unable to save changes*.

### Reproduction steps

1. Open Project.
2. Edit mode.
3. Add new feature.
4. Second Tab Dirección.
5. Add new feature
6. Fill the form.
7. Confirm changes.

### Expected behavior

QField should allow creating the new feature in the table related to *Predio*, in this specific case *Dirección*.

### Observed behavior

It doesn't allow creating a feature related to the main table *Predio*.

### Screenshots and GIFs

Error QField:
*Project file for testing:* [Project.zip](https://github.com/user-attachments/files/16242786/Project.zip)

![relation_child_issue](https://github.com/user-attachments/assets/bba32b39-3e6e-48df-9e5e-0c10feb45863)

![error_qfield](https://github.com/user-attachments/assets/f6bfea77-af30-4491-8a14-2cda67ceef65)

### Desktop (please complete the following information)
 - OS: Ubuntu 22.04.4 LTS
 - QGIS Version: 3.34.7
 - QFieldSync Version: No use QFieldSync

### Mobile (please complete the following information)
 - Device: Samsung Galaxy S24 Ultra
 - OS: Android 14
 - QField version: 3.3.6 - Darién (78a4fe)

### Additional information

I tested different versions of QField and identified the issue started in version 3.2.0 - Congo, in the previous version the relations worked correctly, besides, one of the improvements of version 3.2.0 was "Relationship’s children can now be created before saving their parent feature". Probably the issue starts here.

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@jhonalex06 , thanks for the report. The APKs here (https://github.com/opengisch/QField/pull/5455) should fix the regression.

**Comment by jhonalex06** [comment]
> @jhonalex06 , thanks for the report. The APKs here (#5455) should fix the regression.

Amazing, I am going to test it
