### ISSUE TITLE
Qfield Anotattion on Camera removes exif data

### ISSUE THREAD

**Issue by Scintsz** [opengisch/QField#5446]
### Describe the issue
I don't know if this has beeen already reported, but trying to make annotation on photos taken inside qfield corrupts/removes the gps metadata.
I have a custom model to generate a photographic report. So when I take a picture and qfield store the info, another field extracts the exif data called "Coordenada X". The photo field it has a annotation icon to make lines on the image, but trying to make annotation in the image makes the coordinate field became null.

### Reproduction steps

1. Open Qfield App, go to project that has the camera widget.
2. Take a picture or access the gallery and select some image to some field.
3. Make a annotation in the image and confirm it.
4. The gps data is gone.

### Expected behavior
The annotation would be save in the photo and the metadata would still be the same.

### Observed behavior
The annotation is saved in the photo and the metadata is gone.

### Screenshots and GIFs
![01](https://github.com/user-attachments/assets/e8348bc9-22b2-4504-810a-19d8ed768176)
![02](https://github.com/user-attachments/assets/3641188d-b1e3-4d33-a803-a8693aa15407)

### Mobile
 - Device: Samsung S20 FE
 - OS: Android 13
 - QField version: 3.3.6 - Darién (78a4fe v3.3.6) Qt 6.6.3

### Additional Info
The Qgis expression used to extract the metadata is Exif.GPSInfo or to be more precise to_dms(exif(@project_folder || '/' || "foto_02", 'Exif.GPSInfo.GPSLongitude'), 'x', 3, 'aligned') ||
 ' e ' ||
to_dms(exif(@project_folder || '/' || "foto_02", 'Exif.GPSInfo.GPSLatitude'), 'y', 3, 'aligned')

**Comment by nirvn** [comment]
Confirmed.

**Comment by nirvn** [comment]
@Scintsz , fixed, you can try the APKs in this pull request (https://github.com/opengisch/QField/pull/5454)

**Comment by Scintsz** [comment]
@nirvn, Yes, the issue is now fixed on my project. Thank you.
![Screenshot_20240722_111959_Adobe Acrobat_2](https://github.com/user-attachments/assets/176ea4ed-7edd-40e7-8b43-6bb7aa0ae939)
