### ISSUE TITLE
Input of negative values in the decimal field (double) not possible

### ISSUE THREAD

**Issue by fiddlersfan** [opengisch/QField#5450]
### Describe the issue
Direct enter a negative is not possible because you cant enter a minus sign as first value

Error message in message log: 
_Value '-' NOT NULL could not be converted to a compatible value for field Negative_Decimal(Real)_

### Reproduction steps
1. Create new Geopackage
2. Add a decimal field
3. Upload it to QFieldCloud and sync it
4. Create a new feature and try to insert a negative value 
[Project.zip](https://github.com/user-attachments/files/16261722/Project.zip)

### Expected behavior
It should be possible to enter negative values without a workaround

### Observed behavior
An input is only possible if you first enter a positive number, place the cursor in the first position and insert a minus sign.

### Mobile (please complete the following information)
 - OS:  iOS and Android
 - QField version: 3.3.6 - Darien (78a4fe c3.3.6)

**Comment by SeqLaz** [comment]
@fiddlersfan  After reviewing your sample project, it looks like you are using a Text Editor as the Widget type, and after changing the widget to Range, it works perfectly.

![image](https://github.com/user-attachments/assets/c08a1e2c-6578-43bd-a007-716cecbabe12)
![image](https://github.com/user-attachments/assets/68b1eb17-73fe-44a1-80b4-0c3c77d60b73)

**Comment by fiddlersfan** [comment]
@SeqLaz You're absolutely right, my mistake. Sorry for the noise. I will close this issue.

**Comment by nirvn** [comment]
@fiddlersfan , can you try the APK there to confirm your original issue with text field is fixed: 

https://github.com/opengisch/QField/pull/5452

Thanks

**Comment by fiddlersfan** [comment]
@nirvn: Thanks! I have now tested it and it works as expected.
