### ISSUE TITLE
Add support for world (.wld) files for georeferencing with cloud projects

### ISSUE THREAD

**Issue by cruelaid** [opengisch/QField#5451]
### Describe the issue
QGIS can create and display linearly transformed georeferenced images in a world file. This small-file alternative to GeoTIFF seems like a no-brainer for integration in Qfield, yet it currently does not work.

### Reproduction steps
1. Georeference an image in QGIS using a linear or helmert transformation and select "Create world file only."
2. Output the result to your project's synced directory. Make sure the source image is in the same folder.
3. Sync the project and open in Qfield.

### Expected behavior
The georeferenced image layer should appear in the correct size and position as specified by the .wld file.

### Observed behavior
The georeferenced image appears in a completely incorrect location, indicating the transformation data in the world file was not used.

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.38.0
 - QFieldSync Version 4.9.1

### Mobile (please complete the following information)
 - Device: Samsung Galaxy A13
 - OS: Android 14
 - QField version: 3.3.6 (78a4fe)

**Comment by m-kuhn** [comment]
Thank you for this suggestion.
Can you add a sample project (zipped) with files for reproduction?

**Comment by cruelaid** [comment]
Sure thing!

[world file demo.zip](https://github.com/user-attachments/files/16287124/world.file.demo.zip)

**Comment by nirvn** [comment]
@cruelaid , QField does support (.wld), but I think you're running into a different problem. Are you trying to open the project by opening the ZIP file via messenger / email app?

**Comment by nirvn** [comment]
@cruelaid , can you try the APK in this pull request (https://github.com/opengisch/QField/pull/5453), I believe it will fix your issue. 

Proof of life:
![image](https://github.com/user-attachments/assets/10008615-7085-4454-9a07-e7c4722f78ce)

**Comment by cruelaid** [comment]
Indeed, the problem had something to do with QFieldCloud as the project worked as intended in the release version when opened up from a zip. However, there was no change in behavior from the APK provided when syncing from QFieldCloud.

**Comment by nirvn** [comment]
@cruelaid , ah I see, that'd be a different issue here then. I'll reopen and indicate it's a cloud - specific issue. 

Nevertheless, glad this got us to fix the zipped project issue :)

**Comment by nirvn** [comment]
@cruelaid , a fix has been implemented and should make its way to app.qfield.cloud in the coming weeks. In the meantime, one work around for you would be to rename `Morocco Geology.wld` to `Morocco Geology.pgw`, that would lead to a valid layer in your cloud project.
