### ISSUE TITLE
When a polygon feature is split, the splitted parts don't get a new UUID. 

### ISSUE THREAD

**Issue by nielsvanputte** [opengisch/QField#5463]
I'm working on a vegetation survey project in QField Cloud in which field workers map vegetation species to polygons (many to one relation). The polygon layer has a unique UUID field. Users should be able to edit polygons and split polygons before attributing vegetation species to the polygons. 

In editing mode, when a new polygon is created, a new UUID is generated for that polygon. However, when an existing polygon is split, one of the parts gets the UUID from the original polygon and the second parts UUID field is empty and non-editable. Without a UUID, no values can be attributed to the child layer (vegetation observations). When splitting the polygons in QGIS desktop, the split parts do get a new UUID.

### Expected behavior
When a polygon feature is split, at least one of the parts would obtain a new UUID

### Observed behavior
One of the parts keeps the original UUID and one of the parts gets no UUID

### Desktop (please complete the following information)
 - OS: Windows 11
 - QGIS Version  3.34.1-Prizren
 - QFieldSync Version 4.9.1

### Mobile (please complete the following information)
 - Device: Samsung Galaxy A53
 - OS:  Android 14
 - QField version: 3.3.7 Darién

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

[If the problem happened with QFieldCloud, please add your username and project name.]
nielsvanputte, Grote_Vijver

**Comment by m-kuhn** [comment]
Thank you for reporting, could you attach a minimal project file (ideally a single simple point layer) to demonstrate the problem?

**Comment by nielsvanputte** [comment]
I made a screen recording in both QGIS and QField to demonstrate the problem.

QGIS: https://www.youtube.com/watch?v=Hy0_ujRT4Y0
QField: https://www.youtube.com/watch?v=_doIDmzw9Y8

In QGIS one of the splitted parts obtains a new UUID in the attribute form (as expected).
I'm unable to reproduce this in the attribute form of QField. The UUID field of one of the parts remains empty.
Without a UUID, I'm unable to set up a many to one relation to this polygon.

**Comment by m-kuhn** [comment]
Thank you for the videos. Can you provide a minimal sample project?

**Comment by nielsvanputte** [comment]
Here you can find a minimal sample project:

[polygontest.zip](https://github.com/user-attachments/files/16388140/polygontest.zip)

**Comment by nirvn** [comment]
@nielsvanputte , it's not a problem with QField but rather the project configuration. In fact, I 'dare' say QField is behaving better than QGIS on this one :)

QGIS' Uuid Generator editor widget 'lies' about the true value of the newly feature created by the split. When you examine the feature via the attribute form, you get told by the editor widget there's a unique value when in fact the feature itself does not.

Proof:
![image](https://github.com/user-attachments/assets/b0cb6b70-ab70-4227-b20c-faec967765c8)

I would advice you to rely on UUID generation through default value, like this:

![image](https://github.com/user-attachments/assets/83a5eba3-e1a1-4887-ae76-e9b12675bde7)

**Comment by nielsvanputte** [comment]
@nirvn Thank you very much! I will try this!

Niels
