### ISSUE TITLE
QField App build failure

### ISSUE THREAD

**Issue by ajithandro** [opengisch/QField#5464]
### Describe the issue
QField Application Build Got Failed with following error.

### Reproduction steps
First, check out the source code.
The following commands will fetch the latest code.
Step 1 :
# https://github.com/opengisch/QField.git

Step 2:
A simple script helps build everything by using a docker image.
# triplet=arm64-android ./scripts/build.sh

### Operating System
# Ubuntu

### Expected behavior
Build Shuould Success and app needs to be generated

### Observed behavior
-- Running vcpkg install
warning: Embedding `vcpkg-configuration` in a manifest file is an EXPERIMENTAL feature.
qtbase[egl] is only supported on 'linux', which does not match arm64-android. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build qtbase anyway, rerun vcpkg with `--allow-unsupported`.
-- Running vcpkg install - failed
CMake Error at build-arm64-android/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:902 (message):
  vcpkg install failed.  See logs for more information:
  /usr/src/qfield/build-arm64-android/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:30 (project)

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
No such file or directory
CMake Error: Generator: execution of make failed. Make command was:  && 
No such file or directory
CMake Error: Generator: execution of make failed. Make command was:  bundle && 

### Screenshots and GIFs
![image](https://github.com/user-attachments/assets/d92d4e43-0154-457a-bc46-96abeb5e24e6)

**Comment by ajithandro** [comment]
Thanks @nirvn, I got the Build Successfully and can Install the application that is Generated in Android Outputs.
Can we Run / Debug this application with an Emulator / Mobile Device to develop some things with existing Sources?

**Comment by nirvn** [comment]
@ajithandro , we haven't come up with steps to do that. I'm eager to hear back from you if you succeed:)

**Comment by rezw4n** [comment]
> Thanks @nirvn, I got the Build Successfully and can Install the application that is Generated in Android Outputs. Can we Run / Debug this application with an Emulator / Mobile Device to develop some things with existing Sources?


how did you fix the issue? I'm still getting this:
```
-- Building for Android --
-- Using cached vcpkg
-- Building with vcpkg libraries version 1318ab14aae14db20085441cd71366891a9c9d0c
-- Running vcpkg install
warning: Embedding `vcpkg-configuration` in a manifest file is an EXPERIMENTAL feature.
qtbase[egl] is only supported on 'linux', which does not match arm64-android. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build qtbase anyway, rerun vcpkg with `--allow-unsupported`.
-- Running vcpkg install - failed
CMake Error at /home/rezwan/build/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:902 (message):
  vcpkg install failed.  See logs for more information:
  /home/rezwan/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:30 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
```
