### ISSUE TITLE
Some strings don't appear as localized in UI

### ISSUE THREAD

**Issue by fiuzzy** [opengisch/QField#5468]
### Describe the issue
In the User Interface, some text strings appear in original language (English) rather than in the local language (French in my case) despite they appear as translated in the Transifex website for 2 months and other strings translated after are correctly displayed.
Six of them are located in QField Settings Panel: 
- 3 titles of tabs of QField Settings panel: 
         - ‘Positioning’, 
         - ‘General’, 
         - ‘Variables'
- 3 texts strings in 'General' tab of QField Settings panel: 
         - 'Map Canvas',  
         - 'Allow finger tap on canvas to add vertices'
         - 'When enabled, tapping on the map canvas with a finger will add a vertex at the tapped location.'

- The last one I have found is the message at first opening after install or update: 
         - "Please wait while QField installation finalizes."

### Reproduction steps
1. Go to 'Settings', 'General' tab, 'User Interface' part, 'Language' : choose a language other than English (French in my case, but tested also with German and Spanish).
2. Restart QField.
3. Reopen 'Settings' panel.

### Expected behavior
After translation and software update, all text strings should appears according the selected language.

### Observed behavior
At least 7 text strings appears in original language/English despite they are translated in Transifex in other language and QField UI language is set with other language than English.

### Screenshots and GIFs
![IMG_20240722_232321](https://github.com/user-attachments/assets/72bd3300-1ed6-4084-bb9d-a098ba65da23)

### Mobile
 - Fairphone 3
 - OS: Android 13 and Debian 12
 - QField version: master-dev - Dev (326a5e)  and 9f449c v3.3.7 (but problem occurs with prior versions for at least a few weeks)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes
_* Please find Transifex details about concerned strings in added txt file._

**Comment by nirvn** [comment]
@fiuzzy , thanks for the reporting. There's one issue (fixed by https://github.com/opengisch/QField/pull/5469), and some strings that are translatable but where translation lagged behind a bit, which meant it didn't make it into the 3.3 release.

**Comment by fiuzzy** [comment]
@nirvn, thanks for answer and commit quickly. In the dev version (bb26f7) published today, translated strings appear now correctly. It remains only 2 strings untranslated, that is why I wrote another report (issue #5474).
(I suppose it is the good practice, as this one is closed. But don't hesitate to mention a better way about procedures, Software programming is far of my core skills, I am just an user who try to translate and report correctly and I am always happy to learn :-) )
