### ISSUE TITLE
Using Open Camera app with QField under Android 13 to capture EXIF location data

### ISSUE THREAD

**Issue by RatInTheField** [opengisch/QField#5472]
### Describe the issue
I have for some time now used Open Camera as my default camera app so that I can record location data with images captured by QField. This has been very successful and I have come to rely on it.
Since upgrading to Android 13, it is no longer possible to set a default camera, so the ability to capture location data is lost. I am no longer able to record location data from the camera in recorded images.

### Reproduction steps
1. In QField, in settings, leave camera settings as default
2. In Android, load Open Camera app, set Open camera as default camera app.
3. In Qfield, select a layer, create a new feature, navigate to the  camera option and record an image

### Expected behavior
When the camera option is selected, the default camera app is initiated (OpenCamera, identifiable with its blue shutter release button), clicking the shutter release takes an image, control returns to Qfield and the new image is previewed. On the Preview, an icon indicated that the location HAS BEEN recorded.

### Observed behavior
When the camera option is selected, the default camera app is initiated (Google, identifiable with its white shutter release button), clicking the shutter release takes an image, control returns to Qfield and the new image is previewed. On the Preview, an icon indicated that the location HAS NOT BEEN recorded.

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

### Desktop (please complete the following information)
 - OS: [e.g. Windows]
 - QGIS Version [e.g. 3.22.0]
 - QFieldSync Version [e.g.4.0.0]

### Mobile (please complete the following information)
 - Device: Lenovo Tab8 Gen4 TB300XU
 -  - OS: Android 13
 - QField version: 3.3.7 - Darien (9f449c v3.3.7)

### Additional information
* Problem started happening recently with Android upgrade to 13
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

** This is probably an issue caused by Google in Android 13, but is there a workaround?

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@RatInTheField , Android as indeed decided to further restrict access to 3rd party camera apps on security grounds. 

The workaround here is to use QField's own camera by disabling the "use native camera" option in QField's settings panel. QField's own camera has gained the capability to geotag photos a few versions ago, that should restore your workflow.

**Comment by RatInTheField** [comment]
Thanks for your speedy response. I have now re-tested your suggestion and am not getting the functionality you suggest .

QField's own app opens and is noticeably different from either Google's app or Open Camera, but it shows a location icon crossed out and I can not find a way to activate it. 

When an image is saved to QField, the icon on the preview is also crossed out, not no location data can be found.

**Comment by RatInTheField** [comment]
Gotcha!

Thanks for your patience. All seems OK now. This call can now be closed.

**Comment by nirvn** [comment]
@RatInTheField , glad it works; happy field mapping!

**Comment by notgernot** [comment]
For everyone that is able to root your device there is actually an Option to make OpenCamera to the "default camera" again. I testeted it on a dive With Lineage21/Android14 adn it works perfect....Now OpenCamera Opens as default Camera App in Qfield again also is also the default Camera systemwide.

`I copied privapp_whitelist_net.sourceforge.opencamera in /root/system/system_ext/etc/permissions/ (chmod 644, root/root)

I created /root/system/system_ext/priv-app/OpenCamera and copied the apk of the app, net.sourceforge.opencamera.apk

restart the phone (and you'll find OpenCamera installed)`

from 

https://sourceforge.net/p/opencamera/discussion/qa/thread/f77dc7d7a8/
