### ISSUE TITLE
Another 2 text strings don't appear as localized in UI

### ISSUE THREAD

**Issue by fiuzzy** [opengisch/QField#5474]
Quite in the same way of the report #5468, solved by @nirvn in #5469. 
In the User Interface, some text strings appear in original language (English) rather than in the local language (French in my case) despite they appear as translated in the Transifex website. 
 It remains 2 strings untranslated in UI: 
1. "**_Enable Map Rotation_**" in a menu when you tap the Map Canvas, I forgot it to mention in my previous reporting. 

![IMG_20240724_095858b](https://github.com/user-attachments/assets/d56ee15d-6779-4a34-8279-b83069c94799)

2.   And about the message at first opening after installation or updating: **_"Please wait while QField installation finalizes._**":  

  I think it appears for maybe 2 years now? I am pretty sure I have seen this localised before. So it might be a qsTr() function missing rather than a lag in translation push?
  I have checked in Transifex, French version is done and OK.
  
  **QField dev version (bb26f7**)

**Comment by nirvn** [comment]
@fiuzzy , thanks for the second report, the map canvas menu item not translatable is fixed here (https://github.com/opengisch/QField/pull/5475)

As for the 'please wait while installation finalizes', it's unfortunately not something that we can fix easily as when an app upgrade occurs, the app translations are not yet loaded, hence why is hard-coded into English (even though the string is translatable). So on this one, I think we'll have to mark it as won't fix.
