### ISSUE TITLE
Windows version not showing images in field inside QField

### ISSUE THREAD

**Issue by Scintsz** [opengisch/QField#5481]
### Describe the issue
Images preview not appearing on Windows Version. The image is still in the project normally and the appears in the pdf exported (even the localization is detected), but not on Qfield itself.

### Reproduction steps
1. Crate a field with a atatch widget on QGIS attribute form.
2. Go in the project with Qfield and atach a image or take a picture with webcam.
3. The image preview box is grey.

### Expected behavior
The image preview would appear normally.

### Observed behavior
Only a grey color is filled inside box.

### Screenshots and GIFs
![2024-07-26_13-52](https://github.com/user-attachments/assets/e999bd07-4d3d-4143-84e3-5de8673bf4ad)

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version 3.24.8
 - QField 3.3.7 - Darién

**Comment by nirvn** [comment]
@Scintsz , what image format are you using? A small sample project with a feature + image to replicate this issue would help out debug what's happening here.

**Comment by meyerlor** [comment]
I think i ran into the same problem - on Windows 10, i just do not get the fotos to work, on windows 11 it works. With PDF's it's similar - on Windows 11 i get the (correct) filename:
![grafik](https://github.com/user-attachments/assets/32bae9ab-89a2-400b-8e79-4166266b2f38) and the PDF openes when clicking on it.

On Win 10 I'm getting the whole path as file url, but nothing opens when i click on the link.
![grafik](https://github.com/user-attachments/assets/58734871-5849-4521-8bd3-f693930e9e12)


I will check later on a different Win 10 machine to harden the suspicion that it is a Windows 10 only issue.

Will upload a example project if needed, first i want to check other Windows 10 machines

**Comment by meyerlor** [comment]
Update:
With the second Windows 10 machine, the same behaviour occurs. 
I then tested the same project with the Qfield version 3.2.2 - here it works like it should, so this seems to be a regression in Qfield 3.3.X and is not project related. If you need an example project anyways, i happily will provide one!

**Comment by nirvn** [comment]
@meyerlor , what image format isn't working? Is that an image I see towards the top of the form here:

![image](https://github.com/user-attachments/assets/aeb0d716-4db5-414b-8591-35b9f74a5d95)

?

**Comment by meyerlor** [comment]
That screenshot was taken from Windows 11, Qfield 3.3.8 where everything works (Image format is .jpg)
Same Picture/Project/Qfield version does not work with win 11.
I just tested downwards all releases on the Win10 machine - Qfield 3.3.1 is the last one working, in 3.3.2 it stopped! :)

**Comment by nirvn** [comment]
@meyerlor , are you sure that the regression occurred between 3.**3.1** and 3.**3.2**?

**Comment by meyerlor** [comment]
yes, i tested 3.3.1 (working) and 3.3.2 and upwards (not working) on a 3rd Win10 machine. It is definately between those two versions!

**Comment by nirvn** [comment]
@meyerlor , can you test a build from a recent master revision (e.g. this: https://github.com/opengisch/QField/actions/runs/10235088561?pr=5514) to see if things are better in upcoming QField 3.4?

**Comment by meyerlor** [comment]
@nirvn thanks for the fast replies! I tested it with the dev version and unfortunately it does not work here as well. The logs show following:
```
"AppInterface loading file: C:/Temp/Ochs/Ochs_Wasser_qfield.qgs"
Logged warning: Loading a file that was saved with a newer version of qgis (saved in 3.38.1-Grenoble, loaded in 3.38.0-Grenoble). Problems may occur.
qt.svg: Cannot open file ':/images/composer/missing_image.svg', because: No such file or directory
qt.svg: Cannot open file ':/images/composer/missing_image.svg', because: No such file or directory
qt.svg: Cannot open file ':/images/composer/missing_image.svg', because: No such file or directory
qrc:/qml/editorwidgets/ExternalResource.qml:211:5: QML QQuickImage*: Cannot open: file://c/Temp/Ochs/Dokumente_Schacht/Fotos/W00134.jpg
qrc:/qml/editorwidgets/ExternalResource.qml:144:3: QML Label: Binding loop detected for property "text"
qrc:/qml/editorwidgets/ExternalResource.qml:211:5: QML QQuickImage*: Cannot open: file://c/Temp/Ochs/Dokumente_Schacht/Detailpl?ne/W00134.jpg
qrc:/qml/editorwidgets/ExternalResource.qml:144:3: QML Label: Binding loop detected for property "text"
qrc:/qml/editorwidgets/ExternalResource.qml:144:3: QML Label: Binding loop detected for property "text"
ShellExecute 'file://c/Temp/Ochs/Dokumente_Schacht/Fotos/W00134.jpg' failed (error 3).
ShellExecute 'file://c/Temp/Ochs/Dokumente_Schacht/W00134.pdf' failed (error 3).
```
The last line appears whenever i click on the PDF link.
![grafik](https://github.com/user-attachments/assets/0962a6e7-cdb0-4122-88f5-ae4b768c80ed)

**Comment by nirvn** [comment]
@meyerlor , one more build to try: https://github.com/opengisch/QField/actions/runs/10266281814?pr=5525

**Comment by meyerlor** [comment]
@nirvn nope, not working :(

**Comment by nirvn** [comment]
@Scintsz , could you try and confirm that 3.3.1 works and 3.3.2 doesn't work on your machine too?

**Comment by meyerlor** [comment]
hmm, well that is weird - sorry for the wrong lead with the windows versions

**Comment by Scintsz** [comment]
@nirvn , just did that:
I installed right now the version 3.3.1 with the name "QField_3_3_1" to not overwrite the default 3.3.8 folder named "QField", and the previews were working, then installed 3.3.2 with the name "QField_3_3_2" and the preview were showing as well. Than tried 3.3.8 again and the preview started working againg. But I did uninstalled and reinstalled Qfield a few times before to see if was a problem with my installation. Could be something with the librarys path?

**Comment by meyerlor** [comment]
@Scintsz did you open the project via "Recently opened Projects" or did you select it every time via "Open Local Project"?  With the former option it tends to show cached views I discovered

**Comment by Scintsz** [comment]
Yes, that was exaclty what was going on. When I open trough "Open Local Project" I can confirm that 3.3.1 works and 3.3.2 don't.
But more than simples cashing views, it seems that some library is used from the last version formaly opened, because if I open 3.3.1 with "Open Local Projects", than open 3.3.2 or 3.3.8 trough "Recently Opened Projects", I can even take pictures with the webcam see the preview.

**Comment by nirvn** [comment]
@meyerlor , @Scintsz , can you try the Windows build here (https://github.com/opengisch/QField/actions/runs/10277841240?pr=5528), I believe this will fix it for you (I just got my hand on a Windows machine and it works for me).

**Comment by meyerlor** [comment]
@nirvn nice, fotos show up and the PDF URL is klickable again - only difference to my Win11 machine is, that it is showing the full path of the document instead of only the filename:
Win11, Qfield 3.8.8:
![grafik](https://github.com/user-attachments/assets/96e8a308-8e6c-40b3-a417-11122da2e45e)


Win10, QField Static Release:
![grafik](https://github.com/user-attachments/assets/9128e1d9-3a23-4686-a49b-3761d6e229b2)
