### ISSUE TITLE
Value Map: description values truncated at '<' character when viewing full list

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#5489]
### Describe the issue
When setting up a Value Map widget, any description with the '<' character is truncated at that point when viewing the expanded list in QField.

### Reproduction steps
1. Set up form with Value Map widget, include '<' character in Description
2. Open form in QField, navigate to field with above Value Map widget
3. Click on magnifying glass next to dropdown list to see full list

### Expected behavior
Description should not be truncated at '<' character.

### Observed behavior
Description is not truncated at '<' character when accessing dropdown list within form, however once you click on the magnifying glass to see the full list, any description with the '<' character is truncated at that point.

### Screenshots and GIFs

![ezgif-3-aea6cdd20d](https://github.com/user-attachments/assets/e4bb4586-6f6a-48da-9dfa-dee930642a15)

Example from attached test project: [Value Map character test.zip](https://github.com/user-attachments/files/16407682/Value.Map.character.test.zip)

### Desktop (please complete the following information)
 - OS: Windows
 - QGIS Version: 3.34.9
 - QFieldSync Version: 4.10.0

### Mobile (please complete the following information)
 - Device: Samsung S10
 - OS: Android 12
 - QField version: 3.3.7 9f449c

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Unsure, but feels recent
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Propably interpreted as html accidentally ...

**Comment by nirvn** [comment]
@she-weeds , this should be fixed by the change this PR (https://github.com/opengisch/QField/pull/5543). If you can test APKs in ~15 minutes, it'd be great.
