### ISSUE TITLE
Problem with upload from Qfield

### ISSUE THREAD

**Issue by fantan61** [opengisch/QField#5494]
I have the following problem with the Qfieldcloud:
I can see my project  "BB_Str in  QGis 3.28 Firenze" data and images on my cell phone, but I cannot download them (not even via USB). The following error message appears:

![20240730_130722](https://github.com/user-attachments/assets/e565744d-322c-4536-9b48-492b5395de9b)

![20240730_130741](https://github.com/user-attachments/assets/edf1f50d-c067-4609-aed4-d5aa221ac3ca)

would be very grateful if you suggested a solution, because the data is very important to me.
fantan61

**Comment by nirvn** [comment]
@fantan61 , that error means you have reached the maximum storage usage for your user account. You can learn how to add additional storage here: 

https://docs.qfield.org/get-started/storage-qfc/
