### ISSUE TITLE
fid field forces manually input every second time I add a feature, although autogenerated (similar to #1480) - since Darién 3.3.7

### ISSUE THREAD

**Issue by harrykomposch** [opengisch/QField#5502]
cannot save new dataset without manually fill in a unique no in the fid-field (although it's autogenerated)  OR after closing the attribute form (trash can) and reenter a new feature! (it works every second attempt)
issue since qfield Darién 3.3.7 and 3.3.8  (not in qgis 3.36.3)

my old projects do not work any more (geopackage; point layer with fid, nr, name)
new test-geopackage does not work

### Reproduction steps
1 open test-layer in edit-mode
2 add new feature
3 cannot save until I have deleted the term 'autogenerate' and entered a unique number
4 close 'add feature'
5 add new feature - now it works as expected

### Expected behavior
field 'fid' should be automatically assigned a unique number by qfield when the feature is saved

### Observed behavior
1st try: qfield forces me to insert a no, otherwise I cannot save the new feature
attribute form: 'not null, unique' (in red, also heading of form is red), on saving: "constraints not valid"
2nd try: attribute form shows an orange heading and fid is autogenerated correctly
3rd try: attribute form is red again (no input without a unique and manually inserted fid)

### Screenshots and GIFs
![Screenshot_20240802-032927](https://github.com/user-attachments/assets/4090b5a4-26ce-415b-9662-7100585a808c)
![Screenshot_20240802-032946](https://github.com/user-attachments/assets/31347514-5e21-4cd0-a639-4f152bedc549)

### Desktop (please complete the following information)
 - OS: Windows 11
 - QGIS Version 3.36.3
 - QFieldSync Version 4.9.1

### Mobile (please complete the following information)
 - Device: samsung tab active pro
 - OS: Android 11
 - QField version: 3.3.8 Darién (5187e v3.3.8 Qt 6.6.3)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@harrykomposch , can you share a sample project?

**Comment by harrykomposch** [comment]
[testprojekt.zip](https://github.com/user-attachments/files/16470420/testprojekt.zip)
(didn't see that zips are allowed)
well, here is a reduced project that shows the behaviour (on my devices)
