### ISSUE TITLE
Qfield 3.3.8 - Issues

### ISSUE THREAD

**Issue by denilsonjesus** [opengisch/QField#5509]
Some observations/doubts that I don't know if it's a Qfield problem or an error in my project:

- 1 - When disabling the native camera (Use native camera) in the Qfield 3.3.8 settings, the resolution and size of the photos become smaller (1920x1080, 261k) when compared to the tablet camera (S6 Samsung, 4128x3096 size 3 to 6 megabytes).

- 1.1 - When activating the native camera (Use native camera) in the settings, the command 'exif( @project_folder || '/' || "Foto_prj", 'Exif.GPSInfo.GPSImgDirection')' does not work, leaving the azimuth with a null value.

- 2 - The command 'exif( @project_folder || '/' || "Foto_prj" , 'Exif.GPSInfo.GPSImgDirection')' , according to the manual, the angle varies from 0 to 360 degrees, but in my practical tests the count varies as follows: 0 to 270 degrees and 0 to -90 degrees.
- 3 - When turning on 'fast editing mode' in the settings, it seems to me that Qfield becomes slower in executing the project. For example, when inserting vertices of a polygon there is a longer delay to release for the next vertex and when closing the polygon there is a longer delay to open the form.

**Comment by nirvn** [comment]
1: QField's next version will come with a resolution picker UI for the non-native camera. That will list all resolutions supported by QField/Qt. You can test the functionality by installing the APK in this PR (https://github.com/opengisch/QField/pull/5520). 

1.1: We have no control over the native camera. If it's not there, it means the OS doesn't add it (that's actually why we added info to the non-native camera to begin with :) )

2: Fixed. The test APK mentioned above should have values from 0 to 360.

3: Are you using remote layers there? Fast editing is a bit of a misleading title. The function insures that a given feature is saved as early as possible, and updated for every single change. So for e.g., if you are digitizing a polygon, starting at the 3rd vertex entered, the feature will be saved then updated every time you add a vertex. That would create lag for slow remote layers. Friendly suggestion: just don't use it :)

**Comment by denilsonjesus** [comment]
Thanks for the responses. Qfield has been progressing very well with your work.
