### ISSUE TITLE
Newly implemented qgis-"current_parent_value"-expression not working in qfield

### ISSUE THREAD

**Issue by koenigherford** [opengisch/QField#5513]
### Describe the issue
The newly introduced '`current_parent_value`'-expression is not working in qfield

### Reproduction steps
1. Create a project with parent (line-) and (geometryless-)child-layer. 
2. Create a virtual field 'length' with expression `round($length,2)` in parent layer
3. Create a field 'amount' with default-value-expression `current_parent_value(  'length' ) `in child-layer
4. Collect some data in QGIS -> works as expected: amount-value in child-layer is filled with the same value like parent layer
5. 
![grafik](https://github.com/user-attachments/assets/a74c1692-bcef-4ec7-8572-d66f77039f48)
6. Export project to mobile device and collect data : amount-default-value stays empty in contrary to qgis
![grafik](https://github.com/user-attachments/assets/ec860612-c529-4452-bc3c-f5f098783b2a)

7. Alterntaively use prdefined test-project (as described before)
[test_current_parent_value.zip](https://github.com/user-attachments/files/16486696/test_current_parent_value.zip)

### Expected behavior
QGIS- and QFIELD-expression-behaviour are identical

### Observed behavior
In QFIELD current_parent_value( ...) is not working

### Screenshots and GIFs
see above

### Desktop (please complete the following information)
 - OS: [Windows]
 - QGIS Version [e.g. 3.38.1]
 - QFieldSync Version [e.g. 4.9.1]

### Mobile (please complete the following information)
 - Device: [e.g. IPAD 10]
 - OS: [e.g. 17.5.1]
 - QField version: [3.38 (51873e v3.3.8)] QT 6.6.3

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [?]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@koenigherford , I believe this PR (https://github.com/opengisch/QField/pull/5515) fixes the issue you've raised here. APKs should show up in the PR within the next 10 minutes for you to try.

**Comment by koenigherford** [comment]
@nirvn , thank you very much for your quick fix!

Tested with android device.
