### ISSUE TITLE
spelling mistake - synchornization instead of synchronization

### ISSUE THREAD

**Issue by MMR100** [opengisch/QField#5523]
When clicking on the cloud logo in QField, if the project is not stored on Qfield Cloud, the text says "The curent project [...] seamless synchornization"

Sorry for issuing a ticket for such a tiny mistake. If there is another way to inform you, let me know.

**Comment by m-kuhn** [comment]
Thank you for reporting it here.
This has been fixed few days ago in https://github.com/opengisch/QField/pull/5376 .
If you find something again, please keep it coming,!
