### ISSUE TITLE
Gpkg - constrains not walid

### ISSUE THREAD

**Issue by birkologus** [opengisch/QField#5526]
Hi all, 
![Uploading Screenshot_20240806_142558.jpg…]()

When trying to digitise new object I can't save my forms as id field has invalid constrains.When second object is digitised it works good. If I set id it can be null I can save and id is filled but it used to work before. 

 It was a default setup and I'm clueless why this happens. Do you have a guess what changed?

I use geopackage with gfield 3.3.8 

Many thanks

**Comment by nirvn** [comment]
@birkologus , fixed already, will be in QField 3.3.9 in the coming ~48-72 hours.

**Comment by birkologus** [comment]
Many thanks
