### ISSUE TITLE
Primary key having Text Edit Widget Type doesn't autoincrement

### ISSUE THREAD

**Issue by nicpitsch** [opengisch/QField#5530]
### Describe the issue

Using the default *Text Edit* Widget Type for the primary key in the latest QField causes *Autogenerate* functionality to fail (it doesn't set the next integer value).

### Reproduction steps

1. Create a new QGIS project.
2. Create a new empty GeoPackage in QGIS using menu *Layer.. Create Layer.. New GeoPackage Layer*.
3. Add a simple geo layer using standards to it like:

![grafik](https://github.com/user-attachments/assets/dd0c4e0b-4b49-4b8b-b31a-0d24ca15b2a4)

4. Add this layer to the project.
5. Deploy the QGIS project and the GeoPackage to QField.
6. Add feature to the above layer. I get this message about missing a unique *Autogenerate*

![grafik](https://github.com/user-attachments/assets/3d8ffca3-b510-4589-bb66-90f8a4558322)

### How to solve the problem

Use *Range* Widget Type in QGIS instead of the default *Text Edit* for the primary key field *fid*.

### Desktop (please complete the following information)

 - OS: Windows
 - QGIS Version 3.38.1

### Mobile

 - Device: Android, e.g. Pixel 6 
 - OS: Android 14
 - QField version: 3.3.8 (51873e)

### Additional information

* Problem wasn't with earlier versions: Yes it wasn't until probably 3.3.7
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@nicpitsch , known regression, will be fixed by a new point release today.
