### ISSUE TITLE
Photos not Geotagged on iOS

### ISSUE THREAD

**Issue by cemno** [opengisch/QField#5532]
### Describe the issue
Photos taken on iOS are not geotagged. Using the same project the photos are geotagged on Android. Geolocation for photos is available on the device when using the regular camera app, so permissions should be set right on the user side. 

#### Additon:
Using the internal camera of qfield instead of the native one also doesn't create geotags, but would not be viable anyway as on that particular iPhone the wrong camera is used (ultra-wide) and can't be changed.

### Reproduction steps
1. Set up a photo layer [as described on the qfield docs](https://docs.qfield.org/how-to/pictures/)
2. Export to Qfield
3. Start the project and load the project
4. Add photo on the created layer through the foto icon
5. Take a foto with an iOS device

### Expected behavior
Geotags should be created as in android and should be shown by the geotag symbol of the media preview.

### Observed behavior
After taking a picture the symbol for geotags of the media preview shows **no** geotag is present, which is correct (confirmed by importing the photo back on the pc)

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.38.
 - QFieldSync Version 4.10.0
### Mobile (please complete the following information)
 - Device: iPhone 13
 - OS: iOS 17.6
 - QField version: 3.3.8 - Darién (51873e)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Unkown
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@cemno , I suspect a feature in upcoming QField 3.3.4 (https://github.com/opengisch/QField/pull/5520) will help you with the wrong camera/resolution. As for geotagging, I assume you've toggled on the geotagging tool buton in the camera as well as turned on  positioning?

**Comment by cemno** [comment]
#### Solved
Thanks for the quick reply. It seems that I did indeed forget to enable positioning for QField. 

In the **non-native** camera the geotagging button was greyed out and not working at first, but after enabling positioning in the map view (by pressing the positioning button) I was asked to give permission and now the geotagging button in the camera can be switched on. 

The different cameras can also be toggled now, I don't know why it didn't work before.

#### Expand documentation
From the Website in [Geotagging](https://docs.qfield.org/how-to/pictures/#geotagging):
> To enable geotagging in case your native OS camera does not support this functionality, follow these steps:

It might be useful to expand the documentation for iOS devices to say that need the non-native camera to get geotags, as currently from a non-developer perspective, an iOS device's native camera is generally capable of geotagging, just not in QField.

#### Further Notes
I'm also looking forward to the upcoming improvements for the internal camera. I hope that the handling of taking a photo vertically or horizontally will also be improved. But is the QField version 3.3.4 you mentioned correct?

Last but not least, thank you very much for constantly improving QField, it really is an application I have always been looking for! :)
