### ISSUE TITLE
Expression behavior differs in QGIS and QField?

### ISSUE THREAD

**Issue by 9ls1** [opengisch/QField#5539]
### Describe the issue
QGIS and QField behave differently for the same expression.

### Reproduction steps
In a value relation where multiple selections are allowed, I have set an expression
![image](https://github.com/user-attachments/assets/df6a42b3-79e1-4fff-9b27-20a71b74a118)

### Expected behavior
In QGIS the field turns "yellow" showing value(s) are expected whenever no check box is checked. I expected the same to happen in QField.
https://github.com/user-attachments/assets/4d4c491a-63bd-4cea-aace-5afe73cc3349

### Observed behavior
In QField everything is fine also when a checked check box is unchecked. The tab should have turned "yellow" again warning the user that at least one check box should be checked.
https://github.com/user-attachments/assets/ebbf7387-b304-4ffc-9aa0-e66a8a273626

### Desktop (please complete the following information)
 - OS: Windows 10
 - QGIS Version3.38.0
 - QFieldSync Version 4.10.0

### Mobile (please complete the following information)
 - Device: Samsung Galaxy Tab Active4 Pro 5G
 - OS: Android 14
 - QField version: 3.3.9 (6e7c2a v3.3.9)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Could you provide a minimal sample project @9ls1 (ideally even with a very simple expression)?

**Comment by 9ls1** [comment]
Set layer "Indikatorer" in edit mode and add a new point.
[jvregistrering.zip](https://github.com/user-attachments/files/16573335/jvregistrering.zip)

**Comment by nirvn** [comment]
@9ls1 , I believe this PR (https://github.com/opengisch/QField/pull/5555) will fix your issue here. APKs will appear in the pull request within the next 15 minutes, give it a try :)

**Comment by 9ls1** [comment]
@nirvn, works great, thanks!
