### ISSUE TITLE
Unable to paste password in Qfield for Mac

### ISSUE THREAD

**Issue by AlDante** [opengisch/QField#5548]
### Describe the issue
QField for Mac neither uses stored information in Keychain, nor does it allow passwords to be copied from Keychain when logging in. This discourages the use of long passwords, reducing security.
### Reproduction steps
1. Start QField for Mac.
2. Paste password into password field
3. Password is not copied into password field.

### Expected behavior
Preferably allow the use of Keychain-stored passwords with QField. If that is not possible for some reason, allow the pasting of passwords into the password field.

### Observed behavior
Password is not copied into password field

### Screenshots and GIFs

<img width="1031" alt="Screenshot 2024-08-11 at 14 13 02" src="https://github.com/user-attachments/assets/4d5cd0c1-951e-4fb0-8abe-8623c88da18f">

### Desktop (please complete the following information)
 - OS: macOS Sonoma 14.6.1 (23G93)
 - QGIS Version not relevant
 - QField Version 030310990 (030310990)

### Mobile (please complete the following information)
 - Device: Not relevant
 - OS: Not relevant
 - QField version: Not relevant

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No idea
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@AlDante , pasting as in ctrl+v or whatever the macos shortcut equivalent is :)  ?

**Comment by VxTedxV** [comment]
> @AlDante , pasting as in ctrl+v or whatever the macos shortcut equivalent is :) ?

⌘ (Cmd) +v ;)

**Comment by AlDante** [comment]
Exactly. ⌘ (Cmd) +v does not work.

**Comment by AlDante** [comment]
⌘ (Cmd) +v doesn’t work, nor does the equivalent of a right-click, nor using Paste from the Edit menu.

**Comment by nirvn** [comment]
@AlDante , that's a bummer. Are u able to paste the password if you click on the little eye icon in that text input area? 

Is pasting broken only for this text input or all inputs (eg the user text input above)?

Glad to hear from a macos user BTW, thanks for taking the time to report this.

**Comment by AlDante** [comment]
@nirvn No, that makes no difference. What you can't see on the screenshot is that "Paste" actually appears in the context menu, but it is greyed out. Pasting doesn't work for either field, neither username nor password.

**Comment by nirvn** [comment]
@AlDante , could this be a clipboard permission / security issue at the OS level?

**Comment by AlDante** [comment]
MacOS normally tells you if an application requires additional permissions. And I can't recall ever having had to grant an app permission to use the clipboard. A quick check in Privacy & Security reveals that there is no such option.

**Comment by m-kuhn** [comment]
Paste works fine here on Ventura 13.6.7 (22G720), also copied from the keychain.

Can you paste something into the other fields (e.g. user name)

**Comment by nirvn** [comment]
Had someone test on Sonoma  14.1.1, pasting worked fine there to:

![image](https://github.com/user-attachments/assets/93a5300a-bcd1-494e-ab21-7d32697cc29d)

**Comment by AlDante** [comment]
I’m on Sonoma. I already tried pasting into the user name, also doesn’t work.On 11. Aug 2024, at 18:06, Matthias Kuhn ***@***.***> wrote:﻿
Paste works fine here on Ventura 13.6.7 (22G720), also copied from the keychain.
Can you paste something into the other fields (e.g. user name)

**Comment by AlDante** [comment]
When you say that you copied from the keychain, do you mean you could use your fingerprint to sign in? Which would be the desired behaviour. Or did you just cut and paste from keychain?On 11. Aug 2024, at 18:06, Matthias Kuhn ***@***.***> wrote:﻿
Paste works fine here on Ventura 13.6.7 (22G720), also copied from the keychain.
Can you paste something into the other fields (e.g. user name)

**Comment by AlDante** [comment]
So what on earth could it be with my setup? Very strange.On 12. Aug 2024, at 04:57, Mathieu Pellerin ***@***.***> wrote:﻿
Had someone test on Sonoma  14.1.1, pasting worked fine there to:
image.png (view on web)

**Comment by AlDante** [comment]
As you can see, all the shortcuts are greyed out on my system. I will try reinstalling, but that won’t be until later today, because I have some other things to take care of first.

If it’s a permissions issue, does anybody (maybe your other Sonoma user) have an idea where I might be able to check that?

￼

**Comment by m-kuhn** [comment]
I only tested copy/paste `⌘ (Cmd)` + `c` / `⌘ (Cmd)` + `v` (also from keychain). This should be working.

For tighter integration with keychain, there is almost certainly something to do.

**Comment by AlDante** [comment]
Copy/Paste should not care where the source string came from, but thanks for checking. Trust, but verify.On 12. Aug 2024, at 10:27, Matthias Kuhn ***@***.***> wrote:﻿
I only tested copy/paste ⌘ (Cmd) + c / ⌘ (Cmd) + v (also from keychain). This should be working.
For tighter integration with keychain, there is almost certainly something to do.

**Comment by AlDante** [comment]
I uninstalled QField (deleted it from Applications) and downloaded it again from the App Store. Same problem. 

As I don't think I'm going to be using QField, and don't really have time to look for the problem, I am happy if we chalk this down to my system or myself being stupid and close the issue.

**Comment by m-kuhn** [comment]
> I uninstalled QField (deleted it from Applications) and downloaded it again from the App Store. Same problem.

Interesting, as far as I am aware, we don't have a macos version published on the app store. Are you able to install the iOS version or is there some other (old?) version lingering around?

**Comment by AlDante** [comment]
The Qfield home page says that it is in the App Store. The App Store version is the iPad version but claims to be compatible, if untested, on the Mac, so I assumed that this was the Mac version. 

My apologies. 

The downloaded version from [here](https://onelink.to/qfield?olbm=1) lets me copy and paste with no problems. 

May I respectfully suggest you mark the iPad version as not visible in the Mac App Store, so it can't be downloaded? And possibly add "Qfield for Mac" somewhere visible to avoid similar problems in the future. 

Thanks everybody for all of your help!

<img width="1292" alt="image" src="https://github.com/user-attachments/assets/753d03c7-b3af-45b6-892e-574a00cdc050">

**Comment by AlDante** [comment]
Now closed.

**Comment by nirvn** [comment]
@AlDante , thanks for alerting us to this, I've disabled apple silicon mac availability (it turned itself on without our knowledge).
