### ISSUE TITLE
The native Android camera does not work. The QFIELD camera does not store GPS data in the JPG exif.

### ISSUE THREAD

**Issue by DaniFH** [opengisch/QField#555]
I keep pictures of some agricultural plots in a form (polygon layer). I know that the photo is of the plot but not of what concrete point. It would be very useful if the photo had the GPS location in the JPG exif

**Comment by JAVIERSIG** [comment]
Hello; the same thing happens to me with the latest version (in the previous one I could not verify it). In the photos that are taken, the coordinates are not recorded, so if you later want to import them into some qgis project, it is impossible ... Is this issue to be solved, or help ?. Regards

**Comment by signedav** [comment]
Hi there 
With the successful crowdfunding the implementation of the new camera functionality is on it's way.

**Comment by signedav** [comment]
After a successful crowdfunding the implementation of the new camera functionality is on it's way.

**Comment by m-kuhn** [comment]
Can you try the current 1.4.1 release with native camera and check if this is fixed?
Some system cameras don't support this out of the box, opencamera should help in those cases.
Thank you.

**Comment by m-kuhn** [comment]
Closed since there is no feedback. This is supposed to be working.
