### ISSUE TITLE
Adding favourite directories doesn't work any more

### ISSUE THREAD

**Issue by monticola2** [opengisch/QField#5575]
### Reproduction steps
1. Go to the file selector and choose "Open local file", then "QField files directory".
2. Now choose the folder you want to add to the "favorites" by long clicking on the directory name (as described in the documentation [here](https://docs.qfield.org/how-to/projects/)).

### Expected behavior
Folder gets added to favorites. In older versions (can't remember which) a pop-up confirmed that the folder had been added after long-clicking.

### Observed behavior
When long clicking a pop-up menu opens with these options: "Export to folder", "Send compressed folder to", "Remove project folder". The folder does not get added to the favorites. 

### QGIS
 - OS: Windows 8.1 Pro
 - QGIS Version 3.34.4
 - QFieldSync Version 4.9.1

### QField (please complete the following information)
 - Device: Xiaomi Mi 10 Lite 5G
 - OS: MIUI Global 13.0.4
 - QField version: 3.3.11 - Darién (f59b22)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes, but cannot remember when
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@monticola2 , interesting, this regressed a long, long time ago, thanks for letting us now.

It is fixed; you can try APKs to confirm it works for you here (https://github.com/opengisch/QField/pull/5580#issuecomment-2298027618).
