### ISSUE TITLE
Add photo watermark functionality to QField's camera

### ISSUE THREAD

**Issue by XuBaocai** [opengisch/QField#5585]
After installing cameras such as Open Camera in the Android system, it is not possible to select them in QField. There are many modified versions of the Android system that cannot set a default camera. It is best to choose the camera to use in QField.

**Comment by nirvn** [comment]
@XuBaocai , as of QField 3.3, QField's own camera (i.e. what is used when you disable native camera) has a camera picker. Did you try that already?

Something to look forward too: in QField 3.4, users will be able to select the _photo size_ too.

**Comment by XuBaocai** [comment]
Very good, and add new features. It would be perfect if we could add watermarks such as coordinates to photos and customize the text.

**Comment by nirvn** [comment]
@XuBaocai , alright, I've transformed this issue into an enhancement request for the QField camera to support text watermarks. It's something that indeed would be quite useful to have in QField, it's probably the only thing left people are missing from OpenCamera ;-)

**Comment by denilsonjesus** [comment]
The Qfield 3.3 camera only has a 16:9 aspect ratio. I would like to know if it is possible to include/enable other options, such as: 4:3, 1:1 and full.

**Comment by nirvn** [comment]
@denilsonjesus , it will be possible in QField 3.4

**Comment by Ipickedausername** [comment]
> @XuBaocai , alright, I've transformed this issue into an enhancement request for the QField camera to support text watermarks. It's something that indeed would be quite useful to have in QField, it's probably the only thing left people are missing from OpenCamera ;-)

This and the possibility to display the compass😇
#5219

**Comment by nirvn** [comment]
@XuBaocai , here we go: https://github.com/opengisch/QField/pull/5596
