### ISSUE TITLE
Happy Mönch, IMU deactivated with averaged positioning

### ISSUE THREAD

**Issue by lucienicolier** [opengisch/QField#5597]
I got an issue using a Happy Survey external receiver. 

I need to survey with the IMU technologize, when doing it with only one measure it works but as soon as I turn on the "enable averaged positioning requirement" and add 5 measures, the IMU turns off and I get wrong survey. 

### Reproduction steps
1. Turn on "enable averaged positioning requirement" with 5 measures
2. Make an IMU survey with an external Happy Survey receiver.

### Expected behavior
The all surveys should be done with the IMU

### Observed behavior
The IMU turns off during the survey

### QField (please complete the following information)
 - Device: Happy Survey Mönch II
 - OS: Android 9
 - QField version: 3.3.11

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@lucienicolier , can you describe what you perceive as reflecting a "deactivated" IMU state?

**Comment by lucienicolier** [comment]
@nirvn, the quality switches to `Fixed RTK + IMU` to `Fixed RTK` and if we are not measuring straight, the point is false.

![image](https://github.com/user-attachments/assets/164d6bbd-14ba-4e27-af1f-e567a1cc0f44)

**Comment by lucienicolier** [comment]
@nirvn with the last version of QField (3.4.1) The IMU is active even with an averaged positioning, but the information is not present on the Quality. 
![WhatsApp Image 2024-09-20 at 15 06 46](https://github.com/user-attachments/assets/5fc178d4-2d5d-43cc-87a9-d777532988f0)
![WhatsApp Image 2024-09-20 at 15 07 07](https://github.com/user-attachments/assets/1bede81f-0584-41e6-a50b-7583835fca84)
