### ISSUE TITLE
Allow the validation of WFS login form with "Enter"

### ISSUE THREAD

**Issue by rbovard** [opengisch/QField#5599]
Is it possible to add the possibility of validating the WFS connection login form with “Enter”?

Currently, we have to click on the check button in the top left-hand corner of the login window, which isn't very intuitive.

![image](https://github.com/user-attachments/assets/cfd6dc5b-1478-4da6-8627-7e592ff770dc)

Thanks a lot!

**Comment by nirvn** [comment]
@rbovard , fixed in upcoming QField 3.4.

**Comment by rbovard** [comment]
Just tested and it works fine, thanks a lot!
