### ISSUE TITLE
pinch zoom not working properly

### ISSUE THREAD

**Issue by rdbath** [opengisch/QField#56]
I encountered a problem using QField with a bunch of spatialite-layers.
After reading your tweet about using spatialite OSM-Data in QField ( https://twitter.com/_mkuhn/status/748622494848917504 ) I gave it a try (with only 600MB and scale dependend visibility).
The data is loaded but the pinch zoom is not working properly anymore. The canvas is flickering when trying to zoom in and is zooming out instead. Then QField is freezing.

I tested it on two different tablets with the same experience:
Sony Xperia Tablet Z2 (SGB521) with Android 6.01 and newest QField-version
and
Samsung Galaxy Note Pro P905 Android 5.02 and newest QField-version.

**Comment by m-kuhn** [comment]
We will be working on general rendering and usability improvements soon. We are currently in contact with sponsors. Possibly we might launch a crowdfunding initiative for this.

**Comment by m-kuhn** [comment]
Related to #51

**Comment by m-kuhn** [comment]
Can you check if this problem persists with 0.8?
