### ISSUE TITLE
Detailed Instructions for Capturing of Photos

### ISSUE THREAD

**Issue by FatherRandom** [opengisch/QField#560]
I've built a project with QGIS 3.6.1 to digitize parking spaces and associated road signs. All is well and works in QField as well except for the ability to take photos.

I followed the sparse information on configuring a data field (type: attachment, relative paths, store file names) for photos. In QGIS this works, I can display the photos with a designated action that reads the stored paths and file names. In QFIELD however, something is amiss. I see the camera button and the missing photo icon. Using the camera button I am able to bring up the camera function and take a photo and hit Save. Unfortunately, it won't be stored properly. In fact, it doesn't appear at all. QField displays an icon with a broken photo afterwards.

So I created a directory named DCIM within my project directory on the phone's memorycard. I took another picture for a point feature that didn't show up either and wasn't to be found by the phone's file manager.

The strange thing is that a photo file name/path *was* stored for the feature in the corresponding shape file! Pointing to the DCIM folder! I could see that after transferring the project back to QGIS.

If I use the sample project concerning the bees I am able to take and save my own pictures. I also tried to run the project from the internal memory instead of the external memory card but that didn't work out either.

Are there detailed instructions for this?

**Comment by VxTedxV** [comment]
What is your project's path ? Must be `SDcard/Android/data/ch.opengis.qfield/...`
Another possible explanation : #157

**Comment by FatherRandom** [comment]
The structure of my project is as follows:
Parkrauminventur
   /Offlinedaten
      /DOP/AerialPhoto.mbtiles
      /Kontrollgebiete/Shapefiles
      /Parkstaende/Shapefiles
      /Parkstandlinien/Shapefiles
      /Pictures
         /Parkstaende/Subfolders/....jpg
         /Parkstandlinien/Subfolders/....jpg
         /Verkehrszeichen/Subfolders/....jpg
      /PSA/Shapefiles
      /Verkehrszeichen/Shapefiles
Parkrauminventur.qgs

My device: Huawei Mate 8 with 512 GB microSDXC card

I've tried both the QField folders (internal and external storage) to no avail. By the way - with the exception of storing photos my project works even when stored someplace else.

#157 shouldn't be the cause, since the field is configured as String of length 254. Works perfectly in QGIS Desktop.

**Comment by FatherRandom** [comment]
Is there a detailed explanation or How To for the configuration of a QGIS project that is designed to take lots of photos and the subsequent use in QField?

**Comment by VxTedxV** [comment]
> I can display the photos with a designated action that reads the stored paths and file names.

With your QGis version, it's native and maybe if you use another way to show images, it won't work in QField. When you configure your field as "attachment", don't forget to set the _integrated document viewer_ as "image". In QGis, you'll see the image in the form mode only with _identify features_ tool.

**Comment by Emic37** [comment]
I encounter the same problem. I used this functionality which works quite well with older versions of qfield and the same project.  But now, I encounter the same behaviour as described here. 
After taking photo, Qfield displays an icon with broken image and I don't find any photo in the internal memory of my smartphone.

**Comment by Emic37** [comment]
Nobody? 
@FatherRandom, do you find a way to fix this problem?

**Comment by FatherRandom** [comment]
No, unfortunately not. As I have no prior working experience with QField, I can't compare with older versions. However, I will try to get my hands on the sample project files (about the bees) so that I can see how this is configured in QGIS. I will also try to obtain an older version of QField to see if that can be made to work.

**Comment by Emic37** [comment]
Ok thanks for your reply. For me, I tried a few things but I obtained no improvement. I'll open a new issue. Maybe someone will have an idea.

**Comment by signedav** [comment]
With the successful crowdfunding the implementation of the new camera functionality is on it's way.
So I mark this issue as bug and we will test it with the new version.

**Comment by m-kuhn** [comment]
Can you try the current 1.4.1 release with native camera and check if this is fixed?
Thank you.

**Comment by m-kuhn** [comment]
Closed since there is no feedback.
Please reopen if appropriate.

**Comment by thjack** [comment]
Matias I am using qfield writing directly to the database and everything is fine.
but the photo remains alone on the cell phone.
because I can only use the attached widget and it is recorded in a folder
I have a bytea field in postgres my idea was to save a photo or better still a short video of 10 seconds for example.
Will you implement this function to record the photo or video directly on the server in a next version of qfield?

Matias estoy usando qfield grabando directamente en la base de datos y todo bien.
pero la foto se queda solo en el celular.
porque solo puedo usar el widget adjunto y que se grabe en una carpeta
tengo un campo bytea en postgres mi idea era guardar ahi una foto o mejor aun un video corto de 10 segundos por ejemplo
implementaras esta funcion de grabar la foto o video directamente en el servidor en una proxima version de qfield?

**Comment by m-kuhn** [comment]
Hi, there is currently no such functionality in the backlog. I also wonder about the latency on the field if we load/store image data through a network connection all the time.
But if this really is something you need, you have the possibility to provide a pull request or ask a quote for support of the binary widget.

On the other hand we are actively working on https://qfield.cloud/ which may be in line with what you want.
