### ISSUE TITLE
qgis plugin geofencing turns itself back on

### ISSUE THREAD

**Issue by gdt** [opengisch/QField#5603]
### Describe the issue

When opening the qfield dialog, geofencing is enabled.  That's a bug as I never asked for it and it should be default off.
I turned it off and saved.  On opening again, it is back on.

plugin version 4.10.1, qgis 3.34.10, NetBSD/pkgsrc.

**Comment by gdt** [comment]
This is likely related to #5601.

**Comment by gdt** [comment]
I edited `gui/project_configuration_widget.py` and deleted all lines with Geofencing in them.   Exiting and restarting qgis, I still see the geofencing checkbox checked, and uncheck/ok/reopen still shows it checked again, but there is no crash.   Also, project properties now opens normally. 

This experiment also relates to #5601.

**Comment by nirvn** [comment]
@gdt , this feels like an error with the libqfieldsync wheel. Did you restart QGIS after upgrading?

**Comment by gdt** [comment]
I had not.  I removed, reinstalled, exited and restarted and it seems ok now.   No crashes, project properties ok, and geofencing not checked.

 (It still feels like a bug that it is throwing an exception that crashes the rest of the properties dialog.  And probably that plugin code is allowed to run after upgrade before restart, if not safe.  But that's not a QFieldSync bug.)
