### ISSUE TITLE
Multiselect lists are not supported in QFIeld

### ISSUE THREAD

**Issue by jhonalex06** [opengisch/QField#561]
Multiselect lists are not supported in QFIeld, but it would be a handy addition to improve the data capture process on the field. For example, when I add the next meta-attribute to map “multi-valent” attributes as arrays: **!!@ili2db.mapping=ARRAY** to the .ili file and generate a Geopackage with QgsModelBaker The layer inside of QGIS has the possibility to visualize the information in Multilist format, but in QField this is not possible.

### Reproduction Steps:
1. Open .ili file
2. Add **!!@ili2db.mapping=ARRAY** before of **Servicios_Publicos : BAG {0..*} OF ServicioPublicoTipo_Ficha_Predio_Servicios_Publicos;**
![Ili_configuration](https://user-images.githubusercontent.com/27906888/55741926-145c5b00-59f4-11e9-84fd-287bd75205ac.png)
3. Use QgsModelBaker to convert the .ili file to Geopackage 
4. Open the form in QGIS and visualize the field: **Servicios_Publicos.**
5. Followed, generate a project to QFieldSync and load the project in QField.
6. Open the form in QField and visualize the field: **Servicios_Publicos.**

### Observed behavior:

I can see support for Multi Select list in QField.

### Screenshots and GIFs

![result_multi_lists](https://user-images.githubusercontent.com/27906888/55741947-20481d00-59f4-11e9-8a7a-0666555ab123.png)

**QField version:** v1.0.3

Do you plan to include this specific widget in QField?

.ili file: [Captura_Alfanumerica_V0_1.zip](https://github.com/opengisch/QField/files/3055412/Captura_Alfanumerica_V0_1.zip)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
Implemented with this #600
Thanks.
