### ISSUE TITLE
Updating QField Sync to Version 4.10.1 in QGIS causes Trend Micro to remove and quarantine QGIS

### ISSUE THREAD

**Issue by HeatherHillers** [opengisch/QField#5613]
I was running QGIS 3.36.3 Maidenhead and updated QField Sync to the latest version, 4.10.1.
This caused qgis-bin.exe to be immediately deleted and put into Quarantine by my organisation's Antivirus Trend Micro.   

![image](https://github.com/user-attachments/assets/f2b6751a-575d-4aa3-8509-c98592928f18)
(it is called qgis-bin_osgeo.exe because I have a qgis-bin.exe that sets global environment variables and calls a copy of the original qgis-bin.exe which is called qgis-bin_osgeo.exe.  I promise it is qgis and not some wierd thing.)
Clicking on Details gives nothing useful.  It is just a link to the Trend Micro marketing website

I updated other plugins today (AnotherDxfConverter, Plugin Reloader) without any problems.

### Reproduction steps  
No projects loaded.  
Have Trend Micro Virus Scanner running  
Open the plugin manager  
update QField Sync

### Observed behavior
Directly after i clicked on the update plugin button for QField Sync, QGIS closed.  I got an alarm from the Virus Scanner.  QGIS could not be restarted because the executable had been removed from the bin directory.

### QGIS 

QGIS-Version
3.36.3-Maidenhead
QGIS-Codeversion
2df96554
Qt-Version
5.15.13
Python-Version
3.12.3
GDAL-Version
3.9.0
PROJ-Version
9.4.0
EPSG-Registraturdatenbankversion
v11.004 (2024-02-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.45.1
PDAL-Version
2.6.3
PostgreSQL-Client-Version
16.2
SpatiaLite-Version
5.1.0
QWT-Version
6.2.0
QScintilla2-Version
2.14.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
AnotherDXF2Shape
1.3.2
ImportPhotos
3.0.6
Mergin
2024.2
nominatim
1.4.5
pg_raster_import
3.2.0
plugin_reloader
0.10
processing_saga_nextgen
1.0.0
profiletool
4.2.6
crayfish
3.6.0
db_manager
0.1.20
ev_anlieger
0.1
ev_bde
2.0
ev_cat
3.0
ev_einwohner
2.0
ev_fdb
0.1
ev_flaechensumme
0.1
ev_g2_schadenspotenzial
0.1
ev_ganglinien
1.0
ev_gd_bohrprofile
0.3.2
ev_gefaelleinterpolation
0.1
ev_gwanalysis
0.1
ev_imagemapplugin
0.1
ev_image_processing
0.1
ev_infilsum
0.1
ev_kanaldatenbank
0.1
ev_kartierung
0.1
ev_llp
0.1
ev_mstinfo
1.0
ev_nasim
0.1
ev_pegeldaten
0.1
ev_profil_tool
0.0.1
ev_project_check
0.1
ev_revier_db
1.0
ev_revier_knoteninfo
1.0
ev_revier_modell_daten
0.7.0
ev_slope_signature
0.1
ev_sumfoerd
0.1
ev_veg_gang
0.1
ev_wiener_filter
0.1
geocsv
1.0
grassprovider
2.12.99
GroupStats
2.2.7
latlontools
3.6.20
MetaSearch
0.3.6
processing
2.12.99
Qgis2threejs
2.7.3
qkan
3.3.7
QNEAT3
1.0.5
VoGisProfilTool
3.0.2

### QField (please complete the following information)
QField Sync 4.10.1

### Additional information
* Previeous Versions of QField Sync had no issues, in combination with the current QGIS setup. It only happened on update.
* Problem can be reliably reproduced, doesn't happen randomly: I cant reproduce.  I deleted the plugin when the event happened and rebooted my machine, then copied the executable from another machine to restore it.  After that i tried to install QField Sync and that caused no problems.  I also tried a reinstall and that caused no problems.  It seems to only have happened on the update from the old version to the new.  And I no longer have the old version, because it was deleted on update.  I cant even say what version it was, except that I downloaded that Version after Tartu in July, also on the same Maidenhead installation.
* Problem happens with all files and projects, not only some files or projects: No files or projects were used.

**Comment by m-kuhn** [comment]
qgis gets repeatedly flagged as dangerous by virus scanners, normally the virus scanner companies update their signatures when they find out it's a false alert (qgis mailing list has various related discussions). Unless we have more information, what would be wrong on qfieldsync side we cannot do anything.

If you (or someone else) can provide more information, we'll be happy to have a look.

**Comment by gdt** [comment]
@HeatherHillers What happened when you reported this as a bug to Trend Micro?  Can you add a link to the bug in their public bug tracker?
