### ISSUE TITLE
Add photo from tablet gallery/photos

### ISSUE THREAD

**Issue by KirstenReilly** [opengisch/QField#562]
It would be useful to be able to add images from the tablets gallery/photo album, as sometimes survey photos might be taken outside of QField.

Is this a function that could be added?

**Comment by m-kuhn** [comment]
Hi @KirstenReilly 
This is definitely something that could be added.
Can you contact us on info@opengis.ch to discuss the details?
Thanks!

**Comment by m-kuhn** [comment]
@signedav is this fixed?

**Comment by signedav** [comment]
Yes
