### ISSUE TITLE
QField upload to Cloud

### ISSUE THREAD

**Issue by Flitz-ide** [opengisch/QField#5630]
### Describe the issue
[A clear and concise description of what the problem is.]
When I try to synchronize my QField Project from my Phone there's a network error and the Upload is being stopped.

### Reproduction steps
1. [Go to the QField App]
2. [Click on 'QFieldCloud projects']
3. [Scroll down to 'open the specific file']
4. [Click the blue cloud to get to the QFieldCloud]
5. [Tap "Symcjronize"]

_Add a simple sample project if it requires a specific configuration_

### Expected behavior
[A clear and concise description of what you expected to happen.]
When I tried to upload the File from my Phone to my Laptop/the Cloud the first time I was able to download the file on my Laptop from the cloud to work on it.

### Observed behavior
[A clear and concise description of what actually happened.]
Now the Project from my Phone isn't connecting to the cloud. 

It says: Packaging job finished unsuccessfully for ´Kartierung Spandau´. [HTTP/402]
https://app.qfield.cloud/api/v1/ Server Error.
{"code":"over_quota","message":"Quota error"}

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]
![WhatsApp Image 2024-09-09 at 18 13 38](https://github.com/user-attachments/assets/b2d4f872-9057-44a0-ad02-693dc432b0df)

### QGIS (please complete the following information)
 - OS: [Windows 10]
 - QGIS Version [e.g. 3.38]
 - QFieldSync Version

### QField (please complete the following information)
 - Device: [iPhone 10]
 - OS: [iOS- Version 17.6.1]
 - QField version: [Enter QField version here including build number found in the about screen after the release name example 3.0.0 (10200993)]
3.3.11 - Darién (f59b22 v3.3.11)
Qt 6.6.3
### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]
username: burdakca
File Name: Kartierung Spandau

**Comment by SeqLaz** [comment]
Hi @Flitz-ide ,

The error message indicates that the project trying to synchronize has exceeded its storage limit.

For more information, please visit: https://docs.qfield.org/get-started/storage-qfc/
