### ISSUE TITLE
Raster graphics as background map

### ISSUE THREAD

**Issue by jimmyhenne** [opengisch/QField#565]
I recently updated QField from 1.0.0-rc3 to 1.0.3 and an exisiting and former working project doesn't run properly anymore.
The project contains several georeferenced aerial photos (.tif) which are stored on the internal memory (no SD-card) under 
"Tablet\Android\data\ch.opengis.qfield\files\Projekte\Luftbilder\2018-05". When loading the project none of the layers containing the photos can be loaded.
The error message shows the layername (e.g. 0074) and the source (e.g. ./Luftbilder/2018-05/0074.tif). But the files are there indeed and a downgrade to 1.0.0-rc3 "solves" the problem.
Where am I wrong?

**Comment by EmilyNGH** [comment]
We are having the same issue with .tiff. Using an identical second tablet with an earlier qfield version installed caused us no problems. Using a geopackage instead was our work around.

**Comment by suricactus** [comment]
Is this still an issue?
