### ISSUE TITLE
Relation from the table without geometry to the table with geometry doesn't create the geometry.

### ISSUE THREAD

**Issue by jhonalex06** [opengisch/QField#5662]
### Describe the issue

I created a project with a relation many to many between the table 
_(CCA) Punto_ and the table _(CCA) Predio_, the pivot table between these tables is _cca_predio_punto_. When I try to create a new feature related to the table _(CCA) Predio_, QField doesn't allow me to create the geometry so the feature can't be saved.

### Reproduction steps
1. Open Project.
2. Edit mode.
3. Add new feature from (CCA) Predio
4. Fill the mandatory attributes first tab.
5. Chose the second tab cca_punto.
6. Add new feature
7. Notice doesn't allow to create the geometry.
8. Fill the form.
9. Confirm changes.

Project file for testing: [basic.zip](https://github.com/user-attachments/files/17037108/basic.zip)

### Expected behavior

QField should allow the creation of a new geometry feature in many-to-many relations.

### Observed behavior

QField doesn't allow creating a feature with geometry in a relation of many-to-many.

### Screenshots and GIFs

![result_reduced](https://github.com/user-attachments/assets/41e76da2-4fc8-4fe0-b0a9-91c98d581312)

![error_geom](https://github.com/user-attachments/assets/ddb76582-c4de-4d8d-b69d-0d85d2b511f5)

### QGIS (please complete the following information)

 - OS: Ubuntu 22.04.4 LTS
 - QGIS Version 3.34.7
 - QFieldSync Version: No use QFieldSync

### QField (please complete the following information)

 - Device: Samsung Galaxy S24 Ultra
 - OS: Android 14
 - QField version: 3.4.1 - Ebo (c28cef)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by jhonalex06** [comment]
Hello @nirvn excuse me bugging you, I just would like to know if you have opportunity to check this issue and if you consider it is doable the fix?

Thank you

**Comment by nirvn** [comment]
@jhonalex06 , thanks for the good issue reporting and the test project, it made is very easy to identify what was wrong here.

A fix has been found. If you could test the APKs that will show up in this PR (https://github.com/opengisch/QField/pull/5807) to confirm things now work as you expected to be, it'd be useful.

**Comment by jhonalex06** [comment]
> @jhonalex06 , thanks for the good issue reporting and the test project, it made is very easy to identify what was wrong here.
> 
> A fix has been found. If you could test the APKs that will show up in this PR (#5807) to confirm things now work as you expected to be, it'd be useful.

@nirvn Amazing, I am glad the report and the test project help 👍🏾 , I am going to test the APKs, count on it.
