### ISSUE TITLE
The points simbology don't see in the qfield

### ISSUE THREAD

**Issue by nes74-bh** [opengisch/QField#5664]
The points don't see in the screen on my cellphone when i add a new object in QField 3.4.0. But, in my QGIS 3.34.7 i can see when i add a point.

I make a expression in symbology with "basado en reglas" and i make 2 condicionals
 "Cat_arbol"  =  'aprovechable' : red point 
 "Cat_arbol"  =  'semillero' : green point 

In qfield, add the new point but is imposible see. the opacity is 100% by default

**Comment by nirvn** [comment]
@nes74-bh , we'll need a sample project to see if there's a problem with QField itself.

If you have a rule based renderer and your new points do not match either of the rules, they will be invisible.

**Comment by nes74-bh** [comment]
Hi Mr. Mathieu Pellerin

This is a sample project of what I talked about.
If you have a rule based renderer and your new points do not match either
of the rules, they will be invisible.
that's exactly what happens to me,but i don't know what part is wrong.
Because in the qgis go well, but qfield is invisible.

I hope you can help me, thank you in advance. I look forward to hearing
from you.

**Comment by nirvn** [comment]
@nes74-bh , GitHub doesn't support email attachments, you'll need to attach your sample project using it's web interface using your browser.
