### ISSUE TITLE
Tracking line not recording m value when Positioning source is external device

### ISSUE THREAD

**Issue by aghiraldi** [opengisch/QField#5671]
In a line layer that records the trace, I try to insert ‘Timestamp’ or ‘Elapsed dtime’ in the m value. This works when the positioning is internal, but when the external device is used, m is 0.

### Reproduction steps

Preparing the project in QGIS : 
1. Create a lines layer + activate tracking in the qfield parameters (one point every 5 seconds, for example)
2. Choose ‘Elapsed time’ as Measure (M) vallue attached to vertices

Use Qfield on the tablet to record tracking lines using 2 positioning methods:
 A : internal device
 B : external device - in my case a Bluetooth (NMEA) : the SXBlue II GNSS

Synchronise the data. Explore in QGIS the lines and see the M values of the nodes.
 - when recording with positioning according to A, values in seconds are well recorded
 - when recording with positioning according to B, the M value contains zeros.

Recording M values should work in both cases A and B.

### QGIS
 - OS: Windows
 - QGIS Version 3.34.11
 - QFieldSync Version 4.10.1

### QField
 - Device: Samsung Galaxy Tab Active 5
 - OS: Android 14
 - QField version: 3.4.1 - Ebo build nummer c28cef

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: ?
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

QFieldCloud project : grande-caricaie / micromys (not public)

**Comment by aghiraldi** [comment]
Oops! This may not be a Qfield bug.

My new test with this additional case : 
C: external device - Bluetooth NMEA - EOS Arrow 100

The timestamp record is written correctly in the M value.

**Comment by nirvn** [comment]
@aghiraldi , shall we close this bug then?

**Comment by aghiraldi** [comment]
Yes, please.
Thank you.

Alexandre Ghiraldi

________________________________
De : Mathieu Pellerin ***@***.***>
Envoyé : vendredi, septembre 27, 2024 7:55:41 AM
À : opengisch/QField ***@***.***>
Cc : Alexandre Ghiraldi ***@***.***>; Mention ***@***.***>
Objet : Re: [opengisch/QField] Tracking line not recording m value when Positioning source is external device (Issue #5671)


@aghiraldi<https://github.com/aghiraldi> , shall we close this bug then?
