### ISSUE TITLE
low resolution photo

### ISSUE THREAD

**Issue by RAFALCO** [opengisch/QField#5672]
Since version 3.4.1 it seems impossible to take photos with the phone's definition. They are all in low resolution. (300-500 kb)
With version 3.4.0 the photos are several MB in size.
This problem exists with my personal projects but also with the "bees" example project.
 Do other people have this problem?
thanks.

**Comment by nirvn** [comment]
@RAFALCO , setting the resolution via the top right tool button doesn't help? Are you sure the problem didn't occur in 3.4.0?

**Comment by RAFALCO** [comment]
the definition setting does not affect the final resolution.
![Screenshot_20240923_135441 1](https://github.com/user-attachments/assets/2c2b0fb8-3e80-4de4-992f-fc83387bfa2b)
the definition of the photos was total on the previous versions.

**Comment by nirvn** [comment]
@RAFALCO and if you revert to 3.4.0 manually (by installing the APK on the github releases page), is it working for you?

**Comment by RAFALCO** [comment]
sorry but on my phone it is impossible to install an apk

**Comment by nirvn** [comment]
@RAFALCO , I suspect this is the result of a need for QField to downgrade to Qt 6.6.3 at the end of the last development cycle. If you enabled native camera in your settings panel, does it help?

**Comment by RAFALCO** [comment]
That’s exactly it!
You had to activate “Use native camera”.
Problem solved.
Thank you so much.
