### ISSUE TITLE
Multi-editing of attributes makes QField crashed on iOS, and edits only one attribute on Android

### ISSUE THREAD

**Issue by bordoray** [opengisch/QField#5677]
### Describe the issue

When editing multiple features attributes, QField crashes on iOS when taping "save edits" ✓ check button (iPhone and iPad).
On Android, taping save edits does not make QField crashed, but not all selected features but only one feature has been edited.

### Reproduction steps
1. On QField Appli, Open project (has also been tested on "BeeFarming" demo project
2. Select multi features of one layer (e.g. 3 features).
3. Tap on edit attributes
4. Edit one attribute
5. Tap on ✓ button on the top-left of the edit box

- On iOS (iPhone, iPad), QField crash without saving edits.
- On Android, a popup like "Edit has been saved" appeared, but only 1 of the 3 selected features has been correctly edited.

### Expected behavior
- On iOS, QField to not crash.
- On iOS and Android, Edits to be correctly saved when selecting multifeatures.

### Observed behavior
- On iOS (iPhone, iPad), QField crash without saving edits.
- On Android, a popup like "Edit has been saved" appeared, but only 1 of the 3 selected features has been correctly edited.

### Screenshots and GIFs

<img src="https://github.com/user-attachments/assets/3221f1dc-8b9c-42bb-bcfb-8d951bc3abad" width="250" />

### QField (please complete the following information)
 - Devices: iPad, iPhone, Android
 - OS: iOS 17.4.1, Android 12
 - QField version: 3.4.1 Ebo

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Probably. Our customer said that QField did not crash in a recent past.
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Probably

**Comment by m-kuhn** [comment]
Confirmed the Android behavior

**Comment by nirvn** [comment]
Already fixed (https://github.com/opengisch/QField/pull/5660), will be part of next point release.
