### ISSUE TITLE
When embedding QML charts QField fails evaluating expressions containing line breaks

### ISSUE THREAD

**Issue by nirvn** [opengisch/QField#5688]
### Discussed in https://github.com/opengisch/QField/discussions/5684

<div type='discussions-op-text'>

<sup>Originally posted by **lp-dj** September 27, 2024</sup>
The attached code [code_with_linebreak.txt](https://github.com/user-attachments/files/17165140/code_with_linebreak.txt) is rendered correctly in QGIS in a QML widget as a bar chart. In QField all bars remain empty.

After some (much) trial and error I realized that QField has problems with line breaks within an expression.evaluate().

The - in my eyes a bit more difficult to read - code [code_without_linebreak.txt](https://github.com/user-attachments/files/17165141/code_without_linebreak.txt) is now also rendered correctly in QField

![Screenshot_20240927-152316](https://github.com/user-attachments/assets/a0482c81-81dc-43fe-9b39-7745ee70f34a)

Is this already a bug? Would I have had a chance to find out somewhere about the syntax QField needs to get the same result as QGIS?

With many thanks and best regards

By the way: Is there actually a way to use the "array_foreach" function in a nested manner in order to significantly reduce the code (e.g. like here: [array_foreach_nested.txt](https://github.com/user-attachments/files/17165175/array_foreach_nested.txt) )? If so, how do I refer specifically to the `@element` of the different levels?
</div>

**Comment by nirvn** [comment]
@lp-dj , thanks for spotting this issue, fix here: https://github.com/opengisch/QField/pull/5689

**Comment by lp-dj** [comment]
@nirv, Thank you for fixing the problem so quickly. Tested your APK, now both variants work, with and without line breaks.
