### ISSUE TITLE
"Mode" button in main menu missing

### ISSUE THREAD

**Issue by quadragmbh** [opengisch/QField#569]
I just downloaded QField and opened a .qgs-project. All my layers were there, looked good. As soon as i wanted to start working I realised I couldn't switch to digitalising mode, because in the main menu the button to switch between the modes is missing...

### Reproduction Steps:

1. Open Main Menu
2. Look for "mode" - button

### Expected behavior:

Find "mode"-Button

### Observed behavior:

No "mode"-Button

![grafik](https://user-images.githubusercontent.com/49752510/56357359-d7564c80-61db-11e9-869b-7771821f3f4b.png)

**QField version:** 1.0.3 Matterhorn (10003991)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Never had an older version
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by 3nids** [comment]
There is now a toggle button next to the menu button where you can enable digitizing.
