### ISSUE TITLE
Editing not working on Samsung TAB S2 8"

### ISSUE THREAD

**Issue by ludodo** [opengisch/QField#57]
Hello,

We are using two different machines : 
- samsung tab S2 8", android 5.0
- smartphone Crosscall trekker X2 android 4.4
Project and data are the same on both machines on SD card.

With the smartphone, we manage to edit points, lines and atributes. Nevertheless with the tablet, editing doesn't work. With the last Qfield version (0.7.4) we can read this log :
Cannot start editing
Feature could not be added
Could not save changes. Rolling back

Any ideas ?
Thank's for answer

**Comment by m-kuhn** [comment]
It's problem related to external SD card and newer android versions, see #32

You will also find the workaround in there:
https://github.com/opengisch/QField/issues/32#issuecomment-231047800

**Comment by m-kuhn** [comment]
I opened #58 to tack this issue
