### ISSUE TITLE
QField on iOS Crashes after logging in to Postgres server

### ISSUE THREAD

**Issue by jflgators** [opengisch/QField#5705]
### Describe the issue
Before the newest update, I was able to connect to my postgresql server with the connection details saved in the project. Since the newest update prompting the user to fill out the credentials, QField has crashed every time I put the correct credentials in.

### Reproduction steps
1. Load qfield project onto device using cable export. Set relevant layers to directly access data source.
2. Open the project on the device
3. When prompted for username and password enter them.

_Add a simple sample project if it requires a specific configuration_

### Expected behavior
Load into the project

### Observed behavior
Application crashes on device if the correct username and password are entered. If the credentials are not correct it prompts you to renter them like it should.

### QGIS (please complete the following information)
 - OS: Windows
 - QGIS Version 3.28.15
 - QFieldSync Version 4.10.1

### QField (please complete the following information)
 - Device: iPhone 11
 - OS: iOS 17.6.1
 - QField version: 3.4.2

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: I have only tried one project so far

**Comment by nirvn** [comment]
@jflgators , are you able to check if crash also occurs on an Android?

**Comment by jflgators** [comment]
@nirvn I may be able to today. If not I can definitely do so tomorrow.

**Comment by jflgators** [comment]
@nirvn I was able to test my project on android as well as on Qfield for windows today. The project opens and prompts the user for credentials then loads the layer as it should. On my iPhone however I did not get any crashes today but I was unsuccessful in logging into the server and viewing the data.

When the app is given the wrong credentials or no credentials on iPhone it prompts the user for the credentials again as it should. When the app is given the correct credentials it attempts to load into the project but every time it tries to render the scene I get a message in the log saying "Connection to database failed connection to server at "xxx.xx.xxx.xxx", port 5432 failed: fe_sendauth: no password supplied."

**Comment by jflgators** [comment]
A weird detail that I've noticed with this bug is that the app works perfectly fine if I'm on the same LAN as the server and connect to it with the local IP. The issue only occurs when I'm not on the same network and I try to connect using the public IP. I have confirmed this is not an issue with the server setup as I can access it through QGIS on my home computer just fine.

**Comment by nirvn** [comment]
@jflgators , did QField 3.4.4 improve the situation for you ?

**Comment by nirvn** [comment]
@jflgators , apologies, I hadn't realized 3.4.4 was not released on iOS until _yesterday_; has the situation improved on this new version?
