### ISSUE TITLE
QFieldCloud Synchronize & Push Changes not working as expected

### ISSUE THREAD

**Issue by mottensmann** [opengisch/QField#5708]
### Describe the issue
Recently, I experience problems to synchronize and push changes via QFieldCloud. When clicking on `Synchronize` or `Push changes` there is no apparent reaction. Similarly, automatic pushes after 30 minutes are not executed anymore. The behavior is found on several projects and across devices. 
As a workaround, I have to close and reopen the project each time on QField. Then `Synchronize` or `Push changes`  work once, and the steps have to be repeated after entering new data. 
The unexpected behavior occurs since a few weeks, but I can not trace back since when exactly. 

Any ideas to solve it are most welcome!

### QGIS (please complete the following information)
 - OS: Win 11
 - QGIS Version 3.34.9
 - QFieldSync Version 4.10.1

### QField (please complete the following information)
 - Device: Galaxy S20+ & Galaxy Tab Active2
 - OS: Android 13 & Android 9
 - QField version: 3.4.2-Ebo (bc25d0 v3.4.2)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Not sure!
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by BoswachterMarc** [comment]
I am having the same issue, especially with a community project, sometimes with another project.
In my experience, the problem arises when you log in/start QField offline and afterwards want to push/sync online.
When I start online, make changes and then push or sync there is no problem.

The community project - to replicate the issue - can be found under my username with the title 'Vrijwilligers_Miradal'.
I think it is a regression in the latest 3.4.1 and 3.4.2 Ebo QField versions.

**Comment by BoswachterMarc** [comment]
@nirvn I did two tests with the community project. It seems to work now. I can test more extensively tomorrow.

I also previously experienced that when I started QField offline, online maps (e.g. WMS) would no longer load when I went online. That used to work. Perhaps this is related to the error you now corrected? If necessary, I will create a new issue for this.

**Comment by nirvn** [comment]
@BoswachterMarc , online maps like WMS and PostGIS will "heal" themselves if you first opened the project offline as they are marked invalid when unable to connect (it's _not_ the case for XYZ layers though, those will work).

**Comment by nirvn** [comment]
@mottensmann , did QField 3.4.3 fix the issue for you?

**Comment by mottensmann** [comment]
@nirvn, yes, all works fine again. Thanks for this very quick fix!
