### ISSUE TITLE
QField doesn't save captured photos

### ISSUE THREAD

**Issue by Emic37** [opengisch/QField#571]
I can't add photo to an object. QField takes photos and add the path and the name of the file but it seems QField doesn't save the file. QField displays an icon which annunce it can't found the file. And indeed, the file can't be found in memory. The problem is probably similar that this issue #560 .

### Reproduction Steps:

1. [Open project with image widget]
2. [Select an object and open form]
3. [Choose image widget and push button to add image]
4. [Take a photo and save it]
5. [Save the project and open it using Qgis. The path and the name of the photo were saved, but not the file]

### Expected behavior:

Normally, photo should be saved in the DCIM directory, as it configured in Qgis.

### Observed behavior:

When I take a photo and save it, photo are not displayed by QField and it seems any image isn't saved in memory. 
When I open my project with Qgis Desktop, the name and the path corresponding the photo taked in QField is displayed in the field. But no photo... 

If I try to add a photo with Qgis Desktop, all works perfectly in Qgis but not in QField. QField displays icon of breaking image. 

### Screenshots and GIFs

The first image was added with Qgis Desktop and the file is in the DCIM repertory. The second was taked with QField but the file can't be found in memory. 
![Screenshot_20190425-123821_QField](https://user-images.githubusercontent.com/2921424/56734101-409d0900-6762-11e9-8575-8565bdce3828.jpg)

In Qgis Desktop, we can see all seem normal. Clicking on link, Qgis opens photo in external viewer. It works for the first image but not for the second. But this behavior is surely normal : first file exist in the DCIM directory, but not the second.
![qgis_photo_screen](https://user-images.githubusercontent.com/2921424/56735381-9921d580-6765-11e9-9dc1-95a78cd2d62d.JPG)

**QField version:** [1.0.3]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [I don't know]

I hope I was clear and have clearly described problem. @m-kuhn @3nids @signedav I remain to your disposal if you want more informations. Thanks in advance.

**Comment by m-kuhn** [comment]
Thanks for the report. We are currently planning a revival of the integrated camera which I hope will also fix this issue. Would you be avialable to help sponsor this work?

**Comment by VxTedxV** [comment]
Related to #560 ?

**Comment by Emic37** [comment]
Ok. Good new ! I gladly could to help sponsor this work or another, but personally and to the extent of my means...

**Comment by signedav** [comment]
With the successful crowdfunding the implementation of the new camera functionality is on it's way. 
So I mark this issue as bug and we will test it with the new version.

**Comment by m-kuhn** [comment]
Can you try the current 1.4.1 release with native camera and check if this is fixed?
Thank you.

**Comment by VxTedxV** [comment]
Still buggy under Android 9 :
At first try (without GPS enabled), camera launched, picture is taken but after confirmation, QField came back to launch screen.
Second try, it worked.
Third try (with GPS enabled), camera launched, picture is taken but after confirmation, QField quit without prompting (but still opened in processes).
Fourth try, it worked.
Each photo taken is stored even if experiencing a crash but none of them contains GPS data (geotagging in the native camera is on).
Note : camera interface in QField looks stripped-down compared to native camera app

**Comment by m-kuhn** [comment]
Thank you for the feedback. We will have a look at it and get back for further information.

>  Note : camera interface in QField looks stripped-down compared to native camera app

For what is known so far, this is an issue of the camera. Could you try the opencamera app instead of the native app?

**Comment by RobiFag** [comment]
I have just tested the new beta version with Android 8 and the photos captured with the native camera are still not saved. Everything works fine without using the native camera (DCIM folder is created within the project folder and the images are stored in it).

**Comment by RobiFag** [comment]
I made other tests (Android 8) and I noticed that the native camera saves the photos only if the DCIM folder already exists in the project folder. While using the non-native camera the DCIM folder is automatically created, if not present in the project folder, and the photos are correctly saved.

**Comment by SumoJoe66** [comment]
Help! I have the same problem here. I tried with both native and QFIELD camera, but I still can't find the DCIM folder with the pictures I took...

FYI, here are the steps I followed:

I installed QFIELD on my mobile phone (LG G5) on March 31 2020.
Created a QGIS project in which I added a single shapefile (point) with 1 field for photo.
Exported QGIS project to QFIELD.
Opened the project in QFIELD
Digitized 1 feature point and took a photo with native camera (I can see the picture in the form and the file path DCIM\JPEG20200331_53536727.JPG)
Digitized 1 feature point and took a photo with QFIELD camera (I can see the picture in the form and the file path DCIM\JPEG20200331_5686980.JPG)
Imported the QFIELD folder on my laptop and synchronized in QGIS (I can see the 2 new feature points with DCIM folder path)
DCIM folder can't be found in the imported folder.

**Comment by signedav** [comment]
Hi @SumoJoe66 

This issue is about that the photos cannot be saved in the folder on the mobile, because the DCIM folder has not been created. This is fixed.

What you describe is that the picture can be saved on the mobile folder but on synchronization with QFieldSync the photos are not copied to the original project, correct?
This has not been integrated until this week. The PR is open but not yet merged and released https://github.com/opengisch/qfieldsync/pull/142

**Comment by SumoJoe66** [comment]
Hi @signedav 

Correct. Sorry for that misunderstanding.

I have to manually copy/paste the DCIM folder from the mobile phone to the original project. No big deal, but will be great when fixed and released. Any insight on when it will be released?

Thanks!

**Comment by flotschi2004** [comment]
I have a similar issue. After taking the photo I get a message 'Value "DCIM/.... jpg" NOT NULL could not be converted to a compatible value or field nnnn(String).  However, a photo is stored in a DCIM folder - any advice how to solve?

**Comment by cartophyl** [comment]
Hi ! We have fixed this issue by changing the default date format for pictures in the *.qgs file from 

photo_naming value="{&quot;photo&quot;: &quot;'DCIM/photo_'||now() 
to 
photo_naming" value="{&quot;photo&quot;: &quot;'DCIM/photo_'||format_date(now(),'yyyy_MM_dd_hh_mm_s_zzz')

Best regards.
Yann aka Cartophyl

**Comment by roydenyates** [comment]
> Hi ! We have fixed this issue by changing the default date format for pictures in the *.qgs file from
> 
> photo_naming value="{"photo": "'DCIM/photo_'||now()
> to
> photo_naming" value="{"photo": "'DCIM/photo_'||format_date(now(),'yyyy_MM_dd_hh_mm_ss_zzz')
> 
This is deserving of some attention, perhaps in docs, once confirmed.

I have a device on Android 10, LineageOS and a Qfield  project takes multiple photo records just fine, with the renaming having the date format as 'hh:mm:ss'. That reads well.This format is what now() delivers as default.

A device on Android 11, Moto Stock ROM, with exactly the same project, will not save native app photos in the DCIM folder even if it does capture the rename format. The in-house QFiled camera will save the image but the renaming fails.

 Changing the rename  date format to 'hh_mm_ss' as **cartophyl** noted (thanks!) gets everything working.

So Android 10 --> 11 may catch out folk in this way, being more picky about characters in file names.

**Comment by dto** [comment]
Just to let you know, on android 11 I had to use 'hh_mm_ss' for the photos to upload properly, so this is still an active issue. You may want to address it in the documentation, if you haven't already!

> Changing the rename date format to 'hh_mm_ss' as cartophyl noted (thanks!) gets everything working.
