### ISSUE TITLE
Language localisation does not work "out of the box"

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#5744]
Hello, 
on my Android devices the localisation of QField's UI never worked after a fresh install - UI is always in englisch, despite my devices beeing german. I know i can change the language via settings which is working fine then - but i think it should be german right after install, as it is the system locale.

Thanks for looking into it!

**Comment by nirvn** [comment]
@meyerlor , can you tell us what value you see when you open the QField settings' variables tap for the qgis_locale global variable? E.g. here I see 'en':

![image](https://github.com/user-attachments/assets/1486f12b-5e47-40c8-95ea-b55f51f726b6)

**Comment by nirvn** [comment]
@meyerlor , you can test the APK that will pop up in this PR (https://github.com/opengisch/QField/pull/5783), I believe it'll fix your issue.

**Comment by meyerlor** [comment]
Hey @nirvn locale says "de" - unfortunately the APK did not fix it

**Comment by meyerlor** [comment]
@nirvn I took the liberty and directly download the artifact from https://github.com/opengisch/QField/actions/runs/11591816157/job/32272374407?pr=5783

It is working now perfectly! Great!
