### ISSUE TITLE
Slow GPSarrow on iOS

### ISSUE THREAD

**Issue by Rickard9** [opengisch/QField#5753]
iPhone 15 Pro
iOS: 18.0.1
Qfield 3.4.3

**Problem:**
The gps arrow and field of new feels very sluggish, it also stutters. - Sometime they look in different directions al do they are the same, do to sluggishness.

**Note:** I just downloaded Qfield for the first time yesterday, so i can't answer for previews versions.

**Comment by nirvn** [comment]
@Rickard9 , we'd need a screencast video to better understand what you perceive as sluggish here. Thanks

**Comment by ranleu** [comment]
Maybe it is related to this but I just reported:

https://github.com/opengisch/QField/discussions/5820
