### ISSUE TITLE
GeoPackage/SpatiaLite trigger to create geometry doesn't work.

### ISSUE THREAD

**Issue by jenast** [opengisch/QField#576]
I have a point layer with a custom made trigger. The trigger inserts a new geometry in another table (polygon) after inserts of a new point. This works in QGIS with data in a GeoPackage, but breaks in QFIELD. No row is created (in either table).

The idea is to create a new point for a sampling location in the field, and have a survey buffer area automatically created in another layer. This polygon is then used in the field to see what area to survey for background environmental data. We plan to use a LEICA high precision GPS antenna, which is tested to work in QGIELD.

### Reproduction Steps:

1. Create two layers with geometries as a GeoPackage. Add a trigger to insert a new row in Table B after insert on Table A. The offending trigger I used: "CREATE TRIGGER felle_landskog AFTER INSERT ON felle_b395fec6_8df8_4b03_8fc4_6f9e34fcb23b begin INSERT INTO landsskog_6fb8cfff_5ed0_47e3_868c_a070c9a1f248(id, geom) VALUES(NEW.id, AsGPB(ST_BUFFER(NEW.geom, 8.92))); END"
2. Export/copy to QFIELD.
3. Add row to Table A. 

Using the attached QGIS project:
1. Add new point to layer "felle". 
2. In QGIS, a new row with geometry is then created in layer "landsskog". In QFIELD, not so.

### Expected behavior:
Geometry in Table A and B created, as in QGIS.

### Observed behavior:

Error msg: OGR error creating feature -2: failed to prepare SQL: INSERT INTO "table....."

### Screenshots and GIFs
Error log didn't capture the whole output. Don't know where the log files are stored.
![Screenshot_20190509-111049](https://user-images.githubusercontent.com/4839471/57443609-bf0fa580-724e-11e9-9665-6aab5f186975.png)

QGIS project attached.

[qfieldBug.zip](https://github.com/opengisch/QField/files/3161336/qfieldBug.zip)

**QField version:** [Enter QField version here]
1.0.4 (10004993)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: NA
* Problem can be reliably reproduced, doesn't happen randomly: YES
* Problem happens with all files and projects, not only some files or projects: NO

**Comment by jenast** [comment]
There seems to have been some sort of mistake on my part. I can now get it to work using spatiallite, and writing the trigger a bit differently. I will try geopackage as well and open this up again if I encounter any problems. 

Sorry for the trouble, and thanks for a great app!

**Comment by jenast** [comment]
I'm reopening this since I cannot get the trigger to work with a GeoPackage. 
Here is another version of a trigger with a GeoPackage. Works in QGIS but not QFIELD:

CREATE TRIGGER "point_buffer_insert" AFTER INSERT ON "felle_b395fec6_8df8_4b03_8fc4_6f9e34fcb23b" FOR EACH ROW BEGIN INSERT INTO landsskog_6fb8cfff_5ed0_47e3_868c_a070c9a1f248 (location_gid, geom) SELECT new.id, AsGPB(ST_Buffer(new.geom, 8.92)) ; END

And another version, using plain SpatiaLite that works both in QGIS and QFIELD. The difference is not using AsGPB, and the names for the geometries. SpatialLite seems to rename the geometry column by default.

CREATE TRIGGER "points_buffer_insert" AFTER INSERT ON "felle_b395fec6_8df8_4b03_8fc4_6f9e34fcb23b" FOR EACH ROW 
BEGIN INSERT INTO landsskog_6fb8cfff_5ed0_47e3_868c_a070c9a1f248 (location_gid, Geometry) 
SELECT new.id, ST_Buffer(new.Geometry, 8.92) ; END

**Comment by signedav** [comment]
Hi @jenast
Does the trigger in the generated Geopackage work in QGIS?
I do assume no.

If no, then we will move this issue to QGIS or QFieldSync Bugtracker, okay?

**Comment by geomondego** [comment]
Hello guys, i'm having the same problem reported here. 
I have a QGIS project with a Geopackage layer and I was trying to use a trigger to fill / update two attributes with XY coordinates.
Everything works on the desktop, but when I move the project to QField (without using the QFieldSync plugin) after inserting a point in the layer, the message reported in this issue is provided.
In your tests, have you used triggers within Geopackage? Did it work?
If necessary, I can share the project.

Thanks

**Comment by nirvn** [comment]
@geomondego , is it still a problem with the latest QField 2.0 beta? We have updated quite a few underlying libraries which might have fixed this issue.

If it's still a problem, please provide a sample project and dataset.

**Comment by geomondego** [comment]
@nirvn I just tested it with version 2.0.7 and everything is working

**Comment by nirvn** [comment]
@geomondego , beautiful! Happy field mapping! :)
