### ISSUE TITLE
request: create polyline through gps tracking

### ISSUE THREAD

**Issue by Rickard9** [opengisch/QField#5775]
i have a request for an funktion.

Use the GPS to create Polylines. So if I walk from A to B, 500 meter the tool would make an poly line from A to B in a existing or new SHP SHP layer/file.

**Comment by m-kuhn** [comment]
Is the tracking functionality what you are looking for?
https://docs.qfield.org/how-to/tracking/

**Comment by Rickard9** [comment]
Thanks it is.

However I have now tried it, and there are some **problems** with it that's make it unusable. (I don't know if this is do to user error, but I don't think so)

1. The **GPS** possession **stutters** witch make the line going all places (iPhone 15 Pro) no big houses or trees.
2. the **tracking turns of** when the screen is turned off or when the app is not "active"

it's nice the function exists but it **feels unfinished**. I tried the same function on the Mergin Maps app which works great.

**Comment by nirvn** [comment]
@Rickard9 , 

1/ could you send us a screencast of this? Please open the positioning information panel too so we can see the position details while it stutters

2/ background tracking is an enhancement that will come in early 2025, for the time being, you are correct in identifyign that the phone must remain open.

**Comment by m-kuhn** [comment]
@nirvn is iPhone included in the early 2025 background tracking?

**Comment by Rickard9** [comment]
> @Rickard9 ,
> 
> 1/ could you send us a screencast of this? Please open the positioning information panel too so we can see the position details while it stutters
> 
> 2/ background tracking is an enhancement that will come in early 2025, for the time being, you are correct in identifyign that the phone must remain open.

This is from this morning, I will see if I can recreate this with more information

The red line is the actual path I walked.
![IMG_0210](https://github.com/user-attachments/assets/c5b1a91e-f085-4205-a878-6506fd11d753)

**Comment by m-kuhn** [comment]
Can you open the positioning panel (long press the gps button)?

**Comment by Rickard9** [comment]
i have not had time to recreate this when walking, however I tried it agen when in a taxi, The car is coming from a 30/km road and accelerating after the turn. note the gps behavior before the turn.

![IMG_0217](https://github.com/user-attachments/assets/3c277c2f-43a8-4f56-ad1b-75bd089d1a9b)


https://github.com/user-attachments/assets/999bef29-79d4-427c-81d9-9a90dced9839

i will try to record a better example of the problem.

**Comment by m-kuhn** [comment]
This is more likely a hardware problem (GNSS antenna) or environment problem (e.g. multipath/reflection issues between buildings), the spike in the first screenshot hints that the position is not stable enough for your expectations.
There is also the potential that CRS/reprojection is not perfectly configured.

I don't think we have enough evidence in here for a software/app problem to leave this open as an issue, but feel free to open a discussion at a [community channel](https://docs.qfield.org/get-started/support/)

**Comment by gis-kmg** [comment]
Sorry for being sneaky but with the 'background' tracking function currently being looked at, could the tracking + 'photo gallery' issue be reviewed at the same time? https://github.com/opengisch/QField/issues/5610

**Comment by m-kuhn** [comment]
> Sorry for being sneaky but with the 'background' tracking function currently being looked at, could the tracking + 'photo gallery' issue be reviewed at the same time? #5610

The background tracking is the result of a crowdfunding campaign (https://www.opengis.ch/2023/06/29/qfield-background-tracking/) I don't think it is included there.
