### ISSUE TITLE
Setting up own server - Projects are visible but content is not

### ISSUE THREAD

**Issue by Rickard9** [opengisch/QField#5788]
Hello

i am trying so set up my own server to sync QGIS with Qfield.

* I am loggd in in both the app and Qgis
* I have sync't the project

- But I can't see any content

what am I missing?
(The same project works fine in Qfield Cloud)

![IMG_0262](https://github.com/user-attachments/assets/fa16b568-6bc0-42fc-9629-260ff8a89834)
![IMG_0261](https://github.com/user-attachments/assets/f55c258a-a3ca-4e92-aaff-2fb1d82dacf2)

**Comment by suricactus** [comment]
When you check the file contents, what is in there? Reading the error message, it looks like the error was not downloaded correctly. Why is that I cannot answer just from the screenshots.

Note that we do not provide official support here on GitHub for privately installed QFieldCloud, there are just too many variables (literally in .env file).

If you want a more in depth look at your issue, you can always drop us an email at [sales@qfield.cloud](mailto:sales@qfield.cloud).

**Comment by Rickard9** [comment]
ok. I can see all the files, however all but one is at 0b...
