### ISSUE TITLE
Map unresponsive when activating GPS

### ISSUE THREAD

**Issue by ivankautter** [opengisch/QField#579]
Map is unable to zoom or pan upon activating GPS.  Attempts to do so appear to trigger a refresh in that a loading spinner occurs and resolves, but the map does not perform the desired action.  Similarly, tapping on Center current position does not pan the map to current location.  On screen GPS information confirms that the device has a current and correct GPS location.

The only means of allowing the app to be responsive with GPS on is either:
1. close the app and reopen once it obtains a GPS position
2. obtain a GPS fix with another app and open QField

### Reproduction Steps:

1. Open QField project without an existing GPS fix
2. Activate positioning services in QField
3. Attempt to pan or zoom the map manually or programmatically (i.e. center current position)

### Expected behavior:

Ability to pan and zoom manually or zoom to current position

### Observed behavior:

Map becomes unresponsive. No ability to pan and zoom. All other controls work as expected (e.g. nav drawer, menu control, etc)

**QField version:** 1.0.4

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

Hardware: Samsung Tab S 8.3 (SM-T700) running Android 6.0.1

**Comment by spono** [comment]
the same on [Galaxy tab A 2016](https://www.samsung.com/it/tablets/galaxy-tab-a-10-1-2016-t585/) running Android 7.

**Comment by northwestview** [comment]
Same on Samsung Galaxy Tab S5e

**Comment by KirstenReilly** [comment]
This issue has also been identified on Samsung Galaxy Tab S4 device, but not had this issue with Samsung Galaxy Tab S3 device.

**Comment by nirvn** [comment]
@KirstenReilly , can you check it the latest version, 1.8.3, fixed your issue? Permission handling has been rewritten and should have helped.
