### ISSUE TITLE
Freehand digitizing is working only with the MOUSE

### ISSUE THREAD

**Issue by Zou48** [opengisch/QField#5793]
### Describe the issue
When I use QFIELD on my tablet with a stylus or tablet pen and want to use the 'Freehand digitizing' mode, it doesn't work,. I can only make straight lines or polygons even if the mode is activate. The 'Freehand digitizing' mode only works with my mouse connected to my tablet. 

### Reproduction steps
1. OPEN QfieldProject
2. Select a polygon or line layer
3. Click on digitize mode 
4. Click on Freehand digitize mode
5. Use the pen or stylus
6. Surrend15

### Expected behavior
Freehand drawing

### Observed behavior
Straight line or polygon drawn
![Screenshot_20241107-171641](https://github.com/user-attachments/assets/bfa66556-9678-486f-8adc-a905a00f86f6)

### QGIS
 - OS: [Windows]
 - QGIS Version [e.g. 3.34.0]
 - QFieldSync Version [e.g.4.0.0]

### QField
 - Device: [e.g. BlackView Active 8 Pro]
 - OS: [e.g. Android 13]
 - QField version: 3.4.4 - Ebo (5cc32f) Qt 6.7.3 
### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No, I downloaded old version too
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

![ezgif-1-bc8ef44aed](https://github.com/user-attachments/assets/a03ce938-00c9-4b46-8a74-f6d60e4e1c7e)

**Comment by m-kuhn** [comment]
Is this Possibly a duplicate of https://github.com/opengisch/QField/issues/3054 ?

**Comment by nirvn** [comment]
@Zou48 , are you saying your device stylus isn't working, or that you wish to use freehand digitizing with your finger?
