### ISSUE TITLE
Layer CRS has to match project CRS

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#58]
Newly added geometries are always written to the layer in project CRS.

If the two CRS definitions do not match, the newly added geometry ends up at the wrong position.

Digitizied geometries will need to be reprojected into the layer CRS before saving.

For now, just make sure that the two CRS match for layers for which you want to digitize geometries.

**Comment by ludodo** [comment]
Well, I managed to have all my layers in the same projection EPSG 3857, no more projection on the fly in the project.
Still doesn't work. I join the project file, maybe something is wrong I don't see ?

[formation_projet_qfield_45.qgs.txt](https://github.com/opengisch/QField/files/378286/formation_projet_qfield_45.qgs.txt)

**Comment by m-kuhn** [comment]
I remember having troubles with shp. Can you save the layer as spatialite and try with that? Make sure it's added with the spatialite provider and not with the ogr provider. (Layer => Add => SpatiaLite)

**Comment by ludodo** [comment]
Well well...
I transformed 3 layers in spatialite, 2 polygons layers and the point one. The polyline layer didn't pass in the spatialite file. So I had it in the project as Shapefile.
Result : edition works both for the point layer in the spatialite base AND for the polyline layer that didn't work until this...

Conclusion :
- be careful to have the same SCR for all layers and the project,
- shapefile can cause problems, but not all time !

Thank's a lot for your help and for this project in wich I really believe.
By the way do you plan to develop :
- polygon editing ?
- layer control ?

**Comment by m-kuhn** [comment]
> shapefile can cause problems, but not all time !

Were you able to isolate the cause?

> By the way do you plan to develop :
> 
> * polygon editing ?
> * layer control ?

* Polygon is very probable to be included in a nearby project
* Layer control is a big topic. We have no (closeby) project dealing with this. I started to write down some ideas in #59. Volunteers for sponsoring welcome :)

**Comment by ludodo** [comment]
I think my layer's origin is part of the problem. This is IGN's data (french institutional organism in geographic data) from BD Topo in a strange SCR and not in UTF8 encoding. I already had problems to transform them from shapefile to spatialite and had to cut the data with my study zone to make it work.

We (french Conservatoires espaces naturels) recently little sponsored the Qgis project. Maybe I could suggest to have a look to Qfield project too ?

**Comment by m-kuhn** [comment]
> I think my layer's origin is part of the problem. This is IGN's data (french institutional organism in geographic data) from BD Topo in a strange SCR and not in UTF8 encoding. I already had problems to transform them from shapefile to spatialite and had to cut the data with my study zone to make it work.

If you have any indication that you think may be helpful to identify the root of this problem, please let me know.

> We (french Conservatoires espaces naturels) recently little sponsored the Qgis project. Maybe I could suggest to have a look to Qfield project too ?

Much appreciated :+1:
Si tu vois des possibilités, n’hésite pas nous contacter.
