### ISSUE TITLE
What causes the QField error message 'unable to save'?

### ISSUE THREAD

**Issue by shad432** [opengisch/QField#5821]
I cannot seem to find any information about this particular error message.

I am trying to set up QField for a project, and during testing, I am not able to save changes to point layer, and get the error "Unable to save changes".
When trying to add a point feature in QGIS, I receive the message 'Unable to save' (see screenshot).

We're using the latest version of QField. Does anyone know how what's causing this error and how to solve it?

![Capture](https://github.com/user-attachments/assets/8e5aa140-bc27-4a01-a9bd-a59ca279bc6b)

**Comment by nirvn** [comment]
@shad432 , you are using a very, _very_ old version of QField, why is that? Step one would be to upgrade to the latest version first.
