### ISSUE TITLE
Track points: time set to 1970/01/01 00:00:00 on first points

### ISSUE THREAD

**Issue by vincentBenet** [opengisch/QField#5824]
### Describe the issue
Few firsts points of a track layer have time set to 1970/01/01. 

### Reproduction steps
1. Set a track layer on qgis
2. Set time tracking of clock
3. Synchronize with qfieldcloud
4. Open on qfield the project
5. Wait for the first point and see time attribute, other points have correct time

### Expected behavior
Wait for the time to be correct to record the point

### Observed behavior
The point is recorded with uncorrect time

### Screenshots and GIFs
![Screenshot_20241116_165444_ch_opengis_qfield_QFieldActivity](https://github.com/user-attachments/assets/2e8beb12-bc84-41f6-a226-ceea02bf3496)

### QGIS (please complete the following information)
 - OS: Will be referenced if needed
 - QGIS Version: Will be referenced if needed
 - QFieldSync Version: Will be referenced if needed

### QField (please complete the following information)
 - Device: HONOR CRT NX1
 - OS: MagicOS 8.0
 - QField version: v3.4.4 5cc32f

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

QfieldCloud is made with my server

**Comment by m-kuhn** [comment]
Can you attach a minimal sample project to reproduce this behavior?
