### ISSUE TITLE
Release 3.4.4+ on Android 6

### ISSUE THREAD

**Issue by amgiss** [opengisch/QField#5845]
### Describe the issue
Build 3.4.4 and 3.4.5 will not run on Android 6.0.1

Builds up to and including 3.4.3 run normally.

### Reproduction steps

Let QField update via Google Play to 3.4.4 or 3.4.5 or manually install android-arm64.apk version.

### Expected behavior
QField updates and runs.

### Observed behavior
"Unfortunately, QField has stopped" error message.

The same error occurs for Google Play or manual install.

### QField (please complete the following information)
 - Device: Trimble TDC100
 - OS: Android 6.0.1 (I know this is very old but it's vendor hardware specific)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes] On multiple devices.
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
We are using qt which imposes this minimum requirement.
See https://doc.qt.io/qt-6/android-supported-versions-selection-guidelines.html for how qt selects the minimum supported version.

You might be able to build yourself against an older version, for us it's unfortunately not possible to keep updating the app and support all devices.

**Comment by nirvn** [comment]
@amgiss , can you try the arm-neon-android APK in this PR to confirm the crash is gone: https://github.com/opengisch/QField/pull/5876

Thanks
