### ISSUE TITLE
Stop screen dimming

### ISSUE THREAD

**Issue by ronantaylorware** [opengisch/QField#5846]
Any way to stop the screen dimming while idling? Android 14.

Ive got "stay awake" set in developer settings, and the timeout set to the max 180s...

Cheers

**Comment by suricactus** [comment]
If you set it to 0 (zero), the dimming is disabled as documented here: 
https://docs.qfield.org/get-started/settings/?h=dim#dim-screen-when-idling

**Comment by ronantaylorware** [comment]
ahhh thank you!
