### ISSUE TITLE
Qfield does not change symbologies according to boolean fields

### ISSUE THREAD

**Issue by JAVIERSIG** [opengisch/QField#5847]
If I have a Boolean field in QGIS, I can change the style of the layer based on that value (yes/no), but when I export the style within the gpkg layer, qfield ignores that style.    Is it possible that he does not recognize well the rules defined according to that Boolean?

**Comment by SeqLaz** [comment]
Hi @JAVIERSIG 

Could you provide us with a sample project for testing?
