### ISSUE TITLE
QField crash on sorry time after open

### ISSUE THREAD

**Issue by Hikuritamete** [opengisch/QField#5859]
Lo### Describe the issue
QField crash after a moment start and when open again crash immediately and can do anything

### Reproduction steps
1. Opens a local project
2. Create a new object in a layer
3. Go to put in editing mode a new layer
4. QField crash
5. Open again
6. Crash when open again the project and no works again
7. Have to delete cache from the app to let me open QField again
8. Same happens when I work with QField Cloud

### Expected behavior
Let me work with my project without crasing

### Observed behavior
QField is unable to open the project

### QGIS (please complete the following information)
 - Android
 - QGIS Version 3.40
 - QFieldSync Version 4.12
 
### QField (please complete the following information)
 - Device: Xiaomi Redmi note 11
 - OS: Android 12
 - QField version: 3.4.5

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: 
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

QField cloud:
OmarRuelas 
Puerto_Cuyutlan

**Comment by nirvn** [comment]
@Hikuritamete , I'm unable to reproduce here locally, could you try a build of QField by installing the arm64-android APK here: https://github.com/opengisch/QField/pull/5855#issuecomment-2509572591 and see if the crash is gone on that version?

>> Go to put in editing mode a new layer

By that you mean that as soon as you toggle editing on it crashes, or do you need to actually add a feature for it to crash?

**Comment by Hikuritamete** [comment]
> By that you mean that as soon as you toggle editing on it crashes, or do you need to actually add a feature for it to crash?

Yes, i created a object in a layer, stop editting and go to a new layer to put in editng mode and crash.
I already modify mi GPKG layers names. And use another movil and a new tablet and the same ocurre, i think is something with my files beacuse in all these gadgets occurs the same.

**Comment by nirvn** [comment]
@Hikuritamete , ok, could you provide us with a screencast (ie video recording of your device screen) from the time you open the project until it crashes? Thanks

**Comment by Hikuritamete** [comment]
https://github.com/user-attachments/assets/5e4cc1ef-a356-4abf-a25d-a852da4a92c4

Now QField crash when  open the project

**Comment by nirvn** [comment]
@Hikuritamete , could you send me an email at mathieu@opengis.ch to agree for me to open the above-mentioned cloud project? Without this I can't get in :)

Also, could you clear the QField Beta's application storage (using the App Info's storage & cache action) so you can give us a screencast that shows what layers / features / attributes you were adding prior to leading you to this state of crash? Thanks.

**Comment by Hikuritamete** [comment]
https://github.com/user-attachments/assets/525ffa25-1e23-42b8-994a-2f25ad798862

**Comment by Hikuritamete** [comment]
> @Hikuritamete , could you send me an email at [mathieu@opengis.ch](mailto:mathieu@opengis.ch) to agree for me to open the above-mentioned cloud project? Without this I can't get in :)

I send you a email but a dont understand well whath i have to put in

**Comment by nirvn** [comment]
@Hikuritamete , I've received it, all good thanks. That'll help us figure out what's happening

**Comment by Hikuritamete** [comment]
@nirvn, Thanks

**Comment by Hikuritamete** [comment]
This was a bug? i am no programer. This means that QFiel needs a update?

**Comment by nirvn** [comment]
@Hikuritamete , it was indeed a bug, and QField will need an update.

Could you help out one last time and confirm that the crash is gone for you? Please download the arm64-android APK here: https://github.com/opengisch/QField/pull/5864#issuecomment-2513336090 , your project should not crash anymore.
