### ISSUE TITLE
QFieldYNC: 4.12 in Linux (Ubuntu 22.04.5 LTS) can

### ISSUE THREAD

**Issue by Hikuritamete** [opengisch/QField#5865]
### Describe the issue
This maybe take me some time to explain. Sorry for my english.
I use Linux (Ubuntu 22.04.5 LTS) with QGis 3.40, and QField Sync 4.12.
I have a project where desactive the option sort loop from the Widget Value Relation in the Atribute Form. But even that i cant create a workable QField Cloud project. 
I have 2 situations, First. When a achievement that the Cloud works, QField Crash when i click a layer of points o others layers.
Second, QFieldSyn creates a corrupted Cloud project. The GPKG that creats is not linked to the .QGS. And shows this message:
"Layer /media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/Salvamento_Puerto_Cuyutlan.gpkg" is outside the project's home directory.This layers may cause issues.Please move the layer within "/media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/QField/Cloud"
![1](https://github.com/user-attachments/assets/a1a52bed-bf4f-4c93-84ed-a951b0380848)

When a look inside the QGIS File QGS, the Data Source is the original GPKG no the Cloud GPKG.

[salvamento_puerto_cuyutlan.zip](https://github.com/user-attachments/files/17986354/salvamento_puerto_cuyutlan.zip)

Curiously, i can do works when my QGIS files DPKG and QGZ are in diferent paths

**Comment by nirvn** [comment]
@Hikuritamete , we'll need a better description than this :)

**Comment by Hikuritamete** [comment]
> @Hikuritamete , we'll need a better description than this :)

@nirvn , sorry i publish unfinish post its update now

**Comment by nirvn** [comment]
@Hikuritamete 

> QField Crash when i click a layer of points o others layers.

This is fixed in https://github.com/opengisch/QField/pull/5864 (you can try the APK in there to confirm)

> Layer /media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/Salvamento_Puerto_Cuyutlan.gpkg" is outside the project's home directory.

When you create a cloud project, all of your datasets must be _within_ your project file folder. E.g., say your project folder is this: `/home/my_cloud_project/project_file.qgz` , all of your datasets must be in the `/home/my_cloud_project/` folder. To fix your warning, you simply need to move your `Salvamento_Puerto_Cuyutlan.gpkg` file (and any other gpkg with the same warning) _into_ your local cloud project folder.

**Comment by Hikuritamete** [comment]
> @Hikuritamete
> 
> > QField Crash when i click a layer of points o others layers.
> 
> This is fixed in #5864 (you can try the APK in there to confirm)
> 
> > Layer /media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/Salvamento_Puerto_Cuyutlan.gpkg" is outside the project's home directory.
> 
> When you create a cloud project, all of your datasets must be _within_ your project file folder. E.g., say your project folder is this: `/home/my_cloud_project/project_file.qgz` , all of your datasets must be in the `/home/my_cloud_project/` folder. To fix your warning, you simply need to move your `Salvamento_Puerto_Cuyutlan.gpkg` file (and any other gpkg with the same warning) _into_ your local cloud project folder.

@nirvn , al my dataset, are in: /media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/.
Are 2 files, a GPKG and a QGZ that works with QGIS. But when a create a QField Cloud project use the path /media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/QField/Cloud/salvamento_puerto_cuyutlan/. To put the files generated by QFieldSync. And show me the last error message.
When a put the QGZ in other path like: /media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento1/ and the GPKG stay in /media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/ the Cloud proyect works fine without the mentioned Error.

**Comment by nirvn** [comment]
If your cloud project file (i.e. .qgz or .qgs) is in `/media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/QField/Cloud/salvamento_puerto_cuyutlan/` then your GPKGs **must** be in that folder too, not in a parent folder (which is what you are indicating in your text above). Move your GPKGs **into** `/media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/QField/Cloud/salvamento_puerto_cuyutlan/` and make sure your cloud project use these GPKGs.

**Comment by Hikuritamete** [comment]
> If your cloud project file (i.e. .qgz or .qgs) is in `/media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/QField/Cloud/salvamento_puerto_cuyutlan/` then your GPKGs **must** be in that folder too, not in a parent folder (which is what you are indicating in your text above). Move your GPKGs **into** `/media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/QField/Cloud/salvamento_puerto_cuyutlan/` and make sure your cloud project use these GPKGs.

But i use the option "Convert currently project to Cloud Project" and this create bot files the GPKG an the QGS in `/media/Archivos/Archivo/Trabajo/Proyectos/2024/Puerto_Cuyutlan/SIG/QGIS/Salvamento/QField/Cloud/salvamento_puerto_cuyutlan/`. 
Even so there are a GPKG created by QField i need no copy the Parent GPKG?

**Comment by nirvn** [comment]
@Hikuritamete , ah, if you are converting a project into a cloud project, then yes this should all be taken care of. You can check that the resulting cloud project relies on layers copied _into_ the cloud project folder. If for some reason that isn't happening, let us know with maybe a sample project + steps to reproduce when using the 'convert project to cloud project'.

**Comment by Hikuritamete** [comment]
Sample Dataset:
[Salvamento.zip](https://github.com/user-attachments/files/17986588/Salvamento.zip)

I use QField withe the option "Convert currently project to Cloud Project", but this shows a error:
![1](https://github.com/user-attachments/assets/f85889a7-cdf9-4233-9190-290be0cd7f49)

Project generated by QFile Sync:
[salvamento_puerto_cuyutlan.zip](https://github.com/user-attachments/files/17986645/salvamento_puerto_cuyutlan.zip)

**Comment by nirvn** [comment]
@Hikuritamete , I'm able to convert this project properly over here, using QFieldSync 4.12. When you convert your project, are there error messages being pushed into QGIS' message logs panel? You can see them by clicking here:

![image](https://github.com/user-attachments/assets/d387f216-0265-4b0f-9ee8-d7a31669cdfc)

**Comment by Hikuritamete** [comment]
@nirvn This show:

2024-12-02T21:17:09     INFO    Layer "Administracion-Arqueologos" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Administracion-Trabajadores" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Area_de_Estudio" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Excavacion-Atributos" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Excavacion-Bolsas_de_Materiales" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Excavacion-Estratigrafia" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Excavacion-Muestras" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Excavacion-Puntos-Inmueble" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Excavacion-Unidades" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Geografico-Curvas_de_Nivel" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Geografico-INEGI_Cartas" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Perimetro" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Prospeccion-Atributos" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Prospeccion-Bolsas_de_Materiales" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Prospeccion-Lineas_Inmueble" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Prospeccion-Poligonos" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Prospeccion-Puntos_Inmueble" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Prospeccion-Puntos_Mueble" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Prospeccion-Tracks" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Recintos_Portuarios" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Reticula_1Ha" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Sitios_con_Registro" will use attribute "fid" as a primary key.
2024-12-02T21:17:09     INFO    Layer "Sitios_sin_Registro" will use attribute "fid" as a primary key.

**Comment by nirvn** [comment]
@Hikuritamete , I'm at lost as to what's happening here, I have roughly the same system as you and I can make a cloud project out of converting Salvamento.zip.

I hope it won't bother you too much to do the conversion manually :)

**Comment by Hikuritamete** [comment]
When i use the option "Create a new empty QFieldCloud Project" works great with the QField 5864 dont crash anymore

**Comment by nirvn** [comment]
@Hikuritamete , good to know the crash is gone, thanks for the confirmation. A new version of QField on the play store with this crash fixed should emerge within the next 24 hours.

QField's value relation editor widget doesn't yet support multi-column layout. 

I'm inclined to close this issue now as some of the problems here have been fixed, and enhancement request should be filed separately. Is that OK with you?
