### ISSUE TITLE
QField application doesn't open on Trimble TDC 100 device

### ISSUE THREAD

**Issue by Fedepeche65** [opengisch/QField#5875]
### Describe the issue
QField application doesn't open on Trimble TDC 100 device

### Reproduction steps
1. Open QField application
2. Error message 'QField stopped'
3. Uninstall QField application
4. Device Reset on the Trimble TDC 100
6. Install Qfield application
7. Open QField application
8. Error message 'QField stopped'

### Expected behavior
Open QField application

### Observed behavior
Error message 'QField stopped'

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

### QField (please complete the following information)
 - Device: Trimble TDC 100
 - OS: Android 6.0.1
 - QField version: QField version 3.4.5 - Ebo

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by suricactus** [comment]
@Fedepeche65 can you please edit your issue and change the report to English.

**Comment by Fedepeche65** [comment]
@suricactus I'm sorry, I'm reissue my publish in english.

**Comment by nirvn** [comment]
@Fedepeche65 , can you try the arm-neon-android A0
