### ISSUE TITLE
Taking photos crashes QField

### ISSUE THREAD

**Issue by Paul-Losse** [opengisch/QField#5891]
### Describe the issue
When taking photographs, QField crashes

### Reproduction steps
1.tap plus button in photos field in QField
2. Take photograph
3. Tap 'OK' - QField crashes

_Add a simple sample project if it requires a specific configuration_

### Expected behavior
The photograph is listed and captured in QField

### Observed behavior
QField closes
### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]

### QGIS (please complete the following information)
 - OS: Windows 10
 - QGIS Version 3.34.13
 - QFieldSync Version 4.12.1

### QField (please complete the following information)
 - Device: Samsung Galaxy Tab Active 3
 - OS:  Android 13
 - QField version: 3.4.7 (dfab7b v3.4.7)
### Additional information
* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: No - happens occasionally
* Problem happens with all files and projects, not only some files or projects: Yes

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by nirvn** [comment]
@Paul-Losse , does it crash on the sample bees project shipped with QField too? Did you enable the [x] native camera option?

**Comment by Paul-Losse** [comment]
@nirvn, I've tried multiple times taking photos using the sample bees project as well as my other projects, both with and without the native camera. Annoyingly I've not been able to reproduce the issue. The problem is that it's very intermittent. Sometimes the photos are captured without problems, other times QField crashes immediately after taking the photo. This has happened for on and off over the last couple of years with the various iterations of QField

**Comment by nirvn** [comment]
@Paul-Losse , I'd advise to a/ use the non-native camera (it's the default now for QField >= 3.4), and reduce the image resolution.

**Comment by Paul-Losse** [comment]
@nirvn, do you mean use the minimalist internal camera i.e turn off the option to 'use native camera' in the settings?

**Comment by nirvn** [comment]
@Paul-Losse , you are correct.

**Comment by Paul-Losse** [comment]
@nirvn Thanks, I'll try that

**Comment by nirvn** [comment]
@Paul-Losse , any perceived improvements ?

**Comment by Paul-Losse** [comment]
@nirvn Yes, I've tried it numerous times using the QField camera with no crashes so far. Many thanks

**Comment by nirvn** [comment]
@Paul-Losse , can we close this issue?

**Comment by Paul-Losse** [comment]
@nirvn Yes, thanks. I think it's safe to do so
