### ISSUE TITLE
Impossible to syncronize Qfield to Qgis

### ISSUE THREAD

**Issue by simone100** [opengisch/QField#590]
[Short description of problem here]

### Reproduction Steps:

1. [First Step]: running QFieldSync with Package for QField, all is right and I can work in QField
2. [Second Step]: running QFieldSync with Sincronyze from QField, all is wrong and I can't syncronize my work in QField with the Qgis Desktop.
3. [Other Steps...]: message of error

### Expected behavior:

Syncronization from QField project to Qgis Desktop 

### Observed behavior:

No syncronyzation occurs, but a message of error appears

### Screenshots and GIFs: 
No screenshot, I copy exactly the message of error. 

Here you can see: 

"_An error has occurred while executing Python code: 

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Simone/OneDrive/Documenti/qgis/Progetto Colmar/sincronizzazione qfield\\data.sqlite' 
Traceback (most recent call last):
  File "C:/Users/Simone/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\dialogs\synchronize_dialog.py", line 65, in start_synchronization
    current_import_file_checksum = import_file_checksum(qfield_folder)
  File "C:/Users/Simone/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\utils\file_utils.py", line 89, in import_file_checksum
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Simone/OneDrive/Documenti/qgis/Progetto Colmar/sincronizzazione qfield\\data.sqlite'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.8-Madeira Madeira, 04ee8e0761 

Python Path:
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/Simone/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Simone/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Simone/AppData/Roaming/QGIS/QGIS3\profiles\default/python_"

**QField version:** probably all version! I tried with Qgis 3.6 and the most stable 3.4.8, even the same result! 
## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Always happens 
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by djes** [comment]
I have the same issue. I noticed something strange when comparing the offline data.gpkg and the returned, it seems that the data is corrupted :  ![image](https://user-images.githubusercontent.com/12065874/59767695-23d50b80-92a3-11e9-99a4-1310fe55848d.png)
I suspect that having space and special chars in the original datasources could be the problem, or special CRS.

**Comment by GCouet** [comment]
Do you have any layers for which the actions in QFieldsync were set to **offline editing**? I had the same problem until I found out that if your project has only **copy** actions, no sync log will be created and instead of telling you there is nothing to sync, it will throw this error when it can't find a log.

**Comment by signedav** [comment]
I think this issue is more related to QFieldSync (https://github.com/opengisch/qfieldsync/issues) than to QField. Anyway. What version of QFieldSync do you use?

On QFieldSync Version 3.1.5 I receive a message in that case:
> QFieldSync : The project you imported does not seem to be an offline project

**Comment by signedav** [comment]
What is the status here? Can you provide us test data?
Thanks.
