### ISSUE TITLE
support for expression evaluation in html widgets

### ISSUE THREAD

**Issue by bladnor** [opengisch/QField#5915]
### Describe the issue
Even tough the "HTML Widget" in a form is marked as supported here: https://docs.qfield.org/how-to/attributes-form/ it looks like evaluating an expression is not (yet) supported:

<script>document.write(expression.evaluate("\"my-layer-field\""));</script>

The goal is to display an iframe in a HTML Widget using fields from the layer. Something like this:
<body>
  <iframe 
    src="https://example.org?<script>document.write(expression.evaluate("\"my-layer-field\""));</script>" 
  </iframe>
</body>

If the src attribute of the iframe is static it works.

1. Can you confirm that this is not yet supported?
2. Is there any other way to display an external website in a form widget using attribute values from the layer as paramter to craft the url to use?

QField Version: 3.4.7-Ebo
QGIS Version: 3.40.1-Bratislava

**Comment by nirvn** [comment]
@bladnor , alright, few things I'd suggest here :)

a/ when you have an HTML widget configuration, _test within QGIS first_ to see if it works. What you're pasting here would not work in QGIS.

b/ if it doesn't work in QGIS, simply try what you are typing as a simple .html file, e.g. in your case it'd be:

```
<!doctype html>
<html><head></head><body>
<iframe style="width:200px;height:200px;" src="<script>document.write('https://www.google.com/');</script>"> </iframe> 
</body></html>
```

That would have quickly taught you that your HTML code is wrong to begin with :) you cannot add a <script> tag within a src attribute.

My suggestion here would be to achieve what you want within a .html test file using javascript's document.write('static_value'), then when that works, go in QGIS, make it work there, then it'll work in QField :)
