### ISSUE TITLE
Snapping - Apply z value in geometry

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/QField#592]
When capturing, if snapping is activated, the Z coordinate is not taken over in the geometry.

It would be very usefull to use it with precice gnss receivers, when obtaining elevetion data for example. There you need to add breaklines if you have a ridge or other formation. Or when you connect different object in the field (pipeline between shafts or so..).

### Reproduction Steps:

1. snapping activated on a geometry with z value
2. capture a point snapped on this feature
3. Look up geometry for this point

### Expected behavior:

Snapped Z value is applied

### Observed behavior:

Snapped Z value is not applied

### Screenshots and GIFs

Sample project is attached
[z_value.zip](https://github.com/opengisch/QField/files/3260379/z_value.zip)

**QField version:** 1.1.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: ?
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
This is solved and tested with the linked PR - so I close it. Thanks.
