### ISSUE TITLE
GNSS Positioning Display - values not readable

### ISSUE THREAD

**Issue by EulenspiegelTill** [opengisch/QField#593]
Since a certain Version (??) the positioning display is moved to the bottom of the display. The texts  like **Horizontale Genauigkeit** are quite long, so the actual value disapears.

### Reproduction Steps:

1. Activate positioning display with a long press on the blue gps button
2. the pos.-display appears on the bottom of the device.

### Expected behavior:

All values are readable on any device screen size.

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs
 In the Picture the GPS is not activated, but can be imagined **N.a.** as a placeholder vor the value.

![Screenshot_20190613-081748](https://user-images.githubusercontent.com/23494522/59430196-e58ea680-8de1-11e9-8600-9fbb8a777d48.jpg)

**QField version:** 1.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by geomoes** [comment]
I encounter the same issue regardless if I'm using QField in portrait or landscape mode. 
Using it on a Huawei m3, Android 7.0 at a screen display of 1600x2560 (8"-Display).

**Comment by signedav** [comment]
I think this is fixed meanwhile like this:
![WhatsApp Image 2019-11-06 at 15 01 02](https://user-images.githubusercontent.com/28384354/68304565-4c20a380-00a6-11ea-8a1d-e1c155a2dc22.jpeg)

Can you confirm @geomoes and @EulenspiegelTill ?

Latest master build you can find [here](https://github.com/opengisch/QField/commit/3249a9ac1ee1e4fe38f549b6f58663cd538391d3#commitcomment-35774953)

**Comment by EulenspiegelTill** [comment]
@signedav from my point of view this issue can be closed. Thanks!
