### ISSUE TITLE
Avoid intersections feature does not work

### ISSUE THREAD

**Issue by eysupa** [opengisch/QField#594]
Avoid intersections of new polygons feature does not work when creating new polygons in qfield.

### Reproduction Steps:

1. Create Qgis project and activate Avoid intersections in Snapping options
2. Open Qgis project in Qfield and create overlapping polygons

### Expected behavior:

Overlapping parts won't be created

### Observed behavior:

Polygons do overlap, function shows no effect

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
This has been fixed a while back.
