### ISSUE TITLE
Too many open libraries

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#6]
We should try to reduce the number of libraries. A system threshold is hit on some devices.

Candidates:
 * ~~QwtPolar~~ (0.2.9 ships without)
 * QScintilla
 * Print support?
 * GDAL monolithic build?

https://drive.google.com/file/d/0B4viNCOF63D-dXJZRnNyazByUHc/view

**Comment by saultdon** [comment]
Is there something I can ask the manufacturer of the RangerX tablets about too? It's a pretty decent device and it might be strange that it's running out of resources.

**Comment by saultdon** [comment]
I tried with 0.2.9 and it's still crashing on start for the RangerX.

Here's the link to the log:
https://drive.google.com/file/d/0B4viNCOF63D-cEVDUkhUcVVJME0/view?usp=sharing

**Comment by saultdon** [comment]
It got a little farther with 0.3.2.

The black screen popped up, then shortly a small window that said something like "unpacking install files/libraries" appeared then when that got to 100%, the app crashed.

Here's my log for it. 

https://drive.google.com/file/d/0B4viNCOF63D-czhFSmtIcTBZb28/view?usp=sharing

**Comment by m-kuhn** [comment]
The unpacking part is new and is pure (startup) Java that is executed before the libraries are loaded. Therefore the unpacking process already takes place before the loading libraries issue surfaces.

**Comment by m-kuhn** [comment]
If someone feels experimental he may install CyanogenMod or another custom ROM to check if it is an OS issue. Just make sure you get Android 4.x. And be aware that this may void your warranty! You have been warned!

**Comment by m-kuhn** [comment]
If you find a line containing the following text in your logcat, you are affected by this problem:

    Cannot load library: soinfo_alloc(linker.cpp:287): too many libraries when loading 

E.g.

    W/Qt      ( 2360): qrc:/qml/qgismobileapp.qml:18 ((null)): qrc:/qml/qgismobileapp.qml:18:1: plugin cannot be loaded for module "QtQuick": Cannot load library /data/data/org.kde.necessitas.ministro/files/dl/1/stable/qml/QtQuick.2/libqtquick2plugin.so: (Cannot load library: soinfo_alloc(linker.cpp:287): too many libraries when loading "libqtquick2plugin.so")

**Comment by saultdon** [comment]
It's funny that on a consumer tablet like the EVGA Tegra Note or Samsung Galaxy Tab 4 that qfield opens and runs.

But on a industry/military grade tablet like Xplore Technologies RangerX - won't.

Is this like a kernel env. variable that needs to be changed? I wonder if it's as simple as increasing the ulimit or something... There's more RAM on the RangerX than there is in the Tegra Note or Galaxy Tab 4 too.

If I knew, I could talk to the manufacturers to patch the devices we have.

**Comment by mbernasocchi** [comment]
I remember investigating this deeply, and it is indeed a hardcoded value in android builds, I'll try to digg up my bug report

**Comment by mbernasocchi** [comment]
not my bug report but sound interesting:  https://forum.qt.io/topic/52468/too-many-libraries-when-loading/3

**Comment by mbernasocchi** [comment]
its line 54 in https://android.googlesource.com/platform/bionic/+/android-4.2_r1/linker/linker.cpp

**Comment by mbernasocchi** [comment]
ok I had a bit of a further look, 
in https://android.googlesource.com/platform/bionic/+/android-cts-4.2_r2/linker/linker.cpp
SO_MAX is still present, in 
https://android.googlesource.com/platform/bionic/+/android-4.3_r0.9/linker/linker.cpp
it is not any more, so I think we should suggest android 4.3 to 4.4.4 as best OS versions for QField

**Comment by m-kuhn** [comment]
We can't really do anything about it.
You are adviced to look for a device >= 4.3.
