### ISSUE TITLE
Label rounding not working consistently

### ISSUE THREAD

**Issue by etiennethomassen** [opengisch/QField#60]
I am using a label which uses several fields with the last field being the area in m2 divided by 10.000 and rounded to 2 decimal values to show hectares. For some features the label looks fine, but most are not rounded and show more then 10 decimal values.

**Comment by m-kuhn** [comment]
Can you paste the exact expression and some samples that work and don't work.

**Comment by etiennethomassen** [comment]
`CASE WHEN "sub">0 
THEN  "vak" ||  "afdeling" || "sub" || '\n' ||  "boomsoort"  || ' ' ||  "kiemjaar" || '\n' ||  round(($area/10000),2)  ||  ' ha' 
ELSE  "vak" ||  "afdeling"   || '\n' ||  "boomsoort"  || ' ' ||  "kiemjaar" || '\n' ||  round(($area/10000),2)  ||  ' ha' 
END`

Result in screenshot below.
In the center there is a polygon of which the surface area is rounded correctly. The others are not.

![screenshot_2016-08-04-08-51-48](https://cloud.githubusercontent.com/assets/1319600/17393245/c5cef52a-5a22-11e6-92d0-a04f4cc63930.png)

**Comment by m-kuhn** [comment]
This is a Qt5 issue https://bugreports.qt.io/browse/QTBUG-47192
We will need to update to Qt 5.7 to solve it (which is a considerable amount of work).

**Comment by m-kuhn** [comment]
Checkout the latest (beta) release 0.9.0, it should be fixed in there.

If the problem persists with 0.9.0, please reopen this issue.
