### ISSUE TITLE
Seach bar not expanding when selected

### ISSUE THREAD

**Issue by nicolasmcfadden** [opengisch/QField#601]
Search bar doesn't expand when selected

### Expected behavior:
Search bar expands
![photo_2019-06-26_02-45-34](https://user-images.githubusercontent.com/27243743/60140939-14caed80-97bc-11e9-95a6-fcf933180497.jpg)

### Observed behavior:
Search bar stays too small to read search results
![photo_2019-06-26_02-45-22](https://user-images.githubusercontent.com/27243743/60140959-1bf1fb80-97bc-11e9-881b-21b7925edd1a.jpg)

**QField version:** [Enter QField version here]
QField 1.1.1

Last worked properly with :

![image](https://user-images.githubusercontent.com/27243743/60141118-be11e380-97bc-11e9-8c09-be160c727dc2.png)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by signedav** [comment]
Hi @nicolasmcfadden 
Can you test that with the current master version [here](https://github.com/opengisch/QField/commit/3249a9ac1ee1e4fe38f549b6f58663cd538391d3#commitcomment-35774953)? I think, this is solved.

**Comment by signedav** [comment]
Since I did not received a feedback and I think it's solved meanwhile, I close this issue.
Feel free to reopen it, if it's still pending. Thanks :+1:
