### ISSUE TITLE
GPS does not work with EPSG:27700 British National Grid

### ISSUE THREAD

**Issue by coastalrocket** [opengisch/QField#604]
GPS position lat/long is not projected to eastings/northings

### Reproduction Steps:

1. Create project in EPSG:27700
2. Transfer project to Android device
3. Activate GPS
4. Run QField
5. Activate GPS button

### Expected behavior:

Map to centre to GPS position

### Observed behavior:

Map is centred to easting = long, northing = lat. 

### Screenshots and GIFs

![Screenshot_20190709-115200](https://user-images.githubusercontent.com/1110688/61115410-4addc200-a48a-11e9-9ce3-9f97c679c64c.png)

**QField version:** 1.1.0 (Matterhorn 10100993)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Have only tried this one version.
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: GPS works with a EPSG:3857 project.

**Comment by Dubhain** [comment]
There is an ongoing problem with the proj datum for 27700. In the main QGIS it doesn't work properly either (Project in 3857-layer in 27700 works fine, but Project in 27700-layer in 3857 does not work).

The reason I mention it is that it seems exactly the same nature of problem. If you zoom out, are you located somewhere in sea off Cape Town by any chance?

If so, I think it's the same problem, the x,y transformation seems to have got switched around, it's sending coordinates south and west of the equator/greenwich where it should be sending them north and east.

**Comment by signedav** [comment]
On what version of QGIS you've seen that @Dubhain ?
Maybe it's something happening in the QGIS part of QField.

**Comment by alansaviolobo** [comment]
I am getting this issue.
In addition I get the following errors:
SQLite error: no such table: tbl_srs
SQL: select srs_id from tbl_srs where srs_id >= 100000
SQLite error: no such table: tbl_srs
SQL: select srs_id from tbl_srs where srs_id >= 100000

**Comment by nirvn** [comment]
@alansaviolobo , what QField version and device model are you running? You should open a new issue with as much details as possible.

**Comment by alansaviolobo** [comment]
after uninstalling the app and reinstalling it, the issue seems to be resolved. Thanks.
