### ISSUE TITLE
NULL in Value Map

### ISSUE THREAD

**Issue by alsper78** [opengisch/QField#605]
In QGIS the Value Map widget has the possibility to add the NULL value, but selecting NULL in QFIELD give the hidden value {2839923C-8B7D-419E-B84B-CA2FE9B80EC7}. This value appears as NULL but it is not actually null if used in expressions (for filter, symbology, virtual field, ...).
Moreover if the field is not 'Text' or if it's too short the value is not accepted.

**Comment by saemiw** [comment]
Yes this is an issue. If i copy the attribute table with NULL values to excel in a text field the "NULL" are represented (in excel) like: {2839923C-8B7D-419E-B84B-CA2FE9B80EC7}. For an integer field excel shows empty fields (which is better). But QField gives this error message when saving <NULL> to an integer field.  I think the widget just needs a little bit of more love for properly distinguishing between NULL, empty, 0. 

![Screenshot_20191009-170154_QField](https://user-images.githubusercontent.com/20398621/66493985-3a53dc80-eab7-11e9-87c8-07e0ea9e6f9c.jpg)

You may try with this very simple project to reproduce:
[NULL in value map.zip](https://github.com/opengisch/QField/files/3708068/NULL.in.value.map.zip)

QField 1.2.0
QGIS 3.4.12

**Comment by saemiw** [comment]
O.k. I just realised that a setting like the one below will behave perfectly and save all data correctly. Just don't use the button "add "NULL" values" and you're fine.

![grafik](https://user-images.githubusercontent.com/20398621/66822193-06a80500-ef44-11e9-829d-657a34722405.png)

**Comment by signedav** [comment]
Does the same issue exists on QGIS as well @saemiw ?

**Comment by gioman** [comment]
> Does the same issue exists on QGIS as well @saemiw ?

@signedav no, just tested on QGIS 3.12 on Linux.

**Comment by gioman** [comment]
No stale, still a valid issue.

**Comment by gioman** [comment]
@suricactus thanks!
