### ISSUE TITLE
autogenerate geometry based on tracking

### ISSUE THREAD

**Issue by geostonemarten** [opengisch/QField#607]
Objectif is to autogenerate information in relation to a tracking

2 possibilities: 
set point with position : this is ok but I need also auto generate point in relation to speed, bearing and time delay.
set line with form information with geometry based on GPS position. The start declaration generate automaticly a new line and stop the last line.

**Comment by m-kuhn** [comment]
Is this a duplicate of of https://github.com/opengisch/QField/issues/111
