### ISSUE TITLE
Edit attributes of multiple features simultaneously

### ISSUE THREAD

**Issue by carlospsig** [opengisch/QField#61]
You could add a feature that allows you to enter or modify multiple features simultaneously??

Like this new functionality in QGIS Desktop:
http://www.qgis.org/en/site/forusers/visualchangelog216/index.html#feature-edit-attributes-of-multiple-features-simultaneously
;-)

**Comment by m-kuhn** [comment]
Good idea, but not too high on the todo list. Main pre-requisite: find a good way to edit selections.

**Comment by nirvn** [comment]
@carlospsig , we have multi feature editing these days, enjoy! :tada:
