### ISSUE TITLE
Checkbox widget with integer field

### ISSUE THREAD

**Issue by geomondego** [opengisch/QField#612]
I have an integer field defined with the checkbox widget and when enabled the box assumes correctly. But, if i click again on the point object, the box is no longer checked.

Opening the project in QGIS, i can confirm that the field it filled with the desired value (1) and if i open the form, the box has the respective checkmark.

### Expected behavior:

Show checkmark for user marked objects

### Observed behavior:

Not showing the checkmarck

### Screenshots and GIFs

![Screenshot_20190816-080225](https://user-images.githubusercontent.com/4389239/63249531-8fb30080-c261-11e9-8bd8-bec3fa4d840a.png)

![Screenshot from 2019-08-16 08-15-52](https://user-images.githubusercontent.com/4389239/63249536-93468780-c261-11e9-8c39-0f5e6e27d852.png)

**QField version:** 1.1.0 - Matterhorn (10100993)

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Can you paste a screenshot of the checkbox configuration too?

**Comment by geomondego** [comment]
Here it is

![Screenshot from 2019-08-20 12-03-50](https://user-images.githubusercontent.com/4389239/63342142-a715ea80-c342-11e9-9f35-74b5f0552ba2.png)

**Comment by m-kuhn** [comment]
How are you taking the project offline, using qfield_sync and offline editing?

**Comment by geomondego** [comment]
> How are you taking the project offline, using qfield_sync and offline editing?

Just copy/paste

**Comment by m-kuhn** [comment]
Are you able to share the project?

**Comment by geomondego** [comment]
> Are you able to share the project?

i will send to your mail

**Comment by m-kuhn** [comment]
Thanks, we will get back to you

**Comment by geomondego** [comment]
> Thanks, we will get back to you

@m-kuhn i cant install provided apa. It is necessary to uninstall the other version?

**Comment by saemiw** [comment]
I was not able to reproduce the issue with QGIS 3.4.12, QField 1.2.0 using qfieldSync for setting the project offline.

**Comment by m-kuhn** [comment]
Thanks @saemiw
