### ISSUE TITLE
Printed PDF location

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#617]
It used to be the project directory itself. But then we had the case on projects (like e.g. the demo projects) that the external PDF could not access the document. That's why it has been moved to `QStandardPaths::DocumentsLocation` here https://github.com/opengisch/QField/pull/615 (not to temp path, because this is in the app folder as well).

Problem with DocumentLocation is, that it's not cleaned up...

It would be nice to have it improved like that the PDF would be stored to a tmp folder where the external app could access. Or sending the document with the intent to the app directly.

**Comment by signedav** [comment]
> The solution to this problem is per-URI permissions: when starting an activity or returning a result to an activity, the caller can set Intent.FLAG_GRANT_READ_URI_PERMISSION and/or Intent.FLAG_GRANT_WRITE_URI_PERMISSION. This grants the receiving activity permission access the specific data URI in the intent, regardless of whether it has any permission to access data in the content provider corresponding to the intent.

Seen on https://developer.android.com/guide/topics/permissions/overview

**Comment by jipi04** [comment]
Hello,
How is it possible to keep the grip of the current view in the PDF (set to map canvas extent)? Thanks in advance, Regards,

**Comment by signedav** [comment]
It does not take the current extent?

**Comment by jipi04** [comment]
No, it does not take the current extent :-( qgis 3.14, qfield 1.2, on redmi note 7
thank you

**Comment by jipi04** [comment]
sorry it's about QGIS 3.4.8

**Comment by signedav** [comment]
Thanks. I opened a seperate issue for that. #722

**Comment by signedav** [comment]
Hi @jipi04 

Can you test the APKs built here #723 ?

**Comment by meyerlor** [comment]
Uhm just checking - where is the pdf saved to when you have your project synced via QfieldCloud? I just get the menu where i can select the pdf reader app. Once i close the pdf i can not find it anymore in the filesystem. Do i neeed to save it actively to an accessible folder with my pdf program?

**Comment by nirvn** [comment]
This has been fixed a while back :partying_face:
