### ISSUE TITLE
Layer disapears after editing feature

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#618]
After editing a feature in a layer saved as .gpkg the whole layer disapears after the message "Changes Saved". 

### Reproduction Steps:
1. Select a feature
2. Edit it's content
3. Accept Changes
4. Message: "Changes Saved" 
5. All other features disapear, only the selected feature remains visible
6. Tapping somwhere on the map canvas makes the selected feature disapear as well

**QField version:** 1.1.0

## Additional information:
Quitting QField and restarting it loads all layers as desired, changes were not saved.
Pressing on the Bell in th right top corner leads to the message "Feature 310 could not be loaded after the commit"

**Comment by 3nids** [comment]
Does this happen at every try? or randomly?

**Comment by meyerlor** [comment]
at every try. i copied the data now into a new gpkg, and applied the layer styling of the old (non-functional). this new gpkg is working now as desired.

**Comment by 3nids** [comment]
Do you think any issue remains to be fixed?

**Comment by meyerlor** [comment]
well, i can not explain what led to the disfunctional gpkg. but as i can not really share the gpkg with the (customer) data and no one else expirienced this issue so far, this might as well be closed :)

**Comment by 3nids** [comment]
ok, thanks.
do not hesitate to re-open if you can reproduce the original issue.
