### ISSUE TITLE
Projection problems on WMS / WFS

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#620]
When having a **WFS layer** that use another CRS than the OSM map, the features are on the right position on QGIS and QField running in developing environment, but not on QField on the device. They are somewhere above the OSM world map. This is the same behavior when I have the credentials hard stored in the projectfile or I do it with the login implementation. When I test the hard stored project on the 1.1.0 Version (10100993) it's the same.
**Locally in dev. environment**
![image](https://user-images.githubusercontent.com/28384354/64337048-c4071a80-cfde-11e9-9917-f3988fa9db82.png)

**On QField on the device**
![image](https://user-images.githubusercontent.com/28384354/64337061-cec1af80-cfde-11e9-8b9b-ffd54b275e6f.png)

[heritage-unfiltered.zip](https://github.com/opengisch/QField/files/3579013/heritage-unfiltered.zip)

Another situation on **WMS layer**. Where this works with hard stored credentials it does not with the login implementation. But this issue only appears when the WMS layer does not have the same CRS like the project. Otherwise it works.

PS. Check with GPKG: I created 3 Layers with 3 different CRS and copied polygons from one to the other two - overlying each other and checked on QField on device. It's the same like on QGIS and QField on computer. Everything seems to work fine. Not sure id I did it right.

**Comment by nirvn** [comment]
@signedav , that's likely fixed with the whole proj / gdal upgrade.

**Comment by signedav** [comment]
The behavior on QField is the same like in QGIS so this is no QField issue anymore and can be closed.

![WhatsApp Image 2021-02-09 at 09 03 29 (2)](https://user-images.githubusercontent.com/28384354/107334342-e3995100-6ab6-11eb-9f61-78558d86951c.jpeg)


But I noticed that on QField (and QGIS as well) that ass soon as I zoom out that the OSM map does not cover anymore the canvas, the projection is changed (of OSM, not of the WMS) like this. 

![WhatsApp Image 2021-02-09 at 09 03 29 (1)](https://user-images.githubusercontent.com/28384354/107334259-c5cbec00-6ab6-11eb-8375-20b1e56f30f3.jpeg)

This might be confusing for me because of a lack of knowledge about projections, what I want to fix. Do you know what I did wrong here?
