### ISSUE TITLE
Enter coordinates in search bar as a GOTO

### ISSUE THREAD

**Issue by 3nids** [opengisch/QField#621]
show a go to action when coordinates can be deduced from the search text.

This could be a new locator filter in QGIS source code (and would replace the functionnality from extent line edit) and then added to QField.

**Comment by 3nids** [comment]
see https://github.com/kurtraschke/geolucidate/blob/master/geolucidate/tests/tests.py
for a 4326 coordinate parser

**Comment by 3nids** [comment]
for QGIS core:  add registry of coordinate formats in core `QString formatPoint( QgsPointXY )` and `QgsPointXY parsePoint( QString )`
see also https://github.com/kadas-albireo/kadas-albireo/blob/master/src/core/qgscoordinateformat.cpp#L209

**Comment by suricactus** [comment]
The locator already supports goto coordinates? Should we close?

**Comment by nirvn** [comment]
Let's close.
