### ISSUE TITLE
Deselect all selected features and close attributes sidebar

### ISSUE THREAD

**Issue by geomoes** [opengisch/QField#622]
Maybe I'm missing some thing, 
but when I select a feature on the screen, I can only close the sidebar that displays the attributes when I tap on an area of the map, where no selectable features are.
When I have a map layer (like e.g. a geological map) that covers all the screen, I have no chance to close the sidebar, since ther's no way to deselect features.
It would be nice to have a functionality that allows to deselect all the selected features, to close the sidebar and to return to the map. Otherwise I have to zoom out to reach a region outside of the selectable layer and tap on the map.
But as I said, might be that I'm missing something.
Great work

**Comment by signedav** [comment]
You should be able to go back by the hard-key on your device.
![droidxhardkeys (1)](https://user-images.githubusercontent.com/28384354/68298115-dcf08280-0098-11ea-86f8-8318f0d53d92.jpg)

Maybe in future a back key in the feature list would be good as well.

**Comment by signedav** [comment]
I close that. Feel free to reopen on further questions.
