### ISSUE TITLE
GPS / GNSS z-offset [feature request]

### ISSUE THREAD

**Issue by soester** [opengisch/QField#623]
If you are collecting field data for surveying purposes with high precision RTK GNSS-recievers the z-coordinate is extremely important. 

When digitizing Features with GNSS it is currently not possible to handle
a. antenna height above ground (if using a pole)
b. local geoid divergences

In both cases it would be enough to be able to enter a simple z-offset. To capture accurate data in real time this z-offset would have to be applied on the coordinate accquired by the gps and stored in the geometry of the feature.

We would be happy to fund this feature at least partially.

**Comment by soester** [comment]
@m-kuhn 
This could be a temporary (hopefully easier to implement) workaround to the problems according geoids discussed.
What do you think?

**Comment by m-kuhn** [comment]
As discussed by mail, it's scheduled

**Comment by signedav** [comment]
PR pending #677

**Comment by geomoes** [comment]
actually a workaround to eliminate at least the pole height would be to adapt the z-value stored in a separate field by just entering z(@position_coordinate)-2.00 (for an 2.00 m height pole) as a default value. This has been done in QGis and the offset of the z-value has to been adapted to the correct antenna heigt.

**Comment by m-kuhn** [comment]
Fixed in #677
