### ISSUE TITLE
Beautify menus lookandfeel 

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField#635]
the menus we have do not really look as nice as the rest of the application. 

## menu
![Screenshot_20190927-145057_QField Beta 624](https://user-images.githubusercontent.com/233663/65770846-34fda600-e137-11e9-8364-884d756559a5.jpg)

## long-press on gps
![Screenshot_20190927-150538_QField Beta 624 (1)](https://user-images.githubusercontent.com/233663/65771538-b3a71300-e138-11e9-9a9d-978934d3e18e.jpg)

**Comment by Emic37** [comment]
Good idea ! But for me, simply user of QField on ma smartphone, I think that the position menu can be deleted :

The option to show the localisation information could be add to the parameters, eventually in a "localisation" subsection.

Then, a long press enables or disables the localisation. A short press centers the current localisation.

This should improve a lot the experience. The use should be easier, and more intuitive. What do you think about that?

**Comment by suricactus** [comment]
These menus have recently experienced some nice redesign from @nirvn , should we close this?

**Comment by nirvn** [comment]
Agreed, we can close this.
