### ISSUE TITLE
Copy and paste

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField#66]
I'd be nice to have copy&paste in the editor fields

**Comment by m-kuhn** [comment]
This will be available (or at least easier) with [Qt 5.8](https://wiki.qt.io/New_Features_in_Qt_5.8)

> New Features in Qt 5.8
> ==================
> * Qt GUI
>   * Selection handles on Android, with edit menu for copy/paste)

**Comment by RolfBerlin** [comment]
I am not able to double-tap e.g. 2 words together or a whole sentence or datum ...

**Comment by nirvn** [comment]
This PR (https://github.com/opengisch/QField/pull/3142) implements a work around Qt limitations.
