### ISSUE TITLE
Crash when start GPS

### ISSUE THREAD

**Issue by veroniqueC** [opengisch/QField#660]
[Crash when start GPS]

### Reproduction Steps:

1. Start Qfield
2. Start GPS
3. Can't navigate on the map, it's frozen but i can go to the other menu and windows
4. restart Qfield: all is ok even GPS

### Expected behavior:

Starting GPS without frozen of map

**QField version: 1.2.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Probably also existed before: https://github.com/opengisch/QField/issues/558
Workaround: kill and restart the app (should only need to be done once)

**Comment by signedav** [comment]
Hi @veroniqueC 
Can you test that with the current master version [here](https://github.com/opengisch/QField/commit/3249a9ac1ee1e4fe38f549b6f58663cd538391d3#commitcomment-35774953)? I think, this is solved.

**Comment by veroniqueC** [comment]
Hi,

I 've tried the master and no, it's froze when i start the GPS the first time. After it's OK.

**Comment by signedav** [comment]
Okay, so I leave this issue open. Thanks for testing :slightly_smiling_face:

**Comment by veroniqueC** [comment]
Hi, same issue with the 1.7.4 version on all our devices.

**Comment by nirvn** [comment]
@veroniqueC , can you give QField 1.8.3 a try? Permission requests have been re-written and might well have fixed your freeze-on-first-GPS-use issue.

**Comment by veroniqueC** [comment]
I tried it on 2 devices and it's seem OK. No freeze, and it find position very quickly

**Comment by nirvn** [comment]
@veroniqueC , fantastic. We'll close this issue and hope to never open it again 😉

**Comment by veroniqueC** [comment]
Sorry but the probleme is here again...
I tested 2 samsung galaxy tab and a smartphone (xcover4s):
- on the first samsung there is a glonass gps (qfield 1.8.3)
- on the 2nd only the internal tab GPS(qfield 1.8.3)
- on the smartphone only internal GPS(qfield 1.7.3)

I took the same tracks on the 3 devices. But the 2nd device loose the gps signal and freeze, so no tracks registered. No pb on the 2 other devices

**Comment by nirvn** [comment]
If you're trying multiple smartphones against one gps device, you'll likely face connectivity issues. 

QField itself doesn't crash right? You meant it in a metaphorical way? :)

Also, by freezing you mean position updates aren't received and the location is therefore "frozen"?

**Comment by nirvn** [comment]
If you're trying multiple smartphones against one gps device, you'll likely face connectivity issues. 

QField itself doesn't crash right? You meant it in a metaphorical way? :)

Also, by freezing you mean position updates aren't received and the location is therefore "frozen"?

**Comment by veroniqueC** [comment]
Qfield crash: the map is frozen when qfield loose the gps signal and i must to restart qfield. I just think that qfield don't loose the gps signal on the 2 other device

**Comment by veroniqueC** [comment]
Hy,
Still have the pb on qfield 1.8.4 :( Can you re-open the issue?

Qfield frozen when i loose GPS signal, i can't move on map anymore. I must restart qfield.

### Reproduction Steps:

1. start GPS in qfield
2. lost GPS signal

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]
