### ISSUE TITLE
App crashed - version 1.2.0

### ISSUE THREAD

**Issue by ElvisDahnert** [opengisch/QField#664]
Is impossible use version 1.2.0. I'm has problem with my projects. Application closes unexpectedly with zoom out.

### Reproduction Steps:

1. Open a project
2. Manipulate the screen, search, enter features, zoom out ...
3. The app crashes again

### Expected behavior:

Work with any project.

### Observed behavior:

My project is read, but the application is closed after reducing or enlarging the map. This did not occur in version 1.1.1. Would it be a problem of rendering?
I did preparing projects directly from QGIS to QField, without using qfieldsync, didn't work.
I did preparing the projects using qfieldsync, it didn't work either.
Layers are in Geopackage.
The demo projects are working perfectly in version 1.2.0.

### GIF & Video

https://youtu.be/US863TV2Y_w

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/48390608/66366367-90fdd100-e966-11e9-8e51-3f67dc511bdc.gif)

**QField version:** 1.2.0 - (10200993)
**Android version:** 7.1.1
**Smartphone:** Motorola Moto G4 Play

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: No
* Problem happens with all files and projects, not only some files or projects: No

**Comment by signedav** [comment]
Hi @ElvisDahnert 
Do you notice the same issue on the demo projects as well?
Would it be possible to provide us your project files?
Thanks a lot.

**Comment by ElvisDahnert** [comment]
Hi @signedav 
The problem does not occur with demo projects.
I realized that my project has a problem with only one layer, it is isolated here... [Projeto.zip](https://github.com/opengisch/QField/files/3820176/Projeto.zip)
Note that the line thickness and font size are being calculated according to the scale (@map_scale).
Thanks a lot.

**Comment by signedav** [comment]
Okay. I can reproduce it with your project. Thanks.

**Comment by ElvisDahnert** [comment]
Since the release of version [1.3.1](https://github.com/opengisch/QField/releases/tag/v1.3.1) the problem has not occurred. So, I am closing this issue.
Thanks a lot!
