### ISSUE TITLE
Reload WFS feature from webservice on form opening and after edit

### ISSUE THREAD

**Issue by monodo** [opengisch/QField#665]
Reload WFS feature from webservice on form opening and after edit

### Reproduction Steps:

1. Add a new feature on a WFS layer, edit a few attribute, save and close the form in Qfield in a client that we will call "client 1"
2. Click on the feature on the map again in order to open the form => the unique id is = 0 and not the value that is stored in db.
3. Edit the feature attribute from another client (Geomapfish, other QField, ...) "client 2"
4. Click on the feature again => the edits done with "client 2" are not loaded in "client 2"

### Expected behavior:

Edits from "client 2" should be visible when form in opened again in "client 1"

### Observed behavior:

Edits from "client 2" are not visible when form in opened again in "client 1"

**QField version:** master

https://github.com/opengisch/QField/commit/79b14a6845df8406357b81f57732d0333c4edb4c

## Additional information:

Without adressing all the challenges of concurrent edition, it would be a useful improvement to have the attributes of the selected feature reloaded at form opening time. Futher improvement would be an button to reload a given layer.

**Comment by monodo** [comment]
Workaround: use uuid instead of serials.

**Comment by m-kuhn** [comment]
@monodo is this fixed with #1473 ?
