### ISSUE TITLE
Problem with editing point geometry 

### ISSUE THREAD

**Issue by LeelooSIG** [opengisch/QField#666]
Hello everyone, 

I try to use Qfield for a forestry inventory. So my shapefile is point feature.
It work well to put information related to existing point.
But when I try to create a new point, nothing happen. 
- no creation of the point (the GPS is actived and I see the yellow cross-circle, but I can't record)
- the form doesn't open.

Does anyone know why ? thanks in advance

**Comment by LeelooSIG** [comment]
Yes of course : this is a wetransfer.com link : https://we.tl/t-XmcoBt8Yne

**Comment by signedav** [comment]
The wetransfer link is not available anymore.
Do we have here a status or more information @LeelooSIG @3nids ?

**Comment by signedav** [comment]
Hi @LeelooSIG
Did you tried with the latest QField release? Do you have another test project to reproduce?
Thanks

**Comment by m-kuhn** [comment]
Closing for lack of feedback.

@LeelooSIG please leave a comment if this is still an issue.
