### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by JAVIERSIG** [opengisch/QField#667]
Hello; I want to collaborate on the Qfield project, at the moment in the Spanish translations, but I don't see the way, how can I do it?

**Comment by m-kuhn** [comment]
Hi @JAVIERSIG is there an open question regarding this or can we close this issue?

@ElvisDahnert thanks for the help. I have just added the translation to "Portuguese (Brazil)" as you requested. Please note, that we already have a translation for "Portuguese" (generic), having two different translations in place means more work as we have to keep alive two different translations. Was this your intention or should I delete "Portuguese (Brazil)" again and you can help on the generic "Portuguese" translation instead?

**Comment by JAVIERSIG** [comment]
@ElvisDahnert  Hello;
No, I don't want to duplicate the work at all (I already have enough); I was referring in Spanish, not in Portuguese. Regards

**Comment by m-kuhn** [comment]
Hi @JAVIERSIG your help on the Spanish translation will be much appreciated. Please sign up on travis and ask to collaborate on the QField team (see the link posted by @ElvisDahnert).

The comment on Portuguese was for @ElvisDahnert only, sorry for asking this unrelated topic.

**Comment by ElvisDahnert** [comment]
Hello

@JAVIERSIG, you will like to translate through transifex, it is quite simple.

@m-kuhn, thanks for the clarification! Please keep both, I would like to perfect the app for my countrymen.

**Comment by m-kuhn** [comment]
Perfect, let's close this issue then.
