### ISSUE TITLE
By default open .qgs files with QField

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField#67]
Need a way to open a .QGS file by default when opening QGIS.

Hints:
http://stackoverflow.com/questions/4799576/register-new-file-type-in-android and remember that for now all argv are stripped

**Comment by mbernasocchi** [comment]
ideally than we could put a link to a file on the desktop and allow easily opening a project

**Comment by m-kuhn** [comment]
Fixed in 3546d1df05ea2c4b1636e535b4e482041dd74dcb
