### ISSUE TITLE
Split features

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#675]
It should be possible to split polygons with a line.

Attributes should be copied to both new features (or one new feature and the existing feature have the geometry replaced). Except for attributes with unique constraints, those shall be handled in the default QGIS way (e.g. using QgsVectorLayerUtils.createFeature).

Workflow:
1. Select feature
2. Choose edit geometry
3. Choose the split geometry tool
4. Draw the line
5. Enjoy

**Comment by signedav** [comment]
This is integrated.
