### ISSUE TITLE
Cannot install test apk

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#687]
@Emic37 wrote https://github.com/opengisch/QField/pull/677#issuecomment-544223568

> did you make changes about the compilation of the test apks this last days ?
I cannot install anymore all of the new test-apks armv7 which were released since 4 days.
> 
> all happens as if there is no issue. The installation Wizard opens, works a few seconds and when the progress bar is completed, it displays "app is not installed".
> 
> it doesn't work when I uninstall the previous version before.

**Comment by m-kuhn** [comment]
@Emic37 to make sure we are on the right track, can you check if this was introduced between these two versions (i.e. one works, the other does not):

https://github.com/opengisch/QField/commit/8e41684be6528d0eba204d6c2617491c49546aa2#comments

and

https://github.com/opengisch/QField/commit/9383cf5d85b3f33930da5ceb1ed63b17dfef2fa4#comments

**Comment by Emic37** [comment]
No. I encountered the same issue with these two version. The problem seems to be older.

**Comment by Emic37** [comment]
@ m-kuhn, I just tried and it works with arm64v8 version.

**Comment by Emic37** [comment]
@mbernasocchi wrote https://github.com/opengisch/QField/pull/677#issuecomment-544496013

> @Emic37 could you try uninstalling QField installed from the playstore?

@mbernasocchi I just tried that. It works. And that's right, when I tested with a more modern phone, QField was not installed on it.
I just tried to install a test apk of Qfield while QField stable is installed (from Play Store) on this new phone and I encounter the same issue as with an armv7 phone.

So it's not possible anymore to install the stable version and a beta version ? But maybe it's a normal behavior ?

**Comment by Emic37** [comment]
No good new. Both doesn't work.

**Comment by signedav** [comment]
I can confirm the issue. There is no test version installed beside the original implementation.

**Comment by m-kuhn** [comment]
#710 should fix this

**Comment by Emic37** [comment]
@m-kuhn thanks, that seems to work again.

**Comment by m-kuhn** [comment]
@Emic37 so unrelated question, what's your opinion about the adjusted font size?

**Comment by Emic37** [comment]
@m-kuhn : https://github.com/opengisch/QField/pull/710#issuecomment-552633804
