### ISSUE TITLE
Layers unstable when "Show Feature Count" option is checked

### ISSUE THREAD

**Issue by rwjdennis** [opengisch/QField#688]
QField layers are unstable when their QGIS Desktop analogues have the "Show Feature Count" box checked.

### Reproduction Steps:

1. In QGIS desktop, check "Show Feature Count" on a vector layer that will be edited in QField. Package project for QField and load onto device.
2. In QField, toggle to _Digitize_ mode and add a point to the layer.

### Expected behavior:

Based on typical workflow, the point should be added and the layer should still be visible.

### Observed behavior:

The added point does not show up, the layer disappears, and an error message may be given in the log

### Screenshots and GIFs

QField map, in Digitize mode. No new features have been added since project has been opened.
![Screenshot_20191021-150435_QField 1](https://user-images.githubusercontent.com/18429044/67235547-49228380-f415-11e9-9bdc-7b390e34a45a.jpg)

Add new feature form with some fields populated.
![Screenshot_20191021-150608_QField 1](https://user-images.githubusercontent.com/18429044/67235638-7e2ed600-f415-11e9-875a-d90dec7f7f56.jpg)

QField map after feature has been "saved". Note none of the previous points are shown on map. Feature counts are also wrong. New feature is also not shown.
![Screenshot_20191021-150619_QField 1](https://user-images.githubusercontent.com/18429044/67235678-94d52d00-f415-11e9-90b8-c0b0e2b6725c.jpg)

**QField version:** 1.0.4 - Matterhorn (10004993)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No. Only files that are being edited.

Updating features when there is a symbology rule based on some update information also causes the same problem. For example, the layer in the screenshots is set to display features that are updated differently than those that have not been updated, so when existing features are updated, the layer disappears.

In previous instances, QField does give an error message: "Feature ## could not be fetched after commit".

Unchecking the "Show Feature Count" box in QGIS desktop clears the problem.

**Comment by m-kuhn** [comment]
@rwjdennis @Emic37 can you check if #694 fixes your issues?

**Comment by Emic37** [comment]
@m-kuhn That seems to be ok for me. Thanks!

**Comment by signedav** [comment]
This fix will be in the upcoming release.

So I close this bug report. Thank you, guys.
