### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QField#70]
QField misses SSL support for WMS / WMTS / WFS / Postgis... connections

```
09-08 09:11:34.753 11498 11527 W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve CRYPTO_free
09-08 09:11:34.753 11498 11527 W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve EVP_rc2_cbc
09-08 09:11:34.753 11498 11527 W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
09-08 09:11:34.753 11498 11527 W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
09-08 09:11:34.753 11498 11527 W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve EC_get_builtin_curves
09-08 09:11:34.753 11498 11527 W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot resolve EC_curve_nist2nid
09-08 09:11:34.753 11498 11527 W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot call unresolved function EC_get_builtin_curves
09-08 09:11:34.753 11498 11527 W QField  : (null):0 ((null)): qt.network.ssl: QSslSocket: cannot call unresolved function EC_get_builtin_curves

```

**Comment by luipir** [comment]
are QCA and openssl available under android?

**Comment by m-kuhn** [comment]
QGIS doesn't compile without QCA since it was introduced. So we were required to cross compile this to still build QGIS.
OpenSSL should be available. If not in can be cross-compiled.

**Comment by luipir** [comment]
hmmm... well now QCA is part of QT5 distribution, I didn't realised you where using qt5, sorry I'm not used with QField.

**Comment by m-kuhn** [comment]
> well now QCA is part of QT5 distribution

That sounds interesting because we still use a self-compiled one. Do you have any pointers? I'm happy for every dependency that can be removed.

**Comment by luipir** [comment]
it's a QT5 submodule... just looking for the link

**Comment by luipir** [comment]
sorry my fault (as usual) it's still external

**Comment by luipir** [comment]
and probably a auth partial rewrite will be necessary to use now qt5 supported ssl infrastructure (also for keystore interface)
http://code.qt.io/cgit/qt/qtbase.git/tree/src/network/ssl?h=5.8

**Comment by mbernasocchi** [comment]
in the past I played around with ssl already:
https://github.com/qgis/QGIS-Android/blob/master/scripts/build-libs.sh#L298

**Comment by 3nids** [comment]
@m-kuhn fixed?

**Comment by m-kuhn** [comment]
Yes
