### ISSUE TITLE
HTML link in feature's form widget not working

### ISSUE THREAD

**Issue by avinashtavares** [opengisch/QField#709]
I've created a layer having features and each feature has an attribute which creates a google maps links by using the latitude and longitude of the feature. In qgis, the field gets rendered as a clickable link which opens google maps in the browser.

However, when the attribute is rendered in qfield, when rendered the link is not clickable and behaves like ordinary text.

The Expected behavior is that when the link is clicked, google maps must open with the location of the feature so that the surveyor gets the directions to the location of the feature. 

I tried making a link using actions but qfield did not display the action buttons in the form

**QField version:  1.2.0 

Qgis shows link
![image](https://user-images.githubusercontent.com/57594309/68546173-cda36900-03f9-11ea-996a-999c75f50b46.png)
Qfield does not show link
![Screenshot_2019-11-10-20-43-17-177_ch opengis qfield](https://user-images.githubusercontent.com/57594309/68546310-d9435f80-03fa-11ea-8cd4-2162a80df4b1.png)

**Comment by avinashtavares** [comment]
Qgis shows link
![image](https://user-images.githubusercontent.com/57594309/68546173-cda36900-03f9-11ea-996a-999c75f50b46.png)
Qfield does not show link
![Screenshot_2019-11-10-20-25-59-971_ch opengis qfield](https://user-images.githubusercontent.com/57594309/68546036-d34c7f00-03f8-11ea-9410-a027888899ea.png)

**Comment by ElvisDahnert** [comment]
I would also like to add a link to my features.
I even found this in my search.

![S20](https://user-images.githubusercontent.com/48390608/68633415-9358cb00-04d0-11ea-8b33-c586b259fb6d.png)
[http://talks.opengis.ch/qfield-workshop/#20](url)

**Comment by signedav** [comment]
Thanks for reporting. I agree that this is, what you would expect on an URL.
I guess the widget needs to be improved to make the URLs clickable.

**Comment by alansaviolobo** [comment]
The link works fine as long as you are "viewing" the attributes of the feature.
When you try to edit the feature, then the link turns into a textbox to allow editing.

**Comment by signedav** [comment]
Yes. This has been implemented meanwhile. We can close this. Thanks.
