### ISSUE TITLE
QField 0.8.1 crashes during startup on Fairphone 2

### ISSUE THREAD

**Issue by etiennethomassen** [opengisch/QField#71]
QField 0.8.1 crashes after it has loaded the menu and crosshairs icon on the top left. From the black screen it just closes/disappears.

### Reproduction Steps:

1. Open QField
2. ...

### Expected behavior:

Appearence of previous openen project. Like 0.7 verion did on my Fairphone2 

### Observed behavior:

QGIS crashes on startup

### Screenshots and GIFs

none

**QField version:** 0.8.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes (since 0.8.0)
* Problem can be reliably reproduced, doesn't happen randomly: Yes, every startup
* Problem happens with all files and projects, not only some files or projects: I don't know.

**Comment by m-kuhn** [comment]
Probably there is a layer which cannot be loaded. We are aware of this problem and working on it. In the meanwhile, try to figure out which layer could be responsible and temporarily remove it.

**Comment by etiennethomassen** [comment]
I found the layer that triggers the problem. It is a WMS layer. 

This is it's source:
tileMatrixSet=nltilingschema&crs=EPSG:28992&layers=luchtfoto&styles=&format=image/jpeg&url=http://geodata1.nationaalgeoregister.nl/luchtfoto/wmts/1.0.0/WMTSCapabilities.xml

It works as expected without the WMS layer

**Comment by m-kuhn** [comment]
Probably related to https://github.com/opengisch/QField/issues/70

**Comment by stamogis** [comment]
On my Galaxy Tab S2 with Android 6, I can't load any WMS services since the last two QField Updates (0.81 / 0.86) - no matter whether the WMS is ssl encrypted or freely accessible (e.g. http://ows.terrestris.de/osm/service?).

**Comment by m-kuhn** [comment]
All fixed in 0.8.7
