### ISSUE TITLE
Form does not appear correctly in search mode

### ISSUE THREAD

**Issue by geomondego** [opengisch/QField#712]
Using version **1.3.0** when I try to perform a search, I noticed that the configured form does not appear correctly.
In the images below, the first image shows the form using the **_Identify_** tool. The second shows the form view when using the **_Search_** tool.

Data is a PostGIS database and the form have special characters such as ÇÃO, etc. 
Will it be related with encoding?

### Screenshots and GIFs
![img1](https://user-images.githubusercontent.com/4389239/68774134-8cdb6800-0624-11ea-8675-ca0e3b9e4f0d.png)
![img2](https://user-images.githubusercontent.com/4389239/68774136-8cdb6800-0624-11ea-8540-cc0677601d1b.png)

**QField version:** [1.3.0 - Ben Nevis (10300995)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: [No]

**Comment by signedav** [comment]
Weird. We need to investigate.
Thanks for reporting @geomondego

**Comment by suricactus** [comment]
@geomondego Is this still an issue?

**Comment by geomondego** [comment]
> @geomondego Is this still an issue?

No. Can be closed
