### ISSUE TITLE
Record sounds with microphone

### ISSUE THREAD

**Issue by MMR100** [opengisch/QField#715]
One colleague working in environmental field is interested in recording animals sounds. Is it possible to open the microphone from a form in Qfield ?

**Comment by signedav** [comment]
I like the idea but it's not yet possible. Thanks for your input.

**Comment by m-kuhn** [comment]
This is implemented since release 2.7.0
@nirvn do you think we can close this?

**Comment by nirvn** [comment]
@m-kuhn , yep we can close that, implemented across all platforms we support
