### ISSUE TITLE
Already filled form + point not appering on the map

### ISSUE THREAD

**Issue by varrieta** [opengisch/QField#72]
When you create a point, the informations and picture of the last created point stays (even if we didn't check the box next to the attribute). Also some of the points created don't appear on the map (eventhough they are created in the layer). 

### Reproduction Steps:

1. Create a point with pictures and informations
2. Create a new point 

### Expected behavior:

An empty form to create the new point

### Observed behavior:
The form is already filled with the informations and picture of the latest point created. Then even if you refill the form, the point doesn't appear physically but is created.

**QField version:** 0.8.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of Atom: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by m-kuhn** [comment]
This doesn't seem to happen here.
Are you able to share a project that shows this behavior?
