### ISSUE TITLE
Offline Base Map cannot be zoomed in

### ISSUE THREAD

**Issue by avinashtavares** [opengisch/QField#721]
When using the offline base map option, only a single zoom level of map is saved. Therefore, in remote areas where internet is unavailable, the surveyor is unable to identify the exact location of the destination (eg waterbodies).

It appears that qfield does not accept more than 50000 as an input for the number of tiles, in the configuration form. Only is the input is less than 50000, the base map is saved. Basemap file saved in this case is maximum of 32 mb. If i input a figure above 50000, a file of less than 1 mb is saved. 

I hope the bug is fixed and we get an option of saving a more detailed offline map.

**Comment by signedav** [comment]
Hi @avinashtavares 
Thanks for reporting.

Where do you define the number of tiles? In QFieldSync? There is a field to define the tile size.
If you want to have a more detailed map, please test it with a lower mapunit/pixel configuration.
