### ISSUE TITLE
Value Relation Widget Improvements

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#724]
To have it here as enhancement request instead of input comments in this PR https://github.com/opengisch/QField/pull/600

- [x] Filter functions 
- [ ] Completer

**Comment by signedav** [comment]
FYI @jhonalex06 and @Emic37

**Comment by Emic37** [comment]
Really good! I am your tester... 😉

**Comment by 9ls1** [comment]
Any progress regarding the Auto completer? Quite inconvenient to scroll through more than 400 species which is the case in one of my cases.

**Comment by signedav** [comment]
Not in the completer but on the filter - maybe this helps already to organize your form.

**Comment by she-weeds** [comment]
@signedav This would only work if you had one column for entering search words and another column for the dropdown list. Thus necessitating the creation of an extra column in the schema purely for data entry purposes and adding complexity where it is really an UI problem. It is a sufficient workaround for now but if there was any way to support the development of autocomplete in the QField form itself, that would really take this to a killer app level, IMO :)

**Comment by signedav** [comment]
I totally agree on that @she-weeds Would be great to have it solved in the UI.

If it's important for you and you are interested in sponsoring it (or parts of it) then please contact us :heart: :seedling:

**Comment by 9ls1** [comment]
How about making a campaign (like the one you had for the camera implementation) - alone or together with option row (one of my other wishes for QField)?

**Comment by signedav** [comment]
There are more infos as well #264

**Comment by m-kuhn** [comment]
@suricactus is this fixe?
