### ISSUE TITLE
Expression now() is not working in Qfield

### ISSUE THREAD

**Issue by bakkerss** [opengisch/QField#728]
In Qgis I have a layer which is used to record bat sightings in my case. Each sighting should be stored with a date and timestamp. I have used a date/time widget for this and used expression now() to display a default date or time

On my desktop this is just working fine (for bioth 3.4 Madeira and 3.10 Coruna). The current date and time are proposed and I am allowed to change the proposed value. However, when I try to add sightings in Qfield the date and time fields are empty and I need to add these manually. This is very annoying when working in the field.

When I open de date field I can simply select the current date and this date is copied correctly in the field. 

### Reproduction Steps:

1. Project is copied to Tablet and opened in Qfield
2. I open the layer to add new sightings.
3. The date and time field are displayed in a grey box showing __-__-__. The current date and time are thus not proposed.
4. When I open de date field I can select a date from the calendar menu and this date is copied correctly in the field. However, normally I don't want to perform this manual step.
4. When I open de time field I need to manually add a time. When I enter 11:11:11 a random time suddenly appears (10:51:39) while the current time on my tablet is 17:23. In this case I am not able to add a correct time

### Expected behavior:

I expect the same behaviour in Qfield as in Qgiis

### Observed behavior:

As described in the reproduction steps

### Screenshots and GIFs

(https://github.com/opengisch/QField/files/3897868/Qfield.issue.date.now.function.pdf)

**QField version:** 1.2.0 - Matterhorn (10200997)

**Comment by saemiw** [comment]
Can you provide printscreens of your default and date/time widget settings in QGIS. We are successfully using now() on the same version. I think it must be an issue of how you set up the project...

**Comment by bakkerss** [comment]
I have played around with some of the widget settings successfully. The dates are now proposed. But there still seems to be a bug. If you change the time manually a default time is subtracted from the inputted value. See attachment for more information.

[Qfield issue 728.pdf](https://github.com/opengisch/QField/files/3902345/Qfield.issue.728.pdf)

Furthermore, now the major issue with the date and time is solved suddenly my user account field is also displaying the OS user name. Before it showed an error 'not available'. I haven't made any modifications to this field. So it seems fixing the issues for the date and time field also fixed the other problem. So I will close the ticket I raised for that problem as well.

**Comment by ghtmtt** [comment]
I can confirm the issue using QGIS master and QFIeld 1.2. Basically if the ``Default Value`` is set to `now()` in QGIS it is correctly updated while in QField not (it waits for an user input).

**Comment by signedav** [comment]
I tried to reproduce without success. Can you provide a test project?

I do have always the current time like it should be:
![WhatsApp Image 2019-12-04 at 15 47 47](https://user-images.githubusercontent.com/28384354/70152433-82554100-16ad-11ea-8e2f-86e61d69b2e0.jpeg)

@bakkerss 
> When I change the time manually to 12:00:00 it changes to 11:40:28

When does it change the time? After typing in? On saving and reopening?

**Comment by ghtmtt** [comment]
It works only if you add a new geometry and not if you update and existing field of an existing geometry.

**Comment by bakkerss** [comment]
I would like to mention that I also reported an issue in QGIS which relates to this Qfield issue. It looks like there is also an issue storing time when using the now() expression in QGIS. See https://github.com/qgis/QGIS/issues/33303 for more information.

Currently time is only stored correctly in QGIS if the field has data type string. In this case the current time is also proposed by default. However, when syncing this field to Qfield this field is empty in Qfield. See also the attachment for an example.

[QGIS issue - further info.pdf](https://github.com/opengisch/QField/files/3955844/QGIS.issue.-.further.info.pdf)
Looking at my basic requirement (propose by default the current time) this could also be solved if Qfield has the exact same behaviour as QGIS. So if the data type of a field is ‘string’, the widget type is ‘date/time’ and the field format is ‘time’ then by default Qfield should  display the current time of the device. 
In this way you can also bypass the now() problems in both QGIS and Qfield. Solving the now() issue in Qfield will still cause a problem if the now() issue is not solved in QGIS.

**Comment by bakkerss** [comment]
I am closing this issue as QGIS and Qfield behave differently in the current version. I will raise a new issue
