### ISSUE TITLE
Alias and widgets no tworking together

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#73]
If you enter an alias, there is no widgets settings. only line edit. Removing an alias note, widgets settings will be restored.

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**QField version:** [Enter QField version here]

## Additional information:

* Problem started happening recently, didn't happen in an older version of Atom: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by m-kuhn** [comment]
Which version is affected?

**Comment by giedrioks26** [comment]
QFIELD 0.8.1 on android 5.0 samsung galaxy core prime

**Comment by m-kuhn** [comment]
This works for me. Can you provide more details?

**Comment by giedrioks26** [comment]
On QGIS desktop layer Properties --> Fields. When filling out the "Alias", widgets settings does not work on qfield. Only "Text edit". [https://s16.postimg.org/cft16x65x/image.png](url)
Project  her [https://drive.google.com/file/d/0BzfwITizxXObRVBrdWRNUmxlbEk/view?usp=sharing](url)
In project two layers. One without an alias (points), the other with an alias (points_alias).

**Comment by giedrioks26** [comment]
And yet I noticed. With Alias, click on the point show empty fields, although the data is entered.

**Comment by m-kuhn** [comment]
As a workaround until the next release, please use a drag and drop designer form.
