### ISSUE TITLE
Crash QField when project contains PostGIS layer(s)

### ISSUE THREAD

**Issue by ghtmtt** [opengisch/QField#730]
When the `qgs` file contains one or more remote layers stored in a PG DB and the credential to access to the DB are **not** saved within the file, when opening the project in QField the APP crashes.

### Reproduction Steps:

1. Connect to a DB Postgres **without** service and **without** storing the user/pws into the project
2. Import a vector layer in QGIS from a DB Postgres
3. Save the project
4. Copy the project to the QField folder
5. Open the project in QField

The app crashes and no additional information are given.

If the user/pws are stored in the `qgs` file then no problems happen. 

### Expected behavior:

QField asks for the user/pws if not stored in the DB or gives an error.

### Observed behavior:

APP crash

**QField version:** 1.2.0 (10200993)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
Thanks for reporting. I need to investigate here.

**Comment by signedav** [comment]
Hi Matteo

While I can reproduce the crash on 1.2 it does not happen anymore on 1.3. There we have a proper message like this:
![20191128_173737](https://user-images.githubusercontent.com/28384354/69822258-2babbb00-1206-11ea-8580-2bc5b6292995.jpg)

Please test it and if there is no crash

**Comment by ghtmtt** [comment]
1.3 not release in google store right? BTW: thanks for checking!

**Comment by signedav** [comment]
Not yet. Just for beta testers.
But you can find the apks here as well: https://github.com/opengisch/QField/releases/tag/v1.3.1

**Comment by m-kuhn** [comment]
@ghtmtt 1.3 is released, are you able to confirm the fix?

**Comment by 80ben** [comment]
Version Qfield: 1.3.4 Ben Nevis.

There are still problems with the postgis connection!


![Screenshot__QField](https://user-images.githubusercontent.com/30823307/72877813-01541680-3cfa-11ea-9c4f-53ed1b2f0d86.jpg)

**Comment by m-kuhn** [comment]
@80ben a timeout is a strong indicator that there is a problem in the network configuration unrelated to QField.

**Comment by 80ben** [comment]
@m-kuhn 
 I solved,
there was a network block

**Comment by nirvn** [comment]
Good to hear.
