### ISSUE TITLE
Problem with boolean type field (Postgres)

### ISSUE THREAD

**Issue by ghtmtt** [opengisch/QField#731]
Seems that QField has some problems with `boolean` field types defined in PG. Simply enough, even if all the features have NULL values (in QGIS), when the offline project is created and loaded in QField, the boolean (recognized as automatically as checkbox by QGIS forms) is checked for every feature and is not possible to chance the state.

Running QGIS master on debian with Postgres 11.5.

### Reproduction Steps:

1. just create a boolean field type in PG and follow the standard QField - Sync workflow

### Expected behavior:

Changeable state of the checkbox

### Observed behavior:

Checkboxes are always checked and not editable (BTW, QGIS has no problems to chance the state)

**QField version:** 1.2.0 (10200993)

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Fixed in QGIS master / 3.12
