### ISSUE TITLE
Offline project crash if layer(s) are set to "No action"

### ISSUE THREAD

**Issue by ghtmtt** [opengisch/QField#733]
If one or more layer of a PG DB are set to "No action" in the QFieldSync plugin, QField crashes.

### Reproduction Steps:

1. Set a layer as "no action" in the plugin
2. Load the project in QField

### Expected behavior:

Not crashing and the layer(s) should be there but no action could be performed

### Observed behavior:

[Describe observed behavior here]

### Screenshots and GIFs

Here the sample project to directly load in QField (created with the QFieldSync) plugin.

[pontedera-offline.zip](https://github.com/opengisch/QField/files/3912484/pontedera-offline.zip)

**QField version:**1.2.0 (10200993)

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
I'm pretty sure this will be solved with QField Version 1.3.1.
https://github.com/opengisch/QField/releases/tag/v1.3.1
Since it has been a QGIS bug once, that it crashed.

Can you test again with 1.3.1?

**Comment by ghtmtt** [comment]
will do that ASAP, thanks

**Comment by m-kuhn** [comment]
@ghtmtt did you manage to test again?

**Comment by ghtmtt** [comment]
not yet. I'll do that ASAP.

**Comment by kandre** [comment]
I confirm the problem on latest versions : 
QField v1.5.3
QfieldSync v3.3.0
