### ISSUE TITLE
GPS does not work with ETRS89 / UTM Zone 32 N

### ISSUE THREAD

**Issue by bsturm** [opengisch/QField#737]
Before the Map just froze when activating GPS in a project in ETRS89 - Problem vanished with reinstallment. Now, after toogling Positioning, the Position Marker shows coordinates switch around, so instead of my office in germany, the pointer is somwhere in Somalia. Projects in Gauss-Krüger do work.

### Reproduction Steps:

1. Open Project in CRS ETRS89
2. Toggle GPS
3. Marker appears with long and lat switched around.

### Expected behavior:

Correct Positioning within selected Project.

### Observed behavior:

GPS shows incorrect coordinates, x and y are switched.

![Screenshot_20191205-141547](https://user-images.githubusercontent.com/58474997/70238983-b0e52180-176a-11ea-843d-19b7973144f5.png)

**QField version:**  1.2.0 (10200997)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [unknown]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No]

**Comment by signedav** [comment]
Can you please check with the latest version? 1.3? Thanks.

**Comment by bsturm** [comment]
> 
> 
> Can you please check with the latest version? 1.3? Thanks.

@signedav 
It is working now. I am currently using 1.4.4. Olavtoppen
I am very Sorry for answering that late!

**Comment by signedav** [comment]
Great. Thanks.
