### ISSUE TITLE
Enabling GPS clears the map

### ISSUE THREAD

**Issue by LostCollection** [opengisch/QField#738]
I'm currently trying to use QField on Trimble TDC600s. When I try and enable GPS position display on the map, the display clears off and leaves a single dot on it. Every other feature is working as intended including the display of position information at the bottom of the screen.

Please note: I have tried reinstalling as that seemed to fix this for at least some others in the past. This also occurs on multiple units. Additionally when I long press to turn on and off positioning, I get an error message that QField does not have permissions to positioning when turning it off, but no error message when enabling it.

QField version 1.3.1 QGIS version 3.10. Data layers are in a geopackage on the Trimble.

**Comment by LostCollection** [comment]
This issue appears to have been a CRS issue.  It works when using WGS84 but not ESRI 120761

**Comment by m-kuhn** [comment]
Interesting, I could imagine that it's related to inverted X/Y axis. Unfortunately I cannot find any reference to ESRI 120761, is there a different name for it? Is it shipped out of the box on QGIS?

**Comment by m-kuhn** [comment]
@LostCollection could you provide us with a test dataset?
