### ISSUE TITLE
porting to ubuntu touch

### ISSUE THREAD

**Issue by sem-geologist** [opengisch/QField#74]
Hello, I want to port this app to ubuntu touch. I never ported anything to that platform ( especially to such a bugy platform), however I tried compiling this on debian and it worked on debian, so I guess I could try doing version for UT. most probably it would be unconfined, and would require kernel recompilation of ubuntu ( to enable any non internal gps, (yes the platform is ****\* by default)). I didnt checked the code for gps on qfield, does it use android hal, or is it possible to use usbserial, or gpsd?

**Comment by m-kuhn** [comment]
I haven't ported anything to UT, but [looking at the developer page](http://www.ubuntu.com/phone/developers) it looks like the mainly use Qt/QML for their apps and this is what QField uses as well, so most of it should be straightforward.

For the GPS it uses QtPositioning which I assume should com with proper drivers on UT as well. There seems to be the possibility to write plugins for this but we have never looked into this. We will probably also be working on some NMEA capabilities (mostly for advanced positioning features like RTK).

If you happen to have to reimplement a different backend for something, have a look at how picture handling is done. There is [a generic picture source interface](https://github.com/opengisch/QField/blob/master/src/picturesource.h) which can be [reimplemented for android](https://github.com/opengisch/QField/blob/master/src/androidpicturesource.h) or whatever platform you like.

**Comment by sem-geologist** [comment]
I actually have give up and simply flashed android on my tablet, where Qfield rocks. I used it for my field work last month that is such a nice application.
 For my disappointment there is no GNU/linux/non android platform at the moment worth of any effort (maybe KDE plasma mobile?) The Ubuntu Touch is particularly ****** up mess. 1. The Qt is 5.5 and looks is not going to be upgraded any time soon (thanks to Mir crap), the GPS is ***** completely: the internal gps custom driver and its usability is laughable joke and external gps is locked out.  I see it have no future. Eventually it could be worth trying to port this to Sailfish OS at the beginning of 2017 if I will have the time to port it to my tablet... I think most prominent mobile GNU/Linux for this app is KDE plasma mobile, which uses Qt 5.7 already, but it also requires enormous effort to be ported to my tablet. Pretty annoying situation, but good this works and rocks on the android. I am going to close this issue and if I will get any of SFOS or KDE plasma-mobile on my hardware I will open up new issue :).

**Comment by m-kuhn** [comment]
Thanks for the in-depth update.

We'll probably be updating to Qt 5.7 soon (solves issues like #60 and offers [new nice controls](https://blog.qt.io/blog/2016/06/10/qt-quick-controls-2-0-a-new-beginning/)).

Also it's likely that NMEA GPS connections will be integrated besides the builtin one.

Keep us posted on the progress.
