### ISSUE TITLE
nm_relation widget: "Parent primary keys are not available."

### ISSUE THREAD

**Issue by Jean-Zombie** [opengisch/QField#740]
I have a functioning n-to-m relation set up in my QGIS-project (Postgis). I can associate my features in the attribute form resp. subform and everything gets written to the pivot table. Trying the same in QField **with a newly create feature** gives me the `Cannot add child. Parent primary keys are not available` error. On an **already created feature** it works fine, though. 

For troubleshooting I inspected this repos "middleearth_cardinality" [sample-project](https://github.com/opengisch/QField/pull/568). The relevant difference I spotted is the use of an extra id field for the n-to-m relation (with a default value generated by the uuid function). 

**My question: Is an extra id field with a default uuid value the only way to make n-to-m work in QField?** 

…or can I somehow replicate the working QGIS behavior, i.e. stick to the auto-generated feature ids as a reference. 

**QField version:** 
QField version: 1.3.0 - Ben Nevis (10300995)

**Comment by signedav** [comment]
Do you create an offline project or use an online connection to Postgres from QField?

The behavior is like that, that the parent is stored on clicking the add-button on a child to be able to create the childs. When then the entering of the new parent is canceled (instead of stored) it's deleted again including his childs.

**Comment by Jean-Zombie** [comment]
I have an offline project.

> … the parent is stored on clicking the add-button on a child…

That is exactly when I get the error message. So it seems the parent doesn't get stored on my end while in editing mode for a new feature. 

My relation works in general though. Editing an **existing** feature and adding childs works like a charm.

**Comment by m-kuhn** [comment]
> My question: Is an extra id field with a default uuid value the only way to make n-to-m work in QField?

It's not the only way (database side default values are another one), but uuids are the generally recommended way. See also https://qfield.org/docs/project-management/vector-layers.html#field-widget
