### ISSUE TITLE
QGIS 3.4.13 Creating _packed shapefiles and fails to save edits correctly

### ISSUE THREAD

**Issue by malinbaru** [opengisch/QField#741]
Dear all! The issue I have with the QGIS 3.4.13 is, that every other now an then while editing a shapefile in the savingprocess attributes are missing or got mixed up. The program shows an error about "saving the editing failed" and that the"layer got repacked". After that, I get two different shapes from one layer, none of them are correct. Sometimes just the lable-features are mixed up, other times, as I said, everything I edited is missing. Does someone has a clue about how to fix this? The error happens to appear at different PCs/Macs.

**Comment by m-kuhn** [comment]
This is the [QField](https://qfield.org) issue tracker.
Please open an issue at https://github.com/qgis/QGIS/issues
