### ISSUE TITLE
New camera - custom picture path(s) and names?

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#743]
Hello,
as discussed here https://github.com/opengisch/QField/pull/258 I wanted to raise the question at the end of the thread: "Is there a feature that allows one to name the picture files from a station ID ?"

Is it planned/possible/expectable for the new camera implementation to

a) have different paths to store pictures? For example we have one picture folder in our project for sewer entrances/covers, one for the signs and another one for scanned documents regarding this sewer entrance. So would it be possible to define where i want to save the picture for the entrance or sign in the right folder?

b) give the picture a proper name (like "station name" + '_' + now() + '_' + 'sign.jpeg' )

If asking two questions in one thread is not helpful, i will split it into a new issue!

Thanks in advance and keep up the good work!

**Comment by signedav** [comment]
Thanks for asking. What is currently on the roadmap and what would be new enhancement requests @marioba ?

**Comment by marioba** [comment]
Point b) should be possible when the planned development of the native camera is completed. It is not yet exactly defined, but it will probably be possible to define a (virtual) field to be used as a name for the images.

Point a) is not currently planned.

**Comment by signedav** [comment]
Thanks @marioba

**Comment by signedav** [comment]
Opened an enhancement request here #744

This issue we probably can close after the new camera is released.

**Comment by signedav** [comment]
Or since the question is replied I close it already.
