### ISSUE TITLE
Define name pattern of pictures

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#744]
Give the picture a proper name (like "station name" + '' + now() + '' + 'sign.jpeg' )

(Excluded from this issue  #743 )

**Comment by signedav** [comment]
@meyerlor please specify if needed.

**Comment by meyerlor** [comment]
thank you for making this "official" :)

a free adjustable picture-name string would be really appreciated, a combination of field + string + expressions would be an absolute bummer!

**Comment by m-kuhn** [comment]
@signedav is this solved?

**Comment by signedav** [comment]
QFieldSync PR is not yet merged and released.

**Comment by m-kuhn** [comment]
@signedav is this solved?

**Comment by signedav** [comment]
Yes
