### ISSUE TITLE
Switching GeoPackage to "offline editable" makes it disapear

### ISSUE THREAD

**Issue by meyerlor** [opengisch/QField#746]
I have data stored in a geopackage (Multipolygon). When i sync it with the QGIS sync plugin, everything is fine on my tablet. When i switch it to offline editable in the sync plugin and copy the data to the tablet, the layer is not visible anymore.

I tried several things:

- Switching the layer off and on again in QField -> no change
- removing all widgets (including switch date fields to text fields) -> no change
- exported the gpkg layer in QGIS to .shp (ugh!) "solved" the issue, switching the .shp to offline editable seems to work (at least it is still rendered!). Problem is now with the column name length..

Interestingly, when i exported the gpkg to shp, OGR threw me an error that only 304 of 309 could be written into the shape as the other 5 features have a wrong geometry (POINT) and the .shp is of type POLYGON. So i assume, QField has problems with multitype gpkg? is this already known?

I gladly provide the gpkg via mail if needed, it contains some data of our customer so i would rather not post it here! :)

**Comment by meyerlor** [comment]
ok, digging a little further into my data revealed that the 5 features are not points but of type "geometrycollection" which is not supported by QGIS - those 5 features are not rendered at all. so it is not really a QField issue. 

On the other hand, it is still strange why the 304 features are rendered but when switching to offline editing non of them are rendered -  anyway, i guess this issue is quite low in the Qfield priority list :)

**Comment by m-kuhn** [comment]
Thanks for the feedback and investigation.
This is most likely an upstream issue in QGIS (where offline editing lives), so it would be nice if you could open an issue there.

Priorities are defined by our users and what's important enough for them to work on (or make us work on), so it's really up to you, if you want to fix this issue, make us fix this issue or hope that someone might someday fix this issue :)

Closing this as upstream.
