### ISSUE TITLE
Attribute Data don't show

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#75]
I have 2 point-layers. When clicking on one (named "pont") attributes show up in the form that opens. When klicking on the other (named "camerapositions") the form doesn't show any content. To me this behaviour is not explainable.

### Reproduction Steps:

1. Use offline-editing plugin to transfer postgis layers "points" and "camerapositions" into one sqlite-file called "offline"
2. Copy everything to QField. Everything displays well in QGIS
3. Click on a point from the "points"-layer. The attribute table with the attributes apperas
4. Click on a point from the "camerapositions"-layer. The opening form shows no content. It does not recognize that I clicked on a point. So the behaviour is like when klicking far away from ony data point.

### Expected behavior:

I expect the form to show the attributes of the data point I clicked on.

### Observed behavior:

Form opens but appears to be empty, not recognizing that there are data points.

**QField version:** [0.8.2]

## Additional information:

[Standorterfassung_withoutmap.zip](https://github.com/opengisch/QField/files/482898/Standorterfassung_withoutmap.zip)

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No]

**Comment by m-kuhn** [comment]
An error concerning identification of points on reprojected layers has been fixed in 0.8.4. I assume it was the issue triggering this error.

Please reopen this issue if the problem persists in 0.8.4
