### ISSUE TITLE
Multiline attribute fields

### ISSUE THREAD

**Issue by geomoes** [opengisch/QField#755]
Well done to move the attribute field display to the bottom of the screen in the new version 1.3.4 - Ben Nevis version.
Still it isn't possible to view, add or edit attributes-text, that surpasses the width of the screen. As we use sometimes longer descriptions in text fields, we would be happy to have the entire text to be displayed in multiple lines.

**Comment by m-kuhn** [comment]
Did you configure your text edit field as multiline?

**Comment by geomoes** [comment]
OK, I didn't realize that it was so simple.
