### ISSUE TITLE
Failure to scale combo box item touch area

### ISSUE THREAD

**Issue by ivankautter** [opengisch/QField#779]
As of version 1.3.0, the combo box item area on an attribute form does not seem to scale correctly. For XHDPI or higher density displays, the tappable area for each item has shrunk such that it is now difficult to tap the desired item.  Tested on a Pixel 2 (5 inch 1080p display, 441 dpi) and Samsung Galaxy Tab 8.4 (8.4 inch 2560 X 1600, 359 dpi).  On both devices, the space around combo box item text is sufficiently small to make interacting with the control difficult or inaccurate.

This behavior does not occur in version 1.2.0.

### Screenshots
Version 1.2.0
![Screenshot_20200109-133944](https://user-images.githubusercontent.com/17435854/72107461-3ddd4680-32e6-11ea-9aaa-e6ed166615b5.png)

Version 1.3.4
![Screenshot_20200107-110901](https://user-images.githubusercontent.com/17435854/72107424-24d49580-32e6-11ea-8a5e-78e37a3ecc4b.png)

### Reproduction Steps:

1. Run QField version 1.3.0 or later on at least XHDPI device
2. Open project with editable layer including custom drag and drop UI form
3. Beginning editing editable layer and create new point feature in this case
4. Interact with combo box for data entry in any field specified to use that input control

### Expected behavior:

Combo box item area should scale to a size to meet a basic usability requirement for touch interaction since the size of the touch object area appears dependent upon the density of the device display.

### Observed behavior:

As of version 1.3.0, combo box item spaces appears significantly smaller than it used to be on XHDPI devices or higher.  Since the space around combo box items appears to scale down on higher density displays, accurate touches to select an item has become difficult and error prone.

**QField version:** 1.3.0 or later

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
Thanks @ivankautter 

I think it's not an issue with scale. I think this is made on purpose to have tighter lists and a better overview. But I see your point.

@nirvn What do you think about it?

**Comment by nirvn** [comment]
It'd be nice to have an height for line edit and combo boxes that match. In 1.2, the height was likely too big, and in 1.3, it's too small. 

I'd be +1 on consistency across the line edit / combo box widgets.

**Comment by ivankautter** [comment]
Just to contextualize the scale issue, here are two screenshots of two difference devices running similar versions of QField.  The red rectangles have an approximate height of 48 dp which is an Android spec for touch target sizes.  As you can see, the lower density display has what one might consider an appropriately large area for touch interactions, whereas the Pixel 2 at 441 ppi appears not to.  Lowering the display resolution on the higher ppi device can make the presumed touch target larger, but essentially at the expense of the amount of information displayed on the form.

Not trying to harp on the issue. I appreciate all your efforts, but the scale of the UI elements is directly related to the device's ppi.  So, hopefully whatever enhancement may be coming down the line could attempt to capture the device's ppi and scale the UI to some set standard.

Pixel 2, 5 inch screen, 441 dpi (Version 010401992)
![Pixel_2_Screenshot_20200204-103959](https://user-images.githubusercontent.com/17435854/73778137-88b07980-473f-11ea-98c7-417e0ba36150.png)

Samsung Tab Active2, 8 inch screen, 189 ppi (Version 01041990)
![Active_Tab2_Screenshot_20200204-104440_QField](https://user-images.githubusercontent.com/17435854/73778334-e47b0280-473f-11ea-8b50-77e72c637069.jpg)

**Comment by nirvn** [comment]
This has been fixed when we said goodbye to QtQuick 1.
