### ISSUE TITLE
Does not respect layer visibility

### ISSUE THREAD

**Issue by andrerjesus** [opengisch/QField#78]
I'm not sure if this is bug or expected behavior, but It didn't happen in versions previous 0.8.x

QGIS project with two layer (lyr1 and lyr2), lyr1 has visibility ticked, lyr2 doesn't. 
When open the project in Qfield (0.8.5) both layers are displayed, what was expected is to only show lyr1.

Scale dependent visibility works fine

**Comment by m-kuhn** [comment]
Thank you for the report. This will be fixed in the next release.
