### ISSUE TITLE
GPS direction is not working

### ISSUE THREAD

**Issue by ivankautter** [opengisch/QField#782]
Upon installing new version 1.4.0 from apk available here, I tested the GPS direction functionality on a Pixel 2 running Android 10 and a Samsung Galaxy Tab Active2 running Android 9. In both cases, the cone graphic indicating the direction always faces straight up (in most cases presumed North). Rotating the device produces no change in the heading.  Walking around a square city block produces no change in heading. I confirmed that the implementation in Google Maps is functioning correctly and did compass calibrations on each device.  In addition, I tested the dev apk version associated with PR #757 just in case this functionality somehow didn't make it into the 1.4.0 release.  GPS direction also did not function as intended in that version. 

### Reproduction Steps:

1. Install Version 1.4.0 from apk over existing 1.3.4 version or install independent version from dev apk
2. Open any project and activate GPS positioning services
3. Once a fix has been obtained, change orientation of device by rotating or walking differing headings for at least a city block

### Expected behavior:

Direction indicator graphic should point towards my GPS heading

### Observed behavior:

Direction indicator always points straight up

**QField version:** 1.4.0

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@ivankautter , thanks for the report. PR #786 fixes this issue.
