### ISSUE TITLE
Project files which are in some folders are not listed in the browser

### ISSUE THREAD

**Issue by pcav** [opengisch/QField#79]
If I copy the files on a folder seen as `SDcard/Android/data/ch.opengis.qfield/files/share/` (do not know the actual path on the filesystem, there seems to be some remapping), I cannot find it from QFiedl.
If I copy it to a subdir in `/storage/emulated/0/` they are found correctly.
IMHO it would be good to have a fixed, understandable default dir, not to mess up too much with a system that is not too transparent to the users.

**QField version:** 0.8.5 and previous

**Comment by 3nids** [comment]
should be fixed
