### ISSUE TITLE
Add 1:n pictures to advanced bee demo project

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField#799]
we should enhance the demo project to show that there is already a way to support multiple pictures linked to a feature

**Comment by filleg** [comment]
I would really appreciate an explanation on how to accomplish this 👍

**Comment by mbernasocchi** [comment]
# Tables
Create 2 tables:
## hive (Sprengungen in the screenshots)
- id (UUID)
- geometry
- ...
## hive_picture (sprengung_bild in the screenshots)
- id
- hive_id (UUID)
- path (TEXT)
- ...

# Relations
create a relation with:
- `hive` Referenced layer
- `id` Referenced field
- `hive_picture` Referencing layer
- `hive_id` Referencing field 

![image](https://user-images.githubusercontent.com/233663/76217441-b68f4f00-6212-11ea-9eaa-170bc1fe9791.png)


# Widgets
## hive
set default value of id to `uuid()`. No need to show it in the form.
![image](https://user-images.githubusercontent.com/233663/76216540-0ff67e80-6211-11ea-982c-0b3121d30742.png)
Set the relation widget to `Many to one relation`
![image](https://user-images.githubusercontent.com/233663/76217026-ef7af400-6211-11ea-97d9-eb0344d844f2.png)

## picture
set  widget type of path to `attachment`
![image](https://user-images.githubusercontent.com/233663/76216384-cdcd3d00-6210-11ea-96f8-c5a90c6d9bae.png)

Done

**Comment by mbernasocchi** [comment]
@lucienicolier this could be added to the QField documentation

**Comment by rjwillson** [comment]
thanks a lot Marco for providing that answer with screen clips as I was able to get the relationships set up and can now collect multiple photos per feature with QField. Wouldn't have been able to figure it out without the screen clips.

**Comment by marioba** [comment]
Since it's answered and already part of the documentation, I close the issue.
