### ISSUE TITLE
QField 0.8.5 crashes after 3-5 minutes of use on Nexus 5

### ISSUE THREAD

**Issue by mmarius2** [opengisch/QField#80]
QField 0.8.5 crashes after 3-5 minutes of use on Nexus 5

### Reproduction Steps:

1. I start Qfield. I open a qgis project. Starts OK.
2. panning, zooming (in/out).

### Expected behavior:
normal use with a qgis (version 2.16.2) project

### Observed behavior:

 After 3-5 minutes of use, the application crashes/disappears without error message.

### Screenshots and GIFs

none.

**QField version:** 0.8.5

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes (since 0.8.0). In 0.7.5 (Gonnus Mons) I have not encountered crashes.
* Problem can be reliably reproduced, doesn't happen randomly: Yes, every time after 3-5 minutes of use.
* Problem happens with all files and projects, not only some files or projects: Yes, with different projects/files. The problem occurs both on the Nexus 5 (Android 6.0.1) and Nexus 7 (Android 4.4.4).

**Comment by mmarius2** [comment]
with adb logcat, I obtained the following file:
[errorlog_qfield.txt](https://github.com/opengisch/QField/files/514227/errorlog_qfield.txt)

**Comment by m-kuhn** [comment]
We just received information about a memory leak in this version, caused by the new rendering engine. That very well explains this behavior.

**Comment by mmarius2** [comment]
OK. Thanks for your response. 
I suspected that the problem is related to the rendering engine.

**Comment by m-kuhn** [comment]
A memory leak has been fixed in version 0.8.6.
https://github.com/opengisch/QField/releases/tag/release-0.8.6

Any feedback from testing results from this release (for download as apk on the above link) would be much appreciated.

**Comment by mmarius2** [comment]
Thank you very much.
Now, the usage is flawless, without a single glitch.

**Comment by m-kuhn** [comment]
Thanks for the feedback.
@mbernasocchi, could you upload this version to the playstore?

On October 9, 2016 12:47:28 PM GMT+02:00, mmarius2 <notifications@github.com> wrote:
>Thank you very much.
>Now, the usage is flawless, without a single glitch.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/opengisch/QField/issues/80#issuecomment-252479187

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mbernasocchi** [comment]
done
