### ISSUE TITLE
Offer a way to automatically load the last opened project when re-launching QField

### ISSUE THREAD

**Issue by ElvisDahnert** [opengisch/QField#800]
The welcome page  (#761) looks great! Whoever starts at QField has a lot of questions about how to enjoy the app and the demos help a lot.
But I want to suggest an improvement.
There are users, in my case, who use QField always with the same projects, so if the user only uses one project, it is not necessary to display the welcome page for him whenever he starts QField. We are used to starting the last session directly.
I suggest a counter, for example, if the user uses the same project 5 times, the welcome page stops showing until he changes projects.
Available for clarification.
Thank you!

**Comment by signedav** [comment]
Hm... good input.
But instead of a counter I would prefer a setting option. 

Are there opinions? @m-kuhn @mbernasocchi @nirvn

**Comment by nirvn** [comment]
+1 to adding a load last project upon launch setting, defaulting to false.

**Comment by mbernasocchi** [comment]
I agree with @nirvn, no surprising magic, but we could add that setting.

**Comment by nirvn** [comment]
@ElvisDahnert , implemented in latest QField, enjoy!
