### ISSUE TITLE
Delete WAL files

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#804]
There are no issues anymore with data loss on synchronization.
But the WAL files still persist sometimes. This is not only confusing but can lead to problems with other programs.

Maybe we could drop the files after the flush or something?

<img width="1440" alt="walissue" src="https://user-images.githubusercontent.com/28384354/74170795-c294ea80-4c2d-11ea-9691-d72268b979ea.png">

**Customer says:**
Bezüglich des Problems mit dem wal files beim Einlesen der Daten in R. Ich kann das Problem nicht richtig reproduzieren und eingrenzen. Ich habe mal die Fehlermeldung unten einkopiert. Gestern lief das Skript einwandfrei und heute gibt es einen Fehler obwohl ich die Daten seitdem eigentlich nicht angefasst habe. Wenn ich die .gpkg Datei in der Cloudablage von meinem Desktop aus öffne und wieder schließe wird die wal Datei gelöscht und das Einlesen funktioniert. Allerdings wird sie ja regelmäßig von den Tabletts auch wieder in die Ablage gepusht falls das Projekt auf dem Tablett noch geöffnet ist. Der Import kann aber auch klappen, wenn die wal Datei in der Ablage liegt und letztes Jahr hatte ich dieses Problem nie, deshalb bin ich gerade überfragt.

**Comment by signedav** [comment]
@m-kuhn what do you think?

**Comment by m-kuhn** [comment]
I don't think the files can be dropped because they are not "ours". They are created by ogr/the sqlite driver even if a file is opened readonly. We can ask ogr/the sqlite driver to not create wal files by changing the delete mode - which we did in the past which introduced other problems.

The only thing we can do on our end is to make sure we unload the layer properly on application exit. We could also do that in other scenarios (e.g. 5 seconds no map interaction), but 1. this could be complicated and require lowlevel ogr provider changes in QGIS and 2. will come at an additional cost of opening the file again on next usage resulting in decreased performance.

I wonder if the code in RStudio can be changed to work around the current behavior. Does the error also happen if the file is opened in R/W mode in R? Or even just opened and closed in R/W mode once before it's loaded?

**Comment by Kanoet** [comment]
I tried to narrow the problem. In case the .gpkg file is in read only mode in the QField project and the created wal file is completly empty (0 Byte) no problems occur when importing the data into R. When I switch the .gpkg file to editing mode I get the error message. When I close editing mode and / or the whole project it works fine again. 

However, in my case the problem will be that with more than two dozen devices and even more unexperienced users there is always a high chance that some projects may not be properly closed and the wal files will then cause trouble in the automatized data treatment. 

I have posted the issue in the sf package section and maybe there is a workaround in R. 

https://github.com/r-spatial/sf/issues/1262

**Comment by Kanoet** [comment]
I tried two workarounds. 

1. open all .gpkg layers within a QGIS project and close again. That removes the shm and wal files from the directory and importing in R works without problems. 

2. delete all shm and wal files within the R script before importing the .gpkg file. Deleting works but some .gpkg file then cannot be imported anymore and need to be "fixed" by opening and closing them in QGIS.

Code for removing the files from the directory: 
```
file.remove(paste(file_path_name, ".gpkg-shm", sep=""))   
file.remove(paste(file_path_name ".gpkg-wal", sep=""))
```

**Comment by m-kuhn** [comment]
@Kanoet I noticed the sf issue was closed. Is there a GDAL/OGR related R issue tracker where you could ask the same question.

If it's possible that QGIS fixes it by using GDAL, it should also be possible to make R fix it by using GDAL.

**Comment by m-kuhn** [comment]
I'll close this issue in order to find solutions for problems.

Always removing the WAL files is not possible in the current state of sqlite/gpkg/ogr. As soon as a gpkg is opened (even read only) a WAL file is created. When the last accessing process exits it's deleted again. If users copy away files without exiting QField, the wal file is there. And there is not much we can do about it (unless we dig deeeep).

As @Kanoet mentioned, the files can be opened in QGIS also when the WAL file is present. Or was present and not copied along.

In the worst case, most corrupted sqlite files can be rescued with the following command (even though beware that this is not something required because of wal files and only happens if many things go south)

```
sqlite3 file.gpkg ".dump" | sqlite3 file_restored.gpkg
```

**Comment by gioman** [comment]
> When the last accessing process exits it's deleted again. If users copy away files without exiting QField, the wal file is there. And there is not much we can do about it (unless we dig deeeep).

@m-kuhn @signedav I'm using the latest version of QField on a Android 10 mobile, and I see that the WAL and SHM files are never removed, not even if exiting editing mode and exiting correctly Qfield (and not even if stopping Qfield altogether). Is this expected?

**Comment by m-kuhn** [comment]
@gioman I think it should be removed if you properly exit (hitting back twice) but didn't test in a while.
However, it is flushed almost immediately after every edit, so there shouldn't be any leftovers in the wal

**Comment by gioman** [comment]
>  However, it is flushed almost immediately after every edit, so there shouldn't be any leftovers in the wal

@m-kuhn that is correct, there are no leftovers in the WAL.



> I think it should be removed if you properly exit (hitting back twice) but didn't test in a while.

they are not removed, not when properly exiting or (afterwards) stopping QField. Just wanted to to know if we must assume that this is the expected outcome or if those files should be really removed.

**Comment by suricactus** [comment]
AFAIK QField has never purposely removed the wal and shm files, but it is possible that it was a side effect. I also confirm the buffer has been flushed.

**Comment by m-kuhn** [comment]
wal and shm files should be removed when the layer (with the gdal data provider) is unloaded. On desktop (linux build) this is working as expected here.

**Comment by gioman** [comment]
> @gioman I think it should be removed if you properly exit (hitting back twice) but didn't test in a while.
> However, it is flushed almost immediately after every edit, so there shouldn't be any leftovers in the wal

@m-kuhn sorry for commenting again in this ticket that is long closed. I'm using QField 2.0.8 and what I see is that *.gpkg-shm
*.gpkg-wal are never removed when exiting the application the right way (hitting back twice). Also the *.gpkg-wal has only size 0 when it is created the first time the gpkg is opened, afterwards it never returns to 0 size and it grows is size along with editing operations.

Also side question: there is a way to avoid a GPKG file that was opened but **not** edited to change on disk? This is what happens with both QGIS and QField and is really a pain when using sync platforms like nextcloud.

**Comment by m-kuhn** [comment]
I don't know why they are not removed but they are always flushed immediately.

There is a gdal env var to make sure it doesn't use wal, i think that should avoid the edit on read.

**Comment by gioman** [comment]
> There is a gdal env var to make sure it doesn't use wal, i think that should avoid the edit on read.

@m-kuhn I remember that now you say it. I tried once on QGIS, setting it from the python console. Does it remains set at a project level (so it works also on QField)? or must be set separately on QField too?

**Comment by m-kuhn** [comment]
I think in qgis you have to set it before you start or in the app settings. Not sure it works from the console.
On Qfield i am not aware of any way to set it.

**Comment by gioman** [comment]
> Not sure it works from the console

This:

`QSettings().setValue("/qgis/walForSqlite3", False)`

It works as wal is not created and most of the times the gpkg is not modified, still at times it still change (not sure what), if just the date/time or else).

> I don't know why they are not removed but they are always flushed immediately.

So it doesn't matter that the wal file is not zero size after closing Qfield (when is not removed, which for me now is always)?

**Comment by m-kuhn** [comment]
> > Not sure it works from the console
> 
> This:
> 
> `QSettings().setValue("/qgis/walForSqlite3", False)`
> 
> It works as wal is not created and most of the times the gpkg is not modified, still at times it still change (not sure what), if just the date/time or else).
> 

That looks good

> > I don't know why they are not removed but they are always flushed immediately.
> 
> So it doesn't matter that the wal file is not zero size after closing Qfield (when is not removed, which for me now is always)?

I am not familiar enough with the format to comment on what could be inside. There might be other information than new data.
All I can say is that shortly after each edit it is flushed and since this is done we haven't heard of issues with lost data.
