### ISSUE TITLE
Qfield crash on using drag and drop form 

### ISSUE THREAD

**Issue by varrieta** [opengisch/QField#81]
Qfield happen to crash when using drag and drop designer to organise the fields.  
### Reproduction Steps:
1. Select a point
2. Start the edition mode
3. Edit fields in a tab
4. Change the tab
### Expected behavior:

Change the tab so we can continue to edit the fields
### Observed behavior:

Qfield crashes (not always, but most of the time)

**QField version:** 0.8.2
## Additional information:
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by m-kuhn** [comment]
Is this still an issue with 0.9.0?

**Comment by m-kuhn** [comment]
This appears to be fixed.
Please reopen (with a demo project) if this happens again.
