### ISSUE TITLE
issue with new camera feature

### ISSUE THREAD

**Issue by vlebert** [opengisch/QField#812]
Set a "file field" in a project 
In Qfield use the button to choose a local file. Press cancel (android back arrow) many time to quit.
Instead of null the field take value 'DCIM/'

### Reproduction Steps:

1. Create a project with a "file" field
2. Edit the layer in Qfield, add a feature
3. Choose the button to browse for a file then press cancel to exit the menu

### Expected behavior:
Field value being NULL

### Observed behavior:
Field value is 'DCIM/'

1.4.2
 7768204

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by signedav** [comment]
It's especially dangerous because an existing value get's overwritten on cancel.
