### ISSUE TITLE
Warning: Could not open CRS database

### ISSUE THREAD

**Issue by dariogambino** [opengisch/QField#84]
[Short description of problem here]
### Reproduction Steps:
1. installed application
2. select a qgis project from the menu
### Expected behavior:

See the project
### Observed behavior:

got error
CRS

could not open CRS database
/data/user/0/ch.opengis.qfield/files/.qgis3//qgis.db

infact the above mentioned is not present in the TABLET
## Additional information:
- Problem started happening recently, didn't happen in an older version of QField: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]
- Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by m-kuhn** [comment]
Thanks for the report.

Where do you get the error? Is it a popup window or in the message log with the icon on the top right of the map canvas?
Am I understanding it correctly, that it only happens after opening a project?

**Comment by m-kuhn** [comment]
Note to self: The file is located in

    /data/user/0/ch.opengis.qfield/files/share/resources/qgis.db

**Comment by m-kuhn** [comment]
@dariogambino can you verify if the abovementioned file exists.

Are you using a custom CRS in your project? I'm not sure in which case the user database is accessed, normally the system db is good enough I think.

**Comment by dariogambino** [comment]
I made a video
https://www.dropbox.com/s/vvxtuigtpqhq7ba/20161026_171732.mp4?dl=0

Il 26 Ott 2016 17:01, "Matthias Kuhn" <notifications@github.com> ha scritto:

**Comment by m-kuhn** [comment]
Are you able to share the project?

**Comment by m-kuhn** [comment]
I have recently seen this on also on a tablet. However, **the project could still be opened**.
It is likely that the two things are unrelated and the project can not be opened for another reason (check http://www.qfield.org/docs/project-management/portable-project.html)

**Comment by dariogambino** [comment]
Ok I will check it later

Il 08 Nov 2016 15:26, "Matthias Kuhn" <notifications@github.com> ha scritto:

**Comment by dariogambino** [comment]
I can confirm the problem is solved.

But when I create a new item in the shp (example "fabbricati") I can see 
it on Qfield but un QGIS it says the shp is corrupted.

Is there a reason ? In attachment my project


Il 08/11/2016 15:13, Matthias Kuhn ha scritto:
