### ISSUE TITLE
New Global variables cannot be saved

### ISSUE THREAD

**Issue by RatInTheField** [opengisch/QField#856]
[Short description of problem here]
Existing global variables from previous versions of Qfield continue to work, but when new global variables are added, they can be viewed in Settings for the rest of the session, but disappear when Qfield is closed. Also, expressions that rely on them and that worked correctly in earlier versions of Qfield no longer work.

### Reproduction Steps:

1. [First Step]
Navigate to Settings>Global Variables
2. [Second Step]
Naviagate to the new record
3. [Other Steps...]
Add a new variable name and value "Operator_name","RatLen"
Click Tick
[AshwayGap.zip](https://github.com/opengisch/QField/files/4250199/AshwayGap.zip)

### Expected behavior:
New global variable is added permenantly and remains available after closing and reopening Qfield
New global variable is available to expressions allowing functionality that mirrors QGIS

[Describe expected behavior here]

### Observed behavior:

[Describe observed behavior here]
New global variables remain ONLY for the current session dying when Qfield is closed
New global variables are not available for expressions to use.

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]
1.4.4 - Olavtoppen (code:010404992)
1.3.4 - Ben Nevis (10304995)
Issue has been seen in the Above versions of Qfield

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No] Yes
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by RatInTheField** [comment]
Further investigation suggests that this functionality was working correctly in 1.2.0, Matterhorn, but did not work in 1.3.0, Ben Nevis

**Comment by m-kuhn** [comment]
Is it possible that if you use the back key (device) instead of the button (app) it works?

**Comment by RatInTheField** [comment]
Back key on the device works, but tick does not., When the Global variable is created and saved using Back Key, the expressions work as expected.

**Comment by m-kuhn** [comment]
@RatInTheField thanks for the feedback.
Can you install the apk from https://github.com/opengisch/QField/pull/862 (probably arm64_v8a) and check if this fixes the issue?
Thanks in advance.

**Comment by RatInTheField** [comment]
[Qfield#856.docx](https://github.com/opengisch/QField/files/4279896/Qfield.856.docx)
Attached file contains test results for .apk in #862 (https://download.opengis.ch/qfield/ci-builds/qfield-dev-862-eadc49888ec77688537ed312758e3031ddc2b190-arm64_v8a.apk).
Tests are all SUCCESSFUL.
Thanks!

**Comment by m-kuhn** [comment]
Thanks for the tests @RatInTheField 
This will be fixed in the next release (1.5 - or 1.4.5 if there is one)
