### ISSUE TITLE
Improve selection by setting a search radius for identifying features

### ISSUE THREAD

**Issue by GisUsers** [opengisch/QField#858]
If multiple features are adjacent, a single touch will identify several of them.
A way to control this behaviour would be extremely useful.

The current behaviour offers no control and makes feature identification imprecise.
If several adjacent polygons are present in the layer, a single touch will identify all of them.
After that, the desired polygon must be selected from the list.
It would be effective to allow the user to decide the precision/tolerance of the touch interface.
QGIS has an option to set the search radius for identifying features and I think a similar option would greatly increase QField usability.
Alternatively, an option to force the identification of a single feature upon touch would be effective.

I often suggest Qfield to my clients as an effective solution to leverage geospatial data in field operations.
The current behaviour is not perceived as a feature but rather as the interface being imprecise (even with a stylus) and the feature identification process more complex than it needs to be.

If such a functionality already exists it is inadequately documented.

**Comment by signedav** [comment]
I think, the radius set in the QGIS Project Map Setting affect QField as well. No?

**Comment by GisUsers** [comment]
The option I am aware of is "Search radius for identifying features and displaying map tips" located under QGIS Settings>Options>MapTools
As such, it should be a global setting rather than a project setting.
Two quick tests:
1. changing the setting and then loading a different project does not change the setting back;
2. changing the radius in the setting and creating a new project for Qfield does not modify Qfield behaviour.

If you are referring to a different setting please explain in detail and I will be glad to test.

**Comment by signedav** [comment]
Ok, then I think this would be something that will make sense to integrate. Thanks for reporting @GisUsers

**Comment by m-kuhn** [comment]
Can you check #1142 ? It lowers the hardcoded value for the radius.
I would prefer to avoid an option and find a suitable default value that works for all.
