### ISSUE TITLE
Add visibility checkbox to the layers list

### ISSUE THREAD

**Issue by GisUsers** [opengisch/QField#859]
With the current interface, the way to show or hide a layer in the canvas is not intuitive, especially for new or casual users.
When they open the layers list, there is no visual cue.
Moreover, the long press to access the visibility chekbox is not user friendly, as it requires two actions when only one is needed.
A simple visibility checkbox in the layers list would be straightforward, self-explanatory and much faster.
![qfield_eye](https://user-images.githubusercontent.com/61540606/75438997-46064980-5959-11ea-94a3-65f78cc3cb6d.jpg)

**Comment by nirvn** [comment]
@GisUsers , good news, this has been implemented as of QField 3.3. Happy field mapping!
