### ISSUE TITLE
Project loads but keeps zooming out when touchscreen used

### ISSUE THREAD

**Issue by casswelly** [opengisch/QField#86]
Project loads fine but as soon as you use the touchscreen it zooms out and keeps going. Unable to use.
Current version 0.8.8. Worked well on previous version before update this morning. Using Sony Z2 compact phone and lenovo tab 2 a10-30.
Problem encountered on multiple projects and devices.

**Comment by m-kuhn** [comment]
Can you verify with the 0.9.0 again?

**Comment by casswelly** [comment]
Have verified 0.9.0 on both devices (although now I'm using a Z5 compact phone) and problem still persists.

**Comment by m-kuhn** [comment]
Really strange, I haven't seen this happen nowhere and I cannot think of anything that could have triggered this...

**Comment by m-kuhn** [comment]
Finally got a lead on this, map rotation is responsible. Reset map rotation to 0 to fix the project.

The next release will do this automatically and issue a warning if map rotation is enabled.
