### ISSUE TITLE
Constraint across many fields not updated on changes in other fields

### ISSUE THREAD

**Issue by saemiw** [opengisch/QField#87]
### Observed behavior:
Example: I have 3 fields (e.g. f1, f2, f3) and define for field 3 a constrain like this in QGIS ("f1"+"f2"+"f3")=100 in order to check if the 3 fields sum up to 100%. If entering a new feature in QGIS Desktop the constraint is checked (as expected) as soon as I type in a number in any one of the 3 fields. On QField on the other hand, the constraint is only checked if I type in a number in field 3.

### Expected behavior:

The constraint should continously be validated (upon every touch on the screen).

**QField version:** [0.8.8]

## Additional information:

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Comment by saemiw** [comment]
2 videos illustrating the above explained:

Constraints across many fields not updated satisfactory on QField 0.10.1: 
https://youtu.be/2odN7VPwhFE

Constraints across many fields not updated satisfactory on QGIS 2.18.13: 
https://youtu.be/atLOqJNIPh4

**Comment by m-kuhn** [comment]
> When implementing this, can you make sure that it also works when the layers are set to offline-editing (i.e. go through the qfieldsync plugin).

Are you currently experiencing extra troubles with constraints in combination with offline editing? If yes, can you provide more information?

**Comment by saemiw** [comment]
No at the moment I don't  experience extra problems (used to be a problem in early versions). Just a reminder (also to myself) to check this once its implemented.

**Comment by signedav** [comment]
Fixed in Version 0.10.5 (in Playstore for Beta-Testers or [here](https://github.com/opengisch/QField/releases/tag/release-0.10.8_5))

**Comment by saemiw** [comment]
I can confirm that this is fixed and works nicely unter 0.10.11. Thanks.
