### ISSUE TITLE
Main app translation

### ISSUE THREAD

**Issue by ElvisDahnert** [opengisch/QField#871]
Some translations do not appear in the main app. In Transifex there are **113 strings blocked** for translation in all languages.

### Expected behavior:

100% translated app.

**QField version:** 1.4.4 - Olavtoppen (code: 010404991)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by signedav** [comment]
Thanks. Where do you see the blocked strings in Transifex?

**Comment by m-kuhn** [comment]
@ElvisDahnert are you able to provide the missing information?

**Comment by ElvisDahnert** [comment]
Excuse me, I was disconnected.
I visualize it [here](https://www.transifex.com/opengisch/qfield-for-qgis/language/pt_BR/).

![QField](https://user-images.githubusercontent.com/48390608/80557019-e275b800-89ab-11ea-8e40-2f92d73dce13.png)

I have now verified that in version 1.5.2 - Piz Palü (code: 010502992) there are some untranslated strings.

**Comment by m-kuhn** [comment]
There are no further releases of the series 1.5 planned. The locking of old series was done to avoid spending time on translations that will never ever end up in a release.

Is this ok @ElvisDahnert ?
