### ISSUE TITLE
fatal error: 'type_traits' file not found

### ISSUE THREAD

**Issue by dannyrs18** [opengisch/QField#872]
When building the project, it generates the file error not found.
The ndk that I initially used was r21 and r22, this presents a compatibility error with "tessellate". The error is not presented with r19c (which is listed in the requirements), but generates the error mentioned above with "type_traits"

```
/opt/Qt/5.14.1/android/include/QtCore/qglobal.h:45:12: fatal error: 'type_traits' file not found
#  include <type_traits>
           ^~~~~~~~~~~~~
```

**Comment by m-kuhn** [comment]
Hi @dannyrs18 is there something you would like to add to that?
It's unclear to me what should be done here.

**Comment by dannyrs18** [comment]
Thank you very much, I found the solution to the problem, I was following the guide and I did it wrong jeje
