### ISSUE TITLE
photoviewingproblem

### ISSUE THREAD

**Issue by okademirbilek** [opengisch/QField#874]
[photo viewing problem]

### Reproduction Steps:

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:

[we need to be able to view the picture which we take for point]

### Observed behavior:

[i see just a image logo under my photo label]

### Screenshots and GIFs
![Screenshot_2020-03-09-15-54-04](https://user-images.githubusercontent.com/48480726/76215277-7c787a00-621f-11ea-8d4b-2a5a90b5d8ca.png)

![https://cdn.discordapp.com/attachments/540927475870466059/686557536358367262/Screenshot_2020-03-09-15-54-04.png](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.4.4 (10200993)]

## Additional information:
my android version is 6.0.1 device : samsung galaxy s5 
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

**Comment by signedav** [comment]
This icon tells us that the image path is not pointing to an image.
Can you provide more information and tell the detailed behavior step by step?

**Comment by m-kuhn** [comment]
This is likely fixed. Please reopen if it is still an issue.
