### ISSUE TITLE
Qfield application 

### ISSUE THREAD

**Issue by mirankunda** [opengisch/QField#875]
I tried to open Qfield application in MobileMapper50_4G ( Android version is 5.1.1) but nothing happened in another words is not working try to resolve this issue but last year Qfield was working well . I reinstalled old app which was working well and I installed latest Qfield app which is not opened .

@JinIgarashi

**Comment by signedav** [comment]
Thanks for reporting. What QField Version you tried to install? And which one still works?

**Comment by mirankunda** [comment]
Qfield version which is not working is 1.4.4 updated on Feb 20,2020 for the
one which was working i uninstalled it so i don't know the version










        Best regards
*** Eng. Moise Irankunda****
*** BTech in surveying and geomatics Engineering****
***Department: Civil Environmental and Geomatic Engineering ** *

*** GIS Consultant at Esri Rwanda****


****(Sept 2015 Up to June 2016)***

***GIS Survey Officer at EDCL/REG****
*****( 01 July 2016 Up 4 October 2019)*****

****MIS Specialist at Water & Sanitation Corporation ****


*****( 07 October 2019 Up to date )**********
*Contacts:1. Phone:+250788209547****
*               2. Email:moiseirankunda@gmail.com
<Email%3Amoiseirankunda@gmail.com> ****

***Measurements is fundamental for Sustainable Development*****

**Comment by nirvn** [comment]
As per the documentation says here (https://qfield.org/docs/install/), QField now requires at minimum Android 6.
