### ISSUE TITLE
Crash with labels enabled

### ISSUE THREAD

**Issue by mhcpan** [opengisch/QField#88]
App crash when open a project with label enabled at one of layer with Huawei M3 tablet. No problem at all if using same project with One Plus 3 handset

### Reproduction Steps:

1. Create a project with Qgis (v2.18 or v2.99)
2. Copy to Android phone or tablet
3. Open the project from QField v0.8.8

### Expected behavior:

Display normally

### Observed behavior:

Crash with Hauwei M3 tablet

### Screenshots and GIFs

https://youtu.be/V1_aR1QZH-8

**QField version:** 0.8.8

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No, all version has same problem
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: No, seems only happen with Label enabled (I only enable on layer's label)
* Huawei M3 use Kirin 950 chipset, One Plus 3 use Qualcomm 820.
* Huawei M3 Android OS 6.0, One Plus 3 Android OS 6.0.1

**Comment by jpicheral** [comment]
I experiment the same bug on phone Huawey P9 lite with Android 6.0. 
Once I have remove the label, it is ok, thank you for the trick.

**Comment by m-kuhn** [comment]
Can you upload an affected project somewhere? Especially the labeling configuration will be interesting.

**Comment by jpicheral** [comment]
this is an example where the labeling configuration
[chataigniers_label.zip](https://github.com/opengisch/QField/files/683335/chataigniers_label.zip)

**Comment by mhcpan** [comment]
0.9.1 works without crash. Thanks for the update.

**Comment by Ushgorod** [comment]
I have same Problem with HUAWEI P9 Model vns-L31 (Kirin 650 - CPU) with Android 6.0
"Dissable ´Labeling" is helpfull Workaround

**Comment by hchristol** [comment]
Same problem with huawei tablet with Android 6. No problem on Samsung Galaxy Note 8

**Comment by mhcpan** [comment]
Hauwei M3 updated to Android 7.0 and problem solved,
