### ISSUE TITLE
QField -dev -v commit d11953d problem with switching tabs on features

### ISSUE THREAD

**Issue by hristo-mavrodiev** [opengisch/QField#883]
When the users try to create a new features, there is a problem with the switching of the tabs on the feature attributes. 

QField Unstable version -dev -v commit d11953d
### Reproduction Steps:

1. Open demo project "Live QField Users Survey Demo"
2. Switch to edit mode
3. Click on the + button and try to create a new "QField user"
4. On the "User" tab, enter something on "name" field
5.Try to switch to "Usage" tab

### Expected behavior:

Expected behavior:
Switch to "Usage" tab with text "Do you want to......"

### Observed behavior:
Still visualizing the "User" tab fields

### Screenshots and GIFs
The User tab
<img src="https://user-images.githubusercontent.com/61916767/76681399-06975880-65fb-11ea-88dc-dc3f44e9b0ec.png" width="40%" height="40%">  
After Clicking on Usage tab, still showing the user fields. After some clicking between tabs and discard/create a new feature it is switching sometimes
<img src="https://user-images.githubusercontent.com/61916767/76681405-0c8d3980-65fb-11ea-9156-1f79f1846710.png" width="40%" height="40%">

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]
Live QField Users Survey Demo

**QField version:** QField -dev -v commit d11953d (code:007312091)
Android 6.0.1
## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Not tested
* Problem can be reliably reproduced, doesn't happen randomly: No,it's randmonly
* Problem happens with all files and projects, not only some files or projects: Yes, Also on bee hive's demo project is reproduced

**Comment by signedav** [comment]
I cannot reproduce. Can you provide a project to test? Thanks.

**Comment by hristo-mavrodiev** [comment]
The default projects are in a hidden folder that I don't have access to. The folder /data/user/0/ch.opengis....... is not in my list when connected to my PC or with local file explorer.

**Comment by signedav** [comment]
Yes. Do you need them?

**Comment by hristo-mavrodiev** [comment]
No, I don't need them, I was going to upload a default sample project here as you requested. I don't have this issue on the stable version - 1.4.4 - Olavtoppen, only on the dev and it's very rare. I'm trying to create my own QGIS project with such tabs, but haven't achieved this yet.

**Comment by nirvn** [comment]
@hristo-mavrodiev , I suspect this is fixed, can you verify with qfield's latest version? Thanks

**Comment by hristo-mavrodiev** [comment]
Confirm, It's fixed.
