### ISSUE TITLE
QField -dev -v commit d11953d change of zooming function

### ISSUE THREAD

**Issue by hristo-mavrodiev** [opengisch/QField#886]
When the attribute table of a feature is opened and the user try to use the button for "zoom to"
 the feature, it will be good the feature to be centered only on the visible map area.
### Reproduction Steps:

1. Open "Simple Bee Farming Demo"
2. Click on a group of features
3. Use the button for "zoom to center"

### Expected behavior:
It's some kind of enhancement.
The feature to be zoomed on the visible area of the map.

### Observed behavior:
Currently it's zooming on the center of the phone screen area.

### Screenshots and GIFs
<img src="https://user-images.githubusercontent.com/61916767/76698848-07d68d00-66b0-11ea-88ec-dd15563de15f.png" width="40%" height="40%">
[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:**  
QField -dev -v commit d11953d (code:007312091)
Android 6.0.1
## Additional information:

* Problem started happening recently, didn't happen in an older version of QField:Not tested
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nirvn** [comment]
@hristo-mavrodiev , good news, that's been implemented in QField's latest version. Happy field mapping!
