### ISSUE TITLE
Layers disappearing from the project when exporting

### ISSUE THREAD

**Issue by pcav** [opengisch/QField#89]
if I choose a layer to be exported as offline (.sqlite), it remains in the project and in the canvas.
If it's of the type "copy" (so it remains as .shp), it disappears from the original source project.

**QField version:** 0.8.8
**QGIS version**: 2.18.1
**OS**: Debian sid
**Layer type**: shapefile

**Comment by m-kuhn** [comment]
The version of QFieldSync would be of the main interest, as far as I understand it's about this plugin?

**Comment by pcav** [comment]
Oh, right, sorry. Latest available, as usual: 0.9.1

**Comment by m-kuhn** [comment]
Thanks, moved to https://github.com/opengisch/qfieldsync/issues/28
