### ISSUE TITLE
Geometry Editor Toolbars Menu Button

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#891]
On the geometry editors like vertex tool, split tool or fill ring tool we have the left icon of the tool itself.
It's nice that we know what tool we are currently using but still I find it not intuitive, that we go back to the overview by pressing it. I would prefer to have there a close/back/toolmenu button.

![WhatsApp Image 2020-03-20 at 07 54 07](https://user-images.githubusercontent.com/28384354/77147031-ad14ab00-6a8c-11ea-8479-66e8d5ba0b8e.jpeg)

**Comment by 3nids** [comment]
do you have an example?

**Comment by signedav** [comment]
At the current master when you go to the geometry edit, the toolbar appears with: Vertex Tool Icon, Split Tool Icon. When you click the Vertex Tool Icon, the Buttons of the Vertex Tool appears, but the rightest button is still the Vertex Tool Icon (to return to the Geometry Editor Toolbar). I like it, that you know where you are, but I don't like that to return to the Geometry Editor Toolbar you have to click the Vertex Tool Icon (I would prefer to have a Return- or Menu-Icon here).

**Comment by signedav** [comment]
@3nids Maybe this scenario helps to follow:

1. My colleage used QField yesterday and splitted a feature
2. Today I'm on the field and I want to edit a feature - I go to the feature list and press "edit feature"-button
3. I see this:
![WhatsApp Image 2020-04-07 at 07 50 17 (1)](https://user-images.githubusercontent.com/28384354/78634766-f6defd00-78a4-11ea-9aa2-abc4192a341c.jpeg)
I am confused why I cannot control the vertexes? Because I'm in the snipping. Fair enough. But how can I get out of this mode? By pressing the scissors. Why I need to click on the scissors, when this is exactly the thing I don't want to do?

**Comment by 3nids** [comment]
well, that's a bit the idea you have in QGIS with the selection map tool. It has different modes and choose the mode.
Now, it's correct that you actually click on an arrow to change the mode.

Do you have any idea how to solve this?
ping @nirvn

**Comment by nirvn** [comment]
The current situation confused me a lot too.

I think the UI/UX could be greatly improved by, when starting the geometry editing, the toolbar shows available tools instead of jumping into the node editor. 

Then when we are in one tool, we use a (back) arrow as icon for the button that gets us back to available tools.

**Comment by 3nids** [comment]
> I think the UI/UX could be greatly improved by, when starting the geometry editing, the toolbar shows available tools instead of jumping into the node editor.

If you consider you are often reusing the same tool, it puts everything one click behind. If we display the message of which tool is being used and maybe go for a "…" icon to switch?

> we use a (back) arrow as icon for the button that gets us back to available tools.

wouldn't you expect it to work as an undo?

**Comment by signedav** [comment]
> wouldn't you expect it to work as an undo?
Maybe it's confusing since we have already a > symbol in the editor toolbar. But a symbol for "close" or coming "back to toolbox" would be nice. Maybe we can use the edit-geometry symbol...

**Comment by nirvn** [comment]
@3nids , I agree, a '...' icon to switch would be less confusing than a back arrow, and definitively better than using the current tool's icon.

To lower the confusion on first use (I was really, _really_ confused), what about trying to reach the best of both worlds: when someone _first_ get into the geometry edit mode, he/she sees the available tools. Once he/she clicks on a tool, it'll be remembered, and when he/she returns to geometry edit mode, that tool will be active.

**Comment by signedav** [comment]
> ... when someone first get into the geometry ...

You mean first since starting the app or first since using the app (should it be stored in the configuration or not). I think first since starting the app, would be a good idea.
