### ISSUE TITLE
Qfield 1.4.4 visualization style issue on splitted polygons

### ISSUE THREAD

**Issue by hristo-mavrodiev** [opengisch/QField#894]
After a splitting of a polygon the visualization of the splitted polygon looks as selected feature.

### Reproduction Steps:

1. Start edit mode
2. Create a new polygon
3. Split the polygon

### Expected behavior:

The splitted polygon to be visualized as normal.

### Observed behavior:
The polygon is visualized as selected. After restart of the application, the polygon is visualized as normal.
### Screenshots and GIFs

![image](https://user-images.githubusercontent.com/61916767/77229137-a2453d80-6b94-11ea-9290-337893760245.png)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:**  1.4.4 (010404991)]
Android 6.0.1
## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Not tested
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by 3nids** [comment]
this has been fixed in ec5bb653eacbb87b2465d139d6eb9ac4e7db4824

**Comment by hristo-mavrodiev** [comment]
The test from latest version, looks selected again.
![image](https://user-images.githubusercontent.com/61916767/77244697-e54cf280-6c20-11ea-89a6-f1040df4e053.png)

**Comment by signedav** [comment]
I guess it will be fixed with the upcoming Fill Ring implementation, right @3nids ?

**Comment by 3nids** [comment]
this has been fixed for 1.5
