### ISSUE TITLE
Qfield 1.4.4 Not working button for centering

### ISSUE THREAD

**Issue by hristo-mavrodiev** [opengisch/QField#895]
After long click on GPS icon the advanced menu is shown. On this menu the button for centering on current location is not working.

### Reproduction Steps:

1. Turn on the GPS location
2. Zoom to area different from the current location
3. Long click on GPS icon
4. Click "Center to Current location" 

### Expected behavior:
Zoom to current location

### Observed behavior:

No change in zoom

### Screenshots and GIFs

![image](https://user-images.githubusercontent.com/61916767/77235131-fc0d2e00-6bbb-11ea-883d-72b27424cd62.png)

**QField version:** QField version: 1.4.4 (010404991)]
Android 6.0.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Not tested
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
Thanks. I can reproduce this.

**Comment by signedav** [comment]
@m-kuhn I'm not sure if I understand this part of the concept. Should "Center to Current Location" do the same like on quick tip on the GPS button?

Means this part of the code: 
https://github.com/opengisch/QField/blob/master/src/qml/qgismobileapp.qml#L925-L929
Should do the same like this part: 
https://github.com/opengisch/QField/blob/master/src/qml/qgismobileapp.qml#L587
And if so, why it does not do it the same way?

**Comment by m-kuhn** [comment]
> Should "Center to Current Location" do the same like on quick tip on the GPS button?

I think so yes

>  And if so, why it does not do it the same way?

Probably unintentionally.
