### ISSUE TITLE
"Fixed scale navigation" setting is not working. Zooming based on feature class.

### ISSUE THREAD

**Issue by hristo-mavrodiev** [opengisch/QField#904]
The setting for "Fixed scale setting" is not affecting the zoom function.
Also there is a difference if the user tries to zoom on point feature or polygon feature.
If the user choose a point and click on the "zoom center" button the zoom scale is not affected with both modes on "Fixed scale navigation".
On polygon feature there is always change in the zoom, with both options on "Fixed scale navigation".

### Reproduction Steps:
Test 1:
1. Choose a point feature
2. Select "zoom center" icon
3.Change the "Fixed scale navigation" and repeat step 1 and 2.
-----------------------------------
Test 2:
1.Choose polygon feature  and repeat 2 and 3 from Test1

### Expected behavior:

Change in the zoom based on Fixed scale navigation" 
### Observed behavior:

Change in the zoom based on feature class - point/polygon

### Screenshots and GIFs

Tested on Demo datasets
**QField version:** 
QField 1.4.4 (010404991)] and 1.5.0(010500991)
Android 6.0.1

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
This setting only affects the search - not the `followCurrentButton` on the selected feature.

Means on the ***search*** depending on this "fixed" setting:
- Not set "fixed" (for poly and point): zoom
- Set "fixed" (for poly and point): no zoom

Means on `followCurrentButton` depending on the geometry type:
- On Polygon (for "fixed" and not "fixed"): zoom
- On Point (for "fixed" and not "fixed"): no zoom

I agree that the behavior is confusing.

@3nids Is this the behavior that we should have? Should we make here an improvement?

### Possibilities:
- Use the "fixed" setting for the `followCurrentButton` as well.
- Don't use the "fixed" settings for `followCurrentButton` but zoom on point as well.

**Comment by signedav** [comment]
I think we leave this input open.

@3nids Maybe you have an opinion about it :-)

**Comment by 3nids** [comment]
I think that the action from the button should also respect the setting.

Regarding points, there is a method in QgsMapCanvas which determines a scale depending on the density of the points. This approach could be used when the lock is disabled.
