### ISSUE TITLE
Hidden field is visible

### ISSUE THREAD

**Issue by rbovard** [opengisch/QField#91]
Hidden field is visible

### Reproduction Steps:

1. Set a field as `hidden` is QGIS

### Expected behavior:

The field should be hidden in QField

### Observed behavior:

The field should is visible in QField

**QField version:** 0.8

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No idea (first use)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
As a workaround, you can use the drag and drop designer to only use the fields which you actually want (and even put them onto tabs).
