### ISSUE TITLE
Default values calculated from other fields with live update

### ISSUE THREAD

**Issue by she-weeds** [opengisch/QField#914]
This is more of a feature suggestion than a bug...

In QGIS 3.10+, if you set a field (say `thisfield`) to apply a default value on update and the default value expression refers to another field (say `"thatfield"*0.12`), any changes to `thatfield` will automatically re-calculate the values in `thisfield` on the fly, in the attribute table or form, without needing to save any edits.

Any chance of getting this to work in QField? I have some lookup expressions and calculations as default expressions for some fields, but when first inserting a feature the fields are empty (presumably they cannot read the values entered in the fields they depend on). I have to edit the feature (attributes or geometry) before it applies the default (=calculated) value. 

Part of my symbology depends on these calculated values so it would be great to support the implementation of this now that QGIS natively supports it...

**Comment by signedav** [comment]
Hi @she-weeds and thanks for the input. Yes, this is implemented in QGIS but not yet in QField.
It would be nice to have that.
