### ISSUE TITLE
Encoding issue for special chars in labels

### ISSUE THREAD

**Issue by rbovard** [opengisch/QField#92]
Encoding issue for special chars in labels

### Reproduction Steps:

1. Label a layer with special chars like `éà` in QGIS

### Expected behavior:

Special chars should be correct (like in QGIS)

### Observed behavior:

Special chars are incorrect

### Screenshots and GIFs

![image](https://cloud.githubusercontent.com/assets/4549666/21347508/35845052-c6a9-11e6-888d-cd1e6db16e5c.png)

**QField version:** 0.8

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: No idea (first use)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Is this based on an attribute from a file? Which file format? Shapefile?

**Comment by rbovard** [comment]
Yes, a shapefile.

In QGIS (label and attributes table), the values are fine.

**Comment by m-kuhn** [comment]
Check the layer properties -> general -> encoding setting.

If this is set to System, the encoding used is taken from the computer and not the file.

Android uses UTF-8 by default (which fully supports many character sets). The best you can do is:

1. do not use shapefiles ;) or
2. define the encoding (try latin1)

What we could do is to warn the user in the QFieldSync tool but that's not really a satisfying solution

**Comment by m-kuhn** [comment]
See also
https://lists.osgeo.org/pipermail/qgis-developer/2016-December/046271.html

**Comment by rbovard** [comment]
Thanks for the explanations @m-kuhn 

1. I tried to use PostGIS layer but QFieldSync did not export them... I haven't time to investigate more so I used Shape File :/
2. It worked fine with latin1
