### ISSUE TITLE
Menu panel improvements suggestions

### ISSUE THREAD

**Issue by rbovard** [opengisch/QField#93]
Some improvements suggestions for the menu panel:

1. The panel should be closed with return button like right panel (many times I accidendtaly closed QField)
2. The header seems inactive because of its color, it should be the same as the right panel

**QField Version:** 0.8
**OS and Version:** Android 6.0

**Comment by giedrioks26** [comment]
> 1. The panel should be closed with return button like right panel (many times I accidendtaly closed QField)

I guess there must be only one way to turn off the field, it _Menu button ‣ Quit_
This would be the simplest.

**Comment by signedav** [comment]
After the new logic with closing QField and the solution with the focus stack here #266, I guess this can be closed. Right?

**Comment by giedrioks26** [comment]
Yes you are right. This solves the problem.
