### ISSUE TITLE
QGis Extension QField : changing type numeric

### ISSUE THREAD

**Issue by gsollberger** [opengisch/QField#953]
Hi,
A QGis project is connected to 2 postgres/postgis layers : eu_grille_pg09 and eu_chambre_pg10.
This layers contain char attributes and numeric attributes, for exmple 'alt_couv' defined with double precision in postgres.
Extension QField Sync "transform" this QGis project in QField project with gpkg data ... *et là c'est le drame" ... the numeric attributes are not decimal :
![Annotation 2020-04-15 133805](https://user-images.githubusercontent.com/4537306/79334718-1c14e080-7f21-11ea-9206-962e9378e3e6.png)

Impossible to enter an altitude without decimal numbers.

Any one for a solution ?

Thank's a lot and best regards.

Gérard Sollberger
HKD Géomatique Vaud SA

My environnement :

QGis 3.12.1
QField Sync extension : 3.1.6
postgres 9 et 10
QField on dive Mobile : 1.4.4
Device mobile : Samsung Galaxy Tab Active 2
[tmp-qfield.zip](https://github.com/opengisch/QField/files/4481024/tmp-qfield.zip)

**Comment by m-kuhn** [comment]
@gsollberger is this still an issue with the latest release?

**Comment by gsollberger** [comment]
Hi,
It's ok, it works with french language settings.
Thanks ... and happy new year ;-)
Gérard
