### ISSUE TITLE
QField (dev commit 9878f23) doesn't see graphs, but stable does in the same project

### ISSUE THREAD

**Issue by Kasami-s** [opengisch/QField#956]
Hello!

I have a project that has one of the fields set up this way:
![Screenshot from 2020-04-17 01-48-42](https://user-images.githubusercontent.com/22294173/79513975-cab63f80-804d-11ea-98b0-f2a04a15eb44.png)

It does work perfectly fine on stable QField (or QGIS)
![stable](https://user-images.githubusercontent.com/22294173/79514003-dace1f00-804d-11ea-8717-48c14b4c9685.jpg)

But fails to render on the dev 9878f23 (one from Google Play)
![dev](https://user-images.githubusercontent.com/22294173/79514023-e4f01d80-804d-11ea-9674-6b29230fdd00.jpg)

Problem can be reliably reproduced, doesn't happen randomly: Yes
Problem happens with all files and projects, not only some files or projects: Yes

**Comment by m-kuhn** [comment]
Thanks for the report. For reference, can you add the version of "current stable QField"?

Also, can you configure the field as a simple text edit to have a reference of a file path? I assume it's an absolute path looking at the expression of the virtual field.

@signedav any idea why an absolute expression like this would no longer work?

**Comment by Kasami-s** [comment]
Thank you for your response!

Sure. Stable QField I'm using is 1.4.4 - Olavtoppen

At the moment it's set as a relative path, settings look like this

![Screenshot from 2020-04-22 15-07-40](https://user-images.githubusercontent.com/22294173/79979986-154f1600-84ab-11ea-9d2f-72076d837729.png)

Essentially all points have an ID to them and inside the project directory there's "graph" directory with images and names corresponding to those IDs

If you'd like, I could generate a small project with some random stuff and send it over to you. Would that be useful?

**Comment by signedav** [comment]
I cannot reproduce it with the current release 1.5.3.

I can use `@project_basename` as a part of the picture path.

Can you test with the current release @Kasami-s ? And if it still does not work, provide us your project to test?

**Comment by signedav** [comment]
![Screenshot_20200526-112941_QField](https://user-images.githubusercontent.com/28384354/82884795-88cdc280-9f44-11ea-8d07-2b9a27876866.jpg)
