### ISSUE TITLE
Unable to load project in QField synced with Nextcloud

### ISSUE THREAD

**Issue by geomoes** [opengisch/QField#959]
We would like to use our Nextcloud server to sync between QGis-desktop and QField on Android.
On both devices, the project-file (*.qgs) and the used layer-files are in one directory and the path to the layer-files is relative. All the files are properly synced to the tablet.
When we try to open the project, the project seems to be loaded, but the screen is blank, and there are no layers in the layer list. No error message is displayed.

A similar set up using Google drive is working as expected in both directions. The only difference is, that we can choose the directory where Google is syncing to.
In Nextcloud we are limited to the following storage options:
- /storage/emulated/0/Android/media/com.nectcloud.client   
- /storage/6364-6630/Android/media/com.nectcloud.client 
- /data/user/0/com.nectcloud.client/files 
- /storage/6364-6630/Android/data/com.nectcloud.client/files 

We tried all options, but with no success. We tried both, to sync the whole project from QGis as well as the sync-folder created with QField Sync Plugin.
When we copy all the files manually to our device so that the files resides in a directory /storage/6364-6630/qfield/ everything works like expected.
After all we must conclude, that it seems not to be a problem with QField, but more a problem related to Nextcloud, since they actually do not offer the ability to sync files to another location other that the options mentioned above. 
And QField obviously doesn't like the paths offered by Nextcloud. 
We would really like using Nextcloud to sync our files. We think that QField and Nextcloud would be a great team to work together. So we are going to contact them, to see if they are willing to offer a more flexible way to define a sync folder.

**Comment by m-kuhn** [comment]
FYI, I have successfully loaded projects from nextcloud snyced folders (I regularly use this for testing)

    /storage/emulated/0/Android/media/com.nextcloud.client

**Comment by geomoes** [comment]
Strange,
I can choose the /storage/emulated/0/Android/media/com.nextcloud.client
inside the Nextcloud-client (3.11.0). All the files are synced to this folder and downloaded to the device.
When I try to open it in QField (Open local project > external memory (read only) and then browse to the project file /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/user@domain%2Fnextcloud/qfield/project.qgs I can load the file, but the screen stays blank (no error message) and the layer list is also blank. The same folder manually copied to another place e.g. storage/6364-6630/qfield/ everything works like expected. 
???

**Comment by m-kuhn** [comment]
I open them through "Internal storage"

**Comment by geomoes** [comment]
this is what I tried first, since the 'External storage' says 'read only' - which does not make sense when one want to be able to collect data.
So choosing 'Internal stoage' leads me directly to /storage/6364-6630 and NOT to /storage/emulated/0 since this is the path of the 'External storage'.
I've tried almost every combination, but QField loads the project file, all the layers are in place, but I end up with a blank screen and no layers?

[QField_Nextcloud__.pdf](https://github.com/opengisch/QField/files/4505496/QField_Nextcloud__.pdf)

**Comment by m-kuhn** [comment]
More information about external storage in the docs:

https://qfield.org/docs/project-management/project-selection.html?highlight=external#external-sd-card

**Comment by bsturm** [comment]
We are working with the same setup and it is working very well, same storage-path and everything.

Were you able to solve your problems?

**Comment by strathmannm** [comment]
Hello,
did you try it with saving your qgis project (Project/Save) after setting the layer to "offline editing" (Plugins/QFieldSync/Configure Current Project/)  but before exporting the project to qfield (Plugins/QFieldSync/Package for QField/)
This step seemed to solve the problem for us.
Kind regards

**Comment by Franc-Brs** [comment]
Hi all anche thank for the infos. I'm also stopped on a similar issue.
I can see the nextcloud 
When I try to load my qgs project from Qfield I've got the following log in the app:

```
Project file "/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/dorota@www.gishosting.gter.it/nextcloud/progBrsQfield/provaBrs.qgs" does not exist
Project file "/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/dorota@www.gishosting.gter.it/nextcloud/progBrsQfield/provaBrs.qgs" does not exist
```

**Comment by Franc-Brs** [comment]
> Hello everyone and thanks for the infos. I'm also facing a similar issue. I can see the nextcloud folder but when I try to load my qgs project from Qfield I've got the following log in the app:
> 
> ```
> Project file "/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/dorota@www.gishosting.gter.it/nextcloud/progBrsQfield/provaBrs.qgs" does not exist
> Project file "/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/dorota@www.gishosting.gter.it/nextcloud/progBrsQfield/provaBrs.qgs" does not exist
> ```

Ok, I saw the problem. The path of the file is
```
Android/media/com.nextcloud.client/nextcloud/dorota@www.gishosting.gter.it%2nextcloud/progBrsQfield/provaBrs.qgs
```
where Qfield parse the following uri
```
/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/dorota@www.gishosting.gter.it/nextcloud/progBrsQfield/provaBrs.qgs
```
So the %2 is giving some problem in the parsing (and maybe the nextcloud device app insert the %2 by error). If I change the name of the folder in the device I'm able to open it with Qfield, of course by changing the name I loose the syncro in nextcloud.
I dont have time right now to dive into the code and maybe the imminet releases (beta) will solve this problem in some other ways https://github.com/opengisch/QField/pull/2429/commits/921edc5a00dcbc7f5767b247129ee3bb0e2eb1c1

**Comment by nirvn** [comment]
Latest Android storage policies make this issue irrelevant (unfortunately). That said, QField can now import nextcloud directly from within its interface, which is quite neat.

Closing.
