### ISSUE TITLE
Scalebar is smaller than it should with mercator based CRS

### ISSUE THREAD

**Issue by legrostdg** [opengisch/QField#962]
The scalebar reports 100m when it should be 75m or so.

### Reproduction Steps:

- Open a project
- Set the zoom level to get the scalebar be around 1.5cm for 100m
- Open the Measure Tool
- Mesure the scalebar (with visual landmarks on the screen)

### Expected behavior:

The measure of the scalebar should give 100m (in fact the scalebar should be bigger than 1.5cm).

### Observed behavior:

I get around 75m for the scalebar

**QField version:** 1.5.1 (010501991) (The problem was also there on 1.4.x).

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: no
* Problem can be reliably reproduced, doesn't happen randomly: yes
* Problem happens with all files and projects, not only some files or projects: I just have one project

**Comment by m-kuhn** [comment]
What CRS are you using?

**Comment by legrostdg** [comment]
epsg:3857

I just tried to change the project epsg:2154, and it seems to fix the problem...

**Comment by legrostdg** [comment]
So... I guess that's a problem with projection on my part. Sorry for the noise!
