### ISSUE TITLE
*.gsb file custom crs integration

### ISSUE THREAD

**Issue by bogboco** [opengisch/QField#965]
On QGIS, i'm using a custom crs, with ntv2, *.gsb file. GPS coordinates in Qfield are lat lon and not custom ones from desktop.

### Reproduction Steps:

1. Create project with custom crs in QGIS and export it with QSYNC.
2. Open project in Qfield, all looks good except position of GPS, that one being in lat long format ( much smaller values that the ones from custom CRS.

### Expected behavior:

See gps coordinates in project crs. Probably *gsb file need to be copied in qfield, somewhere.

**QField version:** [1.50]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by signedav** [comment]
Thanks for reporting. This is not yet integrated AFAIK. Do you know more @m-kuhn ?

I'll label this as enhancement.

**Comment by m-kuhn** [comment]
We have recently done an estimation of this (bundled with other high precision measurement related improvements) and looking into financing possibilities with interested parties. If you have the potential to participate in this, please contact info@opengis.ch, it would be great to be able to improve high precision measurements with this !

**Comment by nirvn** [comment]
@bogboco , PR #1385 implements a mechanism for QField to handle projection grid files. You can test it already via APKs offered in the PR. You would copy your grid files in your mobile device's external storage /QField/proj directory (which you can create if not present yet).

**Comment by nirvn** [comment]
This has been fixed for a while.
