### ISSUE TITLE
Remove project(s) from welcome list

### ISSUE THREAD

**Issue by geomondego** [opengisch/QField#966]
Hello everyone, this is just a suggestion as user.
Would it be possible to have a way to remove some projects from the list on the welcome page like in QGIS Desktop?

Sometimes I tend to create test projects with different names and then they stay on the page without any interest.

If we are talking about something that is simple, fine. If it is not, I have to change the way I act :smile: 

Thanks :+1:

**Comment by m-kuhn** [comment]
A long press -> Project Actions Menu -> Remove would be super nice
@nirvn better ideas?

**Comment by nirvn** [comment]
@m-kuhn , yep, that's what I had in mind. We already have a long press menu in the QField Cloud panel, so that'll harmonize things quite nicely.

**Comment by m-kuhn** [comment]
Implemented for 1.6, thanks @nirvn
