### ISSUE TITLE
Value Relation widget with "Allow multiple selections" not working

### ISSUE THREAD

**Issue by devfaz74** [opengisch/QField#968]
Value Relation widget  with "Allow multiple selections" working on QGIS but not on QField. The multiple selections are shown, but can't check/uncheck any of the selections, i.e the widget appears as read only.

### Screenshots and GIFs
QGIS screenshots:
https://ibb.co/8cGc4zz
https://ibb.co/ssLMJrK

QField not working screenshot:
https://ibb.co/hBj9qvq

I am using QField version 1.4.4

**Comment by signedav** [comment]
Hi and thanks for reporting

I cannot reproduce any problem. Can you provide us a project to test it?
