### ISSUE TITLE
Recent project name containing dot

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#969]
Projects which name contains a dot show only the part of the name before the dot.
Ex: "project_v3.6.0.qgs" is shown in QField like "project_v3"

### Reproduction Steps:

1. Open a project named with a dot
2. Quit QField
3. Open QField and the list of recent projects at start shows first our recent project not-well-named

### Expected behavior:

Show the full name of recent projects (with or without extension file type ?)

### Observed behavior:

Names of recent projects are incomplete if there is a dot in the name

**QField version:** 1.5.0 (010500991)]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No, since new recent projects screen exists]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [name-doted projects only]

**Comment by nirvn** [comment]
I'll have a look at it.
