### ISSUE TITLE
Identification button

### ISSUE THREAD

**Issue by giedrioks26** [opengisch/QField#97]
Needed identification button or menu, exaple:"_Menu button ‣ mode ‣ Identification_"

Now every time you touch the screen, switches on the identification window, and the object is marked.

Examples pics:
https://s27.postimg.org/8rayx24o3/identi2.png
https://s27.postimg.org/pt3sz5jj7/identi.png

**Comment by m-kuhn** [comment]
There's a new option "show identify view in full screen", does toggling this solve your issues?

**Comment by giedrioks26** [comment]
I think this does not solve the problem. I had in mind that when browsing the map is unlikely to affect object identifier. It should only act when to turn it on.

**Comment by m-kuhn** [comment]
Maybe it is just too sensitive?
Thinking about other apps (like google maps) there is also no identify button and I think they are doing fine.

We are super careful to add new buttons to not clutter the interface.

**Comment by gnerred** [comment]
+1 for not adding a new button for identifier. The UI has to be as simpler as possible. Most webmapping applications of today do not have a button for identifier, just a click or touch does it.

**Comment by giedrioks26** [comment]
Yes, I agree. I THINK touching the sensitive. I remember the first qfield version of a long touch. Why do not they now?

**Comment by nirvn** [comment]
@giedrioks26 , how are things these days? There have been countless refinements on the way we handle touch (from closing the list when no features are identified under a touch to avoiding identification when double tapping to zoom etc). 

There's also the possibility to set layers as non-identifiable per project, that should help _a lot_.

**Comment by giedrioks26** [comment]
> @giedrioks26 , how are things these days? There have been countless refinements on the way we handle touch (from closing the list when no features are identified under a touch to avoiding identification when double tapping to zoom etc).
> 
> There's also the possibility to set layers as non-identifiable per project, that should help _a lot_.

This is no longer necessary

**Comment by nirvn** [comment]
@giedrioks26 , still using QField these days?

**Comment by giedrioks26** [comment]
> @giedrioks26 , still using QField these days?

Really so! A lot! QField supports incomparably more complex projects. It’s an integral part of my job today. I am responsible for a group of at least 40 people who use QField. Sorry, I don't always manage to write here. I don’t always manage to watch changes. But this functionality is no longer a problem for us.
