### ISSUE TITLE
QField does not open project if a print layout is configured

### ISSUE THREAD

**Issue by nischmi1** [opengisch/QField#970]
After adding and configuring a Layout in QGIS, the project could not be opened in QField any more.

### Reproduction Steps:

1. Configure a Project in QGIS (4.10.4 LTR)
2. Export it with QField Sync and run it successfully on QField (1.4.4) on a Huawei P20
3. Work further on the project in QGIS: Add a print Layout with an HTML Table and a map to create a report on some of the features.
4. Export again with QField Sync and transfer to mobile device.
5. QField is stalled when the project is opened.
6. When the print layout is again deleted, the project can be run on Qfield again.

### Expected behavior:
QField should not care about any print layouts and should not be affected by them.

### Observed behavior:
Mostly, the app is stalled. Some reactions are possible after long waiting times, e.g. I managed to see the log entries and saw a hint about the print layout (e.g. external source for html table not found). 

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** 1.4.4 010404992

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: ?
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by signedav** [comment]
Thanks for reporting. The issue only occurs on using HTML Elements in the print layout. It needs more investigations.

**Comment by samueldurante** [comment]
Hi,
I am facing the same issue. I do have a print layout configured with an html element in it.
How can I help to report more information ?
Is it possible to get a crash log from QField ?

Thanks for helping (not a serious bug, but I have to duplicate projects, one for Qfield, one for print layouts)

**Comment by nirvn** [comment]
@samueldurante , @nischmi1 , a fix is on its way, you should expect QField 1.9 to not freeze/crash anymore when a layout HTML item is present in a project file being loaded.
