### ISSUE TITLE
qgis stops opening the project in latest version 1.5.2

### ISSUE THREAD

**Issue by frgis** [opengisch/QField#972]
Hi,

yesterday I downloaded version 1.5.2 of Qfield.
I'm using two Qfield projects (no layout configured).
For one of the two projects, the application is stopped from from a specific zoom.
For the other, the application stops when it opens (the application begins to load the map and stops, see the attachment).

In my projects there are only datasets in gpkg format (vector and raster).
Update forms are created in both projects.

### Reproduction Steps:

1. Open Qfield application
2. Open project
3. For the first project it opens and when I zoom in on a specific level the application stops. For the other, the application stops when the project is opened.

### Screenshots and GIFs
![Screenshot_20200428-004816](https://user-images.githubusercontent.com/56657014/80455462-1610fd80-892c-11ea-9b68-1f50684435dc.png)

**QField version:** "1.5.2-Piz Palü" (code:010502991)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: Yes
* Problem can be reliably reproduced, doesn't happen randomly: I don't know (my smartphone is Android version 7.1.1)
* Problem happens with all files and projects, not only some files or projects: Yes

Thanks

**Comment by m-kuhn** [comment]
Can you "envoyer des commentaires" and add a link to this issue?

**Comment by frgis** [comment]
for the attached project, it opens but when I zoom in strongly qfield stops.

For additional information my smartphone works with an armv7 processor.
This project works correctly in the previous version.
The current version was downloaded from the Play store.
[qfield_972.zip](https://github.com/opengisch/QField/files/4585224/qfield_972.zip)

**Comment by frgis** [comment]
after additional tests, doublon with Issue 988
