### ISSUE TITLE
VRT file with geometries on OGR doesn't load in QField

### ISSUE THREAD

**Issue by alafr** [opengisch/QField#975]
VRT files (ogr provider) don't load in QField.

### Reproduction Steps:

1. Unzip and copy the attached folder in an Android Device
2. Launch QField
3. The message "The following layers could not be loaded, please review those and reconfigure the QGIS project" appears

### Expected behavior:

The layers should appear as in Qgis Desktop, since they have relative paths and are in the same folder with the Qgs project

### Observed behavior:

The message "The following layers could not be loaded, please review those and reconfigure the QGIS project" appears, and the layers don't load

### Screenshots and GIFs

[VRT QFIELD.zip](https://github.com/opengisch/QField/files/4546802/VRT.QFIELD.zip)

**QField version:** 1.5.2 - Piz Palü (010502992)

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [No, only .VRT files]

**Comment by signedav** [comment]
Info: A VRT for a raster referencing tiffs in a folder works fine.

**Comment by signedav** [comment]
![Screenshot_20200526-095953_QField](https://user-images.githubusercontent.com/28384354/82876941-d2fd7680-9f39-11ea-83b8-fa50d508e54e.jpg)
![Screenshot_20200526-095929_QField](https://user-images.githubusercontent.com/28384354/82876945-d3960d00-9f39-11ea-8108-a8ae28b5e0a3.jpg)

**Comment by nirvn** [comment]
@alafr , you'll be happy to know this is working just fine in the latest QField 2.0 beta. Closing.
