### ISSUE TITLE
QField doesn't save captured photos

### ISSUE THREAD

**Issue by 1900g** [opengisch/QField#985]
QField correctly saves the image path but does not record the photo in any DCIM folder.

**Comment by m-kuhn** [comment]
Does it show up the pictures in the form?

**Comment by 1900g** [comment]
no any pictures

**Comment by m-kuhn** [comment]
I cannot follow your answer, I am sorry. Can you please write exactly which step works, where you see and don't see the photos. Is this possibly a duplicate of https://github.com/opengisch/QField/issues/400?

**Comment by 1900g** [comment]
I take the photograph and the path is correctly recorded in the database, but the photograph is not saved in any DCIM folder. it is not reproduced in the qfield form at the end of the shot

**Comment by m-kuhn** [comment]
Which version of QField are you using?
Did it work properly with older versions?

**Comment by 1900g** [comment]
the latest with android 8

**Comment by m-kuhn** [comment]
Can you attach your project file here?

**Comment by 1900g** [comment]
problem solved! In qgis the project home of the general settings must not be set: it must be left empty

**Comment by m-kuhn** [comment]
Thank you, I have opened a followup issue here: https://github.com/opengisch/qfieldsync/issues/146
