### ISSUE TITLE
QFIELD don't open multiple raster on the same gpkg file

### ISSUE THREAD

**Issue by pobsteta** [opengisch/QField#986]
QFIELD don't open multiple raster on the same gpkg file

### Reproduction Steps:

1. GPKG with muliple raster
2. copy on smartphone after the export
3. open the project on smartphone and we have the message that all raster are not openend ??
4. or all vector files are opened

![S00505-18224385](https://user-images.githubusercontent.com/932599/81090268-c28b4a80-8efd-11ea-9304-5c68d242041a.jpg)

**Comment by pobsteta** [comment]
If i open the qgs file and change the path : GPKG:../../test1.gpkg: ... to GPKG:./test1.gpkg: ... all is right and application can run !

**Comment by m-kuhn** [comment]
> If i open the qgs file and change the path : GPKG:../../test1.gpkg: ... to GPKG:./test1.gpkg: ... all is right and application can run !

Thanks for the feedback. Is this really a QField issue. Or rather a configuration in QGIS issue?
