### ISSUE TITLE
translations QField 1.6

### ISSUE THREAD

**Issue by VxTedxV** [opengisch/QField#987]
Some strings are not translatable in Transifex :
- [x] value "not available" in global variables
- [x] "show on map canvas"
- [x] "center to current location"
- [x] "features" (attribute form title)

**Comment by m-kuhn** [comment]
> value "not available" in global variables

This one is from QGIS, we'll need to either load qgis translations or to treat it differently

> "show on map canvas"

True, there was an issue open about that one, truly weird (it's tagged as translatable in the source and I think I even verified it's sent to transifex but does not pop up)

> "center to current location"

Shows up for me in the web frontend / transifex

> "features" (attribute form title)

Pull request pending https://github.com/opengisch/QField/pull/989

**Comment by nirvn** [comment]
"Not available" fixed as part of PR #971.

**Comment by VxTedxV** [comment]
"center to current location" -> my bad, I just checked. I made a mistake. It's better like that ;)

**Comment by m-kuhn** [comment]
The last bit has been fixed in https://github.com/opengisch/QField/pull/1071, "Show on map canvas" shows up on transifex.

If there are more missing translation strings, please open a new issue. Thank you.
