### ISSUE TITLE
Qfield crashes after opening a project that contain layer postgres

### ISSUE THREAD

**Issue by giocoro** [opengisch/QField#990]
I have always used Qfield with projects that contain postgres/postgis layers. Using 1.3.2, and earlier versions, Qfield worked fine on all my smarthpone and tablet. Versions since then crash QField when a project that contain postgres layer  is loaded.

**Reproduction Steps:**

1. Start Qfield
2. Load a project with one or more postgres/postgis layer
3. Qfield Crashes

**Observed behavior:**

No input can be done to prevent a crash at startup.

QGis 3.12.0
Postgres 10
QField on dive Mobile : 1.5.3
Device mobile : Samsung Galaxy J2, Samsung Tablet Tab A 8.0 LTE

 **Additional information:**

Problem started happening recently, didn't happen in an older version of QField: No, version since 1.3.3 had the same problem;
Problem can be reliably reproduced, doesn't happen randomly: Yes;
Problem happens with all files and projects, not only some files or projects: No, only with project that contain postgres layer.

**Comment by m-kuhn** [comment]
This sounds like a severe bug.
Can you verify if the demo project "live survey" that is shipped with the app works?

**Comment by giocoro** [comment]
The "live survey" demo project works properly. I created a new project with the same postgres layers for further testing and it works properly. The problem was my old project, not a bug.
Thanks a lot.
