### ISSUE TITLE
Print to PDF maps not georeferenced

### ISSUE THREAD

**Issue by rockyuc** [opengisch/QField#994]
[Short description of problem here]
Hello, when I try to make a map in QField using the 'Print to PDF' feature, the resulting map is not georeferenced.

### Reproduction Steps:
sorry not to sure what this means i'm just a firefighter. when i set up my map to how i want it to look, then hit 'Print to PDF' using a print layout i've made in QGIS, the resulting map is not georeferenced. 
1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Expected behavior:
print to pdf maps to be georeferenced so we can use the maps in Avenza (our agency uses Avenza but I want to make our maps in QGIS/QField)

[Describe expected behavior here]

### Observed behavior:
Print to pdf maps look great but they are not referenced so we can't use them in Avenza

[Describe observed behavior here]

### Screenshots and GIFs

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

[Please also attach additional files if a specific project/dataset is useful to investigate the problem.]

**QField version:** [Enter QField version here including build number found in the about screen after the release name example 1.2.0 (10200993)]
1.5.3

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
No (I haven't tried previous versions)
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
Yes
* Problem happens with all files and projects, not only some files or projects: [Yes/No]
Yes (from the one's i've tried anyway)

**Comment by m-kuhn** [comment]
Printing to georeferenced maps sounds like a very cool suggestion.

**Comment by m-kuhn** [comment]
I think this has the potential to make it to an upcoming crowdfunding

**Comment by nirvn** [comment]
@rockyuc , this is your lucky month :wink: this enhancement will be available in forthcoming QField 1.9.
